### ISSUE TITLE
Build Issue at Linking Stage on mac os 10.8 (but maybe upstream)

### ISSUE THREAD

**Issue by ariypriy** [BVLC/caffe#1007]
I'm somewhat of a newbie to this, so I apologise in advance if I'm doing something really silly. I'm running this on mac os 10.8. I have installed cuda, opencv and the other dependencies without any errors.

I followed the installation instructions, edited my Makefile.config and then ran 'make all'. This seems to run fine invoking the compiler to build the tools source files, and producing .o object files without any errors. However, after it completes this, it tries to create a symbolic link  and then I get the error:

ln: .build_release/tools/caffe: No such file or directory
make: **\* [.build_release/tools/caffe] Error 1

It seems as though there should be an executable file in that directory which it's trying to link - but it's not there, so does that mean there was an issue further upstream? I looked through the console log and cannot see any errors apart from a warning:

ld: warning: directory not found for option '-L/usr/local/cuda/lib64'

Is this relevant?

Any clue as to what I'm doing wrong here?

**Comment by sseltser** [comment]
upstream problem not downstream. this is an issue with Makefile...

**Comment by sseltser** [comment]
i have made a list of files to be listed in .build_release/tools
more exec_list.txt
caffe
compute_image_mean
convert_imageset
device_query
dump_network
extract_features
finetune_net
net_speed_benchmark
test_net
train_net
upgrade_net_proto_binary
upgrade_net_proto_text

this command links them to their bin counterparts
for req in $(cat all_execs.txt); do ln -s $req.bin $req; done

**Comment by sunshineatnoon** [comment]
@sseltser This solves my problem too, thanks. I met this problem in [py-fast-rcnn](https://github.com/rbgirshick/py-faster-rcnn) instead of caffe itself. It is strange we have to link these files manually since I didn't have this problem when compiling caffe.

**Comment by anghostcici** [comment]
I also met this problem, except link these files manually, is there other method to solve that?
