### ISSUE TITLE
Workaround to use image as label

### ISSUE THREAD

**Issue by bai-capital** [BVLC/caffe#1013]
There has been an issue #523 on multi-label problem. In my case, I'm trying to implement an image-deblur network. For deblurring, I have to give image as label, so it's more than multi-labeling.

My workaround is feeding an extra data layer as label, and calculate the euclidean loss of the label and prediction. All true "labels" are set to 0, which is expected to be the euclidean loss of prediction and the extra label layer. This workaround is proved to be working on some image auto-encoder problem. However, in more tricky tasks, the training process will stop improving the net at some high loss. 

My question is, do you think this workaround should work? Will the workaround hurt the training process?

![srcnn prototxt](https://cloud.githubusercontent.com/assets/1207595/4100882/b6e90696-30bb-11e4-8091-5351b7bcd028.jpg)

**Comment by RyanCV** [comment]
@SolessChong Hi, how do you generate the lmdb for both data and label using caffe??
