### ISSUE TITLE
Dense per pixel label output

### ISSUE THREAD

**Issue by ankurhanda** [BVLC/caffe#1019]
Hi everyone, 

I have finally unit tested the changes I made to caffe-public to enable per pixel label for the whole image. I realised (so far at least) that only inner product and softmax layers needed the densified versions of forward and backward passes. These changes now pass the unit tests that come with the repository. I think it might be very useful for both me and others if they wish to use this code at some point, to have this feature tested thoroughly by the community or those who would like to, to spot remaining bugs if any. I will hopefully be releasing these codes at some point with our research work anyway later this year end or next year. 

Also, looking at the growing research of dense semantic labels using conv-nets for image segmentation or indoor scene understanding, I presume someone else might have done this conversion as well. I wonder what's the best way to collate the contributions? Also, has anyone used depth image input (e.g. NYU dataset) to the conv-net to do indoor scene understanding? 

Look forward to hearing from you.

Thank you.

**Comment by jingweiz** [comment]
Hi @ankurhanda 
Is it possible for you so share the Upsample Layer you wrote? Thanks in advance!

**Comment by shelhamer** [comment]
#1615 adds a deconvolution / backward convolution layer that can do upsampling.

**Comment by LIACS-medialab** [comment]
Hi @ankurhanda
How did you convert the ground truth images? with levelDB?
in fact, I donot know how to save these GT images and compare them with th efinal conv outputs?
thanks

**Comment by igorb871** [comment]
Hi @ankurhanda ,

Is your layer available yet? I'm doing a class project on classifying object in maps and I think it could be really valuable.

Thank!

**Comment by je310** [comment]
Hello @ankurhanda, did you manage to find out how to arrange the ground truths to be tested against a fully convolutional output?

**Comment by shelhamer** [comment]
Closing as this is handled by fully convolutional networks and their implementation in Caffe through reshaping, coordinate mapping, and cropping. See fcn.berkeleyvision.org for the reference implementation.
