### ISSUE TITLE
Imagenet problem "Incorrect data field size"

### ISSUE THREAD

**Issue by armcortex** [BVLC/caffe#1021]
Hello,
I am new in Caffe. When I run create_imagenet.sh  there is a error information

Check failed: data.size() == data_size (562500 vs. 540000) Incorrect data field size 562500

Both wront in creating train leveldb and val leveldb
everytime I run create_imagenet.sh, first I will remove directories ilsvrc12_train_leveldb and ilsvrc12_val_leveldb

and I use chmod 777  change  train and val image database.
But still get this wrong information, is there any method I can try?

Thank you

**Comment by Shravani-Chintalapudi** [comment]
Hello, I am facing same issue in the process of training Imagenet. @mxzhao Could you please elaborate your solution. I could not find those lines in create_imagenet.sh file. Thanks :)

**Comment by halaneji** [comment]
thank you very much
