### ISSUE TITLE
Checking core Caffe and Pycaffe results

### ISSUE THREAD

**Issue by denny1108** [BVLC/caffe#1032]
As Caffe can output testing accuracy during training, I print out the prediction accuracy on test data with the learned model, when training is done. I check the code, the accuracy is based on top_1 prediction. My questions is when I use the python wrapper to evaluate the test data, it outputs different values with the scores I saw during training. I don't know why it happens. Any one has the same observation?

**Comment by longjon** [comment]
Please ask usage questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) list. Thanks!
