### ISSUE TITLE
The mean image of the ILSVRC dataset is corrupted?

### ISSUE THREAD

**Issue by jasonustc** [BVLC/caffe#1078]
I've run the get_ilsvrc_aux.sh and downloaded gzip file "caffe_ilsvrc12.tar.gz" from the dropbox, but the problem is, I failed to unzip this file and the error message is :
gzip: stdin: not in gzip format 
tar: child returned status 1 
tar: Error is not revoverble: exiting now
Where can I get the file imagenet_mean.binaryproto?
Thanks.

**Comment by anubhav-nd** [comment]
Hi,

dl.caffe.berkeleyvision.org seems to be down. Could anyone please share val.txt

Thanks
