### ISSUE TITLE
Crash on caffe_copy/caffe_set

### ISSUE THREAD

**Issue by yariv-c** [BVLC/caffe#1082]
I am getting:

math_functions.cpp:92] Check failed: error == cudaSuccess (11 vs. 0)  invalid argument
**\* Check failure stack trace: ***
    @     0x7ffff0a86b7d  google::LogMessage::Fail()
    @     0x7ffff0a88c7f  google::LogMessage::SendToLog()
    @     0x7ffff0a8676c  google::LogMessage::Flush()
    @     0x7ffff0a8951d  google::LogMessageFatal::~LogMessageFatal()
    @           0x4e34a1  caffe::caffe_copy<>()
    @           0x4a228c  caffe::SGDSolver<>::ComputeUpdateValue()
    @           0x49e3f7  caffe::Solver<>::Solve()
    @           0x417de8  train()
    @           0x418b9c  main

The training crashes both in dev and in master, but in different lines (caffe_copy vs. caffe_set). It only happens with a dataset with more than 70,000 images. The net is simple, with layers such as convolution, max-pooling, softmax loss. It happens on two different types of GPU cards. I didn't try running on CPU only. I have Nvidia 331.62.

**Comment by swamiviv** [comment]
@yariv-c  What do you mean by the size of softmax layer ? Could you please explain ? I am experiencing the same error: https://github.com/BVLC/caffe/issues/2691
