### ISSUE TITLE
Train the dataset in random order each time?

### ISSUE THREAD

**Issue by dreadlord1984** [BVLC/caffe#1087]
I found that the train batch samples were trained by the order saved in level-db. The test dataset have the same law. I want to know how to train the samples in random order.

**Comment by sajjo79** [comment]
I am using my own input data layer developed in python. I did two experiments one with sequential batch and other with random batch strategy. Sequential batch i.e. takes 240 images in one step and in next it takes next 240 images and when data set ends, it starts from 0th image again for second epoch. In random image batch, every image is selected at random from data image set. I found random batch strategy more converging as compared to sequential batch strategy. Can anyone comment on it?
