### ISSUE TITLE
An example build on AWS using latest generation GPU instances

### ISSUE THREAD

**Issue by AKSHAYUBHAT** [BVLC/caffe#1092]
I have been unsuccessfully trying to get Caffe to install on latest GPU instances, is it possible to provide a public AMI that has caffe pre-installed?

**Comment by AKSHAYUBHAT** [comment]
Thank you everyone.

**Comment by gun4w1** [comment]
thanks all.. i didn need to ask more..
<a href="http://updatedriversfree.com/canon-pixma-mp495-driver-download-windows-mac-linux/">Canon Pixma MP495 Driver Download for Linux</a>
