### ISSUE TITLE
Use adaptive CUDA launch config to fully utilize GPU devices

### ISSUE THREAD

**Issue by kloudkl** [BVLC/caffe#111]
@sguada published the first profiling result in #81. Starting from there, we can do some more in depth analysis of key success factors such as occupancy to [improve device utilization](http://docs.nvidia.com/cuda/kepler-tuning-guide/index.html#device-utilization-and-occupancy). Occupancy is defined as the ratio of active warps versus the maximum number of warps of a GPU. CUDA visual profiler and occupancy calculator both provide such data.

The best practice guide gives some general principles of [execution configuration optimizations](http://docs.nvidia.com/cuda/cuda-c-best-practices-guide/#execution-configuration-optimizations) to effectively manage the resource utilization. Jared Hoberock, a NVIDIA researcher and co-creator of CUDA template library Thrust, put them into practice with [adaptive CUDA launch configurations](https://github.com/jaredhoberock/cuda_launch_config) whose only essential dependency is cuda_runtime_api.h which will not introduce any new dependency into Caffe.

**Comment by shelhamer** [comment]
Closing as this is not a significant bottleneck at this point.
