### ISSUE TITLE
L-BFGS and CG solvers

### ISSUE THREAD

**Issue by ankurhanda** [BVLC/caffe#1121]
I was reading this paper from Andrew Ng's group http://cs.stanford.edu/~jngiam/papers/LeNgiamCoatesLahiriProchnowNg2011.pdf. I wondered if there is anyone who tried different optimisers e.g. L-BFGS and CG in Caffe? 

Ankur

**Comment by shelhamer** [comment]
Closing as L-BFGS and CG aren't particularly popular (read: effective) approaches for optimizing deep nets as far as the current evidence goes.
