### ISSUE TITLE
How to compile python wrapper on windows

### ISSUE THREAD

**Issue by gogo00007** [BVLC/caffe#1123]
Dear all,

I wanna test a new image on the pretrained models (on windows), but the py file always contain a sentence like "import caffe". Can anyone show me the details on how to compile the python wrapper?

Before that i've successfully run the rest samples as suggested.

**Comment by Coderx7** [comment]
For a thorough tutorial on compiling pycaffe in windows check this out : 
http://thirdeyesqueegee.com/deepdream/2015/07/13/running-deep-dream-on-windows-with-full-cuda-acceleration/
