### ISSUE TITLE
Python interface: get output from layer X, given the output of layer Y

### ISSUE THREAD

**Issue by egavves** [BVLC/caffe#1146]
Hi,

If I have the output from layer X ('pool5' for example), and want to get the output of layer Y ('fc7' for example), what should I do?

I tried to solve this by my own, but I couldn't get it right and I guess it must be something very simple. Currently I was trying to do something with the "forward" function, but I could find the correct arguments.

Cheers,
Stratis

**Comment by HonkeeChan** [comment]
Hi, I am trying to get the feature, but i fail. Could you tell me what is the variable 'net_p5' and 'net_fc7' in the article above?
Thank you very much!

**Comment by fradaric** [comment]
Have a look at this,  this is how I extract intermediate data

data_list = ['conv1','conv2', 'pool1','pool2','ip2','ip1','prob']
	out = net.forward_all(data_list,data=np.asarray([image]))
	interDataConv1 = net.blobs['conv1'].data
	interDataPool1 = net.blobs['pool1'].data
	interDataConv2 = net.blobs['conv2'].data
	interDataPool2 = net.blobs['pool2'].data
	interDataIP1 = net.blobs['ip1'].data
	interDataIP2 = net.blobs['ip2'].data
	interDataSoftMax = net.blobs['prob'].data

**Comment by jundeli** [comment]
> Hi, I am trying to get the feature, but i fail. Could you tell me what is the variable 'net_p5' and 'net_fc7' in the article above?
> Thank you very much!

Did you know how to get these two?
