### ISSUE TITLE
[bug report] bug of convert_imageset of the master branch

### ISSUE THREAD

**Issue by shuokay** [BVLC/caffe#1162]
I have updated the caffe to the lastest master and I found there is a bug when I convert data to leveldb or lmdb format with ```-gray=true```. with that converted data, the CNN will not convergence. how if I check to the tag v0.9999, and convert data with this branch, everything goes well. I am too busy these days, so I have not check the code. I report this bug here, hoping someone would handle it.

**Comment by longjon** [comment]
Closing as this seems to have expired, and there is not enough information to tell if there is really a possible bug here. Please ask usage questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) list. Thanks!
