### ISSUE TITLE
Data Input by MemoryDataLayer example?

### ISSUE THREAD

**Issue by slaweks17** [BVLC/caffe#1168]
Hi,
Could someone please explain how I could convert say an .csv file with 20 columns, out of which first 15 are features and last 5 are outputs into something caffe would accept?
I am trying to use the Windows version, where, it appears, hdf5 data layer has not been ported.
Using MemoryDataLayer? But how do I specify number of inputs, outputs?

Thanks,
Slawek

**Comment by shelhamer** [comment]
Closing as solved by the Python layer interface.

With Python layers almost all of these special data format issues are moot since if you have a line of Python that can load your data you can make a Python data layer to load it too.
