### ISSUE TITLE
Create binary packages for the stable releases

### ISSUE THREAD

**Issue by kloudkl** [BVLC/caffe#1188]
With a large and rapidly growing user base, it is very possible that some of them only need to install and use the library but not to develop itself. Of course, they can always build from the source code. However, the use case can be better satisfied by installing binary packages with a single line command. 

Following [the example of CUDA](https://developer.nvidia.com/cuda-downloads#linux), we can choose between platform specific package formats deb and rpm or platform independent run file. The latter is simply [a all-in-one wrapper](http://www.megastep.org/makeself/) of an installation script and an archive directory which contains the pre-built shared library files and header files.

**Comment by scottsievert** [comment]
+1 for a script

**Comment by shelhamer** [comment]
Closing as we never adopted a fixed release schedule, packaging for debian was taken on and documented in #5111, and packaging by snapcraft could be on its way #5300.
