### ISSUE TITLE
[Bug] image_data layer in feature_extraction example's imagenet_val.prototxt height and width

### ISSUE THREAD

**Issue by EvanWeiner** [BVLC/caffe#1197]
In the examples/feature_extraction/imagenet_val.prototxt, new_height and new_width are defined as 256, but should be set as 227 because a center crop will limit the features extracted from the image.

**Comment by shelhamer** [comment]
Feature extraction is best left to the Python or MATLAB interfaces or custom code that saves to hdf5. The feature extraction example as-is causes more confusion than good so it might just be removed.
