### ISSUE TITLE
RBM layer ? (+DBN)

### ISSUE THREAD

**Issue by cbalint13** [BVLC/caffe#1207]
- Anyone thinking or planning to implement $subj ? I think it would be quite usefull to have:

RBM, GRBM with CD-k, PCD-k

**Comment by kashefy** [comment]
@cbalint13
Did you end up creating a PR for this? still planning to? dropped it?

**Comment by krikru** [comment]
+1 on @kashefy's comment. Why was this issue closed?

**Comment by cbalint13** [comment]
@krikru ,

* An effort is going on: https://github.com/BVLC/caffe/pull/3568 . My time is limited but this on my top todo list and will try enhance with more features.

**Comment by krikru** [comment]
@cbalint13 Sweet. I was just curious :)
