### ISSUE TITLE
MNIST example : data_layer.cpp:61] Check failed: mdb_env_open

### ISSUE THREAD

**Issue by asa88** [BVLC/caffe#1217]
I am getting the following error on running ./train_lenet.sh for the MNIST example :

I1003 22:00:30.171175  2111 net.cpp:67] Creating Layer mnist
I1003 22:00:30.171239  2111 net.cpp:356] mnist -> data
I1003 22:00:30.171288  2111 net.cpp:356] mnist -> label
I1003 22:00:30.171334  2111 net.cpp:96] Setting up mnist
F1003 22:00:30.171702  2111 data_layer.cpp:61] Check failed: mdb_env_open(mdb_env_, this->layer_param_.data_param().source().c_str(), 0x20000|0x200000, 0664) == 0 (2 vs. 0) mdb_env_open failed
**\* Check failure stack trace: ***
    @     0x7f4685d65daa  (unknown)
    @     0x7f4685d65ce4  (unknown)
    @     0x7f4685d656e6  (unknown)
    @     0x7f4685d68687  (unknown)
    @           0x4b3260  caffe::DataLayer<>::DataLayerSetUp()
    @           0x4a31ef  caffe::BaseDataLayer<>::LayerSetUp()
    @           0x4a37b9  caffe::BasePrefetchingDataLayer<>::LayerSetUp()
    @           0x465731  caffe::Net<>::Init()
    @           0x46703e  caffe::Net<>::Net()
    @           0x4703a0  caffe::Solver<>::InitTrainNet()
    @           0x471606  caffe::Solver<>::Init()
    @           0x471766  caffe::Solver<>::Solver()
    @           0x415650  caffe::GetSolver<>()
    @           0x411b44  train()
    @           0x40ef21  main
    @     0x7f4682ff6ec5  (unknown)
    @           0x410691  (unknown)
    @              (nil)  (unknown)
Aborted (core dumped)

Any idea what might be causing this ?

**Comment by jes93** [comment]
I'm having exactly the same problem, but with my own data instead (using create_imagenet.sh). I have created the .mdb files without any problem, but I don't know how to solve this issue.
