### ISSUE TITLE
Problem with extracting features for multiple input images

### ISSUE THREAD

**Issue by StevenLobo2** [BVLC/caffe#1219]
I used python wrapper to classify input images placed in a folder and tried to extract features at pool5.( using features= classifier.blobs['pool5'].data[0].flatten(). Will this extract feature of only one image file or all input images that are passed to classifier.predict? When I write features to a file its only some KB data. 
The same if I use loop and then use classifier.predict for each image in a folder and extract feature for pool5 layer for each image into an feature array and finally write the features to a file it will be in terms of some MBs. 
How to extract the feature of particular layer for all input images that are passed to classifier.predict call?
Thanks
Steven

**Comment by longjon** [comment]
Please ask usage questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) list. Thanks!
