### ISSUE TITLE
AbsVal returns backwards nan

### ISSUE THREAD

**Issue by rodrigob** [BVLC/caffe#1230]
Currently testing my first non-trivial network, I find nan values on the very first iteration.
`I1007 09:26:20.877076 25590 solver.cpp:263] Iteration 0, Testing net (#0)`

First forward pass goes well, loss values are computed.
The on the way backward, I see the first nan at
`I1007 09:26:20.945518 25590 net.cpp:599]     [Backward] Layer abs_z3, bottom blob z3_relu2_0_split_0 diff: nan`

`abs_z3` is simply and `ABSVAL` layer. Why would it have a nan diff ?

`layers {
    name: "abs_z3"
    type: ABSVAL
    bottom: "z3"
    top: "abs_z3"
}`

I guess returning nan is a bug. Either it should check for "improper connections" and raise an error, or  return "sensical values".
Any clue of what might be going wrong are welcome.

ps: I am building over revision b84009e168e6a2354540dff8fabbdc39f574d66f of the caffe-dev branch.

**Comment by shelhamer** [comment]
Fixed by #1326.
