### ISSUE TITLE
Performing net-surgery in pycaffe on a caffe.SGDSolver net

### ISSUE THREAD

**Issue by to3i** [BVLC/caffe#1257]
I have an issue concerning the python wrapper. It seems that a network initialized by the caffe.SGDSolver provides only part of the functionality of a network initialized through caffe.Net. Specifically I tried to use the backward() method as well as the net surgery trick (copy weights from a caffe.Net to a caffe.SGDSolver net) without success. Everything executes, however, without the expected behavior. 

In the following you find my example code for the net surgery. It seems to me that in the background no params are copied. Since I have only a very limited understanding of the python wrapper, I wonder if this is expected behavior and the caffe.SGDSolver net only allows read-only access. Do the efforts in https://github.com/BVLC/caffe/pull/1228 provide a possible workaround?

```
# init SGD solver (using memory data layers for train and test)
solver = caffe.SGDSolver('../models/bvlc_reference_caffenet/solver_memory_train_val.prototxt')
solver.net.set_mode_gpu()
testnet = solver.test_nets[0]

# load caffe reference model
caffenet = caffe.Net('../models/bvlc_reference_caffenet/deploy.prototxt', '../models/bvlc_reference_caffenet/bvlc_reference_caffenet.caffemodel')

# generate dictionaries of the parameters
params = caffenet.params.keys()
source_params = {pr: (caffenet.params[pr][0].data, caffenet.params[pr][1].data) for pr in params}
target_params = {pr: (solver.net.params[pr][0].data, solver.net.params[pr][1].data) for pr in params}

# copy weights from caffenet to solver
for pr in params:
    target_params[pr][1][...] = source_params [pr][1]  #bias
    target_params[pr][0][...] = source_params [pr][0]  #weights

# load and preprocess input data
input_image = caffe.io.load_image('../examples/images/cat.jpg')
input_oversampled = caffe.io.oversample([caffe.io.resize_image(input_image, (256, 256))], (227, 227))
data = np.asarray([solver.net.preprocess('data', in_) for in_ in input_oversampled])
testnet.set_input_arrays(data, labels)

# run solver
solver.solve()

# top-3 outputs
data_prob = testnet.blobs['prob'].data
top_k = data_prob[0].flatten().argsort()[-1:-4:-1]
# class_id [794 599 728] and corresponding probs [ 0.00169671  0.00153411  0.00147332]
```

**Comment by longjon** [comment]
Closing as the problem here seems to have been resolved, and the underlying issues have either been fixed or are documented in other issues.
