### ISSUE TITLE
Library not loaded: @rpath/libcudart.6.5.dylib

### ISSUE THREAD

**Issue by DenisTome** [BVLC/caffe#1273]
when i execute make runtest on Mac OS X 10.9,  this is the error that i get:

dyld: Library not loaded: @rpath/libcudart.6.5.dylib
  Referenced from:    /Users/denntom/Dropbox/DeepLearning/caffe - master/.build_release/test/test_all.testbin 
Reason: image not found 
make: **\* [runtest] Trace/BPT trap: 5

I've reinstalled Cuda and checked that the library was there, but the error is the same.

**Comment by deepsamal** [comment]
@DenisTome Sorry for opening this issue, but couldn't find answer in google group. I am having the same problem. make runtest results-
.build_release/tools/caffe
dyld: Library not loaded: @rpath/libcudart.7.0.dylib
  Referenced from: /Users/deepsamal/Desktop/Research/caffe/.build_release/tools/caffe
  Reason: image not found
make: *** [runtest] Trace/BPT trap: 5

I think I have loaded all variables-
echo $DYLD_FALLBACK_LIBRARY_PATH
/Users/deepsamal/anaconda/lib:/usr/local/lib:/usr/lib:/usr/local/cuda/lib/:/Users/deepsamal/Desktop/Research/cudnn-6.5-osx-v2/:/opt/intel/composer_xe_2015.2.132/mkl/lib/:

**Comment by cntswj** [comment]
If I remove 'sudo' that prefixes 'make', the error disappears...
