### ISSUE TITLE
Only 2 crops used instead of 10 crops in filter_visualization.ipynb

### ISSUE THREAD

**Issue by EvanWeiner** [BVLC/caffe#1275]
In the filter_visualization.ipynb notebook, you will find that only 2 crops are used, the entire image itself and it's mirror. The fix as seen in #1002 is to set net.image_dims=(256, 256) when defining the caffe.Classifier.

**Comment by longjon** [comment]
Closing as this seems to have expired; `filter_visualization.ipynb` uses neither `Classifier` nor crops.
