### ISSUE TITLE
OpenCV 3.0 linking error when compiling CAFFE

### ISSUE THREAD

**Issue by swamiviv** [BVLC/caffe#1276]
I am trying to install CAFFE in ubuntu 14.04 (no-gpu option) with OpenCV 3.0. I am getting the following linker error:

---

Linking CXX executable convert_imageset
cd /home/swami/packages_local/caffe/build/tools && /usr/bin/cmake -E cmake_link_script CMakeFiles/convert_imageset.bin.dir/link.txt --verbose=1
/usr/bin/c++   -fPIC    CMakeFiles/convert_imageset.bin.dir/convert_imageset.cpp.o  -o convert_imageset -rdynamic ../lib/libcaffe.so ../src/caffe/proto/libproto.so -lprotobuf -llapack_atlas -lcblas -latlas -lboost_system -lboost_thread -lpthread -lpthread -lgflags -lglog -lhdf5_hl -lhdf5 -lleveldb -lsnappy -llmdb /usr/local/lib/libopencv_highgui.so.3.0.0 /usr/local/lib/libopencv_imgproc.so.3.0.0 /usr/local/lib/libopencv_core.so.3.0.0 -Wl,-rpath,/home/swami/packages_local/caffe/build/lib:/home/swami/packages_local/caffe/build/src/caffe/proto:/usr/local/lib: -Wl,-rpath-link,/usr/local/lib 
../lib/libcaffe.so: undefined reference to `cv::imread(cv::String const&, int)'
collect2: error: ld returned 1 exit status
make[2]: *** [tools/compute_image_mean] Error 1
make[2]: Leaving directory`/home/swami/packages_local/caffe/build'
make[1]: **\* [tools/CMakeFiles/compute_image_mean.bin.dir/all] Error 2
make[1]: **\* Waiting for unfinished jobs....
../lib/libcaffe.so: undefined reference to `cv::imread(cv::String const&, int)'
collect2: error: ld returned 1 exit status
make[2]: *** [tools/convert_imageset] Error 1
make[2]: Leaving directory`/home/swami/packages_local/caffe/build'
make[1]: **\* [tools/CMakeFiles/convert_imageset.bin.dir/all] Error 2

---

Has anyone come across this problem and can help me with this ?

**Comment by eubmabe** [comment]
I added -lopencv_imgcodecs to my make file and it solved the issue for me.
Thanks!!!

**Comment by abhishek9893** [comment]
how to add -lopencv_imgcodecs to make file??

**Comment by LiberiFatali** [comment]
You can add opencv_imgcodecs to 'Makefile'

**Comment by Mohammad-Mahdi** [comment]
how to add that to the make file? what did you write into the makefile?

**Comment by CharlesShang** [comment]
@Mohammad-Mahdi 

open your Makefile with some text editor, locate line 164 (in my case), add opencv_imgcodecs behind. 


     LIBRARIES += glog gflags protobuf leveldb snappy \
	  lmdb boost_system hdf5_hl hdf5 m \
	  opencv_core opencv_highgui opencv_imgproc opencv_imgcodecs

**Comment by shubhamgoel27** [comment]
I added opencv_imgcodecs to 'Makefile' but it didn't help.

**Comment by SylviaZeng** [comment]
@shubhamgoel27 there is opencv_imgcodecs in my Makefile already, and after I delete opencv_imgcodecs then I make pycaffe successfully.

**Comment by robosina** [comment]
I encounter with this issue and solve by removing # before pkg-config  line and all above comments are helpful.I will write some Makefile line that run for me without any error
       
       uncomment line 11:      USE_OPENCV := 1
       uncomment line 21:      OPENCV_VERSION := 3
       uncomment line 108:     USE_PKG_CONFIG := 1
**but one thing that you must consider** is that when you change  Makefile you must try below commands again(in my case I forgot to uncomment line 11 and after I realized that I change it in Makefile and then test if it works by `make test` command but it not worked because I have to make everything again so try below command first)

     make clean
     make all        (if you want to do that faster then you use make all -j3  )
     
and test again with below commands

     make test    (or make test -j3)

**Comment by tub-sgg** [comment]
where is the  Makefile   i cant find this file

**Comment by hieunm131** [comment]
> where is the Makefile i cant find this file

Is is here? https://github.com/BVLC/caffe/blob/master/Makefile

**Comment by LiberiFatali** [comment]
> where is the Makefile i cant find this file

Is it here? https://github.com/BVLC/caffe/blob/master/Makefile
