### ISSUE TITLE
[cmake] proto header files caffe.pb.h is created in the root include directory

### ISSUE THREAD

**Issue by baeuml** [BVLC/caffe#1285]
The protobuf header files caffe.pb.h is created in include/caffe/proto .

This gives problems if you want to compile caffe for different (versions of) distributions (i.e. on different servers), which have different versions of protobuf.  If the caffe.pb.h is generated with one version of protoc, the build with another version fails due to a version check in caffe.pb.h.

The solution would probably be to move the generated header files to the build directory and include them from there.

**Comment by shelhamer** [comment]
Thanks for catching this -- #1667 fixes this along with making other nice CMake improvements.
