### ISSUE TITLE
Problems running test with MKL

### ISSUE THREAD

**Issue by sguada** [BVLC/caffe#1289]
It seems that something have change in Makefile that prevents `make runtest` to work with MKL

Now I'm getting the problem reported in #344

...: /misc/software-lin/x/mkl/lib/intel64/libmkl_intel_thread.so: undefined symbol: omp_get_num_procs

Maybe it is something related to the dynamic use of libraries.

**Comment by sunsided** [comment]
Very nice. For me, the path to `libiomp5.a` did the trick - it was in `/opt/intel/lib/intel64_lin`.

**Comment by yazdanbakhsh** [comment]
I got this error and none of these solutions worked for me. Any solution?

**Comment by YerongLi** [comment]
I added the path setting in my profile:
```
# MKL
export LD_LIBRARY_PATH=/opt/intel/lib/intel64:/opt/intel/mkl/lib/intel64:$LD_LIBRARY_PATH
# OpenBLAS
export LD_LIBRARY_PATH=/opt/OpenBLAS/lib:$LD_LIBRARY_PATH
```
But running **python -c "import numpy as np;np.test('full')"**  stiil gives me a mkl error:
```
Running unit tests for numpy
NumPy version 1.13.3
NumPy relaxed strides checking option: True
NumPy is installed in /home/yerong/local/anaconda3/lib/python3.6/site-packages/numpy
Python version 3.6.2 |Anaconda custom (64-bit)| (default, Sep 30 2017, 18:42:57) [GCC 7.2.0]
nose version 1.3.7
...........................................................................................................................................................................................................................S....................python: symbol lookup error: /home/yerong/local/anaconda3/lib/python3.6/site-packages/numpy/core/../../../../libmkl_intel_thread.so: undefined symbol: omp_get_num_procs
```

**Comment by jyotipriya** [comment]
@YerongLi, did you get any solution? 
I got kind of similar issue at run time "symbol lookup error: libmkl_intel_thread.so: undefined symbol: __kmpc_global_thread_num". 
I have precompiled required library for MKL and the path are set to that. 
However, the precompiled list does not have the libiomp5.so or libiomp5md.so in it.

**Comment by YerongLi** [comment]
I reinstalled the anaconda and rebuild the caffe and everything works out fine after that.
