### ISSUE TITLE
Testcase failed during make runtest

### ISSUE THREAD

**Issue by moegitree** [BVLC/caffe#1294]
Hi, I am trying execute "make runtest" and met some problems.
The caffe is successfully compiled on Ubuntu12.04 with CPU only.
When executing the testcases, it shows like this:

src/caffe/test/test_math_functions.cpp:109: Failure
Value of: x[i] < 0 ? 1 : 0
  Actual: 1
Expected: signbits[i]
Which is: 512
..................
[  PASSED  ] 450 tests.
[  FAILED  ] 7 tests, listed below:
[  FAILED  ] MathFunctionsTest/0.TestSgnbitCPU, where TypeParam = float
[  FAILED  ] MathFunctionsTest/1.TestSgnbitCPU, where TypeParam = double
[  FAILED  ] MathFunctionsTest/1.TestHammingDistanceCPU, where TypeParam = double
[  FAILED  ] EltwiseLayerTest/0.TestProd, where TypeParam = caffe::FloatCPU
[  FAILED  ] EltwiseLayerTest/0.TestSum, where TypeParam = caffe::FloatCPU
[  FAILED  ] EltwiseLayerTest/1.TestProd, where TypeParam = caffe::DoubleCPU
[  FAILED  ] EltwiseLayerTest/1.TestSum, where TypeParam = caffe::DoubleCPU

I am a new learner of linux and caffe. Great thanks for any help.

**Comment by shuimulinxi** [comment]
hi, when i run make runtest on my computer (ubuntu12.04) ，I get this long

[ RUN      ] MemoryDataLayerTest/0.TestSetBatchSize
OpenCV Error: Assertion failed (k == STD_VECTOR_MAT) in getMat, file /build/buildd/opencv-2.3.1/modules/core/src/matrix.cpp, line 918
unknown file: Failure
C++ exception with description "/build/buildd/opencv-2.3.1/modules/core/src/matrix.cpp:918: error: (-215) k == STD_VECTOR_MAT in function getMat
" thrown in the test body.
[  FAILED  ] MemoryDataLayerTest/0.TestSetBatchSize, where TypeParam = caffe::FloatCPU (1 ms)
[ RUN      ] MemoryDataLayerTest/0.AddMatVectorDefaultTransform
OpenCV Error: Assertion failed (k == STD_VECTOR_MAT) in getMat, file /build/buildd/opencv-2.3.1/modules/core/src/matrix.cpp, line 918
unknown file: Failure
C++ exception with description "/build/buildd/opencv-2.3.1/modules/core/src/matrix.cpp:918: error: (-215) k == STD_VECTOR_MAT in function getMat
" thrown in the test body.
[  FAILED  ] MemoryDataLayerTest/0.AddMatVectorDefaultTransform, where TypeParam = caffe::FloatCPU (1 ms)
[----------] 5 tests from MemoryDataLayerTest/0 (21 ms total)

[----------] 3 tests from ThresholdLayerTest/1, where TypeParam = caffe::DoubleCPU

**Comment by PoulpeVengeur** [comment]
Hi, I have the same problem that stas-si, when I do make runtest I've got this http://pastebin.com/KvubSdsP
and for eltwise_layer it's a little bit weird http://pastebin.com/kEjHmZ3p the values are exactly the same...
I'm using a 32 bits debian testing
Anyone can help me ? Thx !!

**Comment by LinZhineng** [comment]
I met some problems when trying execute "make runtest" . The caffe is compiled on Ubuntu12.04 with CPU only. Detail just listed below：

OpenCV Error: Assertion failed (k == STD_VECTOR_MAT) in getMat, file /build/buildd/opencv-2.3.1/modules/core/src/matrix.cpp, line 918
unknown file: Failure
C++ exception with description "/build/buildd/opencv-2.3.1/modules/core/src/matrix.cpp:918: error: (-215) k == STD_VECTOR_MAT in function getMat

[  FAILED  ] 12 tests, listed below:
[  FAILED  ] IOTest.TestDecodeDatumToCVMat
[  FAILED  ] IOTest.TestDecodeDatumToCVMatContent
[  FAILED  ] IOTest.TestDecodeDatumToCVMatContentNative
[  FAILED  ] IOTest.TestDecodeDatum
[  FAILED  ] IOTest.TestDecodeDatumToCVMatNativeGray
[  FAILED  ] IOTest.TestDecodeDatumToCVMatNative
[  FAILED  ] IOTest.TestDecodeDatumNative
[  FAILED  ] IOTest.TestDecodeDatumNativeGray
[  FAILED  ] MemoryDataLayerTest/0.AddMatVectorDefaultTransform, where TypeParam = caffe::FloatCPU
[  FAILED  ] MemoryDataLayerTest/0.TestSetBatchSize, where TypeParam = caffe::FloatCPU
[  FAILED  ] MemoryDataLayerTest/1.AddMatVectorDefaultTransform, where TypeParam = caffe::DoubleCPU
[  FAILED  ] MemoryDataLayerTest/1.TestSetBatchSize, where TypeParam = caffe::DoubleCPU
12 FAILED TESTS
make: *** [runtest] Error 1
Many thanks for any help.

**Comment by LinZhineng** [comment]
I met some problems when trying execute "make runtest" . The caffe is compiled on Ubuntu12.04 with CPU only.

OpenCV Error: Assertion failed (k == STD_VECTOR_MAT) in getMat, file /build/buildd/opencv-2.3.1/modules/core/src/matrix.cpp, line 918
unknown file: Failure
C++ exception with description "/build/buildd/opencv-2.3.1/modules/core/src/matrix.cpp:918: error: (-215) k == STD_VECTOR_MAT in function getMat

I chage the Makefile.config
PYTHON_LIB := /usr/lib               replace with              PYTHON_LIB := usr/local/lib

Succesful!!!

notes: when you compile once again, please execute "make clean" first

**Comment by sarkeribrahim** [comment]
[----------] 5 tests from ImageDataLayerTest/1, where TypeParam = caffe::CPUDevice<double>
[ RUN      ] ImageDataLayerTest/1.TestReshape
[       OK ] ImageDataLayerTest/1.TestReshape (46 ms)
[ RUN      ] ImageDataLayerTest/1.TestShuffle
[       OK ] ImageDataLayerTest/1.TestShuffle (106 ms)
[ RUN      ] ImageDataLayerTest/1.TestRead
[       OK ] ImageDataLayerTest/1.TestRead (103 ms)
[ RUN      ] ImageDataLayerTest/1.TestResize
[       OK ] ImageDataLayerTest/1.TestResize (122 ms)
[ RUN      ] ImageDataLayerTest/1.TestSpace
[       OK ] ImageDataLayerTest/1.TestSpace (63 ms)
[----------] 5 tests from ImageDataLayerTest/1 (440 ms total)

[----------] Global test environment tear-down
[==========] 1096 tests from 150 test cases ran. (68513 ms total)
[  PASSED  ] 1095 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] NeuronLayerTest/0.TestPReLUForward, where TypeParam = caffe::CPUDevice<float>

 1 FAILED TEST
make[3]: *** [src/caffe/test/CMakeFiles/runtest] Error 1
make[2]: *** [src/caffe/test/CMakeFiles/runtest.dir/all] Error 2
make[1]: *** [src/caffe/test/CMakeFiles/runtest.dir/rule] Error 2
make: *** [runtest] Error 2



why this error?
