### ISSUE TITLE
Max over feature maps / MaxOut?

### ISSUE THREAD

**Issue by BestSonny** [BVLC/caffe#1299]
Caffe have this function？

**Comment by Coderx7** [comment]
Any answer if the post @BestSonny  is the correct way to go with this?

**Comment by BestSonny** [comment]
@Coderx7  [May helps](https://github.com/BestSonny/DeepFeature/blob/master/model/deploy.prototxt)

**Comment by Coderx7** [comment]
Thanks alot @BestSonny
