### ISSUE TITLE
encounter problems with single input data  227*227 store in levelDB.

### ISSUE THREAD

**Issue by BestSonny** [BVLC/caffe#1302]
I1016 21:09:34.857409 40678 data_layer.cpp:128] output data size: 256,3,227,227
I1016 21:09:34.857434 40678 base_data_layer.cpp:36] Loading mean file fromimagenet_mean_train.binaryproto
I1016 21:09:34.955337 40678 net.cpp:103] Top shape: 256 3 227 227 (39574272)
I1016 21:09:34.955394 40678 net.cpp:103] Top shape: 256 1 1 1 (256)
I1016 21:09:34.955430 40678 net.cpp:67] Creating Layer conv1
I1016 21:09:34.955481 40678 net.cpp:394] conv1 <- data
I1016 21:09:34.955515 40678 net.cpp:356] conv1 -> conv1
Floating point exception (core dumped)

**Comment by xxw345** [comment]
I0119 11:16:12.814046  4355 net.cpp:394] conv1 <- data
I0119 11:16:12.814069  4355 net.cpp:356] conv1 -> conv1
I0119 11:16:12.814139  4355 net.cpp:96] Setting up conv1
Floating point exception
I meet a similar error, could you tell me where I might have a problem?

**Comment by svanschalkwyk** [comment]
Has anyone found the cause of this?
I0123 12:30:46.109096  5580 net.cpp:103] Top shape: 256 3 64 64 (3145728)
I0123 12:30:46.109103  5580 net.cpp:103] Top shape: 256 1 1 1 (256)
I0123 12:30:46.109109  5580 net.cpp:113] Memory required for data: 12583936
I0123 12:30:46.109135  5580 net.cpp:67] Creating Layer conv1
I0123 12:30:46.109145  5580 net.cpp:394] conv1 <- data
I0123 12:30:46.109177  5580 net.cpp:356] conv1 -> conv1
I0123 12:30:46.109194  5580 net.cpp:96] Setting up conv1
Floating point exception (core dumped)

**Comment by svanschalkwyk** [comment]
Here is the train.prototxt file up to the failure:
name: "CaffeNet"
layers {
  name: "data"
  type: DATA
  top: "data"
  top: "label"
  data_param {
    source: "/projects/kaggle/exp0/train_lmdb"
    backend: LMDB
    batch_size: 256
  }
  transform_param {
    crop_size: 64
    mean_file: "/projects/kaggle/exp0/mean.binaryproto"
    mirror: true
  }
  include: { phase: TRAIN }
}
layers {
  name: "data"
  type: DATA
  top: "data"
  top: "label"
  data_param {
    source: "/projects/kaggle/exp0/val_lmdb"
    backend: LMDB
    batch_size: 50
  }
  transform_param {
    crop_size: 64
    mean_file: "/projects/kaggle/exp0/mean.binaryproto"
    mirror: false
  }
  include: { phase: TEST }
}
layers {
  name: "conv1"
  type: CONVOLUTION
  bottom: "data"
  top: "conv1"
  blobs_lr: 1
  blobs_lr: 2
  weight_decay: 1
  weight_decay: 0
  convolution_param {
    num_output: 256
    kernel_size: 11
    stride: 4
    weight_filler {
      type: "gaussian"
      std: 0.01
    }
    bias_filler {
      type: "constant"
      value: 0
    }
  }
}
layers { .....}

**Comment by xxw345** [comment]
I meet the similar errors first time, but when I change the real patch size to 36x36, it will never come out. I also need to know why so sensitive to the patch size.

**Comment by svanschalkwyk** [comment]
Are there any errors when you "make runtest"?

**Comment by xxw345** [comment]
I also meet the errors when completed training and prepare to use the trained model to recover the image patches. It also looks like size issues, but still not resolved.

**Comment by svanschalkwyk** [comment]
set mirror:false - solves first problem and produces others, but getting
further...

_______________________________________________
*Remcam LLC <http://remcam.net>  *                                 *
http://remcam.net
<http://remcam.net>*
Voice/SMS:  +1 312 281 8982 <312+281+8982> (all lines)
Skype: svanschalkwyk
LinkedIn <http://linkedin.com/in/vanschalkwyk>
_______________________________________________

**Comment by svanschalkwyk** [comment]
send me your protox files. I'v got mine running


_______________________________________________
*Remcam LLC <http://remcam.net>  *                                 *
http://remcam.net
<http://remcam.net>*
Voice/SMS:  +1 312 281 8982 <312+281+8982> (all lines)
Skype: svanschalkwyk
LinkedIn <http://linkedin.com/in/vanschalkwyk>
_______________________________________________

**Comment by svanschalkwyk** [comment]
https://github.com/BVLC/caffe/issues/1199


_______________________________________________
*Remcam LLC <http://remcam.net>  *                                 *
http://remcam.net
<http://remcam.net>*
Voice/SMS:  +1 312 281 8982 <312+281+8982> (all lines)
Skype: svanschalkwyk
LinkedIn <http://linkedin.com/in/vanschalkwyk>
_______________________________________________
