### ISSUE TITLE
How to set the parallel structure of CNN architecture 

### ISSUE THREAD

**Issue by dongguangyao** [BVLC/caffe#1303]
Dear Sir:
  Sorry to bother you, I want to know how to write the prototxt and set the slover of caffe if i want to utilize several CNN to train the model at the same time. In detail, if I want to utilize several positions(eye,mouth...) of one image to do the training. In other words, I want to divide one image into 60 patchs (use 60 cnn to train it parallelly) and add one full connected layer. The detail could be explained in the paper "Deep Learning Face Representation from Predicting 10,000 Classes" 
  Please give me a favor. Thank you very much!

Best Regards

**Comment by shelhamer** [comment]
Please ask modeling questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) group.
