### ISSUE TITLE
Cannot load leveldb features when training Lenet

### ISSUE THREAD

**Issue by mowangphy** [BVLC/caffe#1314]
Currently I am trying to use Caffe to do my deep learning research. I have installed Caffe and hope to test it by using your Lenet MNIST example. However, I met a very strange problem.

I firstly download and generate MNIST feature by using the two scripts get_mnist.sh and create_mnist.sh, and successfully output two folds "mnist-train-leveldb" and "mnist-test-leveldb" that contain one data.mdb and one lock.mdb respectively. Then I revised the datalayer in "lenet_train_test.prototxt" to make the source points to those two data folds. However, when I run the script "train_lenet.sh", it cannot work and the error report is shown below:

I1016 11:05:57.590065  9462 net.cpp:67] Creating Layer mnist
I1016 11:05:57.590072  9462 net.cpp:356] mnist -> data
I1016 11:05:57.590087  9462 net.cpp:356] mnist -> label
I1016 11:05:57.590095  9462 net.cpp:96] Setting up mnist
I1016 11:05:57.590114  9462 data_layer.cpp:45] Opening leveldb mnist-train-leveldb
F1016 11:05:57.601310  9462 data_layer.cpp:48] Check failed: status.ok() Failed to open 
leveldb mnist-train-leveldb
Invalid argument: mnist-train-leveldb: does not exist (create_if_missing is false)
**\* Check failure stack trace: ***
    @     0x7f8204d3bb6d  google::LogMessage::Fail()
    @     0x7f8204d3fb87  google::LogMessage::SendToLog()
    @     0x7f8204d3da09  google::LogMessage::Flush()
    @     0x7f8204d3dd0d  google::LogMessageFatal::~LogMessageFatal()
    @           0x4ea288  caffe::DataLayer<>::DataLayerSetUp()
    @           0x4be66d  caffe::BaseDataLayer<>::LayerSetUp()
    @           0x4bed29  caffe::BasePrefetchingDataLayer<>::LayerSetUp()
    @           0x4682fc  caffe::Net<>::Init()
    @           0x46aa2e  caffe::Net<>::Net()
    @           0x49de7f  caffe::Solver<>::InitTrainNet()
    @           0x49f347  caffe::Solver<>::Init()
    @           0x49f7d5  caffe::Solver<>::Solver()
    @           0x416578  caffe::GetSolver<>()
    @           0x413440  train()
    @           0x413dd6  main
    @       0x33ff61ed1d  (unknown)
    @           0x411ce9  (unknown)

The error report said the fold "mnist-train-leveldb" does not exist, but I confirmed that I have already generated the two data folds and defined the routes in "lenet_train_test.prototxt" correctly. I have tried to put the data folds in different directions and use "chmod 777 ./mnist-train-leveldb" to change the right, but the error still happens. 

Does anyone meet the same problem or have some hints to deal with this error?

**Comment by palewithout** [comment]
Hi ,@mowangphy,I am new to caffe,and I met the same problem,can you tell me how to solve it in details? In fact,I do not know how to "add back end: LMDB to the Data layers"......thank you very much!

**Comment by mowangphy** [comment]
Hi @palewithout , to deal with this problem just add a line 'backend' in the datalayer of mnist prototxt:
layers {
  name: "mnist"
  type: DATA
  top: "data"
  top: "label"
  data_param {
    source: "mnist-train-leveldb"
    scale: 0.00390625
    batch_size: 64
	backend: LMDB
  }
  include: { phase: TRAIN }
}

Regards

**Comment by palewithout** [comment]
@mowangphy,oh,it is very kind of you,i have solved this before by myself,but your suggestion is still helpful,thanks a lot,:-)
