### ISSUE TITLE
Caffe Timings for GoogleNet, VGG, AlexNet with cuDNN

### ISSUE THREAD

**Issue by sguada** [BVLC/caffe#1317]
As part of my on going training of GoogleNet in Caffe (the wining entry of ImageNet-2014) I was doing some timings, and these are my findings:

[Comparison with Caffe_reference]
- GoogleNet with cuDNN is (2.8x forward, 3.6x backward) slower than caffe_reference with cuDNN.
- VGGNet_16Layers without cuDNN is (11.5x forward, 18.7x backward) slower than caffe_reference with cuDNN.
- VGGNet_19Layers without cuDNN is (13.8x forward, 22x backward) slower than caffe_reference with cuDNN.

These experiments are run in one K40c using batch_size:128 in a server with 8-GPUs running other tasks.

[Comparison with cuDNN vs without cuDNN]
- caffe_reference with cuDNN is (1.4x forward, 1.28x backward) faster than without cuDNN
  - Average Forward pass: 200.792 ms.
  - Average Backward pass: 310.973 ms.
  - Average Forward-Backward: 511.953 ms.
- caffe_reference without cuDNN 
  - Average Forward pass: 281.24 ms.
  - Average Backward pass: 398.719 ms.
  - Average Forward-Backward: 680.189 ms.
- GoogleNet with cuDNN is (1.6x forward, 1.4x backward) faster than without cuDNN
  - Average Forward pass: 562.841 ms. 
  - Average Backward pass: 1123.84 ms. 
  - Average Forward-Backward: 1688.8 ms. 
- GoogleNet without cuDNN
  - Average Forward pass: 922.007 ms. 
  - Average Backward pass: 1533.55 ms. 
  - Average Forward-Backward: 2455.89 ms.

For the VGG networks I need to use batch_size: 64 to be able to fit them in memory, so I multiplied the times by 2.
- VGG_16Layers with cuDNN is (1.2x, 1.12x) slower than without cuDNN
  - Average Forward pass: 2772 ms.
  - Average Backward pass: 6546.86 ms.
  - Average Forward-Backward: 9324.94 ms.
- VGG_16Layers without cuDNN 
  - Average Forward pass: 2298.68 ms. 
  - Average Backward pass:  5825.2 ms.
  - Average Forward-Backward: 8124.48 ms. 
- VGG_19Layers with cuDNN is (1.22x, 1.36x) slower than without cuDNN
  - Average Forward pass: 3387.08 ms.
  - Average Backward pass: 7928.3 ms.
  - Average Forward-Backward: 11316.92 ms.
- VGG_19Layers without cuDNN 
  - Average Forward pass:  2769.9 ms.
  - Average Backward pass: 6850.64 ms.
  - Average Forward-Backward: 9623.26 ms.

**Comment by andresromero** [comment]
Hi Sergio!

I am testing your GoogleNet implementation with a personal dataset and I am running out of memory (I am using a GeRorce GTX 760 card with 2048 MB).

I have already tried to reduce the batch size (I even tested with `batch_size: 1`) but it is still running out memory. I was just wondering which Nvidia card did you use for your tests or how can I change my configuration files to run the GoogleNet on my card (for the AlexNet it runs flawlessly using `batch_size: 96`).

I would appreciate your help, thanks!

**Comment by ducha-aiki** [comment]
@andresromero 
Try to turn off testing while learning. (comment out test_iter and test_interval in solver)

**Comment by andresromero** [comment]
Thanks @ducha-aiki  it worked!

**Comment by LIACS-medialab** [comment]
Hi @andresromero 
I met the same problem with you. For VGGnet, I use the Titan(6GB) card, and the batchsize =1,
but it always runs out of memory. How to solve it ? (comment out test_iter and test_interval in solve does not work)

**Comment by jmendozais** [comment]
Hi, I am training the VGG16 model with a K20 4 GB card, but it works just for batch sizes <= 10. How can I  train the model with greater batch sizes ?

**Comment by ducha-aiki** [comment]
Turn off testing -> ~2 times less memory consumption.

**Comment by iCodeBIT** [comment]
Hi,I am new to Caffe. How do you get the average timing data?

**Comment by yuhan210** [comment]
Does anyone have any ideas why using cuDNN makes things slower for some networks (e.g., VGG)?

**Comment by sjlee7748** [comment]
Hi, I want to know why forward pass is faster than backward pass. If you know about that, please tell me about that. thank you!

**Comment by gurkirt** [comment]
@sjlee7748  check <a href="https://github.com/weiliu89/caffe/issues/123">here</a> 

What I have observed from my  is that backward pass in faster than forward pass without cuDNN and other way around if you compiled using cuDNN.

I guess it depends upon the implementation.

hope it helps.
Cheers,
Gurkirt

**Comment by raequin** [comment]
Question: I'd like to train and test your GoogLeNet replica for my application where I have 512x512 grayscale images that can have one of four possible classifications, so can you point me in the direction of what I would need to modify in the prototxt for this situation?  As you can see, I am new to this.
