### ISSUE TITLE
Should pooling regions be identical to convolution regions? 

### ISSUE THREAD

**Issue by longjon** [BVLC/caffe#1318]
Pooling and convolution both aggregate inputs over rectangular regions defined by kernel size, stride, and padding parameters. (In fact, average pooling is convolution with a fixed filter, and max pooling is a special case of "tropical convolution".)

However, Caffe currently uses different sets of regions (and consequently, produces different output sizes) for pooling and convolution. Convolution regions are never allowed outside of the padded input, while pooling is performed when a _strided_ pooling region extends off the ends of the input.

This inconsistency causes some annoyance when the exact sizes of things need to be computed and can vary (due to to #594). (The issue doesn't normally come up when using networks like AlexNet that ensure that their pooling regions don't encounter this edge case.)

Should the behavior be made consistent, or is there a good reason for its current state?

(See also #988, but note that the expression presented there is different from both the current behaviors.)

**Comment by dujianyi** [comment]
I met with the same problem, just wonder if there is already a solution to this? 
It might be good to have a switch that I can choosing between taking ceiling and floor?

**Comment by wenwei202** [comment]
Thanks for details. Wired dimension of outputs of pooling is confusing.

**Comment by drcege** [comment]
Hey guys, it has been a very long time since the issue was opened. 
When can we solve this problem？
