### ISSUE TITLE
Datum float_data: shouldn't it be packed?

### ISSUE THREAD

**Issue by ssafar** [BVLC/caffe#1321]
Just noticed that although BlobProto uses a `[packed = true]` data format, the same isn't true for floats stored in a `Datum` proto. The result is a single byte prefix for every float, incurring a 25% storage overhead, also making it complicated to bulk copy the floats into e.g. a Blob.

I was wondering whether there was a good reason for this, or is it a merely historical thing that could be fixed?

**Comment by shelhamer** [comment]
Closed as unlikely to be fixed at this point.
