### ISSUE TITLE
make all with  USE_CUDNN := 1 cannot find cudnn.h

### ISSUE THREAD

**Issue by synchro--** [BVLC/caffe#1325]
This might really be a stupid error but I cannot locate the 'cudnn.h' file. 
The error is this :
./include/caffe/util/cudnn.hpp:5:19: fatal error: cudnn.h: No such file or directory
Someone can help me? 

Thank you

**Comment by jnhwkim** [comment]
In my case, `cudnn.h` took place in `/opt/cudnn/cuda/include/` by unknown.

**Comment by SmallOneHan** [comment]
Hello, I met the same issue  in the beginning. I have fixed it now by doing these.
https://developer.nvidia.com/cudnn
resigier and download cudnn-7.0-linux-x64-v4.0-rc.tgz 
explode file in ~/ directory

**Comment by Coderx7** [comment]
I had the same problem, I downloaded the cuddn library package ( in my case (cudnn-7.0-linux-x64-v3.0-prod.tgz) and after extracting its contetnt (include and lib64 directories) I placed their contents in the usr/include and usr/lib respectively . everything compiled just fine.

**Comment by sabako123** [comment]
Good Morning,

The file 'cudnn.h' is located in the foler where you have installed your 'cudnn', for exemple : 

cp lib64/* /usr/local/cuda/lib64/
cp include/cudnn.h /usr/local/cuda/include/

so you have to edit the Makefile.config which is in the caffe root folder,
#edit Makefile.config
#uncomment this line "USE_CUDNN := 1" for acceleration GPU
# add /usr/local/cuda/include/  to INCLUDE_DIRS ( just add withspace between two path)
# and add /usr/local/cuda/lib64/ to LIBRARY_DIRS ( just add withspace between two path)

cordially.

**Comment by luisitobarcito** [comment]
I would suggest not to copy the cudnn library files into /usr/local/cuda directory. This may create issues with newer versions of the library. 
An easier solution is to modify the Makefile.config:  
add <your_cudnn_location>/cuda/include/ to INCLUDE_DIRS ( just add withspace between two path)
and add <your_cudnn_location>/cuda/lib64/ to LIBRARY_DIRS ( just add withspace between two path)

and edit your .bashrc file adding the following line:
export LD_LIBRARY_PATH=<your_cudnn_location>/cuda/lib64/:${LD_LIBRARY_PATH}

<your_cudnn_location> is the place here you untar the library files obtained from https://developer.nvidia.com/cudnn
Notice that at the moment, caffe supports cudnn v4.0 not v5.0 (current version)

**Comment by monajalal** [comment]
After downloading CuDNN library folder in tgz format you get cudnn.h in /cuda/include folder, then I did so:
`sudo cp /home/jalal/cudnn/cuda/include/cudnn.h /usr/include/`

**Comment by anshkapil** [comment]
Is it possible to link caffe to a local cudnn installation instead of copying the include and lib64 files?

I tried to change cuda.cmakelists , but its not successful

**Comment by vg123** [comment]
In Makefile I changed `GPU=1 CUDNN=1 OPENCV=0`. but initially It was giving error this.
```
ubuntu@ip-10-0-0-226:~/$ make
gcc  -DGPU -I/usr/local/cuda-7.0/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DGPU -DCUDNN -c ./src/gemm.c -o obj/gemm.o
In file included from ./src/gemm.c:3:0:
./src/cuda.h:15:19: fatal error: cudnn.h: No such file or directory
 #include "cudnn.h"
                   ^
compilation terminated.
make: *** [obj/gemm.o] Error 1
``` 
And when I included the `cudnn.h` in `/usr/include/` it is giving this error.

```
ubuntu@ip-10-0-0-226:~/$ make
gcc  -DGPU -I/usr/local/cuda-7.0/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DGPU -DCUDNN -c ./src/gemm.c -o obj/gemm.o
In file included from ./src/cuda.h:15:0,
                 from ./src/gemm.c:3:
/usr/include/cudnn.h:54:0: error: unterminated #if
 #if !defined(CUDNN_H_)
 ^
compilation terminated due to -Wfatal-errors.
make: *** [obj/gemm.o] Error 1
```
Please tell me how can I solve this error.

**Comment by sumsuddin** [comment]
Install `cudnn` developer library, not the runtime library.  Make sure you're not silly like me :-)

**Comment by khazaddim** [comment]
> Hello, I met the same issue in the beginning. I have fixed it now by doing these. https://developer.nvidia.com/cudnn resigier and download cudnn-7.0-linux-x64-v4.0-rc.tgz explode file in ~/ directory

Thank you.  I could not get cudnn.h in the .deb installers.  i had to use the Tar and extract.

**Comment by synchro--** [comment]
People commenting on an issue I opened 9 years ago 😢 
The feels. 

Is Caffe still being used? Isn't everyone on PyTorch?

**Comment by Coderx7** [comment]
> People commenting on an issue I opened 9 years ago 😢 The feels.
> 
> Is Caffe still being used? Isn't everyone on PyTorch?

Caffe is pretty much dead, but there are people still using it for some reason. Turbo c++ was used by some teachers, students like up until 2012, 2015!! Caffe ain't that old yet 😄
Caffe 2 has been merged into pytorch as far I know.
