### ISSUE TITLE
Maximum label dimension and how to model problems with 2+ dimensions

### ISSUE THREAD

**Issue by mauinz** [BVLC/caffe#1341]
Hi, from what I've read about caffe and the HDF5 data layers, it seems the label dimension is capped at 2. If I understand this correctly, since our first dimension defines where in our batch we are this means for any training image we can only have a 1D vector for regression.

If this is the case I'm curious as to why this cap was enforced. Of course we could get around this by flattening any none 1D label but that seems rather inelegant.

I could be understanding the code wrong so please correct me if this is the case. 

edit: Having thought a bit more, has this been done as you assume the final layer (pre label) will be fully connected?

**Comment by thigitogatiamas** [comment]
When you say 

> To learn a k-D problem, define a model with k-D output and k-D truth for k in {1, 2, 3, 4}, prepare the data, and brew

How do you create a k-D output? I thought the only output you have is a loss layer and accuracy layer for the test phase?
