### ISSUE TITLE
finetune_net.bin deprecated?

### ISSUE THREAD

**Issue by dongguangyao** [BVLC/caffe#1356]
Dear Sir:
  I want to do some classfication on my own data based on the imagenet architecture. After converting the data to lmdb. I wrote a shell to run that,like following:
 finetune_net.bin xxx/solver reference_model.
 However, it says that i need to utilize caffe train --solver =... [--weights = ... ] instead,
 Therefore, I wrote the command like that:
 finetune_net.bin caffe train --slover = xxx/solver.  However, it still occurs that problem.
 As the result of that, could you give me a favor and tell me how to overcome that? Thank you

Best Regards

**Comment by Elpidam** [comment]
@melgor hello! could you indicate me where "caffe" should be located? In caffe 0.999 there is no directory "tools" so I can not run finetuning :(

**Comment by melgor** [comment]
Did you compile the Caffe? If so, go into build/tools and there is "caffe" bianary, which should be used for fine-tunning.
