### ISSUE TITLE
convolution when there is no enough area

### ISSUE THREAD

**Issue by dabilied** [BVLC/caffe#1357]
For example , resize image to 224 224 and conv {size 11, stride 4,pad 1 } 
As 224+2=226; 226-11+1=216; 1+4*54=217 >216 ;the last convolution has no enough areas an the
out put will be size (54,54), can some option padding zero, and make the out put size (55,55)

**Comment by shelhamer** [comment]
Convolution and pooling both have a `pad` field for implicit zero padding in model definitions.
