### ISSUE TITLE
Fatal error : 'tr1/tuple' file not found

### ISSUE THREAD

**Issue by jamesguoxin** [BVLC/caffe#1358]
Hello guys,

I was compiling caffe under OS X 10.10 with clang++, and encountered with following error:

/usr/bin/clang++ src/caffe/net.cpp -pthread -fPIC -DNDEBUG -O2 -DCPU_ONLY -I/Users/JamesGuo/anaconda/include -I/Users/JamesGuo/anaconda/include/python2.7 -I/Users/JamesGuo/anaconda/lib/python2.7/site-packages/numpy/core/include -I/usr/local/include -I.build_release/src -I./src -I./include -I/Users/JamesGuo/Documents/openblas/include -Wall -Wno-sign-compare -Wno-unneeded-internal-declaration -c -o .build_release/src/caffe/net.o 2> .build_release/src/caffe/net.o.warnings.txt \
        || (cat .build_release/src/caffe/net.o.warnings.txt; exit 1)
In file included from src/caffe/net.cpp:17:
In file included from ./include/caffe/test/test_caffe_main.hpp:7:
./src/gtest/gtest.h:1561:13: fatal error: 'tr1/tuple' file not found
# include  < tr1/tuple >  // NOLINT

1 error generated.
make: **\* [.build_release/src/caffe/net.o] Error 1

Personally I think there is some issue with gtest since this is a quite famous error and should be fixed in new version of gtest. I just don't know how to adapt it in caffe. Thank you so much if you could provide any suggestion.

**Comment by scottsievert** [comment]
Editing the makefile and specifing 10.10 instead of 10.9 worked for me. Maybe a good fix would be to use `if(version >= 10.9)`?

```make
#ifneq ($(findstring 10.9, $(shell sw_vers -productVersion)),) 
ifneq ($(findstring 10.10, $(shell sw_vers -productVersion)),)
```

**Comment by sseltser** [comment]
awesome, the makefile worked for me!

**Comment by shelhamer** [comment]
#1740 makes Yosemite work out of the box with the Makefile.

**Comment by keshavbashyal** [comment]
@jnhwkim Can you please explain how to add include path.
