### ISSUE TITLE
Skip unneeded forward computation during learning?

### ISSUE THREAD

**Issue by longjon** [BVLC/caffe#1360]
We have a pretty general mechanism to perform only the necessary backward steps during learning. Perhaps we should also skip unnecessary forward steps. It's easy enough to remove layers or use phases or stages to accomplish the same thing, but it might still be convenient to know that unnecessary computation is never being performed, without having to do anything.

This comes up, for example, when one has a net with multiple losses, and disables some of those losses (e.g., with `loss_weight`).

**Comment by hyojinie** [comment]
@mtamburrano @longjon  Was there any progress afterwards other than #2053? CuDNN layers do not seem to handle 0 batch size bottom blobs.  

tatus == CUDNN_STATUS_SUCCESS (3 vs. 0)  CUDNN_STATUS_BAD_PARAM
*** Check failure stack trace: ***
    @     0x7fd13693edaa  (unknown)
    @     0x7fd13693ece4  (unknown)
    @     0x7fd13693e6e6  (unknown)
    @     0x7fd136941687  (unknown)
    @     0x7fd13700fb31  caffe::CuDNNSigmoidLayer<>::Reshape()
    @     0x7fd13712cbaa  caffe::Net<>::ForwardFromTo()
    @     0x7fd13712cf47  caffe::Net<>::Forward()
    @     0x7fd136fbd1dc  caffe::Solver<>::Test()
    @     0x7fd136fbdb0e  caffe::Solver<>::TestAll()
    @     0x7fd136fbdc00  caffe::Solver<>::Step()
    @     0x7fd136fbe5c9  caffe::Solver<>::Solve()
    @           0x40873b  train()
    @           0x405b3c  main
    @     0x7fd13594af45  (unknown)
    @           0x4063ab  (unknown)
    @              (nil)  (unknown)
