### ISSUE TITLE
Easy access for asking questions in GitHub other than the caffe-users mailing list in google

### ISSUE THREAD

**Issue by llyydd007** [BVLC/caffe#1365]
Chinese is not easy to use google mailing list. Google mail is blocked in China. I have to use agent to access the mailing list, but it is still really slow.But the GitHub is more easily scanned. I wonder Whether we can have a place to ask questions in GitHub. Thanks a lot !

**Comment by asgailey** [comment]
I am trying to do pixelwise predictions for RGB images, and I would like to know whether the ground truth is in the form of another image, a python matrix or some other type of matrix?

I know that when classifying an image, each line of the train.txt file has the image path followed by an integer.  When doing pixelwise predictions, would each line of train.txt by the image path followed by the path to the ground truth matrix?

**Comment by shaibagon** [comment]
@asgailey 
Please use the [caffe-users list][1] for usage, installation, or modeling questions, or other requests for help.
You may also post questions on [stackoverflow][3], make sure you tag them with `caffe` tag.  
There is also [caffe.help][4] documenting the different layers of caffe.
Do not post such requests to Issues. Doing so interferes with the development of Caffe.

Please read the [guidelines for contributing][2] before submitting this issue.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
 [3]: http://stackoverflow.com/questions/tagged/caffe
 [4]: http://caffe.help/manual/layers.html
