### ISSUE TITLE
new Net(string param_file) failed in matcaffe 

### ISSUE THREAD

**Issue by SophieZhou** [BVLC/caffe#1393]
I debug the code under windows, I found when I use a param_file to new a net in matcaffe, the matlab or in vs debug will failed. I found in matcaffe's static void init(MEX_ARGS) function, the command line is      
net_.reset(new Net<float>(string(param_file))). I found that the operation 'new Net<float>(string(param_file))' failed.

Do anyone has met this problem?

**Comment by shelhamer** [comment]
Windows isn't officially supported, but it sounds like your Windows Caffe included an old version of the protobuf definition. Please ask on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) mailing list. Thanks!
