### ISSUE TITLE
What is the guideline for namespaces?

### ISSUE THREAD

**Issue by netheril96** [BVLC/caffe#1401]
Is it acceptable to create a sub-namespace of namespace `caffe`? It seems that currently all classes live in this giant namespace, and I would like to know if this is a design choice that I should not violate.

I am not suggesting changing the current namespace structure. Instead, I plan to write a bunch of classes related together, and it will be easier to group them in another namespace.

**Comment by longjon** [comment]
Yes, it's okay to create sub-namespaces within `caffe` where appropriate, and in fact we have some now.
