### ISSUE TITLE
Selective Search and detect.py slow

### ISSUE THREAD

**Issue by sailes437** [BVLC/caffe#1408]
I am using caffe to train a model for face recognition. i am also woking on multiple object detection using the bvlc_reference_caffenet.caffemodel and i use the detect.py python file for this purpose. The classify.py works well with good accuracy but when i work with detect.py i am facing two problems.
1> The detection is too slow. I use selective_search/selective_search_rcnn to generate probable windows for detection. It generates around 1k windows for each image. Maybe 1000 windows are too big for python to process and it takes around 140 seconds to process them in a single image.
2>> The other problem I am facing is that the program after detection returns many windows(more than 20) with prediction greater than 95 %. But the image I am using has no more than 2 -5 object. How can I agregate nearby windows?? Or is their any way to filter out the false detection windows?

**Comment by kar-fai** [comment]
@sailes437 
Hi, did you manage to solve the 2 problems? I also facing the same issues when I train my own datasets.

**Comment by sailes437** [comment]
The solution to first problem is to write your custom sliding window generator and apply classification on each proposal window using cpp code given by caffe instead of python's detect.py. 
For the second problem, refer to the Non Maximum Supression Technique. If two windows have high overlap(check this using ratio of intersection over Union of window area) then merge them into single window and so on until all windows are processed. Another easier way is to use openCVGroupRectangle() function.

**Comment by mtrth** [comment]
@sailes437 
if possible could you share your code as I am also facing the same issues..

**Comment by sailes437** [comment]
No, sorry about it but I can't share my code. However I can guide you through theory of what I have done.

**Comment by catsdogone** [comment]
@sailes437 @shelhamer 
The detect.py demo works well when I used bvlc_reference_rcnn_ilsvrc13.caffemodel, while it failed when I used bvlc_reference_caffenet.caffemodel or GoogLeNet model, the classify result is wrong. 
Am I wrong?Thanks for your help.

I run the detect.py in this way:
./detect.py --crop_mode=selective_search --pretrained_model=/data/DIGITS-2.0/dataset/20150929-153608-64f5/snapshot_iter_200200.caffemodel --model_def=/data/DIGITS-2.0/dataset/20150929-153608-64f5/deploy2.prototxt --gpu --raw_scale=255 ../examples/_temp/det_input.txt ../examples/_temp/det_output_cat.h5
show the result in this way:
http://nbviewer.ipython.org/github/BVLC/caffe/blob/master/examples/detection.ipynb
