### ISSUE TITLE
training is freezing for multiple hours

### ISSUE THREAD

**Issue by tarik0005092** [BVLC/caffe#1412]
I am fine tuning the imagenet pretrained model using around 170k training images. After certain number of iterations of training ( e.g. 1600  - depends on the training set; last week it was getting stuck around iteration 2420 on a different dataset), it seems to freeze for 3/4 ( sometimes more ) hours without showing any diagnostic message for the freeze. Has anyone experienced this / Does anyone have the solution?

**Comment by bwang0** [comment]
If this is the same problem as #1377, try setting /proc/sys/vm/swappiness to zero. This solved our system freezes. See this very helpful answer from the main author of LMDB, http://www.openldap.org/lists/openldap-technical/201503/msg00077.html
