### ISSUE TITLE
caffe.io.resize_image generates nan if passed a constant image

### ISSUE THREAD

**Issue by cdoersch** [BVLC/caffe#1418]
If you pass an image that's all the same value to caffe.io.resize_image(), you get nan's.  It's due to [this line](https://github.com/BVLC/caffe/blob/c18d22eb92488f02c0256a3fe4ac20a8ad827596/python/caffe/io.py#L48) which divides by the difference between the min and max.  This is needed because skimage resize clips values outside the range [0,1]. A fix would involve just checking whether min and max are too close.

**Comment by shelhamer** [comment]
Fixed by #1662.
