### ISSUE TITLE
[still unsolved] "_regcompA", referenced from: testing::internal::RE::Init(char const*) in gtest-all.o

### ISSUE THREAD

**Issue by ghost** [BVLC/caffe#1421]
Hello,

Whilst "make all" finished successfully, in the testing stage "make test" I get the following error:

/usr/bin/clang++ src/caffe/test/test_caffe_main.cpp .build_release/src/caffe/test/test_accuracy_layer.o .build_release/src/caffe/test/test_argmax_layer.o .build_release/src/caffe/test/test_benchmark.o .build_release/src/caffe/test/test_blob.o .build_release/src/caffe/test/test_common.o .build_release/src/caffe/test/test_concat_layer.o .build_release/src/caffe/test/test_contrastive_loss_layer.o .build_release/src/caffe/test/test_convolution_layer.o .build_release/src/caffe/test/test_data_layer.o .build_release/src/caffe/test/test_dummy_data_layer.o .build_release/src/caffe/test/test_eltwise_layer.o .build_release/src/caffe/test/test_euclidean_loss_layer.o .build_release/src/caffe/test/test_filler.o .build_release/src/caffe/test/test_flatten_layer.o .build_release/src/caffe/test/test_gradient_based_solver.o .build_release/src/caffe/test/test_hdf5_output_layer.o .build_release/src/caffe/test/test_hdf5data_layer.o .build_release/src/caffe/test/test_hinge_loss_layer.o .build_release/src/caffe/test/test_im2col_layer.o .build_release/src/caffe/test/test_image_data_layer.o .build_release/src/caffe/test/test_infogain_loss_layer.o .build_release/src/caffe/test/test_inner_product_layer.o .build_release/src/caffe/test/test_internal_thread.o .build_release/src/caffe/test/test_lrn_layer.o .build_release/src/caffe/test/test_math_functions.o .build_release/src/caffe/test/test_maxpool_dropout_layers.o .build_release/src/caffe/test/test_memory_data_layer.o .build_release/src/caffe/test/test_multinomial_logistic_loss_layer.o .build_release/src/caffe/test/test_mvn_layer.o .build_release/src/caffe/test/test_net.o .build_release/src/caffe/test/test_neuron_layer.o .build_release/src/caffe/test/test_platform.o .build_release/src/caffe/test/test_pooling_layer.o .build_release/src/caffe/test/test_power_layer.o .build_release/src/caffe/test/test_protobuf.o .build_release/src/caffe/test/test_random_number_generator.o .build_release/src/caffe/test/test_sigmoid_cross_entropy_loss_layer.o .build_release/src/caffe/test/test_slice_layer.o .build_release/src/caffe/test/test_softmax_layer.o .build_release/src/caffe/test/test_softmax_with_loss_layer.o .build_release/src/caffe/test/test_solver.o .build_release/src/caffe/test/test_split_layer.o .build_release/src/caffe/test/test_stochastic_pooling.o .build_release/src/caffe/test/test_syncedmem.o .build_release/src/caffe/test/test_threshold_layer.o .build_release/src/caffe/test/test_upgrade_proto.o .build_release/src/caffe/test/test_util_blas.o .build_release/src/gtest/gtest-all.o .build_release/lib/libcaffe.a \
-o .build_release/test/test_all.testbin -stdlib=libstdc++ -fPIC -DNDEBUG -O2 -DCPU_ONLY -I/usr/local/Cellar/boost/1.55.0_2/include -I/usr/local/Cellar/boost/1.55.0_2/include/boost -I.build_release/src -I./src -I./include -I/usr/local/opt/openblas/include -Wall -Wno-sign-compare -Wno-unneeded-internal-declaration -L/Users/master/anaconda/lib -L/usr/local/lib -L/usr/lib -L/usr/local/Cellar/boost/1.55.0_2/lib -L/usr/local/opt/openblas/lib -lglog -lgflags -lprotobuf -lleveldb -lsnappy -llmdb -lboost_system -lhdf5_hl -lhdf5 -lopencv_core -lopencv_highgui -lopencv_imgproc -lpthread -lboost_thread-mt -lopenblas
Undefined symbols for architecture x86_64:
  "_regcompA", referenced from:
      testing::internal::RE::Init(char const_) in gtest-all.o
  "_regexecA", referenced from:
      testing::internal::DeathTestImpl::Passed(bool) in gtest-all.o
      testing::internal::RE::PartialMatch(char const_, testing::internal::RE const&) in gtest-all.o
      testing::internal::RE::FullMatch(char const_, testing::internal::RE const&) in gtest-all.o
  "_regfreeA", referenced from:
      testing::internal::RE::~RE() in gtest-all.o
      testing::internal::RE::~RE() in gtest-all.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *_\* [.build_release/test/test_all.testbin] Error 1

I tried "make clean" and then again "make all" and "make test" but the same error appears.

I am using boost 1.55 (downgraded from 1.56) on MAC OS 10.10 platform.
Any ideas/guidance ?

**Comment by blackCmd** [comment]
Have you found a solution? 
i got a solution right now ! 
if you want solution mail me

**Comment by lamctran** [comment]
blackcmd,. how did you fix the error?
