### ISSUE TITLE
[PyCaffe] `preprocess` method work properly??

### ISSUE THREAD

**Issue by everpeace** [BVLC/caffe#1423]
Hi, I am trying to run CIFAR-10 example and faced an issue on processing mean file.

Using `set_mean` method for processing mean values, I got about 33.04 % error.  However, when I subtracted mean values from input data manually, I got 16.89%.  I suspect that some bugs hide inside of `preprocess` methods...

I would be happy if somebody gave me some insights.

My codes used are below:
The case of using `set_mean`(some codes are omitted):
```{python}
MODEL_FILE = './cifar10/cifar10_full.prototxt'
PRETRAINED_WEIGHTS = './cifar10/cifar10_full_iter_70000.caffemodel'
MEAN_FILE = "./cifar10/mean.binaryproto"

net = caffe.Classifier(MODEL_FILE, PRETRAINED_WEIGHTS)
net.set_mode_gpu() 
assert net.inputs == ['data']
assert net.blobs['data'].data.shape == (1, 3, 32,32)
assert mean.shape == (3, 32, 32)

# set mean values on input layer ('data' layer)
net.set_mean('data', mean)

# subtract mean values by using preprocess method.
# It needs to convert (N, 3, 32, 32) => (N, 32, 32, 3) for passing preprocess method
# and preprocess method returns a matrix of (N, 3, 32, 32).
# It needs to convert (N, 3, 32, 32) => (N, 32, 32, 3) for passing predict method.
assert test_data.shape == (10000, 3, 32, 32)
input_data = np.array([ net.preprocess('data', x) for x in test_data.transpose(0,2,3,1)]).transpose(0,2,3,1)
assert input_data.shape == (10000, 32, 32, 3)

# This reports 33.04% prediction error on test data.
predictions_raw = net.predict(input_data)
```

The case of processing mean manually.
```{python}
net = caffe.Classifier(MODEL_FILE, PRETRAINED_WEIGHTS)
net.set_mode_gpu()

# subtract mean values manually
assert test_data.shape == (10000, 3, 32, 32)
assert mean.shape == (3, 32, 32)
input_data = np.array([d - mean for d in test_data]).transpose(0,2,3,1)
assert input_data.shape == (10000, 32, 32, 3)

# This report 16.89% prediction error on test data
predictions_raw = net.predict(input_data)
```

**Comment by shelhamer** [comment]
You have to be careful to match preprocess settings to the data layer settings. These problems will go away once #1245 is addressed.

**Comment by thesby** [comment]
Hi, everpeace, I have a question. Why can you use net.set_mode_gpu() ? I cannot use it, I can only use caffe.set_mode_gpu(). And it still uses cpu, not gpu.

**Comment by everpeace** [comment]
@thesby maybe, I think api has just been changed over time. I'm not sure, though.

**Comment by bentanust** [comment]
@thesby I have the same problem. I set caffe.set_mode_gpu(). I still work with cpu..
have you solved your problem?

**Comment by thesby** [comment]
@bentanust  You still suffered from this problem? The new version caffe solved the problem.
