### ISSUE TITLE
cuDNN v1 and other factors on CaffeNet convergence

### ISSUE THREAD

**Issue by yulingzhou** [BVLC/caffe#1429]
I trained the bvlc_reference_caffenet after executing create_imagenet.sh and compute_image_mean.cpp , and there is no error happened. But after 70000 iterations, the accuracy is still 0.001 and the loss keeps around 6.9. Why the training does not work?

**Comment by shelhamer** [comment]
This should be resolved, but when in doubt for reproducibility one might use the standard `CAFFE` engine to check a few iterations.
