### ISSUE TITLE
Recurrent Network Dynamics

### ISSUE THREAD

**Issue by ericjang** [BVLC/caffe#1439]
This is my suspicion right now, but I just wanted to make sure - currently caffe supports weight sharing for training purposes, but the forward pass cannot compute recurrently, like as in a dynamical system, right? For example, a basic RNN structure has weights from input(t) to hidden(t), weights from hidden(t) to hidden(t), and hidden(t-1) to hidden(t).

If not, are there current plans for implementing cyclic architectures in the network prototxts?

**Comment by shelhamer** [comment]
LSTM-style RNNs will be PR'd soon.
