### ISSUE TITLE
C++ Image Classification with memory_data_param

### ISSUE THREAD

**Issue by Zackory** [BVLC/caffe#1443]
Lately I've been attempting to classify images using C++. A few references have pointed to #499, however I have only been able to reproduce some of the results within that issue.

As it stands I am able to classify images with [predict.cpp](https://gist.github.com/Zackory/fc32b1876aadb3f9aca1) which uses `image_data_param` and a source list of images. Nonetheless, I am interested in classifying images using `memory_data_param` and thus not needing to rely on a saved image on disk. While this is certainly possible with Python, is this possible in C++?

**Comment by jayajadhav** [comment]
@Zackory 
Have you got the answer for how to use memory data layer for testing the model in real time with camera frames. I am unable to use memory data layer for image inputs. Please help me

**Comment by Dive-frank** [comment]
I'm use opencv load a caffe module :(http://docs.opencv.org/trunk/d5/de7/tutorial_dnn_googlenet.html)
is there anyone know how to deal with this problem?

main.cpp:13:23: error: variable or field ‘getMaxClass’ declared void
 void getMaxClass(dnn::Blob &probBlob, int *classId, double *classProb)  
                       ^
main.cpp:13:18: error: ‘Blob’ is not a member of ‘cv::dnn’
 void getMaxClass(dnn::Blob &probBlob, int *classId, double *classProb)
