### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by tjusxh** [BVLC/caffe#1447]
When I use my own lenet and my own data.It occur the question:
*** Aborted at 1416146147 (unix time) try "date -d @1416146147" if you are using GNU date ***
PC: @     0x7f99bf6179f0 (unknown)
*** SIGSEGV (@0x7e98dfffd700) received by PID 6586 (TID 0x7f99bf7c89c0) from PID 18446744073172670208; stack trace: ***
    @     0x7f99be35a340 (unknown)
    @     0x7f99bf6179f0 (unknown)
    @     0x7f99bf60fcd7 (unknown)
    @     0x7f99be352716 __pthread_create_2_1
    @     0x7f99b75c93b9 (unknown)
    @           0x514069 caffe::InternalThread::StartInternalThread()
    @           0x4d119e caffe::BasePrefetchingDataLayer<>::CreatePrefetchThread()
    @           0x479b5b caffe::Net<>::ForwardFromTo()
    @           0x479f87 caffe::Net<>::ForwardPrefilled()
    @           0x4a7a8f caffe::Solver<>::Solve()
    @           0x4164e2 train()
    @           0x4104f1 main
    @     0x7f99b6789ec5 (unknown)
    @           0x414f17 (unknown)
Segmentation fault

**Comment by shelhamer** [comment]
Check the data preparation and ask usage questions (https://groups.google.com/forum/#!forum/caffe-users) mailing list.
