### ISSUE TITLE
Error: 'CaffeNet' object has no attribute 'blobs'

### ISSUE THREAD

**Issue by ghost** [BVLC/caffe#145]
Hi

I was trying to run the selective_search_demo as given in the caffe website. I got the following error 

Traceback (most recent call last):
  File "../python/caffe/detection/detector.py", line 412, in <module>
    args.images_mean_file)
  File "../python/caffe/detection/detector.py", line 346, in config
    CROPPED_DIM = NET.blobs()[0].width
AttributeError: 'CaffeNet' object has no attribute 'blobs'

I am a beginner in python/c++. Can you please tell me what could be the reason for this

Thanks

**Comment by AllenYLJiang** [comment]
CaffeNet is a user-defined class, in the file defining it, you can find that it uses
self._net = caffe.Net(net_proto, net_weights, caffe.TEST)
input_shape = self._net.blobs['data'].data.shape
so you can use net._net.blobs['data'].data.shape
