### ISSUE TITLE
cifar10 and cifar100 preprocessing

### ISSUE THREAD

**Issue by hyungwonchoi** [BVLC/caffe#1454]
I am currently working on cifar10 and cifar100 classification using Network in Network caffe model.
(Thanks to https://gist.github.com/mavenlin/e56253735ef32c3c296d)

I want to preprocess the data myself, but having difficulties applying the method proposed in the maxout network paper. 

Is there any reference I can apply in caffe? not from the code in pylearn2? 
Since I am new to python, I am currently having difficulties changing the data into caffe format(leveldb or lmdb).

Thanks in advance.

**Comment by SpencerL** [comment]
Hello,  I'm sorry that I have no idea with your problem. I'm asking for your help.
 I wanted to test caffe on cifar10 dataset . To transform the data format to lmdb, I did just as the tutorial http://caffe.berkeleyvision.org/gathered/examples/cifar10.html
and I only get cifar10_train_lmdb , the error seems like as follow:
![error](https://cloud.githubusercontent.com/assets/7265041/7061995/484c620a-decb-11e4-8e53-07ae660148cb.png)
I'm new to caffe, and this issue bothered for a long time, and I didn't find resolution in internet,
May I have your help? 
Thank  you  anyway~

**Comment by shelhamer** [comment]
Please ask on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) group.

**Comment by guillaume-chevalier** [comment]
I made a [preprocessing of both cifar-10 and cifar-100 datasets to the HDF5 format supported by Caffe](https://github.com/guillaume-chevalier/caffe-cifar-10-and-cifar-100-datasets-preprocessed-to-HDF5).

If you want to have a better idea on how to use the preprocessed datasets in caffe, you can then check my [cifar-10](https://github.com/guillaume-chevalier/python-caffe-custom-cifar-10-conv-net) and [cifar-100](https://github.com/guillaume-chevalier/python-caffe-custom-cifar-100-conv-net) projects on my profile.
