### ISSUE TITLE
undefined reference to `boost::thread::start_thread_noexcept()' 

### ISSUE THREAD

**Issue by huxintong** [BVLC/caffe#1464]
I encountered this problem while installing the latest caffe. My OS is ubuntu 13.04 and I've installed all prerequisites including boost 1.55.
The error information shows:

../lib/libcaffe.a(internal_thread.cpp.o): In function `boost::thread::start_thread()':
internal_thread.cpp:(.text._ZN5boost6thread12start_threadEv[_ZN5boost6thread12start_threadEv]+0x15): undefined reference to`boost::thread::start_thread_noexcept()'
../lib/libcaffe.a(internal_thread.cpp.o): In function `boost::thread::join()':
internal_thread.cpp:(.text._ZN5boost6thread4joinEv[_ZN5boost6thread4joinEv]+0x6f): undefined reference to`boost::thread::join_noexcept()'
collect2: error: ld returned 1 exit status
make[2]: **\* [tools/caffe] Error 1
make[1]: **\* [tools/CMakeFiles/caffe.bin.dir/all] Error 2
make: **\* [all] Error 2

**Comment by bikong2** [comment]
any one who solved this problem?

**Comment by feng1o** [comment]
update  gcc.....
g++ xxxx.cpp    -lboost_system -lboost_thread，，，works

**Comment by mrgloom** [comment]
Same problem on `Ubuntu 12.04`, `gcc version 4.6.3 (Ubuntu/Linaro 4.6.3-1ubuntu5)`, `boost-1.54`.

**Comment by yin19961202** [comment]
@huxintong have you solved the problem?I met the same problem.THank you!

**Comment by dongzhens** [comment]
this problem comes from multiple boost lib installed,  I solve this problem by
 removing some files as 
sudo rm –r /usr/local/include/boost
sudo rm –r /usr/local/lib/libboost_*
