### ISSUE TITLE
Dot product layer

### ISSUE THREAD

**Issue by mcheshkov** [BVLC/caffe#1471]
I want to use dot product in network: given two bottom blobs NxKxWxH will produce one top blob Nx1x1x1, each of N will be dot product of appropriate KxWxH bottom pieces.
Is there a good way to do this with implemented layers? If not, is such layer appropriate?

**Comment by shelhamer** [comment]
Elementwise product by `Eltwise` layer then sum with `Reduction` layer is a substitute for a dedicated layer.
