### ISSUE TITLE
image data not found when training

### ISSUE THREAD

**Issue by Engin007** [BVLC/caffe#1476]
Hello guys,

I have written a net similar to that of LeNet that takes in image_data in its data layer and according to the documentation I should include a text file that states on each row the image file name and its label. However when I run the solver I get the following error message:

image_data_layer.cpp:30] Opening file
image_data_layer.cpp: 45] A total of 0 images
Segmentation fault

My text file is in the root folder with my Net alongside the 20 images I am trying to feed in. I tried many things including changing the format of the text file (i am using windows WordPad).

Naturally I inspected the image_data_layer.cpp file just to make sure all the prerequisits of my text files are met. I have seen no issue with that. My only concern is: I am working on a Windows 7 OS and I am using my unis computer to do the calculation. The latter has a Linux OS. could the problem be there ? (my programming background is very limited, therefore I can't really put my finger on the problem)

Thank you

**Comment by aharishkumar** [comment]
Can anyone help me with this error ?

I0830 11:16:13.044762 16727 convert_imageset.cpp:86] Shuffling data
I0830 11:16:13.190182 16727 convert_imageset.cpp:89] A total of 0 images.
I0830 11:16:13.190224 16727 convert_imageset.cpp:92] encode_type specified, assuming encoded=true.
I0830 11:16:13.190408 16727 db_lmdb.cpp:35] Opened lmdb lmdb

my text file includes the correct path to the images. I want to create a lmdb using convert_imageset built-in code.
