### ISSUE TITLE
Training stops at iteration 0 with  hdf5_classification net?

### ISSUE THREAD

**Issue by gungun1010** [BVLC/caffe#1488]
Hi There, 
    I am trying to supply my own data with the hdf5_classification sample net (train_val2.prototxt). 
    The training part seems to be able to complete, but when it does test, it simply stops at Iteration 0, Testing net (#0) with no warnings / errors. Does anyone might know whats going on?
    My data is HD5F with dimensions like (10000, 40, 1, 1), so it is thousands of 40 elements vectors, and each element is hashed into f64

The last couple lines of STDOUT is shown below:

1126 21:41:30.808037 20065 net.cpp:219] Network initialization done.
I1126 21:41:30.808043 20065 net.cpp:220] Memory required for data: 5048
I1126 21:41:30.808064 20065 solver.cpp:41] Solver scaffolding done.
I1126 21:41:30.808073 20065 solver.cpp:160] Solving Process Monitor
I1126 21:41:30.808086 20065 solver.cpp:247] Iteration 0, Testing net (#0)

**Comment by ZVERKA** [comment]
I am encountering the same problem, so any help would be much appreciated .

**Comment by gungun1010** [comment]
Hi.
   My problem was I had way too many classes so it just can't learn anything from it. Another case is that if u have only one class, it will stop as well
