### ISSUE TITLE
[bug report] extract_features.bin encountered a wrong answer

### ISSUE THREAD

**Issue by CCv5** [BVLC/caffe#1490]
Dir Sir,
       When I use the extract_features.bin to extract the layer 'prob' feature, the first 50 (this is my batch_size) results are correct which agreed with the webdemo result , But the others are wrong which are not consistent with the webdemo result using the same image.
     My validation process is as follows:
     I read the result from the leveldb and transform it to array form to get the argmax(array), then I use the index to get the correspond text in the 'data/ilsvrc12/synset_words.txt'
    the extracting script is here:
    ./build/tools/extract_features.bin models/bvlc_reference_caffenet/bvlc_reference_caffenet.caffemodel examples/_temp/imagenet_val.prototxt prob examples/_temp/features 2
    I wonder what rules the extract_features.bin is taken to store features in leveldb

Best Regards

**Comment by shelhamer** [comment]
The extract features example is likely going away in favor of using the Python and MATLAB interfaces or custom C++ code.
