### ISSUE TITLE
Error in ./build_docs.sh

### ISSUE THREAD

**Issue by erogol** [BVLC/caffe#1504]
As I run ./build_docs.sh I get following error:

usage: build.sh [port]
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': iconv will be deprecated in the future, use String#encode instead.
/usr/bin/jekyll:137:in `<main>': invalid option: -w (OptionParser::InvalidOption)

I am on Ubuntu 14.04 machine and I installed Jekyll with apt-get

**Comment by shelhamer** [comment]
This seems like an out-of-date ruby issue or some-such. This isn't a script error.
