### ISSUE TITLE
bug in make_imagenet_mean.sh

### ISSUE THREAD

**Issue by sunnyalien** [BVLC/caffe#1506]
When I run "make_imagenet_mean.sh", I get a error shown as below:

    F1201 16:04:40.272322  8199 compute_image_mean.cpp:57] Check failed:     mdb_env_open(mdb_env, argv[1], 0x20000, 0664) == 0 (2 vs. 0) mdb_env_open failed
    *** Check failure stack trace: ***
        @     0x7f5f58b5adaa  (unknown)
        @     0x7f5f58b5ace4  (unknown)
        @     0x7f5f58b5a6e6  (unknown)
        @     0x7f5f58b5d687  (unknown)
        @           0x409dcd  main
        @     0x7f5f55db0ec5  (unknown)
        @           0x40acb7  (unknown)
        @              (nil)  (unknown)
    Aborted (core dumped)

Then, I find that since the data generated by create_imagenet.sh are in lmdb format, the input in make_imagenet_mean should be changed to lmdb rather than leveldb.

original code in "make_imagenet_mean":

    ./build/tools/compute_image_mean examples/imagenet/ilsvrc12_train_leveldb \
      data/ilsvrc12/imagenet_mean.binaryproto

fixed:

    ./build/tools/compute_image_mean examples/imagenet/ilsvrc12_train_lmdb \
      data/ilsvrc12/imagenet_mean.binaryproto

It works after I fix the format of data.

**Comment by wqysq** [comment]
thank you very much ！

**Comment by Hzzone** [comment]
Solved my problem, thank you very much！
