### ISSUE TITLE
Fail to install with error "cannot find

### ISSUE THREAD

**Issue by Shaofanl** [BVLC/caffe#1508]
When I was compiling with "make all"
This error message occured:

> /usr/bin/ld: cannot find -lcblas
> /usr/bin/ld: cannot find -latlas
> collect2: error: ld returned 1 exit status
> make: **\* [.build_release/lib/libcaffe.so] error 1

Then I use "make all --debug" to look inside:

> File “all” doesn't exist
> File ".build_release/lib/libcaffe.so” doesn't exist

Anyone know how to fix it?

**Comment by linrio** [comment]
I meet the same problem.

_CXX src/caffe/util/signal_handler.cpp
CXX src/caffe/util/upgrade_proto.cpp
AR -o .build_release/lib/libcaffe.a
LD -o .build_release/lib/libcaffe.so.1.0.0-rc3
/bin/ld: cannot find -lcblas
/bin/ld: cannot find -latlas
collect2: error：ld returned 1
make: *** [.build_release/lib/libcaffe.so.1.0.0-rc3] error 1
[root@lingfeng caffe]# 
_

May I ask have you dealt with it?

**Comment by Chengcheng0709** [comment]
I ran this problem, too. Have you solved the problem?

**Comment by WanZhang1** [comment]
I ran this problem, too. Have you solved the problem?
LD -o .build_release/lib/libcaffe.so.1.0.0
/usr/bin/ld: cannot find -lcblas
/usr/bin/ld: cannot find -latlas
collect2: 错误：ld 返回 1
make: *** [.build_release/lib/libcaffe.so.1.0.0] 错误 1
