### ISSUE TITLE
make runtest failed

### ISSUE THREAD

**Issue by jamesguoxin** [BVLC/caffe#1509]
Today I copy the current dev branch and try to compile it with my previous makefile settings for master branch(works fine with master), but when I make runtest, I get check failed,

F1201 12:50:17.673465 2135225088 layer_factory.hpp:81] Check failed: registry.count(type) == 1 (0 vs. 1) 
**\* Check failure stack trace: ***
    @        0x1019bda6a  google::LogMessage::Fail()
    @        0x1019bcc88  google::LogMessage::SendToLog()
    @        0x1019bd6fa  google::LogMessage::Flush()
    @        0x1019c11e8  google::LogMessageFatal::~LogMessageFatal()
    @        0x1019bdf05  google::LogMessageFatal::~LogMessageFatal()
    @        0x1015bfcff  caffe::LayerRegistry<>::CreateLayer()
    @        0x1015ae19a  caffe::Net<>::Init()
    @        0x1015ad7bb  caffe::Net<>::Net()
    @        0x10142c6b4  caffe::NetTest<>::InitNetFromProtoString()
    @        0x10142d9f0  caffe::NetTest<>::InitReshapableNet()
    @        0x10142b98f  caffe::NetTest_TestReshape_Test<>::TestBody()
    @        0x10150e2cc  testing::internal::HandleExceptionsInMethodIfSupported<>()
    @        0x1014fe2ea  testing::Test::Run()
    @        0x1014ff232  testing::TestInfo::Run()
    @        0x1014ff900  testing::TestCase::Run()
    @        0x101504e15  testing::internal::UnitTestImpl::RunAllTests()
    @        0x10150ebb4  testing::internal::HandleExceptionsInMethodIfSupported<>()
    @        0x101504b39  testing::UnitTest::Run()
    @        0x1012688b5  main
    @     0x7fff8f9c45c9  start
    @                0x4  (unknown)
make: **\* [runtest] Abort trap: 6

I don't know why is it, anyone has any clue?
My system is Mac OSX Yosemite. Thank you very much!!

**Comment by maichm** [comment]
@jamesguoxin How to solved this problem,Thanks.
