### ISSUE TITLE
Access necessary information from Caffe to plot ROC curve

### ISSUE THREAD

**Issue by Engin007** [BVLC/caffe#1520]
Hello Caffe Community,

I would like to know how I can access information needed i.e FP, TP, TN , FN to build a confusion matrix and eventually be able to use this info to plot an ROC curve. So basically I would like to  know if there exists a function/layer that would help me give an output I can use. I have already read the layer catalogue but I am not sure which one would give out the classification results. 
(c++)

Thank you

**Comment by shivangpatel** [comment]
After this changes, How to show ROC? recompilation of caffe or  write new layer ?
