### ISSUE TITLE
Converting npy mean file to binaryproto file

### ISSUE THREAD

**Issue by erogol** [BVLC/caffe#1526]
I don't see any function, at least a direct one, that converts given npy file to binaryproto. I implemented this in the following way. Does it seem okay or do you suggest anything?

DATA_MEAN has shape Channel x Height x Width

blob = caffe.proto.caffe_pb2.BlobProto()
blob.channels, blob.height, blob.width = DATA_MEAN.shape
blob.data.extend(DATA_MEAN.astype(float).flat)
binaryproto_file = open(PROJECT_FOLDER+'/data/mango_data_mean.binaryproto', 'wb' )
binaryproto_file.write(blob.SerializeToString())
binaryproto_file.close()

**Comment by shelhamer** [comment]
This is fine, but see https://github.com/BVLC/caffe/blob/master/python/caffe/io.py#L113-L125
