### ISSUE TITLE
Compress the training data with Google Snappy for higher IO throughput

### ISSUE THREAD

**Issue by futurely** [BVLC/caffe#1533]
When [computation is faster than data IO](https://github.com/BVLC/caffe/pull/1148), the device utitlization  is reduced. To reduce the throughput gap, the data is usually compressed in many distributed computation or storage framework such as [Hadoop](https://www.ibm.com/developerworks/community/wikis/home?lang=en#!/wiki/W265aa64a4f21_43ee_b236_c42a1c875961/page/Hadoop%20compression%20formats), [HBase](http://blog.erdemagaoglu.com/post/4605524309/lzo-vs-snappy-vs-lzf-vs-zlib-a-comparison-of), [Hive](http://hortonworks.com/blog/orcfile-in-hdp-2-better-compression-better-performance/) and [Kafka](http://nehanarkhede.com/2013/03/28/compression-in-kafka-gzip-or-snappy/). Among many compressing libraries available for this purpose, [Google Snappy](https://github.com/google/snappy) is a very widely used one. It supports [many languages](https://code.google.com/p/snappy/) and strikes a [good balance between compression ratio and speed](https://github.com/ning/jvm-compressor-benchmark/wiki#results).

**Comment by shelhamer** [comment]
Closing as not a grievous bottleneck in many cases, and b.c. this can be handled by specialized layers relevant to the given use case that don't necessarily have general relevance.
