### ISSUE TITLE
Improve data prefeteching efficiency

### ISSUE THREAD

**Issue by futurely** [BVLC/caffe#1535]
Current implementation prefetch only a single batch after the last batch was used for computations. The initial motivation for this design is probably to avoid thread synchronization. There may not be maximal overlap between computation and data IO. This problem becomes a serious bottleneck when multiple devices simultaneously train the data (#1148). 

The IO efficiency can be increased by continuously prefetching multiple batches without waiting for the computation thread and storing them in a [thread safe buffer with limited capacity](http://www.threadingbuildingblocks.org/docs/help/reference/containers_overview/concurrent_bounded_queue_cls.htm).

**Comment by shelhamer** [comment]
Solved by #2366 #2367 #2368 #2383 #2386 soon to be merged as part of #2114. The persistent prefetch thread and data reader avoid overhead and can fetch multiple batches.
