### ISSUE TITLE
In CPU mode, using multi-core is much slower than using a single core

### ISSUE THREAD

**Issue by RenfengLiu** [BVLC/caffe#1539]
We have no GUP machine, so could only use CPU. We use OPENBLAS and set OMP_NUM_THREADS = 16, which is the number of cores in the machine, and run example "./examples/mnist/train_lenet.sh " and it takes 1065 seconds to run, but if we set the OMP_NUM_THREADS = 1, the running time is 651 seconds. 
The environment is Ubuntu linux 14.04 on a 64 bit machine with 16 cores  CPU and 64G memory.

**Comment by shwetgarg** [comment]
Does this work for apollocaffe models also. I have tried @borisgin suggestions. But it seems it is still using only 1 core.

**Comment by shwetgarg** [comment]
Hey, I have followed following steps for apollocaffe fork of caffe:
1. set BLAS := open
2. make -j8 USE_OPENMP=1 (make apollocaffe)

After this when I am training my model, looking into htop gives me a feeling that it is using all 8 cores available of cpu. But surprisingly my training time has increased (rather than decreasing). Following are exact nos:
with BLAS:=atlas, 1133.01528096 seconds
with BLAS:=open and USE_OPENMP=1,  1217.153198 seconds

Does anyone has any idea on this.

**Comment by soulslicer** [comment]
I have a different situation..

I compiled the intel branch with MKL. Its about 10 times faster than the normal CPU master branch version. However, changing the number of openmp threads has no effect on the runtime. Why is this the case

**Comment by ateymour** [comment]
Im having the same issue as @soulslicer.
Im using MKL with OPENMP enabled.
Increasing threads using OMP_NUM_THREADS does nothing. Increasing threads using MKL_NUM_THREADS decreases performance.

**Comment by soulslicer** [comment]
I have found that reducing the net resolution makes it observable. At a higher resolution, the effect of threads is moot

**Comment by naibaf7** [comment]
Has anyone actually run a profiler to see what the threads actually do??

**Comment by ateymour** [comment]
I used ```mpstat``` to monitor the threads while running. When using MKL_NUM_THREADS, all cores are being utilized but if I had to guess it seems like the overhead drops the performance.
When using OMP_NUM_THREADS it continues to run on 1 core at a time, which explains the performance not changing.

**Comment by naibaf7** [comment]
It has to be noted no layers in standard Caffe are parallelized for CPU, only GPU.
The only CPU parallelization you can get out of standard Caffe is with a parallelized BLAS. That could be part of the issue. And there, not every GEMM/GEMV operation profits equally from parallelization.

One way to get all layers parallel on the CPU is to use OpenCL Caffe using POCL as a backend. In that case, GEMM/GEMV will still be executed by a normal CPU BLAS (Open or MKL). YMMV on the speedups though.

**Comment by vishalkumarchaudhary** [comment]
```
sudo apt-get install -y libopenblas-dev
```
Before compiling Caffe, edit Makefile.config, replace ```BLAS := atlas``` by ```BLAS := open```

```
export OPENBLAS_NUM_THREADS=8
````
