### ISSUE TITLE
When I run python classifier.py, I get the error

### ISSUE THREAD

**Issue by coder-Xi** [BVLC/caffe#1542]
/PythonModule/lib/python2.7/site-packages/scikit_image-0.11dev-py2.7-linux-x86_64.egg/skimage/io/_io.py", line 1, in <module>
    from io import BytesIO
ImportError: cannot import name BytesIO

**Comment by digitalimagep** [comment]
When I run the classifier.py, I got this error:
    in_ = self.inputs[0]
IndexError: list index out of range
what's wrong?help!

**Comment by seanbell** [comment]
@digitalimagep it looks like you're possibly missing the inputs from the top of the network?  When making a deploy network you need to specify the input shapes.  Also, the issues page is not the right place to ask these kinds of questions.

From https://raw.githubusercontent.com/BVLC/caffe/master/CONTRIBUTING.md:
>_Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
> Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

**Comment by digitalimagep** [comment]
I see. Thank you for your help.

At 2015-12-17 19:09:05, "Sean Bell" <notifications@github.com> wrote:


@digitalimagep it looks like you're possibly missing the inputs from the top of the network? When making a deploy network you need to specify the input shapes. Also, the issues page is not the right place to ask these kinds of questions.

From https://raw.githubusercontent.com/BVLC/caffe/master/CONTRIBUTING.md:

Please do not post usage, installation, or modeling questions, or other requests for help to Issues.
Use the caffe-users list instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
