### ISSUE TITLE
Caffe not running multicore when built on a CentOS VM

### ISSUE THREAD

**Issue by deepusenan** [BVLC/caffe#1554]
I have built caffe on a CentOS VM with openBLAS...   I tried running the MNIST example that is present in the toolkit..  It seems only one core of the CPU is getting utilized.   Was it not supposed to use multiple cores?   

Please help. 
Thanks

**Comment by shelhamer** [comment]
How to configure your BLAS is out of scope -- read your BLAS documentation.
