### ISSUE TITLE
installing with cuDNN R2 on OS X 10.10

### ISSUE THREAD

**Issue by ericqh** [BVLC/caffe#1556]
Hello guys,

I was compiling caffe under OS X 10.10, and encounter some error when doing "make all". The solution in https://groups.google.com/forum/#!msg/caffe-users/rXjBlzWkA8c/kEKGeiqZhBAJ    is NOT working. 

Any ideas on how fix it? Thanks a lot. 

Undefined symbols for architecture x86_64:
  "google::protobuf::MessageLite::ParseFromString(std::string const&)", referenced from:
      caffe::DataLayer<float>::DataLayerSetUp(std::vector<caffe::Blob<float>*, std::allocator<caffe::Blob<float>*> > const&, std::vector<caffe::Blob<float>*, std::allocator<caffe::Blob<float>*> >*) in data_layer.o
      caffe::DataLayer<float>::InternalThreadEntry() in data_layer.o
      caffe::DataLayer<double>::DataLayerSetUp(std::vector<caffe::Blob<double>*, std::allocator<caffe::Blob<double>*> > const&, std::vector<caffe::Blob<double>*, std::allocator<caffe::Blob<double>*> >*) in data_layer.o
      caffe::DataLayer<double>::InternalThreadEntry() in data_layer.o
      caffe::Net<float>::Forward(std::string const&, float*) in net.o
      caffe::Net<double>::Forward(std::string const&, double*) in net.o
  "google::protobuf::MessageFactory::InternalRegisterGeneratedFile(char const*, void (*)(std::string const&))", referenced from:
      caffe::protobuf_AddDesc_caffe_2eproto() in caffe.pb.o
      caffe::protobuf_AddDesc_caffe_5fpretty_5fprint_2eproto() in caffe_pretty_print.pb.o
  "google::protobuf::io::CodedOutputStream::WriteStringWithSizeToArray(std::string const&, unsigned char*)", referenced from:
      caffe::Datum::SerializeWithCachedSizesToArray(unsigned char*) const in caffe.pb.o
      caffe::FillerParameter::SerializeWithCachedSizesToArray(unsigned char*) const in caffe.pb.o
      caffe::NetParameter::SerializeWithCachedSizesToArray(unsigned char*) const in caffe.pb.o
      caffe::SolverParameter::SerializeWithCachedSizesToArray(unsigned char*) const in caffe.pb.o
      caffe::SolverState::SerializeWithCachedSizesToArray(unsigned char*) const in caffe.pb.o
      caffe::NetState::SerializeWithCachedSizesToArray(unsigned char*) const in caffe.pb.o
      caffe::NetStateRule::SerializeWithCachedSizesToArray(unsigned char*) const in caffe.pb.o
      ...
  "google::protobuf::internal::WireFormatLite::ReadString(google::protobuf::io::CodedInputStream*, std::string*)", referenced from:
      caffe::FillerParameter::MergePartialFromCodedStream(google::protobuf::io::CodedInputStream*) in caffe.pb.o
      caffe::NetParameter::MergePartialFromCodedStream(google::protobuf::io::CodedInputStream*) in caffe.pb.o
      caffe::SolverParameter::MergePartialFromCodedStream(google::protobuf::io::CodedInputStream*) in caffe.pb.o
      caffe::SolverState::MergePartialFromCodedStream(google::protobuf::io::CodedInputStream*) in caffe.pb.o
      caffe::NetState::MergePartialFromCodedStream(google::protobuf::io::CodedInputStream*) in caffe.pb.o
      caffe::NetStateRule::MergePartialFromCodedStream(google::protobuf::io::CodedInputStream*) in caffe.pb.o
      caffe::LayerParameter::MergePartialFromCodedStream(google::protobuf::io::CodedInputStream*) in caffe.pb.o
      ...
  "google::protobuf::internal::WireFormatLite::WriteString(int, std::string const&, google::protobuf::io::CodedOutputStream*)", referenced from:
      caffe::NetParameter::SerializeWithCachedSizes(google::protobuf::io::CodedOutputStream*) const in caffe.pb.o
      caffe::SolverParameter::SerializeWithCachedSizes(google::protobuf::io::CodedOutputStream*) const in caffe.pb.o
      caffe::NetState::SerializeWithCachedSizes(google::protobuf::io::CodedOutputStream*) const in caffe.pb.o
      caffe::NetStateRule::SerializeWithCachedSizes(google::protobuf::io::CodedOutputStream*) const in caffe.pb.o
      caffe::LayerParameter::SerializeWithCachedSizes(google::protobuf::io::CodedOutputStream*) const in caffe.pb.o
      caffe::NetParameterPrettyPrint::SerializeWithCachedSizes(google::protobuf::io::CodedOutputStream*) const in caffe_pretty_print.pb.o
  "google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(int, std::string const&, google::protobuf::io::CodedOutputStream*)", referenced from:
      caffe::Datum::SerializeWithCachedSizes(google::protobuf::io::CodedOutputStream*) const in caffe.pb.o
  "google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(int, std::string const&, google::protobuf::io::CodedOutputStream*)", referenced from:
      caffe::FillerParameter::SerializeWithCachedSizes(google::protobuf::io::CodedOutputStream*) const in caffe.pb.o
      caffe::NetParameter::SerializeWithCachedSizes(google::protobuf::io::CodedOutputStream*) const in caffe.pb.o
      caffe::SolverParameter::SerializeWithCachedSizes(google::protobuf::io::CodedOutputStream*) const in caffe.pb.o
      caffe::SolverState::SerializeWithCachedSizes(google::protobuf::io::CodedOutputStream*) const in caffe.pb.o
      caffe::LayerParameter::SerializeWithCachedSizes(google::protobuf::io::CodedOutputStream*) const in caffe.pb.o
      caffe::TransformationParameter::SerializeWithCachedSizes(google::protobuf::io::CodedOutputStream*) const in caffe.pb.o
      caffe::DataParameter::SerializeWithCachedSizes(google::protobuf::io::CodedOutputStream*) const in caffe.pb.o
      ...
  "google::protobuf::internal::WireFormatLite::ReadBytes(google::protobuf::io::CodedInputStream*, std::string*)", referenced from:
      caffe::Datum::MergePartialFromCodedStream(google::protobuf::io::CodedInputStream*) in caffe.pb.o
  "google::protobuf::internal::StringTypeHandlerBase::Delete(std::string*)", referenced from:
      caffe::NetParameter::NetParameter() in caffe.pb.o
      caffe::NetParameter::NetParameter(caffe::NetParameter const&) in caffe.pb.o
      caffe::NetParameter::~NetParameter() in caffe.pb.o
      caffe::SolverParameter::SolverParameter() in caffe.pb.o
      caffe::SolverParameter::SolverParameter(caffe::SolverParameter const&) in caffe.pb.o
      caffe::SolverParameter::~SolverParameter() in caffe.pb.o
      caffe::NetState::NetState() in caffe.pb.o
      ...
  "google::protobuf::MessageLite::SerializeToString(std::string*) const", referenced from:
      caffe::Net<float>::Forward(std::string const&, float*) in net.o
      caffe::Net<double>::Forward(std::string const&, double*) in net.o
  "google::protobuf::DescriptorPool::FindFileByName(std::string const&) const", referenced from:
      caffe::protobuf_AssignDesc_caffe_2eproto() in caffe.pb.o
      caffe::protobuf_AssignDesc_caffe_5fpretty_5fprint_2eproto() in caffe_pretty_print.pb.o
  "google::protobuf::Message::SerializeToOstream(std::ostream*) const", referenced from:
      caffe::WriteProtoToBinaryFile(google::protobuf::Message const&, char const*) in io.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [.build_release/lib/libcaffe.so] Error 1

**Comment by sseltser** [comment]
same prob. which library orders did you change?

**Comment by pallabdatta** [comment]
I have the exact same problem in OS X 10.10. When I do $protoc --version
it comes to -- libprotoc 2.6.1
How do you resolve the above problem?! Can you please let me know ASAP. thanks a lot.

**Comment by pallabdatta** [comment]
Looks like if I comment out  USE_CUDNN 
# cuDNN acceleration switch (uncomment to build with cuDNN).
# USE_CUDNN := 1

I can run make all; make test etc. But as soon as I turn on USE_CUDNN it fails when I run make all with the following:

$ make all
/usr/bin/clang++ tools/caffe.cpp -stdlib=libstdc++ -pthread -fPIC -DNDEBUG -O2 -DUSE_CUDNN -I/Users/pallabdatta/anaconda/include -I/Users/pallabdatta/anaconda/include/python2.7 -I/Users/pallabdatta/anaconda/lib/python2.7/site-packages/numpy/core/include -I/usr/local/include -I.build_release/src -I./src -I./include -I/usr/local/cuda/include -I/Users/pallabdatta/openBLAS -Wall -Wno-sign-compare -Wno-unneeded-internal-declaration -c -o .build_release/tools/caffe.o 2> .build_release/tools/caffe.o.warnings.txt \
		|| (cat .build_release/tools/caffe.o.warnings.txt; exit 1)
In file included from tools/caffe.cpp:8:
In file included from ./include/caffe/caffe.hpp:7:
In file included from ./include/caffe/blob.hpp:4:
In file included from ./include/caffe/common.hpp:18:
In file included from ./include/caffe/util/device_alternate.hpp:40:
./include/caffe/util/cudnn.hpp:59:32: error: unknown type name 'cudnnTensor4dDescriptor_t'; did you mean 'cudnnTensorDescriptor_t'?
inline void createTensor4dDesc(cudnnTensor4dDescriptor_t* desc) {
                               ^~~~~~~~~~~~~~~~~~~~~~~~~
                               cudnnTensorDescriptor_t
/usr/local/cuda/include/cudnn.h:107:42: note: 'cudnnTensorDescriptor_t' declared here
typedef struct cudnnTensorStruct*        cudnnTensorDescriptor_t;
                                         ^
In file included from tools/caffe.cpp:8:
In file included from ./include/caffe/caffe.hpp:7:
In file included from ./include/caffe/blob.hpp:4:
In file included from ./include/caffe/common.hpp:18:
In file included from ./include/caffe/util/device_alternate.hpp:40:
./include/caffe/util/cudnn.hpp:60:15: error: use of undeclared identifier 'cudnnCreateTensor4dDescriptor'; did you mean 'cudnnCreateTensorDescriptor'?
  CUDNN_CHECK(cudnnCreateTensor4dDescriptor(desc));
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
              cudnnCreateTensorDescriptor
./include/caffe/util/cudnn.hpp:11:28: note: expanded from macro 'CUDNN_CHECK'
    cudnnStatus_t status = condition; \
                           ^
/usr/local/cuda/include/cudnn.h:122:27: note: 'cudnnCreateTensorDescriptor' declared here
cudnnStatus_t CUDNNWINAPI cudnnCreateTensorDescriptor( cudnnTensorDescriptor_t   *tensorDesc );
                          ^
In file included from tools/caffe.cpp:8:
In file included from ./include/caffe/caffe.hpp:7:
In file included from ./include/caffe/blob.hpp:4:
In file included from ./include/caffe/common.hpp:18:
In file included from ./include/caffe/util/device_alternate.hpp:40:
./include/caffe/util/cudnn.hpp:64:29: error: unknown type name 'cudnnTensor4dDescriptor_t'; did you mean 'cudnnTensorDescriptor_t'?
inline void setTensor4dDesc(cudnnTensor4dDescriptor_t* desc,
                            ^~~~~~~~~~~~~~~~~~~~~~~~~
                            cudnnTensorDescriptor_t
/usr/local/cuda/include/cudnn.h:107:42: note: 'cudnnTensorDescriptor_t' declared here
typedef struct cudnnTensorStruct*        cudnnTensorDescriptor_t;
                                         ^
In file included from tools/caffe.cpp:8:
In file included from ./include/caffe/caffe.hpp:7:
In file included from ./include/caffe/blob.hpp:4:
In file included from ./include/caffe/common.hpp:18:
In file included from ./include/caffe/util/device_alternate.hpp:40:
./include/caffe/util/cudnn.hpp:72:29: error: unknown type name 'cudnnTensor4dDescriptor_t'; did you mean 'cudnnTensorDescriptor_t'?
inline void setTensor4dDesc(cudnnTensor4dDescriptor_t* desc,
                            ^~~~~~~~~~~~~~~~~~~~~~~~~
                            cudnnTensorDescriptor_t
/usr/local/cuda/include/cudnn.h:107:42: note: 'cudnnTensorDescriptor_t' declared here
typedef struct cudnnTensorStruct*        cudnnTensorDescriptor_t;
                                         ^
In file included from tools/caffe.cpp:8:
In file included from ./include/caffe/caffe.hpp:7:
In file included from ./include/caffe/blob.hpp:4:
In file included from ./include/caffe/common.hpp:18:
In file included from ./include/caffe/util/device_alternate.hpp:40:
./include/caffe/util/cudnn.hpp:97:5: error: unknown type name 'cudnnTensor4dDescriptor_t'; did you mean 'cudnnTensorDescriptor_t'?
    cudnnTensor4dDescriptor_t bottom, cudnnFilterDescriptor_t filter,
    ^~~~~~~~~~~~~~~~~~~~~~~~~
    cudnnTensorDescriptor_t
/usr/local/cuda/include/cudnn.h:107:42: note: 'cudnnTensorDescriptor_t' declared here
typedef struct cudnnTensorStruct*        cudnnTensorDescriptor_t;
                                         ^
In file included from tools/caffe.cpp:8:
In file included from ./include/caffe/caffe.hpp:7:
In file included from ./include/caffe/blob.hpp:4:
In file included from ./include/caffe/common.hpp:18:
In file included from ./include/caffe/util/device_alternate.hpp:40:
./include/caffe/util/cudnn.hpp:99:15: error: use of undeclared identifier 'cudnnSetConvolutionDescriptor'
  CUDNN_CHECK(cudnnSetConvolutionDescriptor(*conv, bottom, filter,
              ^
./include/caffe/util/cudnn.hpp:11:28: note: expanded from macro 'CUDNN_CHECK'
    cudnnStatus_t status = condition; \
                           ^
./include/caffe/util/cudnn.hpp:118:15: error: use of undeclared identifier 'cudnnSetPoolingDescriptor'; did you mean 'cudnnSetPoolingNdDescriptor'?
  CUDNN_CHECK(cudnnSetPoolingDescriptor(*conv, *mode, h, w,
              ^~~~~~~~~~~~~~~~~~~~~~~~~
              cudnnSetPoolingNdDescriptor
./include/caffe/util/cudnn.hpp:11:28: note: expanded from macro 'CUDNN_CHECK'
    cudnnStatus_t status = condition; \
                           ^
/usr/local/cuda/include/cudnn.h:545:27: note: 'cudnnSetPoolingNdDescriptor' declared here
cudnnStatus_t CUDNNWINAPI cudnnSetPoolingNdDescriptor(  cudnnPoolingDescriptor_t poolingDesc,
                          ^
In file included from tools/caffe.cpp:8:
In file included from ./include/caffe/caffe.hpp:7:
In file included from ./include/caffe/blob.hpp:4:
In file included from ./include/caffe/common.hpp:18:
In file included from ./include/caffe/util/device_alternate.hpp:40:
./include/caffe/util/cudnn.hpp:118:58: error: cannot initialize a parameter of type 'const int *' with an lvalue of type 'int'
  CUDNN_CHECK(cudnnSetPoolingDescriptor(*conv, *mode, h, w,
                                                         ^
./include/caffe/util/cudnn.hpp:11:28: note: expanded from macro 'CUDNN_CHECK'
    cudnnStatus_t status = condition; \
                           ^
/usr/local/cuda/include/cudnn.h:548:67: note: passing argument to parameter 'windowDimA' here
                                                        const int windowDimA[],
                                                                  ^
In file included from tools/caffe.cpp:8:
In file included from ./include/caffe/caffe.hpp:16:
In file included from ./include/caffe/vision_layers.hpp:10:
In file included from ./include/caffe/common_layers.hpp:12:
In file included from ./include/caffe/loss_layers.hpp:11:
./include/caffe/neuron_layers.hpp:383:3: error: unknown type name 'cudnnTensor4dDescriptor_t'; did you mean 'cudnnTensorDescriptor_t'?
  cudnnTensor4dDescriptor_t bottom_desc_;
  ^~~~~~~~~~~~~~~~~~~~~~~~~
  cudnnTensorDescriptor_t
/usr/local/cuda/include/cudnn.h:107:42: note: 'cudnnTensorDescriptor_t' declared here
typedef struct cudnnTensorStruct*        cudnnTensorDescriptor_t;
                                         ^
In file included from tools/caffe.cpp:8:
In file included from ./include/caffe/caffe.hpp:16:
In file included from ./include/caffe/vision_layers.hpp:10:
In file included from ./include/caffe/common_layers.hpp:12:
In file included from ./include/caffe/loss_layers.hpp:11:
./include/caffe/neuron_layers.hpp:384:3: error: unknown type name 'cudnnTensor4dDescriptor_t'; did you mean 'cudnnTensorDescriptor_t'?
  cudnnTensor4dDescriptor_t top_desc_;
  ^~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by lou-k** [comment]
I'm seeing the same issue with cuda.
Versions:
Cuda: `cudnn-6.5-osx-R2-rc1`
OSX: `10.10.1`
Caffe: revision `7e465f2`, branch `master`

**Comment by yogaliew** [comment]
same prob. Does anyone work it out?

**Comment by shelhamer** [comment]
#1731 is an in-progress branch for cuDNN R2 support. At the moment Caffe only supports the stable cuDNN R1, which does not support OS X.

Note that the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) mailing list is the right place to discuss installation.

**Comment by lou-k** [comment]
@shelhamer  thank you very much!

**Comment by shelhamer** [comment]
The general compilation issue is solved by #1740 while #1739 has a full patch for cuDNN R2 compatibility.Yosemite support will be in the next release while cuDNN R2 is currently planned to stay a pull request while the release candidates are validated.
