### ISSUE TITLE
libopencv_highgui.so:undefined reference to `TIFFIsTiled@LIBTIFF_4.0'

### ISSUE THREAD

**Issue by luyifan** [BVLC/caffe#1559]
Today I use caffe and use the command make all
And then It have some errors.
The errors are as follow:g++ .build_debug/tools/compute_image_mean.o .build_debug/lib/libcaffe.a -o .build_debug/tools/compute_image_mean.bin -fPIC -DDEBUG -g -O0 -I/root/anaconda/include -I/root/anaconda/include/python2.7 -I/root/anaconda/lib/python2.7/site-packages/numpy/core/include -I/usr/local/include -I.build_debug/src -I./src -I./include -I/usr/local/cuda/include -Wall -Wno-sign-compare -L/root/anaconda/lib -L/usr/local/lib -L/usr/lib -L/usr/local/cuda/lib64 -L/usr/local/cuda/lib -lcudart -lcublas -lcurand -lglog -lgflags -lprotobuf -lleveldb -lsnappy -llmdb -lboost_system -lhdf5_hl -lhdf5 -lopencv_core -lopencv_highgui -lopencv_imgproc -lpthread -lboost_thread -lcblas -latlas
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libopencv_highgui.so: undefined reference to `TIFFIsTiled@LIBTIFF_4.0'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libopencv_highgui.so: undefined reference to `TIFFOpen@LIBTIFF_4.0'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libopencv_highgui.so: undefined reference to `TIFFReadEncodedStrip@LIBTIFF_4.0'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libopencv_highgui.so: undefined reference to `TIFFSetField@LIBTIFF_4.0'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libopencv_highgui.so: undefined reference to `TIFFWriteScanline@LIBTIFF_4.0'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libopencv_highgui.so: undefined reference to `TIFFGetField@LIBTIFF_4.0'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libopencv_highgui.so: undefined reference to `TIFFScanlineSize@LIBTIFF_4.0'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libopencv_highgui.so: undefined reference to `TIFFSetWarningHandler@LIBTIFF_4.0'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libopencv_highgui.so: undefined reference to `TIFFSetErrorHandler@LIBTIFF_4.0'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libopencv_highgui.so: undefined reference to `TIFFReadEncodedTile@LIBTIFF_4.0'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libopencv_highgui.so: undefined reference to `TIFFReadRGBATile@LIBTIFF_4.0'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libopencv_highgui.so: undefined reference to `TIFFClose@LIBTIFF_4.0'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libopencv_highgui.so: undefined reference to `TIFFRGBAImageOK@LIBTIFF_4.0'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libopencv_highgui.so: undefined reference to `TIFFReadRGBAStrip@LIBTIFF_4.0'
collect2: error: ld returned 1 exit status
make: *** [.build_debug/tools/compute_image_mean.bin] Error 1

I use the ubuntu 14.04 LTS Desktop 
and nvidia qudaro K4000

And I don't know how to solve this problem,
Could someone help me? Thanks a lot !!!

**Comment by rndmania** [comment]
if you install libopencv using apt, install libtiff4 such as 
sudo apt-get install libtiff4-dev

**Comment by luyifan** [comment]
@rndmania thx, It solved my problem and I try another way by install opencv not by apt-get

**Comment by ih4cku** [comment]
Should it be the newer one `libtiff5-dev`? @rndmania

**Comment by mrgloom** [comment]
Can you explain the source of this problem? Opencv conflict with TIFF library or something else?

**Comment by Lakung** [comment]
how did you solve this problem?@luyifan , cause i just met this issue.

**Comment by empty16** [comment]
@Lakung , here is the solution:   http://www.voidcn.com/blog/cfyzcc/article/p-6253725.html

**Comment by rohitrawat** [comment]
@Lakung, on Ubuntu 16.04, libtiff has moved to libtiff5 which gets installed with libopencv-dev, but caffe fails to compile with it producing the linker errors in the original post. You will have to remove libtiff5 (which would also remove libopencv due to a dependency), install libtiff4, then reinstall libopencv, then rebuild caffe. Here is how I did it:
```bash
# remove libtiff5 (also removes libopencv-* as a side effect)
sudo apt-get remove libtiff5-dev
# get libtiff4 and dependencies from archives
wget http://security.ubuntu.com/ubuntu/pool/main/t/tiff/libtiff4-dev_3.9.5-2ubuntu1.9_amd64.deb
wget http://security.ubuntu.com/ubuntu/pool/main/t/tiff/libtiff4_3.9.5-2ubuntu1.9_amd64.deb
wget http://security.ubuntu.com/ubuntu/pool/main/t/tiff/libtiffxx0c2_3.9.5-2ubuntu1.9_amd64.deb
sudo dpkg -i libtiff*.deb
# reinstall opencv
sudo apt-get install libopencv-dev
#rebuild caffe
make clean
make all
make test
```

**Comment by juiceboxjoe** [comment]
conda uninstall libtiff worked for me

**Comment by TonyMou** [comment]
conda uninstall libtiff worked for me too.

**Comment by smallflyingpig** [comment]
@juiceboxjoe good idea! it works for me. But why it it the problem of conda?

**Comment by abelguima** [comment]
I have a solution from here: https://github.com/lagadic/visp/issues/109

These errors may appear after installation of anaconda.

If you follow the default anaconda installation, you can see that anaconda has a set of libraries in ~/anaconda3/lib like libtiff.so, libjpeg.so, libxml2.so ... that are also installed in /usr/lib but with other versions. The result is that the corresponding system libraries in /usr/lib/x86_64-linux-gnu may be hidden by files in ~/anaconda3/lib.

The solution I found to be able to build caffe with OpenCV is to remove anaconda3/bin folder from PATH.


< export PATH="/home/user/anaconda3/bin:$PATH"
editing ~/.bashrc and commenting

#export PATH="/home/user/anaconda3/bin:$PATH"

Then do a fresh build

at caffe directory

rm -r build
mkdir build
cd build
cmake ..
make all
make install
make runtest

**Comment by shizukanaskytree** [comment]
`conda uninstall libtiff` works!

**Comment by suiwei** [comment]
I solve this porblem by add sudo 
sudo su；
make all -j16；
make test -j16；
make runtest -j16；
make pycaffe；

**Comment by cc786537662** [comment]
after you have install anaconda, in your .bashrc you should have added this line:

export PATH="/home/user/anaconda2/bin:$PATH"

before you make -j8 ,you  should comment this line first:

#export PATH="/home/user/anaconda2/bin:$PATH"

**Comment by ideex2** [comment]
conda uninstall libtiff works!

**Comment by shin1919** [comment]
conda uninstall libtiff works for me, too!

**Comment by BalajiB197** [comment]
conda uninstall libtiff works 
but it removes opencv, how to resolve this error.
anybody can help me with this issue?

**Comment by wangqiqi** [comment]
reinstall opencv can solve the problem in my side.

**Comment by derkbreeze** [comment]
@BalajiB197 
You can remove the 
export PATH=~/anaconda3/bin:$PATH and 
export LD_LIBRARY_PATH=~/anaconda3/lib:$LD_LIBRARY_PATH in your bashrc file and open another terminal to compile, it should work.

**Comment by pflarr** [comment]
I'm looking at a similar problem, and thought I'd chime in. 

There is no libtiff5. libtiff.so.5 is the libtiff 4.X ABI. They had to jump an ABI number because of a mistake in an earlier version. 

I'm seeing this exact same problem; Cmake is building against the system libtiff.so.5, but is linking against anaconda's libtiff.so.5. The ABI versions aren't that different, but the symbols in the system version include a suffix of @@LIBTIFF_4.0, and the anaconda version doesn't.

**Comment by JakeMalis** [comment]
Bump?

**Comment by Light--** [comment]
> @rndmania thx, It solved my problem and I try another way by install opencv not by apt-get

by what?

**Comment by Coldmooon** [comment]
I solved the problem by manually compiling `libtiff` and setting `CMAKE_PREFIX_PATH`, which makes `caffe` and `opencv` link to the same `libtiff`. I think this is a better way without side effects.

The error of `undefined reference toTIFFxxxxxx` comes from the following fact: 

`Opencv` links to the `libtiff` found by `cmake`. By default, `cmake` only searches the standard library path, e.g., `/usr/local/lib/`, by `find_package()` in `/usr/local/share/cmake-xx/Modules/FindTIFF.cmake`. If `libtiff` was not found there, `opencv` will compile it on the fly from its distribution `/path/to/opencv_source_code/3rdparty/libtiff/`.

While, `caffe` links to the `libtiff` pre-compiled by `anaconda`, located in `$HOME/anaconda3/lib/`

So, `caffe` and `opencv` link to different versions of `libtiff`.

## solution

The way is to make `opencv` and  `caffe` link to the same `libtiff`.

**Step 1**: manually compile the `libtiff`
```
wget http://download.osgeo.org/libtiff/tiff-4.0.10.tar.gz
tar -zxvf tiff-4.0.10.tar.gz && cd tiff-4.0.10
./configure --prefix=/path/to/libtiff/
make
make install (**Note**: no `sudo` since most people have no `root` privilege)
```
This will install `libtiff` into `/path/to/libtiff/` in your home directory.

**Step 2**: recompile `opencv` with the newly installed `libtiff`
```
cd /path/to/opencv_source_code/
mkdir release && cd release

cmake -DCMAKE_PREFIX_PATH=/path/to/libtiff/ -DBUILD_LIST=core,highgui,improc,python3 -DCMAKE_INSTALL_PREFIX=$(python -c "import sys; print(sys.prefix)") -DPYTHON3_EXECUTABLE=$(which python) -DPYTHON3_INCLUDE_DIR=$(python -c "from distutils.sysconfig import get_python_inc; print(get_python_inc())") -DPYTHON3_PACKAGES_PATH=$(python -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())") .. 
(you can choose other options) 

make
make install (**Note**: no `sudo`)
```
The **critical** in step 2 is that set `CMAKE_PREFIX_PATH` to force `cmake` to follow the newly installed `libtiff`.
`PYTHON3_EXECUTABLE`, `PYTHON3_INCLUDE_DIR`, and `PYTHON3_PACKAGES_PATH` point to the anaconda python.
I only choose four modules of opencv, `core,highgui,improc,python3`, by setting `BUILD_LIST`, which is enough for `caffe`.


**Step 3**: recompile `caffe` with the newly installed `libtiff`
```
cd /path/to/caffe
vim Makefile.config
```
In `Makefile.config`, modify:
```
INCLUDE_DIRS := /path/to/libtiff/include  $(PYTHON_INCLUDE) /usr/local/include
LIBRARY_DIRS := /path/to/libtiff/lib  $(PYTHON_LIB) /usr/local/lib /usr/lib
```
This will force `caffe` to use the newly installed `libtiff`. Then, 
```
make all
```

**Comment by isekeylabSunQixiang** [comment]
conda install --channel https://conda.anaconda.org/menpo opencv3
works for me

**Comment by 520Chris** [comment]
@DNALuo  `conda install -c menpo opencv3` work for me
For ubuntu 16.04 users, libtiff4 is unavailable and libtiff5 is the default.
You can use the following commands to validate
```
sudo updatedb
locate libtiff
```

**Comment by Swjtu-only** [comment]
> conda uninstall libtiff worked for me too.
wow,the line solve my many questions!!!

**Comment by jingzhao3200** [comment]
> rndmania: there is no libtiff4 available in current ubuntu 16.04 only libtiff5.
> 
> `conda uninstall libtiff` does not work for me.
> 
> Because in my system Ubuntu16.04, libtiff5 is default. So I just`sudo apt-get remove libtiff5-dev`
> And `conda install -c menpo opencv3`

I noticed that there are some conflict with conda 
so 
`sudo apt-get remove libtiff5-dev`
works for me

**Comment by hranjbar** [comment]
> conda uninstall libtiff worked for me too.

This solved the problem for me when I was trying to build and run cudnn samples. 
Thanks for sharing!

**Comment by dragonQian** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
