### ISSUE TITLE
How to calculate back-propagation for Local Response Normalization layer?

### ISSUE THREAD

**Issue by peterson123** [BVLC/caffe#1563]
Hi,
I'm reading caffe's implementation for LRN layer, but i'm confuse about how to calculate that. Can some one offer some information about how to calculate the back-propagation for LRN(cross channel).

**Comment by rohrbach** [comment]
Please ask usage questions on [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) -- this issues tracker is primarily for Caffe development discussion. Thanks!
