### ISSUE TITLE
Provide a bundled speech example

### ISSUE THREAD

**Issue by jeehye** [BVLC/caffe#1570]
Hi
I want to classify speech phoneme by using caffe.
I will use TIMIT DB.
I want to know is there any example for speech?not for image.
And how can I make data and label from TIMIT for caffe format?

**Comment by futurely** [comment]
@pannous, RNN and LSTM updates are in #2033.

**Comment by futurely** [comment]
[Computational Network Toolkit (CNTK)](https://cntk.codeplex.com/) is a speech recognition deep neural network framework including DNN, CNN, RNN, LSTM, etc.

Dong Yu, Adam Eversole, Mike Seltzer, Kaisheng Yao, Zhiheng Huang, Brian Guenter, Oleksii Kuchaiev, Yu Zhang, Frank Seide, Huaming Wang, Jasha Droppo, Geoffrey Zweig, Chris Rossbach, Jon Currey, Jie Gao, Avner May, Baolin Peng, Andreas Stolcke, Malcolm Slaney, "An Introduction to Computational Networks and the Computational Network Toolkit", Microsoft Technical Report MSR-TR-2014-112, 2014.

**Comment by shelhamer** [comment]
Closing as this particular example was kept in a fork, but further clear, general audience Caffe examples are still welcome as PRs.
