### ISSUE TITLE
Adding Caffe to a project via CMake

### ISSUE THREAD

**Issue by GiuliaP** [BVLC/caffe#1574]
Hi,

I wrote a CMakeLists.txt and a FindCaffe.cmake to link Caffe to an external project via CMake.
I can share the code if anybody is interested.

The project should use Caffe to extract features from a stream of incoming images. I am starting from the script extract_features.cpp.

The problem is that actually I am still not able to link Caffe to my project, because when I compile it I get a lot of linking errors (unresolved externals). I cannot find on the web any example of a simple code that uses Caffe as a library, i.e. source files + CMakeLists.txt (+ eventually FindCaffe.cmake) and as so many people are using this framework I wonder if anyone could please give me some hints or eventually post an example in the tutorials (I think it would be helpful for many who want to begin using Caffe).

Thank you,
Giulia

**Comment by shelhamer** [comment]
#1667 is a nice reformation of the CMake build that also makes including Caffe in your own projects easier through `find_package`. Follow-up there.

**Comment by marwaSaid** [comment]
@GiuliaP 
Would you please share it?

**Comment by GiuliaP** [comment]
see https://github.com/robotology/himrep
