### ISSUE TITLE
Xavier filler and inner product parameters

### ISSUE THREAD

**Issue by denizyuret** [BVLC/caffe#1575]
XavierFiller in filler.hpp takes a blob and fills it with U[-scale, scale] where scale = sqrt(Dtype(3) / fan_in).  fan_in is calculated as blob->count() / blob->num().  Now if this is a parameter blob (I am assuming it is, since we are passing it to a filler), blob->num() is always 1 (in fact the GaussianFiller checks for this condition) so we are in effect scaling all weights to sqrt(3/count) instead of sqrt(3/fan_in).  Isn't the fan_in simply blob->width()?

**Comment by shelhamer** [comment]
@sguada @Yangqing I agree the current shape of the inner product params is unfortunate. We could switch them as part of the next protobuf definition but it adds a step to the conversion.

**Comment by seanbell** [comment]
Until this gets fixed, perhaps documentation should be updated to clearly explain that Xavier is only correct for convolutional layers?

**Comment by Yangqing** [comment]
It was an unfortunate mistake. I propose to not allow InnerProductLayer to have arbitrary input shape - we always require a FlattenLayer before InnerProductLayer if the shape does not correspond to a vector (which is what I am doing in my refactoring). FlattenLayer will just share data pointers so no additional cost will incur.

**Comment by sguada** [comment]
I propose to make InnerProductLayer behave as a ConvolutionalLayer with
kernel equal to the bottom size.

Sergio

2015-02-23 9:27 GMT-08:00 Yangqing Jia <notifications@github.com>:

**Comment by seanbell** [comment]
In #1970, the weights for `InnerProductLayer` are updated to be 2D.  Assuming that existing `output x input x 1 x 1` parameter blobs are reshaped to `output x input`, this should solve the layout issue (since `count() / num() = output * input / output = input` as required).

**Comment by shelhamer** [comment]
Fixed by #1970. Thanks for the catch and discussion everyone.
