### ISSUE TITLE
How to specify propagate_down() values for each layer

### ISSUE THREAD

**Issue by yzxyzh** [BVLC/caffe#1576]
Hi!

Forgive my bad english :D.I noticed every layer has a propagate_down() parameter to let a layer decide whether a certain blob's delta value shall be computed. However I cannot find equal definitions in caffe.proto. I wonder if there is a way to change the values of propagate_down() while still sticking to caffe's net::init and solver::solve() methods , I do not want to change source codes in net.cpp or solver.cpp, nor reimplementing my own net initialization.

Many Thanks

**Comment by longjon** [comment]
Please ask usage questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) list. Thanks!
