### ISSUE TITLE
How to convert .mat into leveldb or LMDB formt?

### ISSUE THREAD

**Issue by gumanchang** [BVLC/caffe#1577]
Hi,GuysI want to train the SVHN dataset(train.mat,test.mat which contains the images and its labels) on my net. I read from #21 there was a convert.py script at the time ? Now where has it gone? Or the only way is extract the images and label from .mat then process like the ImageNet in caffe shown.Thanks.

**Comment by dk683** [comment]
This link might be useful: https://github.com/alexgkendall/SegNet-Tutorial/blob/master/Scripts/convert_mat_to_lmdb.py/
