### ISSUE TITLE
Loss function for ordinal regression

### ISSUE THREAD

**Issue by run2** [BVLC/caffe#1588]
Hi

Is it possible to have a loss class for ordinal regression ? 

There is a paper on this "Loss Functions for Preference Levels: Regression with Discrete Ordered Labels" it seems quite sensible. (and related blog http://fa.bianp.net/blog/2013/loss-functions-for-ordinal-regression/)

Would be grateful for any advice. I am stuck with this on a problem where I definitely want to use Caffe. 

Thanks

Regards

**Comment by iSawyer** [comment]
I think  Euclidean Loss Layers or Hinge Loss Layers can solve L1 or L2 regression problem.

**Comment by longjon** [comment]
Please ask usage questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) list. Thanks!
