### ISSUE TITLE
Segment fault before setting up a inner_product file

### ISSUE THREAD

**Issue by BestSonny** [BVLC/caffe#1589]
Pass the hdf5 data and obly with batch size 1.so memory is supposed to not be a issue.
the beginning are just several convolution layer with sigmoid func.And when it goes to the fc layer.
Just get Segment fault.Is it a bug or I really made a mistake?

**Comment by shelhamer** [comment]
Check the HDF5 data input.

Please ask usage questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) mailing list. Thanks!
