### ISSUE TITLE
how many fully connected layers can we have?

### ISSUE THREAD

**Issue by fujunliu84** [BVLC/caffe#1590]
Most architectures only include one fully connected layer followed by the output layer. I tried to add more fully connected layers to make it deeper, the performance seems to degrade. I encountered this problem several times, is there some theory behind this? Or just I did something wrong.

**Comment by shelhamer** [comment]
Increasing the number of parameters by adding layers can lead to overfitting.

Please ask modeling questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) mailing list. Thanks!
