### ISSUE TITLE
The macro NOT_IMPLEMENTED conflicts with Apache Thrift

### ISSUE THREAD

**Issue by futurely** [BVLC/caffe#1592]
Apache Thrift defines [NOT_IMPLEMENTED as a TProtocolExceptionType](http://stackoverflow.com/questions/25232147/tprotocolexception-expected-identifier-before). Maybe there are also other libraries that use this name.

Caffe should use `caffe::NOT_IMPLEMENTED` or rename `NOT_IMPLEMENTED` as `CAFFE_NOT_IMPLEMENTED`.

**Comment by futurely** [comment]
`find . -type f -print0 | xargs -0 sed -i 's/NOT_IMPLEMENTED/CAFFE_NOT_IMPLEMENTED/'`

**Comment by shelhamer** [comment]
Closing as unnecessary; howl here if you find this is really holding you back.

**Comment by BoyuanYan** [comment]
> `find . -type f -print0 | xargs -0 sed -i 's/NOT_IMPLEMENTED/CAFFE_NOT_IMPLEMENTED/'`

Thanks very much :100:
