### ISSUE TITLE
Prediction for multiple different inputs

### ISSUE THREAD

**Issue by vasicek** [BVLC/caffe#1593]
Hi, I am wondering about prediction of two inputs (image, vector of numbers). Lets say that I wanna insert an image that will be convoluted by multiple convolution layers. Then there will be a vector of numbers that will be read by the second data layer and concatenated with result of convolutions. This concatenated blob will be inserted into ip layers.

I was searching in classifier.py and found predict method. Am I able to change predict method with something like this:

predict(self, inputs, oversample=True) => predict_multiple(self, inputs, vector, oversample=True)

.....
vector will become an array of same vectors (because of the oversample=>multiple images)
.....
 out = self.forward_all(**{self.inputs[0]: caffe_in}) => out = self.forward_all(**{self.inputs[0]: caffe_in, "second_data_layer_name":vector})
.....

Thanks for help

**Comment by shelhamer** [comment]
Caffe nets can have multiple inputs. Please ask modeling questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) mailing list.
