### ISSUE TITLE
Siamese for Face Verification

### ISSUE THREAD

**Issue by Prasanna1991** [BVLC/caffe#1597]
Hello,
I would be grateful if anyone could point me out how to test the Siamese model. I train with my own datasets, and passed an image in the deploy file and then noted the resulting 'feat' value. Similarly to test similarity, passed another image in the same deploy file and again noted its result. At last I calculate the distance between two results. I doubt if this approach is ok. Even if its ok, I am having very poor results, the distance between the same person face is large than even gender different face. I had around 300 faces of 26 different classes and trained with 2457 genuine pair and 59319 impostor pairs.

Thank You!!

**Comment by shelhamer** [comment]
Start by following the "Siamese Network Tutorial" on the homepage that learns and tests a siamese net on MNIST.

Please ask modeling questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) mailing list. Thanks!
