### ISSUE TITLE
What OpenCV versions should we support?

### ISSUE THREAD

**Issue by sanchom** [BVLC/caffe#1603]
I attempted to submit a pull request to upgrade the OpenCV imread constants to be compatible with OpenCV 3.0 (https://github.com/BVLC/caffe/pull/1594).

However, Travis CI uses OpenCV 2.3, and the constants, cv::IMREAD_COLOR, cv::IMREAD_UNCHANGED, etc. are not available in OpenCV until 2.4.0.

Right now, Caffe is compatible with OpenCV 2.3 to 2.4.9. If we switch to the new constants, Caffe would be compatible with OpenCV 2.4.0 to 3.0.0 and onward. Is this something that we'd like to do? It would break support for OpenCV 2.3.

It would also require updating Travis CI to use OpenCV 2.4.0 or greater. We could do that by using a backport from https://launchpad.net/~yjwong/+archive/ubuntu/opencv2

**Comment by blackibiza** [comment]
I've added this extra fix: https://github.com/BVLC/caffe/pull/1714

Now CMake accepts both OpenCV 2.x (min 2.3) and OpenCV 3.x. 
cv::imread now is adjusted accordingly to the proper API used. I've defined the variables OPENCV_3 and OPENCV_2 to do the conditional choice.

**Comment by bhack** [comment]
Referencing also https://github.com/BVLC/caffe/issues/581

**Comment by shelhamer** [comment]
We should be compatible with 2.4 through the present (3) and if there needs to be an ifdef path for Travis that's life. I think this was resolved by #1667 but comment if I'm mistaken -- I don't have an OpenCV 3 install to check.
