### ISSUE TITLE
can't build the python wrapper with make pycaffe

### ISSUE THREAD

**Issue by helxsz** [BVLC/caffe#1604]
I have compiled and built the caffe through the cmake, and it is working well for the example - imagenet, which I can train the CNN network and get the model. Now I want to use the model to classify, the classification example - http://nbviewer.ipython.org/github/BVLC/caffe/blob/master/examples/classification.ipynb is given in the python example. so I need to have a python wrapper built as well. 
According to the python instruction, use 
make pycaffe
so I also downloaded the cudnn6.5 library, and place cudnn.h into /usr/include. and I tried to make all , the error of 'cannot find cudnn.h' is gone.
But more errors come out 
```
./include/caffe/util/cudnn.hpp:11:28: note: in definition of macro ‘CUDNN_CHECK’
     cudnnStatus_t status = condition; \
                            ^
In file included from ./include/caffe/loss_layers.hpp:11:0,
                 from ./include/caffe/common_layers.hpp:12,
                 from ./include/caffe/vision_layers.hpp:10,
                 from src/caffe/layer_factory.cpp:5:
./include/caffe/neuron_layers.hpp: At global scope:

./include/caffe/neuron_layers.hpp:467:3: error: ‘cudnnTensor4dDescriptor_t’ does not name a type
   cudnnTensor4dDescriptor_t bottom_desc_;

src/caffe/layer_factory.cpp: In function ‘caffe::SoftmaxLayer<Dtype>* caffe::GetSoftmaxLayer(const string&, const caffe::LayerParameter&) [with Dtype = float; std::string = std::basic_string<char>]’:
src/caffe/layer_factory.cpp:167:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
src/caffe/layer_factory.cpp: In function ‘caffe::PoolingLayer<Dtype>* caffe::GetPoolingLayer(const string&, const caffe::LayerParameter&) [with Dtype = double; std::string = std::basic_string<char>]’:
src/caffe/layer_factory.cpp:59:1: warning: control reaches end of non-void function [-Wreturn-type]
```

Anyone experience the similar problem ?

**Comment by shelhamer** [comment]
Install cuDNN R1 instead of the R2 release candidate which is still experimental. See #1731 for an in-progress R2 branch.
