### ISSUE TITLE
The size of the mean isn't applied properly in MemoryDataLayer

### ISSUE THREAD

**Issue by rold2007** [BVLC/caffe#1614]
As mentioned in the forum [here](https://groups.google.com/forum/#!topic/caffe-users/jloh0NTkBGQ) the mean is applied without verifying its size correctly.

In BaseDataLayer::LayerSetUp() the mean is loaded from the file into a pointer. Later, when calling MemoryDataLayer::AddDatumVector() this same pointer is sent to the data_transformer but with no information about the width/height of the data. When using the mean file associated with ilsvrc12, the mean data is actually a 256x256 image. The examples for ilsvrc12 usually take a 227x227 image in input, thus the mean pointer isn't being indexed correctly in DataTransformer::Transform().

I think that the mean data should be resized automatically when loaded, but I'm not sure this is the right solution.

**Comment by bhack** [comment]
cc: @sguada

**Comment by shelhamer** [comment]
Closing according to #5528. This use case can be handled by a `Python` layer or `Input` layer.
