### ISSUE TITLE
Why do you normalize an uploaded img before predictions even you don't for URL img in web-demo?

### ISSUE THREAD

**Issue by erogol** [BVLC/caffe#1616]
In the web demo, I see that you normalize an uploaded image with the line 26 in exifutil.py

img = np.asarray(im).astype(np.float32) / 255.

However, you do not touch given URL img and give it to net.predict directly. Is there anything wrong about it or do I miss something?

**Comment by shelhamer** [comment]
`classify_url` relies on `caffe.io.load_image()` for normalization while `classify_upload1 relies on `exifutil.open_oriented_im()` doing normalization. In both cases, the input image is normalized.
