### ISSUE TITLE
cuDNN R2 is available

### ISSUE THREAD

**Issue by ducha-aiki** [BVLC/caffe#1622]
CuDNN RC 2 is available for download. https://developer.nvidia.com/cuDNN
They say, it is 40% faster than original cuDNN. However, it breaks a compatibility with caffe-wrappers (more general ways to pass n-d tensors, additional coefficients, etc.) Does anyone know, NVIDIA guys going to support caffe in future, or rewriting cudnn-layers are up to us?

**Comment by ziyuang** [comment]
Is [this](https://groups.google.com/forum/#!topic/caffe-users/xLi8tX2-kcw) what Caffe will report due to the incompatibility between R1 and R2?

**Comment by shelhamer** [comment]
While cuDNN R2 has a different interface, the change is quite slight and we will support it soon by a few changes to [include/caffe/util/cudnn.hpp](https://github.com/BVLC/caffe/blob/master/include/caffe/util/cudnn.hpp).

While cuDNN R2 is still a release candidate R1 will likely stay the default.

**Comment by Felix-neko** [comment]
Maybe you can make a temporary branch?

**Comment by shelhamer** [comment]
See #1731 for an in-progress cuDNN R2 branch.

The Caffe crew collaborates with the cuDNN team on roadmap planning and interface design but at the moment the Caffe coding happens at Berkeley and in the open source community.

**Comment by shelhamer** [comment]
Covered by #1731 / #1739 thanks to Simon Layton at NVIDIA.
