### ISSUE TITLE
I guess argv indexing is wrong in tools/convert_imageset.cpp

### ISSUE THREAD

**Issue by erogol** [BVLC/caffe#1624]
In the code there are optional flags to be used and if I use it argc returns 5 with FLAGS ROOT_PATH IMGFILE_LIST DB_NAME. However if clause at the begining of the code returns 1 if argc != 4. Therefore, if I provide flags to the code, code does not work. I guess it should be corrected in a way that allows the use of FLAGS

**Comment by shelhamer** [comment]
Fixed in dev @ d612f4a.
