### ISSUE TITLE
Bounding Boxes (and Sliding Windows) in Caffe

### ISSUE THREAD

**Issue by res97** [BVLC/caffe#1626]
Is there any facility available in caffe for sliding windows and bounding boxes. Or should we create our sliding windows (or BBs) before feeding to caffe.

**Comment by shelhamer** [comment]
The `WindowDataLayer` trains on bounding boxes. R-CNN includes an example of how to use it and define its input file.

Please ask usage questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) mailing list. Thanks!
