### ISSUE TITLE
DrawNet provides too few details

### ISSUE THREAD

**Issue by Russell91** [BVLC/caffe#1628]
It would be nice to have more verbose details about a prototxt, perhaps provided by a `--verbose` flag to the draw_net.py file. Normally, I would consider the current system, where users just implement the verbose drawing themselves when they want it, to be good enough. However, when I tried to do this by appending layer information to the name of each node, I ran into the issue that pydot support for naming nodes is horrendous due to graphviz artifacts (http://code.google.com/p/pydot/issues/detail?id=28). However, after working on what should have been a trivial change for far too long, I came up with the following simple modification to python/caffe/draw.py: 

    extra = str(layer)
    pydot_nodes[name + '_' + layertype] = pydot.Node(
          '\"%s (%s):\r%s\"' % (name, layertype, extra.replace('\n', '\r').replace('"', '\'')), **LAYER_STYLE)

The results are quite nice, and nontrivial to implement simply due to the graphviz parsing bug. Here's an example of the result on the alexnet prototxt:

![a](https://cloud.githubusercontent.com/assets/1069617/5544915/997ccb90-8ac7-11e4-97b9-eabeba68ba44.jpg)

**Comment by Russell91** [comment]
@StevenLOL I ran into your problem on a ubuntu system. The \n->\r hack is not necessary on Ubuntu (I was previously on centOS). Using the following should work:

    value = '\n' # use '\r' for centOS
    extra = str(layer)
    pydot_nodes[name + '_' + layertype] = pydot.Node( 
          '\"%s (%s):%s%s\"' % (name, layertype, value, extra.replace('\n', value).replace('"', '\'')), **LAYER_STYLE)

**Comment by shelhamer** [comment]
#1555 improved draw net. If you would like further detail, please send a PR. Thanks for sharing your visualization.
