### ISSUE TITLE
How to use a fine-tuned caffe model

### ISSUE THREAD

**Issue by atique81** [BVLC/caffe#1630]
Hi all,
I am very new to Caffe and so is with fine-tuning. I would like to fine-tune following the flickr_style_fine-tuning example and then want to use that model to extract features of my dataset in matlab. My questions are -

1. What is the output of fine-tuning? Is it a file like model_name.caffemodel? In that case, can I use this model_name.caffemodel to extract features in matlab? if so, then how to convert this model file to something .mat (to be usable with matlbab)?

2. If not possible in matlab, how can I use the model_name.caffemodel (fine-tuned model) to extract features for my new dataset and also to test on that dataset?

I would highly appreciate if anyone could help me from scratch.

**Comment by shelhamer** [comment]
Please ask usage questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) mailing list. Thanks!

Fine-tuning outputs a model as a binary protobuf `.caffemodel`. The matcaffe interface can run such models in MATLAB, although the pycaffe interface has more features.

**Comment by atique81** [comment]
@shelhamer Thanks a lot for replying. I have also posted this query on the caffe-users mailing list, but didn't get fruitful reply.
I just want to know - 
1. Now that I have a fine-tuned model on flicr style dataset, how caan I directly use this model to find out scores of a test set from flickr style having 20 classes? I mean, where do I need to make changes (e.g. deploy.prototxt usually has the last layer output size 1000, but flickr has 20 classes). 

2. I thought calling the matcaffe_batch(list_im, use_gpu) with the model file set to new fine-tuned model and the model definition file set to the default deploy.ptotoxt with the last layer output changed to 20 (instead of the default value of 1000 for ImageNet) would work. But, its giving me a constant score of 0.05 for all the 20 classes.
