### ISSUE TITLE
How to fine-tune a model using images that have bounding boxes

### ISSUE THREAD

**Issue by atique81** [BVLC/caffe#1631]
Hi all,

Could you please let me know if I can fine-tune a caffe model using images that have specified bounding box information with one bounding box per image?

**Comment by shelhamer** [comment]
See `WindowDataLayer` or crop the images according to your bounding boxes before input to Caffe.

Please ask usage questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) mailing list. Thanks!
