### ISSUE TITLE
Android demo

### ISSUE THREAD

**Issue by bhack** [BVLC/caffe#1641]
It could be interesting to have a mobile Android demo. Take a look to this effort https://github.com/sh1r0/caffe-android-demo and https://github.com/sh1r0/caffe-android-lib

**Comment by bhack** [comment]
Take a look also to java-cpp at https://github.com/bytedeco/javacpp-presets/issues/34

**Comment by bhack** [comment]
@bittnt no.. But if java-cpp works code could directly run on [robo-vm](http://www.robovm.com)

**Comment by bhack** [comment]
An initial preset is ready. Please anybody interested try it and comment on https://github.com/bytedeco/javacpp-presets/issues/34

**Comment by bhack** [comment]
Please refer at [Readme](https://github.com/bytedeco/javacpp-presets/blob/master/caffe/README.md). /cc @shelhamer @longjon @jeffdonahue

**Comment by futurely** [comment]
https://github.com/BVLC/caffe/issues/1823#issuecomment-93659994

**Comment by shelhamer** [comment]
Closing as this is a minority platform for Caffe.
