### ISSUE TITLE
how to  check out the classification results of every picture in the test dataset with the model we already finished training

### ISSUE THREAD

**Issue by haoleipeng** [BVLC/caffe#1643]
we've already had the model trained and the result says the classification accuracy of this model over the whole test dataset is 87%. But we wanna see the classification result of each picture in detail. We download a python script and run it following the instruction steps offered. By the way, the photo in the test dataset belongs to 2 classes. anyway, we run the python scripts, and all the pictures in the test dataset were assigned  to Class. i wanna know how to check out the clasification results of each picture in the test...a scripts with instructions in brief would be nice.  
also, in the python scripts we used, a picture-mean file is required, can anyone tell me how to create this file? i do not know if the way i create it is correct or not

**Comment by shelhamer** [comment]
Please ask usage questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) mailing list. Thanks!

Note that it is important to be sure the input preprocessing is the same with the `caffe` command line tool and Python interface settings.
