### ISSUE TITLE
Split headers to improve build granularity

### ISSUE THREAD

**Issue by longjon** [BVLC/caffe#1646]
#1472 brings proper incremental building to the Makefile (which presumably the CMake build has as well). However, interactive building can be still be pretty slow, largely due to the use of monolithic header files (such as `vision_layers.hpp`).

Unless there's some good reason to have things the way they are, it seems better to give each layer its own header file. (Of course, we can still provide `vision_layers.hpp` etc. to include the others if that's actually useful somewhere.)

**Comment by futurely** [comment]
I tried to do that but gave up the idea several months ago. The Makefile became too cumbersome without the automatic dependency generation mechanism.

It's also a good time to split the whole project into modules which is a common practice for large and quickly growing projects such as OpenCV.

**Comment by bhack** [comment]
:+1:

**Comment by shelhamer** [comment]
Solved by #3315 and #3226.
