### ISSUE TITLE
Configurate Convolutional Auto-Encoders in Caffe

### ISSUE THREAD

**Issue by pl8787** [BVLC/caffe#1647]
Does anyone know how to config Convolutional Auto-Encoders in Caffe? And is it useful for initialize the CNN parameters?
Ref: [Stacked Convolutional Auto-Encoders for Hierarchical Feature Extraction](www.idsia.ch/~ciresan/data/icann2011.pdf)

**Comment by pl8787** [comment]
Does anyone know about this issue?

**Comment by shelhamer** [comment]
The encoder part is easily defined in Caffe as-is, but the decoder needs unpooling, deconvolution #1615, and transposed inner product layers that are not currently in the public BVLC/caffe.

Please ask modeling questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) mailing list. Thanks!
