### ISSUE TITLE
Compiling Error from cblas

### ISSUE THREAD

**Issue by helson73** [BVLC/caffe#1649]
Hi, all
  I got a problem when I want to compile caffe.
  My system is:
  OS: Ubuntu 14.04
  BLAS: openblas
  GPU? : cuda 6.5, cudnn
  The error message is:

---

  g++ home/skywalker/Program/caffe/build_release/tools/caffe.o ./home/skywalker/Program/caffe/build_release/lib/libcaffe.a -o home/skywalker/Program/caffe/build_release/tools/caffe.bin -fPIC -DNDEBUG -O2 -DUSE_CUDNN -I/usr/include/python2.7 -I/usr/local/lib/python2.7/dist-packages/numpy/core/include -I/usr/local/include -I./home/skywalker/Program/caffe/build_release/src -I./src -I./include -I/home/skywalker/cuda-6.5/include -I/opt/OpenBLAS/include -Wall -Wno-sign-compare -L/usr/lib -L/usr/local/lib -L/usr/lib -L/home/skywalker/cuda-6.5/lib64 -L/home/skywalker/cuda-6.5/lib -L/opt/OpenBLAS/lib -lcudart -lcublas -lcurand -lpthread -lglog -lgflags -lprotobuf -lleveldb -lsnappy -llmdb -lboost_system -lhdf5_hl -lhdf5 -lopencv_core -lopencv_highgui -lopencv_imgproc -lboost_thread -lcudnn
./home/skywalker/Program/caffe/build_release/lib/libcaffe.a(window_data_layer.o): In function `caffe::WindowDataLayer<float>::InternalThreadEntry()':
window_data_layer.cpp:(.text._ZN5caffe15WindowDataLayerIfE19InternalThreadEntryEv[_ZN5caffe15WindowDataLayerIfE19InternalThreadEntryEv]+0x370): undefined reference to`cv::imread(cv::String const&, int)'
./home/skywalker/Program/caffe/build_release/lib/libcaffe.a(window_data_layer.o): In function `caffe::WindowDataLayer<double>::InternalThreadEntry()':
window_data_layer.cpp:(.text._ZN5caffe15WindowDataLayerIdE19InternalThreadEntryEv[_ZN5caffe15WindowDataLayerIdE19InternalThreadEntryEv]+0x373): undefined reference to`cv::imread(cv::String const&, int)'
./home/skywalker/Program/caffe/build_release/lib/libcaffe.a(math_functions.o): In function `void caffe::caffe_cpu_gemm<float>(CBLAS_TRANSPOSE, CBLAS_TRANSPOSE, int, int, int, float, float const*, float const*, float, float*)':
math_functions.cpp:(.text+0xde): undefined reference to`cblas_sgemm'
./home/skywalker/Program/caffe/build_release/lib/libcaffe.a(math_functions.o): In function `void caffe::caffe_cpu_gemm<double>(CBLAS_TRANSPOSE, CBLAS_TRANSPOSE, int, int, int, double, double const*, double const*, double, double*)':
math_functions.cpp:(.text+0x13e): undefined reference to`cblas_dgemm'
./home/skywalker/Program/caffe/build_release/lib/libcaffe.a(math_functions.o): In function `void caffe::caffe_cpu_gemv<float>(CBLAS_TRANSPOSE, int, int, float, float const*, float const*, float, float*)':
math_functions.cpp:(.text+0x17f): undefined reference to`cblas_sgemv'
./home/skywalker/Program/caffe/build_release/lib/libcaffe.a(math_functions.o): In function `void caffe::caffe_cpu_gemv<double>(CBLAS_TRANSPOSE, int, int, double, double const*, double const*, double, double*)':
math_functions.cpp:(.text+0x1bf): undefined reference to`cblas_dgemv'
./home/skywalker/Program/caffe/build_release/lib/libcaffe.a(math_functions.o): In function `void caffe::caffe_cpu_axpby<float>(int, float, float const_, float, float_)':

---

something like this, and it says "undefined reference to 'cblas_*' 
In my Makefile.config, my setting is: 

BLAS := openblas
BLAS_INCLUDE := /opt/OpenBLAS/include
BLAS_LIB := /opt/OpenBLAS/lib

Also, the path to openblas is added to my $LD_LIBRARY_PATH in my .bashrc  file
and I checked /opt/OpenBLAS/include/cblas.h
all the functions make errors are defined in "cblas.h"
so I don't understand what happens at all. Because my openblas works well with python-numpy and Theano. 
Could you guys pleass help me? and welcome to post your advise if you have similar problem.
Many thanks.

**Comment by xiaopuLee** [comment]
set BLAS := open and you will probably fix it

**Comment by kwende** [comment]
This worked for me too. Accidentally used BLAS := OpenBlas instead.
