### ISSUE TITLE
New layer building error: expected constructor, destructor, or type conversion before ‘(’ token  REGISTER_LAYER_CLASS)

### ISSUE THREAD

**Issue by wangdelp** [BVLC/caffe#1652]
Hi, there: 
I have followed the [development wiki: https://github.com/BVLC/caffe/wiki/Development] to develop my own layer. I have done all the steps listed there except the last two steps (In my understanding, the last two steps are not  necessary, if I am right.)

Then I tried to make file again by typing "make all" under $CAFFEROOT directory, but I got an error as following: 
expected constructor, destructor, or type conversion before ‘(’ token  REGISTER_LAYER_CLASS)

How can I fix that issue? Thank you.

**Comment by shelhamer** [comment]
Double-check your layer definition in the relevant header file, and check that 

```
INSTANTIATE_CLASS(NewLayer);
REGISTER_LAYER_CLASS(NEW_LAYER, NewLayer);
```

are done *after* the class implementation. See the existing layer implementations for examples.
