### ISSUE TITLE
Adagrad and Nesterov solvers do not understand weight sharing

### ISSUE THREAD

**Issue by cdoersch** [BVLC/caffe#1659]
The history_ variable in solver.cpp tracks the parameter history *per blob.*  In nesterov, for instance, the history is the integral of one particular blob's gradients, which means that comparing it to the current parameter's value is almost totally meaningless.  Similarly, for Adagrad, we end up with a separate step size per blob.  This is a potentially serious bug since currently, Caffe silently computes these incorrect updates and applies them.  Since these updates are unlikely to make the learning diverge, the user may have no indication that they're wrong.  

Also, while somebody has the solver opened up, they should look into whether it actually makes sense that the nesterov solver never looks at the current parameter value while it makes updates.  While the current computation does seem to be mathematically correct, it also seems like numerical inaccuracy between history_ and the true parameter value could compound over thousands of iterations to result in very inaccurate gradients being computed.

**Comment by shelhamer** [comment]
Weight sharing history is fixed in #2866.
