### ISSUE TITLE
How to extract inner layer features of an image in C++

### ISSUE THREAD

**Issue by StevenLobo2** [BVLC/caffe#1664]
I used feature_extraction with input IMAGE_DATA layer to extract the feature. But it provides the class for an image. I am interested to extracting data in inner layer. I change prototext to include only till pool4 layer. But I am getting unexpected results.

**Comment by shelhamer** [comment]
Please ask application questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) mailing list. Thanks!
