### ISSUE TITLE
Caffe Build Error

### ISSUE THREAD

**Issue by Jiansen** [BVLC/caffe#1668]
I received the following error when building caffe

```
src/caffe/util/math_functions.cpp: In function ‘void caffe::caffe_cpu_axpby(int, Dtype, const Dtype*, Dtype, Dtype*) [with Dtype = float]’:
src/caffe/util/math_functions.cpp:120: error: ‘cblas_saxpby’ was not declared in this scope
src/caffe/util/math_functions.cpp: In function ‘void caffe::caffe_cpu_axpby(int, Dtype, const Dtype*, Dtype, Dtype*) [with Dtype = double]’:
src/caffe/util/math_functions.cpp:126: error: ‘cblas_daxpby’ was not declared in this scope
make: *** [.build_release/src/caffe/util/math_functions.o] Error 1
```

I noticed that cblas_daxpby is defined in include/caffe/util/mkl_alternate.hpp , which is included in src/caffe/util/math_functions.cpp .

How could I fix the issue.

Meanwhile, as I have set BLAS := mkl in Makefile.config, why the make file still compile mkl_alternate ?

Thanks

**Comment by shelhamer** [comment]
Please double-check your Makefile.config and ask installation questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) mailing list. Thanks!
