### ISSUE TITLE
how to print convolution kernel value??

### ISSUE THREAD

**Issue by jeehye** [BVLC/caffe#1674]
Hello
I want to know exact value of the 5*5 convolution filter matrix.
How can I get the value??

**Comment by yassersouri** [comment]
If I undrestand correctly, with the python interface you can use `net.params['conv1']` for instance.

**Comment by jeehye** [comment]
I'm not used to python.
could you be more specific??
The code which I made does not work...
How could I change the code??

#!/usr/bin/env python
import numpy as np
import pandas as pd
import os
import argparse
import time
import caffe
net = caffe.Net('/examples/mnist/lenet.prototxt', '/examples/mnist/lenet_iter_5000.caffemodel')
print net.params['conv1']

**Comment by yassersouri** [comment]
Take a look at this example: <http://nbviewer.ipython.org/github/BVLC/caffe/blob/master/examples/filter_visualization.ipynb>

I think you should look at `In[5]`

**Comment by Engin007** [comment]
hey yasser i have been wanting to do the same thing recently however I am using the ported version of caffe for windows. Do you have any idea how to extract the data and or add kernels to the convolution layer? I am new to python and a beginner with programming in General

**Comment by bhack** [comment]
Please use the mailinglist.
