### ISSUE TITLE
Siamese network with RGB image

### ISSUE THREAD

**Issue by jrabary** [BVLC/caffe#1676]
Hi all,

The current example of siamese network uses two gray images as a channel of the data blob. How one should create a data blob for a pair of RGB images ?

Best regards

**Comment by jrabary** [comment]
I managed to do what I want by using the slicing_point parameters.

**Comment by sunbaigui** [comment]
@jrabary how do you make db with RGB images? could you post it?

**Comment by anxiaoxi45** [comment]
if I want to use RGB image dirctly with the layer( LayerType: IMAGE_DATA ), how to write the source param (source: name of a text file, with each line giving an image filename and label)?

**Comment by nassarofficial** [comment]
@jrabary could you tell us how you did it?
