### ISSUE TITLE
Model selection and crossvalidation with caffe

### ISSUE THREAD

**Issue by jrabary** [BVLC/caffe#1677]
What is the best practice to run a model  selection (nb of layers, nb of filters, ... ) and cross validation with caffe ?

**Comment by kamikawa** [comment]
Hi 

Regarding cross validation, Caffe seems not to be supposed to do so thus far. 
Train/Test data are explicitly divided and the locations are hard coded in prototxt.
I hope cross validation would be supported .

**Comment by ih4cku** [comment]
What do u mean by 'locations'?@kamikawa

**Comment by shelhamer** [comment]
Please ask usage questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) group.
