### ISSUE TITLE
Contributing a new model to the Model Zoo

### ISSUE THREAD

**Issue by GilLevi** [BVLC/caffe#1678]
Hi, 

I have a new model that I can contribute to the Model Zoo. However, I'm not sure if it's interesting enough.

Basically, I finetuned Caffe Imagenet reference net on the official CIFAR10 dataset that I've downloaded from CIFAR's site.

I got an accuracy of 92.61% using the center crop and an accuracy of 93.09 using "oversample". 

Caffe moderators, please let me know if you'd like me to contribute this model. Perhaps it can even serve as a finetune example (using the train_val prototxt files). 

Thanks,
Gil.

**Comment by shelhamer** [comment]
Thanks for checking, but in general I suggest either sharing your work on the mailing list or if you have a model accompanying a paper/product/project you can include it in the Model Zoo wiki.
