### ISSUE TITLE
Make all Failed

### ISSUE THREAD

**Issue by AndroidCloud** [BVLC/caffe#1679]
In file included from /usr/include/c++/4.6/atomic:38:0,
                 from /usr/local/include/boost/math/special_functions/detail/bernoulli_details.hpp:17,
                 from /usr/local/include/boost/math/special_functions/bernoulli.hpp:16,
                 from /usr/local/include/boost/math/special_functions/gamma.hpp:35,
                 from /usr/local/include/boost/math/special_functions/detail/bessel_jy.hpp:14,
                 from /usr/local/include/boost/math/special_functions/bessel.hpp:20,
                 from /usr/local/include/boost/math/special_functions/airy.hpp:12,
                 from /usr/local/include/boost/math/special_functions.hpp:15,
                 from /usr/local/include/boost/random/generate_canonical.hpp:22,
                 from /usr/local/include/boost/random.hpp:52,
                 from /home/anirudh/caffe-rc/src/caffe/util/math_functions.cpp:2:
/usr/include/c++/4.6/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the upcoming ISO C++ standard, C++0x. This support is currently experimental, and must be enabled with the -std=c++0x or -std=gnu++0x compiler options.
In file included from /usr/local/include/boost/optional.hpp:15:0,
                 from /usr/local/include/boost/format/internals.hpp:20,
                 from /usr/local/include/boost/format.hpp:38,
                 from /usr/local/include/boost/math/policies/error_handling.hpp:31,
                 from /usr/local/include/boost/math/special_functions/next.hpp:14,
                 from /home/anirudh/caffe-rc/src/caffe/util/math_functions.cpp:1:
/usr/local/include/boost/optional/optional.hpp:1008:39: error: expected ‘;’ at end of member declaration
/usr/local/include/boost/optional/optional.hpp:1008:46: error: expected unqualified-id before ‘{’ token
/usr/local/include/boost/optional/optional.hpp:1009:37: error: expected ‘;’ at end of member declaration
/usr/local/include/boost/optional/optional.hpp:1009:46: error: expected unqualified-id before ‘{’ token
/usr/local/include/boost/optional/optional.hpp:1010:5: error: ‘reference_type_of_temporary_wrapper’ does not name a type
/usr/local/include/boost/optional/optional.hpp:1017:34: error: expected ‘;’ at end of member declaration
/usr/local/include/boost/optional/optional.hpp:1018:7: error: expected unqualified-id before ‘{’ token
/usr/local/include/boost/optional/optional.hpp:1025:26: error: expected ‘;’ at end of member declaration
/usr/local/include/boost/optional/optional.hpp:1026:7: error: expected unqualified-id before ‘{’ token
/usr/local/include/boost/optional/optional.hpp:1033:5: error: ‘reference_type_of_temporary_wrapper’ does not name a type
/usr/local/include/boost/optional/optional.hpp:1062:28: error: expected ‘,’ or ‘...’ before ‘&&’ token
/usr/local/include/boost/optional/optional.hpp:1062:40: error: expected initializer before ‘&’ token
/usr/local/include/boost/optional/optional.hpp:1071:28: error: expected ‘,’ or ‘...’ before ‘&&’ token
/usr/local/include/boost/optional/optional.hpp:1071:35: error: expected initializer before ‘&&’ token
/usr/local/include/boost/optional/optional.hpp:1101:43: error: expected initializer before ‘&’ token
/usr/local/include/boost/optional/optional.hpp:1110:38: error: expected initializer before ‘&&’ token
In file included from /usr/include/c++/4.6/atomic:41:0,
                 from /usr/local/include/boost/math/special_functions/detail/bernoulli_details.hpp:17,
                 from /usr/local/include/boost/math/special_functions/bernoulli.hpp:16,
                 from /usr/local/include/boost/math/special_functions/gamma.hpp:35,
                 from /usr/local/include/boost/math/special_functions/detail/bessel_jy.hpp:14,
                 from /usr/local/include/boost/math/special_functions/bessel.hpp:20,
                 from /usr/local/include/boost/math/special_functions/airy.hpp:12,
                 from /usr/local/include/boost/math/special_functions.hpp:15,
                 from /usr/local/include/boost/random/generate_canonical.hpp:22,
                 from /usr/local/include/boost/random.hpp:52,
                 from /home/anirudh/caffe-rc/src/caffe/util/math_functions.cpp:2:
/usr/include/c++/4.6/bits/atomic_base.h:204:25: error: ‘char16_t’ was not declared in this scope
/usr/include/c++/4.6/bits/atomic_base.h:204:33: error: template argument 1 is invalid
/usr/include/c++/4.6/bits/atomic_base.h:204:53: error: invalid type in declaration before ‘;’ token
/usr/include/c++/4.6/bits/atomic_base.h:207:25: error: ‘char32_t’ was not declared in this scope
/usr/include/c++/4.6/bits/atomic_base.h:207:33: error: template argument 1 is invalid
/usr/include/c++/4.6/bits/atomic_base.h:207:53: error: invalid type in declaration before ‘;’ token
/usr/include/c++/4.6/bits/atomic_base.h:210:25: error: ‘char32_t’ was not declared in this scope
/usr/include/c++/4.6/bits/atomic_base.h:210:33: error: template argument 1 is invalid
/usr/include/c++/4.6/bits/atomic_base.h:210:53: error: invalid type in declaration before ‘;’ token
In file included from /usr/include/c++/4.6/atomic:42:0,
                 from /usr/local/include/boost/math/special_functions/detail/bernoulli_details.hpp:17,
                 from /usr/local/include/boost/math/special_functions/bernoulli.hpp:16,
                 from /usr/local/include/boost/math/special_functions/gamma.hpp:35,
                 from /usr/local/include/boost/math/special_functions/detail/bessel_jy.hpp:14,
                 from /usr/local/include/boost/math/special_functions/bessel.hpp:20,
                 from /usr/local/include/boost/math/special_functions/airy.hpp:12,
                 from /usr/local/include/boost/math/special_functions.hpp:15,
                 from /usr/local/include/boost/random/generate_canonical.hpp:22,
                 from /usr/local/include/boost/random.hpp:52,
                 from /home/anirudh/caffe-rc/src/caffe/util/math_functions.cpp:2:
/usr/include/c++/4.6/bits/atomic_0.h:176:7: error: ‘constexpr’ does not name a type
/usr/include/c++/4.6/bits/atomic_0.h:176:7: note: C++0x ‘constexpr’ only available with -std=c++0x or -std=gnu++0x
/usr/include/c++/4.6/bits/atomic_0.h:455:7: error: ‘constexpr’ does not name a type
/usr/include/c++/4.6/bits/atomic_0.h:455:7: note: C++0x ‘constexpr’ only available with -std=c++0x or -std=gnu++0x
In file included from /usr/include/c++/4.6/atomic:43:0,
                 from /usr/local/include/boost/math/special_functions/detail/bernoulli_details.hpp:17,
                 from /usr/local/include/boost/math/special_functions/bernoulli.hpp:16,
                 from /usr/local/include/boost/math/special_functions/gamma.hpp:35,
                 from /usr/local/include/boost/math/special_functions/detail/bessel_jy.hpp:14,
                 from /usr/local/include/boost/math/special_functions/bessel.hpp:20,
                 from /usr/local/include/boost/math/special_functions/airy.hpp:12,
                 from /usr/local/include/boost/math/special_functions.hpp:15,
                 from /usr/local/include/boost/random/generate_canonical.hpp:22,
                 from /usr/local/include/boost/random.hpp:52,
                 from /home/anirudh/caffe-rc/src/caffe/util/math_functions.cpp:2:
/usr/include/c++/4.6/bits/atomic_2.h:143:7: error: ‘constexpr’ does not name a type
/usr/include/c++/4.6/bits/atomic_2.h:143:7: note: C++0x ‘constexpr’ only available with -std=c++0x or -std=gnu++0x
/usr/include/c++/4.6/bits/atomic_2.h:458:7: error: ‘constexpr’ does not name a type
/usr/include/c++/4.6/bits/atomic_2.h:458:7: note: C++0x ‘constexpr’ only available with -std=c++0x or -std=gnu++0x
In file included from /usr/local/include/boost/math/special_functions/detail/bernoulli_details.hpp:17:0,
                 from /usr/local/include/boost/math/special_functions/bernoulli.hpp:16,
                 from /usr/local/include/boost/math/special_functions/gamma.hpp:35,
                 from /usr/local/include/boost/math/special_functions/detail/bessel_jy.hpp:14,
                 from /usr/local/include/boost/math/special_functions/bessel.hpp:20,
                 from /usr/local/include/boost/math/special_functions/airy.hpp:12,
                 from /usr/local/include/boost/math/special_functions.hpp:15,
                 from /usr/local/include/boost/random/generate_canonical.hpp:22,
                 from /usr/local/include/boost/random.hpp:52,
                 from /home/anirudh/caffe-rc/src/caffe/util/math_functions.cpp:2:
/usr/include/c++/4.6/atomic:68:5: error: ‘constexpr’ does not name a type
/usr/include/c++/4.6/atomic:68:5: note: C++0x ‘constexpr’ only available with -std=c++0x or -std=gnu++0x
/usr/include/c++/4.6/atomic:167:7: error: ‘constexpr’ does not name a type
/usr/include/c++/4.6/atomic:167:7: note: C++0x ‘constexpr’ only available with -std=c++0x or -std=gnu++0x
/usr/include/c++/4.6/atomic:245:7: error: ‘constexpr’ does not name a type
/usr/include/c++/4.6/atomic:245:7: note: C++0x ‘constexpr’ only available with -std=c++0x or -std=gnu++0x
/usr/include/c++/4.6/atomic:428:7: error: ‘constexpr’ does not name a type
/usr/include/c++/4.6/atomic:428:7: note: C++0x ‘constexpr’ only available with -std=c++0x or -std=gnu++0x
/usr/include/c++/4.6/atomic:447:7: error: ‘constexpr’ does not name a type
/usr/include/c++/4.6/atomic:447:7: note: C++0x ‘constexpr’ only available with -std=c++0x or -std=gnu++0x
/usr/include/c++/4.6/atomic:466:7: error: ‘constexpr’ does not name a type
/usr/include/c++/4.6/atomic:466:7: note: C++0x ‘constexpr’ only available with -std=c++0x or -std=gnu++0x
/usr/include/c++/4.6/atomic:485:7: error: ‘constexpr’ does not name a type
/usr/include/c++/4.6/atomic:485:7: note: C++0x ‘constexpr’ only available with -std=c++0x or -std=gnu++0x
/usr/include/c++/4.6/atomic:504:7: error: ‘constexpr’ does not name a type
/usr/include/c++/4.6/atomic:504:7: note: C++0x ‘constexpr’ only available with -std=c++0x or -std=gnu++0x
/usr/include/c++/4.6/atomic:523:7: error: ‘constexpr’ does not name a type
/usr/include/c++/4.6/atomic:523:7: note: C++0x ‘constexpr’ only available with -std=c++0x or -std=gnu++0x
/usr/include/c++/4.6/atomic:542:7: error: ‘constexpr’ does not name a type
/usr/include/c++/4.6/atomic:542:7: note: C++0x ‘constexpr’ only available with -std=c++0x or -std=gnu++0x
/usr/include/c++/4.6/atomic:561:7: error: ‘constexpr’ does not name a type
/usr/include/c++/4.6/atomic:561:7: note: C++0x ‘constexpr’ only available with -std=c++0x or -std=gnu++0x
/usr/include/c++/4.6/atomic:580:7: error: ‘constexpr’ does not name a type
/usr/include/c++/4.6/atomic:580:7: note: C++0x ‘constexpr’ only available with -std=c++0x or -std=gnu++0x
/usr/include/c++/4.6/atomic:599:7: error: ‘constexpr’ does not name a type
/usr/include/c++/4.6/atomic:599:7: note: C++0x ‘constexpr’ only available with -std=c++0x or -std=gnu++0x
/usr/include/c++/4.6/atomic:618:7: error: ‘constexpr’ does not name a type
/usr/include/c++/4.6/atomic:618:7: note: C++0x ‘constexpr’ only available with -std=c++0x or -std=gnu++0x
/usr/include/c++/4.6/atomic:637:7: error: ‘constexpr’ does not name a type
/usr/include/c++/4.6/atomic:637:7: note: C++0x ‘constexpr’ only available with -std=c++0x or -std=gnu++0x
/usr/include/c++/4.6/atomic:656:7: error: ‘constexpr’ does not name a type
/usr/include/c++/4.6/atomic:656:7: note: C++0x ‘constexpr’ only available with -std=c++0x or -std=gnu++0x
/usr/include/c++/4.6/atomic:664:19: error: ‘char16_t’ was not declared in this scope
/usr/include/c++/4.6/atomic:664:27: error: template argument 1 is invalid
/usr/include/c++/4.6/atomic:665:5: error: expected class-name before ‘{’ token
/usr/include/c++/4.6/atomic:683:19: error: ‘char32_t’ was not declared in this scope
/usr/include/c++/4.6/atomic:683:27: error: template argument 1 is invalid
/usr/include/c++/4.6/atomic:684:5: error: expected class-name before ‘{’ token
make[2]: *** [src/caffe/CMakeFiles/caffe.dir/util/math_functions.cpp.o] Error 1
make[1]: *** [src/caffe/CMakeFiles/caffe.dir/all] Error 2
make: *** [all] Error 2

gcc version 4.6.3 (Ubuntu/Linaro 4.6.3-1ubuntu5)

ubuntu version - 12.04

**Comment by lukeyeager** [comment]
I believe this is a question better asked in the [user forum](https://groups.google.com/forum/#!forum/caffe-users).

**Comment by shelhamer** [comment]
Please ask installation questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) mailing list. Thanks!
