### ISSUE TITLE
cifar 10 - high prob scores for false positives

### ISSUE THREAD

**Issue by quadstreaming** [BVLC/caffe#1684]
I'm testing the cifar10 network and I have a problem related with the false positives, I use the dataset provided by caffe script, for training I run about 10000 iterations. Cifar10 has only 10 classes, if a feed some random images from other classes the probability score for this false positives is very high. e.g. 0.8 for class 1. 
I use the python wrapper to get the actual results computed the network. 
Did some else notice this kind of things ?

**Comment by sguada** [comment]
All questions about usage, installation, code, and applications should be searched for and asked on the [caffe-users mailing list](https://groups.google.com/forum/#!forum/caffe-users).
