### ISSUE TITLE
Switch LayerType to string for extensibility

### ISSUE THREAD

**Issue by shelhamer** [BVLC/caffe#1685]
**Originally proposed by @jeffdonahue**

The bookkeeping for the `LayerType` enum in `caffe.proto` is a hassle. Having a coordination-free method to add layers would make life easier and open up Caffe for extension in forks or a potential "sandbox" section of the project.

The layer type could just be the C++ class name of the layer, minus the "Layer" at the end. So, it would look like:

```
layers {
  name: "accuracy"
  class: "Accuracy"  # for class AccuracyLayer
  ...
}
```

Introducing the `class` field instead of `type` gives a signature for automatically upgrading net definitions like we've done in the past.

`LayerParameter` is another obstacle. Since these are actual fields they still require unique IDs. Any thoughts on a workaround?

@jeffdonahue @Yangqing @longjon

**Comment by longjon** [comment]
I wonder if it would be a good idea to coordinate this with #1474 and a new layer interface?

As an aside, I like the name `type` better than `class`, but so be it. Also consider `function` or `fun` or `fn`, although that might be confusing because our functions are implemented as classes.

**Comment by shelhamer** [comment]
Agreed on coordinating with #1474 and bringing up old musings on the One True Layer Interface.

> As an aside, I like the name type better than class

Yeah, me too. We can always come up with another signature to trigger the automagic upgrade.

**Comment by Yangqing** [comment]
I agree with Jon that "type" is a better name - I am a bit afraid of using a c++ reserved keyword.

RE parameters for specific layers, protobuf's extension is a good solution:

https://developers.google.com/protocol-buffers/docs/proto#extensions

We can add to LayerParameter something like "extensions 1000 to max" and individual users can choose their own extension number, which will hopefully conflict less. Of course there may be some popular numbers (1701?), but that would probably not be too bad.

**Comment by shelhamer** [comment]
Done by #1694.
