### ISSUE TITLE
Models state both unrestricted and non-commercial only license

### ISSUE THREAD

**Issue by auduno** [BVLC/caffe#1689]
The licenses for most of the models were recently changed to unrestricted use, but the tables in the readme.me for all of the models still state license as "non-commercial". Is this an oversight or intentional?

**Comment by shelhamer** [comment]
Thanks for catching that -- 7e465f2 fixes the BVLC model metadata to reflect the unrestricted license.

**Comment by bhack** [comment]
@shelhamer Is shared model license is  conformant with (opendefinition)[ http://opendefinition.org/licenses/]?

**Comment by bhack** [comment]
For example [libccv models](http://libccv.org/post/ccv-0.6-open-sources-near-state-of-the-art-image-classifier-under-creative-commons/)

**Comment by bhack** [comment]
I've opened a new thicket for this at https://github.com/BVLC/caffe/issues/1701
