### ISSUE TITLE
data consistency between C and Python 

### ISSUE THREAD

**Issue by kamikawa** [BVLC/caffe#1691]
Hi

My second request.
It took me a while to grasp a differece between "caffe train/test" command and python "classify.py" command.
I think that could cause mistakes of users and common data format should be supported.

1. Input data 
 C: database format ( leveldb etc, )
 python : image file

2. mean data
C: binary proto
python: numpy format

3. test phase model prototxt (as I mentioned previous topic)

Best regards.

**Comment by shelhamer** [comment]
The `caffe` command and `caffe` Python module can load exactly the same net to take the same type of inputs -- see https://github.com/BVLC/caffe/issues/1774. Doing so reproduces the same results with the command line and the `caffe.Net` interface in Python.

This should be documented better as noted by #1774.
