### ISSUE TITLE
Caffe compatibility with RHEL 6.5?

### ISSUE THREAD

**Issue by chrish42** [BVLC/caffe#1692]
I'm trying to install Caffe on a RHEL 6.5 (not my choice) cluster. I've been following the instructions for installing caffe (from the website), but when compiling, I get the following a bunch of "file not found" errors around src/caffe/util/io.cpp:6:33 searching for the following include files:

* opencv2/core/core.hpp
* opencv2/highgui/highgui.hpp
* opencv2/highgui/highgui_c.h
* opencv2/imgproc/imgproc.hpp

Looking in /usr/include, I don't have an opencv2 directory. I do have an opencv directory, but its organization differs significantly from what caffe's io.cpp expects. So, RHEL 6.5 ships with OpenCV 2.0. I guess Caffe needs a more recent version of OpenCV. Is it known what the minimum version of OpenCV required is? Any ideas on how to solve this? Is it possible to install easily a more recent version of OpenCV on RHEL 6.5? Is it possible to make Caffe compatible with OpenCV 2.0?

One way or another, it'd be nice if some way of getting Caffe running with RHEL 6 was documented on the "install" webpage. Or at least, it'd be nice if this problem was documented on said install webpage.

**Comment by shelhamer** [comment]
OpenCV >= 2.4 should work.

**Comment by shelhamer** [comment]
Please ask installation questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) mailing list. Thanks!

**Comment by chrish42** [comment]
Any plans to document the version requirement for OpenCV in the installation documentation? That would have saved me a fair bit of time. Thanks.

**Comment by shelhamer** [comment]
6af39c5 notes the version requirement for OpenCV.
