### ISSUE TITLE
Caffe Installation Problem

### ISSUE THREAD

**Issue by pnambiar** [BVLC/caffe#1693]
I'm have some issue installing caffe. Please let me know if you have a solution
make runtest
.build_release/test/test_all.testbin 0 --gtest_shuffle 
Cuda number of devices: 1
Setting to use device 0
Current device id: 0
Note: Randomizing tests' orders with a seed of 88789 .
[==========] Running 838 tests from 169 test cases.
[----------] Global test environment set-up.
[----------] 3 tests from ImageDataLayerTest/3, where TypeParam = caffe::DoubleGPU
[ RUN      ] ImageDataLayerTest/3.TestResize
F0107 14:26:04.664185  3079 math_functions.cpp:91] Check failed: error == cudaSuccess (11 vs. 0)  invalid argument
*** Check failure stack trace: ***
    @     0x2ab3f5243daa  (unknown)
    @     0x2ab3f5243ce4  (unknown)
    @     0x2ab3f52436e6  (unknown)
    @     0x2ab3f5246687  (unknown)
    @           0x6bdc35  caffe::caffe_copy<>()
    @           0x7439af  caffe::BasePrefetchingDataLayer<>::Forward_gpu()
    @           0x428da2  caffe::Layer<>::Forward()
    @           0x62ff53  caffe::ImageDataLayerTest_TestResize_Test<>::TestBody()
    @           0x657363  testing::internal::HandleExceptionsInMethodIfSupported<>()
    @           0x64de07  testing::Test::Run()
    @           0x64deae  testing::TestInfo::Run()
    @           0x64dfb5  testing::TestCase::Run()
    @           0x6512f8  testing::internal::UnitTestImpl::RunAllTests()
    @           0x651587  testing::UnitTest::Run()
    @           0x41d3a0  main
    @     0x2ab3f8396ec5  (unknown)
    @           0x4243d7  (unknown)
    @              (nil)  (unknown)
make: *** [runtest] Aborted (core dumped)

#############################################################################

Ubuntu 14.04

/$ lspci | grep -i nvidia
01:00.0 VGA compatible controller: NVIDIA Corporation G92GLM [Quadro FX 3800M] (rev a2)

/$ cat /proc/driver/nvidia/version
NVRM version: NVIDIA UNIX x86_64 Kernel Module  340.29  Thu Jul 31 20:23:19 PDT 2014
GCC version:  gcc version 4.8.2 (Ubuntu 4.8.2-19ubuntu1) 

/$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2014 NVIDIA Corporation
Built on Thu_Jul_17_21:41:27_CDT_2014
Cuda compilation tools, release 6.5, V6.5.12

################################################################################

**Comment by sguada** [comment]
All questions about usage, installation, code, and applications should be searched for and asked on the [caffe-users mailing list](https://groups.google.com/forum/#!forum/caffe-users).

**Comment by ravikrn** [comment]
I am having same issue. Did you guys found solution?
