### ISSUE TITLE
`make runtest` fails randomly on osx 10.9 with Illegal instruction: 4

### ISSUE THREAD

**Issue by mikedewar** [BVLC/caffe#1699]
`make all` and `make test` run successfully, but `make runtest` fails, seemingly at random, with `Illegal instruction: 4`. The tests often run for a few seconds, other times this error is triggered immediately. 

For example
```
[----------] 6 tests from NesterovSolverTest/1, where TypeParam = caffe::DoubleCPU
[ RUN      ] NesterovSolverTest/1.TestNesterovLeastSquaresUpdateWithWeightDecay
make: *** [runtest] Illegal instruction: 4
```
or
```
[----------] 2 tests from SoftmaxLayerTest/1, where TypeParam = caffe::DoubleCPU
[ RUN      ] SoftmaxLayerTest/1.TestGradient
make: *** [runtest] Illegal instruction: 4
```
or 
```
[----------] 3 tests from InnerProductLayerTest/0, where TypeParam = caffe::FloatCPU
[ RUN      ] InnerProductLayerTest/0.TestForward
make: *** [runtest] Illegal instruction: 4
```

I have installed Caffe following the OSX 10.9 instructions http://caffe.berkeleyvision.org/installation.html. I am using OpenBLAS, the latest CUDA, and had to set `DYLD_FALLBACK_LIBRARY_PATH := /usr/local/cuda/lib:/usr/local/lib:/usr/lib` to get `make runtest` to run at all.

**Comment by HiroakiMachida** [comment]
The reason it fails randomly is --gtest_shuffle option for "make test".

**Comment by mikedewar** [comment]
That makes sense. Would this be easier to diagnose if the tests were run in a fixed order? Or does this just prove that whatever causes this failure is caused all over the place?

**Comment by shelhamer** [comment]
`Illegal instruction: 4` usually indicates that there is a platform / compiler mismatch. Caffe must be compiled with clang++ and not g++ on OS X.

A note of encouragement: several of the core developers have run Caffe on OS X 10.9, so it can be done! Sorry to say I never ran into this failure though.

Please ask follow-up installation questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) mailing list. Thanks!
