### ISSUE TITLE
Opendefinition of BVLC model

### ISSUE THREAD

**Issue by bhack** [BVLC/caffe#1701]
Are models shared by BVLC conformant with [opendefinition](http://opendefinition.org/licenses/)?

**Comment by bhack** [comment]
See also licensing of [libccv models](http://libccv.org/post/ccv-0.6-open-sources-near-state-of-the-art-image-classifier-under-creative-commons/)

**Comment by shelhamer** [comment]
At a quick glance it seems they are -- we'll have to have a BVLC meeting to check. Thanks for pointing out standard licenses.

**Comment by bhack** [comment]
cc: @okfn If any feedback is needed.

**Comment by bhack** [comment]
See also [this](https://news.ycombinator.com/item?id=8296031). I really hope that a trained network must not be considered a derivate work.

**Comment by longjon** [comment]
We are not lawyers, but it seems almost certain that our license ("This model is released for unrestricted use.") is Open Definition compliant.

**Comment by bhack** [comment]
You don't need to be a lawyers to choiche BSD for the code. So probably releasing models under http://creativecommons.org/licenses/by/4.0/ could legally standardize the model usage rights.

**Comment by longjon** [comment]
If our current model license is problematic for anyone, I think we could consider releasing the models under additional licenses. However, I don't know how that's possible; the models are released for unrestricted use, like it says. As far as I know you could take the models and distribute them yourself under whatever license you like.
