### ISSUE TITLE
train_lenet.sh error : num_train_nets >= 1

### ISSUE THREAD

**Issue by htso** [BVLC/caffe#1707]
Hey guys, after a successful install (make all, make test, and make runtest), out of the gate I just ran the mnist example for the fun of it and got the following error. 

The mnist dataset is downloaded and converted alright, i think. I see a file named convert_mnist_data.bin in /caffe-master/build/examples/mnist. 

Any idea? 

My platform : ubuntu 12.04, boost 1.56.0, CUDA 6.5

rspace@GreatStuff:~/caffe-master/examples/mnist$ ./train_lenet.sh
I0111 15:28:28.218602  4731 caffe.cpp:99] Use GPU with device ID 0
I0111 15:28:28.351842  4731 caffe.cpp:107] Starting Optimization
I0111 15:28:28.352663  4731 solver.cpp:32] Initializing solver from parameters: 
F0111 15:28:28.352700  4731 solver.cpp:49] Check failed: num_train_nets >= 1 (0 vs. 1) SolverParameter must specify a train net using one of these fields: net, net_param, train_net, train_net_param
*** Check failure stack trace: ***
    @     0x7f480c767b7d  google::LogMessage::Fail()
    @     0x7f480c769c7f  google::LogMessage::SendToLog()
    @     0x7f480c76776c  google::LogMessage::Flush()
    @     0x7f480c76a51d  google::LogMessageFatal::~LogMessageFatal()
    @           0x492f85  caffe::Solver<>::InitTrainNet()
    @           0x493ef6  caffe::Solver<>::Init()
    @           0x494056  caffe::Solver<>::Solver()
    @           0x4274e0  caffe::GetSolver<>()
    @           0x423967  train()
    @           0x41e691  main
    @     0x7f4809a2d76d  (unknown)
    @           0x4224bd  (unknown)
Aborted (core dumped)

**Comment by shelhamer** [comment]
Please ask example questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) mailing list. Include the caffe branch / version and the solver configuration prototxt. This example works fine on master and dev.

**Comment by htso** [comment]
Evan, i think i posted the same question on caffe-users but have not seen
any response. Will repost.

Horace
