### ISSUE TITLE
Is there any tutorial about pycaffe?

### ISSUE THREAD

**Issue by tartavull** [BVLC/caffe#1708]
I want to learn to import data to lmdb.
I saw the c++ code for mnist, I was wondering if there is something similar using pycaffe

**Comment by shelhamer** [comment]
No, there isn't any further documentation than the tutorial docs on the Python interface and the docstrings. The new Python interface #1703 will mark a good occasion to add more examples and documentation. Meanwhile, check https://github.com/BVLC/caffe/issues/1698#issuecomment-70211045 for how to make LMDB data in Python.

**Comment by Franck-Dernoncourt** [comment]
I agree, that could be great to have some tutorial about pycaffe…

An interesting example (that used LMDB): http://nbviewer.ipython.org/github/joyofdata/joyofdata-articles/blob/master/deeplearning-with-caffe/Neural-Networks-with-Caffe-on-the-GPU.ipynb
