### ISSUE TITLE
Caffe with Cuda 6.5 on Ubuntu 14.04

### ISSUE THREAD

**Issue by canerhazirbas** [BVLC/caffe#1710]
Hi,

I have successfully compiled the caffe with cuda 6.5 on ubuntu 14.04. However, when I make runtest, I get the following error.

Major linking error

.build_release/test/test_all.testbin 0 --gtest_shuffle 
.build_release/test/test_all.testbin: error while loading shared libraries: libcudart.so.5.5: cannot open shared object file: No such file or directory
make: *** [runtest] Error 127

I have not linked cuda 5.5 anywhere, neither I have it on my .bashrc. I could not figure out what the actual problem is. Would be gratefull if you could help me ?

**Comment by beniz** [comment]
AFAIK, cuda 5.5 ships with Ubuntu 14.04. You need to remove it and hand-install cuda 6.5.

**Comment by canerhazirbas** [comment]
Hi, thanks for the answer; but there is no cuda 5.5 installed on my machine. And 6.5 is already hand-installed.

**Comment by bhack** [comment]
Please close this ticket and use the mailing list.

**Comment by canerhazirbas** [comment]
The answer is any dependency library compiled across different cuda version causes trouble. For my case it is DARWIN and OpenCV Libraries.
