### ISSUE TITLE
HDF5DataLayer and MemoryDataLayer silently doesn't do data transformations

### ISSUE THREAD

**Issue by shelhamer** [BVLC/caffe#1718]
The `HDF5_DATA` layer does not do transformations, since it is intended to be completely general w.r.t. the input data. However, setting transformation parameters is completely valid in the protobuf definition since `TransformationParameter` is nested in the layer message so it can be used across data layers.

`MEMORY_DATA` is more complicated as transformations are done for inputs added as `Datum` or `cv::Mat` but not for raw data taken by pointer through `reset()`.

They should complain or even die loudly so that users know this.

**Comment by boechat107** [comment]
Do you mean that, even I add a `transform_param` to a `HDF5_DATA` layer, no transformation is really applied to the data?

**Comment by shelhamer** [comment]
More-or-less addressed by #1841 and the follow-up to relax to a warning for `MemoryData`.
