### ISSUE TITLE
SLICE should be in-place

### ISSUE THREAD

**Issue by shelhamer** [BVLC/caffe#1719]
The `SLICE` layer should make its tops by indexing into the bottoms with the right shapes to save memory and time. Right now it copies on forward and backward.

@sguada this makes sense, right?

**Comment by shelhamer** [comment]
Oh, this of course won't work for channels. Forget it, nothing to see here...

**Comment by sguada** [comment]
Hi Evan,

It only makes sense for ´num´, but not sure if it is worthy or not to
handle that case.

Sergio

2015-01-13 17:20 GMT-08:00 Evan Shelhamer <notifications@github.com>:

**Comment by shelhamer** [comment]
Yeah you're totally right -- sorry I didn't give it a little more thought first. Thanks for checking Sergio.
