### ISSUE TITLE
Where is the implementing of the function  LayerSetUp?

### ISSUE THREAD

**Issue by iSawyer** [BVLC/caffe#1720]
Hi, I'm reading the source code of the layer class, where is the details of the function LayerSetUp? I can't find it in either layer.hpp or neuron_layers.hpp.

**Comment by HiroakiMachida** [comment]
https://github.com/BVLC/caffe/blob/master/src/caffe/layers/base_data_layer.cpp:17

This one?

**Comment by shelhamer** [comment]
`LayerSetUp` is implemented by each layer class. Method implementations are found in layer class cpp and not headers, like https://github.com/BVLC/caffe/blob/master/src/caffe/layers/dropout_layer.cpp#L13-L22.

If a layer doesn't need any setup -- like `ReLU` -- then the method is not implemented.
