### ISSUE TITLE
pixel labeling for scene understanding

### ISSUE THREAD

**Issue by jiangfeng15** [BVLC/caffe#1721]
Hi,everyone
    I have read some papers[1] about scene parsing with convolution networks, I am planning to implement semantic segmentation/scene parsing using convolutional networks.but I find none of the papers on this topic have released their source code,It is difficut to do the experiments of the papers[1]
if you work on this,can you provide me with some help! 

Look forward to hearing from you.
Thank you!

[1] Clement Farabet et al, "Learning Hierarchical Features for Scene Labeling", Pattern Analysis and Machine Intelligence

**Comment by shelhamer** [comment]
Please ask usage questions and how to model different tasks on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) mailing list.
