### ISSUE TITLE
How should I define the prototxt using the multi-label branch?

### ISSUE THREAD

**Issue by skyfeiyun** [BVLC/caffe#1723]
Dear sir @sguada .I'm now working on a project about human face classification, in which we define tens of labels for each face(each image). I'd like to use the multi-label branch, but there's several questions:
1. how should I define the input layer? should I just use the 'IMAGE_DATA' like in a normal single label? is there any additional parameters?
2. how about the loss layer and accuracy layer?which type and parameters should I use? I'd like to display multi-accuracy and for each label the value varies in {0,1} instead of {-1,0,1} by the way.
3. I'd like to finetune my model based on the bvlc_reference_caffenet, should I just change the prototxt file and run the command of finetune straightly?
thank you:)

**Comment by bhack** [comment]
@netheril96 @sguada Is this a mailing list question? Or this comment need to be moved on related PR?

**Comment by skyfeiyun** [comment]
besides, I'd like to ask is this version just fit for the Windows, not for Ubuntu?

**Comment by shelhamer** [comment]
Please ask compilation and usage questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) mailing list. Thanks!
