### ISSUE TITLE
Why MemoryDataLayer can't be used in the TEST phase of solver?

### ISSUE THREAD

**Issue by deepCNN** [BVLC/caffe#1727]
Hello, every author who contrbute to Caffe!  First I want to say thanks very much for your work, now I had a problem about the MemoryDataLayer. I can test a model in MemoryDataLayer, but when I train a model, it failed(I want to testing a model after training), I don't know why this happen, the reason why I post my question here is that I am not sure whether we need a new PR to solve this problem.  Thanks in advance!

**Comment by bhack** [comment]
You have opened already a thread on the mailinglist. Use that.
