### ISSUE TITLE
How  to set GPU'ID.when i use the interface of matlab of caffe?

### ISSUE THREAD

**Issue by wuqiangch** [BVLC/caffe#1729]
Ｉ　ｈａｖｅ　ｔｗｏ　ＧＰＵｓ（Ｋ４０），ｏｎｅ　ＧＰＵ　ｉｓ　ｕｓｅｄ　ｂｙ　ｍｙ　ｏｎｅ　ｃｏｌｌｅａｇｕｅ．　Ｉ　ｗａｎｔ　ｔｏ　ｕｓｅ　ａｎｏｔｈｅｒ　ＧＰＵ，ｂｕｔ　ｉ　ｄｏｎｔ　ｋｎｏｗ　ｈｏｗ　ｔｏ　ｓｅｔ　ｔｈｅ　ｇｐｕ＇ｉｄ．Ａｎｙｏｎｅ　ｃａｎ　ｈｅｌｐ　ｍｅ　？　Ｔｈａｎｋｓ　ｖｅｒｙ　ｍｕｃｈ．

**Comment by shelhamer** [comment]
Please ask usage questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) mailing list. Thanks!
