### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by xuhuazhe** [BVLC/caffe#1730]
Hi Dear fellow, 
I have just tried to compile caffe on an ubuntu machine. I think I got all the 3party dependency done. But still I got some errors. Does anyone know how to figure it out? 
Thanks a lot!
I have posted the errors below:

![ar e5q9 e7czv v4pw rice](https://cloud.githubusercontent.com/assets/8836001/5753841/8c8dc75a-9c6e-11e4-95ea-54e0da347970.png)

**Comment by shelhamer** [comment]
Please ask installation questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) mailing list. Thanks!
