### ISSUE TITLE
Caffe "Caffè"

### ISSUE THREAD

**Issue by bhack** [BVLC/caffe#1734]
@shelhamer  What do you think of adding a channel like [Gitter](https://gitter.im/) as an alternative to classic freenode irc channels used by many opensource projects?

**Comment by erogol** [comment]
I support the idea as a outsider even though this is not directed to me. I believe this ll ease the overwhelm of the issue page of the caffe project  and google groups stays so static and has no enough support I believe.

**Comment by shelhamer** [comment]
@bhack what advantage is there over the mailing list? Chat seems more ephemeral while the list is archived for searching. It seems like the mailing list + chat would just fracture conversation.

**Comment by bhack** [comment]
I think that the only real substitute for the community, of the BVLC face2face meetings, could be a more synchronous communication medium. This could also lower the noise/issue ratio on github ticketing system and help the community to support himself. Many open source (successful) projects have both irc/chat and mailing list. It is a totally different kind of community building and computer mediated communication on the interaction profile. It could be also very useful to open a gitter for developer discussions and weekly meetings.

**Comment by shelhamer** [comment]
We have made a gitter chat room at https://gitter.im/BVLC/caffe as suggested! Thanks for the pointer @bhack.
