### ISSUE TITLE
"make runtest" fails

### ISSUE THREAD

**Issue by yogaliew** [BVLC/caffe#1737]
.build_release/test/test_all.testbin 0 --gtest_shuffle --gtest_filter="-*GPU*"
dyld: Library not loaded: libhdf5_hl.8.dylib
  Referenced from: /Users/YogaLiew/Documents/caffe-master/.build_release/test/test_all.testbin
  Reason: image not found
make: *** [runtest] Trace/BPT trap: 5

Can anyone give me a hint?
Thanks!

**Comment by HiroakiMachida** [comment]
You should provide version information and etc.

"brew install hdf5" would fix it.

See this for more detail.
https://groups.google.com/d/msg/caffe-users/J5YlVnfoo4A/TKXx0QiqySwJ

**Comment by yogaliew** [comment]
Thank you HiroakiMachida!
Actually I've installed the hdf5 already. Inspired by your information, I checked /usr/local/lib and found libhdf5_hl.9.dylib instead of libhdf5_hl.8.dylib. So I just brutally change 9 to 8. And so far it works.
