### ISSUE TITLE
Separate dependencies for configurable installation

### ISSUE THREAD

**Issue by shelhamer** [BVLC/caffe#1738]
Caffe has dependencies that aren't necessarily universally needed especially when it comes to IO. The installation could be streamlined by making

- leveldb
- lmdb
- hdf5
- and even OpenCV

optional so that the Python or MATLAB interfaces can take care of IO or a client C++ library could handle input.

Of course there is an advantage to having a standard all-in build since input formats and portability can be counted on, but there are cases when it's overkill.

This would need a fleet of build flags and ifdef guards and is perhaps best left until the build has been standardized by work like #1667.

Note that this was first suggested by @kloudkl in #1074 but it was too early and at the time and the build needed to improve before turning our attention to separation.

**Comment by bhack** [comment]
As I stated some month ago when cmake was introduced in caffe it is better to support only one build system to avoid divergence between make tools and cmake and to not duplicate community and core members effort to maintain two build systems. Especially now that we have https://github.com/BVLC/caffe/pull/1667

**Comment by Nerei** [comment]
Excellent idea! Once cmake standardized and all switch it, I need one weekend to prepare PR and test all these features.

NB: nothing will bring so much popularity to your library as porting it to iOS. Optional dependencies with cmake is just one of steps required to reach this.

**Comment by bhack** [comment]
My original comment was here https://github.com/BVLC/caffe/pull/943. Also with only one build system we drastically reduce travis testing time of the build matrix.

**Comment by futurely** [comment]
#1074

**Comment by shelhamer** [comment]
Closed by #2523 for optional IO dependencies -- HDF5 was made a hard dependency by #2836.
