### ISSUE TITLE
pycaffe compilation & imagenet module

### ISSUE THREAD

**Issue by ienaplissken** [BVLC/caffe#1742]
After compiling caffe and pycaffe following the instructions in http://caffe.berkeleyvision.org/ (Ubuntu 14.04), I'm able to import caffe module. But caffe_master/python/caffe/imagenet folder doesn't contain any file, so when I call
`from caffe import imagenet`
I receive "no module named imagenet" and I can't use the ImageNetClassifier class.

I googled a bit and it seems that I'm the only one having such a problem. Any suggestion?

**Comment by seanbell** [comment]
The "python/caffe/imagenet" directory isn't a python package; you can't import it.  It just contains a data file (the mean image).

You probably want caffe.Classifier; see documentation and examples here: http://nbviewer.ipython.org/github/BVLC/caffe/blob/master/examples/classification.ipynb

**Comment by bhack** [comment]
Please close this and use the mailinglist

**Comment by shelhamer** [comment]
Make sure you are using a recent Caffe like the master or dev branches.

**Comment by ienaplissken** [comment]
Thanks a lot, I was following a kind of old doc: http://nbviewer.ipython.org/github/BVLC/caffe/blob/v0.99/examples/imagenet_pretrained.ipynb.

I will use the mailing list for further doubts.
