### ISSUE TITLE
Same training data, same iteration but models produces different results, is it a bug?

### ISSUE THREAD

**Issue by StevenLOL** [BVLC/caffe#1745]
Same training data, same iteration but models produce different results, is it a bug? Or it means I should train the model with more iteration?

Details:

Hi, I have 20 models trained on same 20K images.  Each time  I get different errors on development data (another 50K images). The error is in range of 0.5% ->2.5%  at same iteration eg (8500). Is it a bug? 
 
Indeed my very first model which is the best model gives err 0.5% . I test this best model, it works well on the development data as well as on other test cases( 40K images).

**Comment by bhack** [comment]
Please close this and use mailinglist for support.

**Comment by StevenLOL** [comment]
Sorry, I retrain 20 models, each gives me different results, so is it a bug?

**Comment by shelhamer** [comment]
No. Each model has a different random initialization so they will have
different task performance after training. Please use the mailing list.
