### ISSUE TITLE
inconsistency detected by ld.so

### ISSUE THREAD

**Issue by chenliangren** [BVLC/caffe#1750]
the total class number is 436, each class has 40~210 samples, the total samples is 70170. when caffe reach the 1040 iteration, it said: "inconsistency detected by ld.so: dl-tls.c: 426: _dl_allocate_tls_init: Assertion '(size_t) map->l_tls_offset>=map->l_tls_blocksize' failed!" But when I fix the each class samples number or remove the 436th class samples, that bug disappeared. I am so confused with this. I don't know what i am going to do.

**Comment by shelhamer** [comment]
This is usually a corrupted glibc / system issue. It's unlikely that this is Caffe's fault, and adding the class might just increase memory usage to cause the system problem.
