### ISSUE TITLE
convert mnist error

### ISSUE THREAD

**Issue by yogaliew** [BVLC/caffe#1751]
I think I've succeeded in compiling caffe because I passed make all, make test, and make runtest without any error notice. But I don't have the build/examples folder in the caffe.
Then I tried to download and convert MNIST dataset exactly as the Tutorial says:

caffe-master YogaLiew$ ./data/mnist/get_mnist.sh

Succeeded, but

caffe-master YogaLiew$ ./examples/mnist/create_mnist.sh
Creating lmdb...
./examples/mnist/create_mnist.sh: line 17: build/examples/mnist/convert_mnist_data.bin: No such file or directory
./examples/mnist/create_mnist.sh: line 19: build/examples/mnist/convert_mnist_data.bin: No such file or directory
Done.

Can anyone give me a hint?
Thanks!

**Comment by aymericdamien** [comment]
You can check in your Makefile.config that you have set build_dir to 'build':
BUILD_DIR := build

build is a symlink to directory .build_release, you can also check if .build_release exists, convert_mnist_data.bin should be inside.

**Comment by shelhamer** [comment]
Please ask installation / example questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) mailing list.

**Comment by GmZhang3** [comment]
hi,yogaliew ,do you solve this problem?

**Comment by garywangcn** [comment]
Please excuting ./examples/mnist/create_mnist.sh  under root directory of caffe, below log for you reference.

#:~/dl/caffe$ ./data/mnist/get_mnist.sh 
Downloading...
#:~/dl/caffe$ ./examples/mnist/create_mnist.sh 
Creating lmdb...
I1012 17:38:14.271512 30157 db_lmdb.cpp:35] Opened lmdb examples/mnist/mnist_train_lmdb
I1012 17:38:14.271659 30157 convert_mnist_data.cpp:88] A total of 60000 items.
I1012 17:38:14.271680 30157 convert_mnist_data.cpp:89] Rows: 28 Cols: 28
I1012 17:38:18.485410 30157 convert_mnist_data.cpp:108] Processed 60000 files.
I1012 17:38:18.512091 30159 db_lmdb.cpp:35] Opened lmdb examples/mnist/mnist_test_lmdb
I1012 17:38:18.512225 30159 convert_mnist_data.cpp:88] A total of 10000 items.
I1012 17:38:18.512233 30159 convert_mnist_data.cpp:89] Rows: 28 Cols: 28
I1012 17:38:19.202750 30159 convert_mnist_data.cpp:108] Processed 10000 files.

**Comment by KingfaLuis** [comment]
create_mnist.sh: line 17: build/examples/mnist/convert_mnist_data.bin: No such file or directory
