### ISSUE TITLE
Failed to parse bvlc_reference_caffenet.caffemodel

### ISSUE THREAD

**Issue by dvreed77** [BVLC/caffe#1760]
I am getting the following error:

```
Check failed: ReadProtoFromBinaryFile(param_file, param) Failed to parse NetParameter file: ../models/bvlc_reference_caffenet/bvlc_reference_caffenet.caffemodel
```

when attempting to run the classification.ipynb.

I have confirmed I have that file and am running this script from the correct place, because the rest of the paths are correct.  Does anyone have any ideas?

**Comment by mingtop** [comment]
me too!!!!

**Comment by shelhamer** [comment]
Please ask installation questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) mailing list -- pycaffe might be linked against a different version of protobuf.

**Comment by mingtop** [comment]
I fix it  by replace the data layer by 
four dimension blobs .
 Thank u very much!

**Comment by ducminhnguyen** [comment]
mingtop: how did you change the data layer, can you give me an example
