### ISSUE TITLE
cant draw bvlc_reference_rcnn_ilsvrc13 net graph,error:TypeError: must be string or buffer, not list

### ISSUE THREAD

**Issue by zdx3578** [BVLC/caffe#1763]
ubuntu@ip-172-30-0-198:/opt/caffeall/caffe$ python python/draw_net.py models/bvlc_reference_rcnn_ilsvrc13/deploy.prototxt  /tmp/t2.png
libdc1394 error: Failed to initialize libdc1394
/usr/lib/python2.7/dist-packages/pkg_resources.py:1031: UserWarning: /home/ubuntu/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
  warnings.warn(msg, UserWarning)
Couldn't import dot_parser, loading of dot files will not be possible.
Drawing net to /tmp/t2.png
Warning: /tmp/tmpimv_PI: syntax error in line 1 near '-'

Traceback (most recent call last):
  File "python/draw_net.py", line 25, in <module>
    main(sys.argv)
  File "python/draw_net.py", line 20, in main
    caffe.draw.draw_net_to_file(net, sys.argv[2])
  File "/opt/caffeall/caffe/python/caffe/draw.py", line 76, in draw_net_to_file
    fid.write(draw_net(caffe_net, ext))
TypeError: must be string or buffer, not list
ubuntu@ip-172-30-0-198:/opt/caffeall/caffe$

**Comment by zdx3578** [comment]
ubuntu@ip-172-30-0-198:/opt/caffeall/caffe$  python python/draw_net.py models/VGG_CNN_M_1024/f0f3d010e6d5f0100274/VGG_CNN_M_1024_deploy.prototxt modelsarchs/VGG_CNN_M_1024_deploy.png
libdc1394 error: Failed to initialize libdc1394
/usr/lib/python2.7/dist-packages/pkg_resources.py:1031: UserWarning: /home/ubuntu/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
  warnings.warn(msg, UserWarning)
Traceback (most recent call last):
  File "python/draw_net.py", line 25, in <module>
    main(sys.argv)
  File "python/draw_net.py", line 18, in main
    text_format.Merge(open(sys.argv[1]).read(), net)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 158, in Merge
    _MergeField(tokenizer, message)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 236, in _MergeField
    _MergeField(tokenizer, sub_message)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 210, in _MergeField
    message_descriptor.full_name, name))
google.protobuf.text_format.ParseError: 34:1 : Message type "caffe.LayerParameter" has no field named "layers".

**Comment by zdx3578** [comment]
ubuntu@ip-172-30-0-198:/opt/caffeall/caffe$ python python/draw_net.py  models/Places205-CNN/places205CNN_deploy.prototxt  modelsarchs/places205CNN_deploy.png           libdc1394 error: Failed to initialize libdc1394
/usr/lib/python2.7/dist-packages/pkg_resources.py:1031: UserWarning: /home/ubuntu/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
  warnings.warn(msg, UserWarning)
Drawing net to modelsarchs/places205CNN_deploy.png
Warning: /tmp/tmpEH6VHP: syntax error in line 1 near '-'

Traceback (most recent call last):
  File "python/draw_net.py", line 25, in <module>
    main(sys.argv)
  File "python/draw_net.py", line 20, in main
    caffe.draw.draw_net_to_file(net, sys.argv[2])
  File "/opt/caffeall/caffe/python/caffe/draw.py", line 76, in draw_net_to_file
    fid.write(draw_net(caffe_net, ext))
TypeError: must be string or buffer, not list

**Comment by shelhamer** [comment]
Check your Python and protobuf installation -- ask Caffe-specific questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) mailing list.

**Comment by alfredtofu** [comment]
Hi, have you solve it?
