### ISSUE TITLE
error: ‘class caffe::Solver<float>’ has no member named ‘Step’    solver_->Step(1);

### ISSUE THREAD

**Issue by AjayTalati** [BVLC/caffe#1764]
Hi, I'm trying to build a project which use caffe. When I make, I get the following error

ajay@ajay-h8-1170uk:~/CppProjects/dqn-in-the-caffe-master/build$ make
Scanning dependencies of target dqn
[ 50%] Building CXX object CMakeFiles/dqn.dir/dqn_main.cpp.o
In file included from /home/ajay/CppProjects/dqn-in-the-caffe-master/dqn_main.cpp:3:0:
/usr/local/ale_cpp/ale_0.4.4/ale_0_4/src/ale_interface.hpp:124:28: warning: ‘auto_ptr’ is deprecated (declared at /usr/include/c++/4.8/backward/auto_ptr.h:87) [-Wdeprecated-declarations]
     std::auto_ptr<OSystem> theOSystem;
                            ^
/usr/local/ale_cpp/ale_0.4.4/ale_0_4/src/ale_interface.hpp:125:29: warning: ‘auto_ptr’ is deprecated (declared at /usr/include/c++/4.8/backward/auto_ptr.h:87) [-Wdeprecated-declarations]
     std::auto_ptr<Settings> theSettings;
                             ^
/usr/local/ale_cpp/ale_0.4.4/ale_0_4/src/ale_interface.hpp: In function ‘void createOSystem(int, char**, std::auto_ptr<OSystem>&, std::auto_ptr<Settings>&)’:
/usr/local/ale_cpp/ale_0.4.4/ale_0_4/src/ale_interface.hpp:84:49: warning: ignoring return value of ‘FILE* freopen(const char*, const char*, FILE*)’, declared with attribute warn_unused_result [-Wunused-result]
         freopen(outputFile.c_str(), "w", stdout);
                                                 ^
[100%] Building CXX object CMakeFiles/dqn.dir/dqn.cpp.o
In file included from /home/ajay/CppProjects/dqn-in-the-caffe-master/dqn.hpp:9:0,
                 from /home/ajay/CppProjects/dqn-in-the-caffe-master/dqn.cpp:1:
/usr/local/ale_cpp/ale_0.4.4/ale_0_4/src/ale_interface.hpp:124:28: warning: ‘auto_ptr’ is deprecated (declared at /usr/include/c++/4.8/backward/auto_ptr.h:87) [-Wdeprecated-declarations]
     std::auto_ptr<OSystem> theOSystem;
                            ^
/usr/local/ale_cpp/ale_0.4.4/ale_0_4/src/ale_interface.hpp:125:29: warning: ‘auto_ptr’ is deprecated (declared at /usr/include/c++/4.8/backward/auto_ptr.h:87) [-Wdeprecated-declarations]
     std::auto_ptr<Settings> theSettings;
                             ^
/home/ajay/CppProjects/dqn-in-the-caffe-master/dqn.cpp: In member function ‘void dqn::DQN::Update()’:
/home/ajay/CppProjects/dqn-in-the-caffe-master/dqn.cpp:350:12: error: ‘class caffe::Solver<float>’ has no member named ‘Step’
   solver_->Step(1);
            ^
make[2]: *** [CMakeFiles/dqn.dir/dqn.cpp.o] Error 1
make[1]: *** [CMakeFiles/dqn.dir/all] Error 2
make: *** [all] Error 2

I can't find anything on the internet about this one

**Comment by bhack** [comment]
Please ask building support questions to the mailinglist and close this ticket.

**Comment by AjayTalati** [comment]
Sorry, I did'nt know that was the procedure
