### ISSUE TITLE
`pooling_layer.cu` incorrect computation of index

### ISSUE THREAD

**Issue by hotpxl** [BVLC/caffe#1768]
Code [here](https://github.com/BVLC/caffe/blob/master/src/caffe/layers/pooling_layer.cu#L31).

During every loop iteration, the amount `bottom_data` changes differ.

**Comment by shelhamer** [comment]
No, the code is correct -- each step of the unrolled loop is computing its index (`bottom_data` is the same for each so the needed offset is calculated and added).

**Comment by shelhamer** [comment]
See #2493 for the fix -- while this bug is currently hidden since all the loops only execute once this deserves fixing. Thanks for the report @hotpxl.
