### ISSUE TITLE
Convolution issue with hdf5

### ISSUE THREAD

**Issue by olddocks** [BVLC/caffe#1769]
What is the issue here? I feed images from hdf5 to convolution layer and seems not working.

```I0121 18:44:25.625943  3346 net.cpp:96] Setting up conv1
F0121 18:44:25.886196  3346 blob.cpp:13] Check failed: height >= 0 (-3 vs. 0) ```

This is the original output
```
$ ./facialkp.sh
I0121 18:44:24.394758  3346 caffe.cpp:103] Use CPU.
I0121 18:44:24.762547  3346 caffe.cpp:107] Starting Optimization
I0121 18:44:24.762717  3346 solver.cpp:32] Initializing solver from parameters: 
base_lr: 0.01
display: 100
max_iter: 10000
lr_policy: "step"
gamma: 0.1
momentum: 0.9
weight_decay: 0.0005
stepsize: 5000
snapshot: 10000
snapshot_prefix: "/home/pbu/Desktop/tmp"
solver_mode: CPU
net: "/home/pbu/Desktop/facialkp.prototxt"
I0121 18:44:24.762830  3346 solver.cpp:67] Creating training net from net file: /home/pbu/Desktop/facialkp.prototxt
I0121 18:44:24.763418  3346 net.cpp:275] The NetState phase (0) differed from the phase (1) specified by a rule in layer data
I0121 18:44:24.763582  3346 net.cpp:39] Initializing net from parameters: 
name: "LogReg"
layers {
  top: "data"
  top: "label"
  name: "fkp"
  type: HDF5_DATA
  hdf5_data_param {
    source: "train.txt"
    batch_size: 100
  }
  include {
    phase: TRAIN
  }
}
layers {
  bottom: "data"
  top: "conv1"
  name: "conv1"
  type: CONVOLUTION
  blobs_lr: 1
  blobs_lr: 2
  convolution_param {
    num_output: 64
    kernel_size: 5
    stride: 1
    weight_filler {
      type: "xavier"
    }
    bias_filler {
      type: "constant"
    }
  }
}
layers {
  bottom: "conv1"
  top: "pool1"
  name: "pool1"
  type: POOLING
  pooling_param {
    pool: MAX
    kernel_size: 2
    stride: 2
  }
}
layers {
  bottom: "pool1"
  top: "conv2"
  name: "conv2"
  type: CONVOLUTION
  blobs_lr: 1
  blobs_lr: 2
  convolution_param {
    num_output: 256
    kernel_size: 5
    stride: 1
    weight_filler {
      type: "xavier"
    }
    bias_filler {
      type: "constant"
    }
  }
}
layers {
  bottom: "conv2"
  top: "pool2"
  name: "pool2"
  type: POOLING
  pooling_param {
    pool: MAX
    kernel_size: 2
    stride: 2
  }
}
layers {
  bottom: "pool2"
  top: "ip1"
  name: "ip1"
  type: INNER_PRODUCT
  blobs_lr: 1
  blobs_lr: 2
  inner_product_param {
    num_output: 500
    weight_filler {
      type: "xavier"
    }
    bias_filler {
      type: "constant"
    }
  }
}
layers {
  bottom: "ip1"
  top: "ip1"
  name: "relu1"
  type: RELU
}
layers {
  bottom: "ip1"
  top: "ip2"
  name: "ip2"
  type: INNER_PRODUCT
  blobs_lr: 1
  blobs_lr: 2
  inner_product_param {
    num_output: 30
    weight_filler {
      type: "xavier"
    }
    bias_filler {
      type: "constant"
    }
  }
}
layers {
  bottom: "ip2"
  bottom: "label"
  top: "loss"
  name: "loss"
  type: EUCLIDEAN_LOSS
}
state {
  phase: TRAIN
}
I0121 18:44:24.764245  3346 net.cpp:67] Creating Layer fkp
I0121 18:44:24.764274  3346 net.cpp:356] fkp -> data
I0121 18:44:24.764314  3346 net.cpp:356] fkp -> label
I0121 18:44:24.764351  3346 net.cpp:96] Setting up fkp
I0121 18:44:24.764372  3346 hdf5_data_layer.cpp:57] Loading filename from train.txt
I0121 18:44:24.764480  3346 hdf5_data_layer.cpp:69] Number of files: 1
I0121 18:44:24.764509  3346 hdf5_data_layer.cpp:29] Loading HDF5 filefacialkp-train.hd5
I0121 18:44:25.625666  3346 hdf5_data_layer.cpp:49] Successully loaded 4934 rows
I0121 18:44:25.625735  3346 hdf5_data_layer.cpp:81] output data size: 100,9216,1,1
I0121 18:44:25.625778  3346 net.cpp:103] Top shape: 100 9216 1 1 (921600)
I0121 18:44:25.625800  3346 net.cpp:103] Top shape: 100 30 1 1 (3000)
I0121 18:44:25.625844  3346 net.cpp:67] Creating Layer conv1
I0121 18:44:25.625871  3346 net.cpp:394] conv1 <- data
I0121 18:44:25.625905  3346 net.cpp:356] conv1 -> conv1
I0121 18:44:25.625943  3346 net.cpp:96] Setting up conv1
F0121 18:44:25.886196  3346 blob.cpp:13] Check failed: height >= 0 (-3 vs. 0) 
```

**Comment by bhack** [comment]
Please, can you move this thread on the mailinglist?

**Comment by shelhamer** [comment]
Check the top shapes! The HDF5 data was saved with dimensions 100 x 9216 x 1 x 1 per batch so there's of course no way to convolve a 5 x 5 filter on this input with singleton height and width dimensions.

```
I0121 18:44:24.764509  3346 hdf5_data_layer.cpp:29] Loading HDF5 filefacialkp-train.hd5
I0121 18:44:25.625666  3346 hdf5_data_layer.cpp:49] Successully loaded 4934 rows
I0121 18:44:25.625735  3346 hdf5_data_layer.cpp:81] output data size: 100,9216,1,1
I0121 18:44:25.625778  3346 net.cpp:103] Top shape: 100 9216 1 1 (921600)
I0121 18:44:25.625800  3346 net.cpp:103] Top shape: 100 30 1 1 (3000)
```

@olddocks follow-up on and please ask usage questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) mailing list.

**Comment by dineshresearch** [comment]
change the batch_size = 1 in SegNet/SegNet-Tutorial-master/Models/segnet_train.prototxt will solve the problem.It is caused because of using different height and width for the images
