### ISSUE TITLE
Unsupervised Learning using AutoEncoder

### ISSUE THREAD

**Issue by lorrybrooks** [BVLC/caffe#1770]
Hi guys,
   As far as I have understood, the mnist tutorial on auto encoder converts mnist data to 28x28 single channel image and store it as lmdb  which is then used for training.  When i use the same mnist_autoencoder.prototxt and its solver.prototxt to use my 256x256 with 3 channel images lmdb, I am getting error that the number of neurons mismatch. I would like to do it for 256x256 3 channel image just like the supervised learning methods. It would be very helpful if you could give me an heads up on what needs to be done.

**Comment by mingtop** [comment]
I also meet the problem when train a gray cifar's lmdb, I changed the number of last neural numbers, I fixed the problem.
You can draw you net's by  pycaffe's  
draw.py   /***you.prototxt   younet.png

**Comment by ashokrbp** [comment]
But is this how it is supposed to be done? Can we not use crop size param to change the input layers as we do with supervised learning?

**Comment by longjon** [comment]
Please ask usage questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) list. Thanks!
