### ISSUE TITLE
solver_mode: CPU is ignored when gpu flag provided

### ISSUE THREAD

**Issue by Russell91** [BVLC/caffe#1771]
It seems that this may have been by design, but it really is quite confusing to have the GPU code run when you specify solver_mode: CPU. Often times you change the solver.prototxt to use CPU, but you happen to use a command from your bash history that specified the --gpu flag, and you end up getting the gpu code by accident. It seems like the solver_mode: CPU should take priority over any other details. Not my call, but I think it should be discussed.

**Comment by longjon** [comment]
This was discussed at #925 and fixed to its current behavior in #961.

The consensus was that `solver_mode` shouldn't really be in `solver.prototxt`, and that the command line flag should take priority if it is. I agree with that view... the command line is more immediate, and should override things written down in config files somewhere.

**Comment by Russell91** [comment]
Right, but the problem is that no one expects a command line flag used to specify the gpu device to also specify the cpu/gpu mode. The tutorials explicitly recommend using the solver.prototxt to specify the mode. One only encounters the --gpu flag when they need to specify a device. And then later they get the spooky behavior where changing the solver_mode stops working.

**Comment by longjon** [comment]
The tutorials may be out-of-date in this regard, but if I specify `--gpu 6` on the command line, I do expect to run on a GPU, specifically number 6. In my mind, the mode is a spurious level of abstraction; one wants to specify a device, which is either `CPU` or `GPU` plus an integer.

**Comment by shelhamer** [comment]
As suspected by @Russell91 , and as summarized by @longjon, this is working as expected. I've updated [the tutorial slide](https://docs.google.com/presentation/d/1UeKXVgRvvxg9OUdh_UiC5G71UMscNPlvArsWER41PsU/edit#slide=id.g38b6d86c6_47) to suggest the command line arg and not the `solver_mode` field in the configuration.
