### ISSUE TITLE
Synchronization of multiple data layers

### ISSUE THREAD

**Issue by leiucky** [BVLC/caffe#1778]
My work takes image triplets as input (query image, positive image and negative image). And each image has its own network (similar work [1]). 

![qq 20150122160751](https://cloud.githubusercontent.com/assets/4113735/5852396/f111bc30-a250-11e4-837d-c138fdd84909.png)

In the official tutorial, it says that Caffe supports multiple inputs (data layers). However, I wonder that whether there is synchronization problem? 

For example,
input1:
query_image1   label1
query_image2   label2
query_image3   label3

input2:
positive_image1  label1
positive_image2  label2
positive_image3  label3

input3:
negative_image1 lable1
negative_image2 lable2
negative_image3 lable3

Now I put these three dataset as three data layers. Ideally, query_image1, positive_image1  and  negative_image1 should be a set of training data. 
Would they be shuffled in the training process?  For example, taking query_image1, positive_image2  and  negative_image3 as a set of training data.

Is there some better solutions of my issues?

Thanks.

[1] Jiang Wang, Yang Song, Thomas Leung, Chuck Rosenberg, JingBin Wang, James Philbin, Bo Chen, Ying Wu, "Learning Fine-grained Image Similarity with Deep Ranking", CVPR 2014.

**Comment by leiucky** [comment]
moreover, is it okay if one of layers is a vector of numbers instead of an image.

**Comment by bhack** [comment]
Please ask modelling question to the mailinglist.

**Comment by shelhamer** [comment]
Please ask on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) mailing list. The input for the data layers needs to be synchronized, so the same shuffling should be done for each data source.
