### ISSUE TITLE
MemoryDataLayer does not apply transform_params.

### ISSUE THREAD

**Issue by erogol** [BVLC/caffe#1784]
I try to load data by using Python Net interface but as far as I see from the results MemoryDataLayer does not apply given transformation parameters, most importantly subtracting mean file. It should at least work like ImageDataLayer in order to resolve the image preprocessing issues in Python interface.

**Comment by DmitryUlyanov** [comment]
I confirm that, at least you can specify crop_size = 5 for example but nothing will happen at all, while I expect a mess.

**Comment by vpestret** [comment]
There is no way using memory data layer from python in dev branch at least, what are you talking about?

**Comment by futurely** [comment]
There's no longer such a problem in the latest master branch. The following code snippet outputs the correct answers.
```python
batch_size = 10
net_data_size = (224, 224)

test_images_files = [some, test, image, files]
label_words = [load, the, label, words, such, as, the, ILSVRC, synset, words]
test_images = [cv2.imread(x) for x in test_images_files]
test_images = [cv2.resize(x, net_data_size, fx = 0, fy = 0,
                     interpolation = cv2.INTER_CUBIC) for x in test_images]
## Swap (height, width, channels) into (channels, height, width) which is required by the net
test_images = [np.swapaxes(x, 0, 2) for x in test_images]
test_images = [np.swapaxes(x, 1, 2) for x in test_images]
index = 0
while len(test_images) < batch_size:
    test_images.append(test_images[index % len(test_images)])
    index += 1
test_x = np.array(test_images)
test_y = np.array([1] * batch_size)

model_file = 'googlenet_deploy.prototxt'
trained_model = 'bvlc_googlenet.caffemodel'
feature_layer_name = 'prob'
net = caffe.Net(model_file, trained_model, caffe.TEST)   
net.set_input_arrays(test_x.astype(np.float32), test_y.astype(np.float32))
net.forward()
features = net.blobs[feature_layer_name].data.copy()
max_features = np.argmax(features, axis = 1)
for x in max_features:
    print label_words[x]
```

**Comment by dkozlov** [comment]
@futurely , but you manually have resized these images

> `test_images = [cv2.resize(x, net_data_size, fx = 0, fy = 0,
                     interpolation = cv2.INTER_CUBIC) for x in test_images]`

**Comment by shelhamer** [comment]
Closing according to #5528. Otherwise unsupported cases such as this should be caught by `CHECK`s that explain and crash.
