### ISSUE TITLE
How to reshape a blob?

### ISSUE THREAD

**Issue by TorosFanny** [BVLC/caffe#1788]
How to reshape a blob of the shape N x C x H x W to N x 1 x (C*H) x W?

I want to make a convolution layer the weights of which are identical between channels.

One way I come up with is to reshape the bottom blob of the shape N x C x H x W to N x 1 x (C*H) x W and place a convolution layer upon it. But I just don't know how to reshape a blob.

Please help me out, thank you.

**Comment by bhack** [comment]
Please ask support to the mailinglist.

**Comment by shelhamer** [comment]
Please ask usage questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) mailing list.
