### ISSUE TITLE
Access mean image size (data_mean_) from outside Caffe's code to resize input image before feeding to MemoryDataLayer

### ISSUE THREAD

**Issue by GiuliaP** [BVLC/caffe#1791]
Hi,

I'm using a very similar code to the feature_extraction.cpp example, except that I'm using a MEMORY_DATA layer because I already have the images in memory instead of saved on disk.

As pointed out in issue #1614, according to the current implementation of the MemoryDataLayer, the image fed to the network must be resized to the same size of the mean image to be subtracted, by hand, before calling the method AddDatumVector (or AddMatVector if one uses pull request number #1416).

However, I cannot find any way of accessing the information about the size of the mean image from outside Caffe's code.

Indeed, the image is loaded at the initialization of the network from the .binaryproto file into a Blob called data_mean_, that is contained in the MemoryDataLayer's DataTransformer protected data member and there are no methods to access it.

The MemoryDataLayer's TransformationParameter indeed only contains the name of the .binaryproto file of the mean.

Is there any way of getting the size of the mean image without reading again from this file?

Giulia

**Comment by shelhamer** [comment]
You can check the channel, height, and width dimensions of the `MemoryDataLayer`'s top blob. The blobs can retrieved by `Net::blob_by_name()` so if the layer's top is `data` you can access that blob and then call `blob->channels()` and so on for the dimensions.

**Comment by GiuliaP** [comment]
Thanks! Sorry just another question... In case there is cropping (as in my case), how can this info be retrieved? At present I'm reading from the .binaryproto when the net is initialized.

**Comment by patrickflavel** [comment]
Hi @GiuliaP,
Did you manage to find a way of getting the size of the binaryproto mean image?
Thanks
