### ISSUE TITLE
incompatibility with cudnn v2-rc2

### ISSUE THREAD

**Issue by xinkang** [BVLC/caffe#1792]
I am compiling using cuDNN v2-rc2 on Mac OS X and got the following errors.  It looks that cuDNN changed some functions as well as arguments.  Does anyone know how to solve this problem?  Thanks a lot!

Best,
Ben

In file included from src/caffe/blob.cpp:1:
In file included from ./include/caffe/blob.hpp:4:
In file included from ./include/caffe/common.hpp:18:
In file included from ./include/caffe/util/device_alternate.hpp:40:
./include/caffe/util/cudnn.hpp:59:32: error: unknown type name 'cudnnTensor4dDescriptor_t'; did you mean 'cudnnTensorDescriptor_t'?
inline void createTensor4dDesc(cudnnTensor4dDescriptor_t* desc) {
                               ^~~~~~~~~~~~~~~~~~~~~~~~~
                               cudnnTensorDescriptor_t
/Users/ben/lib/cudnn-6.5-osx-v2-rc2/cudnn.h:107:42: note: 'cudnnTensorDescriptor_t' declared here
typedef struct cudnnTensorStruct*        cudnnTensorDescriptor_t;
                                         ^
In file included from src/caffe/blob.cpp:1:
In file included from ./include/caffe/blob.hpp:4:
In file included from ./include/caffe/common.hpp:18:
In file included from ./include/caffe/util/device_alternate.hpp:40:
./include/caffe/util/cudnn.hpp:60:15: error: use of undeclared identifier 'cudnnCreateTensor4dDescriptor'; did you mean 'cudnnCreateTensorDescriptor'?
  CUDNN_CHECK(cudnnCreateTensor4dDescriptor(desc));
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
              cudnnCreateTensorDescriptor
./include/caffe/util/cudnn.hpp:11:28: note: expanded from macro 'CUDNN_CHECK'
    cudnnStatus_t status = condition; \
                           ^
/Users/ben/lib/cudnn-6.5-osx-v2-rc2/cudnn.h:122:27: note: 'cudnnCreateTensorDescriptor' declared here
cudnnStatus_t CUDNNWINAPI cudnnCreateTensorDescriptor( cudnnTensorDescriptor_t   *tensorDesc );
                          ^
In file included from src/caffe/blob.cpp:1:
In file included from ./include/caffe/blob.hpp:4:
In file included from ./include/caffe/common.hpp:18:
In file included from ./include/caffe/util/device_alternate.hpp:40:
./include/caffe/util/cudnn.hpp:64:29: error: unknown type name 'cudnnTensor4dDescriptor_t'; did you mean 'cudnnTensorDescriptor_t'?
inline void setTensor4dDesc(cudnnTensor4dDescriptor_t* desc,
                            ^~~~~~~~~~~~~~~~~~~~~~~~~
                            cudnnTensorDescriptor_t
/Users/ben/lib/cudnn-6.5-osx-v2-rc2/cudnn.h:107:42: note: 'cudnnTensorDescriptor_t' declared here
typedef struct cudnnTensorStruct*        cudnnTensorDescriptor_t;
                                         ^
In file included from src/caffe/blob.cpp:1:
In file included from ./include/caffe/blob.hpp:4:
In file included from ./include/caffe/common.hpp:18:
In file included from ./include/caffe/util/device_alternate.hpp:40:
./include/caffe/util/cudnn.hpp:72:29: error: unknown type name 'cudnnTensor4dDescriptor_t'; did you mean 'cudnnTensorDescriptor_t'?
inline void setTensor4dDesc(cudnnTensor4dDescriptor_t* desc,
                            ^~~~~~~~~~~~~~~~~~~~~~~~~
                            cudnnTensorDescriptor_t
/Users/ben/lib/cudnn-6.5-osx-v2-rc2/cudnn.h:107:42: note: 'cudnnTensorDescriptor_t' declared here
typedef struct cudnnTensorStruct*        cudnnTensorDescriptor_t;
                                         ^
In file included from src/caffe/blob.cpp:1:
In file included from ./include/caffe/blob.hpp:4:
In file included from ./include/caffe/common.hpp:18:
In file included from ./include/caffe/util/device_alternate.hpp:40:
./include/caffe/util/cudnn.hpp:97:5: error: unknown type name 'cudnnTensor4dDescriptor_t'; did you mean 'cudnnTensorDescriptor_t'?
    cudnnTensor4dDescriptor_t bottom, cudnnFilterDescriptor_t filter,
    ^~~~~~~~~~~~~~~~~~~~~~~~~
    cudnnTensorDescriptor_t
/Users/ben/lib/cudnn-6.5-osx-v2-rc2/cudnn.h:107:42: note: 'cudnnTensorDescriptor_t' declared here
typedef struct cudnnTensorStruct*        cudnnTensorDescriptor_t;
                                         ^
In file included from src/caffe/blob.cpp:1:
In file included from ./include/caffe/blob.hpp:4:
In file included from ./include/caffe/common.hpp:18:
In file included from ./include/caffe/util/device_alternate.hpp:40:
./include/caffe/util/cudnn.hpp:99:15: error: use of undeclared identifier 'cudnnSetConvolutionDescriptor'
  CUDNN_CHECK(cudnnSetConvolutionDescriptor(*conv, bottom, filter,
              ^
./include/caffe/util/cudnn.hpp:11:28: note: expanded from macro 'CUDNN_CHECK'
    cudnnStatus_t status = condition; \
                           ^
./include/caffe/util/cudnn.hpp:112:13: error: use of undeclared identifier 'CUDNN_POOLING_AVERAGE'; did you mean 'CUDNN_POOLING_MAX'?
    *mode = CUDNN_POOLING_AVERAGE;
            ^~~~~~~~~~~~~~~~~~~~~
            CUDNN_POOLING_MAX
/Users/ben/lib/cudnn-6.5-osx-v2-rc2/cudnn.h:518:5: note: 'CUDNN_POOLING_MAX' declared here
    CUDNN_POOLING_MAX     = 0,
    ^
In file included from src/caffe/blob.cpp:1:
In file included from ./include/caffe/blob.hpp:4:
In file included from ./include/caffe/common.hpp:18:
In file included from ./include/caffe/util/device_alternate.hpp:40:
./include/caffe/util/cudnn.hpp:118:15: error: use of undeclared identifier 'cudnnSetPoolingDescriptor'; did you mean 'cudnnSetPoolingNdDescriptor'?
  CUDNN_CHECK(cudnnSetPoolingDescriptor(*conv, *mode, h, w,
              ^~~~~~~~~~~~~~~~~~~~~~~~~
              cudnnSetPoolingNdDescriptor
./include/caffe/util/cudnn.hpp:11:28: note: expanded from macro 'CUDNN_CHECK'
    cudnnStatus_t status = condition; \
                           ^
/Users/ben/lib/cudnn-6.5-osx-v2-rc2/cudnn.h:546:27: note: 'cudnnSetPoolingNdDescriptor' declared here
cudnnStatus_t CUDNNWINAPI cudnnSetPoolingNdDescriptor(  cudnnPoolingDescriptor_t poolingDesc,
                          ^
In file included from src/caffe/blob.cpp:1:
In file included from ./include/caffe/blob.hpp:4:
In file included from ./include/caffe/common.hpp:18:
In file included from ./include/caffe/util/device_alternate.hpp:40:
./include/caffe/util/cudnn.hpp:118:58: error: cannot initialize a parameter of type 'const int *' with an lvalue of type 'int'
  CUDNN_CHECK(cudnnSetPoolingDescriptor(*conv, *mode, h, w,
                                                         ^
./include/caffe/util/cudnn.hpp:11:28: note: expanded from macro 'CUDNN_CHECK'
    cudnnStatus_t status = condition; \
                           ^
/Users/ben/lib/cudnn-6.5-osx-v2-rc2/cudnn.h:549:67: note: passing argument to parameter 'windowDimA' here
                                                        const int windowDimA[],
                                                                  ^
9 errors generated.
make: *** [.build_release/src/caffe/blob.o] Error 1

**Comment by bhack** [comment]
Please close this issue and subscribe to https://github.com/BVLC/caffe/pull/1731 if you want.

**Comment by shelhamer** [comment]
See #1739 for a cuDNN v2 rc2 compatible branch.
