### ISSUE TITLE
CaffeReference model raises "Check failed: error == cudaSuccess (9 vs. 0)  invalid configuration argument" for batch size > 100

### ISSUE THREAD

**Issue by erogol** [BVLC/caffe#1793]
I am working on a workstation with Tesla C2075. Any reason for that error? I looked for GPU memory overflow but batch szei 100 allocates only2/5 of the memory

**Comment by shelhamer** [comment]
Ask hardware questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) mailing list. This GPU likely doesn't have enough blocks / threads for a kernel for that batch size.

**Comment by shelhamer** [comment]
This is addressed on the installation page's [hardware questions](http://caffe.berkeleyvision.org/installation.html#hardware-questions). Caffe requires compute capability > 2.0 as configured.

**Comment by mrgloom** [comment]
`Check failed: error == cudaSuccess (9 vs. 0)  invalid configuration argument`  Seems this kind of error occur on old hardware, I tested it on `Tesla M2090`, but even if I have enough memory at some point inreasing batch size produce this kind of non informative error.

**Comment by KangolHsu** [comment]
@mrgloom the same error
