### ISSUE TITLE
can't add model as weights into a new model

### ISSUE THREAD

**Issue by mingtop** [BVLC/caffe#1795]
first, I train a 3 layers autoencoder and get a weights  1024*2048 /2048 * 1024
then , I want to stacked autoencoder ,so a train a stacked auto encouder 1024~2048~1024~2028~1024. I want fill the first weights I trained in step1 into step2's stacked autoencoder. I used the --weights in an ***.sh file to train.
but , when I finished the train, I got this:
*********
optimization Done.
./examples/test5/test2.sh: 6: ./examples/test5/test2.sh: --weights=examples/test5/cifar_test2_modify.caffemodel: not found

-----------------------
please help me~

**Comment by mingtop** [comment]
And I am sure my folder has that file

**Comment by shelhamer** [comment]
This is just a shell scripting error and not about Caffe -- the script loads from the current working directory.
