### ISSUE TITLE
A question related to the cnn training model 

### ISSUE THREAD

**Issue by dongguangyao** [BVLC/caffe#1797]
Dear SIr:
 I draw lessons from the model proposed by the DeepID. As the result, the framework could be concluded as follows:
 input layer：50 3 118 82
conv1: 50 20 115 79 
relu1:  50 20 115 79
pool1: 50 20 58 40
conv2: 50 40 56 38
relu2: 50 40 56 38
pool2: 50 40 28 19
conv3: 50 60 27 18
relu3: 50 60 27 18
pool3: 50 60 14 9 
conv4: 50 80 13 8
ip1: 50 160 1 1 
ip2: 50 5424 1 1
  However, it indicates that the loss always remains nan. Could somebody give me some suggestions？

**Comment by bhack** [comment]
Please close this ticket and use the mailing list.

**Comment by dongguangyao** [comment]
Ok, I will close that and ask it in the mailing list.
