### ISSUE TITLE
Duplicate of closed Issue #782 - numpy-skimage issue

### ISSUE THREAD

**Issue by swamiviv** [BVLC/caffe#1803]
I did a completely new install of caffe and compiled using ccmake instead of editing the makefile manually. I had no problems in the compilation. The compilation was in CPU mode and I built pycaffe too by setting the BUILD_PYTHON_LIBS flag to ON. I did "make runtest" and had no errors.

Then, I used this to try the feature extraction part:
http://caffe.berkeleyvision.org/gathered/examples/feature_extraction.html

I was able to do it with the given in-built network without any trouble. Next, for visualizing the filters I wanted to use the python interface as said here:

http://nbviewer.ipython.org/github/BVLC/caffe/blob/master/examples/filter_visualization.ipynb

Before running this piece of code, I set the PYTHONPATH variable to contain '/python' as said in the previous comment. I store the visualization code as 'visualize.py' in the '/examples' directory. Now I go to my home directory and run the 'visualize.py' script from there. If I do that, I got this error:

ImportError: No module named _caffe

Instead, If I add '/python/caffe' to my PYTHONPATH variable, I get this error:

File "/usr/lib/python2.7/dist-packages/numpy/init.py", line 153, in 
from . import add_newdocs
File "/usr/lib/python2.7/dist-packages/numpy/add_newdocs.py", line 13, in 
from numpy.lib import add_newdoc
File "/usr/lib/python2.7/dist-packages/numpy/lib/init.py", line 22, in 
from .npyio import *
File "/usr/lib/python2.7/dist-packages/numpy/lib/npyio.py", line 4, in 
from . import format
File "/usr/lib/python2.7/dist-packages/numpy/lib/format.py", line 141, in 
import io
File "/home/swami/packages_local/caffe/python/caffe/io.py", line 2, in 
import skimage.io
File "/usr/local/lib/python2.7/dist-packages/skimage/init.py", line 171, in 
from .util.dtype import *
File "/usr/local/lib/python2.7/dist-packages/skimage/util/init.py", line 1, in 
from .dtype import (img_as_float, img_as_int, img_as_uint, img_as_ubyte,
File "/usr/local/lib/python2.7/dist-packages/skimage/util/dtype.py", line 8, in 
dtype_range = {np.bool_: (False, True),
AttributeError: 'module' object has no attribute 'bool_'

Where am I going wrong here ?

**Comment by shelhamer** [comment]
@swamiviv don't open duplicates! Keep to #782 and read carefully -- this is entirely a problem with your PYTHONPATH.

**Comment by chrisite** [comment]
if you setting up PYTHONPATH didn't work for you , make sure you add this line before importing caffe
import sys
sys.path.insert(0,"/home/christie/downloaded_libraries/caffe/python")
You should replace the path with your own path.(Make sure your path doesn't look like /whatever/caffe/python/caffe)
if you can't run pycaffe , your build was unsuccessful and fix up that first!

**Comment by rnsandeep** [comment]
Upgrading numpy solved the issue.

**Comment by kunsa** [comment]
how to Upgrading numpy？
