### ISSUE TITLE
Autoencoder Model Testing

### ISSUE THREAD

**Issue by lorrybrooks** [BVLC/caffe#1809]
I created a model using autoencoder using the mnist_autoencoder.prototxt. But I have problems evaluating the model. How do I test the model? Previously for other models, I use classifer.py or tools/caffe test to test the model. But both of them throw errors when I feed in the autoencoder model. What is the model supposed to output?

**Comment by rohrbach** [comment]
Please ask usage questions on [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) -- this issues tracker is primarily for Caffe development discussion. Thanks!
