### ISSUE TITLE
 Why no accuracy output?

### ISSUE THREAD

**Issue by tjusxh** [BVLC/caffe#1810]
Before net,
I0129 11:03:41.127631 26709 net.cpp:208] This network produces output accuracy
I0129 11:03:41.127640 26709 net.cpp:208] This network produces output loss

But another new net as follow.But only
I0129 11:06:57.912511 27467 net.cpp:208] This network produces output loss
layers {
  name: "accuracy"
  type: ACCURACY
  bottom: "fc8"
  bottom: "label"
  top: "accuracy"
  include: { phase: TEST }
}
why occur the question?

**Comment by shelhamer** [comment]
Ask usage questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) mailing list. The `include: { phase: TEST }` line indicates that the layer should only be included for the test net.
