### ISSUE TITLE
Does Caffe support multiple object detection, and if yes, how ?

### ISSUE THREAD

**Issue by waelHamdan** [BVLC/caffe#1811]
I couldn't find this functionality, and I was thinking that Caffe supports it

Thanks in Advance

**Comment by erogol** [comment]
I guess this is google-users question but net-surgery example might be good for you.  http://nbviewer.ipython.org/github/BVLC/caffe/blob/master/examples/net_surgery.ipynb

**Comment by waelHamdan** [comment]
Thank you very much for your answer.
So if we have multiples objects in the same pictures, let's say cat and dog, the example will still give the prediction for both objects

**Comment by erogol** [comment]
Yes, at least you can have little changes to do so.

**Comment by waelHamdan** [comment]
Thank you

**Comment by bhack** [comment]
Please close this and use the mailing list.
