### ISSUE TITLE
 error: When build the Caffe on Ubuntu 14.04 with GPU

### ISSUE THREAD

**Issue by ErnstHowie** [BVLC/caffe#1822]
I get following errors: 

g++ .build_release/tools/dump_network.o .build_release/lib/libcaffe.a -o .build_release/tools/dump_network.bin -fPIC -DNDEBUG -O2 -DUSE_CUDNN -I/usr/include/python2.7 -I/usr/lib/python2.7/dist-packages/numpy/core/include -I/usr/local/include -I.build_release/src -I./src -I./include -I/usr/local/cuda/include -Wall -Wno-sign-compare -L/usr/lib -L/usr/local/lib -L/usr/lib -L/usr/local/cuda/lib64 -L/usr/local/cuda/lib -lcudart -lcublas -lcurand -lglog -lgflags -lprotobuf -lleveldb -lsnappy -llmdb -lboost_system -lhdf5_hl -lhdf5 -lopencv_core -lopencv_highgui -lopencv_imgproc -lpthread -lboost_thread -lcudnn -lcblas -latlas
/usr/lib/x86_64-linux-gnu/libgflags.so: undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)@GLIBCXX_3.4.20'
collect2: error: ld returned 1 exit status
Makefile:494: recipe for target '.build_release/tools/dump_network.bin' failed
make: *** [.build_release/tools/dump_network.bin] Error 1

I am a beginner for the Caffe and Linux. I have no any idea. If anyone know how to solve this error, please help me! Thanks very much!

**Comment by stray-leone** [comment]
How about trying 'make clean' and make sequence ??

**Comment by ErnstHowie** [comment]
@stray-leone Thanks a lot. I reinstall the libgflags-dev, then make it pass.
