### ISSUE TITLE
Applying pre-trained caffe model in Java

### ISSUE THREAD

**Issue by benjaminklein** [BVLC/caffe#1823]
I would like to apply a pre-trained caffe model to images using Java.
Does someone have any idea how to do it?

I want for the code to run on CPU only and I don't want to install caffe on the machine on which the model will be run. I want that the model will work out-of-the-box so I will be able to pack it in a Jar without worrying about dependencies.

**Comment by bhack** [comment]
There was a jni based effort referenced at https://github.com/BVLC/caffe/issues/1641.

**Comment by futurely** [comment]
Great news! Bytedeco has just released their Java binding.
https://github.com/bytedeco/javacpp-presets/tree/master/caffe
http://mvnrepository.com/artifact/org.bytedeco.javacpp-presets/caffe
```
<dependency>
	<groupId>org.bytedeco.javacpp-presets</groupId>
	<artifactId>caffe</artifactId>
	<version>master-0.11</version>
</dependency>
```

**Comment by futurely** [comment]
https://github.com/bytedeco/javacpp-presets/issues/34

**Comment by benjaminklein** [comment]
Thank you for the news! 

Do you understand if one could also use this in order to classify images with an existing (pre-trained) model of caffe. For example - download the VGG model (http://www.robots.ox.ac.uk/~vgg/research/very_deep/), load it in Java and use your code in order to classify new images? Could you give a code example of how do to this?

Thank you.

**Comment by futurely** [comment]
https://github.com/bytedeco/javacpp-presets/tree/master/caffe#the-srcmainjavacaffejava-source-file

**Comment by longjon** [comment]
Please use [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) for this kind of discussion and other usage issues. Thanks!
