### ISSUE TITLE
Boost command not found

### ISSUE THREAD

**Issue by jaythegenius48** [BVLC/caffe#1824]
I installed boost and then ran this command on my MAC OS yosemite.

boost snappy leveldb protobuf gflags glog szip lmdb homebrew/science/opencv

It gives this error:
-bash: boost: command not found

And also make pycaffe gives error saying "'boost/shared_ptr.hpp' file not found"

**Comment by Nazanin84** [comment]
I got the same error. Were you able to solve it?
