### ISSUE TITLE
Improve Model Zoo Interface

### ISSUE THREAD

**Issue by shelhamer** [BVLC/caffe#1827]
The model zoo scripts aren't too friendly and kind of hidden, so they should more conveniently take any gist url that includes the user + hash and have an easy step-by-step tutorial + be included in a notebook example.

**Comment by longjon** [comment]
An additional note: the current link path from caffe.berkeleyvision.org to the actual model zoo page is difficult and should be made much more obvious.

**Comment by shelhamer** [comment]
Counting this as closed by #5537 even though it only adjusts the documentation to better point out the zoo.
