### ISSUE TITLE
Installing Caffe on Yosemite 10.10

### ISSUE THREAD

**Issue by katerakelly** [BVLC/caffe#1830]
I am on OS X Yosemite 10.10, using Anaconda Python, Boost 1.56, OpenCV 2.4.10 (using Homebrew to install everything).
I followed the installation instructions on the website for OS X 10.9, but used the new Makefile found in 1740.
I am compiling CPU only version, and I do not have CUDA installed (so I also did not do all the home-brew formula editing specified in the installation instructions)
I also tried the solution detailed here: https://groups.google.com/forum/#!searchin/caffe-users/how$20to$20run$20caffe$20on$20yosemite/caffe-users/J5YlVnfoo4A/em_HV11oA-8J which did not work.
Here is my compiler error. It seems to complain about OpenCV, among other things, but OpenCV seems to work fine on its own.
Sorry for the wall of text, but here goes:

~/caffe-master$ make all
LD .build_release/src/caffe/proto/caffe.pb.o
/usr/bin/clang++ -shared -o .build_release/lib/libcaffe.so .build_release/src/caffe/proto/caffe.pb.o .build_release/src/caffe/proto/caffe_pretty_print.pb.o .build_release/src/caffe/blob.o .build_release/src/caffe/common.o .build_release/src/caffe/data_transformer.o .build_release/src/caffe/internal_thread.o .build_release/src/caffe/layer_factory.o .build_release/src/caffe/layers/absval_layer.o .build_release/src/caffe/layers/accuracy_layer.o .build_release/src/caffe/layers/argmax_layer.o .build_release/src/caffe/layers/base_data_layer.o .build_release/src/caffe/layers/bnll_layer.o .build_release/src/caffe/layers/concat_layer.o .build_release/src/caffe/layers/contrastive_loss_layer.o .build_release/src/caffe/layers/conv_layer.o .build_release/src/caffe/layers/cudnn_conv_layer.o .build_release/src/caffe/layers/cudnn_pooling_layer.o .build_release/src/caffe/layers/cudnn_relu_layer.o .build_release/src/caffe/layers/cudnn_sigmoid_layer.o .build_release/src/caffe/layers/cudnn_softmax_layer.o .build_release/src/caffe/layers/cudnn_tanh_layer.o .build_release/src/caffe/layers/data_layer.o .build_release/src/caffe/layers/dropout_layer.o .build_release/src/caffe/layers/dummy_data_layer.o .build_release/src/caffe/layers/eltwise_layer.o .build_release/src/caffe/layers/euclidean_loss_layer.o .build_release/src/caffe/layers/flatten_layer.o .build_release/src/caffe/layers/hdf5_data_layer.o .build_release/src/caffe/layers/hdf5_output_layer.o .build_release/src/caffe/layers/hinge_loss_layer.o .build_release/src/caffe/layers/im2col_layer.o .build_release/src/caffe/layers/image_data_layer.o .build_release/src/caffe/layers/infogain_loss_layer.o .build_release/src/caffe/layers/inner_product_layer.o .build_release/src/caffe/layers/loss_layer.o .build_release/src/caffe/layers/lrn_layer.o .build_release/src/caffe/layers/memory_data_layer.o .build_release/src/caffe/layers/multinomial_logistic_loss_layer.o .build_release/src/caffe/layers/mvn_layer.o .build_release/src/caffe/layers/neuron_layer.o .build_release/src/caffe/layers/pooling_layer.o .build_release/src/caffe/layers/power_layer.o .build_release/src/caffe/layers/relu_layer.o .build_release/src/caffe/layers/sigmoid_cross_entropy_loss_layer.o .build_release/src/caffe/layers/sigmoid_layer.o .build_release/src/caffe/layers/silence_layer.o .build_release/src/caffe/layers/slice_layer.o .build_release/src/caffe/layers/softmax_layer.o .build_release/src/caffe/layers/softmax_loss_layer.o .build_release/src/caffe/layers/split_layer.o .build_release/src/caffe/layers/tanh_layer.o .build_release/src/caffe/layers/threshold_layer.o .build_release/src/caffe/layers/window_data_layer.o .build_release/src/caffe/net.o .build_release/src/caffe/solver.o .build_release/src/caffe/syncedmem.o .build_release/src/caffe/util/benchmark.o .build_release/src/caffe/util/im2col.o .build_release/src/caffe/util/insert_splits.o .build_release/src/caffe/util/io.o .build_release/src/caffe/util/math_functions.o .build_release/src/caffe/util/upgrade_proto.o -stdlib=libstdc++ -pthread -fPIC -DNDEBUG -O2 -DCPU_ONLY -I/Users/rakelly/anaconda/include -I/usr/local/include -I.build_release/src -I./src -I./include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/Accelerate.framework/Versions/Current/Frameworks/vecLib.framework/Headers/ -Wall -Wno-sign-compare -Wno-unneeded-internal-declaration -framework Accelerate -L/Users/rakelly/anaconda/lib -L/usr/local/lib -L/usr/lib -L.build_release/lib  -lglog -lgflags -lprotobuf -lleveldb -lsnappy -llmdb -lboost_system -lhdf5_hl -lhdf5 -lm -lopencv_core -lopencv_highgui -lopencv_imgproc -lboost_thread-mt -lcblas
clang: warning: argument unused during compilation: '-pthread'
Undefined symbols for architecture x86_64:
  "cv::imread(std::string const&, int)", referenced from:
      caffe::WindowDataLayer<float>::InternalThreadEntry() in window_data_layer.o
      caffe::WindowDataLayer<double>::InternalThreadEntry() in window_data_layer.o
      caffe::ReadImageToDatum(std::string const&, int, int, int, bool, caffe::Datum*) in io.o
  "google::protobuf::MessageLite::ParseFromString(std::string const&)", referenced from:
      caffe::DataLayer<float>::DataLayerSetUp(std::vector<caffe::Blob<float>*, std::allocator<caffe::Blob<float>*> > const&, std::vector<caffe::Blob<float>*, std::allocator<caffe::Blob<float>*> >*) in data_layer.o
      caffe::DataLayer<float>::InternalThreadEntry() in data_layer.o
      caffe::DataLayer<double>::DataLayerSetUp(std::vector<caffe::Blob<double>*, std::allocator<caffe::Blob<double>*> > const&, std::vector<caffe::Blob<double>*, std::allocator<caffe::Blob<double>*> >*) in data_layer.o
      caffe::DataLayer<double>::InternalThreadEntry() in data_layer.o
      caffe::Net<float>::Forward(std::string const&, float*) in net.o
      caffe::Net<double>::Forward(std::string const&, double*) in net.o
  "leveldb::DB::Open(leveldb::Options const&, std::string const&, leveldb::DB**)", referenced from:
      caffe::DataLayer<float>::DataLayerSetUp(std::vector<caffe::Blob<float>*, std::allocator<caffe::Blob<float>*> > const&, std::vector<caffe::Blob<float>*, std::allocator<caffe::Blob<float>*> >*) in data_layer.o
      caffe::DataLayer<double>::DataLayerSetUp(std::vector<caffe::Blob<double>*, std::allocator<caffe::Blob<double>*> > const&, std::vector<caffe::Blob<double>*, std::allocator<caffe::Blob<double>*> >*) in data_layer.o
  "google::protobuf::MessageLite::SerializeToString(std::string*) const", referenced from:
      caffe::Net<float>::Forward(std::string const&, float*) in net.o
      caffe::Net<double>::Forward(std::string const&, double*) in net.o
  "google::protobuf::Message::SerializeToOstream(std::ostream*) const", referenced from:
      caffe::WriteProtoToBinaryFile(google::protobuf::Message const&, char const*) in io.o
  "std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::__init(char const*, unsigned long)", referenced from:
      caffe::protobuf_AssignDesc_caffe_2eproto() in caffe.pb.o
      caffe::protobuf_AddDesc_caffe_2eproto() in caffe.pb.o
      caffe::protobuf_AssignDesc_caffe_5fpretty_5fprint_2eproto() in caffe_pretty_print.pb.o
  "std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::assign(char const*, unsigned long)", referenced from:
      caffe::Datum::MergeFrom(caffe::Datum const&) in caffe.pb.o
      caffe::FillerParameter::MergeFrom(caffe::FillerParameter const&) in caffe.pb.o
      caffe::FillerParameter::Clear() in caffe.pb.o
      caffe::NetParameter::MergeFrom(caffe::NetParameter const&) in caffe.pb.o
      caffe::SolverParameter::MergeFrom(caffe::SolverParameter const&) in caffe.pb.o
      caffe::SolverParameter::Clear() in caffe.pb.o
      caffe::SolverState::MergeFrom(caffe::SolverState const&) in caffe.pb.o
      ...
  "std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::basic_string(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)", referenced from:
      caffe::FillerParameter::MergePartialFromCodedStream(google::protobuf::io::CodedInputStream*) in caffe.pb.o
      caffe::SolverParameter::MergePartialFromCodedStream(google::protobuf::io::CodedInputStream*) in caffe.pb.o
      caffe::WindowDataParameter::MergePartialFromCodedStream(google::protobuf::io::CodedInputStream*) in caffe.pb.o
      caffe::V0LayerParameter::MergePartialFromCodedStream(google::protobuf::io::CodedInputStream*) in caffe.pb.o
  "std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::~basic_string()", referenced from:
      caffe::protobuf_AssignDesc_caffe_2eproto() in caffe.pb.o
      caffe::protobuf_ShutdownFile_caffe_2eproto() in caffe.pb.o
      caffe::Datum::~Datum() in caffe.pb.o
      caffe::Datum::SharedDtor() in caffe.pb.o
      caffe::FillerParameter::~FillerParameter() in caffe.pb.o
      caffe::FillerParameter::SharedDtor() in caffe.pb.o
      caffe::NetParameter::~NetParameter() in caffe.pb.o
      ...
  "std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::operator=(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)", referenced from:
      void google::protobuf::internal::RepeatedPtrFieldBase::MergeFrom<google::protobuf::RepeatedPtrField<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >::TypeHandler>(google::protobuf::internal::RepeatedPtrFieldBase const&) in caffe.pb.o
      void google::protobuf::internal::RepeatedPtrFieldBase::MergeFrom<google::protobuf::RepeatedPtrField<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >::TypeHandler>(google::protobuf::internal::RepeatedPtrFieldBase const&) in caffe_pretty_print.pb.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [.build_release/lib/libcaffe.so] Error 1

**Comment by RenfengLiu** [comment]
I had the same problem and haven't been solved yet.

**Comment by HiroakiMachida** [comment]
Use protobuf version 2.6.1

Brew edit protobuf and
modify url and sha1 to 
  url 'https://github.com/google/protobuf/releases/download/v2.6.1/protobuf-2.6.1.tar.bz2'
  sha1 '6421ee86d8fb4e39f21f56991daa892a3e8d314b'

**Comment by katerakelly** [comment]
These are the current url and sha1 that I have already.

**Comment by pannous** [comment]
> "std::__1::basic_string, std::__1::allocator >::basic_string(std::__1::basic_string, std::__1::allocator > const&)", referenced from:

probably the standard libstdc++ vs libc++ problem
Wait one week or search the threads+forum

**Comment by shelhamer** [comment]
See #1740 and the recent https://github.com/BVLC/caffe/commit/33a56e08d9a2714c2492bb7999a350636ed142be that defaults the Yosemite installation to libc++ so that everything works by default without the surgery on homebrew formulae. This does mean that all the dependencies need to be returned to normal however if you've previously installed Caffe with the libstdc++ workaround for older CUDA.

You can drop and restore the dependencies by

```
    for x in snappy leveldb gflags glog szip hdf5 lmdb homebrew/science/opencv; do brew uninstall $x; brew install --fresh -vd $x; done
    brew uninstall --force protobuf; brew install --with-python --fresh -vd protobuf
    brew uninstall boost boost-python; brew install --fresh -vd boost boost-python
```

then `make clean` followed by a `make && make test && make runtest` should be alright. Please follow-up on the caffe-users mailing list.
