### ISSUE TITLE
Why my classified result is the same?Including the scores,Using the Mnist example.

### ISSUE THREAD

**Issue by greatgao** [BVLC/caffe#1831]
I had trained my image data by modifing the mnist example.What my task is to divide my data into 2 categories.And I modified the  "convert_mnist_data.cpp" which in the mnist folder to formate my data(1 channel) as leveldb,and the other content is the same to the turtorial about training the MNIST .But when I called the classify.py ,the same output I GET!Yes, no matter which image inputted ,the same result dispearing. 
The result is always is:[('noLine', '0.78390'), ('SegLine', '0.21079')]

I don't know how to deal with the problem.How could I do?
PS:to apology for my English ability.....

**Comment by erictzeng** [comment]
Some things to look at:
- Have you checked your leveldb to make sure your data is well formatted?
- Is your loss going down?
- Is your validation accuracy doing something reasonable?

Please ask usage questions on [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) -- the issues tracker is primarily for Caffe development discussion.
