### ISSUE TITLE
how to debug caffe?

### ISSUE THREAD

**Issue by whjxnyzh** [BVLC/caffe#1832]
I want to know how to debug caffe step by step. I can not find the main function

**Comment by BlGene** [comment]
Hi,

have a look at ./tools/caffe.cpp, otherwise try using GDB, for example:
gdb --args ../../install/tools/caffe train --solver=testNet_solver.prototxt

**Comment by whjxnyzh** [comment]
gdb: unrecognized option '--solver=.......................

**Comment by whjxnyzh** [comment]
Reading symbols from /public/home/kli/caffe/.build_release/tools/caffe...(no debugging symbols found)...done.
what's wrong?

**Comment by BlGene** [comment]
You have to compile caffe with debug symbols, in your cmake integrate this line:

set(CMAKE_CXX_FLAGS_DEBUG ${CMAKE_CXX_FLAGS_DEBUG} )#set debug flags here)

This is a general gcc/gdb question, you are probably better off having a look around stackoverflow and co for help on this kind of stuff.

**Comment by whjxnyzh** [comment]
Thank you very much, BIGene. I am not very familiar with linux

**Comment by BlGene** [comment]
Wait, I messed up I updated my previous comment.

BR, Max

**Comment by BlGene** [comment]
resolved

**Comment by shelhamer** [comment]
How to debug C++ in general is out of scope for this, but thanks @BlGene for pointing out that the debug mode of the build needs to be turned on. Please discuss Caffe-specific gdb questions on caffe-users.

**Comment by zeakey** [comment]
@whjxnyzh I have a [post](http://zhaok.xyz/blog/post/debug-caffe/) on this, hope it help.
