### ISSUE TITLE
different crop_size for width and height?

### ISSUE THREAD

**Issue by graphitash** [BVLC/caffe#1834]
When defining an image transformation in a protobuf file. is there a way to set a rectangular crop size, i.e. a separate size for width and height? I can only see how to set a single crop size for both width and height as in AlexNet.

**Comment by lukeyeager** [comment]
Sadly, no. Caffe only supports square crops in the [protobuf definition](https://github.com/BVLC/caffe/blob/e3c895baac64c7c2da4f30ab7ae35a1c84e63733/src/caffe/proto/caffe.proto#L351) at the moment.

**Comment by ChenglongChen** [comment]
To achieve that, you have to modify the data layer and replace crop_size with crop_height and crop_width as discussed in: https://github.com/BVLC/caffe/issues/284
But I have no luck with it so far :(

**Comment by nmerrill67** [comment]
I have a working crop_width and crop_height in [my fork](https://github.com/nmerrill67/caffe). However, if you have to specify crop_width and crop_height even if they are equal in my patch.

**Comment by magomezs** [comment]
I have a python layer to make rectangular cropping in caffe
Please see: https://github.com/magomezs/data_augmentation_layers
