### ISSUE TITLE
Stochastic pooling layer: using a multinomial distribution based on activation values instead of a uniform distribution

### ISSUE THREAD

**Issue by ShriramKumar** [BVLC/caffe#1843]
As I have understood it the code for a stochastic pooling layer uses random sampling to select elements. Another approach would be to sample using a multinomial distribution with probabilities derived from the activation values. (normalized appropriately of course)

Reference: http://www.matthewzeiler.com/pubs/iclr2013/iclr2013.pdf

1)Am I right in about the pooling layer using random sampling?
2) Is there an existing way to do multinomial sampling?
2) If not this would be a good addition?

**Comment by erictzeng** [comment]
1) Yes.
2) No, but we certainly wouldn't mind having an implementation!

@longjon Thoughts?

**Comment by ob29** [comment]
As I went through the code, I think it already does so. To generate a number from a given probability distribution, you'll need to generate a random number in (0,1) which is then fed to inverse of the cumulative distribution. 
float thres = rand_idx[index] * cumsum;
this handles the generating a random number in (0, cumsum)
the next loop does the inverse on cumulative distribution.
Correct me if I am wrong.

**Comment by ob29** [comment]
I may be wrong, but isn't the second loop calculating the inverse over the un-normalized cumulative distribution using a random value in [0,sum_over_region]. If so, then they are using multinomial sampling rather than simple random sampling.

**Comment by longjon** [comment]
Please use the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) list for discussion of algorithms and such (unless you are PRing them, of course). Thanks!
