### ISSUE TITLE
How the blob know the number of channels, width and height from leveldb input?

### ISSUE THREAD

**Issue by xdybfq** [BVLC/caffe#1845]
I want to train my own CNN model with Caffe. The input is two channels, non-image data. I store the training data into leveldb as the input of Caffe. But I don't know how Caffe knows the number of channels. From the prototxt file, it doesn't specify the number of channels? Anybody can help me out of this?

**Comment by lukeyeager** [comment]
Sure it does, check out the [Datum](https://github.com/BVLC/caffe/blob/e3c895baac64c7c2da4f30ab7ae35a1c84e63733/src/caffe/proto/caffe.proto#L20) message. You store a Datum for each entry when you are [creating the database](https://github.com/BVLC/caffe/blob/e3c895baac64c7c2da4f30ab7ae35a1c84e63733/tools/convert_imageset.cpp#L146).

I haven't tried it, but you should be able to set `channels=2` or whatever else you like.

**Comment by xdybfq** [comment]
Yeager, thanks a lot for your answer. I got it done. 
From: Luke YeagerDate: 2015-02-10 01:57To: BVLC/caffeCC: xdybfqSubject: Re: [caffe] How the blob know the number of channels, width and height from leveldb input? (#1845)Sure it does, check out the Datum message. You store a Datum for each entry when you are creating the database.

I haven't tried it, but you should be able to set channels=2 or whatever else you like.
