### ISSUE TITLE
how to create lmdb with jpg image files

### ISSUE THREAD

**Issue by shendelin** [BVLC/caffe#1846]
Hi, I'm new and started to learn Caffe recently and have a very basic question. I have a few thousand jpg images and would like to use them to train CNN using Caffe. How can I create a lmdb file or leveldb file from a group of jpg images, where the labels are simply the file names? The tutorials I found all started from some DB, not single files.

Thanks!

**Comment by avalada** [comment]
http://caffe.berkeleyvision.org/gathered/examples/imagenet.html
Labels should be category class numbers from 0 to n

**Comment by erictzeng** [comment]
You should take a look at build/tools/convert_imageset, and check out the source if that doesn't do what you want. Alternatively, there's a Python script here that may work: https://github.com/BVLC/caffe/issues/1698#issuecomment-70211045

Please ask future usage questions on [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) -- the issues tracker is primarily for Caffe development discussion.

**Comment by shendelin** [comment]
Thank you for the help! Looking at the source code really helped.

BTW, the imagenet aux file seems no longer available at this URL:
https://www.dropbox.com/s/g5myor4y2scdv95/caffe_ilsvrc12.tar.gz

**Comment by smajida** [comment]
@shendelin 

try this link: https://github.com/BVLC/caffe/blob/master/data/ilsvrc12/get_ilsvrc_aux.sh

**Comment by annanurov** [comment]
Image net  data is 1.2 TB! cannot even think about downloading to my laptop. 
Can I getaway with a smaller data set?
Can I get my own data?

**Comment by williford** [comment]
@annanurov StackOverflow or the Caffe Users mailing list is better suited for asking this type of question.

**Comment by rhammoud** [comment]
Please advise how to unsubscribe if you know. Thanks much.


Quoting "Jonathan R. Williford" <notifications@github.com>:
