### ISSUE TITLE
the caffe conv algorithm

### ISSUE THREAD

**Issue by songjmcn** [BVLC/caffe#1847]
I find that the caffe conv algorithm cost more memory, so I have develop a new conv algorithm, and I want to put in caffe. Does anyone want to help me develop this?

**Comment by BlGene** [comment]
In that case the best option would be to submit a pull request and start a discussion based on it.

**Comment by songjmcn** [comment]
I have developed the new algorithm,but not test by large data. So I want to more people test it and then put it in caffe

**Comment by erictzeng** [comment]
Yeah, a pull request sounds like the right way to get this started. It'll let others take a look at your algorithm and develop it further if there are any issues.
