### ISSUE TITLE
Out of memory in "syncedmem.cpp"

### ISSUE THREAD

**Issue by 7oud** [BVLC/caffe#1848]
Hi
I am starting training the bvlc_reference_caffenet model, I get following error messages.

I0209 17:15:00.764143 30298 net.cpp:219] Network initialization done.
I0209 17:15:00.764150 30298 net.cpp:220] Memory required for data: 343607608
I0209 17:15:00.764214 30298 solver.cpp:41] Solver scaffolding done.
I0209 17:15:00.764225 30298 solver.cpp:160] Solving CaffeNet
I0209 17:15:00.764232 30298 solver.cpp:161] Learning Rate Policy: step
I0209 17:15:00.764256 30298 solver.cpp:264] Iteration 0, Testing net (#0)
I0209 17:16:44.094523 30298 solver.cpp:315]     Test net output #0: accuracy = 0.001
I0209 17:16:44.115337 30298 solver.cpp:315]     Test net output #1: loss = 7.14228 (* 1 = 7.14228 loss)
F0209 17:16:46.276556 30298 syncedmem.cpp:51] Check failed: error == cudaSuccess (2 vs. 0)  out of memory
*** Check failure stack trace: ***
    @     0x7f6b5afd0378  google::LogMessage::Fail()
    @     0x7f6b5afd02c4  google::LogMessage::SendToLog()
    @     0x7f6b5afcfcb2  google::LogMessage::Flush()
    @     0x7f6b5afd2bb1  google::LogMessageFatal::~LogMessageFatal()
    @           0x4be592  caffe::SyncedMemory::mutable_gpu_data()
    @           0x487562  caffe::Blob<>::mutable_gpu_diff()
    @           0x535f71  caffe::ConvolutionLayer<>::Backward_gpu()
    @           0x468c26  caffe::Net<>::BackwardFromTo()
    @           0x47fac3  caffe::Solver<>::Solve()
    @           0x426229  train()
    @           0x42036b  main
    @     0x7f6b584a676d  (unknown)
    @           0x42392d  (unknown)

It seemed that there was not enough device memory, The GPU I used was GTX780Ti with 3GB ram, is that enough?

Thanks!
Da Zou

**Comment by avalada** [comment]
Reduce the TRAIN and TEST batch_size in the train_val.prototxt
