### ISSUE TITLE
Failed in test_layer_factory.cpp

### ISSUE THREAD

**Issue by liuxianming** [BVLC/caffe#1850]
Hi, Folks

Have anyone experienced this problem: failed the test in LayerFactoryTest/3.TestCreateLayer?

It seems that it is due to the update 4 days ago, or do I have some configuration errors?

Thanks

**Comment by avalada** [comment]
Im having the same issue after the recent pull. Test passes in CPU only

**Comment by liuxianming** [comment]
@avalada Yes, if disabled the cudnn option, seems it will be fine. Anyway, I disabled the test for now.

**Comment by shelhamer** [comment]
See #1851 -- the fix is merged in dev.
