### ISSUE TITLE
About  GPU  Acceleration 

### ISSUE THREAD

**Issue by wzq12138** [BVLC/caffe#1853]
Hello  ,everyone,I  am  new  to   CAFFE  and  gpu  ,I  wan  to  know  the  GPU is  acceleration  on   tranining  or  on  test ,I  mean  if  I  have  model  now ,then  I  use  the  python  to  classifiy  something,when  I  running  python ,is  caffe  and  gpu  accelering  now?how  can I  know  the time.

**Comment by BlGene** [comment]
Hi wzq12138,

In both training and python it is possible to select either the GPU or the CPU as a computation backend.


When training you can specify the following in your solver file:
# solver mode: CPU or GPU
solver_mode: GPU

In you python program you will have something along the lines of:
net = caffe.Classifier(MODEL_FILE, PRETRAINED)

Afterwards you can use the functions to specify GPU/CPU computation.
net.set_mode_gpu()
net.set_mode_cpu()

You can then time the differences.

This is a usage question and should be closed, it probably belongs in the mailing list.

**Comment by erictzeng** [comment]
BlGene seems to have thoroughly answered your question (thanks for the help!).

As he indicated, the issues tracker is for development discussion, so if you have any more usage questions please ask them on [caffe-users](https://groups.google.com/forum/#!forum/caffe-users)!
