### ISSUE TITLE
Gsoc 2015

### ISSUE THREAD

**Issue by bhack** [BVLC/caffe#1856]
Are we interested in [GSOC 2015](https://www.google-melange.com/gsoc/homepage/google/gsoc2015)? Organization submission deadline is 20 Feb 2015.

/cc @shelhamer @longjon @jeffdonahue @sguada

**Comment by BlGene** [comment]
I would be interested in doing something related to segmentation / scene parsing. Who would I talk to for this? In the unlikely case that there are no spare ideas floating around I could try to come up with a proposal, though I would need some time for that.

**Comment by bhack** [comment]
BVLC members need to apply the organization before 20th Feb 2015

**Comment by shelhamer** [comment]
@bhack This is a nice suggestion, and I agree wholeheartedly with the spirit of Google Summer of Code, but we cannot participate this year for lack of guaranteed mentoring time. We are beginning a pilot student mentoring program in the BVLC however, so we will keep GSoC in mind next year once we have more mentoring experience. This will furthermore make us a more capable mentoring organization by raising the number of hands on the project at Berkeley.

Thanks for bringing this up. I encourage students interested in open-source to try GSoC! (Even if Caffe can't take part this time.)

**Comment by Aravind-Suresh** [comment]
Is caffe taking part in GSoC 2016?

**Comment by warmspringwinds** [comment]
@bhack @Aravind-Suresh I am also interested :+1:

**Comment by wchuanghard** [comment]
When will you be making a decision? (I am truly interested in, if Caffe can take part this year!)
