### ISSUE TITLE
matcaffe_demo cannot run successfully.

### ISSUE THREAD

**Issue by WanzhengZhu** [BVLC/caffe#1857]
Hi all,
      My operating system is windows 7 (64 bits), with VS 2012 X64, CUDA toolkit 6.5. 
When I run matcaffe_demo, I got problems shown below,

Undefined function 'caffe' for input arguments of
type 'char'.

Error in matcaffe_init (line 19)
if caffe('is_initialized') == 0

Error in matcaffe_demo (line 53)
  matcaffe_init();

Anyone can help me out? Thanks a lot!!!

**Comment by erictzeng** [comment]
It looks to me like Matlab can't find your installation of matcaffe -- have you compiled it (`make matcaffe`) and added it to the Matlab path?

If you have further questions, please ask on [caffe-users](https://groups.google.com/forum/#!forum/caffe-users). Github issues is exclusively for Caffe development discussion.
