### ISSUE TITLE
how to classify generic n-dimensional samples

### ISSUE THREAD

**Issue by rpagliarix** [BVLC/caffe#1859]
I'm pretty new to Caffe and deep learning. I have to questions about this library:
- is it possible to use Caffe for classification of data that is not image (generic vectors in n-dimensional space)? Are there examples?
- is Caffe compatible with hadoop or similar?

**Comment by shelhamer** [comment]
[Off-the-shelf SGD for classification](http://nbviewer.ipython.org/github/BVLC/caffe/blob/master/examples/hdf5_classification.ipynb)
Use Caffe as a generic SGD optimizer to train logistic regression on non-image HDF5 data

is an example from the home page.

Ask usage questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) group.
