### ISSUE TITLE
Want to share codes shuffling the order of images in training/testing for DataLayer (with LMDB) 

### ISSUE THREAD

**Issue by lim0606** [BVLC/caffe#1862]
Hi :) I wrote a code to shuffle the order of images when caffe use DataLayer (esp. LMDB). 

This set of codes are very simple, so I think there are many people who have their own code for them. However, I think this implementation will be helpful to others who are not familiar with caffe implementation. 

I'm not familiar with how I can share the code in this caffe repository. I would appreciate if you let me know how to share it.

Thanks :)

**Comment by erictzeng** [comment]
Glad to hear you'd like to contribute!

The best place to read up on our workflow is here: http://caffe.berkeleyvision.org/development.html

After that, just make a pull request with your changes and one of us will be around to review it. :)

**Comment by erictzeng** [comment]
One more thing: you may want to wait until after #1849 is merged. I think there will be a lot of changes, and the workflow will change too, so it may be easier to contribute after that goes through!

**Comment by joyousrabbit** [comment]
@lim0606 Where is your code???
