### ISSUE TITLE
New Network

### ISSUE THREAD

**Issue by sunilrao43** [BVLC/caffe#1863]
I am  new to caffe and NN can any one provide me info about 
are  there any tutorials for programming with caffe
how can i create my own network with caffe .

**Comment by rohrbach** [comment]
Hi, there are lots of tutorials and examples at http://caffe.berkeleyvision.org/

Please ask usage questions on [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) -- the issues tracker is primarily for Caffe development discussion. Thanks!
