### ISSUE TITLE
normalizing using LRN layer

### ISSUE THREAD

**Issue by ethanfetaya** [BVLC/caffe#1864]
I wish to normalize across channels (I have 30 channels). To do so (unless I misunderstand) I can use the LRN layer with norm_region=ACROSS_CHANNEL and local_size = 61. The local_size = 2*num_of_channels+1 with zero padding should ensure the normalisation factor is constant across channels. 

If I do this in CPU, it works fine. If I run it in GPU when norm_region is larger then the number of channels I get NAN's. 

Any ideas?

Thanks

**Comment by erictzeng** [comment]
Thanks for the report. It's looking like this might be a bug that occurs when local_size is larger than the number of channels.

https://github.com/BVLC/caffe/blob/44bc1552781eea958c228981a8638ddfcf80e3d9/src/caffe/layers/lrn_layer.cu#L34

In the case where `size > channels` I believe this loop is causing us to index out of bounds. This is something that shouldn't be too hard to fix, although there's a release upcoming so this might have to wait until after that release goes through.
