### ISSUE TITLE
Save initial snapshots at higher frequency

### ISSUE THREAD

**Issue by Russell91** [BVLC/caffe#1866]
I've always felt a tension between wanting a high snapshot frequency for the initial iterations, so that I can quickly review training early on, and a lower frequency at high iteration counts, as snapshots you never use just waste local storage. I've found that a pretty good compromise is to do snapshots at 10x the rate for the first interval. It's a little harder to explain, but is a more sensible default. Everyone else I know who uses caffe has to deal with this at some point too. Anyways, I think it's worth considering:

```
if (param_.snapshot() && iter_ > start_iter &&
    iter_ % (iter_ < param_.snapshot() ? param_.snapshot() / 10 : param_.snapshot()) == 0) {
  Snapshot();
}
```

**Comment by lukeyeager** [comment]
+1 for this. Maybe add something like this to the SolverParameter definition?

```protobuf
optional int32 snapshot_boost_iteration = 36;
optional int32 snapshot_boost_interval = 37;
```

So, if your solver is:
```
snapshot:100
snapshot_boost_iteration: 100
snapshot_boost_interval: 20
```
then you'd get snapshots at 20, 40, 60, 80, 100, 200, 300.

"Boost" doesn't seem like the right word, but is this the type of behavior you're talking about, @Russell91?

**Comment by shelhamer** [comment]
This can be handled through pycaffe by manually calling `solver.snapshot()` in pycaffe.
