### ISSUE TITLE
Implementing Stratified Data Sampler for Mini-Batches

### ISSUE THREAD

**Issue by erogol** [BVLC/caffe#1868]
In a case of unbalanced datasets, I beleive it is important to set the learning rate accordingly for each class or sample the minibatch of data in a stratified fashion. To solve such a problem, I guess it is better to implement one of these in caffe.

**Comment by longjon** [comment]
Closing as this seems outside the current scope of Caffe; you can of course prepare and feed data in any way you see fit.
