### ISSUE TITLE
Error at training  due to "unix time"

### ISSUE THREAD

**Issue by erogol** [BVLC/caffe#1871]
After I pulled newest version of dev branch I started to get following error on training

*** Aborted at 1424038984 (unix time) try "date -d @1424038984" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGSEGV (@0x0) received by PID 5445 (TID 0x7fa4bc227800) from PID 0; stack trace: ***
    @     0x7fa4b2afac30 (unknown)
Segmentation fault (core dumped)

**Comment by erogol** [comment]
it is resolved by re-compilation

**Comment by RafaRuiz** [comment]
did you recompile with other arguments? did you change libraries?

**Comment by JanySunny** [comment]
I have the same question. Have you solved it?
