### ISSUE TITLE
Add exta features to net - detection with matlab

### ISSUE THREAD

**Issue by esason** [BVLC/caffe#1876]
Hi,

I would like to add some manual features to the net.
My problem is that at the test (or detection) stage.  I am using Matlab and would like to give it another input and to add the additional data  to an intermediate layer.  I believe that i should change something at the matcaffe.cpp file. 
As it seems at the current implementation i can only give just one data blob.
Can someone help?

- what sould i change in the matcaffe file?
 - what changes should i do in the proto file at the detection step. i.e how should i define 2 inputs?

regards,
Eli

**Comment by longjon** [comment]
Please ask usage questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) list. Thanks!
