### ISSUE TITLE
Out of memory error

### ISSUE THREAD

**Issue by prote376** [BVLC/caffe#1877]
When I run fcn_32, I got these messages.

I0217 00:02:05.946698 13030 net.cpp:222] Memory required for data: 1192246208
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:505] Reading dangerously large protocol message.  If the message turns out to be larger than 1073741824 bytes, parsing will be halted for security reasons.  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:78] The total number of bytes read was 544614056
F0217 00:02:07.073874 13030 syncedmem.cpp:51] Check failed: error == cudaSuccess (2 vs. 0)  out of memory

It seems like that I need only 1192246208 bytes.
But I already have 2GB memory on 750 Ti.
And, remain memory is bigger than that as below.

+------------------------------------------------------+                       
| NVIDIA-SMI 340.29     Driver Version: 340.29         |                       
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 750 Ti  Off  | 0000:01:00.0     N/A |                  N/A |
| 33%   31C    P8    N/A /  N/A |    401MiB /  2047MiB |     N/A      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Compute processes:                                               GPU Memory |
|  GPU       PID  Process name                                     Usage      |
|=============================================================================|
|    0            Not Supported                                               |
+-----------------------------------------------------------------------------+

What is problem?

**Comment by erictzeng** [comment]
The "memory required for data" message relates only to the memory required for the *input data*. The remaining layers of the network also require significant amounts of memory for their parameters and outputs. You could try decreasing your batch size and seeing if that saves enough memory to avoid the issue.

If you have more questions, please ask on [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) -- the issues tracker is primarily for Caffe development discussion. Thanks!
