### ISSUE TITLE
in Latest DEV branch PyCaffe raises error when Classifier interface is initialized with a mean file

### ISSUE THREAD

**Issue by erogol** [BVLC/caffe#1893]
In the latest DEV branch, If I init the classifier with the following code which was just fine before the PyCaffe updates recently done;

classifier = caffe.Classifier('model.prototxt', 
                       'bla.caffemodel',
                       mean=np.load('mean_file.npy'),
                       channel_swap=(0,1,2),
                       raw_scale=255,
                       image_dims=(45, 25, 3))

It raises;

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-8-19c9fba3f941> in <module>()
     10                        channel_swap=(0,1,2),
     11                        raw_scale=255,
---> 12                        image_dims=(45, 25, 3))
     13 
     14 solver.net.share_with(classifier)

/home/retina18/Downloads/caffe_dev/python/caffe/classifier.pyc in __init__(self, model_file, pretrained_file, image_dims, gpu, mean, input_scale, raw_scale, channel_swap)
     33 
     34         if mean is not None:
---> 35             self.set_mean(self.inputs[0], mean)
     36         if input_scale is not None:
     37             self.set_input_scale(self.inputs[0], input_scale)

/home/retina18/Downloads/caffe_dev/python/caffe/pycaffe.pyc in _Net_set_mean(self, input_, mean, mode)
    221             mean = caffe.io.resize_image(mean.transpose((1,2,0)),
    222                                          in_shape[2:]).transpose((2,0,1))
--> 223         self.mean[input_] = mean
    224     elif mode == 'channel':
    225         self.mean[input_] = mean.mean(1).mean(1).reshape((in_shape[1], 1, 1))

AttributeError: 'Classifier' object has no attribute 'mean'

**Comment by shelhamer** [comment]
Thanks for the report -- this will be fixed shortly as the last pycaffe changes are made for the next release #1849 today.

**Comment by erogol** [comment]
Now mean file problem is resolved but now, 

 caffe.Net.__init__(self, model_file, pretrained_file)

raises error since there is not such an constructur. It needs to be somthing like

 caffe.Net.__init__(self, model_file, pretrained_file, caffe.TEST)

**Comment by shelhamer** [comment]
Fix in #1902.
