### ISSUE TITLE
error compiling

### ISSUE THREAD

**Issue by ggdhines** [BVLC/caffe#1898]
I've checked out the master branch and tried compiling according to the instructions on http://caffe.berkeleyvision.org/installation.html. I'm using Ubuntu 14.10. The command "make all" results in the error:
g++ src/caffe/layers/window_data_layer.cpp -pthread -fPIC -DNDEBUG -O2 -DCPU_ONLY -I/usr/include/python2.7 -I/usr/lib/python2.7/dist-packages/numpy/core/include -I/usr/local/include -I.build_release/src -I./src -I./include -Wall -Wno-sign-compare -c -o .build_release/src/caffe/layers/window_data_layer.o 2> .build_release/src/caffe/layers/window_data_layer.o.warnings.txt \
        || (cat .build_release/src/caffe/layers/window_data_layer.o.warnings.txt; exit 1)
src/caffe/layers/window_data_layer.cpp: In member function ‘virtual void caffe::WindowDataLayer<Dtype>::InternalThreadEntry()’:
src/caffe/layers/window_data_layer.cpp:230:48: error: ‘CV_LOAD_IMAGE_COLOR’ was not declared in this scope
       cv::Mat cv_img = cv::imread(image.first, CV_LOAD_IMAGE_COLOR);
                                                ^
Makefile:500: recipe for target '.build_release/src/caffe/layers/window_data_layer.o' failed
make: *** [.build_release/src/caffe/layers/window_data_layer.o] Error 1

**Comment by ggdhines** [comment]
Nevermind - figured out it was opencv being an issue

**Comment by MdAsifKhan** [comment]
I am also getting the same error could you please explain how to resolve it.

**Comment by ggdhines** [comment]
Been a while since this problem (haven't used caffe much since) - I think it was something related to opencv 2 vs. 3.
