### ISSUE TITLE
Training with encoded LMDB broken by #1878

### ISSUE THREAD

**Issue by yanii** [BVLC/caffe#1901]
Some change that's happened in the last week seems to have broken training with the dev branch and encoded LMDB for me, and I think it may be the changes from 52465873d08cfd58a4c84ee8b239908814de4f39 to the functions for reading encoded data. It seems that it will now load data in native format, including using the same number of channels as the original image (imdecode has the flag set to -1), and this is not handled properly datalayer or data_transformer.

Instead, at least for an existing encoded LMDB, greyscale (single-channel) images from Imagenet now make it all the way through to data_transfomer and throw an assert: 

```
F0218 23:24:28.115943  2648 data_transformer.cpp:208] Check failed: channels == img_channels (3 vs. 1) 
*** Check failure stack trace: ***
    @     0x7f102732ac6c  (unknown)
    @     0x7f102732abb8  (unknown)
    @     0x7f102732a5ba  (unknown)
    @     0x7f102732d551  (unknown)
    @     0x7f1027894094  caffe::DataTransformer<>::Transform()
    @     0x7f1027888a45  caffe::DataLayer<>::InternalThreadEntry()
    @     0x7f10278234cf  boost::_mfi::mf0<>::operator()()
    @     0x7f1027823432  boost::_bi::list1<>::operator()<>()
    @     0x7f102782317c  boost::_bi::bind_t<>::operator()()
    @     0x7f1027822e12  boost::detail::thread_data<>::run()
    @     0x7f101f03ad3a  (unknown)
    @     0x7f101d15d0a5  start_thread
    @     0x7f102690988d  (unknown)
    @              (nil)  (unknown)
Aborted
Done.

```

**Comment by shelhamer** [comment]
It seems like the encoding / decoding need to have a flag for forcing decoding to color or grayscale. This could be exposed through caffe.proto in `transform_param`.

**Comment by yanii** [comment]
Yeah, that makes sense. We should make sure it's backwards compatible with existing networks though - so perhaps it should default to forcing colour? Doesn't seem like a great solution, but I can't see an alternative.

**Comment by philkr** [comment]
One issue with force_color (or is_color) for the DataLayer is that encoded and non-encoded images will have different semantics. We load a non-encoded datum as is (however many dimensions it has), while we convert encoded datums.
We could just add a encoded_is_color flag and keep having different semantics between non-encoded and encoded images, but at least make it explicit.
Maybe a nicer solution would be to store a native_encoding flag in the database, and add it to newly created db's.

**Comment by yanii** [comment]
Well is there any use case in which we want to be loading data samples with different numbers of channels for a single network/DB? Presumably non-encoded images always have a fixed set of channels already. From what I can see we would only ever want to load the same fixed number of channels from each sample from a DB. Am I missing something though - what was the motivation for this change in 5246587?

**Comment by shelhamer** [comment]
> Well is there any use case in which we want to be loading data samples with different numbers of channels for a single network

Not that I can imagine. I am reverting #1878 for the next release -- it can be brought back once we decide exactly what to do about this.

**Comment by philkr** [comment]
@yanii I completely agree that we never want to mix different channel sizes. For non-encoded images this is currently enforced by creating your lmdb with a fixed channel size, for encoded images this was only enforced after 5246587 . Pre 5246587 encoded lmbd are currently not decoded correctly. A flag like encoded_is_color could fix this.
Maybe an easier way of fixing it is inferring the fixed channel dimension from the first few images in the dataset.
On the other hand, there is no way of encoding gray scale images (eg. dense image labels) pre 5246587 .

**Comment by yanii** [comment]
I see.. so a big part of the problem with encoded LMDBs is not knowing which version of the code created the LMDB to begin with it sounds like. Is there currently any version information written into the LMDB? Prompting a user to create an updated LMDB even is a much more preferable outcome than an assert failing.

**Comment by philkr** [comment]
#1910 should fix the issues.

**Comment by shelhamer** [comment]
#1910 took care of this by adding a compatibility flag and warning about mixed-encoding LMDBs. This will give everyone a chance to re-encode data if need be. Thanks for the report and thoughts on a fix @yanii.
