### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by sunilrao43** [BVLC/caffe#1903]
Hi ,

I have succesfullyimplemented alex net using caffe and i was able to predict new data 
but iam curious to know what happens within the layers ..is there any way to do a step by step procedure so that i can understand the whats happening inside the layers
if so please suggest me 

Thanks in advance

**Comment by BlGene** [comment]
If you load your net using the Python api you have acces to all your network parameters and intermediate calculation states. Have a look at the Python examples. This is a usage question and belongs on the mailing list, the issue should be closed.

**Comment by shelhamer** [comment]
Thanks for helping @BlGene -- @sunilrao43 do check the Python filter visualization example.
