### ISSUE TITLE
PyCaffe Solver raises error for .set_input_arrays function.

### ISSUE THREAD

**Issue by erogol** [BVLC/caffe#1904]
I am working on ipython and as I run .set_input_arrays functions (which was fine before the pycaffe revision), it stops the kernel and quits the console. I guess there is something wrong about the function but nothing shown by the code itself as a error message.

This is how I call the function.
....
solver.net.set_input_arrays(np.ascontiguousarray(caffe_image, dtype=np.float32), np.ascontiguousarray(label, dtype=np.float32))
....

**Comment by erogol** [comment]
I realized that this is because of the denial if mean transformation in MemoryDataLayer. I guess data transformation is reoved from this layer, even I do not like the idea.

**Comment by shelhamer** [comment]
See #1907 that switches to a warning while we figure out the One True Reconciliation of pre-processing code.
