### ISSUE TITLE
Solver.solve() interface raises error if the given blob is larger then a number.

### ISSUE THREAD

**Issue by erogol** [BVLC/caffe#1916]
solver = caffe.SGDSolver(SOLVER_PYTHON_FILE)

solver.net.set_input_arrays(np.ascontiguousarray(train_img_blob, dtype=np.float32), 
                            np.ascontiguousarray(train_label_blob, dtype=np.float32))
solver.solve()

This is what I've done for training a network over python interface. Given train data blob is multiple of the batch size (32). This code works for train data blob size < 512, otherwise it gives this as an output

I0220 15:08:21.057770  4054 net.cpp:213] Network initialization done.
I0220 15:08:21.057777  4054 net.cpp:214] Memory required for data: 556160
I0220 15:08:21.057915  4054 solver.cpp:42] Solver scaffolding done.
Segmentation fault (core dumped)

I guess something wrong or missing from my humble side.

**Comment by rohrbach** [comment]
I believe this should go to [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) -- this issues tracker is primarily for Caffe development discussion. Thanks!

**Comment by erogol** [comment]
Yes, but I beleive so this is an development issue to track and nothing to do with the caffe-users

**Comment by shelhamer** [comment]
This is actually a duplicate of #1470 -- no single blob can be larger than 2 GB given the current types.

**Comment by rohrbach** [comment]
sorry @erogol for commenting/closing this incorrectly, but @shelhamer clarified it.

**Comment by erogol** [comment]
Thanks for the clarification @shelhamer  and np @rohrbach . Best :)
