### ISSUE TITLE
Dev branch is broken, error loading libcaffe.so

### ISSUE THREAD

**Issue by mees** [BVLC/caffe#1919]
Currently the dev branch at 079e4168f55112f6cf62f1d9ee7f4927f15978c5 seems broken.
$ build/tools/caffe test
build/tools/caffe: error while loading shared libraries: libcaffe.so: cannot open shared object file: No such file or directory
I reproduced this on two different computers, anybody knows what is causing this?

**Comment by shelhamer** [comment]
Fixed in #1921 -- sorry for the linking issue.

**Comment by shelhamer** [comment]
By the way, the fix is be made to `master` since the `dev` branch will be discontinued in favor of single branch development.
