### ISSUE TITLE
 undefined reference to `caffe::Datum::Datum()' when integrating with QT?

### ISSUE THREAD

**Issue by helxsz** [BVLC/caffe#1924]
I am new to caffe, I have installed caffe and run the examples successfully, but now I am trying to integrate caffe with QT based application. My environment is ubuntu 14.04. Assume the CAFFE_ROOT as the caffe root folder, CAFFE_ROOT/build is the folder to put the compiled files.

to configure the QT based application, include path and library path needs to be configured.In the CAFFE_ROOT/build, I can find the lib folder where libcaffe.so library can be found and src folder for the include path

therefore the .pro is looking like as below

```javascript
INCLUDEPATH += /usr/include \
                /usr/local/include \
              /CAFFE_ROOT/build/src
LIBS += -L/usr/lib \
         -lglog \
         -lgflags \
         -llmdb \
         -lprotobuf \
        -L/CAFFE_ROOT/build/lib
         -lcaffe
```

in my c++ application, 
```javascript
#include <QCoreApplication>
#include<iostream>
#include <fstream>
#include <gflags/gflags.h>
#include <glog/logging.h>
#include <google/protobuf/text_format.h>
#include <lmdb.h>
#include <sys/stat.h>
#include <caffe/proto/caffe.pb.h>
using namespace caffe;
using namespace std;
int main(int argc, char *argv[])
{
    QCoreApplication a(argc, argv);
    Datum datum;
    datum.set_channels(1);
    return a.exec();
}
```
when compiling, it gives me a error , * error: undefined reference to `caffe::Datum::Datum()' *

(sorry I am back in China for a month, could not log into google forum so far)

**Comment by patrickhuie19** [comment]
solution??
I have this problem too
