### ISSUE TITLE
Cannot get the reported performance using bvlc_googlenet.caffemodel in model zoo

### ISSUE THREAD

**Issue by Dav-Jay** [BVLC/caffe#1927]
Hi all, recently I have downloaded the bvlc_googlenet.caffemodel from Caffe's model zoo in this link: https://github.com/BVLC/caffe/tree/master/models/bvlc_googlenet. I also used the same prototxt file provided in above link. After that, I resized the imagenet's validation set to be 256x256 and test on it using the downloaded model. However, I only get top5 accuracy: 87.8%, which is quite lower than the reported performance: top5 88.9%.

So, has anyone tested with the googlenet model in model zoo? Could you please tell where my problems lie and how you get the reported performance? Your generous help shall be appreciated very much. Thanks a lot!

**Comment by ducha-aiki** [comment]
@Dav-Jay, do you have 50K validation set from image-net.org or you downloaded images yourself?

**Comment by Xiaojie-Jin** [comment]
Problem solved. Thank you all! @ducha-aiki @sguada

**Comment by Dav-Jay** [comment]
Problem solved! Thank you all! @ducha-aiki  @sguada

**Comment by ducha-aiki** [comment]
@Dav-Jay  then close the issue, please.
