### ISSUE TITLE
Simple example of process one image

### ISSUE THREAD

**Issue by drozdvadym** [BVLC/caffe#1930]
I tried to found simple example how to:
1) Open one image (using opencv for example)
2) Load trained network (imageNet for example)
3) Print to stdout result of feedforward
Maybe there is some examples or docs?

But there are many complicated and hard to understanding for beginner.

Thank you.

**Comment by rohrbach** [comment]
We welcome you to look at the extensive documentation, tutorials, and examples at http://caffe.berkeleyvision.org/ 
Please ask usage questions on [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) -- this issues tracker is primarily for Caffe development discussion. Thanks!
