### ISSUE TITLE
Compile Error   ./examples/cifar10/create_cifar10.sh 

### ISSUE THREAD

**Issue by ujiyasuh** [BVLC/caffe#1934]
Could you tell me how to solve?

I did comand below, but it output was compile error.
I refer to this web site,
http://caffe.berkeleyvision.org/gathered/examples/cifar10.html

~/caffe-master$ ./examples/cifar10/create_cifar10.sh Creating leveldb...
rm: cannot remove ‘examples/cifar10/cifar10_train_leveldb/LOG’: Permission denied
rm: cannot remove ‘examples/cifar10/cifar10_train_leveldb/LOCK’: Permission denied
./examples/cifar10/create_cifar10.sh: 11: ./examples/cifar10/create_cifar10.sh: ./build/examples/cifar10/convert_cifar_data.bin: not found
Computing image mean...
F0222 08:56:21.730981  5518 compute_image_mean.cpp:47] Check failed: status.ok() Failed to open leveldb examples/cifar10/cifar10_train_leveldb
*** Check failure stack trace: ***
    @     0x7fc344452daa  (unknown)
    @     0x7fc344452ce4  (unknown)
    @     0x7fc3444526e6  (unknown)
    @     0x7fc344455687  (unknown)
    @           0x408a9f  main
    @     0x7fc341cddec5  (unknown)
    @           0x4091c3  (unknown)
    @              (nil)  (unknown)
Aborted (core dumped)
Done.

Thanks best regards.

**Comment by rohrbach** [comment]
Hi, 
as you can see from the error log "./build/examples/cifar10/convert_cifar_data.bin: not found".
You have very likely not build caffe successfully (follow http://caffe.berkeleyvision.org/installation.html). This will create ./build/examples/cifar10/convert_cifar_data.bin.

However, please ask usage questions on [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) -- this issues tracker is primarily for Caffe development discussion. Thanks!

**Comment by ujiyasuh** [comment]
rohrbach-san,
I thank for an immediate reply.
I am happy when I can have some advice.

I think that it is OK situation as below.
cp Makefile.config.example Makefile.config
# Adjust Makefile.config (for example, if using Anaconda Python)
make all
make test
make runtest
---->
[----------] Global test enmkdir build
[==========] 457 tests from 98 test cases ran. (12848 ms total)
[  PASSED  ] 457 tests.

But 
in CMake Compilation
I did comand as below, and got cmake failure.
-----------------------------------------------------------------------------------------------------
cd build
cmake ..
make all
make runtestvironment tear-down

~/caffe-master/build$ cmake ..
-- Found leveldb in /usr/include /usr/lib/x86_64-linux-gnu/libleveldb.so
-- LMDB lib: /usr/lib/x86_64-linux-gnu/liblmdb.so
-- LMDB include: 
-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   system
--   thread
-- Found PROTOBUF Compiler: /usr/bin/protoc
-- Examples enabled
CMake Error at examples/CMakeLists.txt:13 (add_executable):
  add_executable cannot create target "matrix" because another target with
  the same name already exists.  The existing target is an executable created
  in source directory "/home/kenichi/caffe-master/examples".  See
  documentation for policy CMP0002 for more details.


-- Configuring incomplete, errors occurred!
See also "/home/kenichi/caffe-master/build/CMakeFiles/CMakeOutput.log".
See also "/home/kenichi/caffe-master/build/CMakeFiles/CMakeError.log".
