### ISSUE TITLE
ImageData requires file paths with no spaces

### ISSUE THREAD

**Issue by d4l3k** [BVLC/caffe#1935]
I'm not really sure if this is a bug or a feature request, but it would be nice if the file paths passed into the ImageData layer could have spaces in them and respected the shell '\ ' escape sequences.

Here's the relevant line:
https://github.com/BVLC/caffe/blob/f998127ef2224b15dbcee9d392b080b978788bd0/src/caffe/layers/image_data_layer.cpp#L40

If I have some free time I'll make a PR with the changes.

**Comment by marcuniq** [comment]
+1

**Comment by longjon** [comment]
See also #1951.

**Comment by bamos** [comment]
+1

**Comment by bchu** [comment]
+1. Wasted 2 weeks of research time because of this. :person_frowning:

**Comment by seanbell** [comment]
Fixed by #4059
