### ISSUE TITLE
web demo and classify.py broken

### ISSUE THREAD

**Issue by EvanWeiner** [BVLC/caffe#1937]
The python tools and examples are currently broken on master.

I'd like to suggest adding a test case for this before releasing future Caffe updates.

**Comment by shelhamer** [comment]
> The python tools and examples are currently broken on master.

No, pycaffe and the examples actually work when installed according to the instructions as evidenced by `make pytest` checked by continuous integration and ourselves and individually checking the ipython notebook examples for release. Without any detail it's hard to know your problem. Remember to `make clean` between releases at least.

> I'd like to suggest adding a test case

Adding more Python tests -- in particular integration tests of small examples that run a network and check output -- is a good idea to not rely on manual checking. If you have a concrete idea for a test, please send a PR.

If you need installation / build help join the [caffe-users group](https://groups.google.com/forum/#!forum/caffe-users).

**Comment by EvanWeiner** [comment]
@shelhamer - I kindly request this issue be re-visited because in Caffe's latest release much of the python code is indeed broken, here's the details:

1. The python-based web_demo in the examples folder is no longer working.
2. The classifiy.py script in the python folder is no longer working.
3. `sudo make pytest` fails for me after upgrading to latest code base and doing a make clean. Note that `sudo make runtest` does work fine for me after compiling the main source. Here's the error I'm getting for the failed `make pytest`:

F0223 08:14:56.364547  7935 layer_factory.hpp:77] Check failed: registry.count(type) == 1 (0 vs. 1) Unknown layer type: Python (known types: AbsVal, Accuracy, ArgMax, BNLL, Concat, ContrastiveLoss, Convolution, Data, Deconvolution, Dropout, DummyData, Eltwise, EuclideanLoss, Exp, Flatten, HDF5Data, HDF5Output, HingeLoss, Im2col, ImageData, InfogainLoss, InnerProduct, LRN, MVN, MemoryData, MultinomialLogisticLoss, Pooling, Power, ReLU, Sigmoid, SigmoidCrossEntropyLoss, Silence, Slice, Softmax, SoftmaxWithLoss, Split, TanH, Threshold, WindowData)
*** Check failure stack trace: ***
Aborted (core dumped)
make: *** [pytest] Error 134

**Comment by shelhamer** [comment]
Thanks for coming back with detail. 1 & 2 can be looked into -- @sergeyk
could you check the web demo? -- and should likely be given pytests for
automatic checking.

3. there is a pytest for PythonLayer so if you install without it that test
fails. We'll post an issue to explain that / note it in the error message.
At some point we might be able to make it conditional but can't loop back
on it now.

Note that the actual caffe.Net interface and all the *.ipynb notebooks do
work.

**Comment by sergeyk** [comment]
Will check later tonight.

**Comment by smr277** [comment]
I'm having the same issu where ```make pytest``` works, however there is still the error ```TypeError: __init__() got an unexpected keyword argument 'gpu'``` when running web_app.py.
Running Ubuntu 14.04 64Bit, Python 2.7, NVidia GTX680

**Comment by shelhamer** [comment]
`classify.py` and the web demo are fixed in #2058.
