### ISSUE TITLE
master vs dev?

### ISSUE THREAD

**Issue by jyegerlehner** [BVLC/caffe#1943]
I must have missed something. Docs used to instruct us to rebase PRs against dev, and now I see the docs say master. Is that right? What is the status of the dev branch? Deprecated? So any PR that's open would need to be updated before it can be merged, and is that simply a matter of rebasing off master? Thanks in advance if anyone can unconfuse me.

**Comment by bhack** [comment]
If you have time you can rebase your PR branch on master and open a new PR. Dev branch is "de facto" deprecated but core members can still pickup your PR code and merge to master. There was a discussion on https://gitter.im/BVLC/caffe

**Comment by shelhamer** [comment]
Please see the release notes for rc2 and the links to issues explaining the
workflow change. @bhack has summarized it: dev has been deprecated for
simplicity.

**Comment by jyegerlehner** [comment]
OK thanks everyone.
