### ISSUE TITLE
Error while running ../tools/caffe on RHEL 

### ISSUE THREAD

**Issue by StevenLobo2** [BVLC/caffe#1944]
I have successfully compiled caffe on GPU enabled RHEL. 

While running tools/caffe I am getting below error.  Please help me to solve this.
undefined symbol: _ZN60FLAG__namespace_do_not_use_directly_use_DECLARE_bool_instead21FLAGS_alsologtostderrE

**Comment by longjon** [comment]
Closing as there is not enough information here to tell if this is a current issue with `master`. If you are able to reproduce while up-to-date in and in `DEBUG` mode and building against a sufficient version of `gflags`, you're welcome to open a new issue.
