### ISSUE TITLE
Finetuning without changing layer names

### ISSUE THREAD

**Issue by rosenfeldamir** [BVLC/caffe#1945]
Fine-tuning a network fails if the output dimensions of a layer , e.g, the last layer, are changed but the name remains the same. The caffe binary complains that there is a dimension mismatch. 
Is this intentional? Only when the name of the layer is changed to a different name, caffe proceeds with the training, as it "understands" that the renamed layer is a new one. 
I suggest that this behaviour be either clearly documented, or changed.

**Comment by longjon** [comment]
Yes, this is intentional. Silently continuing after failing to copy parameters to a layer with the same name would hide bugs (e.g., initializing from the wrong `caffemodel`).

Documentation PRs are welcome!
