### ISSUE TITLE
Parallel Branch ImageNet Example Crash

### ISSUE THREAD

**Issue by omkarparkhi** [BVLC/caffe#1947]
Parallel branch example crashes at

 CUDA_CHECK(cudaMemcpyAsync(buf, &cpu[off], len, put, stream));

in template<typename Dtype> void CPUGPUSync<Dtype>::run()  in parallel.cpp with
illegal memory access.

**Comment by WuZifeng** [comment]
uint8_t get_grads = true;
size_t off = index * CHUNK;
sync_worker_kernel<Dtype>(gpu, last, &buf, &off, &buf, &get_grads, 0, 1, stream, CHUNK);
...
offs[0] in the kernel function sync_worker_kernel leads to illegal memory access.

Above is my case. Is it ok to use host addresses in this way? Or is there any way to make this code work?

**Comment by longjon** [comment]
The parallel branch is development code, so I'd prefer that we reserve the issue tracker for current problems with `master`. You're welcome to discuss on [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) or the relevant PRs.
