### ISSUE TITLE
Terrible accuracy (same net, same data) compared to matlab NNToolBox in classification

### ISSUE THREAD

**Issue by Geekrick88** [BVLC/caffe#1952]
Hi Everyone,

I seem to be in a bit of a fix. I was trying to test caffe with HDF5 image classification and it was not converging. So, to eliminate variables and pin point potential issues, I intended to do a comparison with the matlab nn toolbox. To this end, I extracted an 1764 length HOG descriptor for each 64x64 sized input images. The total number of samples was 23667 images.  Then I split it into train and validation ratio of 80:20.

Then I saved the images and labels into two HDF5 files for training and testing respectively.Download data from onedrive. (~127 MB). :http://1drv.ms/1DjZGis
I used the same data to train the nn toolbox in matlab. The following is the image of the network. (1764 Input, 100 Tanh hidden, 8 linear output)  And I am also attaching the confusion matrices. It can be seen that the net achieves around ~80% accuracy.
![matnet](https://cloud.githubusercontent.com/assets/6443208/6352499/0d7959b0-bc3b-11e4-9c1f-737baf1a2e4d.png)
![untitled](https://cloud.githubusercontent.com/assets/6443208/6352500/0d7a0f0e-bc3b-11e4-8d20-9637cf312a7b.jpg)

Now I ran the same experiment with caffe. I am attaching the solver prototext, the network file and also the stderr output. (Link: https://skydrive.live.com/redir?resid=D6DD9504A21CE8A6!110415) However after 70000 iterations the network only achieves 35% accuracy which is a far cry from the matlab toolbox accuracy.
What is going wrong?

I had to do this because the convnet was not converging on the original images. Now I see that even a simple MLP is also not converging. I have tried lowering the learning rate. I have tried both gaussian and xavier weight fillers, I also tried both TanH and ReLU activations. But it is not improving.

I have a paper deadline looming and I need to do this comparison fast. Any help in this regard would be appreciated.

Kind Regards,
Rick

**Comment by shelhamer** [comment]
Please ask modeling questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) group!

**Comment by Geekrick88** [comment]
@shelhamer I have asked questions there in the past but it does not seem very active. This same question is there https://groups.google.com/forum/#!topic/caffe-users/oZwYenDQBLQ. It seems like there is something wrong in caffe as I just ran the same experiment with theano and achieved similar results to that of matlab. It is not very easy to debug the caffe code base to see what is going wrong. Any ideas?

**Comment by aspats** [comment]
@Geekrick88 I would be grateful if you could share theano code with all details how to make experiment with it. I also have the same problem with caffe.
Thanks!
