### ISSUE TITLE
What will be the new approach for data pre-processing of the memory data?

### ISSUE THREAD

**Issue by erogol** [BVLC/caffe#1954]
Right now, if I am not mistaken, MemoryDataLayer does not support data transformation to be more generic kind. However, it makes the things very vague. I also cannot see any way to do it by a implicit mechanism of caffe. The only option I found is to reading mean_file and subtracting it by hand and cropping the images by again hand. Is this the only solution or as the core developers do you think something for the future, since it makes things very hard. 

My humble solution is to define a separate layer that applies the data processing by itself so that it is decoupled form the data layers. Maybe it can be phase depended as data layers as well.

**Comment by longjon** [comment]
Ideally, Caffe will eventually support all transformations as layers, which I think is what you have in mind. For additional discussion of the specific issues with `MemoryDataLayer`, let's stick to #1784.
