### ISSUE TITLE
Issue with differently sized image data and image mean

### ISSUE THREAD

**Issue by kptikku** [BVLC/caffe#1963]
With the 'Greater than or equalto' check done inside 'LayerSetUp' function between the dimensions of datum and image_mean can lead to significant erroneous output which the user might not be aware about. With the current settings, if the mean_image is bigger than the image, the execution continues and leads to an errernous subtraction of the mean with the image.

Shouldn't the check be done to see whether the dimensions are exactly the same and issue a warning if they are not, so that the user could crop ~~or resize~~ the mean_image as required.

**Comment by longjon** [comment]
Closing as I can't figure out what code, if any, this refers to in current `master`. You're welcome to open a new issue if you still believe there's a bug in `master`.
