### ISSUE TITLE
issue in pycaffe

### ISSUE THREAD

**Issue by amiltonwong** [BVLC/caffe#1967]
Hi, all,

I had followed the install steps in page, the caffe library can run successfully, but fpycaffeor  , I came across the following issue. Did someone come across this issue before and how to fix it?  THX!
My system is  ubuntu 12.04 64bit, I had installed anacorda, and set $PYTHONPATH as:
export PYTHONPATH="$CAFFE_ROOT/python:$PYTHONPATH"

=============================================================

root@milton-Desktop:~# python ~/Downloads/caffe-public-bvlc_googlenet/python/classify.py
Traceback (most recent call last):
  File "/root/Downloads/caffe-public-bvlc_googlenet/python/classify.py", line 14, in <module>
    import caffe
  File "/root/Downloads/caffe-public-bvlc_googlenet/python/caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver
  File "/root/Downloads/caffe-public-bvlc_googlenet/python/caffe/pycaffe.py", line 10, in <module>
    from ._caffe import Net, SGDSolver
ImportError: /root/anaconda/bin/../lib/libm.so.6: version `GLIBC_2.15' not found (required by /usr/lib/libopencv_core.so.2.3)
root@milton-Desktop:~# 

=============================================================

**Comment by albenoit** [comment]
Hi,
i used to have the same issue on Debian and the solution was to add an additionnal library link : ldl
In Makefile.config, add
LDFLAGS := $(LDFLAGS) -ldl

hope it helps

**Comment by longjon** [comment]
Please ask usage questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) list. Thanks!
