### ISSUE TITLE
call UpgradeNetAsNeeded() in Solver::Restore()?

### ISSUE THREAD

**Issue by moskewcz** [BVLC/caffe#1973]
if not, resuming old training runs where the .solverstate links to a .caffemodel that need an upgrade can have bad results. in particular, V1 nets seem like they can silently load no weights / leave the weights as garbage. this manifests as 0 / initial accuracy and high / initial loss after resuming training.

 see PR #1972

**Comment by longjon** [comment]
Closing as this appears to have been fixed (see comment at #1972).
