### ISSUE TITLE
caffe

### ISSUE THREAD

**Issue by sunilrao43** [BVLC/caffe#1981]
@shelhamer 
I need to parse the .caffemodel to my C code so where can i find the weight and bias blobs
In C++ when  i run a small prediction exapmles the blob named "fc6"
it has only the parameter of height ,width ,input dim,and output dim

where can i find the weights of the particular layer stored 

example:

const boost::shared_ptr<Blob<float> >& fc6Layer = net.blob_by_name("fc6");
const float *fc6s_out = fc6Layer->cpu_data();
    int i = fc6Layer->num();
    int a = fc6Layer->channels();
    int b = fc6Layer->height();
    int c = fc6Layer->width();
    int d = fc6Layer->count(); 

------------------------------------------
THANKS IN ADVANCE @shelhamer

**Comment by sunilrao43** [comment]
@shelhamer waiting for reply please @shelhamer

**Comment by jyegerlehner** [comment]
Usage questions should be posted here:
https://groups.google.com/forum/#!forum/caffe-users

The layers can retrieved from the `Net::layer_by_name()` method (see net.hpp). 

The Layer base class has a public method 
```c++
  /**
   * @brief Returns the vector of learnable parameter blobs.
   */
  vector<shared_ptr<Blob<Dtype> > >& blobs() {
    return blobs_;
  }
```
How many blobs and what they are will be layer-dependent. For example, if we look at `InnerProductLayer::LayerSetUp` in `inner_product_layer.cpp`, blobs[0] is the always the weight matrix, and if the layer has biases, then blob[1] will have the biases. 

And if I may offer a bit of perspective: I think it's unrealistic to expect shelhammer will be at our beck and call whenever we have a question. Our Brewers are busy grad students with studies and research of their own. They don't have to share their code; we benefit from the fact that they do. Let's avoid putting undue demands on them.

**Comment by sunilrao43** [comment]
@jyegerlehner  sure thanks for the reply ..
