### ISSUE TITLE
MemoryDataLayer performs transformations inconsistently

### ISSUE THREAD

**Issue by meijia85** [BVLC/caffe#1983]
in MemoryDataLayer
  top[0]->Reshape(batch_size_, channels_, height_, width_);
  top[1]->Reshape(batch_size_, 1, 1, 1);
  added_data_.Reshape(batch_size_, channels_, height_, width_);
  added_label_.Reshape(batch_size_, 1, 1, 1);

in ImageDataLayer
  if (crop_size > 0) {
    top[0]->Reshape(batch_size, channels, crop_size, crop_size);
    this->prefetch_data_.Reshape(batch_size, channels, crop_size, crop_size);
    this->transformed_data_.Reshape(1, channels, crop_size, crop_size);
  } else {
    top[0]->Reshape(batch_size, channels, height, width);
    this->prefetch_data_.Reshape(batch_size, channels, height, width);
    this->transformed_data_.Reshape(1, channels, height, width);
  }
When crop is used in MemoryDataLayer the result is wrong

**Comment by longjon** [comment]
Thanks for the report; there is a known issue that `MemoryDataLayer` only sometimes performs transformations, which I'll now generalize this issue to.

**Comment by longjon** [comment]
Actually, this is #1784, so continue any discussion there.
