### ISSUE TITLE
can't run mnist example with new version of caffe for not loading the libcaffe.so

### ISSUE THREAD

**Issue by helxsz** [BVLC/caffe#1988]
previously a old version of caffe exists in my computer, and today I just installed a new version of caffe on my ubuntu 14.04, the installation, runtest is all successful.

 However, when I run the ./examples/mnist/train_lenet.sh from CAFFE_ROOT, a error appears saying  ' ./build/tools/caffe: error while loading shared libraries: libcaffe.so: cannot open shared object file: No such file or directory '

**Comment by helxsz** [comment]
I fixed it by export LD_LIBRARY_PATH=/home/admin/caffe2/build/lib:$LD_LIBRARY_PATH, why installation didn't work for this add the path for the library?

**Comment by drohit92** [comment]
To prevent this happening in the fufutre, you can probably add it to your .bashrc

**Comment by sinhaabhit** [comment]
I am having similar trouble. Getting error 
"error while loading shared libraries: libcaffe.so.1.0.0-rc3: cannot open shared object file: No such file or directory"
Please help me out.
