### ISSUE TITLE
Migrate fbfft to accelerate convolutions

### ISSUE THREAD

**Issue by futurely** [BVLC/caffe#1989]
Nicolas Vasilache, Jeff Johnson, Michael Mathieu, Soumith Chintala, Serkan Piantino, Yann LeCun. [Fast Convolutional Nets With fbfft: A GPU Performance Evaluation](http://arxiv.org/abs/1412.7580). ICLR 2015.

Code is available at: https://github.com/facebook/fbcunn

**Comment by bhack** [comment]
Already discussed here https://github.com/BVLC/caffe/pull/544
