### ISSUE TITLE
Implement Microsoft Parametric ReLU and corresponding initialization method to surpass human on ImageNet classification task

### ISSUE THREAD

**Issue by futurely** [BVLC/caffe#1991]
Kaiming He, Xiangyu Zhang, Shaoqing Ren, Jian Sun. [Delving Deep into Rectifiers: Surpassing Human-Level Performance on ImageNet Classification](http://arxiv.org/abs/1502.01852). arXiv:1502.01852 [cs.CV]

**Comment by ducha-aiki** [comment]
See #1940 and #1946
