### ISSUE TITLE
Implement large network distillation as an example

### ISSUE THREAD

**Issue by futurely** [BVLC/caffe#1992]
Geoffrey Hinton, Oriol Vinyals, Jeff Dean. [Distilling the Knowledge in a Neural Network](http://www.dlworkshop.org/65.pdf?attredirects=0). NIPS 2014.

The proposed method is able to consolidate one or more large neural networks into a much smaller model with almost the same performance. This is critical to improve response time of neural networks backed web services and to deploy high performance models into resource limited devices such as smart phones or embedded devices.

For example, the GoogleNet can be used to train an equivalent AlexNet.

**Comment by longjon** [comment]
Again, closing as not an issue with Caffe, but welcome for a (new?) wiki page, and you're also welcome to announce such things on caffe-users.
