### ISSUE TITLE
Support scalar and vector quantization matrix compression

### ISSUE THREAD

**Issue by futurely** [BVLC/caffe#1994]
To enable the matrix compression methods proposed by Gong et. al.[1], a weight matrix needs to be approximated by a codebook and a matrix storing indices pointing to the codebook.

For example, the scalar quantization uses kmeans to produce a scalar codebook of size k and the original matrix values are replaced with the closed codebook indices which are integers between 0 to k-1. Thus 32-bit float numbers are compressed into log2(k)-bit integers.

The vector quantization method is similar except the row or column vectors are splitted into multiple segments with equal length before applying kmeans clustering on each segment. The output segment-wise vector codebooks also require more spaces.

[1] Yunchao Gong, Liu Liu, Ming Yang, Lubomir Bourdev. [Compressing Deep Convolutional Networks using Vector Quantization](http://arxiv.org/abs/1412.6115). ICLR 2015.

**Comment by longjon** [comment]
Closing as this is not an issue with Caffe. You're welcome to document desirable algorithms to support on the wiki.
