### ISSUE TITLE
How define the number of INNER_PRODUCT Layer + Regression

### ISSUE THREAD

**Issue by souzou** [BVLC/caffe#1996]
Hello,

I have some confusion about the number of INNER_PRODUCT Layer in two class Regression Problem.
The input of the Eucludian_Loss layer should be at the value of one.

----------------------------------------------------------------------
layers {
  name: "fc8"
  type: INNER_PRODUCT
  blobs_lr: 1         
  blobs_lr: 2        
  weight_decay: 1   
  weight_decay: 0      
  inner_product_param {
    num_output: 1
    weight_filler {
      type: "gaussian"
      std: 0.01
    }
    bias_filler {
      type: "constant"
      value: 0
    }
  }
  bottom: "fc7"
  top: "fc8"
}
layers{
name:"loss"
type: EUCLIDEAN_LOSS
bottom: "fc8"
bottom:"label"
top:"loss"
}

--------------------------------------------------------------

My question is how mutch of number of INNER_PRODUCT layer shoud I have, if the output of the last  Convolution layer is : num_output=256 to obtain at the final INNER_PRODUCT layer  2 output...????
Just if it have any mathematical reason or the number is chosen randomly?
Thanks,

**Comment by shelhamer** [comment]
Please ask modeling questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) group. `num_output` is the number of outputs for the task.
