### ISSUE TITLE
Pillow needed for filter_visualization.ipynb

### ISSUE THREAD

**Issue by danielhamngren** [BVLC/caffe#1997]
Hi, I was having some problems when following the ipython notebook examples. I got the error:
```
AttributeError: 'builtin_function_or_method' object has no attribute 'iterkeys'
```
when running the following line
```
scores = net.predict([caffe.io.load_image(caffe_root + 'examples/images/cat.jpg')])
```
The problem was resolved by installing the package Pillow with pip.
Since I'm new to this project I don't know the process on contributing, can I just add the line 
```
pillow>=2.70
```
to https://github.com/BVLC/caffe/blob/master/python/requirements.txt and do a pull request?

**Comment by shelhamer** [comment]
> can I just add the line
> pillow>=2.70
> to https://github.com/BVLC/caffe/blob/master/python/requirements.txt and do a pull request?

Please do, then close this issue with a reference to your pull request. Thanks.

**Comment by danielhamngren** [comment]
All right! It is done :-)

The pull request is over here https://github.com/BVLC/caffe/pull/2010
