### ISSUE TITLE
"Binary compatibility break" in creating new python layer 

### ISSUE THREAD

**Issue by Edward12138** [BVLC/caffe#2000]
When I was trying the new python layer "test_python_layer.py", a problem occurred saying "QMetaType::registerType: Binary compatibility break".  The errors it gave are:

Creating layer testpython..
QMetaType::registerType: Binary compatibility break -- Size mismatch for type 'QPaintBufferCacheEntry' [1024]. Previously registered size 16, now registering size 0.

I'm not sure why there will be a binary file problem, I followed the installation document step by step.

Thanks!

**Comment by Edward12138** [comment]
I'm adding the sample python layer on top of flickr tine tune net for trial.  Wondering if you could give me a hint on where I can find QT-related codes to try on.. @shelhamer 

Thank you! :)

**Comment by Edward12138** [comment]
I've fixed this problem. My computer is installed with Qt5.3. It seems that if I am using anaconda instead of python, anaconda will call qt4 which is conflicted with qt5.x. And it'll generate this problem.

When I googled anaconda compatible with Qt5, I didn't find anything.. So I just use python instead of anaconda then it's fixed. 
Maybe this could be useful for you guys about the new python layer. @shelhamer

**Comment by shelhamer** [comment]
Sorry, this doesn't make sense to me -- Caffe has no dependency on QT and it is used nowhere in the C++ or Python code. I'm not sure how it was linked in on your system although it perhaps came in by a library accompanying the dependencies with your configuration.

At least if other users encounter this they'll have your notes.
