### ISSUE TITLE
Speed benchmarking for classification in CPU mode

### ISSUE THREAD

**Issue by vaibhawchandel** [BVLC/caffe#2003]
I am running first five convolutional layers of Zeiler model in CPU mode. 
It is mentioned in this [presentation: slide#7](http://dl.caffe.berkeleyvision.org/caffe-presentation.pdf) that forward propagation for one image can be brought out to the order of 20 ms in cpu if run in batch mode. 

When I ran the model for a single image and batch size of 50, following is the runtime for forward propagation

Batch Size |  GPU   |   CPU
-------------  | ---------- | --------
1                |  0.007s  |   0.3s
50              |  0.38s    |  11.8s

Even when I run the Caffenet model, timings are of the same order as Zeiler model.

Server Specifications:
CPU: Intel(R) Xeon(R) CPU E5-2650 0 @ 2.00GHz with 8 cores
RAM: 32 GB
OS: Ubuntu 12.04 64bit
Blas Library: OpenBLAS

The computation time I am getting is almost 10 times slower than what is mentioned on webpage. Am I doing something wrong or missing something which can speed up the calculations. 

Using GPU is not an option because of scalability issues.

**Comment by longjon** [comment]
Our reported timings are using MKL. I wouldn't expect such a large difference with OpenBLAS, but you might want to try MKL..

**Comment by longjon** [comment]
Closing as there doesn't seem to be an issue with Caffe here. You're welcome to open new issues if you do find specific performance bugs.
