### ISSUE TITLE
relocation R_X86_64_32S against `_ZTVN7leveldb2DBE' 

### ISSUE THREAD

**Issue by hayderm** [BVLC/caffe#2008]
Please, could someone help me with this issue? I have compiled caffe and gotten this message error 

VCC src/caffe/layers/cudnn_sigmoid_layer.cu
NVCC src/caffe/layers/im2col_layer.cu
NVCC src/caffe/layers/pooling_layer.cu
NVCC src/caffe/layers/lrn_layer.cu
NVCC src/caffe/layers/cudnn_pooling_layer.cu
NVCC src/caffe/layers/inner_product_layer.cu
NVCC src/caffe/layers/power_layer.cu
NVCC src/caffe/layers/eltwise_layer.cu
NVCC src/caffe/layers/exp_layer.cu
NVCC src/caffe/layers/conv_layer.cu
NVCC src/caffe/layers/softmax_loss_layer.cu
NVCC src/caffe/layers/relu_layer.cu
NVCC src/caffe/layers/sigmoid_layer.cu
NVCC src/caffe/layers/hdf5_data_layer.cu
NVCC src/caffe/layers/hdf5_output_layer.cu
NVCC src/caffe/layers/euclidean_loss_layer.cu
AR -o .build_release/lib/libcaffe.a
LD -o .build_release/lib/libcaffe.so
/usr/bin/ld: /usr/local/lib/libleveldb.a(db_impl.o): relocation R_X86_64_32S against `_ZTVN7leveldb2DBE' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libleveldb.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
make: *** [.build_release/lib/libcaffe.so] Error 1

**Comment by n-zhang** [comment]
We welcome you to look at the extensive documentation, tutorials, and examples at http://caffe.berkeleyvision.org/ 
However, please ask usage questions on [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) -- this issues tracker is primarily for Caffe development discussion. Thanks!

**Comment by jeckian** [comment]
How to solve the problem?

**Comment by jeckian** [comment]
I have the same problem
