### ISSUE TITLE
ISSUE On Using Imagenet to Train My Database

### ISSUE THREAD

**Issue by lanshishi** [BVLC/caffe#2011]
Dear all,
I use my imagenet to train my database. But there is some problem when use ./create_imagenets.sh:

Creating train lmdb...
I0302 11:50:01.329725 19180 convert_imageset.cpp:70] Shuffling data
I0302 11:50:01.330209 19180 convert_imageset.cpp:73] A total of 269 images.
I0302 11:50:01.330230 19180 convert_imageset.cpp:104] Opening lmdb /home/tom/caffe/coco/coco_train_lmdb
F0302 11:50:01.340950 19180 convert_imageset.cpp:157] Check failed: mdb_put(mdb_txn, mdb_dbi, &mdb_key, &mdb_data, 0) == 0 (-30792 vs. 0) mdb_put failed
*** Check failure stack trace: ***
Aborted (core dumped)
Creating val lmdb...
I0302 11:50:01.422473 19182 convert_imageset.cpp:70] Shuain My Databaseffling data
I0302 11:50:01.422925 19182 convert_imageset.cpp:73] A total of 40 images.
I0302 11:50:01.422947 19182 convert_imageset.cpp:104] Opening lmdb /home/tom/caffe/coco/coco_val_lmdb
F0302 11:50:01.433758 19182 convert_imageset.cpp:157] Check failed: mdb_put(mdb_txn, mdb_dbi, &mdb_key, &mdb_data, 0) == 0 (-30792 vs. 0) mdb_put failed
*** Check failure stack trace: ***
Aborted (core dumped)
Done.

How can I fix this problem??

**Comment by zixiaofan** [comment]
I meet the same question.when I want to creat leveldb to replace lmdb,I meet the other question.
GLOG_logtostderr=1 $TOOLS/convert_imageset \
    --resize_height=$RESIZE_HEIGHT \
    --resize_width=$RESIZE_WIDTH \
    --shuffle \
    --backend='leveldb'
    $TRAIN_DATA_ROOT \
    $DATA/train.txt \
    $EXAMPLE/ilsvrc12_train_lmdb

**Comment by lanshishi** [comment]
Actually, when I change another computer to create lmdb, the problem didn't exist. I don't know why~~

**Comment by n-zhang** [comment]
We welcome you to look at the extensive documentation, tutorials, and examples at http://caffe.berkeleyvision.org/ 
However, please ask usage questions on [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) -- this issues tracker is primarily for Caffe development discussion. Thanks!
