### ISSUE TITLE
make matcaffe error on Mac OS X Yosemite

### ISSUE THREAD

**Issue by courosh** [BVLC/caffe#2014]
I am a newbie to Caffe. I have Mac OSX 10.10 and Matlab 2014b.

I have successfully run these caffe builds:

make all
make test
make runtest (all tests passed)
make pycaffe

But I am getting an error with

make matcaffe

The build gets down to this line

MEX matlab/caffe/matcaffe.cpp

and gives this error:

dyld: Symbol not found: __ZN6matrix6detail10noninlined12mx_array_api10mxMallocExEm
  Referenced from: /Applications/MATLAB_R2014b.app/bin/maci64/libmwm_dispatcher.dylib
  Expected in: /usr/lib/libSystem.B.dylib
 in /Applications/MATLAB_R2014b.app/bin/maci64/libmwm_dispatcher.dylib
/Applications/MATLAB_R2014b.app/bin/mex: line 365:  8206 Trace/BPT trap: 5       $MATLAB/bin/maci64/mex $args
make: *** [matlab/caffe/caffe.mexmaci64] Error 133

I have followed the procedures in these posts:

[Mathworks] (http://www.mathworks.com/matlabcentral/answers/103904-can-i-use-xcode-5-as-my-c-or-c-compiler-in-matlab-8-1-r2013a-or-matlab-8-2-r2013b)

[Github 915] (https://github.com/BVLC/caffe/issues/915)

The problem is still there.

Can anyone kindly help?

Thanks,
Courosh

**Comment by greatgao** [comment]
Ｉ　had installed the Caffe  in Ubuntu 12.04.And now I want to run the Caffe in MAC OS X10.10.2,but there is some problems about to Install BLAS.How do you solve the question?What's Guide document  you followed?And I can't make all in the caffe file.

**Comment by n-zhang** [comment]
We welcome you to look at the extensive documentation, tutorials, and examples at http://caffe.berkeleyvision.org/ 
However, please ask usage questions on [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) -- this issues tracker is primarily for Caffe development discussion. Thanks!

**Comment by SamiMourad** [comment]
courosh how'd you solve your problem? It might be a MATLAB 2014 vs. MATLAB 2012 thing.
