### ISSUE TITLE
caffe  on  Jetson  TK1

### ISSUE THREAD

**Issue by wzq12138** [BVLC/caffe#2022]
Hello  everyone,I  am  a student  from  China,I have  to  write  a  paper  about  caffe  and  jetson  tk1.
I  am  doing  the  imagenet  examples  which  is  called  thr  vehicle  color  classification.I  have  some  questions  to  ask.
1.How  can  I  know  the  TK1 is  faster  than  my computer,as  I  did,TK1  could  not  training  but  only  run  caffe .it means  TK1 is   used  to  run  the  model  which  is  trained  on  the other  computer.so  it  is  not  accelerationed  on   training.
2.when   I  was  training  the  model  ,the  accuracy  is   about  0.4  all  the  time,is  not  it  should  be  increased  by  the  interation  to 0.999?why  is  this?
3.is   there  anybody  make  caffe  on  TK1,with  cuda6.5  and  cudnn6.5.I  am  very  confused  about   how   to  see  it  is   faster  the  computer.as  the  queston 1,is   there  some  command  to  show  the  time or  show  some  the  result  to  let  me  know,it  is  better  than  my  computrt.then   I  can  figure  out  the  TK1 is  better  than  my  computer  on  my  paper
4.is   there  some  paper  about  what  I  am  doing,as  I  am  in  China ,I   could   not  use   google.

thanks   everyone,my  English  is   not   good.sorry  about   this.

**Comment by beniz** [comment]
> 3.is there anybody make caffe on TK1,with cuda6.5 and cudnn6.5
This might help you:
http://jetsonhacks.com/2015/01/20/nvidia-jetson-tk1-cudnn-install-caffe-example/

**Comment by Yangqing** [comment]
A few pointers that you might find useful:

(1) TK1 is probably not going to be faster than your desktop CPU if it has a few (like 4 or 8) cores. It is definitely not going to be faster if you use a modern desktop GPU.
(2) TK1 is probably most fit for deployment in low-power environments.
(3) TK1 can probably only train with relatively small data. If you need to train e.g. imagnet data, there are two potential issues to address:
    - The GPU memory is really limited, and is probably not solveable.
    - The on-board storage is limited, and you may need to attach a hard disk to TK1. I think there is a SATA port as well as a molex power supply for that.

Also, I've written a recipe to build caffe on TK1, and my colleague Pete Warden kindly compiled it to a nice article here:

http://petewarden.com/2014/10/25/how-to-run-the-caffe-deep-learning-vision-library-on-nvidias-jetson-mobile-gpu-board/

Back then there was no cudnn, but I assume it would be easy - just download cudnn, put it under the right folder, and build.
