### ISSUE TITLE
how  to  use  cudnn

### ISSUE THREAD

**Issue by wzq12138** [BVLC/caffe#2024]
I  know  make  caffe  with  cudnn  is  
# cuDNN acceleration switch (uncomment to build with cuDNN).
USE_CUDNN := 1

I  want  to  ask  how  to  change  it  to  cudnn mode  ,as  I  know  gpu  and  cpu  is  like  that:
caffe.set_mode_gpu()   and   caffe.set_mode_cpu()

what  the  command  is  when  I  want  to  use  cudnn.

**Comment by ducha-aiki** [comment]
It is used by default, so no command.

**Comment by wzq12138** [comment]
@ducha-aiki    thanks  for  the  answer.  anther  question  ,how  can  I   see  the  time  change,I  want  to  do  the  experiment  to  know  the  time,in  the  web,   http://devblogs.nvidia.com/parallelforall/deep-learning-computer-vision-caffe-cudnn/      it  said  

	Caffe	Caffe + cuDNN	Speedup
Training	1325 ms	960 ms	1.38
Testing	100 ms	66.7 ms	1.50



can  you   tell   me  how  to know  the  time,is  there  any  comand?

**Comment by lugiavn** [comment]
What I'd do is: uninstall cuDNN, train something, measure the time.
Then install cuDNN, train the same thing and measure the time. Compare.
There're timestamps in the log files, or you can use http://manpages.ubuntu.com/manpages/maverick/man1/time.1.html

**Comment by zxzhijia** [comment]
@lugiavn 
How to uninstall cuDNN?

**Comment by ronalddas** [comment]
@zxzhijia  You can just remove the include and libs files. It worked for me.
