### ISSUE TITLE
Include missing in blob.hpp to compile solver.cpp

### ISSUE THREAD

**Issue by albenoit** [BVLC/caffe#2027]
After last code update, compilation fails on Debian testing for the following reason in file include/caffe/blob.hpp :
```
CXX src/caffe/solver.cpp
In file included from ./include/caffe/net.hpp:10:0,
                 from src/caffe/solver.cpp:7:
./include/caffe/blob.hpp:13:26: error: ‘INT_MAX’ was not declared in this scope
 const int kMaxBlobAxes = INT_MAX;
```
This problem can be solved easily by adding the missing include
```
 #include <climits>
```
However, it should be more elegant to add this include into another header already included in this file
(maybe in caffe/common.hpp ?).

Thank you for this great library !

**Comment by jeffdonahue** [comment]
Thanks for reporting this, let us know if you still have problems after #2035.

**Comment by albenoit** [comment]
Hi, thanks for this quick push !

it now compiles fine on Debian testing, CPU mode.

Good and thank you again !
   Alex

2015-03-05 0:54 GMT+01:00 Jeff Donahue <notifications@github.com>:

> Thanks for reporting this, let us know if you still have problems after
> #2035 <https://github.com/BVLC/caffe/pull/2035>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BVLC/caffe/issues/2027#issuecomment-77277348>.
>



-- 
Alexandre BENOIT,
Associate Professor / Maître de Conférence
Image processing and visual scene classification,
LISTIC Lab / IUT Annecy
https://sites.google.com/site/benoitalexandrevision/
