### ISSUE TITLE
Read Caffe Features to a txt file for further analysis

### ISSUE THREAD

**Issue by kilickaya** [BVLC/caffe#2043]
Hi everyone,

I'm using tools/extract_features.cpp to extract features of a set of images in my dataset. Caffe extracts and saves features in leveldb format. 

However I conduct most of my analysis on Matlab, so I try to read extracted features to a txt file where each row corresponds to the features of a single image.

I use simple iterator examples provided on leveldb's website, and iterate through all keys and values stored in the database, and printing them to a text file. But at the end I get these strange characters in my text file:

![untitled](https://cloud.githubusercontent.com/assets/8891413/6506505/51cc575a-c354-11e4-9f5d-92c9ce9b28aa.png)
 
 I read that leveldb stores data in BYTE array format, but if this is the case, I do not know how to convert this format to a human consumable format (i.e: floating point values like 0.3 0.788 etc)

Thanks in advance for your help and support!

**Comment by mauriciolp** [comment]
I am having the same issue here, for me it is not clear how to convert the DB information to human consumable format.

As an workaround, I intend to perform the feature extraction with python, based on the [tutorial](http://nbviewer.ipython.org/github/BVLC/caffe/blob/master/examples/filter_visualization.ipynb) and ```python/classify.py``` script.

**Comment by longjon** [comment]
Please ask usage questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) list. Thanks!

**Comment by Dev2022** [comment]
I also have the same problem. Can you please let me know if you have got the answer.Thanks

**Comment by kilickaya** [comment]
Sadly, I do not have any improvements over this.

**Comment by didpurwanto** [comment]
I have a problem too, same with this. Anyone know? Thanks
