### ISSUE TITLE
Examples on how to add data labels on top of an arbitrary prototxt file

### ISSUE THREAD

**Issue by kilickaya** [BVLC/caffe#2044]
Hi,

I've succesfully used Caffe  (tools/extract_features.cpp) and the standard prototxt file (imagenet.prototxt) to extract features from images. Now I would like to be able to use any other models to extract features, conduct analysis. 

As everybody knows, we should add a "data_layer" on top of every prototxt file to be able to use it with Caffe, which explains crop size, the source directory where images stored, and the path of the mean image binary, etc.

Could anybody please explain how to add those data layers to a prototxt file?  If we can use places model as a running example: http://places.csail.mit.edu/ this would be awesome.

**Comment by n-zhang** [comment]
We welcome you to look at the extensive documentation, tutorials, and examples at http://caffe.berkeleyvision.org/, the data layer tutorial is here http://caffe.berkeleyvision.org/tutorial/data.html
However, please ask usage questions on [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) -- this issues tracker is primarily for Caffe development discussion. Thanks!
