### ISSUE TITLE
Getting "error while loading shared libraries: libleveldb.so.1" when running "make runtest"

### ISSUE THREAD

**Issue by izCACI** [BVLC/caffe#2045]
I am trying to install caffe using instructions from the main install page http://caffe.berkeleyvision.org/installation.html. To get "make all" and "make test" work, I had to add multiple paths to INCLUDE_DIRS and LIBRARY_DIRS of Makefile.config. Now I am running "make runtest" and getting:

 make runtest
.build_release/tools/caffe
.build_release/tools/caffe: error while loading shared libraries: libleveldb.so.1: cannot open shared object file: No such file or directory
make: *** [runtest] Error 127

How can I fix this? Thx

**Comment by izCACI** [comment]
Forgot to mention: I am building it on an AWS Ubuntu instance

**Comment by n-zhang** [comment]
It seems that you either didn't install leveldb correctly or didn't include the leveldb path correctly. Please ask usage questions on [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) -- this issues tracker is primarily for Caffe development discussion. Thanks!
