### ISSUE TITLE
failure when running make_imagenet_mean.sh

### ISSUE THREAD

**Issue by WanzhengZhu** [BVLC/caffe#2062]
I would like to run imagenet example (BTW, I can successfully the mnist example), however, when i do image mean computing
./examples/imagenet/make_imagenet_mean.sh
it popped up error message as below:

F0307 22:00:48.693943  3415 db.hpp:109] Check failed: mdb_status == 0 (2 vs. 0) No such file or directory
*** Check failure stack trace: ***
    @     0x7f4c83f25daa  (unknown)
    @     0x7f4c83f25ce4  (unknown)
    @     0x7f4c83f256e6  (unknown)
    @     0x7f4c83f28687  (unknown)
    @     0x7f4c8430f9fe  caffe::db::LMDB::Open()
    @           0x4019f4  main
    @     0x7f4c83135ec5  (unknown)
    @           0x40243a  (unknown)
    @              (nil)  (unknown)
Aborted (core dumped)
Done.

Anyone got any idea? Many thanks for helping me!

**Comment by tishibas** [comment]
It may be same problem in #1506 .
The bug has already fixed in #2055 .
Git pull from master branch of Caffe or change the code of make_imagenet_mean.sh.

**Comment by WanzhengZhu** [comment]
Thank you!!! I just noticed that bug. Thanks for your help. @tishibas

**Comment by snapo** [comment]
i have exactly the same problem 
running cpu only ..... if i execute 
root@vultr:~/caffe# ./examples/mnist/train_lenet.sh

**Comment by atique81** [comment]
Dear @WanzhengZhu and @tishibas 

I am running a caffe PR made available by @longjon (https://github.com/longjon/caffe/tree/future). I am stuck with the same problem while trying to read the label lmdb files, though the image lbdb files get passed. Could you please explain what was the fix you applied in your case?

I would highly appreciate your response.

**Comment by WanzhengZhu** [comment]
@atique81 
Please see this:
https://github.com/BVLC/caffe/issues/1506

**Comment by atique81** [comment]
Dear @WanzhengZhu  thanks a lot for responding. However, I am not using make_imagenet_mean.sh to create mean files for ilsvrc dataset, but the python script as mentioned in #1698 to create my lmdb files both for images and their ground-truth labels on pascal voc dataset. For the image lbdb, caffe is successful in reading them, but for the gound-truth labels' corresponding lmdb, it is generating the error.

Please not that, I am subtracting image mean, not with the help of a mean file, but by following transform param, though the error pops up for the label lmdb file. 

Any help would be highly appreciated

  transform_param {
    mean_value: 104.00699
    mean_value: 116.66877
    mean_value: 122.67892
  }

**Comment by WanzhengZhu** [comment]
@atique81  Hi, I used caffe quite a long time ago, I forgot the things you are talking about already. sorry that I couldn't help.

**Comment by atique81** [comment]
Dear @WanzhengZhu 

Thanks a lot for your kind response....I am trying to figure it out....
