### ISSUE TITLE
Which `mean` produces better classification performance, empirically?

### ISSUE THREAD

**Issue by lxduan** [BVLC/caffe#2069]
I found from this [example](http://nbviewer.ipython.org/github/BVLC/caffe/blob/master/examples/classification.ipynb) that `mean` is set as `np.load(caffe_root + 'python/caffe/imagenet/ilsvrc_2012_mean.npy').mean(1).mean(1)` in `net = caffe.Classifier(...)`, which basically means to subtract the overall mean value, over each color channel, from each element in a given image matrix. Actually, I feel it is more appropriate to do a pixel-wise subtraction using the full mean matrix.

In terms of classification performance, is `mean=np.load(caffe_root + 'python/caffe/imagenet/ilsvrc_2012_mean.npy')` better or `np.load(caffe_root + 'python/caffe/imagenet/ilsvrc_2012_mean.npy').mean(1).mean(1)`, empirically?

Thank you.

**Comment by shelhamer** [comment]
The same pre-processing at train and test time is best empirically whether mean pixel or mean image. One of the strongest ILSVRC models, VGG, is learned with a mean pixel.

Even switching a model learned with a mean image, like CaffeNet, and switching to a mean pixel has next to no effect in my experience. Inspect the ILSVRC mean to see that it is nearly spatially constant.

The important exception can be if you are in a domain with registered data for which absolute position is informative, but that's a whole modeling discussion in itself and not about the mean alone.

This kind of modeling question should be asked on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) group.

**Comment by deepalianeja** [comment]
So if all the data is centrally registered and similar, so mean pixel is better?
