### ISSUE TITLE
conv_layer parameter: group 

### ISSUE THREAD

**Issue by jeehye** [BVLC/caffe#2074]
I tried to use group parameter in convolution layer

I have 2 input channels and want to get 8 output channels.
Then, input channel 1 make output channels 1-4 into the first group 
and input channel 2 make output channels 5-8 into the second group.
In this case, output channel 1 and 5 use same convolution filter??

**Comment by lugiavn** [comment]
I think each output channel corresponds to one filter, so basically you have 10 different filters.

**Comment by shelhamer** [comment]
Search for past issues on group convolution for an explanation. `group: 2` means that the first half of the input channels are connected to the first half of the output channels and likewise for the second halves of the input and output channels.
