### ISSUE TITLE
R-CNN detection using "Selective Search" component

### ISSUE THREAD

**Issue by waelHamdan** [BVLC/caffe#2080]
Dear all,

I would like to know if I use the a Similar code from R-CNN that uses MatLab inside the component "Selective Search", Do I need a license for MatLab?. and does it affect the licence of Caffe?

Thanks

**Comment by n-zhang** [comment]
If you want to try the opensource selective search code in matlab. You need to install matlab and get matlab license. It has nothing to do with Caffe.
