### ISSUE TITLE
Can this software be installed in user space? 

### ISSUE THREAD

**Issue by kangtianyu** [BVLC/caffe#2087]
I'm trying install caffe in a remote GPU cluster. But that machine doesn't have many prerequisites of caffe. I'm not authorized run sudo on that machine. I asked the administrators to help me but they seemed not have time to do this. They give me an advice that I could install caffe in user space. Anyone know how to do that?

**Comment by dabilied** [comment]
you can install those softwares caffe needed on your  own space ,  which doesn't need root  authority, such as on ~kangtianyu/environment
