### ISSUE TITLE
caffe set phase 

### ISSUE THREAD

**Issue by sunilrao43** [BVLC/caffe#2094]
Net<float> net("./examples/bvlc_alexnet/bvlc_alexnet.prototxt");
 how do i set phase in cafffe

**Comment by n-zhang** [comment]
When you run the build/tools/caffe.bin, you can set either train or test. We welcome you to look at the extensive documentation, tutorials, and examples at http://caffe.berkeleyvision.org/ and ask usage questions on [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) -- this issues tracker is primarily for Caffe development discussion. Thanks!
