### ISSUE TITLE
Leveldb data format

### ISSUE THREAD

**Issue by jackiechensuper** [BVLC/caffe#21]
Hi guys, since my data set is in matlab .mat file, I want to convert it to leveldb format, so it can be  used in caffe frame, can you give me some hints? Many thanks.

**Comment by peerajak** [comment]
Thanx ChenlongChen

I just follow what you say, and now can transform cifar10 .mat format to binary format, then just follow the cifar10 example and get the correct training accuracy.
Matlab code
```
for i=1:5
name_load= sprintf('data_batch_%d',i);
name_bin = sprintf('data_batch_%d.bin',i);
load(name_load);
dlabels = [labels data]';
fileID = fopen(name_bin,'w');
fwrite(fileID,dlabels,'uint8');
fclose(fileID);
end
```
