### ISSUE TITLE
A simple case for two class classification

### ISSUE THREAD

**Issue by WanzhengZhu** [BVLC/caffe#2100]
Hi, guys. I am very new with caffe. 
Now I am doing a small example of two class classification examples. I used 400 bird pictures and 100 cat pictures in total for training, validating and testing. 
Can anyone share with me how you would deal with this problem? 
What is the layer configuration you would recommend (base_lr, stepsize, weight_decay, momentum, gamma,etc.) ? 
How should i adjust the test_iter? (I don't understand what does test_iter mean?! Do you know that?)
Another question is: where we can write validation layer configuration? Where to adjust all the parameters for validation layer? Because I didn't see anything about validation for the imagenet example. 
Thank you in advance!!!!!!! For any help!!!!!!!
Many appreciations!

**Comment by n-zhang** [comment]
We welcome you to look at the extensive documentation, tutorials, and examples at http://caffe.berkeleyvision.org/ and ask any usage questions on [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) -- this issues tracker is primarily for Caffe development discussion.
