### ISSUE TITLE
RAM usage

### ISSUE THREAD

**Issue by adikhosla** [BVLC/caffe#2121]
The RAM usage of Caffe seems to be quite erratic and inexplicable. We have a machine with a few K40s and about 224GB RAM, and somehow the combination of a few caffe processes seem to be using 300GB of RAM (see image below - RES column). Further, despite this, we are able to run a few more processes that seem to use about 400GB RAM total. This is fine for machines where there are no strict queues and RAM limits, but for certain clusters the RAM requested is strictly enforced, and they keep killing the processes because of the erratic RAM usage (i.e. exceeding my allocated 160GB of RAM).

![caffe_memory](https://cloud.githubusercontent.com/assets/667613/6644174/55dee12a-c988-11e4-80da-948cb61db9e1.png)

Some basic information about the system:
OS: Ubuntu 12.04
Networks being trained: AlexNet style networks on ImageNet LMDB
BLAS: MKL
Branch: Master pulled just a few days ago, compiled with cuDNN (this issue occurs without cuDNN as well)

When compiling, 'make runtest' runs without issue. The outputs of the networks are fine. Just the RAM usage is inexplicable.

I do not know if its just us having this issue or others are facing it too. We have the same behavior on multiple machines. I apologize if this issue has already been filed - I tried to do a brief search but couldn't find it. Any suggestions would be greatly appreciated.

Thanks!

**Comment by cvondrick** [comment]
Minor comment that may be helpful for anyone debugging: It seems caffe loads the entire LMDB into memory. Once the data loader has completed a full pass through the LMDB, the memory usage will stay constant. So, I think these memory issues are due to some sort of caching in the data loader.

**Comment by sguada** [comment]
Yeah the RAM usage is due to how LMDB handle the DB, it just map the file
into page memory, reserving up to 1TB of virtual memory and letting the os
to handle it.

You could try leveldb instead, which is much more memory friendly, but will
need to make symbolic links since it doesn't allow more than one instance
open the same leveldb.

Sergio

2015-03-18 7:29 GMT-07:00 Carl Vondrick <notifications@github.com>:

**Comment by adikhosla** [comment]
Ah I see. Thanks for the information! I did not realize that this had led to our memory woes as we were doing fine earlier when LevelDBs were the norm.
