### ISSUE TITLE
layerwise pretraining not supported?

### ISSUE THREAD

**Issue by AminSuzani** [BVLC/caffe#2122]
Hi,

I was wondering if there is a way to train a neural network layer-by-layer using Caffe (either supervised or unsupervised). It is a popular approach for training deep neural networks and autoencoders, but I did not find it in any examples in this repository. Is it not supported in Caffe? or for specific types of networks it is the default training approach?

Thanks in advance.

**Comment by n-zhang** [comment]
One way to do that is you can set blobs_lr = 0 of each layer to freeze the back propagation of that layer. By doing that, you can train the net layer-by-layer. 

We welcome you to look at the extensive documentation, tutorials, and examples at http://caffe.berkeleyvision.org/ 
However, please ask usage questions on [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) -- this issues tracker is primarily for Caffe development discussion. Thanks!
