### ISSUE TITLE
CIFAR10 model in caffe

### ISSUE THREAD

**Issue by bharatsingh430** [BVLC/caffe#2124]
Hi,

Is there a prototxt file in caffe for CIFAR10 which gives 11% error rate as shown here https://code.google.com/p/cuda-convnet/? I think the CIFAR10 full model provided in caffe gives around 81.x% accuracy. Would it be possible for someone to point to a location where I could find the network parameter file for CIFAR10?

**Comment by longjon** [comment]
Please ask usage questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) list. Thanks!
