### ISSUE TITLE
mdb_put failed MDB_MAP_FULL

### ISSUE THREAD

**Issue by dabilied** [BVLC/caffe#2128]
when I use caffe for very big  dataset , 
 convert_imageset.cpp:136] Processed 5476000 files.
E0314 07:58:45.217167 32177 lmdb_dataset.cpp:118] mdb_put failed MDB_MAP_FULL: Environment mapsize limit reached
F0314 07:58:45.217581 32177 convert_imageset.cpp:131] Check failed: dataset->put(string(key_cstr, length), datum)
*** Check failure stack trace: ***
    @     0x7f9d8ae6b42d  google::LogMessage::Fail()
    @     0x7f9d8ae6d1f3  google::LogMessage::SendToLog()
    @     0x7f9d8ae6b048  google::LogMessage::Flush()
    @     0x7f9d8ae6da4e  google::LogMessageFatal::~LogMessageFatal()
    @           0x4263b0  main
    @       0x3cbc01ecdd  (unknown)
    @           0x4240d1  (unknown)
./create_imagenet.sh: line 44: 32177 Aborted                 (core dumped) GLOG_logtostderr=1 $TOOLS/convert_imageset --resize_height=$RESIZE_HEIGHT --resize_width=$RESIZE_WIDTH --shuffle $TRAIN_DATA_ROOT $DATA/combine_train.txt $EXAMPLE/combine_train_lmdb

I'm not sure  if my machine have some limitations, As process more than 6M images will takes a lot of time, can someone helps why this error could happen .

**Comment by n-zhang** [comment]
We welcome you to look at the extensive documentation, tutorials, and examples at http://caffe.berkeleyvision.org/ 
However, please ask usage questions on [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) -- this issues tracker is primarily for Caffe development discussion. Thanks!
