### ISSUE TITLE
leveldb: LOCK: Resource temporarily unavailable

### ISSUE THREAD

**Issue by jetliwei123** [BVLC/caffe#2131]
In my project, there is a suse11 sp3 which is my project server, and repository type is NFS which store all of my data include leveldb database. The operator system crash during I do some task which will open the leveldb database, then after the operator recover, I continue did the same task, but all task failed, the failed reason is: XX/XX/LOCK:Resource temporarily unavailable(the leveldb path). what can I do and could you please help me?

**Comment by n-zhang** [comment]
Leveldb has a lock that only allows one process to open it and that is where the complaint comes from. You can choose to use that data layers or create duplicated leveldb.

We welcome you to look at the extensive documentation, tutorials, and examples at http://caffe.berkeleyvision.org/ 
However, please ask usage questions on [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) -- this issues tracker is primarily for Caffe development discussion. Thanks!
