### ISSUE TITLE
Has anyone test Batch Normalization technique in general models?

### ISSUE THREAD

**Issue by RalphMao** [BVLC/caffe#2132]
I guess this technique is quite easy to fit into caffe
I am planning to do so, but before that I'd like to know if anyone has already made it.

The link of the paper is here
https://www.google.ca/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0CBwQFjAA&url=http%3A%2F%2Farxiv.org%2Fabs%2F1502.03167&ei=FYkGVfzXA8eRoQTr4oLgAQ&usg=AFQjCNHG7iTJA_dAepV1W6VhFR_CaRCZ3Q&bvm=bv.88198703,d.cGU

**Comment by ducha-aiki** [comment]
#1965
