### ISSUE TITLE
Visualization tools in Caffe

### ISSUE THREAD

**Issue by JiaxuZhu** [BVLC/caffe#2133]
I wanna build visualization tools in Caffe as my graduation program.
And I plan to start to from 
http://arxiv.org/abs/1311.2901
which uses deconvnet to mapping activitions back to the input pixel space.

The deconvnet has MATLAB code 
http://www.matthewzeiler.com/software/DeconvNetToolbox2/DeconvNetToolbox.zip

Is there any visualization tool already in Caffe?
And as a beginner, could you please give me some advice.
Thank you very much.

**Comment by dxj19831029** [comment]
there is discussion on: #481

**Comment by JiaxuZhu** [comment]
Thanks.
But what I am going to do is not a UI but a tool that can map activitions back to the input pixel space which can help people can more insight of the CNN

**Comment by erictzeng** [comment]
We have a DeconvolutionLayer already, if that's what you're looking for. See #1615 for more details.

If you're completely new to Caffe, there's a lot of examples on the website that you should definitely take a look at: http://caffe.berkeleyvision.org

If you have further questions, though, please ask them on [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) -- this issues tracker is primarily for Caffe development discussion. Thanks, and good luck!

**Comment by wxjay123** [comment]
The deconvnet has MATLAB code
http://www.matthewzeiler.com/software/DeconvNetToolbox2/DeconvNetToolbox.zip 
这个代码你有吗？？

**Comment by soulslicer** [comment]
Link does not work
