### ISSUE TITLE
Images tag problem

### ISSUE THREAD

**Issue by aspats** [BVLC/caffe#2134]
Hi everyone!

I need a bit information how caffe work in such one situation:
For example I have 4 groups of image classes and I want to use caffe to classify it. For example I have for each classes 30 000 images. So each classes should looks like this (synset_words.txt):

0 dog
1 tree_or_cat
2 bird
3 house

The question is if caffe would understand that in 1 group are mixed two differents objects (tree and cat) and the accuracy will be quite the same when I saparate 1 group into two groups?. Or it will be a noise to bind in one group two different things? 

If it is a noise, I have another question. I have image list where some tags looks like in my example, but I could not know which from the photo are cat and which are tree, I have just tag tree_or_cat so how I could split it that I will get better classification accuracy of all 4 groups?  Maybe there some tricks what I could do with caffe?

**Comment by erictzeng** [comment]
This is just speculation, but I'd guess that most commonly used architectures will simply group trees and cats together under label 1. The problem of splitting trees and cats into different groups without labels seems like a much harder problem than simply learning them together as a single class.

If you have any further questions, please ask them on [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) -- this issues tracker is primarily for Caffe development discussion. Thanks!
