### ISSUE TITLE
how to make a classification in c++ caffe

### ISSUE THREAD

**Issue by mons91** [BVLC/caffe#2135]
Hi all!
I'm trying to make a classification code in c++ for caffe running on a Jetson TK1, bases on the pretrained Alexnet. I tries following this code https://gist.github.com/onauparc/dd80907401b26b602885 that I corrected to run on the new version of caffe, however I don't get a significant improvement art the python tutorial in the notebook sections, do you have any suggestion about how to build this code to achieve this improvement or there is a better way to do classification in c++ that i'm missing? Thank you all!!

**Comment by erictzeng** [comment]
When you say "significant improvement art the python tutorial," do you mean in terms of runtime? The Python interface is just a wrapper over the C++ core, so you're not really going to see much of a performance increase by switching to C++.

Yangqing also made a few comments about Jetson TK1s the other day that you may find useful: https://github.com/BVLC/caffe/issues/2022#issuecomment-79267882

If you have any further questions, please ask them on [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) -- this issues tracker is primarily for Caffe development discussion. Thanks!
