### ISSUE TITLE
Error with protobuf while compiling caffe

### ISSUE THREAD

**Issue by mgarbade** [BVLC/caffe#2137]
Apparantly my caffe compilation breaks when it tries to use the protobuf libraries. 
I'm using Ubuntu 12.04 64bit.
I already found the same issue and the person suggested to install protobuf 2.5.0, but unfortunately I can only find versions >= 2.6 on github.
currently I'm using 
libprotoc 3.0.0
Here is the part where my compliation crashes:

CXX/LD -o .build_release/tools/device_query.bin
CXX/LD -o .build_release/examples/mnist/convert_mnist_data.bin
CXX/LD -o .build_release/examples/cifar10/convert_cifar_data.bin
CXX/LD -o .build_release/examples/siamese/convert_mnist_siamese_data.bin
.build_release/lib/libcaffe.so: undefined reference to `google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(int, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, google::protobuf::io::CodedOutputStream*)'
.build_release/lib/libcaffe.so: undefined reference to `boost::thread::start_thread_noexcept()'
.build_release/lib/libcaffe.so: undefined reference to `google::protobuf::io::CodedOutputStream::WriteStringWithSizeToArray(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned char*)'
.build_release/lib/libcaffe.so: undefined reference to `google::protobuf::io::CodedInputStream::DecrementRecursionDepthAndPopLimit(int)'
.build_release/lib/libcaffe.so: undefined reference to `google::protobuf::io::CodedInputStream::~CodedInputStream()'
.build_release/lib/libcaffe.so: undefined reference to `google::protobuf::Arena::AddListNode(void*, void (*)(void*))'
.build_release/lib/libcaffe.so: undefined reference to `google::protobuf::io::CodedInputStream::IncrementRecursionDepthAndPushLimit(int)'
.build_release/lib/libcaffe.so: undefined reference to `google::protobuf::Arena::AllocateAligned(unsigned long)'
.build_release/lib/libcaffe.so: undefined reference to `google::protobuf::internal::InitEmptyString()'
.build_release/lib/libcaffe.so: undefined reference to `google::protobuf::io::CodedInputStream::default_recursion_limit_'

Any help would be welcome.
Best Regards

**Comment by n-zhang** [comment]
We welcome you to look at the extensive documentation, tutorials, and examples at http://caffe.berkeleyvision.org/ 
However, please ask usage questions on [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) -- this issues tracker is primarily for Caffe development discussion. Thanks!
