### ISSUE TITLE
how  to  create  a  new  imagenet.bet.pickle   file  my  own

### ISSUE THREAD

**Issue by wzq12138** [BVLC/caffe#2138]
I  have  trained  a  model  myself,I  need  to  create  the  imagenet.bet.pickle  my own,I  did  not  find  the way.

**Comment by erictzeng** [comment]
If I recall correctly, the imagenet.bet.pickle file contains the graph structure of ImageNet, so it's unclear to me what exactly you mean by "creating one." Do you have your own graph structure that you want to use?

If you use the pickle module, you can inspect the structure of the file and see if you can't create your own version. You can also look at the "Hedging Your Bets" paper for details about the structure.

If you have any further questions, please ask them on [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) -- this issues tracker is primarily for Caffe development discussion. Thanks!
