### ISSUE TITLE
Is there a regression framework for Caffe?

### ISSUE THREAD

**Issue by StevenLOL** [BVLC/caffe#2139]
Hi, I saw many closed issues on regression [here](https://github.com/BVLC/caffe/issues?q=is%3Aissue+is%3Aopen+regression), but which only end up to [Multivariate regression](https://github.com/BVLC/caffe/issues/881).  Is there a regression framework that can use a image as regression target? 

Something like [A General Framework for Whole Image Regression](http://arxiv.org/pdf/1412.6885.pdf)

**Comment by WanzhengZhu** [comment]
I have the same question, I also would like to know whether caffe can do regression problems.

**Comment by erictzeng** [comment]
Just from a short skim through that paper, it doesn't look there's anything in their architecture that you can't do directly using the layers that Caffe provides out of the box. Most of the provided Caffe examples deal with classification, but if you hook up the right architecture with the right loss at the top you should be able to do 2D regression too.

If you need more details, you can always try asking on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) mailing list. However, we'd like to keep the issues tracker primarily for development discussion. Thanks!

**Comment by StevenLOL** [comment]
"Please join the caffe-users group or gitter chat to ask questions and talk about methods and models. Framework development discussions and thorough bug reports are collected on Issues."


According the readme, this post fit 100% in framework development discussions, so kindly reopen this issue.
