### ISSUE TITLE
How to output the testing label?

### ISSUE THREAD

**Issue by WanzhengZhu** [BVLC/caffe#2140]
I am doing a classification problems using Caffe. But what I can see is only the training and testing accuracy, How do I see the output label for each sample so that I would know where goes wrong? 

By the way, how do I see the inner kernel weight/feature?

**Comment by erictzeng** [comment]
Both of the things you'd like to do are probably most easily done via the Python interface: http://nbviewer.ipython.org/github/BVLC/caffe/blob/master/examples/filter_visualization.ipynb

In general, most of the basic Caffe use cases have examples on our website, so it's always a good idea to check there first: http://caffe.berkeleyvision.org

If you have any further questions, please ask them on [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) -- this issues tracker is primarily for Caffe development discussion. Thanks!

**Comment by ZhangXinNan** [comment]
http://nbviewer.ipython.org/github/BVLC/caffe/blob/master/examples/filter_visualization.ipynb

**Comment by shelhamer** [comment]
The link is now http://nbviewer.ipython.org/github/BVLC/caffe/blob/master/examples/00-classification.ipynb -- refer to the list of examples on the Caffe homepage.
