### ISSUE TITLE
Real time training in caffe

### ISSUE THREAD

**Issue by getsiddd** [BVLC/caffe#2142]
Does caffe support real time training on non-image application, If anyone has done it on non-image or image application, I request them to share there code...

**Comment by erictzeng** [comment]
If by "real-time training" you mean streaming data, this should be doable either by using a MemoryDataLayer or by writing a PythonLayer to provide the data. Unfortunately, we don't have much documentation on this point, but hopefully that's enough of a lead to get you started.

If you have any further questions, please ask them on [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) -- this issues tracker is primarily for Caffe development discussion. Thanks!
