### ISSUE TITLE
Range of labels is not checked before they are used

### ISSUE THREAD

**Issue by jukkaho** [BVLC/caffe#2143]
Caffe does not check if the output layer's size is enough to assigned label for the data. This can cause crashes with CPU implementation when an invalid label is processed. With GPU implementation, only loss becomes nonsensical (negative values, NaN etc.) as invalid memory areas are referenced and it might be difficult to track this problem down.

It would increase the usability of the software by catching this error as early as possible and verifying that the label is within valid range at appropriate places.

**Comment by longjon** [comment]
Loss layers should perform label bounds checking in `DEBUG` mode. Softmax loss certainly does; if there are other cases where such checks are missing (do you know of specific ones?), they should be added.

**Comment by longjon** [comment]
Closing as labels are in fact checked in `DEBUG` mode; if you find a specific case where that is not true, you're welcome to open a new issue or PR.
