### ISSUE TITLE
make pycaffe: undefined symbols boost::python

### ISSUE THREAD

**Issue by waelHamdan** [BVLC/caffe#2146]
I am using Centos 6.6 which has python version 2.6

I have installed python 2.7 and now I have the two version.

when I try: make pycaffe
I got errors in

/usr/local/include/boost/python

cannot find many classes
and at the end:

/usr/local/include/boost/python/object_core.hpp:334: error: ‘object_base_initial                                                                                        izer’ was not declared in this scope
make: *** [python/caffe/_caffe.so] Error 1

I understood that I have to compile boost with python 2.7, but I didn't figure out how to do it

any help??

**Comment by waelHamdan** [comment]
fFurther details:

the error messages starts with this

CXX/LD -o python/caffe/_caffe.so python/caffe/_caffe.cpp
python/caffe/_caffe.cpp:1:52: error: Python.h: No such file or directory

**Comment by erictzeng** [comment]
Please ask usage/installation questions on [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) -- this issues tracker is primarily for Caffe development discussion. Thanks!

**Comment by aaronshan** [comment]
@waelHamdan have you resolved this problem? I get the error too.
