### ISSUE TITLE
The problem of fine tuning.

### ISSUE THREAD

**Issue by gjy3035** [BVLC/caffe#2153]
I want to fine tune the imagenet2012 network on my own dataset. I wrote a shell 

GLOG_logtostderr=1 $TOOLS/finetune_net.bin finetune $EXAMPLE/solver.prototxt $EXAMPLE/ilsvrc_2012_train_iter_310k

However, it said that "Deprecated. Use caffe train --solver=... [--weights=...] instead......."

I don't know why, and it is possible that other stage is not correct in the finetuning. 
How to finetune imagenet2012 on the other dataset? Thank you!

**Comment by bhack** [comment]
Please use mailing list or gitter to get support. Tickets are for bug or development.

**Comment by liqing-ustc** [comment]
the "finutune.cpp" process is integrated into the "caffe.cpp", so you can replace finetune with "caffe train --solver=[...] --weights=[ImageNet model file] "

**Comment by gjy3035** [comment]
@liqing-ustc Thanks! 
Ana I also find out something to explain it.

caffe.bin: command line brew
usage: caffe <command> <args>

commands:
  train           train or finetune a model
  test            score a model
  device_query    show GPU diagnostic information
  time            benchmark model execution time

  Flags from tools/caffe.cpp:
    -gpu (Run in GPU mode on given device ID.) type: int32 default: -1
    -iterations (The number of iterations to run.) type: int32 default: 50
    -model (The model definition protocol buffer text file..) type: string
      default: ""
    -snapshot (Optional; the snapshot solver state to resume training.)
      type: string default: ""
    -solver (The solver definition protocol buffer text file.) type: string
      default: ""
    -weights (Optional; the pretrained weights to initialize finetuning. Cannot
      be set simultaneously with snapshot.) type: string default: ""

the command ‘train’ can not only train models but also finetune it. In addition, we need to add '-solver' and so on.

**Comment by erictzeng** [comment]
Sounds like things are worked out.

If you have more questions in the future, please ask usage questions on [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) -- this issues tracker is exclusively for Caffe development discussion. Thanks!
