### ISSUE TITLE
The  time  about CNN  take

### ISSUE THREAD

**Issue by wzq12138** [BVLC/caffe#2155]
In  the  web  example,there  is  one  thing  about  CNN took {{ result[3] }} seconds,what  is  the  result[3],does  it  mean  the  time  of  CNN  run  the  image classificition  code ,I  have  tried  it  on  my computer(Geforce  720M),and it  is  about  0.31seconds  per  image,and  in  the  demo:http://demo.caffe.berkeleyvision.org/   ,it  is  about  0.077seconds,  and  on  the  jeston  TK1,it  is  about  0.5  seconds,all  of  them  is  run  in  GPU  mode,why  the  TK1  is  so  slowly,even  slowly  than  my  computer  whose  CUDA/GPU  cability  is  2.1.
at  first ,I  thought  the  caffe  web  said  That’s 1 ms/image for inference and 4 ms/image for learning. We believe that Caffe is the fastest convnet implementation available...
so is  the  time   related  to  the  hardware?and  what  is  the  hardware  on  the  demo .              http://demo.caffe.berkeleyvision.org/

 Platform                     CUDA/GPU  cability              time
web-demo                              no  idea                        0.077seconds
my  conputer               geforce720m  2.1                  0.31   seconds
Jeston  TK1                  3.1                                       0.5  seconds
my  question  is:1    what  does    the  time  acctually      mean
                         2      why  the  web-demo  so  fast  than  the  others,what  is  the  server  of  the  web-demo
                        3       what  does  the  time  relative  to,does  it  have  relation  to  the  CUDA/GPU  cability,if   it   does,,why  is  TK1  still  slower  than  my  computer?

**Comment by erictzeng** [comment]
Please ask usage questions on [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) -- this issues tracker is exclusively for Caffe development discussion. Thanks!

**Comment by wzq12138** [comment]
@erictzeng    Do  not  let  me   ask    questions  on  the  caffe-users............I   am  in  China ,,I   have  no  server  on  the  google.holy  shit

**Comment by bhack** [comment]
@erictzeng Use the caffe gitter channel.
