### ISSUE TITLE
Replace ":=" with "?=" in Makefile.config.example to enable user specification at compilation time

### ISSUE THREAD

**Issue by weijianwen** [BVLC/caffe#2156]
I propose to replace the ```:=``` operator with ```?=``` in ```Makefile.config.example```. This will enable user specification of customized compiler, BLAS et al. at compilation time without modifying ```Makefile.config```.

For exmaple, say
```
CPU_ONLY ?= 1
BALS ?= atlas
BALS ?= atlas
CUDA_DIR ?= /usr/local/cuda
```

To build a CPU-only version with GCC and OpenBLAS:

```
CPU_ONLY=1 BLAS=open make all
```

To build a GPU version with GCC and ATLAS as backend:

```
CPU_ONLY=0 BLAS=atlas CUDA_DIR=${CUDA_DIR} make all
```

**Comment by longjon** [comment]
We could do this, the downside is that it opens the possibility of namespace conflicts with the environment. If there are specific cases where this is obviously useful (like the existing `Q=` option), I'd entertain the possibility, but for changes that require a clean build anyway, I'm not sure the danger is worth the convenience of not popping open `Makefile.config`.

**Comment by longjon** [comment]
Closing as this does not seem to have gained popular support; thanks for the suggestion.
