### ISSUE TITLE
Build caffe with Intel Compiler icc/icpc

### ISSUE THREAD

**Issue by weijianwen** [BVLC/caffe#2157]
I used to build caffe with Intel Compiler (icc for short) v14 and CUDA v6.5, which works quite well. However, recent master branch seems to remove support for icc. Builidng with compilers other than gcc and clang will fall into the error "Cannot static link with the $(CXX) compiler".

Then I try to build the master with icc 14 and cuda 7.0, setting the flag the same as gcc
```
STATIC_LINK_COMMAND := -Wl,--whole-archive $(STATIC_NAME) -Wl,--no-whole-archive
```

**Buiding** caffe and test cases pass, with some warnings though. Test cases have **NOT** run yet.

```
CPU_ONLY=1 BLAS=mkl CC=icc CXX=icpc CUSTOM_CXX=icpc make all
CPU_ONLY=1 BLAS=mkl CC=icc CXX=icpc CUSTOM_CXX=icpc make test 
```

I have Intel compierl version 14 & 15, along with necessary hardware at hand (K20, K40). I wonder how I can help to re-add icc into the list of supported compilers.

Best,

**Comment by longjon** [comment]
Static linking is tricky due to the use of a global registry. You do need to build the static library to use Caffe (just remove it from the list of targets). If the dynamic build works okay with `icc`, that would be great to know.

**Comment by longjon** [comment]
Closing as there does not seem to be an issue currently here; it seems that `icc` actually works, although the static linking will not.
