### ISSUE TITLE
oversampling data for when creating leveldb

### ISSUE THREAD

**Issue by rosenfeldamir** [BVLC/caffe#2161]
Hi,
I have a non-balanced dataset. To correct this, I am creating a leveldb file using input text files repeating each training example a number of times so that overall each class appears with the same probability. 
When I create the leveldb, the reported number of images is same as the original. Does this mean caffe ignores duplicate images, or it is being efficient and the leveldb and keeps track of those examples which were specified several times? 
Thanks,
-Amir

**Comment by thatguymike** [comment]
That isn't going to do what you want.  The DB will deduplicate if the keys and value are the same, which they would be in your example.  Moreover, replicating an example will lead to overfitting.  Better would be to try direct augmentation by manipulating the image yourself ahead of time.  e.g. warp, distortion, noise, etc.  Take a look at the Baidu paper: http://arxiv.org/abs/1501.02876

**Comment by erictzeng** [comment]
Please ask usage questions on [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) -- this issues tracker is exclusively for Caffe development discussion. Thanks!
