### ISSUE TITLE
OpenGL ES 2.0

### ISSUE THREAD

**Issue by snapo** [BVLC/caffe#2162]
Hi ,
i did try to find more information on what is supported by caffe (what cpus, what gpus) ... i have a ubuntu arm running with opengl es and a mali450 gpu . i did want to make a speed test but im not able to get caffe finding a gpu....
Anyone has a recommendation?

Best regards

**Comment by thatguymike** [comment]
Caffe's GPU backend uses CUDA, which is only supported on Nvidia GPUs.  I fyou want to run on your embedded ARM+Mali, compile Caffe in CPU mode and use OpenBLAS for multiCPU scaling.

**Comment by erictzeng** [comment]
Please ask usage questions on [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) -- this issues tracker is exclusively for Caffe development discussion. Thanks!
