### ISSUE TITLE
DataLayer accept db path from external parameter

### ISSUE THREAD

**Issue by immars** [BVLC/caffe#2170]
Hi,
currently net's `prototxt` defines the net structure, including leveldb/lmdb path of DataLayer.

It's fine when I train the net locally, but not very convenient for building a data-parallelism learning cluster, in which there could be data partitioning and job assignment before caffe start to work.

If DataLayer can accept parameters from external, say cmdline, things would be much easier. 

Thanks!

**Comment by npit** [comment]
What I do is to process the .prototxt, modifying the source: field in the input data layer.

**Comment by immars** [comment]
Thanks for mentioning. It's true that workaround is possible indeed. So I guess this is low priority...

**Comment by longjon** [comment]
Closing as this does not seem to be an issue with Caffe; `prototxt` is just a serialization format and there are many ways to generate/process it. In general, please ask usage questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) list. Thanks!
