### ISSUE TITLE
Euclidean loss, should I multiply 2 to get MSE?

### ISSUE THREAD

**Issue by paradiselostgit** [BVLC/caffe#2176]
I'm using Caffe to do regression, by set the loss type to Euclidean loss.
I noticed in Euclidean loss layer, the summed square error is divided by 2*N.
While in a formal MSE equation, the summed square error is divided by N.

So the output by Euclidean loss should be multiplied 2 to get MSE, or I misunderstand something?

**Comment by pathak22** [comment]
please ask usage questions on [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) -- this issues tracker is primarily for Caffe development discussion. Thanks!
