### ISSUE TITLE
The  meaning  of  accuracy  and  loss

### ISSUE THREAD

**Issue by wzq12138** [BVLC/caffe#2179]
I  am  training  the  imagenet,and  what  does  the  accuracy  and  loss mean.my  accuracy  is  aboout  0.4,and  loss  is  about  1.0  to  3.0.does  it  normal.
and  as  I  think,the  accuracy  should  be  increaseing  as the  Iteration  increasing,will  it  be  0.99?and  I  really do  not  know  what  does  loss mean  ,can  you tell me

**Comment by buriy** [comment]
Loss means this: http://caffe.berkeleyvision.org/tutorial/loss.html

**Comment by pathak22** [comment]
We welcome you to look at the extensive documentation, tutorials, and examples at http://caffe.berkeleyvision.org/ 
However, please ask usage questions on [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) -- this issues tracker is primarily for Caffe development discussion. Thanks!
