### ISSUE TITLE
Java web service for image classification

### ISSUE THREAD

**Issue by waelHamdan** [BVLC/caffe#2181]
I want to develop a simple web service using Java.

My question: Is it possible to call python files (in caffe python wrapper) directly from the java web service? so my web service can relay on python wraper

or I have to deal directly with Cpp code?

Thanks

**Comment by Lewuathe** [comment]
Although this topic does not seemed related to caffe, I think there are several ways to call python process from Java web server such as [Runtime](http://docs.oracle.com/javase/7/docs/api/java/lang/Runtime.html) or it will be better to run python WAF if you want to run python wrapper of caffe such as [Django](https://www.djangoproject.com/ ). Anyway I think it is the best way to post on [Google Group](https://groups.google.com/forum/#!forum/caffe-users).

**Comment by bhack** [comment]
See https://github.com/BVLC/caffe/issues/1641

**Comment by waelHamdan** [comment]
Thanks.
@bhack I have already seen it but I am still confused about the choice, as I need only to implement image classification using java web service. 

So you advise me to look at the java preset?

**Comment by pathak22** [comment]
please ask usage questions on [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) -- this issues tracker is primarily for Caffe development discussion. Thanks!

**Comment by futurely** [comment]
https://github.com/BVLC/caffe/issues/1823#issuecomment-93659994
