### ISSUE TITLE
BUG? runtest error for current version and RC2 

### ISSUE THREAD

**Issue by guanggz** [BVLC/caffe#2182]
It prompts 16 errors when I ran  ``` make runtest ``` as below 
```
...
[----------] Global test environment tear-down
[==========] 1122 tests from 198 test cases ran. (173000 ms total)
[  PASSED  ] 1106 tests.

[  FAILED  ] 16 tests, listed below:
[  FAILED  ] MemoryDataLayerTest/0.AddMatVectorDefaultTransform, where TypeParam = caffe::FloatCPU
[  FAILED  ] MemoryDataLayerTest/0.TestSetBatchSize, where TypeParam = caffe::FloatCPU
[  FAILED  ] MemoryDataLayerTest/1.AddMatVectorDefaultTransform, where TypeParam = caffe::DoubleCPU
[  FAILED  ] MemoryDataLayerTest/1.TestSetBatchSize, where TypeParam = caffe::DoubleCPU
[  FAILED  ] MemoryDataLayerTest/2.AddMatVectorDefaultTransform, where TypeParam = caffe::FloatGPU
[  FAILED  ] MemoryDataLayerTest/2.TestSetBatchSize, where TypeParam = caffe::FloatGPU
[  FAILED  ] MemoryDataLayerTest/3.TestSetBatchSize, where TypeParam = caffe::DoubleGPU
[  FAILED  ] MemoryDataLayerTest/3.AddMatVectorDefaultTransform, where TypeParam = caffe::DoubleGPU
[  FAILED  ] IOTest.TestDecodeDatumToCVMatContentNative
[  FAILED  ] IOTest.TestDecodeDatumToCVMatNativeGray
[  FAILED  ] IOTest.TestDecodeDatumToCVMat
[  FAILED  ] IOTest.TestDecodeDatumToCVMatNative
[  FAILED  ] IOTest.TestDecodeDatum
[  FAILED  ] IOTest.TestDecodeDatumNativeGray
[  FAILED  ] IOTest.TestDecodeDatumNative
[  FAILED  ] IOTest.TestDecodeDatumToCVMatContent
```
It happens with ver. RC-2 and the latest package, I presume this was caused by bugs?

**Comment by zym1010** [comment]
Mine worked fine, although with another problem... (#2186)

**Comment by guanggz** [comment]
I found it might be related to opencv. Can you share the specific method of opencv installation? Thsnks.

**Comment by zym1010** [comment]
@guanggz `apt-get` on ubuntu 14.04 server.

**Comment by pathak22** [comment]
please ask usage questions on [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) -- this issues tracker is primarily for Caffe development discussion. Thanks!

**Comment by jia55060503** [comment]
I meet the same problem. Have u solved it at last?

**Comment by nian-liu** [comment]
Hi @guanggz , I met some same weird problems with you of the system shutting down while running caffe, as you described in  https://forums.geforce.com/default/topic/831691/system-shutdown-with-titan-x-caffe-cudnn/, could you share me some your experience? My Gmail address is liunian228@gmail.com, thank you!

**Comment by guanggz** [comment]
On 1/15/2016 5:40 PM, nian-liu wrote:
>
> Hi @guanggz <https://github.com/guanggz> , I met some same weird 
> problems with you of the system shutting down while running caffe, as 
> you described in 
> https://forums.geforce.com/default/topic/831691/system-shutdown-with-titan-x-caffe-cudnn/, 
> could you share me some your experience? My Gmail address is 
> liunian228@gmail.com <mailto:liunian228@gmail.com>, thank you!
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/BVLC/caffe/issues/2182#issuecomment-172009896>.
>
Hi, that's a bit hard to say. What's in your rig?

--

**Comment by nian-liu** [comment]
Hi @guanggz , it may be inappropriate to discuss my problem in this post. I am wondering whether I can know your mailbox so that we can discuss this by email?

**Comment by nian-liu** [comment]
Hi @guanggz, if you have time, plz kindly have a look at my messages above, I really need some help.
