### ISSUE TITLE
Matlab wrapper install

### ISSUE THREAD

**Issue by mahdisr85** [BVLC/caffe#2185]
I was making so much progress! Caffe is installed, Python wrapper is installed, but I'm having trouble with the MATLAB wrapper. I don't have CUDA supported graphic card so I'm skipping that with CPU_ONLY := 1 in Makefile.config

I have Mac Os 10.10.2 and MATALB R2013b. 

Any thoughts? 

Here is the error I get: 
>> make matcaffe
/bin/sh: /usr/local/cuda/bin/nvcc: No such file or directory
(standard_in) 1: parse error
MEX matlab/caffe/matcaffe.cpp
clang: warning: no such sysroot directory: '-mmacosx-version-min=10.8'
In file included from matlab/caffe/matcaffe.cpp:6:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/sstream:174:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ostream:131:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ios:215:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iosfwd:90:10: fatal error: 
      'wchar.h' file not found
#include <wchar.h>  // for mbstate_t
         ^
1 error generated.

    mex: compile of ' "matlab/caffe/matcaffe.cpp"' failed.

make: *** [matlab/caffe/caffe.mexmaci64] Error 255

**Comment by pathak22** [comment]
please ask usage questions on [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) -- this issues tracker is primarily for Caffe development discussion. Thanks!
