### ISSUE TITLE
Code for training on single image...

### ISSUE THREAD

**Issue by getsiddd** [BVLC/caffe#2187]
I had written this code training a single image on caffe, but it is crashing... someone please check...

caffe::Caffe::set_phase(caffe::Caffe::TRAIN);
caffe::Caffe::set_mode(caffe::Caffe::CPU);

// read trained net
caffe::Net<Dtype> * net = new caffe::Net<Dtype>("lenet_test.prototxt");
net->CopyTrainedLayersFrom("lenet_iter_50");

// load and resize image to 256^2
const int width = 256;
const int height = 256;
cv::Mat cv_img;
cv::Mat cv_img_origin = cv::imread("valpics\Banane.jpg", CV_LOAD_IMAGE_COLOR);
cv::resize(cv_img_origin, cv_img, cv::Size(height, width));
if (!cv_img.data) {
    printf("Could not open or find input file.\n");
    return 1;
}

// convert the image to a caffe::Blob
caffe::Blob<Dtype> * blob = new caffe::Blob<Dtype>(1, 3, width, height);
for (int c = 0; c < 3; ++c) {
    for (int h = 0; h < cv_img.rows; ++h) {
        for (int w = 0; w < cv_img.cols; ++w) {
            blob->mutable_cpu_data()[blob->offset(0, c, h, w)] = cv_img.at<cv::Vec3b>(h, w)[c];
        }
    }
}

// create input and output vectors for the Forward call
vector<caffe::Blob<Dtype>*> bottom_vecs;
vector<caffe::Blob<Dtype>*> top_vecs;
bottom_vecs.push_back(blob);

Dtype loss;
top_vecs = net->Forward(bottom_vecs, &loss);

// calculate mean of the resulting blob, which is the classification result?
caffe::Blob<Dtype>* topvec = top_vecs[0];
float mean = 0;
for (int c = 0; c < topvec->channels(); ++c) {
    for (int h = 0; h < topvec->height(); ++h) {
        for (int w = 0; w < topvec->width(); ++w) {
            mean += topvec->data_at(0, c, h, w);
        }
    }
}
mean /= (topvec->channels() * topvec->height() * topvec->width());

printf("mean=%f\n", mean);

delete blob;
delete net;

**Comment by pathak22** [comment]
please ask usage questions on [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) -- this issues tracker is primarily for Caffe development discussion. Thanks!
