### ISSUE TITLE
AccuracyLayer should support multiple (e.g., spatial) labels

### ISSUE THREAD

**Issue by peter254** [BVLC/caffe#2188]
In line 33 in file accuracy_layer.cpp a +1throws an error when using multiple labels for each input and removing it solves the issue

**Comment by pathak22** [comment]
please ask usage questions on [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) -- this issues tracker is primarily for Caffe development discussion. Thanks!

**Comment by peter254** [comment]
To me this actually seems to be an issue as it does not seem to work when using an array as label. I am not a caffe developer, so please correct me if I am wrong

**Comment by shelhamer** [comment]
Right -- I re-opened it to note that `AccuracyLayer` only works with single labels (at least for now).
