### ISSUE TITLE
How to employ the Caffe trained model in a real/industrial application?

### ISSUE THREAD

**Issue by dingcius** [BVLC/caffe#2189]
I have trained a CNN model with Caffe, and it works fine when I use it to extract feature from .lmdb or .hf5 files (within the Caffe package). But now I want to employ the model in one serious industrial application, i.e., I want to do some detection work for a surveillance camera. 

Ideally, I hope there is a function that extracts feature using the provided Caffe model and the image data in the memory (captured by the camera in real-time).

I spend a lot of time searching on the Internet, but there is no solution. Can anybody help me? Thanks in advance.

**Comment by pathak22** [comment]
please ask usage questions on [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) -- this issues tracker is primarily for Caffe development discussion. Thanks!
