### ISSUE TITLE
python deploy prototxt problem

### ISSUE THREAD

**Issue by shuangao** [BVLC/caffe#2190]
Hi, all:

I am trying to use the python to build a model with existing prototxt and caffemodel file. However, I found that I could not successfully build one even with the deploy file and model offered on github unless I delete all the weigth_filler and bias_filler content. 
I run my code on python command and it shows "Segmentation fault (core dumped)"
Can anyone figure out what's wrong?

**Comment by pathak22** [comment]
please ask usage questions on [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) -- this issues tracker is primarily for Caffe development discussion. Thanks!
