### ISSUE TITLE
Errors occured when compiling the newest caffe

### ISSUE THREAD

**Issue by RobotiAi** [BVLC/caffe#2198]
Hi All,
When I compiled the newest caffe, I encountered the following errors:
.build_release/tools/convert_imageset.o: In function `main':
convert_imageset.cpp:(.text.startup+0x600): undefined reference to `caffe::db::GetDB(std::string const&)'
convert_imageset.cpp:(.text.startup+0x778): undefined reference to `caffe::ReadImageToDatum(std::string const&, int, int, int, bool, std::string const&, caffe::Datum*)'
collect2: error: ld returned 1 exit status
...
I think it's a link problem. Has anyone ever had the same problem? Could you please provide a solution? Thanks!

**Comment by pathak22** [comment]
please ask usage questions on [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) -- this issues tracker is primarily for Caffe development discussion. Thanks!
