### ISSUE TITLE
python wrapper fail

### ISSUE THREAD

**Issue by shuangao** [BVLC/caffe#2200]
Hi, all 
I want to use the classify.py to test the model and I found that it could not work. The dimension of the cropped image is not consistent with the mean file.
Here is the error:
````
ValueError: operands could not be broadcast together with shapes (3,227,227) (3,256,256) (3,227,227)
````
I used to try python wrapper according to  [tutorial](http://nbviewer.ipython.org/github/udibr/caffe/blob/master/examples/classification.ipynb). But it doesn't work now.
The current one in examples is not the latest version. The python wrapper has [changed the setting strategy](https://github.com/BVLC/caffe/pull/1728). Can anyone provide a latest python tutorial?

**Comment by lukeyeager** [comment]
Have a look at #1928.

**Comment by shuangao** [comment]
Got it! Thanks.
