### ISSUE TITLE
The  dataset  about  CIFAR-10

### ISSUE THREAD

**Issue by wzq12138** [BVLC/caffe#2202]
It  could  be  download  the  dataset  by  ./get_cifar10.sh.and  the  dataset  is  done  by  the  athur,how  can  I  do  it  my  self,I   mean  I  have  my  images,and  I  want  to  train  it  myself

**Comment by wzq12138** [comment]
as  the  imagenet  example  ,it  could  be  down  by  test.txt  and  train.txt.

**Comment by pathak22** [comment]
please ask usage questions on [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) -- this issues tracker is primarily for Caffe development discussion. Thanks!
