### ISSUE TITLE
when I use matlab to call my own deploy.prototxt,it has an error that says blob.cpp  Shape Equals(proto) shape mismatch (reshape not set)

### ISSUE THREAD

**Issue by henurgwpf** [BVLC/caffe#2205]
when I use matlab to call my own deploy.prototxt,it has an error that says blob.cpp  Shape Equals(proto) shape mismatch (reshape not set)

input: "data"
input_dim: 10
input_dim: 1
input_dim: 39
input_dim: 31
layer {
  name: "conv1"
  type: "Convolution"
  bottom: "data"
  top: "conv1"
  convolution_param {
    num_output: 20
    kernel_size: 4
    stride: 1
  }
}

I run the matcaffe_demo ,there is no errors. But I change the imagenet_deploy to my own deploy.prototxt, there has an error that says  blob.cpp  Shape Equals(proto) shape mismatch (reshape not set)

**Comment by henurgwpf** [comment]
anyone knows how to solve the problem???????????/

**Comment by henurgwpf** [comment]
Please help! Thank you!

**Comment by henurgwpf** [comment]
@pluskid 
@sergeyk 
@rodrigob 
@geenux

**Comment by npit** [comment]
Are you trying to load an existing .caffemodel using that .deploy?

**Comment by pathak22** [comment]
please ask usage questions on [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) -- this issues tracker is primarily for Caffe development discussion. Thanks!

**Comment by RafaRuiz** [comment]
If anyone did a workaround??... people here try to redirect everybody (since it's a development forum) to https://groups.google.com/forum/#!forum/caffe-users but I finally can't find the answer anywhere.
