### ISSUE TITLE
Memory leak? in R-CNN python scripts

### ISSUE THREAD

**Issue by tishibas** [BVLC/caffe#2207]
I'm trying R-CNN detection in my laptop with 4GB RAM.
When using python/detect.py, the process is stopped forcedly in crop function called detect_windows function of python/caffe/detector.py and outputs only "killed".
It may happens memory leak because when inputting small size file has 1k rows, it has not happened. But he scripts is always stopped with 6k+ rows inputs file.

```
...
I0326 15:14:21.177304 16948 net.cpp:213] Network initialization done.
I0326 15:14:21.177311 16948 net.cpp:214] Memory required for data: 62425920
E0326 15:14:21.808954 16948 upgrade_proto.cpp:618] Attempting to upgrade input file specified using deprecated V1LayerParameter: ../../caffe/models/bvlc_reference_rcnn_ilsvrc13/bvlc_reference_rcnn_ilsvrc13.caffemodel
I0326 15:14:22.105556 16948 upgrade_proto.cpp:626] Successfully upgraded file specified using deprecated V1LayerParameter
Loading input...
Killed
```

**Comment by pathak22** [comment]
please ask usage questions on [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) -- this issues tracker is primarily for Caffe development discussion. Thanks!
