### ISSUE TITLE
Caffe Installation Issue on Ubuntu 14.04.2

### ISSUE THREAD

**Issue by ericqh** [BVLC/caffe#2210]
I successfully installed caffe on my dual-boot laptop (GTX 860M, Windows 7 + Ubuntu 14.04.2). All the tests were successfully passed. When I restarted, however, the ubuntu got stuck on the opening screen (the one with ubuntu logo and FIVE dots). Don't know what to do with it. Has anyone run into the same issue before? I reckon something is wrong with graphic card driver.  
![fullsizerender](https://cloud.githubusercontent.com/assets/5845619/6853652/a6ce638c-d3a9-11e4-9301-08370c0e805c.jpg)

**Comment by talda** [comment]
This problem is not related to caffe.
The problem is that the nvidia driver that is installed from the ubuntu software center does not support your card,
Uninstall any nvidia-* package (sudo apt-get purge nvidia-*) and install the last driver version from the nvidia website.

**Comment by ericqh** [comment]
Thanks a lot, problem solved.

**Comment by anuraggargnitk** [comment]
How did you solve this issue? I am also facing the same issue.

**Comment by ericqh** [comment]
This tutorial 
<https://github.com/tiangolo/caffe/blob/88b1db8bd74dbfbb0c63d2996fb19761e20ccedb/docs/install_apt2.md>can 
help. Install latest NVIDIA graphic card driver first, then install CUDA 
7.0. This works for me. If you cannot log in to the desktop, just reboot 
and get into BIOS. Then switch to integrated graphic card mode. Then 
uninstall previous nvidia driver using sudo apt-get purge nvidia-*. 
Download the latest from nvidia website and install the whole package 
again.

Hope this will work for you too!

**Comment by anuraggargnitk** [comment]
Thanks for getting back!

I have one more query. Does this work for Graphic Cards other than Nvidia? My graphic card belongs to Mobile Intel (4) Series Express Chipset family.

**Comment by ericqh** [comment]
I'm not sure. Caffe can work only using CPU. But GPU does great 
acceleration, and Nvidia provides best supports for deep learning. You 
can always search online for some useful information.
