### ISSUE TITLE
How  to  create   the  leveldb  file

### ISSUE THREAD

**Issue by wzq12138** [BVLC/caffe#2212]
I  download  a   file  named  leveldb ,and   I  have  seen  the  file  contains  many  files  lika  00012.sst.
and  as  I  know  ,I  just  have  seen  the  file  lmdb,and  it  is  data.mdb  and  lock.mdb  .so   how  can  I  create  the  file  like  00012.sst  with  my  image

**Comment by pathak22** [comment]
look at convert_imageset tool.

However, please ask usage questions on [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) -- this issues tracker is primarily for Caffe development discussion. Thanks!
