### ISSUE TITLE
How  can  I  get  the  figures  like  this.

### ISSUE THREAD

**Issue by wzq12138** [BVLC/caffe#2214]
I  have  seen  it  here  https://github.com/BVLC/caffe/issues/430

![image](https://cloud.githubusercontent.com/assets/9315227/6863383/10f9a532-d48b-11e4-8edc-d823988e2e60.png)
![image](https://cloud.githubusercontent.com/assets/9315227/6863385/1e637aae-d48b-11e4-966a-8f9facb80f56.png)

**Comment by pathak22** [comment]
please ask this question on [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) -- this issues tracker is primarily for Caffe development discussion. Thanks!
