### ISSUE TITLE
I have a trouble on ImageNet example...

### ISSUE THREAD

**Issue by Hswoong** [BVLC/caffe#2220]
hi,

I had got the ILSVRC2012 images and Creating lmdb filed of train and validation data was well done.

But when i`m in training stage, console shows error which state 

F0328 16:03:12.503332  3028 syncedmem.cpp:51] Check failed: error == cudaSuccess (2 vs. 0)  out of memory

So i modified the batch size of train_val.prototxt to 12. I think it is quite small compare to original 256. 

Though training was done, another error about dimension mismatch(target blob width vs source blob width) occurred. 

1.  I just wondering how to calculate memory required whole training procedure?

2. With classification example, how can i set input dimension ( batch, channel, width, height) of deploy.prototxt?
 Are width, heights identical to crop_size of train_val.prototxt ?

**Comment by pathak22** [comment]
please ask usage questions on [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) -- this issues tracker is primarily for Caffe development discussion. Thanks!
