### ISSUE TITLE
Homebrew includes and library paths for OS X build

### ISSUE THREAD

**Issue by dwt** [BVLC/caffe#2221]
Hi there,

building caffe on Mac OS X Yosemite with the dependencies provided by home-brew I noticed that the build didn't pick up my build locations as they are non standard (i.e. I have homebrew installed in my home directory).

The problem was fixed by handing in the CXXFLAGS at three locations in the build script, so that they also apply when building the test tool and the python bindings.

```patch
diff --git a/Makefile b/Makefile
index cb39679..24173b6 100644
--- a/Makefile
+++ b/Makefile
@@ -431,7 +431,7 @@ py: $(PY$(PROJECT)_SO) $(PROTO_GEN_PY)
 $(PY$(PROJECT)_SO): $(PY$(PROJECT)_SRC) $(PY$(PROJECT)_HXX) | $(DYNAMIC_NAME)
 	@ echo CXX/LD -o $@ $<
 	$(Q)$(CXX) -shared -o $@ $(PY$(PROJECT)_SRC) \
-		-o $@ $(LINKFLAGS) -l$(PROJECT) $(PYTHON_LDFLAGS) \
+		-o $@ $(CXXFLAGS) $(LINKFLAGS) -l$(PROJECT) $(PYTHON_LDFLAGS) \
 		-Wl,-rpath,$(ORIGIN)/../../build/lib
 
 mat$(PROJECT): mat
@@ -520,7 +520,7 @@ $(TEST_ALL_BIN): $(TEST_MAIN_SRC) $(TEST_OBJS) $(GTEST_OBJ) \
 		| $(DYNAMIC_NAME) $(TEST_BIN_DIR)
 	@ echo CXX/LD -o $@ $<
 	$(Q)$(CXX) $(TEST_MAIN_SRC) $(TEST_OBJS) $(GTEST_OBJ) \
-		-o $@ $(LINKFLAGS) $(LDFLAGS) -l$(PROJECT) -Wl,-rpath,$(ORIGIN)/../lib
+		-o $@ $(CXXFLAGS) $(LINKFLAGS) $(LDFLAGS) -l$(PROJECT) -Wl,-rpath,$(ORIGIN)/../lib
 
 $(TEST_CU_BINS): $(TEST_BIN_DIR)/%.testbin: $(TEST_CU_BUILD_DIR)/%.o \
 	$(GTEST_OBJ) | $(DYNAMIC_NAME) $(TEST_BIN_DIR)
@@ -532,7 +532,7 @@ $(TEST_CXX_BINS): $(TEST_BIN_DIR)/%.testbin: $(TEST_CXX_BUILD_DIR)/%.o \
 	$(GTEST_OBJ) | $(DYNAMIC_NAME) $(TEST_BIN_DIR)
 	@ echo LD $<
 	$(Q)$(CXX) $(TEST_MAIN_SRC) $< $(GTEST_OBJ) \
-		-o $@ $(LINKFLAGS) $(LDFLAGS) -l$(PROJECT) -Wl,-rpath,$(ORIGIN)/../lib
+		-o $@ $(CXXFLAGS) $(LINKFLAGS) $(LDFLAGS) -l$(PROJECT) -Wl,-rpath,$(ORIGIN)/../lib
 
 # Target for extension-less symlinks to tool binaries with extension '*.bin'.
 $(TOOL_BUILD_DIR)/%: $(TOOL_BUILD_DIR)/%.bin | $(TOOL_BUILD_DIR)
```

Using this patch I was able to build caffe with this simple script:

```sh
#!/usr/bin/env sh

# Dependencies are all homebrew provided

# Most dependencies
BREW="$(brew --prefix)"
# openblas is keg only
OPENBLAS="$(brew --prefix openblas)"
NUMPY="$(brew --prefix numpy)"
# numpy headers are at a non standard location when built using homebrew
NUMPY_INCLUDE="$(dirname $(python -c 'import numpy.core; print(numpy.core.__file__)'))/include"

export CXXFLAGS="-I$BREW/include -I$OPENBLAS/include -I$NUMPY_INCLUDE" 
export LINKFLAGS="-L$BREW/lib -L$OPENBLAS/lib -L$NUMPY/lib" 


make
make pycaffe
make test
make runtest
```

Thus I think you might want to apply the patch to the makefile to make it more correct / resilient.

Have fun!

EDIT: updated build script and make file to also build the python integration.

**Comment by dwt** [comment]
If you want, I can also provide a shell script, something like build_mac.sh, that also pulls in all the dependencies for a CPU only build via homebrew.

**Comment by pathak22** [comment]
please ask usage questions on [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) -- this issues tracker is primarily for Caffe development discussion. Thanks!

**Comment by shelhamer** [comment]
@dwt you could add `$BREW/include` and `$BREW/lib` to the Makefile.config `INCLUDE_DIRS` and `LIBRARY_DIRS` no? This is a helpful hint that could be commented out by default as is done for Anaconda. Send a PR if you have a chance.

Thanks for posting your details and script.

**Comment by shelhamer** [comment]
Closing since there is a PR.
