### ISSUE TITLE
any tutorial for using caffe with language

### ISSUE THREAD

**Issue by talktothehawkaman** [BVLC/caffe#2223]
I have written the layers and defined the solver files and i also ran the training from command line. 
My question is, though may be silly, what is the way caffe is dealt with, i mean should i write the model and the solver and train through cammand line and then after getting the trained model how do i use it to test the images or it all has to be done in the code.

I am new  to this domain but i want to learn, please help me with the above question and also it would be best if anyone can give me a proper tutorial of writing codes with either C++ or python or C.  Please help

**Comment by pathak22** [comment]
please ask usage questions on [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) -- this issues tracker is primarily for Caffe development discussion. Thanks!
