### ISSUE TITLE
make pycaffe error

### ISSUE THREAD

**Issue by chenbinghui1** [BVLC/caffe#2226]
i have installed python2.7 followed the installtion and use the anaconda ,but when i type make pycaffe,some errors come up like this:

/usr/bin/ld: /usr/local/lib/libpython2.7.a(abstract.o): relocation R_X86_64_32S against `_Py_NotImplementedStruct' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libpython2.7.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
make: *** [python/caffe/_caffe.so] Error 1

did anyone meet with this problem?and how can i fit it.
thanks

**Comment by pathak22** [comment]
please ask usage questions on [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) -- this issues tracker is primarily for Caffe development discussion. Thanks!
