### ISSUE TITLE
Building Caffe with CUDA 7.0 SDK

### ISSUE THREAD

**Issue by Brainiarc7** [BVLC/caffe#2228]
Hello guys,

I'm currently on Arch Linux, and have installed the latest CUDA SDK (Version 7, as of today).
When I tried building the package today, it failed (done with makepkg via a local PKGBUILD), and on CUDA 6.5 it built without a hitch.

Here's the error log:

PROTOC src/caffe/proto/caffe.proto
CXX src/caffe/syncedmem.cpp
CXX src/caffe/layers/pooling_layer.cpp
CXX src/caffe/layers/tanh_layer.cpp
CXX src/caffe/layers/power_layer.cpp
CXX src/caffe/layers/data_layer.cpp
CXX src/caffe/layers/window_data_layer.cpp
CXX src/caffe/layers/argmax_layer.cpp
CXX src/caffe/layers/contrastive_loss_layer.cpp
CXX src/caffe/layers/base_conv_layer.cpp
CXX src/caffe/layers/accuracy_layer.cpp
CXX src/caffe/layers/softmax_layer.cpp
CXX src/caffe/layers/eltwise_layer.cpp
CXX src/caffe/layers/cudnn_tanh_layer.cpp
CXX src/caffe/layers/cudnn_sigmoid_layer.cpp
CXX src/caffe/layers/infogain_loss_layer.cpp
CXX src/caffe/layers/deconv_layer.cpp
CXX src/caffe/layers/cudnn_conv_layer.cpp
CXX src/caffe/layers/cudnn_relu_layer.cpp
CXX src/caffe/layers/loss_layer.cpp
CXX src/caffe/layers/relu_layer.cpp
CXX src/caffe/layers/threshold_layer.cpp
CXX src/caffe/layers/cudnn_softmax_layer.cpp
CXX src/caffe/layers/memory_data_layer.cpp
CXX src/caffe/layers/mvn_layer.cpp
CXX src/caffe/layers/inner_product_layer.cpp
CXX src/caffe/layers/hinge_loss_layer.cpp
CXX src/caffe/layers/neuron_layer.cpp
CXX src/caffe/layers/dummy_data_layer.cpp
CXX src/caffe/layers/base_data_layer.cpp
CXX src/caffe/layers/sigmoid_cross_entropy_loss_layer.cpp
CXX src/caffe/layers/cudnn_pooling_layer.cpp
CXX src/caffe/layers/flatten_layer.cpp
CXX src/caffe/layers/absval_layer.cpp
CXX src/caffe/layers/bnll_layer.cpp
CXX src/caffe/layers/sigmoid_layer.cpp
CXX src/caffe/layers/hdf5_data_layer.cpp
CXX src/caffe/layers/euclidean_loss_layer.cpp
CXX src/caffe/layers/image_data_layer.cpp
CXX src/caffe/layers/im2col_layer.cpp
CXX src/caffe/layers/conv_layer.cpp
CXX src/caffe/layers/dropout_layer.cpp
CXX src/caffe/layers/slice_layer.cpp
CXX src/caffe/layers/lrn_layer.cpp
CXX src/caffe/layers/softmax_loss_layer.cpp
CXX src/caffe/layers/silence_layer.cpp
CXX src/caffe/layers/concat_layer.cpp
CXX src/caffe/layers/multinomial_logistic_loss_layer.cpp
CXX src/caffe/layers/hdf5_output_layer.cpp
CXX src/caffe/layers/exp_layer.cpp
CXX src/caffe/layers/split_layer.cpp
CXX src/caffe/layers/prelu_layer.cpp
CXX src/caffe/util/math_functions.cpp
CXX src/caffe/util/benchmark.cpp
CXX src/caffe/util/insert_splits.cpp
CXX src/caffe/util/db.cpp
CXX src/caffe/util/cudnn.cpp
CXX src/caffe/util/upgrade_proto.cpp
CXX src/caffe/util/im2col.cpp
CXX src/caffe/util/io.cpp
CXX src/caffe/internal_thread.cpp
CXX src/caffe/layer_factory.cpp
CXX src/caffe/net.cpp
CXX src/caffe/data_transformer.cpp
CXX src/caffe/solver.cpp
CXX src/caffe/blob.cpp
CXX src/caffe/common.cpp
NVCC src/caffe/layers/deconv_layer.cu
NVCC src/caffe/layers/conv_layer.cu
NVCC src/caffe/layers/slice_layer.cu
NVCC src/caffe/layers/silence_layer.cu
NVCC src/caffe/layers/lrn_layer.cu
NVCC src/caffe/layers/pooling_layer.cu
NVCC src/caffe/layers/cudnn_conv_layer.cu
NVCC src/caffe/layers/dropout_layer.cu
NVCC src/caffe/layers/power_layer.cu
NVCC src/caffe/layers/threshold_layer.cu
NVCC src/caffe/layers/contrastive_loss_layer.cu
NVCC src/caffe/layers/sigmoid_layer.cu
NVCC src/caffe/layers/absval_layer.cu
NVCC src/caffe/layers/prelu_layer.cu
NVCC src/caffe/layers/cudnn_pooling_layer.cu
NVCC src/caffe/layers/softmax_loss_layer.cu
NVCC src/caffe/layers/im2col_layer.cu
NVCC src/caffe/layers/split_layer.cu
NVCC src/caffe/layers/sigmoid_cross_entropy_loss_layer.cu
NVCC src/caffe/layers/euclidean_loss_layer.cu
NVCC src/caffe/layers/exp_layer.cu
NVCC src/caffe/layers/cudnn_tanh_layer.cu
NVCC src/caffe/layers/hdf5_output_layer.cu
NVCC src/caffe/layers/cudnn_relu_layer.cu
NVCC src/caffe/layers/inner_product_layer.cu
NVCC src/caffe/layers/hdf5_data_layer.cu
NVCC src/caffe/layers/bnll_layer.cu
NVCC src/caffe/layers/tanh_layer.cu
NVCC src/caffe/layers/cudnn_softmax_layer.cu
NVCC src/caffe/layers/softmax_layer.cu
NVCC src/caffe/layers/cudnn_sigmoid_layer.cu
NVCC src/caffe/layers/mvn_layer.cu
NVCC src/caffe/layers/eltwise_layer.cu
NVCC src/caffe/layers/concat_layer.cu
NVCC src/caffe/layers/relu_layer.cu
NVCC src/caffe/layers/base_data_layer.cu
NVCC src/caffe/util/math_functions.cu
NVCC src/caffe/util/im2col.cu
CXX tools/device_query.cpp
CXX tools/net_speed_benchmark.cpp
CXX tools/upgrade_net_proto_binary.cpp
CXX tools/train_net.cpp
CXX tools/finetune_net.cpp
CXX tools/upgrade_net_proto_text.cpp
CXX tools/compute_image_mean.cpp
CXX tools/convert_imageset.cpp
CXX tools/caffe.cpp
CXX tools/extract_features.cpp
CXX tools/test_net.cpp
CXX examples/siamese/convert_mnist_siamese_data.cpp
CXX examples/cifar10/convert_cifar_data.cpp
CXX examples/mnist/convert_mnist_data.cpp
CXX .build_release/src/caffe/proto/caffe.pb.cc
AR -o .build_release/lib/libcaffe.a
LD -o .build_release/lib/libcaffe.so
CXX/LD -o .build_release/tools/device_query.bin
CXX/LD -o .build_release/tools/net_speed_benchmark.bin
CXX/LD -o .build_release/tools/upgrade_net_proto_binary.bin
CXX/LD -o .build_release/tools/train_net.bin
CXX/LD -o .build_release/tools/finetune_net.bin
CXX/LD -o .build_release/tools/upgrade_net_proto_text.bin
CXX/LD -o .build_release/tools/compute_image_mean.bin
CXX/LD -o .build_release/tools/convert_imageset.bin
/usr/bin/ld: warning: libcudart.so.6.5, needed by /usr/lib/libcaffe.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libcublas.so.6.5, needed by /usr/lib/libcaffe.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libcurand.so.6.5, needed by /usr/lib/libcaffe.so, not found (try using -rpath or -rpath-link)
/usr/lib/libcaffe.so: undefined reference to `gflags::ParseCommandLineFlags(int*, char***, bool)'
collect2: error: ld returned 1 exit status
/usr/bin/ld: warning: libcudart.so.6.5, needed by /usr/lib/libcaffe.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libcublas.so.6.5, needed by /usr/lib/libcaffe.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libcurand.so.6.5, needed by /usr/lib/libcaffe.so, not found (try using -rpath or -rpath-link)
/usr/lib/libcaffe.so: undefined reference to `gflags::ParseCommandLineFlags(int*, char***, bool)'
make: *** [.build_release/tools/upgrade_net_proto_text.bin] Error 1
make: *** Waiting for unfinished jobs....
collect2: error: ld returned 1 exit status
make: *** [.build_release/tools/finetune_net.bin] Error 1
/usr/bin/ld: warning: libcudart.so.6.5, needed by /usr/lib/libcaffe.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libcublas.so.6.5, needed by /usr/lib/libcaffe.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning/usr/bin/ld: warning: libcudart.so.6.5, needed by /usr/lib/libcaffe.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libcublas.so.6.5, needed by /usr/lib/libcaffe.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libcurand.so.6.5, needed by /usr/lib/libcaffe.so, not found (try using -rpath or -rpath-link)
/usr/lib/libcaffe.so: undefined reference to `gflags::ParseCommandLineFlags(int*, char***, bool)'
: libcurand.so.6.5, needed by /usr/lib/libcaffe.so, not collect2: error: ld returned 1 exit status
found (try using -rpath or -rpath-link)
/usr/lib/libcaffe.so: undefined reference to `gflags::ParseCommandLineFlags(int*, char***, bool)'
collect2: error: ld returned 1 exit status
make: *** [.build_release/tools/upgrade_net_proto_binary.bin] Error 1
make: *** [.build_release/tools/device_query.bin] Error 1
/usr/bin/ld: warning: libcudart.so.6.5, needed by /usr/lib/libcaffe.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libcublas.so.6.5, needed by /usr/lib/libcaffe.so, not found (try using -rpath or -rpath-link)/usr
/usr/bin/ld: warning: libcurand.so.6.5, needed by /usr/lib/libcaffe.so, not found (try using -rpath or -rpath-link)
.build_release/tools/convert_imageset.o: In function `main':
convert_imageset.cpp:(.text.startup+0x873): undefined reference to `caffe::ReadImageToDatum(std::string const&, int, int, int, bool, std::string const&, caffe::Datum*)'
/usr/lib/libcaffe.so: undefined reference to `gflags::ParseCommandLineFlags(int*, char***, bool)'
/bin/ld: warning: libcudart.so.6.5collect2: error: ld returned 1 exit status
, needed by /usr/lib/libcaffe.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libcublas.so.6.5, needed by /usr/lib/libcaffe.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libcurand.so.6.5make: , needed by *** [.build_release/tools/convert_imageset.bin] Error 1
/usr/lib/libcaffe.so, not found (try using -rpath or -rpath-link)
.build_release/tools/compute_image_mean.o: In function `main':
compute_image_mean.cpp:(.text.startup+0x2a4): undefined reference to `caffe::DecodeDatumNative(caffe::Datum*)'
compute_image_mean.cpp:(.text.startup+0x492): undefined reference to `caffe::DecodeDatumNative(caffe::Datum*)'
/usr/lib/libcaffe.so: undefined reference to `gflags::ParseCommandLineFlags(int*, char***, bool)'
collect2: error: ld returned 1 exit status
make: *** [.build_release/tools/compute_image_mean.bin] Error 1
/usr/bin/ld: warning: libcudart.so.6.5, needed by /usr/lib/libcaffe.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libcublas.so.6.5, needed by /usr/lib/libcaffe.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libcurand.so.6.5, needed by /usr/lib/libcaffe.so, not found (try using -rpath or -rpath-link)
/usr/lib/libcaffe.so: undefined reference to `gflags::ParseCommandLineFlags(int*, char***, bool)'
collect2: error: ld returned 1 exit status
make: *** [.build_release/tools/net_speed_benchmark.bin] Error 1
/usr/bin/ld: warning: libcudart.so.6.5, needed by /usr/lib/libcaffe.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libcublas.so.6.5, needed by /usr/lib/libcaffe.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libcurand.so.6.5, needed by /usr/lib/libcaffe.so, not found (try using -rpath or -rpath-link)
/usr/lib/libcaffe.so: undefined reference to `gflags::ParseCommandLineFlags(int*, char***, bool)'
collect2: error: ld returned 1 exit status
make: *** [.build_release/tools/train_net.bin] Error 1

Is it possible to build Caffe with CUDA 7.0 or must we revert back to 6.5?

Regards,

Brainiarc7

**Comment by immars** [comment]
cuda 7 works for me.
maybe `make clean` first? or delete the old `/usr/lib/libcaffe.so` first?

**Comment by dzhwinter** [comment]
cuda7.0 works well. I think you can change cuda path and rebuild it .

**Comment by pathak22** [comment]
please ask usage questions on [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) -- this issues tracker is primarily for Caffe development discussion. Thanks!
