### ISSUE TITLE
How  to  increase the  accuracy

### ISSUE THREAD

**Issue by wzq12138** [BVLC/caffe#2232]
I  have  trained  the image  myself  about  the  bvlc_caffenet  example,at  first,the  increase  could  only  be  about  0.4,then  I  changed  the  base_lr  to  0.001,at  first  it  is 0.01,the  accuracy  could  be 0.9  now
1.what  is  base_lr，why  I  changed  it  has  such  a   result.
2.what  can  I  do  to  make the  accuracy  to  0.99,the  net  is  the  example  of   bvlc_caffenet,and  I used  it  to  classify   the  big,middle  and  small  car

**Comment by mdilli** [comment]
The base_lr is the initial learning rate. Too high learning rate means the weights take big steps. This may cause them to overstep the minimum. There are also settings to change the learning rate over time (decrease after a while when presumably closer to the minimum).

**Comment by shelhamer** [comment]
Please ask on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) group.
