### ISSUE TITLE
missing O_BINARY in ReadProtoFromBinaryFile(), io.cpp

### ISSUE THREAD

**Issue by mattip** [BVLC/caffe#2233]
In io.cpp, ReadProtoFromBinaryFile, the line::

    int fd = open(filename, O_RDONLY);

should be:

    int fd = open(filename, O_RDONLY | O_BINARY);

Should I make a pull request or is this enough?

**Comment by longjon** [comment]
Closing as this does not seem correct; on Linux there is no `O_BINARY` flag. If this is a Windows issue, note that Windows is not supported by `master` at this time.
