### ISSUE TITLE
draw_net error of importing libhdf5_hl.so.8

### ISSUE THREAD

**Issue by Jianchao-ICT** [BVLC/caffe#2234]
I have run 

make all
make pycaffe
make matcaffe
make test 
make runtest

All of them seem to be successful. The questionable one is make pycaffe, which gives the following information:

CXX/LD -o python/caffe/_caffe.so python/caffe/_caffe.cpp
touch python/caffe/proto/__init__.py
PROTOC (python) src/caffe/proto/caffe.proto

Then I call draw_net.py to visualize the network structure, but it throws an import error w.r.t libhdf5_hl.so.8. I check the PYTHONPATH, LD_LIBRARY_PATH and the actual path of libhdf5_hl.so.8 and do not find obvious problems.

Could you give any advice on what is the possible reason of the error?

**Comment by shelhamer** [comment]
Please ask on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) group. `pycaffe` is likely linked to a different HDF5 library.
