### ISSUE TITLE
Re: Check failed: target_blobs[j]->num() ==source_layer.blobs(j).num() (48 vs. 0)

### ISSUE THREAD

**Issue by wzq12138** [BVLC/caffe#2236]
The  error  comes  from  Jeston  TK1,when  I  want  to  test  my  model  on  the  jetson  TK1,it comes  the error,I  test  it  as  the  web_demo，can  you  help  me,what  does  it  mean,,and  how  can  I  slove  it

**Comment by longjon** [comment]
Closing as this looks like a usage issue; please ask such issues on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) list. Thanks!

**Comment by y22ma** [comment]
I'm running into this issue as well, and I'm not sure if it is a usage issue. The exact same code, model and deploy.prototxt works on my PC, but fails on TK1.
