### ISSUE TITLE
[bug report] Floating point exception when width and/or height equals crop_size

### ISSUE THREAD

**Issue by Ashwani001** [BVLC/caffe#2242]
This issue was brought up in #1199 , due to which in
>caffe_root/src/caffe/data_transformer.cpp

this part:
>if (phase_ == TRAIN) {
      h_off = Rand(datum_height - crop_size + 1);
      w_off = Rand(datum_width - crop_size + 1);
    } 

was modified.

However the error stills persists.
I believe the 
>else {
      h_off = (datum_height - crop_size) / 2;
      w_off = (datum_width - crop_size) / 2;
    }

part needs to be modified.

Also, the same error occurs due to
> caffe_root/src/caffe/net.cpp

It needs to be modified as well (I have not been able to figure out what is wrong, I solved the issue by reducing crop size).

**Comment by longjon** [comment]
Closing as I don't see an issue here. The code you are citing appears to be correct. If there's a specific crash or incorrect behavior you're witnessing, you're welcome to open a new issue.
