### ISSUE TITLE
text classification

### ISSUE THREAD

**Issue by nazarblch** [BVLC/caffe#2244]
Hello,
I study methods of text classification using CNN, in this task I have input data elements with different sizes. So to process them with caffe a new type of convolution and pooling layers are required: their bottom and top blobs should have non-fixed height_ and height_out_.
Could you provide some hints or base instructions for implementing such type of layers?

**Comment by shelhamer** [comment]
The convolution and pooling layers already work for this case. There's no need for new layers.

On-the-fly reshaping #594 gave layers a `Reshape` method so their bottom and top blobs can change shape. With reshaping data #1313 each input can be a different size. One can manually reshape in Python too like in the 3rd code cell of the [filter visualization example](http://nbviewer.ipython.org/github/BVLC/caffe/blob/master/examples/filter_visualization.ipynb).

All this does need documentation. Although the development you asked about is already done, you could help by adding detail to the layer documentation or making examples.

On the same topic, @pannous has nicely shared examples on [speech](https://github.com/pannous/caffe-speech-recognition) and [text](https://github.com/pannous/caffe/tree/topics/examples/topics) that I hope to see pull requested when they're ready one day.

**Comment by nazarblch** [comment]
Thanks for comment, I will try to help with documentation during my research.  

Where I can find code blocks, corresponded for merging diffs (backward gradients) from different inputs and executing Rashape methods in data layers during train stage?

I have observed examples of nets proto for text classification (https://github.com/pannous/caffe/blob/topics/examples/topics/hello_net.prototxt), but I haven't found an intermediate layer that converts blobs from different inputs with different sizes to fixed size top blobs.
For example:
data
conv
pool
from_var_shape_to_fixed_layer
fc

from_var_shape_to_fixed_layer should be included because fc layer requires fixed bottom shape.
Has such type of layer (from_var_shape_to_fixed_layer) already implemented?
