### ISSUE TITLE
pycaffe: input layers are not in `self._inputs`?

### ISSUE THREAD

**Issue by mdilli** [BVLC/caffe#2246]
I am not 100% if sure this is a bug or somethingI'm doing wrong, but [I'm not the only one](http://stackoverflow.com/questions/29124840/prediction-in-caffe-exception-input-blob-arguments-do-not-match-net-inputs) so I thought it'd be useful to report (maybe for documentation).

With code like this:

	net = Net(network_path, TRAIN)
	data = array([[sample] for sample in samples[:128]])  # samples are 70x70 ndarrays

And network that starts like:

	name: "pymemorydatanet"
	layer {
	  name: "data"
	  type: "MemoryData"
	  top: "data"
	  top: "label"
	  memory_data_param {
	    batch_size: 128
	    channels: 1
	    height: 70
	    width: 70
	  }
	}
	layer {
	  name: "conv1"
	...

I get the error

	File "/home/mark/mlip1/caffe/python/caffe/pycaffe.py", line 84, in _Net_forward
	  raise Exception('Input blob arguments do not match net inputs.')

I found that this is because `list(net._inputs)` is `[]`, while I think it should be `[0]`.

Indeed, for a network like

    name: "CaffeNet"
    input: "data"
    input_dim: 1
    input_dim: 3
    input_dim: 227
    input_dim: 227
    layer {
      name: "conv1"
    ...

`list(net._inputs) = [0]` and things work.

What surprises me is that `net._input` seems to come from the C code, so should not be limited to pycaffe? But it works for the command line for me (that is, it crashes at a later point with `MemoryDataLayer needs to be initalized by calling Reset`, perhaps unrelated).

Is this a bug, and what can be done about it? I'll gladly provide more information tomorrow.

**Comment by mdilli** [comment]
Can anyone confirm whether this is indeed a bug?

**Comment by longjon** [comment]
This is not a bug. An `input` in this case does not include a data layer; it's an unattached bottom.

Please ask further usage questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) list. Thanks!

**Comment by mdilli** [comment]
For people who find this issue, I asked on the list: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/caffe-users/eEhSBlKcjpc/llQi9PTPAYsJ
