### ISSUE TITLE
what  does  the  time  in  web_demo  relative  to

### ISSUE THREAD

**Issue by wzq12138** [BVLC/caffe#2248]
HI,guys,can  you  tell  me  what  does  the  time  in  web_demo  relative  to?I  hvae  tested  the  web_demo  http://demo.caffe.berkeleyvision.org/   here,the   time  is  0.077seconds.
and  I  tested  it  on  my  computer   the  time  is  about  0.15seconds,and   tested  it  on  TK1,it  is  about  0.35  seconds.
web          computer        TK1
0.077        0.15               0.35

cpu?        4G                  2G

does  it  relative  to  the  CPU,and  the  server  of  web  is  8G?
and  has  it  no  relative  to  the  CUDA  GPU  capility.
if  I   increase  the  CPU  of  TK1,then  the  speed  will  increase???????

**Comment by wzq12138** [comment]
nobody  knows?

**Comment by shelhamer** [comment]
The web demo is running on a spare desktop with a GTX 770.
