### ISSUE TITLE
MemoryDataLayer that accepts multiple float labels associated to a sample

### ISSUE THREAD

**Issue by gabrielecostante** [BVLC/caffe#2257]
Hi, I'm trying to use caffe for multi-output regression and this means that I need multiple float label values for each sample. 
Analyzing the code for the MemoryDataLayer I saw that it only accepts a single int label for each sample. 

Is it possible to change that layer easily to accept multiple float values? For example by only adding another AddMatVector function that takes cons vector<vector< float> >& labels? or would these require a deeper modification of the framework?

Thanks

**Comment by longjon** [comment]
Please ask usage questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) list. Thanks!
