### ISSUE TITLE
Cudnn v2 with caffe on Jetson TK1

### ISSUE THREAD

**Issue by jcbppf** [BVLC/caffe#2259]
I am having trouble compiling caffe on the Jetson TK1 board. I already have Cudnn v2 set up, but I am following the instructions to install caffe and when I get to the 'make -j 4 all' step, I execute that step, but during compilation, I get several errors about 'functions not being declared in this scope' or several other errors that terminate compilation. I know that caffe and cudnn v2 don't play well together (yet), but this version of caffe should. Any advice? Thanks!

**Comment by wzq12138** [comment]
what  do  you want  to  do  for  the  cudnn,I have  tried  the  cudnn V1,it  is  not  faster,I  do  not  know  why

**Comment by jcbppf** [comment]
I would like to use cudnn v2 with caffe. I downloaded cudnn on the Nvidia
website and the only version offered was cudnn v2. I want to use it for
robotics and general neural network stuff. Thanks!

**Comment by shelhamer** [comment]
Caffe is compatible with cuDNN v2 as of #2038 which was merged when v2 was officially released.

Please discuss installation on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) group.
