### ISSUE TITLE
how to use matlab interface to train my own model

### ISSUE THREAD

**Issue by henurgwpf** [BVLC/caffe#2260]
I mean that I want use my own deploy.prototxt(not imagenet), but I think I should train a corresponding model(not imagenet-reference model) for the deploy.prototxt file. The problem is how I train my own model use matlab interface.

**Comment by rohrbach** [comment]
Please ask usage questions on [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) -- this issues tracker is primarily for Caffe development discussion. Thanks!
