### ISSUE TITLE
Find similar Images

### ISSUE THREAD

**Issue by talktothehawkaman** [BVLC/caffe#2261]
Hi, 
I am new to caffe so just have a quick doubt. Suppose i have an image and i want to find images similar to that image. What is the general idea and how to do it by caffe. Can it be achieved by just fine tuning because training a complete network from scratch requires months of time and data. Please Help

**Comment by jmozah** [comment]
Look at the Siamese network example included in caffe

**Comment by talktothehawkaman** [comment]
@jmozah  What do you suggest is training a network from scratch is good or just fine tuning will do the job ?

**Comment by shelhamer** [comment]
Please ask on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) group.
