### ISSUE TITLE
make runtest Error: gflags problem

### ISSUE THREAD

**Issue by IdiosyncraticDragon** [BVLC/caffe#2263]
Here is the error message:

========================================================
.build_release/test/test_all.testbin 0 --gtest_shuffle

ERROR: something wrong with flag 'flagfile' in file '/home/lgy/Experiments/gflags-master/src/gflags.cc'.  One possibility: file '/home/lgy/Experiments/gflags-master/src/gflags.cc' is being linked both statically and dynamically into this executable.
make: *** [runtest] Error 1

========================================================

I am Ubuntu 14.04 LTS+ cuda-5.5, and I install the glog and gflag from source, then I met such error, so I go to the source folder glog and gflag, run "make clean" and delete them,  use this command mentioned in Caffe website:

        sudo apt-get install libgflags-dev libgoogle-glog-dev liblmdb-dev protobuf-compiler
but...it doesn't work, it is still this error, seems like I didn't delete some settings of the gflag , Do anyone meet such error?

**Comment by tetsunosuke** [comment]
remove libgflags.a, libgflags_nothreads.a, and again make caffe.

so you will unlink the "statically" one.

**Comment by RomainDWipsea** [comment]
Hi, I have the same problem here and removing the .a files didn't solve it, has someone found a way?

**Comment by IdiosyncraticDragon** [comment]
I solved this problem by re-install every thing about caffe, and using MKL lib instead of Altas

**Comment by rjbruin** [comment]
So this is a problem with Atlas, not with gflags?

Can anybody shed some light on the actual problem at hand? I would like to understand what is going wrong here.

**Comment by RomainDWipsea** [comment]
Hi, in my case, it was my mistake, i installed both 2 versions of the packages for ubuntu 12.04 and 14.04 in this tutorial http://caffe.berkeleyvision.org/install_apt.html . I didn't notice it was twice the same thing, I started again doing it right and it was ok.

**Comment by rjbruin** [comment]
I may actually have done that as well. I just cannot find the right way to uninstall both installations of the package, but that is no issue related to Caffe.

Thanks for your help! If anyone else thinks there may still be another problem I'd like to hear it. :)

**Comment by IdiosyncraticDragon** [comment]
I found that I was in the same situation as @RomainDWipsea  when I met this problem, and I don't know how to uninstall the the gflags properly , so finally I do all the installation again and found the problem didn't appear any more

**Comment by rjbruin** [comment]
By 'all the installation', do you mean reinstalling your OS or something requiring less effort than that?

**Comment by IdiosyncraticDragon** [comment]
I mean the installation of caffe. According to your discussion I think I met this problem because I installed both dependency packages for 12.04 and 14.04.  But I don't know how to fix the problem that time, so I followed the installation instructions supplied by caffe for 14.04 again,  step by step , and change the altas to mkl( which seems may not have relationship with this issue)

**Comment by rjbruin** [comment]
My problem though is that the gflags.cc file the error is referencing doesn't even exist anymore. Do you know how I can remove gflags so that the system does not try to use it anymore? I have tried a complete reinstall of caffe and all dependencies but that does not solve the problem.

**Comment by RomainDWipsea** [comment]
I tried to find a way to remove these packages but couldn't find a way, so i reinstalled my OS to start clean. However I'm quite sure there is another way but it was just faster for me to reinstall than finding this other way...

**Comment by IdiosyncraticDragon** [comment]
If you are installing the gflags  from source code (download the source file , and make install), then I don't know.., because I tried many time, but failed, it just keep warning the message "file '/home/lgy/Experiments/gflags-master/src/gflags.cc' is being linked both statically and dynamically into this executable." Even if I delete the folder "gflags-master", it doesnt' work, it seems like the path of gflags was  written into some global setting where we do not know where it is

**Comment by matlab379** [comment]
I have solve this problem by this way as follows. Firstly, you can follow the steps of installing these packages by sources, and make install them, then you can find what files are installed in the root of operator system, then remove it forcibly. Secondly, use the command of "apt-get remove " to remove these three packages. Reboot the computer. Thirdly, install the packages by the way you want.　Just try it, hope it can help you too.

**Comment by fernandoc1** [comment]
The issue here is that you installed two versions of the same library.
So, my suggestion is to do the following, in order to remove the files installed in your system:
    cd /usr/local
    find . -type f -printf '%T@ %p\n' | sort -k 1 -n
This will list files sorted in the last modification order.
Then, just see which ones are installed and just remove them all.

Remove the build folder and compile everything again and the problem will be solved.

**Comment by ahmdtaha** [comment]
I made the same mistake.
I followed the solution posted in this stackoverflow link
http://stackoverflow.com/questions/30475415/caffe-compilation-error-gflags-cc-is-being-linked-both-statically-and-dynamica

and it worked for me.

**Comment by GodOfProbability** [comment]
I followed the same link posted by @ahmdtaha. Thanx man. I think the issue can be closed now.

**Comment by ArturoDeza** [comment]
I can't seem to find the commands to make a proper to caffe uninstall to later reinstall. I am supposed to just do make clean? Should I delete the folder? What if I have two differente caffe version and I want to trace them down?
