### ISSUE TITLE
how to share weights for different input in a conv_layer?

### ISSUE THREAD

**Issue by hqqxyy** [BVLC/caffe#2265]
I have 2 input blob, and their sizes are same: 16 * 3 * 224 * 224. They are all inputted into a conv_layer, I want to share the weight between them. How should I set the conv layer? 

Is this OK?

data_1: 16 * 3 * 224 * 224
data_2: 16 * 3 * 224 * 224

layer {
  name: "conv1"
  type: "Convolution"
  bottom: "data_1"
  bottom: "data_2"
  top: "conv1_1"
  top: "conv1_2"
  convolution_param {
    num_output: 96
    kernel_size: 11
    stride: 4
  }
}

**Comment by shelhamer** [comment]
This is fine. Please ask usage questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) group.
