### ISSUE TITLE
error when creating cifar10 lmdb and mean.binaryproto

### ISSUE THREAD

**Issue by SpencerL** [BVLC/caffe#2266]
Hello,everyone. I wanted to test caffe  on cifar10 dataset . To transform the data format to lmdb, I did just  as the tutorial http://caffe.berkeleyvision.org/gathered/examples/cifar10.html
and I only get cifar10_train_lmdb , the error  seems like as follow:

![error](https://cloud.githubusercontent.com/assets/7265041/7004892/82f97a7e-dca4-11e4-9e59-00a56e60b367.png)
Is there someone knows how to  deal with this? Thank you all~

**Comment by longjon** [comment]
Please ask usage questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) list. Thanks!
