### ISSUE TITLE
problem similar to #2041 with detector.py

### ISSUE THREAD

**Issue by latharam** [BVLC/caffe#2268]
I am facing a problem similar to #2041 but with detector.py

Am getting the same error:
predictions = out[self.outputs[0]].squeeze(axis=(2,3))
ValueError: 'axis' entry 2 is out of bounds [-2, 2)

removing the arguments from
predictions = out[self.outputs[0]].squeeze(axis=(2,3))
and making it 
predictions = out[self.outputs[0]].squeeze()
fixes this problem but later

when I execute the following piece of code from http://nbviewer.ipython.org/github/bvlc/caffe/blob/master/examples/detection.ipynb

---->predictions_df = pd.DataFrame(np.vstack(df.prediction.values), columns=labels_df['name'])
print(predictions_df.iloc[0])

I got the following error
Traceback (most recent call last):
File "ipynotebuk.py", line 22, in 
predictions_df = pd.DataFrame(np.vstack(df.prediction.values), columns=labels_df['name'])
File "/home/lpemula/LPIR_Caffe/env/lib/python2.7/site-packages/pandas/core/frame.py", line 239, in init
copy=copy)
File "/home/lpemula/LPIR_Caffe/env/lib/python2.7/site-packages/pandas/core/frame.py", line 399, in _init_ndarray
return create_block_manager_from_blocks([values.T], [columns, index])
File "/home/lpemula/LPIR_Caffe/env/lib/python2.7/site-packages/pandas/core/internals.py", line 3534, in create_block_manager_from_blocks
construction_error(tot_items, blocks[0].shape[1:], axes, e)
File "/home/lpemula/LPIR_Caffe/env/lib/python2.7/site-packages/pandas/core/internals.py", line 3515, in construction_error
passed,implied))
ValueError: Shape of passed values is (1000, 1570), indices imply (200, 1570)

If I modify it as below,
predictions_df = pd.DataFrame(np.vstack(df.prediction.values))

It runs fine but I am not sure if what I did is right. Please let me know the right fix for this.

**Comment by BinRoot** [comment]
Confirmed. I am also experiencing this exact bug.

**Comment by latharam** [comment]
I found out the problem in mine. 
The last error

ValueError: Shape of passed values is (1000, 1570), indices imply (200, 1570)

was caused because I was using the caffenet for classification for detection task and hence the mismatch of the passed values (classification challenge has 1000 categories and detection has 200 categories).

this confusion is caused because of this line

-Run ./scripts/download_model_binary.py models/bvlc_reference_caffenet to get the Caffe R-CNN ImageNet model.

 in the ipython notebook readme at this link http://nbviewer.ipython.org/github/bvlc/caffe/blob/master/examples/detection.ipynb

the bvlc_reference_caffenet model is for classification. We are supposed to use bvlc_reference_rcnn_ilsvrc13 for detection.

Once I replaced the model, everything worked fine. So the only place where you need to edit manually is

emoving the arguments from
predictions = out[self.outputs[0]].squeeze(axis=(2,3))
and making it 
predictions = out[self.outputs[0]].squeeze().

SO I think this issue can be closed

**Comment by ashr59** [comment]
@latharam, It is a perfect solution. Thanks.
