### ISSUE TITLE
error  when  classify  the  image

### ISSUE THREAD

**Issue by wzq12138** [BVLC/caffe#2270]
I  have  trained  my  model  with  the  command   :./caffe/build/tools/caffe train --solver=./caffe/models/bvlc_reference_caffenet/solver.prototxt --weights=./caffe/models/bvlc_reference_caffenet/bvlc_reference_caffenet.caffemodel
my  model  is  3classes,and  then  I  test  the  accuracy  with  the   command  
./build/tools/caffe test --model=models/bvlc_reference_caffenet/train_val.prototxt -weights=models/bvlc_reference_caffenet/caffenet_train_iter_2000.caffemodel -gpu=0
the  accuracy  is  0.96,   but  when  I  test  it  as  the  example  like http://nbviewer.ipython.org/github/BVLC/caffe/blob/master/examples/classification.ipynb

the  result  is  very  strange,each  classes   is   the  same as  0.33333333333,I  heared   it  should  create  a  new  mean_file,instead  of   ilsvrc_2012_mean.npy,so  how   can  I   create  the   new  mean  file

**Comment by shelhamer** [comment]
Please ask on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) group.
