### ISSUE TITLE
Java web service Call "classify.py" python script

### ISSUE THREAD

**Issue by waelHamdan** [BVLC/caffe#2272]
I have written a java web service that call the "classify.py" in java using .getRuntime().exec. command

The problem is, every time I call the web service it will initialize the net model.

Would you please suggest me a way to go over this prob., 

Thanks

**Comment by bhack** [comment]
Have you tried to pilot directly in java trough java-cpp caffe preset?
Please close this ticket and use mailing list or gitter channel for support.

**Comment by waelHamdan** [comment]
Thank you
No I didn't try. I think I have to

**Comment by waelHamdan** [comment]
@bhack 
sorry to reopen again.........
But would please advise me to sample code than I can start with?
I am really very new to java-cpp preset and I feel lost already

Thanks in advance

**Comment by bhack** [comment]
See pom and a java example here https://github.com/bytedeco/javacpp-presets/tree/master/caffe.
Please close the ticket and use mailing list, gitter or continue the discussion you have already opened at https://github.com/bytedeco/javacpp-presets/issues/43
