### ISSUE TITLE
getting path name (generate_sample_data.py)

### ISSUE THREAD

**Issue by Ashwani001** [BVLC/caffe#2273]
In >caffe/src/caffe/test/test_data/generate_sample_data.py

The function
>os.path.dirname(__file__) 

returns empty.

I believe 
>os.path.dirname(os.path.abspath(__file__))

should be used instead. I changed it and it solved the problem.

**Comment by Ashwani001** [comment]
see pull request #2274

**Comment by longjon** [comment]
Closing as this has evolved into a PR (thanks!).
