### ISSUE TITLE
Deconvolution of a specific layer

### ISSUE THREAD

**Issue by fariba-abbasi** [BVLC/caffe#2277]
I am new to caffe and i could install and use it for classification and feature extraction successfully. now, i want to deconvolve each layer that i need, for example i need deconvolution of layer 'conv5'. 
Is there someone knows how to do it in caffe?Thank you all.

**Comment by longjon** [comment]
Please ask usage questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) list. Thanks!
