### ISSUE TITLE
Compiling caffe with cuDNN unsuccessful

### ISSUE THREAD

**Issue by wangzheallen** [BVLC/caffe#2280]
When I compiled caffe with cuDNN based on cbef35c76af15c8d133aae37e8029a0705f5aa69(commit with Apr 5 2015), it is with error. When using 6925de1c2edc11e07ccb15fc03c60cadf4607955, it worked well(Jan 17 2015)

**Comment by vimalthilak** [comment]
cudnn v1 vs v2 issue perhaps?

**Comment by wangzheallen** [comment]
I just use cudnn v1, you mean I should use cudnn v2?

**Comment by vimalthilak** [comment]
@wangzheallen Yes, CUDNN v2 support was added recently and unfortunately it's a one way upgrade. If you want to continue working with CUDNN v1, then you will have to work with an older version of the repository.
