### ISSUE TITLE
How  to  create  the  train_model.prototxt   myself

### ISSUE THREAD

**Issue by wzq12138** [BVLC/caffe#2282]
As  I  am  a  new  study   of   cnn,I  just   use  the  example  in  the  caffe-master,such  as   the model  caffenet  model   to  train  my  own  data,whatever   the  result  is  not  bad,the  accuracy   could  be  0.855,
my   question is   how   can  I  learn  to  create  the  prototxt  myself

**Comment by Shaunakde** [comment]
This is a good tutorial: http://caffe.berkeleyvision.org/gathered/examples/mnist.html

Henceforth, please ask such question in caffe google group https://groups.google.com/forum/#!forum/caffe-users

Please close this issue
