### ISSUE TITLE
can I create lmdb from txt file?

### ISSUE THREAD

**Issue by BrendenWashington** [BVLC/caffe#2289]
ok, here is the thing. 

I want to substract a Image by its own mean value, and by doing this , some of the pixel value will be negative, so I plan to store it in a txt file, so my question is that can I use txt files instead of image files  to create the lmdb? is there anyway that I can achieve this

**Comment by melgor** [comment]
Hi,
as I know there is no ready to use tool for it. Now it need paths to images. You have to create that script by your own.
About image mean: Caffe can do this for you. Create LMDB with raw images, then compute image mean using script in tools. Then point it in caffe prototxt. 

Henceforth, please ask such question in caffe google group https://groups.google.com/forum/#!forum/caffe-users

Please, close this issue.
