### ISSUE TITLE
Using .caffemodel in Decaf

### ISSUE THREAD

**Issue by enoonIT** [BVLC/caffe#2291]
Hi,
I'm working on some legacy code using Decaf and the ImageNet trained network to extract features from images. We now need to use the network weights trained on the Places dataset, which are in .caffemodel format.
Our code is in the process of being ported to Caffe but in the meantime it would really be important to test the new weights in the existing framework as soon as possible.

Is there a way to use .caffemodel files in Decaf? Or to convert them into the appropriate format?

Furthermore, are there any pointers on how to port Decaf code to PyCaffe?

Thanks,
Fabio M.

**Comment by rohrbach** [comment]
Please ask usage questions on [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) -- this issues tracker is primarily for Caffe development discussion. Thanks!
