### ISSUE TITLE
how to clear caffe.mex in Matlab

### ISSUE THREAD

**Issue by xn8812** [BVLC/caffe#2292]
Hi dear all,

Does anyone know how to clear caffe.mex in Matlab? I tried "clear mex" and "clear all", but neither works. I use the command "inmem( '-completenames' )"  to check the loaded mex file in memory. Any help? 

Thanks!

**Comment by xn8812** [comment]
@shelhamer

**Comment by rohrbach** [comment]
Please ask usage questions on [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) -- this issues tracker is primarily for Caffe development discussion. Thanks!
