### ISSUE TITLE
Apple match-O linker error 

### ISSUE THREAD

**Issue by karthikeyanchenniappan** [BVLC/caffe#2297]
Hi i am developing a demo iOS app using caffe libraries in Xcode 6.2. I have added libcaffe-d.dylib,
libproto-d.a,caffe.pb.cc,caffe.pb.h,caffe_pb2.py files in my project directory.

 While building the app i got the below architecture error:

 ld: building for iOS Simulator, but linking against dylib built for MacOSX file '/Users/Macpro_ios_v2/Downloads/Caffe-Build-Version/lib/Debug/libcaffe-d.dylib' for architecture x86_64

clang: error: linker command failed with exit code 1 (use -v to see invocation)

While run Caffe master in xocde to generate libcaffe-d.dylib,libproto-d.a libraries ,xocde will automaticalliy selects “universal (32/64 bit intel) (x86_64,i386) - $(ARCHS_STANDRED_32_64_BIT) ” architecture by default.

 Is there any ways to build the Caffe app in armv7 architure? any other frameworks are needs to be added to fix the above issues? How to change architecture preferences in Cmake file list?

**Comment by longjon** [comment]
Closing as this does not seem like an issue with Caffe; it would be nice to have an ARM build but we don't currently support it, so it's up to you to figure it out. You're welcome to discuss this and other usage issues on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) list.
