### ISSUE TITLE
plotting the values in caffe

### ISSUE THREAD

**Issue by talktothehawkaman** [BVLC/caffe#2299]
Suppose i want start the training and i want to see the various plots like the iteration vs loss plot or anything else what should be done .. should where should the code be edited in what file ?

**Comment by shelhamer** [comment]
Please ask usage questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) group. There's an example script for plotting https://github.com/BVLC/caffe/blob/master/tools/extra/plot_training_log.py.example
