### ISSUE TITLE
Where is the cross-validation done in Caffe?

### ISSUE THREAD

**Issue by polySolo** [BVLC/caffe#2303]
One thing that was not apparent to me while going through Caffe tutorials, was where exactly cross-validation is done? 

Depending on the loss function, we can have different regularization parameters, but it was not apparent to me where/how those parameters were being tuned, if even selected. 

So, where does Caffe do cross-validation for tuning of regularization parameters? (Or is there something fundamental I have missed here?) 

Thanks.

**Comment by lugiavn** [comment]
Caff e doesn't do it. You have to do it manually.
