### ISSUE TITLE
Calculate accuracy on both train and test

### ISSUE THREAD

**Issue by mtHust** [BVLC/caffe#2310]
Hi !
I am trying to do the exaple on MNIST autoencoder, I use the solver exactlly the [mnist_autoencoder_solver](https://github.com/BVLC/caffe/blob/master/examples/mnist/mnist_autoencoder_solver.prototxt)
I have checked the nte file [mnist_autoencoder.prototxt](https://github.com/BVLC/caffe/blob/master/examples/mnist/mnist_autoencoder.prototxt).
I have read the question #1345 . But I got this error:
> 13:41:00.484758 39972 net.cpp:290] The NetState did not contain stage 'test-on-test' specified by a rule in layer data

Addition, my Caffe is MSVC version build by Visual Studio 2013 on  Windows 7 x64,
[Caffe MSVC](https://github.com/mtHust/caffe/tree/msvc)

Thanks.

**Comment by rohrbach** [comment]
We do not support Windows and please ask usage questions on [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) -- this issues tracker is primarily for Caffe development discussion. Thanks!
