### ISSUE TITLE
A bug in contrastive_loss_layer?

### ISSUE THREAD

**Issue by norouzi** [BVLC/caffe#2312]
I think the gradient of the contrastive loss is computed incorrectly in `contrastive_loss_layer`.

The objective has the term `||a-b||^2` and the gradient of squared distance with respect to a is `a - 2 * b`. However, in the code this gradient is computed as `a - b` using the cashed difference.

I think this is okay when `a` and `b` are connected to identical networks which share the same parameters, but when the networks are not identical this becomes an issue. Further, this may confuse other people too, so may be a good idea to fix it if I am right.

**Comment by nickcarlevaris** [comment]
After looking it over I don't see any errors. 
```
d/da ||a-b||_2^2 = d/da (a - b)'(a - b) = 2(a - b) * d/da(a-b) = 2(a-b)
d/db ||a-b||_2^2 = d/db (a - b)'(a - b) = 2(a - b) * d/db(a-b) = -2(a-b)
```
Right?

Note that this code passes the test in test_contrastive_loss_layer.cpp and that the test makes no assumption about a and b coming from identical networks, it just feeds two random vectors in for a and b.

Also, checkout how the derivative is calculated for the Euclidean loss layer--it is the same.

**Comment by norouzi** [comment]
Oops, you are right, my bad!
