### ISSUE TITLE
Global pooling layer

### ISSUE THREAD

**Issue by PiranjaF** [BVLC/caffe#2316]
Does Caffe has a global pooling layer such as mentioned in http://benanne.github.io/2014/08/05/spotify-cnns.html? (search for global temporal pooling layer).

It's very useful as Caffe expands to other datatypes than images, where the position isn't relevant. From the article: "This layer pools across the entire time axis, effectively computing statistics of the learned features across time. I included three different pooling functions: the mean, the maximum and the L2-norm."

I guess that it isn't implemented. How difficult would it be for me to implement? Could you give me a few pointers on where to start?

**Comment by avalada** [comment]
It is.
https://github.com/BVLC/caffe/issues/1210

**Comment by shelhamer** [comment]
Done in #1214. There is a [global pooling switch](https://github.com/BVLC/caffe/blob/master/src/caffe/proto/caffe.proto#L650-L652) in the `PoolingLayer` configuration. Check [caffe.proto](https://github.com/BVLC/caffe/blob/master/src/caffe/proto/caffe.proto) for all of the configuration options.

**Comment by PiranjaF** [comment]
Thanks. I've tried using it and it seems really useful. However, would it be possible to add the L2-norm or std to the choice of pooling layer? With a mean, std/L2-norm and max global pooling layer, the neural network should be able to extract a lot of information from the data it is pooling. With only a mean and a max pooling layer, important information about the variance is lost. This is particularly an issue when pooling over large amounts of data using the global pooling layer.

Is it perhaps something I could implement rather easily?
