### ISSUE TITLE
Explain in some details about the prototxt file and ask for help about define a "multi scale" layer

### ISSUE THREAD

**Issue by caxieyou** [BVLC/caffe#2317]
Hi

Just start to use the caffe and read all the documentation I can find(maybe missing some). Can any help tell me about where I can find the details about the prototxt file, like what does "lr_mult decay_mult" means when I check the imagenet prototxt file. the caffe.proto is not that "self explain" 
-_-!!!

Besides I am trying to make the net as images shows below.
![1234](https://cloud.githubusercontent.com/assets/6970846/7176306/c0d6ab5c-e44f-11e4-9128-c7d998e9321b.jpg)

the "Max-pooling layers 3" and the "Convolutional layer 4" both connected to the DeepID layer and  "Max-pooling layers 3" connects to the "Convolutional layer 4" too!!!

I dont know how to represent this in caffe, any help?

Thanks~

**Comment by shelhamer** [comment]
Please ask modeling questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) group.
