### ISSUE TITLE
Mixed pooling

### ISSUE THREAD

**Issue by PiranjaF** [BVLC/caffe#2318]
Could Caffe implement mixed pooling as an option for the pooling layers? It seems like it would be quite easy to implement as it's just a combination of mean and max pooling (http://www.tongji.edu.cn/~hanliwang/papers/C28_RSKT14.pdf).

**Comment by amuetzel** [comment]
That link is dead, could you provide a working one?

**Comment by PiranjaF** [comment]
Sorry about that. Link is updated now.

**Comment by longjon** [comment]
Please ask usage questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) list. Thanks!
