### ISSUE TITLE
web_demo example

### ISSUE THREAD

**Issue by geraldstanje** [BVLC/caffe#2319]
Hi,

is the web_demo example (https://github.com/BVLC/caffe/tree/master/examples/web_demo) also available as c++ code?

how many different objects can the web demo recognize?

i see the classification takes: CNN took 0.081 seconds ... any idea how to speed up that?

Thanks,
G

**Comment by geraldstanje** [comment]
can you comment on this?

**Comment by shelhamer** [comment]
No, the web demo is in Python. Please ask usage questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) group.
