### ISSUE TITLE
loss very small 0.0002 but accuracy "not that high"

### ISSUE THREAD

**Issue by userfou** [BVLC/caffe#2322]
I have trained a ConvNet and I am getting a loss of 0.0002. The output of the softmax containing the votes for each class is also very high for one class (0.99 in general, but some are also 0.8) and very low for the others.
Wouldn't that mean that the network is doing very accurate predictions? why am I then getting an accuracy of "only" 80%?

Thanks!

**Comment by userfou** [comment]
would that mean that the network is learning my data set "by heart" in the training phase? Is there a way to avoid this?

**Comment by shelhamer** [comment]
Please ask modeling questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) group or refer to general machine learning tutorials and tips.
