### ISSUE TITLE
The meaning of the If we increased the momentum to μ=0.99, we’ve increased our update size multiplier to 100, so we should drop α (base_lr) by a factor of 10.

### ISSUE THREAD

**Issue by henurgwpf** [BVLC/caffe#2333]
The meaning of the If we increased the momentum to μ=0.99, we’ve increased our update size multiplier to 100, so we should drop α (base_lr) by a factor of 10.  

Why drop  α (base_lr) by a factor of 10,why not 100???

**Comment by shelhamer** [comment]
It's a 10x increase of update size over the base setting of momentum = 0.9, so the learning rate is divided by 10x to balance.

Please ask usage and modeling questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) group.
