### ISSUE TITLE
BNLL layer

### ISSUE THREAD

**Issue by robertotru** [BVLC/caffe#2336]
I'm not sure this is an issue. 

Are you sure about the following ternary operator?

    top_data[i] = bottom_data[i] > 0 ?
        bottom_data[i] + log(1. + exp(-bottom_data[i])) :
        log(1. + exp(bottom_data[i]));

I mean, is ok that `top_data[i]` is the sum of `bottom_data[i]` and the BNLL function only when `bottom_data[i]` is positive?

**Comment by longjon** [comment]
That's what's written in the docs, no? http://caffe.berkeleyvision.org/doxygen/classcaffe_1_1BNLLLayer.html#details

Please ask these types of questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) list. Thanks!
