### ISSUE TITLE
GPU not fully utilized

### ISSUE THREAD

**Issue by weiliu89** [BVLC/caffe#2337]
I implemented a layer which needs to do operations per channel, such as add all channels or scale each channel with a value. I use many caffe_gpu_add, caffe_gpu_mul operations, etc. Besides, I also need to access/store some array (relatively small size), so I use cpu_data() to access the array easily (because I cannot index gpu_data(), e.g. some_gpu_array[10] is not valid operation).

I saw that GPU is not fully utilized when I add such layer in my network. For example, some of the GPUs uses 20% - 50% very frequently. While for network without this layer, GPU utilization is mostly > 90%.

Does anyone has experienced this problem before? If so, how to make it faster and use GPU more efficiently?

**Comment by shelhamer** [comment]
To better utilize the GPU your layer should implement a CUDA kernel to replace the operations that are done on the CPU. See the [dropout layer source](https://github.com/BVLC/caffe/blob/master/src/caffe/layers/dropout_layer.cu) for instance. Optimizing GPU code is a bit out of scope of our github issues, but good luck with your hacking.
