### ISSUE TITLE
Out-of-memory in syncedmem.cpp (when GPU has enough memory)

### ISSUE THREAD

**Issue by Frandre** [BVLC/caffe#2339]
Hi,

I use Linux 14.04, GPU is K40c and I use CUDA6.5. I can compile and run test codes successfully (in both GPU and CPU) and can also run my code in CPU.

However, when it comes to GPU, an error occurs with :
I0419 19:59:24.111495 11084 data_layer.cpp:158] Prefetch batch: 1 ms.
I0419 19:59:24.111529 11084 data_layer.cpp:159]      Read time: 0.073 ms.
I0419 19:59:24.111536 11084 data_layer.cpp:160] Transform time: 1.645 ms.
I0419 19:59:24.113900 11085 data_layer.cpp:158] Prefetch batch: 4 ms.
I0419 19:59:24.113925 11085 data_layer.cpp:159]      Read time: 1.502 ms.
I0419 19:59:24.113931 11085 data_layer.cpp:160] Transform time: 0.826 ms.
Memery need is58082304
Memery need is522740736
F0419 19:59:24.128612 11075 syncedmem.cpp:53] Check failed: error == cudaSuccess (2 vs. 0)  out of memory
*** Check failure stack trace: ***
Aborted (core dumped)

The code error occurs in syncedmem.cpp:
inline void SyncedMemory::to_gpu() {
#ifndef CPU_ONLY
  switch (head_) {
  case UNINITIALIZED:
    using namespace std;
    cout << "Memery need is " << size_ << endl;  <====== print the size_ before memory check
   CUDA_CHECK(cudaMalloc(&gpu_ptr_, size_));   <======HERE!!!!
    caffe_gpu_memset(size_, 0, gpu_ptr_);
    head_ = HEAD_AT_GPU;
    break;
  case HEAD_AT_CPU:
    if (gpu_ptr_ == NULL) {
      CUDA_CHECK(cudaMalloc(&gpu_ptr_, size_));
    }
    caffe_gpu_memcpy(size_, cpu_ptr_, gpu_ptr_);
    head_ = SYNCED;
    break;
  case HEAD_AT_GPU:
  case SYNCED:
    break;
  }
#else
  NO_GPU;
#endif
}

And the GPU information  :
|   1  Tesla K40c          Off  | 0000:02:00.0     Off |                    0 |
| 23%   33C    P8    19W / 235W |     23MiB / 11519MiB |      0%      Default |

I use pycaffe and initialize GPU with : caffe.set_device(1) and caffe_set_mode_gpu() so I think I use the K40 instead of the smaller one. (Smaller one has 1G memory, which should also be alright in this case)

It requires only 500M but still comes up with "out of memory" problem. Does anyone know where the problem is?

Thank you~

P.S. : the batch size is 1 and I cannot make it any smaller.

**Comment by weiliu89** [comment]
@Frandre Memery need is522740736 is not exactly how much memory the network uses, as each layer has additional temporary memory used for computation. For example, in convolution layer, it has the col_buff_ variable which takes a lot of memory. #2016 can save some memory if you have many convolution layer.

**Comment by Frandre** [comment]
@weiliu89  Thanks for your reply. I finally figure out this problem (actually, someone else suggested me to have a try~)

The number of GPU is NOT RIGHT! In my case, although K40c seems to be the number 1 and the smaller one is 0, when I initialize with caffe.set_device(1), it actually uses the smaller one. If we change it to caffe.set_device(0) and everything is alright.

I would like to close the issue and hope my answer can help others.

**Comment by karenyun** [comment]
@Frandre 
i have the same issue, but i can't find the file to set the caffe.set_device(0), which file and which function to set the caffe.set_device(0)?? Thx!

**Comment by ankurgupta7** [comment]
@Frandre thanls for the tip. my code now works!

**Comment by appyfizzA** [comment]
Even with caffe.set_device(0), my code gives the same error.
