### ISSUE TITLE
 build Caffe framework XCode 6.2, iOS 8.3 environment

### ISSUE THREAD

**Issue by karthikeyanchenniappan** [BVLC/caffe#2341]
I am working on build caffe framework for ios, i used the Caffe master source and make files to build the framework for iOS.

I changed the OS target in CMake GUI config as "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk"

While run Xcode to build project i got the below error messages /Users/Macpro_ios_v2/Caffe_iOS/src/caffe/common.cpp:1:10: 'glog/logging.h' file not found "boost/thread.h" file not found i included usr/local/include and opt/local/include to search paths in the build phase

while run the same xcode project for OSX, it works fine and generates the libs perfectly. If i change the target for iphone OS i got above error.

Please help me to fix the above issuse. Please help how to configure the make list in Caffe master for iphone.

I have caffe dylip, lib-a for OSX. Is it possible to link mac osx libaries in iOS project?

**Comment by mfentross** [comment]
Any updates on this one?

**Comment by karthikeyanchenniappan** [comment]
No

**Comment by rohrbach** [comment]
Please ask usage questions on [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) -- this issues tracker is primarily for Caffe development discussion. Thanks!
