### ISSUE TITLE
undefined reference to `cblas_*"

### ISSUE THREAD

**Issue by wbtxd2004** [BVLC/caffe#2353]
When I make all to compile caffe, I got this error:
.build_debug/lib/libcaffe.so: undefined reference to `cblas_dasum'
.build_debug/lib/libcaffe.so: undefined reference to `cblas_dcopy'
.build_debug/lib/libcaffe.so: undefined reference to `cblas_sdot'
.build_debug/lib/libcaffe.so: undefined reference to `cblas_dscal'
.build_debug/lib/libcaffe.so: undefined reference to `cblas_sgemm'
.build_debug/lib/libcaffe.so: undefined reference to `cblas_dgemm'
.build_debug/lib/libcaffe.so: undefined reference to `cblas_sgemv'
.build_debug/lib/libcaffe.so: undefined reference to `cblas_sscal'
.build_debug/lib/libcaffe.so: undefined reference to `cblas_scopy'
.build_debug/lib/libcaffe.so: undefined reference to `cblas_saxpy'
.build_debug/lib/libcaffe.so: undefined reference to `cblas_dgemv'
.build_debug/lib/libcaffe.so: undefined reference to `cblas_sasum'

I use mkl as BLAS. How to solve this problem? 
Thanks!

**Comment by StevenLOL** [comment]
Do you have a build folder, once I got same problem when I  build caffe in its own directory.


mkdir build
cd build
cmake ..
make

**Comment by wbtxd2004** [comment]
Thank you! I use your method and successful installed caffe.

**Comment by wincle** [comment]
I also have this problem, check your Makefile.config , Is there leave one space after BLAS := open  ?delete the space after "open",then recompile it.

**Comment by vishwa15** [comment]
Thank you Wincle. It worked!!

**Comment by noldorj** [comment]
Hi. Were you able to solve this issue with Intel MKL ? I'm facing the same error.

**Comment by northeastsquare** [comment]
@noldorj , iset mkl not MKL, solve
BLAS := mkl
# Custom (MKL/ATLAS/OpenBLAS) include and lib directories.
# Leave commented to accept the defaults for your choice of BLAS
# (which should work)!
BLAS_INCLUDE := /opt/intel/mkl/include/
BLAS_LIB := /opt/intel/mkl/lib/intel64/

**Comment by srbnghosh99** [comment]
I am finding this error message when I am trying to make. 


CXX/LD -o .build_release/test/test_all.testbin src/caffe/test/test_caffe_main.cpp
.build_release/lib/libcaffe.so: undefined reference to `cblas_sgemv'
.build_release/lib/libcaffe.so: undefined reference to `cblas_dgemm'
.build_release/lib/libcaffe.so: undefined reference to `cblas_sscal'
.build_release/lib/libcaffe.so: undefined reference to `cblas_dgemv'
.build_release/lib/libcaffe.so: undefined reference to `cblas_saxpy'
.build_release/lib/libcaffe.so: undefined reference to `cblas_ddot'
.build_release/lib/libcaffe.so: undefined reference to `cblas_dasum'
.build_release/lib/libcaffe.so: undefined reference to `cblas_sgemm'
.build_release/lib/libcaffe.so: undefined reference to `cblas_dscal'
.build_release/lib/libcaffe.so: undefined reference to `cblas_scopy'
.build_release/lib/libcaffe.so: undefined reference to `cblas_sasum'
.build_release/lib/libcaffe.so: undefined reference to `cblas_daxpy'
.build_release/lib/libcaffe.so: undefined reference to `cblas_dcopy'
.build_release/lib/libcaffe.so: undefined reference to `cblas_sdot'
collect2: error: ld returned 1 exit status
make: *** [.build_release/test/test_all.testbin] Error 1

**Comment by kviktor** [comment]
I had the same issue on Manjaro (I'm reporting here cause this is the first hit on Google), as far as I understood the issue was that the openblas library doesn't include all bindings (https://bugs.archlinux.org/task/66092) so I had to install https://aur.archlinux.org/packages/openblas-lapack/ instead.

```
git clone https://aur.archlinux.org/openblas-lapack.git
cd openblas-lapack
makepkg -si
```

With this I could build caffe.

**Comment by jmlago** [comment]
> I had the same issue on Manjaro (I'm reporting here cause this is the first hit on Google), as far as I understood the issue was that the openblas library doesn't include all bindings (https://bugs.archlinux.org/task/66092) so I had to install https://aur.archlinux.org/packages/openblas-lapack/ instead.
> 
> ```
> git clone https://aur.archlinux.org/openblas-lapack.git
> cd openblas-lapack
> makepkg -si
> ```
> 
> With this I could build caffe.

Many thanks, installing openblas-lapack with yay, I was able to compile and install caffe in Manjaro without any problems
