### ISSUE TITLE
Regression for a 2d signal in caffe

### ISSUE THREAD

**Issue by vinaymaddali** [BVLC/caffe#2357]
Hi

I am trying to do some regression for audio signals. My training signal is a big spectrogram which I am feeding in as data of size 513 x num_frames. I want my loss to be computed based on this signal and another spectrogram of the same dimensions. I am using 2d convolution for this and am feeding in the data to the first data blob in HDF5 format as 1 1 513 num_frames. I adjusted the padding according to the kernel size at each layer to keep this dimensionality consistent. At the loss layer (using eucledian distance), I have 1 1 513 num_frames but caffe doesn't let me feed in the label as more than 2d (though my data is 4d as mentioned). It gives me an error: Check failed: ndims <= max_dim (4 vs. 2) 

I tried feeding in an extra input to the first data layer of 1 1 513 num_frames as well along with data and label. But I get the error: ExactNumTopBlobs() == top.size() (2 vs. 3) HDF5_DATA Layer produces 2 top blob(s) as output.

I need my labels to be in the format 1 1 513 num_frames. Could you help me with this?

**Comment by shelhamer** [comment]
Please ask modeling questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) group. `EuclideanLossLayer` accepts predictions and truth of any dimension (as long as they match, of course) if it is given the input in the right way.

**Comment by vinaymaddali** [comment]
But the input it can take is the output from the previous CONV layer and the label from the intial blob input. The data blob layer won't let me give a label input greater than 2d, I need 4d. I posted in the caffe users group as well:
https://groups.google.com/forum/#!topic/caffe-users/xjJqwauvBMQ

**Comment by shelhamer** [comment]
Continued in the Caffe users thread.
