### ISSUE TITLE
Check failed: ReadProtoFromBinaryFile(param file, param)

### ISSUE THREAD

**Issue by loonyma** [BVLC/caffe#2360]
hi All,

I'm new to caffe, I setup caffe on Nvdia Jetson K1 board.
And make runtest already pass. I also setup Python environment, but failed 
After running Python ./Python/classify.py ./cat.jpg output_file, the error message
Attached,please check out. BTY, shall we have a mail list for discussion ？

![Uploading image.jpg . . .]()

**Comment by shelhamer** [comment]
Please ask installation questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) group.
