### ISSUE TITLE
Caffe and CUDA 1.1

### ISSUE THREAD

**Issue by dbl001** [BVLC/caffe#2362]
Hi,

I have an older  MacBook Pro (2009) with:
NVIDIA GeForce 9600M GT
NVIDIA GeForce 9400M
CUDA Driver Version: 6.5.14

Mathematica, Matlab,  and Theano can't use the GPU.
I've read that cuDNN requires CUDA 3.0 (or greater).
Can Caffe run with CUDA 1.1?

Thanks in advance!

**Comment by shelhamer** [comment]
Please ask hardware questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) group and see the [hardware section of the installation guide](http://caffe.berkeleyvision.org/installation.html#hardware).
