### ISSUE TITLE
Caffe Build Issue with protobuf 2.6 on Mac OS X 10.10.3

### ISSUE THREAD

**Issue by dbl001** [BVLC/caffe#2374]
Hi,

I'm getting compilation errors building Caffe on my Mac.
I downloaded, built and installed protobuf from Github.

David-Laxers-MacBook-Pro:caffe davidlaxer$ protoc --version
libprotoc 2.6.1

Any suggestions?

David-Laxers-MacBook-Pro:caffe davidlaxer$ make
protoc --proto_path=src --cpp_out=build/src src/caffe/proto/caffe.proto

protoc --proto_path=src --cpp_out=build/src src/caffe/proto/caffe_pretty_print.proto

/usr/bin/clang++ build/src/caffe/proto/caffe.pb.cc -pthread -fPIC -DNDEBUG -O2 -I/Users/davidlaxer/anaconda/include -I/usr/local/include -Ibuild/src -I./src -I./include -I/Developer/NVIDIA/CUDA-6.5//include -I/System/Library/Frameworks/vecLib.framework/Versions/Current/Headers/ -c -o build/src/caffe/proto/caffe.pb.o
In file included from build/src/caffe/proto/caffe.pb.cc:5:
build/src/caffe/proto/caffe.pb.h:17:2: error: This file was generated by an
      older version of protoc which is
#error This file was generated by an older version of protoc which is
 ^
build/src/caffe/proto/caffe.pb.h:18:2: error: incompatible with your Protocol
      Buffer headers. Please
#error incompatible with your Protocol Buffer headers.  Please
 ^
build/src/caffe/proto/caffe.pb.h:19:2: error: regenerate this file with a newer
      version of protoc.
#error regenerate this file with a newer version of protoc.
 ^
build/src/caffe/proto/caffe.pb.cc:117:9: error: no matching constructor for
      initialization of
      '::google::protobuf::internal::GeneratedMessageReflection'
    new ::google::protobuf::internal::GeneratedMessageReflection(
        ^
/usr/local/include/google/protobuf/generated_message_reflection.h:130:3: note: 
      candidate constructor not viable: requires at least 10 arguments, but 9
      were provided
  GeneratedMessageReflection(const Descriptor* descriptor,
  ^
/usr/local/include/google/protobuf/generated_message_reflection.h:166:3: note: 
      candidate constructor not viable: requires at least 12 arguments, but 9
      were provided
  GeneratedMessageReflection(const Descriptor* descriptor,
  ^
/usr/local/include/google/protobuf/generated_message_reflection.h:541:37: note: 
      candidate constructor not viable: requires 1 argument, but 9 were provided
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(GeneratedMessageReflection);
                                    ^
/usr/local/include/google/protobuf/stubs/common.h:90:3: note: expanded from
      macro 'GOOGLE_DISALLOW_EVIL_CONSTRUCTORS'
  TypeName(const TypeName&);                           \
  ^
build/src/caffe/proto/caffe.pb.cc:132:9: error: no matching constructor for
      initialization of
      '::google::protobuf::internal::GeneratedMessageReflection'
    new ::google::protobuf::internal::GeneratedMessageReflection(
        ^
/usr/local/include/google/protobuf/generated_message_reflection.h:130:3: note: 
      candidate constructor not viable: requires at least 10 arguments, but 9
      were provided
  GeneratedMessageReflection(const Descriptor* descriptor,
  ^
/usr/local/include/google/protobuf/generated_message_reflection.h:166:3: note: 
      candidate constructor not viable: requires at least 12 arguments, but 9
      were provided
  GeneratedMessageReflection(const Descriptor* descriptor,
  ^
/usr/local/include/google/protobuf/generated_message_reflection.h:541:37: note: 
      candidate constructor not viable: requires 1 argument, but 9 were provided
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(GeneratedMessageReflection);
                                    ^
/usr/local/include/google/protobuf/stubs/common.h:90:3: note: expanded from
      macro 'GOOGLE_DISALLOW_EVIL_CONSTRUCTORS'
  TypeName(const TypeName&);                           \
  ^
build/src/caffe/proto/caffe.pb.cc:152:9: error: no matching constructor for
      initialization of
      '::google::protobuf::internal::GeneratedMessageReflection'
    new ::google::protobuf::internal::GeneratedMessageReflection(
        ^
/usr/local/include/google/protobuf/generated_message_reflection.h:130:3: note: 
      candidate constructor not viable: requires at least 10 arguments, but 9
      were provided
  GeneratedMessageReflection(const Descriptor* descriptor,
  ^
/usr/local/include/google/protobuf/generated_message_reflection.h:166:3: note: 
      candidate constructor not viable: requires at least 12 arguments, but 9
      were provided
  GeneratedMessageReflection(const Descriptor* descriptor,
  ^
/usr/local/include/google/protobuf/generated_message_reflection.h:541:37: note: 
      candidate constructor not viable: requires 1 argument, but 9 were provided
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(GeneratedMessageReflection);
                                    ^
/usr/local/include/google/protobuf/stubs/common.h:90:3: note: expanded from
      macro 'GOOGLE_DISALLOW_EVIL_CONSTRUCTORS'
  TypeName(const TypeName&);                           \
  ^
build/src/caffe/proto/caffe.pb.cc:173:9: error: no matching constructor for
      initialization of
      '::google::protobuf::internal::GeneratedMessageReflection'
    new ::google::protobuf::internal::GeneratedMessageReflection(
        ^
/usr/local/include/google/protobuf/generated_message_reflection.h:130:3: note: 
      candidate constructor not viable: requires at least 10 arguments, but 9
      were provided
  GeneratedMessageReflection(const Descriptor* descriptor,
  ^
/usr/local/include/google/protobuf/generated_message_reflection.h:166:3: note: 
      candidate constructor not viable: requires at least 12 arguments, but 9
      were provided
  GeneratedMessageReflection(const Descriptor* descriptor,
  ^
/usr/local/include/google/protobuf/generated_message_reflection.h:541:37: note: 
      candidate constructor not viable: requires 1 argument, but 9 were provided
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(GeneratedMessageReflection);
                                    ^
/usr/local/include/google/protobuf/stubs/common.h:90:3: note: expanded from
      macro 'GOOGLE_DISALLOW_EVIL_CONSTRUCTORS'
  TypeName(const TypeName&);                           \
  ^
build/src/caffe/proto/caffe.pb.cc:192:9: error: no matching constructor for
      initialization of
      '::google::protobuf::internal::GeneratedMessageReflection'
    new ::google::protobuf::internal::GeneratedMessageReflection(
        ^
/usr/local/include/google/protobuf/generated_message_reflection.h:130:3: note: 
      candidate constructor not viable: requires at least 10 arguments, but 9
      were provided
  GeneratedMessageReflection(const Descriptor* descriptor,
  ^
/usr/local/include/google/protobuf/generated_message_reflection.h:166:3: note: 
      candidate constructor not viable: requires at least 12 arguments, but 9
      were provided
  GeneratedMessageReflection(const Descriptor* descriptor,
  ^
/usr/local/include/google/protobuf/generated_message_reflection.h:541:37: note: 
      candidate constructor not viable: requires 1 argument, but 9 were provided
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(GeneratedMessageReflection);
                                    ^
/usr/local/include/google/protobuf/stubs/common.h:90:3: note: expanded from
      macro 'GOOGLE_DISALLOW_EVIL_CONSTRUCTORS'
  TypeName(const TypeName&);                           \
  ^
build/src/caffe/proto/caffe.pb.cc:226:9: error: no matching constructor for
      initialization of
      '::google::protobuf::internal::GeneratedMessageReflection'
    new ::google::protobuf::internal::GeneratedMessageReflection(
        ^
/usr/local/include/google/protobuf/generated_message_reflection.h:130:3: note: 
      candidate constructor not viable: requires at least 10 arguments, but 9
      were provided
  GeneratedMessageReflection(const Descriptor* descriptor,
  ^
/usr/local/include/google/protobuf/generated_message_reflection.h:166:3: note: 
      candidate constructor not viable: requires at least 12 arguments, but 9
      were provided
  GeneratedMessageReflection(const Descriptor* descriptor,
  ^
/usr/local/include/google/protobuf/generated_message_reflection.h:541:37: note: 
      candidate constructor not viable: requires 1 argument, but 9 were provided
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(GeneratedMessageReflection);
                                    ^
/usr/local/include/google/protobuf/stubs/common.h:90:3: note: expanded from
      macro 'GOOGLE_DISALLOW_EVIL_CONSTRUCTORS'
  TypeName(const TypeName&);                           \
  ^
build/src/caffe/proto/caffe.pb.cc:244:9: error: no matching constructor for
      initialization of
      '::google::protobuf::internal::GeneratedMessageReflection'
    new ::google::protobuf::internal::GeneratedMessageReflection(
        ^
/usr/local/include/google/protobuf/generated_message_reflection.h:130:3: note: 
      candidate constructor not viable: requires at least 10 arguments, but 9
      were provided
  GeneratedMessageReflection(const Descriptor* descriptor,
  ^
/usr/local/include/google/protobuf/generated_message_reflection.h:166:3: note: 
      candidate constructor not viable: requires at least 12 arguments, but 9
      were provided
  GeneratedMessageReflection(const Descriptor* descriptor,
  ^
/usr/local/include/google/protobuf/generated_message_reflection.h:541:37: note: 
      candidate constructor not viable: requires 1 argument, but 9 were provided
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(GeneratedMessageReflection);
                                    ^
/usr/local/include/google/protobuf/stubs/common.h:90:3: note: expanded from
      macro 'GOOGLE_DISALLOW_EVIL_CONSTRUCTORS'
  TypeName(const TypeName&);                           \
  ^
build/src/caffe/proto/caffe.pb.cc:280:9: error: no matching constructor for
      initialization of
      '::google::protobuf::internal::GeneratedMessageReflection'
    new ::google::protobuf::internal::GeneratedMessageReflection(
        ^
/usr/local/include/google/protobuf/generated_message_reflection.h:130:3: note: 
      candidate constructor not viable: requires at least 10 arguments, but 9
      were provided
  GeneratedMessageReflection(const Descriptor* descriptor,
  ^
/usr/local/include/google/protobuf/generated_message_reflection.h:166:3: note: 
      candidate constructor not viable: requires at least 12 arguments, but 9
      were provided
  GeneratedMessageReflection(const Descriptor* descriptor,
  ^
/usr/local/include/google/protobuf/generated_message_reflection.h:541:37: note: 
      candidate constructor not viable: requires 1 argument, but 9 were provided
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(GeneratedMessageReflection);
                                    ^
/usr/local/include/google/protobuf/stubs/common.h:90:3: note: expanded from
      macro 'GOOGLE_DISALLOW_EVIL_CONSTRUCTORS'
  TypeName(const TypeName&);                           \
  ^
build/src/caffe/proto/caffe.pb.cc:296:9: error: no matching constructor for
      initialization of
      '::google::protobuf::internal::GeneratedMessageReflection'
    new ::google::protobuf::internal::GeneratedMessageReflection(
        ^
/usr/local/include/google/protobuf/generated_message_reflection.h:130:3: note: 
      candidate constructor not viable: requires at least 10 arguments, but 9
      were provided
  GeneratedMessageReflection(const Descriptor* descriptor,
  ^
/usr/local/include/google/protobuf/generated_message_reflection.h:166:3: note: 
      candidate constructor not viable: requires at least 12 arguments, but 9
      were provided
  GeneratedMessageReflection(const Descriptor* descriptor,
  ^
/usr/local/include/google/protobuf/generated_message_reflection.h:541:37: note: 
      candidate constructor not viable: requires 1 argument, but 9 were provided
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(GeneratedMessageReflection);
                                    ^
/usr/local/include/google/protobuf/stubs/common.h:90:3: note: expanded from
      macro 'GOOGLE_DISALLOW_EVIL_CONSTRUCTORS'
  TypeName(const TypeName&);                           \
  ^
build/src/caffe/proto/caffe.pb.cc:318:9: error: no matching constructor for
      initialization of
      '::google::protobuf::internal::GeneratedMessageReflection'
    new ::google::protobuf::internal::GeneratedMessageReflection(
        ^
/usr/local/include/google/protobuf/generated_message_reflection.h:130:3: note: 
      candidate constructor not viable: requires at least 10 arguments, but 9
      were provided
  GeneratedMessageReflection(const Descriptor* descriptor,
  ^
/usr/local/include/google/protobuf/generated_message_reflection.h:166:3: note: 
      candidate constructor not viable: requires at least 12 arguments, but 9
      were provided
  GeneratedMessageReflection(const Descriptor* descriptor,
  ^
/usr/local/include/google/protobuf/generated_message_reflection.h:541:37: note: 
      candidate constructor not viable: requires 1 argument, but 9 were provided
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(GeneratedMessageReflection);
                                    ^
/usr/local/include/google/protobuf/stubs/common.h:90:3: note: expanded from
      macro 'GOOGLE_DISALLOW_EVIL_CONSTRUCTORS'
  TypeName(const TypeName&);                           \
  ^
build/src/caffe/proto/caffe.pb.cc:339:9: error: no matching constructor for
      initialization of
      '::google::protobuf::internal::GeneratedMessageReflection'
    new ::google::protobuf::internal::GeneratedMessageReflection(
        ^
/usr/local/include/google/protobuf/generated_message_reflection.h:130:3: note: 
      candidate constructor not viable: requires at least 10 arguments, but 9
      were provided
  GeneratedMessageReflection(const Descriptor* descriptor,
  ^
/usr/local/include/google/protobuf/generated_message_reflection.h:166:3: note: 
      candidate constructor not viable: requires at least 12 arguments, but 9
      were provided
  GeneratedMessageReflection(const Descriptor* descriptor,
  ^
/usr/local/include/google/protobuf/generated_message_reflection.h:541:37: note: 
      candidate constructor not viable: requires 1 argument, but 9 were provided
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(GeneratedMessageReflection);
                                    ^
/usr/local/include/google/protobuf/stubs/common.h:90:3: note: expanded from
      macro 'GOOGLE_DISALLOW_EVIL_CONSTRUCTORS'
  TypeName(const TypeName&);                           \
  ^
build/src/caffe/proto/caffe.pb.cc:354:9: error: no matching constructor for
      initialization of
      '::google::protobuf::internal::GeneratedMessageReflection'
    new ::google::protobuf::internal::GeneratedMessageReflection(
        ^
/usr/local/include/google/protobuf/generated_message_reflection.h:130:3: note: 
      candidate constructor not viable: requires at least 10 arguments, but 9
      were provided
  GeneratedMessageReflection(const Descriptor* descriptor,
  ^
/usr/local/include/google/protobuf/generated_message_reflection.h:166:3: note: 
      candidate constructor not viable: requires at least 12 arguments, but 9
      were provided
  GeneratedMessageReflection(const Descriptor* descriptor,
  ^
/usr/local/include/google/protobuf/generated_message_reflection.h:541:37: note: 
      candidate constructor not viable: requires 1 argument, but 9 were provided
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(GeneratedMessageReflection);
                                    ^
/usr/local/include/google/protobuf/stubs/common.h:90:3: note: expanded from
      macro 'GOOGLE_DISALLOW_EVIL_CONSTRUCTORS'
  TypeName(const TypeName&);                           \
  ^
build/src/caffe/proto/caffe.pb.cc:370:9: error: no matching constructor for
      initialization of
      '::google::protobuf::internal::GeneratedMessageReflection'
    new ::google::protobuf::internal::GeneratedMessageReflection(
        ^
/usr/local/include/google/protobuf/generated_message_reflection.h:130:3: note: 
      candidate constructor not viable: requires at least 10 arguments, but 9
      were provided
  GeneratedMessageReflection(const Descriptor* descriptor,
  ^
/usr/local/include/google/protobuf/generated_message_reflection.h:166:3: note: 
      candidate constructor not viable: requires at least 12 arguments, but 9
      were provided
  GeneratedMessageReflection(const Descriptor* descriptor,
  ^
/usr/local/include/google/protobuf/generated_message_reflection.h:541:37: note: 
      candidate constructor not viable: requires 1 argument, but 9 were provided
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(GeneratedMessageReflection);
                                    ^
/usr/local/include/google/protobuf/stubs/common.h:90:3: note: expanded from
      macro 'GOOGLE_DISALLOW_EVIL_CONSTRUCTORS'
  TypeName(const TypeName&);                           \
  ^
build/src/caffe/proto/caffe.pb.cc:385:9: error: no matching constructor for
      initialization of
      '::google::protobuf::internal::GeneratedMessageReflection'
    new ::google::protobuf::internal::GeneratedMessageReflection(
        ^
/usr/local/include/google/protobuf/generated_message_reflection.h:130:3: note: 
      candidate constructor not viable: requires at least 10 arguments, but 9
      were provided
  GeneratedMessageReflection(const Descriptor* descriptor,
  ^
/usr/local/include/google/protobuf/generated_message_reflection.h:166:3: note: 
      candidate constructor not viable: requires at least 12 arguments, but 9
      were provided
  GeneratedMessageReflection(const Descriptor* descriptor,
  ^
/usr/local/include/google/protobuf/generated_message_reflection.h:541:37: note: 
      candidate constructor not viable: requires 1 argument, but 9 were provided
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(GeneratedMessageReflection);
                                    ^
/usr/local/include/google/protobuf/stubs/common.h:90:3: note: expanded from
      macro 'GOOGLE_DISALLOW_EVIL_CONSTRUCTORS'
  TypeName(const TypeName&);                           \
  ^
build/src/caffe/proto/caffe.pb.cc:409:9: error: no matching constructor for
      initialization of
      '::google::protobuf::internal::GeneratedMessageReflection'
    new ::google::protobuf::internal::GeneratedMessageReflection(
        ^
/usr/local/include/google/protobuf/generated_message_reflection.h:130:3: note: 
      candidate constructor not viable: requires at least 10 arguments, but 9
      were provided
  GeneratedMessageReflection(const Descriptor* descriptor,
  ^
/usr/local/include/google/protobuf/generated_message_reflection.h:166:3: note: 
      candidate constructor not viable: requires at least 12 arguments, but 9
      were provided
  GeneratedMessageReflection(const Descriptor* descriptor,
  ^
/usr/local/include/google/protobuf/generated_message_reflection.h:541:37: note: 
      candidate constructor not viable: requires 1 argument, but 9 were provided
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(GeneratedMessageReflection);
                                    ^
/usr/local/include/google/protobuf/stubs/common.h:90:3: note: expanded from
      macro 'GOOGLE_DISALLOW_EVIL_CONSTRUCTORS'
  TypeName(const TypeName&);                           \
  ^
build/src/caffe/proto/caffe.pb.cc:424:9: error: no matching constructor for
      initialization of
      '::google::protobuf::internal::GeneratedMessageReflection'
    new ::google::protobuf::internal::GeneratedMessageReflection(
        ^
/usr/local/include/google/protobuf/generated_message_reflection.h:130:3: note: 
      candidate constructor not viable: requires at least 10 arguments, but 9
      were provided
  GeneratedMessageReflection(const Descriptor* descriptor,
  ^
/usr/local/include/google/protobuf/generated_message_reflection.h:166:3: note: 
      candidate constructor not viable: requires at least 12 arguments, but 9
      were provided
  GeneratedMessageReflection(const Descriptor* descriptor,
  ^
/usr/local/include/google/protobuf/generated_message_reflection.h:541:37: note: 
      candidate constructor not viable: requires 1 argument, but 9 were provided
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(GeneratedMessageReflection);
                                    ^
/usr/local/include/google/protobuf/stubs/common.h:90:3: note: expanded from
      macro 'GOOGLE_DISALLOW_EVIL_CONSTRUCTORS'
  TypeName(const TypeName&);                           \
  ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [build/src/caffe/proto/caffe.pb.o] Error 1
David-Laxers-MacBook-Pro:caffe davidlaxer$

**Comment by shelhamer** [comment]
You have a protobuf version mismatch. Check your `PATH` and ask installation questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) group.
