### ISSUE TITLE
draw.py draws networks from top to bottom, contrary to what proto syntax suggests

### ISSUE THREAD

**Issue by Pastafarianist** [BVLC/caffe#2377]
In `*.prototxt` files, we specify the first layers of the network as being the ones at the bottom, and the following layers as being on top of them. However, the visualization in draw.py draws networks from top to bottom instead of bottom to top.

**Comment by longjon** [comment]
Closing as this doesn't seem like an issue with Caffe. `prototxt` files are naturally written in a topological order; visualization is a separate issue. That said, `draw.py` just invokes `pydot`, so you might be able to find an option to draw in whatever direction you prefer. (In addition, Caffe _is_ in need of cleaner, easier, visualization tools...)
