### ISSUE TITLE
Unable to make matcaffe

### ISSUE THREAD

**Issue by Carix0n** [BVLC/caffe#2378]
I did:
make
make all
make pycaffe
make test
make runtest

But when trying to make matcaffe, it's a message: "make: *** no rule to make target 'matcaffe'. Stop.'
OS is Ubuntu 14.04

**Comment by rohrbach** [comment]
Please ask usage questions on [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) -- this issues tracker is primarily for Caffe development discussion. Thanks!
