### ISSUE TITLE
Titan or Tesla? float or double?

### ISSUE THREAD

**Issue by dongb5** [BVLC/caffe#2379]
I do not know whether there is any introduction of this question. If I raised a introduced question then I am sorry. But I just want to know is there any difference between using 'float' and 'double' in computation results? e.g. Do I get a better result if I use 'double' rather than 'float'? If 'double' works better, in my opinion, Tesla will be a good choice.

**Comment by dzhwinter** [comment]
No response at all, Hia hia hia...  Big brother. It's float by default. Tracing the train process will confirm that.

**Comment by rohrbach** [comment]
we always use float, it should be sufficient in most scenarios.

However, please ask usage questions on [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) -- this issues tracker is primarily for Caffe development discussion. Thanks!
