### ISSUE TITLE
Socket Data Layer

### ISSUE THREAD

**Issue by sergeyk** [BVLC/caffe#238]
Data preparation is orders of magnitude easier with high-level languages such as Python or R than with C++. `HDF5DataLayer` is a welcome interface between data preparation scripts and Caffe, but we can go even further. I propose a DataSource (see #148) that reads input on a socket. A separate process -- or processes -- which can be Python or R scripts, will be responsible for preparing data to send to the socket.

I haven't coded sockets in C++ before. The main questions are:
- Is there a good library for our type of IPC (float/double blobs)?
- If there isn't, then what's the best off-the-shelf solution? Protobuf? Capn proto? YAML Binary?

**Comment by shelhamer** [comment]
I believe @cypof has an in-progress layer that fits this purpose.

**Comment by iconica** [comment]
Yes. @cypof and I have a socket-layer and some additional data-adapters that are almost complete. We'll be doing further internal tests at Flickr this week, and are hoping to have things finished from our side and PR'ed soon. (If not this week, it'll likely get pushed until after GTC though.)

**Comment by bhack** [comment]
@cypof Do you have some news on this?

**Comment by cypof** [comment]
@bhack this was replaced by integrating with Spark instead.

**Comment by shelhamer** [comment]
Closing as this has been addressed by CaffeOnSpark among other projects, and most simply can be handled by a Python data layer + zeromq or the like.
