### ISSUE TITLE
A problem when I compile the matcaffe in VS 2012

### ISSUE THREAD

**Issue by csxqwu** [BVLC/caffe#2381]
Hi, I have downloaded this windows version of Caffe and succefuuly compiled and works well. However, I wanna use caffe in Matlab and use the project file to compile. I have changed the directory of Matlab and Cuda 6.5. When I compile it, I get the following error:
错误	1	error MSB3073: 命令“set origin_dir=Í%
cd ../../
"./scripts/GeneratePB.bat"
cd %origin_dir%
:VCEnd”已退出，代码为 1。	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V110\Microsoft.CppCommon.targets	124	5	caffe
  

Can anyone help me to check what's the problem?

Many thanks.

**Comment by rohrbach** [comment]
please ask usage questions on [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) -- this issues tracker is primarily for Caffe development discussion. Thanks!
