### ISSUE TITLE
'Net' object has no attribute 'predict'

### ISSUE THREAD

**Issue by vyokky** [BVLC/caffe#2388]
Hi, I was having some problems when following the ipython notebook examples. I got the error:

'Net' object has no attribute 'predict'

when running the following line

prediction = net.predict([input_image])

Is there any method can resolve this problem?

**Comment by vyokky** [comment]
import numpy as np
import matplotlib.pyplot as plt

caffe_root='/home/vyokky/caffe/caffe-master/'
IMAGE_FILE = 'examples/images/cat.jpg'

import sys
sys.path.insert(0, caffe_root + 'python')

import caffe



caffe.set_mode_cpu()
net = caffe.Net(caffe_root + 'data/flavia/leaves_model/0.83/feature.prototxt',
                caffe_root + 'data/flavia/leaves_model/0.83/leaves_model_iter_10000.caffemodel',
                caffe.TEST)

# input preprocessing: 'data' is the name of the input blob == net.inputs[0]
transformer = caffe.io.Transformer({'data': net.blobs['data'].data.shape})
transformer.set_transpose('data', (2,0,1))
#transformer.set_mean('data', np.load(caffe_root + 'python/caffe/imagenet/ilsvrc_2012_mean.npy').mean(1).mean(1)) # mean pixel
transformer.set_raw_scale('data', 255)  # the reference model operates on images in [0,255] range instead of [0,1]
transformer.set_channel_swap('data', (2,1,0))  # the reference model has channels in BGR order instead of RGB


input_image = caffe.io.load_image(caffe_root +IMAGE_FILE)
plt.imshow(input_image)
#plt.show()
prediction = net.predict([input_image])  # predict takes any number of images, and formats them for the Caffe net automatically
print 'prediction shape:', prediction[0].shape
plt.plot(prediction[0])
print 'predicted class:', prediction[0].argmax()

Here is the full code

**Comment by rohrbach** [comment]
Where is the ipython example from?
It might be that this ipython example has to be updated.

However, please ask usage questions on [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) -- this issues tracker is primarily for Caffe development discussion. Thanks!
