### ISSUE TITLE
Caffe installation crashes with GPU

### ISSUE THREAD

**Issue by Rachnog** [BVLC/caffe#2392]
Hi, guys,
I tried to build Caffe with USE_CUDNN := 1 (of course, I've downloaded CUDNN V2 and added cudnn.h to path usr/local/cuda/include). And this is what I get while installation:

alex@alex-GE60-2PE:~/Desktop/caffe$ make all
PROTOC src/caffe/proto/caffe.proto
CXX .build_debug/src/caffe/proto/caffe.pb.cc
CXX src/caffe/layers/hdf5_output_layer.cpp
CXX src/caffe/layers/tanh_layer.cpp
CXX src/caffe/layers/sigmoid_cross_entropy_loss_layer.cpp
CXX src/caffe/layers/cudnn_relu_layer.cpp
CXX src/caffe/layers/euclidean_loss_layer.cpp
CXX src/caffe/layers/contrastive_loss_layer.cpp
CXX src/caffe/layers/base_data_layer.cpp
CXX src/caffe/layers/flatten_layer.cpp
CXX src/caffe/layers/lrn_layer.cpp
CXX src/caffe/layers/cudnn_softmax_layer.cpp
CXX src/caffe/layers/neuron_layer.cpp
CXX src/caffe/layers/exp_layer.cpp
CXX src/caffe/layers/cudnn_sigmoid_layer.cpp
CXX src/caffe/layers/mvn_layer.cpp
CXX src/caffe/layers/hinge_loss_layer.cpp
CXX src/caffe/layers/absval_layer.cpp
CXX src/caffe/layers/cudnn_tanh_layer.cpp
CXX src/caffe/layers/slice_layer.cpp
CXX src/caffe/layers/eltwise_layer.cpp
CXX src/caffe/layers/threshold_layer.cpp
CXX src/caffe/layers/power_layer.cpp
CXX src/caffe/layers/softmax_layer.cpp
CXX src/caffe/layers/concat_layer.cpp
CXX src/caffe/layers/window_data_layer.cpp
CXX src/caffe/layers/cudnn_conv_layer.cpp
CXX src/caffe/layers/argmax_layer.cpp
CXX src/caffe/layers/memory_data_layer.cpp
CXX src/caffe/layers/bnll_layer.cpp
CXX src/caffe/layers/image_data_layer.cpp
CXX src/caffe/layers/sigmoid_layer.cpp
CXX src/caffe/layers/pooling_layer.cpp
CXX src/caffe/layers/loss_layer.cpp
CXX src/caffe/layers/silence_layer.cpp
CXX src/caffe/layers/deconv_layer.cpp
CXX src/caffe/layers/data_layer.cpp
CXX src/caffe/layers/dummy_data_layer.cpp
CXX src/caffe/layers/hdf5_data_layer.cpp
CXX src/caffe/layers/im2col_layer.cpp
CXX src/caffe/layers/base_conv_layer.cpp
CXX src/caffe/layers/relu_layer.cpp
CXX src/caffe/layers/inner_product_layer.cpp
CXX src/caffe/layers/infogain_loss_layer.cpp
CXX src/caffe/layers/split_layer.cpp
CXX src/caffe/layers/cudnn_pooling_layer.cpp
CXX src/caffe/layers/multinomial_logistic_loss_layer.cpp
CXX src/caffe/layers/conv_layer.cpp
CXX src/caffe/layers/accuracy_layer.cpp
CXX src/caffe/layers/softmax_loss_layer.cpp
CXX src/caffe/layers/dropout_layer.cpp
CXX src/caffe/layers/prelu_layer.cpp
CXX src/caffe/syncedmem.cpp
CXX src/caffe/solver.cpp
CXX src/caffe/net.cpp
CXX src/caffe/internal_thread.cpp
CXX src/caffe/layer_factory.cpp
CXX src/caffe/util/insert_splits.cpp
CXX src/caffe/util/db.cpp
CXX src/caffe/util/math_functions.cpp
CXX src/caffe/util/upgrade_proto.cpp
CXX src/caffe/util/io.cpp
CXX src/caffe/util/cudnn.cpp
CXX src/caffe/util/im2col.cpp
CXX src/caffe/util/benchmark.cpp
CXX src/caffe/common.cpp
CXX src/caffe/data_transformer.cpp
CXX src/caffe/blob.cpp
NVCC src/caffe/layers/euclidean_loss_layer.cu
NVCC src/caffe/layers/absval_layer.cu
NVCC src/caffe/layers/concat_layer.cu
NVCC src/caffe/layers/tanh_layer.cu
NVCC src/caffe/layers/cudnn_sigmoid_layer.cu
NVCC src/caffe/layers/relu_layer.cu
NVCC src/caffe/layers/softmax_loss_layer.cu
NVCC src/caffe/layers/cudnn_relu_layer.cu
NVCC src/caffe/layers/conv_layer.cu
NVCC src/caffe/layers/deconv_layer.cu
NVCC src/caffe/layers/lrn_layer.cu
NVCC src/caffe/layers/cudnn_softmax_layer.cu
NVCC src/caffe/layers/sigmoid_layer.cu
NVCC src/caffe/layers/slice_layer.cu
NVCC src/caffe/layers/softmax_layer.cu
NVCC src/caffe/layers/mvn_layer.cu
NVCC src/caffe/layers/im2col_layer.cu
NVCC src/caffe/layers/split_layer.cu
NVCC src/caffe/layers/inner_product_layer.cu
NVCC src/caffe/layers/prelu_layer.cu
NVCC src/caffe/layers/threshold_layer.cu
NVCC src/caffe/layers/hdf5_output_layer.cu
NVCC src/caffe/layers/cudnn_pooling_layer.cu
NVCC src/caffe/layers/eltwise_layer.cu
NVCC src/caffe/layers/cudnn_tanh_layer.cu
NVCC src/caffe/layers/power_layer.cu
NVCC src/caffe/layers/pooling_layer.cu
NVCC src/caffe/layers/silence_layer.cu
NVCC src/caffe/layers/cudnn_conv_layer.cu
NVCC src/caffe/layers/bnll_layer.cu
NVCC src/caffe/layers/sigmoid_cross_entropy_loss_layer.cu
NVCC src/caffe/layers/exp_layer.cu
NVCC src/caffe/layers/base_data_layer.cu
NVCC src/caffe/layers/dropout_layer.cu
NVCC src/caffe/layers/hdf5_data_layer.cu
NVCC src/caffe/layers/contrastive_loss_layer.cu
NVCC src/caffe/util/math_functions.cu
NVCC src/caffe/util/im2col.cu
AR -o .build_debug/lib/libcaffe.a
LD -o .build_debug/lib/libcaffe.so
/usr/bin/ld: cannot find -lcudnn
collect2: error: ld returned 1 exit status
make: *** [.build_debug/lib/libcaffe.so] Error 1

I'm new to Linux and Caffe and can't understand, what is this trouble about.
Thank you for any help or hints.

**Comment by shelhamer** [comment]
Please ask install questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) group. You need to install not only `cudnn.h` but dynamic library `so` too.

**Comment by linuxthink** [comment]
Try adding a symbolic link `libcudnn.so` pointing to its specific version in the same directory. For my case:

    sudo ln -s libcudnn.so.7.0.64 libcudnn.so

See: https://groups.google.com/forum/#!topic/caffe-users/QJ7L8c4Tn7c
