### ISSUE TITLE
Error Building Caffe on OS X Yosemite 10.10.3

### ISSUE THREAD

**Issue by dbl001** [BVLC/caffe#2403]
Hi,

I'm getting the following error building Caffe:
...

src/caffe/util/math_functions.cu(140): error: calling a __host__ function("std::signbit<float> ") from a __global__ function("caffe::sgnbit_kernel<float> ") is not allowed

src/caffe/util/math_functions.cu(140): error: calling a __host__ function("std::signbit<double> ") from a __global__ function("caffe::sgnbit_kernel<double> ") is not allowed

2 errors detected in the compilation of "/var/folders/nj/nphdkhyj6s1dttb0pd9zb2wc0000gn/T//tmpxft_0000c8a4_00000000-12_math_functions.compute_35.cpp1.ii".
make: *** [build/src/caffe/util/math_functions.cuo] Error 2

I discovered that others have had this problem, but their recommended fix didn't resolve my build errors.

vi +140 src/caffe/util/math_functions.cu

Original code:
DEFINE_AND_INSTANTIATE_GPU_UNARY_FUNC(sgnbit, y[index] = signbit(x[index]));
proposed change:
DEFINE_AND_INSTANTIATE_GPU_UNARY_FUNC(sgnbit, y[index] = std::signbit(x[index]));

Any ideas?

Thanks in advance.

**Comment by rohrbach** [comment]
Please ask usage questions on [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) -- this issues tracker is primarily for Caffe development discussion. Thanks!
