### ISSUE TITLE
Conversion of stacked images to lmdb

### ISSUE THREAD

**Issue by aravindsrinivas** [BVLC/caffe#2405]
I am trying to do some work on Deep Learning for Atari Games, where they consider the input to the Deep Network as a leveldb/lmdb entity with 4 stacked images together.  

I would like to know, how the stacking is done, because, I think having one mdb entity per input is better, than having to accept 4 mdb entities for every single input. Basically, I have several 160*210 images, with me now. I want to stack them in a particular way, such that, my final inputs are of the form 84*84*4, and I want to know how I can stack 4 images, to one mdb entity. 

Also, I would like to know, if reshaping while running the code in caffe, or before converting to lmdb itself, which one would be more preferable?

Thanks.

**Comment by rohrbach** [comment]
We welcome you to look at the extensive documentation, tutorials, and examples at http://caffe.berkeleyvision.org/ 
However, please ask usage questions on [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) -- this issues tracker is primarily for Caffe development discussion. Thanks!
