### ISSUE TITLE
Accuracy averaging in solver.

### ISSUE THREAD

**Issue by MarkWissler** [BVLC/caffe#2409]
Accuracy is reported as the mean of batch accuracies. This will not work for all accuracy metrics. 

Without giving irrelevant details, I wrote an accuracy layer, but the metric needs to be computed on all batches as a whole, not per-batch.

**Comment by waylonflinn** [comment]
Here's the relevant line in solver.cpp:
https://github.com/BVLC/caffe/blob/master/src/caffe/solver.cpp#L310

Have others run into this issue or have any thoughts on architecture changes to facilitate this sort of thing?

**Comment by longjon** [comment]
Closing as this doesn't seem like an issue with Caffe. It's certainly true that you can't write a layer whose output is a function of multiple batches of input; that would violate the batched nature of the computation. It's possible to imagine extensions to Caffe that would support that, but it's generally easier to write code (e.g., evaluation code) that calls Caffe in a loop and then computes whatever is desired. Feel free to discuss this and other usage issues further on [caffe-users](https://groups.google.com/forum/#!forum/caffe-users).
