### ISSUE TITLE
hdf5: command not found

### ISSUE THREAD

**Issue by RafaRuiz** [BVLC/caffe#2412]
Hello, it's been 3 days trying to make Caffe run but this is a stupid question. I've got many errors on training and it's maybe because I didn't follow the right install instructions. I'm using OSx and in the installation there is:

![image](https://cloud.githubusercontent.com/assets/6842786/7456940/727cb732-f280-11e4-8c17-36ceebd61a40.png)

but when I type `hdf5 opencv` I get: "hdf5: command not found"

I have installed hdf5 through `brew` and `MacPorts` but still saying "command not found".

Does anyone have a clue?
Thank you.

**Comment by rohrbach** [comment]
you also have to do 
brew install hdf5 opencv

we will try to make this more clear.

**Comment by RafaRuiz** [comment]
It's already installed. I've installed by `Homebrew`, `MacPorts` and from source (http://stackoverflow.com/questions/30035581/installing-caffe-deep-learning-issues) but I don't have a binary called "hdf5", so the error is:

> MacBook-Pro-de-Rafael:hdf5-1.8.14 rafaelruizmunoz$ hdf5 opencv
> -bash: hdf5: command not found

**Comment by RafaRuiz** [comment]
These are my binaries:

![image](https://cloud.githubusercontent.com/assets/6842786/7460934/85779b54-f29e-11e4-98db-7e84917451bf.png)

**Comment by rohrbach** [comment]
oh, what I mean "hdf5 opencv" is not a command, it tells you what to install.

However, please ask usage questions on [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) -- this issues tracker is primarily for Caffe development discussion. Thanks!

**Comment by longjon** [comment]
The documentation issue is fixed in the GitHub but not yet live on the web; it should appear soon.
