### ISSUE TITLE
Maxout issue

### ISSUE THREAD

**Issue by vglazkov** [BVLC/caffe#2419]
Hi!

I implemented a classic CNN architecture based on MNIST example. I replaced relu activation function by maxout with the following sequence inner_product -> slice -> eltwise(max). Everything worked fine, until i started to reduce size of inner_product layer. When i significantly reduce size of inner_product layer (in my case before i have 500 neurones and after  i have 128 neurones) my CNN after 2000 iterations of learning started to gave me always the same big value of loss function. Why is this happening? By the way, i have the same problem if i place after maxout layer a dropout layer.

**Comment by longjon** [comment]
Please ask usage and modeling questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) list. Thanks!
