### ISSUE TITLE
Make runtest error with caffe-master

### ISSUE THREAD

**Issue by acpn** [BVLC/caffe#2420]
Hy guys I'm install caffe, but when I run make runtest I got this error:

```
[  FAILED  ] 1 test, listed below:
[  FAILED  ] BenchmarkTest/3.TestTimerMilliSeconds, where TypeParam = caffe::DoubleGPU

 1 FAILED TEST
  YOU HAVE 2 DISABLED TESTS

*** Aborted at 1430843491 (unix time) try "date -d @1430843491" if you are using GNU date ***
PC: @     0x7f11a3b6b150 __lll_unlock_elision
*** SIGSEGV (@0x0) received by PID 13414 (TID 0x7f11ae316980) from PID 0; stack trace: ***
    @     0x7f11a3b69740 (unknown)
    @     0x7f11a3b6b150 __lll_unlock_elision
    @     0x7f119141e12c (unknown)
    @     0x7f11913b08c2 (unknown)
```

any idea?

Thanks.

**Comment by longjon** [comment]
Segfaults shouldn't happen, could be an upstream issue though.

Does this happen every time? (Can you reproduce it?) Do any other tests fail? What's your distro/hardware?

**Comment by acpn** [comment]
I realized that this does not seem to be caffe error, there seems to be some conflict between the nvidia driver and the cuda, not sure what is, I'll reinstall caffe and nvidia drivers to see the result. I report later.

Thanks Longjon

**Comment by xinkang** [comment]
Any one solved this problem?  Thanks!

**Comment by acpn** [comment]
I reinstall caffe with cuda 6.5 and everithing it's fine now. I'm using nvidia GTX  770.
