### ISSUE TITLE
varying input shape feature

### ISSUE THREAD

**Issue by adhamghazali** [BVLC/caffe#2421]
Does caffe support varying input shape? I see no reason why this wouldn't be a feature in caffe since the snapshotted model is only the trained kernels and the dimension of the activation/s is allocated at run-time.

**Comment by flx42** [comment]
Sure it can, using the C++ API you can do something like that:
```
input_layer->Reshape(N, 3, 256, 256);
net->Reshape(); /* to forward the dimension change */
```

**Comment by longjon** [comment]
Right. In the future, please ask usage questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) list. Thanks!
