### ISSUE TITLE
what  does  the  norm  layer  mean  ?

### ISSUE THREAD

**Issue by wzq12138** [BVLC/caffe#2423]
layer {
  name: "norm1"
  type: "LRN"
  bottom: "pool1"
  top: "norm1"
  lrn_param {
    local_size: 5
    alpha: 0.0001
    beta: 0.75
  }
}

**Comment by jshfeng** [comment]
Hi, the norm layer is for response normalization, and in particular, LRN represents Local Response Normalization.
See the documentation here: http://caffe.berkeleyvision.org/tutorial/layers.html

**Comment by mrgloom** [comment]
Some more info:
http://stats.stackexchange.com/questions/145768/importance-of-local-response-normalization-in-cnn
