### ISSUE TITLE
How to fine-tuning CaffeNet with a saliency map ?

### ISSUE THREAD

**Issue by xavigiro** [BVLC/caffe#2428]
Dear Caffe community,

we would like to fine-tune CaffeNet with a saliency map (eg. a gray-scale image indicating the human fixation points in an image). We have seen the works of fully connected networks based on multi-label classification, but it is not clear for us how to adapt it to our case.

Do you have any hint how to do it with Caffe ?

Thanks in advance,

Xavi

**Comment by longjon** [comment]
Please ask usage and modeling questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) list. Thanks!
