### ISSUE TITLE
run mnist in examples failed  

### ISSUE THREAD

**Issue by donalwilson** [BVLC/caffe#2431]
I'm using Ubuntu 14.04.2, and all make are passed. but when I testing caffe on mnist in examples. An error occurs: 
F0508 11:00:05.430325  8582 db.hpp:109] Check failed: mdb_status == 0 (2 vs. 0) No such file or directory
*** Check failure stack trace: ***
    @     0x7fa547ada9fd  google::LogMessage::Fail()
    @     0x7fa547adc89d  google::LogMessage::SendToLog()
    @     0x7fa547ada5ec  google::LogMessage::Flush()
    @     0x7fa547add1be  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fa547ecebe1  caffe::db::LMDB::Open()
    @     0x7fa547ec3df4  caffe::DataLayer<>::DataLayerSetUp()
    @     0x7fa547ec85ba  caffe::BaseDataLayer<>::LayerSetUp()
    @     0x7fa547ec8739  caffe::BasePrefetchingDataLayer<>::LayerSetUp()
    @     0x7fa547f1bdf1  caffe::Net<>::Init()
    @     0x7fa547f1e2b2  caffe::Net<>::Net()
    @     0x7fa547efdc35  caffe::Solver<>::InitTrainNet()
    @     0x7fa547efe157  caffe::Solver<>::Init()
    @     0x7fa547efe545  caffe::Solver<>::Solver()
    @           0x40d636  caffe::SGDSolver<>::SGDSolver()
    @           0x40d8f8  caffe::GetSolver<>()
    @           0x407223  train()
    @           0x4052d8  main
    @     0x7fa547211ec5  (unknown)
    @           0x4056b2  (unknown)
Aborted (core dumped)

**Comment by longjon** [comment]
Please ask usage questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) list. Thanks!

**Comment by sunshineatnoon** [comment]
Did you solve this bug? I have the same one.

**Comment by jomof** [comment]
I see the same

**Comment by atique81** [comment]
me too

**Comment by moazamijaz** [comment]
i see the same
