### ISSUE TITLE
Does Caffe support HDF5 sub-groups?

### ISSUE THREAD

**Issue by NerdPollution** [BVLC/caffe#2434]
I am new to using caffe and I am having trouble loading in a HDF5. My old HDF5 did not have sub-groups in it, so it it just consisted of a data section and a label section. My current HDF5 that I have has the following structure:

h5ls examples/eeg/test.hdf5 
rec_00                   Group
rec_01                   Group

h5ls examples/eeg/chb01.hdf5/rec_00
data                     Dataset {921600, 23}
labels                   Dataset {921600}

So, its consist of two sub-groups. When I attempt to run my code, I receive the following error below. Is there a way in caffe to deal with sub-groups?

F0509 15:02:00.213076 1933718272 io.cpp:237] Check failed: H5LTfind_dataset(file_id, dataset_name_) Failed to find HDF5 dataset data
**\* Check failure stack trace: ***
    @        0x10a3c276a  google::LogMessage::Fail()
    @        0x10a3c1f14  google::LogMessage::SendToLog()
    @        0x10a3c23c7  google::LogMessage::Flush()
    @        0x10a3c5679  google::LogMessageFatal::~LogMessageFatal()
    @        0x10a3c2a4f  google::LogMessageFatal::~LogMessageFatal()
    @        0x10570581c  caffe::hdf5_load_nd_dataset_helper<>()
    @        0x105704e2b  caffe::hdf5_load_nd_dataset<>()
    @        0x10569bde0  caffe::HDF5DataLayer<>::LoadHDF5FileData()
    @        0x10569b1ac  caffe::HDF5DataLayer<>::LayerSetUp()
    @        0x1056da774  caffe::Net<>::Init()
    @        0x1056d9717  caffe::Net<>::Net()
    @        0x1056ec9ce  caffe::Solver<>::InitTrainNet()
    @        0x1056ec3ec  caffe::Solver<>::Init()
    @        0x1056ec23d  caffe::Solver<>::Solver()
    @        0x1055f8c62  caffe::SGDSolver<>::SGDSolver()
    @        0x1055f6b85  caffe::GetSolver<>()
    @        0x1055f4438  train()
    @        0x1055f671f  main
    @     0x7fff89a655c9  start
    @                0x3  (unknown)

**Comment by sudeepgaddam** [comment]
Even I face same issue.

**Comment by lukeyeager** [comment]
I think you're SOL. h5py lets you do this:
```python
h5py.File('train.h5')['group/data'].shape
```
So I thought you might be able to simply change the `tops` in the HDF5Data layer like this:
```
layer {
  name: "data"
  type: "HDF5Data"
  top: "group/data"
  top: "group/label"
  include {
    phase: TRAIN
  }
}
```
But that didn't work. Apparently [H5LTfind_dataset](https://www.hdfgroup.org/HDF5/doc/HL/RM_H5LT.html#H5LTfind_dataset) doesn't allow that kind of implicit grouping.
