### ISSUE TITLE
How to calculate Euclidean distance only without back propagation

### ISSUE THREAD

**Issue by leiucky** [BVLC/caffe#2438]
I have two vectors, and I want to calculate the Euclidean distance of them.
I know there is a layer called EuclideanLossLayer, however, I don't want to perform back propagation  here.  Because it is not a loss layer. Moreover, EuclideanLossLayer only outputs a 1*1*1*1 blob instead of N*1*1*1 blob. I want to calculate Euclidean distance for each batch.

BTW, EuclideanLossLayer will always perform back propagation and fine tune the parameters, right?

What should do?

I have used ELTWISELayer and PowerLayer to calculate the square value of each element (is the code below right?), now the problem is how to sum all elements of a vector.

layers {
                name: "diff"
                type: ELTWISE
                bottom: "vec1"
                bottom: "vec2"
                top: "diff"
                eltwise_param{
                operation: SUM
                coeff: 1
                coeff: -1
               }
}
layers {
                name: "square"
                type: POWER
                bottom: "diff"
                top: "square"
                power_param{
                    power: 2
                }
}

 Similar to the 64 pages in the tutorial  https://docs.google.com/presentation/d/1UeKXVgRvvxg9OUdh_UiC5G71UMscNPlvArsWER41PsU/edit#slide=id.g39a0d7271_022

**Comment by leiucky** [comment]
Could anybody help me? Thanks~

**Comment by longjon** [comment]
Please ask usage questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) list. Thanks!
