### ISSUE TITLE
How to use pretrained model in C++,say cifar?

### ISSUE THREAD

**Issue by wait1988** [BVLC/caffe#2445]
Hello,I'am currently studying Caffe.I trained  a model named cifar10_full_iter_70000.caffemodel following the tutorial.When I test it in C++,however,the result is weird.The prob I got is all "1.#QNAN".My test code is:
void main(int argc, char** argv)
{
	Caffe::set_phase(Caffe::TEST);
	Caffe::set_mode(Caffe::CPU);
	Net<float> caffe_Net("../../examples/cplusplus/cifar10/cifar10_quick.prototxt");//load caffe net 
	caffe_Net.CopyTrainedLayersFrom("../../examples/cplusplus/cifar10/cifar10_quick_iter_4000.caffemodel");//Load pretrained model

	//read image data and translate it to Dtype type 
	cv::Mat img = cv::imread("../../examples/cplusplus/cifar10/boat.jpg");
	cv::Mat img_resize;
	int height = 32;
	int width = 32;
	cv::resize(img, img_resize, cv::Size(width, height));
	int channels = 3;
	caffe::Blob<float> *blob = new caffe::Blob<float>(1, channels, height, width);
	/*
	The conventional blob dimensions for data are number N x channel K x height H x width W. 
	Blob memory is row-major in layout so the last / rightmost dimension changes fastest. 
	For example, the value at index (n, k, h, w) is physically located at index ((n * K + k) * H + h) * W + w.
	*/
	for (int c = 0; c < channels; c++)//channels 
	for (int h = 0; h < height; h++)//height
		for (int w = 0; w < width; w++)//width
			blob->mutable_cpu_data()[blob->offset(0, c, h, w)] = img_resize.at<cv::Vec3d>(h, w)[c];
	//create input and output vectors for the Forward call 
	vector<caffe::Blob<float>*> bottom_vecs;//network input
	vector<caffe::Blob<float>*> result;//network output
	bottom_vecs.push_back(blob);
	float loss;
	result = caffe_Net.Forward(bottom_vecs, &loss);
	int idx = 0;
	for (int j = 0; j < result.size(); ++j) {
		const float* result_vec = result[j]->cpu_data();
		for (int k = 0; k < result[j]->count(); ++k, ++idx) {
			const float score = result_vec[k];
			const std::string& output_name = caffe_Net.blob_names()[
				caffe_Net.output_blob_indices()[j]];
			LOG(INFO) << output_name << " = " << score;
		}
	}
	getchar();
}
 I really don't know what's going on,who can help me out?Thanks.

**Comment by longjon** [comment]
Please ask usage questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) list. Thanks!
