### ISSUE TITLE
How to solve make runtest failed?

### ISSUE THREAD

**Issue by b2220333** [BVLC/caffe#2447]
I run make runtest,it shows 12 errors:

[  PASSED  ] 599 tests.
[  FAILED  ] 12 tests, listed below:
[  FAILED  ] IOTest.TestDecodeDatumToCVMatContentNative
[  FAILED  ] IOTest.TestDecodeDatum
[  FAILED  ] IOTest.TestDecodeDatumNative
[  FAILED  ] IOTest.TestDecodeDatumToCVMatContent
[  FAILED  ] IOTest.TestDecodeDatumToCVMat
[  FAILED  ] IOTest.TestDecodeDatumToCVMatNativeGray
[  FAILED  ] IOTest.TestDecodeDatumNativeGray
[  FAILED  ] IOTest.TestDecodeDatumToCVMatNative
[  FAILED  ] MemoryDataLayerTest/0.AddMatVectorDefaultTransform, where TypeParam = caffe::FloatCPU
[  FAILED  ] MemoryDataLayerTest/0.TestSetBatchSize, where TypeParam = caffe::FloatCPU
[  FAILED  ] MemoryDataLayerTest/1.TestSetBatchSize, where TypeParam = caffe::DoubleCPU
[  FAILED  ] MemoryDataLayerTest/1.AddMatVectorDefaultTransform, where TypeParam = caffe::DoubleCPU

12 FAILED TESTS

How to solve them?
Thank you~

**Comment by n-zhang** [comment]
Please ask usage questions on the caffe-users list. Thanks!
