### ISSUE TITLE
HDF5 on ubuntu is not found

### ISSUE THREAD

**Issue by lababidi** [BVLC/caffe#2449]
doing a ```sudo apt-get install libhdf5-dev libhdf5-8``` does not solve the dependency on hdf5. I had to download the tarball and manually copy the resulting compiled files from a ```make; make install``` into ```/usr/include``` and ```/usr/lib``` in order for caffe to compile.

**Comment by n-zhang** [comment]
Please ask usage questions on the caffe-users list. Thanks!

**Comment by lababidi** [comment]
This is not a question. This is a bug. Open this issue back up and read it carefully @n-zhang

**Comment by lababidi** [comment]
@pluskid @sergeyk  @rodrigob @arntanguy
