### ISSUE TITLE
How to compile Caffe on Raspberry Pi 1

### ISSUE THREAD

**Issue by treepop** [BVLC/caffe#2452]
I have compiled Caffe on ubuntu linux successfully. I used the same command compile Caffe on Raspberry Pi 1. Compilation was complete but when run the error has occur.

While compile, the compiler said "/tmp/ccNdOkhZ.s:18512: Warning: swp{b} use is deprecated for ARMv6 and ARMv7" a lot.

$ build/tools/caffe
Illegal instruction

In file Makefile.config
I set the follows
CPU_ONLY := 1
CUSTOM_CXX := g++-4.6

**Comment by GeorgiAngelov** [comment]
I would like to know if anybody else has done it.

**Comment by chwangaa** [comment]
Very curious as well

**Comment by wiemrachman** [comment]
could you read
https://scientistnobee.wordpress.com/2014/06/20/machine-learning-with-raspberry-pi/
sudo nano /boot/config.txt
gpu_mem=128

**Comment by seanbell** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

**Comment by 3073** [comment]
@wiemrachman:  does this link show installation of caffe on raspberry pi? you mentioned it !!
https://scientistnobee.wordpress.com/2014/06/20/machine-learning-with-raspberry-pi/
