### ISSUE TITLE
osx running error

### ISSUE THREAD

**Issue by ai2010** [BVLC/caffe#2453]
I got this error running a python script that imports caffe

Traceback (most recent call last):
  File "cnntest.py", line 1, in <module>
    import caffe
  File "/Users/andrea/caffe/python/caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver
  File "/Users/andrea/caffe/python/caffe/pycaffe.py", line 13, in <module>
    from ._caffe import Net, SGDSolver
ImportError: dlopen(/Users/andrea/caffe/python/caffe/_caffe.so, 2): Library not loaded: /usr/local/lib/libIlmImf-Imf_2_1.21.dylib
  Referenced from: /usr/local/lib/libopencv_highgui.2.4.dylib
  Reason: image not found

It seems that the opencv library has a problem with links of the dependencies.
Any idea?
(I am using the anaconda version and OSX Yosemite)

**Comment by ai2010** [comment]
Update:
I just found out that the problem is with anaconda python that does not have opencv installed:
andreas-MacBook-Pro:lib andrea$ python
Python 2.7.9 |Anaconda 2.2.0 (x86_64)| (default, Dec 15 2014, 10:37:34)
[GCC 4.2.1 (Apple Inc. build 5577)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://binstar.org
>>> import cv
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/cv.py", line 1, in <module>
    from cv2.cv import *
ImportError: dlopen(/usr/local/lib/python2.7/site-packages/cv2.so, 2): Library not loaded: /usr/local/lib/libImath-2_1.11.dylib
  Referenced from: /usr/local/Cellar/opencv/2.4.10.1/lib/libopencv_highgui.2.4.dylib
  Reason: image not found


Do you have an idea how to install opencv in anaconda python?

**Comment by ai2010** [comment]
update:
I did manage to import opencv on the python interpreter through the export:
export PYTHONPATH=/Users/andrea/anaconda/lib/python2.7/site-packages/:$HOME/anaconda/lib::/Users/andrea/caffe/python/:/Users/andrea/caffe/

however the problem is now as many posts (as #2307) building caffe:
andreas-MacBook-Pro:build andrea$make all -j2
[ 81%] Building CXX object src/caffe/CMakeFiles/caffe.dir/util/upgrade_proto.cpp.o
Linking CXX shared library ../../lib/libcaffe.dylib
Undefined symbols for architecture x86_64:
  "cv::imread(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int)", referenced from:
      caffe::WindowDataLayer<float>::InternalThreadEntry() in window_data_layer.cpp.o
      caffe::WindowDataLayer<double>::InternalThreadEntry() in window_data_layer.cpp.o
      caffe::ReadImageToCVMat(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, int, bool) in io.cpp.o
  "cv::imencode(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, cv::_InputArray const&, std::__1::vector<unsigned char, std::__1::allocator<unsigned char> >&, std::__1::vector<int, std::__1::allocator<int> > const&)", referenced from:
      caffe::ReadImageToDatum(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, int, int, bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, caffe::Datum*) in io.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [lib/libcaffe.dylib] Error 1
make[1]: *** [src/caffe/CMakeFiles/caffe.dir/all] Error 2
make: *** [all] Error 2

**Comment by longjon** [comment]
Closing, since this does not sound like an issue with Caffe. Please discuss usage and installation on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) list. Thanks!
