### ISSUE TITLE
Compilation error when using caffe on Ubuntu 14.04

### ISSUE THREAD

**Issue by MdAsifKhan** [BVLC/caffe#2455]
I am trying to install and build Caffe along with its dependencies. After going through all the prerequisite when I run 'make all' I get this:
CXX src/caffe/net.cpp
In file included from src/caffe/net.cpp:8:0:
./include/caffe/common.hpp:5:27: fatal error: gflags/gflags.h: No such file or directory
 #include <gflags/gflags.h>
                           ^
compilation terminated.
make: *** [.build_release/src/caffe/net.o] Error 1

Please help in resolving it.

**Comment by longjon** [comment]
Please ask usage and installation questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) list. Thanks!
