### ISSUE TITLE
Chnage input data to MemoryDataLayer for *.prototxt

### ISSUE THREAD

**Issue by tzutalin** [BVLC/caffe#2459]
Hello all,
  I am going to change places205CNN_deploy.prototxt to MemoryDataLayer as input.
I try to replace the top of texts with MemoryData, but it fails. The error message will show as runtime:

E0514 19:02:40.481307  1898 upgrade_proto.cpp:591] Attempting to upgrade input file specified using deprecated V0LayerParameter: /home/darrenl/places205CNN_deploy_mobile.prototxt
F0514 19:02:40.481416  1898 upgrade_proto.cpp:82] Unknown blob input data to layer 0

Do someone know the reason?? Thanks in advance.

Original:
name: "Places205-CNN"
input: "data"
input_dim: 10
input_dim: 3
input_dim: 227
input_dim: 227
layers {
  layer {
    name: "conv1"
    type: "conv"
    num_output: 96
    kernelsize: 11
    stride: 4
    weight_filler {
      type: "gaussian"
      std: 0.01
    }
    bias_filler {
      type: "constant"
      value: 0.
    }
    blobs_lr: 1.
    blobs_lr: 2.
    weight_decay: 1.
    weight_decay: 0.
  }
  bottom: "data"
  top: "conv1"
}
layers {
  ......
}

-------
After
name: "Places205-CNN"
layer {
  name: "data"
  type: "MemoryData"
  top: "data"
  top: "label"
  memory_data_param {
    batch_size: 1
    channels: 3
    height: 227
    width: 227
  }
  transform_param {
    crop_size: 227
    mean_value: 104
    mean_value: 117
    mean_value: 123
    mirror: false
  }
}
layers {
....

**Comment by longjon** [comment]
Please ask usage questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) list. Thanks!
