### ISSUE TITLE
MemoryData issue

### ISSUE THREAD

**Issue by WenchenLi** [BVLC/caffe#2460]
Hi, recently I upgrade caffe to the newest version for the project I build from the last year, when I try to rerun the code it goes like this:

W0514 10:37:11.844255  4219 memory_data_layer.cpp:120] MemoryData does not transform array data on Reset()
Segmentation fault (core dumped)

and my own implementation leads to this problem is:

template <typename Dtype>
void MemoryDataLayer<Dtype>::AddImagesAndLabels(
    const vector<cv::Mat>& images, const vector<int>& labels,
    const bool is_color_images) {
  CHECK(!has_new_data_) <<
      "There are pending images that haven't been consumed";
  size_t num_images = images.size();
  CHECK_GT(num_images, 0) << "There is no image to add";
  CHECK_EQ(num_images, batch_size_) <<
      "The number of added images must be equal to the batch size";
  CHECK_EQ(num_images, labels.size()) <<
      "The number of images must be equal to the number of labels";

  Datum datum;
  Dtype* top_data = added_data_.mutable_cpu_data();
  Dtype* top_label = added_label_.mutable_cpu_data();
  for (int batch_item_id = 0; batch_item_id < num_images; ++batch_item_id) {
    OpenCVImageToDatum(
        images[batch_item_id], labels[batch_item_id], this->height_,
        this->width_, &datum);

    // Apply data transformations (mirror, scale, crop...)
    //this->data_transformer_.Transform(batch_item_id, datum, this->mean_,
      //                                top_data);
	  this->data_transformer_->Transform( datum,&added_data_);
                                      
    top_label[batch_item_id] = labels[batch_item_id];
  }
  // num_images == batch_size_
  Reset(top_data, top_label, batch_size_);
  has_new_data_ = true;
}

Can anyone help me with this issue? Thanks!

**Comment by longjon** [comment]
Please ask usage questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) list. Thanks!
