### ISSUE TITLE
Linking problems (C++) with functions from caffe::Net< Dtype >

### ISSUE THREAD

**Issue by mcmachado** [BVLC/caffe#2461]
Hi,

I'm trying to use Caffe's C++ interface. To do this I started to implement a simple code but I got stuck when trying to use functions of the class caffe::Net< Dtype >. More specifically, if I am trying to use blob_by_name or layer_by_name I get the following error:

    Undefined symbols for architecture x86_64:
      "caffe::Net<float>::blob_by_name(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const", referenced from:
          _main in main-b22fb1.o
      "caffe::Net<float>::layer_by_name(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const", referenced from:
          _main in main-b22fb1.o
    ld: symbol(s) not found for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    make: *** [all] Error 1

For sake of completeness, my code is in a unique file:

    // Libary
    #include <string>
    #include <iostream>
    #include <cuda_runtime.h>

    #include "caffe/include/caffe/caffe.hpp"
    #include "caffe/include/caffe/util/io.hpp"
    #include "caffe/include/caffe/blob.hpp"
    #include "/usr/local/Cellar/opencv/2.4.11_1/include/opencv2/core/core.hpp"
    #include "/usr/local/Cellar/opencv/2.4.11_1/include/opencv2/highgui/highgui.hpp"
    #include "/usr/include/python2.7/Python.h"

    using namespace caffe;
    using namespace std; 
    
    using NetSp = boost::shared_ptr<caffe::Net<float>>;
    using BlobSp = boost::shared_ptr<caffe::Blob<float>>;
    using SolverSp = std::shared_ptr<caffe::Solver<float>>;
    using MemoryDataLayerSp = boost::shared_ptr<caffe::MemoryDataLayer<float>>;

    int main(int argc, char** argv){

      string solver_file = argv[1];

      // Set code to use CPU:
      Caffe::set_mode(Caffe::CPU);
      cerr << "Using CPU..." << endl;

      // Read solver file (Caffe library):
      caffe::SolverParameter solver_param;
      //Read network description:
      caffe::ReadProtoFromTextFileOrDie(solver_file, &solver_param);

      NetSp net_;
      SolverSp solver_;
      BlobSp q_values_blob_;

      MemoryDataLayerSp frames_input_layer_;

      solver_.reset(caffe::GetSolver<float>(solver_param));
      net_ = solver_->net();

      // The line below is giving me "Undefined symbols for architecture x86_64"
      q_values_blob_ = net_->blob_by_name("q_values");

      // The line below is giving me "Undefined symbols for architecture x86_64"
      frames_input_layer_ = boost::dynamic_pointer_cast<caffe::MemoryDataLayer<float>>(
        net_->layer_by_name("frames_input_layer"));

      return 0;
    }

And my Makefile is below:

    CC=g++

    CAFFE := caffe

    #                                                        I don't want deprecated warnings neither missing braces
    CXXFLAGS = -O2 -Wall -D__STDC_CONSTANT_MACROS -std=c++11 -Wno-deprecated-declarations -Wno-missing-braces
    
    INCLUDE = -I $(CAFFE)/include \
    		 		-I $(CAFFE)/build/include/ \
    				-I /usr/local/cuda/include \
    			    -I /usr/local/Cellar/opencv/2.4.11_1/include \
    			    -I /usr/include/python2.7 \
    			    -I /Developer/NVIDIA/CUDA-6.0/include \
    			    -I /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/Headers
    
    LIBRARY = -L$(CAFFE)/build/lib -L/usr/local/Cellar/opencv/2.4.11_1/lib/ \
    	-lglog -lprotobuf -lpython2.7 -lcaffe -lm -lpthread \
    	-lopencv_core -lopencv_imgproc -lopencv_highgui
    
    all:
    	$(CC) $(INCLUDE) $(OBJS) $(CXXFLAGS) main.cpp -o simple_test $(LIBRARY)

**Am I forgetting to link something?**

Thanks in advance.

**Comment by longjon** [comment]
This tracker is for specific Caffe issues and bug reports; please ask usage questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) list. Thanks!
