### ISSUE TITLE
How define a output in softmax layer

### ISSUE THREAD

**Issue by acpn** [BVLC/caffe#2470]
Hi guys, I start a train with 360.000 images for train, and 150.000 for validation, and your labels are 0, 1, -90, 45 , -35...... N.

I have 13 class, distrubuted for all images, and the images are RGB, size 54x54.

but in my validation tests accuracy no pass of 0.07823. Softmax layer have something to do with this bad accuracy?

If yes, how I calculate output os softmax layer?

Thanks

**Comment by longjon** [comment]
This tracker is for issues and bugs with Caffe; please ask usage questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) list. Thanks!
