### ISSUE TITLE
Allow the solver to step backwards, where possible

### ISSUE THREAD

**Issue by longjon** [BVLC/caffe#2471]
When running SGD with momentum (for example), each parameter update contains enough information to compute the _previous_ parameter update (using the current parameters and input data). That means you can run the solver backwards. Of course, you would also need to be able to go backwards through the data and remember the rng state, if needed (and perhaps other state I am forgetting?).

While loss of precision will be an issue, this could be a useful debugging tool, especially when something goes wrong on a particular datum which isn't noticed until a few iterations later. Caffe could throw an exception (e.g., in Python) as soon as a NaN gradient appears (or some other condition is met), and the user could walk backwards to find out what happened.

**Comment by shelhamer** [comment]
Closing as too involved although the debugging use case is otherwise compelling and that it can be done at all is neat.
