### ISSUE TITLE
ImportError: dynamic module does not define init function (PyInit__caffe)

### ISSUE THREAD

**Issue by sendit2me** [BVLC/caffe#2478]
I have, and am still trying to get caffe running under python (python3.4)

during the "import caffe" statement I get.
is there a make pycaffe3 for python 3 vs 2 init ? 
or am I missing a step.

Thanks
Peter

**Comment by longjon** [comment]
Please note that Python 3 is not (yet) tested, and therefore we can't guarantee that it will work (though we try not to break it, and accept PRs that fix it). See also #2464.

In addition, please ask usage questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) list. Thanks!

**Comment by monajalal** [comment]
Is Caffe not still supported for Python3?

**Comment by Coderx7** [comment]
@monajalal : You should be able to compile with python3 in linux. in windows it is not supported afaik. just change the make.config file to use python3.
