### ISSUE TITLE
Is there a fast scanning implementation in caffe?

### ISSUE THREAD

**Issue by XericZephyr** [BVLC/caffe#2479]
For some detection purpose, the fast scanning technology[1] is highly demanded due to the redundant convolution operations. Is there a known fast image scanning implementation in caffe? Thanks. 

[1] Giusti, Alessandro, et al. "Fast image scanning with deep max-pooling convolutional neural networks." arXiv preprint arXiv:1302.1700 (2013).

**Comment by longjon** [comment]
This tracker is for issues and bugs with Caffe. You can do this with Caffe, but please ask about this and other usage questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) list. Thanks!
