### ISSUE TITLE
solverstate depends on the current directory

### ISSUE THREAD

**Issue by longjon** [BVLC/caffe#248]
The .solverstate files saved by caffe use relative pathnames to find the relevant parameter file. This means that resuming from a solverstate in the wrong directory can cause a crash, or worse (if there are parameter files in the current directory), silently use unexpected parameters.

We could:
1. Ignore and document this issue
2. Use absolute pathnames in solverstate files (but then moving them around becomes difficult)
3. Look for parameters in the same directory as the solverstate file
4. Embed parameters in the solverstate files (or vice versa) (but this couples things that might not want to be coupled)

**Comment by VasLem** [comment]
Sorry for opening this issue again, but what do you mean by relative path? From what I understood in the first place, if let's say solverstate and caffemodel are in the same folder, then the path of the caffemodel would be recorded as './caffemodel' by the solverstate. However, when I move both files to a different folder I get a 'caffemodel not found' error, at least using Python API. Is this a bug, or when one says relative path, he means something else?

**Comment by extragoya** [comment]
I have the same problem as @VasLem, when I move both files to a different folder, and then restore the solverstate, caffe complains about not being able to find the caffemodel in its original location. Unless I'm missing something, this doesn't seem like a relative path. Or do most people not run into this issue?

**Comment by Huxwell** [comment]
+1, If I move both .solverstate and .caffemodel to different directory and try to resume training, caffe cannot find the .caffemodel file.

**Comment by p1x31** [comment]
+1
