### ISSUE TITLE
unable to make all

### ISSUE THREAD

**Issue by smajida** [BVLC/caffe#2481]
Hi Everyone,
I'm somehow new in Caffe, I'm trying to install Caffe on my laptop (with Gefore 425M)
I'm not sure I should impose this question here or in Caffe User in google group. please let me know.
but I get this error:
majid@arrival:~/caffe-master$ make all
PROTOC src/caffe/proto/caffe.proto
CXX .build_release/src/caffe/proto/caffe.pb.cc
/bin/sh: 1: Syntax error: redirection unexpected
make: *** [.build_release/src/caffe/proto/caffe.pb.o] Error 2

My Makefile.config is as follows:

## Refer to http://caffe.berkeleyvision.org/installation.html
# CUDA directory contains bin/ and lib/ directories that we need.
CUDA_DIR := /usr/local/cuda-7.0

# CUDA architecture setting: going with all of them.
# For CUDA < 6.0, comment the *_50 lines for compatibility.
CUDA_ARCH := -gencode arch=compute_20,code=sm_20 \
<------><------>-gencode arch=compute_20,code=sm_21 \
<------><------>-gencode arch=compute_30,code=sm_30 \
<------><------>-gencode arch=compute_35,code=sm_35 \
<------><------>-gencode arch=compute_50,code=sm_50 \
<------><------>-gencode arch=compute_50,code=compute_50

BLAS := atlas

# This is required only if you will compile the matlab interface.
# MATLAB directory should contain the mex binary in /bin.
MATLAB_DIR := /usr/local/MATLAB/R2015a/
#MATLAB_DIR := /Applications/MATLAB_R2015a.app

# NOTE: this is required only if you will compile the python interface.
# We need to be able to find Python.h and numpy/arrayobject.h.
#PYTHON_INCLUDE := /usr/include/python2.7 \
#<------><------>/usr/lib/python2.7/dist-packages/numpy/core/include
# Anaconda Python distribution is quite popular. Include path:
# Verify anaconda location, sometimes it's in root.
ANACONDA_HOME := home/majid/anaconda
PYTHON_INCLUDE := home/majid/anaconda/include \
<------><------>/home/majid/anaconda/include/python2.7 \
<------><------>/home/majid/anaconda/lib/python2.7/site-packages/numpy/core/include \

# We need to be able to find libpythonX.X.so or .dylib.
# PYTHON_LIB := /usr/lib/python2.7/config-x86_64-linux-gnu
PYTHON_LIB := /home/majid/anaconda/lib

# Whatever else you find you need goes here.
INCLUDE_DIRS := $(PYTHON_INCLUDE) /usr/local/include \
	/usr/local/lib/python2.7/dist-packages/numpy/core/include \
	/home/majid/protobuf-2.6.1 \
	/home/majid/glog-0.3.3 \
	/home/majid/leveldb-master/include \
	/home/majid/gflags-master/build/include \
	/home/majid/mdb/libraries/liblmdb

LIBRARY_DIRS := $(PYTHON_LIB) /usr/lib /usr/local/lib \
    /home/majid/protobuf-2.6.1 \
    /home/majid/glog-0.3.3 \
    /home/majid/snappy-1.1.1 \
    /home/majid/leveldb-master/include \
    /home/majid/gflags-master/build/lib \
    /home/majid/mdb/libraries/liblmdb

Really appreciate it if you could help me to solve this problem. I tried many times.

**Comment by smajida** [comment]
The second one I tried make all everything went good but in the end I got this error could you let me know why?

NVCC src/caffe/layers/cudnn_pooling_layer.cu
AR -o .build_release/lib/libcaffe.a
LD -o .build_release/lib/libcaffe.so
CXX tools/caffe.cpp
CXX/LD -o .build_release/tools/caffe.bin
.build_release/lib/libcaffe.so: undefined reference to `cv::imread(cv::String const&, int)'
.build_release/lib/libcaffe.so: undefined reference to `cv::imencode(cv::String const&, cv::_InputArray const&, std::vector<unsigned char, std::allocator<unsigned char> >&, std::vector<int, std::allocator<int> > const&)'
.build_release/lib/libcaffe.so: undefined reference to `cv::imdecode(cv::_InputArray const&, int)'
collect2: error: ld returned 1 exit status
make: *** [.build_release/tools/caffe.bin] Error 1
majid@arrival:~/caffe$

**Comment by longjon** [comment]
This tracker is for issues and bugs with Caffe. The right venue for usage and installation questions is the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) list. Thanks!
