### ISSUE TITLE
IMK Stall detected, *please Report* your user scenario in <rdar://problem/16792073> - (imkxpc_bundleIdentifierWithReply:) block performed very slowly (16.02 secs)

### ISSUE THREAD

**Issue by juandent** [BVLC/caffe#2490]
I am getting this error when I run a small sample app:

IMK Stall detected, *please Report* your user scenario in <rdar://problem/16792073> - (imkxpc_bundleIdentifierWithReply:) block performed very slowly (16.02 secs)

I run MAC OS X 10.10.3 on MacBookPro

??

Thanks.,
Juan Dent

**Comment by longjon** [comment]
Closing, as I'm pretty sure this message is not coming from Caffe. If you are also seeing incorrect behavior from Caffe, you're welcome to open another issue describing that. Otherwise, please discuss on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) list. Thanks!
