### ISSUE TITLE
Caffe cannot build up!

### ISSUE THREAD

**Issue by kuochiyoug** [BVLC/caffe#2491]
Hi, everyone.
I recently tried to use caffe for my research, but I cannot make caffe, please help me! I had installed CUDA 7.0 Toolkits but still don't work!

This is Error message:
---------------------------------------------------------------------------------------------------------------------
[  1%] Built target proto
[  1%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/cuda_compile_generated_dropout_layer.cu.o
/home/assimilation/caffe/src/caffe/layers/dropout_layer.cu(35): error: a host function call cannot be configured
          detected during instantiation of "void caffe::DropoutLayer<Dtype>::Forward_gpu(const std::vector<caffe::Blob<Dtype> *, std::allocator<caffe::Blob<Dtype> *>> &, const std::vector<caffe::Blob<Dtype> *, std::allocator<caffe::Blob<Dtype> *>> &) [with Dtype=float]" 
(74): here

/home/assimilation/caffe/src/caffe/layers/dropout_layer.cu(64): error: a host function call cannot be configured
          detected during instantiation of "void caffe::DropoutLayer<Dtype>::Backward_gpu(const std::vector<caffe::Blob<Dtype> *, std::allocator<caffe::Blob<Dtype> *>> &, const std::vector<__nv_bool, std::allocator<__nv_bool>> &, const std::vector<caffe::Blob<Dtype> *, std::allocator<caffe::Blob<Dtype> *>> &) [with Dtype=float]" 
(74): here

/home/assimilation/caffe/src/caffe/layers/dropout_layer.cu(35): error: a host function call cannot be configured
          detected during instantiation of "void caffe::DropoutLayer<Dtype>::Forward_gpu(const std::vector<caffe::Blob<Dtype> *, std::allocator<caffe::Blob<Dtype> *>> &, const std::vector<caffe::Blob<Dtype> *, std::allocator<caffe::Blob<Dtype> *>> &) [with Dtype=double]" 
(74): here

/home/assimilation/caffe/src/caffe/layers/dropout_layer.cu(64): error: a host function call cannot be configured
          detected during instantiation of "void caffe::DropoutLayer<Dtype>::Backward_gpu(const std::vector<caffe::Blob<Dtype> *, std::allocator<caffe::Blob<Dtype> *>> &, const std::vector<__nv_bool, std::allocator<__nv_bool>> &, const std::vector<caffe::Blob<Dtype> *, std::allocator<caffe::Blob<Dtype> *>> &) [with Dtype=double]" 
(74): here

4 errors detected in the compilation of "/tmp/tmpxft_00000d0d_00000000-7_dropout_layer.cpp1.ii".
CMake Error at cuda_compile_generated_dropout_layer.cu.o.cmake:264 (message):
  Error generating file
  /home/assimilation/caffe/src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_dropout_layer.cu.o

make[2]: *** [src/caffe/CMakeFiles/cuda_compile.dir/layers/cuda_compile_generated_dropout_layer.cu.o] Error 1
make[1]: *** [src/caffe/CMakeFiles/caffe.dir/all] Error 2
make: *** [all] Error 2
---------------------------------------------------------------------------------------------------------------------

My Graphic card is Nvidia GTX980
Using Ubuntu12.04 64bits version
Please Help me!!

**Comment by longjon** [comment]
This tracker is for issues and bugs with Caffe. Please ask usage and installation questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) list. Thanks!
