### ISSUE TITLE
Travis should check that USE_CUDNN builds

### ISSUE THREAD

**Issue by futurely** [BVLC/caffe#2492]
#1792
https://github.com/BVLC/caffe/issues/2475#issuecomment-103745608
https://gitter.im/BVLC/caffe/archives/2015/05/02
http://stackoverflow.com/questions/30127415/caffe-cudnn-r1-compile-error

**Comment by longjon** [comment]
Yes, Travis currently does not check that the build works with `USE_CUDNN` set, and it should (PRs welcome).

Separately, Travis cannot run GPU tests; we may eventually have CI for the GPU tests, but that is a separate issue.

Note that the latest master supports cuDNN R2 _only_. We do not plan to continue supporting R1.
