### ISSUE TITLE
There is a error line "/usr/bin/ld:cannot find -lboost_numpy",when my make the caffe.

### ISSUE THREAD

**Issue by greatgao** [BVLC/caffe#2494]
At last,I have trying the Baidu's paper which is called 'An Empirical Evaluation of Deep Learning on Highway Driving'.I had download the source code from the website, BUT when I type the 'make all' on the terminal screen,it printed a error line '/usr/bin/ld:cannot find -lboost_numpy' ,then I download the NUMPY_BOOST file ,and run the setup.py [which in the NUMPY_BOOST file].Done that, there are still a error line popped as the same upon.
Has anyone gotten the same error,how do you deal with it?
To my best.

**Comment by longjon** [comment]
This tracker is for issues and bugs with Caffe. Please ask usage and installation questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) list. Thanks!

**Comment by minxueric** [comment]
Hello, I am also looking at this paper. I don't know where can I find the source code of this paper, could you please tell me that? Thanks!

**Comment by arushk1** [comment]
https://github.com/ndarray/Boost.NumPy install this
