### ISSUE TITLE
Parallel caffe error: This MPI version is NOT support multi-thread!

### ISSUE THREAD

**Issue by anurikadisha** [BVLC/caffe#2496]
The mpi_train.sh has the following line:

mpiexec.hydra -prepend-rank -host node11 -n 16

While running examples/cifar10/mpi_train_quick.sh in parallel caffe I get the following error:

    F0521 18:33:32.101737 16179 caffe.cpp:293] This MPI version is NOT support multi-thread!
    *** Check failure stack trace: ***
    @ 0x7f8367e83daa (unknown)
    @ 0x7f8367e83ce4 (unknown)
    @ 0x7f8367e836e6 (unknown)
    @ 0x7f8367e86687 (unknown)
    @ 0x410ac8 main
    @ 0x7f8364b76ec5 (unknown)
    @ 0x414e77 (unknown)
    @ (nil) (unknown)
    Aborted (core dumped)

I have installed mpich-3.1.4 version.
When I do which mpirun, which mpiexec, which mpicc, I get the path to the mpich-3.1.4 folder from all of these
Also the system has both Open-Mpi and MPICH-3.1.4 installed since open-mpi gets installed automatically while installing opencv which is a pre-requisite for parallel caffe . How can I resolve this error?

**Comment by lucmichalski** [comment]
+1
