### ISSUE TITLE
target_blobs.size() == source_layer_blobs.size() (2 vs. 0) - Incompatible number of blobs for layer 1

### ISSUE THREAD

**Issue by N-01** [BVLC/caffe#2499]
Hey, i am currently trying to train and test my own model with my own data via latest version of caffe(c++). Training goes as expected with such prototxt:

```
name: "FACES"
layer {
  name: "data"
  type: "Data"
  top: "data"
  top: "label"
  include {
    phase: TRAIN
  }

  data_param {
    source: "examples/_faces/trainldb"
    batch_size: 155
    backend: LEVELDB
  }
}
layer {
  name: "data"
  type: "Data"
  top: "data"
  top: "label"
  include {
    phase: TEST
  }

  data_param {
    source: "examples/_faces/testldb"
    batch_size: 45
    backend: LEVELDB
  }
}
layer {
  name: "conv1"
  type: "Convolution"
  bottom: "data"
  top: "conv1"
  param {
    lr_mult: 1
	decay_mult: 1
  }
  param {
    lr_mult: 2
	decay_mult: 0
  }
  convolution_param {
    num_output: 12
    kernel_size: 13
    stride: 2
    weight_filler {
      type: "gaussian" # initialize the filters from a Gaussian
      std: 0.01        # distribution with stdev 0.01 (default mean: 0)
    }
    bias_filler {
      type: "constant"
	  value: 0
    }
  }
}

....

layer {
  name: "accuracy"
  type: "Accuracy"
  bottom: "ip2"
  bottom: "label"
  top: "accuracy"
  include {
    phase: TEST
  }
}
layer {
  name: "loss"
  type: "SoftmaxWithLoss"
  bottom: "ip2"
  bottom: "label"
  top: "loss"
}
```

but when i'm trying to load with model for making predictions with such prototxt:

```
name: "FACES"
input: "data"
input_dim: 1
input_dim: 3
input_dim: 150
input_dim: 150
layer {
  name: "conv1"
  type: "Convolution"
  bottom: "data"
  top: "conv1"
  param {
    lr_mult: 1
	decay_mult: 1
  }
  param {
    lr_mult: 2
	decay_mult: 0
  }
  convolution_param {
    num_output: 12
    kernel_size: 13
    stride: 2
  }
}
layer {
  name: "relu1"
  type: "ReLU"
  bottom: "conv1"
  top: "conv1"
}
....
layer {
  name: "prob"
  type: "Softmax"
  bottom: "ip2"
  top: "prob"
}
```

It breaks with **target_blobs.size() == source_layer_blobs.size() (2 vs. 0) - Incompatible number of blobs for layer 1**
but i can't see a mistake on my side. and it also matches simillar setup for caffenet.

maybe i'm not supposed to load it like that?:

```
Caffe::set_mode(Caffe::CPU);

	Net<float>* net;
	net = new Net<float>("azf_faces.prototxt", Phase::TEST);
	cout << "Num inputs in Net: " << net->num_inputs() << endl; //1
	cout << "Num outputs in Net: " << net->num_outputs() << endl; //1

	net->CopyTrainedLayersFrom("azf3_iter_10000.caffemodel");
```

**Comment by N-01** [comment]
Re-opening this issue since it did escalate to something weird... Same error also occurs with mnist example. It has trained succesfully, but when i try to load resulting model with lenet.prototxt for recognition, it throws an exception "target_blobs.size() == source_layer_blobs.size() (2 vs. 0) - Incompatible number of blobs for layer 1". So either my initialization routine is wrong, or i did skrew up framework compilation(it was hell, i use it under windows 7 and VS2013), guided by this post: https://initialneil.wordpress.com/2015/01/11/build-caffe-in-windows-with-visual-studio-2013-cuda-6-5-opencv-2-4-9/

Maybe someone, who knows this framework's source very well could give a hint, what could lead to such behaviour. Because you can't google it and it conflicts with all the tutorials.

**Comment by libzlibz** [comment]
change io.cpp function ReadProtoFromBinaryFile
from open(filename, O_RDONLY)
to open(filename, O_RDONLY|O_BINARY)

you will find you can read the caffemodel file.

open read text format file default, you can only read part of the file if you read caffemodel, you would change text to binary.

**Comment by captainzone** [comment]
I can see O_BINARY was not declare in this scope. compile error occurs.

**Comment by pppoe** [comment]
@libzlibz Thanks! Works for me.

**Comment by JosephChenHub** [comment]
In Linux, O_BINARY is not defined!!!
