### ISSUE TITLE
Fine-tune a pretrained model 

### ISSUE THREAD

**Issue by pulsefire2000** [BVLC/caffe#2500]
Model : BVLC_ALEXNET

Task : Fine tune the model , detect ground truth and classify the image

I've followed this link : https://github.com/BVLC/caffe/tree/master/examples/imagenet

Objective is to detect multiple faces.For that,am using a dataset http://vis-www.cs.umass.edu/fddb/ and also considering AFLW dataset.

Question: How to fine tune,detect ground truth pixel and train the model(which is designed to classify image but I want to use it to classify whether the picture pertains face(s) or no face) using caffe and python. Sorry am new to this field so I dont know much about it. 

Any help would be appreciated. Thanks,

**Comment by ronghanghu** [comment]
@pulsefire2000 you may follow [Fast RCNN](https://github.com/rbgirshick/fast-rcnn) which is an example using Caffe (a custom branch) to train detectors, but please ask installation or usage questions on [Caffe-users](https://groups.google.com/forum/#!forum/caffe-users).
