### ISSUE TITLE
Pretrain a model using caffe

### ISSUE THREAD

**Issue by jensen810814** [BVLC/caffe#2506]
Hello guys, I wanna ask can I use caffe to pretrain a model, and then use the papameters of this model to initialize another model ?
If it can, can anyone teach me how to do it? Thank you.

**Comment by longjon** [comment]
This tracker is for issues and bugs with Caffe. Please ask usage questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) list. Thanks!
