### ISSUE TITLE
Is zero-padding not supporting with cuDNN v2 (caffe:master)???  bug in cuDNN v2. 

### ISSUE THREAD

**Issue by lim0606** [BVLC/caffe#2508]
Hi! 

I got an error when I use following conditions; 
1) use cuDNN v2
2) use conv layer with
2.1) bottom size < kernel size (either width or height)
2.2) bottom size + pad > kernel size (either width or height)

```
F0525 17:36:32.711757  4106 cudnn_conv_layer.cu:53] Check failed: status == CUDNN_STATUS_SUCCESS (3 vs. 0)  CUDNN_STATUS_BAD_PARAM
```
from 
```
CUDNN_CHECK(cudnnGetConvolutionForwardWorkspaceSize(handle_[g],
        bottom_descs_[i],
        filter_desc_,
        conv_descs_[i],
        top_descs_[i],
        algo,
        &workspaceSizeInBytes_temp));
```

Some layers have to be defined with above layer conditions, especially when I want to use inception layer in googlenet. 

I confirmed the same error condition with CIFAR-10 example by changing conv3 from "bottom size: 8 / pad: 2, kernel: 5" to "bottom size: 8 / pad: 5, kernel: 10". 

If I compile without cuDNN options, i.e. use conv_layer.cu, it works. 

~~I think it is initialisation issue. While LayerSetUp() of cudnn_conv_layer.cpp relies on base_conv_layer.cpp, Reshape() seems not; thus, top shape seems not to be initialised properly.~~

~~If I solve this issue, i will post it~~

It seems like a bug in cuDNN v2. 

One of the failure case I tested is as follows, (it has been worked with cuDNN v1 successfully)

workspace_limit_bytes: 5761
bottom_desc -> n: 96, c: 160, h: 2, w: 2, nStride: 640, cStride: 4, hStride: 2, wStride: 1, dataType: 0
top_desc -> n: 96, c: 320, h: 2, w: 2, nStride: 1280, nStride: 4, hStride: 2, wStride: 1, dataType: 0
conv_desc -> pad_h: 1, pad_w: 1, u: 1, v: 1, upscale_x: 1, upscale_y: 1, mode: 1
filter_desc -> k: 320, c: 160, kernel_h: 3, kernel_w: 3, dataType: 0

Even if I manually set workspaceSizeInBytes with large value and directly run `cudnnConvolutionForward`, I got the same error. 

```
CUDNN_CHECK(cudnnConvolutionForward(handle_[g],
            cudnn::dataType<Dtype>::one,
            bottom_descs_[i], bottom_data + bottom_offset_ * g,
            filter_desc_, weight + weight_offset_ * g,
            conv_descs_[i],
            algo, workspace, workspaceSizeInBytes,
            cudnn::dataType<Dtype>::zero,
            top_descs_[i], top_data + top_offset_ * g));
```
(I set `workspaceSizeInBytes = 11522` with above sample case)

Is there anyone can help me to fix this issue?

**Comment by lim0606** [comment]
Sorry! This error should not happen if the network is properly designed.

**Comment by DeepDreamer89** [comment]
Is there any Workaround for especially for bvlc_googlenet model?
How I understood it could be fixed juggling with parameters like kernel_size.
I tried change it, but then other things not work anymore, the message is
"To learn this layer's parameters from scratch rather than copying from a saved net, rename the layer."
Anybody did that successfully?
