### ISSUE TITLE
Multi-task learning  gradient backpropagation in the shared layer

### ISSUE THREAD

**Issue by chocolate9624** [BVLC/caffe#2509]
layer {
  name: "fc7"
  type: "INNERPRODUCTt"
  bottom: "fc6"
  top: "fc7"
}
layer {
  name: "cls_score"
  type: "InnerProduct"
  bottom: "fc7"
  top: "cls_score"
}
layer {
  name: "bbox_pred"
  type: "InnerProduct"
  bottom: "fc7"
  top: "bbox_pred"
}

In the above examples, the blob 'fc7' has two gradients, which back propagate form "cls_score" layer and "bbox_pred" layer respectively. So I think these two gradients should add together. But, in "innerProduct" layer of caffe, the back propagated gradients are in this way :
  
  if (propagate_down[0]) {
    const Dtype* top_diff = top[0]->gpu_diff();
    // Gradient with respect to bottom data
    caffe_gpu_gemm<Dtype>(CblasNoTrans, CblasNoTrans, M_, K_, N_, (Dtype)1.,
        top_diff, this->blobs_[0]->gpu_data(), (Dtype)0.,
        bottom[0]->mutable_gpu_diff());
  }
The gradients don't add together. 
Am I wrong ?

Thanks a lot!

.

**Comment by chocolate9624** [comment]
I know that adding the split layer after "fc6" can solve this problem. The two gradients will add together in the split layer.
But, why the prototxt of fast-rcnn don't add the split layer? 
Thanks!

**Comment by happynear** [comment]
Caffe will automatically add a split layer when one layer is connected to two layers.

**Comment by longjon** [comment]
This tracker is for issues and bugs with Caffe. Please ask usage questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) list. Thanks!
