### ISSUE TITLE
Unknown layer type when using Release mode

### ISSUE THREAD

**Issue by BurningBurning** [BVLC/caffe#2510]
Hi,

I'm new to caffe. I just write a new layer, and in DEBUG mode, the layer is tested all right. But when I make my layer with RELEASE mode ,the error generated : Check failed: registry.count(type) == 1 (0 vs. 1) Unknown layer type
So what's the problem?

Thanks,
Burning

**Comment by leifblaese** [comment]
The error can appear if the layers are not linked correctly (see http://stackoverflow.com/questions/30325108/caffe-layer-creation-failure ). Maybe you need to recompile the RELEASE mode and check whether everything is linked correctly?
