### ISSUE TITLE
Houston, We've Got a Problem (I mean.. I have)!

### ISSUE THREAD

**Issue by acpn** [BVLC/caffe#2512]
Hi guys, I'm trying train my own net with LFW dataset: http://vis-www.cs.umass.edu/lfw/

I'm using 9.000 images for train and 4.233 for validation, size  of images is 58x58, and I labeled my images with values between 0......N. I create the databases, based on imagenet tutorial: http://caffe.berkeleyvision.org/gathered/examples/imagenet.html

but my accuracy is always 0 and loss between 6.16 and 7.90.

I designed a small architecture defined in paper of Guosheng Hu 2015 named: When Face recognition meets Deep Learning.

I don't no what I'm doing wrong, anybody help me?

Thanks guys!!

**Comment by longjon** [comment]
This tracker is for issues and bugs with Caffe. Please ask usage and modeling questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) list. Thanks!
