### ISSUE TITLE
cannot investigate matcaffe network compoenent

### ISSUE THREAD

**Issue by johnny5550822** [BVLC/caffe#2517]
We are able to look into network components (such as a layer's output) in pycaffe. However, in matcaffe, I only see the 'forward' option available, i.e. we can only see the last layer's outcome. 

How can we view the components in the network via matcaffe? I heard matcaffe2 is somewhere in the repository?

Thanks!

**Comment by ronghanghu** [comment]
@johnny5550822 take a look at my implementation at #2505 .

**Comment by johnny5550822** [comment]
Wow, that looks great! So now matcaffe3 is not in the master of caffe yet, right? And I can only access it in your repo with matcaffe3 branch?

**Comment by ronghanghu** [comment]
@johnny5550822 yes, and I hope it can be merged into caffe's master branch soon, although it seems that recently the reviewing process of community PRs is quite slow.

**Comment by johnny5550822** [comment]
@ronghanghu Great! With your implementation, I can change one particular node a layer right?

**Comment by ronghanghu** [comment]
@johnny5550822 Yes, just follow the examples in PR message.

**Comment by johnny5550822** [comment]
@ronghanghu Great thanks!
