### ISSUE TITLE
Non-meaningful errors when parsing window files

### ISSUE THREAD

**Issue by nightrome** [BVLC/caffe#2520]
After hours of debugging I found why my window file (used for fine tuning) produces the following not very enlightening error:
I0527 15:10:47.169782  4144 window_data_layer.cpp:376] output data size: 64,0,227,227
I0527 15:10:47.169786  4144 window_data_layer.cpp:388] Loading mean file from../../data/ilsvrc12/imagenet_mean.binaryproto
F0527 15:10:47.173749  4144 window_data_layer.cpp:394] Check failed: data_mean_.channels() == channels (3 vs. 0) 
**\* Check failure stack trace: ***
    @     0x7fcd1cf2fdaa  (unknown)
    @     0x7fcd1cf2fce4  (unknown)
    @     0x7fcd1cf2f6e6  (unknown)
    @     0x7fcd1cf32687  (unknown)
    @           0x4b84c6  caffe::WindowDataLayer<>::SetUp()
    @           0x4375e7  caffe::Net<>::Init()
    @           0x438875  caffe::Net<>::Net()
    @           0x43b9b6  caffe::Solver<>::Init()
    @           0x43e34b  caffe::Solver<>::Solver()
    @           0x40a289  main
    @     0x7fcd1aa0cec5  (unknown)
    @           0x40c1ae  (unknown)
    @              (nil)  (unknown)

It turns out that whitespaces in file names (in this case in the Barcelona dataset) are not supported. I did not find any workaround, other than to rename the files (tried using "" and escaping the whitespace).

Furthermore it turns out that if one image is missing in the window file (where missing means that after #423 comes #425), it just crashes after reading in the network definition without any error.

I think especially the first error is a serious issue that should need to be fixed (at least with proper error messages).

Cheers

**Comment by shelhamer** [comment]
The `WindowData` layer is essentially deprecated and only kept for archival purposes for the sake of the original R-CNN. It should be declared deprecated in the documentation as it is not going to be further maintained.
