### ISSUE TITLE
Feature Request: Multi-Network Definition

### ISSUE THREAD

**Issue by elleryrussell** [BVLC/caffe#2521]
Working with Model compression and filter reconstruction techniques, it'd be very nice if caffe could differentiate between different networks used in the same training script.  For example, when training AlexNet to match the outputs of VGGNet, I'm currently writing a prototxt file that includes both network architectures into the same prototxt - I have to transfer the weights from each by hand to initialize the network, edit all VGG layers to have zero learning weights separately, and snapshotting saves all the VGG layers parameters, which requires considerably higher disk space per snapshot.  Then, to move the model into a deploy format, the alexnet parameters have to be extracted from the larger snapshots.  For situations like these, it would be wonderful if caffe could abstract to many separate networks each with their own definition, but synchronized during training.  If anyone else has ideas about this, I'd love to hear.

**Comment by shelhamer** [comment]
Closing as too involved. This can be handled through pycaffe, albeit somewhat manually. Sorry about the time overhead of handling this by net surgery.
