### ISSUE TITLE
Solver parameter 'test_iter' affects label values in test phase.

### ISSUE THREAD

**Issue by mbamelis** [BVLC/caffe#2524]
I'm using Caffe to research convolutional neural networks. My dataset contains 10240 images, 9216 are used as sample images for training, 1024 are used for testing.

The sample images have 38 labels each that are either 0 or 1. Because each sample has multiple labels, I'm using the HDF5 format to store the images and the vector of labels for each image.

I've come onto this bug by accident and constructed a simple network to replicate the results:

```
layer {
	name: "data"
	type: "HDF5Data"
	top: "data"
	top: "label"
	hdf5_data_param {
		source: "./convset_hdf5_train.txt"
		batch_size: 32
	}
	include {
		phase: TRAIN
	}
}
layer {
	name: "data"
	type: "HDF5Data"
	top: "data"
	top: "label"
	hdf5_data_param {
		source: "./convset_hdf5_test.txt"
		batch_size: 1024
	}
	include {
		phase: TEST
	}
}
layer {
	name: "silence"
	type: "Silence"
	bottom: "data"
}
```

This network will simply output all labels.

Each HDF5 file contains 1024 images: 9 files (=9216 images) are used for training, 1 file is used for testing. I'm running this on a Nvidia 540M graphics card which has 1GB of memory.

In a real network, I cannot load all testing images without going out of memory. This is why I used a batch size of 64 or 32 during both training and testing.

If all samples are tested as a single batch, nothing goes wrong. However, if I try to balance out the `batch_size` and `test_iter` parameters (so that `batch_size * test_iter = 1024`), labels with value 1 get changed to a new value.

These are my results:
`batch_size = 1024, test_iter = 1:` no problem, labels stay the same
`batch_size = 512, test_iter = 2:` labels with value 1 are changed to value 0.5
`batch_size = 256, test_iter = 4:` labels with value 1 are changed to value 0.5 or 0.25
`batch_size = 128, test_iter = 8:` labels with value 1 are changed to value 0.5 or 0.25 or 0.125
[...]

The pattern continues. What is going on here? Am I doing something wrong?

According to the [LeNet example](http://caffe.berkeleyvision.org/gathered/examples/mnist.html), `test_iter * batch_size = number_of_test_samples`. Am I interpreting this wrong?

**Comment by shelhamer** [comment]
This is not a bug -- during solving the outputs of the test net are averaged across iterations. See `Solver::Test()` https://github.com/BVLC/caffe/blob/master/src/caffe/solver.cpp#L267-L321 in particular line 313 that computes the mean

    const Dtype mean_score = test_score[i] / param_.test_iter(test_net_id);

The data is unaltered -- it's output this way for printing.

**Comment by shaibagon** [comment]
You can find more information at stackoverflow: http://stackoverflow.com/q/30510722/1714410
