### ISSUE TITLE
Has anyone come up against the same problem?

### ISSUE THREAD

**Issue by zhangchen-qinyinghua** [BVLC/caffe#2526]
It was about May 5th, 2015, when I was using the bleeding edge version of Caffe to train a GoogleNet, I came up against a problem that:

the GPU server _Get Stuck and responded very slow_ after about thousands of iterations of training, 
and the only solution was to reboot the server or somehow close the Caffe process.

This problem reappeared a lot.

I really didn't look for the cause carefully and just turned to cxxnet and the same problem never came up any more.

I now wonder whether it is a bug of Caffe ( or just something I did wrong). 
So has anyone come up against the same problem?

I was using GPU server with 2 Teska K40m, 
Red Hat with GCC version 4.4.7
Cuda 7.0 and cuDNN 6.5

I was training GoogleNet with the model files offered in model zoo,
with the input pictures resized to 256 x 256 and cropped to 224 x 224, in LMDB,
and the size of data.mdb is about 100GB.

**Comment by shelhamer** [comment]
Sorry, this sounds like a downstream configuration issue perhaps with lmdb and virtual memory. Please ask system configuration questions on the mailing list.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
