### ISSUE TITLE
Convolutional Sparse Coding Unsupervised Learning.

### ISSUE THREAD

**Issue by nebojsaandjelkovic** [BVLC/caffe#2531]
I have been trying to implement architecture/solver protobuf for neural network for unsupervised learning using convolutional sparse coding as described in the following paper http://cs.nyu.edu/~ylan/files/publi/koray-nips-10.pdf.

I did not find a way to implement weight sharing between encoder and decoder layers and also the implementation of lost function as described in paper with L1 regularization of features.

Is it even possible to describe such network and lost function using Caffe?

**Comment by longjon** [comment]
This tracker is for issues and bugs with Caffe. Please ask usage and modeling questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) list. Thanks!
