### ISSUE TITLE
Combining outputs of several CNNs?

### ISSUE THREAD

**Issue by titubeta** [BVLC/caffe#2533]
Hello,
Let's say for a particular application, I want to train left and right side of images separately using two separate CNNs and each image can have either of the two class labels i.e. [0,1]. How can we combine the outputs of these CNNs?
My understanding is that we can use a feed-forward layer to combine both of their outcomes, how could we define it in the prototxt file? Since both CNNs may save models separately, can we use these models and add another layer to combine their results? Is there a straight forward answer to this?
Your help will be highly appreciated.
regards

**Comment by sausthapit** [comment]
hi,
Have you looked at this:
http://caffe.berkeleyvision.org/gathered/examples/siamese.html
Also regarding the data you may want to generate label for pair of data, there is a discussion in caffe user's group which might be of interest.
https://groups.google.com/forum/#!msg/caffe-users/SOgOkPYps1g/Ne9qCUZs1L0J

Thanks

**Comment by longjon** [comment]
This tracker is for issues and bugs with Caffe. Please ask usage questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) list. Thanks!
