### ISSUE TITLE
Can Caffe handle gray scale images?

### ISSUE THREAD

**Issue by titubeta** [BVLC/caffe#2534]
The documentation says that the images should be RGB, however if we have gray scale images, will Caffe have any problem with that?
regards

**Comment by burk** [comment]
Caffe has no problem with that, see the documentation on [blobs, layers and nets](http://caffe.berkeleyvision.org/tutorial/net_layer_blob.html), where RGB is only an example.

How to enforce that they are treated as grayscale depends on your data layer.

**Comment by ben-eysenbach** [comment]
For example, the MNIST dataset is composed of greyscale images. A network for recognizing MNIST (e.g. [LeNet](https://github.com/BVLC/caffe/blob/master/examples/mnist/lenet.prototxt)) would be defined as:
```
name: "LeNet"
input: "data"
input_dim: 64 // batch size
input_dim: 1 // number of channels (3 for RGB)
input_dim: 28 // height
input_dim: 28 // width
...
```

**Comment by longjon** [comment]
This tracker is for issues and bugs with Caffe. Please ask usage questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) list. Thanks!
