### ISSUE TITLE
Storing the features output from a middle layer

### ISSUE THREAD

**Issue by anurikadisha** [BVLC/caffe#2535]
Hi!!
I am new to caffe and hence dont have much idea. I want to  extract and store the features which are the output from the first fully connected layer for each image in the training set after training is complete. How can I do it?

**Comment by ben-eysenbach** [comment]
Check out the [Feature Extraction](http://caffe.berkeleyvision.org/gathered/examples/feature_extraction.html) tool.

**Comment by longjon** [comment]
This tracker is for issues and bugs with Caffe. Please ask usage questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) list. Thanks!
