### ISSUE TITLE
Error while training on RHEL

### ISSUE THREAD

**Issue by prajesh0486** [BVLC/caffe#2541]
There two GPU cards on my system. 
1. Tesla K20
2. GeForce GT 610
I have installed RHEL on my system. When i am keep training on the system, after 460 iterations it is showing the error message,

F0601 10:27:47.313387  4577 math_functions.cpp:91] Check failed: error == cudaSuccess (30 vs. 0)  unknown error
*** Check failure stack trace: ***
    @     0x7f71dc511bbd  google::LogMessage::Fail()
    @     0x7f71dc513c77  google::LogMessage::SendToLog()
    @     0x7f71dc5117ac  google::LogMessage::Flush()
    @     0x7f71dc51453d  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f71dccfd71a  caffe::caffe_copy<>()
    @     0x7f71dcd42f19  caffe::BasePrefetchingDataLayer<>::Forward_gpu()
    @     0x7f71dcc484b2  caffe::Net<>::ForwardFromTo()
    @     0x7f71dcc4874f  caffe::Net<>::ForwardPrefilled()
    @     0x7f71dcd297b0  caffe::Solver<>::Step()
    @     0x7f71dcd2a3e5  caffe::Solver<>::Solve()
    @           0x4080e3  train()
    @           0x4059fe  main
    @       0x3a5841ed5d  (unknown)
    @           0x4050c9  (unknown)
Aborted (core dumped)

Can anyone help me ... ?

**Comment by shelhamer** [comment]
Closing as this looks like a usage issue/platform problem.

This tracker is reserved for specific Caffe development issues and bugs; please ask usage questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) list.

For more information, see our [contributing guide](https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md).

Thanks!
