### ISSUE TITLE
VGG train_val prototxt for trained instance

### ISSUE THREAD

**Issue by tmbo** [BVLC/caffe#2542]
There is a trained instance of the VGG model at https://gist.github.com/ksimonyan/fd8800eeb36e276cd6f9 which is referenced by caffe, but there is no train_val prototxt available for finetuning.

Can someone provide one?

**Comment by longjon** [comment]
This tracker is for issues and bugs with Caffe. Please ask usage and model zoo questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) list. Thanks!
