### ISSUE TITLE
make runtest error

### ISSUE THREAD

**Issue by LplusKira** [BVLC/caffe#2544]
Hi everyone!
I'm quite new in using github and not familiar with rules here. So, if there's anything unappropriate, pls tell me. Thx a lot!

My problem is that:
  After finishing (i guessed...) the parts in "Prerequisites" and "Compilation"(exactly the instructions in CMake Compilation) mentioned in http://caffe.berkeleyvision.org/installation.html#compilation
  I got the following error messages (Check failed: error == cudaSuccess (30 vs. 0)  unknown error)
  
F0604 00:06:01.585976 13946 math_functions.cpp:91] Check failed: error == cudaSuccess (30 vs. 0)  unknown error
*** Check failure stack trace: ***
    @     0x2ac2169d2daa  (unknown)
    @     0x2ac2169d2ce4  (unknown)
    @     0x2ac2169d26e6  (unknown)
    @     0x2ac2169d5687  (unknown)
    @     0x2ac2162a9b72  caffe::caffe_copy<>()
    @           0x731dc7  caffe::GradientChecker<>::CheckGradientSingle()
    @           0x7326ec  caffe::GradientChecker<>::CheckGradientEltwise()
    @           0x7446c6  caffe::ReshapeLayerTest_TestGradient_Test<>::TestBody()
    @           0x9d4e03  testing::internal::HandleExceptionsInMethodIfSupported<>()
    @           0x9cb627  testing::Test::Run()
    @           0x9cb6ce  testing::TestInfo::Run()
    @           0x9cb7d5  testing::TestCase::Run()
    @           0x9ce528  testing::internal::UnitTestImpl::RunAllTests()
    @           0x9ce7c7  testing::UnitTest::Run()
    @           0x6aab3a  main
    @     0x2ac21c1abec5  (unknown)
    @           0x6ab512  (unknown)
    @              (nil)  (unknown)
Aborted (core dumped)
make[3]: *** [src/caffe/test/CMakeFiles/runtest] Error 134
make[2]: *** [src/caffe/test/CMakeFiles/runtest.dir/all] Error 2
make[1]: *** [src/caffe/test/CMakeFiles/runtest.dir/rule] Error 2

  I searched for the same problems, but it doesn't help...
environment:
  OS: Ubuntu 14.04.2 LTS
  nvidia driver version: 346.46
 cuda-7.0

  Plus, there are 
    installation logfile
    cuda-driver version's details
    error msagges after $make runtest
  in the link: https://www.dropbox.com/s/k0ba0s1ntb8j5q2/runttest_error_msg.zip?dl=0
  Any advice on what I did wrong here or how to debug this would be very very helpful.
Many thanks,
Po-Kai.

**Comment by longjon** [comment]
Welcome! This tracker is for issues and bugs with Caffe. Please ask usage and installation questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) list. Thanks!

**Comment by LplusKira** [comment]
OK thx!
