### ISSUE TITLE
Merge train_val.prototxt and deploy.prototxt to one file

### ISSUE THREAD

**Issue by MartinThoma** [BVLC/caffe#2545]
This is an "enhancement issue".

Why are there two model description files (commonly named `deploy.prototxt` and `train_val.prototxt`) which do essentially the same thing?

## train_val.prototxt → deploy.prototxt

As far as I can see, the `train_va.prototxt` to `deploy.prototxt` works like this:

1. Remove input datalayer and insert a description of input data dimension
2. Remove “loss” and “accuracy” layer at the end
3. Remove weight initializations as shown in the following (is this necessary? why?)

```txt
    weight_filler {
      type: "gaussian"
      std: 0.0001
    }
    bias_filler {
      type: "constant"
    }
```

Couldn't that be done in one file? What was the reason to have two files?

**Comment by shelhamer** [comment]
You're entirely right to want to merge the definitions. See #1245 for context.

**Comment by longjon** [comment]
Closing as this is pretty much subsumed by #1245 (on which hacking has begun). We can revisit the subtleties 2 and 3 if they still matter once that issue is closed.
