### ISSUE TITLE
Preset Convergence Criteria

### ISSUE THREAD

**Issue by swamiviv** [BVLC/caffe#2549]
In the training examples provided with Caffe (imagenet or cifar), is there a way to stop the training based on some preset convergence criteria like value of the loss function or accuracy on validation data ? How and where to specify these threshold in the prototxt files ?

**Comment by longjon** [comment]
This tracker is for issues and bugs with Caffe. Please ask usage questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) list. Thanks!
