### ISSUE TITLE
draw_net.py for VGG Very Deep / Network in Network

### ISSUE THREAD

**Issue by sbrugman** [BVLC/caffe#2554]
draw_net.py seems to work for AlexNet and GoogLeNet, but for VGG Very Deep and Network in Network, it gives an empty image. Why is this?

(Example: https://gist.githubusercontent.com/ksimonyan/211839e770f7b538e2d8/raw/0067c9b32f60362c74f4c445a080beed06b07eb3/VGG_ILSVRC_16_layers_deploy.prototxt)

**Comment by melgor** [comment]
This tracker is for issues and bugs with Caffe. Please ask usage and installation questions on the caffe-users list. Thanks!

Because VGG net have old style of .prototxt (have CONVOLUTION, where new style, have "Convolutional")
Please, close this issue.

**Comment by sbrugman** [comment]
You were right, that was the issue. It would be good to throw an error when the input is not valid, rather than just returning an empty image though.
