### ISSUE TITLE
My image data is Matlab .mat file. How to let caffe read *.mat file?

### ISSUE THREAD

**Issue by civilmanxx** [BVLC/caffe#2555]
My image data is Matlab .mat file. How to let caffe read *.mat file?

**Comment by flx42** [comment]
If you use Python you can use scipy:
http://docs.scipy.org/doc/scipy-0.15.1/reference/generated/scipy.io.loadmat.html

**Comment by ronghanghu** [comment]
Maybe we should allow using MemoryDataLayer in Matlab.

**Comment by civilmanxx** [comment]
is there any concrete example about how to use python caffe for imagenet. I find most of docs are very blur below. Which .py file should I run DIRECTLY and how to pass in parameter?


https://github.com/BVLC/caffe/tree/master/python/caffe
http://caffe.berkeleyvision.org/tutorial/interfaces.html

**Comment by longjon** [comment]
This tracker is for issues and bugs with Caffe. Please ask usage questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) list. Thanks!
