### ISSUE TITLE
make test error

### ISSUE THREAD

**Issue by Eniac-Xie** [BVLC/caffe#2558]
Hi everyone!
After finishing 'sudo make all -j8' (no error), I got error when I execute 'sudo make test':

.build_release/src/gtest/gtest-all.o: In function 'testing::internal::RE::PartialMatch(char const*, testing::internal::RE const&)':
gtest-all.cpp:(.test+0x13c2): undefined reference to 'regexecA'
.build_release/src/gtest/gtest-all.o: In function 'testing::internal::RE::FullMatch(char const*, testing::internal::RE const&)':
gtest-all.cpp:(.test+0x13f2): undefined reference to 'regexecA'
.build_release/src/gtest/gtest-all.o: In function 'testing::internal::RE::~RE()':
gtest-all.cpp:(.test+0x141d): undefined reference to 'regfreeA'
gtest-all.cpp:(.test+0x1426): undefined reference to 'regfreeA'
.build_release/src/gtest/gtest-all.o: In function 'testing::internal::RE::Init(char const*)':
gtest-all.cpp:(.test+0xdc0a): undefined reference to 'regcompA'
gtest-all.cpp:(.test+0xdc35): undefined reference to 'regcompA'
collect2: ld returned 1 exit status
make: *** [.build_release/test/test_all.testbin] Error 1

Any advice would be very very helpful.
Thanks

Xie

**Comment by longjon** [comment]
This tracker is for issues and bugs with Caffe. Please ask usage and installation questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) list. Thanks!

(And please don't run `make` as root!)
