### ISSUE TITLE
Using wrapper.py with own data - what do we use in place of ilsvrc_2012_mean.npy? 

### ISSUE THREAD

**Issue by johnswan** [BVLC/caffe#256]
Hi,

I can't find anything in the documentation about this, so I'm asking here in the hope of guidance from some kind soul. ;-)

I'm trying to get predictions out of caffe using a model that I trained previously with my own image data. I used the imagenet code as a template throughout.

As far as I can tell, the only way to get predictions out is to use wrapper.py, but it refers to the ilsvrc_2012_mean.npy file. This is clearly a numpy file containing the "imagenet mean", presumably precalculated for the imagenet dataset.

However, the only mean file that I have for my data is imagenet_mean.binaryproto, created when running make_imagenet_mean.sh. 

Is this the correct data? If so, how do I convert it (I presume to a numpy array)? 

And if it's not the correct data, then how do I produce the equivalent of ilsvrc_2012_mean.npy for my own data?

Any pointers gratefully received!

Thanks
John

**Comment by Ashwani001** [comment]
@zirohut there should be a .bashrc file in your root directory

**Comment by alimurreza** [comment]
please don't add the extra path "~Documents/caffe/python/caffe/" as @johnswan did. It would cause problem later on. I faced it but got it resolved here is the reference https://github.com/BVLC/caffe/issues/1803

instead just do the following only:
export PYTHONPATH=~Documents/caffe/python:$PYTHON_PATH

**Comment by alimurreza** [comment]
If you just want to set it for a particular program from the terminal then just typing it once before excuting the program would work.
Moreover, If you want it to be automatically set up each time you open up a terminal then do the following:
- In the terminal, open up the .bashrc file as follows:
$vi ~/.bashrc
- append the following line at the very end: 
export PYTHONPATH=~Documents/caffe/python:$PYTHONPATH

**Comment by Nusrat12** [comment]
Thank you so much
