### ISSUE TITLE
osx: abs not defined absval_layer

### ISSUE THREAD

**Issue by peter254** [BVLC/caffe#2564]
When compiling on osx Yosemite the absval_layer raises a warning stating:
"warning: absolute value function 'abs' given an argument of type 'long long' but has parameter of type 'int' which may cause truncation of value"

I resolved it for me by putting the following code directly after "namespace caffe {"

```
inline long abs(long _X) {
    if (_X < 0) {
        return -_X;
    }
    else {
        return _X;
    }
}
```

**Comment by shelhamer** [comment]
Sorry, I can't reproduce this. It might have been a temporary issue with new tooling while Yosemite was young.
