### ISSUE TITLE
caffe make error

### ISSUE THREAD

**Issue by LM23** [BVLC/caffe#2566]
I get the following errors when doing make all in Caffe. I have these packages installed already.
/usr/bin/ld: cannot find -lleveldb
/usr/bin/ld: cannot find -lsnappy
/usr/bin/ld: cannot find -lboost_system
Any suggestions will be helpful,
Thanks
LM

**Comment by longjon** [comment]
Please ask usage and installation questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) list. Thanks!
