### ISSUE TITLE
`FilterLayer` usage inquiry

### ISSUE THREAD

**Issue by prclibo** [BVLC/caffe#2568]
Hi,
I was trying using the `FilterLayer` recently merged, but found that for this layer the "mask" bottom input can only be of size Nx1x1x1. I thought it is more convenient to allow "mask" blob of size NxKxHxW, which enables an element-wise filtering on the rest of bottoms (yes, this requires all bottoms to have the same size). So just wanna to inquiry if it is good to allow full 4D mask blob. Thanks.

**Comment by longjon** [comment]
This tracker is for issues and bugs with Caffe. Please ask usage questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) list. Thanks!
