### ISSUE TITLE
Layer factory breaks windows compatibility.

### ISSUE THREAD

**Issue by dtmoodie** [BVLC/caffe#2578]
Since the advent of the layer factory, windows compatibility has been broken.  The reason behind this is that Visual Studio optimizes out references that it believes are unused (IE the layer registration static variables).  Because of this layers are never registered.
Using the MSVC linker flag /OPT:NOREF does nothing, building as static or dynamic libraries does nothing.
Currently I'm in the process of attempting to manually update all layers to use a different registration scheme.  Will report back on results.
http://stackoverflow.com/questions/4383602/how-to-force-inclusion-of-unused-object-definitions-in-a-library

**Comment by shunmiao** [comment]
I followed this post and solve this problem: http://stackoverflow.com/questions/599035/force-visual-studio-to-link-all-symbols-in-a-lib-file

The following two macros are used to force visual studio to link the unused object:
#define FORCE_LINK_THIS(x) int force_link_##x = 0;
#define FORCE_LINK_THAT(x) void force_link_function_##x(void) { extern int force_link_##x; force_link_##x = 1; }

**Comment by longjon** [comment]
(Note that special compiler flags are also needed for this reason on unix systems.)

Closing as we don't test or officially support Windows. See #15. You're welcome to discuss Windows further on [caffe-users](https://groups.google.com/forum/#!forum/caffe-users).

**Comment by happynear** [comment]
@woozzu
I have seen that your caffe repository have solved this problem. However, I can't find where you have modified to achieve this. Could you teach us how to register the layers correctly in MSVC?

**Comment by woozzu** [comment]
@happynear What I have done is here woozzu/caffe@56a20347b0b05cab9382f74fc70393313ae4718d. It is hard to remember now, but it has been done like below.

libcaffe: core source, caffe: main function
caffe has a project reference to libcaffe.
1. `caffe property - Common Property - Reference - libcaffe - Project Reference Property - Library Dependency Link`: True
2. It solves the problem, but MSVC cannot link the object files of cuda codes. So, we should manually add all `*.cu.obj` files to `caffe property - Linker - Command Line` like `/DYNAMICBASE "..\libcaffe\$(Platform)\$(Configuration)\absval_layer.cu.obj"`.

If you figure out how to automatically link `*.cu.obj` files, please let me know.

**Comment by happynear** [comment]
@woozzu Thanks for your guidance. 

I haven't add `*.cu.obj`s but VS linked all the .obj files successfully. I have tested the exe file with mnist and cifar, everything works well. It seems that step 2 is not needed.

**Comment by woozzu** [comment]
@happynear Oh, that's good news. I will try, thanks!

**Comment by dtmoodie** [comment]
I too have a fixed version of caffe that builds on windows and linux.
It can be found in https://github.com/dtmoodie/caffe/tree/windows

If I remember correctly, the main issue with getting the layer factory to work was to export it, then I put the definition in a .cpp.

**Comment by happynear** [comment]
@dtmoodie
I used to use [a new cpp file](https://github.com/happynear/caffe-windows/blob/master/src/caffe/util/force_link.cpp) containing all the registers. However, I don't think it is an elegant way.

I prefer @woozzu 's solution.

**Comment by dtmoodie** [comment]
@happynear 
I just wanted to be clear that my solution can be seen here:
https://github.com/dtmoodie/caffe/blob/windows/src/caffe/layer_factory.cpp

I moved the definition of the LayerRegistry into the cpp file then instantiated it in that cpp file, that's what made 
I also decorated the class declaration with DLL_EXPORT which resolves to __declspec(dllexport) with msvc.

**Comment by dashesy** [comment]
@dtmoodie what doe you mean you used `DLL_EXPORT`? I do not see that in the code. I am building Caffe from [here](https://github.com/Microsoft/caffe) it build dll but I do not get any import library (.lib).

**Comment by willyd** [comment]
The newly merged CMake build in the windows [branch](https://github.com/BVLC/caffe/tree/windows) handles this similarly to @dtmoodie and to the SO post @shunmiao mentionned. 

The default is to build a static library and add a post build event that looks for symbols that look like the gInstantiationGuard. From this, a header with `#pragma`'s that force the symbol inclusion is generated. When consuming projects include this header (this is transparent when you include caffe/common.hpp) your binary automatically links in the required symbols because they are forced with the mentioned linker instructions.

When building a shared library the above step is not necessary has the linker will include all the defined symbols in the DLL. The DLL is built using CMake WINDOWS_EXPORT_ALL_SYMBOLS feature. This is useful since we don't have to add DLL_EXPORT all over the place but does not allow full control on what is exported what is not. Currently the shared library builds and works correctly but due to the fact that protobuf is built as a static library there is a conflict between the tests executable and the caffe.dll which makes the Solver tests fail. If anyone can come up with a fix for this I will happily merge the change.

**Comment by dashesy** [comment]
@willyd I wish I had seen your branch earlier! I was merging [MS](https://github.com/Microsoft/caffe) and [this](https://github.com/dtmoodie/caffe). As for protobuf (and other libraries) I link them all as external shared library.

**Comment by sunsided** [comment]
Hm, shared builds fail for me with the "`caffe_gpu_dot<float>` not found" linker error:

```
1>caffe.obj : error LNK2019: unresolved external symbol "void __cdecl caffe::caffe_gpu_dot<float>(int,float const *,float const *,float *)" (??$caffe_gpu_dot@M@caffe@@YAXHPEBM0PEAM@Z) referenced in function "public: float __cdecl caffe::Layer<float>::Forward(class std::vector<class caffe::Blob<float> *,class std::allocator<class caffe::Blob<float> *> > const &,class std::vector<class caffe::Blob<float> *,class std::allocator<class caffe::Blob<float> *> > const &)" (?Forward@?$Layer@M@caffe@@QEAAMAEBV?$vector@PEAV?$Blob@M@caffe@@V?$allocator@PEAV?$Blob@M@caffe@@@std@@@std@@0@Z)
1>...foobar\caffe.windows.official\build\tools\Release\caffe.exe : fatal error LNK1120: 1 unresolved externals
```

using CUDA 8, if that matters.
