### ISSUE TITLE
model zoo readme.md formatting with download_model_binary.py

### ISSUE THREAD

**Issue by phil0stine** [BVLC/caffe#2581]
With the general assumption that the steps outlined in the [model zoo wiki](https://github.com/BVLC/caffe/wiki/Model-Zoo) are the preferred method to download new models, there appear to be problems related to the assumed formatting of `readme.md` in the `download_model_binary.py` script.

For one, the script assumes a particular type of markdown heading syntax (`---`) when another is also valid (`##`). 

Also, the assumption is that the first section is valid YAML, and that the keys include `caffemodel`, `caffemodel_url`, and `sha1`. 

At least two models ([VGG](https://gist.github.com/ksimonyan/211839e770f7b538e2d8#file-readme-md) and [VGG_CNN_S](https://gist.github.com/ksimonyan/fd8800eeb36e276cd6f9#file-readme-md)) do not quite adhere to these requirements, though they are close

I have made a patch that takes care of some of these issues, but am wondering whether to pursue it further, or to instead explicitly require new models to adhere to the stated conventions.

**Comment by shelhamer** [comment]
I think the most we can do is hope that entries adhere to the format or fallback to manual fetching of model zoo models. There are too many ways to mangle the format and no way to catch them all.
