### ISSUE TITLE
Does classification.bin work fine?

### ISSUE THREAD

**Issue by RafaRuiz** [BVLC/caffe#2585]
Hello, I'm trying to call this code:

I'm calling the binary stored in caffe/build/examples/cpp_classification/

`./classification.bin ../../../examples/imagenet/imagenet_deploy.prototxt ../../../caffe_mycaffe_train_iter_10000.caffemodel ../../../data/mycaffe/mycaffe_train_mean.binaryproto ../../../examples/imagenet/labels.txt ../../../data/mycaffe/testingset/alm/alm263.png`

and with more images. This is what I get with almost all results:

---------- Prediction for ../../../data/mycaffe/testingset/alm/alm263.png ----------
Segmentation fault (core dumped)

for others, I get this:

---------- Prediction for ../../../data/mycaffe/testingset/alm/alm265.png ----------
0.0000 - "0 almweird"
0.0000 - "b(5S?M????????Accuracy?AS`(?+?I????4S?JAccuracyI?AS?(?p+??I????4S 1

                                                                             InnerProductASpܩ`?PA??I????4S1

                                                                                                           InnerProductASpN????A?hJ????4S?J?1SplitpH?AS?9???J???4SICr/lib1SplitAS?8?p?HK???4SAReshape@!X8??G?3S1Pj(5S???ameteconstantat(5S?3?-S-???3?-S?3?-S

but for some of them, I get binary code for a long time like this previous which seems that I cracked Matrix.

Is this well compiled? what's wrong ?

**Comment by flx42** [comment]
Hello, thanks for reporting the issue, can you try the following?
1) Is it working with the command given in the docs (on image `cat.jpg`)?
2) Compile in debug mode: set `DEBUG := 1` in `Makefile.config` and then prefix your command with `gdb --args` to get a nice backtrace.

**Comment by StrongK** [comment]
In classification.cpp,its output is accuracy ranked in the top five.if your types less than five,you will get "Segmentation fault".Two ways can solve your problem:
1.Increase your object types to more than five;
2.modify classification.cpp where:
   std::vector<Prediction> Classify(const cv::Mat& img, int N = 5);
 let N=1 or others.Then you should recompile it

(Forgive me for my poor English，I hope it can help you)

**Comment by flx42** [comment]
@StrongK thank you for reporting! I finally had the time to submit a simple fix.
Since it's just an example program and not a "tool", I'm silently modifying the number of classes to display in this situation.
