### ISSUE TITLE
crop_size issue

### ISSUE THREAD

**Issue by artshcherbina** [BVLC/caffe#2589]
Hello!
When setting crop_size in data layer equal to image size segmentation fault happens in data_transformer.cpp:
      h_off = Rand() % (height - crop_size);
      w_off = Rand() % (width - crop_size);
Also, this code should be fixed to 
      h_off = Rand() % (height - crop_size + 1);
      w_off = Rand() % (width - crop_size + 1);
Thank you.

**Comment by ronghanghu** [comment]
I believe this has already been fixed in #1149. Please use our latest code.

Current code: https://github.com/BVLC/caffe/blob/master/src/caffe/data_transformer.cpp#L84-L85

**Comment by artshcherbina** [comment]
Oh, thank you. 
I have forgotten to pull latest changes
