### ISSUE TITLE
Wrong when install cuda in VMware "Incomplete installation"

### ISSUE THREAD

**Issue by mjohn123** [BVLC/caffe#2591]
Hello all, I installed Ubuntu 14.04 ,64 bit in VMware. I tried to install Cuda by follow this link https://github.com/BVLC/caffe/wiki/Ubuntu-14.04-VirtualBox-VM

However, I got error as bellow. Could you suggest one way to me to solve it? Thank you so much

This is my bug

Missing recommended library: libGLU.so
Missing recommended library: libX11.so
Missing recommended library: libXi.so
Missing recommended library: libXmu.so
Missing recommended library: libGL.so

Installing the CUDA Samples in /home/toanhoi ...
Copying samples to /home/toanhoi/NVIDIA_CUDA-6.5_Samples now...
Finished copying samples.

===========
= Summary =
===========

Driver:   Not Selected
Toolkit:  Installed in /usr/local/cuda-6.5
Samples:  Installed in /home/toanhoi, but missing recommended libraries

Please make sure that
 -   PATH includes /usr/local/cuda-6.5/bin
 -   LD_LIBRARY_PATH includes /usr/local/cuda-6.5/lib64, or, add /usr/local/cuda-6.5/lib64 to /etc/ld.so.conf and run ldconfig as root

To uninstall the CUDA Toolkit, run the uninstall script in /usr/local/cuda-6.5/bin
To uninstall the NVIDIA Driver, run nvidia-uninstall

Please see CUDA_Getting_Started_Guide_For_Linux.pdf in /usr/local/cuda-6.5/doc/pdf for detailed information on setting up CUDA.

***WARNING: Incomplete installation! This installation did not install the CUDA Driver. A driver of version at least 340.00 is required for CUDA 6.5 functionality to work.
To install the driver using this installer, run the following command, replacing <CudaInstaller> with the name of this run file:
    sudo <CudaInstaller>.run -silent -driver

Logfile is /tmp/cuda_install_3082.log
Signal caught, cleaning up

**Comment by Keerthikan** [comment]
Has this issue been resolved? 
What did you do to resolve it?

I am having a similar problem  I am using Vmware fusion to virtually run ubuntu. 
I followed this guide: https://github.com/BVLC/caffe/wiki/Ubuntu-14.04-VirtualBox-VM 
I am stuck at (bulletpoint) Run the CUDA installer:
Here is my output: 

Error: unsupported compiler: 4.8.4. Use --override to override this check.
Missing recommended library: libXmu.so

Error: cannot find Toolkit in /usr/local/cuda-6.5

===========
= Summary =
===========

Driver:   Not Selected
Toolkit:  Installation Failed. Using unsupported Compiler.
Samples:  Cannot find Toolkit in /usr/local/cuda-6.5

Logfile is /tmp/cuda_install_15286.log

**Comment by Egiiegii** [comment]
I am having similar missing library problems too.
Did you find the solution?

**Comment by mjohn123** [comment]
Thank all for intersting my question. Sorry for reply late. I did not receive notify. 
My solution is very simple. I just used real machine, instead of virtual machine. The reason is that the virual machine does not support to use GPU. Thus, it cannot pass the CUDA test. If someone has other method in VMware, please share here. I am also interesting in it
