### ISSUE TITLE
spp-net first steps

### ISSUE THREAD

**Issue by etienne87** [BVLC/caffe#2593]
Does anyone tried to reproduce first steps of SPP-Net? What i would like to try is to run first half of alexnet (data -> conv5), define several levels of pyramid with custom maxpool layer in python to output blobs of different sizes, & then run second half (fc6-conv -> fc8-conv) for all the different levels in the pyramid. is there an example somewhere on how to define layers without the proto txt file?

**Comment by BlGene** [comment]
It is possible to define network structure in python, see #2086 ( as of yet unmerged). 

For python layers see [here](https://github.com/BVLC/caffe/blob/master/python/caffe/test/test_python_layer.py).

In case you haven't used caffe a lot please note that a SPP pooling layer was merged recently #2177 so specifying this from a prototxt file would probably be easiest way to get started.

This is a usage question and would belong on the mailing list.

BR, Max

**Comment by etienne87** [comment]
Thanks a lot Max! and Sorry about putting this into issues.
