### ISSUE TITLE
problem with caffenet training 

### ISSUE THREAD

**Issue by morteza94** [BVLC/caffe#2595]
Hi 
So I'm training the caffenet cnn with my own imagenet data.
I have 308 classes.

The problem is that the training process doesn't get passed the "Iteration 0, Testing net (#0)".

Does anybody have any idea what's wrong?

Thanks

**Comment by lukeyeager** [comment]
This tracker is for issues and bugs with Caffe. Please ask usage questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) list.

**Comment by morteza94** [comment]
I'm sorry
I didn't know
