### ISSUE TITLE
Trivial input / output to make sure that caffe was built correctly?

### ISSUE THREAD

**Issue by pwnall** [BVLC/caffe#2596]
I'm trying to submit a Caffe recipe to [homebrew-science](https://github.com/Homebrew/homebrew-science):
https://github.com/Homebrew/homebrew-science/pull/2402

I'm wondering what's the best way to put together a trivial test case that makes sure caffe was built and can do meaningful things without crashing. I'd have to inline the input file(s) into the recipe, so ideally they wouldn't be awfully long.

I'm asking this question because, off the top of my head, I'd try to train a tiny network on a tiny dataset, but that still requires a bunch of files.

Thank you!

**Comment by ronghanghu** [comment]
I think `make runtest` already does it. If all your tests passes successfully, then Caffe is expected to do meaningful things without crashing.

**Comment by pwnall** [comment]
`make runtest` requires a full source distribution though, right?

I was hoping for a way to sanity-check a binary that I built on one machine and copied over to a cluster.

**Comment by sguada** [comment]
Try

caffe time -model /models/bvlc_reference_caffenet/deploy.prototxt

Sergio

2015-06-16 14:32 GMT-07:00 Victor Costan <notifications@github.com>:

**Comment by jshfeng** [comment]
I think the problem has been solved and I close the issue here.
