### ISSUE TITLE
Caffe predict is slow in python

### ISSUE THREAD

**Issue by leemoon1288** [BVLC/caffe#2600]
Hello all, I have to used predict method in caffe . I have a training data with its size about 80MB (its name is age_net_model_file). I load it by this code in python

   age_net = caffe.Classifier(age_net_model_file, age_net_pretrained,
		       mean=mean,
		       channel_swap=(2,1,0),
		       raw_scale=255,
		       image_dims=(256, 256))

Now, with input image. I call predict method such as

  prediction = age_net.predict([image_input])

The result return is correct. However, the computational time is very slow. Have any suggest to speed up it? Thank you so much

**Comment by BlGene** [comment]
Try replacing:
```python:
    caffe.set_mode_cpu()
```
with:
```python
    caffe.set_mode_gpu()
 ```
Just add the second line if the first is not present. If that doesn't speed things up you could consider investing in a quicker gpu.

BR, Max

**Comment by leemoon1288** [comment]
Good job. It worked well.

**Comment by BlGene** [comment]
Then please close the issue. ;)

BR, Max
