### ISSUE TITLE
Caffe Double Precision

### ISSUE THREAD

**Issue by SuperSoulHunter** [BVLC/caffe#2604]
Hi, 

I notice that Caffe hard code the solver type to be float, is it possible to change it to double by specifying a parameter in the protocol files? Thanks.

**Comment by BlGene** [comment]
Hi,

Have a look at #1368. You should be able to change the floats in caffe/tools/caffe.cpp to doubles, but as said, it is unlikely to lead to improvements.

BR, Max

**Comment by longjon** [comment]
This tracker is for issues and bugs with Caffe. Please ask usage questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) list. Thanks!

**Comment by forever3000** [comment]
Whether I can change the precision to half? Because I want to reduce time to classify on TK1 Jetson board. Normally it will take about 50ms for classification on each image, I want to optimize to 5ms.
