### ISSUE TITLE
Does caffe SGD solver shuffle training data in each epoch?

### ISSUE THREAD

**Issue by zer0n** [BVLC/caffe#2606]
If yes, how does it shuffle data for very large datasets (e.g. ImageNet)?

**Comment by amiralush** [comment]
Nope. There is no shuffling of the dataset. I guess because it's very expensive to re create the dataset or doing random access rather than consecutive access.

**Comment by talda** [comment]
The solver doesn't, but some of the data layers do. For example image data layerhas a "shuffle" parameter that reshuffles the data every epoch.

**Comment by longjon** [comment]
This tracker is for issues and bugs with Caffe. Please ask usage questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) list. Thanks!
