### ISSUE TITLE
How to compute precision and recall?

### ISSUE THREAD

**Issue by ruoyanwang** [BVLC/caffe#262]
I'm setting up a CNN for human pose estimation. I'm not sure how to compute precision and recall rate on training/validation set. Has it been achieved in R-CNN?

**Comment by jenifferYingyiWu** [comment]
How to implement getting the  "precision" and "recall" from the val.txt file (which has been tested by Caffe model).

**Comment by jenifferYingyiWu** [comment]
The val.txt file has testing images and labels, which have been tested by Caffe model.
     After the images in train.txt haven been trained, and the images in val.txt have been tested.
How to calculate the "precision" and "recall" from the val.txt file (which has been tested by Caffe model)?
    Could you pls help to recommend some python codes?

**Comment by seanbell** [comment]
@jenifferYingyiWu it seems like you've asked this question several times on different pages.  Please refrain from spamming, as it adds noise and isn't productive for the community.  Please ask for help on the user mailing list ([caffe-users list](https://groups.google.com/forum/#!forum/caffe-users)).
