### ISSUE TITLE
Accuracy for Contrastive Loss Layer

### ISSUE THREAD

**Issue by swamiviv** [BVLC/caffe#2626]
For computing the Contrastive Loss, I want to compute the accuracy for the validation set for the labels provided. As of now, the Contrastive Loss layer takes as inputs the feature vectors computed from previous layers and computes the average loss. I want to modify the layer to take in the label information and compute the accuracy as follows:

`acc=0`
` for i = each_sample_in_batch`
`if((loss(i) > margin & label(i) == 0) || (loss(i) <= margin & label(i) == 1) ) `
       `acc++`
`end`
`acc/=(size_of_batch)`

It should be noted that the loss should be computed here for each sample as compared to the way its done in the contrastive_loss_layer.cpp file. Also, I want to change the layer definition to include the label information to be able to perform this accuracy computation - both of which I am finding it hard to do. Any help/pointers would be great.

**Comment by longjon** [comment]
This tracker is for issues and bugs with Caffe. Please ask usage and application questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) list. Thanks!
