### ISSUE TITLE
Model file Cannot be loaded (deploy.prototxt)

### ISSUE THREAD

**Issue by gopi1989** [BVLC/caffe#2627]
In Caffe i was tried to load Model file such as deploy.prototxt but the file cannot be loaded. I have issue in that Line [ net = new caffe::Net<float>(netArchitecture, caffe::TEST); ]
I passing a path such as /data/data/com.example.smile/app_assets/deploy.prototx.

**Comment by jshfeng** [comment]
This tracker is used for reporting bugs and issues with caffe. For the questions about the usage, please refer to the mail list: https://groups.google.com/forum/#!forum/caffe-users
