### ISSUE TITLE
Access middle layer feature with matcaffe

### ISSUE THREAD

**Issue by MarcoSaku** [BVLC/caffe#2631]
Hi all! I need to access to features in middle layers using Matlab. When I use caffe('forward') I can only access to features of the last layer of CNN. Any help? Thanks all

**Comment by ronghanghu** [comment]
@MarcoSaku you should pull the latest caffe to use the new matlab wrapper to access features of any layer. Usages of this new wrapper can be seen at http://caffe.berkeleyvision.org/tutorial/interfaces.html#matlab

However, this tracker is for issues and bugs with Caffe. Please ask usage questions on the [caffe-users](https://groups.google.com/forum/#%21forum/caffe-users) list.
