### ISSUE TITLE
debug with parallel branch

### ISSUE THREAD

**Issue by dzhwinter** [BVLC/caffe#2633]
i'm not sure its proper open an issue here, There is a bug in  #2219  ,(may be depend on my GPU environment).  my train procedure always failed after hundred iterations. Hard to reproduce and locate. I want to fix it myself or  report it after locating it 
I'm not familiar with cuda-gdb how to debug parallel cuda program because I used to log the mid result and fix the bug , I have read some tutorial about cuda-gdb, but still stuck in here.
How are you guys debug  the layer_xxx_.cu source code? use Logging tool with print? or cuda-gdb advanced trick i didn't know?
 It is great value. Any suggestion is welcome.  thank you in advance.

**Comment by longjon** [comment]
Closing as this is a PR issue; discuss on the PR (and ask usage questions on [caffe-users](https://groups.google.com/forum/#!forum/caffe-users)). But note that #2219 is still pretty experimental; there are no guarantees and you're probably on your own for debugging.
