### ISSUE TITLE
Clarify Caffe Batch vs. Deploy pre-processing

### ISSUE THREAD

**Issue by fferrara** [BVLC/caffe#2643]
Hi there. I can't work the Caffe preprocessing out, and it seems I'm not the only one. Sorry, I know it's a mailing-list problem, but I posted there and nobody could answer that.

The confusion raises from the pre-processing needed in order to use a Imagenet-pretrained model. What are the best practices?

[Here](https://groups.google.com/forum/#!topic/caffe-users/zzoqxAdyPSk) and [here](https://groups.google.com/forum/#!msg/caffe-users/3gi8MrSJTvU/7CXEqVyolZkJ) are two related threads. I know that #1245 is supposed to fix it, but meanwhile we get different results depending on the prototxt employed.

When we use the python Net object and load the classic _deploy.prototxt_ model, which includes 
_input_ fields, we should take care of the entire pre-processing:
- Image resizing&cropping
- Transposing
- Mirroring
- Channel swap (from RGB to BGR)
- Image scaling (from [0,1] to [0,255])
- Normalizing (mean subtraction)

Something like:
```python
transformer = caffe.io.Transformer({'data': net.blobs['data'].data.shape})
# setup transformer...
net.blobs['data'].reshape(1,3,227,227)
net.blobs['data'].data[...] = transformer.preprocess('data', caffe.io.load_image(image))
net.forward()
```

When, instead, we use the python Net object but we load a _train\_val.prototxt_ that contains a proper Data layer, things get tricky. We can handle:
- image resizing&cropping
- mean subtraction
- mirroring

via _transform\_params_. So, it's just loading the train_val file and 
```python
net.forward()
```
But, what about Channel swap and Image scaling, for example? Are they handled by the Data layer, or we need to manually implement them? Since the layer loads the data in batches, it seems that we need to pre-process the entire dataset **before** feeding the net.

Someone suggested the operations are embedded in the code responsible for creating the LMDB dataset, but I can't find any reference in the code.

**Comment by pathak22** [comment]
You have to transform them before feeding into the layer.
Sorry to hear that you couldn't get much help on caffe users. But this issue tracker is primarily dedicated for development issues. Thanks!
