### ISSUE TITLE
Build MatCaffe issue

### ISSUE THREAD

**Issue by ChrysLiang** [BVLC/caffe#2646]
Hi ALL,

I am new to Caffe. I am trying build MatCaffe (in windows) according the instruction as stated in http://caffe.berkeleyvision.org/tutorial/interfaces.html

When I run the command, make all matcaffe, I got the error as shown in the attached file. 

Can anyone give me some hints on the cause of the problem? Thanks very much!

![make_error](https://cloud.githubusercontent.com/assets/13046119/8350174/b7e7e8ac-1b55-11e5-86a6-459d1c25c4be.jpg)

**Comment by ronghanghu** [comment]
Window is not officially supported for caffe (and its interfaces) (however, there has been several community versions for windows).

This tracker is for issues and bugs with Caffe. Please ask usage questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) list. Thanks!
