### ISSUE TITLE
Windows caffe：How to parse string value type in layer param

### ISSUE THREAD

**Issue by dreadlord1984** [BVLC/caffe#2647]
caffe env：almost latest version caffe-master （build in VS2012）.
I found the new protobuf could parse the layer type with string value，for example
layer {
  name: "mnist"
  type: "Data"
  top: "data"
  top: "label"
  ....
}
But，my protobuf only parse the layer type with numerical value， for example
layer {
  name: "mnist"
  type: DATA
  top: "data"
  top: "label"
  ....
}
I tried to use protobuf version 2.5 and 2.6.1. But these version could not parse【 type: "Data"】. I don't know which version of protobuf could parse 【 type: "Data"】. I built the latest version 3.0 failed in vs2012. Although i built 3.0 in vs2013，but had link error with caffe(MSVC 1700 VS MSVC 1800).
Thanks.

**Comment by pathak22** [comment]
It doesn't appear to be a problem in protobuf. If you think its a bug in caffe and can reproduce it with the latest master then feel free to report it.
https://github.com/BVLC/caffe/wiki/Reporting-Bugs-and-Other-Issues
