### ISSUE TITLE
MemoryDataLayer Reshape C++ problem

### ISSUE THREAD

**Issue by mnmoustafa** [BVLC/caffe#2648]
I am trying the net surgery (a fully convolutional network) example in C++. I am using MemoryDataLayer so I can feed the network from memory (images with different sizes). For each new image, I call Reshape for my input blob and Reshape() for my net to accommodate the new input image size. However, MemoryDataLayer::AddMatVector fails with:

```
F0626 01:56:41.623599 12815 data_transformer.cpp:260] Check failed: img_height == height (1116 vs. 600)
```

So even after Reshape, MemoryDataLayer batch_size(), channels(), height(), and width() is still using the original image dimensions (from the proto file, 600 in my case above). On the other hand, the blobs dimensions have been correctly updated.

Is this a bug or a misuse from my side?
Thanks,

**Comment by matsypaev** [comment]
Hi,

I have the similar problem. It would be nice if somebody could help.

Thank you.

**Comment by smartbitcoin** [comment]
if you use memory data layer,  it's better write your own c++ code to feeding the data. I feeding csv file into memory data layer with my own code and found that the memory data layer is a pretty simple implementation so far. with your own code, you get more flexibility how the data format you like to  pump in.

**Comment by matthieu637** [comment]
I've got the same problem with the MemoryDataLayer.
In my case, I need only to increase the batch size, luckily there is a set_batch_size() function for MemoryDataLayer that must be called when I use Reshape on the blob&network.

For the channels, height, width don't know how to fix it.

**Comment by YohanBreux** [comment]
I came across the same problem.
In fact, MemoryDataLayer has no reimplementation of the function : 

> void Reshape(const vector<Blob<Dtype>*>& bottom, const vector<Blob<Dtype>*>& top) 

 inherited from baseDataLayer parent class (which do nothing by default).

So I have just added in MemoryDataLayer.cpp : 

```
template <typename Dtype>
void MemoryDataLayer<Dtype>::Reshape(const vector<Blob<Dtype>*>& bottom,
                                     const vector<Blob<Dtype>*>& top) {
  const vector<int>& dataShape = top[0]->shape();
  batch_size_ = dataShape[0];
  channels_   = dataShape[1];
  height_     = dataShape[2];
  width_      = dataShape[3];
} 
```

**Comment by shelhamer** [comment]
Closing according to #5528
