### ISSUE TITLE
Solver Type

### ISSUE THREAD

**Issue by anurikadisha** [BVLC/caffe#2649]
Hi,
Can anyone tell me where can I set the solver type (SGD, NESTEROV, ADAGRAD) to train the data?
Also, what is the solver that has been used in caffenet model training for ImageNet data?

**Comment by dreadlord1984** [comment]
In the solver.prototxt, you can set solver_type : SGD (or NESETEROV, AGAGRAD). Just like set base_lr: 0.001, gamma: 0.001. I found it form the caffe.proto. But i don't know which solver_type has been used in ImageNet data. You can try it, i don't have the imagenet data for test.

**Comment by anurikadisha** [comment]
Okay thanks a lot !! :)
