### ISSUE TITLE
ALEXnet models

### ISSUE THREAD

**Issue by arashmh** [BVLC/caffe#2650]
Hi
I'm relatively new to deep learning. I was wondering which of the models described in model zoo , are actually of ALEXnet type ?

**Comment by fariba-abbasi** [comment]
Hi
The network definition (models/bvlc_reference_caffenet/train_val.prototxt) follows the one in Krizhevsky et al. see this link for more information:
http://caffe.berkeleyvision.org/model_zoo.html

**Comment by seanbell** [comment]
Note that caffenet doesn't quite follow Krizhevsky et al.  It's nearly the same and performs the same, but if you want exactly AlexNet, you should use the "alexnet" model.

**Comment by arashmh** [comment]
So does it mean that basically all models built in Caffe are more or less of AlexNet type ?

**Comment by seanbell** [comment]
No.  Look at what the models say.  They will list themselves as "AlexNet" or "Krizhevsky et al" or "CaffeNet" if they are of "AlexNet type".

There are a variety of architectures; some popular ones include: AlexNet/CaffeNet, VGG-16, GoogLeNet, NIN (Network in Network), FCN (Fully Convolutional Network).

This really isn't the right place for this discussion -- Github issues are for actual issues with the code, not for model discussions.  Please close the issue and continue it on the ["Caffe Users" google group](https://groups.google.com/forum/#!forum/caffe-users).
