### ISSUE TITLE
HDF5DataLayer documentation

### ISSUE THREAD

**Issue by DavidYoungSoton** [BVLC/caffe#2652]
Is there documentation that describes what the HDF5DataLayer expects to find in the input file? I've looked at the demo in caffe/matlab/hdf5creation, which is clearly helpful, but what I was hoping for is a document setting out what the file contents should be in general.

The source code doesn't seem to have any useful comments - I get the impression that it should somehow be obvious, but I'm afraid it isn't.

**Comment by Tgaaly** [comment]
If you mean the prototxt script, then it should be something like this:

```  
layer {
  name: "data"
  type: "HDF5Data"
  top: "data"
  hdf5_data_param{
	source: "<path_to_txt_file_produced_by_matlab_hdf5creation>/list.txt"
  	batch_size: 100
  }
  include{
	phase: TRAIN
  }
}
```

**Comment by DavidYoungSoton** [comment]
Thank you Tgaaly. Yes, it's the contents of the hdf file itself that I'm not sure about. I'll try and work from the demo and I guess it will become clearer with a bit more experience of Caffe.
