### ISSUE TITLE
Training Caffe on my own dataset for object localization

### ISSUE THREAD

**Issue by mtrth** [BVLC/caffe#2653]
I am new to caffe. I am trying to use caffe on my own dataset to perform object localization.I am following this blog to train caffe on my own dataset http://sites.duke.edu/rachelmemo/2015/04/03/train-and-test-lenet-on-your-own-dataset/. I was able to train and test the model as mentioned in the blog. For the next step object localization I am using the example to https://github.com/BVLC/caffe/blob/master/examples/detection.ipynb . But when I run the command to convert the data to .h5 format as mentioned in example using the command

./python/detect.py --crop_mode=selective_search --pretrained_model=./examples/trial/trial_iter_10000.caffemodel --model_def=./examples/trial/trial.prototxt --gpu --raw_scale=255 _temp/det_input.txt _temp/det_output.h5

where,

pretrained_model=./examples/trial/trial_iter_10000.caffemodel (new model based on my dataset) and

--model_def=./examples/trial/trial.prototxt (new model def )

I am getting the error:

Check failed: ShapeEquals(proto) shape mismatch (reshape not set)
*** Check failure stack trace: ***

But all my inputs are of same size 64*64.

**Comment by pathak22** [comment]
please ask usage questions on [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) -- this issues tracker is primarily for Caffe development discussion. Thanks!
