### ISSUE TITLE
Can caffe simultaneously load 2 models in a finetuning network?

### ISSUE THREAD

**Issue by haochen593** [BVLC/caffe#2654]
A finetuning network has two streams, each stream load respective well-trained model, then the top layer of the two streams are connected to the same fully connection layer, as a whole finetuning net.

Can caffe simultaneously load 2 models and recognize the different well-trained mode corresponding to which stream in a finetuning network?

Thanks in advance.

**Comment by pathak22** [comment]
Please ask usage questions on [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) -- this issues tracker is primarily for Caffe development discussion. Thanks!
