### ISSUE TITLE
GNU date error recurring

### ISSUE THREAD

**Issue by swamiviv** [BVLC/caffe#2655]
I am getting this error during training a network (when its setting up the inner product layer)
https://github.com/BVLC/caffe/issues/1993

I debugged with gdb and this is more specific info on the error("bn" is supposed to be an inner product layer) :

---

I0627 16:51:52.707917 27561 layer_factory.hpp:74] Creating layer bn
I0627 16:51:52.707973 27561 net.cpp:90] Creating Layer bn
I0627 16:51:52.707999 27561 net.cpp:413] bn <- pool4
I0627 16:51:52.708044 27561 net.cpp:371] bn -> bn
I0627 16:51:52.708084 27561 net.cpp:120] Setting up bn
Works 1
1 1
[libprotobuf FATAL /usr/include/google/protobuf/repeated_field.h:613] CHECK failed: (index) < (size()): 
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  CHECK failed: (index) < (size()): 

Program received signal SIGABRT, Aborted.
[Switching to Thread 0x7fffb42b5700 (LWP 27578)]
0x00007ffff65f3cc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56  ../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.

---

Any help would be appreciated.

**Comment by Cindyniu** [comment]
Hi, I have met the same problem. Have you solved the issue yet?

**Comment by shelhamer** [comment]
This looks like a system configuration issue and not a Caffe issue.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
