### ISSUE TITLE
Image Data Layer test Fails

### ISSUE THREAD

**Issue by TheLegendAli** [BVLC/caffe#2656]
I'm trying to run caffe on Centos(6.6). At first attempt I'm trying to make the CPU only version to work and then once that works I will try to install the GPU version.

make all -j8 and make test work without problem. But when I do make runtest I get the following problem:

[----------] 4 tests from ImageDataLayerTest/0, where TypeParam = caffe::CPUDevice<float>
[ RUN      ] ImageDataLayerTest/0.TestResize
**\* Aborted at 1435481957 (unix time) try "date -d @1435481957" if you are using GNU date ***
PC: @     0x2b0510412d16 boost::thread::start_thread()
**\* SIGSEGV (@0x20) received by PID 31750 (TID 0x2b051d0fb4c0) from PID 32; stack trace: ***
    @     0x2b051179b710 (unknown)
    @     0x2b0510412d16 boost::thread::start_thread()
    @     0x2b0510f61b55 boost::thread::thread<>()
    @     0x2b0510f616a1 caffe::InternalThread::StartInternalThread()
    @     0x2b0510f7701b caffe::BasePrefetchingDataLayer<>::CreatePrefetchThread()
    @           0x494a30 caffe::Layer<>::SetUp()
    @           0x55d64e caffe::ImageDataLayerTest_TestResize_Test<>::TestBody()
    @           0x68ac7d testing::internal::HandleExceptionsInMethodIfSupported<>()
    @           0x67cb71 testing::Test::Run()
    @           0x67cc57 testing::TestInfo::Run()
    @           0x67cd97 testing::TestCase::Run()
    @           0x681c9f testing::internal::UnitTestImpl::RunAllTests()
    @           0x68a82d testing::internal::HandleExceptionsInMethodIfSupported<>()
    @           0x67c19a testing::UnitTest::Run()
    @           0x490e82 main
    @     0x2b05119c8d5d __libc_start_main
    @           0x490d59 (unknown)
make: **\* [runtest] Segmentation fault
1. I'm not sure what that means? any one knows?
2. How can I debug it to see where this error takes place?

**Comment by kyokim751** [comment]
I have the same issue on thinkpad T430 compiled with CPU_ONLY on
and on my desktop with CUDA 8 with AMD-FX4100 with GTX 560.
Both machines use Ubuntu 16.10

**Comment by evertonberz** [comment]
@kyokim751  
same issue here on my laptop using Ubuntu 16.10, compiled with CPU_ONLY.
did you get any solution?

**Comment by alpop** [comment]
I have (almost) the same  issue with Ubuntu 16.10 on 'make runtest'. 
NVIDIA-Digits-Detectnet/Caffe is working ok though (KITTY example).
Caffe was built with OpenCV 2.4.9. 

Earler I built  Caffe with  OpenCV 3.2.0-dev  (3.2.0-5-g23e53a3)
and  did not have this problem but was not able to get  KITTY example   working.

Just in case here  is output of failing test:
[----------] 4 tests from ImageDataLayerTest/0, where TypeParam = caffe::CPUDevice<float>
[ RUN      ] ImageDataLayerTest/0.TestRead
[       OK ] ImageDataLayerTest/0.TestRead (62 ms)
[ RUN      ] ImageDataLayerTest/0.TestResize
*** Aborted at 1483483586 (unix time) try "date -d @1483483586" if you are using GNU date ***
PC: @     0x7f5ee43360ba (unknown)
*** SIGSEGV (@0xfffffffffffffff7) received by PID 16797 (TID 0x7f5eba8b5700) from PID 18446744073709551607; stack trace: ***
    @     0x7f5ee5601630 (unknown)
    @     0x7f5ee43360ba (unknown)
    @     0x7f5ee433618b (unknown)
    @     0x7f5ee4337ce8 (unknown)
    @     0x7f5ee4336692 (unknown)
    @     0x7f5ee4331020 (unknown)
    @     0x7f5ee432f165 tbb::internal::allocate_root_with_context_proxy::allocate()
    @     0x7f5ee74e6e22 cv::parallel_for_()
    @     0x7f5ee6dcdb2a (unknown)
    @     0x7f5ee6dcabb7 cv::resize()
    @     0x7f5ee60742ca caffe::ReadImageToCVMat()
    @     0x7f5ee5fa3bd5 caffe::ImageDataLayer<>::load_batch()
    @     0x7f5ee5f3613f caffe::BasePrefetchingDataLayer<>::InternalThreadEntry()
    @     0x7f5ee5ef1605 caffe::InternalThread::entry()
    @     0x7f5ee6a8d596 (unknown)
    @     0x7f5ee55f76ca start_thread
    @     0x7f5ee53310af clone
Makefile:538: recipe for target 'runtest' failed
make: *** [runtest] Segmentation fault (core dumped)

**Comment by shelhamer** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

**Comment by ravikrn** [comment]
I am having same issue. Did you guys found some solution?
