### ISSUE TITLE
How to do multi-view test in caffe?

### ISSUE THREAD

**Issue by AIROBOTAI** [BVLC/caffe#2659]
Dear all,

Multi-view test is very useful to boost the performance. However, by now caffe seems not support multi-view test. Could anyone tell me how to do this in caffe? Thanks!

**Comment by Coldmooon** [comment]
@AIROBOTAI Have you found any way to make multi-view test ?

**Comment by AIROBOTAI** [comment]
@Coldmooon I wrote some codes in caffe, not an elegant solution, but can meet my needs...

**Comment by Coldmooon** [comment]
@AIROBOTAI Now I know the matlab example can do this. However, could you public your codes?
