### ISSUE TITLE
Specify Per Layer CPU or GPU

### ISSUE THREAD

**Issue by ChrisWC** [BVLC/caffe#2661]
Is there a way to specify a specific layer to run on the cpu rather than the gpu, but still let the other layers run on the gpu? I'm trying to run SoftmaxWithLossLayer on the cpu since we are getting issues with running it on the gpu. It would be a nice feature to have if it doesn't exist already.

**Comment by shelhamer** [comment]
Per-layer device placement is not currently possible nor planned but see #1500 for a gradual diffusion of mode and device.
