### ISSUE TITLE
how to create a new imagenet.bet.pickle file my own

### ISSUE THREAD

**Issue by zhaozhijun1988** [BVLC/caffe#2662]
I have trained a model myself,I want to use it in a web demo,so I read the example/web_demo/app.py code,
'bet_file': (
            '{}/data/ilsvrc12/imagenet.bet.pickle'.format(REPO_DIRNAME)),

in this line code,i don't kown the 'imagenet.bet.pickle' file how to create, is it necessary,who can tell me how to solve the problem, thanks.

**Comment by longjon** [comment]
Closing as this looks like a usage issue/request for help.

This tracker is reserved for specific Caffe development issues and bugs; please ask usage questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) list.

For more information, see our [contributing guide](https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md).

Thanks!
