### ISSUE TITLE
Training Caffe on ILSVRC2012 dataset occupies 120GB memory?

### ISSUE THREAD

**Issue by wpqmanu** [BVLC/caffe#2675]
Hi All,

This question might be just basic, but I am just wondering that why training on ILSVRC 2012 dataset occupies the memory the same size of the dataset (around 120GB)?
![capture](https://cloud.githubusercontent.com/assets/2476427/8465972/f4cb0e0a-2002-11e5-94fb-5786a2b9de2f.PNG)

I assume everything should be done on GPU via batching, and the GPU memory consumption seems OK (around 2GB). 
![capture2](https://cloud.githubusercontent.com/assets/2476427/8465977/fcac7bb8-2002-11e5-84f4-83a8ac214444.PNG)

Is it because I set up thing wrong somewhere? Is there a way to reduce the RAM consumption? Thanks!

**Comment by rayz0620** [comment]
It may be because of LMDB. LMDB uses memory mapping for disk IO. If your memory is large enough, it gradually reads all data into the memory and keeps it there.

**Comment by wpqmanu** [comment]
@rayz0620 Thanks! But is there a way to reduce the memory usage, as we may want to train another network on another GPU?

**Comment by rayz0620** [comment]
@wpqmanu You can just run multiple instances of caffe. The OS will swap data into and out of memory automatically. If you are running with the same LMDB data, it does not even need to swap memory.

**Comment by longjon** [comment]
Closing as this looks like an LMDB artifact rather than a Caffe issue; see https://lmdb.readthedocs.org/en/release/#memory-usage.
