### ISSUE TITLE
osx make fails (error: expected a ";") incompatible with boost 1.58

### ISSUE THREAD

**Issue by forresto** [BVLC/caffe#2678]
`brew install boost` with 1.57 with these instructions made it possible for me to build: http://itinerantbioinformaticist.blogspot.fi/2015/05/caffe-incompatible-with-boost-1580.html

**Comment by dplarson** [comment]
Boost 1.59.0 was released yesterday (http://www.boost.org/users/history/version_1_59_0.html), but unfortunately, it appears this error persists in 1.59.0.

**Comment by shelhamer** [comment]
Closing as I believe this is fixed in more recent OS X and boost versions.
