### ISSUE TITLE
Averaged SGD for sparse data

### ISSUE THREAD

**Issue by PiranjaF** [BVLC/caffe#2680]
Has anyone ever implemented Averaged Stochastic Gradient Descent (ASGD) for Caffe as described in research.microsoft.com/pubs/192769/tricks-2012.pdf?

It is supposedly useful for training on sparse datasets. As the performance of CNNs are improving and deep learning is spreading to more and more areas, I believe that it would be useful to have. Due to the fixed-size matrix format, the data representation for a CNN on new tasks may very well be sparse. I'm performing classifcation on a sparse dataset right now with good results. However, my training could be improved, which is why I'm interesting in ASGD.

I also guess that any type of signal (image/audio) with a lot of background noise could benefit from removing the noise (subtract the image with mean of noise and force remaining parts of the noise to zero) and then use ASGD for training.

**Comment by shelhamer** [comment]
Closing for lack of interest, but thank you for raising this potential direction for sparse optimization.
