### ISSUE TITLE
convert_imageset is very slow, not normal?

### ISSUE THREAD

**Issue by zizhaozhang** [BVLC/caffe#2681]
Hi,

I realize it is very slow to convert data to lmdb using caffe toolkit convert_imageset. It tooks about 10 hours by converting 2 millions images with the size of 95*95. My friend's caffe is much faster (6 millions in 4 hours). He has similar computer configuration with me (CPU and hard drive). The weird thing is when I am converting, the tool does not use much memory and CPU. The only difference with my friend's is the version of caffe (I use the latest one he has a older version),and he use ATLAS and I use OpenBlas. Is there anyone know how to solve this problem?

**Comment by zizhaozhang** [comment]
And as more and more data being processed. The speed convert every 1000 images goes down. Is this the problem of overhead of writing disk?

**Comment by CHUNYUWANG** [comment]
Have you solved the problem?

**Comment by shelhamer** [comment]
Closing as irreproducible without further system detail.  This tool does not usually slow down during use.
