### ISSUE TITLE
Ubuntu install instructions are missing a dependency for Ubuntu 12.04

### ISSUE THREAD

**Issue by semitrivial** [BVLC/caffe#2683]
I'm referring to this page: http://caffe.berkeleyvision.org/install_apt.html

The protobuf-compiler dependency is missing for Ubuntu 12.04.

(It appears that this package *is* available from apt-get in 12.04)

I'd be happy to submit a pull request, but the page in question doesn't seem to be part of the repo.

**Comment by lukeyeager** [comment]
> the page in question doesn't seem to be part of the repo

Sure it is!

https://github.com/BVLC/caffe/blob/master/docs/install_apt.md

**Comment by longjon** [comment]
Closing as fixed by opener in #2712. Thanks!
