### ISSUE TITLE
How to change the batch size dynamically?

### ISSUE THREAD

**Issue by chwangaa** [BVLC/caffe#2684]
In pycaffe particular

Is there any ways we can change the batch_size dynamically without modifying the prototxt file ?

I noticed the method ``reshape``, but apparently it does not really change the shape, as after I run ``forward()``, the shape will have be altered back to its original shape

Many thanks

**Comment by chwangaa** [comment]
Basically I am trying to see the relationship between the batch size and the running time

**Comment by seanbell** [comment]
You need to reshape the input blob and then call reshape on the net, before calling forward.

**Comment by chwangaa** [comment]
I did the following
``
net.blobs['data'].reshape(BLOCK_SIZE, DIMENSION, HEIGHT, WIDTH)
net.blobs['label'].reshape(BLOCK_SIZE, )
net.reshape()
``

The shape of every layer changes correctly. However, as soon as I run `forward`, the shape will automatically change back :-(

**Comment by lukeyeager** [comment]
[This example](https://github.com/NVIDIA/DIGITS/blob/digits-2.0/examples/classification/example.py) may be helpful to you. See the code in `forward_pass()`:

```python
for chunk in [caffe_images[x:x+batch_size] for x in xrange(0, len(caffe_images), batch_size)]:
    new_shape = (len(chunk),) + tuple(dims)
    if net.blobs['data'].data.shape != new_shape:
        net.blobs['data'].reshape(*new_shape)
    for index, image in enumerate(chunk):
        image_data = transformer.preprocess('data', image)
        net.blobs['data'].data[index] = image_data
    output = net.forward()[net.outputs[-1]]
```

**Comment by chwangaa** [comment]
Somehow I cannot manage to have it work. I am not trying to classify here. So I used the method suggested above to change the batchSize to 1000. However, the running time of forward does not even slightly alter, (i.e. when I modify the value in prototxt file the running time will be longer). Therefore I think the above method does not work

**Comment by shelhamer** [comment]
Please discuss usage on caffe-users; I've answered in the thread [Regarding Change BatchSize in python](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/caffe-users/hqXJovy2-DQ/y3Z24vv_vzQJ).

**Comment by shellyfung** [comment]
@chwangaa Did you get the answer?

>Basically I am trying to see the relationship between the batch size and the running time
