### ISSUE TITLE
i am trying to install caffe in my ubuntu 14.04 system, i have downloaded the caffe-master from github. now when i did make all i am geting this error..can someone tell me how to overcome this issue

### ISSUE THREAD

**Issue by surajits** [BVLC/caffe#2685]
i am trying to install caffe in my ubuntu 14.04 system, i have downloaded the caffe-master from github. now when i did make all i am geting this error..can someone tell me how to overcome this issue

root@tesla-S2050-host:/home/dmacs7/caffe-master# make all
CXX/LD -o .build_release/tools/compute_image_mean.bin
.build_release/lib/libcaffe.so: undefined reference to `cblas_sgemv'
.build_release/lib/libcaffe.so: undefined reference to `cblas_dgemm'
.build_release/lib/libcaffe.so: undefined reference to `cblas_sscal'
.build_release/lib/libcaffe.so: undefined reference to `cblas_dgemv'
.build_release/lib/libcaffe.so: undefined reference to `cblas_saxpy'
.build_release/lib/libcaffe.so: undefined reference to `cblas_ddot'
.build_release/lib/libcaffe.so: undefined reference to `cblas_dasum'
.build_release/lib/libcaffe.so: undefined reference to `cblas_sgemm'
.build_release/lib/libcaffe.so: undefined reference to `cblas_dscal'
.build_release/lib/libcaffe.so: undefined reference to `cblas_scopy'
.build_release/lib/libcaffe.so: undefined reference to `cblas_sasum'
.build_release/lib/libcaffe.so: undefined reference to `cblas_daxpy'
.build_release/lib/libcaffe.so: undefined reference to `cblas_dcopy'
.build_release/lib/libcaffe.so: undefined reference to `cblas_sdot'
collect2: error: ld returned 1 exit status
make: *** [.build_release/tools/compute_image_mean.bin] Error 1

**Comment by jmhessel** [comment]
I am having the same issue -- I'll let you know if I figure something out.

**Comment by jmhessel** [comment]
I had the same issue. What does your makefile.config look like?

**Comment by surajits** [comment]
hii.... i set BLAS:= open in my makefile.config  and i did "make all"...and it worked. But when i typed the next command "make test"..then again i am geting the same error.....if u figured out just let me know
thnks :)

**Comment by jmhessel** [comment]
Did you try doing a make clean before you re-made with this setting fixed?

**Comment by surajits** [comment]
yeah i did,,,,,even i tried to install again and again..is ur make all
command working??.....i feel there some is reference problem in
caffe_master folder

**Comment by surajits** [comment]
now the problem is here in the test directory..test_caffe_main.cpp.....it stops here...
root@tesla-S2050-host:/home/dmacs7/caffe# make runtest
CXX/LD -o .build_release/test/test_all.testbin src/caffe/test/test_caffe_main.cpp
/usr/lib/libcaffe.so: undefined reference to `cblas_sgemv'
/usr/lib/libcaffe.so: undefined reference to `cblas_dgemm'
/usr/lib/libcaffe.so: undefined reference to `cblas_sscal'
/usr/lib/libcaffe.so: undefined reference to `cblas_dgemv'
/usr/lib/libcaffe.so: undefined reference to `cblas_saxpy'
/usr/lib/libcaffe.so: undefined reference to `cblas_ddot'
/usr/lib/libcaffe.so: undefined reference to `cblas_dasum'
/usr/lib/libcaffe.so: undefined reference to `cblas_sgemm'
/usr/lib/libcaffe.so: undefined reference to `cblas_dscal'
/usr/lib/libcaffe.so: undefined reference to `cblas_scopy'
/usr/lib/libcaffe.so: undefined reference to `cblas_sasum'
/usr/lib/libcaffe.so: undefined reference to `cblas_daxpy'
/usr/lib/libcaffe.so: undefined reference to `cblas_dcopy'
/usr/lib/libcaffe.so: undefined reference to `cblas_sdot'
collect2: error: ld returned 1 exit status
make: *** [.build_release/test/test_all.testbin] Error 1

**Comment by longjon** [comment]
Closing as this does not appear to be a bug with Caffe, but an issue with build configuration/dynamic linking. Please ask installation questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) list. Thanks!

**Comment by DanlanChen** [comment]
Have you solved the problem?

**Comment by ysh329** [comment]
@DanlanChen Have you solved the problem too? :crying_cat_face:

**Comment by Merlin2013** [comment]
check if there is a space in BLAS := mkl
make sure no space after mkl

**Comment by Merlin2013** [comment]
check if there is a space after BLAS := mkl
make sure no space after mkl

**Comment by SoraTrails** [comment]
@Merlin2013 Your answer worked for me! Thank you very much!!
