### ISSUE TITLE
make pycaffe error

### ISSUE THREAD

**Issue by tonyyang1993** [BVLC/caffe#2687]
I was trying to install python caffe, following instruction on [compilation](http://caffe.berkeleyvision.org/installation.html#compilation).

`make all`, `make test` and `make runtest` have been done successfully.

After downloaded and installed Anaconda Python distribution, I modified `$ANACONDA_HOME` in the `Makefile.config` file. Then I runed `$make pycaffe` and got following error:
```
CAFFE_ROOT$: make pycaffe
CXX/LD -o python/caffe/_caffe.so python/caffe/_caffe.cpp
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.8/README.Bugs> for instructions.
make: *** [python/caffe/_caffe.so] Error 4
```

I googled and it seems no one is getting the same error. Any suggestions are welcome.

**Comment by AlanZucconi** [comment]
I'm experiencing the same problem. I'm using Ubuntu 10.04.02, virtualised with VirtualBox on Windows.
Everything else is compiling file, but `make pycaffe` fails due to `g++: internal compiler error: Killed (program cc1plus)`.

Did you find a solution?

**Comment by Derrik** [comment]
I also had this issue, I increased the memory the memory vagrant uses to 2048 and that appears to have solved the issue. http://docs.vagrantup.com/v2/virtualbox/configuration.html

**Comment by tonyyang1993** [comment]
Hi @Derrik, I increased the memory to 2GB on my VMWare and it worked for me. Thank you very much. :)
```
CAFFE_ROOT$: make pycaffe
CXX/LD -o python/caffe/_caffe.so python/caffe/_caffe.cpp
touch python/caffe/proto/__init__.py
PROTOC (python) src/caffe/proto/caffe.proto
```

**Comment by LJ147** [comment]
@tonyyyang  Thank you! It worked for me by increasing the memory on my Parallels Desktop.
