### ISSUE TITLE
cuDNN max-pooling is not compatible with in-place dropout

### ISSUE THREAD

**Issue by mfigurnov** [BVLC/caffe#2688]
This is the same issue as https://github.com/BVLC/caffe/issues/117, except that now the problem arises only when max-pooling layer uses cuDNN engine. The reason is probably the same: cuDNN's max-pooling compares inputs and outputs of the layer to perform backward pass.

How to reproduce: train @mavenlin's [network for CIFAR-10](https://gist.github.com/mavenlin/e56253735ef32c3c296d) using cuDNN-enabled Caffe. The training gets stuck after few thousand iterations. However, if pool1 layer is switched to Caffe engine, the training proceeds just fine.

**Comment by longjon** [comment]
This is a symptom of #2015, so I'll note it there as a special case.
