### ISSUE TITLE
Why do the features extracted with matcaffe_demo.m and matcaffe_batch.m for the same input are different?

### ISSUE THREAD

**Issue by tsingtaogemini** [BVLC/caffe#2689]
I am using Caffe to extract features with matlab wrapper.I have 5011 images as test data set.I chopped all the layers after relu7 in deploy.prototxt. I found out if you take the same image as input of matcaffe_demo.m and matcaffe_batch.m, you will get the different 4096-dim features. Could someone tell me why? what is the differences between you extract features from all these images one by one with matcaffe_demo.m and extract features by listing all these images with matcaffe_batch.m?

**Comment by ronghanghu** [comment]
You should NOT use matcaffe_demo.m for feature extraction.

matcaffe_demo.m is for classification purpose, takes 10 crop (4 corner + 1 center and their x-flips) and average the output from these 10 crops (which is usually not the behavior you want), while matcaffe_batch.m takes only output from one center crop.

**Comment by ronghanghu** [comment]
Note that these two files matcaffe_batch.m and matcaffe_demo.m do not exist in the latest matlab wrapper.

**Comment by tsingtaogemini** [comment]
Thanks for the explanation. then could you brief me how to extract features with current version
Of matcaffe or if alternatively do so with matcaffe_batch.m the way I did is appropriate.

**Comment by ronghanghu** [comment]
You may use the code below (assume you start matlab from caffe root folder).

    % create net and load weights
    net = caffe.Net('path_to_your_model.prototxt', 'path_to_your_weights.caffemodel', 'test');
    load ./matlab/+caffe/imagenet/ilsvrc_2012_mean.mat; % load mean

    % load image and forward (do this on each image)
    im_data = caffe.io.load_image('path_to_your_image.jpg'); % load image in caffe's data format
    im_data = imresize(im_data, [256 256]) - mean_data; % resize to 256 x 256 and subtract mean
    im_data = im_data(15:241, 15:241, :); % take 227 x 227 center crop
    res = net.forward({im_data}); % run forward
    feature = res{1}; % get feature

**Comment by ronghanghu** [comment]
You may use the code below, assume you start matlab from caffe root folder and use a alexnet-like network prototext for feature extraction.

    load ./matlab/+caffe/imagenet/ilsvrc_2012_mean.mat; % load mean
    % create net and load weights
    net = caffe.Net('path_to_your_model.prototxt', 'path_to_your_weights.caffemodel', 'test');
    net.blobs('data').reshape([227 227 3 1]);

    % load image and forward (do this on each image)
    im_data = caffe.io.load_image('path_to_your_image.jpg'); % load image in caffe's data format
    im_data = imresize(im_data, [256 256]) - mean_data; % resize to 256 x 256 and subtract mean
    im_data = im_data(15:241, 15:241, :); % take 227 x 227 center crop
    res = net.forward({im_data}); % run forward
    feature = res{1}; % get feature

**Comment by tsingtaogemini** [comment]
Ok.I get what you mean. The thing is my test image data are really huge(around 5011*300), I assume doing this one by one with CPU mode(don't have GPU mode) would take months. What about if I still use matcaffe_batch.m in the old versions? thanks a lot.

**Comment by ronghanghu** [comment]
Yes, you can. However, you need to modify matcaffe_batch.m to initialize your net with `net = caffe.Net(model, weights, 'test')` and run forward with `output_data = net.forward({input_data});` instead of `output_data = caffe('forward', {input_data});`

**Comment by shelhamer** [comment]
Please ask matcaffe and usage questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) group. Thanks for answering @ronghanghu.
