### ISSUE TITLE
Check Failed error : Finetuning (UPDATED)

### ISSUE THREAD

**Issue by swamiviv** [BVLC/caffe#2691]
I am trying too finetune the Alexnet model for my purpose and the following error occurs:
```
I0704 00:23:24.011356 20595 solver.cpp:346]  Test net output #1: loss = 9.26521 (* 1 = 9.26521 
loss)
I0704 00:23:24.670114 20645 data_layer.cpp:118] Prefetch batch: 644 ms.
I0704 00:23:24.670202 20645 data_layer.cpp:119]      Read time: 15.737 ms.
I0704 00:23:24.670225 20645 data_layer.cpp:120] Transform time: 627.198 ms.
I0704 00:23:26.363464 20595 solver.cpp:214] Iteration 0, loss = 9.27414
I0704 00:23:26.363550 20595 solver.cpp:229]  Train net output #0: loss = 9.27414 (* 1 = 9.27414 
loss)
I0704 00:23:26.363598 20595 solver.cpp:489] Iteration 0, lr = 0.001
F0704 00:23:26.363885 20595 math_functions.cpp:91] Check failed: error == cudaSuccess (11 vs. 
0)  invalid argument
*** Check failure stack trace: ***
    @     0x7f0ca11e6daa  (unknown)
    @     0x7f0ca11e6ce4  (unknown)
    @     0x7f0ca11e66e6  (unknown)
    @     0x7f0ca11e9687  (unknown)
    @     0x7f0ca16b581c  caffe::caffe_copy<>()
    @     0x7f0ca175864d  caffe::SGDSolver<>::ComputeUpdateValue()
    @     0x7f0ca1757b12  caffe::SGDSolver<>::ApplyUpdate()
    @     0x7f0ca1752739  caffe::Solver<>::Step()
    @     0x7f0ca1751b75  caffe::Solver<>::Solve()
    @           0x411377  train()
    @           0x41334c  main
    @     0x7f0ca06f8ec5  (unknown)
    @           0x410799  (unknown)
    @              (nil)  (unknown)
Aborted (core dumped)
```

Its clearly during the solver update step, but I cannot figure out what is going on, even with the debug symbols on. I have only changed the last layer acc. to my purpose and of course the data layers (source etc). If it helps, my problem has more than 1000 categories which was the case in the alexnet model. The GPU I am using is K40.

UPDATE: The same error occured when I tried to start with the caffenet model too. But When I tried to train from scratch there were no errors.

**Comment by swamiviv** [comment]
Any help from anyone ?

**Comment by swamiviv** [comment]
After a bit of debugging I found the error: I had grayscale images and hence when I created the database and mean I read the mas grayscale. But the weights in the original model are being learnt on color images. Once I read my images as color images, the error didn't occur.

**Comment by mansirankawat** [comment]
Hi @swamiviv,
How did you read grayscale images as color images as I am having the same issue?
Thanks
