### ISSUE TITLE
How to solve runtime error In Caffe IOS.?

### ISSUE THREAD

**Issue by karthikeyanchenniappan** [BVLC/caffe#2692]
Hi ,

1.I download source from https://github.com/aleph7/caffe/ and builded the caffe as static library for IOS and IPhone.
2.Created sample demo code and Linked Caffe static lib(.a) and execute the code.
3.Now I got Run time error

F0519 14:54:12.494139 14504 layer_factory.hpp:77] Check failed: registry.count(t ype) == 1 (0 vs. 1) Unknown layer type: Convolution (known types: MemoryData)

4.I searched a lot and found one solution from below link

http://stackoverflow.com/questions/30325108/caffe-layer-creation-failure

5.If I create dynamic library instead of static library. It will work.

6.I tried to convert static library into Dynamic library.I got Error on Xcode that is cannot open the project I referred below link.

http://stackoverflow.com/questions/1349115/how-do-i-change-an-existing-xcode-target-from-dynamic-to-static

Can you help how to solve this..?

**Comment by aleph7** [comment]
Don't use a library, neither static or dynamic works due the way Caffe instantiates the templates. Just include the source code in your project.

**Comment by mfentross** [comment]
@aleph7 It would be superb if you could include a working iOS target in your examples. :)

**Comment by seanbell** [comment]
Shouldn't this discussion be on the aleph7 caffe page (https://github.com/aleph7/caffe), since this has nothing to do with the BVLC/caffe codebase?

**Comment by longjon** [comment]
Closing as (as noted by @seanbell) this appears to be an issue with a separate fork.
