### ISSUE TITLE
How we can set up Caffe in windows visual studio?

### ISSUE THREAD

**Issue by surajits** [BVLC/caffe#2694]

**Comment by seanbell** [comment]
Windows is not officially supported, but there are some unofficial ports of caffe to windows.

From the [Installation page](http://caffe.berkeleyvision.org/installation.html): "There is an unofficial Windows port of Caffe at [niuzhiheng/caffe:windows](https://github.com/niuzhiheng/caffe)."

**Comment by ronghanghu** [comment]
Windows is not officially supported. You may follow this link (however it may be out-of-date): https://initialneil.wordpress.com/2015/01/11/build-caffe-in-windows-with-visual-studio-2013-cuda-6-5-opencv-2-4-9/

Please ask installation and usage questions on the [caffe-users mailing list](https://groups.google.com/forum/#!forum/caffe-users).

**Comment by bhack** [comment]
See https://github.com/BVLC/caffe/pull/2538
