### ISSUE TITLE
train caffe net failde 

### ISSUE THREAD

**Issue by donalwilson** [BVLC/caffe#2695]
I0705 15:30:44.474939 14386 net.cpp:127] Top shape: 256 4096 (1048576)
I0705 15:30:44.474980 14386 layer_factory.hpp:74] Creating layer relu7
I0705 15:30:44.474992 14386 net.cpp:90] Creating Layer relu7
I0705 15:30:44.474998 14386 net.cpp:410] relu7 <- fc7
I0705 15:30:44.475006 14386 net.cpp:357] relu7 -> fc7 (in-place)
I0705 15:30:44.475015 14386 net.cpp:120] Setting up relu7
I0705 15:30:44.475220 14386 net.cpp:127] Top shape: 256 4096 (1048576)
I0705 15:30:44.475230 14386 layer_factory.hpp:74] Creating layer drop7
I0705 15:30:44.475239 14386 net.cpp:90] Creating Layer drop7
I0705 15:30:44.475244 14386 net.cpp:410] drop7 <- fc7
I0705 15:30:44.475252 14386 net.cpp:357] drop7 -> fc7 (in-place)
I0705 15:30:44.475260 14386 net.cpp:120] Setting up drop7
I0705 15:30:44.475266 14386 net.cpp:127] Top shape: 256 4096 (1048576)
I0705 15:30:44.475271 14386 layer_factory.hpp:74] Creating layer fc8
I0705 15:30:44.475280 14386 net.cpp:90] Creating Layer fc8
I0705 15:30:44.475287 14386 net.cpp:410] fc8 <- fc7
I0705 15:30:44.475293 14386 net.cpp:368] fc8 -> fc8
I0705 15:30:44.475301 14386 net.cpp:120] Setting up fc8
I0705 15:30:44.480556 14386 net.cpp:127] Top shape: 256 1000 (256000)
I0705 15:30:44.480592 14386 layer_factory.hpp:74] Creating layer loss
I0705 15:30:44.480607 14386 net.cpp:90] Creating Layer loss
I0705 15:30:44.480613 14386 net.cpp:410] loss <- fc8
F0705 15:30:44.480624 14386 net.cpp:364] Duplicate blobs produced by multiple sources.
*** Check failure stack trace: ***
    @     0x7f97412328ed  google::LogMessage::Fail()
    @     0x7f97412377af  google::LogMessage::SendToLog()
    @     0x7f9741234cca  google::LogMessage::Flush()
    @     0x7f97412350dd  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f97470e9498  caffe::Net<>::AppendTop()
    @     0x7f97470eac03  caffe::Net<>::Init()
    @     0x7f97470ede71  caffe::Net<>::Net()
    @     0x7f97470d0bcd  caffe::Solver<>::InitTrainNet()
    @     0x7f97470d467f  caffe::Solver<>::Init()
    @     0x7f97470d4dd5  caffe::Solver<>::Solver()
    @           0x40d648  caffe::GetSolver<>()
    @           0x407bc1  train()
    @           0x404ed8  main
    @     0x7f973b7e9ec5  (unknown)
    @           0x404a79  (unknown)
Aborted (core dumped)

**Comment by shelhamer** [comment]
`F0705 15:30:44.480624 14386 net.cpp:364] Duplicate blobs produced by multiple sources.` Check your model definition for duplicates.

Please ask about modeling and usage on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) group.
