### ISSUE TITLE
Hamming distance CPU test failure on 32-bit

### ISSUE THREAD

**Issue by engr3os** [BVLC/caffe#2696]
Hi, I am trying execute "make runtest" and met some problems.
The caffe is successfully compiled on Ubuntu14.04 with CPU only.
When executing the testcases, it got stuck on function : ReferenceHammingDistance(n, x, y)

[----------] 8 tests from CPUMathFunctionsTest/1, where TypeParam = double
[ RUN      ] CPUMathFunctionsTest/1.TestNothing
[       OK ] CPUMathFunctionsTest/1.TestNothing (62 ms)
[ RUN      ] CPUMathFunctionsTest/1.TestHammingDistance
src/caffe/test/test_math_functions.cpp:86: Failure
Value of: caffe_cpu_hamming_distance<TypeParam>(n, x, y)
  Actual: 712929
Expected: this->ReferenceHammingDistance(n, x, y)
Which is: 1413025
[  FAILED  ] CPUMathFunctionsTest/1.TestHammingDistance, where TypeParam = double (62 ms)

The test finally aborted due to this. I saw there was similar problem in some old thread but indication it was actually solved.

https://github.com/BVLC/caffe/issues/1294

Can someone help?

**Comment by longjon** [comment]
Can you reproduce this with the latest `master` in `DEBUG` mode? (See https://github.com/BVLC/caffe/wiki/Reporting-Bugs-and-Other-Issues.)

(You should only need to run `build/test/test_math_function.testbin`.) What's your CPU architecture? Are you running a 32-bit or 64-bit version of Ubuntu?

**Comment by engr3os** [comment]
I'm  using 32-bit version of Ubuntu installed in virtual machine. And yes I
have the same error with the latest master.

Thanks,
Oluwatobi

On Mon, Jul 13, 2015 at 3:29 AM, Jon Long <notifications@github.com> wrote:

> Can you reproduce this with the latest master in DEBUG mode? (See
> https://github.com/BVLC/caffe/wiki/Reporting-Bugs-and-Other-Issues.)
>
> (You should only need to run build/test/test_math_function.testbin.)
> What's your CPU architecture? Are you running a 32-bit or 64-bit version of
> Ubuntu?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BVLC/caffe/issues/2696#issuecomment-120837459>.
>



-- 
Regards,
Oluwatobi Olabiyi

No one ever attain very eminent success in life by doing only what is
required of him, it is the amount of that which is over and above the
required that determines the greatness of ultimate distinction

**Comment by longjon** [comment]
Thanks. It looks there is a bug on line https://github.com/BVLC/caffe/blob/master/src/caffe/util/math_functions.cpp#L367, which should probably read `__builtin_popcountll` instead of `__builtin_popcountl`.

By the way, this should have generated warnings (`make warn`); did it not?

We don't have CI for 32-bit platforms, so it's not too surprising to see issues like this.

**Comment by jjmontesl** [comment]
Affected by this, running on Ubuntu 14.04 32 bit. I can confirm the proposed solution by @longjon works.

**Comment by longjon** [comment]
Closing as the relevant code has been removed by #3404.
