### ISSUE TITLE
Broken links to python notebook examples

### ISSUE THREAD

**Issue by alex540** [BVLC/caffe#2699]
The links from http://caffe.berkeleyvision.org/ to the python notebook examples, e.g., http://nbviewer.ipython.org/github/BVLC/caffe/blob/master/examples/filter_visualization.ipynb ,
recently broke. This may be related to the June 30 commit: "[examples] sequence and revise notebooks"

**Comment by ybur-yug** [comment]
this is a problem with gitorious being briefly down transfering to archive.org, I believe @alex540 (not on the caffe team, just am toying with it myself and working around)

**Comment by shelhamer** [comment]
The site was slightly out-of-date with respect to the latest examples so the notebook links broke. It's fixed now.

**Comment by kleinsound** [comment]
This appears to be broken again. The link from http://caffe.berkeleyvision.org/gathered/examples/feature_extraction.html to the "filter visualization example" leads to a 404 page for http://nbviewer.ipython.org/github/BVLC/caffe/blob/master/examples/filter_visualization.ipynb

The correct like would appear to be http://nbviewer.ipython.org/github/BVLC/caffe/blob/master/examples/00-classification.ipynb, as linked from https://github.com/BVLC/caffe/tree/master/examples/feature_extraction.

**Comment by shelhamer** [comment]
We accidentally let the site branch `gh-pages` go out of sync but it's fixed now.

**Comment by kleinsound** [comment]
Confirmed!
