### ISSUE TITLE
Compressing Neural Networks with the Hashing Trick

### ISSUE THREAD

**Issue by robertsdionne** [BVLC/caffe#2700]
Generalize class SyncedMemory to support storing a set of virtual parameters within a smaller set of actual parameters with the hashing trick. Based on the following paper:

Compressing Neural Networks with the Hashing Trick
Authors: Wenlin Chen, James Wilson, Stephen Tyree, Kilian Weinberger, Yixin Chen
[Abstract](http://jmlr.org/proceedings/papers/v37/chenc15.html)
[Full text](http://jmlr.org/proceedings/papers/v37/chenc15.pdf)

Further ideas:
- In the paper, virtual parameters for a given layer are stored in a smaller set of actual parameters using the hashing trick. However, I imagine one large block of actual parameters could serve as the backing storage for the virtual parameters of almost all layers in a network, and doing so might have benefits due to spreading out hash collisions among more parameters.
- Likewise, inputs and outputs to each layer could be stored in a reduced set of actual values with the hashing trick, perhaps gaining similar benefits.

The above techniques might allow training models that are virtually 8x to 16x larger than ones that currently fit on graphics hardware with decreases in error (see figure 4), or equivalently, models that are 8x to 16x smaller than the full-size ones with only small increases in error (~2% vs ~1% test error) [see figures 2 & 3].

However, I'm not sure how negatively random-access through hashing will affect the memory cache performance.

**Comment by shelhamer** [comment]
Closing for lack of interest—while model compression is an active direction for research and engineering it might be done better apart from the core framework for simplicity.
