### ISSUE TITLE
Make_imagenet_mean.sh "Incorrect data field size"

### ISSUE THREAD

**Issue by leonga** [BVLC/caffe#2705]
When I try to run make_imagenet_mean.sh, I get the following error: 

F0706 10:00:18.529913 12940 compute_image_mean.cpp:76] Check failed: size_in_datum == data_size (132096 vs. 125952) Incorrect data field size 132096
*** Check failure stack trace: ***
    @     0x7fc5ad61fea4  (unknown)
    @     0x7fc5ad61fdeb  (unknown)
    @     0x7fc5ad61f7bf  (unknown)
    @     0x7fc5ad622a35  (unknown)
    @           0x4037a1  main
    @     0x7fc5ac7f1a40  (unknown)
    @           0x403159  _start
    @              (nil)  (unknown)
Aborted (core dumped)
Done.

I'm not sure why this is happening or how to fix this. Am I missing data? What is the difference between size_in_datam and data_size? I tried looking at compute_image_mean.cpp but I don't understand.

**Comment by longjon** [comment]
Closing as this does appear to be an issue with Caffe; please ask usage questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) list. Thanks!
