### ISSUE TITLE
Probability layer in VGG model 

### ISSUE THREAD

**Issue by forwardcjj** [BVLC/caffe#2708]
Hi, Dear all, 

I extracted the features using the python interface and it achieves the correct prediction for examplar cat category. 
However, when I used the vgg model in the model zoo, for the last layer, it did not give the correct prediction category.  
Anyone met the same problem?  Thanks in advance. 

http://nbviewer.ipython.org/github/BVLC/caffe/blob/master/examples/00-classification.ipynb

@Shelhamer @ksimonyan

**Comment by seanbell** [comment]
I believe that the VGG models were trained on images that are resized in a way that maintains aspect ratio.  The default code for caffe warps images to a square (thereby throwing away the aspect ratio).  This could be why the CaffeNet/AlexNet models worked but VGG16 did not.

Also, you shouldn't expect every image to be correctly classified.  For example, for a single scale (256 px), VGG16 has an error rate of 27% (http://arxiv.org/pdf/1409.1556.pdf).

Please ask these kinds of questions on the [Caffe users group](https://groups.google.com/forum/#!forum/caffe-users).
