### ISSUE TITLE
Multicore + GPU?

### ISSUE THREAD

**Issue by marker68** [BVLC/caffe#2710]
I'm looking for some excellent solutions for multicore + GPU hybrid systems that can use all the power of computing resources in PC. Do you have any plan to support these kind of systems? While it seems that the current Caffe only support only CPU or only GPU mode.

Some useful references:
http://icl.cs.utk.edu/magma/index.html (an extension of LAPACK for multicore +  GPU systems)

**Comment by longjon** [comment]
Closing as this is not a specific issue or proposal to enhance Caffe. This tracker is for specific issues and bugs with Caffe (see https://github.com/BVLC/caffe/wiki/Reporting-Bugs-and-Other-Issues). You're welcome to discuss this on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) list.

Note that #2219 implements a concrete proposal that includes CPU/GPU parallelism. However, it's less cumbersome and more effective to simply use multiple GPUs.
