### ISSUE TITLE
At end of source: warning: routine is both "inline" and "noinline"

### ISSUE THREAD

**Issue by philkr** [BVLC/caffe#2711]
For the last half a year I kept getting compiler warnings:
```
At end of source: warning: routine is both "inline" and "noinline"
```
I usually see 2 or more for each .cu file in caffe, when I build with cmake (I'm also getting the warning with make). Is anyone else getting those? Any ideas on how to suppress them?

**Comment by longjon** [comment]
What are your `nvcc` and host compiler versions?

**Comment by philkr** [comment]
nvcc
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2015 NVIDIA Corporation
Built on Mon_Feb_16_22:59:02_CST_2015
Cuda compilation tools, release 7.0, V7.0.27
```
gcc
```
gcc (Ubuntu 4.9.2-10ubuntu13) 4.9.2
```
I vaguely recall this also happening with gcc 4.8 .

**Comment by lukeyeager** [comment]
I was poking around in the CMake files and found [this](https://github.com/BVLC/caffe/blob/77d66dfc907dd875d69bb9fc12dd950b531e464f/cmake/Cuda.cmake#L224-L230):
```cmake
# Boost 1.55 workaround, see https://svn.boost.org/trac/boost/ticket/9392 or
# https://github.com/ComputationalRadiationPhysics/picongpu/blob/master/src/picongpu/CMakeLists.txt
if(Boost_VERSION EQUAL 105500)
  message(STATUS "Cuda + Boost 1.55: Applying noinline work around")
  # avoid warning for CMake >= 2.8.12
  set(CUDA_NVCC_FLAGS "${CUDA_NVCC_FLAGS} \"-DBOOST_NOINLINE=__attribute__((noinline))\" ")
endif()
```
What version of Boost do you have?

**Comment by philkr** [comment]
I have 1.55, but I'm not sure if this is the cause. I'm getting those warning with both Make and CMake. I didn't see make apply this workaround. I'll see if I can upgrade boost...

**Comment by philkr** [comment]
No luck, boost 1.58 has the same issues.

**Comment by philkr** [comment]
Updating to CUDA 7.5 seems to have made this error disappear.

**Comment by kyuusaku** [comment]
I use CUDA 6.5 and I have the same issues.
