### ISSUE TITLE
i am trying to install caffe in my ubuntu 14.04 system and geting the following error when i did "make test"...please someone help

### ISSUE THREAD

**Issue by surajits** [BVLC/caffe#2713]
i CXX/LD -o .build_release/test/test_all.testbin src/caffe/test/test_caffe_main.cpp
/usr/lib/libcaffe.so: undefined reference to `cblas_sgemv'
/usr/lib/libcaffe.so: undefined reference to `cblas_dgemm'
/usr/lib/libcaffe.so: undefined reference to `cblas_sscal'
/usr/lib/libcaffe.so: undefined reference to `cblas_dgemv'
/usr/lib/libcaffe.so: undefined reference to `cblas_saxpy'
/usr/lib/libcaffe.so: undefined reference to `cblas_ddot'
/usr/lib/libcaffe.so: undefined reference to `cblas_dasum'
/usr/lib/libcaffe.so: undefined reference to `cblas_sgemm'
/usr/lib/libcaffe.so: undefined reference to `cblas_dscal'
/usr/lib/libcaffe.so: undefined reference to `cblas_scopy'
/usr/lib/libcaffe.so: undefined reference to `cblas_sasum'
/usr/lib/libcaffe.so: undefined reference to `cblas_daxpy'
/usr/lib/libcaffe.so: undefined reference to `cblas_dcopy'
/usr/lib/libcaffe.so: undefined reference to `cblas_sdot'
collect2: error: ld returned 1 exit status

**Comment by danbuckler** [comment]
It looks like you have not installed OpenBLAS.

**Comment by longjon** [comment]
This tracker is for specific issues and bugs with Caffe (see https://github.com/BVLC/caffe/wiki/Reporting-Bugs-and-Other-Issues). Please ask usage and installation questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) list. Thanks!
