### ISSUE TITLE
"You can install with" instruction is a bit odd

### ISSUE THREAD

**Issue by stuaxo** [BVLC/caffe#2717]
You can install the dependencies with

```
for req in $(cat requirements.txt); do pip install $req; done
```

Is a bit strange, when 

```pip install -r requirements.txt```

Will do

**Comment by ronghanghu** [comment]
No, `pip install -r requirements.txt` won't work.

Take a look at #1950 for details.

**Comment by stuaxo** [comment]
Ok, closing this as a duplicate of #1950 .... it's a horrible thing to try and workaround, I'm going to bash pip a bit and see what happens ...
