### ISSUE TITLE
Travis: WITH_CMAKE=true, WITH_CUDA=true does not use cuda.

### ISSUE THREAD

**Issue by philkr** [BVLC/caffe#2722]
Travis with WITH_CMAKE=true, WITH_CUDA=true still has the CPU_ONLY=ON flag set, so it never builds the cuda code with cmake.
See https://github.com/BVLC/caffe/blob/master/scripts/travis/travis_build_and_test.sh line 10. Is there a reason for this or just oversight?

**Comment by longjon** [comment]
It doesn't look like there's a good reason for this; the commits are @jeffdonahue's, so maybe he can comment further. I think we'd accept a PR that fixes this.

**Comment by jeffdonahue** [comment]
Yup, my bad. Fix welcome.

**Comment by shelhamer** [comment]
Fixed in #2740
