### ISSUE TITLE
[BUG] Unable to do forward pass with updated internal layer data in pycaffe

### ISSUE THREAD

**Issue by liuyipei** [BVLC/caffe#2725]
I am trying to do a conv-net forward pass after manually setting the data blobs.

In the demo below, I loaded VGG16, and tried to update the pycaffe Net object's internal blobs with random values before trying to run a forward pass. When conv5=True, repeated execution does not yield different output when I print fc8_forward. In contrast, it does work for the data/conv1 code.

Any advice on this matter is greatly appreciated. 
Also, I would also like to hear advice regarding whether I should be copying my numpy arrays before using them in the C++ bindings. 

Thank you for your help in advance!

```
import caffe
import numpy as np
caffe_root = '/somewhere/caffe'
caffe.set_mode_gpu()
net = caffe.Net(caffe_root + 'models/bvlc_reference_caffenet/deploy_hallucination.prototxt',
                caffe_root + 'models/bvlc_reference_caffenet/bvlc_reference_caffenet.caffemodel',
                caffe.TEST)

conv5 = True
if conv5: # doesn't work -- i.e. fc8_forward does not change on repeated execution of this code block
    x = np.random.rand(1,256,13,13)*255 
    net.blobs['conv5'].data[...] = x.copy() 
    curr_forward = net.forward(start = 'pool5',end='fc8') 
    # also tried start = 'conv5'. pool5 is right after conv5 -- same behavior
else: # this works as expected
    y= np.random.rand(1,3,227,227)*255 
    net.blobs['data'].data[...] = y.copy() 
    curr_forward = net.forward(start = 'conv1',end='fc8')

fc8_forward = np.array(curr_forward['fc8'].flat) 
print fc8_forward
```
The layers in VGG 16 are:

['data', 'conv1', 'pool1', 'norm1', 'conv2', 'pool2', 'norm2', 'conv3', 'conv4', 'conv5', 'pool5', 'fc6', 'fc7', 'fc8', 'prob']

**Comment by liuyipei** [comment]
Subsequently, I have manually verified that 
1. The layers are properly connected.
2. I am able to directly inject data into all layers and observe a different forward pass output. "conv5" is the only one that fails. Based on this observation, it is clear that the behavior is not intended, and hence I am marking this issue as a bug.

**Comment by seanbell** [comment]
You might need to start from the relu5 layer after conv5, rather than the pool5 layer?

Regarding copying, when assigning to a blob with [...], you don't need to do a copy, since the [...] syntax already copies into the target.  However, when you extract a blob from the net, you do need to do a copy (or else you'll end up with a bunch of different pointers all to the same memory).  Note that some of the pycaffe methods do the copy for you, and others don't.  For example, net.foward (https://github.com/BVLC/caffe/blob/master/python/caffe/pycaffe.py#L98) does not do a copy.

Also, I believe you're using CaffeNet and not VGG16.

**Comment by liuyipei** [comment]
@seanbell Yes, you are correct that I was on CaffeNet. 
Your comment on the blob [...] syntax is greatly appreciated, and thank you for that link into pycaffe.py.

It turns out that in caffe, ReLus are done in-place, and thus ReLu are not considered proper blobs.
Somehow I have been unable to reproduce this problem since rebooting my computer ... closing issue...
