### ISSUE TITLE
python.h no such file when making pycaffe

### ISSUE THREAD

**Issue by hurnhu** [BVLC/caffe#2727]
`~/caffe$ sudo make pycaffe
CXX/LD -o python/caffe/_caffe.so python/caffe/_caffe.cpp
python/caffe/_caffe.cpp:1:52: fatal error: Python.h: No such file or directory
 #include <Python.h>  // NOLINT(build/include_alpha)
                                                    ^
compilation terminated.
make: *** [python/caffe/_caffe.so] Error 1`

i installed all listed dependencies from here http://caffe.berkeleyvision.org/install_apt.html
and anaconda, set up the anaconda path, and tried to set python path
`export PATH="/home/grayson/anaconda/bin:$PATH"
export PYTHONPATH="/usr/include/python2.7"
`

and my make file config

`
PYTHON_INCLUDE := /usr/include/python2.7 \`
        `        /usr/lib/python2.7/dist-packages/numpy/core/include`
`# Anaconda Python distribution is quite popular. Include path:`
`# Verify anaconda location, sometimes it's in root.`
` ANACONDA_HOME := $/home/grayson/anaconda`
` PYTHON_INCLUDE := $/home/grayson/anaconda/include \`
 `               # $/home/grayson/anaconda/include/python2.7 \`
 `               # $/home/grayson/anaconda/lib/python2.7/site-packages/numpy/core/include \`

`# We need to be able to find libpythonX.X.so or .dylib.`
`#PYTHON_LIB := /usr/lib`
`PYTHON_LIB := $/home/grayson/anaconda/lib`

but it cant find Python.h when i try make pycaffe

**Comment by damienstanton** [comment]
It looks like you set your `PYTHONPATH` to the system Python. Try setting it to the Anaconda Python path. On my machine this is
```
/Users/me/anaconda/bin/python
```

**Comment by longjon** [comment]
This tracker is for issues and bugs with Caffe; please ask installation questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) list. Thanks!

**Comment by srbnghosh99** [comment]
I am getting the same error.
when I am giving this command to try example
python python/classify.py --print_results examples/images/cat.jpg foo

I am getting this error.
CXX/LD -o python/caffe/_caffe.so python/caffe/_caffe.cpp
python/caffe/_caffe.cpp:1:52: fatal error: Python.h: No such file or directory
 #include <Python.h>  // NOLINT(build/include_alpha)
                                                    ^
compilation terminated.
make: *** [python/caffe/_caffe.so] Error 1

How to solve this?

**Comment by archenroot** [comment]
Plase check this, I fixed this by compiling against python 3.4.
The 2.7 is mystery for me...

https://stackoverflow.com/questions/39874099/caffegpuopencv3-1python3-5anacondafatal-error-python-h-no-such-file-or-di/44135622#44135622

**Comment by archenroot** [comment]
#https://github.com/BVLC/caffe/issues/4538

**Comment by archenroot** [comment]
#4538
