### ISSUE TITLE
Missing link in ImageNet toturial

### ISSUE THREAD

**Issue by tonyyang1993** [BVLC/caffe#2732]
On the [Brewing ImageNet](http://caffe.berkeleyvision.org/gathered/examples/imagenet.html) page, the last link results in 404 not found:

"
...
And since now you have a trained network, check out how to use it with the Python interface for classifying [ImageNet](http://nbviewer.ipython.org/github/BVLC/caffe/blob/master/examples/classification.ipynb).
"

Does any one know where the link goes?

**Comment by seanbell** [comment]
It's probably supposed to point here: https://github.com/BVLC/caffe/blob/master/examples/00-classification.ipynb (the file was renamed after a tutorial was merged into the main codebase)

**Comment by tonyyang1993** [comment]
@seanbell Awesome! Thank you very much.
