### ISSUE TITLE
how to extract fully-connected layer parameters using caffe?

### ISSUE THREAD

**Issue by jingruixiaozhuang** [BVLC/caffe#2733]
I recently trained a network and found that caffe.Net.params is an OrderedDict, which only contains parameters of convolutional layers. So how can I extract fully-connected layers' parameters using caffemodel? Thanks!

**Comment by seanbell** [comment]
net.params should contain the parameters for all layers.  See this for an example: https://github.com/BVLC/caffe/blob/master/examples/net_surgery.ipynb

Also, please as usage questions on the [https://groups.google.com/forum/#!forum/caffe-users](caffe-users mailing list) and not on Github -- thanks!
