### ISSUE TITLE
Caffe / DeepDream build with cuDNN, nVidia driver v352.21 and GTX 960 does not utilize GPU

### ISSUE THREAD

**Issue by vladislavdonchev** [BVLC/caffe#2735]
Hello,

I have successfully compiled the latest version of Caffe with USE_CUDNN := 1 and installed the newest nVidia graphics / CUDA drivers available for Ubuntu x64.

However, when I run Google's DeepDream algorithms I can see that my CPU load is at 100% while the 'nvidia-settings' tool reports that the GPU utilization is 0%.

Is this normal? How can I make sure that the CUDA cores are actually doing the work and not my CPU?

Thanks

**Comment by robertsdionne** [comment]
import caffe
caffe.set_mode_gpu()
caffe.set_device(0)

**Comment by vladislavdonchev** [comment]
Thanks a lot! It seems that I've missed that...
