### ISSUE TITLE
"Kitten installation test" (cat.jpg) not working

### ISSUE THREAD

**Issue by fundou** [BVLC/caffe#2736]
Hi,

The first test (cat.jpg) is not working per the instructions here: https://github.com/BVLC/caffe/wiki/Ubuntu-14.04-VirtualBox-VM.

vagrant@vagrant-ubuntu-trusty-64:~/caffe$ python python/classify.py --labels_file data/ilsvrc12/synset_words.txt --print_results examples/images/cat.jpg foo

Traceback (most recent call last):
  File "python/classify.py", line 173, in <module>
    main(sys.argv)
  File "python/classify.py", line 157, in main
    indices = (-scores).argsort()[:5]
NameError: global name 'scores' is not defined

I copied the --print_results code from https://github.com/jetpacapp/caffe/blob/master/python/classify.py:

    if args.print_results:
        with open(args.labels_file) as f:
          labels_df = pd.DataFrame([
               {
                   'synset_id': l.strip().split(' ')[0],
                   'name': ' '.join(l.strip().split(' ')[1:]).split(',')[0]
               }
               for l in f.readlines()
            ])
        labels = labels_df.sort('synset_id')['name'].values

        indices = (-scores).argsort()[:5]
        predictions = labels[indices]

        meta = [
                   (p, '%.5f' % scores[i])
                   for i, p in zip(indices, predictions)
               ]

        print meta
, but the output of classifier.predict(inputs, not args.center_only) has changed in master. I tried to change the printing code appropriately, but that didn't work either:

# Classify.
    start = time.time()
    predictions = classifier.predict(inputs, not args.center_only)
    print("Done in %.2f s." % (time.time() - start))

    print predictions

    if args.print_results:
        with open(args.labels_file) as f:
          labels_df = pd.DataFrame([
               {
                   'synset_id': l.strip().split(' ')[0],
                   'name': ' '.join(l.strip().split(' ')[1:]).split(',')[0]
               }
               for l in f.readlines()
            ])
        labels = labels_df.sort('synset_id')['name'].values

        indices = (-predictions).argsort()[:5]
        candidates = labels[indices]

        meta = [
                   (p, '%.5f' % predictions[i])
                   for i, p in zip(indices, candidates)
               ]

        print meta

vagrant@vagrant-ubuntu-trusty-64:~/caffe$ python python/classify.py --labels_file data/ilsvrc12/synset_words.txt --print_results examples/images/cat.jpg foo

Traceback (most recent call last):
  File "python/classify.py", line 173, in <module>
    main(sys.argv)
  File "python/classify.py", line 162, in main
    for i, p in zip(indices, candidates)
IndexError: index 281 is out of bounds for axis 0 with size 1

**Comment by fundou** [comment]
Looks like this PR: https://github.com/BVLC/caffe/pull/2359 from @dribnet does the trick.

**Comment by kkarnatak** [comment]
Did anyone got solution to this problem?
I am facing the same error, and have followed steps as mentioned by @fundou
