### ISSUE TITLE
Data Layer Test Fails with Segfault

### ISSUE THREAD

**Issue by ahmedallibhoy** [BVLC/caffe#2744]
I'm trying to install caffe on my machine with the following specs:

MacBook Pro Retina - OSX Yosemite 10.10.4
CPU: Intel Core i7
GPU: Nvidia GeForce 750M
Memory: 16 GB 1600 MHz DDR3

I successfully ran make all && make test, but make runtest fails with the following error. 

[----------] 12 tests from DataLayerTest/0, where TypeParam = N5caffe9CPUDeviceIfEE
[ RUN      ] DataLayerTest/0.TestReadLevelDB
**\* Aborted at 1436577942 (unix time) try "date -d @1436577942" if you are using GNU date ***
PC: @        0x11419105a boost::detail::thread_data_base::~thread_data_base()
**\* SIGSEGV (@0x1) received by PID 56391 (TID 0x7fff75a59300) stack trace: ***
    @     0x7fff89ea8f1a _sigtramp
    @     0x7fff61ce64fb (unknown)
make: **\* [runtest] Segmentation fault: 11

Some other relevant notes:
I'm using the anaconda python distribution. OpenCV and Boost 1.57 were built from source using Homebrew. For BLAS I'm using Intel MKL. I initially tried to compile using cuDNN, however, the same issue appears when I comment out the USE_CUDNN := 1 flag. I tried updating my CUDA drivers to the latest version but no luck. 

Any solutions? Thanks!

**Comment by seanbell** [comment]
It looks like the problem is with leveldb; this is the failing test: https://github.com/BVLC/caffe/blob/master/src/caffe/test/test_data_layer.cpp#L351 which just inserts some dummy data and then reads it again from the database.

Perhaps you should check your installation of leveldb?

**Comment by ahmedallibhoy** [comment]
It seems that the problem is unrelated to leveldb. All of the tests in test_data_layer fail with a segfault as well as the tests from test_image_data_layer. I downgraded from Boost 1.57 to Boost 1.55 and that seems to have fixed the problem. 

Thanks

**Comment by gnperdue** [comment]
I am seeing the same failure. I've tried uninstalling and re-installing leveldb a few times. I am using Boost 1.55 already

      [----------] 12 tests from DataLayerTest/1, where TypeParam =      N5caffe9CPUDeviceIdEE
      [ RUN      ] DataLayerTest/1.TestReshapeLevelDB
      *** Aborted at 1440090331 (unix time) try "date -d @1440090331" if you are using GNU date ***
      PC: @     0x7fff85a456cf std::_Rb_tree_decrement()
      *** SIGSEGV (@0x8) received by PID 92345 (TID 0x10dac2000) stack trace: ***
          @     0x7fff91757f1a _sigtramp
          @     0x7fff68a16508 (unknown)
          @        0x101851384 std::_Rb_tree<>::_M_insert_unique()
          @        0x10184fa63 boost::detail::add_new_tss_node()
          @        0x10184fe6f boost::detail::set_tss_data()
          @        0x104d8f57e boost::thread_specific_ptr<>::reset()
          @        0x104d8ef4f caffe::Caffe::Get()
          @        0x104da25b2 caffe::InternalThread::entry()
          @        0x10184e625 boost::(anonymous namespace)::thread_proxy()
          @     0x7fff89f99268 _pthread_body
          @     0x7fff89f991e5 _pthread_start
          @     0x7fff89f9741d thread_start
      make: *** [runtest] Segmentation fault: 11 (core dumped)

I'm using an iMac with a Core i5 and NVIDIA GeForce GTX 660M (I am building with CPU only mode right now.)

I'm using OpenBLAS from Homebrew, Boost 1.55 from Homebrew, and I also got all of the following from homebrew:

* get `eigen`
* get `openexr`
* get `opencv`
* get `protobuf`
* get `gflags`
* get `glog`
* get `leveldb`
* get `lmdb`

In order to get Caffe to build, I had to follow the "hack" for HDF5 outlined here (to get 1.8.15): https://groups.google.com/forum/#!topic/caffe-users/MFmdpuId8e0

**Comment by tsingjinyun** [comment]
@gnperdue http://christopher5106.github.io/big/data/2015/07/16/deep-learning-install-caffe-cudnn-cuda-for-digits-python-on-mac-osx.html
change boost1.58 to boost 1.57( the same error of make runtest as yours),and it can work well

**Comment by dzung-hoang** [comment]
I encountered the same issue and resolved it by editing Makefile.config and changing
`# USE_LEVELDB := 0`
to
`USE_LEVELDB := 1`
so it looks like a bug in the build scripts.
