### ISSUE TITLE
The installation instructions are incomplete

### ISSUE THREAD

**Issue by shyamalschandra** [BVLC/caffe#2754]
Hi,

Could you insert links with all of the packages necessary to install caffe on the different platforms where it can work?  Also, if possible, would it be possible to find out the packages associated with the particular frameworks that are perquisites for caffe?

Thanks!

**Comment by longjon** [comment]
This tracker is for specific issues and bugs with Caffe. For installation questions, please ask on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) list. In addition, we do provide installation instructions for common platforms, and we're happy to accept PRs that improve those instructions.

**Comment by seanbell** [comment]
@shyamalschandra the instructions are here: http://caffe.berkeleyvision.org/installation.html.  There is a link on the repository homepage.
