### ISSUE TITLE
Mem leaks when training Alexnet on ilsvrc2012

### ISSUE THREAD

**Issue by chasegh** [BVLC/caffe#2755]
When I was running Caffe to train Alexnet, I found that mem occupancy is soon over 90% after the program started. My computer's mem is 64GB, and it runs on GPU mode, I thought it should not have taken so many mem. Is that mem leak or just a bug?

**Comment by shelhamer** [comment]
Closing as most likely due to system configuration of memory usage by lmdb. See https://symas.com/understanding-lmdb-database-file-sizes-and-memory-utilization/ for more detail.
