### ISSUE TITLE
how to load all dataset to gpu global memories

### ISSUE THREAD

**Issue by mmmonkeytao** [BVLC/caffe#2758]
hey guys, I just start to use caffe and try to modify it for my own project. In my case, since the whole image set is not really big, I want to load them once into gpu so that I can read batches of images from global memory afterwards. How can I do that?

**Comment by seanbell** [comment]
You could create your own data layer that has a Blob object containing the entire dataset.  Then, you just copy from the dataset blob into the top blob for your data layer.

**Comment by mmmonkeytao** [comment]
thanks seanbell, I am testing on my code, I think it works :)
