### ISSUE TITLE
model zoo - show valid inputs for deepdream with each model

### ISSUE THREAD

**Issue by stuaxo** [BVLC/caffe#2759]
Different models have differently named layers, so plugging them into deepdream doesn't "just work" it would good if each model had info on which layers are good to plug into deep dream.

For instance the places_cnds_model has differently named layers, and not all of them work, it would be good if modelzoo had some info on the layers for each model.

**Comment by seanbell** [comment]
The valid inputs for deepdream are the top (output) blob names, not the layer names.  It just so happens that most people make the layers and output layer names the same, but they don't have to be.  You want to use the string after `top` and not `name` when looking at the layer names in `deploy.prototxt`.

**Comment by shelhamer** [comment]
Right, it's the tops and not the layers that you want. Please ask usage questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) group.
