### ISSUE TITLE
Build error in OSX 10.9.2

### ISSUE THREAD

**Issue by happyyxw** [BVLC/caffe#276]
Hi I am sorry if this is a not proper place to ask the question. However, I did not find any user group, where I could ask the question. If there is such a place, please let me know. 

I have followed the instructions to to build caffe in IOS 10.9.2. I checked out the master branch. I face a build error when building. I just showed a small portion below. 

Undefined symbols for architecture x86_64:
  "google::protobuf::MessageLite::ParseFromString(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)", referenced from:
      _main in compute_image_mean.o
  "leveldb::DB::Open(leveldb::Options const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, leveldb::DB**)", referenced from:
      _main in compute_image_mean.o

Is there any suggestion for that? Thanks a lot.

**Comment by karthikeyanchenniappan** [comment]
@shelhamer , any update on Caffe build for iOS?, any directions to build for iOS will be much more appreciated.
