### ISSUE TITLE
Step-by-step custom training How-to?

### ISSUE THREAD

**Issue by jmcclaire** [BVLC/caffe#2760]
Does anyone know of or feel like creating a simple step-by-step how-to on training a custom caffe model? Everything I've found leaves out a ton of steps. I am using this with Google Deep Dream and want to swap dog faces or places with my own image set. Thanks so much for any help at all!

**Comment by teamheisenberg** [comment]
Hi jmcclaire, I am also trying to train on a custom dataset. have you gone through this tutorial? http://caffe.berkeleyvision.org/gathered/examples/imagenet.html

**Comment by shelhamer** [comment]
Please ask usage questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) group. Thanks.
