### ISSUE TITLE
What are the installation instructions for caffe on Win32?

### ISSUE THREAD

**Issue by shyamalschandra** [BVLC/caffe#2761]
What should I do?

**Comment by seanbell** [comment]
Windows isn't officially supported, though it has been ported to 64-bit windows by niuzhiheng: https://github.com/niuzhiheng/caffe.  There might be something there to get 32-bit to work.

**Comment by eelstork** [comment]
I got it to work on Win32 / VS 2015 using [willyd/caffe-windows-dependencies](https://github.com/willyd/caffe-windows-dependencies) and [win-cmake-lite](https://github.com/eelstork/caffe/tree/win-cmake-lite) Depending on your experience and requirements this or Niuzhiheng's may provide a starting point. Few differences with 64-bit except you need replacements for suggested binaries.

**Comment by longjon** [comment]
Closing as this looks like a usage issue/request for help.

This tracker is reserved for specific Caffe development issues and bugs; please ask usage questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) list.

For more information, see our [contributing guide](https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md).

Thanks!

**Comment by wangjian4500** [comment]
You can refer to: https://github.com/VisionRush/Caffe-Win32
