### ISSUE TITLE
The caffe model zoo

### ISSUE THREAD

**Issue by lgbwust** [BVLC/caffe#2769]
I run the script "python scripts/download_model_binary.py models/bvlc_reference_googlenet"
It returns
ERROR: [Errno 2] No such file or directory: 'models/bvlc_reference_googlenet/readme.md'
usage: download_model_binary.py [-h] dirname
download_model_binary.py: error: argument dirname: Must be valid Caffe model directory with a correct readme.md
I can download it now.How can I solve the problem?

**Comment by shelhamer** [comment]
Please ask usage questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) group.

The right directory is `models/bvlc_googlenet` and not `models/bvlc_reference_googlenet`.

**Comment by koolkarni** [comment]
./download_model_binary.py models/bvlc_googlenet
ERROR: [Errno 2] No such file or directory: 'models/bvlc_googlenet/readme.md'
usage: download_model_binary.py [-h] dirname
download_model_binary.py: error: argument dirname: Must be valid Caffe model directory with a correct readme.md
ubuntu@ip-172-31-6-58:~/caffe/scripts$

**Comment by beaunorgeot** [comment]
The download scripts, both .py and .sh, also fail for me with identical errors(on Ubu 14.04). This seems to be a bug (although a tiny one). The easy workaround is to: 
1.open the model's readme
2. In the header, get the model's url
3. from the model's dir on your local machine, download the model manually:
eg: $wget 'http://dl.caffe.berkeleyvision.org/bvlc_googlenet.caffemodel'

**Comment by jblakeley** [comment]
Hi, I am having the exact same trouble. However, I am not able to download the models manually as I am working within a docker file where I do not have write permissions. Has this issue been resolved so that the scripts can be used? 

Thanks!
