### ISSUE TITLE
Finding gradient of a conv-filter with regards to input for visualization through optimization

### ISSUE THREAD

**Issue by PiranjaF** [BVLC/caffe#2771]
I want to apply an optimization technique to find the gradient of a single convolutional filter in my CNN. Given a trained network with the pycaffe interface such as the one in [this example][3], how can I then find the gradient of a conv-filter with respect to the data in the input layer?

I know that `diffs = net.backward(diffs=['conv1', 'conv2'])` can give me the gradients with regards to the loss. However, I cannot do an visualization of a single filter using that.

  [3]: http://nbviewer.ipython.org/github/BVLC/caffe/blob/tutorial/examples/01-learning-lenet.ipynb

**Comment by longjon** [comment]
This tracker is for specific issues and bugs with Caffe; please ask usage questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) list. Thanks!

**Comment by PiranjaF** [comment]
Sorry if I wasn't clear enough. I can't find any functionality in Caffe that allows me to find the gradient of a filter with regards to the input. I would like to request this functionality, which would likely be useful for others as well.

**Comment by shelhamer** [comment]
See #583 #833 #1240 and search for `force_backward` but please discuss usage of `backward()` on caffe-users.
