### ISSUE TITLE
Is that possible to use the image mean in .prototxt that isn't in .binaryproto format?

### ISSUE THREAD

**Issue by anselmoferreira** [BVLC/caffe#2772]
I am not using lmdb files in my problem. For Hard disk space reasons I am using GoogleLenet and a list of images that are stored in the hard drive. In the definition of the network (train_test.prototxt) I inform what are these text files.

But to calculate the image mean the script  compute_image_mean needs the name of the LMBD folder. Is this possible to me create the mean image as a .png file and inform this in mean_file argument of the image_transform

**Comment by BlGene** [comment]
The relevant part of code is in data_transformer.cpp. Yes, you can generate a mean file yourself, but you need to save it as a serialized BlobProto instead of a .png file.

```
  // check if we want to use mean_file
  if (param_.has_mean_file()) {
    CHECK_EQ(param_.mean_value_size(), 0) <<
      "Cannot specify mean_file and mean_value at the same time";
    const string& mean_file = param.mean_file();
    LOG(INFO) << "Loading mean file from: " << mean_file;
    BlobProto blob_proto;
    ReadProtoFromBinaryFileOrDie(mean_file.c_str(), &blob_proto);
    data_mean_.FromProto(blob_proto);

**Comment by longjon** [comment]
Closing as this looks like a usage issue/request for help.

This tracker is reserved for specific Caffe development issues and bugs; please ask usage questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) list.

For more information, see our [contributing guide](https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md).

Thanks!
