### ISSUE TITLE
cuDNN not found

### ISSUE THREAD

**Issue by christopher5106** [BVLC/caffe#2777]
Hello, 
I installed Cuda, and copied cudnn.h to /usr/local/cuda/include/, libcudnn.6.5.dylib libcudnn.dylib libcudnn_static.a   to /usr/local/cuda/lib and I get during the cmake command :

-- NVIDIA CUDA:
--   Target GPU(s)     :   Auto
--   GPU arch(s)       :   sm_30
--   cuDNN             :   Not found

on OS X 10.10.4

Do you know why ?

**Comment by BlGene** [comment]
Try running ccmake and setting CUDNN_INCLUDE, CUDNN_LIBRARY and CUDNN_ROOT.

**Comment by odellus** [comment]
or   
```
cmake  -DCUDNN_INCLUDE="/your/path/to/include" -DCUDNN_LIBRARY="/your/path/to/lib" /path/to/caffe 
  ```
if you don't have ccmake.

**Comment by christopher5106** [comment]
Great thanks !

**Comment by christopher5106** [comment]
In CCMAKE i can see also for HDF5_DIR the value HDF5_DIR-NOTFOUND. 
Is it a problem ?

**Comment by BlGene** [comment]
Only if you want to used hdf5.

**Comment by christopher5106** [comment]
ok thanks

I get the following warnings, will they be problematic ?

-- Configuring done
WARNING: Target "caffe" requests linking to directory "/Users/christopherbourez/cudnn-6.5-osx-v2".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "caffe" requests linking to directory "/Users/christopherbourez/cudnn-6.5-osx-v2".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "test.testbin" requests linking to directory "/Users/christopherbourez/cudnn-6.5-osx-v2".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "caffe.bin" requests linking to directory "/Users/christopherbourez/cudnn-6.5-osx-v2".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "compute_image_mean" requests linking to directory "/Users/christopherbourez/cudnn-6.5-osx-v2".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "convert_imageset" requests linking to directory "/Users/christopherbourez/cudnn-6.5-osx-v2".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "device_query" requests linking to directory "/Users/christopherbourez/cudnn-6.5-osx-v2".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "extract_features" requests linking to directory "/Users/christopherbourez/cudnn-6.5-osx-v2".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "finetune_net" requests linking to directory "/Users/christopherbourez/cudnn-6.5-osx-v2".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "net_speed_benchmark" requests linking to directory "/Users/christopherbourez/cudnn-6.5-osx-v2".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "test_net" requests linking to directory "/Users/christopherbourez/cudnn-6.5-osx-v2".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "train_net" requests linking to directory "/Users/christopherbourez/cudnn-6.5-osx-v2".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "upgrade_net_proto_binary" requests linking to directory "/Users/christopherbourez/cudnn-6.5-osx-v2".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "upgrade_net_proto_text" requests linking to directory "/Users/christopherbourez/cudnn-6.5-osx-v2".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "classification" requests linking to directory "/Users/christopherbourez/cudnn-6.5-osx-v2".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "convert_cifar_data" requests linking to directory "/Users/christopherbourez/cudnn-6.5-osx-v2".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "convert_mnist_data" requests linking to directory "/Users/christopherbourez/cudnn-6.5-osx-v2".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "convert_mnist_siamese_data" requests linking to directory "/Users/christopherbourez/cudnn-6.5-osx-v2".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pycaffe" requests linking to directory "/Users/christopherbourez/cudnn-6.5-osx-v2".  Targets may link only to libraries.  CMake is dropping the item.
-- Generating done
-- Build files have been written to: /Users/christopherbourez/caffe/build

**Comment by BlGene** [comment]
your libraries dir might be wrong, I would try getting it to work without CUDNN first and then including it later.

**Comment by odellus** [comment]
I had the same issue. You have to give the full library path (not just the directory) for `cmake` to find the library. The flag -DCUDNN_INCLUDE should point to a directory, but if you point it at `cudnn.h` it should still work. The compiler gripes about it, but it still works.

**Comment by christopher5106** [comment]
ok 
I created a tutorial (but without cmake) http://christopher5106.github.io/big/data/2015/07/16/deep-learning-install-caffe-cudnn-cuda-for-digits-python-on-mac-osx.html

**Comment by vijayhareesh** [comment]
@christopher5106 I had similar warnings when I tried /usr/lib but it went well after i used /usr/local/cuda/lib which is ../lib from my include directory.
Hope it helps without warnings
