### ISSUE TITLE
Linking CXX shared library ../../lib/libcaffe.dylib

### ISSUE THREAD

**Issue by christopher5106** [BVLC/caffe#2778]
I get the following error. Sounds very mysterious to me. Thanks for your help again

Undefined symbols for architecture x86_64:
  "cv::imread(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int)", referenced from:
      caffe::WindowDataLayer<float>::InternalThreadEntry() in window_data_layer.cpp.o
      caffe::WindowDataLayer<double>::InternalThreadEntry() in window_data_layer.cpp.o
      caffe::ReadImageToCVMat(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, int, bool) in io.cpp.o
  "cv::imencode(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, cv::_InputArray const&, std::__1::vector<unsigned char, std::__1::allocator<unsigned char> >&, std::__1::vector<int, std::__1::allocator<int> > const&)", referenced from:
      caffe::ReadImageToDatum(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, int, int, bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, caffe::Datum*) in io.cpp.o
  "_cudnnActivationBackward", referenced from:
      caffe::CuDNNReLULayer<float>::Backward_gpu(std::__1::vector<caffe::Blob<float>*, std::__1::allocator<caffe::Blob<float>*> > const&, std::__1::vector<bool, std::__1::allocator<bool> > const&, std::__1::vector<caffe::Blob<float>*, std::__1::allocator<caffe::Blob<float>*> > const&) in cuda_compile_generated_cudnn_relu_layer.cu.o
      caffe::CuDNNReLULayer<double>::Backward_gpu(std::__1::vector<caffe::Blob<double>*, std::__1::allocator<caffe::Blob<double>*> > const&, std::__1::vector<bool, std::__1::allocator<bool> > const&, std::__1::vector<caffe::Blob<double>*, std::__1::allocator<caffe::Blob<double>*> > const&) in cuda_compile_generated_cudnn_relu_layer.cu.o
      caffe::CuDNNSigmoidLayer<float>::Backward_gpu(std::__1::vector<caffe::Blob<float>*, std::__1::allocator<caffe::Blob<float>*> > const&, std::__1::vector<bool, std::__1::allocator<bool> > const&, std::__1::vector<caffe::Blob<float>*, std::__1::allocator<caffe::Blob<float>*> > const&) in cuda_compile_generated_cudnn_sigmoid_layer.cu.o
      caffe::CuDNNSigmoidLayer<double>::Backward_gpu(std::__1::vector<caffe::Blob<double>*, std::__1::allocator<caffe::Blob<double>*> > const&, std::__1::vector<bool, std::__1::allocator<bool> > const&, std::__1::vector<caffe::Blob<double>*, std::__1::allocator<caffe::Blob<double>*> > const&) in cuda_compile_generated_cudnn_sigmoid_layer.cu.o
      caffe::CuDNNTanHLayer<float>::Backward_gpu(std::__1::vector<caffe::Blob<float>*, std::__1::allocator<caffe::Blob<float>*> > const&, std::__1::vector<bool, std::__1::allocator<bool> > const&, std::__1::vector<caffe::Blob<float>*, std::__1::allocator<caffe::Blob<float>*> > const&) in cuda_compile_generated_cudnn_tanh_layer.cu.o
      caffe::CuDNNTanHLayer<double>::Backward_gpu(std::__1::vector<caffe::Blob<double>*, std::__1::allocator<caffe::Blob<double>*> > const&, std::__1::vector<bool, std::__1::allocator<bool> > const&, std::__1::vector<caffe::Blob<double>*, std::__1::allocator<caffe::Blob<double>*> > const&) in cuda_compile_generated_cudnn_tanh_layer.cu.o
  "_cudnnActivationForward", referenced from:
      caffe::CuDNNReLULayer<float>::Forward_gpu(std::__1::vector<caffe::Blob<float>*, std::__1::allocator<caffe::Blob<float>*> > const&, std::__1::vector<caffe::Blob<float>*, std::__1::allocator<caffe::Blob<float>*> > const&) in cuda_compile_generated_cudnn_relu_layer.cu.o
      caffe::CuDNNReLULayer<double>::Forward_gpu(std::__1::vector<caffe::Blob<double>*, std::__1::allocator<caffe::Blob<double>*> > const&, std::__1::vector<caffe::Blob<double>*, std::__1::allocator<caffe::Blob<double>*> > const&) in cuda_compile_generated_cudnn_relu_layer.cu.o
      caffe::CuDNNSigmoidLayer<float>::Forward_gpu(std::__1::vector<caffe::Blob<float>*, std::__1::allocator<caffe::Blob<float>*> > const&, std::__1::vector<caffe::Blob<float>*, std::__1::allocator<caffe::Blob<float>*> > const&) in cuda_compile_generated_cudnn_sigmoid_layer.cu.o
      caffe::CuDNNSigmoidLayer<double>::Forward_gpu(std::__1::vector<caffe::Blob<double>*, std::__1::allocator<caffe::Blob<double>*> > const&, std::__1::vector<caffe::Blob<double>*, std::__1::allocator<caffe::Blob<double>*> > const&) in cuda_compile_generated_cudnn_sigmoid_layer.cu.o
      caffe::CuDNNTanHLayer<float>::Forward_gpu(std::__1::vector<caffe::Blob<float>*, std::__1::allocator<caffe::Blob<float>*> > const&, std::__1::vector<caffe::Blob<float>*, std::__1::allocator<caffe::Blob<float>*> > const&) in cuda_compile_generated_cudnn_tanh_layer.cu.o
      caffe::CuDNNTanHLayer<double>::Forward_gpu(std::__1::vector<caffe::Blob<double>*, std::__1::allocator<caffe::Blob<double>*> > const&, std::__1::vector<caffe::Blob<double>*, std::__1::allocator<caffe::Blob<double>*> > const&) in cuda_compile_generated_cudnn_tanh_layer.cu.o
  "_cudnnAddTensor", referenced from:
      caffe::CuDNNConvolutionLayer<float>::Forward_gpu(std::__1::vector<caffe::Blob<float>*, std::__1::allocator<caffe::Blob<float>*> > const&, std::__1::vector<caffe::Blob<float>*, std::__1::allocator<caffe::Blob<float>*> > const&) in cuda_compile_generated_cudnn_conv_layer.cu.o
      caffe::CuDNNConvolutionLayer<double>::Forward_gpu(std::__1::vector<caffe::Blob<double>*, std::__1::allocator<caffe::Blob<double>*> > const&, std::__1::vector<caffe::Blob<double>*, std::__1::allocator<caffe::Blob<double>*> > const&) in cuda_compile_generated_cudnn_conv_layer.cu.o
  "_cudnnConvolutionBackwardBias", referenced from:
      caffe::CuDNNConvolutionLayer<float>::Backward_gpu(std::__1::vector<caffe::Blob<float>*, std::__1::allocator<caffe::Blob<float>*> > const&, std::__1::vector<bool, std::__1::allocator<bool> > const&, std::__1::vector<caffe::Blob<float>*, std::__1::allocator<caffe::Blob<float>*> > const&) in cuda_compile_generated_cudnn_conv_layer.cu.o
      caffe::CuDNNConvolutionLayer<double>::Backward_gpu(std::__1::vector<caffe::Blob<double>*, std::__1::allocator<caffe::Blob<double>*> > const&, std::__1::vector<bool, std::__1::allocator<bool> > const&, std::__1::vector<caffe::Blob<double>*, std::__1::allocator<caffe::Blob<double>*> > const&) in cuda_compile_generated_cudnn_conv_layer.cu.o
  "_cudnnConvolutionBackwardData", referenced from:
      caffe::CuDNNConvolutionLayer<float>::Backward_gpu(std::__1::vector<caffe::Blob<float>*, std::__1::allocator<caffe::Blob<float>*> > const&, std::__1::vector<bool, std::__1::allocator<bool> > const&, std::__1::vector<caffe::Blob<float>*, std::__1::allocator<caffe::Blob<float>*> > const&) in cuda_compile_generated_cudnn_conv_layer.cu.o
      caffe::CuDNNConvolutionLayer<double>::Backward_gpu(std::__1::vector<caffe::Blob<double>*, std::__1::allocator<caffe::Blob<double>*> > const&, std::__1::vector<bool, std::__1::allocator<bool> > const&, std::__1::vector<caffe::Blob<double>*, std::__1::allocator<caffe::Blob<double>*> > const&) in cuda_compile_generated_cudnn_conv_layer.cu.o
  "_cudnnConvolutionBackwardFilter", referenced from:
      caffe::CuDNNConvolutionLayer<float>::Backward_gpu(std::__1::vector<caffe::Blob<float>*, std::__1::allocator<caffe::Blob<float>*> > const&, std::__1::vector<bool, std::__1::allocator<bool> > const&, std::__1::vector<caffe::Blob<float>*, std::__1::allocator<caffe::Blob<float>*> > const&) in cuda_compile_generated_cudnn_conv_layer.cu.o
      caffe::CuDNNConvolutionLayer<double>::Backward_gpu(std::__1::vector<caffe::Blob<double>*, std::__1::allocator<caffe::Blob<double>*> > const&, std::__1::vector<bool, std::__1::allocator<bool> > const&, std::__1::vector<caffe::Blob<double>*, std::__1::allocator<caffe::Blob<double>*> > const&) in cuda_compile_generated_cudnn_conv_layer.cu.o
  "_cudnnConvolutionForward", referenced from:
      caffe::CuDNNConvolutionLayer<float>::Forward_gpu(std::__1::vector<caffe::Blob<float>*, std::__1::allocator<caffe::Blob<float>*> > const&, std::__1::vector<caffe::Blob<float>*, std::__1::allocator<caffe::Blob<float>*> > const&) in cuda_compile_generated_cudnn_conv_layer.cu.o
      caffe::CuDNNConvolutionLayer<double>::Forward_gpu(std::__1::vector<caffe::Blob<double>*, std::__1::allocator<caffe::Blob<double>*> > const&, std::__1::vector<caffe::Blob<double>*, std::__1::allocator<caffe::Blob<double>*> > const&) in cuda_compile_generated_cudnn_conv_layer.cu.o
  "_cudnnCreate", referenced from:
      caffe::CuDNNConvolutionLayer<float>::LayerSetUp(std::__1::vector<caffe::Blob<float>*, std::__1::allocator<caffe::Blob<float>*> > const&, std::__1::vector<caffe::Blob<float>*, std::__1::allocator<caffe::Blob<float>*> > const&) in cudnn_conv_layer.cpp.o
      caffe::CuDNNConvolutionLayer<double>::LayerSetUp(std::__1::vector<caffe::Blob<double>*, std::__1::allocator<caffe::Blob<double>*> > const&, std::__1::vector<caffe::Blob<double>*, std::__1::allocator<caffe::Blob<double>*> > const&) in cudnn_conv_layer.cpp.o
      caffe::CuDNNPoolingLayer<float>::LayerSetUp(std::__1::vector<caffe::Blob<float>*, std::__1::allocator<caffe::Blob<float>*> > const&, std::__1::vector<caffe::Blob<float>*, std::__1::allocator<caffe::Blob<float>*> > const&) in cudnn_pooling_layer.cpp.o
      caffe::CuDNNPoolingLayer<double>::LayerSetUp(std::__1::vector<caffe::Blob<double>*, std::__1::allocator<caffe::Blob<double>*> > const&, std::__1::vector<caffe::Blob<double>*, std::__1::allocator<caffe::Blob<double>*> > const&) in cudnn_pooling_layer.cpp.o
      caffe::CuDNNReLULayer<float>::LayerSetUp(std::__1::vector<caffe::Blob<float>*, std::__1::allocator<caffe::Blob<float>*> > const&, std::__1::vector<caffe::Blob<float>*, std::__1::allocator<caffe::Blob<float>*> > const&) in cudnn_relu_layer.cpp.o
      caffe::CuDNNReLULayer<double>::LayerSetUp(std::__1::vector<caffe::Blob<double>*, std::__1::allocator<caffe::Blob<double>*> > const&, std::__1::vector<caffe::Blob<double>*, std::__1::allocator<caffe::Blob<double>*> > const&) in cudnn_relu_layer.cpp.o
      caffe::CuDNNSigmoidLayer<float>::LayerSetUp(std::__1::vector<caffe::Blob<float>*, std::__1::allocator<caffe::Blob<float>*> > const&, std::__1::vector<caffe::Blob<float>*, std::__1::allocator<caffe::Blob<float>*> > const&) in cudnn_sigmoid_layer.cpp.o
      ...
  "_cudnnCreateConvolutionDescriptor", referenced from:
      caffe::CuDNNConvolutionLayer<float>::LayerSetUp(std::__1::vector<caffe::Blob<float>*, std::__1::allocator<caffe::Blob<float>*> > const&, std::__1::vector<caffe::Blob<float>*, std::__1::allocator<caffe::Blob<float>*> > const&) in cudnn_conv_layer.cpp.o
      caffe::CuDNNConvolutionLayer<double>::LayerSetUp(std::__1::vector<caffe::Blob<double>*, std::__1::allocator<caffe::Blob<double>*> > const&, std::__1::vector<caffe::Blob<double>*, std::__1::allocator<caffe::Blob<double>*> > const&) in cudnn_conv_layer.cpp.o
  "_cudnnCreateFilterDescriptor", referenced from:
      void caffe::cudnn::createFilterDesc<float>(cudnnFilterStruct**, int, int, int, int) in cudnn_conv_layer.cpp.o
      void caffe::cudnn::createFilterDesc<double>(cudnnFilterStruct**, int, int, int, int) in cudnn_conv_layer.cpp.o
  "_cudnnCreatePoolingDescriptor", referenced from:
      void caffe::cudnn::createPoolingDesc<float>(cudnnPoolingStruct**, caffe::PoolingParameter_PoolMethod, cudnnPoolingMode_t*, int, int, int, int, int, int) in cudnn_pooling_layer.cpp.o
      void caffe::cudnn::createPoolingDesc<double>(cudnnPoolingStruct**, caffe::PoolingParameter_PoolMethod, cudnnPoolingMode_t*, int, int, int, int, int, int) in cudnn_pooling_layer.cpp.o
  "_cudnnCreateTensorDescriptor", referenced from:
      caffe::CuDNNConvolutionLayer<float>::LayerSetUp(std::__1::vector<caffe::Blob<float>*, std::__1::allocator<caffe::Blob<float>*> > const&, std::__1::vector<caffe::Blob<float>*, std::__1::allocator<caffe::Blob<float>*> > const&) in cudnn_conv_layer.cpp.o
      caffe::CuDNNConvolutionLayer<double>::LayerSetUp(std::__1::vector<caffe::Blob<double>*, std::__1::allocator<caffe::Blob<double>*> > const&, std::__1::vector<caffe::Blob<double>*, std::__1::allocator<caffe::Blob<double>*> > const&) in cudnn_conv_layer.cpp.o
      caffe::CuDNNPoolingLayer<float>::LayerSetUp(std::__1::vector<caffe::Blob<float>*, std::__1::allocator<caffe::Blob<float>*> > const&, std::__1::vector<caffe::Blob<float>*, std::__1::allocator<caffe::Blob<float>*> > const&) in cudnn_pooling_layer.cpp.o
      caffe::CuDNNPoolingLayer<double>::LayerSetUp(std::__1::vector<caffe::Blob<double>*, std::__1::allocator<caffe::Blob<double>*> > const&, std::__1::vector<caffe::Blob<double>*, std::__1::allocator<caffe::Blob<double>*> > const&) in cudnn_pooling_layer.cpp.o
      caffe::CuDNNReLULayer<float>::LayerSetUp(std::__1::vector<caffe::Blob<float>*, std::__1::allocator<caffe::Blob<float>*> > const&, std::__1::vector<caffe::Blob<float>*, std::__1::allocator<caffe::Blob<float>*> > const&) in cudnn_relu_layer.cpp.o
      caffe::CuDNNReLULayer<double>::LayerSetUp(std::__1::vector<caffe::Blob<double>*, std::__1::allocator<caffe::Blob<double>*> > const&, std::__1::vector<caffe::Blob<double>*, std::__1::allocator<caffe::Blob<double>*> > const&) in cudnn_relu_layer.cpp.o
      caffe::CuDNNSigmoidLayer<float>::LayerSetUp(std::__1::vector<caffe::Blob<float>*, std::__1::allocator<caffe::Blob<float>*> > const&, std::__1::vector<caffe::Blob<float>*, std::__1::allocator<caffe::Blob<float>*> > const&) in cudnn_sigmoid_layer.cpp.o
      ...
  "_cudnnDestroy", referenced from:
      caffe::CuDNNConvolutionLayer<float>::~CuDNNConvolutionLayer() in cudnn_conv_layer.cpp.o
      caffe::CuDNNConvolutionLayer<double>::~CuDNNConvolutionLayer() in cudnn_conv_layer.cpp.o
      caffe::CuDNNPoolingLayer<float>::~CuDNNPoolingLayer() in cudnn_pooling_layer.cpp.o
      caffe::CuDNNPoolingLayer<double>::~CuDNNPoolingLayer() in cudnn_pooling_layer.cpp.o
      caffe::CuDNNReLULayer<float>::~CuDNNReLULayer() in cudnn_relu_layer.cpp.o
      caffe::CuDNNReLULayer<float>::~CuDNNReLULayer() in cudnn_relu_layer.cpp.o
      caffe::CuDNNReLULayer<float>::~CuDNNReLULayer() in cudnn_relu_layer.cpp.o
      ...
  "_cudnnDestroyConvolutionDescriptor", referenced from:
      caffe::CuDNNConvolutionLayer<float>::~CuDNNConvolutionLayer() in cudnn_conv_layer.cpp.o
      caffe::CuDNNConvolutionLayer<double>::~CuDNNConvolutionLayer() in cudnn_conv_layer.cpp.o
  "_cudnnDestroyFilterDescriptor", referenced from:
      caffe::CuDNNConvolutionLayer<float>::~CuDNNConvolutionLayer() in cudnn_conv_layer.cpp.o
      caffe::CuDNNConvolutionLayer<double>::~CuDNNConvolutionLayer() in cudnn_conv_layer.cpp.o
  "_cudnnDestroyPoolingDescriptor", referenced from:
      caffe::CuDNNPoolingLayer<float>::~CuDNNPoolingLayer() in cudnn_pooling_layer.cpp.o
      caffe::CuDNNPoolingLayer<double>::~CuDNNPoolingLayer() in cudnn_pooling_layer.cpp.o
  "_cudnnDestroyTensorDescriptor", referenced from:
      caffe::CuDNNConvolutionLayer<float>::~CuDNNConvolutionLayer() in cudnn_conv_layer.cpp.o
      caffe::CuDNNConvolutionLayer<double>::~CuDNNConvolutionLayer() in cudnn_conv_layer.cpp.o
      caffe::CuDNNPoolingLayer<float>::~CuDNNPoolingLayer() in cudnn_pooling_layer.cpp.o
      caffe::CuDNNPoolingLayer<double>::~CuDNNPoolingLayer() in cudnn_pooling_layer.cpp.o
      caffe::CuDNNReLULayer<float>::~CuDNNReLULayer() in cudnn_relu_layer.cpp.o
      caffe::CuDNNReLULayer<float>::~CuDNNReLULayer() in cudnn_relu_layer.cpp.o
      caffe::CuDNNReLULayer<float>::~CuDNNReLULayer() in cudnn_relu_layer.cpp.o
      ...
  "_cudnnGetConvolutionForwardAlgorithm", referenced from:
      caffe::CuDNNConvolutionLayer<float>::Forward_gpu(std::__1::vector<caffe::Blob<float>*, std::__1::allocator<caffe::Blob<float>*> > const&, std::__1::vector<caffe::Blob<float>*, std::__1::allocator<caffe::Blob<float>*> > const&) in cuda_compile_generated_cudnn_conv_layer.cu.o
      caffe::CuDNNConvolutionLayer<double>::Forward_gpu(std::__1::vector<caffe::Blob<double>*, std::__1::allocator<caffe::Blob<double>*> > const&, std::__1::vector<caffe::Blob<double>*, std::__1::allocator<caffe::Blob<double>*> > const&) in cuda_compile_generated_cudnn_conv_layer.cu.o
  "_cudnnGetConvolutionForwardWorkspaceSize", referenced from:
      caffe::CuDNNConvolutionLayer<float>::Forward_gpu(std::__1::vector<caffe::Blob<float>*, std::__1::allocator<caffe::Blob<float>*> > const&, std::__1::vector<caffe::Blob<float>*, std::__1::allocator<caffe::Blob<float>*> > const&) in cuda_compile_generated_cudnn_conv_layer.cu.o
      caffe::CuDNNConvolutionLayer<double>::Forward_gpu(std::__1::vector<caffe::Blob<double>*, std::__1::allocator<caffe::Blob<double>*> > const&, std::__1::vector<caffe::Blob<double>*, std::__1::allocator<caffe::Blob<double>*> > const&) in cuda_compile_generated_cudnn_conv_layer.cu.o
  "_cudnnPoolingBackward", referenced from:
      caffe::CuDNNPoolingLayer<float>::Backward_gpu(std::__1::vector<caffe::Blob<float>*, std::__1::allocator<caffe::Blob<float>*> > const&, std::__1::vector<bool, std::__1::allocator<bool> > const&, std::__1::vector<caffe::Blob<float>*, std::__1::allocator<caffe::Blob<float>*> > const&) in cuda_compile_generated_cudnn_pooling_layer.cu.o
      caffe::CuDNNPoolingLayer<double>::Backward_gpu(std::__1::vector<caffe::Blob<double>*, std::__1::allocator<caffe::Blob<double>*> > const&, std::__1::vector<bool, std::__1::allocator<bool> > const&, std::__1::vector<caffe::Blob<double>*, std::__1::allocator<caffe::Blob<double>*> > const&) in cuda_compile_generated_cudnn_pooling_layer.cu.o
  "_cudnnPoolingForward", referenced from:
      caffe::CuDNNPoolingLayer<float>::Forward_gpu(std::__1::vector<caffe::Blob<float>*, std::__1::allocator<caffe::Blob<float>*> > const&, std::__1::vector<caffe::Blob<float>*, std::__1::allocator<caffe::Blob<float>*> > const&) in cuda_compile_generated_cudnn_pooling_layer.cu.o
      caffe::CuDNNPoolingLayer<double>::Forward_gpu(std::__1::vector<caffe::Blob<double>*, std::__1::allocator<caffe::Blob<double>*> > const&, std::__1::vector<caffe::Blob<double>*, std::__1::allocator<caffe::Blob<double>*> > const&) in cuda_compile_generated_cudnn_pooling_layer.cu.o
  "_cudnnSetConvolution2dDescriptor", referenced from:
      caffe::CuDNNConvolutionLayer<float>::Reshape(std::__1::vector<caffe::Blob<float>*, std::__1::allocator<caffe::Blob<float>*> > const&, std::__1::vector<caffe::Blob<float>*, std::__1::allocator<caffe::Blob<float>*> > const&) in cudnn_conv_layer.cpp.o
      caffe::CuDNNConvolutionLayer<double>::Reshape(std::__1::vector<caffe::Blob<double>*, std::__1::allocator<caffe::Blob<double>*> > const&, std::__1::vector<caffe::Blob<double>*, std::__1::allocator<caffe::Blob<double>*> > const&) in cudnn_conv_layer.cpp.o
  "_cudnnSetFilter4dDescriptor", referenced from:
      void caffe::cudnn::createFilterDesc<float>(cudnnFilterStruct**, int, int, int, int) in cudnn_conv_layer.cpp.o
      void caffe::cudnn::createFilterDesc<double>(cudnnFilterStruct**, int, int, int, int) in cudnn_conv_layer.cpp.o
  "_cudnnSetPooling2dDescriptor", referenced from:
      void caffe::cudnn::createPoolingDesc<float>(cudnnPoolingStruct**, caffe::PoolingParameter_PoolMethod, cudnnPoolingMode_t*, int, int, int, int, int, int) in cudnn_pooling_layer.cpp.o
      void caffe::cudnn::createPoolingDesc<double>(cudnnPoolingStruct**, caffe::PoolingParameter_PoolMethod, cudnnPoolingMode_t*, int, int, int, int, int, int) in cudnn_pooling_layer.cpp.o
  "_cudnnSetStream", referenced from:
      caffe::CuDNNConvolutionLayer<float>::LayerSetUp(std::__1::vector<caffe::Blob<float>*, std::__1::allocator<caffe::Blob<float>*> > const&, std::__1::vector<caffe::Blob<float>*, std::__1::allocator<caffe::Blob<float>*> > const&) in cudnn_conv_layer.cpp.o
      caffe::CuDNNConvolutionLayer<double>::LayerSetUp(std::__1::vector<caffe::Blob<double>*, std::__1::allocator<caffe::Blob<double>*> > const&, std::__1::vector<caffe::Blob<double>*, std::__1::allocator<caffe::Blob<double>*> > const&) in cudnn_conv_layer.cpp.o
  "_cudnnSetTensor4dDescriptorEx", referenced from:
      caffe::CuDNNConvolutionLayer<float>::Reshape(std::__1::vector<caffe::Blob<float>*, std::__1::allocator<caffe::Blob<float>*> > const&, std::__1::vector<caffe::Blob<float>*, std::__1::allocator<caffe::Blob<float>*> > const&) in cudnn_conv_layer.cpp.o
      caffe::CuDNNConvolutionLayer<double>::Reshape(std::__1::vector<caffe::Blob<double>*, std::__1::allocator<caffe::Blob<double>*> > const&, std::__1::vector<caffe::Blob<double>*, std::__1::allocator<caffe::Blob<double>*> > const&) in cudnn_conv_layer.cpp.o
      caffe::CuDNNPoolingLayer<float>::Reshape(std::__1::vector<caffe::Blob<float>*, std::__1::allocator<caffe::Blob<float>*> > const&, std::__1::vector<caffe::Blob<float>*, std::__1::allocator<caffe::Blob<float>*> > const&) in cudnn_pooling_layer.cpp.o
      caffe::CuDNNPoolingLayer<double>::Reshape(std::__1::vector<caffe::Blob<double>*, std::__1::allocator<caffe::Blob<double>*> > const&, std::__1::vector<caffe::Blob<double>*, std::__1::allocator<caffe::Blob<double>*> > const&) in cudnn_pooling_layer.cpp.o
      caffe::CuDNNReLULayer<float>::Reshape(std::__1::vector<caffe::Blob<float>*, std::__1::allocator<caffe::Blob<float>*> > const&, std::__1::vector<caffe::Blob<float>*, std::__1::allocator<caffe::Blob<float>*> > const&) in cudnn_relu_layer.cpp.o
      caffe::CuDNNReLULayer<double>::Reshape(std::__1::vector<caffe::Blob<double>*, std::__1::allocator<caffe::Blob<double>*> > const&, std::__1::vector<caffe::Blob<double>*, std::__1::allocator<caffe::Blob<double>*> > const&) in cudnn_relu_layer.cpp.o
      caffe::CuDNNSigmoidLayer<float>::Reshape(std::__1::vector<caffe::Blob<float>*, std::__1::allocator<caffe::Blob<float>*> > const&, std::__1::vector<caffe::Blob<float>*, std::__1::allocator<caffe::Blob<float>*> > const&) in cudnn_sigmoid_layer.cpp.o
      ...
  "_cudnnSoftmaxBackward", referenced from:
      caffe::CuDNNSoftmaxLayer<float>::Backward_gpu(std::__1::vector<caffe::Blob<float>*, std::__1::allocator<caffe::Blob<float>*> > const&, std::__1::vector<bool, std::__1::allocator<bool> > const&, std::__1::vector<caffe::Blob<float>*, std::__1::allocator<caffe::Blob<float>*> > const&) in cuda_compile_generated_cudnn_softmax_layer.cu.o
      caffe::CuDNNSoftmaxLayer<double>::Backward_gpu(std::__1::vector<caffe::Blob<double>*, std::__1::allocator<caffe::Blob<double>*> > const&, std::__1::vector<bool, std::__1::allocator<bool> > const&, std::__1::vector<caffe::Blob<double>*, std::__1::allocator<caffe::Blob<double>*> > const&) in cuda_compile_generated_cudnn_softmax_layer.cu.o
  "_cudnnSoftmaxForward", referenced from:
      caffe::CuDNNSoftmaxLayer<float>::Forward_gpu(std::__1::vector<caffe::Blob<float>*, std::__1::allocator<caffe::Blob<float>*> > const&, std::__1::vector<caffe::Blob<float>*, std::__1::allocator<caffe::Blob<float>*> > const&) in cuda_compile_generated_cudnn_softmax_layer.cu.o
      caffe::CuDNNSoftmaxLayer<double>::Forward_gpu(std::__1::vector<caffe::Blob<double>*, std::__1::allocator<caffe::Blob<double>*> > const&, std::__1::vector<caffe::Blob<double>*, std::__1::allocator<caffe::Blob<double>*> > const&) in cuda_compile_generated_cudnn_softmax_layer.cu.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [lib/libcaffe.dylib] Error 1
make[1]: *** [src/caffe/CMakeFiles/caffe.dir/all] Error 2
make: *** [all] Error 2

**Comment by longjon** [comment]
This tracker is for specific issues and bugs with Caffe; please ask installation questions on [caffe-users](https://groups.google.com/forum/#!forum/caffe-users). Thanks!

**Comment by christopher5106** [comment]
this was due to a mixed of opencv libs 
mentioned it my tutorial if it could serve anyone : http://christopher5106.github.io/big/data/2015/07/16/deep-learning-install-caffe-cudnn-cuda-for-digits-python-on-mac-osx.html
