### ISSUE TITLE
Error parsing text-format caffe.NetParameter: 394:9: Expected integer or identifier

### ISSUE THREAD

**Issue by tonnyw** [BVLC/caffe#2779]
caffe training loading failed with the following error message:
how to explain the number,'394:9' in 'caffe.NetParameter: 394:9' as the below message?

I0717 02:37:24.541980  3566 solver.cpp:70] Creating training net from net file: train_test.prototxt
[libprotobuf ERROR google/protobuf/text_format.cc:245] Error parsing text-format caffe.NetParameter: 394:9: Expected integer or identifier.
F0717 02:37:24.544946  3566 upgrade_proto.cpp:631] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: train_test.prototxt
*** Check failure stack trace: ***
    @     0x7feab793bcfd  google::LogMessage::Fail()
    @     0x7feab79410ba  google::LogMessage::SendToLog()
    @     0x7feab793dde0  google::LogMessage::Flush()
    @     0x7feab793e0cd  google::LogMessageFatal::~LogMessageFatal()
    @           0x5ab158  caffe::ReadNetParamsFromTextFileOrDie()
    @           0x57f1cb  caffe::Solver<>::InitTrainNet()
    @           0x582bbf  caffe::Solver<>::Init()
    @           0x582ff5  caffe::Solver<>::Solver()
    @           0x42ac28  caffe::GetSolver<>()
    @           0x427086  train()
    @           0x425c76  main
    @     0x7feab24fdd5d  __libc_start_main
    @           0x425459  (unknown)

**Comment by seanbell** [comment]
"394:9" means line 394, column 9.  You have a typo in the file train_test.prototxt on line 394.

**Comment by tonnyw** [comment]
thanks, it was solved

**Comment by atique81** [comment]
Hi, @seanbell @tonnyw 
any idea about the below error while running "make runtest" ? Would really appreciate any pointer to the error..

[----------] 21 tests from NetTest/2, where TypeParam = caffe::FloatGPU
[ RUN      ] NetTest/2.TestHasBlob
[       OK ] NetTest/2.TestHasBlob (1 ms)
[ RUN      ] NetTest/2.TestHasLayer
[       OK ] NetTest/2.TestHasLayer (1 ms)
[ RUN      ] NetTest/2.TestBottomNeedBackwardEuclideanForce
[       OK ] NetTest/2.TestBottomNeedBackwardEuclideanForce (0 ms)
[ RUN      ] NetTest/2.TestComboLossWeight
libprotobuf ERROR google/protobuf/text_format.cc:169] Error parsing text-format caffe.NetParameter: 1:367: Expected identifier.
F0719 18:26:45.284832 11792 test_net.cpp:28] Check failed: google::protobuf::TextFormat::ParseFromString(proto, &param)
*** Check failure stack trace: ***
    @     0x7fe141f7aa5d  google::LogMessage::Fail()
    @     0x7fe141f7eef7  google::LogMessage::SendToLog()
    @     0x7fe141f7cd59  google::LogMessage::Flush()
    @     0x7fe141f7d05d  google::LogMessageFatal::~LogMessageFatal()
    @           0x66035d  caffe::NetTest<>::InitNetFromProtoString()
    @           0x667df6  caffe::NetTest<>::InitUnsharedWeightsNet()
    @           0x67cdb0  caffe::NetTest_TestComboLossWeight_Test<>::TestBody()
    @           0x7961bd  testing::internal::HandleExceptionsInMethodIfSupported<>()
    @           0x7880b1  testing::Test::Run()
    @           0x788197  testing::TestInfo::Run()
    @           0x7882d7  testing::TestCase::Run()
    @           0x78d1df  testing::internal::UnitTestImpl::RunAllTests()
    @           0x795d6d  testing::internal::HandleExceptionsInMethodIfSupported<>()
    @           0x7876da  testing::UnitTest::Run()
    @           0x4ae82f  main
    @       0x38ee21ed5d  (unknown)
    @           0x4ae589  (unknown)
make: *** [runtest] Aborted

**Comment by longjon** [comment]
Closing; please ask usage questions on [caffe-users](https://groups.google.com/forum/#!forum/caffe-users). @atique81, if you think this is a bug that you can reproduce with the latest `master`, you're welcome to open a new issue (see https://github.com/BVLC/caffe/wiki/Reporting-Bugs-and-Other-Issues).

**Comment by imag2046** [comment]
Could you share any idea how to resolve these errors? Thanks very much. @tonnyw

**Comment by imag2046** [comment]
I have the following errors. 
------------------------------------------------------
Setting up LSTM NET
[libprotobuf ERROR google/protobuf/text_format.cc:245] Error parsing text-format caffe.NetParameter: 105:19: Message type "caffe.LayerParameter" has no field named "recurrent_param".
WARNING: Logging before InitGoogleLogging() is written to STDERR
F0629 21:50:55.635407 23922 upgrade_proto.cpp:928] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: ./s2vt.words_to_preds.deploy.prototxt
*** Check failure stack trace: ***
Aborted (core dumped)

**Comment by eriche2016** [comment]
@imag2046  how do you solve your problems
