### ISSUE TITLE
Allow MATLAB wrapper to accept start and end layers 

### ISSUE THREAD

**Issue by fariba-abbasi** [BVLC/caffe#2781]
Hi
How can I start network from middle layers?
In python interface it is possible to start and stop network in arbitrary layer with net.forward(start= 'starting layer' ,end= 'end layer' ). Is it possible in matlab interface too?

**Comment by ronghanghu** [comment]
Right now it isn't possible in current matlab wrapper to specify start and end layer during forward (however, it should not be too hard to implement).

You are welcome to send a PR to add such feature if you are interested.
