### ISSUE TITLE
Continue training in a different learning rate

### ISSUE THREAD

**Issue by jshtok** [BVLC/caffe#2786]
I have started my training with a low lr (learning rate) and have some progress after many iterations. I would like to resume the training from the current solverstate, with a new lr. 
I have changed the base_lr value in the solver.prototxt, but the old lr was loaded from the solverstate.

Is there a way to change the lr while starting from a saved state?

I apologize if this is not the right way to ask the question, bu this seems to be the only forum for Caffe questions. If there is another one, please direct me to it.

Thank you,
Joseph

**Comment by terrychenism** [comment]
You can use a fix lr in solver, and continue to train using solverstate.

**Comment by jshtok** [comment]
Hi terrychenism,
Can you please elaborate how to set a nw lr when I start training from the solversate? what do I write in the solver.prototxt?

Thank you

**Comment by terrychenism** [comment]
in solver you should set lr_policy: "fixed" and base_lr:0.01
for command: "caffe" train --solver=your.solver ----snapshot=your.solverstate

**Comment by jshtok** [comment]
Thank you, this has worked. Earlier, when I set a new lr but left the lr_policy at "step", the learning rate was loaded from previous training session. With "fixed" lr_policy, it was set to the new value in solver.
