### ISSUE TITLE
Better 

### ISSUE THREAD

**Issue by teamheisenberg** [BVLC/caffe#2787]
I have Caffe installed and I'm going through this tutorial:
http://caffe.berkeleyvision.org/gathered/examples/imagenet.html
it says:
![image](https://cloud.githubusercontent.com/assets/7588956/8768852/ef1f1d4a-2e42-11e5-9084-a0b1b28a1f87.png)

Why is the tutorial giving a path to a single jpeg file? Shouldn't the input be like a zip file with classes separated into subdirectories?

**Comment by teamheisenberg** [comment]
Found answer here:
https://github.com/cvjena/caffe_pp/blob/GradMaps/HowToTrain.md

**Comment by seanbell** [comment]
It's just showing an example of what the paths look like.  It's not saying that you have one image in your dataset.
