### ISSUE TITLE
ImportError: libprotobuf.so.10 error in  protobuf v 2.5

### ISSUE THREAD

**Issue by mtrth** [BVLC/caffe#2791]
I am new to caffe and I am facing problems with google protobuf version 2.5. When I do import caffe in python I get the error,
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/GradeScan/caffe/python/caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver
  File "/home/GradeScan/caffe/python/caffe/pycaffe.py", line 13, in <module>
    from ._caffe import Net, SGDSolver
ImportError: libprotobuf.so.10: cannot open shared object file: No such file or directory

But isnt libprotobuf.so.10 a part of protobuf 3.0? But in https://github.com/BVLC/caffe/issues/19 it was mentioned to use protobuf 2.5

**Comment by longjon** [comment]
This looks like your build is misconfigured with respect to your installed libraries.

This tracker is for specific issues and bugs with Caffe; please ask usage and installation questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) list. Thanks!
