### ISSUE TITLE
CUDA Compilation issue on MacBook

### ISSUE THREAD

**Issue by wpm** [BVLC/caffe#2792]
I am installing Caffe on a Mac Book. I am able to get it to compile and run in CPU only mode, but cannot get it to compile for the GPU. I have followed the [installation instructions](http://caffe.berkeleyvision.org/installation.html) and am not sure what to do next.

This is a Mac Book Pro running OS X 10.10.4. The graphics card is an Intel Iris Pro GPU. I am using Python from the Anaconda distribution.

I installed dependencies as outlined on the ["OS X Installation" page](http://caffe.berkeleyvision.org/install_osx.html) via Homebrew.  I installed CUDA 7 for Mac OS from the [CUDA website](https://developer.nvidia.com/cuda-downloads).  The CUDA tools are installed beneath /usr/local/cuda.

I cloned the Caffe distribution from https://github.com/BVLC/caffe. I am on commit 247d6d66 from July 15, 2015.

In Makefile.config I uncommented the Python Anaconda include lines but otherwise left things the same.

make clean;make all builds a lot of .cpp files but fails the first time it tries to use the NVCC compiler

    NVCC src/caffe/layers/absval_layer.cu
    /usr/local/include/boost/smart_ptr/detail/sp_counted_base_clang.hpp(27): error: expected a ";"
    ....
    many errors follow
    .....

sp_counted_base_clang.hpp looks fine to me. Line 27 is the first line that is neither an include or namespace statement. The only two includes preceding it are

    #include <boost/detail/sp_typeinfo.hpp>
    #include <boost/cstdint.hpp>

Maybe there is something wrong with my Boost configuration, although I was able to install Boost via Homebrew without a problem.

If I uncomment "CPU_ONLY := 1" in Makefile.config and do another clean build, I do not get any compiler errors.

(When I try to run the tests I have the problem described in issue  https://github.com/BVLC/caffe/issues/1737. I work around this by soft linking my libhdf58 libraries to libhdf9 and specifying the hdf5 headers from /usr/local/include/ in the COMMON_FLAGS in Makefile. I do not think this this is related to my CUDA compilation issue.)

Do you have any ideas why the CUDA code is not compiling for me?

**Comment by neurohn** [comment]
I think I have a pretty good idea. A Macbook or for that matter any computer, is compatible with CUDA only if it has NVIDIA GPU's. They won't work with Intel Iris Prof. Hard luck.

**Comment by longjon** [comment]
Well, the CUDA build should work with or without a compatible GPU. However, please ask installation questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) list. Thanks!
