### ISSUE TITLE
caffe looks for old libboost in ubuntu

### ISSUE THREAD

**Issue by i1abnrk** [BVLC/caffe#2804]
current Ubuntu version of libboost-dev is 1.55 but caffe has import error looking for version 1.54.

ipython
Python 2.7.10 |Anaconda 2.3.0 (64-bit)| (default, May 28 2015, 17:02:03) 
Type "copyright", "credits" or "license" for more information.

IPython 3.2.1 -- An enhanced Interactive Python.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import caffe
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-1cca3aa1f8c5> in <module>()
----> 1 import caffe

/usr/local/anaconda/lib/python2.7/site-packages/caffe/__init__.py in <module>()
----> 1 from .pycaffe import Net, SGDSolver
      2 from .pycaffe import set_mode_cpu, set_mode_gpu, set_phase_train, set_phase_test
      3 from .pycaffe import set_device
      4 from .classifier import Classifier
      5 from .detector import Detector

/usr/local/anaconda/lib/python2.7/site-packages/caffe/pycaffe.py in <module>()
      8 import numpy as np
      9 
---> 10 from ._caffe import Net, SGDSolver
     11 from ._caffe import set_mode_cpu, set_mode_gpu, set_phase_train, set_phase_test
     12 from ._caffe import set_device

ImportError: libboost_python-py27.so.1.54.0: cannot open shared object file: No such file or directory

**Comment by flx42** [comment]
> current Ubuntu version of libboost-dev is 1.55

This doesn't make sense, it depends on your Ubuntu version. The latest LTS version is 14.04 and it uses 1.54.

**Comment by lukeyeager** [comment]
It looks to me like you compiled against 1.54 but then you upgraded to 1.55. Maybe you just need to recompile?

By the way, you can wrap your output with ``` to make it more legible. See [here](https://guides.github.com/features/mastering-markdown/) under "Code".

**Comment by i1abnrk** [comment]
I'm using the development kernel, but this issue cleared up with a fresh clone of the repo, so it must have been residual config before an update. Still having other issues but this can be closed. Thanks.

**Comment by shelhamer** [comment]
Please ask installation questions on the mailing list. If you're having trouble, you might want to try the Caffe [Dockerfile](https://github.com/BVLC/caffe/tree/master/docker) to take care of installation for you.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
