### ISSUE TITLE
Error during make all

### ISSUE THREAD

**Issue by manmax31** [BVLC/caffe#2815]
I am trying to buildin caffe in MacOS 10.10.4 using CUDA 7 by `make all` using MKL but i get the following errors. Can someone tell me how to work it out?

![screen shot 2015-07-24 at 11 55 30 pm](https://cloud.githubusercontent.com/assets/2748495/8875895/85fe4752-325f-11e5-98dc-dbf405613cf4.png)

**Comment by smartbitcoin** [comment]
looks like it's missing  opencv on your enviroment. (   x64 version ).

**Comment by manmax31** [comment]
@smartbitcoin i installed ```OpenCV``` using ```brew install opencv```. Is there any other way I can do it to have the ```x64``` version?

**Comment by filmo** [comment]
I'm having the exact same issue on Mac OS X 10.9.5

Followed the  [http://caffe.berkeleyvision.org/install_osx.html Caffe Guidance] and installed opencv 2.4.10 via homebrew. 

Set:
$DYLD_FALLBACK_LIBRARY_PATH = /usr/local/cuda/lib:$HOME/anaconda/lib:/usr/local/lib:/usr/lib

Downloaded and cuDNN and placed files in /usr/local/cuda/lib

Edited the makefile.config to adjust for anaconda

Compile crashes in same place as original poster.

Do we need to provide the opencv path somewhere? (on my brew install is shows up in: /usr/local/Cellar/opencv/2.4.10.1/ )

**Comment by manmax31** [comment]
@filmo Please use CMAKE to compile

**Comment by filmo** [comment]
I'm trying that but getting a separate error regarding not finding cuDNN

```
-- NVIDIA CUDA:
--   Target GPU(s)     :   Auto
--   GPU arch(s)       :   sm_30
--   cuDNN             :   Not found
```

I placed the cuDNN files in /usr/local/cuda/lib that I downloaded from NVIDIA

*cudnn.h
*libcudnn.6.5.dylib
*libcudnn.dylib
*libcudnn_static.a

**Comment by filmo** [comment]
I added:

```
INCLUDE_DIRS += /usr/local/Cellar/opencv/2.4.10.1/include
LIBRARY_DIRS += /usr/local/Cellar/opencv/2.4.10.1/lib
```
to the Makefile.config but that doesn't seem to make a difference.

**Comment by manmax31** [comment]
@filmo 
Please try using `cmake`
```cmake  \
-DCUDNN_INCLUDE=/usr/include \
-DCUDNN_LIBRARY=/usr/lib/libcudnn.so \
 /pathToCaffe```

**Comment by filmo** [comment]
Thank you for the help. What do you mean by /pathToCaffe?

Do you mean the path to the source files? the build directory??? 

In my case, I cloned the git repository into:
/Users/pg/Desktop/version-control/caffe

ls /Users/pg/Desktop/version-control/caffe

```
CMakeLists.txt          LICENSE                 README.md               docs                    models                  tools
CONTRIBUTING.md         Makefile                caffe.cloc              examples                python
CONTRIBUTORS.md         Makefile.config         cmake                   include                 scripts
INSTALL.md              Makefile.config.example data    
```

**Comment by filmo** [comment]
I tried cmake \ -DCUDNN_INCLUDE=/usr/include \ -DCUDNN_LIBRARY=/usr/lib/libcudnn.so \ ..

Still crashes when trying to create libcaffe.dylib with essentially the same error. Doesn't like somethin gin the cv function (which I'm assuming is an opencv function)

```
[ 85%] Building CXX object src/caffe/CMakeFiles/caffe.dir/util/io.cpp.o
[ 85%] Building CXX object src/caffe/CMakeFiles/caffe.dir/util/math_functions.cpp.o
[ 86%] Building CXX object src/caffe/CMakeFiles/caffe.dir/util/upgrade_proto.cpp.o
Linking CXX shared library ../../lib/libcaffe.dylib
Undefined symbols for architecture x86_64:
  "cv::imread(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int)", referenced from:
      caffe::WindowDataLayer<float>::InternalThreadEntry() in window_data_layer.cpp.o
      caffe::WindowDataLayer<double>::InternalThreadEntry() in window_data_layer.cpp.o
      caffe::ReadImageToCVMat(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, int, bool) in io.cpp.o
  "cv::imencode(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, cv::_InputArray const&, std::__1::vector<unsigned char, std::__1::allocator<unsigned char> >&, std::__1::vector<int, std::__1::allocator<int> > const&)", referenced from:
      caffe::ReadImageToDatum(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, int, int, bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, caffe::Datum*) in io.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [lib/libcaffe.dylib] Error 1
make[1]: *** [src/caffe/CMakeFiles/caffe.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by filmo** [comment]
I think this error has something to do with [libstdc++ versus libc++ ] (https://groups.google.com/forum/#!topic/caffe-users/G7gj03A-JPw)

On a lark I changed USE_libstdcpp:BOOL=FALSE  in CMakeCache.txt to "TRUE". Now it fails on a different part of the code ('google::protobuf') instead of the 'cv' part.

**Comment by shelhamer** [comment]
Please ask installation questions on the mailing list. If you're having trouble, you might want to try the Caffe [Dockerfile](https://github.com/BVLC/caffe/tree/master/docker) to take care of installation for you.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
