### ISSUE TITLE
CSV memory data layer

### ISSUE THREAD

**Issue by smartbitcoin** [BVLC/caffe#2817]
As I know maybe 90% caffe user come from image processing, I am the few who use caffe for temporal data processing.
When data is temporal,  it don't need load into data base instead of directly to RAM since it's 1D and small in size. So I wrote a  CSV memory data layer,  which can load data from csv ( excel ) to CPU(GPU) ram.
If there are user who want this feature,  I can put a PR and contribut into caffe master.  I use this csv memory layer with parallel branch , and it works well and as it's all in ram, it's super fast too.
It need some proto chance to recognize the new model. eg , it looks like 

`layer {`
`name: "TaData"`
`type: "CsvMemoryData"`
`top: "data"`
`top: "label1"`
`top: "label2"`
`memory_data_param {`
`batch_size: 1024`
`channels: 64`
`height: 1`
`width:  1`
`cvsfile: "xxxx.csv"`
`}`
`}`
`

**Comment by iwen-kang** [comment]
Yes, this is a much needed feature and will be very helpful! Can you please publish your cvs patch in a branch so we can pull from it soon? I certainly hope you can commit to the Caffe master branch but I guess that will take time.

Thanks!

**Comment by shelhamer** [comment]
Closing as better addressed by the `Python` layer. There are many types of data, and as long as it can be handled in Python it can be handled as a Python layer.
