### ISSUE TITLE
why propagate back to target (bottom[1]) in euclidean_loss_layer?

### ISSUE THREAD

**Issue by apoliver** [BVLC/caffe#2821]
Hi,

I am wondering why need propagate back to bottom[1] in euclidean_loss_layer? Is it strange to propagate to target which actually is label for regression?

Thanks much!

for (int i = 0; i < 2; ++i) {
    if (propagate_down[i]) {
      const Dtype sign = (i == 0) ? 1 : -1;
      const Dtype alpha = sign * top[0]->cpu_diff()[0] / bottom[i]->num();
      caffe_gpu_axpby(
          bottom[i]->count(),              // count
          alpha,                              // alpha
          diff_.gpu_data(),                   // a
          Dtype(0),                           // beta
          bottom[i]->mutable_gpu_diff());  // b
    }
  }

**Comment by jeffdonahue** [comment]
This implementation makes the layer behave in the expected way regardless of the input order (i.e. `target, prediction` or `prediction, target`), as well as cases when neither input can be considered a "target" and needs to be backpropagated.  In the case where either input blob is a "target" (or more generally, a blob that the net can't influence by changing its learnable parameters), that input's `propagate_down` is set to `false`, so its gradient computation is skipped.

**Comment by apoliver** [comment]
I see. Thanks, Jeff.
