### ISSUE TITLE
how to free the memories used by setDevice?

### ISSUE THREAD

**Issue by alfredtofu** [BVLC/caffe#2823]
I found that the function `setDevice` will use gpu memories.
In my application, I need to query all the gpu devices to get the gpu with **maximum** free memories.  If I  have two gpu, I call `setDevice(0)` and then call `setDevice(1)`. And I decide to use device 1. However, the memories used by device 0 will not be freed. Are there any means to free the memories used by device 0?

**Comment by shelhamer** [comment]
Caffe lazily allocates memory but does not free it until exit, sorry!
