### ISSUE TITLE
Provide an Adam solver

### ISSUE THREAD

**Issue by slavnyk** [BVLC/caffe#2827]
Are there any plans to add Adam solver to Caffe in the near future?
[Adam: A Method for Stochastic Optimization](http://arxiv.org/abs/1412.6980)
[Python implementation (Theano)](https://github.com/Lasagne/Lasagne/issues/144)
[Lua implementation (Torch)](https://github.com/torch/optim/blob/master/adam.lua)
I have been using the Lua implemenation for training neural networks for low-level image processing (such as [noise reduction and super-resolution](https://github.com/nagadomi/waifu2x)) with great success, but could not reproduce results of similar quality in Caffe with SGD/Adagrad/Nesterov. There are reports of better results (faster, more accurate) when training various types of deep networks using Adam.

**Comment by kashif** [comment]
I would like to try to do this, if no one else has started. I took the time to update the adam implementation for Lasagne and torch to the latest version of the paper.  So next I will try to implement it in caffe.

**Comment by PatWie** [comment]
Just started to write the CPU version:
https://github.com/PatWie/caffe/blob/adam/src/caffe/solver.cpp

Not sure if we really want to use

   this->iter

for computing the effective stepsize.

**Comment by kashif** [comment]
Ok I was thinking perhaps:

```c++
int t = this->iter_ / this->param_.stepsize() + 1;
```

**Comment by shelhamer** [comment]
Thanks for the suggested solver. Closing as addressed by #2856 -- see the PR for status.
