### ISSUE TITLE
In MATLAB, cannot find caffe_.cpp

### ISSUE THREAD

**Issue by Paralysis** [BVLC/caffe#2828]
Because caffe_.cpp is a private function, when I call functions like caffe.reset_all(), there will always be a error telling me it cannot find caffe_.cpp. 

So how to use that in MATLAB?

**Comment by ronghanghu** [comment]
After compiling by running `make matcaffe`, you should have a `caffe_.mex64a` (the extension may vary on your platform) in `caffe/matlab/+caffe/private`, however, you are not expected to access it directly. Instead, add `caffe/matlab` directory to your MATLAB Path.

You may refer to http://caffe.berkeleyvision.org/tutorial/interfaces.html#matlab for a tutorial on compiling and usage of matcaffe.

**Comment by longjon** [comment]
Closing as this looks like a usage issue/request for help.

This tracker is reserved for specific Caffe development issues and bugs; please ask usage questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) list.

For more information, see our [contributing guide](https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md).

Thanks!
