### ISSUE TITLE
pycaffe net.forward() assumes end blobs have the same name as their layers

### ISSUE THREAD

**Issue by cdoersch** [BVLC/caffe#2829]
If you call `net.forward(end='somelayer')` from python, where `somelayer` is a layer that has a different name for its output blob, _Net_forward() will attempt to access `net.blobs['somelayer']` (and in fact, returns this as the output).  This happens because [this line](https://github.com/BVLC/caffe/blob/master/python/caffe/pycaffe.py#L80) appends the end layer name to the list of blobs to be output. If the appended name doesn't exist as a blob, the result is an exception.  

Note that there may also be multiple outputs for the end layer, in which case the current behavior doesn't make sense either.

**Comment by vishakhhegde** [comment]
I too had the same issue. For my application, I just needed to comment out the line "return {out: self.blobs[out].data for out in outputs}" in pycaffe.py. Forward propagation now happens without returning any blob vectors.

**Comment by shelhamer** [comment]
Note that #5519 fixed the layer/top name issue but still does not handle multiple tops as #2975 does.

**Comment by Noiredd** [comment]
I just checked `forward` on `Slice` layer with 2 tops and it worked just fine. Also checked in conjunction with `blobs` param with no problems. @shelhamer any example where it fails? I'll be glad to improve the code.

**Comment by shelhamer** [comment]
@Noiredd sorry, I misspoke! This looks like it handles everything 👍

**Comment by Noiredd** [comment]
@shelhamer Looks like this issue is fully resolved then :)
