### ISSUE TITLE
Caffe CUDA issue

### ISSUE THREAD

**Issue by 12rohanb** [BVLC/caffe#2832]
I'm trying to build caffe with the python wrapper on Mac OSX 10.0, but keep getting the following error when I execute make runtest.

Check failed: error == cudaSuccess (35 vs. 0) CUDA driver version is insufficient for CUDA runtime version

I've updated the CUDA driver to the latest version online. Tried uninstalling and reinstalling CUDA and the driver, but the error still persists. Any advice would be much appreciated. Thanks!

**Comment by 12rohanb** [comment]
Nevermind, realized my computer had an AMD GPU, and it wouldn't work with CUDA.

**Comment by bhack** [comment]
You could try the opencl version.

**Comment by tzutalin** [comment]
https://github.com/BVLC/caffe/pull/2610 has opencl version. Try it if your OpenCL can work on your environment.
