### ISSUE TITLE
Check failed: ShapeEquals(proto) shape mismatch  (reshape not set)

### ISSUE THREAD

**Issue by Linzert** [BVLC/caffe#2834]
When I finetune a model,I got the error message below:
I0729 16:17:21.237010  7683 net.cpp:218] Network initialization done.
I0729 16:17:21.237015  7683 net.cpp:219] Memory required for data: 494328700
I0729 16:17:21.237133  7683 solver.cpp:42] Solver scaffolding done.
I0729 16:17:21.237192  7683 caffe.cpp:86] Finetuning from models/fcn-8s/fcn-8s-pascalcontext.caffemodel
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:505] Reading dangerously large protocol message.  If the message turns out to be larger than 2147483647 bytes, parsing will be halted for security reasons.  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:78] The total number of bytes read was 542361868
F0729 16:17:21.807909  7683 blob.cpp:454] Check failed: ShapeEquals(proto) shape mismatch 
(reshape not set)
What's the problem?

**Comment by ducha-aiki** [comment]
@Linzert I had such problem, when copy-pasted data layers parameter from AlexNet to VGGNet. The problem was crop size: 227 or 224.

**Comment by Linzert** [comment]
@ducha-aiki  Thanks for your reply!But I tried it and occured the same problem.So I think the problem may be not here.Do you have any other idea?

**Comment by atique81** [comment]
Hi @Linzert,
I guess, you are trying to fine-tune using the Fully-Convolutional Caffe model provided by @longjon . I am also trying to do so, but using the alexnet caffemodel and stuck in the same error.
Did you find any solution?

**Comment by Linzert** [comment]
@atique81 I don't have any good idea.If I have,I will tell you and I also hope the you could tell me if you have one.

**Comment by atique81** [comment]
Thanks @Linzert ......By the way, can you please provide me your email address, since I have some other issues to discuss with you regarding Fully Convolutional Semantic Segmentation?

**Comment by Linzert** [comment]
@atique81    linzertling@gmail.com

**Comment by atique81** [comment]
Hi, @Linzert,

what about this post https://groups.google.com/forum/#!topic/caffe-users/riTWI6nlIJ4. 

I haven't tried it yet though.

**Comment by longjon** [comment]
Closing as this looks like a usage issue/request for help.

This tracker is reserved for specific Caffe development issues and bugs; please ask usage questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) list.

For more information, see our [contributing guide](https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md).

Thanks!

**Comment by deepsemantic** [comment]
Hi all, I have same error, but I fixed it by simply rename "fc8", hope it helps!
