### ISSUE TITLE
How to deploy lenet_iter_10000 in my application?

### ISSUE THREAD

**Issue by Darknesszlx** [BVLC/caffe#2838]
The final model, stored as a binary protobuf file, is stored at lenet_iter_10000 which you can deploy as a trained model in your application, if you are training on a real-world application dataset.

I wonder how can I deploy lenet_iter_10000 in my application?

**Comment by BlGene** [comment]
An easy option would be to load the the binary protobuf via the python API, then write a function that does the required classification. Have a look [here](https://github.com/BVLC/caffe/blob/master/examples/web_demo/app.py) for example.

This is a usage question and shouldn't really be an issue.

BR, Max

**Comment by Darknesszlx** [comment]
Is there any C++ API?

**Comment by tzutalin** [comment]
First, you can refer it.
https://github.com/tzutalin/caffe_test
Second,
$ cafferoot/examples/cpp_classification/classification.cpp

**Comment by longjon** [comment]
Closing as this looks like a usage issue/request for help.

This tracker is reserved for specific Caffe development issues and bugs; please ask usage questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) list.

For more information, see our [contributing guide](https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md).

Thanks!
