### ISSUE TITLE
Implement transformations as layers

### ISSUE THREAD

**Issue by IMG-PRCSNG** [BVLC/caffe#2840]
There have been multiple issues regarding transformations not being applied properly in **memory data layer** and _Ignored_ in **HDF5 Data layer**. I have also noticed that there is a separate _transform_ function for 
- **Datum** (used by lmdb backend) 
- **OpenCV Mat** ( used by memory data layer - > addMatVector ) 
- **Caffe Blobs** ( which, i think, can be used along with hdf5 data layer )

Is there a possibility in combining everything by adding Transformation as a layer? 
This will enable us to apply transformations to in-memory 4D array using OpenCV, Magick++, etc. with just a reference to the memory blob ( OpenCV also supports GPU ops (using _CUDA_ and _OpenCL_ which can help batch processing ).

Thoughts?

**Comment by ronghanghu** [comment]
Currently, I think the most convenient way to do transformation is to use a PythonLayer. A transform layer was previously proposed in #569 but was declined due to overhead issues (see discussions in #569 for details).

**Comment by IMG-PRCSNG** [comment]
I went through #569 and I think I understood why creating a separate transform layer will add memory and speed overhead issues. But I also feel that we should at least support in-place ops on data ( as there is no memory overhead ) and add threading to solve speed overhead. But yes, according to #569 it is costlier to save a copy of the image as it doubles up the memory consumption by the data layer for non in-place operations.

Though it requires certain implementation changes, My idea was to separate the data layers from the processing layers so that an **Asynchronous Queue** of batches can be prepared by the CPU while the GPU computes the *forward* and *backward* functions. But again, it becomes and issue for CPU only builds but it would definitely be an improvement for GPU builds at no cost. If multiple GPU devices are present, we can utilize to batch process the input data and transfer the transformed batch from one device to the other.

So, Looks like this has become more of a feature request than an issue. I am just keeping this open for the Mods to review and close if necessary.

**Comment by longjon** [comment]
Yes, transformations as layers is something we've discussed in the past and desire, so long as prefetching and memory usage can be worked out. I can't find a specific existing issue on this so I'll make this that for now.

**Comment by bhack** [comment]
:+1:

**Comment by sguada** [comment]
I still think is a good idea.

Sergio

**Comment by lukeyeager** [comment]
:+1:

**Comment by achalddave** [comment]
Would it be worthwhile to first add a TransformationLayer that does incur overhead, but leave data layers as they are? I'm still new to this, but it seems that it is common to write Python data layers without prefetching, and reimplement transformations (e.g. [SimpleTransformer](https://github.com/BVLC/caffe/blob/be163be0ea5befada208dbf0db29e6fa5811dc86/examples/pycaffe/tools.py#L4)) inside the Python data layer. Having a TransformationLayer could at least make that process cleaner.

**Comment by shelhamer** [comment]
Closing as better addressed by a Python data layer, because while Python data layers do not prefetch by default, one can handle prefetching through multiprocessing.
