### ISSUE TITLE
Super Resolution with CNN

### ISSUE THREAD

**Issue by acpn** [BVLC/caffe#2841]
Hi guys, I'm trying use super resolution by http://mmlab.ie.cuhk.edu.hk/projects/SRCNN.html

but after I use a super resolution in a single image i got the worse quality, I'm newbie in deep learning, but some thing is very strange.

See the images below

![original](https://cloud.githubusercontent.com/assets/12258695/9015347/b2104a7c-379e-11e5-9d5e-0f1f66338d53.png)
![srcnn](https://cloud.githubusercontent.com/assets/12258695/9015346/b20fd6be-379e-11e5-92c9-70211fe5877a.png)

Any idea??

Thanks

**Comment by longjon** [comment]
Closing as this looks like a usage issue/request for help.

This tracker is reserved for specific Caffe development issues and bugs; please ask usage questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) list.

For more information, see our [contributing guide](https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md).

Thanks!
