### ISSUE TITLE
Mutable gpu data error

### ISSUE THREAD

**Issue by swamiviv** [BVLC/caffe#2844]
I changed the contrastive loss layer a bit to define a new loss function for which the CPU version works. The gpu version compiles, but when I start training I get the following error:

```
F0801 00:02:53.291753 12738 blob.cpp:108] Check failed: data_ 
*** Check failure stack trace: ***
    @     0x7fc8ad8ede6d  (unknown)
    @     0x7fc8ad8efced  (unknown)
    @     0x7fc8ad8eda5c  (unknown)
    @     0x7fc8ad8f063e  (unknown)
    @     0x7fc8b37bb24e  caffe::Blob<>::mutable_gpu_data()
    @     0x7fc8b38028b0  caffe::AngleLossLayer<>::Forward_gpu()
    @     0x7fc8b37ccbc9  caffe::Net<>::ForwardFromTo()
    @     0x7fc8b37ccff7  caffe::Net<>::ForwardPrefilled()
    @     0x7fc8b37dc147  caffe::Solver<>::Test()
    @     0x7fc8b37dca06  caffe::Solver<>::TestAll()
    @     0x7fc8b37e58cb  caffe::Solver<>::Step()
    @     0x7fc8b37e628f  caffe::Solver<>::Solve()
    @           0x406786  train()
    @           0x404cd1  main
    @     0x7fc8a79cdaf5  __libc_start_main
    @           0x40527d  (unknown)
```

Any help would be appreciated.

**Comment by longjon** [comment]
Closing as this looks like a usage issue/request for help.

This tracker is reserved for specific Caffe development issues and bugs; please ask usage questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) list.

For more information, see our [contributing guide](https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md).

Thanks!
