### ISSUE TITLE
Support additional OpenCV Mat types

### ISSUE THREAD

**Issue by IMG-PRCSNG** [BVLC/caffe#2845]
The **data_transformer**, when using the memory_data layer's _addMatVector_, calls the respective Transform function for each Mat in the vector. 

There is a statement which is used to initialize the **ptr** to each row of the Mat vector. But it is static cast to **uchar**\* assuming input image is of depth **CV_8U**. This becomes a problem when input Mat is of different depth ( _CV_32F, CV_64F, etc._ ). I think this problem can be resolved with templates and traits but I have no experience in coding with traits.

Is there a possibility of a fix or workaround ?

**Comment by longjon** [comment]
I think a mild patch for more OpenCV types could be accepted, though in the longer term I think we'd rather factor out than tightly integrate OpenCV functionality, so I don't expect a lot of core dev attention here.

Of course there are workarounds: convert your data, code the types you need, use the raw memory interface, write a layer, etc...

**Comment by bhack** [comment]
If you need only forward pass see https://github.com/Itseez/opencv_contrib/pull/265

**Comment by IMG-PRCSNG** [comment]
Currently my workaround is to *template the datatype* in the transform function and check the depth of the Mat with a **switch-case** and call the respective transform function with the respective template datatype in the data layers. I wanted to keep the current implementation of the data transformer function parts clean and reuse the code. But the switch-case looks ugly when it reappears at every point in the data layers where a Mat is being passed to the transformer.

I was just wondering if we can initialize the pointer type in the data layers just like we initialize caffe Net with *float* or *double*.

Thoughts?

**Comment by shelhamer** [comment]
Closing as better addressed through Python data layers, since there are many data types.
