### ISSUE TITLE
layer-wised unsupervised  feature learning 

### ISSUE THREAD

**Issue by zkl123** [BVLC/caffe#2846]
I've read some papers about unsupervised training CNN, it can provide the network initial data,so results may be better.I wonder caffe support this way? if so,how can I define the network proto file.
thanks!

**Comment by longjon** [comment]
Closing as this looks like a usage issue/request for help.

This tracker is reserved for specific Caffe development issues and bugs; please ask usage questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) list.

For more information, see our [contributing guide](https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md).

Thanks!
