### ISSUE TITLE
hdf5.h file not found when doing a "make all"

### ISSUE THREAD

**Issue by shyamalschandra** [BVLC/caffe#2849]
Do I have the configuration of the makefile wrong?

Thanks!

Configuration below:

![image](https://cloud.githubusercontent.com/assets/9545735/9038532/b6183f3c-39a9-11e5-94c7-dc47919c3f41.png)

**Comment by IMG-PRCSNG** [comment]
How did you install the **dependencies** for caffe?

If you have used `apt-get` (with root permissions) to install the *dependencies*, I don't think you will get this error.

But if you have downloaded the **source** of hdf5 and compiled it yourself, then you need to add the the respective *include*, *lib* and *ldflags* to the file, **Makefile.config**

Try adding the include directory of the compiled hdf5 source in the *INCLUDE_DIRS* ( below the line "Whatever else you find you need goes here", separated by space for more than one directory )
and
add the compiled library directory ( which contains the static and shared libraries of hdf5 ) to the line below it ( Named *LIBRARY_DIRS* )

Hope it works.

**Comment by ronghanghu** [comment]
On ubuntu 14.04 you may need to do 

    INCLUDE_DIRS := $(PYTHON_INCLUDE) /usr/local/include /usr/include/hdf5/serial/
    LIBRARY_DIRS := $(PYTHON_LIB) /usr/local/lib /usr/lib /usr/lib/x86_64-linux-gnu/hdf5/serial/

since those hdf5 headers and libraries are installed in different locations than in Ubuntu 12.04.

**Comment by bhack** [comment]
Please don't feed  support  ticket in the caffe zoo.

**Comment by ronghanghu** [comment]
@bhack OK, I'll redirect them to [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) next time.
