### ISSUE TITLE
fail to link gflag

### ISSUE THREAD

**Issue by micheleAlberto** [BVLC/caffe#2852]
from the current master branch , on Ubuntu 14.04 LTS
using the standard makefile with CPU_ONLY := 1 the build process stop linking

CXX tools/compute_image_mean.cpp
CXX/LD -o .build_release/tools/compute_image_mean.bin
/usr/bin/ld: .build_release/tools/compute_image_mean.o: undefined reference to symbol '_ZN6google15SetUsageMessageERKSs'
//usr/lib/x86_64-linux-gnu/libgflags.so.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make: *** [.build_release/tools/compute_image_mean.bin] Error 1

with 
readelf -Ws /usr/lib/x86_64-linux-gnu/libgflags.so.2

i can confirm that the DSO has the said symbol. 
Am i missing something ?

**Comment by odellus** [comment]
This is a problem with building against static vs dynamic libraries. Try `VERBOSE=1 make` and see if the `-shared` flag is being passed during the linking phase as without that flag, the linker won't be able to make sense of the symbols in the dynamic libgflags.so library.

**Comment by JakaCikac** [comment]
Hello!

Can you be more specific as to how to solve this issue? 

Thanks.

**Comment by odellus** [comment]
If `-shared` isn't being used in the linking phase you might have to add it manually during configuration with `cmake` or possibly afterwards with a `CFLAG`. `VERBOSE=1 make` will let you see what flags `ld` is being handed. I don't remember exactly how I did it as that was a while ago.

**Comment by BoomFan** [comment]
I've been wasting my time on this for days!! Here's my solution.
Before I compile Caffe, I did this:
In my Caffe directory:   /caffe/cmake/External
there is a file named:  gflags.cmake
In which, there is a line
set(GFLAGS_LIBRARIES ${gflags_INSTALL}/lib/libgflags.a ${CMAKE_THREAD_LIBS_INIT})

Then add the following after the above line:
set(GFLAGS_LIBRARIES ${gflags_INSTALL}/lib/libgflags.so ${CMAKE_THREAD_LIBS_INIT})

Then, compile caffe.

Hope this helps!

**Comment by soulslicer** [comment]
I tried the above..but still get the error:

/usr/bin/ld: CMakeFiles/classification_test.dir/src/classification_test.cpp.o: undefined reference to symbol '_ZN6google4base21CheckOpMessageBuilderD1Ev'
//usr/lib/x86_64-linux-gnu/libglog.so.0: error adding symbols: DSO missing from command line

**Comment by BoomFan** [comment]
I tried on my second computer. Error still exist...Sry, I may not provide thr right solution. It only works for my first computer. I am now more prefer to call this error as a bug.

Let us know if you find the solution.

**Comment by soulslicer** [comment]
Nevermind..i just include Glog in my cmakelists and it works now

**Comment by kvmanohar22** [comment]
@soulslicer You just need to add `libglog.so.0` library to the list of `LIBRARIES` the linker uses to link during the linking phase. It can be done like this by adding the following line in your `CMakeLists.txt`. 

`list(APPEND LIBRARIES "/usr/lib/x86_64-linux-gnu/libglog.so.0")`

**Comment by zzqiuzz** [comment]
Append with flag "-lboost_system -lglog" in your command line

**Comment by soulslicer** [comment]
those are all quite hacky 

i just did this in my cmake
```

find_package(Caffe REQUIRED)
find_package(CUDA REQUIRED)
find_package(Glog REQUIRED)
if(CUDA_FOUND)
add_definitions(-DCUDA_FOUND)
endif(CUDA_FOUND)
include_directories(
  ${CAFFE_INCLUDE_DIRS}
  ${CUDA_INCLUDE_DIRS}
  ${GLOG_INCLUDE_DIR}
)
target_link_libraries(
  **
  ${CAFFE_LIBRARIES}
  ${CUDA_LIBRARIES}
  ${GLOG_LIBRARY}
)
```

**Comment by advance512** [comment]
If you're installing caffe via conda and running into this, try:
```
conda install python=2.7 caffe-gpu protobuf gflags
```

**Comment by yestinl** [comment]
> Append with flag "-lboost_system -lglog" in your command line

I want to know where should I append?

**Comment by yestinl** [comment]
> Nevermind..i just include Glog in my cmakelists and it works now

Can you tell me the specified place to modify?

**Comment by ghost** [comment]
Stop stop to message

Le dim. 8 mars 2020 6 h 06 a.m., yestinl <notifications@github.com> a
écrit :
