### ISSUE TITLE
Error when import caffe

### ISSUE THREAD

**Issue by skywalker1990** [BVLC/caffe#2857]
After compile caffe,I use make pycaffe, but when I import caffe,the error happens.

ImportError: libboost_python.so.1.56.0: undefined symbol: PyUnicodeUCS4_FromEncodedObject

**Comment by IMG-PRCSNG** [comment]
Can you please leave a comment on how to reproduce the error?
Can you also check in the user mailing list and dev mailing list if this has been reported before?

**Comment by shelhamer** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
