### ISSUE TITLE
Matcaffe incompatible with Octave

### ISSUE THREAD

**Issue by hidiryuzuguzel** [BVLC/caffe#2858]
Hi everyone,

Is there anyone who could succed in building & compiling matcaffe using octave instead of matlab ? I could run "cmake .. -DBUILD_matlab=ON && make -j4" succesfully. However, "make matcaffe" and "make mattest" fails with the following message: make: *** No rule to make target `mattest'.  Stop.  

BR

**Comment by ronghanghu** [comment]
The current matcaffe is built on some advanced features of matlab (such as `container.Map`) and the test cases are built upon `matlab.unittest.TestCase`. These features have not been implemented in Octave yet, so currently I don't expect anyone to run matcaffe with octave.
