### ISSUE TITLE
Console output spoiled with many printouts 'Train net output'

### ISSUE THREAD

**Issue by febert** [BVLC/caffe#2875]
Hello,

I am running a modified cnn based on the bvlc_reference_caffenet model.
The only difference is that I use image-layers instead of the lmdb-data-layer and an hdf5 layer for the labels (multi-dim regression).

The problem is that the console output is spoiled by thousands of lines of this kind:
I0806 17:34:46.422387 16373 solver.cpp:229]     Train net output #23871: data = 119
I0806 17:34:46.422399 16373 solver.cpp:229]     Train net output #23872: data = 122
I0806 17:34:46.422408 16373 solver.cpp:229]     Train net output #23873: data = 122
I0806 17:34:46.422418 16373 solver.cpp:229]     Train net output #23874: data = 122
I0806 17:34:46.422430 16373 solver.cpp:229]     Train net output #23875: data = 123

The label associated with each image-file in train_fullpath.txt is not needed and shall be discarded with the silence layer. Does the silence layer not function properly thus causing the undesired output?

name: "CaffeNet"
layer {
  name: "train_label"
  type: "HDF5Data"
  top: "train_label"
  hdf5_data_param {
    source: "/home/ubuntu/grasping/2015-DL-MrPink/caffe/Image_Net_full_grasping/data/train_label.txt" # num_sample x 6 array
    batch_size: 256
  }
    include {
    phase: TRAIN
  }
}
layer {
  name: "test_label"
  type: "HDF5Data"
  top: "test_label"
  hdf5_data_param {
    source: "/home/ubuntu/grasping/2015-DL-MrPink/caffe/Image_Net_full_grasping/data/test_label.txt"  # num_sample x 60 array
    batch_size: 256
  }
    include {
    phase: TEST
  }
}
#####
layers {
name: "images"
type: IMAGE_DATA
top: "data"
top: "dummy1"
image_data_param {
source: "/home/ubuntu/grasping_data/Agument_Data/train_fullpath.txt"
batch_size: 256
crop_size: 224
shuffle: false
}
#transform_param {
#scale: 0.00390625
#mirror: false
#crop_size: 224
#}
include: { phase: TRAIN }
}

layers {
name: "images"
type: IMAGE_DATA
top: "data"
top: "dummy2"
image_data_param {
source: "/home/ubuntu/grasping_data/Agument_Data/test_fullpath.txt"
batch_size: 50
shuffle: false
crop_size: 224
}
transform_param {
scale: 0.00390625
mirror: false
crop_size: 224
}
include: { phase: TEST }
}

layers {
  name: "silence_layer"
  type: SILENCE
  bottom: "dummy1"
  include: { phase: TRAIN }
}

layers {
  name: "silence_layer"
  type: SILENCE
  bottom: "dummy2"
  include: { phase: TEST }
}

###
layer {
  name: "conv1"
  type: "Convolution"
  bottom: "data"
  top: "conv1"
  param {
    lr_mult: 1
    decay_mult: 1
  }
  param {
    lr_mult: 2
    decay_mult: 0
  }
  convolution_param {
    num_output: 96
    kernel_size: 11
    stride: 4
    weight_filler {
      type: "gaussian"
      std: 0.01
    }
    bias_filler {
      type: "constant"
      value: 0
    }
  }
}
layer {
  name: "relu1"
  type: "ReLU"
  bottom: "conv1"
  top: "conv1"
}
layer {
  name: "pool1"
  type: "Pooling"
  bottom: "conv1"
  top: "pool1"
  pooling_param {
    pool: MAX
    kernel_size: 3
    stride: 2
  }
}
layer {
  name: "norm1"
  type: "LRN"
  bottom: "pool1"
  top: "norm1"
  lrn_param {
    local_size: 5
    alpha: 0.0001
    beta: 0.75
  }
}
layer {
  name: "conv2"
  type: "Convolution"
  bottom: "norm1"
  top: "conv2"
  param {
    lr_mult: 1
    decay_mult: 1
  }
  param {
    lr_mult: 2
    decay_mult: 0
  }
  convolution_param {
    num_output: 256
    pad: 2
    kernel_size: 5
    group: 2
    weight_filler {
      type: "gaussian"
      std: 0.01
    }
    bias_filler {
      type: "constant"
      value: 1
    }
  }
}
layer {
  name: "relu2"
  type: "ReLU"
  bottom: "conv2"
  top: "conv2"
}
layer {
  name: "pool2"
  type: "Pooling"
  bottom: "conv2"
  top: "pool2"
  pooling_param {
    pool: MAX
    kernel_size: 3
    stride: 2
  }
}
layer {
  name: "norm2"
  type: "LRN"
  bottom: "pool2"
  top: "norm2"
  lrn_param {
    local_size: 5
    alpha: 0.0001
    beta: 0.75
  }
}
layer {
  name: "conv3"
  type: "Convolution"
  bottom: "norm2"
  top: "conv3"
  param {
    lr_mult: 1
    decay_mult: 1
  }
  param {
    lr_mult: 2
    decay_mult: 0
  }
  convolution_param {
    num_output: 384
    pad: 1
    kernel_size: 3
    weight_filler {
      type: "gaussian"
      std: 0.01
    }
    bias_filler {
      type: "constant"
      value: 0
    }
  }
}
layer {
  name: "relu3"
  type: "ReLU"
  bottom: "conv3"
  top: "conv3"
}
layer {
  name: "conv4"
  type: "Convolution"
  bottom: "conv3"
  top: "conv4"
  param {
    lr_mult: 1
    decay_mult: 1
  }
  param {
    lr_mult: 2
    decay_mult: 0
  }
  convolution_param {
    num_output: 384
    pad: 1
    kernel_size: 3
    group: 2
    weight_filler {
      type: "gaussian"
      std: 0.01
    }
    bias_filler {
      type: "constant"
      value: 1
    }
  }
}
layer {
  name: "relu4"
  type: "ReLU"
  bottom: "conv4"
  top: "conv4"
}
layer {
  name: "conv5"
  type: "Convolution"
  bottom: "conv4"
  top: "conv5"
  param {
    lr_mult: 1
    decay_mult: 1
  }
  param {
    lr_mult: 2
    decay_mult: 0
  }
  convolution_param {
    num_output: 256
    pad: 1
    kernel_size: 3
    group: 2
    weight_filler {
      type: "gaussian"
      std: 0.01
    }
    bias_filler {
      type: "constant"
      value: 1
    }
  }
}
layer {
  name: "relu5"
  type: "ReLU"
  bottom: "conv5"
  top: "conv5"
}
layer {
  name: "pool5"
  type: "Pooling"
  bottom: "conv5"
  top: "pool5"
  pooling_param {
    pool: MAX
    kernel_size: 3
    stride: 2
  }
}
layer {
  name: "fc6_grasp"
  type: "InnerProduct"
  bottom: "pool5"
  top: "fc6_grasp"
  param {
    lr_mult: 1
    decay_mult: 1
  }
  param {
    lr_mult: 2
    decay_mult: 0
  }
  inner_product_param {
    num_output: 2048
    weight_filler {
      type: "gaussian"
      std: 0.005
    }
    bias_filler {
      type: "constant"
      value: 1
    }
  }
}
layer {
  name: "relu6"
  type: "ReLU"
  bottom: "fc6_grasp"
  top: "fc6_grasp"
}
layer {
  name: "drop6"
  type: "Dropout"
  bottom: "fc6_grasp"
  top: "fc6_grasp"
  dropout_param {
    dropout_ratio: 0.5
  }
}
layer {
  name: "fc7_grasp"
  type: "InnerProduct"
  bottom: "fc6_grasp"
  top: "fc7_grasp"
  param {
    lr_mult: 1
    decay_mult: 1
  }
  param {
    lr_mult: 2
    decay_mult: 0
  }
  inner_product_param {
    num_output: 2048
    weight_filler {
      type: "gaussian"
      std: 0.005
    }
    bias_filler {
      type: "constant"
      value: 1
    }
  }
}
layer {
  name: "relu7"
  type: "ReLU"
  bottom: "fc7_grasp"
  top: "fc7_grasp"
}
layer {
  name: "drop7"
  type: "Dropout"
  bottom: "fc7_grasp"
  top: "fc7_grasp"
  dropout_param {
    dropout_ratio: 0.5
  }
}
layer {
  name: "fc8_grasp"
  type: "InnerProduct"
  bottom: "fc7_grasp"
  top: "fc8_grasp"
  param {
    lr_mult: 1
    decay_mult: 1
  }
  param {
    lr_mult: 2
    decay_mult: 0
  }
  inner_product_param {
    num_output: 6
    weight_filler {
      type: "gaussian"
      std: 0.01
    }
    bias_filler {
      type: "constant"
      value: 0
    }
  }
}
layer {
  name: "sumofsquares"
  type: "EuclideanLoss"
  bottom: "fc8_grasp"
  bottom: "train_label"
  top: "loss"
  include {
    phase: TRAIN
  }
}

**Comment by seanbell** [comment]
Ah, some of your layers are a "layer" and others are "layers".  You need to make them all consistent as "layer".  You probably copied from somewhere else that used the old API.

@jeffdonahue  perhaps it is a good idea to detect this and generate an error, since it can lead to subtle unintuitive errors when mixing "layer" and "layers" in the prototext.

**Comment by shelhamer** [comment]
Closing this as a usage issue but I posted @seanbell's suggestion in #2889.
