### ISSUE TITLE
No coherence when using lmdb and hdf5 together

### ISSUE THREAD

**Issue by febert** [BVLC/caffe#2878]
Hi,
I have a problem using labeled image data (converted to lmbd) together with numeric labels (6dim vector per image).
Although I disabled the shuffling flag in the bashscript which triggers  convert_imageset.cpp the images still become shuffled.

The image-lmdb layer and hdf5 labels are defined in the prototxt as follows:

name: "CaffeNet"
layer {
  name: "train_label"
  type: "HDF5Data"
  top: "train_label"
  hdf5_data_param {
    source: "/home/ubuntu/grasping/2015-DL-MrPink/caffe/Image_Net_full_grasping/data/train_label.txt" # num_sample x 6 array
    batch_size: 256
  }
    include {
    phase: TRAIN
  }
}
layer {
  name: "test_label"
  type: "HDF5Data"
  top: "test_label"
  hdf5_data_param {
    source: "/home/ubuntu/grasping/2015-DL-MrPink/caffe/Image_Net_full_grasping/data/test_label.txt"  # num_sample x 60 array
    batch_size: 256
  }
    include {
    phase: TEST
  }
}
##### 

layer {
  name: "data"
  type: "Data"
  top: "data"
  #top: "label"
  include {
    phase: TRAIN
  }
  transform_param {
    mirror: false
    crop_size: 224
    mean_file: "/home/ubuntu/grasping_data/grasp_mean.binaryproto"
  }
  data_param {
    source: "/home/ubuntu/grasping_data/db/grasp_train_lmdb"
    batch_size: 256
    backend: LMDB
  }
}
layer {
  name: "data"
  type: "Data"
  top: "data"
  #top: "label"
  include {
    phase: TEST
  }
  transform_param {
    mirror: false
    crop_size: 224
    mean_file: "/home/ubuntu/grasping_data/grasp_mean.binaryproto"
  }
  data_param {
    source: "/home/ubuntu/grasping_data/db/grasp_train_lmdb"
    batch_size: 50
    backend: LMDB
  }
}

**Comment by shelhamer** [comment]
Closing as better handled by a Python data layer. Coordinating separate data layers is a bit perilous, so I instead advise making a single Python data layer with several tops.
