### ISSUE TITLE
Issue building with DEBUG:= 1 with cuda linking error

### ISSUE THREAD

**Issue by StevenHickson** [BVLC/caffe#2879]
I can build and run fine normally, but if I set DEBUG := 1 in Makefile.config in order to debug an issue I have, I get the linking error:
.build_debug/lib/libcaffe.so: undefined reference to `__cudaInitModule'

Any ideas what could be causing this. I have the following setup:
/proc/driver/nvidia/version
NVRM version: NVIDIA UNIX x86_64 Kernel Module  340.29  Thu Jul 31 20:23:19 PDT 2014
GCC version:  gcc version 4.8.2 (Ubuntu 4.8.2-19ubuntu1)

It could be something easy I'm missing but I've searched around and haven't found what's happening.

**Comment by shelhamer** [comment]
Sorry, I've never encountered this.
