### ISSUE TITLE
why there are no function like Blob.m, Layer.m in the matlab/caffe floder ?

### ISSUE THREAD

**Issue by zlinker** [BVLC/caffe#2881]
I can't run the official tutorial of matcaffe now cause the update version of caffe, I think it's not convenient to extract model param in matlab, anybody can help with this, thanks! :(

**Comment by ronghanghu** [comment]
You are using an out-dated version. Pull the lastest caffe from GitHub.

**Please do not post usage, installation, or modeling questions, or other requests for help to Issues.**
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
