### ISSUE TITLE
InternalThreadEntry() function call

### ISSUE THREAD

**Issue by zli79** [BVLC/caffe#2896]
Hi all,
I have trouble to find the point where this InternalThreadEntry() function is called, this function is defined in several files, such as window_data_layer.cpp and image_data_layer.cpp, could anyone give some clue where this function is called related information about this function, structure or logic flow? That would be great. 

Best
zhe

**Comment by longjon** [comment]
Closing as this looks like a usage issue/request for help. (But try searching the GitHub?)

This tracker is reserved for specific Caffe development issues and bugs; please ask usage questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) list.

For more information, see our [contributing guide](https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md).

Thanks!
