### ISSUE TITLE
Caffe Truck Factor

### ISSUE THREAD

**Issue by gavelino** [BVLC/caffe#2898]
As part of my PhD research on code authorship, we calculated the Truck Factor (TF) of some popular GitHub repositories.

As you probably know, the [Truck (or Bus) Factor](https://en.wikipedia.org/wiki/Bus_factor) designates the minimal number of developers that have to be hit by a truck (or quit) before a project is incapacitated. In our work, we consider that a system is in trouble if more than 50% of its files become orphan (i.e., without a main author).

More details on our work in this preprint: https://peerj.com/preprints/1233

We calculated the TF for **Caffe** and obtained a value of **4**.

The developers responsible for this TF are:

Jeff Donahue - author of 35% of the files
Yangqing Jia - author of 28% of the files
Evan Shelhamer - author of 24% of the files
Sergio Guadarrama - author of 10% of the files

To validate our results, we would like to ask **Caffe** developers the following three brief questions:

(a) Do you agree that the listed developers are the main developers of **Caffe**?

(b) Do you agree that **Caffe** will be in trouble if the listed developers leave the project (e.g., if they win in the lottery, to be less morbid)?

(c) Does **Caffe** have some characteristics that would attenuate the loss of the listed developers (e.g., detailed documentation)?

Thanks in advance for your collaboration,

Guilherme Avelino
PhD Student
Applied Software Engineering Group (ASERG)
UFMG, Brazil
http://aserg.labsoft.dcc.ufmg.br/

**Comment by shelhamer** [comment]
Thanks for doing research on open source development! However, this is off-topic for our project issue tracker. Please follow-up with [caffe-dev](caffe-dev@googlegroups.comcaffe-dev@googlegroups.com), our dev mailing list, instead.

**Comment by bhack** [comment]
@shelhamer What is the difference  between the public and open discussion on PRs and this reserved and closed dev mailing list? Are there classified info?
