### ISSUE TITLE
weight decay in convolution layer, is it necessary ?

### ISSUE THREAD

**Issue by hkcqr** [BVLC/caffe#2900]
I'm wondering if weight decay is necessary in convolution layer, I saw some examples, some have weight decay in convolution layer,  some haven't. For example, in caffe cifar10 example, there's not weight decay in conv1 conv2 conv3. So is this necessary ?

**Comment by seanbell** [comment]
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
