### ISSUE TITLE
Makefile Errors

### ISSUE THREAD

**Issue by sburck11** [BVLC/caffe#2906]
Trying to install on OSX 10.10.3 using the newest Makefile, and I'm getting the following errors in terminal:

resnet149-148:caffe Sam$ make
Makefile.config:8: Makefile.config: Too many open files
make: Makefile.config:28: pipe: Too many open files
make: Makefile.config:40: pipe: Too many open files
make: Makefile.config:42: pipe: Too many open files
make: Makefile.config:45: pipe: Too many open files
make: Makefile.config:47: pipe: Too many open files
make: Makefile.config:50: pipe: Too many open files
make: Makefile.config:52: pipe: Too many open files
make: Makefile.config:64: pipe: Too many open files
make: Makefile.config:202: pipe: Too many open files
make: Makefile.config:219: pipe: Too many open files
Makefile.config:276: *** Cannot static link with the c++ compiler.  Stop.

**Comment by longjon** [comment]
Closing as this does not look like a Caffe issue; you're welcome to open a new issue with instructions to reproduce on the latest master if this is still relevant.
