### ISSUE TITLE
How to process data images by pairs instead of just one image

### ISSUE THREAD

**Issue by AlamiMejjati** [BVLC/caffe#2908]
Hi guys, i'm new in caffe and i made a tour of the different demos and tutorials. The Mnist one worked perfectly for me, same as Cifar 10, and imagenet.
 Now that i'm a bit used of the different data and layer structures, i found a problem when i wanted to process my own data. The thing is that my data is a bit different, thus i'm not trying to recognize objects in one image but i want to give the network a set of pair images wich are true labeled if there is per exemple the same car in the image and false if it is not.
I have a dataset containing a lot of images but i have to feed the network a combination of two images. The goal of the network is to return 1 if there is the same object in the two images and 0 on the other side. 
I looked at all the forums, and the caffe documentation but i still doesn't have a clue of how to process that problem. 
Thanks in advance :)

**Comment by seanbell** [comment]
From [CONTRIBUTING.md](https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md):
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
