### ISSUE TITLE
Old caffe seems unable to load models of the newest caffe?

### ISSUE THREAD

**Issue by GGGary** [BVLC/caffe#2912]
Hi,
I have a problem when using caffemodels. It seems that caffe of old version is unable to load models generated by the newest version. I used old caffe and initialized a network to load a model of the newest caffe, but the loaded weights are all 0. The layer names of my network are all the same as the model.
Does anyone have solutions? Thanks a lot!

**Comment by seanbell** [comment]
You could write your own function to "downgrade" back to the old format (from within the new codebase), and then load it from the old codebase.

**Comment by GGGary** [comment]
Thanks a lot! @seanbell 
I have found the upgrade functions.

**Comment by longjon** [comment]
While we generally do try to keep Caffe able to load models from older versions, we do not guarantee the opposite.
