### ISSUE TITLE
Missing Image Data When Creating lmdb

### ISSUE THREAD

**Issue by Dragon-J** [BVLC/caffe#2914]
Hi, I'm new and started to learn Caffe recently and have a very basic question. 
I have collected millions of images in jpg format to support my work. I work is to build a network to class those images into 8 classes. So I make a txt file to write down all the [imagename label] pairs. My label number is from 0 to 7 and I have sorted them in order. 
However, when I have made some neccessary change to creat_imagenet.sh and run it on my own data, I found that only the images which are labelled 0 and 1 are converted. The rest of the data(those that are labelled 2 to 7) seems missing. 
Is there anyone no what's wrong with my data? How to solve this? 
Thanks!

**Comment by elanger4** [comment]
Just to clarify, I believe convert_imageset.sh in /caffe_root/build/tools/ is the script you run to create your lmdb. Assuming by creat_imagenet.sh was a typo, what changes did you make to that file?

**Comment by Dragon-J** [comment]
@elanger4 I just change some file paths and file names. One more change to mention is that I have added a '-grey' after '-shuffle', because all my images is binary. This is all I have done to creat_imagenet.sh

**Comment by seanbell** [comment]
From [CONTRIBUTING.md](https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md):
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
