### ISSUE TITLE
PythonLayer and Multi-GPU random segfaults

### ISSUE THREAD

**Issue by philipp-fischer** [BVLC/caffe#2923]
Hi, unfortunately I cannot give a very clear bug description, because I get different errors every time.
However:

Using the simplest imaginable PythonLayer and multi-gpu with GPUs 0,1 selected, segfaults in boost Python library pop up. Sometimes I get errors from the garbage collector `Fatal Python error: GC object already tracked`

This seems to be because of parallelizing the Python code in multiple threads.
When I set `share_in_parallel: true` to serialize Python execution, everything works fine.

The Python layer I use:

    import caffe
    import numpy as np

    class PythonLayer(caffe.Layer):

        def setup(self, bottom, top):
            if len(bottom) != 1:
                raise Exception("Need one input.")

        def reshape(self, bottom, top):
            top[0].reshape(bottom[0].num, bottom[0].channels, bottom[0].height, bottom[0].width)

        def forward(self, bottom, top):
            top[0].data[...] = bottom[0].data

        def backward(self, top, propagate_down, bottom):
            if propagate_down[0]:
                bottom[0].diff[...] = top[0].diff

**Comment by ronghanghu** [comment]
seems to be similar to http://stackoverflow.com/questions/8888124/embedded-python-segfaults

**Comment by ronghanghu** [comment]
@philipp-fischer Note
>When I set share_in_parallel: true to serialize Python execution, everything works fine.

This is not true in general. Currently `share_in_parallel: true` (introduced in #2903) only applies to forward, not backward, as I hope one only do so when PythonLayer is used as a data layer and does no backward. However, I didn't expect this bug in #2903. It was my fault.

**Comment by ronghanghu** [comment]
Close as is partially resolved by #3032 as a short-term workaround before we have better solutions. Further discussions on this issue should follow in #2936.
