### ISSUE TITLE
ipython cannot show any ipynb file

### ISSUE THREAD

**Issue by b2220333** [BVLC/caffe#2933]
I run :ipython notebook on examples directory.
It run successful:
![1](https://cloud.githubusercontent.com/assets/4596078/9289637/3476704c-43aa-11e5-9ea2-a6a5e1df4939.png)

After I click 00-classification or any ipynb files, it shows nothing.
![1](https://cloud.githubusercontent.com/assets/4596078/9289647/655c91e6-43aa-11e5-9e48-79f3972540f5.png)

How to fix it?
Thank you very much~

**Comment by longjon** [comment]
Closing as this looks like a usage issue (which also does not appear to have anything to do with Caffe).

This tracker is reserved for specific Caffe development issues and bugs; please ask usage questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) list.

For more information, see our [contributing guide](https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md).

Thanks!
