### ISSUE TITLE
Reconcile PythonLayer with Multi-GPU

### ISSUE THREAD

**Issue by ronghanghu** [BVLC/caffe#2936]
Right now PythonLayer cannot be parallelized in MultiGPU, which is a bug. Python Global Interpreter Lock (GIL) only allows one thread at a time to run in the python interpreter. This issue is reported in #2923.

We should find a solution to to this bug, or only allow shared PythonLayer and serializing PythonLayer forward (currently via `share_in_parallel: true`) it in MultiGPU (then we need a backward lock, too? but it is more complicated than that https://github.com/BVLC/caffe/issues/2923#issuecomment-131504078) Perhaps we may use [multiprocessing](https://docs.python.org/2/library/multiprocessing.html) module to fix this bug? But on second thought it doesn't seem like a good idea either.

**Comment by thatguymike** [comment]
This is not going to work that cleanly. Multi-process means multiple gpu
contexts and a different multi-gpu design leading to some perf loss.
Moreover, data exchange in general becomes much more complex.

Still amazes me that python doesn't support threading in a reasonable way.

**Comment by ronghanghu** [comment]
>This is not going to work that cleanly. Multi-process means multiple gpu
contexts and a different multi-gpu design leading to some perf loss.
Moreover, data exchange in general becomes much more complex.

Yes, I totally agree with you.

**Comment by jmschrei** [comment]
Joblib allows you to use a threading backend when used in conjunction with Cython and releasing the GIL. Maybe that work be appropriate here?

**Comment by bhack** [comment]
A manual little example to workaround GIL http://pieceofpy.com/2010/02/26/boost-python-threads-and-releasing-the-gil/

**Comment by ronghanghu** [comment]
The straightforward (and perhaps naive) workaround seems to be to serialize all calls to Python any code, i.e. only allow having one PythonLayer execution at a time behave like before. This can be done via a global python lock, perhaps as a static member variable in PythonLayer class.

From my perspective, I think serializing python execution is reasonable for CPU Bound PythonLayer since Python interpretation is always serialized in GIL and never actually run in parallel. One may argue for the case of IO Bound PythonLayer (such as using PythonLayer as a data layer), but then I would not even expect to run into this case since people should `set share_in_parallel: true` to share it among workers to load data sequentially (avoiding loading all the same data for each solver). After all, even for IO Bound PythonLayer, serialized execution is still better than a crash.

Any comment?

**Comment by seanbell** [comment]
In the short term until this gets sorted out, perhaps setting `share_in_parallel` to `false` on the `PythonLayer` should print a fatal message explaining that the unshared case is not implemented yet.

**Comment by ronghanghu** [comment]
But even for the shared case, backward is not working correctly https://github.com/BVLC/caffe/issues/2923#issuecomment-131504078, as in #2903 I only expected a PythonLayer to be shared when used as DataLayer and performs no backward.

**Comment by seanbell** [comment]
You could also give a fatal message for that case too.

I agree that this is tricky and don't have a solution, but failing cleanly is a reasonable placeholder.

**Comment by BlGene** [comment]
This is probably a stupid idea, but would it be possible to start several python process, each with their own GIL?

**Comment by bhack** [comment]
@BIGene see @thatguymike and  @ronghanghu comments on python multiprocess

**Comment by ronghanghu** [comment]
I'm leaving this issue open for further discussion. #2939 provides a workaround for the crash but it is indeed a not very satisfactory, and I don't like #2939 either. On the other hand, multi-process is a hacky way to go. Everyone are welcome to share if they have good ideas/solutions to this issue.

**Comment by alessandroferrari** [comment]
What about to implement a method pyforward and pybackward in Net class C++ definition, such that it just releases GIL by means of a ScopedGILRelease and immediately after calls the forward (or backward) methods. Then, simply expose pyforward and pybackward functions to boost interface.

Otherwise, a PyNet C++ class that inherit from Net, and override forward and backward doing simply GIL realease and call super.forward() (or super.backward()).

At least for the most used time consuming/commonly used methods is important to release GIL, otherwise making caffe not suited to production multi-threaded python applications.

**Comment by naibaf7** [comment]
@ronghanghu 
I do release the GIL for the forward/backward passes in the OpenCL branch and it seems to work fine so far, also with using multiple GPUs on multiple threads (although for data parallel computation and not multi-GPU training).
For the python layer, the GIL gets re-acquired and it passes the python runtests like that.

**Comment by alessandroferrari** [comment]
I have done a pull request for fix it #4360

**Comment by cypof** [comment]
Each net can run in it's own fork now, there is an example in /python/train.py. #4563

**Comment by DenerKup** [comment]
I can't understand why this was closed? #4563 doesn't release GIL. It only implements multiple GPU training. I wan't to have multiple workers with shared memory and single GPU thread to stream forward passes only, but everything gets blocked during forward pass. What's wrong with #4360, except code style?

**Comment by soulslicer** [comment]
Sorry, so is there any way to create a custom data layer with multiple GPU?
