### ISSUE TITLE
Compilation errors (No such file "common.h" in protobuf, Could NOT find GFlags, Glog, etc.)

### ISSUE THREAD

**Issue by simkezr** [BVLC/caffe#2938]
Hi. I am having an issue compiling Caffe, and have not been able to find a working solution. I followed the steps on the Caffe installation page, but can't get past compilation (http://caffe.berkeleyvision.org/installation.html#compilation). When I run make all, I get the following error:

CXX .build_release/src/caffe/proto/caffe.pb.cc
In file included from .build_release/src/caffe/proto/caffe.pb.cc:4:0:
.build_release/src/caffe/proto/caffe.pb.h:9:42: fatal error: google/protobuf/stubs/common.h: No such file or directory
compilation terminated.
make: *** [.build_release/src/caffe/proto/caffe.pb.o] Error 1

I already have all the dependencies listed on the Caffe installation page, but they are already installed in a root directory, and I did not get them by sudo apt-get which I imagine would do the linking for me. I have tried protobuf 2.6.1, 2.4.1, 2.5.0, all with the same error on make. Since make doesn't seem to work, I have tried all of these versions on cmake as well, which still give me errors like

...
-- Could NOT find GFlags (missing: GFLAGS_INCLUDE_DIR GFLAGS_LIBRARY)
-- Could NOT find Glog (missing: GLOG_INCLUDE_DIR GLOG_LIBRARY)
-- Could NOT find PROTOBUF (missing: PROTOBUF_LIBRARY PROTOBUF_INCLUDE_DIR)
...

I have no clue how to set Caffe to use the right directories. So what I did was manually set these variables to contain all the folders I could find (e.g. setenv PROTOBUF_INCLUDE_DIR /path/to/protobuf/src), and I ran cmake again. This works only for some of the variables, and I cannot get all of them to work, so it still isn't compiling. This solution seems way too cumbersome and error-prone... I don't even know what the LIBRARY directories should be for Glog and GFlags.

Does anybody have any insight on how to get this to work? Please let me know if you need more information. I run Linux.

Thanks.

**Comment by odellus** [comment]
I've had some problems with `gcc` and `protobuf`. The issues you are having are imminently solvable if you go through and `apt-get install` or build from source the dependencies one by one.

If you wouldn't mind, let's continue this discussion on caffe-users@googlegroups.com. The owners of caffe like to keep help with installation and usage issues separate from bug reporting with good reason.

**Comment by simkezr** [comment]
Thanks for the response. I should have mentioned though, I do not have root permissions, unfortunately. So I can't do yum install on my machine :/ . Is there a convenient way around this?

Thanks.

Sent the same info to caffe-users@googlegroups.com also.

**Comment by longjon** [comment]
Closing as this looks like an installation issue/request for help.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
