### ISSUE TITLE
Error during compilation (make all command)

### ISSUE THREAD

**Issue by cynodelic** [BVLC/caffe#2948]
I got this problem while compiling Caffe with the `make all` command:

```
CXX/LD -o .build_release/tools/upgrade_net_proto_text.bin
.build_release/lib/libcaffe.so: undefined reference to `google::protobuf::io::CodedInputStream::~CodedInputStream()'
.build_release/lib/libcaffe.so: undefined reference to `google::protobuf::io::CodedInputStream::default_recursion_limit_'
.build_release/lib/libcaffe.so: undefined reference to `google::protobuf::io::CodedInputStream::BytesUntilLimit() const'
.build_release/lib/libcaffe.so: undefined reference to `google::protobuf::GoogleOnceInitImpl(int*, google::protobuf::Closure*)'
collect2: ld devolvió el estado de salida 1
make: *** [.build_release/tools/upgrade_net_proto_text.bin] Error 1
```

In previous Caffe compilations, I didn't have this problem.

**How can I fix it?**

EDIT: I have all the dependencies installed, but this error still appears.

**Comment by CDLuminate** [comment]
* what is your compiler version?
* what OS are you running?

**Comment by shelhamer** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
