### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by cswhjiang** [BVLC/caffe#2960]
The memory used increases with iterations.

The command I run is 
````
./build/tools/caffe train --solver=models/bvlc_reference_caffenet/solver.prototxt --snapshot=models/bvlc_reference_caffenet/caffenet_train_iter_65000.solverstate
````

**Comment by longjon** [comment]
Closing as there's not enough information here to suggest that there is a memory leak; it may be that LMDB is using memory in an unexpected way.
