### ISSUE TITLE
Change cpp_classify.cpp to handle multiple images

### ISSUE THREAD

**Issue by mczmy** [BVLC/caffe#2962]
http://caffe.berkeleyvision.org/gathered/examples/cpp_classification.html provides codes for classifying single image. I want to know how to change Classifier::WrapInputLayer and Classifier::Preprocess to store multiple images instead of one image. Thanks very much!

**Comment by forresti** [comment]
That seems like a useful thing to do.

FYI, `tools/extract_features.cpp` can do classification for multiple images, if you specify the softmax layer as the output "features." Then, it's just a matter of pulling out the max activation for each image in the batch, and there's your batch of classification results.

**Comment by mczmy** [comment]
thanks:) I solved the problem.

**Comment by flx42** [comment]
What @forresti mentioned should work, but if you don't have the luxury of creating a LMDB file in your application; it's quite easy to modify the code in cpp_classify in order to handle multiple images. I have the code somewhere, if you're interested.

**Comment by sambookhon** [comment]
Hi @flx42, could you share your code. I am interested in how to change cpp_classify to support multiple image at a time and use batching for a single forward calculation.
Thanks

**Comment by flx42** [comment]
Hey @sambookhon, look at this commit:
https://github.com/flx42/caffe/commit/be0bff1a84c9e16fb8e8514dc559f2de5ab1a416

It's pretty brutal, just adding a bunch of vectors everywhere to handle multiple images in a batch. Example usage:
```
./build/examples/cpp_classification/classification.bin models/bvlc_reference_caffenet/deploy.prototxt \
models/bvlc_reference_caffenet/bvlc_reference_caffenet.caffemodel \
data/ilsvrc12/imagenet_mean.binaryproto \
data/ilsvrc12/synset_words.txt \
images/1.jpg images/2.jpg images/3.jpg images/4.jpg images/5.jpg
```

**Comment by sambookhon** [comment]
@flx42 
Thanks for sharing your codes. It helps me a lot.

**Comment by JohnTian** [comment]
@flx42 
Thanks! Awesome work.
