### ISSUE TITLE
Input must have 4 axes, corresponding to, (num, channels, height, width)

### ISSUE THREAD

**Issue by RadicoLabs** [BVLC/caffe#2965]
Not sure if this is an issue or not - but i have been searching for days and cannot seem to figure it out!

Any image i try to classify individually using digits seems to run okay. However, when using the "classify many images" button, the network crashes because of the aforementioned title/bug/i dont even know what the hell it is.

Im entirely new to caffe and DIGITS, and as i said i've spent days googling this problem - and cant seem to figure it out. what is the 5th dimension on the image, and if i do actually have 5D images, how do i convert them to 4D?

Thanks!

**Comment by lukeyeager** [comment]
Please close this issue and ask it on the DIGITS user group:
https://groups.google.com/forum/#!forum/digits-users
