### ISSUE TITLE
training two types of data with one label or two label in one model

### ISSUE THREAD

**Issue by chen1474147** [BVLC/caffe#2967]
Hi, all

now I have two types of data, data one has one label, data two has two labels.

I want to use caffe to train them together, so that when data one comes, the loss just calculate the error of label one, when data two comes, the loss will calculate the error of both label one and label two.

 Can I use caffe framework without change its code to accomplish it? Thanks.

**Comment by longjon** [comment]
Closing as a request for help.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
