### ISSUE TITLE
Preserving keys (image names) in extract_features.cpp?

### ISSUE THREAD

**Issue by forresti** [BVLC/caffe#2971]
I sometimes use `tools/extract_features.cpp` to compute activations from image LMDBs in batch mode.

When I use `tools/convert_imageset.cpp` to create LMDBs of images, the keys are nicely formatted, preserving the original filenames of the images. For example, "car.jpg" would become `0000001_car.jpg`. 

However, `extract_features.cpp` ignores the original LMDB keys and creates new keys like `000000001`. Usually, I want to "remember" what the name of each image, so that I can visualize the results and see what was/wasn't classified correctly. To do this, I have a very hacky script, which opens up multiple LMDBs to correlate `000000001` to `0000001_car.jpg`. 

---

A more sane solution would probably be for `extract_features.cpp` to preserve the original LMDB keys. This is somewhat harder than it looks, since the code for reading the input LMDBs is buried in the `data_layer`.

To make this happen, I'm now trying to convince the `data_layer` to "know" what keys were traversed in the DataReader. 
Has anyone already done this?

**Comment by shelhamer** [comment]
Closing in favor of pycaffe + matcaffe as interfaces for feature extraction, though thanks for the reasonable suggestion for the feature extraction tool.
