### ISSUE TITLE
Error during configure using cmake

### ISSUE THREAD

**Issue by mvvardhan** [BVLC/caffe#2973]
Hi,

I get the following error when I try to configure Caffe using CMake 3.3.0. I have compiled ProtoBuf from source and installed it.
 CMake Error at cmake/ProtoBuf.cmake:19 (string): string sub-command REGEX, mode MATCH needs at least 5 arguments total to command. Call Stack (most recent call first): cmake/Dependencies.cmake:24 (include) CMakeLists.txt:28 (include)

The Os X version that I am using is:
Darwin EN-VishnuM 14.5.0 Darwin Kernel Version 14.5.0: Wed Jul 29 02:26:53 PDT 2015; root:xnu-2782.40.9~1/RELEASE_X86_64 x86_64

Regards,
Vishnu

**Comment by shelhamer** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
