### ISSUE TITLE
cudnn lib link issue

### ISSUE THREAD

**Issue by apollos** [BVLC/caffe#2974]
My OS is ubuntu 14.04.3. I have installed cudnn and I can successfully compile the cudnn example provided by Nvidia. While I compile caffe by make all, there is no any error and all target files are generated. 

But while I double check whether the cudnn lib linked correctly or not by "ldd build/tools/caffe | grep cudnn", it prompt that "libcudnn.so.7.0 =>not found".

I try to add /usr/local/cuda/lib64 into the LIBRARY_DIRS of Makefile.configure and then it seems work.
While I run "sudo ldconfig -v | grep cudnn", it seems that the libcudnn can be found
/sbin/ldconfig.real: Path `/lib/x86_64-linux-gnu' given more than once
/sbin/ldconfig.real: Path `/usr/lib/x86_64-linux-gnu' given more than once
/sbin/ldconfig.real: /lib/x86_64-linux-gnu/ld-2.19.so is the dynamic linker, ignoring

	libcudnn.so.7.0 -> libcudnn.so.7.0.58

So my question is why I have to change the "LIBRARY_DIRS" to enable the cudnn but not just set "USE_CUDNN := 1"? And is my workaround correct or is there any other formal method?

**Comment by odellus** [comment]
@apollos This is an example of how I was able to get cudnn to work.
```
cmake  -DCUDNN_INCLUDE=/usr/include -DCUDNN_LIBRARY=/usr/lib/libcudnn.so ../caffe
```

**Comment by longjon** [comment]
Closing as this looks like a cuDNN installation issue.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
