### ISSUE TITLE
how to use the NEW triplet_loss_layer without using lmdb 3d's generated data

### ISSUE THREAD

**Issue by obrianjunior** [BVLC/caffe#2982]
Hello Guys,

I just saw the the triplet loss layer has been modified , and now takes only 2 bottoms , while the previous took 4 bottoms data.
Now my question is how can i use this new layer without using convert_3d_triplet_data.cpp to generate triplets but rather use the imageData Layer to input 3 distinct   images ?

My first guess is this could be achieve   perhaps by merging the 3 features before sending them to the tripletLossLayer.  But this method required to know exactly how to pack the 3 blobs in the right order so it matches how they are internally used by the layer.

Please could   someone  help me figure out how to do that ? 

Thanks in advance.

**Comment by Wangyida** [comment]
Hi, as the new triplet loss layer released, there is no dependency on leveldb/lmdb. The input data is not arranged in different channel using slice layer, you can use image data with the help of a name list in data layer. So the sequence of images is very important, every set of combination is composed of a reference sample, a most similar sample and a few negative samples, you should put the reference sample in the 1st place and the most similar sample in the 2nd place, and the remaining negative samples afterwards.
For example, if you want to use 3 triplet(and also a pair wise part added by default in the code), you should arrange data like this: reference[0], most similar[0], negative1[0], negative2[0], negative3[0], reference[1], most similar[1], negative1[1], negative2[1], negative3[1],..., reference[n], most similar[n], negative1[n], negative2[n], negative3[n].
The negative samples will be freely selected on your purpose, I think this is clear the the parameters of the triplet loss, you can define the number of negative samples in 1 set. The type of triplet loss is also free to be selected as the 'losstype' parameter. @obrianjunior  @bhack

**Comment by obrianjunior** [comment]
Thanks for your quick replies @bhack  @Wangyida .

So if i've understood well : if using an imageData Layer ,  my input file should be some thing like this:

root_path_folder/reference_img_0.jpg   sim
root_path_folder/similar_img_0.jpg   sim
root_path_folder/negative_img_0_1.jpg  sim
root_path_folder/negative_img_0_2.jpg   sim
root_path_folder/negative_img_0_3.jpg   sim

root_path_folder/reference_img_1.jpg   sim
root_path_folder/similar_img_1.jpg   sim
root_path_folder/negative_img_1_1.jpg   sim
root_path_folder/negative_img_1_2.jpg   sim
root_path_folder/negative_img_1_3.jpg   sim


root_path_folder/reference_img_2.jpg   sim
root_path_folder/similar_img_2.jpg   sim
root_path_folder/negative_img_2_1.jpg   sim
root_path_folder/negative_img_2_2.jpg   sim
root_path_folder/negative_img_2_3.jpg   sim
...

root_path_folder/reference_img_n.jpg   sim
root_path_folder/similar_img_n.jpg   sim
root_path_folder/negative_img_n_1.jpg   sim
root_path_folder/negative_img_n_2.jpg   sim
root_path_folder/negative_img_n_3.jpg   sim

And so, i guess  batch_size should be  such that batch_size%( 2 + 3 ) =  0  , isn't it ?
( with 2 for the reference and similar sample  and 3 for the 3 negatives in this case  )

thanks !

**Comment by Wangyida** [comment]
Yes, that's right, you should care for the batch size in this manner.

**Comment by obrianjunior** [comment]
fine !   thanks  @Wangyida  ! caffe is really nice  :+1:

**Comment by bhack** [comment]
@obrianjunior Please close this. If you want more docs please request it directly commenting at https://github.com/BVLC/caffe/pull/2603

**Comment by bjutdy** [comment]
how I write the .txt file? how to write the head of the file?

**Comment by bjutdy** [comment]
@obrianjunior 
thanks for your answer!!  the error is "A total of 0 images" when i use the file what you recommend
