### ISSUE TITLE
Does anyone knows how I can extract and use the kernels of the first layer and use them separately?

### ISSUE THREAD

**Issue by isalirezag** [BVLC/caffe#2983]
Hi guys.

So I use caffe and I wonder if I just can use one of the filters separately.
So basically I just need the kernel of that filter.
I could not find the formula of the kernels in the paper.
So I really appreciate it if someone can help me out please

Thanks

**Comment by mbakthav** [comment]
Such questions should be on the Caffe users mailing list. Please read https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md

**Comment by bhack** [comment]
@isalirezag See https://github.com/BVLC/caffe/pull/2943

**Comment by longjon** [comment]
Thanks @mbakthav, that's right.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
