### ISSUE TITLE
Matlab crashes upon calling "caffe.reset_all()"

### ISSUE THREAD

**Issue by ehsanj** [BVLC/caffe#2985]
Hello,

My Matlab crashes after calling "caffe.reset_all()". Here is a snapshot of the crash:

![screenshot from 2015-08-27 05 24 09](https://cloud.githubusercontent.com/assets/2586855/9517271/c7cbe446-4c7c-11e5-9293-daf33a3c5df6.png)

I use Ubuntu 15.04 and my version of Matlab is R2014b. This issue happens every time I call "caffe.reset_all()" after I load and use the net but does not happen by calling "caffe.reset_all()" before loading and using the net. I did not have this problem in an older version of caffe from a few months ago calling caffe('reset'). Please help!

Thanks,
Ehsan

**Comment by ehsanj** [comment]
Here is the crash dump file from Matlab:
------------------------------------------------------------------------
              abort() detected at Thu Aug 27 06:03:46 2015
------------------------------------------------------------------------

Configuration:
  Crash Decoding     : Disabled
  Current Visual     : None
  Default Encoding   : UTF-8
  GNU C Library      : 2.21 stable
  MATLAB Architecture: glnxa64
  MATLAB Root        : /usr/local/MATLAB/R2014b
  MATLAB Version     : 8.4.0.150421 (R2014b)
  Operating System   : Linux 3.19.0-26-generic #28-Ubuntu SMP Tue Aug 11 14:16:32 UTC 2015 x86_64
  Processor ID       : x86 Family 6 Model 60 Stepping 3, GenuineIntel
  Software OpenGL    : 0
  Virtual Machine    : Java 1.7.0_11-b21 with Oracle Corporation Java HotSpot(TM) 64-Bit Server VM mixed mode
  Window System      : No active display

Fault Count: 1


Abnormal termination:
abort()

Register State (from fault):
  RAX = 0000000000000000  RBX = 00007f679596c6c0
  RCX = ffffffffffffffff  RDX = 0000000000000006
  RSP = 00007f68c5f181d8  RBP = 00007f68c5f18310
  RSI = 0000000000002697  RDI = 0000000000002671

   R8 = 000000000000ff08   R9 = 00007f67a4014fa0
  R10 = 0000000000000008  R11 = 0000000000000206
  R12 = 0000000000000003  R13 = 0000000000000000
  R14 = 00007f67761ca800  R15 = 00007f67761ca598

  RIP = 00007f68da467267  EFL = 0000000000000206

   CS = 0033   FS = 0000   GS = 0000

Stack Trace (from fault):
[  0] 0x00007f68da467267                    /lib/x86_64-linux-gnu/libc.so.6+00217703 gsignal+00000055
[  1] 0x00007f68da468eca                    /lib/x86_64-linux-gnu/libc.so.6+00224970 abort+00000362
[  2] 0x00007f6795745e7b             /usr/lib/x86_64-linux-gnu/libglog.so.0+00069243 _ZN6google22InstallFailureFunctionEPFvvE+00000000
[  3] 0x00007f6795745ea4             /usr/lib/x86_64-linux-gnu/libglog.so.0+00069284 _ZN6google10LogMessage10SendToSinkEv+00000000
[  4] 0x00007f6795745deb             /usr/lib/x86_64-linux-gnu/libglog.so.0+00069099 _ZN6google10LogMessage9SendToLogEv+00001247
[  5] 0x00007f67957457bf             /usr/lib/x86_64-linux-gnu/libglog.so.0+00067519 _ZN6google10LogMessage5FlushEv+00000429
[  6] 0x00007f6795748a35             /usr/lib/x86_64-linux-gnu/libglog.so.0+00080437 _ZN6google15LogMessageFatalD1Ev+00000025
[  7] 0x00007f6795bf3bfd  /home/ehsan/Documents/caffe/build/lib/libcaffe.so+02489341 _ZN5caffe12SyncedMemoryD1Ev+00000445
[  8] 0x00007f6795ab49e2  /home/ehsan/Documents/caffe/build/lib/libcaffe.so+01182178 _ZN5boost6detail17sp_counted_impl_pIN5caffe12SyncedMemoryEE7disposeEv+00000018
[  9] 0x00007f6795b67712  /home/ehsan/Documents/caffe/build/lib/libcaffe.so+01914642 _ZN5caffe21CuDNNConvolutionLayerIfED1Ev+00001298
[ 10] 0x00007f6795b679d9  /home/ehsan/Documents/caffe/build/lib/libcaffe.so+01915353 _ZN5caffe21CuDNNConvolutionLayerIfED0Ev+00000009
[ 11] 0x00007f6795ba8441  /home/ehsan/Documents/caffe/build/lib/libcaffe.so+02180161 _ZN5caffe3NetIfED1Ev+00001009
[ 12] 0x00007f6795ba8619  /home/ehsan/Documents/caffe/build/lib/libcaffe.so+02180633 _ZN5caffe3NetIfED0Ev+00000009
[ 13] 0x00007f6796036ddd /home/ehsan/Documents/caffe/matlab/+caffe/private/caffe_.mexa64+00028125
[ 14] 0x00007f679603483a /home/ehsan/Documents/caffe/matlab/+caffe/private/caffe_.mexa64+00018490
[ 15] 0x00007f67960353f9 /home/ehsan/Documents/caffe/matlab/+caffe/private/caffe_.mexa64+00021497 mexFunction+00000178
[ 16] 0x00007f68d0ffdc0a     /usr/local/MATLAB/R2014b/bin/glnxa64/libmex.so+00150538 mexRunMexFile+00000090
[ 17] 0x00007f68d0ffa5c4     /usr/local/MATLAB/R2014b/bin/glnxa64/libmex.so+00136644
[ 18] 0x00007f68d0ffb414     /usr/local/MATLAB/R2014b/bin/glnxa64/libmex.so+00140308
[ 19] 0x00007f68d0332329 /usr/local/MATLAB/R2014b/bin/glnxa64/libmwm_dispatcher.so+00791337 _ZN8Mfh_file11dispatch_fhEiPP11mxArray_tagiS2_+00000697
[ 20] 0x00007f68cf3e6ef4 /usr/local/MATLAB/R2014b/bin/glnxa64/libmwm_interpreter.so+05996276
[ 21] 0x00007f68cf3e8809 /usr/local/MATLAB/R2014b/bin/glnxa64/libmwm_interpreter.so+06002697
[ 22] 0x00007f68cf3e903c /usr/local/MATLAB/R2014b/bin/glnxa64/libmwm_interpreter.so+06004796
[ 23] 0x00007f68cf25d1a3 /usr/local/MATLAB/R2014b/bin/glnxa64/libmwm_interpreter.so+04383139
[ 24] 0x00007f68cf26a86e /usr/local/MATLAB/R2014b/bin/glnxa64/libmwm_interpreter.so+04438126
[ 25] 0x00007f68cf26a953 /usr/local/MATLAB/R2014b/bin/glnxa64/libmwm_interpreter.so+04438355
[ 26] 0x00007f68cf3a2284 /usr/local/MATLAB/R2014b/bin/glnxa64/libmwm_interpreter.so+05714564
[ 27] 0x00007f68cf1c126a /usr/local/MATLAB/R2014b/bin/glnxa64/libmwm_interpreter.so+03744362
[ 28] 0x00007f68cf23652e /usr/local/MATLAB/R2014b/bin/glnxa64/libmwm_interpreter.so+04224302
[ 29] 0x00007f68d0332329 /usr/local/MATLAB/R2014b/bin/glnxa64/libmwm_dispatcher.so+00791337 _ZN8Mfh_file11dispatch_fhEiPP11mxArray_tagiS2_+00000697
[ 30] 0x00007f68cfeeaca8  /usr/local/MATLAB/R2014b/bin/glnxa64/libmwmcos.so+02448552
[ 31] 0x00007f68cfe827e2  /usr/local/MATLAB/R2014b/bin/glnxa64/libmwmcos.so+02021346
[ 32] 0x00007f68cfe841ce  /usr/local/MATLAB/R2014b/bin/glnxa64/libmwmcos.so+02027982
[ 33] 0x00007f68cfe89b70  /usr/local/MATLAB/R2014b/bin/glnxa64/libmwmcos.so+02050928
[ 34] 0x00007f68cfe8558d  /usr/local/MATLAB/R2014b/bin/glnxa64/libmwmcos.so+02033037
[ 35] 0x00007f68cfeece06  /usr/local/MATLAB/R2014b/bin/glnxa64/libmwmcos.so+02457094
[ 36] 0x00007f68cff6c2ab  /usr/local/MATLAB/R2014b/bin/glnxa64/libmwmcos.so+02978475
[ 37] 0x00007f68d02dde34 /usr/local/MATLAB/R2014b/bin/glnxa64/libmwm_dispatcher.so+00446004 _ZN13Mfh_MATLAB_fn11dispatch_fhEiPP11mxArray_tagiS2_+00000244
[ 38] 0x00007f68cff6bdd1  /usr/local/MATLAB/R2014b/bin/glnxa64/libmwmcos.so+02977233
[ 39] 0x00007f68cf20cb70 /usr/local/MATLAB/R2014b/bin/glnxa64/libmwm_interpreter.so+04053872
[ 40] 0x00007f68cf1bce02 /usr/local/MATLAB/R2014b/bin/glnxa64/libmwm_interpreter.so+03726850
[ 41] 0x00007f68cf1bf022 /usr/local/MATLAB/R2014b/bin/glnxa64/libmwm_interpreter.so+03735586
[ 42] 0x00007f68cf1c4f87 /usr/local/MATLAB/R2014b/bin/glnxa64/libmwm_interpreter.so+03760007
[ 43] 0x00007f68cf1c06ff /usr/local/MATLAB/R2014b/bin/glnxa64/libmwm_interpreter.so+03741439
[ 44] 0x00007f68cf1c1334 /usr/local/MATLAB/R2014b/bin/glnxa64/libmwm_interpreter.so+03744564
[ 45] 0x00007f68cf23652e /usr/local/MATLAB/R2014b/bin/glnxa64/libmwm_interpreter.so+04224302
[ 46] 0x00007f68d03324af /usr/local/MATLAB/R2014b/bin/glnxa64/libmwm_dispatcher.so+00791727 _ZN8Mfh_file11dispatch_fhEiPP11mxArray_tagiS2_+00001087
[ 47] 0x00007f68cf1f4ff5 /usr/local/MATLAB/R2014b/bin/glnxa64/libmwm_interpreter.so+03956725
[ 48] 0x00007f68cf1b6699 /usr/local/MATLAB/R2014b/bin/glnxa64/libmwm_interpreter.so+03700377
[ 49] 0x00007f68cf1b2a87 /usr/local/MATLAB/R2014b/bin/glnxa64/libmwm_interpreter.so+03684999
[ 50] 0x00007f68cf1b3143 /usr/local/MATLAB/R2014b/bin/glnxa64/libmwm_interpreter.so+03686723
[ 51] 0x00007f68d123e9dc /usr/local/MATLAB/R2014b/bin/glnxa64/libmwbridge.so+00223708
[ 52] 0x00007f68d123f649 /usr/local/MATLAB/R2014b/bin/glnxa64/libmwbridge.so+00226889 _Z8mnParserv+00000729
[ 53] 0x00007f68db64ab7f   /usr/local/MATLAB/R2014b/bin/glnxa64/libmwmcr.so+00772991 _ZN11mcrInstance30mnParser_on_interpreter_threadEv+00000031
[ 54] 0x00007f68db62b083   /usr/local/MATLAB/R2014b/bin/glnxa64/libmwmcr.so+00643203
[ 55] 0x00007f68db62cd69   /usr/local/MATLAB/R2014b/bin/glnxa64/libmwmcr.so+00650601 _ZN5boost6detail11task_objectIvNS_3_bi6bind_tIvPFvRKNS_8functionIFvvEEEENS2_5list1INS2_5valueIS6_EEEEEEE6do_runEv+00000025
[ 56] 0x00007f68db62d737   /usr/local/MATLAB/R2014b/bin/glnxa64/libmwmcr.so+00653111 _ZN5boost6detail9task_baseIvE3runEv+00000071
[ 57] 0x00007f68db62d797   /usr/local/MATLAB/R2014b/bin/glnxa64/libmwmcr.so+00653207
[ 58] 0x00007f68db628bca   /usr/local/MATLAB/R2014b/bin/glnxa64/libmwmcr.so+00633802
[ 59] 0x00007f68ce56da46   /usr/local/MATLAB/R2014b/bin/glnxa64/libmwuix.so+00330310
[ 60] 0x00007f68ce555ad2   /usr/local/MATLAB/R2014b/bin/glnxa64/libmwuix.so+00232146
[ 61] 0x00007f68dbdeb00f /usr/local/MATLAB/R2014b/bin/glnxa64/libmwservices.so+02523151
[ 62] 0x00007f68dbdeb17c /usr/local/MATLAB/R2014b/bin/glnxa64/libmwservices.so+02523516
[ 63] 0x00007f68dbde707f /usr/local/MATLAB/R2014b/bin/glnxa64/libmwservices.so+02506879
[ 64] 0x00007f68dbdec4b5 /usr/local/MATLAB/R2014b/bin/glnxa64/libmwservices.so+02528437
[ 65] 0x00007f68dbdec8e7 /usr/local/MATLAB/R2014b/bin/glnxa64/libmwservices.so+02529511
[ 66] 0x00007f68dbdecfc0 /usr/local/MATLAB/R2014b/bin/glnxa64/libmwservices.so+02531264 _Z25svWS_ProcessPendingEventsiib+00000080
[ 67] 0x00007f68db629248   /usr/local/MATLAB/R2014b/bin/glnxa64/libmwmcr.so+00635464
[ 68] 0x00007f68db629564   /usr/local/MATLAB/R2014b/bin/glnxa64/libmwmcr.so+00636260
[ 69] 0x00007f68db615cdd   /usr/local/MATLAB/R2014b/bin/glnxa64/libmwmcr.so+00556253
[ 70] 0x00007f68da8036aa              /lib/x86_64-linux-gnu/libpthread.so.0+00030378
[ 71] 0x00007f68da538eed                    /lib/x86_64-linux-gnu/libc.so.6+01076973 clone+00000109


This error was detected while a MEX-file was running. If the MEX-file
is not an official MathWorks function, please examine its source code
for errors. Please consult the External Interfaces Guide for information
on debugging MEX-files.

If this problem is reproducible, please submit a Service Request via:
    http://www.mathworks.com/support/contact_us/

A technical support engineer might contact you with further information.

Thank you for your help.

**Comment by ehsanj** [comment]
You might find this useful:

http://www.mathworks.com/matlabcentral/answers/212716-how-do-i-troubleshoot-a-matlab-crash-associated-with-a-custom-mex-function

**Comment by ronghanghu** [comment]
To get more detailed output, run Matlab from a terminal, and see the terminal output for detailed error message. 

This issue is usually caused by one of the CHECK marcos failure in Caffe's internal.
