### ISSUE TITLE
Caffe train on fly

### ISSUE THREAD

**Issue by ahsaniqbal** [BVLC/caffe#2986]
Hi,

I am new to caffe, I am trying to train a convolutional neural network. However due to huge training data I cannot create leveldb/lmdb/hdf5 for all the training data at once. So I was thinking two alternatives 

1. Create leveldb/lmdb/hdf5 for some subset of the data train the network, then finetune for next subset. I think it is possible, but it will be slow? 
2. Or is it possible to rather making caffe load data from leveldb/lmdb/hdf5, Can I feed network example by example from ram?
  
Any help/pointers will be appreciated.\

Regards
Ahsan

**Comment by bhack** [comment]
See https://github.com/BVLC/caffe/pull/2943

**Comment by ahsaniqbal** [comment]
@bhack can you please give some usage example of generators with MemoryDataLayer?

**Comment by seanbell** [comment]
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

To answer your question, Fast R-CNN is a project that uses a PythonLayer to generate data on the fly: https://github.com/rbgirshick/fast-rcnn/blob/master/lib/roi_data_layer/layer.py
