### ISSUE TITLE
proto target cpp and python generation always out of date

### ISSUE THREAD

**Issue by willyd** [BVLC/caffe#2987]
Hi all,

During the process of building Caffe on Windows with the changes from PR #2816 I noticed that the proto target is always out of date. For instance, if i configure via CMake and then build the proto target the .pb.cc .pb.h and _pb2.py file get generated and compiled. But if I build again it regenerates the files and rebuilds the library again. Since just about every file depends on .pb.h header, every time I make a change to a file in the caffe target, VS rebuilds the whole thing because this header was regenerated. It seems that this is happening because the files are not generated in the CMAKE_CURRENT_BINARY_DIR. I wonder if this is a general CMake bug or just a Windows issue?

Anyone experiencing a similar behavior on Linux or Mac OS X with the CMake build?

**Comment by longjon** [comment]
Closing as this appears to be specific to an open PR; discuss there as needed.
