### ISSUE TITLE
How to training LeNet on MNIST with Caffe with multiple GPU

### ISSUE THREAD

**Issue by apollos** [BVLC/caffe#2988]
I am learning the parallel method of Caffe. I have 2 K40 GPUs, how can I parallel the training process while I run ./examples/mnist/train_lenet.sh

**Comment by 3upperm2n** [comment]
I remember there is an option -gpu all when you run caffe.

**Comment by longjon** [comment]
Closing as this looks like a request for help.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
