### ISSUE TITLE
Retrieving Network Outputs in Matlab

### ISSUE THREAD

**Issue by eddy-ilg** [BVLC/caffe#299]
Hi, 

I use ImageNet and would like to get the outputs of the individual layers in matlab. Is this possible? It seems caffe('get_weights'); only gets the filter masks. 

Best, 

Eddy

**Comment by anurikadisha** [comment]
Hi @sharathchandra92 
I want to see the features output after the first fully connected layer after the training is complete using all the layers for training. However if I remove the layers after that in the prototxt file, wont the output change since there will not be back-propogation from the layers after this?

**Comment by sharathchandra92** [comment]
Hi @anurikadisha

Feature extraction is essentially after the model has been trained. So it does not matter which layer you are extracting the features from, as the model that is being used is already trained. You are just doing a feed-forward to get the activations at the layer you are interested in.

________________________________

**Comment by anurikadisha** [comment]
Hi!
So does this mean that imagenet_deploy.prototxt is not used for training and will give the output after training is completed? Also, I cannot find this file in the examples/imagenet_deploy.prototxt. I am sorry but will this file come after doing make matcaffe. I wasnt currently using MATLAB interface.

**Comment by jrterven** [comment]
Once the network is loaded, e.g.

    net = caffe.Net(model.deployFile, model.caffemodel, 'test');

You can access to the output of any layer with blob_vec(id).get_data() as follows:


    function feature_maps = getLayerOutput(images, net, layerName)
      input_data = {images};
      net.forward(input_data);    % forward pass
 
      % get the index of the desired layer
      blob_id_C = strfind(net.blob_names, layerName);
      blob_id = find(not(cellfun('isempty', blob_id_C)));
    
      % get the layer output
      feature_maps = net.blob_vec(blob_id).get_data();
