### ISSUE TITLE
Caffe cannot find HDF5 on Mac OS 10.10.4

### ISSUE THREAD

**Issue by GiuliaP** [BVLC/caffe#2993]
Hi, 

I'm trying to compile Caffe in Mac OS 10.10.4 (via CMake) but it seems that it is not able to find the HDF5_DIR.
I have installed anaconda in the default directory (the home directory), which should provide also HDF5.
I have tried to set the HDF5_ROOT=/Users/giulia/anaconda, as suggested in the FindHDF5.cmake provided by CMake, and I have also tried to install HDF5 via Homebrew and the set the HDF5_DIR to the installation location (/usr/local/Cellar/hdf5/version_number).

I think I need HDF5 in order to perform regression experiments. Any suggestion is appreciated.

Best,
Giulia

**Comment by shelhamer** [comment]
Sorry, I've only been able to compile on OS X with the make build and not cmake.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
