### ISSUE TITLE
Cannot compile matcaffe on Mac OS 10.10.4 (with Matlab R2015a)

### ISSUE THREAD

**Issue by GiuliaP** [BVLC/caffe#2994]
Hi,

I'm not able to compile matcaffe on Mac OS 10.10.4. I have Matlab R2015a.
At first, I have tried to use CMake and I have added the related version to the caffe/cmake/Modules/FindMatlabMex.cmake (that was including only versions until R2014b). In this case I got this error:

In file included from /Users/giulia/LIBRARIES/caffe/matlab/+caffe/private/caffe_.cpp:18:
In file included from /Users/giulia/LIBRARIES/caffe/include/caffe/caffe.hpp:7:
In file included from /Users/giulia/LIBRARIES/caffe/include/caffe/blob.hpp:10:
In file included from /Users/giulia/LIBRARIES/caffe/include/caffe/syncedmem.hpp:7:
In file included from /Users/giulia/LIBRARIES/caffe/include/caffe/util/math_functions.hpp:11:
In file included from /Users/giulia/LIBRARIES/caffe/include/caffe/util/mkl_alternate.hpp:11:
/System/Library/Frameworks/Accelerate.framework/Versions/Current/Frameworks/vecLib.framework/Versions/Current/Headers/cblas.h:760:26: error: expected function body after function declarator
        const int __ldc) __OSX_AVAILABLE_STARTING(__MAC_10_10,__IPHONE_8_0);
                         ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/usr/include/Availability.h:159:50: note: expanded from macro '__OSX_AVAILABLE_STARTING'
    #define __OSX_AVAILABLE_STARTING(_osx, _ios) __AVAILABILITY_INTERNAL##_osx
                                                 ^
<scratch space>:6:1: note: expanded from here
__AVAILABILITY_INTERNAL__MAC_10_10
^
In file included from /Users/giulia/LIBRARIES/caffe/matlab/+caffe/private/caffe_.cpp:18:
In file included from /Users/giulia/LIBRARIES/caffe/include/caffe/caffe.hpp:7:
In file included from /Users/giulia/LIBRARIES/caffe/include/caffe/blob.hpp:10:
In file included from /Users/giulia/LIBRARIES/caffe/include/caffe/syncedmem.hpp:7:
In file included from /Users/giulia/LIBRARIES/caffe/include/caffe/util/math_functions.hpp:11:
In file included from /Users/giulia/LIBRARIES/caffe/include/caffe/util/mkl_alternate.hpp:11:
/System/Library/Frameworks/Accelerate.framework/Versions/Current/Frameworks/vecLib.framework/Versions/Current/Headers/cblas.h:767:26: error: expected function body after function declarator
        const int __ldc) __OSX_AVAILABLE_STARTING(__MAC_10_10,__IPHONE_8_0);
                         ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/usr/include/Availability.h:159:50: note: expanded from macro '__OSX_AVAILABLE_STARTING'
    #define __OSX_AVAILABLE_STARTING(_osx, _ios) __AVAILABILITY_INTERNAL##_osx
                                                 ^
<scratch space>:6:1: note: expanded from here
__AVAILABILITY_INTERNAL__MAC_10_10
^
2 errors generated.

make[2]: *** [../matlab/+caffe/private/caffe_.mexmaci64] Error 255
make[1]: *** [matlab/CMakeFiles/matlab.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
Linking CXX shared library ../lib/_caffe.dylib
Creating symlink /Users/giulia/LIBRARIES/caffe/python/caffe/_caffe.so -> /Users/giulia/LIBRARIES/caffe/build/lib/_caffe.so
[100%] Built target pycaffe
make: *** [all] Error 2

Then, I have tried to change the MATLAB_DIR in the Makefile.config and using make, but still I got the same error.

**Comment by ronghanghu** [comment]
See https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/caffe-users/1sVAqSDLvpk/r9LMUXp7EgAJ
