### ISSUE TITLE
Extract features from multiple layers

### ISSUE THREAD

**Issue by gongenhao** [BVLC/caffe#2997]
Hi I am using `./build/tools/extract_features.bin` which works great for feature extraction. 

I want to ask whether I can extract features from multiple layers, say the last fc layers, together without calling extract_features.bin twice and computing every forward projection twice?

**Comment by seanbell** [comment]
Yes, you can use the Python interface to extract features from any blob in the network.

Also, from https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
