### ISSUE TITLE
on AWS g2.2xlarge error "Check failed: error == cudaSuccess (2 vs. 0)  out of memory"

### ISSUE THREAD

**Issue by kotamat** [BVLC/caffe#2999]
I'm using this script https://github.com/graphific/DeepDreamVideo
and I ran this code
``
python 2_dreaming_time.py -i frames -o processed_frames/ --gpu 0 -it png
``
but this error occurred

> I0830 04:37:39.380446  4368 net.cpp:298] Memory required for data: 545512320
> I0830 04:37:39.834239  4368 upgrade_proto.cpp:618] Attempting to upgrade input file specified using deprecated V1LayerParameter: ../caffe/models/bvlc_googlenet/bvlc_googlenet.caffemodel
> I0830 04:37:39.904917  4368 upgrade_proto.cpp:626] Successfully upgraded file specified using deprecated V1LayerParameter
> Processing frame #1
> /usr/local/lib/python2.7/site-packages/scipy-0.16.0-py2.7-linux-x86_64.egg/scipy/ndimage/interpolation.py:549: UserWarning: From scipy 0.13.0, the output shape of zoom() is calculated with round() instead of int() - for these inputs the size of the returned array has changed.
>   "the returned array has changed.", UserWarning)
> F0830 04:37:44.953891  4368 syncedmem.cpp:58] Check failed: error == cudaSuccess (2 vs. 0)  out of memory
> *** Check failure stack trace: ***

but the detail of nvidia-smi is

```
$ nvidia-smi -q
...
    FB Memory Usage
        Total                       : 4095 MiB
        Used                        : 65 MiB
        Free                        : 4030 MiB
    BAR1 Memory Usage
        Total                       : 128 MiB
        Used                        : 2 MiB
        Free                        : 126 MiB
...
```

and i set both of batch_size in caffe/models/bvlc_googlenet/train_val.prototxt to 1.

I think there no problem, Could you tell me ? thx!

**Comment by seanbell** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

**Comment by kotamat** [comment]
Thank you for replying. Ill follow this.
