### ISSUE TITLE
ReadProtoFromBinaryFile called from windows

### ISSUE THREAD

**Issue by itamab** [BVLC/caffe#3000]
Opening the weights file (io.cpp, ReadProtoFromBinaryFile line 56) with out the O_BINARY flag causes the weights to be read incorrectly and the training to diverge. This probably happens only on windows. I recommend returning it since it should not interrupt Linux training.

Thanks

**Comment by LitingLin** [comment]
call _set_fmode(_O_BINARY); first

**Comment by longjon** [comment]
Closing, see #2233 and other Windows issues.
