### ISSUE TITLE
Unroll Recurrent Network in pycaffe NetSpec

### ISSUE THREAD

**Issue by ronghanghu** [BVLC/caffe#3001]
In #2033, RNN/LSTM layers are unrolled to fill a net in `RecurrentLayer::FillUnrolledNet`, so that one doesn't have to write the entire unrolled network into their network prototxt. This greatly simplifies writing recurrent network with RNN/LSTM.

However, in #2033, the unroll behavior is pre-defined for each RNNLayer or LSTMLayer, which is not general enough. Also, a problem of #2033 is that forward is done per LSTM layer, rather per time, so that if there are two stacked LSTMs (lstm1 and lstm2), lstm1 at `t` will run before lstm2 at `t-1`.

To illustrate my point, consider the following case: Suppose one uses a recurrent network with e.g. 4 layer LSTM network (stacking LSTMs on top of each other), and
- At time step `t`, the fist (bottom-most) LSTM takes in `(x_t, l_{t-1})` where `x_t` is supplied by bottom input to recurrent net, and the last LSTM is followed by an output layer to produce `l_t`. So the bottom input to recurrent network at `t` depends on the top output of `t-1`.
- At `t==0`, one may want to assign a initial memory state to each of the 4 LSTM layers supplied/computed by some layers outside of recurrent part of the whole network (e.g. from a data layer).

These are typical use cases for general recurrent network that requires all computation at time step `t-1` finished before running time step `t`. Typical applications involve attention models in computer vision and control in robotics, as well as lots of reinforcement learning scenarios.

As far as I know, such behavior cannot be implemented by per LSTM unroll in #2033. So instead of unrolling with in a `RecurrentLayer` module, I would prefer to unroll the whole net in NetSpec and then run everything as a feed-forward network.

Currently in my mind, the advantages of unrolling within NetSpec are:
- Allows more general recurrent network with feed back.
- NetSpec is quite flexible compared to C++ LayerSetUp, so that e.g. `LSTM1_{t}` can take `LSTM_{t-1}` output as its input blob.
- Only needs to have a few layers e.g. LSTMUnit, RNNUnit to implement a type of recurrent network.

And the disadvantages are:
- Generated unrolled recurrent network prototxt can be lengthy and unreadable.
- Cannot change unroll time steps dynamically.

So, this issue is opened for how to unroll recurrent network. Should we add unroll to be a functionality in NetSpec? Discussions are welcome!

**Comment by jeffdonahue** [comment]
Thanks for the comments @ronghanghu.  I agree that `NetSpec`ing recurrent architectures is preferable to implementing `FillUnrolledNet` in C++ for new architectures -- I probably would have tried to go that route if `NetSpec` had existed when I started.

The only ability you lose with `NetSpec` that #2033 gives you is the ability to copy state (e.g., memory) from timestep `T` of the previous batch to timestep `0` of the new batch, allowing for exact inference along arbitrary time horizons, even if only unrolling for a single timestep (`T==1`).   I think if we wanted to introduce this functionality, logic would have to be added to `Net` itself -- it can't be encapsulated inside a `Layer`.

I'm not sure about explicitly introducing the notion of unrolling into `NetSpec` itself -- personally I think it's simple enough to do the unrolling yourself in a loop.

**Comment by siddharthachandra** [comment]
Pardon me for my ignorance, but does the current implementation allow "unrolling time steps dynamically"? As far as I understand the `FillUnrolledNet` routine is called inside the `LayerSetup` routine (as opposed to the `Reshape` routine). I know we can set the `cont` blob wisely to achieve this, but implementation of spatial LSTMs (as opposed to temporal), such as pixel-rnn or graph-lstms, would be much cleaner if the unrolling were being done in the `Reshape` routine. Thanks in adance, and kudos for the great work.

**Comment by shelhamer** [comment]
Closing as out-of-scope: this extension makes sense but is too involved to be done in the current design of Caffe. As explained by Jeff, unrolling can be done through net spec through loops even though these explicitly unrolled nets cannot infinitely propagate state. That's enough of a compromise for now.
