### ISSUE TITLE
Test segfault with multiple GPUs?

### ISSUE THREAD

**Issue by zeakey** [BVLC/caffe#3002]
[ RUN      ] SGDSolverTest/2.TestLeastSquaresUpdateWithMomentumMultiIter
**\* Aborted at 1441030058 (unix time) try "date -d @1441030058" if you are using GNU date ***
PC: @     0x2b1b3e919a81 (unknown)
**\* SIGSEGV (@0x6d48000) received by PID 4793 (TID 0x2b1b384e6e00) from PID 114589696; stack trace: ***
    @     0x2b1b3e7fed40 (unknown)
    @     0x2b1b3e919a81 (unknown)
    @     0x2b1b3db0529c std::vector<>::erase()
    @     0x2b1b3db04091 caffe::DevicePair::compute()
    @     0x2b1b3db08fac caffe::P2PSync<>::run()
    @           0x6757b5 caffe::GradientBasedSolverTest<>::RunLeastSquaresSolver()
    @           0x685a7b caffe::GradientBasedSolverTest<>::TestLeastSquaresUpdate()
    @           0x6862eb caffe::SGDSolverTest_TestLeastSquaresUpdateWithMomentumMultiIter_Test<>::TestBody()
    @           0x7b3933 testing::internal::HandleExceptionsInMethodIfSupported<>()
    @           0x7aa617 testing::Test::Run()
    @           0x7aa6be testing::TestInfo::Run()
    @           0x7aa7c5 testing::TestCase::Run()
    @           0x7adb08 testing::internal::UnitTestImpl::RunAllTests()
    @           0x7add97 testing::UnitTest::Run()
    @           0x44fcca main
    @     0x2b1b3e7e9ec5 (unknown)
    @           0x4560e9 (unknown)
    @                0x0 (unknown)
make: **\* [runtest] Segmentation fault (core dumped)

I clone the latest caffe from the official repo , installation is all fellow the official guidence on ubuntu 14.04. And all of the dependencies are installed by 'apt-get' ,except 'OpenBLAS',because it has no proper apt-get installation method.

cuda7 was installed following the nVidia guidence :
  1 download  **_.deb ,
  2 dpkg -i *_.deb
  3 apt-get update
  4 apt-get install cuda

My machine has one Tesla K40c and  a C2050 and another quadro k600 was connected to a monitor. 

cuda deviceQuery can well detect the 3 devices.

make and run the demo is all passed.

But when I try to run make runtest , the error occurs.
I have tried to reinstall caffe and even re-install my ubuntu ,but all of these doesn't work...

I think this is a strongly reproducable bug and it will occur somewhere out of 'make runtest'.

any reply will be highly apperciated!

**Comment by ronghanghu** [comment]
Perhaps this is something related to #2926.

**Comment by cypof** [comment]
The stack shows P2PSync, which is now gone, so probably not relevant anymore.
