### ISSUE TITLE
Question about MemoryData Layer and Solver inteface.

### ISSUE THREAD

**Issue by ahsaniqbal** [BVLC/caffe#3013]
Hi,

I am trying to train a network but rather using lmdb or leveldb, I am feeding data to my network on the fly. So I am following procedure as outlined below

1. My data is loaded in Memory Data Layer.
2. I create a mini badge using python script.
3. Set data and label as solver.net.set_input_arrays(batch,labels)
4. After that I call solver.step(1)

here solver is of type SGDSolver
Now my question is what is difference between solver.solve and solver.step. 2ndly 
this approach doesn't let me have a memory data layer for test network. Is there any workarround for that?

My solver.prototxt looks like 

net: "/path/to/train_val.prototxt"
#test_iter: 1000
#test_interval: 1000
base_lr: 0.01
lr_policy: "step"
gamma: 0.1
stepsize: 100000
display: 20
max_iter: 450000
momentum: 0.9
weight_decay: 0.0005
snapshot: 10000
snapshot_prefix: "/path/to/temporal_net_train"
solver_mode: GPU

With my approach every 20th iteration network displays some output loss etc. And somehow loss stays constant over some numbert of iterations, what could be the reason for that.

Thanks
Ahsan

**Comment by seanbell** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
