### ISSUE TITLE
Sigmoid Cross Enthropy Loss with Imagenet label 

### ISSUE THREAD

**Issue by Sarasra** [BVLC/caffe#3018]
I'm implementing a label converter layer to convert the Nx1x1x1 (integer) label of imagenet to NxCx1x1 (binary) label required for Sigmoid with Cross Enthropy Loss.
The prototxt would be:
layer{
      name: "converter"
      type: "LabelConverter"
      bottom: "label"
      top: "sigLabel"
       labelconverter_param{
                 channel: 1000
       }
}
Does this makes any sense? Is there any easier way to do this in Caffe?

Sara

**Comment by liuyipei** [comment]
AFAIK, you have to do it manually by either doing some data preprocessing or by implementing your own layer.

**Comment by longjon** [comment]
Closing as this looks like a request for help.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
