### ISSUE TITLE
Compilation of Caffe with OpenBLAS throwing error when putting BLAS := open. But same works when we put BLAS: Open. "Open" with Capital O

### ISSUE THREAD

**Issue by bgth** [BVLC/caffe#3028]
Hi Team,

I am getting below error when I try to compile with BLAS: open. Small o. But the same works when I put BLAS: Open. Capital O. Can you please update the MakeFile.config.example comment with the Capital O for OpenBLAS compile? The comment in MakeFile.config.example says to put "open" with Small o.

CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:138 (message):
Could NOT find Atlas (missing: Atlas_CBLAS_LIBRARY Atlas_BLAS_LIBRARY
Atlas_LAPACK_LIBRARY)

Regards,
Gurunath

**Comment by bgth** [comment]
I was wrong. small o open is correct

**Comment by xzzhang** [comment]
Using this flag seems to solve the problem of not finding atlas-related packages as well.

**Comment by rain16881** [comment]
in the dir caffe 
mkdir build 
cd build
cmake -DBLAS=open ..
...
-- Configuring incomplete

**Comment by bgth** [comment]
do you have openBlas installed? what is the error message

**Comment by rain16881** [comment]
yes i installed openblas and atlas....at /usr/local/OpenBLAS /usr/local/atlas

**Comment by rain16881** [comment]
ldconfig -p | grep atlas 
ldconfig -p | grep open
you can see it ....

**Comment by bgth** [comment]
Please mention the error message you recieved for configuration incomplete.

**Comment by FireAndIce** [comment]
I resolved the issue by:
`ldconfig -p | grep libopenblas`
     `libopenblas.so.0 (libc6,x86-64) => /lib64/libopenblas.so.0`

`sudo ln -s /lib64/libopenblas.so.0 /usr/lib64/libopenblas.so`
`sudo cmake -DBLAS=open ..`

**Comment by gerardsimons** [comment]
Can someone explain me how / why this works? What does the `open` statement do exactly?

**Comment by bgth** [comment]
Its to choose OpenBLAS as the BLAS library. More details on the caffe compilation page under section "CUDA and BLAS":

[Caffe Compilation](http://caffe.berkeleyvision.org/installation.html#compilation)

**Comment by rajhlinux** [comment]
Trust me, no one would want to compile "atlas math library"... that will take days to compile with CPU throttling on. Simply install/compile OpenBLAS and use the OpenBLAS flag for caffe build.
