### ISSUE TITLE
Solver Progress Plotting

### ISSUE THREAD

**Issue by aidangomez** [BVLC/caffe#3030]
I've used gunplot to plot the accuracy of a solver over its epochs and was wondering whether this would be functionality Caffe would like to have built-in? I suppose it would add another optional dependancy, but I've found having a .png plot of my training really assists in gaining a higher-level perspective of how my model is performing, and gives greater insight into how the change of hyper parameters effects the curve of training.

Let me know if it would be considered a useful tool or not.

**Comment by PatWie** [comment]
It is already there.
Have a look at
https://github.com/BVLC/caffe/blob/master/tools/extra/parse_log.py
and
https://github.com/BVLC/caffe/blob/master/tools/extra/plot_log.gnuplot.example

I think there is no need for adding another dependency. You can just use a bash-script: 

```
#!/bin/bash
ROOT=~/tools/caffe2/
# name of logfile
LOGNAME=examples/mnist/run.log

# extract information
~/tools/caffe2/tools/extra/parse_log.sh "${ROOT}${LOGNAME}"

# plot everything
gnuplot <<- EOF
  reset
  set key right bottom
  set style data lines
  set font 'Consolas,10'
  set term png enhanced font 'Consolas,10' size 800,400
  set title "Learning process ${LOGNAME}"
  set xlabel "Iterations"
  set ylabel "Loss"  tc rgb "#009e73"
  set y2label "Accuracy" tc rgb "#7570b3"
  set output "run.png"
  set border 11 back ls 80 lc -1
  set mxtics 2
  set grid mxtics
  set ytics autofreq tc rgb "#009e73"
  set y2tics autofreq tc rgb "#7570b3"
  set grid xtics
  set grid ytics

  plot "${ROOT}${LOGNAME}.train" using 1:3 title "training (loss)" lt 2 lc rgb "#aaaaaa" axes x1y1,  \
  "${ROOT}${LOGNAME}.test" using 1:4 title "test (loss)" lt 2 lc rgb "#009e73" lw 2 axes x1y1  ,\
  "${ROOT}${LOGNAME}.test" using 1:3 title "test (accuracy)" lt 2 lc rgb "#7570b3" lw 2 axes x1y2 
EOF

![preview](https://cloud.githubusercontent.com/assets/6756603/9715489/dbcdc044-5560-11e5-874a-5533cdb7b817.png)


```

**Comment by aidangomez** [comment]
@PatWie Thanks, that's perfect.
