### ISSUE TITLE
BN Inception

### ISSUE THREAD

**Issue by daerduoCarey** [BVLC/caffe#3035]
Is there any pre-trained BN_Inception model mentioned in paper http://arxiv.org/abs/1502.03167 available?

Thanks

**Comment by seanbell** [comment]
Yes, see https://github.com/BVLC/caffe/pull/1965#issuecomment-136129299

They have promised to release it (in the LSUN workshop, 12 weeks ago), but as far as I know have not actually released it.  You could try contacting @Yangqing and give a friendly nudge/reminder.

**Comment by longjon** [comment]
Closing as not a Caffe issue.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
