### ISSUE TITLE
errors in detection ipython notebook

### ISSUE THREAD

**Issue by howtobeahacker** [BVLC/caffe#3039]
I tried to execute the first cell of **detection.ipynb**. It has an error. It seems to be an simple error, but I do not know how to rectify it. Hope to see a patch soon.
```
Loading input...
selective_search_rcnn({'/home/tranlaman/BLVC-caffe/examples/images/fish-bike.jpg'}, '/tmp/tmpB_NrWR.mat')
Traceback (most recent call last):
  File "../python/detect.py", line 173, in <module>
    main(sys.argv)
  File "../python/detect.py", line 144, in main
    detections = detector.detect_selective_search(inputs)
  File "/home/tranlaman/BLVC-caffe/python/caffe/detector.py", line 123, in detect_selective_search
    return self.detect_windows(zip(image_fnames, windows_list))
  File "/home/tranlaman/BLVC-caffe/python/caffe/detector.py", line 86, in detect_windows
    predictions = out[self.outputs[0]].squeeze(axis=(2, 3))
ValueError: 'axis' entry 2 is out of bounds [-2, 2)
```

**Comment by seanbell** [comment]
See https://github.com/BVLC/caffe/pull/2984 -- that should fix your problem.  Blobs used to be all 4D, and now they are general ND.

**Comment by howtobeahacker** [comment]
@seanbell Thanks, I have the same answer after debugging. Wish to check the email earlier. I will close my report.

**Comment by TonyDandelion** [comment]
@antran89 excuse me, I am a new user of caffe, and  I had same problem like you when I run the detection.ipynb. Can you tell me How can I fix this problem? Thanks for your enthusiasm.

**Comment by TonyDandelion** [comment]
@antran89  and I pull the lastst code.
