### ISSUE TITLE
centos 7 can not compile caffe

### ISSUE THREAD

**Issue by qingzew** [BVLC/caffe#3041]
when I install atlas atlas-devel-3.10.1-7.el7.x86_64.rpm on centos 7 and compile caffe, it turns out:
```bash
AR -o .build_release/lib/libcaffe.a
LD -o .build_release/lib/libcaffe.so
/usr/bin/ld: cannot find -lcblas
/usr/bin/ld: cannot find -latlas
collect2: 错误：ld 返回 1
make: *** [.build_release/lib/libcaffe.so] 错误 1
```

why?

**Comment by seanbell** [comment]
Read the error message: you are missing ATLAS/BLAS.

Also, from https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

**Comment by qingzew** [comment]
sorry for that
