### ISSUE TITLE
undefined reference error on make all

### ISSUE THREAD

**Issue by kracwarlock** [BVLC/caffe#3045]
I get the following output

    CXX/LD -o .build_release/tools/caffe.bin
    .build_release/tools/caffe.o: In function `main':
    caffe.cpp:(.text.startup+0x3e): undefined reference to `google::SetUsageMessage(std::string const&)'
    caffe.cpp:(.text.startup+0x7b): undefined reference to `google::ShowUsageWithFlagsRestrict(char const*, char const*)'
    .build_release/tools/caffe.o: In function `_GLOBAL__sub_I_caffe.cpp':
    caffe.cpp:(.text.startup+0x2e3): undefined reference to `google::FlagRegisterer::FlagRegisterer(char const*, char const*, char const*, char const*, void*, void*)'
    caffe.cpp:(.text.startup+0x361): undefined reference to `google::FlagRegisterer::FlagRegisterer(char const*, char const*, char const*, char const*, void*, void*)'
    caffe.cpp:(.text.startup+0x3df): undefined reference to `google::FlagRegisterer::FlagRegisterer(char const*, char const*, char const*, char const*, void*, void*)'
    caffe.cpp:(.text.startup+0x45d): undefined reference to `google::FlagRegisterer::FlagRegisterer(char const*, char const*, char const*, char const*, void*, void*)'
    caffe.cpp:(.text.startup+0x4db): undefined reference to `google::FlagRegisterer::FlagRegisterer(char const*, char const*, char const*, char const*, void*, void*)'
    .build_release/tools/caffe.o:caffe.cpp:(.text.startup+0x526): more undefined references to `google::FlagRegisterer::FlagRegisterer(char const*, char const*, char const*, char const*, void*, void*)' follow
    .build_release/lib/libcaffe.so: undefined reference to `google::ParseCommandLineFlags(int*, char***, bool)'
    collect2: error: ld returned 1 exit status
    make: *** [.build_release/tools/caffe.bin] Error 1

I compiled the C3D variant of caffe at https://github.com/facebook/C3D and that compiles fine. I also use:
    export CPLUS_INCLUDE_PATH=$CPLUS_INCLUDE_PATH:/pkgs/gflags/include

**Comment by seanbell** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

Also, that looks like a linking error (so you also need to include the gflags libs on your path).

**Comment by kracwarlock** [comment]
Shifted to CMake and got this problem figured out on the caffe-users list. See link for solution:
https://groups.google.com/forum/#!topic/caffe-users/l7DpTvEud20

Thanks. I am closing this issue.

**Comment by uuudown** [comment]
You can download gflags (https://github.com/gflags/gflags), compile the code (using your current gcc which is the same you're going to use for caffe) and install. I guess this is due to the different gcc version on caffe and gflags.
