### ISSUE TITLE
Undefined reference to google protobuf

### ISSUE THREAD

**Issue by snavavf** [BVLC/caffe#3046]
I got these errors saying there are **undefined reference** to **google protobuf** when `make all` in caffe dir.
I wonder which file (like the Makefile?) I should modify, or where I should set up in my system.

I've already installed [protobuf](https://github.com/google/protobuf) as the command provided in the link, and installed libprotobuf-dev and protobuf-compiler on my Ubuntu 14.04.

```
CXX/LD -o .build_release/tools/convert_imageset.bin
.build_release/lib/libcaffe.so: undefined reference to `google::protobuf::io::CodedOutputStream::WriteVarint64ToArray(unsigned long long, unsigned char*)'
.build_release/lib/libcaffe.so: undefined reference to `google::protobuf::internal::WireFormatLite::WriteInt64(int, long long, google::protobuf::io::CodedOutputStream*)'
.build_release/lib/libcaffe.so: undefined reference to `google::protobuf::UnknownFieldSet::AddVarint(int, unsigned long long)'
.build_release/lib/libcaffe.so: undefined reference to `google::protobuf::io::CodedOutputStream::VarintSize64(unsigned long long)'
.build_release/lib/libcaffe.so: undefined reference to `google::protobuf::io::CodedOutputStream::WriteVarint64(unsigned long long)'
collect2: error: ld returned 1 exit status
make: *** [.build_release/tools/convert_imageset.bin] Error 1
```

**Comment by CDLuminate** [comment]
I encountered trouble alike, see buildlog as follow:
http://debomatic-amd64.debian.net/distribution#experimental/caffe/0.9999~rc2+git20150902+e8e660d3-1/buildlog
  
Where caffe with CPU_ONLY configuration passed the build, however one with CUDA just failed like that. In that build log caffe is built twice.
  
I tried to add `-Wl,--start-group` and `-Wl,--end-group` argument to enclose those `ld` arguments but it made no difference.

**Comment by shibuyanorailgun** [comment]
If you are using Ubuntu, maybe this will help:
```
sudo apt-get install libprotobuf-dev protobuf-compiler
```

**Comment by snavavf** [comment]
I have already installed **libprotobuf-dev** and **protobuf-compiler** on my Ubuntu 14.04 yet still get those error messages.

**Comment by shibuyanorailgun** [comment]
Perhaps add `-pthread -lprotobuf -lpthread` will do.
```
nr@linux ~ % pkg-config --libs protobuf
-pthread -lprotobuf -lpthread
```

**Comment by snavavf** [comment]
@shibuyanorailgun I don't quite understand...
I think **-lprotobuf** is already handled at line 172 and line 364 at [**Makefile**](https://github.com/BVLC/caffe/blob/master/Makefile), 
```
LIBRARIES += glog gflags protobuf leveldb snappy \
	lmdb boost_system hdf5_hl hdf5 m \
	opencv_core opencv_highgui opencv_imgproc
```
```
LDFLAGS += $(foreach librarydir,$(LIBRARY_DIRS),-L$(librarydir)) $(PKG_CONFIG) \
		$(foreach library,$(LIBRARIES),-l$(library))
```
and **-pthread** is handled at line 352.
```
CXXFLAGS += -pthread -fPIC $(COMMON_FLAGS) $(WARNINGS)
```

I tried to edit line 172 to
```
LIBRARIES += glog gflags protobuf leveldb snappy \
	lmdb boost_system hdf5_hl hdf5 m \
	opencv_core opencv_highgui opencv_imgproc pthread
```
but that doesn't help.


I don't know much about Makefile, so maybe I misunderstood. Could you explain more about how to compile it right?

**Comment by shibuyanorailgun** [comment]
= =, I'm sorry I can't figure out what happend.

**Comment by cwlseu** [comment]
I encountered trouble alike
´´´
PROTOC src/caffe/proto/caffe.proto
make: protoc: Command not found
make: *** [.build_release/src/caffe/proto/caffe.pb.h] Error 127
´´´
and thanks for your answer@shibuyanorailgun

**Comment by cwlseu** [comment]
I encountered trouble alike
I encountered trouble alike, see buildlog as follow:
<strong>PROTOC src/caffe/proto/caffe.proto
           make: protoc: Command not found
           make: *** [.build_release/src/caffe/proto/caffe.pb.h] Error 127
</strong>
thanks for your answer @shibuyanorailgun

**Comment by howtobeahacker** [comment]
Hi @snavavf, @cwlseu,
Please try to remove the os versions of protobuf in /usr/lib/x86_64-linux-gnu. (Something like libprotobuf.*, libprotobuf-lite.*, libprotoc.*). There are two versions of protobuf will cause conflicts when compiling.
Then try to install newest version of [protobuf](https://github.com/google/protobuf).

**Comment by snavavf** [comment]
Thanks @howtobeahacker !
That works.

**Comment by hevy-CC4477** [comment]
Can you explain me the solution? I am not sure to understand and I have a similar problem.

**Comment by antran89** [comment]
@hevy-CC4477 
There is an old default OS version of protobuf in ```/usr/lib/x86_64-linux-gnu```. Just delete `libprotobuf.*`, `libprotobuf-lite.*`, `libprotoc.*` and install again new version of protobuf.

**Comment by tinoue** [comment]
FYI: This seems to be a perfect solution.
http://stackoverflow.com/questions/10404027/cant-compile-example-from-google-protocol-buffers

**Comment by ferrouswheel** [comment]
Advising people to delete system libraries isn't an ideal solution.

I tried to remove protobuf-lite in ubuntu 15.10 with `sudo apt-get remove libprotobuf-lite9v5` (because I don't want to break my system) but it tries to remove 205 other packages (including my desktop).

Googling about this reminded me that I had previously tryed to make CUDA work by changing to gcc 4.9. Unfortunately the c++ ABI changed so compiling stuff with 4.9 and trying to link to system libraries built with gcc 5 won't work.

[On the mailing list](https://groups.google.com/d/msg/caffe-users/a6TDx89IByY/kALECEIzDAAJ) people are suggesting to remove the gcc 5 error from the CUDA header `/usr/local/cuda/include/host_config.h`.

**Comment by wadefelix** [comment]
remove the gcc 5 error from the CUDA header `host_config.h`
it works!

**Comment by jay-to-the-dee** [comment]
This appears to be a prevalent issue ob Ubuntu 15.10! Caffe used to work fine on 15.04! Also I'm using CUDA 7.5 so in theory I should be fine for the GCC version issue!

**Comment by netom** [comment]
Hi, Ubuntu 15.10 user here. Had the same issue, solved by patching CUDA (/usr/local/cuda/include/host_config.h).

Diff:

```113c113
< #if __GNUC__ > 4 || (__GNUC__ == 4 && __GNUC_MINOR__ > 9)
---
> //#if __GNUC__ > 4 || (__GNUC__ == 4 && __GNUC_MINOR__ > 9)
115c115
< #error -- unsupported GNU version! gcc versions later than 4.9 are not supported!
---
> //#error -- unsupported GNU version! gcc versions later than 4.9 are not supported!
117c117
< #endif /* __GNUC__ > 4 || (__GNUC__ == 4 && __GNUC_MINOR__ > 9) */
---
> //#endif /* __GNUC__ > 4 || (__GNUC__ == 4 && __GNUC_MINOR__ > 9) */
```

**Comment by michaeljs1990** [comment]
apparently someone called hottobeahacker solved this but i don't see that user or comment anymore. Could anyone enlighten me?

**Comment by antran89** [comment]
@michaeljs1990 It's me, I just changed my name. See my first comment in the thread, it might help you avoid the problem.

**Comment by michaeljs1990** [comment]
@antran89 thanks for the response. Unfortunately I have to use protoc 2.5 with my project so that is a no go for me. It seems that this library no longer works with the stock ubuntu 14.04 packages and the website contains incorrect information for building this package as well.

**Comment by muzhi93** [comment]
@antran89 Hi,following your guidance,I've successfully compiled Caffe,but there is another problem arising:when I reboot my machine,the leftside toolbar of my ubuntu 14.04 desktop is gone,then I typed ccsm in the command window,which reported an error,`ImportError: libprotobuf.so.8: cannot open shared object file: No such file or directory`.I wonder whether it is because I deleted the OS's protobuf file that lead to the breakdown of my desktop?

**Comment by Holdlen2DH** [comment]
I encounter this problem too, but don't how to fix it

**Comment by wenwei202** [comment]
This one works for me, in Ubuntu 16.04:
1) Configure `/usr/local/cuda/include/host_config.h` as suggested.
2) `sudo apt-get autoremove libprotobuf-dev protobuf-compiler`
3) then compile the protobuf-2.5.0 from src and install
Please config the gcc when you compile protobuf
`./configure --prefix=/usr/local/ CC=/usr/bin/gcc`

**Comment by adam-erickson** [comment]
Thanks @wenwei202 ! This worked for me on the latest Ubuntu 16.04 LTS with gcc-4.9.

I did not need to modify `/usr/local/cuda/include/host_config.h` for CUDA Toolkit 7.5 from apt-get, as the config header now supports gcc 5.x. Also, I did not set `--prefix` or `CC` in the `./configure` command, as that broke my install and prevented Caffe from linking.

**Comment by groakat** [comment]
for me this problem was caused because I had `protobuf` installed in anaconda. If you have `protobuf` installed in your anaconda environment, you have to remove all files by hand, as `conda uninstall protobuf` does not remove all the library files.

**Comment by hjc1028** [comment]
@antran89 删了`libprotobuf-lite.so` 之后进不了桌面，这个问题弄了三天

**Comment by hjc1028** [comment]
@wenwei202 It works

**Comment by bragilee** [comment]
@antran89  Hi, I am recently moved on the caffe. I encountered this problems on the ArchLinux. I am not quite familiar with caffe and protobuf so I do not quite understand how this problem happen. Could you instruct me how to solve it? Thank you so much.

**Comment by antran89** [comment]
@bragilee Sorry, I do not know how to fix safely. Some distributions of Linux have two version of Protobuf. You should figure out how to make Caffe only recognize one version of Protobuf. Sorry, my recommendations are not good. Please try out the methods of other people. Now it works fine for me all the time. I also do not know why they have this problem.

**Comment by bragilee** [comment]
@antran89  Thank you so much for your help. I will seek other methods. :)

**Comment by sherylwang** [comment]
It's caused by conflict versions of protobuf, I use 'apt-get remove libprotobuf-dev' that installed  by the  apt-get at ubuntu14.04 system

**Comment by IshwarKulkarni** [comment]
@antran89  's advice of deleting libprotobuf.so* is a bad idea. I should have scrolled further down before following it. 
This causes other packages depending on protobuf to fail. On my Ubunut 16.04, this caused Unity, the desktop manager started to fail and I could not get to a proper desktop until I rebuilt it it. 
If you did the same thing, download the src from here: http://packages.ubuntu.com/xenial/libprotobuf-dev 
and follow instruction to "make install" remember to ./configure --prefix=/usr beforehand.

**Comment by ma-al** [comment]
Hi. Just sharing. I successfully compiled within Miniconda by doing:

```bash
conda uninstall protobuf

conda install protobuf==2.6.1
# NOTE: Do not use 2.5.0 or 3.0.0
```

This was in an `Ubuntu 14.04.3 LTS` machine, where the native `protobuf` versions were `2.5.0-9`. Compiling against that results in:
```bash
CXX src/caffe/layers/infogain_loss_layer.cpp
In file included from ./include/caffe/util/cudnn.hpp:8:0,
                 from src/caffe/util/cudnn.cpp:2:
.build_release/src/caffe/proto/caffe.pb.h:17:2: error: This file was generated by an older version of protoc which is incompatible with your Protocol Buffer headers. Please regenerate this file with a newer version of protoc.
```

On the flip side, if you use the very latest, i.e., `conda install protobuf==3.0.0`, you'll get:
```bash
CXX/LD -o .build_release/examples/mnist/convert_mnist_data.bin
.build_release/lib/libcaffe.so: undefined reference to `google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(int, std::string const&, google::protobuf::io::CodedOutputStream*)'
```

Hopefully this helps the next guy that Google redirects here :bowtie:

**Comment by seindlut** [comment]
Thanks @groakat 
Deleting anaconda lib manually solved my problem.

**Comment by samarth-robo** [comment]
For anyone using Ubuntu 16.04 + Anaconda + Caffe, I was able to compile caffe without deleting Anaconda libs/files:

- Remove all references to Anaconda in system path variables
- run `ccmake ..` in `caffe/build`
- hit `t` to toggle into advanced cmake mode where more variables are displayed
- hit `c` couple of times to configure all library locations to system libraries
- manually point `PYTHON_EXECUTABLE` to `anaconda2/bin/python2.7`, `PYTHON_INCLUDE_DIR` to `anaconda2/include/python2.7` and `PYTHON_LIBRARY` to `anaconda2/lib/libpython2.7.so`
- hit `c` again and then `g` to generate cmake files
- `make all -j8`
- Remember to prepend `anaconda2/bin` to system variable `PATH` again so that you are using Anaconda executables for python

**Comment by NathanBittner** [comment]
@samarth-robo, Great idea. Successful compilation for me, but fails on make runtest. You didn't run into that error at all?

**Comment by ssulun16** [comment]
Regarding the first comment of Antran89

It's my stupidity for not noticing the thumbs down, but I follewed his advice and broke my system, now doing a reinstall, DO NOT REMOVE THE LIBRARY FILES.

**Comment by zchrissirhcz** [comment]
I encounter same problem.

System: ubuntu16.04
cuda:  8.0.44
gcc: 4.9

I have installed matlab2016b, which contains a `libprotobuf.so.8`, while I use `apt-get install libprotobuf-dev` gives `libprotobuf.so.9`, maybe this is the source of conflict. However, when I remove all the libprotobuf.so files under MATLAB  installation folder, I do `make clean; make -j8` still gives same problem.

Finally, I change gcc from 4.9 to 5, and this time I can build caffe successfully. Just don't sure if I dont't remove Matlab folders' libprotobu.so files can Caffe be build successuflly.

**Comment by wang3t** [comment]
I ran into this similar issue on MacOS Sierra during installing caffe
$ make pycaffe -j8

ERROR:
.build_release/src/caffe/proto/caffe.pb.h:17:2: error: This file was generated by an older version of protoc

Finding:
I found the issue was "proton --version" was 3.0.0 from anaconda/bin, 
but i had another protoc (3.1.0) in /usr/local/bin, 

Solution:
Adding the following to my .profile 
export PATH="/usr/local/bin:/anaconda/bin:$PATH"

HTH.

**Comment by selinachenxi** [comment]
@zchrissirhcz I have met the same problem, and by following your comments updating gcc from 4.9 to 5, the problem solved. Thank you so much.

**Comment by samuelcesc** [comment]
Had the same problem. Was using 2.6.1 through sudo apt-get while conda install had 3.2.

Just used conda remove libprotobuf to get rid of the Anaconda install and viola! it works!

**Comment by Anymake** [comment]
@samuelcesc  thank you , “conda remove libprotobuf”   is the right solution！

**Comment by huzqujm** [comment]
To me, install protobuf from source and copy its library to anaconda. [Notice: keep two protobuf version the same]
 I install protobuf from source and keep its version the same as anaconda's protobuf. But I still get thiss error message. If I remove ptotobuf which installed by me and It still return this message. I cannot remove anaconda's protobuf. So I copy system's protobuf(compiled and installed from source) to anaconda's lib and it works...

I fell confused. Anaconda's protobuf is not a complete version of protobuf? I forgot to compile two protobuf versions' file size...

**Comment by YerongLi** [comment]
Actually I think all the undefined error has something to do with the gcc/g++ version on ubuntu side, simple test can be done on the **protobuf**([https://github.com/google/protobuf/tree/master/src](https://github.com/google/protobuf/tree/master/src))
If we build protobuf with g++4.7 then caffe with g++5.4, and then caffe cannot find protobuf as a result.
And  building protobuf with g++4.7 then caffe with g++4.7, and then caffe can at leat find protobuf...

I am not sure whether downgrading gcc/g++4.7 beforehand is a good option for build caffe.

**Comment by yinyanting** [comment]
@zchrissirhcz  
I change gcc from 4.9 to 5, and  I can build caffe successfully. I have same ubuntu,gcc,and cuda

**Comment by Laowai01** [comment]
i have compiled caffe on ubuntu 16.04 LTS both with pythin 2 and python, it is really a hectic process for beginners, for caffe with pythin 2.7 mak sure that your /.local/lib/python2.7/site-packages only contains a version same as you protoc version. protoc version can be checked by entering
protoc --version
for me i got problems with python 2.7 beacause by mistake i installed protbuf 3.0 alpha in python 2.7 site packages, so there was a protobuf error after removing it from python 2.7 sitepackages everything worked fine
also install python-dev version
apt-get install the python3.x-dev
and for python 3.5 make sure you have python 3.0 alpha, if you have both python 2.7 and python 3.x in the system use pip3 otherwise use pip

pip3 install protobuf==3.0.0-alpha-3

or anyother protobuf such as 3.5 version of protobuf.
also do this
pip install python-dateutil --upgrade
after that do
sudo ldconfig

hope everything works ok for you.

**Comment by Laowai01** [comment]
i have compiled caffe on Ubuntu 16.04 LTS both with python 2 and python, it is really a hectic process for beginners, for caffe with python 2.7 make sure that your /.local/lib/python2.7/site-packages only contains a version same as you protoc version. protoc version can be checked by entering
protoc --version
for me i got problems with python 2.7 because by mistake i installed protbuf 3.0 alpha in python 2.7 site packages, so there was a protobuf error after removing it from python 2.7 site packages everything worked fine
also install python-dev version
`apt-get install the python3.x-dev`
and for python 3.5 make sure you have python 3.0 alpha, if you have both python 2.7 and python 3.x in the system use pip3 otherwise use pip

`pip3 install protobuf==3.0.0-alpha-3`

or another protobuf such as 3.5 version of protobuf.
also do this
`pip3 install python-dateutil --upgrade`
after that do 
`make clean`
`make all`
`make runtest`
`make pycaffe`
after performing make all make runtest steps don't forget to do that
`sudo ldconfig`

hope everything works OK for you.

**Comment by AustinVan** [comment]
My solution is to change the INCLUDE_DIRS and LIBRARY_DIRS in Makefile.config.
Note that the detailed protoc path is necessary.

In my case,
protoc lib path is :   /home/tools/protobuf.3.4/lib (change according to your location)
protoc include path is :  /home/tools/protobuf.3.4/include (change according to your location)

After my modification, my makefile is:
INCLUDE_DIRS := $(PYTHON_INCLUDE) /home/tools/protobuf.3.4/include /usr/local/include
LIBRARY_DIRS := $(PYTHON_LIB) /home/tools/protobuf.3.4/lib /usr/local/lib /usr/lib

Note that the protoc need to be in front of the default paths

**Comment by hana9090** [comment]
For UBUNTU 17.10, CUDA 8 and cUDNN 5 what is the best solution for the same error :( 
Which one should I follow?

**Comment by CuiXiaoDao** [comment]
ubuntu 16.04,  problem solved by compiling protobuf 2.5.0 using gcc-4.8.

**Comment by amitfishy** [comment]
I was able to build caffe on cuda 9.0 with cudnn 7 on Ubuntu 16 after modifying some makefile settings and faced most problems with the google protobuf. Originally I had the protobuf stuff installed from the deb package and I got this error. Later I tried installing it from source, but I still got this error.

So I looked at all the lib directories in the makefile path I had given and found the old protobuf.so and .a files which were installed from the deb package were there and they were causing problems. So I manually removed them (created a backup of the files) and was able to build successfully with the protobuf version installed from source.

I did have to make some changes to the makefile though (related to c++11 for protobuf 3.5) as given [here](https://github.com/BVLC/caffe/issues/6359).

**Comment by amitfishy** [comment]
I was able to install and run on Cuda 9.0 with protobuf 3.5.1.
The following worked for me:
Installed protobuf following [this](https://github.com/google/protobuf/blob/master/src/README.md)
This stored my proto.so files in /usr/local/lib
I followed the instructions here after that for using it on [python](https://github.com/google/protobuf/tree/master/python)

I still got the undefined reference error. On looking further there were some old proto.so files in `/usr/lib/x86_64-linux-gnu` which were present there from before using the deb installation. The problem was that it was picking up these files during the caffe build as opposed to the .so files that I had installed from source.
Do not delete the older .so files (my PC wouldn't reboot when I did so), instead in the makefile.config, put the directory which contains your source based .so files (/usr/local/lib in my case - default for source installation) in the beginning so it will take that and build with that instead of your older proto file location (/usr/lib/x86_64-linux-gnu - which I put in $PYTHON_LIB).
```
LIBRARY_DIRS := /usr/local/lib $(PYTHON_LIB) /usr/lib /usr/lib/x86_64-linux-gnu/hdf5/serial
```
Doing so removed the undefined reference error for me. It is mot likely due to conflict in existing version of protobuf that you have in your system.
One of the other major issues I encountered while trying protobuf v3.5.1 was related to c++11, which I was able to fix following [this](https://github.com/BVLC/caffe/issues/6359).

**Comment by g10guang** [comment]
```
gcc `pkg-config --libs --clfags protobuf` you command
```

**Comment by kongcong** [comment]
> If you are using Ubuntu, maybe this will help:
> 
> ```
> sudo apt-get install libprotobuf-dev protobuf-compiler
> ```

it can't help

**Comment by tonyhu20116543** [comment]
@groakat Exactly! It works! This error is indeed caused by the conflict of anaconda installed libprotobuf and apt installed libprotobuf. **So the final solution is that you need to uninstall all libprotobuf of anaconda, and then installed libprotobuf-dev and protobuf-compiler by apt!**

**Comment by tulha** [comment]
> I encounter same problem.
> 
> System: ubuntu16.04
> cuda: 8.0.44
> gcc: 4.9
> 
> I have installed matlab2016b, which contains a `libprotobuf.so.8`, while I use `apt-get install libprotobuf-dev` gives `libprotobuf.so.9`, maybe this is the source of conflict. However, when I remove all the libprotobuf.so files under MATLAB installation folder, I do `make clean; make -j8` still gives same problem.
> 
> Finally, I change gcc from 4.9 to 5, and this time I can build caffe successfully. Just don't sure if I dont't remove Matlab folders' libprotobu.so files can Caffe be build successuflly.

I have MATLAB installed as well and the `libprotobuf.so.9` files are present in the MATLAB folder for me too. However, I can confirm that the source of conflict is not this. Changing the gcc version from 4.9 to 5 solved the problem for me! (Y)

**Comment by northeastsquare** [comment]
in caffe makefile line 262:
ifeq ($(LINUX), 1)
    CXX ?= /usr/bin/g++
    GCCVERSION := $(shell $(CXX) -dumpversion | cut -f1,2 -d.)
    # older versions of gcc are too dumb to build boost with -Wuninitalized
    ifeq ($(shell echo | awk '{exit $(GCCVERSION) < 4.6;}'), 1)
        WARNINGS += -Wno-uninitialized
    endif
    # boost::thread is reasonably called boost_thread (compare OS X)
    # We will also explicitly add stdc++ to the link target.
    LIBRARIES += boost_thread stdc++
    VERSIONFLAGS += -Wl,-soname,$(DYNAMIC_VERSIONED_NAME_SHORT) -Wl,-rpath,$(ORIGIN)/../lib
endif

but I compile protobuf with /usr/local/bin/g++

**Comment by sunshuhuai** [comment]
> libprotobuf.so



> I encounter same problem.
> 
> System: ubuntu16.04
> cuda: 8.0.44
> gcc: 4.9
> 
> I have installed matlab2016b, which contains a `libprotobuf.so.8`, while I use `apt-get install libprotobuf-dev` gives `libprotobuf.so.9`, maybe this is the source of conflict. However, when I remove all the libprotobuf.so files under MATLAB installation folder, I do `make clean; make -j8` still gives same problem.
> 
> Finally, I change gcc from 4.9 to 5, and this time I can build caffe successfully. Just don't sure if I dont't remove Matlab folders' libprotobu.so files can Caffe be build successuflly.

I have the same situation as you.I tried a lot of methods, and finally I uninstalled gcc directly and then reinstalled it.
```
sudo apt-get build-dep gcc
sudo apt-get remove gcc
```

**Comment by charles-loomai** [comment]
Tried almost all the answers above. 
The best is @zchrissirhcz, very convenient, wont remove anything, wont break anything, only need to install gcc-5 via `apt install gcc-5 g++-5`
1. switching to `gcc-5` via `ln -sf /usr/bin/gcc-5 /usr/bin/gcc` and  `ln -sf /usr/bin/g++-5 /usr/bin/g++`, 
2. then run `make clean`, `make -j10`. 
3. [optional] switching back to your previous gcc

**Comment by amolkumarpatil** [comment]
> Tried almost all the answers above.
> The best is @zchrissirhcz, very convenient, wont remove anything, wont break anything, only need to install gcc-5 via `apt install gcc-5 g++-5`
> 
> 1. switching to `gcc-5` via `ln -sf /usr/bin/gcc-5 /usr/bin/gcc` and  `ln -sf /usr/bin/g++-5 /usr/bin/g++`,
> 2. then run `make clean`, `make -j10`.
> 3. [optional] switching back to your previous gcc
> 
> my OS is ubuntu 18.04(Linux Mint19.1), cuda9.0, cudnn7.0, RTX2080 Ti
> cheers

Works for ubuntu 18.04 [confirmed]

**Comment by gongshichina** [comment]
A small tip may help you :）
**Confirm** that your lib and include file for protobuf **correspond**, in Makefile.config
INCLUDE_DIRS := $(PYTHON_INCLUDE) $HOME/anaconda3/include /usr/local/include 
LIBRARY_DIRS := $(PYTHON_LIB) $HOME/anaconda3/lib /usr/local/lib /usr/lib 

That is to say, if your google/protobuf/include comes from $HOME/anaconda3/include, then .so/.a files must comes from $HOME/anaconda3/lib , keeping both version correspond.

**Comment by cannguyen275** [comment]
> Tried almost all the answers above.
> The best is @zchrissirhcz, very convenient, wont remove anything, wont break anything, only need to install gcc-5 via `apt install gcc-5 g++-5`
> 
> 1. switching to `gcc-5` via `ln -sf /usr/bin/gcc-5 /usr/bin/gcc` and  `ln -sf /usr/bin/g++-5 /usr/bin/g++`,
> 2. then run `make clean`, `make -j10`.
> 3. [optional] switching back to your previous gcc
> 
> my OS is ubuntu 18.04(Linux Mint19.1), cuda9.0, cudnn7.0, RTX2080 Ti
> cheers

Ubuntu 18.04, too. But this solution doesn't work.
I'm using gcc/g++ 7.4.0, anaconda3 environment. This gcc version seems to bring me further than gcc 5, gcc5 end up with error in the very first of the installation process.
Here is the error with gcc/g++ 7.4.0:
```bash
[ 65%] Building CXX object src/caffe/CMakeFiles/caffe.dir/util/hdf5.cpp.o
[ 65%] Building CXX object src/caffe/CMakeFiles/caffe.dir/util/im2col.cpp.o
[ 67%] Building CXX object src/caffe/CMakeFiles/caffe.dir/util/im_transforms.cpp.o
[ 67%] Building CXX object src/caffe/CMakeFiles/caffe.dir/util/insert_splits.cpp.o
[ 68%] Building CXX object src/caffe/CMakeFiles/caffe.dir/util/io.cpp.o
[ 68%] Building CXX object src/caffe/CMakeFiles/caffe.dir/util/math_functions.cpp.o
[ 70%] Building CXX object src/caffe/CMakeFiles/caffe.dir/util/sampler.cpp.o
[ 70%] Building CXX object src/caffe/CMakeFiles/caffe.dir/util/signal_handler.cpp.o
[ 70%] Building CXX object src/caffe/CMakeFiles/caffe.dir/util/upgrade_proto.cpp.o
[ 71%] Linking CXX shared library ../../lib/libcaffe.so
[ 71%] Built target caffe
Scanning dependencies of target convert_imageset
[ 71%] Building CXX object tools/CMakeFiles/convert_imageset.dir/convert_imageset.cpp.o
[ 73%] Linking CXX executable convert_imageset
../lib/libcaffe.so.1.0.0-rc3: undefined reference to `google::protobuf::internal::ArenaImpl::AllocateAlignedAndAddCleanup(unsigned long, void (*)(void*))'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to `google::protobuf::RepeatedField<float>::Add(float const&)'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to `google::protobuf::internal::AddDescriptors(google::protobuf::internal::DescriptorTable const*)'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to `google::protobuf::RepeatedField<unsigned int>::~RepeatedField()'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to `google::protobuf::internal::WireFormatLite::UInt32Size(google::protobuf::RepeatedField<unsigned int> const&)'
....I remove because it's too long :))
../lib/libcaffe.so.1.0.0-rc3: undefined reference to `google::protobuf::RepeatedPtrField<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::~RepeatedPtrField()'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to `google::protobuf::RepeatedPtrField<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::Add(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&)'
collect2: error: ld returned 1 exit status
tools/CMakeFiles/convert_imageset.dir/build.make:135: recipe for target 'tools/convert_imageset' failed
make[2]: *** [tools/convert_imageset] Error 1
CMakeFiles/Makefile2:441: recipe for target 'tools/CMakeFiles/convert_imageset.dir/all' failed
make[1]: *** [tools/CMakeFiles/convert_imageset.dir/all] Error 2
Makefile:129: recipe for target 'all' failed

```

**Comment by anushreehede** [comment]
I am struggling with similar errors as @cannguyen275 . Could someone please help out with this issue? I need it to work a bit urgently. I'm working with Debian 9. Would really appreciate the help!

**Comment by leondgarse** [comment]
I solved my problem by compiling and installing the **corresponding**  protobuf version with `anaconda` one from [protobuf releases](https://github.com/protocolbuffers/protobuf/releases).
```sh
$ locate libprotobuf  # List only those matters
# /opt/anaconda3/pkgs/libprotobuf-3.11.4-hd408876_0/lib/libprotobuf.so
# /opt/anaconda3/lib/libprotobuf.so.22
# /usr/local/lib/libprotobuf.so
# /usr/local/lib/libprotobuf.so.22

$ ls /usr/local/lib/libprotobuf.so -l
# /usr/local/lib/libprotobuf.so -> libprotobuf.so.22.0.4
```
- When set using `anaconda` in `Makefile.config`, `libprotobuf` version in system should match with `anaconda` one.
- Download the matched protobuf release `protobuf-cpp-xxx.tar.gz` / `protobuf-cpp-xxx.zip` from [protobuf releases](https://github.com/protocolbuffers/protobuf/releases).
- Extract and compile.
```sh
cd protobuf-3.11.4
./autogen.sh
./configure
make
make check
sudo make install
sudo ldconfig
pkg-config --cflags --libs protobuf
```
I have my own compiling caffe on `Ubuntu 20.04, python3.8` issues summary [here](https://github.com/leondgarse/Atom_notebook/blob/master/public/2019/08-12_caffe.md).

**Comment by aabolfazl** [comment]
Cmake link command

`target_link_libraries(protoTest LINK_PUBLIC -pthread -lprotobuf -lpthread)`

**Comment by enternityFan** [comment]
> apt-get remove libprotobuf-dev

thank u very much!!!!!!!!!!it 's very very helpful for me!

**Comment by enternityFan** [comment]
> apt-get remove libprotobuf-dev

thank u very much!!!!!!!!!!it 's very very helpful for me!

**Comment by dragonQian** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
