### ISSUE TITLE
backpropagate outside loss layer

### ISSUE THREAD

**Issue by mczmy** [BVLC/caffe#3050]
Hi, to some reason I want to calculate gradients on nodes of fc8 layer and backpropagate through the network. A loss layer is inappropriate in my case. I have no idea how to do this and I need some hints. I want to do similar things just like http://caffe.berkeleyvision.org/gathered/examples/cpp_classification.html, in which we have our data and we call ForwardPrefilled() to get the features or classification scores. The difference is, I want to call a function which can back propagate and update network parameters.

**Comment by seanbell** [comment]
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

That being said, you should look into the python interface.  Writing a python layer is easy and could possibly give you the loss layer and gradients you want.  If that's not appropriate, you can manually call forward, and insert in the extra gradients, and then manually call backward, all from the python interface.

**Comment by mczmy** [comment]
There is one issue introduce how to do forward using C++ API. Thus there should be one introduce how to do back propagation. Do not close my issue. I need a solution.

**Comment by PierreHao** [comment]
I have use python interface to do forward and backward, we can get diff, but weights isn't changed. I have checked pycaffe and _caffe.cpp, there isn't update function?

**Comment by seanbell** [comment]
To make a chance to the weights, you need to actually update the weights (`net.params[name].data[...] = new_value`).  Backward only computes the gradient (`net.params[name].diff`).

**Comment by PierreHao** [comment]
That means i should calculate new_value by myself? In the caffe cpp, there are 2 functions ComputeUpdateValue() and Update(), there isn't python wrapper for those functions?

**Comment by mczmy** [comment]
I think we should change diff and call Update() to update the weights. And the question is: is there a way in C++ that we can read and change the value of diff? I'm using C++, please do not tell me use python instead.

**Comment by PierreHao** [comment]
Yes, in c++, there is the way to call ComputeUdpateValue() and Update(), you can read the code in solver.cpp, these function are called in method Solver<Dtype>::Step(int iters).
