### ISSUE TITLE
Eltwise tests had failed during make runtest

### ISSUE THREAD

**Issue by cynodelic** [BVLC/caffe#3051]
Hello, when I executed `make runtest`, I had some troubles during 4 of the tests, but the other ones have successfully passed and Caffe compiled well during `make all` and `make test`.

This is what I got:

```
[----------] Global test environment tear-down
[==========] 880 tests from 133 test cases ran. (621281 ms total)
[  PASSED  ] 876 tests.
[  FAILED  ] 4 tests, listed below:
[  FAILED  ] EltwiseLayerTest/0.TestSum, where TypeParam = caffe::CPUDevice<float>
[  FAILED  ] EltwiseLayerTest/0.TestProd, where TypeParam = caffe::CPUDevice<float>
[  FAILED  ] EltwiseLayerTest/1.TestProd, where TypeParam = caffe::CPUDevice<double>
[  FAILED  ] EltwiseLayerTest/1.TestSum, where TypeParam = caffe::CPUDevice<double>

 4 FAILED TESTS
make: *** [runtest] Error 1
```

Your answers (and help) are welcome.

EDIT: I'm using it on Ubuntu 12.04 (32 bit), in CPU only mode.

**Comment by shelhamer** [comment]
Closing as likely due to numerical error just past the tolerance, as has been seen for certain CPUs and BLAS.
