### ISSUE TITLE
Error with cudaFreeHost(ptr) in syncedmem.hpp:30

### ISSUE THREAD

**Issue by LiberiFatali** [BVLC/caffe#3053]
In my case, when caffe model finishs predicting an image. There is the below error:

F0910 15:09:52.590445 21913 syncedmem.hpp:30] Check failed: error == cudaSuccess (11 vs. 0)  invalid argument
*** Check failure stack trace: ***
Aborted

It comes from CUDA_CHECK(cudaFreeHost(ptr));  in syncedmem.hpp.
Everything else works well. Any ideas for fixing this? I use latest code in the master.

I'm using Ubuntu 14.04, NVIDIA driver 352.41, Cuda 7.5 and CuDNN v2.

**Comment by hberntsen** [comment]
I get the same error in Python 2.7:
```
import caffe
net = caffe.Net('deploy.prototxt', 'bvlc_alexnet.caffemodel', caffe.TEST)
caffe.set_mode_gpu()
exit
```
On Ubuntu 14.04, NVIDIA 346.82, Cuda 7. The error is encountered after the exit command.

**Comment by beniz** [comment]
I've seen this before as well as a crash whenever net is deleted after a predict. This not guaranteed to help you immediately, but you may want to try to get your Caffe tree back to one of these two commits and try your code again:
- 0dfc5dac3d8bf17f833e21ae6ce7bc3ea19a03fa
- d2f045768cba7d494abb4d168fc366d6fce80b85

Hopefully, one of the versions above will work for you, thus helping to pinpoint the issue.

**Comment by ronghanghu** [comment]
I believe we have a bug here. I'll try to look into this today.

**Comment by ronghanghu** [comment]
@hberntsen @beniz I just took a look today. Can you reproduce the same error if you run `caffe.set_mode_gpu()` **before** creating your net? That is, 

    import caffe
    #standard bvlc_alexnet
    caffe.set_mode_gpu()
    net = caffe.Net('deploy.prototxt', 'bvlc_alexnet.caffemodel', caffe.TEST)
    exit

Right now the mode is not (but actually should be) an attribute of the net that is set up during creation (just like phase), since in CPU mode `malloc` is used while in GPU mode `cudaMallocHost is used` (introduced in #2903). If you run `caffe.set_mode_gpu()` after creating a net, caffe will try to use `cudaFreeHost` instead of `free` to free memory allocated by `malloc`, resulting in this error.

**Comment by ronghanghu** [comment]
One solution is to always use `cudaMallocHost` to allocate host memory unless using CPU_ONLY build. @shelhamer do you agree?

Alternatively, we can also add mode to be an attribute of net, but that involves more hacking at the cost of interface change and at risk of introducing new mistakes.

**Comment by beniz** [comment]
@ronghanghu I believe this is indeed a good catch, thanks for the quick reaction! Though I cannot test-run immediately, my code appears to be calling `set_mode_gpu` after Net creation.

> Alternatively, we can also add mode to be an attribute of net, but that involves more hacking at the cost of interface change and at risk of introducing new mistakes.

If this gives the ability to have multiple nets in memory, some using CPU, some using GPU, as a user of the caffelib, I would rate it as a very good feature to conserve (since as far as I understand, this was working prior to enforcing the use of `cudaMallocHost').

**Comment by ronghanghu** [comment]
>If this gives the ability to have multiple nets in memory, some using CPU, some using GPU, as a user of the caffelib, I would rate it as a very good feature to conserve (since as far as I understand, this was working prior enforcing the use of `cudaMallocHost').

Eventually we would like to give mode and device to net and layers, in the spirit of #1500. But it seems like a short-term fix to always use `cudaMallocHost` to allocate cpu memory regardless of the mode of the net to avoid this crash.

However, although mode/device is right now not a member of Net and Layer and thus changable in runtime, it is better to set them in advance and not change them during a lifecycle of a net.

**Comment by hberntsen** [comment]
@ronghanghu In that case the error is does not appear. So setting the mode to GPU before loading the net circumvents the issue.

**Comment by LiberiFatali** [comment]
I use caffe.Classifier to contruct the net, not caffe.Net. So when I use
```
self.net = caffe.Classifier(MODEL_FILE, PRETRAINED) 
caffe.set_mode_gpu()
```
or 
```
caffe.set_mode_gpu()
self.net = caffe.Classifier(MODEL_FILE, PRETRAINED)
```
this error is still there.

I will try suggested commits above. Thanks.

**Comment by LiberiFatali** [comment]
I also test on GPUs with and without connected monitor to see if it is the problem of freeing in-use GPU memory. Still got the error.

**Comment by ronghanghu** [comment]
@LiberiFatali I could not reproduce your mistake (here is the code snap I used).

    import caffe
    caffe.set_mode_gpu()

    model   = './caffe/models/bvlc_reference_caffenet/deploy.prototxt'
    weights = './caffe/models/bvlc_reference_caffenet/bvlc_reference_caffenet.caffemodel'
    net = caffe.Classifier(model, weights)

    impath = './caffe/examples/images/cat.jpg'
    im = caffe.io.load_image(impath)
    probs = net.predict([im])

It doesn't produce any error on a BVLC machine. Can you try out this code snap on your machine?

**Comment by LiberiFatali** [comment]
@ronghanghu Above codes work well on my machine. Setting mode gpu before creating the net solves it now.

**Comment by eldar** [comment]
I have exactly the same issue when cleaning up network instances in Matlab with call to ```caffe.reset_all()```. Placing ```caffe.set_mode_gpu();``` before loading the model also solved it.

**Comment by cheer37** [comment]
I put the setmode before net creation. But i got this error still.
How can i solve this problem?
Thanks.

**Comment by ucasqcz** [comment]
@cheer37 ,have you fix the problem ,i did not use the latest PR of caffe,and i get the same error 
Check failed: error == cudaSuccess (29 vs. 0) driver shutting down
how did you solve this problem ?
thanks.

**Comment by zhxjlbs** [comment]
@ucasqcz have you fix the problem, i get the same error
Check failed: error == cudaSuccess (29 vs. 0) driver shutting down
how did you solve this problem ?
