### ISSUE TITLE
Config option for -ccbin compiling CUDA

### ISSUE THREAD

**Issue by invisiblearts** [BVLC/caffe#3056]
With some rolling update distributions, gcc is up-to-date while CUDA often supports only a former version, decided when it's released. Therefore, the option for -ccbin in Makefile.config should help.

**Comment by longjon** [comment]
Caffe normally sets `-ccbin` to `$(CXX)`, which can be set in `Makefile.config`; is there a good reason to set `-ccbin` to a different value (i.e., for `nvcc` to use a host compiler different from the one used to build the rest of Caffe)?

**Comment by invisiblearts** [comment]
Cuda support for compilers is often much delayed compared to compiler upgrading. For instance, gcc 5 is already released for a long time, while CUDA7.5 (released just recently) still do not support gcc 5. Sometimes the ABI of compiler is not necessarily changed, and therefore there should be a good reason to add support for that. thx.
