### ISSUE TITLE
How to train multiple models for better accuracy

### ISSUE THREAD

**Issue by palmforest** [BVLC/caffe#306]
Hi ,
I want to train multiple models for one application. In Hinton imagenet 2012, they mentioned that multiple models were used to get the final winning score, similar for Overfeat 2013. Does anyone know how to do this exactly? To do this one needs to use the same network structure to train multiple models or not?

**Comment by qingzew** [comment]
I have seen that the output vector of  softmax of caffe mostly like this: [000010000...], only one element is 1, others is 0
I saw some paper say that average the output of the cnn net can ahcieve a good result, so I doubt, someone try this?
