### ISSUE TITLE
Homebrew libgfortran.3.dylib not found

### ISSUE THREAD

**Issue by tcfuji** [BVLC/caffe#3061]
I'm using OS X 10.10.5 and trying to install caffe but I get the following error:
```
$ make all -j4
LD -o .build_release/lib/libcaffe.so
clang: warning: argument unused during compilation: '-pthread'
ld: file not found: /usr/local/lib/gcc/4.9/libgfortran.3.dylib for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [.build_release/lib/libcaffe.so] Error 1
```
As you can see, it's looking for a nonexistent `gcc-4.9`. This is strange since I only have `gcc-5.2.0`. I even removed and installed `gcc` again and got the same error. My guess is that Homebrew is to blame somehow.

**Comment by edudar** [comment]
I've ran it with gcc 4.9 installed through homebrew as well and it still fails because there's no such file in place.

**Comment by longjon** [comment]
Closing as this looks like an installation that's not the fault of Caffe.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
