### ISSUE TITLE
Error: Check failed: target_blobs[j]->shape() == source_blob->shape()

### ISSUE THREAD

**Issue by Tchaikovic** [BVLC/caffe#3064]
Hi, I would be really glad if someone could help me with this error.

This is my architecture:

name: "LogisticRegressionNet"
layer {
  name: "data"
  type: "HDF5Data"
  top: "data"
  top: "label"
  include {
    phase: TRAIN
  }
  hdf5_data_param {
    source: "demo_output.txt"
    batch_size: 100
  }
}

layer {
  name: "data_test"
  type: "HDF5Data"
  top: "data"
  top: "label"
  include {
    phase: TEST
  }
  hdf5_data_param {
    source: "team.txt"
    batch_size: 100
  }
}

layer {
  name: "conv1"
  type: "Convolution"
  bottom: "data"
  top: "conv1"
  param {
    lr_mult: 1
    decay_mult: 1
  }
  param {
    lr_mult: 2
    decay_mult: 0
  }
  convolution_param {
    num_output: 96
    kernel_size: 3
    stride: 1
    weight_filler {
      type: "gaussian"
      std: 0.01
    }
    bias_filler {
      type: "constant"
      value: 0
    }
  }
}
layer {
  name: "relu1"
  type: "ReLU"
  bottom: "conv1"
  top: "conv1"
}
layer {
  name: "pool1"
  type: "Pooling"
  bottom: "conv1"
  top: "pool1"
  pooling_param {
    pool: MAX
    kernel_size: 3
    stride: 2
  }
}

layer {
  name: "fc1"
  type: "InnerProduct"
  bottom: "pool1"
  top: "fc1"
  param {
    lr_mult: 1
    decay_mult: 1
  }
  param {
    lr_mult: 2
    decay_mult: 0
  }
  inner_product_param {
    num_output: 6
    weight_filler {
      type: "gaussian"
      std: 0.01
    }
    bias_filler {
      type: "constant"
      value: 0
    }
  }
}

layer {
  name: "fc2"
  type: "InnerProduct"
  bottom: "fc1"
  top: "fc2"
  param {
    lr_mult: 1
    decay_mult: 1
  }
  param {
    lr_mult: 2
    decay_mult: 0
  }
  inner_product_param {
    num_output: 2
    weight_filler {
      type: "gaussian"
      std: 0.01
    }
    bias_filler {
      type: "constant"
      value: 0
    }
  }
}
layer {
  name: "loss"
  type: "EuclideanLoss"
  bottom: "fc2"
  bottom: "label"
  top: "loss"
   include {
    phase: TRAIN
  }
}
layer {
 name: 'loss_test'
 type: "EuclideanLoss"
 bottom: 'fc2'
 bottom: 'label'
 top: 'loss_test'
  include {
    phase: TEST
  }
}

and this is my solver.prototxt

net: "bvlc_reference_caffenet/train_val.prototxt"
test_iter: 9000
test_interval: 9000
base_lr: 0.05
lr_policy: "step"
gamma: 0.9
stepsize: 5000
display: 5000
max_iter: 45000
momentum: 0.9
weight_decay: 0.0005
snapshot: 10000
snapshot_prefix: "bvlc_reference_caffenet/one_conv_"
solver_mode: CPU

Does anyone know what might be the problem?

**Comment by seanbell** [comment]
First:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

Second:
For that check, if you're on the latest mater branch, it should have given a message explaining the error, starting with the text "Cannot share param ...".  This means you tried to copy weights from one blob to another, with non-matching shapes.
