### ISSUE TITLE
Cannot build caffe on ubuntu 14.04

### ISSUE THREAD

**Issue by 201power** [BVLC/caffe#3066]
Hello,

I am trying to build latest version of caffe on Ubuntu 14.04, however, I always got this error:
![image](https://cloud.githubusercontent.com/assets/7299296/9863887/f8219c82-5af8-11e5-95db-bcd2e9f8b6b3.png)

I do not have hdf5.h under usr/include/hdf5/serial, however, I have hdf5.h under usr/include

Any suggestions?
Thanks!

**Comment by seanbell** [comment]
Are you sure you have the latest version of caffe?

On the master branch, net.cpp:8 is different from what you have:
https://github.com/BVLC/caffe/blob/master/src/caffe/net.cpp#L8

**Comment by 201power** [comment]
Solved by compiling with the latest version of caffe
