### ISSUE TITLE
strange result when running blvc_reference_caffenet model

### ISSUE THREAD

**Issue by deercoder** [BVLC/caffe#3075]
Hi,

I tried to run the example here: https://github.com/BVLC/caffe/blob/master/examples/00-classification.ipynb, but find that my result is quite different from the notebook's description,

Here is my result:
**Predicted class is #48281.**

And the example says:
**Predicted class is #281.**

Does anyone know why here it's different?

BTW, first I think it might be category#48 and category#281, but now I'm sure that it's not, since I check the */data/ilsvrc12/synset_words.txt* and think they're unrelated. I have done several times with the newest caffe repos and download the models from the *readme*'s url: [http://dl.caffe.berkeleyvision.org/bvlc_reference_caffenet.caffemodel](http://dl.caffe.berkeleyvision.org/bvlc_reference_caffenet.caffemodel), I tried to download(Model Zoo) with **./scripts/download_model_binary.py models/bvlc_reference_caffenet/** but it's too slow so I don't test this model, but I wonder that maybe this model is the same as the previous url.

Any suggestions will be much appreciated, Thanks.

**Comment by seanbell** [comment]
You need to do
out['prob'].argmax(axis=1)
to get the prediction for each item in the batch.

Otherwise, it's the argmax across the flattened array which could include images from other batches, if your batchsize isn't set to 1.

**Comment by seanbell** [comment]
Also:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

**Comment by deercoder** [comment]
Thank you very much @seanbell , and for your suggestion. I just found that google group which is also very useful!
