### ISSUE TITLE
HOW TO TRAIN FCN+CAFFE

### ISSUE THREAD

**Issue by northchert** [BVLC/caffe#3076]
I want to know how to set the trained pictures' path and get the codes for training. thank you!

**Comment by seanbell** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
