### ISSUE TITLE
Problem creating LMDB from Matlab

### ISSUE THREAD

**Issue by MarcBS** [BVLC/caffe#3078]
Hello,

I need to call the convert_imageset function for converting a database into LMDB format from inside Matlab. 

I am using Linux, and I have created a shell (.sh) script with the needed parameters for running the conversion. Here is an example of how does my shell file look like:

> GLOG_logtostderr=1 /usr/local/caffe-master2/build/tools/convert_imageset -resize_height=256 -resize_width=256 images_folder data_split/train.txt data_split/dataCNN_train_lmdb

When I simply run my script from the terminal like this:
> ./example_shell.sh

it works without any problem. 
But when I try to do it from Matlab using the system() function:
> system('./example_shell.sh')

it seems it is not able to open/find my files, rising the following error for each image in train.txt:
> I0917 18:15:13.637830  8605 convert_imageset.cpp:82] A total of 68175 images.
I0917 18:15:13.638947  8605 db.cpp:34] Opened lmdb data_split/dataCNN_train_lmdb
E0917 18:15:13.639143  8605 io.cpp:77] Could not open or find file ...
E0917 18:15:13.639143  8605 io.cpp:77] Could not open or find file ...
E0917 18:15:13.639143  8605 io.cpp:77] Could not open or find file ...

Thank you,
Marc

**Comment by ronghanghu** [comment]
Please do not post usage, installation, or modeling questions, or other requests for help to Issues.
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
