### ISSUE TITLE
PyCaffe backward() fails when label is set manually

### ISSUE THREAD

**Issue by fferrara** [BVLC/caffe#3079]
I'm trying to do a single backward pass. Thing is, pycaffe is not accepting neither a 4-d nor a 2-d label specification.
I am using a net specification without a Data Layer, but it should not be related to the problem.

Let's suppose

    label = np.zeros((1, num_classes))
    label[0, 2] = 1
    net.backward(**{net.outputs[0]: label})
fails with `Exception: prob diff is not 4-d`.
Alternatively,

    net.backward(**{net.outputs[0]: label.reshape(1,5,1,1)})
fails with `ValueError: could not broadcast input array from shape (5,1,1) into shape (1,5)`.

It seems that 269dafa37a96250012a10537ad773840b4621ff7  removed the need for 4-d ndarrays for `forward()`, but it's still present for `backward()`.

Cheers

**Comment by longjon** [comment]
Closing as this appears to be have been addressed by https://github.com/BVLC/caffe/commit/09b8738d73ebc37dda09e8c6dd05e35609999c77.
