### ISSUE TITLE
Matlab crashes on net constructor caffe.Net

### ISSUE THREAD

**Issue by amolchanov86** [BVLC/caffe#3080]
Configuration:
Ubuntu 12.04 LTS
Matlab R2013a

Crashes on:
net = caffe.Net(model, weights, 'test');

Crash message:
MATLAB crash file:/home/artem/matlab_crash_dump.26800-1:

------------------------------------------------------------------------
            Abort signal detected at Thu Sep 17 12:07:46 2015
------------------------------------------------------------------------

Configuration:
  Crash Decoding     : Disabled
  Current Visual     : 0x21 (class 4, depth 24)
  Default Encoding   : UTF-8
  GNU C Library      : 2.15 stable
  MATLAB Architecture: glnxa64
  MATLAB Root        : /opt/MATLAB/R2013a
  MATLAB Version     : 8.1.0.604 (R2013a)
  Operating System   : Linux 3.8.0-35-generic #50~precise1-Ubuntu SMP Wed Dec 4 17:25:51 UTC 2013 x86_64
  Processor ID       : x86 Family 6 Model 60 Stepping 3, GenuineIntel
  Virtual Machine    : Java 1.6.0_17-b04 with Sun Microsystems Inc. Java HotSpot(TM) 64-Bit Server VM mixed mode
  Window System      : The X.Org Foundation (11303000), display :0

Fault Count: 1

Abnormal termination:
Abort signal

Register State (from fault):
  RAX = 0000000000000000  RBX = 00007fa03db65828
  RCX = ffffffffffffffff  RDX = 0000000000000006
  RSP = 00007fa02bbc2308  RBP = 0000000000000008
  RSI = 00000000000068de  RDI = 00000000000068b0

   R8 = 00007fa03db66aa0   R9 = 00007fa02bbca700
  R10 = 0000000000000008  R11 = 0000000000000202
  R12 = 0000000000000004  R13 = 0000000000000001
  R14 = 00007f9f2853ff70  R15 = 0000000000000000

  RIP = 00007fa03d7e1425  EFL = 0000000000000202

   CS = 0033   FS = 0000   GS = 0000

Stack Trace (from fault):
[  0] 0x00007fa03d7e1425                    /lib/x86_64-linux-gnu/libc.so.6+00222245 gsignal+00000053
[  1] 0x00007fa03d7e4b8b                    /lib/x86_64-linux-gnu/libc.so.6+00236427 abort+00000379
[  2] 0x00007fa02f2ba68a        /opt/MATLAB/R2013a/bin/glnxa64/libhdf5.so.6+00214666 H5check_version+00000522
[  3] 0x00007f9f46badd5d     /opt/caffe/matlab/+caffe/private/caffe_.mexa64+01650013
[  4] 0x00007f9f46bacc40     /opt/caffe/matlab/+caffe/private/caffe_.mexa64+01645632
[  5] 0x00007f9f46af582a     /opt/caffe/matlab/+caffe/private/caffe_.mexa64+00895018
[  6] 0x00007f9f46af8313     /opt/caffe/matlab/+caffe/private/caffe_.mexa64+00906003
[  7] 0x00007f9f46a5bd13     /opt/caffe/matlab/+caffe/private/caffe_.mexa64+00265491
[  8] 0x00007f9f46a5bfa5     /opt/caffe/matlab/+caffe/private/caffe_.mexa64+00266149 mexFunction+00000180
[  9] 0x00007fa035e48f8a           /opt/MATLAB/R2013a/bin/glnxa64/libmex.so+00110474 mexRunMexFile+00000090
[ 10] 0x00007fa035e450f9           /opt/MATLAB/R2013a/bin/glnxa64/libmex.so+00094457
[ 11] 0x00007fa035e45f1c           /opt/MATLAB/R2013a/bin/glnxa64/libmex.so+00098076
[ 12] 0x00007fa03f75e6b2 /opt/MATLAB/R2013a/bin/glnxa64/libmwm_dispatcher.so+00562866 _ZN8Mfh_file11dispatch_fhEiPP11mxArray_tagiS2_+00000594
[ 13] 0x00007fa03f1e8bf6 /opt/MATLAB/R2013a/bin/glnxa64/libmwm_interpreter.so+04262902
[ 14] 0x00007fa03f1e937a /opt/MATLAB/R2013a/bin/glnxa64/libmwm_interpreter.so+04264826
[ 15] 0x00007fa03f1e9eea /opt/MATLAB/R2013a/bin/glnxa64/libmwm_interpreter.so+04267754
[ 16] 0x00007fa03f04cbbd /opt/MATLAB/R2013a/bin/glnxa64/libmwm_interpreter.so+02575293
[ 17] 0x00007fa03f078412 /opt/MATLAB/R2013a/bin/glnxa64/libmwm_interpreter.so+02753554
[ 18] 0x00007fa03f07853f /opt/MATLAB/R2013a/bin/glnxa64/libmwm_interpreter.so+02753855
[ 19] 0x00007fa03f195500 /opt/MATLAB/R2013a/bin/glnxa64/libmwm_interpreter.so+03921152
[ 20] 0x00007fa03efae868 /opt/MATLAB/R2013a/bin/glnxa64/libmwm_interpreter.so+01927272
[ 21] 0x00007fa03f019e50 /opt/MATLAB/R2013a/bin/glnxa64/libmwm_interpreter.so+02367056
[ 22] 0x00007fa03f75e6b2 /opt/MATLAB/R2013a/bin/glnxa64/libmwm_dispatcher.so+00562866 _ZN8Mfh_file11dispatch_fhEiPP11mxArray_tagiS2_+00000594
[ 23] 0x00007fa03642153a        /opt/MATLAB/R2013a/bin/glnxa64/libmwmcos.so+01672506
[ 24] 0x00007fa0363c213a        /opt/MATLAB/R2013a/bin/glnxa64/libmwmcos.so+01282362
[ 25] 0x00007fa0363c23be        /opt/MATLAB/R2013a/bin/glnxa64/libmwmcos.so+01283006
[ 26] 0x00007fa0363c412c        /opt/MATLAB/R2013a/bin/glnxa64/libmwmcos.so+01290540
[ 27] 0x00007fa03642f246        /opt/MATLAB/R2013a/bin/glnxa64/libmwmcos.so+01729094
[ 28] 0x00007fa0364aecd8        /opt/MATLAB/R2013a/bin/glnxa64/libmwmcos.so+02251992
[ 29] 0x00007fa03f710af8 /opt/MATLAB/R2013a/bin/glnxa64/libmwm_dispatcher.so+00244472 _ZN13Mfh_MATLAB_fn11dispatch_fhEiPP11mxArray_tagiS2_+00000488
[ 30] 0x00007fa03effc256 /opt/MATLAB/R2013a/bin/glnxa64/libmwm_interpreter.so+02245206
[ 31] 0x00007fa03efaca86 /opt/MATLAB/R2013a/bin/glnxa64/libmwm_interpreter.so+01919622
[ 32] 0x00007fa03efb1374 /opt/MATLAB/R2013a/bin/glnxa64/libmwm_interpreter.so+01938292
[ 33] 0x00007fa03efad993 /opt/MATLAB/R2013a/bin/glnxa64/libmwm_interpreter.so+01923475
[ 34] 0x00007fa03efae797 /opt/MATLAB/R2013a/bin/glnxa64/libmwm_interpreter.so+01927063
[ 35] 0x00007fa03f019e50 /opt/MATLAB/R2013a/bin/glnxa64/libmwm_interpreter.so+02367056
[ 36] 0x00007fa03f75e6b2 /opt/MATLAB/R2013a/bin/glnxa64/libmwm_dispatcher.so+00562866 _ZN8Mfh_file11dispatch_fhEiPP11mxArray_tagiS2_+00000594
[ 37] 0x00007fa036425a2f        /opt/MATLAB/R2013a/bin/glnxa64/libmwmcos.so+01690159
[ 38] 0x00007fa0363c15c4        /opt/MATLAB/R2013a/bin/glnxa64/libmwmcos.so+01279428
[ 39] 0x00007fa0363c20b9        /opt/MATLAB/R2013a/bin/glnxa64/libmwmcos.so+01282233
[ 40] 0x00007fa0363c23be        /opt/MATLAB/R2013a/bin/glnxa64/libmwmcos.so+01283006
[ 41] 0x00007fa0363c368d        /opt/MATLAB/R2013a/bin/glnxa64/libmwmcos.so+01287821
[ 42] 0x00007fa0363c37ad        /opt/MATLAB/R2013a/bin/glnxa64/libmwmcos.so+01288109
[ 43] 0x00007fa0363c3a4c        /opt/MATLAB/R2013a/bin/glnxa64/libmwmcos.so+01288780 _Z27omConstructObjectWithClientN4mcos9COSNameIDEiPPK11mxArray_tagPKNS_9COSClientE+00000476
[ 44] 0x00007fa03642eb3d        /opt/MATLAB/R2013a/bin/glnxa64/libmwmcos.so+01727293
[ 45] 0x00007fa0364b0673        /opt/MATLAB/R2013a/bin/glnxa64/libmwmcos.so+02258547
[ 46] 0x00007fa03f710af8 /opt/MATLAB/R2013a/bin/glnxa64/libmwm_dispatcher.so+00244472 _ZN13Mfh_MATLAB_fn11dispatch_fhEiPP11mxArray_tagiS2_+00000488
[ 47] 0x00007fa03effc256 /opt/MATLAB/R2013a/bin/glnxa64/libmwm_interpreter.so+02245206
[ 48] 0x00007fa03efaca86 /opt/MATLAB/R2013a/bin/glnxa64/libmwm_interpreter.so+01919622
[ 49] 0x00007fa03efb1374 /opt/MATLAB/R2013a/bin/glnxa64/libmwm_interpreter.so+01938292
[ 50] 0x00007fa03efad993 /opt/MATLAB/R2013a/bin/glnxa64/libmwm_interpreter.so+01923475
[ 51] 0x00007fa03efae797 /opt/MATLAB/R2013a/bin/glnxa64/libmwm_interpreter.so+01927063
[ 52] 0x00007fa03f019e50 /opt/MATLAB/R2013a/bin/glnxa64/libmwm_interpreter.so+02367056
[ 53] 0x00007fa03f75e6b2 /opt/MATLAB/R2013a/bin/glnxa64/libmwm_dispatcher.so+00562866 _ZN8Mfh_file11dispatch_fhEiPP11mxArray_tagiS2_+00000594
[ 54] 0x00007fa03efe8dcb /opt/MATLAB/R2013a/bin/glnxa64/libmwm_interpreter.so+02166219
[ 55] 0x00007fa03efa67cc /opt/MATLAB/R2013a/bin/glnxa64/libmwm_interpreter.so+01894348
[ 56] 0x00007fa03efa2e1d /opt/MATLAB/R2013a/bin/glnxa64/libmwm_interpreter.so+01879581
[ 57] 0x00007fa03efa3255 /opt/MATLAB/R2013a/bin/glnxa64/libmwm_interpreter.so+01880661
[ 58] 0x00007fa036071fae      /opt/MATLAB/R2013a/bin/glnxa64/libmwbridge.so+00139182
[ 59] 0x00007fa036072111      /opt/MATLAB/R2013a/bin/glnxa64/libmwbridge.so+00139537
[ 60] 0x00007fa036072ce5      /opt/MATLAB/R2013a/bin/glnxa64/libmwbridge.so+00142565 _Z8mnParserv+00000725
[ 61] 0x00007fa03f9f63d2         /opt/MATLAB/R2013a/bin/glnxa64/libmwmcr.so+00447442 _ZN11mcrInstance30mnParser_on_interpreter_threadEv+00000034
[ 62] 0x00007fa03f9d59ac         /opt/MATLAB/R2013a/bin/glnxa64/libmwmcr.so+00313772
[ 63] 0x00007fa03f9d5b88         /opt/MATLAB/R2013a/bin/glnxa64/libmwmcr.so+00314248
[ 64] 0x00007fa0335865c6         /opt/MATLAB/R2013a/bin/glnxa64/libmwuix.so+00480710
[ 65] 0x00007fa033593df2         /opt/MATLAB/R2013a/bin/glnxa64/libmwuix.so+00536050
[ 66] 0x00007fa0400c0862    /opt/MATLAB/R2013a/bin/glnxa64/libmwservices.so+01845346
[ 67] 0x00007fa0400c150f    /opt/MATLAB/R2013a/bin/glnxa64/libmwservices.so+01848591 _Z25svWS_ProcessPendingEventsiib+00001615
[ 68] 0x00007fa03f9d65ef         /opt/MATLAB/R2013a/bin/glnxa64/libmwmcr.so+00316911
[ 69] 0x00007fa03f9d6f5c         /opt/MATLAB/R2013a/bin/glnxa64/libmwmcr.so+00319324
[ 70] 0x00007fa03f9d0592         /opt/MATLAB/R2013a/bin/glnxa64/libmwmcr.so+00292242
[ 71] 0x00007fa03db72e9a              /lib/x86_64-linux-gnu/libpthread.so.0+00032410
[ 72] 0x00007fa03d89f3fd                    /lib/x86_64-linux-gnu/libc.so.6+01000445 clone+00000109

This error was detected while a MEX-file was running. If the MEX-file
is not an official MathWorks function, please examine its source code
for errors. Please consult the External Interfaces Guide for information
on debugging MEX-files.

If this problem is reproducible, please submit a Service Request via:
    http://www.mathworks.com/support/contact_us/

A technical support engineer might contact you with further information.

Thank you for your help.

**Comment by ShaggO** [comment]
There's probably an error somewhere in your model.
You should try to run Matlab from a terminal with the "--nodesktop --novjm" flags, in which case the caffe log is printed to the terminal as well when you run your code. This log will probably tell you why the mex crashes.

**Comment by ronghanghu** [comment]
To get more detailed output, run Matlab from a terminal, and see the terminal output for detailed error message. 

This issue is usually caused by one of the CHECK marcos failure in Caffe's internal.
