### ISSUE TITLE
Blob size exceeds INT_MAX

### ISSUE THREAD

**Issue by PiranjaF** [BVLC/caffe#3084]
When running my code I get the following error `blob.cpp:29] Check failed: shape[i] <= 2147483647 / count_ (24 vs. 17) blob size exceeds INT_MAX`, which I've found in the source code as seen below. However, I am curious as to how to circumvent this limit, which seems rather low. If I e.g. use 200x200 images, then I can only input `2147483647  / 40000 = 53687` images. Is this a bug? 

I am currently using HDF5 as my data source. Would it make any difference if I used another data source instead?

```
template <typename Dtype>
void Blob<Dtype>::Reshape(const vector<int>& shape) {
  CHECK_LE(shape.size(), kMaxBlobAxes);
  count_ = 1;
  shape_.resize(shape.size());
  for (int i = 0; i < shape.size(); ++i) {
    CHECK_GE(shape[i], 0);
    CHECK_LE(shape[i], INT_MAX / count_) << "blob size exceeds INT_MAX";
    count_ *= shape[i];
    shape_[i] = shape[i];
  }
  if (count_ > capacity_) {
    capacity_ = count_;
    data_.reset(new SyncedMemory(capacity_ * sizeof(Dtype)));
    diff_.reset(new SyncedMemory(capacity_ * sizeof(Dtype)));
  }
}
```

**Comment by seanbell** [comment]
See #1470 and #2953

**Comment by PiranjaF** [comment]
@seanbell Thanks! I don't why I couldn't find it with a Google search. Feel free to close this issue.

**Comment by vra** [comment]
@seanbell Thanks for your explanation, but I wonder is there any utility to split that big hdf5 file into small ones? I googled it but did not find a good solution.

**Comment by lukeyeager** [comment]
@vra you can try the DIGITS 'create_db' tool:

https://github.com/NVIDIA/DIGITS/blob/digits-3.0/tools/create_db.py
```sh
tools/create_db.py train.txt train_db 28 28 -b hdf5 --hdf5_dset_limit=2147483648
```

**Comment by vra** [comment]
@lukeyeager Thanks! that's helpful.

**Comment by Santiago810** [comment]
@lukeyeager  could you tell me the content format in the train.txt when you  excute "tools/create_db.py train.txt train_db 28 28 -b hdf5 --hdf5_dset_limit=2147483648"?
thank you

**Comment by smajida** [comment]
@seanbell @vra @lukeyeager @PiranjaF 
I am experiencing the same problem. After searching through the internet, I noticed the blob format should be changed to avoid INT_MAX problem. As I am using faster_rcnn algorithm to detect object, DIGIT is not possible to be used. My images are big (5kx3k). I do not have GPU problem. How I can solve this problem?

> F1214 18:32:32.298799 27802 blob.cpp:33] Check failed: shape[i] <= 2147483647 / count_ (3744 vs. 663) blob size exceeds INT_MAX

**Comment by naibaf7** [comment]
@smajida 
You can try to use the OpenCL branch with USE_CUDA=1, USE_GREENTEA=0 and USE_INDEX64=1, it allows full 64 bit address space and shapes in all critical areas of Caffe.

**Comment by vra** [comment]
Hi @smajida ,
Are you using rgb's [py-faster-rcnn](https://github.com/rbgirshick/py-faster-rcnn) implementation? If so , you can check the code in `lib/fast_rcnn/config.py`  and resize your image since your image is too large. The related lines are [this](https://github.com/rbgirshick/py-faster-rcnn/blob/master/lib/fast_rcnn/config.py#L36-L38) and [this](https://github.com/rbgirshick/py-faster-rcnn/blob/master/lib/fast_rcnn/config.py#L40-L41). Hope this helps.

**Comment by smajida** [comment]
@naibaf7 

> You can try to use the OpenCL branch with USE_CUDA=1, USE_GREENTEA=0 and USE_INDEX64=1, it allows full 64 bit address space (above INT_MAX) and shapes in all critical areas of Caffe. Haven't tested though if it will also work with larger HDF5 files, but it might.

Thanks. I am on it. I will give you feedback as soon as I am done.

@vra 

> Are you using rgb's py-faster-rcnn implementation? If so , you can check the code in lib/fast_rcnn/config.py and resize your image since your image is too large. The related lines are this and this. Hope this helps.

Hi and thanks. Yes, I am using rgb implementation. First I can not change the size of images as the objects are very small and resizing would have negative effect. I can not also split the image as the Ground truth has been provided for the original image and I thought it would be less efficient to split the image as I would miss some objects at the splitting border.  I had already changed the size of images in the following lines from (600,1000) to (5616,3744):
`# Each scale is the pixel size of an image's shortest side
__C.TRAIN.SCALES = (5616,)
# Max pixel size of the longest side of a scaled input image
__C.TRAIN.MAX_SIZE = 3744
`
When training the network, I can see the original image is being read:
`I1214 18:32:32.067646 27802 net.cpp:150] Setting up input-data
I1214 18:32:32.067694 27802 net.cpp:157] Top shape: 1 3 5616 3744 (63078912)
I1214 18:32:32.067699 27802 net.cpp:157] Top shape: 1 3 (3)
I1214 18:32:32.067703 27802 net.cpp:157] Top shape: 1 4 (4)
`
I think if I can be able to increase the blob size (above INT_MAX), it would be the most efficient way to do so as @naibaf7 has mentioned. I have not started doing that, but as soon as I am done, I will write you back.

**Comment by vra** [comment]
Hi @smajida ,
Thanks for your clear explanation, I notice that you set `TRAIN.SCALES` larger than `TRAIN.MAX_SIZE`, however,  from the comments above the lines we can find that the former should be smaller than  or equal to the latter, because the former one is the target size the shorter side resizes to, while the latter one is the max size that the larger side can resize to.

**Comment by smajida** [comment]
Hi @vra 
Thanks. I changed those parameters to the following ones:
```
# Scales to use during training (can list multiple scales)
# Each scale is the pixel size of an image's shortest side
__C.TRAIN.SCALES = (5616,)

# Max pixel size of the longest side of a scaled input image
__C.TRAIN.MAX_SIZE = 5616
```
But I see the wrong image size is being read i.e. instead of 5616x3744x3 now 5616x5616 is being read. 
```
I1215 09:05:41.145800 22868 net.cpp:150] Setting up input-data
I1215 09:05:41.145840 22868 net.cpp:157] Top shape: 1 3 5616 5616 (94618368)
I1215 09:05:41.145849 22868 net.cpp:157] Top shape: 1 3 (3)
I1215 09:05:41.145858 22868 net.cpp:157] Top shape: 1 4 (4)
```
Is 3x5616x5616 a four channel blob with CHW dimension i.e. BGR?  If yes, I swapped 5616 with 3744
```
I1215 09:12:35.132300 26293 net.cpp:150] Setting up input-data
I1215 09:12:35.132341 26293 net.cpp:157] Top shape: 1 3 3744 5616 (63078912)
I1215 09:12:35.132346 26293 net.cpp:157] Top shape: 1 3 (3)
I1215 09:12:35.132349 26293 net.cpp:157] Top shape: 1 4 (4)
```
In both cases I am still experiencing `blob size exceeds INT_MAX
` problem.  
```
first case: Check failed: shape[i] <= 2147483647 / count_ (5616 vs. 995) blob size exceeds INT_MAX
second case: Check failed: shape[i] <= 2147483647 / count_ (5616 vs. 995) blob size exceeds INT_MAX
```


In the comments in the beginning of `config.py`, it says 
```
This file specifies default config options for Fast R-CNN. You should not
change values in this file. Instead, you should write a config file (in yaml)
and use cfg_from_file(yaml_file) to load it and override the default options.
```
shall I change the `cfg_from_file(yaml_file)` to modify the size of input image? does it make any difference?

@naibaf7 
I have changed the parameters which you said, but how about other parameters. I do not know whether I should leave them unchanged or no. Shall I change the others as well? if yes how please?
here is  `Makefile.config` before `USE_CUDNN := 1` which afterwards is the same as caffe version of `pyfaster rcnn `which I am using.

```
# 32 bit / 64 bit indexing
USE_INDEX_64 := 1

# GreenTea (ViennaCL/OpenCL) backend switch
# Enable the CUDA backend
USE_CUDA := 1

# Enable the OpenCL/Greentea backend
USE_GREENTEA := 0

# Enable the Greentea-LibDNN convolution backend
# USE_LIBDNN := 1

# Enable the Intel spatial convolutions
# USE_INTEL_SPATIAL := 1

# Folder of the ViennaCL header-only library
VIENNACL_DIR = ../ViennaCL

# Override BLAS, use CLBlast instead of ViennacLBLAS.
# USE_CLBLAST := 1

# Custom CLBlast lib and include directories.
# CLBLAST_INCLUDE := /path/to/clblast/include
# CLBLAST_LIB     := /path/to/clblast/lib

# Override BLAS, use clBLAS insead of ViennaclBLAS.
# USE_CLBLAS := 1

# Custom clBLAS lib and include directories.
# CLBLAS_INCLUDE := /path/to/clblas/include
# CLBLAS_LIB     := /path/to/clblas/lib

# Override BLAS, use ISAAC instead of ViennaclBLAS.
# USE_ISAAC := 1

# Uncomment for FFT
# USE_FFT := 1
```
@naibaf7 
I did what you said, but I am getting the following error:
```
AR -o .build_release/lib/libcaffe.a
LD -o .build_release/lib/libcaffe.so.1.0.0-rc3
CXX examples/cpp_classification/classification.cpp
CXX/LD -o .build_release/tools/caffe.bin
CXX/LD -o .build_release/tools/compute_image_mean.bin
CXX/LD -o .build_release/tools/convert_imageset.bin
CXX/LD -o .build_release/tools/device_query.bin
CXX/LD -o .build_release/tools/extract_features.bin
CXX/LD -o .build_release/tools/finetune_net.bin
CXX/LD -o .build_release/tools/net_speed_benchmark.bin
CXX/LD -o .build_release/tools/test_net.bin
CXX/LD -o .build_release/tools/train_net.bin
CXX/LD -o .build_release/tools/upgrade_net_proto_binary.bin
CXX/LD -o .build_release/tools/upgrade_net_proto_text.bin
CXX/LD -o .build_release/tools/upgrade_solver_proto_text.bin
CXX/LD -o .build_release/examples/cifar10/convert_cifar_data.bin
CXX/LD -o .build_release/examples/siamese/convert_mnist_siamese_data.bin
CXX/LD -o .build_release/examples/mnist/convert_mnist_data.bin
examples/cpp_classification/classification.cpp: In function 'std::vector<int> Argmax(const std::vector<float>&, int64_t)':
examples/cpp_classification/classification.cpp:124:10: error: could not convert 'result' from 'std::vector<long int>' to 'std::vector<int>'
   return result;
          ^
examples/cpp_classification/classification.cpp: In member function 'std::vector<std::pair<std::basic_string<char>, float> > Classifier::Classify(const cv::Mat&, int64_t)':
examples/cpp_classification/classification.cpp:132:46: error: conversion from 'std::vector<int>' to non-scalar type 'std::vector<long int>' requested
   std::vector<int_tp> maxN = Argmax(output, N);
                                              ^
make: *** [.build_release/examples/cpp_classification/classification.o] Error 1
```

**Comment by naibaf7** [comment]
@smajida 
The other options should be fine.
Okay, that's only the classification binary having an issue, I'll fix that quickly.

**Comment by smajida** [comment]
@naibaf7 
Thanks for your help. I tried the update version and made sure that your recent commits are included in the downloaded file. Unfortunately, I am still getting the same error:
```
examples/cpp_classification/classification.cpp: In function 'std::vector<int> Argmax(const std::vector<float>&, int64_t)':
examples/cpp_classification/classification.cpp:124:10: error: could not convert 'result' from 'std::vector<long int>' to 'std::vector<int>'
   return result;
          ^
examples/cpp_classification/classification.cpp: In member function 'std::vector<std::pair<std::basic_string<char>, float> > Classifier::Classify(const cv::Mat&, int64_t)':
examples/cpp_classification/classification.cpp:132:46: error: conversion from 'std::vector<int>' to non-scalar type 'std::vector<long int>' requested
   std::vector<int_tp> maxN = Argmax(output, N);
make: *** [.build_release/examples/cpp_classification/classification.o] Error 1
```

Just to mention, I got some warning previously as well which I had not mentioned:
```
./include/caffe/layers/recurrent_layer.hpp(57): warning: function "caffe::Layer<Dtype>::AllowForceBackward(int64_t) const [with Dtype=double]" is hidden by "caffe::RecurrentLayer<Dtype>::AllowForceBackward [with Dtype=double]" -- virtual function override intended?
          detected during instantiation of class "caffe::RecurrentLayer<Dtype> [with Dtype=double]" 
src/caffe/layers/recurrent_layer.cu(57): here
```
BTW, I am using Linux Ubuntu 16.04 x64 LTS server version with CUDA 7.5 and Nvidia Titan X (not with Pascal Architecture).

I hope this information would help to fix the problem.

**Comment by jiayi-wei** [comment]
@smajida Hi~ Have you solved your problem? I'm trying to package my Faste-RCNN project to  C++. Undoudtedly, I can train or test my net in python. It runs well. In C++. however, i met a error like this
`F0511 10:25:19.911154  8752 blob.cpp:33] Check failed: shape[i] <= 2147483647 / count_ (3200 vs. 1553) blob size exceeds INT_MAX`
The size of my image is 1600*1200.
Thanks very much for any help！

**Comment by enduringstack** [comment]
@jiayi-wei  Have you solved your problem? I hava the same problem as you.

**Comment by naibaf7** [comment]
@jiayi-wei If your image is of size 3 (RGB) * 1600 * 1200 then this is obviously too large for standard Caffe, as this exceeds the limit for integers. If you can run it in python, it will likely just cut off the data on what's above the allowed size, because Caffe internally does not handle more data / higher indices.

Note that the OpenCL Caffe version, which also has CUDA, supports the compile option "USE_INDEX_64", in which case the limit will not be on 32bit integers for blob sizes, but 64bit integers. Note however, that the OpenCL or CUDA implementation of your device (BLAS, or otherwise) might still not support such large indices, in which case it will compile and run, but can give faulty results!

**Comment by huangbo1221** [comment]
I have solved this problem,and just revised something in caffe.  Firstly locate caffe-master/src/caffe/blob.cpp. Secondly, delete two lines of code:
CHECK_GE(shape[i], 0);
CHECK_LE(shape[i], INT_MAX / count_) << "blob size exceeds INT_MAX";
Lastly,recompile caffe!

**Comment by zchrissirhcz** [comment]
@huangbo1221 By deleting those two lines, the `shape[i]` is with garbage value, and will bring faulty result. Don't do that.

**Comment by naibaf7** [comment]
@huangbo1221 
You absolutely cannot do that. It will result in index overflows, wrong computations, crashes etc.
