### ISSUE TITLE
Unbuntu15.04 installation error. /usr/bin/ld: /usr/local/lib/libhdf5.a(H5.c.o): relocation R_X86_64_32 against `H5_debug_g'

### ISSUE THREAD

**Issue by rockstone533** [BVLC/caffe#3085]
I tried to install caffe under Unbuntu15.04,and got an error below.Anyone could help me?
CXX examples/cpp_classification/classification.cpp
AR -o .build_debug/lib/libcaffe.a
LD -o .build_debug/lib/libcaffe.so
/usr/bin/ld: /usr/local/lib/libhdf5.a(H5.c.o): relocation R_X86_64_32 against `H5_debug_g' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libhdf5.a: error adding symbols: 错误的值
collect2: error: ld returned 1 exit status
Makefile:510: recipe for target '.build_debug/lib/libcaffe.so' failed
make: *** [.build_debug/lib/libcaffe.so] Error 1

**Comment by SerhanGul** [comment]
You should probably recompile libhdf enabling shared and with -fPIC flag. I had the same issue and the same erorr message with ffmpeg and had to recompile all the dependent libraries with --enable-shared. There must be a similar problem here.

**Comment by longjon** [comment]
Closing as this looks like an installation issue.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
