### ISSUE TITLE
pycaffe incorrect classification comparing to DIGITS

### ISSUE THREAD

**Issue by johnkorn** [BVLC/caffe#3087]
I've trained CNN to classify characters of English alphabet. But during tests I noticed that for some images classification results via DIGITS GUI and via python interface differ.

E.g. below is classification result for sample image in DIGITS:
![class](https://cloud.githubusercontent.com/assets/6063097/9965880/a6ab003e-5e39-11e5-9e41-94a56c3854c3.png)
Index ```29``` means character ```d```.

Here is python output when classifying the same image:
```FAIL! 18092015170911-613-d.png - expected: 'd', predicted: 'b'; prob: 0.50```

I suppose the issue may be in preprocessing. Below is the code I use to process the image:
```python
    net = caffe.Classifier(MODEL_FILE, PRETRAINED)    
    img = caffe.io.load_image(path+file, color=False)

    grayimg = 255*img[:,:,0]
    
    gi = np.reshape(grayimg, (32,32,1))
    
    prediction = net.predict([gi]) 
```

I use binary images, so all pixels are either ```0``` or ```255```.
I did not use mean image while training (```Subtract Mean File``` was set to ```No```)
When I tried to set ```mean``` file to classifier:
```python
blob = caffe.proto.caffe_pb2.BlobProto()
data = open(MEAN_FILE, 'rb' ).read()
blob.ParseFromString(data)
arr = np.array( caffe.io.blobproto_to_array(blob) )

net = caffe.Classifier(MODEL_FILE, PRETRAINED, mean=arr[0])
```
classification result was even worse.
What could cause such mistakes?

**Comment by johnkorn** [comment]
I'm sorry, I probably should submit this issue to NVIDIA\DIGITS project.

**Comment by lukeyeager** [comment]
*(resolved at https://github.com/NVIDIA/DIGITS/issues/320)*
