### ISSUE TITLE
Caffe Makefile Command line tools version 7

### ISSUE THREAD

**Issue by christopher5106** [BVLC/caffe#3092]
On MacOS 10.10.3 

I had to change 6 for 7 in : 

               # 10.10 has accelerate while 10.9 has veclib
                XCODE_CLT_VER := $(shell pkgutil --pkg-info=com.apple.pkg.CLTools_Executables | grep -o 'version: 7')
                ifneq (,$(findstring version: 7,$(XCODE_CLT_VER)))
                        BLAS_INCLUDE ?= /System/Library/Frameworks/Accelerate.framework/Versions/Current/Frameworks/vecLib.framework/Headers/
                        LDFLAGS += -framework Accelerate
                else
                        BLAS_INCLUDE ?= /System/Library/Frameworks/vecLib.framework/Versions/Current/Headers/
                        LDFLAGS += -framework vecLib
                endif

since pkgutil --pkg-info=com.apple.pkg.CLTools_Executables was giving : 

package-id: com.apple.pkg.CLTools_Executables
version: 7.0.0.0.1.1441394355
volume: /
location: /
install-time: 1442705061
groups: com.apple.FindSystemFiles.pkg-group com.apple.DevToolsBoth.pkg-group com.apple.DevToolsNonRelocatableShared.pkg-group

**Comment by shelhamer** [comment]
Thanks for reporting -- see #3093.

**Comment by guiquanz** [comment]
It does not work for me, but a have Xcode 7.1.1 installed (under OS X EI C 10.11.1).

**Comment by guiquanz** [comment]
For me, it works while use `pkgutil --pkg-info=com.apple.pkg.Xcode`

➜  caffe git:(master) ✗ pkgutil --pkg-info=com.apple.pkg.CLTools_Executables
No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

➜  caffe git:(master) ✗ pkgutil --pkgs='com.apple.pkg.Xcode.*'
com.apple.pkg.Xcode
com.apple.pkg.XcodeMAS_iOSSDK_8_1

➜  caffe git:(master) ✗ pkgutil --pkg-info=com.apple.pkg.Xcode
package-id: com.apple.pkg.Xcode
version: 7.1.1.0.1.1446150073
volume: /
location: /
install-time: 1447247573
