### ISSUE TITLE
Does Caffe supports Locally weight-sharing in ConvolutionLayer?

### ISSUE THREAD

**Issue by nrailgun** [BVLC/caffe#3094]
In each feature map of convolution layer, a kernel is shared. How can I use 4 kernels in 4 corners of a image, like this [paper](http://ieeexplore.ieee.org/xpls/abs_all.jsp?arnumber=6619290&tag=1)?

Thanks!

**Comment by longjon** [comment]
Closing as this looks like a request for help.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
