### ISSUE TITLE
How to use trained autoencoder model?

### ISSUE THREAD

**Issue by kingofoz** [BVLC/caffe#3098]
Hi buddy,
I am training an MNIST autoencoder model, may I ask how to use the tained model for a real task?

Thanks.

**Comment by seanbell** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
