### ISSUE TITLE
undefined function 'caffe_' for input arguments of type 'char'

### ISSUE THREAD

**Issue by wewant** [BVLC/caffe#3105]
Hi,
When I use Matlab to classify pictures using a model I trained previously, I meet a problem.
I get the following error:

Undefined function 'caffe_' for input arguments of type 'char'.

Error in caffe.get_net (line 27)
hNet = caffe_('get_net', model_file, phase_name);

Error in caffe.Net (line 31)
        self = caffe.get_net(varargin{:});

Error in classification_demo (line 84)
net = caffe.Net(net_model, net_weights, phase);

Any suggestions gratefully received

Thanks

**Comment by ronghanghu** [comment]
This doesn't look like a bug. Make sure you have correctly compiled matlab wrapper according to http://caffe.berkeleyvision.org/tutorial/interfaces.html#matlab
and you have compiled mex file `caffe_.mexa64` (extension may vary on your platform)
in caffe/matlab/+caffe/private/

Please do not post usage, installation, or modeling questions, or other requests for help to Issues.
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
