### ISSUE TITLE
blocking_queue.cpp:50 Data layer prefetch queue empty

### ISSUE THREAD

**Issue by xiaomr** [BVLC/caffe#3107]
I hope to finetune the caffenet with my own data , of 2 category, I had chage the fc8 to fc8-new and change the output num to 2 in fc8-new, and configure the solver.prototxt,  however, when the finetune is ongoing , the logs report that: blocking_queue.cpp:50 Data layer prefetch queue empty, and this log seems is very slow to move on. what does this log mean? and is it the cause that the loss can't convergence?

**Comment by shinysup** [comment]
I'm having the same issue, and in my case, it's giving loss=0 from the very beginning, implying the data were not loaded properly.. can't find out why

**Comment by xiaomr** [comment]
So can you get the right result ( accuracy and loss) while finetune ,  in my result it seems only slow down the test process.

**Comment by longjon** [comment]
Closing as this looks like a usage question/request for help.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

**Comment by zhangxiaodu** [comment]
I met the same problem. And have you solved it?
