### ISSUE TITLE
Data accessing based on key value from Caffe::DB

### ISSUE THREAD

**Issue by iqbalu** [BVLC/caffe#3110]
Hello everyone,

I have saved some features in Caffe::DB (database type does not matter) for a number of images, and features for each image are saved with a different key. While retrieving the features from database, I am able to get the data sequentially, but I was wondering if there is a method to randomly access the data corresponding to a specific key. I looked in to the source code for Caffe::DB and Caffe::DB::Cursor, but couldn't find any method for random access of database entries. The cursor can only be placed either to the first entry of database, or to the next. Should not there be a method where one can access database entries with any key??

Thanks!

**Comment by longjon** [comment]
Closing as this looks like a request for help. (Though note that while key-based access is something you'll find discussed elsewhere on the GitHub, that sort of thing is generally done externally or through a Python layer.)

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
