### ISSUE TITLE
Multi-label classification

### ISSUE THREAD

**Issue by hemanth2090** [BVLC/caffe#3111]
Hi, 

  I am new to caffe. I am trying to achieve multi-label classification of images into 14 classes on caffe. I saw this link on GitHub https://github.com/BVLC/caffe/pull/523 and it directed me to this code https://github.com/BVLC/caffe/tree/50a6ff0cc3a8525f310066c777fd6c4c9d8aa694. When I tried to build the code, I got error of missing cublas_v2.h. I resolved this and got an error of cublas_api.h. I realised that the master has many many more commits and hence, I am getting merge conflicts.

  Then after searching a bit more, I saw this link https://groups.google.com/forum/#!searchin/caffe-users/james$20guo/caffe-users/_NdX1tpHt5Y/4A7ln18nr3YJ. I also looked at the siamese example on caffe. I was unsure of how to save the image in HDF5 format and also how to generate the necessary listfile of all the labels. Is there a a version of the master commit that can be used? The master versions on GitHub are all giving build errors. Can someone please help me?

**Comment by seanbell** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
_Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

**Comment by hemanth2090** [comment]
Hi,

  I did post on the google group as well. https://groups.google.com/forum/#!msg/caffe-users/lUYi4fbFVok/tsuchHQAAQAJ
