### ISSUE TITLE
forward and backward using C++ API

### ISSUE THREAD

**Issue by mczmy** [BVLC/caffe#3113]
I'm using a CNN without fixed data layer and loss layer. Here is an overview of what I did or will do:
(1) Form image batch dynamically, and replace previous data layer with current image batch.
(2) Call net->ForwardPrefilled() to forward current input images through the network, extract features given layer names.
(3) Insert diffs to the layer layer.
(4) Call net->Update() to update weights of all layers.

I finished step 1 and 2. But I have problem of step 3. Here is my question:
(1) Should I change last layer's top->mutable_cpu_diff() to insert diffs? 
(2) And how to make copies from cpu_diff to gpu_diff? 
(3) What's more, is it correct that once I finished step 3, I can call Update() directly to update weights of all layers?

**Comment by ronghanghu** [comment]
Please do not post usage, installation, or modeling questions, or other requests for help to Issues.
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

**Comment by mczmy** [comment]
Sorry. 


     On Thursday, September 24, 2015 2:44 PM, Ronghang Hu <notifications@github.com> wrote:
   

 Closed #3113.—
