### ISSUE TITLE
Setting caffe blob data at particular index manually?

### ISSUE THREAD

**Issue by n3011** [BVLC/caffe#3117]
float weight_data = 0.02199;
float* weightdata = &weight_data;
int offset = caffe_weight.offset(r, c, h, w);
caffe_weight.set_cpu_data(weightdata + offset);
 

When i try to access the value at caffe_weight.data_at(r, c, h, w) it returns me some random very high values. Please help me out here.

**Comment by seanbell** [comment]
You may want to look up some C++ tutorials on how pointers work.  `weightdata + offset` will be a pointer to somewhere in the middle of the local stack.

Assuming that `caffe_weight` is a blob, you can get a pointer into the raw data with `caffe_weight.mutable_cpu_data()`, and then you can write into that chunk of memory at the appropriate offset.

Also, from https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
