### ISSUE TITLE
Issue of running web_demo on AWS g2.2xlarge and g2.8xlarge instances

### ISSUE THREAD

**Issue by trenddev** [BVLC/caffe#3122]
I have followed the installation tutorial to setup caffe environment on AWS. I noticed that it's not stable to run caffe examples on AWS. For instance,  running web_demo will cause CPU reach 100% and it's impossible to kill the process. I am wondering if anyone had similar experience and how to fix the issue.

```
ubuntu@ip-10-71-126-6:~/caffe$ python examples/web_demo/app.py -p 5000 -g
libdc1394 error: Failed to initialize libdc1394

ubuntu@ip-10-71-126-6:~/top
345 root      20   0       0      0      0 R 100.0  0.0   9:17.24 ksoftirqd/16                                                                                                   
3 root      20   0       0      0      0 R  65.0  0.0   5:56.12 ksoftirqd/0 
```

**Comment by barbolo** [comment]
Having the same problems with IRQ.

**Comment by eerwitt** [comment]
I had this issue when Caffe wasn't running using the GPU. After using [this AMI](http://blog.titocosta.com/post/110345699197/public-ec2-ami-with-torch-and-caffe-deep-learning) I stopped seeing a pegged CPU.

**Comment by shelhamer** [comment]
Closing as an AMI issue and not a Caffe issue.
