### ISSUE TITLE
“ImportError: cannot import name layers” in caffe / pycaffe

### ISSUE THREAD

**Issue by mgarbade** [BVLC/caffe#3124]
I'm following the ipython notebook example "Learning LeNet" on training a caffe network via its python interface. However the caffe module seems not to contain the modules described in the tutorial

When I enter

    import caffe
    from caffe import layers as L
I get the error:

    ImportError   Traceback (most recent call last)
    <ipython-input-5-7cbb5661b7a7> in <module>()
    ----> 1 from caffe import layers as L
    
    ImportError: cannot import name layers
when I do dir(caffe) I get:

    ['Classifier',
     'Detector',
     'Layer',
     'Net',
     'SGDSolver',
     'TEST',
     'TRAIN',
     '__builtins__',
     '__doc__',
     '__file__',
     '__name__',
     '__package__',
     '__path__',
     '_caffe',
     'classifier',
     'detector',
     'get_solver',
     'io',
     'proto',
     'pycaffe',
     'set_device',
     'set_mode_cpu',
     'set_mode_gpu']
so it doesn't contain a module called "layers".

I also downloaded the newest version of caffe but the problem remains.

Is the tutorial somehow outdated? 
Is there a newer version of the tutorial which works for my version of caffe?

**Comment by longjon** [comment]
Closing as this does not look like a bug; the latest version of the `caffe` module does indeed contain `layers`, so it's the module being used here that must be out-of-date (are you sure you're importing the right version? have you rebuilt it?).

**Comment by fanser** [comment]
I get the same error.so how did you deal with it?

**Comment by mgarbade** [comment]
The solution given above is correct. I just rebuild the most recent caffe version (not any side branch)! Now I can import `layers`. Make sure your PYTHONPATH is pointing to the correct directory by typing 

    echo $PYTHONPATH

    and inside python you can check if caffe is imported from the right directory by typing:

    import caffe
    print caffe.__file__

**Comment by fanser** [comment]
thanks for your suggestion.
I accept your suggestion and type echo $PYTHONPATH,but i get the error
>>> echo $PYTHONPATH
  File "<stdin>", line 1
    echo $PYTHONPATH
         ^
SyntaxError: invalid syntax
i don't know why ,and i ignore it 
then run the nex two lines:import caffe   print caffe.__file__
i get :
>>> runfile('/home/fzy/caffe-master/1.py', wdir=r'/home/fzy/caffe-master')
/home/fzy/caffe-master/python/caffe/__init__.pyc
>>> 
so,does it mean that i have imported caffe successfully? but  i can't import layers.
and how did you rebuild the most recent caffe version?
Just 'make' the new caffe version?
make clean
make 
make pycaffe
 Is that right?

**Comment by fanser** [comment]
perfeect! I rebuild caffe,and this time i succeed in importting layers! thanks a lot.
but i also have a question,why can't the older version  support to import layers?did you have any thinks abou it?

**Comment by mgarbade** [comment]
No idea, sorry
