### ISSUE TITLE
a problem with make all (caffe-master/tools/convert_imageset.cpp)

### ISSUE THREAD

**Issue by henryham** [BVLC/caffe#3125]
here is the whole errors, anyone can help me? Thanks a lot.

henry@henry:~/Desktop/caffe/caffe-master$ make all -j8
PROTOC src/caffe/proto/caffe.proto
CXX src/caffe/syncedmem.cpp
CXX src/caffe/internal_thread.cpp
CXX src/caffe/blob.cpp
CXX src/caffe/parallel.cpp
CXX src/caffe/layer.cpp
CXX src/caffe/data_transformer.cpp
CXX src/caffe/data_reader.cpp
CXX src/caffe/solver.cpp
CXX src/caffe/layers/concat_layer.cpp
CXX src/caffe/layers/euclidean_loss_layer.cpp
CXX src/caffe/layers/cudnn_sigmoid_layer.cpp
CXX src/caffe/layers/tanh_layer.cpp
CXX src/caffe/layers/slice_layer.cpp
CXX src/caffe/layers/accuracy_layer.cpp
CXX src/caffe/layers/hinge_loss_layer.cpp
CXX src/caffe/layers/bnll_layer.cpp
CXX src/caffe/layers/tile_layer.cpp
CXX src/caffe/layers/hdf5_data_layer.cpp
CXX src/caffe/layers/absval_layer.cpp
CXX src/caffe/layers/deconv_layer.cpp
CXX src/caffe/layers/window_data_layer.cpp
CXX src/caffe/layers/mvn_layer.cpp
CXX src/caffe/layers/neuron_layer.cpp
CXX src/caffe/layers/memory_data_layer.cpp
CXX src/caffe/layers/cudnn_pooling_layer.cpp
CXX src/caffe/layers/dropout_layer.cpp
CXX src/caffe/layers/lrn_layer.cpp
CXX src/caffe/layers/infogain_loss_layer.cpp
CXX src/caffe/layers/reshape_layer.cpp
CXX src/caffe/layers/hdf5_output_layer.cpp
CXX src/caffe/layers/filter_layer.cpp
CXX src/caffe/layers/power_layer.cpp
CXX src/caffe/layers/base_data_layer.cpp
CXX src/caffe/layers/cudnn_relu_layer.cpp
CXX src/caffe/layers/image_data_layer.cpp
CXX src/caffe/layers/prelu_layer.cpp
CXX src/caffe/layers/cudnn_tanh_layer.cpp
CXX src/caffe/layers/multinomial_logistic_loss_layer.cpp
CXX src/caffe/layers/embed_layer.cpp
CXX src/caffe/layers/sigmoid_cross_entropy_loss_layer.cpp
CXX src/caffe/layers/cudnn_conv_layer.cpp
CXX src/caffe/layers/argmax_layer.cpp
CXX src/caffe/layers/relu_layer.cpp
CXX src/caffe/layers/conv_layer.cpp
CXX src/caffe/layers/threshold_layer.cpp
CXX src/caffe/layers/cudnn_softmax_layer.cpp
CXX src/caffe/layers/spp_layer.cpp
CXX src/caffe/layers/softmax_loss_layer.cpp
CXX src/caffe/layers/exp_layer.cpp
CXX src/caffe/layers/data_layer.cpp
CXX src/caffe/layers/sigmoid_layer.cpp
CXX src/caffe/layers/reduction_layer.cpp
CXX src/caffe/layers/silence_layer.cpp
CXX src/caffe/layers/base_conv_layer.cpp
CXX src/caffe/layers/log_layer.cpp
CXX src/caffe/layers/loss_layer.cpp
CXX src/caffe/layers/dummy_data_layer.cpp
CXX src/caffe/layers/pooling_layer.cpp
CXX src/caffe/layers/im2col_layer.cpp
CXX src/caffe/layers/split_layer.cpp
CXX src/caffe/layers/contrastive_loss_layer.cpp
CXX src/caffe/layers/flatten_layer.cpp
CXX src/caffe/layers/softmax_layer.cpp
CXX src/caffe/layers/inner_product_layer.cpp
CXX src/caffe/layers/eltwise_layer.cpp
CXX src/caffe/layer_factory.cpp
CXX src/caffe/common.cpp
CXX src/caffe/util/math_functions.cpp
CXX src/caffe/util/blocking_queue.cpp
CXX src/caffe/util/im2col.cpp
CXX src/caffe/util/hdf5.cpp
CXX src/caffe/util/io.cpp
CXX src/caffe/util/db.cpp
CXX src/caffe/util/benchmark.cpp
CXX src/caffe/util/db_leveldb.cpp
CXX src/caffe/util/upgrade_proto.cpp
CXX src/caffe/util/signal_handler.cpp
CXX src/caffe/util/cudnn.cpp
CXX src/caffe/util/insert_splits.cpp
CXX src/caffe/util/db_lmdb.cpp
CXX src/caffe/net.cpp
CXX tools/upgrade_net_proto_binary.cpp
CXX tools/caffe.cpp
CXX tools/train_net.cpp
CXX tools/device_query.cpp
CXX tools/extract_features.cpp
CXX tools/test_net.cpp
CXX tools/convert_imageset.cpp
CXX tools/finetune_net.cpp
CXX tools/upgrade_net_proto_text.cpp
CXX tools/net_speed_benchmark.cpp
CXX tools/compute_image_mean.cpp
CXX examples/mnist/convert_mnist_data.cpp
CXX examples/cpp_classification/classification.cpp
CXX examples/siamese/convert_mnist_siamese_data.cpp
CXX examples/cifar10/convert_cifar_data.cpp
CXX .build_debug/src/caffe/proto/caffe.pb.cc
AR -o .build_debug/lib/libcaffe.a
LD -o .build_debug/lib/libcaffe.so
CXX/LD -o .build_debug/tools/upgrade_net_proto_binary.bin
CXX/LD -o .build_debug/tools/caffe.bin
CXX/LD -o .build_debug/tools/train_net.bin
CXX/LD -o .build_debug/tools/device_query.bin
CXX/LD -o .build_debug/tools/extract_features.bin
CXX/LD -o .build_debug/tools/test_net.bin
CXX/LD -o .build_debug/tools/convert_imageset.bin
CXX/LD -o .build_debug/tools/finetune_net.bin
CXX/LD -o .build_debug/tools/upgrade_net_proto_text.bin
CXX/LD -o .build_debug/tools/net_speed_benchmark.bin
CXX/LD -o .build_debug/tools/compute_image_mean.bin
CXX/LD -o .build_debug/examples/mnist/convert_mnist_data.bin
CXX/LD -o .build_debug/examples/cpp_classification/classification.bin
CXX/LD -o .build_debug/examples/siamese/convert_mnist_siamese_data.bin
.build_debug/tools/convert_imageset.o: In function `main':
/home/henry/Desktop/caffe/caffe-master/tools/convert_imageset.cpp:120: undefined reference to `caffe::ReadImageToDatum(std::string const&, int, int, int, bool, std::string const&, caffe::Datum*)'
collect2: error: ld returned 1 exit status
make: *** [.build_debug/tools/convert_imageset.bin] Error 1
make: *** Waiting for unfinished jobs....
.build_debug/tools/compute_image_mean.o: In function `main':
/home/henry/Desktop/caffe/caffe-master/tools/compute_image_mean.cpp:53: undefined reference to `caffe::DecodeDatumNative(caffe::Datum*)'
/home/henry/Desktop/caffe/caffe-master/tools/compute_image_mean.cpp:71: undefined reference to `caffe::DecodeDatumNative(caffe::Datum*)'
collect2: error: ld returned 1 exit status
make: *** [.build_debug/tools/compute_image_mean.bin] Error 1

**Comment by longjon** [comment]
Closing as this looks like a usage issue/request for help.

This tracker is reserved for specific Caffe development issues and bugs; please ask usage questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) list.

For more information, see our [contributing guide](https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md).

Thanks!

**Comment by ouxinyu** [comment]
@henryham excuse me, I get the same error of "make: *** .build_debug/tools/compute_image_mean.bin] Error 1".
How do you solve it ?thank you
