### ISSUE TITLE
Transformer from io.py does not handle transposition correctly

### ISSUE THREAD

**Issue by Shadfield** [BVLC/caffe#3126]
The python Transformer object has the option to apply different transpositions to the dimensions of the input data such as [2, 0, 1] to go from H x W x C images to C x H x W.

This functionality is nice but doesn't seem to actually work. Specifically on line 145 of io.py

``` python
        in_dims = self.inputs[in_][2:]
        if caffe_in.shape[:2] != in_dims:
            caffe_in = resize_image(caffe_in, in_dims)
```

Which assumes dimensions 0 and 1 are height and width, ignoring whether transposition is about to happen on the next line.

This would probably be fixed just by doing the transposition before the resizing.

**Comment by shaibagon** [comment]
`io.py` has been changed since this issue was raised.
