### ISSUE TITLE
Does caffe support Nd Convolution?

### ISSUE THREAD

**Issue by rockstone533** [BVLC/caffe#3129]
I tried 3d convolution referring to #2049, and got an error 
F0625 16:20:14.583122  4782 blob.hpp:141] Check failed: num_axes() <= 4 (5 vs. 4) Cannot use legacy accessors on Blobs with > 4 axes.

As @Tgaaly said, I uncomment a sentence "CHECK_LE(num_axes(), 4)<< "Cannot use legacy accessors on Blobs with > 4 axes.";", and the program seems to run.

Will things go right?

**Comment by futurely** [comment]
https://github.com/BVLC/caffe/pull/3983
