### ISSUE TITLE
Matlab interface link problem

### ISSUE THREAD

**Issue by kevindehecker** [BVLC/caffe#313]
When running "make matcaffe" I get a lot of linker errors (see below). It is as if the CXXLIBS arguments are ignored. Caffe itself compiles fine, as well as the Python interface. I'm running the Dev branch, Matlab 2014a and Ubuntu 12.04 (all 64 bit)

I had to make a change to the Makefile as the mex compilers compalns it does not know the -o flag. I changed it to -output

Output:

<blockquote>
$ make matcaffe
/usr/local/MATLAB/R2014a/bin/mex matlab/caffe/matcaffe.cpp build/lib/libcaffe.a \
            CXXFLAGS="\$CXXFLAGS -pthread -fPIC -DNDEBUG -O2 -I/usr/include/python2.7 -I/usr/local/lib/python2.7/dist-packages/numpy/core/include -I/usr/local/include -Ibuild/src -I./src -I./include -I/usr/local/cuda/include -Wall" \
            CXXLIBS="\$CXXLIBS -L/usr/local/lib -L/usr/lib -L/usr/local/lib -L/usr/local/cuda/lib64 -L/usr/local/cuda/lib -lcudart -lcublas -lcurand -lpthread -lglog -lprotobuf -lleveldb -lsnappy -lboost_system -lhdf5_hl -lhdf5 -lopencv_core -lopencv_highgui -lopencv_imgproc -lcblas -latlas" -output matlab/caffe/caffe.mexa64
Building with 'g++'.
build/lib/libcaffe.a(common.o): In function `caffe::Caffe::Caffe()':
common.cpp:(.text+0xa6): undefined reference to `cublasCreate_v2'
common.cpp:(.text+0xfb): undefined reference to `curandCreateGenerator'
common.cpp:(.text+0x15d): undefined reference to `curandSetPseudoRandomGeneratorSeed'
</blockquote>

.
... snap ...
.

<blockquote>
build/lib/libcaffe.a(math_functions.o): In function `void caffe::caffe_cpu_axpby<double>(int, double, double const*, double, double*)':
math_functions.cpp:(.text+0x475): undefined reference to `cblas_daxpy'
build/lib/libcaffe.a(math_functions.o): In function `float caffe::caffe
make: *** [matlab/caffe/caffe.mexa64] Error 255
</blockquote>

**Comment by scotthoule** [comment]
I had the same problem. The problem was solved using exactly the same edit!
