### ISSUE TITLE
Repeated python crashes can produce GPU Out-Of-Memory Error

### ISSUE THREAD

**Issue by eriophora** [BVLC/caffe#3136]
If Python exits improperly during execution of script that creates a GPU convnet, this can produce an out-of-memory error on the GPU. It appears that the memory is orphaned on the GPU when pycaffe exits unexpectedly. If python exits improperly enough times, this will produce the error (I encountered it when trying to debug a multi-process python script). Is this a known issue with a workaround?

**Comment by longjon** [comment]
I've never seen memory left inaccessible on GPU after process exit, and if I did I would consider that a CUDA bug.

What I suspect is happening (which I have seen) is that orphaned _processes_ are holding onto GPU memory, which is not too hard to achieve with `multiprocessing`.

I'm closing as there's no way I can interpret this as a possible Caffe bug, but you're welcome to open a new issue if you do think `pycaffe` is behaving inappropriately in some more specific way.
