### ISSUE TITLE
Caffe  Example - detection.ipynb 

### ISSUE THREAD

**Issue by yawadugyamfi** [BVLC/caffe#3137]
I have been working with this example:
http://nbviewer.ipython.org/github/BVLC/caffe/blob/master/examples/detection.ipynb

When I run the command below, it takes roughly between 300 and 800 seconds per image. Is there a much faster implementation of this example?  Fast as in, one that can be used to process videos 

!../python/detect.py --crop_mode=selective_search --pretrained_model=../models/bvlc_reference_rcnn_ilsvrc13/bvlc_reference_rcnn_ilsvrc13.caffemodel --model_def=../models/bvlc_reference_rcnn_ilsvrc13/deploy.prototxt --gpu --raw_scale=255 _temp/det_input.txt _temp/det_output.h5

**Comment by seanbell** [comment]
If you want to get to video rates, the method method you liked will never scale to that speed.  You'll need to use another approach, such as Fast R-CNN (https://github.com/rbgirshick/fast-rcnn), or Faster R-CNN (http://arxiv.org/pdf/1506.01497v2.pdf).

**Comment by longjon** [comment]
Closing as this looks like a request for help.

This tracker is reserved for specific Caffe development issues and bugs; please ask usage questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) list.

For more information, see our [contributing guide](https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md).

Thanks!
