### ISSUE TITLE
src/caffe/data_transformer.cpp:229: error: invalid use of incomplete type ‘const struct cv::Mat’

### ISSUE THREAD

**Issue by ilyy510** [BVLC/caffe#3142]

**Comment by longjon** [comment]
Closing as this is not a coherent report of an issue. If you think there is a bug in `master` Caffe, you're welcome to open a new issue explaining how to reproduce it. See our [contributing guide](https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md).

Thanks!
