### ISSUE TITLE
Matcaffe issue of reading .jpg files

### ISSUE THREAD

**Issue by alanwsx** [BVLC/caffe#3143]
When I read certain JPG files in Matcaffe, it will say "io.cpp 77 :cannot open or find file XXX.jpg". However, everything goes well in bash mode and in caffe.io.load_image('XXX.jpg'). I tried to convert JPG into BMP and this bug never comes up again.

**Comment by ronghanghu** [comment]
This seems like some issues with your JPEG files. Caffe's io.cpp uses OpenCV as image backend while caffe.io.load_image uses Matlab's image toolbox, so perhaps the latter can handle the issue within your JPEG image files while the former cannot.

**Comment by Almonfrey** [comment]
Hi, I got this same problem when training a network in the MatCaffe. However, when doing the same operation in the Terminal, there was no problem.

When doing this:

solver = caffe.Solver('solver.prototxt');
solver.net.copy_from('model.caffemodel');
solver.solve();

The error was: "window_data_layer.cpp:295] Could not open or find file"

**Comment by Almonfrey** [comment]
I replaced all the JPG images by their BMP versions and the train worked. But, the problem is that BMP images are very large. Maybe someone has a definite solution for this problem... Any suggestions?
