### ISSUE TITLE
ReadTwoImageToDatum -- Could someone proofread my code?

### ISSUE THREAD

**Issue by hyojinie** [BVLC/caffe#3144]
For my research, I wrote a function ReadTwoImageToDatum (in io.cpp/hpp) to load two images in a Datum object for Siamese Network. I assumed two images have the same dimension (c,h,w). 
Do you think following code make sense? 

bool ReadTwoImageToDatum(const string& filename1, const string& filename2, const int label,
    const int height, const int width, const bool is_color,
    const std::string & encoding, Datum* datum) {
  cv::Mat cv_img1 = ReadImageToCVMat(filename1, height, width, is_color);
  cv::Mat cv_img2 = ReadImageToCVMat(filename2, height, width, is_color);
  if (cv_img1.data) {
    if (encoding.size()) {
      if ( (cv_img1.channels() == 3) == is_color && !height && !width &&
          matchExt(filename1, encoding) )
        return ReadTwoFileToDatum(filename1, filename2, label, datum);
      std::vector<uchar> buf1;
      cv::imencode("."+encoding, cv_img1, buf1);
	  std::vector<uchar> buf2;
      cv::imencode("."+encoding, cv_img2, buf2);

	  // append buf1 and buf2
	  buf1.reserve(buf1.size() + buf2.size()); 
	  buf1.insert(buf1.end(), buf2.begin(), buf2.end());

      datum->set_data(std::string(reinterpret_cast<char*>(&buf1[0]),
                      buf1.size());
      datum->set_label(label);
      datum->set_encoded(true);
      return true;
    }
    TwoCVMatToDatum(cv_img1, cv_img2, datum);
    datum->set_label(label);
    return true;
  } else {
    return false;
  }
}

/* ======= TwoCVMatToDatum ======= */

void TwoCVMatToDatum(const cv::Mat& cv_img1, const cv::Mat& cv_img2, Datum* datum) {
  CHECK(cv_img1.depth() == CV_8U) << "Image1 data type must be unsigned byte";
  CHECK(cv_img2.depth() == CV_8U) << "Image2 data type must be unsigned byte";
  datum->set_channels(6); // R G B R G B
  datum->set_height(cv_img1.rows); //256
  datum->set_width(cv_img1.cols); //256
  datum->clear_data();
  datum->clear_float_data();
  datum->set_encoded(false);
  int datum_channels = datum->channels();
  int datum_height = datum->height();
  int datum_width = datum->width();
  int datum_size = datum_channels * datum_height * datum_width;
  std::string buffer(datum_size, ' ');
  for (int h = 0; h < datum_height; ++h) {
    const uchar* ptr1 = cv_img1.ptr<uchar>(h);
	const uchar* ptr2 = cv_img2.ptr<uchar>(h);
    int img_index1 = 0;
	int img_index2 = 0;
    for (int w = 0; w < datum_width; ++w) {
      for (int c = 0; c < 3; ++c) {
        int datum_index = (c * datum_height + h) * datum_width + w;
        buffer[datum_index] = static_cast<char>(ptr1[img_index1++]);
      }

	  for (int c = 3; c < 6; ++c) {
        int datum_index = (c * datum_height + h) * datum_width + w;
        buffer[datum_index] = static_cast<char>(ptr2[img_index2++]);
      }
    }
  }
  datum->set_data(buffer);
}

/* ======= ReadTwoFileToDatum ======= */

bool ReadTwoFileToDatum(const string& filename1, const string& filename2, const int label,
    Datum* datum) {
  std::streampos size1;
  std::streampos size2;

  fstream file1(filename1.c_str(), ios::in|ios::binary|ios::ate);
  fstream file2(filename2.c_str(), ios::in|ios::binary|ios::ate);
  if (file1.is_open() && file2.is_open()) {
    size1 = file1.tellg();
	size2 = file2.tellg();
    std::string buffer(size1+size2, ' ');
    
	file1.seekg(0, ios::beg);
    file1.read(&buffer[0], size1);
    file1.close();
	
	file2.seekg(0, ios::beg);
    file2.read(&buffer[size1], size2);
    file2.close();

    datum->set_data(buffer);
    datum->set_label(label);
    datum->set_encoded(true);
    return true;
  } else {
    return false;
  }
}

**Comment by longjon** [comment]
Closing as this looks like a usage issue/request for help.

This tracker is reserved for specific Caffe development issues and bugs; please ask usage questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) list.

For more information, see our [contributing guide](https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md).

Thanks!

**Comment by hyojinie** [comment]
@longjon Hi I think Caffe does not support input conversion other than the ones in the examples. I wish there was a function that can deal with more general inputs. Making a lmdb/leveldb for image pairs/triplet for Siamese I think should be a common function as many people will use it. In my opinion it will make Caffe more popular as many people are stuck in input conversion and switch to other libraries.
