### ISSUE TITLE
I write a new layer named "my_inner_product_layer.cpp", make all done. but...

### ISSUE THREAD

**Issue by takecareofbigboss** [BVLC/caffe#3145]
I write a new layer named "my_inner_product_layer.cpp", make all done successfully. but when i use this layer to train my model, it failed and said that:

*** Aborted at 1443972908 (unix time) try "date -d @1443972908" if you are using GNU date ***
PC: @     0x7fca83972b30 caffe::Blob<>::Reshape()
*** SIGFPE (@0x7fca83972b30) received by PID 1629 (TID 0x7fca840b3780) from PID 18446744071622306608; stack trace: ***
    @     0x7fca82ac9d40 (unknown)
    @     0x7fca83972b30 caffe::Blob<>::Reshape()
    @     0x7fca839733b4 caffe::Blob<>::Blob()
    @     0x7fca83a378c4 caffe::MyInnerProductLayer<>::LayerSetUp()
    @     0x7fca83931719 caffe::Net<>::Init()
    @     0x7fca83933ed2 caffe::Net<>::Net()
    @     0x7fca8391c025 caffe::Solver<>::InitTrainNet()
    @     0x7fca8391c557 caffe::Solver<>::Init()
    @     0x7fca8391c945 caffe::Solver<>::Solver()
    @           0x40d9c6 caffe::SGDSolver<>::SGDSolver()
    @           0x40dc88 caffe::GetSolver<>()
    @           0x407431 train()
    @           0x405428 main
    @     0x7fca82ab4ec5 (unknown)
    @           0x405802 (unknown)
Floating point exception (core dumped)

real	0m4.095s
user	0m0.195s
sys	0m0.300s

Attachment is the file "my_inner_product_layer.cpp".

**Comment by takecareofbigboss** [comment]
#include <vector>

#include "caffe/blob.hpp"
#include "caffe/common.hpp"
#include "caffe/filler.hpp"
#include "caffe/layer.hpp"
#include "caffe/util/math_functions.hpp"
#include "caffe/vision_layers.hpp"

namespace caffe {

template <typename Dtype>
void MyInnerProductLayer<Dtype>::LayerSetUp(const vector<Blob<Dtype>*>& bottom,
      const vector<Blob<Dtype>*>& top) {
  const int num_output = this->layer_param_.my_inner_product_param().num_output();
  bias_term_ = this->layer_param_.my_inner_product_param().bias_term();
  N_ = num_output;
  const int axis = bottom[0]->CanonicalAxisIndex(
      this->layer_param_.my_inner_product_param().axis());
  // Dimensions starting from "axis" are "flattened" into a single
  // length K_ vector. For example, if bottom[0]'s shape is (N, C, H, W),
  // and axis == 1, N inner products with dimension CHW are performed.
  K_ = bottom[0]->count(axis);
  // Check if we need to set up the weights
  if (this->blobs_.size() > 0) {
    LOG(INFO) << "Skipping parameter initialization";
  } else {
    if (bias_term_) {
      this->blobs_.resize(2);
    } else {
      this->blobs_.resize(1);
    }
    // Intialize the weight
    vector<int> weight_shape(2);
    weight_shape[0] = N_;
    weight_shape[1] = K_;
    this->blobs_[0].reset(new Blob<Dtype>(weight_shape));
    // fill the weights
    shared_ptr<Filler<Dtype> > weight_filler(GetFiller<Dtype>(
        this->layer_param_.my_inner_product_param().weight_filler()));
    weight_filler->Fill(this->blobs_[0].get());
    // If necessary, intiialize and fill the bias term
    if (bias_term_) {
      vector<int> bias_shape(1, N_);
      this->blobs_[1].reset(new Blob<Dtype>(bias_shape));
      shared_ptr<Filler<Dtype> > bias_filler(GetFiller<Dtype>(
          this->layer_param_.my_inner_product_param().bias_filler()));
      bias_filler->Fill(this->blobs_[1].get());
    }
  }  // parameter initialization
  this->param_propagate_down_.resize(this->blobs_.size(), true);
}

template <typename Dtype>
void MyInnerProductLayer<Dtype>::Reshape(const vector<Blob<Dtype>*>& bottom,
      const vector<Blob<Dtype>*>& top) {
  // Figure out the dimensions
  const int axis = bottom[0]->CanonicalAxisIndex(
      this->layer_param_.my_inner_product_param().axis());
  const int new_K = bottom[0]->count(axis);
  CHECK_EQ(K_, new_K)
      << "Input size incompatible with inner product parameters.";
  // The first "axis" dimensions are independent inner products; the total
  // number of these is M_, the product over these dimensions.
  M_ = bottom[0]->count(0, axis);
  // The top shape will be the bottom shape with the flattened axes dropped,
  // and replaced by a single axis with dimension num_output (N_).
  vector<int> top_shape = bottom[0]->shape();
  top_shape.resize(axis + 1);
  top_shape[axis] = N_;
  top[0]->Reshape(top_shape);
  // Set up the bias multiplier
  if (bias_term_) {
    vector<int> bias_shape(1, M_);
    bias_multiplier_.Reshape(bias_shape);
    caffe_set(M_, Dtype(1), bias_multiplier_.mutable_cpu_data());
  }
}

template <typename Dtype>
void MyInnerProductLayer<Dtype>::Forward_cpu(const vector<Blob<Dtype>*>& bottom,
    const vector<Blob<Dtype>*>& top) {
  const Dtype* bottom_data = bottom[0]->cpu_data();
  Dtype* top_data = top[0]->mutable_cpu_data();
  const Dtype* weight = this->blobs_[0]->cpu_data();

    //set the all the value of weights above zero;
//  Dtype* change_weight = this->blobs_[0]->mutable_cpu_data();
//  for(int i = 0; i < K_*N_; ++i) {    
//    if(*change_weight < 0){
//      Dtype tmp(0.0);
//      *change_weight = tmp;
//    }
//    change_weight++;
//  }

  //set the all the value of weights above zero;
  Dtype* change_weight = this->blobs_[0]->mutable_cpu_data();
  for(int i = 0; i < K_*N_; ++i) {    
    change_weight[i] = (change_weight[i]>0)?change_weight[i]:0.0;
  }
  

  caffe_cpu_gemm<Dtype>(CblasNoTrans, CblasTrans, M_, N_, K_, (Dtype)1.,
      bottom_data, weight, (Dtype)0., top_data);

  if (bias_term_) {
    caffe_cpu_gemm<Dtype>(CblasNoTrans, CblasNoTrans, M_, N_, 1, (Dtype)1.,
        bias_multiplier_.cpu_data(),
        this->blobs_[1]->cpu_data(), (Dtype)1., top_data);
  }
}

template <typename Dtype>
void MyInnerProductLayer<Dtype>::Backward_cpu(const vector<Blob<Dtype>*>& top,
    const vector<bool>& propagate_down,
    const vector<Blob<Dtype>*>& bottom) {
  if (this->param_propagate_down_[0]) {
    const Dtype* top_diff = top[0]->cpu_diff();
    const Dtype* bottom_data = bottom[0]->cpu_data();
    // Gradient with respect to weight
    caffe_cpu_gemm<Dtype>(CblasTrans, CblasNoTrans, N_, K_, M_, (Dtype)1.,
        top_diff, bottom_data, (Dtype)1., this->blobs_[0]->mutable_cpu_diff());
  }
  if (bias_term_ && this->param_propagate_down_[1]) {
    const Dtype* top_diff = top[0]->cpu_diff();
    // Gradient with respect to bias
    caffe_cpu_gemv<Dtype>(CblasTrans, M_, N_, (Dtype)1., top_diff,
        bias_multiplier_.cpu_data(), (Dtype)1.,
        this->blobs_[1]->mutable_cpu_diff());
  }
  if (propagate_down[0]) {
    const Dtype* top_diff = top[0]->cpu_diff();
    // Gradient with respect to bottom data
    caffe_cpu_gemm<Dtype>(CblasNoTrans, CblasNoTrans, M_, K_, N_, (Dtype)1.,
        top_diff, this->blobs_[0]->cpu_data(), (Dtype)0.,
        bottom[0]->mutable_cpu_diff());
  }
}

#ifdef CPU_ONLY
STUB_GPU(MyInnerProductLayer);
#endif

INSTANTIATE_CLASS(MyInnerProductLayer);
REGISTER_LAYER_CLASS(MyInnerProduct);

}  // namespace caffe

**Comment by longjon** [comment]
Closing as this looks like a usage issue/request for help.

This tracker is reserved for specific Caffe development issues and bugs; please ask usage questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) list.

For more information, see our [contributing guide](https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md).

Thanks!
