### ISSUE TITLE
How to add constraints L2-norm to the conv layers and L1-norm to the fc layers when training a model

### ISSUE THREAD

**Issue by takecareofbigboss** [BVLC/caffe#3146]
How to add constraints L2-norm to the conv layers and L1-norm to the fc layers when training a model using caffe?
I know that we can use regularization_type: 'L1'  (in solver.prototxt) to give global constraints to all the layers. And also we can adjust the value of weight_decay and decay_mult to rectify the performance.

  optional float weight_decay = 12; // The weight decay.
  // regularization types supported: L1 and L2
  // controlled by weight_decay
  optional string regularization_type = 29 [default = "L2"];
 // The multiplier on the global weight decay for this parameter.
  optional float decay_mult = 4 [default = 1.0];

But how can i add constraints L2-norm to the conv layers and L1-norm to the fc layers when training a model using caffe?

**Comment by longjon** [comment]
Closing as this looks like a usage issue/request for help.

This tracker is reserved for specific Caffe development issues and bugs; please ask usage questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) list.

For more information, see our [contributing guide](https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md).

Thanks!
