### ISSUE TITLE
Using caffe to realize projected gradient descent.

### ISSUE THREAD

**Issue by takecareofbigboss** [BVLC/caffe#3147]
I want to realize gradient descent by using this algorithm, when having done the 1st gradient descent step, if w_2 < 0, we make w_2 equal to 0. If w_2 > 0, we do projection as sgd algorithm. The algorithm is shown as below.
![image](https://cloud.githubusercontent.com/assets/11883059/10273585/01f40930-6b65-11e5-8ed2-a66128d57ff9.png)

I only need do it on the fc layers, and sgd on the conv layers...

**Comment by longjon** [comment]
Closing as this looks like a usage issue/request for help.

This tracker is reserved for specific Caffe development issues and bugs; please ask usage questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) list.

For more information, see our [contributing guide](https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md).

Thanks!
