### ISSUE TITLE
Make Error: 'cudaMemAttachGlobal' was not declared

### ISSUE THREAD

**Issue by HrWangChengdu** [BVLC/caffe#3150]
Hi guys,

I'm running experiments on caffe, which was once successfully installed.
But recently, when I re-make caffe, I got error below with some analysis I did. but could not find out to fix.....

-----------------Error Start--------------
haoran@ XXX:~/Caffe/Normal/caffe$ make all
CXX src/caffe/util/cudnn.cpp
In file included from /usr/include/cudnn.h:60:0,
from ./include/caffe/util/cudnn.hpp:5,
from src/caffe/util/cudnn.cpp:2:
/usr/local/cuda/include/cuda_runtime.h:327:26: error: 'cudaMemAttachGlobal' was not declared in this scope
unsigned int flags = cudaMemAttachGlobal
^
In file included from /usr/include/cudnn.h:60:0,
from ./include/caffe/util/cudnn.hpp:5,
from src/caffe/util/cudnn.cpp:2:
/usr/local/cuda/include/cuda_runtime.h:404:27: error: 'cudaMemAttachSingle' was not declared in this scope
unsigned int flags = cudaMemAttachSingle
-----------------Error Finish--------------

My analysis:

I've checked through /usr/local/cuda/include file. And I've found the definition of both 'cudaMemAttachSingle(Global)' at 'driver_types.h' file, which writes as :

#if !defined(__CUDA_INTERNAL_COMPILATION__)

.
.
.

#define cudaMemAttachGlobal 0x01 /**< Memory can be accessed by any stream on any device*/
#define cudaMemAttachHost 0x02 /**< Memory cannot be accessed by any stream on any device */
#define cudaMemAttachSingle 0x04 /**< Memory can only be accessed by a single stream on the associated device */

#endif /* !__CUDA_INTERNAL_COMPILATION__ */.

So the problem turns into unexpected definition of __CUDA_INTERNAL_COMPILATION__, which is found at "crt/host_runtime.h". But then I cannot find a single sentence about "include "host_runtime.h"" nor how to solve it.

Could anyone give some suggestions?
Thanks a lot :-)

**Comment by longjon** [comment]
Closing as this looks like a cuDNN/CUDA installation issue; does your cuDNN require a newer CUDA version?

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
