### ISSUE TITLE
training using pixel wise labeled ground truth of k-channel image

### ISSUE THREAD

**Issue by mtrth** [BVLC/caffe#3154]
I am trying to do training on pixel-wise labeled ground truth images. The training data is 800 images (5,256,256) also a pixel level ground truth images (1,256,256). I am trying to use this data to train a CNN and then do pixel wise prediction (generate prediction of 1,256,256).
Is there a example which illustrates how to perform this with current caffe implementation? 
it would be great if you could help !

**Comment by longjon** [comment]
Closing as this looks like a usage issue/request for help.

This tracker is reserved for specific Caffe development issues and bugs; please ask usage questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) list.

For more information, see our [contributing guide](https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md).

Thanks!
