### ISSUE TITLE
NVCC src/caffe/layers/hdf5_output_layer.cu,hdf5_output_layer.o error, Using cuda6.5

### ISSUE THREAD

**Issue by xxw345** [BVLC/caffe#3156]
Just fyi, I am compiling Caffe on cluster environment, I don't have root permission.
When using make all, it run smoothly till the line below: 

NVCC src/caffe/layers/hdf5_output_layer.cu
/util/academic/python/anaconda/include/boost/smart_ptr/detail/sp_counted_base_gcc_x86.hpp(49): warning: "cc" clobber ignored

/util/academic/python/anaconda/include/boost/smart_ptr/detail/sp_counted_base_gcc_x86.hpp(65): warning: "cc" clobber ignored

/util/academic/python/anaconda/include/boost/smart_ptr/detail/sp_counted_base_gcc_x86.hpp(91): warning: "cc" clobber ignored

/util/academic/python/anaconda/include/boost/smart_ptr/detail/sp_counted_base_gcc_x86.hpp(75): warning: variable "tmp" was set but never used

At end of source: warning: routine is both "inline" and "noinline"

/util/academic/cuda/6.5/include/cuda_runtime.h(1232): warning: routine is both "inline" and "noinline"

/util/academic/python/anaconda/include/boost/smart_ptr/detail/sp_counted_base_gcc_x86.hpp(49): warning: "cc" clobber ignored

/util/academic/python/anaconda/include/boost/smart_ptr/detail/sp_counted_base_gcc_x86.hpp(65): warning: "cc" clobber ignored

/util/academic/python/anaconda/include/boost/smart_ptr/detail/sp_counted_base_gcc_x86.hpp(91): warning: "cc" clobber ignored

/util/academic/python/anaconda/include/boost/smart_ptr/detail/sp_counted_base_gcc_x86.hpp(75): warning: variable "tmp" was set but never used

At end of source: warning: routine is both "inline" and "noinline"

/util/academic/cuda/6.5/include/cuda_runtime.h(1232): warning: routine is both "inline" and "noinline"

/util/academic/python/anaconda/include/boost/smart_ptr/detail/sp_counted_base_gcc_x86.hpp(49): warning: "cc" clobber ignored

/util/academic/python/anaconda/include/boost/smart_ptr/detail/sp_counted_base_gcc_x86.hpp(65): warning: "cc" clobber ignored

/util/academic/python/anaconda/include/boost/smart_ptr/detail/sp_counted_base_gcc_x86.hpp(91): warning: "cc" clobber ignored

/util/academic/python/anaconda/include/boost/smart_ptr/detail/sp_counted_base_gcc_x86.hpp(75): warning: variable "tmp" was set but never used

At end of source: warning: routine is both "inline" and "noinline"

/util/academic/cuda/6.5/include/cuda_runtime.h(1232): warning: routine is both "inline" and "noinline"

/util/academic/python/anaconda/include/boost/smart_ptr/detail/sp_counted_base_gcc_x86.hpp(49): warning: "cc" clobber ignored

/util/academic/python/anaconda/include/boost/smart_ptr/detail/sp_counted_base_gcc_x86.hpp(65): warning: "cc" clobber ignored

/util/academic/python/anaconda/include/boost/smart_ptr/detail/sp_counted_base_gcc_x86.hpp(91): warning: "cc" clobber ignored

/util/academic/python/anaconda/include/boost/smart_ptr/detail/sp_counted_base_gcc_x86.hpp(75): warning: variable "tmp" was set but never used

At end of source: warning: routine is both "inline" and "noinline"

/util/academic/cuda/6.5/include/cuda_runtime.h(1232): warning: routine is both "inline" and "noinline"

/util/academic/python/anaconda/include/boost/smart_ptr/detail/sp_counted_base_gcc_x86.hpp(49): warning: "cc" clobber ignored

/util/academic/python/anaconda/include/boost/smart_ptr/detail/sp_counted_base_gcc_x86.hpp(65): warning: "cc" clobber ignored

/util/academic/python/anaconda/include/boost/smart_ptr/detail/sp_counted_base_gcc_x86.hpp(91): warning: "cc" clobber ignored

/util/academic/python/anaconda/include/boost/smart_ptr/detail/sp_counted_base_gcc_x86.hpp(75): warning: variable "tmp" was set but never used

At end of source: warning: routine is both "inline" and "noinline"

At end of source: warning: routine is both "inline" and "noinline"

/util/academic/python/anaconda/include/boost/smart_ptr/detail/sp_counted_base_gcc_x86.hpp(49): warning: "cc" clobber ignored

/util/academic/python/anaconda/include/boost/smart_ptr/detail/sp_counted_base_gcc_x86.hpp(65): warning: "cc" clobber ignored

/util/academic/python/anaconda/include/boost/smart_ptr/detail/sp_counted_base_gcc_x86.hpp(91): warning: "cc" clobber ignored

/util/academic/python/anaconda/include/boost/smart_ptr/detail/sp_counted_base_gcc_x86.hpp(75): warning: variable "tmp" was set but never used

At end of source: warning: routine is both "inline" and "noinline"

At end of source: warning: routine is both "inline" and "noinline"

/util/academic/python/anaconda/include/boost/smart_ptr/detail/sp_counted_base_gcc_x86.hpp(49): warning: "cc" clobber ignored

/util/academic/python/anaconda/include/boost/smart_ptr/detail/sp_counted_base_gcc_x86.hpp(65): warning: "cc" clobber ignored

/util/academic/python/anaconda/include/boost/smart_ptr/detail/sp_counted_base_gcc_x86.hpp(91): warning: "cc" clobber ignored

/util/academic/python/anaconda/include/boost/smart_ptr/detail/sp_counted_base_gcc_x86.hpp(75): warning: variable "tmp" was set but never used

At end of source: warning: routine is both "inline" and "noinline"

At end of source: warning: routine is both "inline" and "noinline"

/util/academic/python/anaconda/include/boost/smart_ptr/detail/sp_counted_base_gcc_x86.hpp(49): warning: "cc" clobber ignored

/util/academic/python/anaconda/include/boost/smart_ptr/detail/sp_counted_base_gcc_x86.hpp(65): warning: "cc" clobber ignored

/util/academic/python/anaconda/include/boost/smart_ptr/detail/sp_counted_base_gcc_x86.hpp(91): warning: "cc" clobber ignored

/util/academic/python/anaconda/include/boost/smart_ptr/detail/sp_counted_base_gcc_x86.hpp(75): warning: variable "tmp" was set but never used

At end of source: warning: routine is both "inline" and "noinline"

At end of source: warning: routine is both "inline" and "noinline"

/user/xiangxui/.usr/local/include/google/protobuf/arena.h:909:38: error: conflicting declaration ‘const google::protobuf::internal::integral_constant<bool, ((sizeof (DestructorSkippable<const T>(static_cast<const T*>(0))) == sizeof (char)) || (google::protobuf::internal::has_trivial_destructor<A>::value == true))> google::protobuf::Arena::is_destructor_skippable<T>::value’
     Arena::is_destructor_skippable<T>::value =
                                      ^
/user/xiangxui/.usr/local/include/google/protobuf/arena.h:589:19: error: ‘google::protobuf::Arena::is_destructor_skippable<T>::value’ has a previous declaration as ‘const type google::protobuf::Arena::is_destructor_skippable<T>::value’
     static const type value;
                   ^
/user/xiangxui/.usr/local/include/google/protobuf/arena.h:909:38: error: declaration of ‘const type google::protobuf::Arena::is_destructor_skippable<T>::value’ outside of class is not definition [-fpermissive]
     Arena::is_destructor_skippable<T>::value =
                                      ^
make: *** [.build_release/cuda/src/caffe/layers/hdf5_output_layer.o] Error 1

**Comment by xxw345** [comment]
FYI
I crack this error by #787 by Yangqing Jia.

The final version of arena.h is https://github.com/xfxyjwf/protobuf/commit/494716a682ef854168e92231a3cdcc89d587d9b9

**Comment by sepidehhosseinzadeh** [comment]
@xxw345 
Hi there!
I am having the same error while I am using your mentioned file! Do have any other idea?
