### ISSUE TITLE
Parse volume data caffemodel error

### ISSUE THREAD

**Issue by rockstone533** [BVLC/caffe#3157]
I tried to train volume data by hdf5 data, and got caffemodel.When I tried to use matcaffe to parse caffemodel, I got an error below.
Check failed: num_kernel_dims == 1 || num_kernel_dims == num_spatial_axes_ kernel_size must be specified once, or once per spatial dimension (kernel_size specified 3 times; 2 spatial dims);

**Comment by longjon** [comment]
Closing as this looks like a request for help.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

**Comment by qingzew** [comment]
you do think everyon can google?? no!! not in china
