### ISSUE TITLE
Apply a mask to the activations of fc6 and fc7 during testing at the dropout layer

### ISSUE THREAD

**Issue by vignesh10** [BVLC/caffe#3158]
Hi,

As of now, the dropout layer does not do anything during testing.

During testing, I would like to define a binary mask of the same size as fc6/7 and have the activations multiplied with the mask.

for eg:
fc6 top_data = {1.26156843,0.77140903,0.,0.}
mask = {1,1,0,1} 

top_data = top_data * mask

Kindly let me know how I can implement this in dropout_layer.cu for testing phase.
Thanks in advance!

**Comment by longjon** [comment]
Closing as this looks like a usage issue/request for help.

This tracker is reserved for specific Caffe development issues and bugs; please ask usage questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) list.

For more information, see our [contributing guide](https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md).

Thanks!
