### ISSUE TITLE
Data structures use int instead of size_t or long, issue for 64-bit machines

### ISSUE THREAD

**Issue by jmcq** [BVLC/caffe#3159]
I am working on distributed execution of the matrix multiplies for very large nets, via ScaLAPACK.  These become useful when matrices approach 10k x 10k in size (useful to avoid batching).

However, there are many data structures that use "int" to track sizes, rather than long or size_it.  This puts a limit in, e.g. Blob<Dtype>::Reshape(), because blob size cannot exceed INT_MAX, which is only 2^31 on a 64bit machine, while a 64bit machine can handle larger matrices if long and size_t were used.

**Comment by ronghanghu** [comment]
There is a lot of work to be done before we can change to size_t (or int64 if one wants to have negative index). Some details are mentioned in https://github.com/BVLC/caffe/pull/2473#issuecomment-102720023

**Comment by jmcq** [comment]
I am closing and making followup in #2473, thanks for locating that ticket.
