### ISSUE TITLE
Syntax difference in layer defintion prototxt file

### ISSUE THREAD

**Issue by hasnainv** [BVLC/caffe#3165]
Is there any difference between defining a "layer" vs "layers" in the layers.prototxt file? Can this be consolidated to a single syntax?

Fields like "param { lr_mult: 1 }" do not work with files having "layer{ }" syntax

The models from VGG in the model zoo (https://gist.github.com/ksimonyan/3785162f95cd2d5fee77#file-vgg_ilsvrc_19_layers_deploy-prototxt) are defined with the syntax "layers".

While the models in caffe examples are defined with the syntax "layer" (https://github.com/BVLC/caffe/blob/master/models/bvlc_alexnet/train_val.prototxt)?

**Comment by longjon** [comment]
Closing as this looks like a request for help (though admittedly documentation is underwhelming in this area; you may want to consult https://github.com/BVLC/caffe/blob/master/src/caffe/proto/caffe.proto).

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
