### ISSUE TITLE
ReadImageToCVMat strange error

### ISSUE THREAD

**Issue by swamiviv** [BVLC/caffe#3166]
I am trying to train a deep network on a lot of data stored in a cluster. I have been training several networks successfully over the past weeks and suddenly now I get the following error:

````
E1007 17:11:25.214215   922 io.cpp:81] Could not open or find file /data/1285162/174_t6_06017.jpg
F1007 17:11:25.214344   922 image_data_layer.cpp:162] Check failed: cv_img.data Could not load /data/174_t6_06017.jpg
````

I had checked the following already:

** The file exists and is not corrupted
** I can read/display the file using a stand alone opencv code with imread (the same that caffe uses).

I am puzzled by this. Could anyone get what is happening here ? If it helps, I am using ImageDatalayer to feed the input. I tried to create a lmdb database with all my data, the same thing occured there - the same error occured for some images when lmdb was created.

**Comment by stanstarks** [comment]
Is your data placed under '/' folder? or you mean 'data/1285162/174_t6_06017.jpg'?

**Comment by basuam** [comment]
I have the same error, I posted it recently here....
https://github.com/BVLC/caffe/issues/3367

Apparently is not possible to work with images... something changed in Caffe

**Comment by iridescent303** [comment]
I have met the same problem too.

**Comment by jpsquare** [comment]
Is the above issue caused due to a problem in the file holding the image urls?

**Comment by jpsquare** [comment]
Yes I resolved this issue by prepending the absolute path to the images in the file holding the image names. Thus the image urls could now be resolved by the opencv methods

**Comment by seanbell** [comment]
Closing, since this seems to be resolved, and related to installation/library problems and not caffe.
