### ISSUE TITLE
How to extract one image feature?

### ISSUE THREAD

**Issue by tjusxh** [BVLC/caffe#3167]
I want to extract only one image feature without prototxt file. Not the batch feature. The image is loaded from disk. We don't need configuration file with a set of images path.Thank you!

**Comment by longjon** [comment]
Closing as this looks like a request for help.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
