### ISSUE TITLE
Make runtest loops and fails

### ISSUE THREAD

**Issue by aravindsrinivas** [BVLC/caffe#3169]
I am trying to work with caffe. make and make test succeed. When I run 'make runtest' it seems to go into an infinite loop. 

This also shows up whenever I try to train a network. It stalls with the message of "Use CPU" or "Use GPU with device id " and keeps running, without any messages printed.

![fixcn](https://cloud.githubusercontent.com/assets/10277469/10362481/7d3c9800-6dcc-11e5-964e-19939000ff1e.png)

**Comment by shelhamer** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
