### ISSUE TITLE
Getting Output Log Files on Matcaffe

### ISSUE THREAD

**Issue by suhaslohit** [BVLC/caffe#3171]
Is it possible to get a log file while training using Matcaffe. By this, I mean a file containing the iteration number and error values etc.

**Comment by longjon** [comment]
Closing as this looks like a request for help.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
