### ISSUE TITLE
0 recognition rate of finetuning CaffeNet

### ISSUE THREAD

**Issue by 7oud** [BVLC/caffe#3172]
We are trying to use 10 kinds of ImageNet 2012 data to finetune  CaffeNet. All procedures are consulted "Fine-tuning a Pretrained Network for Style Recognition", and we just changed the number output of the fc8 as 10. At the same time, the pure C++ tools are used to finetune the CaffeNet. The recognition rates of the two methods are both 0.

**Comment by longjon** [comment]
Closing as this looks like a request for help.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
