### ISSUE TITLE
Non-image data. An example of addition.

### ISSUE THREAD

**Issue by DimaSNN** [BVLC/caffe#3173]
Please, could someone show a network example for addition of numbers.
I tried to make a layers structure but I could not find the right layers.
I try to create the regression NN to analyze  spectrum of signal.

**Comment by longjon** [comment]
Closing as this looks like a request for help.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
