### ISSUE TITLE
How to get better detection using "detect.py" when model=GoogLeNet?

### ISSUE THREAD

**Issue by catsdogone** [BVLC/caffe#3178]
I do detection by a pure Caffe edition of the R-CNN model for ImageNet as this example http://nbviewer.ipython.org/github/BVLC/caffe/blob/master/examples/detection.ipynb, it works well. While when I use other models, it is detection result seems not good(image-cat.jpg):
...
name
domestic cat             0.290302
monkey                  -0.364010
fox                     -0.499396
flower pot              -0.561735
horse                   -0.922417
strawberry              -0.923321
salt or pepper shaker   -0.925882
head cabbage            -0.955417
binder                  -0.970688
table                   -0.999349
...
<img width="330" alt="buhuo 2" src="https://cloud.githubusercontent.com/assets/7392509/10424405/80bc251c-7101-11e5-97cd-8f9a3b544f29.PNG">

Does "detect.py" only works when model=bvlc_reference_rcnn_ilsvrc13.caffemodel ? What I should do for a better result when model=GoogLeNet?
Thanks very much for your help.

**Comment by melgor** [comment]
Hi,
did you read paper which explain R-CNN idea? Their model was specially trained for Object Detection task,  where GoogLeNet is a classification net. 
To get better  result, you have to follow pipeline in R-CNN paper to learn GoogLeNet as detection net.

**Comment by catsdogone** [comment]
@melgor 
Thank you very much.

**Comment by catsdogone** [comment]
@melgor 
Does "rcnn-master" created by Ross Girshick etc the best teaching material or application tool if I want to learn my GoogLeNet as detection net ?

**Comment by melgor** [comment]
There are two better options, newer paper from Ross Girshick:
Fast-RCNN: the difference in mainly in speed (it is 9x faster in training and 200x faster in detection) https://github.com/rbgirshick/fast-rcnn
Faster-RCNN: here the difference is that Object Proposal are learned from annotations. So if you have enought data for detection task, it could be better to use Faster-RCNN (https://github.com/rbgirshick/py-faster-rcnn)

For a future questions about using caffe, please ask them in caffe mailing group. https://groups.google.com/forum/#!forum/caffe-users
Please, close that issue.
