### ISSUE TITLE
Data is never assigned to input_vec in extract_features.cpp

### ISSUE THREAD

**Issue by karnivaurus** [BVLC/caffe#3179]
In `extract_features.cpp` (https://github.com/BVLC/caffe/blob/master/tools/extract_features.cpp), line 140 creates a variable called `input_vec`, which is a vector of `Blob` objects. This presumably represents the set of input images which are to be passed through the network. However, `input_vec` is never assigned to any data, and `input_vec.size()` is always 0.

Then three lines later at line 143, with `input_vec` at size 0, we have `feature_extraction_net->Forward(input_vec);` which attempts to send `input_vec` through the network. In the `Forward()` function, each blob in `input_vec` is copied over to the variable `net_input_blobs`, which presumably is then copied over to the blob for the first layer. 

So if the size of `input_vec` is always zero, then this copying is never done, and the network is never assigned the input data. Any features computed will just be based on whatever random data is in the blob in the first layer when the network is initialized. Is this a bug, or am I misunderstanding the code?

**Comment by longjon** [comment]
Here `input_vec` is a dummy vector expected by the `Forward` interface; the real data comes from a data layer which must be present in the network. It would probably make sense to call `ForwardPrefilled` here, although this interface is due to change in #3211, so I'll close in favor of that PR.
