### ISSUE TITLE
flow of caffe

### ISSUE THREAD

**Issue by hridaynathp** [BVLC/caffe#3181]
hi,
I am new to caffe, I have compiled and run the mnist example, and further able to create my own lmdb for train and test. I have a query that after running mnist example how can i use this to test one digit image to identify which number is that?
how to and where to set this image path?
why there are two sets test and train?

Thanks in advance...

**Comment by ronghanghu** [comment]
Please do not post usage, installation, or modeling questions, or other requests for help to Issues.
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
