### ISSUE TITLE
CaffeNet solver.prototxt test mirroring should not be true?

### ISSUE THREAD

**Issue by bchu** [BVLC/caffe#3183]
In https://github.com/BVLC/caffe/blob/master/models/bvlc_reference_caffenet/train_val.prototxt, in the test phase data layer, shouldn't `#    mirror: true` be `#    mirror: false`?

Would be happy to submit a quick PR is this is a bug.

**Comment by shelhamer** [comment]
Yes, the commented-out line https://github.com/BVLC/caffe/blob/master/models/bvlc_reference_caffenet/train_val.prototxt#L48 should be `mirror: false` to match the `TEST` phase data layer definition. Please send a little PR.
