### ISSUE TITLE
16 bit image tiff format

### ISSUE THREAD

**Issue by smithdir101** [BVLC/caffe#3191]
Hi All,

I have images that are 16 bits and I saved them in tiff format image.
I am new in the DL caffe.
From my understanding caffe deep learning does not support 16 bits images.
If it does not is there a way easly to make a  a change in the data layer such that these images 16 bits can be supported.

I saw that it is recommended to have the hdf6 format or the ldbm format. Again, from my understudying it created from many images  an entire database that the CPU can not read it.
Can I create hdf6 format to each image?
Any advise it would be great.

Thanks
Jhon Smithdir

**Comment by longjon** [comment]
Closing as a request for help.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
