### ISSUE TITLE
Build on Windows 7

### ISSUE THREAD

**Issue by hevy-CC4477** [BVLC/caffe#3195]
Do recommend to use caffe-rc2 on windows ? and Why ?

**Comment by longjon** [comment]
Closing as a request for help.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
