### ISSUE TITLE
Adding swap functionality for Blob

### ISSUE THREAD

**Issue by xuzhenqi** [BVLC/caffe#3196]
The Blob class doesn't provide any method to exchange two blobs' contents. Using CopyFrom method will do copying memory, and thus is not efficient. 

I think it's necessary to provide swap() function in Blob class, which only exchange pointers, just like the swap() function in the standard c++ namespace.

**Comment by longjon** [comment]
Closing as I can't think of any use case for this in Caffe; feel free to open a new issue describing such a use case if you have one in mind.

**Comment by Laser-Cat** [comment]
I also think it's necessary to provide swap() function in Blob class. I am trying to implement a multi-thread data layer that fetches data during the time the net runs on GPU. More specifically,
    template<typename Dtype>
void Forward_cpu(const vector<Blob<Dtype> *> &bottom, const vector<Blob<Dtype> *> &top)
{
    if(worker->joinable())
    {
        worker->join();
    }
    use_buffer(buffer[buffer_id],top);
    buffer_id^=1;
    worker.reset(new_worker(buffer_id));
    
}
void use_buffer(const vector<Blob<Dtype> *> & buffer, const vector<Blob<Dtype> *> &top)
    {
        for(int i=0;i<buffer.size();i++)
        {
            top[i]->Swap(*buffer[i]);
        }
    }

**Comment by Laser-Cat** [comment]
I think it is necessary for data layers.
I am implementing a multi-thread data layer that fetches data to buffer while the net work runs on gpu as following .
template<typename Dtype>
void Forward_cpu(const vector<Blob<Dtype> *> &bottom, const vector<Blob<Dtype> *> &top)
{
    if(worker->joinable())
    {
        worker->join();
    }
    
    use_buffer(buffer[buffer_id],top);
    
    buffer_id^=1;
    worker.reset(new_worker(buffer_id));

    
}

    void use_buffer(const vector<Blob<Dtype> *> & buffer, const vector<Blob<Dtype> *> &top)
    {
        for(int i=0;i<buffer.size();i++)
        {
            top[i]->CopyFrom(*buffer[i],0,1); /// Swap will be much better.
        }
    }
