### ISSUE TITLE
python warpper mean shap incompatible with input shape, maybe a bug?

### ISSUE THREAD

**Issue by kli-nlpr** [BVLC/caffe#3197]
When training the network, all images and the mean image are 256*256.

When use python warpper to test, in deploy.prototxt, the input size is 227*227, do I have to resize the mean image from 256*256 to 227*227?

I think it's wrong, because at training phase, every image  subtract a 256*256 mean image, at test time, it's right to subtract a 256*256 mean image too.

Resize mean image to 227*227 will hurt the accuray sometimes.

**Comment by xuzhenqi** [comment]
The deploy proto does not contain a data layer, so the network input dim is [227, 227].

You should crop or resize your image to 227 * 227 manually, thus to feed into the deploy proto.

Or you can contain a data layer in the deploy proto to do it for you.

**Comment by kli-nlpr** [comment]
@xuzhenqi 

I use the python class classifier, 
When I feed the mean image which was used for training  to  caffe.Classifier
It complains mean shap incompatible with input shape

**Comment by kli-nlpr** [comment]
I have to resize the mean image from 256*256 to 227*227, but I think this will hurt accuray, because the mean image will be different from the one which was used for training.
