### ISSUE TITLE
Feature Extraction Tutorial gives segmentation fault. 

### ISSUE THREAD

**Issue by hyojinie** [BVLC/caffe#3198]
Feature Extraction Tutorial gives segmentation fault (core dumped)
E1015 11:38:29.298517 13441 extract_features.cpp:64] Using CPU
Segmentation fault (core dumped)

http://caffe.berkeleyvision.org/gathered/examples/feature_extraction.html

It has been reported in caffe-users, too. Has it been fixed? What is the solution?
https://groups.google.com/forum/#!topic/caffe-users/STI5fYSO4cs

I am not using the old version, I downloaded codes on Sept 26 2015

**Comment by rhythm9229** [comment]
@hyojinie i also got the same error but i got fixed when i added label after the filename in file_list.txt

example -    /images/1.jpg 0

so adding a lable after the image file names should fix the segmentation fault
