### ISSUE TITLE
Create Meanfile

### ISSUE THREAD

**Issue by ruoyanwang** [BVLC/caffe#320]
Hi,
I'm using python detection wrapper to test result of my own network. I don't use meanfile for my network but it seems that a meanfile must be provided for the wrapper. One way I can think of is to create a meanfile with all 0 but how could I actually create it?
Also, I tried hacking the code for meanfile part in detector.py but it still gave error "cannot open flic_deploy.prototxt". Are there better ways to fix the problem?

Best,
Ryan

**Comment by eldarial** [comment]
thanks
