### ISSUE TITLE
Need HDF5 file for regression (with images)

### ISSUE THREAD

**Issue by AWin9** [BVLC/caffe#3202]
I need correct hdf5 file with images for regression (multi label). I searched for a long time example of this file, but I couldn't. Please, give me a link to such a file.

**Comment by seanbell** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

**Comment by helxsz** [comment]
could caffe in the future version provides a example of HDF5 with image data.
