### ISSUE TITLE
ELTWISE layer suspected bug

### ISSUE THREAD

**Issue by stamas02** [BVLC/caffe#3203]
In the eltwise_layer.cpp you do the following check in the Reshape member function

      for (int i = 1; i < bottom.size(); ++i) {
                 CHECK(bottom[i]->shape() == bottom[0]->shape());
      }

Meanwhile in other layers like euclidean_loss_layer.cpp you do this:

     CHECK_EQ(bottom[0]->count(1), bottom[1]->count(1))

I think the above mentioned for loop should look something like this:

      for (int i = 1; i < bottom.size(); ++i) {
                 CHECK(bottom[i]->count(1) == bottom[0]->count(1));
      }

So if I have to following structure (just a small part):

        layers {
            name: "input2-layer"
            type: MEMORY_DATA
            top: "input2"
            top: "dummy2"
            memory_data_param {
                batch_size: 10
                channels: 3
                height: 1
                width: 1
            }

            layers {
                name: "inner-product-layer"
                type: INNER_PRODUCT
                bottom: "previous-data"
                top: "data"
                inner_product_param {
                    num_output: 3
                    weight_filler {
                        type: "gaussian"
                        std: 0.01
                    }
                }
            }

            layers {
                name: "eltwise_layer"
                type: ELTWISE
                bottom: "input2"
                bottom: "data"
                top: "filtered-q-values"
                eltwise_param {
                    operation: PROD
                }
            }

This will result an error even if I have another memory data layer at the beginning which has batch_size: 10 which then goes thorough some convolutional layer and ends up in the inner inner-product-layer. I assume here you are checking 10*3 == 3 instead of checking 3==3.

I might be wrong and please let me know If I am happened to be wrong and I shouldn't change the checking in my version of caffe for some reason.

Thank you

Tamás

**Comment by ronghanghu** [comment]
After a quick glance, I think `CHECK(bottom[i]->shape() == bottom[0]->shape())` should be correct.

`bottom[i]->shape()` returns `std::vector<int>`, a array containing the shape of the blob, and `==` for `std::vector` is elementwise. `CHECK(bottom[i]->shape() == bottom[0]->shape())` means all axis of the two blobs have the same dimension, so this implies `CHECK(bottom[i]->count(1) == bottom[0]->count(1))`

**Comment by ronghanghu** [comment]
In the case you mentioned above, your `data` should be 10 x 3, so your `input2` also needs to be 10 x 3, so that they can be multiplied element-wise.

Note: element-wise layer does not do numpy-style broadcasting, although we may implement it in the future.

**Comment by stamas02** [comment]
So you are saying that this net should not work because it is not supported by the element-wise layer?

		layers {
		  name: "frames-input-layer"
		  type: MEMORY_DATA
		  top: "frames"
		  top: "dummy1"
		  memory_data_param {
			batch_size: 32
			channels: 4
			height: 84
			width: 84
		  }
		}
		layers {
		  name: "target-input-layer"
		  type: MEMORY_DATA
		  top: "target"
		  top: "dummy2"
		  memory_data_param {
			batch_size: 32
			channels: 18
			height: 1
			width: 1
		  }
		}
		layers {
		  name: "filter-input-layer"
		  type: MEMORY_DATA
		  top: "filter"
		  top: "dummy3"
		  memory_data_param {
			batch_size: 32
			channels: 18
			height: 1
			width: 1
		  }
		}
		layers {
		  name: "silence_layer"
		  type: SILENCE
		  bottom: "dummy1"
		  bottom: "dummy2"
		  bottom: "dummy3"
		}
		layers {
		  name: "convolutional-layer-1"
		  type: CONVOLUTION
		  bottom: "frames"
		  top: "convolution1"
		  convolution_param {
			num_output: 16
			kernel_size: 8
			stride: 4
			weight_filler {
			  type: "gaussian"
			  std: 0.01
			}
		  }
		}
		layers {
		  name: "conv1_relu_layer"
		  type: RELU
		  bottom: "convolution1"
		  top: "convolution1"
		  relu_param {
			negative_slope: 0.01
		  }
		}
		layers {
		  name: "convolutional-layer-2"
		  type: CONVOLUTION
		  bottom: "convolution1"
		  top: "convolution2"
		  convolution_param {
			num_output: 32
			kernel_size: 4
			stride: 2
			weight_filler {
			  type: "gaussian"
			  std: 0.01
			}
		  }
		}

		layers {
		  name: "conv2_relu_layer"
		  type: RELU
		  bottom: "convolution2"
		  top: "convolution2"
		  relu_param {
			negative_slope: 0.01
		  }
		}

		layers {
		  name: "inner-product-layer-1"
		  type: INNER_PRODUCT
		  bottom: "convolution2"
		  top: "inner-product-1"
		  inner_product_param {
			num_output: 256
			weight_filler {
			  type: "gaussian"
			  std: 0.01
			}
		  }
		}

		layers {
		  name: "ip1_relu_layer"
		  type: RELU
		  bottom: "inner-product-1"
		  top: "inner-product-1"
		  relu_param {
			negative_slope: 0.01
		  }
		}

		layers {
		  name: "inner-product-layer-2"
		  type: INNER_PRODUCT
		  bottom: "inner-product-1"
		  top: "q-values"
		  inner_product_param {
			num_output: 18
			weight_filler {
			  type: "gaussian"
			  std: 0.01
			}
		  }
		}

		layers {
		  name: "eltwise_layer"
		  type: ELTWISE
		  bottom: "filter"
		  bottom: "q-values"
		  top: "filtered-q-values"
		  eltwise_param {
			operation: PROD
		  }
		}

		layers {
		  name: "loss"
		  type: EUCLIDEAN_LOSS
		  bottom: "filtered-q-values"
		  bottom: "target"
		  top: "loss"
		}

**Comment by ronghanghu** [comment]
I guess it is not working because your `filter` is 32 x 18 x 1 x 1 while your `q-values` is 32 x 18. You may use Reshape layer to reshape `filter` to 32 x 18.

This seems like a usage question than a caffe bug, and should be asked on [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead of here. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
