### ISSUE TITLE
Caffe Can not get gpu_data()

### ISSUE THREAD

**Issue by CMeteor** [BVLC/caffe#3210]
The question is that I have wrote a cpu layer(*.cpp),which can pass the test code. But when I transform the cpu vesion to gpu version(*.cu), I found the blob_bottom_->gpu_data() is a void point, there is no data. In addition, the blob_bottom_->count() and other dim messages are right.

Could somebody help me ? thanks.

**Comment by seanbell** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

**Comment by dingcius** [comment]
I actually encounter the same problem as CMeteor. 
Could anyone  provide solution?
