### ISSUE TITLE
Running multiple caffemodels for predictions on multiple images on one GPU in parallel

### ISSUE THREAD

**Issue by kumarabhinavgupta** [BVLC/caffe#3212]
Hi, 

We are able to run one caffe model on multiple images on one GPU. We want to check whether it is possible to run multiple caffe models on multiple images on one GPU.

The models are pretty light and we are using NVIDIA 980

Thank,
Abhinav

**Comment by longjon** [comment]
Closing as a request for help.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

**Comment by isgursoy** [comment]
I dont think so.
