### ISSUE TITLE
"caffe/proto/caffe.pb.h" file not found error in Mac OS installation.

### ISSUE THREAD

**Issue by dhananjaymehta** [BVLC/caffe#3215]
Hi I tried to setup my Caffe framework on my mac machine but while running the Make commands I have faced the errors - 

1. Make all
PROTOC src/caffe/proto/caffe.proto
make: protoc: No such file or directory

2. Make test 
'caffe/proto/caffe.pb.h' file not found

I have tried the below solution but still doesn't seem to work for me - 
protoc src/caffe/proto/caffe.proto --cpp_out=.
mkdir include/caffe/proto
mv src/caffe/proto/caffe.pb.h include/caffe/proto

Should I check any dependencies or any thing else. Please advise on this.

**Comment by ronghanghu** [comment]
Please do not post usage, installation, or modeling questions, or other requests for help to Issues.
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
