### ISSUE TITLE
Error of db_lmdb.hpp:14 when running ImageNet example

### ISSUE THREAD

**Issue by deepjoy2002** [BVLC/caffe#3216]
Please help, I get an error, when I run the ImageNet example (http://caffe.berkeleyvision.org/gathered/examples/imagenet.html)

deepjoy@deepjoy-HP-ProDesk-600-G1-TWR:~/caffe$ ./examples/imagenet/make_imagenet_mean.sh
F1019 12:53:16.296841 14010 db_lmdb.hpp:14] Check failed: mdb_status == 0 (2 vs. 0) No such file or directory
*** Check failure stack trace: ***
    @     0x7f0f5c688daa  (unknown)
    @     0x7f0f5c688ce4  (unknown)
    @     0x7f0f5c6886e6  (unknown)
    @     0x7f0f5c68b687  (unknown)
    @     0x7f0f5ca1864e  caffe::db::LMDB::Open()
    @           0x4019c4  main
    @     0x7f0f5b898ec5  (unknown)
    @           0x40240a  (unknown)
    @              (nil)  (unknown)
Aborted (core dumped)
Done.

**Comment by seanbell** [comment]
Read the error: `No such file or directory`.  You are missing the `ilsvrc12_train_lmdb` file.

Also,
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
