### ISSUE TITLE
make all: undefined reference error

### ISSUE THREAD

**Issue by ProgmasterX** [BVLC/caffe#3224]
Scanning dependencies of target caffe.bin
[ 89%] Building CXX object tools/CMakeFiles/caffe.bin.dir/caffe.cpp.o
Linking CXX executable caffe
../lib/libcaffe.so: undefined reference to `H5LTget_dataset_ndims'
../lib/libcaffe.so: undefined reference to `H5Fcreate'
../lib/libcaffe.so: undefined reference to `H5LTread_dataset_int'
../lib/libcaffe.so: undefined reference to `H5Fclose'
../lib/libcaffe.so: undefined reference to `H5Gclose'
../lib/libcaffe.so: undefined reference to `H5check_version'
../lib/libcaffe.so: undefined reference to `H5LTfind_dataset'
../lib/libcaffe.so: undefined reference to `H5Lget_name_by_idx'
../lib/libcaffe.so: undefined reference to `H5Lexists'
../lib/libcaffe.so: undefined reference to `H5Gcreate2'
../lib/libcaffe.so: undefined reference to `H5LTmake_dataset_double'
../lib/libcaffe.so: undefined reference to `H5LTmake_dataset_int'
../lib/libcaffe.so: undefined reference to `H5LTread_dataset_float'
../lib/libcaffe.so: undefined reference to `H5LTmake_dataset_float'
../lib/libcaffe.so: undefined reference to `H5LTget_dataset_info'
../lib/libcaffe.so: undefined reference to `H5LTread_dataset_string'
../lib/libcaffe.so: undefined reference to `H5Gget_info'
../lib/libcaffe.so: undefined reference to `H5Gopen2'
../lib/libcaffe.so: undefined reference to `H5LTread_dataset_double'
../lib/libcaffe.so: undefined reference to `H5Fopen'
../lib/libcaffe.so: undefined reference to `H5LTmake_dataset_string'
collect2: error: ld returned 1 exit status
tools/CMakeFiles/caffe.bin.dir/build.make:111: recipe for target 'tools/caffe' failed
make[2]: *** [tools/caffe] Error 1
CMakeFiles/Makefile2:406: recipe for target 'tools/CMakeFiles/caffe.bin.dir/all' failed
make[1]: *** [tools/CMakeFiles/caffe.bin.dir/all] Error 2
Makefile:117: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by ProgmasterX** [comment]
Fixed it by
$ sudo cp /usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5.so /usr/local/lib/libhdf5.so
$ sudo cp /usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5_hl.so /usr/local/lib/libhdf5_hl.so
$ make

**Comment by longjon** [comment]
Closing this resolved usage/installation issue.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

**Comment by intelfx** [comment]
This is still a code issue and not a "usage/installation" one. Please reopen.

**Comment by kwotsin** [comment]
Hi, I edited the dependencies.cmake file with the edits you gave, but when I run makepkg the file gets overwritten again. How do I stop this?

**Comment by intelfx** [comment]
@kwotsin: patch sources, then run `makepkg -e`.

**Comment by jakirkham** [comment]
Also having this issue. Did a patch ever make it in upstream?

**Comment by bragilee** [comment]
@longjon  Hi, I have copied two files to the /usr/local/lib, but cannot solve this issue. Is there anything I have to pay attention to? Thank you so much.

**Comment by jakirkham** [comment]
Did you apply the patch from PR ( https://github.com/BVLC/caffe/pull/4516 ), @bragilee ?

**Comment by Abdul-Mukit** [comment]
I followed the commit https://github.com/Fazecast/caffe/commit/942d22d075851a0c5735042308e72f8f739f40f5
provided above. It seems to work.

**Comment by npurson** [comment]
well...it doesn't work on me
and I solved it by modifying the file <your_caffe_root>/cmake/Dependencies.cmake as following:

# ---[ HDF5
find_package(HDF5 COMPONENTS HL REQUIRED)
include_directories(SYSTEM ${HDF5_INCLUDE_DIRS} ${HDF5_HL_INCLUDE_DIR})
list(APPEND Caffe_LINKER_LIBS ${HDF5_LIBRARIES})
list(APPEND Caffe_LINKER_LIBS ${HDF5_HL_LIBRARIES}) #added

**Comment by npurson** [comment]
well...it doesn't work on me,
and I solved it by modifying the file <your_caffe_root>/cmake/Dependencies.cmake as following:

---[ HDF5
find_package(HDF5 COMPONENTS HL REQUIRED)
include_directories(SYSTEM ${HDF5_INCLUDE_DIRS} ${HDF5_HL_INCLUDE_DIR})
list(APPEND Caffe_LINKER_LIBS ${HDF5_LIBRARIES})
list(APPEND Caffe_LINKER_LIBS ${HDF5_HL_LIBRARIES}) #added
