### ISSUE TITLE
Caffe python interface cannot read encoded image from LMDB.

### ISSUE THREAD

**Issue by erogol** [BVLC/caffe#3225]
Following code, which I assume it is true, does not work if the the images in LMDB are encoded.
```
import caffe
import lmdb
import numpy as np
from caffe.proto import caffe_pb2

lmdb_env = lmdb.open('/matrix/users/eglge/Libs/caffe_bundle/caffe/data/imagenet/')
lmdb_txn = lmdb_env.begin()
lmdb_cursor = lmdb_txn.cursor()
datum = caffe_pb2.Datum()

for key, value in lmdb_cursor:
    datum.ParseFromString(value)

    label = datum.label
    data = caffe.io.datum_to_array(datum)
```
I got the label value but all other fields in datum returns 0 like channel, height and width.

**Comment by galloguille** [comment]
You could try to read the image as bytes like:

```
from PIL import Image
import cStringIO as StringIO
stream = StringIO.StringIO(datum.data)
image = np.uint8(Image.open(stream))
```

This will read the bytestring stored in datum.data and open it as an image.

**Comment by lukeyeager** [comment]
Note that @galloguille's code would return the data in RGB order instead of BGR order, which is how Caffe would see the data when loading the LMDB with a Data layer.

**Comment by galloguille** [comment]
Yes, thank you for pointing that out, to get the image as BGR
```image_bgr = img[...,::-1]```
will do the trick.
