### ISSUE TITLE
Hardcoded data_ and label_ in Batch class disallow using more than 2 "top" blobs in data layers

### ISSUE THREAD

**Issue by katomaso** [BVLC/caffe#3228]
In order to make caffe more generally usable I feel the necessity to add more blobs into the inputting (data) layers. For example, I might need to assign indices to every record so I keep track WHICH record was misclassified or classified correctly.

Even more, the hardcoding makes methods MinTopBlobs and MaxTopBlobs of DataLayer useless.

Since the indices are the only thing which is (imho) missing I propose simple addition of `meta_` into Batch class.

```
template <typename Dtype>
class Batch {
 public:
  Blob<Dtype> data_, label_, meta_;
};
```

**Comment by shelhamer** [comment]
Closing as better handled by a Python data layer for flexibility.
