### ISSUE TITLE
errors when running FEATURE EXTRACTION:Failed to parse bvlc_reference_caffenet.caffemodel

### ISSUE THREAD

**Issue by Sharonno** [BVLC/caffe#3230]
I followed the tutorial step by step,but I got an error below:
![screenshot from 2015-10-21 17 15 05](https://cloud.githubusercontent.com/assets/9607594/10632492/58fa1990-7817-11e5-90ef-2674ac0531f5.png)

here are my codes:
![screenshot from 2015-10-21 17 00 51](https://cloud.githubusercontent.com/assets/9607594/10632244/ba60cc44-7815-11e5-81b2-33b07a91f44e.png)
 

Is there someone to help me ? Please,thank you very much

**Comment by seanbell** [comment]
Are you using the latest version of caffe master?  Have you verified that the .caffemodel file is downloaded without being corrupted?

**Comment by Sharonno** [comment]
sorry there's something wrong with the caffemodel. thank you

**Comment by seanbell** [comment]
If you figured it out, please close the issue.
