### ISSUE TITLE
extraction feature by opencv

### ISSUE THREAD

**Issue by kingvision** [BVLC/caffe#3231]
Hi:
   I am new to caffe. I want to use opencv to extract feature. But i have no ideas that how to use opencv to extraction feature. can you provide an example?

Thanks

**Comment by seanbell** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
