### ISSUE TITLE
Huge difference in two methods of measuring time for CaffeNet

### ISSUE THREAD

**Issue by 7oud** [BVLC/caffe#3237]
Our GPU is NVIDIA Titan X. We used two methods to measure performance of our GPU on the CaffeNet, the Caffe reference ImageNet model.
One is the C++ pure tool:
![c](https://cloud.githubusercontent.com/assets/7981826/10689391/712af880-79ad-11e5-9bdb-408e2c3e2bdc.png)
The results of recognizing single image for different batches are as follows:
![c1](https://cloud.githubusercontent.com/assets/7981826/10689400/9a85eeba-79ad-11e5-99df-28c8f15b2f6e.png)
The other is the Pycaffe tool:
![p](https://cloud.githubusercontent.com/assets/7981826/10689407/b14a15cc-79ad-11e5-9595-c4e2f11339c5.png)
The results of recognizing single image for different batches are as follows:
![p1](https://cloud.githubusercontent.com/assets/7981826/10689418/bd728abe-79ad-11e5-8983-50b2295c7cb9.png)
It can be seen that there are huge differences in two methods of measuring time for CaffeNet, and with  the batch increasing,especially when the batch size >128, the time of recognizing an image is almost unchanged. What happened?

**Comment by 7oud** [comment]
Is there anyone using Titan X, could u tell your performance? Thanks

**Comment by longjon** [comment]
Pycaffe's `Net.forward` does contain some Python code which creates additional overhead, so this is not too surprising. (I assume your units are milliseconds here?) If you want to dig into internals, `Net._forward` provides a rawer interface.

I'm closing for now as the answer here is: `caffe time` is for benchmarking, and you'll need to consider overhead when using `Net.forward`. There are, however, some fairly simple improvements that could be done to make `Net.forward` faster in some situations, so if the overhead is a problem for your specific application, you're welcome to open an issue about it.

**Comment by ujsyehao** [comment]
@longjon Can you tell me how to accelerate pycaffe net.forward() consume time?
