### ISSUE TITLE
[test] support several types of TEST input at one prototxt model

### ISSUE THREAD

**Issue by xjsXjtu** [BVLC/caffe#3246]
Hi,

I am new to CAFFE. For training phase, it makes sense that only one type is supported. Because we mostly pre-process the training images. But for testing phase, sometimes we want to validate ImageNet accuracy, and this is suitable for "data" input. Sometimes, I also want to use the same prototxt model to predict one single raw image, and this needs the input type is "imagedata". 

I know Pycaffe can easily handle this, which is shown in the 00-example. I don't know whether CPP interface already supports this. Otherwise, I would like to modify caffe.cpp to support this. My idea is to add another input TEST layer in the prototxt model.  And Only one input layer is selected by command line.Or maybe you guys have better solutions? :) 

Thanks a lot in advance.

**Comment by longjon** [comment]
Closing as this looks like a request for help.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
