### ISSUE TITLE
Train with GPU and Test with CPU

### ISSUE THREAD

**Issue by aiaiaiyouwei** [BVLC/caffe#3249]
I am new in caffe. There are two questions I want to ask. Please give me some suggestion!
1. Can I train the model with GPU and recognize with CPU only?
2. Does caffe has CPU train mode with multi CPUs?

**Comment by vimalthilak** [comment]
@aiaiaiyouwei Please post usage questions like the above to caffe users group https://groups.google.com/forum/#!forum/caffe-users
