### ISSUE TITLE
pycaffe get Power layer params

### ISSUE THREAD

**Issue by johnkorn** [BVLC/caffe#3251]
Hi, all!
I need to extract *power*, *shift* and *scale* parameters of *Power* layer from loaded *caffe.Net* object. How can I do it? I can't find it anywhere (tried *net.params*, *net.blobs*, *net.layers*).

**Comment by seanbell** [comment]
You can load the prototxt object itself and extract it from there.  It's not part of the `caffe` python interface.

**Comment by johnkorn** [comment]
Could you please provide a code example of how to do it?

**Comment by johnkorn** [comment]
Here is what I came up with:
```python
from google.protobuf import text_format
from caffe.proto import caffe_pb2

net = caffe_pb2.NetParameter()
text_format.Merge(open(MODEL_FILE).read(),netproto)

if net.layer[0].type=='Power':
    print net.layer[0].power_param.shift
```
