### ISSUE TITLE
[ BVLC_Alexnet Caffe Model, Torch] : Misclassification ??

### ISSUE THREAD

**Issue by HarshaVardhanP** [BVLC/caffe#3253]
Hello,
I have loaded bvlc_alexnet caffe model in Torch and classifying the images from ImageNet Dataset. I am unable to interpret the answers based on class labels. I am printing out the index of class label that has highest probability. I am getting '670' & '795' for most of the images. I have tried with more than 5 images per class (elephant, black olive, beer bottles, digital clock). 
Would someone please help me interpreting these results. Also, would someone help me with decoding true labels of 1000 classes (bvlc_alexnet caffe model) corresponding to synset_words.txt (ImageNet)
 
Few of them are :
![elephant2](https://cloud.githubusercontent.com/assets/5204400/10780115/5b5d3b42-7d10-11e5-9d58-11b26ad113b2.jpg)
![blackolive](https://cloud.githubusercontent.com/assets/5204400/10780142/b125c882-7d10-11e5-9e49-14e65089dff3.jpg)
![beerb1](https://cloud.githubusercontent.com/assets/5204400/10780152/bd45d1c0-7d10-11e5-9fed-989dbb3d0f79.jpg)
![dc1](https://cloud.githubusercontent.com/assets/5204400/10780153/c28f6b3c-7d10-11e5-8915-0c1deb446ec2.jpeg)

My code is as follows:
-----------------------------
require 'clnn'
require 'ccn2'
require 'loadcaffe'
require 'nn'
require 'inn'
require 'cunn'
require 'image'
model = loadcaffe.load('deploy.prototxt.lua','bvlc_alexnet.caffemodel','ccn2')
model:evaluate()
--print(model)
--reading images of batch size 32
img = image.load('elephant.jpeg')
img_sca = image.scale(img,227,227)
imB =torch.CudaTensor(32,3,227,227)
for i = 1,32 do imB[i]=img_sca end 

--passing it to model--
model:forward(imB)

--Classification--
op26 = model.modules[26].output[1]
max_op26, class_idx = torch.max(op26,1)
print(class_idx)

**Comment by shelhamer** [comment]
*Please do not post usage, installation, or modeling questions, or other requests for help to Issues* as stated in the [contributing guide](https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md).

Furthermore this is a Torch and not Caffe usage question so try the [Torch mailing list](https://groups.google.com/forum/embed/?place=forum%2Ftorch7#!forum/torch7).
