### ISSUE TITLE
Error:too many values to unpack

### ISSUE THREAD

**Issue by Sharonno** [BVLC/caffe#3255]
I tried to train a custom SVM classifier on top of CNN features. I used bvlc_googlenet and trained svc model.When it comes to predicting the class of a new image using the trained SVM, something goes wrong:
![screenshot from 2015-10-28 17 40 14](https://cloud.githubusercontent.com/assets/9607594/10784782/f8d7a1c0-7d9a-11e5-9f9f-ff1fdf2c1b98.png)
here are my codes,with feat.shape==(10,1024,1,1)
![screenshot from 2015-10-28 17 43 58](https://cloud.githubusercontent.com/assets/9607594/10784888/7f2d14c6-7d9b-11e5-93d9-abe0581389cd.png)

![screenshot from 2015-10-28 17 42 35](https://cloud.githubusercontent.com/assets/9607594/10784856/527ed374-7d9b-11e5-80dc-89f02cb25640.png)

![screenshot from 2015-10-28 17 37 15](https://cloud.githubusercontent.com/assets/9607594/10784757/d4493440-7d9a-11e5-94af-a2a19614ca56.png)

I have no idea what's wrong with my feat or model. Can someone help me, please!Thank you very much.

**Comment by seanbell** [comment]
See https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

_Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

**Comment by seanbell** [comment]
(In your case you probably just need to reshape and/or transpose your data so that it fits the expectations of scikit-learn.  This isn't really a problem with caffe, but more a general python debugging question, so it doesn't belong here.)
