### ISSUE TITLE
L1 regularization of fully connected layer

### ISSUE THREAD

**Issue by rinabao** [BVLC/caffe#3256]
Can caffe set L1 regularization specifically for some layer while other layers set L2 regularization? Not set in the solver.prototxt, but set for each layer using different regularization.

**Comment by longjon** [comment]
Closing as this looks like a request for help.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
