### ISSUE TITLE
error compiling on Fedora: undefined reference to `fLB::FLAGS_alsologtostderr'

### ISSUE THREAD

**Issue by Strateus** [BVLC/caffe#3258]
after make all

    ...
    .build_debug/tools/convert_imageset.o: In function `main':
    /home/igor/caffe/tools/convert_imageset.cpp:49: undefined reference to `fLB::FLAGS_alsologtostderr'
    collect2: error: ld returned 1 exit status
    make: *** [.build_debug/tools/convert_imageset.bin] Error 1
    make: *** Waiting for unfinished jobs....
    [root@localhost caffe]# 

what's wrong here?

**Comment by longjon** [comment]
Closing as this looks like a gflags installation issue; you're welcome to try caffe-users.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
