### ISSUE TITLE
HELP!!! MATLAB & memory data layer

### ISSUE THREAD

**Issue by ryanorchid** [BVLC/caffe#3260]
Recently, I need to use caffe to realise and design an algorithm.
I use MATLAB(Ubuntu14.04) to build caffe.
But when I run solver.solve(), it displays that memory data layer should be initialised by calling Reset.
The official tutorial says how to call Reset in C++ or Python, but there is nothing about MATLAB.
Is there anyone know how to call Reset in MATLAB?
sincerely, thx~

**Comment by seanbell** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

**Comment by ronghanghu** [comment]
Unfortunately currently MemoryDataLayer is not supported in Matlab interface. We may add it recently.

**Comment by san-bil** [comment]
Would also greatly appreciate support for this.

**Comment by joyousrabbit** [comment]
Yes, we need it.
