### ISSUE TITLE
ReadProtoFromBinaryFile error

### ISSUE THREAD

**Issue by kantkris** [BVLC/caffe#3263]
Using this standard example http://caffe.berkeleyvision.org/gathered/examples/feature_extraction.html with caffe results in an error 
Check failed: ReadProtoFromBinaryFile(filename, proto) 
**\* Check failure stack trace: ***
    @     0x7fa06696edbd  google::LogMessage::Fail()
    @     0x7fa066970c5d  google::LogMessage::SendToLog()
    @     0x7fa06696e9ac  google::LogMessage::Flush()
    @     0x7fa06697157e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fa06c3a2af9  caffe::DataTransformer<>::DataTransformer()
    @     0x7fa06c3f74fe  caffe::BaseDataLayer<>::LayerSetUp()
    @     0x7fa06c3f763e  caffe::BasePrefetchingDataLayer<>::LayerSetUp()
    @     0x7fa06c3c1d6a  caffe::Net<>::Init()
    @     0x7fa06c3c3ba7  caffe::Net<>::Net()
    @           0x408839  feature_extraction_pipeline<>()
    @     0x7fa063102ec5  (unknown)
    @           0x404439  (unknown)
Aborted (core dumped)

I also tried changing the io.cpp file to O_RDONLY to O_BINARY|O_RDONLY but the make fails

**Comment by shaibagon** [comment]
Please use the [caffe-users list][1] for usage, installation, or modeling questions, or other requests for help.
You may also post questions on [stackoverflow][3], make sure you tag them with `caffe` tag.  
There is also [caffe.help][4] documenting the different layers of caffe.
Do not post such requests to Issues. Doing so interferes with the development of Caffe.

Please read the [guidelines for contributing][2] before submitting this issue.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
 [3]: http://stackoverflow.com/questions/tagged/caffe
 [4]: http://caffe.help/manual/layers.html

**Comment by lauraslopes** [comment]
I have the same error. Did you find the solution?
