### ISSUE TITLE
Caffe half precision

### ISSUE THREAD

**Issue by forever3000** [BVLC/caffe#3265]
Hi,

I notice that Caffe hard code to be single precision, is it possible to change it to half by specifying a parameter in the protocol files? We want run Caffe on Jetson TK1 (reference link : https://developer.nvidia.com/jetson-tk1) and I want to optimize classification time. Currently, classification each image on this board will take about 50ms. I want to optimize to 5ms, the accuracy can lower than normal. Beside that, is there any way to change quantization to decrease classification time?

Thanks

**Comment by longjon** [comment]
Closing as a request for help. (But note that half precision is a desideratum for the future.)

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
