### ISSUE TITLE
Matcaffe fails to build

### ISSUE THREAD

**Issue by varunagrawal** [BVLC/caffe#3266]
I am able to install Caffe just fine. However, when I run `make matcaffe`, I get the following error

    ld: symbol(s) not found for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    
        mex: link of ' "matlab/+caffe/private/caffe_.mexmaci64"' failed.
    
    make: *** [matlab/+caffe/private/caffe_.mexmaci64] Error 255

Please provide the right way to install Matcaffe.

**Comment by varunagrawal** [comment]
Found a fix. It seems that the mexopts.sh file does not set the LDFLAGS variable correctly.
Just add the following line after the last LDFLAGS assignment for your linker:
`LDFLAGS="$LDFLAGS -L/usr/local/lib"`

**Comment by kalpanki** [comment]
I am having the same problem and unfortunately, the above fix doesn't work. I am on Mac os 10.10.5 with CPU only setting. Please help.
