### ISSUE TITLE
how does the solver execute iteration?

### ISSUE THREAD

**Issue by ryanorchid** [BVLC/caffe#3269]
I have a question:
Assume my dataset has 10000 images and I set the value of 'batch_size' as 100. Then after 100 iterations, all images in the dataset has been used to update net weights. But the value of 'max_iter' is set as a bigger number, e.g. max_iter = 200. I want to know how does the solver choose images to update weights during iteration from 101 to 200.
Is anyone knowing about this?
thx~~

**Comment by DaleSong89** [comment]
1. Before training, caffe will skip a numer of images randomly of which the max value  can be set by "data_param{ rand_skip = ***}" in your prototxt of net defination, using a pointer, namely, "shared_ptr<db::Cursor> Datalayer<Dtype>::cursor", pointed to your db(leveldb or lmdb) files that is converted from your 10000 images. (For this, you can read "DataLayer<Dtype>::DataLayerSetUp()" method in src/data_layer.cpp file.) And that pointer records the positon that the datalayer reads from your image sequence in your db files. 
2. During training, the pointer keeps using "cursor_->Next()" to read the following images and it will use "cursor_->valid()" to judge whether it has reached the last image of you db files. If it is, "cursor_->SeekToFirst()" will make the pointer back to the first image of your db files after it reads the last one. (For this, you can read "DataLayer<Dtype>::InternalThreadEntry()" in the same .cpp file.)
3. Circulates as step 2.
So, the 101st to 200th images should be coresponding to the 1st to 100th images exactly if you set "data_param{ rand_skip = 0}".

**Comment by ryanorchid** [comment]
thx for ur explaining! it helps me a lot. @DaleSong89

**Comment by longjon** [comment]
Closing as a request for help. Please keep these conversations to caffe-users.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
