### ISSUE TITLE
how to solve this question with cuDNN v3

### ISSUE THREAD

**Issue by wqysq** [BVLC/caffe#3270]
when I run "cmake . -DCMAKE_BUILD_TYPE=Debug     # switch to debug
make -j 12 && make install           # installs by default to build_dir/install
cmake . -DCMAKE_BUILD_TYPE=Release   # switch to release
make -j 12 && make install           # doesn’t overwrite debug install
make symlink"

the termial display "home/cwt/deb/caffe/include/caffe/vision_layers.hpp:310:3: error: ‘cudnnConvolutionBwdFilterAlgo_t’ does not name a type
   cudnnConvolutionBwdFilterAlgo_t *bwd_filter_algo_;
   ^
/home/cwt/deb/caffe/include/caffe/vision_layers.hpp:311:3: error: ‘cudnnConvolutionBwdDataAlgo_t’ does not name a type
   cudnnConvolutionBwdDataAlgo_t *bwd_data_algo_;
   ^
/home/cwt/deb/caffe/include/caffe/vision_layers.hpp:477:3: error: ‘cudnnLRNDescriptor_t’ does not name a type
   cudnnLRNDescriptor_t norm_desc_;
   ^
/home/cwt/deb/caffe/include/caffe/vision_layers.hpp:504:3: error: ‘cudnnLRNDescriptor_t’ does not name a type
   cudnnLRNDescriptor_t norm_desc_;
"
But I run caffe OK,someone who can tell me how to solve the question?

**Comment by longjon** [comment]
Closing as this looks like a cuDNN installation issue.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
