### ISSUE TITLE
Calculation in Convolution layer

### ISSUE THREAD

**Issue by ryanorchid** [BVLC/caffe#3271]
I examined that the calculation in convolution layer is as follows.
Assume that feature maps from previous layer are 10 * 3 * 28 * 28, denoted as F1, and paramters of convolution layer is that kernel_size is 5 * 5 and num_output = 20. Then, the shape of 'params' blob should be 20 * 3 * 5 * 5, denoted as W, and the shape of output should be 10 * 20 * 24 * 24, denoted as F2. 
For the feature map output of the first unit in convolution layer, it is the sum of three different convolution result, i.e. F2(1, 1, :, :) = sum(F1(1, 1, :, :)convW(1, 1, :, :) + F1(1, 2, :, :)convW(1, 2, :, :) + F1(1, 3, :, :)convW(1, 3, :, :) + b(1)). ( b(1) is bias term)
It shows that  the default is that convolution layer provide an output map that involves a sum over all convolutions of previous input maps. But how can I define a layer do calculation that won't sum over all combinations of previous feature maps?

**Comment by longjon** [comment]
Closing as a request for help.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
