### ISSUE TITLE
make: execvp: .build_release/tools/caffe permission denied

### ISSUE THREAD

**Issue by zhengxiawu123** [BVLC/caffe#3273]
make: execvp: .build_release/tools/caffe permission denied

**Comment by longjon** [comment]
Closing this as it appears to contain no meaningful content.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

**Comment by zhengxiawu123** [comment]
@longjon thanks for your help:)
