### ISSUE TITLE
ArgMaxLayer Reshape missing checks for legacy path

### ISSUE THREAD

**Issue by AndKo1201** [BVLC/caffe#3274]
- build caffe_test with debug_lvl==2
- run test NetTest, TestSkipPropagateDown
- you will get an OutOfBound assertion in ArgMaxLayer<Dtype>::Reshape for __shape[2] = top_k_;__
 - num_axes of bottom[0] is 2 and the value of has_axis_ is false
 - shape will be initialized with a size of two
 - the access to index 2 in shape causes the assert

I don't know if this is really a bug or if just the net configuration for this unittest is incorrect.
The change in the ArgMaxLayer was introduced with PR #3069.

**Comment by longjon** [comment]
Thanks for the report. It looks #3069 mixed new reshape code with legacy 4d shape code resulting in this error. It may be that checks just need to be added for this case, though I'm not sure what's up with the apparent test failure.

**Comment by timmeinhardt** [comment]
It is definitely a bug, which I am sorry for. I use the bottom blob to shape the top blob and before the new reshape code the bottom blob always had enough axes to incorporate the top output. I will fix that and open a new PR. Thank you for pointing out the error!
