### ISSUE TITLE
top_k parameter doesn't take any effect

### ISSUE THREAD

**Issue by cysin** [BVLC/caffe#3280]
top_k parameter doesn't take any effect in ArgMax layer, could someone have a review on argmax_layer.cpp? There's definitely a bug, there is a line:

```
shape[2] = top_k_;
```
and shape was initialized with std::vector<int> shape(bottom[0]->num_axes(), 1)
and sometimes shape was only with size = 2!

**Comment by longjon** [comment]
Thanks for the report, I'm closing as a duplicate of #3274.
