### ISSUE TITLE
protoc no such file or directory

### ISSUE THREAD

**Issue by stianSjoli** [BVLC/caffe#3283]
Dear developer, 
I get the following error when writing (sudo) make all on MAC OS X
Password:
PROTOC src/caffe/proto/caffe.proto
make: protoc: No such file or directory
make: *** [.build_release/src/caffe/proto/caffe.pb.cc] Error 1

i find it odd as I clearly see that the file is there..

**Comment by ZhangXinNan** [comment]
Can you make sure all dependencies is installed ? All is linked ? Path is setted ?

**Comment by longjon** [comment]
Closing as this looks like an issue with protobuf installation; you're welcome to try caffe-users.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

Also, _please do not build as root_!
