### ISSUE TITLE
Linker issue with "libpython2.7.dylib" 

### ISSUE THREAD

**Issue by consciousgaze** [BVLC/caffe#3284]
Hi, 
I am building caffe on a mac OSX 10.11.1. I got the following error which seems to be a new issue.
```
ld: can't link with a main executable file '/Library/Frameworks/Python.framework/Versions/2.7/lib/libpython2.7.dylib' for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [.build_release/lib/libcaffe.so] Error 1
```
I have changed my Makefile.config properly and have also installed cuda 7. 

This is my first time encounter this issue so I have no idea what else information should be provided. Please bear me if the issue description is not clear enough.

**Comment by ronghanghu** [comment]
Please do not post usage, installation, or modeling questions, or other requests for help to Issues.
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

**Comment by ronghanghu** [comment]
Note that there is also linking issue on OS X 10.11 (#3227), but seems different than this one.
