### ISSUE TITLE
extract_features with mnist_autoencoder.prototxt

### ISSUE THREAD

**Issue by kingofoz** [BVLC/caffe#3288]
I want to extract the activation of encode4 layer. However, I get a 'Aborted' error. Can you please give me an idea about where the problem is?
@jeffdonahue @shelhamer @kloudkl

Please see the below:
yingjun@OZ:~/caffe$ ./build/tools/extract_features ~/caffe/examples/mnist/mnist_autoencoder_iter_65000.caffemodel ~/caffe/examples/mnist/mnist_autoencoder.prototxt encode4 ~/test_features 10 lmdb GPU
E1105 17:17:23.871481 31882 extract_features.cpp:54] Using GPU
E1105 17:17:23.872267 31882 extract_features.cpp:60] Using Device_id=0
F1105 17:17:24.187971 31882 insert_splits.cpp:35] Unknown bottom blob 'data' (layer 'flatdata', bottom index 0)
*** Check failure stack trace: ***
    @     0x7f8fda70fdaa  (unknown)
    @     0x7f8fda70fce4  (unknown)
    @     0x7f8fda70f6e6  (unknown)
    @     0x7f8fda712687  (unknown)
    @     0x7f8fdaa9d206  caffe::InsertSplits()
    @     0x7f8fdabf47fd  caffe::Net<>::Init()
    @     0x7f8fdabf7578  caffe::Net<>::Net()
    @           0x40878a  feature_extraction_pipeline<>()
    @     0x7f8fd9b3eec5  (unknown)
    @           0x4044de  (unknown)
    @              (nil)  (unknown)
Aborted (core dumped)

**Comment by longjon** [comment]
Closing as this looks like a request for help.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

**Comment by kingofoz** [comment]
I have a post in caffe-users list: https://groups.google.com/forum/#!topic/caffe-users/ULfCYk4fGOY
Can you give me a little advice?

**Comment by kingofoz** [comment]
This is a core dump issue, so it may be a product bug. I really need your help. Please look into it and give me some advice.

**Comment by kingofoz** [comment]
Nobody responds to my post in caffe-users. Can you guys give me a little advice?
@jeffdonahue @shelhamer @kloudkl

**Comment by kingofoz** [comment]
@longjon 
Can you please give some help?
