### ISSUE TITLE
Second Layer Information from Caffe

### ISSUE THREAD

**Issue by sid027** [BVLC/caffe#3291]
Hi all,
Can I extract the second layer information during training instead of going all the way to the last layer during the training process.The training takes too much time and the second layer information seems to be good enough for most the purposes I want to use this model for.

Sid

**Comment by seanbell** [comment]
Yes.  Just delete all layers after the ones you want to compute in the deploy prototext file.  The weight copying mechanism silently skips missing layers, so this should do what you want.

Also,
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
