### ISSUE TITLE
extract_features's issue: Cannot copy param 0 weights from layer 'encode1'; shape mismatch.  Source param shape is 1000 784 (784000); target param shape is 1000 2352 (2352000). 

### ISSUE THREAD

**Issue by kingofoz** [BVLC/caffe#3293]
Hi all,
Please see the output:
yingjun@OZ:~/caffe$ ./build/tools/extract_features.bin examples/mnist/mnist_autoencoder_iter_65000.caffemodel examples/_temp/mnist_autoencoder.prototxt encode4 examples/_temp/features 10 lmdb GPU
E1106 17:26:15.961053  2052 extract_features.cpp:54] Using GPU
E1106 17:26:15.961582  2052 extract_features.cpp:60] Using Device_id=0
F1106 17:26:16.755717  2052 net.cpp:829] Cannot copy param 0 weights from layer 'encode1'; shape mismatch.  Source param shape is 1000 784 (784000); target param shape is 1000 2352 (2352000). To learn this layer's parameters from scratch rather than copying from a saved net, rename the layer.
*** Check failure stack trace: ***
    @     0x7faf70f26daa  (unknown)
    @     0x7faf70f26ce4  (unknown)
    @     0x7faf70f266e6  (unknown)
    @     0x7faf70f29687  (unknown)
    @     0x7faf714012f9  caffe::Net<>::CopyTrainedLayersFrom()
    @     0x7faf71408902  caffe::Net<>::CopyTrainedLayersFromBinaryProto()
    @     0x7faf71408966  caffe::Net<>::CopyTrainedLayersFrom()
    @           0x4087e9  feature_extraction_pipeline<>()
    @     0x7faf70355ec5  (unknown)
    @           0x4044de  (unknown)
    @              (nil)  (unknown)
Aborted (core dumped)

I made some changes in examples/_temp/mnist_autoencoder.prototxt, please see:
name: "MNISTAutoencoder"
layer {
  name: "data"
  type: "ImageData"
  top: "data"
  top: "label"
  transform_param {
    mirror: false
  }
  image_data_param {
    source: "examples/_temp/file_list.txt"
    batch_size: 100
    new_height: 28
    new_width: 28
  }
}
layer {
  name: "encode1"
  type: "InnerProduct"
  bottom: "data"
  top: "encode1"
  param {
    lr_mult: 1
    decay_mult: 1
  }
  param {
    lr_mult: 1
    decay_mult: 0
  }
  inner_product_param {
    num_output: 1000
    weight_filler {
      type: "gaussian"
      std: 1
      sparse: 15
    }
    bias_filler {
      type: "constant"
      value: 0
    }
  }
}
layer {
  name: "encode1neuron"
  type: "Sigmoid"
  bottom: "encode1"
  top: "encode1neuron"
}
layer {
  name: "encode2"
  type: "InnerProduct"
  bottom: "encode1neuron"
  top: "encode2"
  param {
    lr_mult: 1
    decay_mult: 1
  }
  param {
    lr_mult: 1
    decay_mult: 0
  }
  inner_product_param {
    num_output: 500
    weight_filler {
      type: "gaussian"
      std: 1
      sparse: 15
    }
    bias_filler {
      type: "constant"
      value: 0
    }
  }
}
layer {
  name: "encode2neuron"
  type: "Sigmoid"
  bottom: "encode2"
  top: "encode2neuron"
}
layer {
  name: "encode3"
  type: "InnerProduct"
  bottom: "encode2neuron"
  top: "encode3"
  param {
    lr_mult: 1
    decay_mult: 1
  }
  param {
    lr_mult: 1
    decay_mult: 0
  }
  inner_product_param {
    num_output: 250
    weight_filler {
      type: "gaussian"
      std: 1
      sparse: 15
    }
    bias_filler {
      type: "constant"
      value: 0
    }
  }
}
layer {
  name: "encode3neuron"
  type: "Sigmoid"
  bottom: "encode3"
  top: "encode3neuron"
}
layer {
  name: "encode4"
  type: "InnerProduct"
  bottom: "encode3neuron"
  top: "encode4"
  param {
    lr_mult: 1
    decay_mult: 1
  }
  param {
    lr_mult: 1
    decay_mult: 0
  }
  inner_product_param {
    num_output: 30
    weight_filler {
      type: "gaussian"
      std: 1
      sparse: 15
    }
    bias_filler {
      type: "constant"
      value: 0
    }
  }
}
layer {
  name: "decode4"
  type: "InnerProduct"
  bottom: "encode4"
  top: "decode4"
  param {
    lr_mult: 1
    decay_mult: 1
  }
  param {
    lr_mult: 1
    decay_mult: 0
  }
  inner_product_param {
    num_output: 250
    weight_filler {
      type: "gaussian"
      std: 1
      sparse: 15
    }
    bias_filler {
      type: "constant"
      value: 0
    }
  }
}
layer {
  name: "decode4neuron"
  type: "Sigmoid"
  bottom: "decode4"
  top: "decode4neuron"
}
layer {
  name: "decode3"
  type: "InnerProduct"
  bottom: "decode4neuron"
  top: "decode3"
  param {
    lr_mult: 1
    decay_mult: 1
  }
  param {
    lr_mult: 1
    decay_mult: 0
  }
  inner_product_param {
    num_output: 500
    weight_filler {
      type: "gaussian"
      std: 1
      sparse: 15
    }
    bias_filler {
      type: "constant"
      value: 0
    }
  }
}
layer {
  name: "decode3neuron"
  type: "Sigmoid"
  bottom: "decode3"
  top: "decode3neuron"
}
layer {
  name: "decode2"
  type: "InnerProduct"
  bottom: "decode3neuron"
  top: "decode2"
  param {
    lr_mult: 1
    decay_mult: 1
  }
  param {
    lr_mult: 1
    decay_mult: 0
  }
  inner_product_param {
    num_output: 1000
    weight_filler {
      type: "gaussian"
      std: 1
      sparse: 15
    }
    bias_filler {
      type: "constant"
      value: 0
    }
  }
}
layer {
  name: "decode2neuron"
  type: "Sigmoid"
  bottom: "decode2"
  top: "decode2neuron"
}
layer {
  name: "decode1"
  type: "InnerProduct"
  bottom: "decode2neuron"
  top: "decode1"
  param {
    lr_mult: 1
    decay_mult: 1
  }
  param {
    lr_mult: 1
    decay_mult: 0
  }
  inner_product_param {
    num_output: 784
    weight_filler {
      type: "gaussian"
      std: 1
      sparse: 15
    }
    bias_filler {
      type: "constant"
      value: 0
    }
  }
}
layer {
  name: "decode1neuron"
  type: "Sigmoid"
  bottom: "decode1"
  top: "decode1neuron"
}

Below is the content of file_list.txt:
/home/yingjun/caffe/examples/images/cat.jpg 0
/home/yingjun/caffe/examples/images/fish-bike.jpg 0
/home/yingjun/caffe/examples/images/cat_gray.jpg 0

I know these images don't make sense to mnist autoencoder. But I don't think 'shape mismatch' should happen. I resized the images to 28 * 28:
image_data_param {
    source: "examples/_temp/file_list.txt"
    batch_size: 100
    new_height: 28
    new_width: 28
  }

**Comment by kingofoz** [comment]
@jeffdonahue @shelhamer @kloudkl
Please give me some suggestion. I really need your help. Thanks!

**Comment by seanbell** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

**Comment by YaoChou** [comment]
Hi @kingofoz ,

Got similar problem recently, did you get the answer? Thanks.

YAO
