### ISSUE TITLE
I have  problem when I use the cmake method to compile the caffe with the cudnn

### ISSUE THREAD

**Issue by lji72** [BVLC/caffe#3298]
ubuntu 15,4
cuda:7.0
cudnn: cudnn-linux64-6.5-v2

The problem are as follow:

src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_cudnn_sigmoid_layer.cu.o
/home/shaoshu/software/caffe/caffe/include/caffe/vision_layers.hpp(310): error: identifier "cudnnConvolutionBwdFilterAlgo_t" is undefined

/home/shaoshu/software/caffe/caffe/include/caffe/vision_layers.hpp(311): error: identifier "cudnnConvolutionBwdDataAlgo_t" is undefined

/home/shaoshu/software/caffe/caffe/include/caffe/vision_layers.hpp(477): error: identifier "cudnnLRNDescriptor_t" is undefined

/home/shaoshu/software/caffe/caffe/include/caffe/vision_layers.hpp(504): error: identifier "cudnnLRNDescriptor_t" is undefined

/home/shaoshu/software/caffe/caffe/include/caffe/vision_layers.hpp(310): error: identifier "cudnnConvolutionBwdFilterAlgo_t" is undefined

/home/shaoshu/software/caffe/caffe/include/caffe/vision_layers.hpp(311): error: identifier "cudnnConvolutionBwdDataAlgo_t" is undefined

/home/shaoshu/software/caffe/caffe/include/caffe/vision_layers.hpp(477): error: identifier "cudnnLRNDescriptor_t" is undefined

/home/shaoshu/software/caffe/caffe/include/caffe/vision_layers.hpp(504): error: identifier "cudnnLRNDescriptor_t" is undefined

/home/shaoshu/software/caffe/caffe/include/caffe/vision_layers.hpp(310): error: identifier "cudnnConvolutionBwdFilterAlgo_t" is undefined

/home/shaoshu/software/caffe/caffe/include/caffe/vision_layers.hpp(311): error: identifier "cudnnConvolutionBwdDataAlgo_t" is undefined

/home/shaoshu/software/caffe/caffe/include/caffe/vision_layers.hpp(477): error: identifier "cudnnLRNDescriptor_t" is undefined

/home/shaoshu/software/caffe/caffe/include/caffe/vision_layers.hpp(504): error: identifier "cudnnLRNDescriptor_t" is undefined

/home/shaoshu/software/caffe/caffe/include/caffe/vision_layers.hpp(310): error: identifier "cudnnConvolutionBwdFilterAlgo_t" is undefined

/home/shaoshu/software/caffe/caffe/include/caffe/vision_layers.hpp(311): error: identifier "cudnnConvolutionBwdDataAlgo_t" is undefined

/home/shaoshu/software/caffe/caffe/include/caffe/vision_layers.hpp(477): error: identifier "cudnnLRNDescriptor_t" is undefined

/home/shaoshu/software/caffe/caffe/include/caffe/vision_layers.hpp(504): error: identifier "cudnnLRNDescriptor_t" is undefined
cloud you tell me how to solve the problem?

**Comment by seanbell** [comment]
Yes, the current master branch only supports cudnn v3.  If you want to use cudnn v2, use an older commit.

Also, from https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

**Comment by lji72** [comment]
Thank you.it works.

**Comment by wqlw** [comment]
hello，l have some problems like this：
[  1%] Running C++/Python protocol buffer compiler on /home/wei/caffe/caffe-master-root/src/caffe/proto/caffe.proto
Scanning dependencies of target proto
[  1%] Building CXX object src/caffe/CMakeFiles/proto.dir/__/__/include/caffe/proto/caffe.pb.cc.o
[  1%] Linking CXX static library ../../lib/libproto.a
[  1%] Built target proto
[  1%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/solvers/cuda_compile_generated_rmsprop_solver.cu.o
/home/wei/caffe/caffe-master-root/include/caffe/util/cudnn.hpp(141): error: identifier "cudnnActivationDescriptor_t" is undefined

1 error detected in the compilation of "/tmp/tmpxft_0000386c_00000000-7_rmsprop_solver.cpp1.ii".
CMake Error at cuda_compile_generated_rmsprop_solver.cu.o.cmake:266 (message):
  Error generating file
  /home/wei/caffe/caffe-master-root/src/caffe/CMakeFiles/cuda_compile.dir/solvers/./cuda_compile_generated_rmsprop_solver.cu.o


make[2]: *** [src/caffe/CMakeFiles/cuda_compile.dir/solvers/cuda_compile_generated_rmsprop_solver.cu.o] 错误 1
make[1]: *** [src/caffe/CMakeFiles/caffe.dir/all] 错误 2
make: *** [all] 错误 2
would you help me please？

**Comment by seanbell** [comment]
I'm closing this thread since we're on a new version of cuDNN by now (v4 and soon v5).

@wqlw please try asking the mailing list for help with installation.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

**Comment by wqlw** [comment]
now my cudnn's version is v3,i am a new one .would you tell me what i do ? i shoule update the cudnn v5 or v4 please?@seanbell thanks

**Comment by seanbell** [comment]
For now, you should use v4.  It will take a little while before v5 is merged in.

**Comment by shelhamer** [comment]
p.s. as of #4159 cuDNN v5 is API compatible, but we're not yet making use of its latest algorithms for further acceleration yet.
