### ISSUE TITLE
Could caffe display message "Ignore source layer xxx" by default when fine-tuning or testing a net?

### ISSUE THREAD

**Issue by tianzhi0549** [BVLC/caffe#3302]
https://github.com/BVLC/caffe/blob/master/src/caffe/net.cpp#L748

I suggest that caffe should change DLOG() to LOG() and displays "Ignore xxx" when debug_info=true or always displays that. Now this message only appears when building caffe with DEBUG:=1.

If do so, when someone types a error mismatch layer name, caffe could hint him even if he doesn't turn DEBUG on when building.

Thank you:-)!

**Comment by ronghanghu** [comment]
Yes, I think we should have this message displayed not only in debug mode. I will create a PR on that.

**Comment by ronghanghu** [comment]
Note that to correctly display messages during fine-tuning or testing a net, one also needs to modify `Net::CopyTrainedLayersFrom`.

**Comment by tianzhi0549** [comment]
Thank you for your PR:-).
