### ISSUE TITLE
make all failed

### ISSUE THREAD

**Issue by heyJoe11** [BVLC/caffe#3314]
I'm trying to install Caffe on Debian, but when i do `make all` i get this error:
```
/usr/bin/ld: /usr/local/lib/libglog.a(logging.cc.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libglog.a: could not read symbols: Bad value
collect2: error: ld returned 1 exit status make: *** [.build_release/lib/libcaffe.so] Error 1

```
what should i do?

**Comment by seanbell** [comment]
Looks like glog wasn't installed properly?

**Comment by seanbell** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

This looks like a request for help so I am closing this, but if you think you found a bug with caffe, please re-open.
