### ISSUE TITLE
Model Zoo - GoogLeNet_cars

### ISSUE THREAD

**Issue by mvvardhan** [BVLC/caffe#3316]
Hi,

I am trying to download the model GoogLeNet_cars using the following command but I get an error. 

./scripts/download_model_from_gist.sh b90eb88e31cd745525ae models/googlenet_finetune_web_car

Downloading Caffe model info to models/googlenet_finetune_web_car/b90eb88e31cd745525ae ...

--2015-11-11 11:30:04--  https://gist.github.com/b90eb88e31cd745525ae/download

Resolving gist.github.com (gist.github.com)... 192.30.252.140

Connecting to gist.github.com (gist.github.com)|192.30.252.140|:443... connected.

HTTP request sent, awaiting response... 302 Found

Location: https://gist.github.com/bogger/b90eb88e31cd745525ae/download [following]

--2015-11-11 11:30:04--  https://gist.github.com/bogger/b90eb88e31cd745525ae/download

Reusing existing connection to gist.github.com:443.

HTTP request sent, awaiting response... 302 Found

Location: https://codeload.github.com/bogger/b90eb88e31cd745525ae/zip/master [following]

--2015-11-11 11:30:04--  https://codeload.github.com/bogger/b90eb88e31cd745525ae/zip/master

Resolving codeload.github.com (codeload.github.com)... 192.30.252.147

Connecting to codeload.github.com (codeload.github.com)|192.30.252.147|:443... connected.

HTTP request sent, awaiting response... 200 OK

Length: 5066 (4.9K) [application/zip]

Saving to: 'models/googlenet_finetune_web_car/b90eb88e31cd745525ae/gist.tar.gz'

100%[================================================================================================================================================================>] 5,066       --.-K/s   in 0s      

2015-11-11 11:30:04 (51.8 MB/s) - 'models/googlenet_finetune_web_car/b90eb88e31cd745525ae/gist.tar.gz' saved [5066/5066]

gzip: stdin has more than one entry--rest ignored

tar: Child returned status 2

tar: Error is not recoverable: exiting now

Done

Regards,

Vishnu

**Comment by seanbell** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

Please contact the owner of that model.  The issues list is not for discussing models.

**Comment by seanbell** [comment]
That being said, if you think you found a bug in the `download_model_from_gist.sh` script itself (and not in the particular model you chose to download), please re-open the issue.
