### ISSUE TITLE
Is there any model that can be used to train caffe for text data?

### ISSUE THREAD

**Issue by ashiqimran** [BVLC/caffe#3318]

**Comment by seanbell** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

You might be interested in looking for forks of caffe that are more targeted towards LSTMs, e.g. https://github.com/Russell91/nlpcaffe or https://github.com/Russell91/apollocaffe
