### ISSUE TITLE
problem creating "correct" mean binary file on Linux 

### ISSUE THREAD

**Issue by andrewliao11** [BVLC/caffe#3330]
I'm trying to use my dataset to fine-tune the imagenet network. So, first I used the caffe/examples/create_imagenet.sh to createthe convert my dataset into lmdb format. Then, i used the caffe/examples/make_imagenet_mean.sh to create the mean binary file. (I just modify the path in these files)
However, when i tried to fine-tune with python, i got the error like this 
![80](https://cloud.githubusercontent.com/assets/10975252/11139677/5cdba58a-8a0d-11e5-8c57-2d137b467dbb.png)
Some recommended that I modify the file io.cpp (caffe/src/caffe/util/io.cpp) like this "int fd = open(filename, O_RDONLY | O_BINARY);"
but it seemed that this solution is for caffe on Windos

**Comment by seanbell** [comment]
https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
> Please do not post usage, installation, or modeling questions, or other requests for help to Issues. Use the caffe-users list instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

If you think you found a bug in caffe, re-open the issue.  Otherwise, please ask for help on caffe-users, since this looks like a request for help.
