### ISSUE TITLE
How is convolution computed over channels in caffe??

### ISSUE THREAD

**Issue by sjammal** [BVLC/caffe#3334]

**Comment by seanbell** [comment]
https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
