### ISSUE TITLE
Looking for an inception-BN network

### ISSUE THREAD

**Issue by cuihenggang** [BVLC/caffe#3338]
Hi,

I find in the MXNet project, they report most of their results on the Inception-BN network, and I hope to compare the performance of Caffe with MXNet. I'm wondering does anyone here have a train_val file for the inception-BN network?

Thank you!

Cui

**Comment by shaibagon** [comment]
Please use the [caffe-users list][1] for usage, installation, or modeling questions, or other requests for help.
You may also post questions on [stackoverflow][3], make sure you tag them with `caffe` tag.  
There is also [caffe.help][4] documenting the different layers of caffe.
Do not post such requests to Issues. Doing so interferes with the development of Caffe.

Please read the [guidelines for contributing][2] before submitting this issue.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
 [3]: http://stackoverflow.com/questions/tagged/caffe
 [4]: http://caffe.help/manual/layers.html
