### ISSUE TITLE
Question about extracting feature with old matlab wrapper after selective search algorithm?

### ISSUE THREAD

**Issue by tsingtaogemini** [BVLC/caffe#3341]
I am trying to use matcaffe_batch.m to extract image feature for linear svm training. First I applied the selective search to the 5011(VOC Challenge 2007) images within 20 classes, yields around 300 regional proposals per image. Due to the total proposals are large, then I am trying to use matcaffe_batch.m to calculate each 300 proposals of one image with batch size equals to 10 and iterate to all the 5011 images. Finally I fit that features to train svm model. It turns out the svm model is not good enough, not even close to be acceptable. 

My question is that should I take all the 300*5011 proposals as input to extract feature with matcaffe_batch once for all, (does that differ to the one above)  or should I use matcaffe_demo.m calculate one by one which would cost much more time for my computer hardware. Prior to extract feature,
I chopped off all the layers following relu7 in deploy.prototxt of bvlc_caffenet.  SO Could anyone give me a hint about which step could possibly go wrong,
what makes that feature not good enough to train a svm model? Thanks.

**Comment by seanbell** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> Please do not post usage, installation, or modeling questions, or other requests for help to Issues. Use the caffe-users list instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

Sorry, but this is not the right place for this question.  Please try the caffe-users list for modeling questions.
