### ISSUE TITLE
python interface for classification

### ISSUE THREAD

**Issue by wqysq** [BVLC/caffe#3350]
When I use the python interface for classificantion,
it display"classifier.py", line 26, in __init__
    caffe.Net.__init__(self, model_file, pretrained_file)
Boost.Python.ArgumentError: Python argument types in
    Net.__init__(Classifier, str, str)
did not match C++ signature:
    __init__(boost::python::api::object, std::string, std::string, int)
    __init__(boost::python::api::object, std::string, int)
",I can not fix it,someone who can help me,thank you very much!

**Comment by lixiaohuihuixiaoli** [comment]
You may forget an argument with "int" type or add an extra argument with "std::string" type.
I guess what you want to code is caffe.Net.init(self, model_file, pretrained_file, caffe::TEST)?

**Comment by martyychang** [comment]
Hi @wqysq did you resolve this issue? I'm running into the same problem.

**Comment by martyychang** [comment]
The extra `int` parameter [appears to be a "phase"](https://github.com/BVLC/caffe/blob/master/python/caffe/_caffe.cpp). I haven't investigated this further though to determine what an appropriate value is for this param. @lixiaohuihuixiaoli do you know in what file the `caffe::TEST` constant you suggested is defined?

**Comment by ajtulloch** [comment]
`caffe.TEST` in Python - e.g. 

```
net = caffe.Net(prototxt, caffemodel, caffe.TEST)
```
