### ISSUE TITLE
Any tools to convert pretrained mxnet model to model for caffe?

### ISSUE THREAD

**Issue by iamhankai** [BVLC/caffe#3353]
Any tools to convert pretrained mxnet model to model for caffe?

**Comment by RishabGargeya** [comment]
Also interested in this tool - @iamhankai Did you ever find anything?

**Comment by iamhankai** [comment]
https://github.com/n3011/cxxnet_converter

**Comment by pertusa** [comment]
I've made it: https://github.com/pertusa/MXNetToCaffeConverter
And also converted the Inception21k model: https://github.com/pertusa/InceptionBN-21K-for-Caffe
