### ISSUE TITLE
Is there any way to convert ".mat" to ".binaryproto"

### ISSUE THREAD

**Issue by jiqiujia** [BVLC/caffe#3354]

**Comment by seanbell** [comment]
This looks like a request for help.  From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
