### ISSUE TITLE
make runtest failure

### ISSUE THREAD

**Issue by usmanshahid** [BVLC/caffe#3356]
Hi,

I'm trying to compile caffe and came across this error.

.build_release/tools/caffe
.build_release/tools/caffe: error while loading shared libraries: libcudart.so.7.5: cannot open shared object file: No such file or directory
make: *** [runtest] Error 127

Now i've checked that the library exists in the subfolder but the subfolder is named /lib64 not /lib which might be causing the issue. Please help.

I've installed cuda from the debian package 7.5 for 64-bit **cuda-repo-ubuntu1404-7-5-local_7.5-18_amd64.deb**

**[EDIT]** I also have cuda path set in Makefile.config as 

>CUDA_DIR := /usr/local/cuda

**[EDIT2: SOLVED]** I didn't have cuda lib64 in library path, i solved it by maink a conf file in /etc/ld.so.conf.d/

**Comment by ManInBlue1932** [comment]
@usmanshahid   Hi, i meet the same question with you , and i did as you said :   /etc/ld.so.conf.d/libcudart.conf    with  { /usr/local/cuda/lib64 } , it still doesn't work.  is there any error in my seting ?  thank you.

**Comment by usmanshahid** [comment]
Try  [this](http://faculty.uml.edu/vbarsegov/gpu/sopgpu/install_cuda.html)
