### ISSUE TITLE
alway got Library NOT FOUND error

### ISSUE THREAD

**Issue by mavericklam** [BVLC/caffe#3368]
Hi dear,

When I run caffe make runtest on my Mac EI captain I always encounter error like:

.build_release/tools/caffe
dyld: Library not loaded: libmkl_rt.dylib
  Referenced from: /Users/HuenLam/Desktop/caffe/caffe/.build_release/tools/caffe
  Reason: image not found
make: *** [runtest] Trace/BPT trap: 5

when I run make all and make test, it perfectly works. Could anyone help me about it?

Thanks !

**Comment by rohrbach** [comment]
You probably have to add the library to the LD_LIBRARY_PATH.

However, closing as this is a usage issue.

Please ask usage questions on caffe-users: https://groups.google.com/forum/#!forum/caffe-users. 
If you do think there is a bug in Caffe, you're welcome to open a new issue according to https://github.com/BVLC/caffe/wiki/Reporting-Bugs-and-Other-Issues. Thanks!
