### ISSUE TITLE
Can I set two MemoryData Layer as multi Inputs

### ISSUE THREAD

**Issue by mingtop** [BVLC/caffe#3369]
Here is my prototxt
layers {
  type: MEMORY_DATA
  name: "data"
  top: "data"
  top: "label"
  ntop: 2
  memory_data_param {
    batch_size:  10
    channels:    1
    height:      28
    width:       28
  }
}

layers {
  type: MEMORY_DATA
  name: "data2"
  top: "data2"
  top: "label2"
  memory_data_param {
    batch_size:  10
    channels:    2
    height:      1
    width:       1
  }
}
--------------------------------------
But I don't know how to put my data into those two layers:
Xi   10*1*28*28
Yi    10*2*1*1
            solver.net.set_input_arrays(Xi, Yi)            
            solver.net.set_input_arrays(Yi, Yi)
from log  I find caffe memory can only use 1D layer, so I have to set my label(Yi) as another data to input.
But I got a error , when I set_input-array on 2nd time:
%%%%%%%%%
  File "/home/jamin/git/caffe/python/caffe/pycaffe.py", line 243, in _Net_set_input_arrays
    return self._set_input_arrays(data, labels)
RuntimeError: data array has wrong number of channels. 
%%%%%
that because the 2nd set input array dim is 10* 2 , the first set input array is 10*1.

So , Can I put my data separately like this ? Or specific each name when I set inpu array to memeoryLayer?

Or some alter idear to do this ?  Thank you very much!

**Comment by 201power** [comment]
Same question here

**Comment by seanbell** [comment]
Please ask questions about how to use caffe on the mailing list.  Thanks!

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
