### ISSUE TITLE
Can caffe run on GPU-Clusters

### ISSUE THREAD

**Issue by lyblsgo** [BVLC/caffe#3371]
Can this caffe run on GPU-Clusters?
If can't, is there any other versions can?
Thanks~

**Comment by seanbell** [comment]
Is there something special about your cluster?  I don't understand your question.  If it's a linux machine and it has GPUs, then you can install the prerequisites and then run caffe.  Just like you can run any other program.  Also, please ask this on the user list (see below).

From https://raw.githubusercontent.com/BVLC/caffe/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
