### ISSUE TITLE
Is `if (this->phase_ == TRAIN) `  necessary in the backward computation of  dropout_layer implementation ?

### ISSUE THREAD

**Issue by Coldmooon** [BVLC/caffe#3374]
For example, in `src/caffe/layers/dropout_layer.cpp`  
Function implementation: ` void DropoutLayer<Dtype>::Backward_cpu ()` 
part of code is:
```
    if (this->phase_ == TRAIN) {
      const unsigned int* mask = rand_vec_.cpu_data();
      const int count = bottom[0]->count();
      for (int i = 0; i < count; ++i) {
        bottom_diff[i] = top_diff[i] * mask[i] * scale_;
      }
    } else {
      caffe_copy(top[0]->count(), top_diff, bottom_diff);
```

Backward pass is only present in the training stage. So, is this `if (this->phase_ == TRAIN) ... else ...` necessary ? I think removing the conditional sentence still makes sense.

**Comment by seanbell** [comment]
Yes, because you can still call `backward` at test time, e.g. when reconstructing an image using the python interface.

**Comment by Coldmooon** [comment]
@seanbell I see. Thank you very much~
