### ISSUE TITLE
Matcaffe demo Problem

### ISSUE THREAD

**Issue by UsamaShafiq91** [BVLC/caffe#3382]
I successfully build the matlab wrapper by make matcaffe. But when i tried to run the demo. I got following error:

>> matcaffe_demo
Invalid MEX-file '/Users/Altair/Documents/MATLAB/caffe/matlab/caffe/caffe.mexmaci64':
dlopen(/Users/Altair/Documents/MATLAB/caffe/matlab/caffe/caffe.mexmaci64, 6): Library not
loaded: libmkl_rt.dylib
  Referenced from: /Users/Altair/Documents/MATLAB/caffe/matlab/caffe/caffe.mexmaci64
  Reason: image not found

Error in matcaffe_init (line 19)
if caffe('is_initialized') == 0

Error in matcaffe_demo (line 53)
  matcaffe_init();

**Comment by ronghanghu** [comment]
Please do not post usage, installation, or modeling questions, or other requests for help to Issues.
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
