### ISSUE TITLE
How to supervise fine-tuning

### ISSUE THREAD

**Issue by affromero** [BVLC/caffe#3386]
Hi, 
Exist any way to check the properties of my net at the time I am fine-tuning it?
I used to play with matconvnet for Matlab and there, I could see something like this when I were finetuning.
![tt](https://cloud.githubusercontent.com/assets/9055917/11409189/20d3caee-938c-11e5-920f-02b7d6b5fd29.png)
Can I get something like this using caffe?
Thanks!

**Comment by affromero** [comment]
Any idea?

**Comment by williford** [comment]
Questions like these should be asked on the [Caffe user mailing list](https://groups.google.com/forum/#!forum/caffe-users) or on another website, such as http://stackoverflow.com/.

You can just parse the training and testing logs like you would do after training.
