### ISSUE TITLE
Matlab crash on Solver

### ISSUE THREAD

**Issue by UsamaShafiq91** [BVLC/caffe#3387]
All the functions are fine except when i try to create the "solver" by caffe.solver the matlab crashes.

**Comment by ronghanghu** [comment]
Please ask questions only on [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users).

Please do not post usage, installation, or modeling questions, or other requests for help to Issues.
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
