### ISSUE TITLE
Hamming distance not used in Caffe, hinders portability. Remove?

### ISSUE THREAD

**Issue by eelstork** [BVLC/caffe#3403]
Caffe [does not use][1] `hamming_distance`; indirectly, this function limits portability via `__builtin__popcount`.

In #3402 I offer a solution to the compatibility issue.

@ronghanghu suggested that `hamming_distance` may be removed. @longjon , @bhack would you agree that this might be removed?
@kloudkl clearly some work went into this; would you favour removing this function from Caffe?

[1]: https://github.com/BVLC/caffe/search?utf8=✓&q=hamming

**Comment by shelhamer** [comment]
I'm ok with dropping this function since it was never put to use by a completed PR and the disabled tests for it have led to confusion in the past. I'm open to other opinions on this though.

**Comment by longjon** [comment]
Dead code should be removed.

It looks like this was added for use in an example that was never merged. However, even that example does not appear to require this as a feature of Caffe. Unless I have missed something, @ronghanghu is right in #3402; this code does not belong in Caffe.

**Comment by eelstork** [comment]
Submitted a PR.

**Comment by longjon** [comment]
Merged, thanks!

**Comment by futurely** [comment]
It's inevitable to say goodbye to the [Done+Dusted](http://www.doneanddusted.com/). C'est la vie.
