### ISSUE TITLE
the relationship of 2 data layer

### ISSUE THREAD

**Issue by mingtop** [BVLC/caffe#3406]
datalayer1    data:x11  label: label1
datalayer2    data:y11 label: label2
The data in two datalayer has relationship of their  order
x11 ---> y11
x12---->y12
when train in SGD , can they shuffle in the same order >? ??

**Comment by seanbell** [comment]
Turn off shuffling and they will be in sync.  Also note that if you use multi-gpu, there is no way to sync them currently, and you either have to use a single data layer (e.g. a custom python layer), or use only one gpu.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
