### ISSUE TITLE
No rule to target '/usr/local/include/glog/logging.h'

### ISSUE THREAD

**Issue by zmykevin** [BVLC/caffe#3412]
Hi Everyone, 
I tried to install caffe following instructions from Caffe site, and I got an error that I find very few information online that can provide help. 
The operating system is ubuntu 14.04
I installed all the packages following the instructions from the installation guide for ubuntu from caffe
I have opencv 2.4.10
I also installed CUDA 7 following the instructions from the cuda site
The error message that I got is as following:
make: *** No rule to make target `/usr/local/include/glog/logging.h', needed by `.build_release/cuda/src/caffe/layers/conv_layer.o'.  Stop.

Hope I can get some help here. Thank you very much.
P.S This is the first time I post questions, so please also let me know how to specify my problem more clearly so that people can understand the issue better and provide helpful suggestions.

**Comment by seanbell** [comment]
Please ask the mailing list for help with installing caffe.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
