### ISSUE TITLE
something about the ignore value

### ISSUE THREAD

**Issue by sophieag** [BVLC/caffe#3417]
Hi, I have two input value, say the image and sentence, and I want to compute their euclidean loss of embedding values. So I have this input_embed_image. And for the sentence, I want the embed value of the binary TF value. As for me, I do the element wise sum to all of the input embed word. However, some of the input word should be ignored, since it is not the word in the sentence, it is the zero_symbol or the end symbol. So I have this question, is it the element wise layer have the ignore value like the softmax layer?
Thanks!

**Comment by shaibagon** [comment]
Please use the [caffe-users list][1] for usage, installation, or modeling questions, or other requests for help.
You may also post questions on [stackoverflow][3], make sure you tag them with `caffe` tag.  
There is also [caffe.help][4] documenting the different layers of caffe.
Do not post such requests to Issues. Doing so interferes with the development of Caffe.

Please read the [guidelines for contributing][2] before submitting this issue.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
 [3]: http://stackoverflow.com/questions/tagged/caffe
 [4]: http://caffe.help/manual/layers.html
