### ISSUE TITLE
When change to the CPU mode

### ISSUE THREAD

**Issue by sophieag** [BVLC/caffe#3424]
Hi, before, I use the GPU mode to run the code. However since we update the cuda and we do not restart(sth is still running), I cannot find the GPU device right now. So I change the prototxt to the CPU mode, and find the error below. Could anyone help me? Please...
![image](https://cloud.githubusercontent.com/assets/14370904/11618261/602ab338-9cd3-11e5-9e56-877dac76b487.png)

**Comment by zeakey** [comment]
could you show more log before * \*\*\*Aborted at ... *, in which some more error information may lies in.

**Comment by sophieag** [comment]
Hi, so we restart and I make all successfully with the GPU...
