### ISSUE TITLE
Add an extra library in caffe

### ISSUE THREAD

**Issue by Elpidam** [BVLC/caffe#3425]
Hello! I want to use fftw3 within a layer in caffe. I compiled it successfully but when I'm trying to run the network I get
/.build_release/tools/../lib/libcaffe.so: undefined symbol: fftw_malloc

where fftw_malloc is a type of malloc in fftw. How can I make caffe see the appropriate lib of fftw3???

**Comment by Oh233** [comment]
Could you please describe how you include that library? Since it seems a link error occurs.

**Comment by Elpidam** [comment]
I have symlinked libfftw3.la to caffe-master/build/lib/. How can I do it differently??? I really appreciate your help!

**Comment by Oh233** [comment]
Sorry I'm not experienced in doing such things. But could you please check this https://github.com/BVLC/caffe/pull/3065/files to see if it can help? (Like the compile configurations)

**Comment by Elpidam** [comment]
I finally got over this issue by symlink all the suitable .so files to the one that caffe see for fftw3 and fftw3f
