### ISSUE TITLE
Add a tool to import TensorFlow models

### ISSUE THREAD

**Issue by futurely** [BVLC/caffe#3429]
Several days ago, Google released its latest state-of-the-art [Inception-V3 image classification model](https://www.tensorflow.org/versions/master/tutorials/image_recognition/index.html) in TensorFlow. It's desirable to import that model into Caffe to benefit from the improved recognition accuracy.

**Comment by LiberiFatali** [comment]
any ideas on how to do this?

**Comment by n3011** [comment]
Hi @futurely @LiberiFatali I have written model definition file for inception v3 and its converging n my dataset. https://github.com/n3011/Inception_v3_GoogLeNet

**Comment by futurely** [comment]
It's great! Thanks!
