### ISSUE TITLE
make runtest failing (Mac OS X 10.11.1)

### ISSUE THREAD

**Issue by AnastasiaSulyagina** [BVLC/caffe#3440]
Installed caffe following the instructions,
on make runtest got:

E1211 03:52:06.057683 1982500864 common.cpp:104] Cannot create Cublas handle. Cublas won't be available.
E1211 03:52:06.138869 1982500864 common.cpp:111] Cannot create Curand generator. Curand won't be available.
F1211 03:52:06.145261 1982500864 syncedmem.hpp:18] Check failed: error == cudaSuccess (35 vs. 0)  CUDA driver version is insufficient for CUDA runtime version
*** Check failure stack trace: ***
...
make: *** [runtest] Abort trap: 6

Cuda version 7.5.20
Driver version 7.5.22 (newest)
Tried reinstalling both, no result.

In mailing list nobody managed to solve it as I saw(except downloading latest driver but it already is).

upd:
Downgraded to cuda 7.0, no result

**Comment by AnastasiaSulyagina** [comment]
Downgraded to 7.0 and it helped but is it meant to work with 7.5?

**Comment by AnastasiaSulyagina** [comment]
Made it with CPU only mode.

**Comment by s1210099** [comment]
Did you fix that program?
Now I am in same situation. If you have some solution to fix this problem, tell me about that please.

**Comment by AnastasiaSulyagina** [comment]
Hi @s1210099! 
Make sure that your gpu supports cuda. You can do it [on Nvidia website](https://developer.nvidia.com/cuda-gpus). If not, set CPU-only mode or try to install caffe to another machine. If yes, make sure you followed all necessary steps [here](http://caffe.berkeleyvision.org/installation.html)
