### ISSUE TITLE
Concat along width/height axis

### ISSUE THREAD

**Issue by zeakey** [BVLC/caffe#3442]
I'm trying to implement a layer that concat 3 probability scalar into a `1*1*3*1` Blob so that on which I cant perform a max pooling to get the final predicted scalar.  

I found that the `Concat` layer can only concat along num or channels, and pooling can be only performed on w*h axes.

Is there a way to concat along `w` or `h` axis,or  alternatively pooling on channel or num axes ?

**Comment by seanbell** [comment]
Where did you find that concat can only be performed along `num` or `channels`?  The ConcatLayer is general and can support any axis: https://github.com/BVLC/caffe/blob/master/src/caffe/layers/concat_layer.cpp#L22

Is it possible that you're working with an old version of caffe where everything was 4D, before being generalized to ND?

**Comment by shelhamer** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> Please do not post usage, installation, or modeling questions, or other requests for help to Issues.
Use the caffe-users list instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
