### ISSUE TITLE
Does current codes support CUDNN 3?

### ISSUE THREAD

**Issue by linnanwang** [BVLC/caffe#3447]
Can anyone kindly answer this question? Thank you.

**Comment by kashif** [comment]
yes it does... see for example:

https://github.com/BVLC/caffe/blob/master/cmake/Cuda.cmake#L188

**Comment by flx42** [comment]
And with #3439, Caffe should compile and execute with both cuDNN v3 and cuDNN v4. If it's not the case, please tell me!
