### ISSUE TITLE
.build_release/lib/libcaffe.so: undefined reference to `__device_builtin_variable_gridDim'

### ISSUE THREAD

**Issue by sophieag** [BVLC/caffe#3448]
When I add self-layer and make all, I come with this error?
![image](https://cloud.githubusercontent.com/assets/14370904/11765556/37937062-a198-11e5-98bb-71c28e7ba1d0.png)

And before, I can make all successfully. How could I solve this?

**Comment by DanielTakeshi** [comment]
Please ask caffe questions on the [Google Group](https://groups.google.com/forum/#!forum/caffe-users).

**Comment by seanbell** [comment]
This looks like a request for help -- please seek the proper channels for these kinds of requests.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
