### ISSUE TITLE
"ImportError: numpy.core.multiarray failed to import" occurs when import caffe

### ISSUE THREAD

**Issue by jishaoming** [BVLC/caffe#3449]
I can run the minist example correctly, but when I want to import caffe in python, I meet this error. But when I import caffe the second time, it successfully imported.... This error happens only the first statement " import caffe "
It's about this...

![4cfaa7f5-9b81-4616-9bd7-13b71e30251c](https://cloud.githubusercontent.com/assets/7392530/11779478/53d33902-a296-11e5-9fe4-ee0627e6f9ef.png)

**Comment by seanbell** [comment]
Looks like your numpy library isn't built correctly and/or your paths are incorrect.  You should search around for a solution to the problem described by the runtimeerror message.  I don't think this is a problem with caffe.

Also, the Issues page is not the right place to ask for installation help.  From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

**Comment by summer9090** [comment]
I got the same issue. Have you got any solution?

**Comment by antran89** [comment]
Probably you have two versions of numpy in `/usr/lib` and `/usr/local/lib`. Try to remove one.

**Comment by ih4cku** [comment]
Met similar error. Have you solved this problem?

**Comment by willyd** [comment]
This can happen (at least on Windows) if you linked pycaffe against some version of numpy, say 1.10, and `import numpy` loads another version, say 1.9.

**Comment by aarafati** [comment]
Have you solved this problem. I've got same Error on Ubunutu 14

**Comment by simbaforrest** [comment]
I got the same error on windows 10 using winpython-64bit-2.7.10.1 (with numpy 1.9 by default). I was able to successfully address the problem by changing to miniconda and install the numpy 1.12.0. I guess if I install numpy 1.10+ should also work with winpython.
