### ISSUE TITLE
Caffe make runtest failed

### ISSUE THREAD

**Issue by JackieTseng** [BVLC/caffe#3456]
I just used make and make test command successfully without errors. However, when I used make runtest command, it failed several times for the same problem.

Though I tried the solution from the issue before, uninstalling the boost and reinstall boost-1.55, it doesn't work. The result is as following. What should I do? 

Ps. My configure is CPU-only with MKL, Anaconda, boost-1.55 now.

[----------] Global test environment tear-down
[==========] 919 tests from 140 test cases ran. (56200 ms total)
[  PASSED  ] 914 tests.
[  FAILED  ] 5 tests, listed below:
[  FAILED  ] DeconvolutionLayerTest/0.TestNDAgainst2D, where TypeParam = caffe::CPUDevice<float>
[  FAILED  ] DeconvolutionLayerTest/1.TestNDAgainst2D, where TypeParam = caffe::CPUDevice<double>
[  FAILED  ] NetTest/0.TestFromTo, where TypeParam = caffe::CPUDevice<float>
[  FAILED  ] ConvolutionLayerTest/0.TestNDAgainst2D, where TypeParam = caffe::CPUDevice<float>
[  FAILED  ] ConvolutionLayerTest/1.TestNDAgainst2D, where TypeParam = caffe::CPUDevice<double>

**Comment by jagadale** [comment]
Hi Friends, I am getting following error while running caffe. 

[----------] Global test environment tear-down
[==========] 1928 tests from 265 test cases ran. (632976 ms total)
[  PASSED  ] 1927 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] DeconvolutionLayerTest/1.TestNDAgainst2D, where TypeParam = caffe::CPUDevice<double>

 1 FAILED TEST

-Anyone ware of this issue?

**Comment by seanbell** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> When reporting a bug, it's most helpful to provide the following information, where applicable:
> 
> * What steps reproduce the bug?
> * Can you reproduce the bug using the latest [master](https://github.com/BVLC/caffe/tree/master), compiled with the `DEBUG` make option?
> * What hardware and operating system/distribution are you running?
> * If the bug is a crash, provide the backtrace (usually printed by Caffe; always obtainable with `gdb`).

**Comment by jagadale** [comment]
I have compiled it for power and then execute runtest.sh

**Comment by seanbell** [comment]
Duplicate; see #4083.

**Comment by yechaochen** [comment]
@jagadale What have you done to deal this problem.I met it when I used make runtest command in GPU mode.
