### ISSUE TITLE
Python fails when import caffe, Library not loaded: @rpath/libcaffe.so

### ISSUE THREAD

**Issue by sueHuang** [BVLC/caffe#3459]
OSX 10.11.12, cud 7.5, make runtest succeeded.
When I try to import caffe in python, got error

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropSolver, AdaDeltaSolver, AdamSolver
  File "caffe/pycaffe.py", line 13, in <module>
    from ._caffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, \
ImportError: dlopen(caffe/_caffe.so, 2): Library not loaded: @rpath/libcaffe.so
  Referenced from: /Users/kiwi/Developer/caffe/distribute/python/caffe/_caffe.so
  Reason: image not found
```

Already tried:
1. set DYLD_LIBRARY_PATH
Not working, and import procedure will pend

2. check python path in makeconfig file, and my system python & anaconda python have the same version

3. hdf5 installed via anaconda not brew.

4. Turned off System Integrity Protection

5. Tried otool -L caffe/libcaffe.so/test_all.testbin, all linked right to lib*.7.5.dylib

**Comment by nunerakesh** [comment]
We have the same problem. We have caffe installed but for some reason it is not being picked up

**Comment by shelhamer** [comment]
See https://github.com/BVLC/caffe/issues/3597#issuecomment-186705799 for an identification of the problem and #3696 for the fix.
