### ISSUE TITLE
Non-Deterministic Behavior during testing

### ISSUE THREAD

**Issue by temak** [BVLC/caffe#3462]
I took one sample image and constructed a test data, duplicating the same image 3 times. 
I run network in TEST mode on single GPU (GTX Titan X), Nvidia Driver Version: 352.68, Ubuntu 14.04.3 LTS.
Caffe version: commit 79539180edc73d3716149fb28e07c67a45896be1 - current master.
And I run forward propagation, using pretrained model.

    net = caffe.Net("deploy.prototxt", "snapshot.caffemodel", caffe.TEST)
    transformer = caffe.io.Transformer ...
    
    # sample is a tuple (image, label)
    # ground truth for sample is label = 0.
    sample = ...

    for i in xrange(3):
        accuracy, res_leveldb, probabilites = run_test_on_images(net, transformer, [sample, sample, sample], batch_size=i+1)
        # print np.all(prob[0] == prob_ref[0])
        for j in xrange(len(probabilites)):
            print probabilites[j][0:4] 
        print 'Accuracy:', accuracy
        print '--'

The output of the code is:
    
    # BATCH_SIZE=1
    [9.99996662e-01   6.29426777e-09   3.36414029e-13   2.84010315e-12]
    [9.99996662e-01   6.29426777e-09   3.36414029e-13   2.84010315e-12]
    [9.99996662e-01   6.29426777e-09   3.36414029e-13   2.84010315e-12]
    Accuracy: 1.0
    --
    # BATCH_SIZE=2
    [9.99996662e-01   6.29426777e-09   3.36414029e-13   2.84010315e-12]
    [0.01269178  0.01190188  0.01211816  0.01099705]
    [9.99996662e-01   6.29426777e-09   3.36414029e-13   2.84010315e-12]
    Accuracy: 0.666666666667
    --
    # BATCH_SIZE=3
    [9.89799500e-01   1.11180425e-05   1.85671357e-11   1.89399674e-09]
    [0.01272871  0.01183242  0.01200763  0.0107049]
    [0.0125249   0.01188682  0.01216117  0.01117585]
    Accuracy: 0.333333333333
    --

So we have large probability fluctuations.
When I run in CPU mode all results become deterministic and we have in every case:

     [9.99996662e-01   6.29426777e-09   3.36414029e-13   2.84010315e-12]

Building caffe without use CUDNN doesn't help.
The question is why the batch size matters? Is it a Cuda's issue or caffe's?

[deploy.prototxt](https://gist.github.com/temak/da8afe54ba02b7a9c705)
[full python script source](https://gist.github.com/temak/ba70c3eeff6da26d68d4)

**Comment by shelhamer** [comment]
You need to `caffe.set_mode_gpu()` and `caffe.set_device(0)` before instantiating the `caffe.Net`, not after. I can't take a close look over your script but you might need to check the data blob has the contents you expect too. Please ask about usage on the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users).

**Comment by asanakoy** [comment]
actually `caffe.set_mode_gpu()` and `caffe.set_device(0)` before instantiating the `caffe.Net`
doesn't change anything. Still different results.
