### ISSUE TITLE
make prediction for any type of data using h5

### ISSUE THREAD

**Issue by GGeorgi** [BVLC/caffe#3464]
Hi. I'm new in caffe and I'm going to train caffe on random data (not on images).
Examples which I saw was for images at most.
Here is my github project: https://github.com/GGeorgi/NN

Data input is look like this:

    Input:
    02400,000000529,000531891,001,001,000,000,000,000,000,000,000,000,000,000,000531892,000,000,001,000,000,000,000,000,000,000,000,000

    Output: 1 3.9 3.6 1.65 0 0 0 0 0 0 0 0 0 0 0 0

Data size for both input and output is fixed.
 
So created h5 file using this script: (https://github.com/GGeorgi/NN/blob/master/main.py)

    import h5py
    import numpy as np

    #
    SIZE = 131
    OUTPUT_SIZE = 16

    with open( 'train.txt', 'r' ) as T :
        lines = T.readlines()

    X = np.zeros( (len(lines), SIZE), dtype='f4' )
    y = np.zeros( (len(lines), OUTPUT_SIZE), dtype='f4' )

    for i,l in enumerate(lines):
        sp = l.split('_')
        x_variables = []
        for j,c in enumerate(sp[0]):
            x_variables.append(float(ord(c))/255)
        X[i] = x_variables

        y_variables = []
        outcomes = sp[1].split(" ")
        for (k,item_k) in enumerate(outcomes):
           y_variables.append(float(str(item_k).split("/n")[0])/500)
        y[i] = y_variables

    with h5py.File('train.h5','w') as H:
        H.create_dataset( 'X', data=X )
        H.create_dataset( 'y', data=y )
    with open('train_h5_list.txt','w') as L:
        L.write( 'train.h5' )

    with open( 'train_test.txt', 'r' ) as T :
        lines = T.readlines()

    X = np.zeros( (len(lines), SIZE), dtype='f4' )
    y = np.zeros( (len(lines), OUTPUT_SIZE), dtype='f4' )

    for i,l in enumerate(lines):
        sp = l.split('_')
        x_variables = []
        for j,c in enumerate(sp[0]):
            x_variables.append(float(ord(c))/255)
        X[i] = x_variables

        y_variables = []
        outcomes = sp[1].split(" ")
        for (k,item_k) in enumerate(outcomes):
           y_variables.append(float(str(item_k).split("/n")[0])/500)
        y[i] = y_variables

    with h5py.File('train_test.h5','w') as H:
        H.create_dataset( 'X', data=X )
        H.create_dataset( 'y', data=y )
    with open('train_h5_list_test.txt','w') as L:
        L.write( 'train_test.h5' )

[I'm not sure about dimensions of X and y]

Train was went ok.
After I was trying to predict on test data in predict.py (https://github.com/GGeorgi/NN/blob/master/predict.py) 

    import caffe
    import numpy as np
    
    SIZE = 131
    
    X_IN = np.zeros( (1,1,1,SIZE), dtype='f4' )

    input_str ="04620,000000529,000531653,000,003,002,000,000,000,000,000,000,000,000,000,000531654,000,002,002,000,000,000,000,000,000,000,000,000";
    
    for j,c in enumerate(input_str):
        X_IN[0][0][0][j] = float(ord(c))/255
    
    caffe.set_mode_gpu();
    
    net = caffe.Classifier("trainedModel/network.prototxt","trainedModel/first_iter_20000.caffemodel")
    
    scores = net.predict(np.array(X_IN))
    
    print(scores)

but getting error:

I1219 11:05:54.197836 1947869184 net.cpp:413] Input 0 -> X
I1219 11:05:54.209097 1947869184 layer_factory.hpp:77] Creating layer ip1
I1219 11:05:54.209121 1947869184 net.cpp:106] Creating Layer ip1
I1219 11:05:54.209126 1947869184 net.cpp:454] ip1 <- X
I1219 11:05:54.209136 1947869184 net.cpp:411] ip1 -> ip1
I1219 11:05:54.213858 1947869184 net.cpp:150] Setting up ip1
I1219 11:05:54.213866 1947869184 net.cpp:157] Top shape: 1 100 (100)
I1219 11:05:54.213872 1947869184 net.cpp:165] Memory required for data: 400
I1219 11:05:54.213883 1947869184 layer_factory.hpp:77] Creating layer reluOnIp1
I1219 11:05:54.213892 1947869184 net.cpp:106] Creating Layer reluOnIp1
I1219 11:05:54.213896 1947869184 net.cpp:454] reluOnIp1 <- ip1
I1219 11:05:54.213901 1947869184 net.cpp:397] reluOnIp1 -> ip1 (in-place)
I1219 11:05:54.326982 1947869184 net.cpp:150] Setting up reluOnIp1
I1219 11:05:54.327002 1947869184 net.cpp:157] Top shape: 1 100 (100)
I1219 11:05:54.327006 1947869184 net.cpp:165] Memory required for data: 800
I1219 11:05:54.327013 1947869184 layer_factory.hpp:77] Creating layer ip2
I1219 11:05:54.327023 1947869184 net.cpp:106] Creating Layer ip2
I1219 11:05:54.327028 1947869184 net.cpp:454] ip2 <- ip1
I1219 11:05:54.327035 1947869184 net.cpp:411] ip2 -> ip2
I1219 11:05:54.327383 1947869184 net.cpp:150] Setting up ip2
I1219 11:05:54.327390 1947869184 net.cpp:157] Top shape: 1 16 (16)
I1219 11:05:54.327395 1947869184 net.cpp:165] Memory required for data: 864
I1219 11:05:54.327404 1947869184 net.cpp:228] ip2 does not need backward computation.
I1219 11:05:54.327409 1947869184 net.cpp:228] reluOnIp1 does not need backward computation.
I1219 11:05:54.327411 1947869184 net.cpp:228] ip1 does not need backward computation.
I1219 11:05:54.327415 1947869184 net.cpp:270] This network produces output ip2
I1219 11:05:54.327419 1947869184 net.cpp:283] Network initialization done.
I1219 11:05:54.327630 1947869184 net.cpp:816] Ignoring source layer 
I1219 11:05:54.327646 1947869184 net.cpp:816] Ignoring source layer loss
/usr/local/lib/python2.7/site-packages/scipy/ndimage/interpolation.py:552: RuntimeWarning: invalid value         encountered in true_divide
      zoom = (numpy.array(input.shape) - 1) / zoom_div
    Traceback (most recent call last):
      File "/Users/georgi/PycharmProjects/NN/predict.py", line 17, in <module>
        scores = net.predict(np.array(X_IN))
      File "/users/georgi/caffe/python/caffe/classifier.py", line 89, in predict
        out = self.forward_all(**{self.inputs[0]: caffe_in})
      File "/users/georgi/caffe/python/caffe/pycaffe.py", line 176, in _Net_forward_all
        outs = self.forward(blobs=blobs, **batch)
      File "/users/georgi/caffe/python/caffe/pycaffe.py", line 103, in _Net_forward
        self.blobs[in_].data[...] = blob
    ValueError: could not broadcast input array from shape (1,131,1,131) into shape (1,1,1,131)

Could anyone help me with this problem ? 

Thanks.

**Comment by seanbell** [comment]
This looks like a request for help -- please seek the proper channels for these kinds of requests.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
