### ISSUE TITLE
why BUILD_matlab is OFF in CMakeLists.txt

### ISSUE THREAD

**Issue by antran89** [BVLC/caffe#3465]
Hi developers,
I tried to build Matlab with CMake, and it worked fine on Ubuntu. I am just curious why BUILD_matlab is set OFF in default.
```
caffe_option(BUILD_matlab "Build Matlab wrapper" OFF IF UNIX OR APPLE)
```
https://github.com/BVLC/caffe/blob/master/CMakeLists.txt#L29
Thanks,

**Comment by CDLuminate** [comment]
I'm not caffe dev.

1. matlab is not the default interface of Caffe.  
2. matlab is proprietary software, not everyone has access to it.  
3. set BUILD_matlab to ON as default will introduce more reports to this github issues tracking system.
