### ISSUE TITLE
Cuda check failed: Invalid device function

### ISSUE THREAD

**Issue by bluechill52** [BVLC/caffe#3466]
Hi, I've trying to run the deeplab-public code available at https://bitbucket.org/deeplab/deeplab-public/ . I had no problem while building their own caffe module. But while running their code, I get the following error:

Check failed: error == cudaSuccess (8 vs. 0)  invalid device function
*** Check failure stack trace: ***
    @     0x7fb6bcbd0daa  (unknown)
    @     0x7fb6bcbd0ce4  (unknown)
    @     0x7fb6bcbd06e6  (unknown)
    @     0x7fb6bcbd3687  (unknown)
    @           0x5c0b19  caffe::im2col_gpu<>()
    @           0x5a7e3b  caffe::ConvolutionLayer<>::Forward_gpu()
    @           0x5948f6  caffe::Net<>::ForwardFromTo()
    @           0x594d37  caffe::Net<>::ForwardPrefilled()
    @           0x4a2c4f  caffe::Solver<>::Solve()
    @           0x41db42  train()
    @           0x416621  main
    @     0x7fb6b9b04ec5  (unknown)
    @           0x41c567  (unknown)
    @              (nil)  (unknown)
Aborted (core dumped)

If I build the original caffe module, the examples run fine with GPU.

**Comment by seanbell** [comment]
This is an issue with DeepLab, not caffe.  Please contact the authors of that code for support.
