### ISSUE TITLE
network.save() of very large network Seg Faults

### ISSUE THREAD

**Issue by Fchaubard** [BVLC/caffe#3467]
I have been trying to train a siamese CNN where each branch is VGG, and transfer learn it from VGG-16.. the problem is when I try to save the network after copying the W,b over at each layer, the network.save('.caffemodel') Seg faults and does not save the model correctly. I believe it is because the network is too big? Is there any way to get around this? Here is the gist: 

https://gist.github.com/Fchaubard/b40ccfe7b76043060e2f

and if you simply do..
model_path = '/some_path/siamese_vgg.prototxt'
network = caffe.Net(model_path, caffe.TEST)
network.save('/some_path/siamese_vgg.caffemodel')
you will get a "Segmentation fault (core dumped)"

I removed the weight sharing in each layer to ensure it was the size and not something involving the shared params. I also tried doing a forward backward to see if it was a lazy instantiation issue. To no avail.  

-- UPDATE --
I just attempted on a different server and it seemed to work. Trying to track down the reason... the .caffemodel is 1.1 GB. And I have more than that available on the original server so I am not sure what the reason for this discrepancy in functionality.

**Comment by shelhamer** [comment]
For large models >2 gb you can save the network as `hdf5` instead of `binaryproto`.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
