### ISSUE TITLE
wrong link

### ISSUE THREAD

**Issue by noshaba** [BVLC/caffe#3469]
Hi!

Please update the link in the file 
https://github.com/BVLC/caffe/blob/master/docs/tutorial/forward_backward.md 
for the solver tutorial from 
https://github.com/BVLC/caffe/blob/master/docs/tutorial/solver.html
to
https://github.com/BVLC/caffe/blob/master/docs/tutorial/solver.md

**Comment by antran89** [comment]
Hi @noshaba 
You can try to make Pull Request to help develop merge this error.
