### ISSUE TITLE
Caffe installation on Mac 10.10.5

### ISSUE THREAD

**Issue by robinlkm** [BVLC/caffe#3470]
Hey all,

I got a problem in compilation. I have checked that all the lib and related software are installed. But it get wrong after I ran the command [make all]. Do you have any ideas about that?

"leveldb::DB::Open(leveldb::Options const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, leveldb::DB**)", referenced from:
      caffe::db::LevelDB::Open(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, caffe::db::Mode) in db_leveldb.o
  "google::protobuf::MessageLite::SerializeToString(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*) const", referenced from:
      caffe::Net<float>::Forward(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, float*) in net.o
      caffe::Net<double>::Forward(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, double*) in net.o
  "google::protobuf::DescriptorPool::FindFileByName(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const", referenced from:
      caffe::protobuf_AssignDesc_caffe_2eproto() in caffe.pb.o
  "google::protobuf::Message::SerializeToOstream(std::__1::basic_ostream<char, std::__1::char_traits<char> >*) const", referenced from:
      caffe::WriteProtoToBinaryFile(google::protobuf::Message const&, char const*) in io.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [.build_release/lib/libcaffe.so] Error 1

**Comment by Hiyorimi** [comment]
Try to get Xcode 6.2 and check google on the matter.

You can also try [my](http://playittodeath.ru/how-to-install-caffe-on-mac-os-x-yosemite-10-10-4/) post on the matter.

**Comment by seanbell** [comment]
This looks like a request for help with installation.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
