### ISSUE TITLE
rms_decay's default value not set

### ISSUE THREAD

**Issue by orsharir** [BVLC/caffe#3472]
According to the documentation, the default value for rms_decay is 0.02, yet in caffe.proto file its default value is not define. Either the documentation should be changed to reflect this (i.e., write "recommended value" instead of "default value"), or change caffe.proto's default value to match the documentation.

**Comment by BlGene** [comment]
It would be helpful if you would submit this as a PR.

BR,

**Comment by shelhamer** [comment]
Confirming the current default is `0`: https://github.com/BVLC/caffe/blob/master/src/caffe/proto/caffe.proto#L220-L222 which is not a particularly good choice. `0.9` might be reasonable given it's the choice in the [slides by Tijmen](http://www.cs.toronto.edu/~tijmen/csc321/slides/lecture_slides_lec6.pdf).
