### ISSUE TITLE
How to finetune two models with same dataset

### ISSUE THREAD

**Issue by wqysq** [BVLC/caffe#3473]
I want to finetune with two models,but I don't know how to fuse them after finetune?someone who
knows how to solve this issue?thank you very much!

**Comment by seanbell** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
