### ISSUE TITLE
"TypeError: No to_python (by-value) converter found for C++ type: boost::shared_ptr<caffe::Blob<float> >"

### ISSUE THREAD

**Issue by ElderFalcon** [BVLC/caffe#3477]
When stepping through the mnist demo for caffe, I was able to successfully train my network and get all of my files in order. I wrote a short python script to test the network on an arbitrary image and I'm getting the error below:

TypeError: No to_python (by-value) converter found for C++ type: boost::shared_ptr<caffe::Blob<float> >

My boost libraries seemed to install without a hitch, so I'm not sure what happened there. My script is as follows:

import numpy as np
import sys
import caffe
import matplotlib.pyplot as plt
import os

carre_root='/home/tyler/caffe/'
MODEL_FILE='examples/mnist/lenet.prototxt'
PRETRAINED='examples/mnist/lenet_iter_10000.caffemodel'
IMAGE_FILE='/home/tyler/Pictures/test.png'

input_image=caffe.io.load_image(IMAGE_FILE,color=False)
net = caffe.Classifier(MODEL_FILE, PRETRAINED, caffe.TEST)
net.predict([input_image],oversample=false)
caffe.set_mode_cpu()
out = net.forward([input_image])
print out['prob']

I've come at this a few different ways, and it seems that python is my Achilles heel no matter how I try to skin the cat. Any ideas?

**Comment by ElderFalcon** [comment]
Closed, moving to proper section.

**Comment by bei21** [comment]
Just wonder whether you have solved the problem, cause I got exactly the same error.

**Comment by bei21** [comment]
I got a solution here: https://github.com/BVLC/caffe/pull/3575
