### ISSUE TITLE
caffe regression different input but same out!

### ISSUE THREAD

**Issue by Eniac-Xie** [BVLC/caffe#3481]
Hello everyone, I have trained a regression model with Euclidean loss. Train loss decreases from about 24 to about 12 quickly and stay around 12 at last. When I use this model to predict, I find all predictions are the same. 
After checking the parameters of the model, I find that the parameters of the last 3 fc layers are almost 0(about 1e-5 or 1e-6).  So the output are similar to the bias of the last fc layer.
Any suggestion?

**Comment by BlGene** [comment]
This is a usage, general machine learning, question so it belongs on the mailing list.

But try having a look to see if your examples are balanced, maybe you have a lot of 0 entries in your training data and the model learns to always output 0.

BR,

**Comment by seanbell** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
