### ISSUE TITLE
Is training with multiple CPUs possible?

### ISSUE THREAD

**Issue by bjsowrd** [BVLC/caffe#3482]
I ran the provided examples and found that only one CPU was working while others were mostly free. Can caffe models be trained with more CPUs? And what should I do? Thanks a lot.

**Comment by BlGene** [comment]
There is no flag to activate multi-cpu support. The ability to run parallel models was introduced with muti GPU support, however as far as I know it has not been extended to running cpu models in parallel. Nearly all parallelism efforts focus on multi-gpu as this is much quicker, and I would encourage you to look into this.
 
BR

**Comment by samitok** [comment]
It's reason might be your BLAS library. Some BLAS libraries doesn't support multi-core CPU calculations.

**Comment by bhack** [comment]
See also https://github.com/tensorflow/tensorflow/issues/583 and https://github.com/tensorflow/tensorflow/pull/763

**Comment by Noiredd** [comment]
To definitely answer and close this question: yes it is possible using OpenBLAS. Check this [answer](https://stackoverflow.com/a/31396229/6919631) by Franck Dernoncourt.
