### ISSUE TITLE
I got error when I predict my own image by mnist

### ISSUE THREAD

**Issue by SmallOneHan** [BVLC/caffe#3485]
python python/classify.py --print_results --model_def examples/mnist/lenet.prototxt --pretrained_model examples/mnist/lenet_iter_10000 --force_grayscale --center_only --labels_file data/mnist/mnist_words.txt --images_dim 28,28 data/mnist/sample_digit.png foo

when I run this on terminal, I got error

unrecognized arguments: --print_results --force_grayscale --labels_file foo

**Comment by BlGene** [comment]
Have a look at the python file to see what arguments it can handle. If you got the command from the documentation it may simply be an issue of the documentation not being updated. In case the command is not present in the documentation this would be usage question and would belong in the mailing list.

Try removing the unrecognized arguments.

BR,

**Comment by seanbell** [comment]
This looks like a request for usage help.  If you think you found a bug in caffe please re-open.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
