### ISSUE TITLE
Problem with Caffe running on multi-GPUs (8 Titan X)

### ISSUE THREAD

**Issue by MichaelHunson** [BVLC/caffe#3486]
Hi everyone! I am trying to run imageNet with caffe on multi-GPU today with 8 Titan X and CentOS. I also set --gpu=all, hoping all the 8 GPUs would run in parallel. But, it turned out that only four GPUs could work for my task. Does not caffe support 8-GPUs framework? Or I have to implement some other things in order to make it work? I attached two log file pictures below to help you to better understand my problem. Anyone's kind advice is appreciated and eagerly needed. Thanks.

**Comment by BlGene** [comment]
IIRC, there was a point where adding GPUs did not increase training speed.

This is a usage question and belongs on the mailing list.

BR,

**Comment by MichaelHunson** [comment]
the Log file Pictures are:
![s1](https://cloud.githubusercontent.com/assets/11781064/12013149/beb4d414-ad4b-11e5-98c9-0d9772ae7fbf.png)
![s2](https://cloud.githubusercontent.com/assets/11781064/12013156/f1c79422-ad4b-11e5-82a5-454866771556.png)

**Comment by shelhamer** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> Please do not post usage, installation, or modeling questions, or other requests for help to Issues.
Use the caffe-users list instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
