### ISSUE TITLE
Slice Layer without Top specification

### ISSUE THREAD

**Issue by noshaba** [BVLC/caffe#3488]
Hello,

could you make it possible to leave out the top name specification, for example, for the slice layer? I currently have the problem that I would like to Slice along the width of a Blob but the width but I don't really want to write 1000 names or slice_points or so for the top blobs... So I wanted to know if you could make it a little more dynamic?
Or if that is too difficult, then maybe another parameter for the EltwiseLayer that sums or multiplies etc. over a wanted axis of a blob, when I just have one bottom blob?

**Comment by rohrbach** [comment]
There is a way to write prototxt with python, which makes it rather easy to write 1000 names, see examples/pycaffe.

**Comment by Noiredd** [comment]
This is already possible from Python using the NetSpec interface. See the [lenet example](https://github.com/BVLC/caffe/blob/master/examples/01-learning-lenet.ipynb), section 2 for details.
