### ISSUE TITLE
Has to re-make after every reboot?

### ISSUE THREAD

**Issue by Samitha2** [BVLC/caffe#3489]
Hi All,

I am using Caffe with GPU (NVIDIA GTX 590) support. I have installed the NVIDIA Driver 352 (comes with Cuda 7.5 runfile) with no open gl libs and Caffe is working fine.

However, every time I start a new Caffe session after turning my computer on I get the following error ,

WARNING: Logging before InitGoogleLogging() is written to STDERR
E1219 10:42:22.132685 23546 common.cpp:104] Cannot create Cublas handle. Cublas won't be available.
E1219 10:42:22.159312 23546 common.cpp:111] Cannot create Curand generator. Curand won't be available.
F1219 10:42:22.176038 23546 common.cpp:142] Check failed: error == cudaSuccess (30 vs. 0)  unknown error

and have to re-make caffe every time. Do you know a permanent solution for this? It would be of great help... Thanks in advance.

**Comment by flx42** [comment]
I believe this question belongs to the Caffe users list.
Anyway, try `nvidia-modprobe -u -c=0` before starting Caffe.

**Comment by shelhamer** [comment]
It looks like this is a systems issue. From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> Please do not post usage, installation, or modeling questions, or other requests for help to Issues.
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
