### ISSUE TITLE
Video description model and code for Long Term Recurrent Covolutional Networks

### ISSUE THREAD

**Issue by thegreatshasha** [BVLC/caffe#3498]
Hi guys

Since you guys have already released the models for LRCN activity recognition here (http://www.eecs.berkeley.edu/~lisa_anne/LRCN_video), is it also possible to release the code for the video description part?

Thanks

**Comment by rohrbach** [comment]
Check out https://vsubhashini.github.io/s2vt.html.
Please directly contact the authors if you have questions about that.

Closing as this is a usage issue.

Please ask usage questions on caffe-users: https://groups.google.com/forum/#!forum/caffe-users. 
If you do think there is a bug in Caffe, you're welcome to open a new issue according to https://github.com/BVLC/caffe/wiki/Reporting-Bugs-and-Other-Issues. Thanks!
