### ISSUE TITLE
How to training/testing my custom model (net) in caffe?

### ISSUE THREAD

**Issue by Navid67** [BVLC/caffe#3501]
just started using caffe and was amazed by its ease for training and testing models. I just wanted to train my own model( net) and keep using it.

For more explanations, I have a Specific multi layer model like as bellow picture. (My input data is breast-cancer data set.):
http://i.stack.imgur.com/fF3E8.png
(This model is not fully connected neural network, and some weights are omitted as you can see in picture.)

My certain question is, how to implement this model in caffe?!

Many thanks!!!! Any advice would be appreciated!

**Comment by shelhamer** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> Please do not post usage, installation, or modeling questions, or other requests for help to Issues.
Use the caffe-users list instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
