### ISSUE TITLE
Use the same name in two branches' net in order to finetune.

### ISSUE THREAD

**Issue by artiit** [BVLC/caffe#3502]
Hi, everyone,

I have a two branches's net and want each of them to finetune from caffenet independently. After five conv layers, they are joined together in FC layer.

According to caffe's guide, when finetunig, I should set the layer's name being same as caffenet. There is two branches, so I have to set two same name layer in one net(such as two conv1, two conv2, etc). But, when I draw the net with caffe's python scripts , there seems something wrong with my net, the net is cross at the layer with the same name(only one conv1 in net image), i.e. the net recognizes the same name's layers  as the same layer(actually they are in different branches).
I think caffe handle the layer by name and in order, so since the two conv1 in different index, it is OK with same name to finetune. Am I wrong with that? My traning's results is bad and I think there's something wrong with my train protofile which has pair layers with same name.

Any suggestions will be appreciate.

Thanks.

**Comment by artiit** [comment]
When I try to visualize parameters layer-by-layer like caffe's Notebook Examples, the results is wrong, since there is only one branches of 5 conv and rest FC layer:
[(k, v[0].data.shape) for k, v in net.params.items()]
[('conv1', (96, 3, 11, 11)),
 ('conv2', (256, 48, 5, 5)),
 ('conv3', (384, 256, 3, 3)),
 ('conv4', (384, 192, 3, 3)),
 ('conv5', (256, 192, 3, 3)),
 ('fc6_d', (4096, 18432)),
 ('fc7_d', (4096, 4096)),
 ('fc8_d', (8, 4096)),
 ('fc8_g', (2, 4096))]
Actually, what I want is something like
conv1,conv2,conv3,conv4,conv5(branch 1),conv1,conv2,conv3,conv4,conv5(branch 2),
fc6_d,fc7_d,fc8_d,fc8_g.

**Comment by leonliuzju** [comment]
I have met the same problem, did you solve it?

**Comment by artiit** [comment]
Hi @leonliuzju, I have solved it using caffe net surgery. You can tricky initialize use net surgery in Python: [http://nbviewer.ipython.org/github/BVLC/caffe/blob/master/examples/net_surgery.ipynb]. Then, save your initial model weights as a .caffemodel to begin training from. Hope it will help.

**Comment by naibaf7** [comment]
I will propose an update to PyCaffe that will allow this...

**Comment by zhoupan9109** [comment]
@naibaf7 Hi, can you tell me how to propose an updata to pycaffe? In my work, I meet the same problem that import two different branches caffe into a single python.  Can you give me your hand?
