### ISSUE TITLE
I install caffe by gpu mode. I have successfully run the "make all" and "make test"conmand.But when I run the "make runtest", I got error."

### ISSUE THREAD

**Issue by SmallOneHan** [BVLC/caffe#3504]
F0102 15:39:36.922955  8207 cudnn_conv_layer.cpp:53] Check failed: status == CUDNN_STATUS_SUCCESS (6 vs. 0)  CUDNN_STATUS_ARCH_MISMATCH
*** Check failure stack trace: ***
    @     0x2b8687272daa  (unknown)
    @     0x2b8687272ce4  (unknown)
    @     0x2b86872726e6  (unknown)
    @     0x2b8687275687  (unknown)
    @     0x2b86892592c9  caffe::CuDNNConvolutionLayer<>::LayerSetUp()
    @           0x47678d  caffe::Layer<>::SetUp()
    @           0x47880f  caffe::GradientChecker<>::CheckGradientExhaustive()
    @           0x577e7a  caffe::CuDNNConvolutionLayerTest_TestGradientCuDNN_Test<>::TestBody()
    @           0x8454d3  testing::internal::HandleExceptionsInMethodIfSupported<>()
    @           0x83c1b7  testing::Test::Run()
    @           0x83c25e  testing::TestInfo::Run()
    @           0x83c365  testing::TestCase::Run()
    @           0x83f6a8  testing::internal::UnitTestImpl::RunAllTests()
    @           0x83f937  testing::UnitTest::Run()
    @           0x46083a  main
    @     0x2b868a15fec5  (unknown)
    @           0x467779  (unknown)
    @              (nil)  (unknown)
make: *** [runtest] Aborted (core dumped)

**Comment by SmallOneHan** [comment]
https://groups.google.com/forum/#!topic/caffe-users/wtmtTvdpXP4

**Comment by antran89** [comment]
check whether you have installed CUDNN, it seems that you do not have it

**Comment by seanbell** [comment]
This looks like a request for help with installation.  

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
_Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
