### ISSUE TITLE
Support blobs > 2GB

### ISSUE THREAD

**Issue by tiferet** [BVLC/caffe#3510]
I have some 2,650 features, and when I try to use a training set greater than about 750,000 examples I run into the following error:
```
Check failed: shape[i] <= 2147483647 / count_ (21 vs. 12) blob size exceeds INT_MAX
```
The full console printout of the error I am getting plus all my net and solver parameters is attached.
[Caffe_error_INT_MAX.txt](https://github.com/BVLC/caffe/files/77061/Caffe_error_INT_MAX.txt)

Is there any solution (or workaround) that would allow me to train with a larger training set? Since I use batch training, it seems I should be able to use an unlimited total number of examples, perhaps even by reading them from multiple smaller files.

This problem seems to be referenced in the following issues, but as far as I can tell none of them actually involve a merge to solve the bug (please correct me if I'm wrong):
#2473 (see especially jeffdonahue's [comment](https://github.com/BVLC/caffe/pull/2473#issuecomment-102720023))
#3159 
#1970

Thank you!

**Comment by shelhamer** [comment]
See [caffe-users thread](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/caffe-users/iuNJ8ZWo_04/h7qROiWbEAAJ); this is a usage question about hdf5 input and memory consumption.
