### ISSUE TITLE
AttributeError: 'Net' object has no attribute 'set_mode_gpu'

### ISSUE THREAD

**Issue by unfir225** [BVLC/caffe#3511]
Hello,everyone,I am using the fcn-8s-pascalcontext.caffemodel, i can run the eval.py without use **net.set_mode_gpu()**
But after i added it, i got the error:  'Net' object has no attribute 'set_mode_gpu'
I am using the caffe-future branch, and the PYTHONPATH is right.

**Comment by seanbell** [comment]
You likely want to use `caffe.set_mode_gpu`.  This looks like a request for help, so please ask the mailing list.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
