### ISSUE TITLE
src/caffe/layers/base_conv_layer.cpp Error

### ISSUE THREAD

**Issue by ragip007** [BVLC/caffe#3513]
When i compile my caffe code. I take this error. How  can i fix this bug?  
I am using CuDNN v3 and cuda 7.5 for GPU. Please can you help me to solve this problem as soon as possible.

Thanks

CXX src/caffe/layers/base_conv_layer.cpp
In file included from src/caffe/layers/base_conv_layer.cpp:7:0:
./include/caffe/vision_layers.hpp:408:3: error: ‘cudnnConvolutionBwdFilterAlgo_t’ does not name a type
   cudnnConvolutionBwdFilterAlgo_t *bwd_filter_algo_;
   ^
./include/caffe/vision_layers.hpp:409:3: error: ‘cudnnConvolutionBwdDataAlgo_t’ does not name a type
   cudnnConvolutionBwdDataAlgo_t *bwd_data_algo_;
   ^
./include/caffe/vision_layers.hpp:616:3: error: ‘cudnnLRNDescriptor_t’ does not name a type
   cudnnLRNDescriptor_t norm_desc_;
   ^
./include/caffe/vision_layers.hpp:643:3: error: ‘cudnnLRNDescriptor_t’ does not name a type
   cudnnLRNDescriptor_t norm_desc_;
   ^
make: *** [.build_release/src/caffe/layers/base_conv_layer.o] Error 1
ragip@ReVeNgEr:~/Desktop/flownet-release$

**Comment by ShaggO** [comment]
Which version of Caffe are you using?
The monolithic "vision_layers.hpp"-file was removed on the 2nd of december and substituted by minor header files for each layer type, and thus you must be using a slightly outdated Caffe.
The type is defined in the cudnn v3.0 header but not in the v2.0 header so make sure you're linking to the correct library.
I believe this is a question of "usage and installation of Caffe", and thus further discussion should be continued at the caffe users mailing list if updating and checking the linking does not help (correct me if I'm wrong):
https://groups.google.com/forum/#!forum/caffe-users

**Comment by shelhamer** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> Please do not post usage, installation, or modeling questions, or other requests for help to Issues.
Use the caffe-users list instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
