### ISSUE TITLE
Compile error about google::protobuf

### ISSUE THREAD

**Issue by xxlylf** [BVLC/caffe#3514]
Dear fellow, I have got the following error while compiling all, I have installed the google logging and google protocol buffer libraries, the 'google' file is in /usr/include, does the version of protobuf effect? Many thanks !

.build_release/lib/libcaffe.so: undefined reference to `google::protobuf::Message::InitializationErrorString() const'
.build_release/lib/libcaffe.so: undefined reference to `google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(int, std::string const&, google::protobuf::io::CodedOutputStream*)'
.build_release/lib/libcaffe.so: undefined reference to `google::protobuf::io::CodedOutputStream::WriteStringWithSizeToArray(std::string const&, unsigned char*)'
.build_release/lib/libcaffe.so: undefined reference to `google::protobuf::internal::WireFormatLite::ReadString(google::protobuf::io::CodedInputStream*, std::string*)'
.build_release/lib/libcaffe.so: undefined reference to `google::protobuf::Message::GetTypeName() const'
.build_release/lib/libcaffe.so: undefined reference to `google::protobuf::MessageLite::SerializeToString(std::string*) const'
.build_release/lib/libcaffe.so: undefined reference to `google::base::CheckOpMessageBuilder::NewString()'
.build_release/lib/libcaffe.so: undefined reference to `google::protobuf::Message::DebugString() const'
.build_release/lib/libcaffe.so: undefined reference to `google::protobuf::internal::empty_string_'
.build_release/lib/libcaffe.so: undefined reference to `google::protobuf::MessageLite::ParseFromString(std::string const&)'
.build_release/lib/libcaffe.so: undefined reference to `google::protobuf::internal::NameOfEnum(google::protobuf::EnumDescriptor const*, int)'
.build_release/lib/libcaffe.so: undefined reference to `cv::imread(std::string const&, int)'
.build_release/lib/libcaffe.so: undefined reference to `google::protobuf::DescriptorPool::FindFileByName(std::string const&) const'
.build_release/lib/libcaffe.so: undefined reference to `google::protobuf::internal::WireFormatLite::ReadBytes(google::protobuf::io::CodedInputStream*, std:.build_release/lib/libcaffe.so: undefined reference to `google::protobuf::Message::InitializationErrorString() const'
.build_release/lib/libcaffe.so: undefined reference to `google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(int, std::string const&, google::protobuf::io::CodedOutputStream*)'
.build_release/lib/libcaffe.so: undefined reference to `google::protobuf::io::CodedOutputStream::WriteStringWithSizeToArray(std::string const&, unsigned char*)'
.build_release/lib/libcaffe.so: undefined reference to `google::protobuf::internal::WireFormatLite::ReadString(google::protobuf::io::CodedInputStream*, std::string*)'
.build_release/lib/libcaffe.so: undefined reference to `google::protobuf::Message::GetTypeName() const'
.build_release/lib/libcaffe.so: undefined reference to `google::protobuf::MessageLite::SerializeToString(std::string*) const'
.build_release/lib/libcaffe.so: undefined reference to `google::base::CheckOpMessageBuilder::NewString()'
.build_release/lib/libcaffe.so: undefined reference to `google::protobuf::Message::DebugString() const'
.build_release/lib/libcaffe.so: undefined reference to `google::protobuf::internal::empty_string_'
.build_release/lib/libcaffe.so: undefined reference to `google::protobuf::MessageLite::ParseFromString(std::string const&)'
.build_release/lib/libcaffe.so: undefined reference to `google::protobuf::internal::NameOfEnum(google::protobuf::EnumDescriptor const*, int)'
.build_release/lib/libcaffe.so: undefined reference to `cv::imread(std::string const&, int)'
.build_release/lib/libcaffe.so: undefined reference to `google::protobuf::DescriptorPool::FindFileByName(std::string const&) const'
.build_release/lib/libcaffe.so: undefined reference to `google::protobuf::internal::WireFormatLite::ReadBytes(google::protobuf::io::CodedInputStream*, std::string:*)string'*
).'build_release
/.libbuild_release/libcaffe.so/:lib /undefinedlibcaffe.so :reference  undefinedto  reference` googleto: :`protobufgoogle::::internalprotobuf::::StringTypeHandlerBaseinternal::::DeleteStringTypeHandlerBase:(:stdDelete:(:stdstring:*:)string'*
).'build_release
/.libbuild_release//libcaffe.solib:/ undefinedlibcaffe.so :reference  undefinedto  reference` googleto: :`protobufgoogle::::MessageFactoryprotobuf::::InternalRegisterGeneratedFileMessageFactory(:char: InternalRegisterGeneratedFileconst(char* ,const *void,  (void* )((*std):(:stdstring: :conststring& )const)&')
).'build_release
./build_releaselib//liblibcaffe.so/:libcaffe.so :undefined  undefinedreference  referenceto  to` leveldb`::leveldbDB::::DBOpen:(:leveldbOpen:(:leveldbOptions: :constOptions& ,const &std,: :stdstring: :conststring& , constleveldb&:,: DBleveldb*:*:)DB'*
*.)build_release'/.
.build_release/lib/libcaffe.sobuild_releaselib/libcaffe.so/tools/: undefinedcompute_image_mean.o: reference In : undefinedfunction ` to std:: referencestring*`cv google to::MakeCheckOpString::imencode<int, ` int>(std:(int cv:const&:imencode, int:string const(std&,  constchar ::const*&,)':string 
compute_image_mean.cpp cv::(.const&,text._ZN6google17MakeCheckOpStringIiiEEPSsRKT_RKT0_PKc[:_InputArray_ZN6google17MakeCheckOpStringIiiEEPSsRKT_RKT0_PKc] cv+0x26 const): ::_InputArrayundefined reference&,  to  const`googlestd::::base&, ::CheckOpMessageBuildervector<unsigned::NewStringstd::()' char
.vector<build_release/tools, std/compute_image_mean.ounsigned : In::allocator function char,`std std::string<unsigned * google::allocator::MakeCheckOpStringchar> <unsigned<unsigned int,>&, int> char(unsigned std int > >const&,::vector int &, const&,<int char std::const*), std':
vector<intcompute_image_mean.cpp:(::allocator.text._ZN6google17MakeCheckOpStringIjiEEPSsRKT_RKT0_PKc, std[_ZN6google17MakeCheckOpStringIjiEEPSsRKT_RKT0_PKc<int>]+0x26::allocator):  >undefined <intreference  constto `> google:&)':base> const::CheckOpMessageBuilder
.::NewString&)'()'build_release/
.
.build_release/lib/tools/build_release/compute_image_mean.o:libcaffe.so: In lib/function  undefined`mainlibcaffe.so:':
 referencecompute_image_mean.cpp: undefined(.text.startup to +0xce reference): `googleundefined  toreference ::to  ``googleprotobuf:::google:SetUsageMessage(:internalstd::protobuf:string ::StringTypeHandlerBaseconst&::)'
internal:compute_image_mean.cpp:::New(.text.startup:StringTypeHandlerBase+0x15a()): ::undefined '
reference New(to .build_release`google)'::protobuf/lib::
.MessageLite:/libcaffe.so:ParseFromStringbuild_release/(std: ::lib/string undefined const&libcaffe.so:)'
reference compute_image_mean.cpp: undefined(.to text.startup+ reference0x276):`google undefined to reference:: to ` `googleprotobuf:::google:protobuf::internal:MessageLite:protobuf::ParseFromString::WireFormatLite(std::::stringinternal: const::WriteBytesMaybeAliased&):WireFormatLite'
(int.build_release::/lib, /libcaffe.soWriteBytesMaybeAliased(: std:undefined int,reference :stringto ` stdgoogle: const:protobuf::::Message&, ::InitializationErrorStringstring ()google: constconst'
:protobuf.build_release&,/lib::/libcaffe.so google: undefinedio:: reference:: toprotobuf: `googleCodedOutputStream*::protobuf:io:::internal)'
::WireFormatLite:CodedOutputStream::WriteStringMaybeAliased.build_release(int*), std/lib::'
string /libcaffe.soconst&.build_release, google: undefined::protobuf/lib/::io reference::CodedOutputStreamlibcaffe.so:*)' to
. undefinedbuild_release/ `lib/libcaffe.so reference: undefinedleveldb: reference to to:Status `google `leveldb::protobuf::ToString::io::Status::CodedOutputStream() ::WriteStringWithSizeToArray::ToString(std:const':string
. const()&, build_release/unsigned  constchar*lib/)'
'
.build_releaselibcaffe.so:/lib.build_release/libcaffe.so undefined: undefined/lib reference reference to/libcaffe.so `google to::: protobuf: `:internalundefined ::WireFormatLitegoogle:::reference ReadString(google:protobuf::protobufto `::io::internal::CodedInputStreamgoogle:*,:: std:protobuf::stringWireFormatLite:*)'::
.:WriteStringbuild_release/internal:lib/libcaffe.so(int: undefined:WireFormatLite reference,  to::WriteString `googlestd:::protobuf(int::Message:string::GetTypeName, () const const&,'
std:.build_release/ googlelib/:stringlibcaffe.so::: undefined const referenceprotobuf: to&, `google:io::protobuf google::MessageLite::CodedOutputStream::SerializeToString::protobuf(std:*)':string::io*) 
const'
.build_release/lib/libcaffe.so: undefined reference to `google::protobuf::collect2: error: ld returned 1 exit status
Message::DebugString:() :CodedOutputStreamconst'
*)'.build_release
/lib./libcaffe.so: build_releaseundefined reference/tools to/convert_imageset.o `google: In::protobuf function:: `internal:std::empty_string_:collect2: error: ld returned 1 exit statusstring'*
 
google.build_release::/libMakeCheckOpString</libcaffe.sounsigned : int,undefined  intreference >(unsignedto ` intgoogle: const:protobuf&, ::internalint ::const&NameOfEnum(, chargoogle: const:protobuf*)::':EnumDescriptor 
convert_imageset.cppconst*,:(. int)text._ZN6google17MakeCheckOpStringIjiEEPSsRKT_RKT0_PKc['
_ZN6google17MakeCheckOpStringIjiEEPSsRKT_RKT0_PKc.build_release]+/lib0x26)/libcaffe.so: : undefined undefined reference reference to to ``googlecv::::imread(base:std::CheckOpMessageBuilder:string:: constNewString(&,)' int
.)'
build_release/.build_releasetools//libconvert_imageset.o:/libcaffe.so In:  functionundefined  `reference main'to :
`googleconvert_imageset.cpp:::protobuf(.text.startup::DescriptorPool+0x2a2::FindFileByName): (stdundefined ::stringreference  constto &) `googleconst'::
.SetUsageMessagebuild_release/(stdlib/::libcaffe.so:string  undefinedconst&) reference '
convert_imageset.cppto `:(google:.text.startup:protobuf+0x7a8::internal): ::WireFormatLiteundefined ::reference ReadBytes(googleto `::protobufgoogle::::protobufio::::CodedInputStreamMessageLite:*,:SerializeToString std(std::::string*stringMakefile:596: recipe for target '.build_release/tools/upgrade_net_proto_binary.bin' failed
*make: *** [.build_release/tools/upgrade_net_proto_binary.bin] Error 1
make: *** Waiting for unfinished jobs....
)'
.build_release/lib/libcaffe.so: undefined reference to `google::protobuf::internal::StringTypeHandlerBase::Makefile:596: recipe for target '.build_release/tools/upgrade_solver_proto_text.bin' failed
make: *** [.build_release/tools/upgrade_solver_proto_text.bin] Error 1
)Delete const'(std:
.build_release:string*/lib)'/libcaffe.so
.build_release: undefined/lib/ reference libcaffe.so: to `undefined referencegoogle:: to protobuf:`google:Message::protobuf::InitializationErrorString::MessageFactory() ::InternalRegisterGeneratedFileconst'
(char .build_releaseconst*,/lib/ void libcaffe.so: (*)undefined (std:reference :stringto  const`google&)::)'
protobuf::.build_release/internal:lib/:WireFormatLitelibcaffe.so:::WriteStringMaybeAliased undefined (int,reference to std: `leveldb:string ::DBconst&,::Open google(leveldb::protobuf::Options::io const&::CodedOutputStream, std*)'::string
.build_release const&/lib/, leveldblibcaffe.so: ::DBundefined reference**) to '
.`google:build_release/lib:protobuf:/libcaffe.so:io: ::undefined CodedOutputStream:reference :WriteStringWithSizeToArrayto `(stdcv::::imencodestring (stdconst&::string, unsigned const& char*, cv)'
::_InputArray.build_release/ const&lib/, stdlibcaffe.so: ::vectorundefined reference<unsigned  to char, `google:std::protobuf:allocator<::internalunsigned char::WireFormatLite> >::ReadString&, (googlestd::::vectorprotobuf:<int,:io std:::CodedInputStream:allocator<*, int> std::> conststring*&)')'

.build_release.build_release//lib/lib/libcaffe.solibcaffe.so: : undefined undefined reference reference to to `google`google::protobuf::protobuf::internal::Message::StringTypeHandlerBase::GetTypeName::New() ()'const'

.build_release.build_release//lib/lib/libcaffe.solibcaffe.so: : undefinedundefined reference reference to  to `google`google::protobuf::protobuf::internal::Message::WireFormatLite::DebugString::WriteBytesMaybeAliased() (int,const'
 std:.build_release/:string lib/libcaffe.soconst&,:  googleundefined reference::protobuf to ::io`google:::CodedOutputStream:protobuf:*)':internal
.::build_release/empty_string_'lib/libcaffe.so
.: undefinedbuild_release/lib reference/libcaffe.so to : undefined`leveldb: reference:Status: to :ToString`google() ::protobufconst'
::MessageLite.build_release/::ParseFromStringlib/libcaffe.so(std:: undefined:string  reference const&to )'
`google:.build_release/:protobuflib/::internallibcaffe.so:::WireFormatLite undefined:: referenceWriteString(int to, std `google::string::protobuf const&::internal, google::NameOfEnum::protobuf(google::::io:protobuf::CodedOutputStream:EnumDescriptor*)' const
*, int)'
.build_release/lib/libcaffe.so: undefined reference to `cvcollect2: error: ld returned 1 exit status::imread(
std::string const&, int)'
.build_release/lib/libcaffe.so: undefined reference to `google::protobuf::DescriptorPool::FindFileByName(std::string const&) const'
.build_release/lib/libcaffe.so: undefined referenceMakefile:596: recipe for target '.build_release/tools/compute_image_mean.bin' failed
 make: *** [.build_release/tools/compute_image_mean.bin] Error 1
to `google::protobuf::internal::WireFormatLite::ReadBytes(google::protobuf::io::CodedInputStream*, std::string*)'
.build_release/lib/libcaffe.so: undefined reference to `google::protobuf::internal::StringTypeHandlerBase::Delete(std::string*)'
.build_release/lib/libcaffe.so: undefined reference to `google::protobuf::MessageFactory::InternalRegisterGeneratedFile(char const*, void (*)(std::string const&))'
.build_release/lib/libcaffe.so: undefined reference to `leveldb::DB::Open(leveldb::Options const&, std::string const&, leveldb::DB**)'
.build_release/lib/libcaffe.so: undefined reference to `cv::imencode(std::string const&, cv::_InputArray const&, std::vector<unsigned char, std::allocator<unsigned char> >&, std::vector<int, std::allocator<int> > const&)'
.build_release/lib/libcaffe.so: undefined reference to `google::protobuf::internal::StringTypeHandlerBase::New()'
.build_release/lib/libcaffe.so: undefined reference to `google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(int, std::string const&, google::protobuf::io::CodedOutputStream*)'
.build_release/lib/libcaffe.so: undefined reference to `leveldb::Status::ToString() const'
.build_release/lib/libcaffe.so: undefined reference to `google::protobuf::internal::WireFormatLite::WriteString(int, std::string const&, google::protobuf::io::CodedOutputStream*)'
collect2: error: ld returned 1 exit status
Makefile:596: recipe for target '.build_release/tools/convert_imageset.bin' failed
make: *** [.build_release/tools/convert_imageset.bin] Error 1

**Comment by seanbell** [comment]
This looks like a request for installation help.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
