### ISSUE TITLE
caffe compile error 

### ISSUE THREAD

**Issue by Ruhjkg** [BVLC/caffe#3517]
CXX/LD -o .build_release/tools/upgrade_net_proto_binary.bin
.build_release/lib/libcaffe.so: undefined reference to `cv::imread(cv::String const&, int)'
.build_release/lib/libcaffe.so: undefined reference to `cv::imencode(cv::String const&, cv::_InputArray const&, std::vector<unsigned char, std::allocator<unsigned char> >&, std::vector<int, std::allocator<int> > const&)'
.build_release/lib/libcaffe.so: undefined reference to `cv::imdecode(cv::_InputArray const&, int)'
collect2: error: ld returned 1 exit status
make: *** [.build_release/tools/upgrade_net_proto_binary.bin] Error 1

my opecv version is 3.0.0 ,and i have a try to  Added LIBRARIES += glog gflags protobuf leveldb snappy \ lmdb boost_system hdf5_hl hdf5 m \ opencv_core opencv_highgui opencv_imgproc opencv_imgcodecs to Makefile.config   

rm -rf ./build

but it have no use

so help !

**Comment by seanbell** [comment]
Take a look at https://github.com/BVLC/caffe/blob/50a23b7ba2c8fe9ee2f6e115bdc5948ff82c194d/Makefile.config.example#L21 .  Does this solve the issue?

**Comment by Ruhjkg** [comment]
i hava solved it ,make clean,not rm -rf ./build ,and add opencv_imgcodecs  to  opencv_core opencv_highgui opencv_imgproc in Makefile  not Makefile.config  ,that worked.

**Comment by seanbell** [comment]
Glad you solved it.
