### ISSUE TITLE
matlab interface use my train_caffemodel for image classification!"Check failed: target_blobs[j]->num() == source_layer.blobs(j).num() (96 vs. 0)"

### ISSUE THREAD

**Issue by rongrong005** [BVLC/caffe#3522]
first I use the imagenet framework to train my dataset, the data have 11 classes, so I change the output_num and the corresponding path , the result of training-processing is done with none error. 
Then I use the  caffenet_train_iter_6000.caffemodel、mean.binaryproto、deploy.prototxt to initial the 
caffe.There is a error come out after "Network initialization done. Memory required data:62433600. "
The error is :
"Check failed: target_blobs[j]->num() == source_layer.blobs(j).num() (96 vs. 0)"

If I use the "bvlc_reference_caffenet.caffemodel" and change the output_num , the classify is success!

How can I do with the error?

**Comment by rongrong005** [comment]
I retrain my model , get a new caffemodel, then everything is well!

**Comment by seanbell** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
