### ISSUE TITLE
Does caffe support kronecker operation?

### ISSUE THREAD

**Issue by musious** [BVLC/caffe#3523]
Hi, all. Recently I read some paper about kronecker production, which can use less parameters to get high accuracy. http://arxiv.org/pdf/1503.05671.pdf. Does caffe or some deep learning framework supports this? Thanks.

**Comment by ajdroid** [comment]
Try [caffe-users mailing list](https://groups.google.com/forum/#!forum/caffe-users). Close this issue as this isn't the right forum for it.

**Comment by seanbell** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
