### ISSUE TITLE
ConfigGen.cmake problem when running Cmake

### ISSUE THREAD

**Issue by FelipeGo** [BVLC/caffe#3524]
I followed the installation instructions of the website. In the build directory i ran <code>cmake..</code> As a result, I get the following error

<pre><code>
RegularExpression::compile(): Nested *?+.
RegularExpression::compile(): Error in compile.
CMake Error at cmake/ConfigGen.cmake:36 (if):
  if given arguments:

    "__e" "MATCHES" "^..../_caffe.*"

 Regular expression "^...../_caffe.*"
 cannot compile
Call Stack (most recent call first):
  cmake/ConfigGen.cmake:93 (caffe_get_items_with_prefix)
  CMakeLists.txt:85 (caffe_generate_export_configs)

-- Configuring incomplete, errors occurred!
See also "...../_caffe/build/CMakeFiles/CMakeOutput.log".
See also "...../_caffe/build/CMakeFiles/CMakeError.log".
</code></pre>
Im not an expert in <code>cmake</code>. However, I believe the problem is that the developer gave as argument to the function <code>caffe_get_items_with_prefix(3)</code> the <b>variable location</b> instead of the <b>variable name</b> as show in the following code
<pre><code>
 92   # remove source and build dir includes
 93   caffe_get_items_with_prefix(<b>${PROJECT_SOURCE_DIR}</b> Caffe_INCLUDE_DIRS __insource)
 94   caffe_get_items_with_prefix(<b>${PROJECT_BINARY_DIR}</b> Caffe_INCLUDE_DIRS __inbinary)
 95   list(REMOVE_ITEM Caffe_INCLUDE_DIRS <b>${__insource} ${__inbinary}</b>)
</code></pre>
I fixed it just by passing the variable name as argument:

<pre><code>
 92   # remove source and build dir includes
 93   caffe_get_items_with_prefix(PROJECT_SOURCE_DIR Caffe_INCLUDE_DIRS __insource)
 94   caffe_get_items_with_prefix(PROJECT_BINARY_DIR Caffe_INCLUDE_DIRS __inbinary)
 95   list(REMOVE_ITEM Caffe_INCLUDE_DIRS __insource __inbinary)
</code></pre>

I hope it helps anyone who encounters the same problem

Cheers!!

**Comment by kingrain213** [comment]
@FelipeGo I didnt find which file contains these lines, is it in "cmake/ConfigGen.cmake" ? but there are only 50 lines in my file

**Comment by FelipeGo** [comment]
@kingrain213 Hi, it has been a while I posted this thread. I believe that you have a newer version that the one I used by then. my _ConfigGen.cmake_ file has 117 lines. If you are having the same output problem I posted before I would suggest if  you are using Linux to _grep_ this lines:

`grep -rin  'caffe_get_items_with_prefix' *`

This will display the files and number line where I made the fix.
