### ISSUE TITLE
Element-wise multiplication by a fixed vector?

### ISSUE THREAD

**Issue by jcpeterson** [BVLC/caffe#3537]
I need to create a convnet that multiplies the output of a certain fc layer by a constant vector known in advance. For example, I might have a 4096 dimensional fc6 layer that I want multiplied by a 4096 vector that never changes. It seems like I would use EltwiseLayer for this, but I haven't seen any clear examples of its range of use, especially how to multiply by a static vector.

**Comment by aivision2020** [comment]
I guess you can have another input to the net.

**Comment by jcpeterson** [comment]
Can you elaborate?

**Comment by aivision2020** [comment]
it's possible to have more than one data layer. you can feed your fixed layer into it and then use it as one of the bottom to your EltwiseLayer. This is not very elegant but it will work
Alternatively, you can write a layer "PointWizeMult" (or something) that is somehow initialized with the constant values...

**Comment by seanbell** [comment]
I agree with @aivision2020.  You could have a dataset containing 1 item and feed it to a second data layer.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

**Comment by jcpeterson** [comment]
Ok, thanks, and sorry. Didn't know about the user group

**Comment by kritikaksu** [comment]
Hi. Did you do that? I was also searching for this and i found this post.

**Comment by jcpeterson** [comment]
Switch to another framework... ;)
