### ISSUE TITLE
Unable to draw the pretrained model

### ISSUE THREAD

**Issue by sijinli** [BVLC/caffe#354]
I download caffe_reference_imagenet_model and verify the downloaded file using "get_caffe_reference_imagenet_model.sh". Then I type

```
   /usr/bin/env python caffe/drawnet.py caffe_reference_imagenet_model netdraw 
```

here is the error I got, 

```
 Traceback (most recent call last):
 File "caffe/drawnet.py", line 75, in <module>
 text_format.Merge(open(sys.argv[1]).read(), net)
 File "/usr/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 152, in  
 Merge
  _MergeField(tokenizer, message)
 File "/usr/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 186, in    
 _MergeField
  name = tokenizer.ConsumeIdentifier()
  File "/usr/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 419, in      
  ConsumeIdentifier
 raise self._ParseError('Expected identifier.')
 google.protobuf.text_format.ParseError: 2:0 : Expected identifier.
```

**Comment by FernWan** [comment]
I have the the wrong that "google.protobuf.text_format.ParseError:3:22:Enum type"caffe.V1LayerParasemeter.LayerType"has no value named MIL_DATA.
How can I resolve the problem?

**Comment by williford** [comment]
@FernWan There is an error in your prototxt. MIL_DATA is not a valid layer type. Please ask on [Caffe user mailing list](https://groups.google.com/forum/#!forum/caffe-users) or on another website, such as http://stackoverflow.com/.

**Comment by sowmyadvn** [comment]
@sijinli  I got the same error in text_format.py. My code here:

```
mean_blob = caffe_pb2.BlobProto()
with(open(filename, "rb") as f:
         text_format.Merge(str(f.read()),mean_blob)
         mean_array = np.asarray(mean_blob.data, type = np.float32).reshape(mean_blob.channels,mean_blob.height, mean_blob.width))
         return mean_array.mean(1).mean(1)
```

Getting the error: google.protobuf.text_format.ParseError: 7:1 : Expected identifier.
Could you please let me know how you resolved the error? Thanks
