### ISSUE TITLE
cmake in qt creator fails but success in terminal

### ISSUE THREAD

**Issue by cslxiao** [BVLC/caffe#3540]
I open the cmakelist.txt with qtcreator and run cmake in the cmake wizard, but it fail with the following errors：

---------------------------------------------------------------------------------------------------------------------------------
-- Boost version: 1.57.0
-- Found the following Boost libraries:
--   system
--   thread
--   filesystem
-- Found gflags  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libgflags.so)
-- Found glog    (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libglog.so)
-- Found PROTOBUF Compiler: /usr/bin/protoc
-- Found lmdb    (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/liblmdb.so)
-- Found LevelDB (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libleveldb.so)
-- Found Snappy  (include: /usr/include, library: /usr/lib/libsnappy.so)
CMake Warning at cmake/Dependencies.cmake:63 (message):
  -- CUDA is not detected by cmake.  Building without it...
Call Stack (most recent call first):
  CMakeLists.txt:38 (include)

CMake Error at /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:108 (message):
  Could NOT find CUDA (missing: CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY) (found
  suitable exact version "7.0")
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:315 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-2.8/Modules/FindCUDA.cmake:806 (find_package_handle_standard_args)
  /usr/local/share/OpenCV/OpenCVConfig.cmake:45 (find_package)
  /usr/local/share/OpenCV/OpenCVConfig.cmake:241 (find_host_package)
  cmake/Dependencies.cmake:72 (find_package)
  CMakeLists.txt:38 (include)

-- Configuring incomplete, errors occurred!
See also "XX/caffe/caffe-master/Debug/CMakeFiles/CMakeOutput.log".
See also "XX/caffe/caffe-master/Debug/CMakeFiles/CMakeError.log".

---------------------------------------------------------------------------------------------------------------------------------

if seems that cuda are not found. But when I run cmake in the terminal, it always successes.
I want to debug with in qt creator, so what can I do the resolve this problem?? Thanks

**Comment by seanbell** [comment]
This looks like a request for help with installation.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
