### ISSUE TITLE
make_imagenet_mean.sh make my computer hung up in Centos 6.5

### ISSUE THREAD

**Issue by sixiong** [BVLC/caffe#3544]
my train data relabel_train_lmdb the size is in 180GB,when I try to use the shell 'make_imagenet_mean.sh' to compute the image mean file,the computer was hung up after 20 minutes.

the computer is Dell PowerEdge R730 and Centos 6.5

any one could give me any suggestions?

**Comment by seanbell** [comment]
This looks like a request for help.  If you think you found a bug in caffe, please re-open the issue.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

**Comment by sixiong** [comment]
thanks,sorry for troubling you.
