### ISSUE TITLE
Simple way of getting ImageNet's caffe example data

### ISSUE THREAD

**Issue by fernandoc1** [BVLC/caffe#3549]
I'm trying to reproduce ImageNet's caffe example, found in http://caffe.berkeleyvision.org/gathered/examples/imagenet.html , but I'm unable to find a way to download the images required by the example.
Could someone point me a link for that, or a script for downloading this data?

**Comment by seanbell** [comment]
http://image-net.org/challenges/LSVRC/2012/signup

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
