### ISSUE TITLE
Reshape layer

### ISSUE THREAD

**Issue by affromero** [BVLC/caffe#3551]
Caffe used to have RESHAPE layer but it is no longer available, at least that's what I see in https://github.com/BVLC/caffe/blob/master/src/caffe/proto/caffe.proto#L1062

Now, I am having a problem, I have one layer which produces N x C (1) vector and another with N x C x H x W (2). I want to perform ACCURACY layer between them, but I cant. I tried to flatten (2) into (1) but got the same error as it were not performed.

This is the error: *Number of labels must match number of predictions; e.g., if label axis == 1 and prediction shape is (N, C, H, W), label count (number of labels) must be N*H*W, with integer values in {0, 1, ..., C-1}.*
I need to achieve (2) from (1) but I do not know how.

I am sorry to post this here but no one answer me at caffe users group and I am a little desperate.

**Comment by seanbell** [comment]
I'm sorry that nobody helped you on the users group, but that doesn't change the fact that this isn't the right place to ask the question.

The reshape layer was never deleted: https://github.com/BVLC/caffe/blob/master/src/caffe/proto/caffe.proto#L385
