### ISSUE TITLE
Running MNIST example

### ISSUE THREAD

**Issue by fernandoc1** [BVLC/caffe#3552]
I'm trying to run the MNIST example found here:
http://caffe.berkeleyvision.org/gathered/examples/mnist.html

So, after training the network, as explained in the document above, I have used the following command to classify:

python python/classify.py --gpu --model_def examples/mnist/lenet.prototxt --pretrained_model examples/mnist/lenet_iter_10000.solverstate ~/tmp/1987.png /tmp/output.png

However, I face an error in the last line:

F0113 19:47:47.948740 44220 upgrade_proto.cpp:75] Check failed: ReadProtoFromBinaryFile(param_file, param) Failed to parse NetParameter file: examples/mnist/lenet_iter_10000.solverstate

Can someone help me finding what is going on?

**Comment by seanbell** [comment]
You want the caffemodel file, not the solverstate file.  The former contains the weights, and the latter contains the momentum vector.

**Comment by seanbell** [comment]
Also, please ask questions like this on the mailing list, not the issues page.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
