### ISSUE TITLE
Training VGG Model

### ISSUE THREAD

**Issue by 3DTOPO** [BVLC/caffe#3554]
I am completely new to Caffe, and I am interested in training a VGG model from scratch (perhaps with 13-convultional layers and 16-layers total). It seems like https://groups.google.com/forum/#!topic/caffe-users/v7XlpZO0SW4 is a good hint, but could someone give a complete noob a little more information? I have the ImageNet data downloaded and available. Thanks!

**Comment by seanbell** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
