### ISSUE TITLE
some problem about flying caffe

### ISSUE THREAD

**Issue by BrendenWashington** [BVLC/caffe#3556]
I just install caffe and all runtest passed

furthermore, the minist example also passed

but when I try to use my owm image data to train a net, the training process just stoped before loading lmdb or level data into the net, it just stop there and don't give any error, it seems it enters a infinite loop...

however, if I try to train the net by image data directly, the caffe can fly, but not convergence.

so, what can I do?

**Comment by seanbell** [comment]
This looks like a request for help.  If you think you found a bug in caffe, please re-open the issue.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
