### ISSUE TITLE
Can Caffe load Torch models?

### ISSUE THREAD

**Issue by kingofoz** [BVLC/caffe#3557]
I cannot find documents about this scenario, so I have to file an issue to ask... I will close it soon.

**Comment by ajtulloch** [comment]
https://github.com/facebook/fb-caffe-exts#torch2caffe might be useful for your purposes.

**Comment by kingofoz** [comment]
Thanks for the tool, @ajtulloch I will try it. :+1:

**Comment by kingofoz** [comment]
Hi @ajtulloch 
I still have a question, my torch model is an autoencoder, it uses Fista in decoder layer like https://github.com/koraykv/unsup/blob/master/SpatialConvFistaL1.lua
Is this model(using Fista) feasible to convert to Caffe?

Thanks,
Yingjun
