### ISSUE TITLE
error: ‘google::protobuf::is_proto_enum’ is not a template type

### ISSUE THREAD

**Issue by wangg12** [BVLC/caffe#3558]
Error occured when I tried to make the newest caffe. My google.protobuf version is '3.0.0a4'. How can I fix this?

**Comment by wangg12** [comment]
solved by reinstalling protobuf 2.6

**Comment by seanbell** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

**Comment by seanbell** [comment]
If only certain versions of protobuf work, perhaps the [documentation](http://caffe.berkeleyvision.org/installation.html) should be updated to reflect this?

**Comment by Darienzhangyy** [comment]
May I ask how you reinstalling protobuf 2.6? I tried apt-get upgrade but it is not working... Thanks!

**Comment by Darienzhangyy** [comment]
May I ask how you reinstalled protobuf 2.6? I tried apt-get upgrade but it did not work... Thanks!
