### ISSUE TITLE
How to use matlab caffe for fine-tuning the existed model?

### ISSUE THREAD

**Issue by tzczsq** [BVLC/caffe#3560]
Hi, I want to use matlab caffe to perform fine tuning tasks with the downloaded model? 
I coud not find an example for matlab caffe use for fine-tuning tasks?
could you give me an example?

**Comment by seanbell** [comment]
This looks like a request for help.  From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
