### ISSUE TITLE
Relu layer in C++

### ISSUE THREAD

**Issue by onlytailei** [BVLC/caffe#3562]

**Comment by onlytailei** [comment]
I use caffe in GPU mode and C++ interface.
Data is transferred to network by Memorydata layer.
But when I use a batch with several input image like (32, 1, 140, 160)
If there is only one input image in the batch. Everything is fine.
If I use the Relu layer, it seems that there is no forward calculation, and every output of the whole batch is the same as the one before caclulated by the one input.

If I change the ReLU to Sigmoid, everything is fine.

**Comment by seanbell** [comment]
If you think you found a bug, can you describe how to reproduce it using a minimal number of steps?

If this is instead a request help, please see the caffe-users mailing list.  https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

**Comment by onlytailei** [comment]
Sorry. 
Just find that it is not a bug.
When the network is more complicated than before. At the beginning, the output is the same.

**Comment by Mengmengbai** [comment]
> I use caffe in GPU mode and C++ interface.
> Data is transferred to network by Memorydata layer.
> But when I use a batch with several input image like (32, 1, 140, 160)
> If there is only one input image in the batch. Everything is fine.
> If I use the Relu layer, it seems that there is no forward calculation, and every output of the whole batch is the same as the one before caclulated by the one input.
> 
> If I change the ReLU to Sigmoid, everything is fine.

I also meet the same problem.
Do you have a solution to this problem?
