### ISSUE TITLE
Can I use caffe for feature extraction of 3D object?

### ISSUE THREAD

**Issue by yobichi** [BVLC/caffe#3563]
I have more than 1000 minecraft entities and I want to do some clustering. Can I caffe to extract the feature such as colour, shape, texture and so on?

**Comment by bhack** [comment]
You can find some work on 3d objects here https://github.com/BVLC/caffe/pull/3123

**Comment by seanbell** [comment]
For modeling questions, please see the caffe-users list.  See https://raw.githubusercontent.com/BVLC/caffe/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
