### ISSUE TITLE
Number of Net output

### ISSUE THREAD

**Issue by fixtern** [BVLC/caffe#3566]
Hi guys,
I have defined a network works on UCF-101 dataset which has 101 classes based on ALEXNet or referenceNet . So i have to set a last layer 101 neurons .But when i do it my network didn't converged and after 200,000 iterations it has error loss 2.7 and its accuracy is only 6 % ! This occurred for various learning rates like 0.01 or 0.001 or 0.0001.

It is strange to tell you when i set the number of network output as 1000 the network works as well and after 200,000 its accuracy becomes 99.8673 %. 
Please tell me why ? why network doesn't work well when we change number of output to our class?
Thanks a lot.

**Comment by seanbell** [comment]
See https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
