### ISSUE TITLE
some errors when building the solutions. cuda7.0+windows+vs2012

### ISSUE THREAD

**Issue by anewlearner** [BVLC/caffe#3577]
When I build the  file in  ./build/MSVC ,there are some grammar errors and many warnings.  How coud I solve this? Thanks!
c:\program files\nvidia gpu computing toolkit\cuda\v7.0\include\math_functions.h : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>I:\APPs\install\vs2012\VC\include\concrt.h(5762): error C2015: 常量中的字符太多
1>I:\APPs\install\vs2012\VC\include\concrt.h(5762): error C2146: 语法错误: 缺少“)”(在标识符“q”的前面)
1>I:\APPs\install\vs2012\VC\include\concrt.h(5762): error C2059: 语法错误:“)”
1>I:\APPs\install\vs2012\VC\include\concrt.h(5762): error C2001: 常量中有换行符
1>I:\APPs\install\vs2012\VC\include\concrt.h(5775): error C2143: 语法错误 : 缺少“)”(在“{”的前面)
1>I:\APPs\install\vs2012\VC\include\concrt.h(5775): error C2143: 语法错误 : 缺少“;”(在“{”的前面)
1>I:\APPs\install\vs2012\VC\include\concrt.h(5775): error C2447: “{”: 缺少函数标题(是否是老式的形式表?)
1>I:\APPs\install\vs2012\VC\include\concrt.h(5775): error C2015: 常量中的字符太多

**Comment by seanbell** [comment]
Windows is not officially supported in caffe.  Also, since this is an installation question please ask the mailing list.  From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

**Comment by Grillnov** [comment]
Concrt.h is an official include header file for Visual Studio and Visual Studio can't compile it correctly
Nice work Microsoft idiots

**Comment by Yuhe-Wang** [comment]
将cuda 7.x的cudafe++.exe (C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.5\bin) 替换成cuda 6.5版本的cudafe++.exe应该可以解决问题， 但可能失去cuda7.x C++11新特性的支持
