### ISSUE TITLE
`make all` produces error: `identifier "__float128" is undefined`

### ISSUE THREAD

**Issue by alexge233** [BVLC/caffe#3578]
Hi,

I'm building on Debian 8.0 (Jessie) using:
* ` g++ 4.8.4-1`
* `nvcc 6.5.12`
* `boost 1.601`
* `intel mkl 11.3.0.109`

I've installed all dependencies, but once g++ finishes and nvcc starts, I get:

```
NVCC src/caffe/util/math_functions.cu
/usr/local/boost/config/suffix.hpp(510): error: identifier "__float128" is undefined
/usr/local/boost/smart_ptr/detail/sp_counted_base_gcc_x86.hpp(49): warning: "cc" clobber ignored
/usr/local/boost/smart_ptr/detail/sp_counted_base_gcc_x86.hpp(65): warning: "cc" clobber ignored
/usr/local/boost/smart_ptr/detail/sp_counted_base_gcc_x86.hpp(91): warning: "cc" clobber ignored
/usr/local/boost/smart_ptr/detail/sp_counted_base_gcc_x86.hpp(75): warning: variable "tmp" was set but never used

1 error detected in the compilation of "/tmp/tmpxft_000018d0_00000000-15_math_functions.compute_50.cpp1.ii".
Makefile:565: recipe for target '.build_release/cuda/src/caffe/util/math_functions.o' failed
make: *** [.build_release/cuda/src/caffe/util/math_functions.o] Error 1
```

Is there any solution/workaround ?

**Comment by alexge233** [comment]
Turns out its a boost 1.60 bug, [here's a post and patch](https://svn.boost.org/trac/boost/ticket/11852).

**Comment by SeoungSeon** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

go21@naver.com 님께 보내신 메일 <Re: [caffe] `make all` produces error: `identifier "__float128" is undefined` (#3578)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by bittnt** [comment]
FYI.
change suffix.hpp line 512, from 
__extension__ typedef __float128 float128_type; 
to 
__extension__ typedef long double float128_type;
