### ISSUE TITLE
Compiler the convert_imageset.cpp file

### ISSUE THREAD

**Issue by LiquidE3** [BVLC/caffe#3585]
如題所示，我想要把jpg圖檔轉成caffe的lmdb/leveldb格式，然後需要先將convert_imageset.cpp做compiler，但是會有convert_imageset.cpp:21:34: fatal error: caffe/proto/caffe.pb.h: 沒有此一檔案或目錄的問題，並且發現caffe-master裡面並沒有caffe.pb.h、db.hpp、format.hpp、io.hpp、rng.hpp標頭檔，想請問您關於這部分要怎麼解決?

**Comment by shaibagon** [comment]
I'm sorry but we can only handle issues in English.
