### ISSUE TITLE
Expose library version to matcaffe

### ISSUE THREAD

**Issue by shelhamer** [BVLC/caffe#3592]
#3311 added library versioning and exposed it to pycaffe but matcaffe needs a similar property for version checking.

**Comment by SeoungSeon** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

go21@naver.com 님께 보내신 메일 <Re: [caffe] Expose library version to matcaffe (#3592)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------
