### ISSUE TITLE
When i run the examples "train_mnist_autoencoder.sh" ,it failed

### ISSUE THREAD

**Issue by Agethub** [BVLC/caffe#3596]
I0124 22:27:07.985637  4793 layer_factory.hpp:77] Creating layer mnist
I0124 22:27:07.985697  4793 net.cpp:106] Creating Layer mnist
I0124 22:27:07.985709  4793 net.cpp:411] mnist -> data
I0124 22:27:07.985723  4793 net.cpp:411] mnist -> label

It run until this and it won't run any more even after a long time ,I want to know why it happened?

**Comment by astorfi** [comment]
It actually stuck ... One of the possible reason is in the "mnist_autoencoder.prototxt" file ...
The Flatten layer is like that:

layer {
  name: "flatdata"
  type: "Flatten"
  bottom: "data"
  top: "flatdata"
}

I used an IDE to run this(Although it needed some modification for the path and not the "mnist_autoencoder.prototxt" or the other Caffe related files) ... It seems that the Caffe cannot realize the bottom:"data" ... It might be related to different data labels that been used simultaneously for creating "mnist_autoencoder.prototxt" file ... I don't know ... I'm still working on that ...

**Comment by saltsuger** [comment]
Thank you very much!
I think the problem is the layer of input data of autoencoder network. Because the autoencoder is an unsupervised learning, it does not need the labels. When we get the data from the leveldb or lmdb, I guess we should convert the data firstly instead of using the leveldb which is used in the le-net or others.
 But I don't know how to convert the images without the labels.

**Comment by darren1231** [comment]
So???
Can anyone talk to me how to solve this problem?

**Comment by astorfi** [comment]
The following modification in the mnist_autoencoder.prototxt solves the problem:

layer {
  name: "data"
  type: "Data"
  top: "data"
  include {
    phase: TRAIN
  }
  transform_param {
    scale: 0.0039215684
  }
  data_param {
    source: "examples/mnist/mnist_train1_lmdb"
    batch_size: 100
    backend: LMDB
  }
}
layer {
  name: "data"
  type: "Data"
  top: "data"
  include {
    phase: TEST
    stage: "test-on-train"
  }
  transform_param {
    scale: 0.0039215684
  }
  data_param {
    source: "examples/mnist/mnist_train2_lmdb"
    batch_size: 100
    backend: LMDB
  }
}

The files "mnist_train1_lmdb" and "mnist_train2_lmdb" are the same files with different name. It looks like Caffe has a bug to read simultaneously from the same file.

The files "mnist_train1_lmdb" and "mnist_train2_lmdb" are copies of the "mnist_train_lmdb" file.

**Comment by saltsuger** [comment]
Thank you @astorfi , That is ,different input layers should have different data source even the layers use the same data. Do you agree ?

**Comment by astorfi** [comment]
Yes ... I believe that's right ...
