### ISSUE TITLE
I find a bug in include/caffe/blob.hpp

### ISSUE THREAD

**Issue by Jieeee** [BVLC/caffe#3598]
In the file include/caffe/blob.hpp, the 168th line initialized the variable offset to zero,which should be initialized to 1. I'm thinking why caffe still works well with this bug.

**Comment by Jieeee** [comment]
Sorry for my carelessness.

**Comment by seanbell** [comment]
You're talking about this https://github.com/BVLC/caffe/blob/master/include/caffe/blob.hpp#L168 ?

Why should it be 1?  The outermost shape axis should never be multiplied as part of an indexing calculation, so I think that the current code is correct.

Please show an example case where the calculation is incorrect (example input and expected output).

**Comment by Jieeee** [comment]
Thank u for your reply,I have made it out.
