### ISSUE TITLE
clang: warning: argument unused during compilation: '-pthread'

### ISSUE THREAD

**Issue by weather319** [BVLC/caffe#3608]
I am installing caffe in my mac ox system with cpu only , I followed the steps on https://haduonght.wordpress.com/2015/02/21/install-caffe-on-mac-os-x-10-10/

Then some errors came out after 'make all' step :
FIRST 
CXX src/caffe/util/blocking_queue.cpp
src/caffe/util/blocking_queue.cpp:50:7: warning: unused typedef 'INVALID_REQUESTED_LOG_SEVERITY' [-Wunused-local-typedef]
      LOG_EVERY_N(INFO, 1000)<< log_on_wait;
      ^
/usr/local/include/glog/logging.h:917:30: note: expanded from macro 'LOG_EVERY_N'
                             INVALID_REQUESTED_LOG_SEVERITY);           \
                             ^
/usr/local/include/glog/logging.h:912:73: note: expanded from macro 'GOOGLE_GLOG_COMPILE_ASSERT'
  typedef google::glog_internal_namespace_::CompileAssert<(bool(expr))> msg[bool(expr) ? 1 : -1]
                                                                        ^
1 warning generated.

SECOND

AR -o .build_release/lib/libcaffe.a
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: .build_release/lib/libcaffe.a(cudnn_conv_layer.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: .build_release/lib/libcaffe.a(cudnn_lcn_layer.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: .build_release/lib/libcaffe.a(cudnn_lrn_layer.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: .build_release/lib/libcaffe.a(cudnn_pooling_layer.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: .build_release/lib/libcaffe.a(cudnn_relu_layer.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: .build_release/lib/libcaffe.a(cudnn_sigmoid_layer.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: .build_release/lib/libcaffe.a(cudnn_softmax_layer.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: .build_release/lib/libcaffe.a(cudnn_tanh_layer.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: .build_release/lib/libcaffe.a(cudnn.o) has no symbols
LD -o .build_release/lib/libcaffe.so.1.0.0-rc3
clang: warning: argument unused during compilation: '-pthread'
CXX tools/caffe.cpp
CXX/LD -o .build_release/tools/caffe.bin
clang: warning: argument unused during compilation: '-pthread'
CXX tools/compute_image_mean.cpp
CXX/LD -o .build_release/tools/compute_image_mean.bin
clang: warning: argument unused during compilation: '-pthread'
CXX tools/convert_imageset.cpp
CXX/LD -o .build_release/tools/convert_imageset.bin
clang: warning: argument unused during compilation: '-pthread'
CXX tools/device_query.cpp
CXX/LD -o .build_release/tools/device_query.bin
clang: warning: argument unused during compilation: '-pthread'
CXX tools/extract_features.cpp
CXX/LD -o .build_release/tools/extract_features.bin
clang: warning: argument unused during compilation: '-pthread'
CXX tools/finetune_net.cpp
CXX/LD -o .build_release/tools/finetune_net.bin
clang: warning: argument unused during compilation: '-pthread'
CXX tools/net_speed_benchmark.cpp
CXX/LD -o .build_release/tools/net_speed_benchmark.bin
clang: warning: argument unused during compilation: '-pthread'
CXX tools/test_net.cpp
CXX/LD -o .build_release/tools/test_net.bin
clang: warning: argument unused during compilation: '-pthread'
CXX tools/train_net.cpp
CXX/LD -o .build_release/tools/train_net.bin
clang: warning: argument unused during compilation: '-pthread'
CXX tools/upgrade_net_proto_binary.cpp
CXX/LD -o .build_release/tools/upgrade_net_proto_binary.bin
clang: warning: argument unused during compilation: '-pthread'
CXX tools/upgrade_net_proto_text.cpp
CXX/LD -o .build_release/tools/upgrade_net_proto_text.bin
clang: warning: argument unused during compilation: '-pthread'
CXX tools/upgrade_solver_proto_text.cpp
CXX/LD -o .build_release/tools/upgrade_solver_proto_text.bin
clang: warning: argument unused during compilation: '-pthread'
CXX examples/cifar10/convert_cifar_data.cpp
CXX/LD -o .build_release/examples/cifar10/convert_cifar_data.bin
clang: warning: argument unused during compilation: '-pthread'
CXX examples/cpp_classification/classification.cpp
CXX/LD -o .build_release/examples/cpp_classification/classification.bin
clang: warning: argument unused during compilation: '-pthread'
CXX examples/mnist/convert_mnist_data.cpp
CXX/LD -o .build_release/examples/mnist/convert_mnist_data.bin
clang: warning: argument unused during compilation: '-pthread'
CXX examples/siamese/convert_mnist_siamese_data.cpp
CXX/LD -o .build_release/examples/siamese/convert_mnist_siamese_data.bin
clang: warning: argument unused during compilation: '-pthread'

I have searched Internet for a long time but cannot fix those problem.My system is ox 10.10 with anaconda and python 3.5m

**Comment by hackwfu** [comment]
I've also been getting this exact problem

**Comment by dpaiton** [comment]
That clang warning is not something that will prevent caffe from compiling correctly. However, if you still want to get rid of it, you can remove the '-pthread' flag from your CXXFLAGS and LINKFLAGS in your Makefile.

**Comment by shelhamer** [comment]
Right, the `-pthread` and GLOG warnings are harmless on OS X. That said, any polishing of the build is welcome so feel free to send a pull request.
