### ISSUE TITLE
Efficiency improvement by CNN branch pruning

### ISSUE THREAD

**Issue by 0xBrandon** [BVLC/caffe#3621]
Suggested addition:

A recent paper in NIPS 2015 had some great results with both space and performance optimizations by pruning branches. 9x space improvement and 3x computational improvement with no accuracy loss using AlexNet and VGG-16 on ImageNet.

If possible, it would be an amazing addition to Caffe. Here is the paper link:

http://papers.nips.cc/paper/5784-learning-both-weights-and-connections-for-efficient-neural-network.pdf

**Comment by shaibagon** [comment]
You are welcome to contribute this change as a PR to caffe! See [how to contribute](http://caffe.berkeleyvision.org/development.html) for more details.
