### ISSUE TITLE
Regarding Validation and Test set in caffe

### ISSUE THREAD

**Issue by surajits** [BVLC/caffe#3622]
hi
I have created a dataset and i have trained in caffe. Here in the test Phase i have val_lmdb.
Now my question is how do we input the test data? Is it both validation and test data same here?
Because we have only train_lmdb and val_lmdb, what about the test data.

**Comment by rohrbach** [comment]
Closing as this is a usage issue.

Please ask usage questions on caffe-users: https://groups.google.com/forum/#!forum/caffe-users. 
If you do think there is a bug in Caffe, you're welcome to open a new issue according to https://github.com/BVLC/caffe/wiki/Reporting-Bugs-and-Other-Issues. Thanks!
