### ISSUE TITLE
Python layer reshape bug.

### ISSUE THREAD

**Issue by BlGene** [BVLC/caffe#3625]
If I am running the following piece of code(see below) as part of a network. With the output of the layer silenced, it runs without a problem. This is the expected behavior, but it changes when I make the following changes.
1. Removing the Silence Layer.
   If I remove the silence layer, I get the following error:
   `F0203 02:14:52.596499  3861 blob.cpp:113] Check failed: data_`
   I understand this to be the code trying to read the output data, but there not being any. This is not what I expected, but probably fair enough. ( I'm trying to run an Epoch accumulation of loss and accuracy, so it would be cool to have output only on certain occasions, in theory should a sometimes empty output layer be allowed? )
2. Double reshape.
   If I do a `top[0].reshape(1)` before the `top[0].reshape(0)` the code runs through again, which makes me slightly queasy.

Are either of these bugs?

```
class EpochAccum(caffe.Layer):
    def setup(self, bottom, top):
        assert(len(bottom) == 1)

    def reshape(self, bottom, top):
        #top[0].reshape(1) # remove '#' here and code will work again.
        top[0].reshape(0)
```

**Comment by seanbell** [comment]
See #3583
