### ISSUE TITLE
Compile fails: g++ Ubuntu 14.04 

### ISSUE THREAD

**Issue by marcoippolito** [BVLC/caffe#3626]
During compiling of Caffe in my Ubuntu 14.04 Server Edition with GPU: Nvidia  GeForce GTX770
cuda_6.5.14, cudnn-6.5-linux-x64-v2 if I put in Makefile.config:
CUSTOM_CXX := g++
I get these erros:

marco@pc:~/caffe-master$ make all -j4
PROTOC src/caffe/proto/caffe.proto
CXX src/caffe/solvers/adagrad_solver.cpp
CXX src/caffe/solvers/sgd_solver.cpp
CXX src/caffe/solvers/nesterov_solver.cpp
make: execvp: protoc: Non è una directory
Makefile:620: recipe for target '.build_release/src/caffe/proto/caffe.pb.cc' failed
make: *** [.build_release/src/caffe/proto/caffe.pb.cc] Error 127
make: *** Attesa per i processi non terminati....
In file included from ./include/caffe/util/device_alternate.hpp:40:0,
                 from ./include/caffe/common.hpp:19,
                 from ./include/caffe/blob.hpp:8,
                 from ./include/caffe/net.hpp:10,
                 from ./include/caffe/solver.hpp:7,
                 from ./include/caffe/sgd_solvers.hpp:7,
                 from src/caffe/solvers/sgd_solver.cpp:4:
./include/caffe/util/cudnn.hpp:5:19: fatal error: cudnn.h: File o directory non esistente
 #include <cudnn.h>
                   ^
compilation terminated.
Makefile:563: recipe for target '.build_release/src/caffe/solvers/sgd_solver.o' failed
make: *** [.build_release/src/caffe/solvers/sgd_solver.o] Error 1
In file included from ./include/caffe/util/device_alternate.hpp:40:0,
                 from ./include/caffe/common.hpp:19,
                 from ./include/caffe/blob.hpp:8,
                 from ./include/caffe/net.hpp:10,
                 from ./include/caffe/solver.hpp:7,
                 from ./include/caffe/sgd_solvers.hpp:7,
                 from src/caffe/solvers/adagrad_solver.cpp:3:
./include/caffe/util/cudnn.hpp:5:19: fatal error: cudnn.h: File o directory non esistente
 #include <cudnn.h>
                   ^
compilation terminated.
Makefile:563: recipe for target '.build_release/src/caffe/solvers/adagrad_solver.o' failed
make: *** [.build_release/src/caffe/solvers/adagrad_solver.o] Error 1
In file included from ./include/caffe/util/device_alternate.hpp:40:0,
                 from ./include/caffe/common.hpp:19,
                 from ./include/caffe/blob.hpp:8,
                 from ./include/caffe/net.hpp:10,
                 from ./include/caffe/solver.hpp:7,
                 from ./include/caffe/sgd_solvers.hpp:7,
                 from src/caffe/solvers/nesterov_solver.cpp:3:
./include/caffe/util/cudnn.hpp:5:19: fatal error: cudnn.h: File o directory non esistente // translation=File or directory doesn't exist
 #include <cudnn.h>
                   ^
compilation terminated.
Makefile:563: recipe for target '.build_release/src/caffe/solvers/nesterov_solver.o' failed
make: *** [.build_release/src/caffe/solvers/nesterov_solver.o] Error 1

If I specify in Makefile.config the version of g++:
CUSTOM_CXX := g++4.9.3
I get these errors:

PROTOC src/caffe/proto/caffe.proto
CXX src/caffe/solvers/adagrad_solver.cpp
CXX src/caffe/solvers/sgd_solver.cpp
CXX src/caffe/solvers/nesterov_solver.cpp
make: execvp: protoc: Non è una directory
Makefile:620: recipe for target '.build_release/src/caffe/proto/caffe.pb.cc' failed
make: *** [.build_release/src/caffe/proto/caffe.pb.cc] Error 127
make: *** Attesa per i processi non terminati....
/bin/sh: g++4.9.3: comando non trovato
Makefile:563: recipe for target '.build_release/src/caffe/solvers/adagrad_solver.o' failed
make: *** [.build_release/src/caffe/solvers/adagrad_solver.o] Error 1
/bin/sh: g++4.9.3: comando non trovato // translation=command not found
/bin/sh: g++4.9.3: comando non trovato
Makefile:563: recipe for target '.build_release/src/caffe/solvers/sgd_solver.o' failed
make: *** [.build_release/src/caffe/solvers/sgd_solver.o] Error 1
Makefile:563: recipe for target '.build_release/src/caffe/solvers/nesterov_solver.o' failed
make: *** [.build_release/src/caffe/solvers/nesterov_solver.o] Error 1

So...What do I have to do?
Marco

**Comment by seanbell** [comment]
See this line from your printout:
> ./include/caffe/util/cudnn.hpp:5:19: fatal error: cudnn.h: File o directory non esistente

You need to make sure that cudnn is on your include path.  Or, you should disable cudnn and use the built-in GPU engine.

**Comment by marcoippolito** [comment]
Yes, thank you
I solved it copying cudnn.h into cuda/include folder.
