### ISSUE TITLE
matcaffe - ubuntu

### ISSUE THREAD

**Issue by prathmeshrmadhu** [BVLC/caffe#3630]
Error Message - Undefined variable "caffe" or class "caffe.reset_all". 
System - UBUNTU 14.04, with matlab R2015b academic version, already did "make matcaffe', tried once again and it says, "nothing to be done for 'matcaffe'". 

So, assuming that matcaffe is properly installed, i am running a .mat file whose first line goes like this,
caffe.reset_all(); 
and its displays the above message. I have added mex file to the path as per the installation guide on official Caffe installation page. Could anyone please guide me?

**Comment by zhFuECL** [comment]
I have the same problem.
How to deal with it?_

**Comment by jiqiujia** [comment]
you should add the path of caffe.mex to the matlab path environment

**Comment by prathmeshrmadhu** [comment]
Later I solved the issue. 

Once you are done with compiling matcaffe and also mattest.
In MATLAB environment, set the cwd to caffe root folder. Then use 'addpath ./matlab'. This will work.
