### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by billqu** [BVLC/caffe#3635]
I have installed as cup only way. 
Nont install cuda and libstdc++.
I install by the document, http://caffe.berkeleyvision.org/install_osx.html.
and I build, but error.
qugmatoMacBook-Pro:caffe-master qug$ make all
PROTOC src/caffe/proto/caffe.proto
make: protoc: No such file or directory
make: *** [.build_release/src/caffe/proto/caffe.pb.cc] Error 1

How to solve?

Thank you.

**Comment by rohrbach** [comment]
Closing as this is a usage issue.

Please ask usage questions on caffe-users: https://groups.google.com/forum/#!forum/caffe-users. 
If you do think there is a bug in Caffe, you're welcome to open a new issue according to https://github.com/BVLC/caffe/wiki/Reporting-Bugs-and-Other-Issues. Thanks!
