### ISSUE TITLE
undefined symbol when make runtest: "undefined symbol: _ZN6google16SetVersionStringERKSs" AND "undefined symbol: _ZN6google15SetUsageMessageERKSs"

### ISSUE THREAD

**Issue by hnanhtuan** [BVLC/caffe#3637]
There is a problem when 
`make runtest -j8`
The output is as following:
`.build_release/tools/caffe
.build_release/tools/caffe: symbol lookup error: .build_release/tools/caffe: undefined symbol: _ZN6google16SetVersionStringERKSs
Makefile:514: recipe for target 'runtest' failed
make: *** [runtest] Error 127
`
There is no problem when:
`make all -j8`
`make test -j8`
`make pycaffe -j8`
`make matcaffe -j8`

Additionally, when I run:
`sh examples/mnist/create_mnist.sh`

There is another error message:
`Creating lmdb...
build/examples/mnist/convert_mnist_data.bin: symbol lookup error: build/examples/mnist/convert_mnist_data.bin: undefined symbol: _ZN6google15SetUsageMessageERKSs
build/examples/mnist/convert_mnist_data.bin: symbol lookup error: build/examples/mnist/convert_mnist_data.bin: undefined symbol: _ZN6google15SetUsageMessageERKSs
Done.
`

I am not sure what is going wrong. Last time install cafffe, I have everything going smooth with Ubuntu 14. Now, I am using Ubuntu 15 (I must use ubuntu 15 since I faced another problem with ubuntu 14).

Please help me to fix this issue. Any idea would be appreciated.

**Comment by seanbell** [comment]
As far as I know, caffe does not work out-of-the-box with Ubuntu 15.*, and you need to fix header/linking issues yourself.  If you want it to work out-of-the-box, please use Ubuntu 14.04 or 12.04.

Please review the other issues which look at this problem: https://github.com/BVLC/caffe/search?utf8=%E2%9C%93&q=ubuntu+15&type=Issues

**Comment by seanbell** [comment]
This looks like a linking problem with a google library (either glog or protobuf).

As far as I know, caffe does not work out-of-the-box with Ubuntu 15.*, and you need to fix header/linking issues yourself.  If you want caffe to work as-is, use Ubuntu 14.04 or 12.04.  Please review the other issues which look at this problem: https://github.com/BVLC/caffe/search?utf8=%E2%9C%93&q=ubuntu+15&type=Issues

**Comment by shelhamer** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
