### ISSUE TITLE
zsh: segmentation fault

### ISSUE THREAD

**Issue by datomnurdin** [BVLC/caffe#3647]
I'm using `python 2.7.10` and `GCC 4.2.1` on OSX.

My `make.config` python setting configuration

    PYTHON_INCLUDE := /usr/include/python2.7 \
    		/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/core/include
    # Anaconda Python distribution is quite popular. Include path:
    # Verify anaconda location, sometimes it's in root.
    # ANACONDA_HOME := $(HOME)/anaconda
    # PYTHON_INCLUDE := $(ANACONDA_HOME)/include \
    		# $(ANACONDA_HOME)/include/python2.7 \
    		# $(ANACONDA_HOME)/lib/python2.7/site-packages/numpy/core/include \
    
    # Uncomment to use Python 3 (default is Python 2)
    # PYTHON_LIBRARIES := boost_python3 python3.5m
    # PYTHON_INCLUDE := /usr/include/python3.5m \
    #                 /usr/lib/python3.5/dist-packages/numpy/core/include
    
    # We need to be able to find libpythonX.X.so or .dylib.
    PYTHON_LIB := /usr/lib
    # PYTHON_LIB := $(ANACONDA_HOME)/lib
    
    # Homebrew installs numpy in a non standard path (keg only)
    # PYTHON_INCLUDE += $(dir $(shell python -c 'import numpy.core; print(numpy.core.__file__)'))/include
    # PYTHON_LIB += $(shell brew --prefix numpy)/lib
    
    # Uncomment to support layers written in Python (will link against Python libs)
    # WITH_PYTHON_LAYER := 1
    
    # Whatever else you find you need goes here.
    INCLUDE_DIRS := $(PYTHON_INCLUDE) /usr/local/include
    LIBRARY_DIRS := $(PYTHON_LIB) /usr/local/lib /usr/lib

When I import caffe, I got this error message

    zsh: segmentation fault

Problem details and System Configuration

    Process:               Python [11913]
    Path:                  /Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
    Identifier:            Python
    Version:               2.7.10 (2.7.10)
    Code Type:             X86-64 (Native)
    Parent Process:        zsh [11816]
    Responsible:           Terminal [11519]
    User ID:               501
    
    Date/Time:             2016-02-09 15:49:27.396 +0800
    OS Version:            Mac OS X 10.11.1 (15B42)
    Report Version:        11
    Anonymous UUID:        A5404A25-D07A-66E5-E626-58DBB498017C
    
    Sleep/Wake UUID:       8FB01C07-7455-4F31-8010-A42080E362BC
    
    Time Awake Since Boot: 18000 seconds
    Time Since Wake:       9100 seconds
    
    System Integrity Protection: enabled
    
    Crashed Thread:        0  Dispatch queue: com.apple.main-thread
    
    Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
    Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000000
    
    VM Regions Near 0:
    --> 
        __TEXT                 0000000100000000-0000000100001000 [    4K] r-x/rwx SM=COW  /Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
    
    Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
    0   ???                           	000000000000000000 0 + 0
    1   org.python.python             	0x00000001041a91ad PyEval_GetGlobals + 23
    2   org.python.python             	0x00000001041b88e1 PyImport_Import + 137
    3   org.python.python             	0x00000001041b7001 PyImport_ImportModule + 31
    
     /** **/
    
    External Modification Summary:
      Calls made by other processes targeting this process:
        task_for_pid: 0
        thread_create: 0
        thread_set_state: 0
      Calls made by this process:
        task_for_pid: 0
        thread_create: 0
        thread_set_state: 0
      Calls made by all processes on this machine:
        task_for_pid: 8447
        thread_create: 0
        thread_set_state: 0
    
    VM Region Summary:
    ReadOnly portion of Libraries: Total=253.4M resident=0K(0%) swapped_out_or_unallocated=253.4M(100%)
    Writable regions: Total=53.4M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=53.4M(100%)
     
                                    VIRTUAL   REGION 
    REGION TYPE                        SIZE    COUNT (non-coalesced) 
    ===========                     =======  ======= 
    Activity Tracing                  2048K        2 
    Kernel Alloc Once                    4K        2 
    MALLOC                            42.0M       33 
    Stack                             64.0M        3 
    VM_ALLOCATE                        264K        4 
    __DATA                            20.4M      277 
    __IMAGE                            528K        2 
    __LINKEDIT                        97.3M       62 
    __TEXT                           156.1M      269 
    __UNICODE                          552K        2 
    shared memory                       12K        4 
    ===========                     =======  ======= 
    TOTAL                            383.2M      649 
    
    Model: MacBookAir6,2, BootROM MBA61.0099.B20, 2 processors, Intel Core i5, 1.3 GHz, 4 GB, SMC 2.13f15
    Graphics: Intel HD Graphics 5000, Intel HD Graphics 5000, Built-In
    Memory Module: BANK 0/DIMM0, 2 GB, DDR3, 1600 MHz, 0x80AD, 0x483943434E4E4E384A544D4C41522D4E544D
    Memory Module: BANK 1/DIMM0, 2 GB, DDR3, 1600 MHz, 0x80AD, 0x483943434E4E4E384A544D4C41522D4E544D
    AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x117), Broadcom BCM43xx 1.0 (7.21.94.29.1a4)
    Bluetooth: Version 4.4.2f1 16391, 3 services, 18 devices, 1 incoming serial ports
    Network Service: Wi-Fi, AirPort, en0
    Serial ATA Device: APPLE SSD SD0256F, 251 GB
    USB Device: USB 3.0 Bus
    USB Device: BRCM20702 Hub
    USB Device: Bluetooth USB Host Controller
    Thunderbolt Bus: MacBook Air, Apple Inc., 23.6

After I "analyze" core dump file

    lldb -c core.11913

Output

    (lldb) target create --core "core.11913"
    warning: (x86_64) /cores/core.11913 load command 289 LC_SEGMENT_64 has a fileoff + filesize (0x29626000) that extends beyond the end of the file (0x29625000), the segment will be truncated to match
    warning: (x86_64) /cores/core.11913 load command 290 LC_SEGMENT_64 has a fileoff (0x29626000) that extends beyond the end of the file (0x29625000), ignoring this section
    Core file '/cores/core.11913' (x86_64) was loaded.
    (lldb) 

Please advice. Thank you.

**Comment by shelhamer** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
