### ISSUE TITLE
Making/Executing only one test file at a time

### ISSUE THREAD

**Issue by DCurro** [BVLC/caffe#3657]
Is this a thing that is currently possible? It would speed up my dev cycle, especially since I am a novice.

**Comment by DCurro** [comment]
A coworker just showed me that individual tests can be run manually via the build test folder.

For example:
`./build/test/test_tanh_layer.testbin`

This will execute all built tests for the tanh layer.

**Comment by flx42** [comment]
You want something like that:
```
make runtest GTEST_FILTER='ConvolutionLayerTest/*'`
```
Or:
```
make runtest GTEST_FILTER='ConvolutionLayerTest/2.TestSobelConvolution'
```

But next time ask your question to the Caffe users list.
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
