### ISSUE TITLE
what about test

### ISSUE THREAD

**Issue by Benedetta89** [BVLC/caffe#3670]
Hi...i'm new to caffe. Do you know what is the difference between the test done during training and those obtained with the command ./caffe test.
During my taining i obtain an accuracy (in test) that is equal to zero. What can be the problem?

**Comment by rohrbach** [comment]
Closing as this is a usage issue.

Please ask usage questions on caffe-users: https://groups.google.com/forum/#!forum/caffe-users. 
If you do think there is a bug in Caffe, you're welcome to open a new issue according to https://github.com/BVLC/caffe/wiki/Reporting-Bugs-and-Other-Issues. Thanks!
