### ISSUE TITLE
how to add a new pooling layer?

### ISSUE THREAD

**Issue by qianguih** [BVLC/caffe#3672]
Hi, there,
    I want to add a new pooling layer. What should I do? Should I directly add the source codes to pooling_layer.cpp? Or write a new .cpp file? What else do I need to modify?
    Thank you guys in advance. : )

**Comment by rohrbach** [comment]
Closing as this is a usage issue, this is only for bugs and issues in caffe.

Please ask usage questions on caffe-users: https://groups.google.com/forum/#!forum/caffe-users. 
If you do think there is a bug in Caffe, you're welcome to open a new issue according to https://github.com/BVLC/caffe/wiki/Reporting-Bugs-and-Other-Issues. Thanks!
