### ISSUE TITLE
JETSON TK1 testing issue

### ISSUE THREAD

**Issue by athus1990** [BVLC/caffe#3673]
Hi when I try to test an image using caffe on jetson TK1,I get the following error:

>./build/examples/cpp_classification/classification.bin \
>   models/bvlc_reference_caffenet/deploy.prototxt \
>   models/bvlc_reference_caffenet/bvlc_reference_caffenet.caffemodel \
>   data/ilsvrc12/imagenet_mean.binaryproto \
>   data/ilsvrc12/synset_words.txt \
>   examples/images/cat.jpg
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted

suppose I try
>./build/tools/caffe test --model=models/bvlc_alexnet/deploy.prototxt --weights=models/bvlc_alexnet
>/bvlc_alexnet.caffemodel --gpu=0 

I0214 19:45:54.360277  9570 upgrade_proto.cpp:42] Attempting to upgrade input file specified using deprecated transformation parameters: models/bvlc_alexnet/bvlc_alexnet.caffemodel
I0214 19:45:54.360486  9570 upgrade_proto.cpp:45] Successfully upgraded file specified using deprecated data transformation parameters.
W0214 19:45:54.360541  9570 upgrade_proto.cpp:47] Note that future Caffe releases will only support transform_param messages for transformation fields.
I0214 19:45:54.360870  9570 upgrade_proto.cpp:51] Attempting to upgrade input file specified using deprecated V1LayerParameter: models/bvlc_alexnet/bvlc_alexnet.caffemodel
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
*** Aborted at 1455479155 (unix time) try "date -d @1455479155" if you are using GNU date ***
PC: @ 0xb67188e6 (unknown)
Killed

**Comment by charterscruz** [comment]
Not really sure what is happening but I have successfully classified images in my jetson. I have followed this site: 
http://planspace.org/20150614-the_nvidia_jetson_tk1_with_caffe_on_mnist/

I think the author is very clear and following that approach after a clean install you should be abble to run caffe.

Cheers
ChartersCruz

**Comment by shelhamer** [comment]
Please ask for installation and usage help on the mailing list.  From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

**Comment by ysh329** [comment]
unresolved
