### ISSUE TITLE
Need assistance with the following error which occurs during Caffe installation!

### ISSUE THREAD

**Issue by vishwajit123** [BVLC/caffe#3674]
The "make all" command engenders the following message:-

LD -o .build_release/lib/libcaffe.so.1.0.0-rc3
/usr/bin/ld: cannot find -lopencv_imgcodecs
collect2: error: ld returned 1 exit status
Makefile:554: recipe for target '.build_release/lib/libcaffe.so.1.0.0-rc3' failed
make: *** [.build_release/lib/libcaffe.so.1.0.0-rc3] Error 1

Previously it couldn't find hdf5 library, which I solved by making the following change in the makefile.config file:
LIBRARY_DIRS := $(PYTHON_LIB) /usr/local/lib /usr/lib /usr/lib/x86_64-linux-gnu/hdf5/serial

**Comment by rohrbach** [comment]
Closing as this looks like a usage issue.

Please ask usage questions on caffe-users: https://groups.google.com/forum/#!forum/caffe-users. 
If you do think there is a bug in Caffe, you're welcome to open a new issue according to https://github.com/BVLC/caffe/wiki/Reporting-Bugs-and-Other-Issues. Thanks!

**Comment by allenzhang23** [comment]
hello, i meet the absolutely same question with you, do you know how to solve it?

**Comment by vishwajit123** [comment]
@allenzhang23 I had upgraded my Ubuntu and re-installed the dependencies. Couldn't solve the problem directly due to lack of time. Good luck. Also, why are you using caffe?

**Comment by allenzhang23** [comment]
I do not solve this problem and i think maybe i do not modify codes in the config file. Because i used other's config file,  the error would not occur.
