### ISSUE TITLE
Caffe does not make snapshots on SIGINT

### ISSUE THREAD

**Issue by yutkin** [BVLC/caffe#3678]
When I'm pressing `CTRL+C` in terminal, caffe stops training but does not make snapshots. How to fix it?
My solver:
```
net: "course-work/testing/model.prototxt"
test_iter: 200
test_interval: 500

base_lr: 0.001
momentum: 0.9
weight_decay: 0.005
lr_policy: "fixed"

display: 50
max_iter: 60000

snapshot: 5000
snapshot_format: HDF5
snapshot_prefix: "course-work/testing/by_solver_lr0"
snapshot_after_train: true

solver_mode: CPU
```

Bash script:
```
TOOLS=./build/tools
NET_DIR=course-work/testing

$TOOLS/caffe train \
    --solver=$NET_DIR/solver_lr0.prototxt 2>&1 | tee $NET_DIR/1.log
```

**Comment by seanbell** [comment]
That is the default behavior: trigger a snapshot with `SIGHUP` and stop training with `SIGINT`.

To change the default behavior, pass arguments to the `caffe` command: https://github.com/BVLC/caffe/blob/b590f1d27eb5cbd9bc7b9157d447706407c68682/tools/caffe.cpp#L44-L49

**Comment by yutkin** [comment]
@seanbell Solution http://stackoverflow.com/questions/35438160/caffe-does-not-make-snapshots-on-sigint/35449401

**Comment by petrpulc** [comment]
I have to say this is really annoying to say in the wiki that "Ctrl + C" will store the state. You ruined my day fine sir!

**Comment by Noiredd** [comment]
@petrpulc Please link to the place in the wiki where it says so, I will update it to be clearer.

**Comment by petrpulc** [comment]
@Noiredd Already fixed it: https://github.com/BVLC/caffe/wiki/Training-and-Resuming

**Comment by Noiredd** [comment]
@petrpulc But what you wrote is not true. If you run `caffe train -solver=solver.prototxt` and then Ctrl+C it, it *will* save. If you redirect to `tee`, then it will not. I'll add the relevant information.
