### ISSUE TITLE
Have cmake figure out OPENCV_VERSION?

### ISSUE THREAD

**Issue by liquidmetal** [BVLC/caffe#3688]
I feel detecting the opencv version automatically and compiling against the correct set of libraries would be a good idea. Different platforms have different mechanisms for this - however using Ubuntu as a starting point might be useful and cover a vast majority of users.

The resolution in #3186 was to modify the `Makefile` in the main directory. No changes were made to the cmake system. I was able to tweak the cmake system to detect and set `OPENCV_VERSION` automatically (at least on Ubuntu). Would I also have to modify this main `Makefile`?

**Comment by flx42** [comment]
Are you sure you need to do that?
For me the cmake build system works fine with all versions of OpenCV, without explicitly setting the version.

**Comment by liquidmetal** [comment]
Interesting - I had assumed the `Makefile` in the main source dir calls cmake. Looks like it doesn't. Is there a reason why the `Makefile` outside exists? Is it for easier compilation if someone doesn't have cmake?

**Comment by flx42** [comment]
The `Makefile` was here first and then cmake support was added.
The legacy build system is still here because some people are still using it, I think

**Comment by lukeyeager** [comment]
> Is there a reason why the Makefile outside exists?

See discussion at https://github.com/BVLC/caffe/issues/3351.

**Comment by liquidmetal** [comment]
Thanks! I guess this issue can be closed now. I've posted a comment on that thread.
