### ISSUE TITLE
9 failed test in "sudo make runtest"

### ISSUE THREAD

**Issue by liruihao** [BVLC/caffe#3690]
My laptop is equiped with  GEFORCE GT650m gpu and Intel® Core™ i7-3610QM CPU @ 2.30GHz × 8 . I installed cuda 7.0, parallel_studio_xe_2016_update1(mkl), opencv 2.4, everything looks fine before. When I "make runtest", thare are 9 failed as below:

[==========] 1928 tests from 265 test cases ran. (837373 ms total)
[  PASSED  ] 1919 tests.
[  FAILED  ] 9 tests, listed below:
[  FAILED  ] SGDSolverTest/0.TestSnapshotShare, where TypeParam = caffe::CPUDevice<float>
[  FAILED  ] AdaGradSolverTest/0.TestSnapshotShare, where TypeParam = caffe::CPUDevice<float>
[  FAILED  ] NesterovSolverTest/0.TestSnapshot, where TypeParam = caffe::CPUDevice<float>
[  FAILED  ] NesterovSolverTest/0.TestSnapshotShare, where TypeParam = caffe::CPUDevice<float>
[  FAILED  ] AdaDeltaSolverTest/0.TestSnapshotShare, where TypeParam = caffe::CPUDevice<float>
[  FAILED  ] AdamSolverTest/0.TestSnapshot, where TypeParam = caffe::CPUDevice<float>
[  FAILED  ] AdamSolverTest/0.TestSnapshotShare, where TypeParam = caffe::CPUDevice<float>
[  FAILED  ] RMSPropSolverTest/0.TestSnapshot, where TypeParam = caffe::CPUDevice<float>
[  FAILED  ] RMSPropSolverTest/0.TestSnapshotShare, where TypeParam = caffe::CPUDevice<float>

 9 FAILED TESTS
make: *** [runtest] Error 1

Coudl you tell me what should I do ? Thank you very much !

**Comment by Anfield-Uncle** [comment]
export MKL_CBWR=AUTO before may help you

**Comment by liruihao** [comment]
Thank you very much. I think it is the problem with MKL, I have used atlas instead, and all works fine.

Thank you very much for your solution.

**Comment by jczaja** [comment]
@liruihao What OS are you running and is this virtual machine ?

**Comment by liruihao** [comment]
I run it in Ubuntu 14.04 with my laptop, and it is not virtual machine. I also tried parallel_studio_xe_2016_update1(MKL) with my desktop (CPU i7-4790), it also failed.

When I changed it to atlas, all worked fine.

**Comment by jczaja** [comment]
1. could you please write how did you set MKL up eg. what is your installation path of MKL?
2. In topic of this issue there is "sudo make runtest" . does "make runtest " works for you (no sudo) ?
3. if you run source <path to mklvars.sh> intel64 before build/run caffe? (did you use sudo here as well?)

Thanks for your time answering this question. It may help us to improve caffe to work seamlessly with MKL.

**Comment by liruihao** [comment]
Cheers, it is my pleasure.

1. I installed parallel_studio_xe_2016_update1(mkl) using graphic installation and I choosed all default location as provided in MKL. Finally it was installed in "opt/MKL"
2. I did use "sudo make runtest" here. I have tried "make runtest -j8" and it did not work as well. 
3. I have not run source intel64 before build caffe.

Regards

**Comment by jczaja** [comment]
Ok,

Could you please try those options:
1. set caffe to work with MKL. execute: MKL_CBWR=AUTO make runtest -j8     # No sudo

2. independently from previous option, please run (no sudo):
   a) source /opt/intel/mkl/bin/mklvars.sh intel64   # tune command  if mklvars.sh is in diffrent location
   b) make runtest -j8  

Please write if any of them worked (and point which one).

Regards,

**Comment by liruihao** [comment]
Sorry for the late reply. I have uninstalled MKL some days ago and reinstall it again today to try the options you suggest.

The first one you gave "MKL_CBWR=AUTO make runtest -j8 " did work.

Independently from the previous option, I echo "source /opt/intel/mkl/bin/mklvars.sh" >> ~/.bashrc && source  ~/.bashrc.  It passed all the tests.

Thank you very much for your help. In my opinion, atlas is more convenient for people to use, so I suggest you can give some instructions in "caffe installation"

Regards

**Comment by jczaja** [comment]
Thanks very much for performing tests. Encouraged by your suggestion we will try to update caffe documentation
