### ISSUE TITLE
running example gives following error

### ISSUE THREAD

**Issue by MunenderVarshney** [BVLC/caffe#3692]
/examples/mnist/train_lenet.sh 
I0219 18:00:41.639117 31211 caffe.cpp:185] Using GPUs 0
I0219 18:00:41.651278 31211 caffe.cpp:190] GPU 0: Quadro 5000
I0219 18:00:41.836889 31211 solver.cpp:48] Initializing solver from parameters: 
test_iter: 100
test_interval: 500
base_lr: 0.01
display: 100
max_iter: 10000
lr_policy: "inv"
gamma: 0.0001
power: 0.75
momentum: 0.9
weight_decay: 0.0005
snapshot: 5000
snapshot_prefix: "examples/mnist/lenet"
solver_mode: GPU
device_id: 0
net: "examples/mnist/lenet_train_test.prototxt"
I0219 18:00:41.837160 31211 solver.cpp:91] Creating training net from net file: examples/mnist/lenet_train_test.prototxt
I0219 18:00:41.837746 31211 net.cpp:322] The NetState phase (0) differed from the phase (1) specified by a rule in layer mnist
I0219 18:00:41.837791 31211 net.cpp:322] The NetState phase (0) differed from the phase (1) specified by a rule in layer accuracy
I0219 18:00:41.837934 31211 net.cpp:49] Initializing net from parameters: 
name: "LeNet"
state {
  phase: TRAIN
}
layer {
  name: "mnist"
  type: "Data"
  top: "data"
  top: "label"
  include {
    phase: TRAIN
  }
...
I0219 18:00:41.838613 31211 layer_factory.hpp:77] Creating layer mnist
I0219 18:00:41.839195 31211 net.cpp:106] Creating Layer mnist
I0219 18:00:41.839229 31211 net.cpp:411] mnist -> data
I0219 18:00:41.839279 31211 net.cpp:411] mnist -> label
I0219 18:00:41.840520 31215 db_lmdb.cpp:38] Opened lmdb examples/mnist/mnist_train_lmdb
I0219 18:00:41.853802 31211 data_layer.cpp:41] output data size: 64,1,28,28
I0219 18:00:41.855271 31211 net.cpp:150] Setting up mnist
I0219 18:00:41.855315 31211 net.cpp:157] Top shape: 64 1 28 28 (50176)
I0219 18:00:41.855340 31211 net.cpp:157] Top shape: 64 (64)
I0219 18:00:41.855357 31211 net.cpp:165] Memory required for data: 200960
I0219 18:00:41.855379 31211 layer_factory.hpp:77] Creating layer conv1
I0219 18:00:41.855428 31211 net.cpp:106] Creating Layer conv1
I0219 18:00:41.855454 31211 net.cpp:454] conv1 <- data
I0219 18:00:41.855487 31211 net.cpp:411] conv1 -> conv1
F0219 18:00:41.856997 31211 cudnn_conv_layer.cpp:53] Check failed: status == CUDNN_STATUS_SUCCESS (6 vs. 0)  CUDNN_STATUS_ARCH_MISMATCH
*** Check failure stack trace: ***
    @     0x7f821ec86daa  (unknown)
    @     0x7f821ec86ce4  (unknown)
    @     0x7f821ec866e6  (unknown)
    @     0x7f821ec89687  (unknown)
    @     0x7f821f3d61b9  caffe::CuDNNConvolutionLayer<>::LayerSetUp()
    @     0x7f821f2f2685  caffe::Net<>::Init()
    @     0x7f821f2f3735  caffe::Net<>::Net()
    @     0x7f821f2a809a  caffe::Solver<>::InitTrainNet()
    @     0x7f821f2a91ac  caffe::Solver<>::Init()
    @     0x7f821f2a94da  caffe::Solver<>::Solver()
    @     0x7f821f2d7273  caffe::Creator_SGDSolver<>()
    @           0x40ea7e  caffe::SolverRegistry<>::CreateSolver()
    @           0x407bb2  train()
    @           0x4059dc  main
    @     0x7f821df94ec5  (unknown)
    @           0x406111  (unknown)
    @              (nil)  (unknown)

**Comment by shelhamer** [comment]
Your Caffe is compiled for the wrong GPU: `CUDNN_STATUS_ARCH_MISMATCH` means that your GPU is not compatible with the library version and GPU arch it was compiled for.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
