### ISSUE TITLE
mnist success on cpu but fails on GPU with GT650m(capability 3.0)

### ISSUE THREAD

**Issue by liruihao** [BVLC/caffe#3693]
F0126 21:48:38.671995 2710 benchmark.cpp:19] Check failed: error == cudaSuccess (77 vs. 0) was encoutered
*** Check failure stack trace: ***
@ 0x7f0b88046b7d google::LogMessage::Fail()
@ 0x7f0b88046b7d google::LogMessage::Fail()
@ 0x7f0b88048c7f google::LogMessage::SendToLog()
@ 0x7f0b88048c7f google::LogMessage::SendToLog()
@ 0x7f0b8804676c google::LogMessage::Flush()
@ 0x7f0b8804676c google::LogMessage::Flush()
@ 0x7f0b8804951d google::LogMessageFatal::~LogMessageFatal()
@ 0x7f0b8804951d google::LogMessageFatal::~LogMessageFatal()

What should I do?

**Comment by hackwfu** [comment]
When you compiled Caffe did you do it with GPU support enabled? If so, did you do the runtest to see if that worked?

**Comment by liruihao** [comment]
Thank you for your reply.

I have already enabled GPU, and have "make runtest" to test the caffe with CPU and GPU, and all tests have passed. 

I compiled caffe on another computer equiped with Quadro K620 and i7 4790. And all is fine including MNIST training. I think it maybe the problem of the capability of my GT650m on laptop.

Thank you very much.

**Comment by hackwfu** [comment]
On my unix computer I can check how many cuda cores are being used with nvidia-smi. It seems like possibly it's trying to use more cuda cores that your GPU has...

**Comment by liruihao** [comment]
Yeah, maybe you are right. My GPU on laptop has some limitations on computing with caffe. 

Thank you very much!
