### ISSUE TITLE
i can not build the caffe docs

### ISSUE THREAD

**Issue by heavytank** [BVLC/caffe#3704]
caffecudnn/caffe-master/scripts/build_docs.sh
usage: build_docs.sh [port]
rm: 无法删除(can not delete)"docs/gathered": 没有那个文件或目录(can not find the file or dirction)
doxygen ./.Doxyfile
make: doxygen：命令未找到(can not find the command)
make: * [doxygen] 错误 (error)127
caffecudnn/caffe-master/scripts/build_docs.sh: 行 20: jekyll: 未找到命令(can not find the command)

my email gengrufeng9527@163.com
my mobile phone number (+86 15801523139)

**Comment by CDLuminate** [comment]
you need `doxygen`

**Comment by shelhamer** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
