### ISSUE TITLE
Why does the computing speed of caffe slow down？

### ISSUE THREAD

**Issue by staticeudemon** [BVLC/caffe#3705]
This is my caffe  runtime environment configuration：
Ubuntu 14.04  ＋CUDA7.5＋Cudnn V4+anaconda 2.7 ＋opencv 2.4.10

Nvidia GPU 4G
Dell Precision Tower 5810

At the beginning ，I have ran my model in a database of about 50，000 images . the Iteration times 450,000 need about  one day. but after one month,the same Iteration times need four days.I have check the memory  and hard disk,I can't find the reasons.I have Installed the Ubuntu system 14.04 LTS again and configured the caffe .Unfortunately,the computing speed still is slow.

**Comment by litingfeng** [comment]
I have encountered the same problem. Can you share with me how you fixed it ? Thanks a lot.
