### ISSUE TITLE
failed with error code 1 in /tmp/pip-build-x6OF7G/Cython

### ISSUE THREAD

**Issue by datomnurdin** [BVLC/caffe#3706]
I got this error message when I execute this command on my terminal (Centor 7.0).

Command
```
for req in $(cat caffe/python/requirements.txt); do sudo pip install $req; done
```

Error message 
```
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-x6OF7G/Cython/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-qgS6sD-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-x6OF7G/Cython
```

Please advice. Thank you.

**Comment by seanbell** [comment]
This looks like an issue with dependencies (`pip` packages) on your operating system, not caffe.  If you are having trouble getting it to work on other operating systems, you could try using the docker image: https://github.com/BVLC/caffe/pull/3518

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
