### ISSUE TITLE
Issue while testing Flownet

### ISSUE THREAD

**Issue by mmuazGit** [BVLC/caffe#3707]
I am new in caffe. I am trying to run the demo of [flownet](http://lmb.informatik.uni-freiburg.de/Publications/2015/FDIB15/). But when I ran the code I get following error:

I0223 12:18:42.116024 46383 layer_factory.hpp:76] Creating layer conv1
F0223 12:18:42.116032 46383 layer_factory.cpp:37] Layer conv1 has unknown engine.
*** Check failure stack trace: ***
    @     0x7f71a4a904cd  google::LogMessage::Fail()
    @     0x7f71a4a92283  google::LogMessage::SendToLog()
    @     0x7f71a4a900e8  google::LogMessage::Flush()
    @     0x7f71a4a92ade  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f71aa345db4  caffe::GetConvolutionLayer<>()
    @     0x7f71aa246d8c  caffe::LayerRegistry<>::CreateLayer()
    @     0x7f71aa24d6fa  caffe::Net<>::Init()
    @     0x7f71aa250092  caffe::Net<>::Net()
    @           0x4078dc  test()
    @           0x405d37  main
    @     0x7f71a0754b45  (unknown)
    @           0x406558  (unknown)

I am using CUDA **v7.5**.

**Comment by shelhamer** [comment]
You should ask the authors or ask on the caffe-users mailing list.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

**Comment by pullaraomaddu** [comment]
Hi  mmuazGit,

Are you able to fix the issue? If so please reply to below thread
https://github.com/bqlabs/flownet/issues/1
