### ISSUE TITLE
Matcaffe cann't use solver

### ISSUE THREAD

**Issue by mirsking** [BVLC/caffe#3712]
When I tried to use caffe.Solver in matlab, the matlab just crashed with the following error,

```
WARNING: Logging before InitGoogleLogging() is written to STDERR
F0224 16:17:12.069447 10598 solver_factory.hpp:76] Check failed: registry.count(type) == 1 (0 vs. 1) Unknown solver type: SGD (known types: )
```

Need your help, thank you!

**Comment by ShaggO** [comment]
How did you specify your solver type in your solver prototext-file?

**Comment by Noiredd** [comment]
Closing this in favor of a more detailed discussion under #4010.
