### ISSUE TITLE
Compile the "convert_imageset.cpp" independently

### ISSUE THREAD

**Issue by Love-world** [BVLC/caffe#3713]
Dear Yang Qing:
     I am a chinese.Thanks your great work.
     I want to know how can I compile the "convert_imageset.cpp" independently.So I can use 'gdb' to debugging it .
    It depends on many ".h" and so on,so I always fail.

**Comment by seanbell** [comment]
This looks like a request for help.  From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
