### ISSUE TITLE
Why input dimentions for same trained model are different in Matlab and C++ code?

### ISSUE THREAD

**Issue by haoyul** [BVLC/caffe#3718]
I'm transferring an image classification Matlab caffe code into C++. My matlab version is verified to output the wanted results. My problem is in C++ part. 

Here is the first part of my prototxt file.
```
input: "data"
input_shape {
  dim: 1
  dim: 3
  dim: 640
  dim: 480
}
```
In Matlab, after calling
 ```
a=net.blobs('data').shape;
num_row=a(1);
num_col=a(2);
```

The num_row is 480 and num_col is 640. Seems it's reading the prototxt part backforward.

In C++, after
`Blob<float>* input_layer = net_->input_blobs()[0];`

Based on caffe's website, the conventional blob dimensions is : number N x channel K x height H x width W. So in C++, input_layer->width() is 480 and input_layer->height() is 640 which means number of row is 640 and number of column is 480. Now you see the difference between Matlab and C++.

In order to make C++ code output the same result as Matlab, I have to transpose the input image first. And of course, the result needs to be transposed back too.

My question is why the input dimentions are different on Matlab and C++? Is there any function in C++ to transpose the size of model so that I don't need to transpose input and output?

By the way, I tried those methods and the output are not correct:  
1. Resize input image from 480 * 640 to 640 * 480. 
2. input_layer->Reshape(1, num_channels_, 480, 640);

Thank you.

**Comment by shelhamer** [comment]
Caffe uses row major array order while MATLAB uses column major array order.

Please ask usage questions on the mailing list.  From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
