### ISSUE TITLE
"Check failed: slice_axis_ < num_axes (1 vs. 1) slice_dim out of range." with googleNet

### ISSUE THREAD

**Issue by liruihao** [BVLC/caffe#3721]
I try the caffe with googlenet, but problem happened as blow:

I0225 00:34:30.682186 13179 layer_factory.hpp:77] Creating layer data
I0225 00:34:30.682914 13179 net.cpp:106] Creating Layer data
I0225 00:34:30.682925 13179 net.cpp:411] data -> data
I0225 00:34:30.682956 13179 net.cpp:411] data -> label
I0225 00:34:30.682967 13179 data_transformer.cpp:25] Loading mean file from: posenet/kings_mean.binaryproto
I0225 00:34:30.683506 13182 db_lmdb.cpp:38] Opened lmdb posenet/posenet_kings_test_lmdb/
I0225 00:34:30.690235 13179 data_layer.cpp:41] output data size: 1,3,224,224
I0225 00:34:30.691720 13179 net.cpp:150] Setting up data
I0225 00:34:30.691746 13179 net.cpp:157] Top shape: 1 3 224 224 (150528)
I0225 00:34:30.691752 13179 net.cpp:157] Top shape: 1 (1)
I0225 00:34:30.691756 13179 net.cpp:165] Memory required for data: 602116
I0225 00:34:30.691762 13179 layer_factory.hpp:77] Creating layer slice_label
I0225 00:34:30.691776 13179 net.cpp:106] Creating Layer slice_label
I0225 00:34:30.691781 13179 net.cpp:454] slice_label <- label
I0225 00:34:30.691788 13179 net.cpp:411] slice_label -> label_xyz
I0225 00:34:30.691797 13179 net.cpp:411] slice_label -> label_wpqr
F0225 00:34:30.691809 13179 slice_layer.cpp:33] Check failed: slice_axis_ < num_axes (1 vs. 1) slice_dim out of range.
*** Check failure stack trace: ***
Aborted (core dumped)

Could anyone tell me what should I do with it ? Thank you very much!

Kind regards

**Comment by liruihao** [comment]
It is the problem of my input blob. Thank you very much.

**Comment by alykhantejani** [comment]
@liruihao can you comment on how you solved this, I am having the same issue when running `test_posenet`

Thanks

**Comment by liruihao** [comment]
https://github.com/alexgkendall/caffe-posenet/issues/3


You can see the solution here. It is closed in PoseNet.

Regards,
