### ISSUE TITLE
Error when making pycaffe

### ISSUE THREAD

**Issue by zirohut** [BVLC/caffe#3726]
`CXX/LD` -o python/caffe/_caffe.so python/caffe/_caffe.cpp
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.9/README.Bugs> for instructions.
Makefile:498: recipe for target 'python/caffe/_caffe.so' failed
make: *** [python/caffe/_caffe.so] Error 4
fa@Ubuntu-mate:~/caffe-master$ `

I was trying to make pycaffe and this error poped out. Any ideas? Thanks.

**Comment by seanbell** [comment]
Please ask installation questions on the mailing list.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
