### ISSUE TITLE
No non-linearity after conv layers in MNIST example

### ISSUE THREAD

**Issue by baumgach** [BVLC/caffe#3727]
Could it be that there is a mistake in the MNIST example: https://github.com/BVLC/caffe/blob/master/examples/mnist/lenet_train_test.prototxt . 

The conv layers are not followed by any non-linearities. In the original paper they were followed by sigmoids. 

In this tutorial here http://caffe.berkeleyvision.org/gathered/examples/mnist.html, it is written that the sigmoids are replaced by ReLUs. However, there is only one ReLU after the FC layer. 

What is even more confusing to me, is that the network without the non-linearities still seems to perform extremely well on the classification... Any idea why that is?

**Comment by seanbell** [comment]
Max pooling is nonlinear.

**Comment by seanbell** [comment]
In general, please ask modeling questions on the mailing list. From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
