### ISSUE TITLE
Grow LMDB map size incrementally

### ISSUE THREAD

**Issue by lukeyeager** [BVLC/caffe#3730]
Several people have proposed decreasing the default LMDB map size from 1TB down to something smaller (https://github.com/BVLC/caffe/pull/3644, https://github.com/BVLC/caffe/pull/3728). The large default causes problems on ARM and Windows, and makes Valgrind unhappy (https://github.com/BVLC/caffe/issues/2404).

@hyc, a maintainer (the author?) of LMDB, suggested catching MDB_MAP_FULL errors and growing the map size as needed.

> you can just grow the map whenever you hit a MDB_MAP_FULL error
https://github.com/NVIDIA/DIGITS/issues/206#issuecomment-129606302

This was implemented with only a few lines of code in DIGITS:
https://github.com/NVIDIA/DIGITS/blob/v3.0.0/tools/create_db.py#L636-L660
```
2016-02-25 12:48:41 [DEBUG] Processed 200/60000
2016-02-25 12:48:42 [DEBUG] Doubling LMDB map size to 20MB ...
2016-02-25 12:48:43 [DEBUG] Processed 500/60000
2016-02-25 12:48:44 [DEBUG] Doubling LMDB map size to 40MB ...
2016-02-25 12:48:45 [DEBUG] Processed 800/60000
2016-02-25 12:48:48 [DEBUG] Processed 1200/60000
2016-02-25 12:48:48 [DEBUG] Doubling LMDB map size to 80MB ...
2016-02-25 12:48:50 [DEBUG] Processed 1600/60000
2016-02-25 12:48:52 [DEBUG] Processed 1800/60000
2016-02-25 12:48:54 [DEBUG] Processed 2200/60000
2016-02-25 12:48:56 [DEBUG] Doubling LMDB map size to 160MB ...
2016-02-25 12:48:56 [DEBUG] Processed 2600/60000
...
```
I submit that the same should be done for Caffe rather than simply changing the default map size.

**Comment by shelhamer** [comment]
Sounds like a reasonable approach to me -- PRs welcome.

**Comment by hyc** [comment]
re: ARM, the MDB_VL32 feature in LMDB is working well for 32bit platforms (including ARM and Win32) and large mapsizes aren't an issue with them. Naturally there has never been an issue with ARM64 or Win64.

**Comment by lukeyeager** [comment]
> Naturally there has never been an issue with ARM64 or Win64.

To be clear, Win32 fails to create a 1TB file because it won't allow files greater than 4GB, while Win64 technically doesn't crash but still creates a 1TB file? That still sounds like a problem to me. Or am I missing something?

Either way, the proposed solution is still the right idea - correct?

**Comment by hyc** [comment]
Win32 will certainly create files larger than 4GB if you ask it. E.g. most DVDs are larger than 4GB... The MDB_VL32 patches allows Win32 to operate on 64bit DBs. https://github.com/LMDB/lmdb/commit/29ebd02efd72fa0b558b6d87fc32afc1061f97ff

As for 1TB files, with the patches for ITS#8324 LMDB will no longer preallocate the entire file on Windows; instead it will grow incrementally.

The proposed solution works of course. But in general it's not necessary.

**Comment by lukeyeager** [comment]
Thanks for the clarifications, @hyc. If I'm understanding things correctly (and I'm probably still not),

* Without https://github.com/LMDB/lmdb/commit/fb5a768a77ca5330e15a3a34ceb694bc11cb216a, Windows will allocate 1TB files on disk
* Without https://github.com/LMDB/lmdb/commit/29ebd02efd72fa0b558b6d87fc32afc1061f97ff, 32-bit systems are unable to create a 1TB map

That's great that these patches are in the `master` branch, but neither are present with version 0.9.10, which comes with [the Ubuntu 14.04 package](http://packages.ubuntu.com/trusty/liblmdb0).

I'd prefer to make Caffe work with old versions of LMDB rather than asking people to run bleeding-edge code for a dependency.

**Comment by hyc** [comment]
Yes, I think you've got it correct.

LMDB 0.9.10 is ancient, released Nov 2013. LMDB 0.9.18 was released a few weeks ago.
But OK, do whatever makes sense for your user population...
