### ISSUE TITLE
What about batch size?

### ISSUE THREAD

**Issue by Benedetta89** [BVLC/caffe#3733]
I'm new to caffe. I want to understand the mean of the paramater batch_size: is it the number of images that were loaded into memory at a time? or what it is?

**Comment by seanbell** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
>_Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
