### ISSUE TITLE
caffe compile error

### ISSUE THREAD

**Issue by qm1004** [BVLC/caffe#3734]
I have install all dependency .

`make all`

I get error below:
> [  0%] Built target proto
[ 88%] Built target caffe
Linking CXX executable caffe
/lib64/libgtk-x11-2.0.so.0: undefined reference to `g_type_check_instance_is_fundamentally_a'
collect2: error: ld returned 1 exit status
make[2]: *** [tools/caffe] Error 1
make[1]: *** [tools/CMakeFiles/caffe.bin.dir/all] Error 2

`ls -l /lib64/libgtk-x11-2.0.so.0`
`lrwxrwxrwx 1 root root 27 Feb 25 19:08 /lib64/libgtk-x11-2.0.so.0 -> libgtk-x11-2.0.so.0.2400.28`

Please advice. Thank you.

**Comment by qm1004** [comment]
I am on centos 7 . 
install opencv2.4

**Comment by qm1004** [comment]
> -- Boost version: 1.59.0
-- Found the following Boost libraries:
--   system
--   thread
--   filesystem
-- Found gflags  (include: /usr/include, library: /usr/lib64/libgflags.so)
-- Found glog    (include: /usr/include, library: /usr/lib64/libglog.so)
-- Found PROTOBUF Compiler: /usr/bin/protoc
-- Found lmdb    (include: /usr/include, library: /usr/lib64/liblmdb.so)
-- Found LevelDB (include: /usr/include, library: /usr/lib64/libleveldb.so)
-- Found Snappy  (include: /usr/include, library: /usr/lib64/libsnappy.so)
-- CUDA detected: 7.5
-- Found cuDNN: ver. 3.0.02 found (include: /usr/local/include, library: /usr/local/lib/libcudnn.so)
-- Added CUDA NVCC flags for: sm_35
-- OpenCV found (/usr/lib64/cmake/OpenCV)
-- Found OpenBLAS libraries: /usr/lib64/libopenblas.so
-- Found OpenBLAS include: /usr/include
-- NumPy ver. 1.7.1 found (include: /usr/lib64/python2.7/site-packages/numpy/core/include)
-- Could NOT find Boost
-- Python interface is disabled or not all required dependencies found. Building without it...
-- Detected Doxygen OUTPUT_DIRECTORY: ./doxygen/
-- 
-- ******************* Caffe Configuration Summary *******************
-- General:
--   Version           :   1.0.0-rc3
--   Git               :   rc3-26-gfe0f441-dirty
--   System            :   Linux
--   C++ compiler      :   /usr/bin/c++
--   Release CXX flags :   -O3 -DNDEBUG -fPIC -Wall -Wno-sign-compare -Wno-uninitialized
--   Debug CXX flags   :   -g -fPIC -Wall -Wno-sign-compare -Wno-uninitialized
--   Build type        :   Release
-- 
--   BUILD_SHARED_LIBS :   ON
--   BUILD_python      :   ON
--   BUILD_matlab      :   OFF
--   BUILD_docs        :   ON
--   CPU_ONLY          :   OFF
--   USE_OPENCV        :   ON
--   USE_LEVELDB       :   ON
--   USE_LMDB          :   ON
--   ALLOW_LMDB_NOLOCK :   OFF
-- 
-- Dependencies:
--   BLAS              :   Yes (open)
--   Boost             :   Yes (ver. 1.59)
--   glog              :   Yes
--   gflags            :   Yes
--   protobuf          :   Yes (ver. 2.5.0)
--   lmdb              :   Yes (ver. 0.9.17)
--   LevelDB           :   Yes (ver. 1.12)
--   Snappy            :   Yes (ver. 1.1.0)
--   OpenCV            :   Yes (ver. 2.4.5)
--   CUDA              :   Yes (ver. 7.5)
-- 
-- NVIDIA CUDA:
--   Target GPU(s)     :   Auto
--   GPU arch(s)       :   sm_35
--   cuDNN             :   Yes (ver. 3.0.02)
-- 
-- Documentaion:
--   Doxygen           :   /usr/bin/doxygen (1.8.5)
--   config_file       :   /home/qianmin/caffe/.Doxyfile
-- 
-- Install:
--   Install path      :   /home/qianmin/caffe/build/install
-- 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/qianmin/caffe/build

**Comment by ryanaaa** [comment]
Have you solved the problem? I have encountered the same problem and still can't solve it.
can you tell me your solution if you just solved it. Thx~

**Comment by ryanaaa** [comment]
I just solved it by installed gtk-devel
