### ISSUE TITLE
Crop layer type is not included

### ISSUE THREAD

**Issue by mujtabahasan** [BVLC/caffe#3737]
when i run FCN train.prototxt for segmentation, it doesn't have Crop layer type

**Comment by seanbell** [comment]
Please ask usage questions on the mailing list.  Also, read the documentation that comes with FCN.  It will tell you how to get the Crop layer.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
