### ISSUE TITLE
issues with examples and make runtest

### ISSUE THREAD

**Issue by mujtabahasan** [BVLC/caffe#3738]
Hi, I have installed the latest version of caffe. make all, make pycaffe, make matcaffe runs smoothly but make runtest fails after running some tests. it fails in SGDSolver test. Also all the examples of mnist like examples/mnist/train_mnist_autoencoder.sh hangs up and doesn't proceed. Please resolve these issues or tell me how can it be resolved

**Comment by seanbell** [comment]
Please ask usage questions on the mailing list.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
