### ISSUE TITLE
Manipulate weights of a network

### ISSUE THREAD

**Issue by ruoyanwang** [BVLC/caffe#374]
Hi,
For some purpose, I wanted to split my trained network into 2 parts. But I'm not sure in which format are those parameters stored and how I could change them.
I know get_weights function provided by matcaffe can get weights of a network but it seems hard to manipulate them and store them separately.

Thanks,
Ryan

**Comment by jayajadhav** [comment]
Can you please tell me about how we can get the weights in c++ caffe?
