### ISSUE TITLE
caffe_copy ERROR cudaSuccess (11 vs 0) 

### ISSUE THREAD

**Issue by hyojinie** [BVLC/caffe#3743]
Hi I don't know why caffe_copy gives me error == cudaSuccess (11 vs 0) invalid argument.

*** Check failure stack trace: ***
    @     0x7f81c6149c3c  google::LogMessage::Fail()
    @     0x7f81c6149b88  google::LogMessage::SendToLog()
    @     0x7f81c614958a  google::LogMessage::Flush()
    @     0x7f81c614c521  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f81c675a10b  caffe::caffe_copy<>()
    @     0x7f81c67e6f95  caffe::NetvladLayer<>::Forward_cpu()
    @     0x7f81c687c561  caffe::Net<>::ForwardFromTo()
    @     0x7f81c687c8d7  caffe::Net<>::ForwardPrefilled()
    @     0x7f81c68b48e9  caffe::Solver<>::Test()
    @     0x7f81c68b524e  caffe::Solver<>::TestAll()
    @     0x7f81c68b5395  caffe::Solver<>::Step()
    @     0x7f81c68b5ea5  caffe::Solver<>::Solve()
    @           0x409ae3  train()
    @           0x407101  main
    @     0x7f81c5665ec5  (unknown)
    @           0x407811  (unknown)
Aborted (core dumped)

The error occurs here. 

caffe_copy(dim, bottom_data + n * dim, residual_data);

dim, n: int
bottom_data, residual_data: Dtype pointer

I also printed the arguments. 
I0227 22:35:27.273406  4808 vlad_layer.cpp:175] dim 43264
I0227 22:35:27.273412  4808 vlad_layer.cpp:176] n 0
I0227 22:35:27.273418  4808 vlad_layer.cpp:177] bottom_data 0x21bfc0000
I0227 22:35:27.273428  4808 vlad_layer.cpp:178] residual_data 0x209935400

I use titian X for my GPU. and CUDA 7.5, and the Caffe downloaded in January 2016.

**Comment by seanbell** [comment]
`NetvladLayer`?  Is this an error in a layer you wrote yourself?  If so, please ask for help on the mailing list, and close this issue.

_Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

**Comment by hyojinie** [comment]
I think my problem occurred because I my forward_gpu just calls forward_cpu, and so the caffe_copy gets cpu pointers while running in the gpu mode.

**Comment by seanbell** [comment]
Aah yes that's a common mistake to make; glad you fixed it!
