### ISSUE TITLE
How to resolve the error when executing "./build/tools/caffe train -solver examples/myfile/solver.prototxt"

### ISSUE THREAD

**Issue by AmandaYingYiWu24** [BVLC/caffe#3744]
F0228 17:38:20.483613  4104 syncedmem.cpp:64] Check failed: error == cudaSuccess (2 vs. 0)  out of memory
*** Check failure stack trace: ***
    @     0x7fcc1f3085cd  google::LogMessage::Fail()
    @     0x7fcc1f30a433  google::LogMessage::SendToLog()
    @     0x7fcc1f30815b  google::LogMessage::Flush()
    @     0x7fcc1f30ae1e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fcc1fa1e2f0  caffe::SyncedMemory::to_gpu()
    @     0x7fcc1fa1d2b9  caffe::SyncedMemory::mutable_gpu_data()
    @     0x7fcc1fa11d42  caffe::Blob<>::mutable_gpu_data()
    @     0x7fcc1f981168  caffe::BasePrefetchingDataLayer<>::LayerSetUp()
    @     0x7fcc1fa76272  caffe::Net<>::Init()
    @     0x7fcc1fa77cb1  caffe::Net<>::Net()
    @     0x7fcc1fa2a562  caffe::Solver<>::InitTestNets()
    @     0x7fcc1fa2aef5  caffe::Solver<>::Init()
    @     0x7fcc1fa2b22a  caffe::Solver<>::Solver()
    @     0x7fcc1faa33f3  caffe::Creator_SGDSolver<>()
    @           0x40a4f8  train()
    @           0x407408  main
    @     0x7fcc1df61a40  __libc_start_main
    @           0x407b79  _start
    @              (nil)  (unknown)
已放弃 (核心已转储)

**Comment by seanbell** [comment]
You are out of memory (on the GPU).  One way of fixing this is to reduce the batchsize by a factor of 2 (and correspondingly increasing `iter_size` by a factor of 2 in the solver prototxt, the default is 1).

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
>_Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
