### ISSUE TITLE
MemoryDataLayer error

### ISSUE THREAD

**Issue by LiquidE3** [BVLC/caffe#3745]
I want to use caffe to classify, and I have trained  a caffemodel.

I use the code (http://codepad.org/JfRKOUh6) from google group (https://groups.google.com/forum/#!topic/caffe-users/tMwpaf3s8GQ) but an error happened.

class caffe::MemoryDataLayer<float> has no member named 'AddMatVector'

Could anyone help me or give me some advice? 

thanks

**Comment by seanbell** [comment]
Please ask for usage help on the mailing list.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
>_Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

**Comment by Madgeeno** [comment]
You have to compile your code by enabling USE_OPENCV

**Comment by xiupingmath** [comment]
Hi, did you solve this problem?  I have the same problem.
