### ISSUE TITLE
Continuous integration for Windows branch 

### ISSUE THREAD

**Issue by pavlejosipovic** [BVLC/caffe#3748]
Now that there is a Windows branch `BVLC/caffe:windows` led by Microsoft we can turn on continuous integration for this branch.

Caffe repo admin should:
1. Go to http://www.appveyor.com
2. Login with GitHub credentials
3. Click on "New Project"
4. Select Caffe repo
5. Go to Settings
6. Check "Skip branches without appveyor.yml " checkbox
7. Save
8. Go to "Latest build"
9. Click "New Build" to trigger first build manually

**Comment by pavlejosipovic** [comment]
In Settings->Badges admin could pickup the build badge URL and place into README.md

**Comment by pavlejosipovic** [comment]
I've added CI for windows branch

**Comment by shelhamer** [comment]
Great, thanks!

**Comment by pavlejosipovic** [comment]
@shelhamer 
Can you add a webhook for appveyor
https://ci.appveyor.com/api/github/webhook?id=128eg95svel2a2xs
So that build trigger automatically on each commit/PR in windows branch?
Settings->webhooks & services->Add webhook

**Comment by shelhamer** [comment]
@pavlejosipovic I think this is done -- I added the webhook and turned it on for push + pull request events.

**Comment by pavlejosipovic** [comment]
I've configured AppVeyor to ignore all branches which don't have  appveyor.yml file (check the step 6 in the guide above). 

Thanks for helping with this.

**Comment by shelhamer** [comment]
Great, thanks for configuring that.
