### ISSUE TITLE
Check failed: google::protobuf::TextFormat::Parse(input, proto) in runtime

### ISSUE THREAD

**Issue by ramialbatal** [BVLC/caffe#375]
Hi,
I am trying to execute a python wrapper for caffe, the installation seems to be fine, I am not able to do 'make runtest' and I have segmentation fault:

```
build/src/caffe/test/test_all.testbin 0
make: *** [runtest] Segmentation fault: 11
```

I ignored this failure and go ahead, and when I try to execute a feature extraction method or a predict method I get the following errors:

```
[libprotobuf ERROR google/protobuf/text_format.cc:245] Error parsing text-format caffe.NetParameter: 10:7: Message type "caffe.LayerConnection" has no field named "name".
WARNING: Logging before InitGoogleLogging() is written to STDERR
F0428 22:09:28.924217 2118574864 io.cpp:40] Check failed: google::protobuf::TextFormat::Parse(input, proto) 
*** Check failure stack trace: ***
Abort trap: 6
```

It looks like I have a problem in protbuf?
Any comment or advise is appreciated.
Thanks

**Comment by LinZhineng** [comment]
I meet one problem, any help? Thank you
libprotobuf ERROR google/protobuf/text_format.cc:172] Error parsing text-format caffe.SolverParameter: 25:9: Message type "caffe.SolverParameter" has no field named "log_file".
F1027 21:16:32.725467  4255 io.hpp:54] Check failed: ReadProtoFromTextFile(filename, proto) 
*** Check failure stack trace: ***
    @     0x7fb834773468  google::LogMessage::Fail()
    @     0x7fb8347733b4  google::LogMessage::SendToLog()
    @     0x7fb834772da2  google::LogMessage::Flush()
    @     0x7fb834775ca1  google::LogMessageFatal::~LogMessageFatal()
    @           0x40902f  train()
    @           0x4054db  main
    @     0x7fb833c7f78d  (unknown)
    @           0x405961  (unknown)
Aborted (core dumped)

**Comment by dwaylooper** [comment]
Same problem is LinZhineng - any solutions please?
