### ISSUE TITLE
cmd print output?

### ISSUE THREAD

**Issue by lilin19890401** [BVLC/caffe#3753]
hi, I want to use caffelibd.dll and caffelib.dll in my own project and my project do not have cmd print, Can I train the caffelibd.dll and caffelib.dll without cmd print output when I use them in other project?

**Comment by seanbell** [comment]
Please ask for installation/usage help on the mailing list.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
