### ISSUE TITLE
Setup aborts when change kernel from 5 to 9

### ISSUE THREAD

**Issue by sodeypunk** [BVLC/caffe#3754]
I have no problems with my architecture when i train with convolution kernel of 5 but when i switch it to 9 for a 5 layer convolution, the training errors out abruptly when setting up the 4th pooling layer with no reason. I want to assume that it is because of memory issues but i'm not sure because i have a 6GB 980GTX TI and training normally doesn't get anywhere near that limit with Kernel size of 5.

Is there anything else that someone could tell me about this error?

...
I0229 23:00:06.098428  1751 layer_factory.hpp:76] Creating layer pool4
I0229 23:00:06.098436  1751 net.cpp:109] Creating Layer pool4
I0229 23:00:06.098440  1751 net.cpp:457] pool4 <- norm4
I0229 23:00:06.098448  1751 net.cpp:414] pool4 -> pool4
*** Aborted at 1456808406 (unix time) try "date -d @1456808406" if you are using GNU date ***
PC: @     0x7fb1464305c3 caffe::Blob<>::Reshape()
*** SIGFPE (@0x7fb1464305c3) received by PID 1751 (TID 0x7fb146c54a40) from PID 1178797507; stack trace: ***
    @     0x7fb14522fd40 (unknown)
    @     0x7fb1464305c3 caffe::Blob<>::Reshape()
    @     0x7fb1464309e9 caffe::Blob<>::Reshape()
    @     0x7fb1463b46fd caffe::PoolingLayer<>::Reshape()
    @     0x7fb14635d166 caffe::CuDNNPoolingLayer<>::Reshape()
    @     0x7fb14644ca75 caffe::Net<>::Init()
    @     0x7fb14644db15 caffe::Net<>::Net()
    @     0x7fb146303a3a caffe::Solver<>::InitTrainNet()
    @     0x7fb146304a3c caffe::Solver<>::Init()
    @     0x7fb146304d49 caffe::Solver<>::Solver()
    @           0x40fe85 caffe::GetSolver<>()
    @           0x408be6 train()
    @           0x406ab5 main
    @     0x7fb14521aec5 (unknown)
    @           0x4071ed (unknown)
    @                0x0 (unknown)
Floating point exception (core dumped)

**Comment by sodeypunk** [comment]
Here is my architecture

layer {
  name: "conv1"
  type: "Convolution"
  bottom: "data"
  top: "conv1"
  param {
    lr_mult: 1
  }
  param {
    lr_mult: 2
  }
  convolution_param {
    num_output: 128
    pad: 0
    kernel_size: 9
    stride: 1
    weight_filler {
      type: "xavier"
    }
    bias_filler {
      type: "constant"
    }
  }
}
layer {
  name: "drop1"
  type: "Dropout"
  bottom: "conv1"
  top: "conv1"
  dropout_param {
    dropout_ratio: 0.5
  }
}
layer {
  name: "relu1"
  type: "ReLU"
  bottom: "conv1"
  top: "conv1"
}
layer {
  name: "norm1"
  type: "LRN"
  bottom: "conv1"
  top: "norm1"
  lrn_param {
    local_size: 3
    alpha: 0.0001
    beta: 0.75
  }
}
layer {
  name: "pool1"
  type: "Pooling"
  bottom: "norm1"
  top: "pool1"
  pooling_param {
    pool: MAX
    kernel_size: 2
    stride: 2
  }
}
layer {
  name: "conv2"
  type: "Convolution"
  bottom: "pool1"
  top: "conv2"
  param {
    lr_mult: 1
  }
  param {
    lr_mult: 2
  }
  convolution_param {
    num_output: 128
    pad: 3
    kernel_size: 9
    stride: 1
    weight_filler {
      type: "xavier"
    }
    bias_filler {
      type: "constant"
    }
  }
}
layer {
  name: "drop2"
  type: "Dropout"
  bottom: "conv2"
  top: "conv2"
  dropout_param {
    dropout_ratio: 0.5
  }
}
layer {
  name: "relu2"
  type: "ReLU"
  bottom: "conv2"
  top: "conv2"
}
layer {
  name: "norm2"
  type: "LRN"
  bottom: "conv2"
  top: "norm2"
  lrn_param {
    local_size: 3
    alpha: 0.0001
    beta: 0.75
  }
}
layer {
  name: "pool2"
  type: "Pooling"
  bottom: "norm2"
  top: "pool2"
  pooling_param {
    pool: MAX
    kernel_size: 2
    stride: 1
  }
}
layer {
  name: "conv3"
  type: "Convolution"
  bottom: "pool2"
  top: "conv3"
  param {
    lr_mult: 1
  }
  param {
    lr_mult: 2
  }
  convolution_param {
    num_output: 128
    pad: 2
    kernel_size: 9
    stride: 1
    weight_filler {
      type: "xavier"
    }
    bias_filler {
      type: "constant"
    }
  }
}
layer {
  name: "drop3"
  type: "Dropout"
  bottom: "conv3"
  top: "conv3"
  dropout_param {
    dropout_ratio: 0.5
  }
}
layer {
  name: "relu3"
  type: "ReLU"
  bottom: "conv3"
  top: "conv3"
}
layer {
  name: "norm3"
  type: "LRN"
  bottom: "conv3"
  top: "norm3"
  lrn_param {
    local_size: 3
    alpha: 0.0001
    beta: 0.75
  }
}
layer {
  name: "pool3"
  type: "Pooling"
  bottom: "norm3"
  top: "pool3"
  pooling_param {
    pool: MAX
    kernel_size: 2
    stride: 2
  }
}
layer {
  name: "conv4"
  type: "Convolution"
  bottom: "pool3"
  top: "conv4"
  param {
    lr_mult: 1
  }
  param {
    lr_mult: 2
  }
  convolution_param {
    num_output: 128
    pad: 2
    kernel_size: 9
    stride: 1
    weight_filler {
      type: "xavier"
    }
    bias_filler {
      type: "constant"
    }
  }
}
layer {
  name: "drop4"
  type: "Dropout"
  bottom: "conv4"
  top: "conv4"
  dropout_param {
    dropout_ratio: 0.5
  }
}
layer {
  name: "relu4"
  type: "ReLU"
  bottom: "conv4"
  top: "conv4"
}
layer {
  name: "norm4"
  type: "LRN"
  bottom: "conv4"
  top: "norm4"
  lrn_param {
    local_size: 3
    alpha: 0.0001
    beta: 0.75
  }
}
layer {
  name: "pool4"
  type: "Pooling"
  bottom: "norm4"
  top: "pool4"
  pooling_param {
    pool: MAX
    kernel_size: 2
    stride: 1
  }
}
layer {
  name: "conv5"
  type: "Convolution"
  bottom: "pool4"
  top: "conv5"
  param {
    lr_mult: 1
  }
  param {
    lr_mult: 2
  }
  convolution_param {
    num_output: 128
    pad: 2
    kernel_size: 9
    stride: 1
    weight_filler {
      type: "xavier"
    }
    bias_filler {
      type: "constant"
    }
  }
}
layer {
  name: "drop5"
  type: "Dropout"
  bottom: "conv5"
  top: "conv5"
  dropout_param {
    dropout_ratio: 0.5
  }
}
layer {
  name: "relu5"
  type: "ReLU"
  bottom: "conv5"
  top: "conv5"
}
layer {
  name: "norm5"
  type: "LRN"
  bottom: "conv5"
  top: "norm5"
  lrn_param {
    local_size: 3
    alpha: 0.0001
    beta: 0.75
  }
}
layer {
  name: "pool5"
  type: "Pooling"
  bottom: "norm5"
  top: "pool5"
  pooling_param {
    pool: MAX
    kernel_size: 2
    stride: 2
  }
}

**Comment by sodeypunk** [comment]
i'm thinking it's caused by the images being reduced too much so by the 4th layer, it has nothing to pool on...

**Comment by seanbell** [comment]
This is an exception inside `Reshape`.  Perhaps you are reshaping down to size 0?

**Comment by seanbell** [comment]
This is an exception inside `Reshape`.  Perhaps you are reshaping down to size 0?

See #3754

**Comment by sodeypunk** [comment]
Yes, i believe that was it. i made sure that the kernel wasn't too large and it worked fine.
