### ISSUE TITLE
one bottom with three top convolution

### ISSUE THREAD

**Issue by yellowyan** [BVLC/caffe#3758]
Hi everyone, now I need to do "three convolution" on "one bottom layer (denotes as bottomlayer)" with different kernel size, the bottom layer need to receive three error terms and add them for backward propagation. Using caffe, I could easily implement the net structure like this:
{ name: conv1
  bottom: bottomlayer
  top: conv1
  convolution_param{
     define kernel size1......
  }
}
{ name: conv2
  bottom: bottomlayer
  top: conv2
  convolution_param{
     define kernel size2......
  }
}
{ name: conv3
  bottom: bottomlayer
  top: conv3
  convolution_param{
     define kernel size3......
  }
}
My question is: Can the bottomlayer waiting until it recieves all three error terms from the three top layers? Or when the bottomlayer recieves one error term e.g. from conv1, it will continue to execute without waiting the other two error terms from conv2 and conv3? 
If the bottomlayer receives three error terms from conv1-3 not only one, can we get the three error terms using top[0]->cpu_diff(),top[1]->cpu_diff(),top[2]->cpu_diff()?

**Comment by seanbell** [comment]
Please ask for modeling help on the mailing list.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
