### ISSUE TITLE
Batch Normalization 

### ISSUE THREAD

**Issue by linnanwang** [BVLC/caffe#3760]
Hello Guys,

According to the Paper from Google, they could achieve > 90% top accuracy using batch normalization.
I noticed that caffe includes the batch normalization layer. So, is there a example model definition for us to play with batch normalization included. Thanks.

**Comment by BlGene** [comment]
See https://github.com/lim0606/caffe-googlenet-bn, These kind of questions belong on the mailing list, please close the issue.
