### ISSUE TITLE
How to finetune on two models?

### ISSUE THREAD

**Issue by timmynth** [BVLC/caffe#3763]
Now I have trained GoogleNet and VGG16 respectively for the same task, i.e. googlenet.caffemodel and vgg16.caffemodel. Now I want to merge the two networks to form an ensemble model. That is, I want to define the two network in a single prototxt. This means I need to fintune on two models. How can I do that?

**Comment by seanbell** [comment]
Please ask for usage help on the mailing list.  From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
