### ISSUE TITLE
Is 3-dimensional autoencoder for voxel data possible in caffe?

### ISSUE THREAD

**Issue by yiisama** [BVLC/caffe#3764]
Hi everyone.

I am a newbie in caffe and deep learning. Now I am going to train an convolutional autoencoder for medical voxel data (250 * 250 * 250). But I am not certain about few things. I would appreciate any helpful answers and advises.

1. Is 3-d convolutional layer available in caffe?
2. Is 3-d pooling layer available in caffe?
3. If the answer to 1 or 2 is no, then how difficult would it be for me to implement a 3d layer myself? Should I turn to other frameworks like theano? (I think theano should be capable of 3d layers but it's way too complex to implement it.)

Besides, I have seen someone said that channel could be used as third dimension. Is that correct for such 250^3 voxel data?

Thank you!

**Comment by seanbell** [comment]
Please ask for usage/modeling help on the mailing list.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

**Comment by futurely** [comment]
https://github.com/BVLC/caffe/pull/3983
