### ISSUE TITLE
CL-Caffe on AMD requires NVIDIA drivers first

### ISSUE THREAD

**Issue by dagamayank** [BVLC/caffe#3765]
@naibaf7  Why does the OpenCL implementation of Caffe requires NVIDIA drivers to be installed first even when it is intended to be run only on AMD GPUs?

**Comment by naibaf7** [comment]
@dagamayank 
Should not be necessary. It could be that I forgot to exclude CUDA/nVidia includes at some point in the code. As I only have systems with both nVidia and AMD GPUs installed (no pure OpenCL system) this might sometimes go unnoticed.

Make sure you disable CUDA and cuDNN in the Makefile.config. If there are still some compilation issues without having CUDA installed, please post the full error log here so I can fix it. Thanks.

**Comment by bhack** [comment]
@naibaf7 Cuda driver could be useful in some cases. Do you have experimented your kernel with llvm [nvptx-nvidia-cuda](http://stackoverflow.com/questions/8795114/how-to-use-clang-to-compile-opencl-to-ptx-code)?

**Comment by naibaf7** [comment]
@bhack 
I did not yet try this. Thanks for the hint though :)
