### ISSUE TITLE
Battery adapter stops supplying power while training big images

### ISSUE THREAD

**Issue by kimhc6028** [BVLC/caffe#3774]
I am training custom images sets with Caffe.
With 32*32 resized image, it works fine. However, training with images more than this size(> 45*45) causes adapter to stop charging.
I suspect power required for computation exceed power supplied by adapter, so adapter turns off. But, does data size really cause more power consumption?
Is there anyone have suffered same problem?
I am using 19V * 7.1A of adapter, and my GPU is nvidia GTX880M

**Comment by BlGene** [comment]
:grin: Try a new adapter and see,

This is interesting (and slightly funny) but not a caffe issue. Please close the issue and ask these question on the mailing list, or comptain to nvdidia that their GPUs don't fail gracefully.

**Comment by kimhc6028** [comment]
Thanks for your reply. I will close this issue.
