### ISSUE TITLE
caffe dll crashes in syncedmem.hpp on exit

### ISSUE THREAD

**Issue by cheer37** [BVLC/caffe#3785]
I made a classification.cpp as a dll in windows.
classification.cpp is working well in exe, but it crashes in syncedmem.hpp on exit in dll version.
There are two symptoms.
1. when i put the Net object as a classification class member, it crashes when Net.reset.
2. when i put the Net object as global object in classification.cpp file, it crashes in syncedmem.hpp on exit.
What's wrong with dll.
Thanks for your help in advance.

**Comment by seanbell** [comment]
Please ask for usage help on the mailing list.  Also note that this repository does not officially support Windows at the moment (see note here: http://caffe.berkeleyvision.org/installation.html).

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
