### ISSUE TITLE
import error No module named 'caffe._caffe'

### ISSUE THREAD

**Issue by Benedetta89** [BVLC/caffe#3790]
i tried to import caffe into a python script with "import caffe" and i got this error:

ImportError Traceback (most recent call last)
in ()
----> 1 import caffe

/home/benedetta/caffe/python/caffe/init.py in ()
----> 1 from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropSolver, AdaDeltaSolver, AdamSolver
2 from .caffe import set_mode_cpu, set_mode_gpu, set_device, Layer, get_solver, layer_type_list
3 from .caffe import __version
4 from .proto.caffe_pb2 import TRAIN, TEST
5 from .classifier import Classifier

/home/benedetta/caffe/python/caffe/pycaffe.py in ()
11 import numpy as np
12
---> 13 from ._caffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, \
14 RMSPropSolver, AdaDeltaSolver, AdamSolver
15 import caffe.io

ImportError:

i tried to import caffe into a python script with "import caffe" and i get this error:

ImportError Traceback (most recent call last)
in ()
----> 1 import caffe

/home/benedetta/caffe/python/caffe/init.py in ()
----> 1 from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropSolver, AdaDeltaSolver, AdamSolver
2 from .caffe import set_mode_cpu, set_mode_gpu, set_device, Layer, get_solver, layer_type_list
3 from .caffe import __version
4 from .proto.caffe_pb2 import TRAIN, TEST
5 from .classifier import Classifier

/home/benedetta/caffe/python/caffe/pycaffe.py in ()
11 import numpy as np
12
---> 13 from ._caffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, \
14 RMSPropSolver, AdaDeltaSolver, AdamSolver
15 import caffe.io

ImportError: No module named 'caffe._caffe'

i have already set the PYTHONPATH. Infact if i do echo $PYTHONPATH i obtain /home/benedetta/caffe/python:

What also have i to do????
thanks

i have already set the PYTHONPATH. Infact if i do echo $PYTHONPATH i obtain /home/benedetta/caffe/python:

What also have i to do????
thanks

**Comment by seanbell** [comment]
Did you build the python module (`make pycaffe`)?  Please ask installation questions on the mailing list. 

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

**Comment by gmt710** [comment]
make pycaffe
