### ISSUE TITLE
what is the relation between batch size and accuracy?

### ISSUE THREAD

**Issue by cheer37** [BVLC/caffe#3793]
I want know what is the relation between batch size and accuracy.
What is better to make batch size big or small in aspect of accuracy?
Thanks.

**Comment by seanbell** [comment]
Please ask usage/modeling questions on the mailing list:

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

**Comment by cheer37** [comment]
This is not usage!
