### ISSUE TITLE
convert binaryproto to npy

### ISSUE THREAD

**Issue by Benedetta89** [BVLC/caffe#3794]
i've converted a binaryproto mean into a numpy array using the function "blobproto_to_array" with these instructions:

MEAN_FILE = '/home/deepcuda/Scrivania/caffe/caffe/data/ilsvrc12/imagenet_mean_65_completo.binaryproto'
blob = caffe.proto.caffe_pb2.BlobProto()
data = open(MEAN_FILE, 'rb').read()
blob.ParseFromString(data)
arr = np.array(caffe.io.blobproto_to_array(blob))
print(arr.shape)
out = arr[0]
numpy.save('/home/deepcuda/Scrivania/caffe/caffe/data/ilsvrc12/imagenet_mean_65_completo.npy', out)

Now when i'm trying to subtract mean during test phase in python script:
mu = numpy.load(caffe_root + 'data/ilsvrc12/imagenet_mean_65_completo.npy')
transformer = caffe.io.Transformer({'data': net.blobs['data'].data.shape})
transformer.set_mean('data', mu)  

i'm getting this error:
    transformer.set_mean('data', mu)
  File "/home/deepcuda/Scrivania/caffe/caffe/python/caffe/io.py", line 258, in set_mean
    raise ValueError('Mean shape incompatible with input shape.')
ValueError: Mean shape incompatible with input shape.

the problem is in the shape that seems have to be (3,) while the shape of my "mu" is (3,65,65).
how have i to save npy file to obtain this shape?

**Comment by seanbell** [comment]
Please ask usage/installation questions on the mailing list.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
