### ISSUE TITLE
LevelDB core dump while snapshotting (out of files)

### ISSUE THREAD

**Issue by sguada** [BVLC/caffe#38]
Unexpected core dumped in io.cpp
WriteProtoToBinaryFile
CHECK(proto.SerializeToOstream(&output));
After writing 1 or 2 times correctly the next one fail.

**Comment by xiadaoxun** [comment]
Solution is to modify src/caffe/layers/data_layer.cpp by setting options.max_open_files = 100 (or any number significantly lower than 1000)

Can you give some examples? Where is the code inserted?
