### ISSUE TITLE
Recurrent Layer - Passing more than 3-dims into LSTM?

### ISSUE THREAD

**Issue by chriss2401** [BVLC/caffe#3800]
Hi,

I am trying to train a RNN (with donahue's code - #2033) by feeding feature maps extracted by a pre-trained CNN. Theoretically the LSTM layer accepts an input of TxNxW, where T is number of sequences, N is number of streams and W is number of dimensions. My W is three dimensional (256 28 28) but when I reshape my data to TxNx256x28x28 I get a notification from the recurrent layer that my bottom blob is of size TxNx256. I am getting very high accuracy when training and was thinking if the layer only receives the 256 dim of my feature map. If yes, should I maybe flatten the layer before passing it in? Thanks!

**Comment by seanbell** [comment]
Please ask usage/installation questions on the mailing list, or on the PR where this is relevant, or contact Jeff directly.  The Issues page is getting overloaded with questions not related to caffe development.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
