### ISSUE TITLE
what is the best optimization algorithm in visual recognition?

### ISSUE THREAD

**Issue by cheer37** [BVLC/caffe#3802]
There are several optimization algorithms SGD, Momentum, NAG, Adagrad, Adadelta, etc.
As i know adadelta is the fastest method to convergence.
however why most people use SGD? what is the best method for image recognition in aspect of speed and convergence?

**Comment by seanbell** [comment]
Please ask usage/modeling questions on the mailing list:

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
