### ISSUE TITLE
make: *** No rule to make target `matcaffe'.  Stop.

### ISSUE THREAD

**Issue by edgarriba** [BVLC/caffe#3803]
Hi,

I succeed at compiling Caffe with Matlab but I get this error when I try to call any function of the caffe api inside Matlab.

I guess everything is okay since the "caffe_.mexa64" is generated.
This is my CMake output:

-- Boost version: 1.55.0
-- Found the following Boost libraries:
--   system
--   thread
--   filesystem
-- Found gflags  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libgflags.so)
-- Found glog    (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libglog.so)
-- Found PROTOBUF Compiler: /usr/bin/protoc
-- Found lmdb    (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/liblmdb.so)
-- Found LevelDB (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libleveldb.so)
-- Found Snappy  (include: /usr/include, library: /usr/lib/libsnappy.so)
-- CUDA detected: 7.5
-- Found cuDNN: ver. 4.0.7 found (include: /usr/local/include, library: /usr/local/lib/libcudnn.so)
-- Added CUDA NVCC flags for: sm_52 sm_50
-- Cuda + Boost 1.55: Applying noinline work around
-- OpenCV found (/usr/local/share/OpenCV)
-- Found Atlas (include: /usr/include, library: /usr/lib/libatlas.so)
-- NumPy ver. 1.8.2 found (include: /usr/lib/python2.7/dist-packages/numpy/core/include)
-- Boost version: 1.55.0
-- Found the following Boost libraries:
--   python
## -- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) 

-- ******************\* Caffe Configuration Summary *******************
-- General:
--   Version           :   1.0.0-rc3
--   Git               :   rc2-878-gbe163be-dirty
--   System            :   Linux
--   C++ compiler      :   /usr/bin/c++
--   Release CXX flags :   -O3 -DNDEBUG -fPIC -Wall -Wno-sign-compare -Wno-uninitialized
--   Debug CXX flags   :   -g -fPIC -Wall -Wno-sign-compare -Wno-uninitialized
## --   Build type        :   Release

--   BUILD_SHARED_LIBS :   ON
--   BUILD_python      :   ON
--   BUILD_matlab      :   ON
--   BUILD_docs        :   ON
--   CPU_ONLY          :   OFF
--   USE_OPENCV        :   ON
--   USE_LEVELDB       :   ON
--   USE_LMDB          :   ON
## --   ALLOW_LMDB_NOLOCK :   OFF

-- Dependencies:
--   BLAS              :   Yes (Atlas)
--   Boost             :   Yes (ver. 1.55)
--   glog              :   Yes
--   gflags            :   Yes
--   protobuf          :   Yes (ver. 2.5.0)
--   lmdb              :   Yes (ver. 0.9.10)
--   LevelDB           :   Yes (ver. 1.15)
--   Snappy            :   Yes (ver. 1.1.0)
--   OpenCV            :   Yes (ver. 3.1.0)
## --   CUDA              :   Yes (ver. 7.5)

-- NVIDIA CUDA:
--   Target GPU(s)     :   Auto
--   GPU arch(s)       :   sm_52 sm_50
## --   cuDNN             :   Yes (ver. 4.0.7)

-- Python:
--   Interpreter       :   /usr/bin/python2.7 (ver. 2.7.6)
--   Libraries         :   /usr/lib/x86_64-linux-gnu/libpython2.7.so (ver 2.7.6)
## --   NumPy             :   /usr/lib/python2.7/dist-packages/numpy/core/include (ver 1.8.2)

-- Matlab:
--   Matlab            :   Yes (/usr/local/MATLAB/R2014b/bin/mex, /usr/local/MATLAB/R2014b/bin/mexext
## --   Octave            :   No

-- Documentaion:
--   Doxygen           :   No
## --   config_file       :   

-- Install:
## --   Install path      :   /home/eriba/software/caffe/build/install

-- Configuring done
-- Generating done
-- Build files have been written to: /home/eriba/software/caffe/build

**Comment by djebm2** [comment]
Same issue. I've only got a mex64 file in install/caffe generated after the compilation.

Have you figured out the matcaffe thing ?

**Comment by edgarriba** [comment]
nope

**Comment by zhangzongliang** [comment]
I have the same problem..

**Comment by scott-vsi** [comment]
I believe this target is now just called matlab. If you are using CMake, the BUILD_matlab flag must be on.

**Comment by Dan1900** [comment]
cmake .. -DUILD_matlab=ON

**Comment by naetherm** [comment]
The answer of @scott-vsi is correct. The target is now just called matlab.
