### ISSUE TITLE
how can we set the proper batch size?

### ISSUE THREAD

**Issue by cheer37** [BVLC/caffe#3805]
I am wondering how large i set the batch size.
I know small batch size tends to divergence, but how large i should set?
please discuss about this.

**Comment by seanbell** [comment]
Please ask usage/modeling questions on the mailing list:

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
