### ISSUE TITLE
make error as: [.build_debug/lib/libcaffe.so.1.0.0-rc3] Error 1

### ISSUE THREAD

**Issue by haohao900618** [BVLC/caffe#3811]
I make && make runtest previous caffe and other caffe repositoies  successful, but when I download and make the newest repository of BVLC/caffe, I encounter an error as:
......
AR -o .build_debug/lib/libcaffe.a
LD -o .build_debug/lib/libcaffe.so.1.0.0-rc3
/usr/bin/ld: cannot find -l/public/home/hyang/anaconda/lib/python2.7 :/public/home/hyang/anaconda/lib/python2.7:
collect2: ld returned 1 exit status
make: *** [.build_debug/lib/libcaffe.so.1.0.0-rc3] Error 1

And when I commence the WITH_PYTHON_LAYER := 1, the make error disapper.
but with another error when I make runtest as:
......
CXX/LD -o .build_debug/test/test_all.testbin src/caffe/test/test_caffe_main.cpp
/usr/bin/ld: warning: libboost_system.so.1.59.0, needed by /public/home/hyang/local/lib/libboost_thread.so, may conflict with libboost_system.so.5
.build_debug/src/caffe/test/test_db.o: In function `boost::filesystem::operator/(boost::filesystem::path const&, boost::filesystem::path const&)':
/public/home/hyang/local/include/boost/filesystem/path.hpp:696: undefined reference to `boost::filesystem::path::operator/=(boost::filesystem::path const&)'
.build_debug/src/caffe/test/test_db.o: In function `boost::filesystem::create_directory(boost::filesystem::path const&)':
/public/home/hyang/local/include/boost/filesystem/operations.hpp:529: undefined reference to `boost::filesystem::detail::create_directory(boost::filesystem::path const&, boost::system::error_code*)'
.build_debug/src/caffe/test/test_db.o: In function `boost::filesystem::temp_directory_path()':
/public/home/hyang/local/include/boost/filesystem/operations.hpp:661: undefined reference to `boost::filesystem::detail::temp_directory_path(boost::system::error_code*)'
.build_debug/src/caffe/test/test_db.o: In function `boost::filesystem::unique_path(boost::filesystem::path const&)':
/public/home/hyang/local/include/boost/filesystem/operations.hpp:668: undefined reference to `boost::filesystem::detail::unique_path(boost::filesystem::path const&, boost::system::error_code*)'
collect2: ld returned 1 exit status
make: *** [.build_debug/test/test_all.testbin] Error 1

I am not sure the two problems have any relationship. Thanks for any clue!

**Comment by seanbell** [comment]
It looks like you may have a boost conflict:
```
/usr/bin/ld: warning: libboost_system.so.1.59.0, needed by /public/home/hyang/local/lib/libboost_thread.so, may conflict with libboost_system.so.5
```

**Comment by seanbell** [comment]
Assuming this is an installation issue, please ask for help on the mailing list.  If you think you found a bug in caffe, re-open the issue.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
