### ISSUE TITLE
How to transform an unencoded datum into cv::mat?

### ISSUE THREAD

**Issue by DBCheung** [BVLC/caffe#3813]
Hello, everyone! I want to add some functions in dataLayer.cpp, so I need to transform datum into cv::mat. I notice DecodeDatumToCVMat in io.cpp, which transforms decoded datum into mat. But what should i do if datum is unencoded?
Thanks in advance for any suggestion.

**Comment by seanbell** [comment]
Please ask questions about how to use caffe on the mailing list.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
