### ISSUE TITLE
Python3: net.params is an empty dictionary

### ISSUE THREAD

**Issue by untom** [BVLC/caffe#3815]
Hi!

After updating to the latest github master ( be163be ) under Python 3.5.1 (using boost 1.59, protobuf 3.0.0.alpha and lmdb 0.9.17). The Python wrapper doesn't seem to work correctly anymore. Concretely, `net.params` returns an empty dictionary:

    import caffe
    net = caffe.Net("../bvlc_alexnet/deploy.prototxt",
                    "../bvlc_alexnet/bvlc_alexnet.caffemodel",
                    caffe.TEST)
    print(net.params.keys())
    >>>> odict_keys([])

Curiously, I can access `net.blobs` just fine:

    print(net.blobs.keys())
    >>>> odict_keys(['data', 'conv1', 'norm1', 'pool1', 'conv2', 'norm2', 'pool2', 'conv3', 'conv4', 'conv5', 'pool5', 'fc6', 'fc7', 'fc8', 'prob'])

This bug was not present in our previous installation (I don't have the exact commit number, but it was cloned ~3 months ago). A colleague of mine tried the same caffe-version under Python 2, and there everything still seems to work as expected. Any help would be appreciated.

**Comment by untom** [comment]
The error has disappeared after a `make clean` and a recompilation, so I'm assuming the error was me not doing a clean recompile.

**Comment by logic1988** [comment]
I encountered same error in python2, and solved it by make clean. Thank you.

**Comment by guolele1990** [comment]
it also solve my problem.Thank you

  File "/opt/caffe-1.0/python/caffe/pycaffe.py", line 65, in _Net_params
    self._params_dict = OrderedDict([(name, lr.blobs)
  File "/opt/caffe-1.0/python/caffe/pycaffe.py", line 68, in <listcomp>
    if len(lr.blobs) > 0])
OverflowError: cannot fit 'int' into an index-sized integer
