### ISSUE TITLE
When dose caffe clear layers' bottom/top's diff?

### ISSUE THREAD

**Issue by sciencefans** [BVLC/caffe#3816]
Hi all!
As we know we need to clear layer's parameters' diff and bottom/top's diff at each step when training a net. And I found that in `solver.cpp` it has `net_->ClearParamDiffs()` to clear layer's parameters' diff, but when does caffe clear layers' bottom/top's diff?

**Comment by shelhamer** [comment]
See #6202 and #6186 for discussion.
