### ISSUE TITLE
Bug: draw_net utility fails when prototxt has no "name" attribute

### ISSUE THREAD

**Issue by shaibagon** [BVLC/caffe#3819]
Consider the following simple prototxt

> layer {
  name: "data"
  type: "DummyData"
  top: "X"
  top: "y"
  dummy_data_param: { 
    shape: {dim:50 dim:1024 }
    shape: {dim:50}
  }
}
layer {
  name: "fc"
  type: "InnerProduct"
  bottom: "X"
  top: "fc"
  inner_product_param {
    num_output: 100
  }
}
layer {
  name: "relu"
  type: "ReLU"
  bottom: "fc"
  top: "fc" # in place
}

if I try to "draw" it

    ~$ python $CAFFE_ROOT/python/draw_net.py dummy.prototxt dummy.png

I get the following error:

> Drawing net to output.png  
Warning: /tmp/tmpOMoJNS: syntax error in line 1 near '{'

However, adding 

> name: "dummy net"

To the prototxt, solves this issue.

Why is this an issue? 
I noticed that when I use `caffe.NetSpec()` to create models' prototxt the `"name"` attribute is omitted.
So please, it would be nice if
1. `draw_net.py` will not fail if `"name"` is missing
2. `caffe.NetSpec()` will have a `"name"` attribute in the resulting `to_proto()` output.

Thanks!

**Comment by lukeyeager** [comment]
Yeah that bothers me too.

https://github.com/NVIDIA/DIGITS/blob/v3.0.0/digits/frameworks/caffe_framework.py#L108-L110

**Comment by shaibagon** [comment]
@lukeyeager  I spent ages to track this &^%$ down... it's so good to know I am not alone here...

**Comment by ferrouswheel** [comment]
For me

> name: "dummy net"

didn't work. I had to ensure that `name` didn't have a space in it:

> name: "dummynet"
