### ISSUE TITLE
make runtest error

### ISSUE THREAD

**Issue by HairongWu** [BVLC/caffe#3820]

**Comment by HairongWu** [comment]
[wuhairong@zhsw-ws02 caffe-master]$ make runtest
.build_release/tools/caffe
ERROR: flag 'tab_completion_word' was defined more than once (in files 'src/gflags_completions.cc' and '/home/wuhairong/gflags-master/src/gflags_completions.cc').
make: *** [runtest] 错误 1

**Comment by seanbell** [comment]
Please questions about how to install caffe on the mailing list.  Judging by your error, you will have the same problem if you just run `make`.  It looks like you should first figure out how to properly install gflags.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
