### ISSUE TITLE
convert .mat to lmdb

### ISSUE THREAD

**Issue by liyangliu** [BVLC/caffe#3822]
Hello, everyone, i am trying to convert a .mat file to lmdb. This .mat file has a variable named "data" which is a H(eight) * W(idth) * C(hannel) * N(um) matrix.

this is my source code

==============================================================================
// This program converts a .mat to a lmdb/leveldb by storing it
// as Datum proto buffers.
// Usage:
//   convert_mat [FLAGS] MAT_NAME DB_NAME

#include "mat.h"
#include <algorithm>
#include <fstream>  // NOLINT(readability/streams)
#include <string>
#include <utility>
#include <vector>
#include <iostream>

#include "boost/scoped_ptr.hpp"
//#include "gflags/gflags.h"
//#include "glog/logging.h"

#include "caffe/proto/caffe.pb.h"
#include "caffe/util/db.hpp"
#include "caffe/util/io.hpp"
#include "caffe/util/rng.hpp"

using namespace caffe;  // NOLINT(build/namespaces)
using boost::scoped_ptr;

int main(int argc, char** argv) {

  char* mat_name = argv[1]; 
  char* db_name = argv[2];

  // Create new DB
  scoped_ptr<db::DB> db(db::GetDB("lmdb"));
  db->Open(db_name, db::NEW);
  scoped_ptr<db::Transaction> txn(db->NewTransaction());

  MATFile* pmat = matOpen(mat_name, "r");
  mxArray* parr = matGetVariable(pmat, "data");
  float* pdat = (float*)mxGetData(parr);
  
  const mwSize* dims = mxGetDimensions(parr);
  int num = dims[3];
  int channel = dims[2];
  int height = dims[0];
  int width = dims[1];
  int area = height * width;
  int size = channel * height * width;

  // Storing to db
  int count = 0;
  const int kMaxKeyLength = 256;
  char key_cstr[kMaxKeyLength];

  for (int i = 0; i < num; i++) {
    
    Datum datum;
    datum.set_channels(channel);
    datum.set_height(height);
    datum.set_width(width);
    datum.clear_float_data();
    
    for (int j = 0; j < size; j++) {
      int chan = j / area;
      int row = (j - chan * area) / width;
      int col = j - row * width - chan * area;
      datum.set_float_data(j, pdat[i * size + chan * area + col * height + row]);
    }
  
    datum.set_label(0);
    datum.set_encoded(false);

    int length = snprintf(key_cstr, kMaxKeyLength, "%08d", i);
    string out;
    CHECK(datum.SerializeToString(&out));
    txn -> Put(string(key_cstr, length), out);

    if (++count % 1000 == 0) {
      txn -> Commit();
      txn.reset(db -> NewTransaction());
      std::cout << "Processed " << count << " files.\n";
    }
  }

  if (++count % 1000 != 0) {
    txn -> Commit();
    std::cout << "Processed " << count << " files.\n";
  }
  
  mxDestroyArray(parr);
  matClose(pmat);
    
  return 0;
}
==============================================================================

and this is my CMakeLists.txt

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
PROJECT(mat2lmdb)
CMAKE_MINIMUM_REQUIRED(VERSION 3.0)

INCLUDE_DIRECTORIES(/usr/local/MATLAB/R2014a/extern/include /home/lly/caffe_dependency/caffe/include)
LINK_DIRECTORIES(/usr/local/MATLAB/R2014a/bin/glnxa64)

SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11 -lmx -lmat")
SET(CMAKE_RUNTIME_OUTPUT_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}/bin")

SET(SOURCE_FILES convert_mat.cpp)

ADD_EXECUTABLE(mat2lmdb ${SOURCE_FILES})
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

I wrote this code according to:
https://bitbucket.org/harryyang_ttic/sema-mat2lmdb

But when I use "cmake ." and "make" command to compile this file. It turns out to be error like follows:

==============================================================================
CMakeFiles/mat2lmdb.dir/convert_mat.cpp.o：在函数‘main’中：
convert_mat.cpp:(.text+0x85)：对‘caffe::db::GetDB(std::string const&)’未定义的引用
convert_mat.cpp:(.text+0x17d)：对‘matOpen’未定义的引用
convert_mat.cpp:(.text+0x198)：对‘matGetVariable’未定义的引用
convert_mat.cpp:(.text+0x1ae)：对‘mxGetData’未定义的引用
convert_mat.cpp:(.text+0x1c4)：对‘mxGetDimensions’未定义的引用
convert_mat.cpp:(.text+0x276)：对‘caffe::Datum::Datum()’未定义的引用
convert_mat.cpp:(.text+0x452)：对‘google::protobuf::MessageLite::SerializeToString(std::string*) const’未定义的引用
convert_mat.cpp:(.text+0x481)：对‘google::LogMessageFatal::LogMessageFatal(char const*, int)’未定义的引用
convert_mat.cpp:(.text+0x495)：对‘google::LogMessage::stream()’未定义的引用
convert_mat.cpp:(.text+0x4e2)：对‘google::LogMessageFatal::~LogMessageFatal()’未定义的引用
convert_mat.cpp:(.text+0x63c)：对‘caffe::Datum::~Datum()’未定义的引用
convert_mat.cpp:(.text+0x6ec)：对‘mxDestroyArray’未定义的引用
convert_mat.cpp:(.text+0x6fb)：对‘matClose’未定义的引用
convert_mat.cpp:(.text+0x7a7)：对‘google::LogMessageFatal::~LogMessageFatal()’未定义的引用
convert_mat.cpp:(.text+0x7fa)：对‘caffe::Datum::~Datum()’未定义的引用
CMakeFiles/mat2lmdb.dir/convert_mat.cpp.o：在函数‘__static_initialization_and_destruction_0(int, int)’中：
convert_mat.cpp:(.text+0x888)：对‘boost::system::generic_category()’未定义的引用
convert_mat.cpp:(.text+0x894)：对‘boost::system::generic_category()’未定义的引用
convert_mat.cpp:(.text+0x8a0)：对‘boost::system::system_category()’未定义的引用
CMakeFiles/mat2lmdb.dir/convert_mat.cpp.o：在函数‘google::protobuf::RepeatedField<float>::Set(int, float const&)’中：
convert_mat.cpp:(.text._ZN6google8protobuf13RepeatedFieldIfE3SetEiRKf[_ZN6google8protobuf13RepeatedFieldIfE3SetEiRKf]+0x3e)：对‘google::protobuf::internal::LogMessage::LogMessage(google::protobuf::LogLevel, char const*, int)’未定义的引用
convert_mat.cpp:(.text._ZN6google8protobuf13RepeatedFieldIfE3SetEiRKf[_ZN6google8protobuf13RepeatedFieldIfE3SetEiRKf]+0x54)：对‘google::protobuf::internal::LogMessage::operator<<(char const*)’未定义的引用
convert_mat.cpp:(.text._ZN6google8protobuf13RepeatedFieldIfE3SetEiRKf[_ZN6google8protobuf13RepeatedFieldIfE3SetEiRKf]+0x6c)：对‘google::protobuf::internal::LogFinisher::operator=(google::protobuf::internal::LogMessage&)’未定义的引用
convert_mat.cpp:(.text._ZN6google8protobuf13RepeatedFieldIfE3SetEiRKf[_ZN6google8protobuf13RepeatedFieldIfE3SetEiRKf]+0x7f)：对‘google::protobuf::internal::LogMessage::~LogMessage()’未定义的引用
convert_mat.cpp:(.text._ZN6google8protobuf13RepeatedFieldIfE3SetEiRKf[_ZN6google8protobuf13RepeatedFieldIfE3SetEiRKf]+0xb6)：对‘google::protobuf::internal::LogMessage::LogMessage(google::protobuf::LogLevel, char const*, int)’未定义的引用
convert_mat.cpp:(.text._ZN6google8protobuf13RepeatedFieldIfE3SetEiRKf[_ZN6google8protobuf13RepeatedFieldIfE3SetEiRKf]+0xcc)：对‘google::protobuf::internal::LogMessage::operator<<(char const*)’未定义的引用
convert_mat.cpp:(.text._ZN6google8protobuf13RepeatedFieldIfE3SetEiRKf[_ZN6google8protobuf13RepeatedFieldIfE3SetEiRKf]+0xe4)：对‘google::protobuf::internal::LogFinisher::operator=(google::protobuf::internal::LogMessage&)’未定义的引用
convert_mat.cpp:(.text._ZN6google8protobuf13RepeatedFieldIfE3SetEiRKf[_ZN6google8protobuf13RepeatedFieldIfE3SetEiRKf]+0xf7)：对‘google::protobuf::internal::LogMessage::~LogMessage()’未定义的引用
convert_mat.cpp:(.text._ZN6google8protobuf13RepeatedFieldIfE3SetEiRKf[_ZN6google8protobuf13RepeatedFieldIfE3SetEiRKf]+0x12b)：对‘google::protobuf::internal::LogMessage::~LogMessage()’未定义的引用
convert_mat.cpp:(.text._ZN6google8protobuf13RepeatedFieldIfE3SetEiRKf[_ZN6google8protobuf13RepeatedFieldIfE3SetEiRKf]+0x14c)：对‘google::protobuf::internal::LogMessage::~LogMessage()’未定义的引用
collect2: 错误： ld 返回 1
make[2]: *** [bin/mat2lmdb] Error 1
make[1]: *** [CMakeFiles/mat2lmdb.dir/all] Error 2
make: *** [all] Error 2
==============================================================================

Sorry for that my system language is Chinese. The main error is "undefined reference" to the function I used from matlab and caffe. Maybe I shoud link some library or .so to compile this file. Would you please be so kind as to help me out. I am so new to caffe and C & Matlab compiling.

Thank you very much.

@shelhamer @Yangqing @everyone

**Comment by seanbell** [comment]
Please ask the mailing list for help with installing, compiling, and linking libraries.  This looks like an error with a file that you created, and not a caffe file?

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

**Comment by 623353908** [comment]
I have the same question with .mat converting to .lmdb.Have you solve this question.Cause I'm a very very new comer to this region. Could you help me to handle this problem. THANKS,Looking for your early replay.

**Comment by liyangliu** [comment]
I don't know how to convert .mat to lmdb yet, but I instead convert original data to lmdb directly using c++ tools included in caffe tools.

**Comment by 623353908** [comment]
Thanks any way,but your way isn't suitable for me,cause i can't find the original images.
