### ISSUE TITLE
Will you be interested in a python interface to create models?

### ISSUE THREAD

**Issue by RalphMao** [BVLC/caffe#3824]
I am recently considering adding a wrapper to caffe.io.caffe_pb2 so that one can easily create a model in python. Current we can do it with caffe_pb2, but it is not easy(no easier than writting the prototxt directly).

What I want is making it as easy as it is in keras (or some other librarys). For example, one can create a CNN like that:

model = DAG()
last_layer = model.add_layer(type='data', source='xxx')
for layer_param in layer_params:
     conv = model.add_layer(type='conv', kernel_size=layer_param['kernel_size'], channel=layer_param['channel'])
     relu = model.add_layer(type='relu')
     model.connect(conv, last_layer)
     model.connect(relu, conv)
     last_layer = relu
........
model.to_proto('train.prototxt')

I am not sure if anybody has already done it, or if others will be interested in such a wrapper.

**Comment by seanbell** [comment]
This already exists in caffe: `caffe.NetSpec` https://github.com/BVLC/caffe/blob/master/python/caffe/net_spec.py.  You can use netspec to generate a prototxt file.

Here is a tutorial example that uses it: http://nbviewer.jupyter.org/github/BVLC/caffe/blob/master/examples/pascal-multilabel-with-datalayer.ipynb
(this tutorial goes further and also uses Python for the data layer and solver)

**Comment by RalphMao** [comment]
@seanbell Thank you so much!
