### ISSUE TITLE
when should we stop the training?

### ISSUE THREAD

**Issue by cheer37** [BVLC/caffe#3828]
I am training my net and went enough many iterations now.
now, loss is fluctuating, and accuracy does not increase.
This means net arrives at optimization? but i am afraid that it would arrive at local minima.
because it's not expected loss.
what we can do at this situation? how can we decide if net arrives at global minima and end training?
Thanks in advance.

**Comment by seanbell** [comment]
Hi @cheer37 please use the mailing list.  This question is about how to use deep learning in general.  For example, Geoff Hinton's coursera course addresses this question.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
