### ISSUE TITLE
How to create train.txt and val.txt file from own dataset?

### ISSUE THREAD

**Issue by monjoybme** [BVLC/caffe#3829]
Hi I am trying to train my own dataset using "bvlc_reference_caffenet" model to detect nuclei. In the image there has 3 types of object like one is nuclei, another one is lymphocytes and third one is background. I want to segment only nuclei. So first of all I have to prepare my dataset. For this we have to label the images. I want to know how can I label image? do I have to manually mark on the original image  and then need to prepare train.txt file or what? Please explain I am new in caffe.

**Comment by seanbell** [comment]
Please questions about how to use caffe on the mailing list.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
