### ISSUE TITLE
Should I need to crop original image to prepare train.txt or val.txt file?

### ISSUE THREAD

**Issue by monjoybme** [BVLC/caffe#3830]
Suppose I have 1056 x 1056 image. The image contains multiple objects like car, house, tree etc but I want only car as a target object in this case how shall I prepare train.txt file? Should I crop only car from original image and prepare two class which have car denoted by 1 and which dose not have car denote by 0.

or 

should I consider original image(size 1056x1056) having car 1 and doesn't have car 0.

Please explain.

**Comment by seanbell** [comment]
Please ask the mailing list for help with using caffe.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
