### ISSUE TITLE
The bias is not learnt in the 1x1 conv layer

### ISSUE THREAD

**Issue by huangjunshi** [BVLC/caffe#3833]
Hi there,

I don't whether I make a mistake or not, I found that the bias in the 1x1 conv layer is not learnt (which is exactly the initialization value) in the latest version of caffe, even if I double check that the second mult_lr is set as 2.0 in my prototxt. Could anyone help to load their google net and check the bias value of some 1x1 layers, such as "conv2/3x3_reduce"? Apologize if I make something wrong. :)

**Comment by seanbell** [comment]
- I'm not sure I understand the problem.  You're saying that the gradient for a layer is nonzero and yet the weights are never updated?  Is the update (weights * learning rate) large enough to make a difference? (e.g. adding 1e-400 to a value won't change it)
- Can you provide a minimal failing example?  That is, the simplest possible setup that shows the issue?
