### ISSUE TITLE
why the accuracy of caffenet is lower than the one in the paper of Alex？

### ISSUE THREAD

**Issue by zhuikonger** [BVLC/caffe#3837]
The top-5 accuracy of Caffenet and Alexnet in Caffe is about 80.3%. But  in the paper of Alex, the top-5 error rate is 16.4%( 5-CNNs in the paper). I want to known why the accuracy of caffenet is lower than the one in the paper of Alex(2012)？

**Comment by seanbell** [comment]
Are you making an apples-to-apples comparison?  How many crops are being averaged together at testime?

**Comment by shelhamer** [comment]
See the BVLC AlexNet readme for details: https://github.com/BVLC/caffe/blob/master/models/bvlc_alexnet/readme.md

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
