### ISSUE TITLE
How I can Classify an Image using my own trained network in MATLAB?

### ISSUE THREAD

**Issue by monjoybme** [BVLC/caffe#3840]
Hi I am trying to classify one image using my trained network in MATLAB. I don't have any idea how can I classify. Please help

**Comment by seanbell** [comment]
Please ask questions like this on the mailing list.  From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
