### ISSUE TITLE
clang: error: no such file or directory: '/usr/local/opt/openblas/lib:'

### ISSUE THREAD

**Issue by kenric** [BVLC/caffe#3844]
I followed berkeleyvision.org instructions to install Caffe on my mac running El Capitan. Make returns:

LD -o .build_release/lib/libcaffe.so.1.0.0-rc3
clang: error: no such file or directory: '/usr/local/opt/openblas/lib:'
make: *** [.build_release/lib/libcaffe.so.1.0.0-rc3] Error 1

but /usr/local/opt/openblas/lib exists. 

Has anyone run into this?

**Comment by seanbell** [comment]
There is an extra `:` at the end of your directory name that should probably be removed.

**Comment by seanbell** [comment]
Assuming this is an installation issue, please ask for help on the mailing list.  If you think you found a bug in caffe, re-open the issue.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

**Comment by pengoofei** [comment]
I also met the error 

`LD -o .build_release/lib/libcaffe.so.1.0.0-rc3
clang: error: no such file or directory: '/usr/local/opt/openblas/lib:'
make: *** [.build_release/lib/libcaffe.so.1.0.0-rc3] Error 1`

I donnot know how to solve it ,help help help!

**Comment by pengoofei** [comment]
we got the error  maybe  used  the xcode ~  ~  ~
