### ISSUE TITLE
A libcaffe.so.1.0.0-rc3 issue appears while compiling with the current vision : undefined leveldb

### ISSUE THREAD

**Issue by zhoususheng** [BVLC/caffe#3847]
**when I make all and make runtest, it appears an issue,**

 ../../../lib/libcaffe.so.1.0.0-rc3：‘leveldb::DB::Open(leveldb::Options const&, std::string const&, leveldb::DB**)’undefined reference
../../../lib/libcaffe.so.1.0.0-rc3：leveldb::Status::ToString() const’ undefined reference
collect2: error: ld returned 1 exit status
src/caffe/test/CMakeFiles/test.testbin.dir/build.make:1755: recipe for target 'test/test.testbin' failed
make[3]: *** [test/test.testbin] Error 1
CMakeFiles/Makefile2:337: recipe for target 'src/caffe/test/CMakeFiles/test.testbin.dir/all' failed
make[2]: *** [src/caffe/test/CMakeFiles/test.testbin.dir/all] Error 2
CMakeFiles/Makefile2:312: recipe for target 'src/caffe/test/CMakeFiles/runtest.dir/rule' failed
make[1]: *** [src/caffe/test/CMakeFiles/runtest.dir/rule] Error 2
Makefile:228: recipe for target 'runtest' failed
make: *** [runtest] Error 2

**Thank you everyone to attention this issue. **

**I have install libleveldb-dev, the report like below:**

-- Boost version: 1.60.0
-- Found the following Boost libraries:
--   system
--   thread
--   filesystem
-- Found gflags  (include: /usr/local/include, library: /usr/local/lib/libgflags.a)
-- Found glog    (include: /usr/local/include, library: /usr/local/lib/libglog.a)
-- Found PROTOBUF Compiler: /usr/local/bin/protoc
-- Found lmdb    (include: /usr/local/include, library: /usr/local/lib/liblmdb.so)
-- Found LevelDB (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libleveldb.so)
-- Found Snappy  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libsnappy.so)
-- CUDA detected: 7.5
-- Added CUDA NVCC flags for: sm_21
-- OpenCV found (/usr/local/share/OpenCV)
-- Found Atlas (include: /usr/include, library: /usr/lib/libatlas.so)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/username/.local/lib/python2.7/site-packages/numpy/__init__.py", line 180, in <module>
    from . import add_newdocs
  File "/home/usename/.local/lib/python2.7/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/home/username/.local/lib/python2.7/site-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/home/username/.local/lib/python2.7/site-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/home/username/.local/lib/python2.7/site-packages/numpy/core/__init__.py", line 14, in <module>
    from . import multiarray
ImportError: /home/usename/.local/lib/python2.7/site-packages/numpy/core/multiarray.so: undefined symbol: _PyUnicodeUCS4_IsWhitespace
-- Could NOT find NumPy (missing:  NUMPY_INCLUDE_DIR NUMPY_VERSION) (Required is at least version "1.7.1")
-- Boost version: 1.60.0
-- Found the following Boost libraries:
--   python
-- Python interface is disabled or not all required dependencies found. Building without it...
-- Detected Doxygen OUTPUT_DIRECTORY: ./doxygen/
-- 
-- ******************* Caffe Configuration Summary *******************
-- General:
--   Version           :   1.0.0-rc3
--   Git               :   rc3-82-gbe163be
--   System            :   Linux
--   C++ compiler      :   /usr/bin/c++
--   Release CXX flags :   -O3 -DNDEBUG -fPIC -Wall -Wno-sign-compare -Wno-uninitialized
--   Debug CXX flags   :   -g -fPIC -Wall -Wno-sign-compare -Wno-uninitialized
--   Build type        :   Debug
-- 
--   BUILD_SHARED_LIBS :   ON
--   BUILD_python      :   ON
--   BUILD_matlab      :   OFF
--   BUILD_docs        :   ON
--   CPU_ONLY          :   OFF
--   USE_OPENCV        :   ON
--   USE_LEVELDB       :   ON
--   USE_LMDB          :   ON
--   ALLOW_LMDB_NOLOCK :   OFF
-- 
-- Dependencies:
--   BLAS              :   Yes (Atlas)
--   Boost             :   Yes (ver. 1.60)
--   glog              :   Yes
--   gflags            :   Yes
--   protobuf          :   Yes (ver. 3.0.0)
--   lmdb              :   Yes (ver. 0.9.70)
--   LevelDB           :   Yes (ver. 1.18)
--   Snappy            :   Yes (ver. 1.1.3)
--   OpenCV            :   Yes (ver. 3.1.0)
--   CUDA              :   Yes (ver. 7.5)
-- 
-- NVIDIA CUDA:
--   Target GPU(s)     :   Auto
--   GPU arch(s)       :   sm_21
--   cuDNN             :   Not found
-- 
-- Documentaion:
--   Doxygen           :   /usr/bin/doxygen (1.8.9.1)
--   config_file       :   /home/username/OpenSource/DeepLearning/caffe/.Doxyfile
-- 
-- Install:
--   Install path      :   /home/username/OpenSource/DeepLearning/caffe/cmake_build/install
-- 
-- Configuring done
CMake Error at CMakeLists.txt:85 (add_dependencies):
  The dependency target "pycaffe" of target "pytest" does not exist.

-- Generating done
-- Build files have been written to: /home/username/OpenSource/DeepLearning/caffe/cmake_build

**Comment by fenrus75** [comment]
make sure you have the python dev headers/libs installed... the lack of those broke this for me.

**Comment by wqlw** [comment]
what you said about " python dev headers/libs",would you tell me how to install?@fenrus75

**Comment by cristiancanton** [comment]
sudo aptitude install python-dev

**Comment by auroua** [comment]
I encounter the same problem. I have solved this problem.
I think you should make sure that the libleveldb.so soft link is correct.

**Comment by shelhamer** [comment]
Please ask installation questions on the mailing list. If you're having trouble, you might want to try the Caffe [Dockerfile](https://github.com/BVLC/caffe/tree/master/docker) to take care of installation for you.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

**Comment by salvador-blanco** [comment]
> make sure you have the python dev headers/libs installed... the lack of those broke this for me.


@fenrus75 Could you explain how to do it ?

I have a similar problem:
https://github.com/CMU-Perceptual-Computing-Lab/caffe_train/issues/16
??

**Comment by salvador-blanco** [comment]
> I encounter the same problem. I have solved this problem.
> I think you should make sure that the libleveldb.so soft link is correct.

@auroua 

Could you explain how to do it?
Thank you!!
