### ISSUE TITLE
make pycaffe error

### ISSUE THREAD

**Issue by CongB** [BVLC/caffe#3850]
Using ubuntu 14 and anaconda, python 2.7
It says cannot find the python header but I just installed python-dev and libpython2.7-dev...
Any suggestion?

```
cong@ubuntu:~/caffe-master$ make pycaffe
CXX/LD -o python/caffe/_caffe.so python/caffe/_caffe.cpp
python/caffe/_caffe.cpp:1:52: fatal error: Python.h: No such file or directory
#include <Python.h>  // NOLINT(build/include_alpha)
                                                   ^
compilation terminated.
make: *** [python/caffe/_caffe.so] Error 1
```
And this is what I have in my makeconfig file:
ANACONDA_HOME := $ home/cong/anaconda2
PYTHON_INCLUDE := $(ANACONDA_HOME)/include \
		 $(ANACONDA_HOME)/include/python2.7 \
		 $(ANACONDA_HOME)/lib/python2.7/site-packages/numpy/core/include \

**Comment by CongB** [comment]
Seems like I need a '/' before 'home/...'
Is this showing import caffe is successful?
What I Run:
```
import sys
caffe_root = '/home/cong/caffe-master/'  # this file should be run from {caffe_root}/examples (otherwise change this line)
sys.path.insert(0, caffe_root + 'python')
import caffe
```

what I got:
```
import sys
caffe_root = '/home/cong/caffe-master/'  # this file should be run from {caffe_root}/examples (otherwise change this line)
sys.path.insert(0, caffe_root + 'python')

import caffe
```

**Comment by Spadille** [comment]
Hi, I have the same problem, have you solved this?

**Comment by CongB** [comment]
@Spadille  I think as long as you have the correct makefile.config it should be good. I'm using anaconda and py2.7 so basically I just follow their instruction step by step...

**Comment by TanLingxiao** [comment]
http://stackoverflow.com/questions/9888289/checking-whether-a-converter-has-already-been-registered
