### ISSUE TITLE
./create_imagenet.sh wrong,while use my own dataset.

### ISSUE THREAD

**Issue by XiaXuehai** [BVLC/caffe#3854]
~/Code/caffe/myself$ ./create_imagenet.sh
Creating train lmdb...
I0321 12:14:15.972949  8659 convert_imageset.cpp:83] Shuffling data
I0321 12:14:16.644664  8659 convert_imageset.cpp:86] A total of 188 images.
F0321 12:14:16.644743  8659 db_lmdb.cpp:16] Check failed: mkdir(source.c_str(), 0744) == 0 (-1 vs. 0) mkdir myself/my_train_lmdbfailed
*** Check failure stack trace: ***
    @     0x7fedc91f9daa  (unknown)
    @     0x7fedc91f9ce4  (unknown)
    @     0x7fedc91f96e6  (unknown)
    @     0x7fedc91fc687  (unknown)
    @     0x7fedc96aea5e  caffe::db::LMDB::Open()
    @           0x40392d  main
    @     0x7fedc8205ec5  (unknown)
    @           0x404b0f  (unknown)
    @              (nil)  (unknown)
Aborted (core dumped)
Creating val lmdb...
I0321 12:14:16.792162  8665 convert_imageset.cpp:83] Shuffling data
I0321 12:14:17.446871  8665 convert_imageset.cpp:86] A total of 0 images.
F0321 12:14:17.446933  8665 db_lmdb.cpp:16] Check failed: mkdir(source.c_str(), 0744) == 0 (-1 vs. 0) mkdir myself/my_val_lmdbfailed
*** Check failure stack trace: ***
    @     0x7fabf319adaa  (unknown)
    @     0x7fabf319ace4  (unknown)
    @     0x7fabf319a6e6  (unknown)
    @     0x7fabf319d687  (unknown)
    @     0x7fabf364fa5e  caffe::db::LMDB::Open()
    @           0x40392d  main
    @     0x7fabf21a6ec5  (unknown)
    @           0x404b0f  (unknown)
    @              (nil)  (unknown)
Aborted (core dumped)
Done.

**Comment by malreddysid** [comment]
I think the error is occurring because of a name conflict.
I think you're trying to create an lmdb file with the name "my_train_lmdb". Are you sure that there is no folder in the directory which has the same name? If there is, delete/rename it and try again

**Comment by seanbell** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

**Comment by corecible** [comment]
my_train_lmdb is already exists

**Comment by malreddysid** [comment]
Delete it and try to make the lmdb file again.

**Comment by sayadyaghoobi** [comment]
i have the same problem, if anyone can help please note.

**Comment by JohnTian** [comment]
@malreddysid thanks very much.

**Comment by IvyGongoogle** [comment]
@malreddysid thank you very much.
