### ISSUE TITLE
caffe windows

### ISSUE THREAD

**Issue by aysegulucar2016** [BVLC/caffe#3857]
I installed caffe windows on Window 7.

I received the error:
Unable to start program
‘C:\Users\can\Documents\caffe-windows\caffe-windows\Build\x64\Release\libcaffe.lib'

What is problem?

**Comment by flmeng** [comment]
I installed caffe on Linux, and never intalled caffe on windows.

It seems that windows cannot find libcaffe.lib, and have you added the path of caffe to the system?

**Comment by aysegulucar2016** [comment]
No, I did not. Which folder should I add path ?
![image](https://cloud.githubusercontent.com/assets/16757934/13915538/084fef92-ef5e-11e5-80ee-2fed14dd44ea.png)

**Comment by seanbell** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

Closing as this is an installation question.

**Comment by seanbell** [comment]
@pavlejosipovic is windows officially supported by caffe now?

If so, maybe this should be updated: http://caffe.berkeleyvision.org/installation.html

**Comment by pavlejosipovic** [comment]
Yep, it's support from Windows branch.
I don't think I can edit the page you have mentioned.

**Comment by pavlejosipovic** [comment]
@seanbell can you edit the installation.html to point to windows branch?

**Comment by shelhamer** [comment]
@pavlejosipovic I suggest making a pull request with a documentation patch explaining the new windows branch. See [caffe/docs/installation.md](https://github.com/BVLC/caffe/blob/master/docs/installation.md).

While there is a windows branch, the usual rules about installation questions and such still apply so @seanbell was right to close the issue. Windows branch *development* can be discussed on github issues as overseen by @pavlejosipovic. Thanks.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
