### ISSUE TITLE
deploy.prototxt does not exist

### ISSUE THREAD

**Issue by monjoybme** [BVLC/caffe#3858]
Hi when I am running
model_dir = '../../models/bvlc_reference_caffenet/';
net_model = [model_dir 'deploy.prototxt'];
net_weights = [model_dir 'bvlc_reference_caffenet.caffemodel'];
net = caffe.Net(net_model, net_weights, phase);
I am getting bellow error.

deploy.prototxt does not exist

Error in caffe.get_net (line 21)
CHECK_FILE_EXIST(model_file);

Error in caffe.Net (line 31)
        self = caffe.get_net(varargin{:});

Please suggest.

**Comment by seanbell** [comment]
Well, does the file exist?  Can you verify that it exists in matlab before calling the caffe interface?

**Comment by monjoybme** [comment]
yes I found the file. Name is different. Thank you.
