### ISSUE TITLE
python3+ 与 python-dateutil1.5（仅支持python2+）

### ISSUE THREAD

**Issue by hawklucky** [BVLC/caffe#3860]
when i import caffe in python，this is the problem

File "/home/××/caffe-master/venv/lib/python3.5/site-packages/dateutil/rrule.py", line 55
    raise ValueError, "Can't create weekday with n == 0"

but the /python/require.txt declare the python-dateutil must >1.4 <2 version,
i don't sure if i change python-dateutil form ver1.5 to ver2.0, is it ok?

**Comment by mecab** [comment]
I had same issue, and fixed by installing python-dateutil ver2.0+ (actually 2.5.3).
Seems working well.

**Comment by achimnol** [comment]
Shouldn't this be open until we have a working requirements.txt for Python 3?

**Comment by jinfagang** [comment]
I am using Python3.5 come this issue too. @mecab  Just wanna ask why I can't find python-util-2.5.3, it seems python-util-2.0 is the latest version. It still have this problem when I upgrade to python-util-2.0.
```
sudo pip3 install --upgrade python-util
The directory '/home/chenqi-didi/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/chenqi-didi/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting python-util
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/4a/1e/627fabbc1e1fea0f8f73d8cbfb42ca98c6114f4b45235c405d2b7339fefa/python_util-2.0.0-py2.py3-none-any.whl
Collecting docopt (from python-util)
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/a2/55/8f8cab2afd404cf578136ef2cc5dfb50baa1761b68c9da1fb1e4eed343c9/docopt-0.6.2.tar.gz
Installing collected packages: docopt, python-util
  Running setup.py install for docopt ... done
Successfully installed docopt-0.6.2 python-util-2.0.0
```
