### ISSUE TITLE
SGD Update Kernel

### ISSUE THREAD

**Issue by linnanwang** [BVLC/caffe#3861]
It comes to my attention that the current release replaces the original L1 BLAS call with a new kernel function in ComputeUpdate of SGD.

I don't think this is optimal in terms of performance. It creates another layer of software complexity and no benefit for performance at all.

**Comment by seanbell** [comment]
This was benchmarked here: #3519; the new code was tested to be faster.  If the new code is slower for you, please provide a benchmark and numbers supporting your claim.

I personally think that the new kernels are much easier to read than the old BLAS calls.
