### ISSUE TITLE
Unable to make caffe on Fedora 20

### ISSUE THREAD

**Issue by ranflanflan** [BVLC/caffe#3870]
Hi! I try to make caffe on Fedora 20. When I did make all, I met these problems. I searched on the Internet but didn't find a solution. 

[ranflanflan@localhost caffe-master]$ make all
PROTOC src/caffe/proto/caffe.proto
CXX .build_release/src/caffe/proto/caffe.pb.cc
CXX src/caffe/data_reader.cpp
CXX src/caffe/data_transformer.cpp
CXX src/caffe/blob.cpp
CXX src/caffe/layer.cpp
CXX src/caffe/syncedmem.cpp
CXX src/caffe/util/im2col.cpp
CXX src/caffe/util/upgrade_proto.cpp
CXX src/caffe/util/io.cpp
CXX src/caffe/util/cudnn.cpp
CXX src/caffe/util/benchmark.cpp
CXX src/caffe/util/signal_handler.cpp
CXX src/caffe/util/hdf5.cpp
CXX src/caffe/util/math_functions.cpp
CXX src/caffe/util/db_lmdb.cpp
CXX src/caffe/util/blocking_queue.cpp
CXX src/caffe/util/insert_splits.cpp
CXX src/caffe/util/db.cpp
CXX src/caffe/util/db_leveldb.cpp
CXX src/caffe/common.cpp
CXX src/caffe/solvers/sgd_solver.cpp
CXX src/caffe/solvers/adagrad_solver.cpp
CXX src/caffe/solvers/nesterov_solver.cpp
CXX src/caffe/solvers/adam_solver.cpp
CXX src/caffe/solvers/rmsprop_solver.cpp
CXX src/caffe/solvers/adadelta_solver.cpp
CXX src/caffe/internal_thread.cpp
CXX src/caffe/net.cpp
CXX src/caffe/layer_factory.cpp
CXX src/caffe/parallel.cpp
CXX src/caffe/layers/image_data_layer.cpp
CXX src/caffe/layers/prelu_layer.cpp
CXX src/caffe/layers/accuracy_layer.cpp
CXX src/caffe/layers/hdf5_data_layer.cpp
CXX src/caffe/layers/silence_layer.cpp
CXX src/caffe/layers/cudnn_lrn_layer.cpp
CXX src/caffe/layers/dropout_layer.cpp
CXX src/caffe/layers/reshape_layer.cpp
CXX src/caffe/layers/loss_layer.cpp
CXX src/caffe/layers/slice_layer.cpp
CXX src/caffe/layers/mvn_layer.cpp
CXX src/caffe/layers/relu_layer.cpp
CXX src/caffe/layers/pooling_layer.cpp
CXX src/caffe/layers/batch_reindex_layer.cpp
CXX src/caffe/layers/exp_layer.cpp
CXX src/caffe/layers/cudnn_tanh_layer.cpp
CXX src/caffe/layers/sigmoid_layer.cpp
CXX src/caffe/layers/cudnn_conv_layer.cpp
CXX src/caffe/layers/hdf5_output_layer.cpp
CXX src/caffe/layers/window_data_layer.cpp
CXX src/caffe/layers/bnll_layer.cpp
CXX src/caffe/layers/split_layer.cpp
CXX src/caffe/layers/flatten_layer.cpp
CXX src/caffe/layers/im2col_layer.cpp
CXX src/caffe/layers/log_layer.cpp
CXX src/caffe/layers/softmax_loss_layer.cpp
CXX src/caffe/layers/cudnn_pooling_layer.cpp
CXX src/caffe/layers/memory_data_layer.cpp
CXX src/caffe/layers/neuron_layer.cpp
CXX src/caffe/layers/euclidean_loss_layer.cpp
CXX src/caffe/layers/absval_layer.cpp
CXX src/caffe/layers/data_layer.cpp
CXX src/caffe/layers/filter_layer.cpp
CXX src/caffe/layers/contrastive_loss_layer.cpp
CXX src/caffe/layers/bias_layer.cpp
CXX src/caffe/layers/base_data_layer.cpp
CXX src/caffe/layers/scale_layer.cpp
CXX src/caffe/layers/spp_layer.cpp
CXX src/caffe/layers/eltwise_layer.cpp
CXX src/caffe/layers/multinomial_logistic_loss_layer.cpp
CXX src/caffe/layers/power_layer.cpp
CXX src/caffe/layers/lrn_layer.cpp
CXX src/caffe/layers/embed_layer.cpp
CXX src/caffe/layers/crop_layer.cpp
CXX src/caffe/layers/sigmoid_cross_entropy_loss_layer.cpp
CXX src/caffe/layers/cudnn_softmax_layer.cpp
CXX src/caffe/layers/argmax_layer.cpp
CXX src/caffe/layers/cudnn_sigmoid_layer.cpp
CXX src/caffe/layers/cudnn_lcn_layer.cpp
CXX src/caffe/layers/softmax_layer.cpp
CXX src/caffe/layers/conv_layer.cpp
CXX src/caffe/layers/deconv_layer.cpp
CXX src/caffe/layers/dummy_data_layer.cpp
CXX src/caffe/layers/base_conv_layer.cpp
CXX src/caffe/layers/threshold_layer.cpp
CXX src/caffe/layers/inner_product_layer.cpp
CXX src/caffe/layers/elu_layer.cpp
CXX src/caffe/layers/tile_layer.cpp
CXX src/caffe/layers/reduction_layer.cpp
CXX src/caffe/layers/cudnn_relu_layer.cpp
CXX src/caffe/layers/tanh_layer.cpp
CXX src/caffe/layers/concat_layer.cpp
CXX src/caffe/layers/hinge_loss_layer.cpp
CXX src/caffe/layers/infogain_loss_layer.cpp
CXX src/caffe/layers/batch_norm_layer.cpp
CXX src/caffe/layers/input_layer.cpp
CXX src/caffe/solver.cpp
NVCC src/caffe/util/im2col.cu
NVCC src/caffe/util/math_functions.cu
NVCC src/caffe/solvers/rmsprop_solver.cu
NVCC src/caffe/solvers/sgd_solver.cu
NVCC src/caffe/solvers/adagrad_solver.cu
NVCC src/caffe/solvers/adadelta_solver.cu
NVCC src/caffe/solvers/adam_solver.cu
NVCC src/caffe/solvers/nesterov_solver.cu
NVCC src/caffe/layers/bnll_layer.cu
NVCC src/caffe/layers/tile_layer.cu
NVCC src/caffe/layers/cudnn_sigmoid_layer.cu
NVCC src/caffe/layers/im2col_layer.cu
NVCC src/caffe/layers/tanh_layer.cu
NVCC src/caffe/layers/hdf5_output_layer.cu
NVCC src/caffe/layers/cudnn_softmax_layer.cu
NVCC src/caffe/layers/batch_norm_layer.cu
NVCC src/caffe/layers/mvn_layer.cu
NVCC src/caffe/layers/absval_layer.cu
NVCC src/caffe/layers/power_layer.cu
NVCC src/caffe/layers/base_data_layer.cu
NVCC src/caffe/layers/softmax_layer.cu
NVCC src/caffe/layers/cudnn_lrn_layer.cu
NVCC src/caffe/layers/cudnn_pooling_layer.cu
NVCC src/caffe/layers/prelu_layer.cu
NVCC src/caffe/layers/bias_layer.cu
NVCC src/caffe/layers/eltwise_layer.cu
NVCC src/caffe/layers/relu_layer.cu
NVCC src/caffe/layers/hdf5_data_layer.cu
NVCC src/caffe/layers/elu_layer.cu
NVCC src/caffe/layers/conv_layer.cu
NVCC src/caffe/layers/log_layer.cu
NVCC src/caffe/layers/deconv_layer.cu
NVCC src/caffe/layers/concat_layer.cu
NVCC src/caffe/layers/euclidean_loss_layer.cu
NVCC src/caffe/layers/inner_product_layer.cu
NVCC src/caffe/layers/dropout_layer.cu
NVCC src/caffe/layers/lrn_layer.cu
NVCC src/caffe/layers/slice_layer.cu
NVCC src/caffe/layers/reduction_layer.cu
NVCC src/caffe/layers/sigmoid_layer.cu
NVCC src/caffe/layers/batch_reindex_layer.cu
NVCC src/caffe/layers/softmax_loss_layer.cu
NVCC src/caffe/layers/cudnn_relu_layer.cu
NVCC src/caffe/layers/cudnn_conv_layer.cu
NVCC src/caffe/layers/crop_layer.cu
NVCC src/caffe/layers/threshold_layer.cu
NVCC src/caffe/layers/split_layer.cu
NVCC src/caffe/layers/filter_layer.cu
NVCC src/caffe/layers/pooling_layer.cu
NVCC src/caffe/layers/embed_layer.cu
NVCC src/caffe/layers/silence_layer.cu
NVCC src/caffe/layers/contrastive_loss_layer.cu
NVCC src/caffe/layers/cudnn_tanh_layer.cu
NVCC src/caffe/layers/exp_layer.cu
NVCC src/caffe/layers/scale_layer.cu
NVCC src/caffe/layers/cudnn_lcn_layer.cu
NVCC src/caffe/layers/sigmoid_cross_entropy_loss_layer.cu
AR -o .build_release/lib/libcaffe.a
LD -o .build_release/lib/libcaffe.so.1.0.0-rc3
/bin/ld: skipping incompatible /usr/lib/libm.so when searching for -lm
/bin/ld: skipping incompatible /usr/lib/libm.so when searching for -lm
/bin/ld: skipping incompatible /usr/lib/libpthread.so when searching for -lpthread
/bin/ld: skipping incompatible /usr/lib/libpthread.so when searching for -lpthread
/bin/ld: skipping incompatible /usr/lib/libc.so when searching for -lc
/bin/ld: skipping incompatible /usr/lib/libc.so when searching for -lc
CXX tools/test_net.cpp
CXX/LD -o .build_release/tools/test_net.bin
/bin/ld: skipping incompatible /usr/lib/libm.so when searching for -lm
/bin/ld: skipping incompatible /usr/lib/libm.so when searching for -lm
/bin/ld: skipping incompatible /usr/lib/libpthread.so when searching for -lpthread
/bin/ld: skipping incompatible /usr/lib/libpthread.so when searching for -lpthread
/bin/ld: skipping incompatible /usr/lib/libc.so when searching for -lc
/bin/ld: skipping incompatible /usr/lib/libc.so when searching for -lc
CXX tools/caffe.cpp
tools/caffe.cpp: In function ‘int main(int, char**)’:
tools/caffe.cpp:393:3: error: ‘SetVersionString’ is not a member of ‘gflags’
   gflags::SetVersionString(AS_STRING(CAFFE_VERSION));
   ^
tools/caffe.cpp: In function ‘caffe::SolverAction::Enum GetRequestedAction(const string&)’:
tools/caffe.cpp:151:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
make: *** [.build_release/tools/caffe.o] Error 1

**Comment by CDLuminate** [comment]
Did you have all the compile dependencies satisfied?
you may want to try cmake, which will also check that for you.
```
$ mkdir build; cd build
$ cmake ..
$ make
```

**Comment by ranflanflan** [comment]
@CDLuminate Thank you very much for your suggestion. I can now make caffe successfully.

**Comment by whatseob** [comment]
I got exactly the same problem. How did you solve this?

**Comment by YihangLou** [comment]
@ranflanflan Hi, Could you share how you fix this problem?

**Comment by ranflanflan** [comment]
@whatseob @YihangLou 

I compared the content of tools/caffe.cpp with a previous version of caffe that my friend used which could be compiled successfully, and the difference is that the successful version doesn't have this line in function ‘int main(int, char*)': 

gflags::SetVersionString(AS_STRING(CAFFE_VERSION)); 

I just deleted this line and then I could make caffe successfully.

**Comment by YihangLou** [comment]
@ranflanflan Thanks for your reply！ I have solved this problem by updating gflag's version and some other dependency packages~

**Comment by codingsmallfish** [comment]
@YihangLou Hi, can you tell me how to update gflag's version?
Thank you!

**Comment by codingsmallfish** [comment]
@ranflanflan Hi, is there any problem emerging after you made caffe by deleting this line? I'm not sure what the meaning of this line is.

**Comment by RenFeiTemp** [comment]
@ranflanflan  /bin/ld: skipping incompatible /usr/lib/libm.so when searching for -lm .How did you solve this?
