### ISSUE TITLE
How to prepare the dataset for siamese net.

### ISSUE THREAD

**Issue by cheer37** [BVLC/caffe#3873]
I am trying to test the siamese net.
I think there are two ways to implement it.
1. softmax + contrastive in one time.
2. softmax is first, then contrastive, seperately.

I am thinking about the first method, but can't figure out how to prepare the dataset to feed two siamese nets.
I imagine i should divide the dataset to two parts, so i am going to divide the data about one person to two parts which they have same images. through all people.
After that, i should arrange them properly, so that the number of intra pairs and extra pairs are the nearly same, but i can't find out the way to do.
Please, guide me.
Thanks.

**Comment by naibaf7** [comment]
Please ask questions like this on the mailing list.  From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
