### ISSUE TITLE
How to use MemoryData layer on GPU?

### ISSUE THREAD

**Issue by b2220333** [BVLC/caffe#3874]
I can use the following sam_finetuned_GoogLeNet_deploy_memorylayer.prototxt on CPU test.
[sam_finetuned_GoogLeNet_deploy_memorylayer.prototxt.txt](https://github.com/BVLC/caffe/files/184309/sam_finetuned_GoogLeNet_deploy_memorylayer.prototxt.txt)
But when I set Caffe::set_mode(Caffe::GPU);
It will suddenly terminate at Creating layer data.
What's happened and How to solve it?
Thank you~
Here is the log:
[MemoryLayerFail_log.txt](https://github.com/BVLC/caffe/files/184311/MemoryLayerFail_log.txt)

**Comment by seanbell** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> When reporting a bug, it's most helpful to provide the following information, where applicable:
> 
> * What steps reproduce the bug?
> * Can you reproduce the bug using the latest [master](https://github.com/BVLC/caffe/tree/master), compiled with the `DEBUG` make option?
> * What hardware and operating system/distribution are you running?
> * If the bug is a crash, provide the backtrace (usually printed by Caffe; always obtainable with `gdb`).

**Comment by b2220333** [comment]
What steps reproduce the bug?
=>g_caffe_net =new Net<float>(model_path, caffe::TEST);
Can you reproduce the bug using the latest master, compiled with the DEBUG make option?
=>I try to type:
git pull;
make --debug
make pycaffe --debug
make distribute --debug

What hardware and operating system/distribution are you running?
=> I use ubuntu 12.04 64 bits.
If the bug is a crash, provide the backtrace (usually printed by Caffe; always obtainable with gdb).
=>I don't know how to attach gdb with rosrun in ROS(Robot Operating System).
I attach the output list after re-compile the latest caffe.
[debug_caffe_gpgpu.txt](https://github.com/BVLC/caffe/files/189606/debug_caffe_gpgpu.txt)

**Comment by shelhamer** [comment]
Closing according to #5528.
