### ISSUE TITLE
Caffe-windows

### ISSUE THREAD

**Issue by aysegulucar2016** [BVLC/caffe#3879]
In caffe windows,
Remark says:

After you have built solution with Matlab support, in order to use it you have to:

add the generated matcaffe folder to Matlab search path, and
add <caffe_root>\Build\x64\Release to your system path.

However there are no build folder.
CAn I use the path: 
C:\caffe-windows\caffe-windows\windows\libcaffe\x64\Release ?

**Comment by aysegulucar2016** [comment]
![image](https://cloud.githubusercontent.com/assets/16757934/13978894/28e7d28a-f0dd-11e5-9842-af7d0dc49dcd.png)

**Comment by pavlejosipovic** [comment]
From the screenshot it seems that your solution is not building due to cuDNN. 
Please double check guidelines for configuring cuDNN https://github.com/bvlc/caffe/tree/undefined#cudnn

You should expect build output at \<caffe root\>\Build\x64\Release, which in your case should be C:\caffe-windows\caffe-windows\Build\x64\Release

Also, from the screen shot you have shared, it seems that you are trying to run libcaffe.lib, which is not an executable.

**Comment by aysegulucar2016** [comment]
Sory I am new. The question maybe simple.
I set cudapath as foollows:
 <CuDnnPath>C:\cudnn-7.0-win-x64-v4.0-prod\cuda</CuDnnPath>
is it correct?
In addition my nvdia is gtx 550 Ti.

**Comment by pavlejosipovic** [comment]
GTX 550Ti supports CUDA compute capability 2.1 https://en.wikipedia.org/wiki/CUDA
And minimum required is 3.5.

You can use Caffe in CPU mode.
Follow the guide here to compile CPU only version https://github.com/BVLC/caffe/blob/windows/README.md#cuda

**Comment by aysegulucar2016** [comment]
Many thanks for answers.

**Comment by aysegulucar2016** [comment]
![image](https://cloud.githubusercontent.com/assets/16757934/13994523/dfe4626e-f12d-11e5-8257-263907d67bf6.png)
What is problem?
Could you please answer ? Many thanks

**Comment by pavlejosipovic** [comment]
You are still trying to run libcaffe.lib, which as I've already mentioned, is not an executable.

**Comment by aysegulucar2016** [comment]
Now, I succeed it. I think,I learnt to run it. Many thanks for your answer.

**Comment by aysegulucar2016** [comment]
Could you please recommend a document to exactly learn caffe?

**Comment by pavlejosipovic** [comment]
you can start looking here http://caffe.berkeleyvision.org/
If we have resolved the original issue please close it.
