### ISSUE TITLE
How can I understand a deconvolution layer

### ISSUE THREAD

**Issue by ginobilinie** [BVLC/caffe#3882]
Hi,

I have read codes in caffe about deconvolution layer. But I'm confused about the codes. In convolutional layer, it is easy to understand, while it is difficult for me to understand the deconvolution layer, I cannot get a formula how to do deconvolution from the codes. Can someone help me?

Thanks.

**Comment by naibaf7** [comment]
In the easiest case (stride = 1), deconvolution is the same as a full convolution with the weights flipped on the axis.
See:
http://www.johnloomis.org/ece563/notes/filter/conv/convolution.html

The standard convolution would be a "valid" convolution in the illustration above. As the weights are machine learned, they don't really need to be flipped on the axis / inverted.

**Comment by ginobilinie** [comment]
@naibaf7 

Thank you.  if the stride is larger than 1, then for deconvolution, what's the situation? According the the FCN paper, "Upsampling is backwards strided convolution", I do not understand it well.

**Comment by ginobilinie** [comment]
@naibaf7 

I got it. Thank you.

**Comment by seanbell** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
