### ISSUE TITLE
build error in caffe-windows

### ISSUE THREAD

**Issue by Mushroom-Head** [BVLC/caffe#3886]
I'm facing build error in caffe-windows. VS2013 shows fatal error LNK1181 'cannot open libcaffe.lib'. I'd like to know how to fix this issue.

**Comment by mnidza** [comment]
@Mushroom-Head Please make sure that you have followed all the instructions exactly, including [CuDNN setup](https://github.com/BVLC/caffe/blob/windows/README.md#cudnn). If you still cannot build, post the entire build log from Visual Studio here.

**Comment by Mushroom-Head** [comment]
I changed UseCuDNN  to  false  in the property file. But, same error is still shown.
Build log is below. Sorry, the messages are Japanese.

1>------ ビルド開始: プロジェクト:caffe, 構成:Release x64 ------
1>  caffe.cpp
1>LINK : fatal error LNK1181: 入力ファイル 'libcaffe.lib' を開けません。
2>------ ビルド開始: プロジェクト:compute_image_mean, 構成:Release x64 ------
3>------ ビルド開始: プロジェクト:convert_imageset, 構成:Release x64 ------
4>------ ビルド開始: プロジェクト:extract_features, 構成:Release x64 ------
5>------ ビルド開始: プロジェクト:test_all, 構成:Release x64 ------
6>------ ビルド開始: プロジェクト:pycaffe, 構成:Release x64 ------
7>------ ビルド開始: プロジェクト:matcaffe, 構成:Release x64 ------
7>  Skipping project matcaffe, Matlab support is not enabled in CommonSettings.props.
6>  PythonPreBuild.cmd : Create output directories for python scripts.
6>  PythonPreBuild.cmd : Create dummy __init__.py file
6>  PythonPreBuild.cmd : Generating src\caffe\proto\caffe.pb.h with python bindings
2>  compute_image_mean.cpp
4>  extract_features.cpp
3>  convert_imageset.cpp
6>  _caffe.cpp
5>  test_accuracy_layer.cpp
5>  test_argmax_layer.cpp
5>  test_batch_norm_layer.cpp
5>  test_batch_reindex_layer.cpp
5>  test_benchmark.cpp
5>  test_bias_layer.cpp
5>  test_blob.cpp
5>  test_caffe_main.cpp
5>  test_common.cpp
5>  test_concat_layer.cpp
5>  test_contrastive_loss_layer.cpp
5>  test_convolution_layer.cpp
5>  test_crop_layer.cpp
5>  test_data_layer.cpp
5>  test_data_transformer.cpp
5>  test_db.cpp
5>  test_deconvolution_layer.cpp
5>  test_dummy_data_layer.cpp
5>  test_eltwise_layer.cpp
5>  test_embed_layer.cpp
5>  test_euclidean_loss_layer.cpp
5>  test_filler.cpp
5>  test_filter_layer.cpp
5>  test_flatten_layer.cpp
5>  test_gradient_based_solver.cpp
5>  test_hdf5data_layer.cpp
5>  test_hdf5_output_layer.cpp
5>  test_hinge_loss_layer.cpp
5>  test_im2col_layer.cpp
5>  test_image_data_layer.cpp
5>  test_infogain_loss_layer.cpp
5>  test_inner_product_layer.cpp
2>LINK : fatal error LNK1181: 入力ファイル 'libcaffe.lib' を開けません。
3>LINK : fatal error LNK1181: 入力ファイル 'libcaffe.lib' を開けません。
4>LINK : fatal error LNK1181: 入力ファイル 'libcaffe.lib' を開けません。
5>  test_internal_thread.cpp
5>  test_io.cpp
5>  test_layer_factory.cpp
5>  test_lrn_layer.cpp
5>  test_math_functions.cpp
5>  test_maxpool_dropout_layers.cpp
5>  test_memory_data_layer.cpp
5>  test_multinomial_logistic_loss_layer.cpp
5>  test_mvn_layer.cpp
5>  test_net.cpp
5>  test_neuron_layer.cpp
5>  test_platform.cpp
5>  test_pooling_layer.cpp
5>  test_power_layer.cpp
5>  test_protobuf.cpp
5>  test_random_number_generator.cpp
5>  test_reduction_layer.cpp
5>  test_reshape_layer.cpp
5>  test_scale_layer.cpp
5>  test_sigmoid_cross_entropy_loss_layer.cpp
5>  test_slice_layer.cpp
5>  test_softmax_layer.cpp
5>  test_softmax_with_loss_layer.cpp
5>  test_solver.cpp
5>  test_solver_factory.cpp
5>  test_split_layer.cpp
5>  test_spp_layer.cpp
5>  test_stochastic_pooling.cpp
5>  test_syncedmem.cpp
5>  test_tanh_layer.cpp
5>  test_threshold_layer.cpp
5>  test_tile_layer.cpp
5>  test_upgrade_proto.cpp
5>  test_util_blas.cpp
5>  gtest-all.cpp
5>LINK : fatal error LNK1181: 入力ファイル 'libcaffe.lib' を開けません。
6>LINK : fatal error LNK1181: 入力ファイル 'libcaffe.lib' を開けません。
========== ビルド: 1 正常終了、6 失敗、0 更新不要、0 スキップ ==========

**Comment by Mushroom-Head** [comment]
Where is libcaffe.lib?

**Comment by zizhaozhang** [comment]
If you can not find libcaffe.lib. It is usually the compiling error of
other parts. So the libcaffe.lib is not generated successfully.

On Thu, Mar 24, 2016 at 10:57 PM, Mushroom-Head <notifications@github.com>
wrote:

> Where is libcaffe.lib?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/BVLC/caffe/issues/3886#issuecomment-201117384>
>



-- 
Best Regards,
Zizhao

**Comment by mnidza** [comment]
@Mushroom-Head `libcaffe.lib` should be generated by building the `libcaffe` project from the same solution. Is `libcaffe` project present in your solution at all? You might have excluded it accidentally, or it failed to load for some reason. Can you try building `libcaffe` separately?

**Comment by Mushroom-Head** [comment]
Thanks.
I don't know why, but I could build project.

**Comment by mnidza** [comment]
@Mushroom-Head Can you build the whole solution now? Please close this issue if you think it's resolved.

**Comment by Scorpionier** [comment]
i have the same problem.HELP!
