### ISSUE TITLE
clang: error: linker command failed with exit code 1

### ISSUE THREAD

**Issue by teachertian** [BVLC/caffe#3889]
I got an error message when I made caffe in OSX 10.11.3

> No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.
/bin/sh: line 0: [: -gt: unary operator expected
LD -o .build_release/lib/libcaffe.so.1.0.0-rc3
clang: warning: argument unused during compilation: '-pthread'
ld: framework not found vecLib
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [.build_release/lib/libcaffe.so.1.0.0-rc3] Error 1

Does anybody know how to solve the issue?Thanks in advance

**Comment by seanbell** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> When reporting a bug, it's most helpful to provide the following information, where applicable:
> 
> * What steps reproduce the bug?
> * Can you reproduce the bug using the latest [master](https://github.com/BVLC/caffe/tree/master), compiled with the `DEBUG` make option?
> * What hardware and operating system/distribution are you running?
> * If the bug is a crash, provide the backtrace (usually printed by Caffe; always obtainable with `gdb`).

**Comment by mmocco** [comment]
I am have the same issue. After running make I get 

` Linking CXX shared library ../../lib/libcaffe.dylib
ld: framework not found vecLib
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [lib/libcaffe.1.0.0-rc3.dylib] Error 1
make[1]: *** [src/caffe/CMakeFiles/caffe.dir/all] Error 2
make: *** [all] Error 2`

I was using openblas but even after I reinstalled and made sure to specify the path in .config file kept getting the error.  
`/caffe-master/include/caffe/util/mkl_alternate.hpp:11:10: fatal error:
      'cblas.h' file not found
#include <cblas.h>`

I eventually switched to using atlas which resulted with the ld: framework not found vecLib
 error

**Comment by teachertian** [comment]
I just solve the problem,you can find the way in https://github.com/BVLC/caffe/issues/1212

**Comment by PeterJiangwy** [comment]
@teachertian , could you show how to solve this problem in detail? In #1212 , I couldn't
find the solution.

**Comment by teachertian** [comment]
@PeterJiangwy I am sorry to say that I have forgotten how to solve it, it has been so long. I hope you can solve this problem soon.
