### ISSUE TITLE
 "caffe.LayerParameter" has no field named "input_param".

### ISSUE THREAD

**Issue by birolkuyumcu** [BVLC/caffe#3895]
when using deploy.prototxt 
after this change https://github.com/BVLC/caffe/commit/2cc3844cb2a4a72de10d321781dc8f994bef95c7
[examples] switch examples + models to Input layers 
rising  "caffe.LayerParameter" has no field named "input_param" error
when using old version of deploy.prototxt  there is no problem

**Comment by seanbell** [comment]
Are you using the newest version of caffe?  This was added recently to `master`.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
