### ISSUE TITLE
Caffe-windows/about cmake

### ISSUE THREAD

**Issue by aysegulucar2016** [BVLC/caffe#3897]
![image](https://cloud.githubusercontent.com/assets/16757934/14065145/69a1080e-f426-11e5-9086-cd900088e6c0.png)

I am trying to use cmake for examples in caffe. How can I use it on windows?

**Comment by pavlejosipovic** [comment]
CMake currently doesn't work for Windows, in windows branch you can find Caffe.sln which we are using to compile for Windows.
Currently it doesn't contain all of the tools/example that are available on Linux.
We are working on enabling some of them.
You can find a work in progress here https://github.com/Microsoft/caffe/tree/win_tools_fix
Here with Caffe.sln you will be able to get more tools, and you could use Cygwin to run existing shell scripts in examples with tools build for windows.
Probably you will have to adjust the scripts slightly to adjust for different output build paths, but is should be doable.

**Comment by aysegulucar2016** [comment]
Thank very much for detailed answer
