### ISSUE TITLE
Hello friend,I have a problem.

### ISSUE THREAD

**Issue by hanxingyixue** [BVLC/caffe#3898]
where I run the code of captcha_recognition,it have a proble.

I will appreciate it if you can help me work it out! Thank you!

Error: TRAIN_DATA_ROOT is not a path to a directory.

log.txt

Starting with 01-3_layers-1000_initial_images-correct_mostuncertain in mode correct_mostuncertain

Creating final testing images...
X-Powered-By: PHP/5.5.9-1ubuntu4.14
Content-type: text/html

Deleting old files...
0 Training Samples have been created...(0 skipped duplicates)
1000 Training Samples have been created...(0 skipped duplicates)
2000 Training Samples have been created...

Creating inital training images...
X-Powered-By: PHP/5.5.9-1ubuntu4.14
Content-type: text/html

Deleting old files...
0 Training Samples have been created...(0 skipped duplicates)
1000 Training Samples have been created...(0 skipped duplicates)
2000 Training Samples have been created...(0 skipped duplicates)
3000 Training Samples have been created...(0 skipped duplicates)
4000 Training Samples have been created...(0 skipped duplicates)
5000 Training Samples have been created...(0 skipped duplicates)
6000 Training Samples have been created...(0 skipped duplicates)
7000 Training Samples have been created...(0 skipped duplicates)
8000 Training Samples have been created...(0 skipped duplicates)
9000 Training Samples have been created...(0 skipped duplicates)
10000 Training Samples have been created...

Creating lmdb database in iteration 50000...
Error: TRAIN_DATA_ROOT is not a path to a directory.

Training network...

... Finished traing.

Creating learning images...
X-Powered-By: PHP/5.5.9-1ubuntu4.14
Content-type: text/html

Deleting old files...
0 Training Samples have been created...(0 skipped duplicates)
1000 Training Samples have been created...(0 skipped duplicates)
2000 Training Samples have been created...(0 skipped duplicates)
3000 Training Samples have been created...(0 skipped duplicates)
4000 Training Samples have been created...(0 skipped duplicates)
5000 Training Samples have been created...(0 skipped duplicates)
6000 Training Samples have been created...(0 skipped duplicates)
7000 Training Samples have been created...(0 skipped duplicates)
8000 Training Samples have been created...(0 skipped duplicates)
9000 Training Samples have been created...(0 skipped duplicates)
10000 Training Samples have been created...(0 skipped duplicates)
11000 Training Samples have been created...(0 skipped duplicates)
12000 Training Samples have been created...(0 skipped duplicates)
13000 Training Samples have been created...(0 skipped duplicates)
14000 Training Samples have been created...(1 skipped duplicates)
15000 Training Samples have been created...(0 skipped duplicates)
16000 Training Samples have been created...(1 skipped duplicates)
17000 Training Samples have been created...(0 skipped duplicates)
18000 Training Samples have been created...(0 skipped duplicates)
19000 Training Samples have been created...(0 skipped duplicates)
20000 Training Samples have been created...(0 skipped duplicates)
21000 Training Samples have been created...(0 skipped duplicates)
22000 Training Samples have been created...(0 skipped duplicates)
23000 Training Samples have been created...(1 skipped duplicates)
24000 Training Samples have been created...(0 skipped duplicates)
25000 Training Samples have been created...(0 skipped duplicates)
26000 Training Samples have been created...(0 skipped duplicates)
27000 Training Samples have been created...(0 skipped duplicates)
28000 Training Samples have been created...(0 skipped duplicates)
29000 Training Samples have been created...(0 skipped duplicates)
30000 Training Samples have been created...(0 skipped duplicates)
31000 Training Samples have been created...(0 skipped duplicates)
32000 Training Samples have been created...(1 skipped duplicates)
33000 Training Samples have been created...(0 skipped duplicates)
34000 Training Samples have been created...(0 skipped duplicates)
35000 Training Samples have been created...(0 skipped duplicates)
36000 Training Samples have been created...(1 skipped duplicates)
37000 Training Samples have been created...(0 skipped duplicates)
38000 Training Samples have been created...(0 skipped duplicates)
39000 Training Samples have been created...(0 skipped duplicates)
40000 Training Samples have been created...(0 skipped duplicates)
41000 Training Samples have been created...(1 skipped duplicates)
42000 Training Samples have been created...(0 skipped duplicates)
43000 Training Samples have been created...(0 skipped duplicates)
44000 Training Samples have been created...(0 skipped duplicates)
45000 Training Samples have been created...(0 skipped duplicates)
46000 Training Samples have been created...(0 skipped duplicates)
47000 Training Samples have been created...(1 skipped duplicates)
48000 Training Samples have been created...(0 skipped duplicates)
49000 Training Samples have been created...(0 skipped duplicates)
50000 Training Samples have been created...(0 skipped duplicates)
51000 Training Samples have been created...(1 skipped duplicates)
52000 Training Samples have been created...(1 skipped duplicates)
53000 Training Samples have been created...(1 skipped duplicates)
54000 Training Samples have been created...(1 skipped duplicates)
55000 Training Samples have been created...(1 skipped duplicates)
56000 Training Samples have been created...(0 skipped duplicates)
57000 Training Samples have been created...(0 skipped duplicates)
58000 Training Samples have been created...(1 skipped duplicates)
59000 Training Samples have been created...(0 skipped duplicates)
60000 Training Samples have been created...(0 skipped duplicates)
61000 Training Samples have been created...(0 skipped duplicates)
62000 Training Samples have been created...(0 skipped duplicates)
63000 Training Samples have been created...(1 skipped duplicates)
64000 Training Samples have been created...(0 skipped duplicates)
65000 Training Samples have been created...(0 skipped duplicates)
66000 Training Samples have been created...(0 skipped duplicates)
67000 Training Samples have been created...(2 skipped duplicates)
68000 Training Samples have been created...(0 skipped duplicates)
69000 Training Samples have been created...(0 skipped duplicates)
70000 Training Samples have been created...(1 skipped duplicates)
71000 Training Samples have been created...(0 skipped duplicates)
72000 Training Samples have been created...(0 skipped duplicates)
73000 Training Samples have been created...(1 skipped duplicates)
74000 Training Samples have been created...(1 skipped duplicates)
75000 Training Samples have been created...(0 skipped duplicates)
76000 Training Samples have been created...(0 skipped duplicates)
77000 Training Samples have been created...(0 skipped duplicates)
78000 Training Samples have been created...(0 skipped duplicates)
79000 Training Samples have been created...(1 skipped duplicates)
80000 Training Samples have been created...(2 skipped duplicates)
81000 Training Samples have been created...(0 skipped duplicates)
82000 Training Samples have been created...(0 skipped duplicates)
83000 Training Samples have been created...(0 skipped duplicates)
84000 Training Samples have been created...(0 skipped duplicates)
85000 Training Samples have been created...(1 skipped duplicates)
86000 Training Samples have been created...(3 skipped duplicates)
87000 Training Samples have been created...(1 skipped duplicates)
88000 Training Samples have been created...(1 skipped duplicates)
89000 Training Samples have been created...(0 skipped duplicates)
90000 Training Samples have been created...(0 skipped duplicates)
91000 Training Samples have been created...(1 skipped duplicates)
92000 Training Samples have been created...(1 skipped duplicates)
93000 Training Samples have been created...(0 skipped duplicates)
94000 Training Samples have been created...(2 skipped duplicates)
95000 Training Samples have been created...(0 skipped duplicates)
96000 Training Samples have been created...(0 skipped duplicates)
97000 Training Samples have been created...(0 skipped duplicates)
98000 Training Samples have been created...(1 skipped duplicates)
99000 Training Samples have been created...(0 skipped duplicates)
100000 Training Samples have been created...

Testing network after 50000 iterations (and creating new training images for next iteration)...

================================================================================

Creating lmdb database in iteration 75000...
Error: TRAIN_DATA_ROOT is not a path to a directory.

Training network...

... Finished traing.

Creating learning images...
X-Powered-By: PHP/5.5.9-1ubuntu4.14
Content-type: text/html

Deleting old files...
0 Training Samples have been created...(0 skipped duplicates)
1000 Training Samples have been created...(0 skipped duplicates)
2000 Training Samples have been created...(0 skipped duplicates)
3000 Training Samples have been created...(0 skipped duplicates)
4000 Training Samples have been created...(0 skipped duplicates)
5000 Training Samples have been created...(1 skipped duplicates)
6000 Training Samples have been created...(0 skipped duplicates)
7000 Training Samples have been created...(0 skipped duplicates)
8000 Training Samples have been created...(0 skipped duplicates)
9000 Training Samples have been created...(0 skipped duplicates)
10000 Training Samples have been created...(0 skipped duplicates)
11000 Training Samples have been created...(0 skipped duplicates)
12000 Training Samples have been created...(0 skipped duplicates)
13000 Training Samples have been created...(0 skipped duplicates)
14000 Training Samples have been created...(0 skipped duplicates)
15000 Training Samples have been created...(0 skipped duplicates)
16000 Training Samples have been created...(0 skipped duplicates)
17000 Training Samples have been created...(0 skipped duplicates)
18000 Training Samples have been created...(0 skipped duplicates)
19000 Training Samples have been created...(0 skipped duplicates)
20000 Training Samples have been created...(0 skipped duplicates)
21000 Training Samples have been created...(0 skipped duplicates)
22000 Training Samples have been created...(0 skipped duplicates)
23000 Training Samples have been created...(0 skipped duplicates)
24000 Training Samples have been created...(0 skipped duplicates)
25000 Training Samples have been created...(0 skipped duplicates)
26000 Training Samples have been created...(0 skipped duplicates)
27000 Training Samples have been created...(0 skipped duplicates)
28000 Training Samples have been created...(0 skipped duplicates)
29000 Training Samples have been created...(0 skipped duplicates)
30000 Training Samples have been created...(0 skipped duplicates)
31000 Training Samples have been created...(0 skipped duplicates)
32000 Training Samples have been created...(0 skipped duplicates)
33000 Training Samples have been created...(0 skipped duplicates)
34000 Training Samples have been created...(1 skipped duplicates)
35000 Training Samples have been created...(0 skipped duplicates)
36000 Training Samples have been created...(1 skipped duplicates)
37000 Training Samples have been created...(0 skipped duplicates)
38000 Training Samples have been created...(0 skipped duplicates)
39000 Training Samples have been created...(0 skipped duplicates)
40000 Training Samples have been created...(0 skipped duplicates)
41000 Training Samples have been created...(0 skipped duplicates)
42000 Training Samples have been created...(1 skipped duplicates)
43000 Training Samples have been created...(0 skipped duplicates)
44000 Training Samples have been created...(2 skipped duplicates)
45000 Training Samples have been created...(1 skipped duplicates)
46000 Training Samples have been created...(1 skipped duplicates)
47000 Training Samples have been created...(0 skipped duplicates)
48000 Training Samples have been created...(0 skipped duplicates)
49000 Training Samples have been created...(0 skipped duplicates)
50000 Training Samples have been created...(0 skipped duplicates)
51000 Training Samples have been created...(0 skipped duplicates)
52000 Training Samples have been created...(0 skipped duplicates)
53000 Training Samples have been created...(1 skipped duplicates)
54000 Training Samples have been created...(1 skipped duplicates)
55000 Training Samples have been created...(0 skipped duplicates)
56000 Training Samples have been created...(2 skipped duplicates)
57000 Training Samples have been created...(1 skipped duplicates)
58000 Training Samples have been created...(0 skipped duplicates)
59000 Training Samples have been created...(1 skipped duplicates)
60000 Training Samples have been created...(0 skipped duplicates)
61000 Training Samples have been created...(0 skipped duplicates)
62000 Training Samples have been created...(2 skipped duplicates)
63000 Training Samples have been created...(0 skipped duplicates)
64000 Training Samples have been created...(1 skipped duplicates)
65000 Training Samples have been created...(0 skipped duplicates)
66000 Training Samples have been created...(1 skipped duplicates)
67000 Training Samples have been created...(0 skipped duplicates)
68000 Training Samples have been created...(0 skipped duplicates)
69000 Training Samples have been created...(0 skipped duplicates)
70000 Training Samples have been created...(0 skipped duplicates)
71000 Training Samples have been created...(0 skipped duplicates)
72000 Training Samples have been created...(1 skipped duplicates)
73000 Training Samples have been created...(0 skipped duplicates)
74000 Training Samples have been created...(0 skipped duplicates)
75000 Training Samples have been created...(0 skipped duplicates)
76000 Training Samples have been created...(0 skipped duplicates)
77000 Training Samples have been created...(0 skipped duplicates)
78000 Training Samples have been created...(1 skipped duplicates)
79000 Training Samples have been created...(0 skipped duplicates)
80000 Training Samples have been created...(1 skipped duplicates)
81000 Training Samples have been created...(3 skipped duplicates)
82000 Training Samples have been created...(1 skipped duplicates)
83000 Training Samples have been created...(1 skipped duplicates)
84000 Training Samples have been created...(0 skipped duplicates)
85000 Training Samples have been created...(1 skipped duplicates)
86000 Training Samples have been created...(0 skipped duplicates)
87000 Training Samples have been created...(1 skipped duplicates)
88000 Training Samples have been created...(0 skipped duplicates)
89000 Training Samples have been created...(0 skipped duplicates)
90000 Training Samples have been created...(1 skipped duplicates)
91000 Training Samples have been created...(0 skipped duplicates)
92000 Training Samples have been created...(1 skipped duplicates)
93000 Training Samples have been created...(0 skipped duplicates)
94000 Training Samples have been created...(0 skipped duplicates)
95000 Training Samples have been created...(0 skipped duplicates)
96000 Training Samples have been created...(0 skipped duplicates)
97000 Training Samples have been created...(0 skipped duplicates)
98000 Training Samples have been created...(3 skipped duplicates)
99000 Training Samples have been created...(1 skipped duplicates)
100000 Training Samples have been created...

Testing network after 75000 iterations (and creating new training images for next iteration)...

================================================================================

Creating lmdb database in iteration 100000...
Error: TRAIN_DATA_ROOT is not a path to a directory.

Training network...

... Finished traing.

Creating learning images...
X-Powered-By: PHP/5.5.9-1ubuntu4.14
Content-type: text/html

Deleting old files...
0 Training Samples have been created...(0 skipped duplicates)
1000 Training Samples have been created...(0 skipped duplicates)
2000 Training Samples have been created...(0 skipped duplicates)
3000 Training Samples have been created...(0 skipped duplicates)
4000 Training Samples have been created...(0 skipped duplicates)
5000 Training Samples have been created...(0 skipped duplicates)
6000 Training Samples have been created...(0 skipped duplicates)
7000 Training Samples have been created...(0 skipped duplicates)
8000 Training Samples have been created...(0 skipped duplicates)
9000 Training Samples have been created...(0 skipped duplicates)
10000 Training Samples have been created...(0 skipped duplicates)
11000 Training Samples have been created...(0 skipped duplicates)
12000 Training Samples have been created...(0 skipped duplicates)
13000 Training Samples have been created...(0 skipped duplicates)
14000 Training Samples have been created...(0 skipped duplicates)
15000 Training Samples have been created...(0 skipped duplicates)
16000 Training Samples have been created...(0 skipped duplicates)
17000 Training Samples have been created...(0 skipped duplicates)
18000 Training Samples have been created...(0 skipped duplicates)
19000 Training Samples have been created...(0 skipped duplicates)
20000 Training Samples have been created...(0 skipped duplicates)
21000 Training Samples have been created...(0 skipped duplicates)
22000 Training Samples have been created...(0 skipped duplicates)
23000 Training Samples have been created...(0 skipped duplicates)
24000 Training Samples have been created...(1 skipped duplicates)
25000 Training Samples have been created...(0 skipped duplicates)
26000 Training Samples have been created...(1 skipped duplicates)
27000 Training Samples have been created...(0 skipped duplicates)
28000 Training Samples have been created...(0 skipped duplicates)
29000 Training Samples have been created...(0 skipped duplicates)
30000 Training Samples have been created...(1 skipped duplicates)
31000 Training Samples have been created...(0 skipped duplicates)
32000 Training Samples have been created...(0 skipped duplicates)
33000 Training Samples have been created...(0 skipped duplicates)
34000 Training Samples have been created...(0 skipped duplicates)
35000 Training Samples have been created...(0 skipped duplicates)
36000 Training Samples have been created...(1 skipped duplicates)
37000 Training Samples have been created...(0 skipped duplicates)
38000 Training Samples have been created...(0 skipped duplicates)
39000 Training Samples have been created...(0 skipped duplicates)
40000 Training Samples have been created...(0 skipped duplicates)
41000 Training Samples have been created...(0 skipped duplicates)
42000 Training Samples have been created...(0 skipped duplicates)
43000 Training Samples have been created...(1 skipped duplicates)
44000 Training Samples have been created...(0 skipped duplicates)
45000 Training Samples have been created...(0 skipped duplicates)
46000 Training Samples have been created...(0 skipped duplicates)
47000 Training Samples have been created...(0 skipped duplicates)
48000 Training Samples have been created...(1 skipped duplicates)
49000 Training Samples have been created...(0 skipped duplicates)

**Comment by seanbell** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

**Comment by SaadRiazQazi** [comment]
Post this to [Caffe User's google group](https://groups.google.com/forum/#!forum/caffe-users).
