### ISSUE TITLE
[apollocaffe] loading saved model

### ISSUE THREAD

**Issue by nyaong7** [BVLC/caffe#3900]
Dear,

I'm trying to build model with apollocaffe (./examples/apollocaffe/char_model/char_model.py).
From the sentences that are sampled after iterations, the results look great!! 

I found that using SnapshotLogger saves model in .h5 file format.
I was trying to load the model that are saved and sample from the model.
However it was not so easy 
Simply I tried to do the following

net = apollocaffe.ApolloNet('./model.h5')

The code runs ok, but it seems like it does not contain any information.
Does anybody know how to load the model and sample new texts?

Thank you in advance!

**Comment by seanbell** [comment]
This question has nothing to do with `BVLC/caffe`; please ask contact the apollocaffe maintainers instead.

**Comment by shwetgarg** [comment]
@nyaong7, Hey were you able to load the model with weights... I am having exactly same problem. 
I feel that as we load prototxt file in caffe, we need to save-load something more in apollocaffe also... but could not figure out what and how. If you have any idea on that, please help me.
