### ISSUE TITLE
export the weight from caffemodel

### ISSUE THREAD

**Issue by Tan12345** [BVLC/caffe#3901]
How to read the weights from caffemodel and save it to other file format? I try to use the net surgery but didn't suceess.

**Comment by wadefelix** [comment]
net = caffe.Net(...)  
net.params['layername'][0] is the blob saving the weights

**Comment by Tan12345** [comment]
Can you write the full coding? I am still a beginner in caffe.

**Comment by shelhamer** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
