### ISSUE TITLE
I have a problem about how to transform image into lmdb who can help me ?

### ISSUE THREAD

**Issue by liuliuqiu** [BVLC/caffe#3902]
Creating train lmdb...
I0328 18:54:11.871381  4062 convert_imageset.cpp:83] Shuffling data
I0328 18:54:12.091869  4062 convert_imageset.cpp:86] A total of 80 images.
F0328 18:54:12.091963  4062 db_lmdb.cpp:16] Check failed: mkdir(source.c_str(), 0744) == 0 (-1 vs. 0) mkdir /home/liu/caffe_master/myfile/image_train_lmdbfailed
*** Check failure stack trace: ***
    @     0x7fbffc1acdaa  (unknown)
    @     0x7fbffc1acce4  (unknown)
    @     0x7fbffc1ac6e6  (unknown)
    @     0x7fbffc1af687  (unknown)
    @     0x7fbffc634aee  caffe::db::LMDB::Open()
    @           0x40394d  main
    @     0x7fbffb1b7ec5  (unknown)
    @           0x404b2f  (unknown)
    @              (nil)  (unknown)
Aborted (core dumped)
Creating val lmdb...
I0328 18:54:12.257506  4069 convert_i**m**ageset.cpp:83] Shuffling data
I0328 18:54:12.478253  4069 convert_imageset.cpp:86] A total of 16 images.
F0328 18:54:12.478343  4069 db_lmdb.cpp:16] Check failed: mkdir(source.c_str(), 0744) == 0 (-1 vs. 0) mkdir /home/liu/caffe_master/myfile/image_val_lmdbfailed
*** Check failure stack trace: ***
    @     0x7f2808484daa  (unknown)
    @     0x7f2808484ce4  (unknown)
    @     0x7f28084846e6  (unknown)
    @     0x7f2808487687  (unknown)
    @     0x7f280890caee  caffe::db::LMDB::Open()
    @           0x40394d  main
    @     0x7f280748fec5  (unknown)
    @           0x404b2f  (unknown)
    @              (nil)  (unknown)
Aborted (core dumped)
Done.
what's wrong ?

**Comment by CDLuminate** [comment]
remove the resulting directory and try again.

**Comment by liuliuqiu** [comment]
it isn't resulting a directory,I try several times but it is not work

**Comment by seanbell** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

**Comment by sayadyaghoobi** [comment]
i have the same problem, if anyone can help please note.

**Comment by ZongweiZhou1** [comment]
@sayadyaghoobi Had the same issue, and resolved it by mkdir lmdb directory manually.

**Comment by DancingJane** [comment]
> @sayadyaghoobi Had the same issue, and resolved it by mkdir lmdb directory manually.

i have the same problem. could you please explain your solution in detail? did you comment the mkdir line in the db_lmdl.hpp and build caffe again? thank you
