### ISSUE TITLE
compile error on caffe windows

### ISSUE THREAD

**Issue by cheer37** [BVLC/caffe#3904]
I got the error C2220: warning treated as error - no 'object' file generated (..\..\src\caffe\data_transformer.cpp) when building the libcaffe project.
How can i fix this error?
Thanks.

**Comment by pavlejosipovic** [comment]
Can you share a build log file from VS?

**Comment by cheer37** [comment]
sure.
1>------ Build started: Project: libcaffe, Configuration: Debug x64 ------
1>  ProtoCompile.cmd : Create proto temp directory "D:\FreeSource\DeepLearning\caffe-windows\windows\..\src\caffe\proto\temp"
1>  ProtoCompile.cmd : Generating "D:\FreeSource\DeepLearning\caffe-windows\windows\..\src\caffe\proto\temp\caffe.pb.h" and "D:\FreeSource\DeepLearning\caffe-windows\windows\..\src\caffe\proto\temp\caffe.pb.cc"
1>  ProtoCompile.cmd : Create proto include directory
1>  A subdirectory or file D:\FreeSource\DeepLearning\caffe-windows\windows\..\include\caffe\proto already exists.
1>  ProtoCompile.cmd : Compare newly compiled caffe.pb.h with existing one
1>  common.cpp
1>  data_transformer.cpp
1>  image_data_layer.cpp
1>  window_data_layer.cpp
1>  math_functions.cpp
1>D:\FreeSource\DeepLearning\caffe-windows\include\caffe/util/rng.hpp : error C2220: warning treated as error - no 'object' file generated (..\..\src\caffe\data_transformer.cpp)
1>D:\FreeSource\DeepLearning\caffe-windows\include\caffe/util/rng.hpp : warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss (..\..\src\caffe\data_transformer.cpp)
1>D:\FreeSource\DeepLearning\caffe-windows\include\caffe/util/rng.hpp : error C2220: warning treated as error - no 'object' file generated (..\..\src\caffe\util\math_functions.cpp)
1>D:\FreeSource\DeepLearning\caffe-windows\include\caffe/util/rng.hpp : warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss (..\..\src\caffe\util\math_functions.cpp)
...

**Comment by pavlejosipovic** [comment]
Did you edit mg.hpp?

**Comment by cheer37** [comment]
No.

**Comment by pavlejosipovic** [comment]
Seems like '-' in line https://github.com/BVLC/caffe/blob/master/include/caffe/util/rng.hpp#L20
is causing issues. 
I'm not sure what is going on exactly, but if you remove It (or just put regular '-'), your compilation will continue, although you might hit similar issue in other files I'm not sure.
Here it is explained how to detect chars which are causing the issue http://stackoverflow.com/questions/10501634/warning-c4819-how-to-find-the-character-that-has-to-be-saved-in-unicode
If you hit this issue in multiple places maybe it's best to configure the solution to ignore C4819

**Comment by cheer37** [comment]
Thank you for your caring.
I made a build successfully saving the rng.hpp file as unicode format.

**Comment by Ocxs** [comment]
@cheer37  Your method does work!

**Comment by sarahzhouUestc** [comment]
@cheer37 Great, thanks!!
