### ISSUE TITLE
Caffe windows is slow.

### ISSUE THREAD

**Issue by cheer37** [BVLC/caffe#3907]
I built caffe windows successfully.
However, this is so slow compared with happynear's caffe-windows.
I did nothing with default props file except cudaArchitecture, means compiled with GPU enable and useCudnn.
My GPU is gtx 750 and it's cc is 50, so i changed cudaArchitecture like below <CudaArchitecture>compute_35,sm_35;compute_50,sm_50</CudaArchitecture>
I embedded cudnnv4. what's wrong?
Thanks in advance.

**Comment by pavlejosipovic** [comment]
What is slow, compile time or runtime?

In my experience Caffe on Windows and Linux has roughly the same performance on same hardware, so I don't see much room for improvement.

**Comment by cheer37** [comment]
I mean runtime, compile time does not matter.
I was using the caffe-windows of happynear here https://github.com/happynear/caffe-windows.
He informed about this repo which is official, so i tried to train with this. but its' running time is slower in the same environment with happynear's caffe.
I never tried to train in linux, so i can't compare this with linux version.

**Comment by cheer37** [comment]
I tried to find out the difference between two repos.
happynear also used cudnnv4, but it's different a bit with my cudnnv4 even though they are the same version.
This would be the factor to make difference speed?

**Comment by pavlejosipovic** [comment]
Can you repro this perf regression on any standard/example training?

**Comment by cheer37** [comment]
I think it does not related with specific example, thus you can repro with any example. like mnist

**Comment by pavlejosipovic** [comment]
OK when I get time I'll try to compare two repos in respect to perf on mnist example, but there shouldn't be big difference.

On your side maybe you can try to use exactly the same cuDNN

**Comment by cheer37** [comment]
ok, i will let you know after i tested with same cuDNN.
when you finish comparing, please let me know.
Thank you.

**Comment by cheer37** [comment]
I compared two repo using the same cuDNN, so they are measured to same runtime.
But i have another problem, i made a dll using example/cpp_classification.
I am using this dll in console program, but this dll gives an infinitive logs on exit in syncedmem.hpp.
check failed: error = cudaSuccess(11 vs 0) invalid argument ... syncedmem.hpp
I knew this is known side effect while googling.
How can i fix this problem? you can reproduce this error easily making a dll and using it in console main program.
Thanks.
