### ISSUE TITLE
/caffe/util/mkl_alternate.hpp:11:10: fatal error:  'cblas.h' file not found

### ISSUE THREAD

**Issue by LeoJohn1991** [BVLC/caffe#3908]
I followed caffe Installation (OS X) , but when i running  `make all -j8`, it get error.
```
/caffe-master/include/caffe/util/mkl_alternate.hpp:11:10: fatal error:
      'cblas.h' file not found
#include <cblas.h>
```
Then I google and tried to fixed it with following way:
`brew install openblas` , then modified Makefile.config, set `BLAS := open`, add `BLAS_INCLUDE := /usr/local/Cellar/openblas/0.2.15/include
BLAS_LIB := /usr/local/Cellar/openblas/0.2.15/lib`. But it still not fixed, how can I do?

**Comment by mmocco** [comment]
I am also having the same problem so I switched to trying to use atlas, but not working correctly either. Now I'm getting the error 
` Linking CXX shared library ../../lib/libcaffe.dylib
ld: framework not found vecLib
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [lib/libcaffe.1.0.0-rc3.dylib] Error 1
make[1]: *** [src/caffe/CMakeFiles/caffe.dir/all] Error 2
make: *** [all] Error 2`

**Comment by seanbell** [comment]
This looks like an installation question; please contact the mailing list for help (see below).  Note that when debugging, it helps to turn on verbose mode (last line in `Makefile.config)`

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

**Comment by VinayHuddar** [comment]
I encountered the cblas.h issue when compiling caffe and fixed it by changing the BLAS include directory in makefile from 
    BLAS_INCLUDE ?= /System/Library/Frameworks/vecLib.framework/Versions/Current/Headers/
to
    BLAS_INCLUDE ?= /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/Headers/
