### ISSUE TITLE
.caffemodel file type is PCX image (image/x-pcx) not Binary (application/octet-stream)

### ISSUE THREAD

**Issue by saustar** [BVLC/caffe#3910]
I have a file type issue .caffemodel file type is PCX. Model is working fine with caffe. But I have to use it in mxnet where they have provided a [converter](https://github.com/dmlc/mxnet/tree/master/tools/caffe_converter) but its not able to parse the caffemodel. I think its because of file type . I have been able to convert caffemodel with type Binary to mxnet .

Any insight?

**Comment by seanbell** [comment]
This issue has to do with mxnet; not caffe.  So I am closing the issue.  Please ask the maintainers of mxnet for help.

**Comment by saustar** [comment]
@seanbell still why file type of pre trained model provided by caffe is binary? Where as when I make a model its file type is PCX?

**Comment by seanbell** [comment]
Caffe saves all of its models as binary protobufs, using the extension `.caffemodel`.  I have no idea what PCX files are.

The schema for the protobufs are here: https://github.com/BVLC/caffe/blob/master/src/caffe/proto/caffe.proto

**Comment by JonathanJohann** [comment]
I have this exact same problem. I am using Ubuntu 16 and what happens is that I can re-save files that are already .caffemodel as .caffemodel. So, if I try to read in say one of the reference nets provided by BVLC, I can re-save that network with new weights. However, if I try to save a completely new set of weights from a caffemodel that I trained and built from scratch, I get the exact same problem. If I try to read this model back into Python, I get an error saying that caffe is unable to open the file.

I tried looking around at Ubuntu's potential tendency to use miming but found nothing useful. I am still looking into this problem currently...

**Comment by JonathanJohann** [comment]
Fast follow up:

So I dug through the code in test_nets.py file and what actually works better for me is using save_hdf5(...).

I had a much easier time saving the caffemodel. To be absolutely clear:

model = solver.test_nets[0]
model.save_hdf5('Example.caffemodel')

This is what worked for me. I hope it works for you too. Cheers.
