### ISSUE TITLE
Symbol lookup error while training the network

### ISSUE THREAD

**Issue by gaush123** [BVLC/caffe#3911]
I compiled caffe with GPU support, and was able to get 'PASSED' status in with 'make runtest'. But when I try to train the network I get the following error:

`./build/tools/caffe: symbol lookup error: /home/ubuntu/Downloads/caffe/.build_release/tools/../lib/libcaffe.so: undefined symbol: _ZN5caffe5cudnn8dataTypeIdE4zeroE
`

**Comment by seanbell** [comment]
Have you tried rebuilding the library with `make clean`?

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> When reporting a bug, it's most helpful to provide the following information, where applicable:
> 
> * What steps reproduce the bug?
> * Can you reproduce the bug using the latest [master](https://github.com/BVLC/caffe/tree/master), compiled with the `DEBUG` make option?
> * What hardware and operating system/distribution are you running?
> * If the bug is a crash, provide the backtrace (usually printed by Caffe; always obtainable with `gdb`).

**Comment by gaush123** [comment]
@seanbell My bad!
Yes, I tried to rebuild after running `make clean`, but it didn't solve the issue
This error occured when I ran `./examples/mnist/create_mnist.sh`
Prior to this step `make runtest` gave me 'PASSED' result
I ran it on g2.2xlarge ec2 instance

I later got around this issue by terminating the machine, and starting from scratch to build Caffe environment.

**Comment by shelhamer** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
