### ISSUE TITLE
unresolved external symbol  "public: static class caffe::Caffe & __cdecl caffe::Caffe::Get(void)" 

### ISSUE THREAD

**Issue by liyheart** [BVLC/caffe#3916]
Hi, I use the code to produce the libcaffe.dll, but when using the library, it shows the error, I'm sure the libcaffe.dll is in the search path. Could you check what's the problem?

**Comment by pavlejosipovic** [comment]
Current solution doesn't have libcaffe.dll, what we currently have is libcaffe.lib.
Did you add dll yourself?

**Comment by liyheart** [comment]
I now use the libcaffe.lib and it works, please close the issue,

**Comment by seanbell** [comment]
Just so you know, you should be able to close the issue yourself.  No need to ask us to do it.
