### ISSUE TITLE
training caffe for four object classes and one "no-object" class

### ISSUE THREAD

**Issue by marutiagarwal** [BVLC/caffe#392]
Has anyone tried training caffe for "no-object" class? Will it help with reducing false-detection among one of the 4 input well-defined-object categories such as car/chair/cloth/table? There are 2 ways I can think through this:
1. If a query image does not have high probability of belonging to one of the 4 training class, then it belongs to no-object class (we have not trained deepnet for this class yet)
2. We specifically train deepnet for non-object class. 

Which one might be a better approach in your opinion. Please share your experience on the same. Thanks.

**Comment by RafaRuiz** [comment]
Any workaround? I'm just curious :)
