### ISSUE TITLE
What is the use reason of the scale layer(power type) in LeNet architecture?

### ISSUE THREAD

**Issue by dgistJihunJung** [BVLC/caffe#3920]
Hello?

I started studying the deep learning using caffe framework with DIGITS.

I have any questions while the network configuration.

In the LeNet network, To exist scale layer(power type) between data layer and conv layer.

I have one question what the role of the layer.

Except for the scale layer, and configure the network, Learning is not all.

**Comment by seanbell** [comment]
Please use the mailing list for help with usage.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
