### ISSUE TITLE
caffe-window without cudnn

### ISSUE THREAD

**Issue by cheer37** [BVLC/caffe#3921]
I built caffe-windows successfully with cudnn support in a computer, and moved the caffe.exe into another computer.
It requires lmdb.dll and opencv dlls to run at other computer.
So I copied them into that computer and run.
But this is strange, why caffe.exe doesn't require the cudnn.dll?, how can it run without cudnn?
This means it runs without the support of cudnn?
How can i make it run with cudnn support in other computer?
Thanks.

**Comment by pavlejosipovic** [comment]
seems like you have cudnn in your  %PATH%, and that one is being used. 
You can use https://technet.microsoft.com/en-us/sysinternals/processmonitor.aspx to figure out which dll is being loaded.

**Comment by cheer37** [comment]
cudnn wasn't loaded seeing in processmonitor.

**Comment by pavlejosipovic** [comment]
if this is set to true https://github.com/BVLC/caffe/blob/windows/windows/CommonSettings.props.example#L8
then you need cuDNN to load in order to do trainings.

**Comment by cheer37** [comment]
I found the cudnn in my path environment variable.
Thanks for your time.

**Comment by cheer37** [comment]
I also have another question, 
Training with caffe-windows, logs like below out periodically.
Could not create logging file: File exists.
I guess this mean log file exists already, so can't create it.
But where is the log file?
Thanks.
