### ISSUE TITLE
Open two networks in the same python script

### ISSUE THREAD

**Issue by patrickrbrandao** [BVLC/caffe#3923]
Hello,

I want to compare some networks that were learned with different methodologies. When I open one network  with caffe.Net()   the script runs without any problem but when I try to open two nets the script stops after loading the first network and doesn't do anything else.
I don't know if it helps but this is last thing that the script prints:
I0331 17:19:53.669747 18481 layer_factory.hpp:77] Creating layer data
I0331 17:19:53.669795 18481 net.cpp:91] Creating Layer data
I0331 17:19:53.669800 18481 net.cpp:399] data -> data
I0331 17:19:53.669812 18481 net.cpp:399] data -> label

Best regards,
Patrick

**Comment by shelhamer** [comment]
This is an instance of #3108. Please see that issue for details on the bug which does indeed need fixing.
