### ISSUE TITLE
unable to make caffe in osx 10.11.3 with 'Undefined symbols for architecture x86_64'

### ISSUE THREAD

**Issue by teachertian** [BVLC/caffe#3927]
when i try to make caffe , i get an error message like this : 

> $ make all -j4
[  1%] Built target proto
[ 73%] Built target caffe
[ 75%] Built target upgrade_net_proto_binary
[ 76%] Built target test_net
[ 78%] Built target upgrade_net_proto_text
[ 80%] Built target upgrade_solver_proto_text
[ 81%] Built target convert_imageset
[ 83%] Built target finetune_net
[ 84%] Built target net_speed_benchmark
[ 86%] Built target device_query
[ 87%] Built target caffe.bin
[ 89%] Built target compute_image_mean
[ 90%] Built target train_net
[ 92%] Built target convert_mnist_data
[ 93%] Built target extract_features
[ 95%] Built target convert_mnist_siamese_data
[ 96%] Built target convert_cifar_data
[ 98%] Built target classification
[ 98%] Linking CXX shared library ../lib/_caffe.dylib
Undefined symbols for architecture x86_64:
  "boost::python::objects::function_object(boost::python::objects::py_function const&, std::pair<boost::python::detail::keyword const*, boost::python::detail::keyword const*> const&)", referenced from:
      void boost::python::class_<caffe::Net<float>, boost::shared_ptr<caffe::Net<float> >, boost::noncopyable_::noncopyable, boost::python::detail::not_specified>::def_impl<caffe::Net<float>, float (caffe::Net<float>::*)(int, int), boost::python::detail::def_helper<char const*, boost::python::detail::not_specified, boost::python::detail::not_specified, boost::python::detail::not_specified> >(caffe::Net<float>*, char const*, float (caffe::Net<float>::*)(int, int), boost::python::detail::def_helper<char const*, boost::python::detail::not_specified, boost::python::detail::not_specified, boost::python::detail::not_specified> const&, ...) in _caffe.cpp.o
      void boost::python::class_<caffe::Net<float>, boost::shared_ptr<caffe::Net<float> >, boost::noncopyable_::noncopyable, boost::python::detail::not_specified>::def_impl<caffe::Net<float>, void (caffe::Net<float>::*)(int, int), boost::python::detail::def_helper<char const*, boost::python::detail::not_specified, boost::python::detail::not_specified, boost::python::detail::not_specified> >(caffe::Net<float>*, char const*, void (caffe::Net<float>::*)(int, int), boost::python::detail::def_helper<char const*, boost::python::detail::not_specified, boost::python::detail::not_specified, boost::python::detail::not_specified> const&, ...) in _caffe.cpp.o
      void boost::python::class_<caffe::Net<float>, boost::shared_ptr<caffe::Net<float> >, boost::noncopyable_::noncopyable, boost::python::detail::not_specified>::def_impl<caffe::Net<float>, void (caffe::Net<float>::*)(), boost::python::detail::def_helper<char const*, boost::python::detail::not_specified, boost::python::detail::not_specified, boost::python::detail::not_specified> >(caffe::Net<float>*, char const*, void (caffe::Net<float>::*)(), boost::python::detail::def_helper<char const*, boost::python::detail::not_specified, boost::python::detail::not_specified, boost::python::detail::not_specified> const&, ...) in _caffe.cpp.o
      void boost::python::class_<caffe::Net<float>, boost::shared_ptr<caffe::Net<float> >, boost::noncopyable_::noncopyable, boost::python::detail::not_specified>::def_impl<caffe::Net<float>, void (caffe::Net<float>::*)(std::string), boost::python::detail::def_helper<char const*, boost::python::detail::not_specified, boost::python::detail::not_specified, boost::python::detail::not_specified> >(caffe::Net<float>*, char const*, void (caffe::Net<float>::*)(std::string), boost::python::detail::def_helper<char const*, boost::python::detail::not_specified, boost::python::detail::not_specified, boost::python::detail::not_specified> const&, ...) in _caffe.cpp.o
      void boost::python::class_<caffe::Net<float>, boost::shared_ptr<caffe::Net<float> >, boost::noncopyable_::noncopyable, boost::python::detail::not_specified>::def_impl<caffe::Net<float>, void (caffe::Net<float>::*)(caffe::Net<float> const*), boost::python::detail::def_helper<char const*, boost::python::detail::not_specified, boost::python::detail::not_specified, boost::python::detail::not_specified> >(caffe::Net<float>*, char const*, void (caffe::Net<float>::*)(caffe::Net<float> const*), boost::python::detail::def_helper<char const*, boost::python::detail::not_specified, boost::python::detail::not_specified, boost::python::detail::not_specified> const&, ...) in _caffe.cpp.o
      void boost::python::class_<caffe::Net<float>, boost::shared_ptr<caffe::Net<float> >, boost::noncopyable_::noncopyable, boost::python::detail::not_specified>::def_impl<caffe::Net<float>, void (*)(caffe::Net<float>*, boost::python::api::object, boost::python::api::object), boost::python::detail::def_helper<boost::python::with_custodian_and_ward<1ul, 2ul, boost::python::with_custodian_and_ward<1ul, 3ul, boost::python::default_call_policies> >, boost::python::detail::not_specified, boost::python::detail::not_specified, boost::python::detail::not_specified> >(caffe::Net<float>*, char const*, void (*)(caffe::Net<float>*, boost::python::api::object, boost::python::api::object), boost::python::detail::def_helper<boost::python::with_custodian_and_ward<1ul, 2ul, boost::python::with_custodian_and_ward<1ul, 3ul, boost::python::default_call_policies> >, boost::python::detail::not_specified, boost::python::detail::not_specified, boost::python::detail::not_specified> const&, ...) in _caffe.cpp.o
      void boost::python::class_<caffe::Net<float>, boost::shared_ptr<caffe::Net<float> >, boost::noncopyable_::noncopyable, boost::python::detail::not_specified>::def_impl<caffe::Net<float>, void (*)(caffe::Net<float> const&, std::string), boost::python::detail::def_helper<char const*, boost::python::detail::not_specified, boost::python::detail::not_specified, boost::python::detail::not_specified> >(caffe::Net<float>*, char const*, void (*)(caffe::Net<float> const&, std::string), boost::python::detail::def_helper<char const*, boost::python::detail::not_specified, boost::python::detail::not_specified, boost::python::detail::not_specified> const&, ...) in _caffe.cpp.o
      ...
  "boost::python::objects::register_dynamic_id_aux(boost::python::type_info, std::pair<void*, boost::python::type_info> (*)(void*))", referenced from:
      caffe::init_module__caffe() in _caffe.cpp.o
      boost::python::class_<caffe::Net<float>, boost::shared_ptr<caffe::Net<float> >, boost::noncopyable_::noncopyable, boost::python::detail::not_specified>::class_(char const*, boost::python::no_init_t) in _caffe.cpp.o
      boost::python::class_<caffe::Blob<float>, boost::shared_ptr<caffe::Blob<float> >, boost::noncopyable_::noncopyable, boost::python::detail::not_specified>::class_(char const*, boost::python::no_init_t) in _caffe.cpp.o
      boost::python::class_<caffe::LayerParameter, boost::python::detail::not_specified, boost::python::detail::not_specified, boost::python::detail::not_specified>::class_(char const*, boost::python::no_init_t) in _caffe.cpp.o
      boost::python::class_<caffe::Solver<float>, boost::shared_ptr<caffe::Solver<float> >, boost::noncopyable_::noncopyable, boost::python::detail::not_specified>::class_(char const*, boost::python::no_init_t) in _caffe.cpp.o
      boost::python::class_<boost::python::objects::iterator_range<boost::python::return_value_policy<boost::python::return_by_value, boost::python::default_call_policies>, __gnu_cxx::__normal_iterator<boost::shared_ptr<caffe::Blob<float> >*, std::vector<boost::shared_ptr<caffe::Blob<float> >, std::allocator<boost::shared_ptr<caffe::Blob<float> > > > > >, boost::python::detail::not_specified, boost::python::detail::not_specified, boost::python::detail::not_specified>::class_(char const*, boost::python::no_init_t) in _caffe.cpp.o
      boost::python::class_<boost::python::objects::iterator_range<boost::python::return_value_policy<boost::python::return_by_value, boost::python::default_call_policies>, __gnu_cxx::__normal_iterator<caffe::Blob<float>**, std::vector<caffe::Blob<float>*, std::allocator<caffe::Blob<float>*> > > >, boost::python::detail::not_specified, boost::python::detail::not_specified, boost::python::detail::not_specified>::class_(char const*, boost::python::no_init_t) in _caffe.cpp.o
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [lib/_caffe.dylib] Error 1
make[1]: *** [python/CMakeFiles/pycaffe.dir/all] Error 2

I am using 

>OS X EI Capitan 10.11.3
   boost_1_60_0
   only_cpu mode

Please give me some advice , thanks in advance!

**Comment by SvenTwo** [comment]
I had the same problem on Ubuntu 14. For me it was because in the Makefile, the boost_python library is not added if the environment variable PYTHON_LIBRARIES is already set, but it's not set to include boost.

I fixed it by changing the Makefile, line 202 from
`PYTHON_LIBRARIES ?= boost_python python2.7`
to 
`PYTHON_LIBRARIES += boost_python python2.7`

which is a bit of a hack of course (maybe just doing `PYTHON_LIBRARIES = boost_python python2.7` would be better?).

Alternatively, running `unset PYTHON_LIBRARIES` prior to doing make may work, too.

**Comment by SvenTwo** [comment]
I think the correct fix would be to use another variable, like:
```
CAFFE_PYTHON_LIBRARIES = PYTHON_LIBRARIES
CAFFE_PYTHON_LIBRARIES ?= boost_python python2.7
```

and then use CAFFE_PYTHON_LIBRARIES for the linker instead of the (system) variable PYTHON_LIBRARIES. But I'm not a makefile expert and I don't know how stuff works for other platforms and python3.

**Comment by teachertian** [comment]
i add 
> set(USE_libstdcpp:BOOL false)
in CMakeLists.txt and  avoid this mistake
but there are some new errors about opencv , so sad

**Comment by teachertian** [comment]
here is the new error : 

> [ 73%] Linking CXX shared library ../../lib/libcaffe.dylib
Undefined symbols for architecture x86_64:
  "cv::imread(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int)", referenced from:
      caffe::WindowDataLayer<float>::load_batch(caffe::Batch<float>*) in window_data_layer.cpp.o
      caffe::WindowDataLayer<double>::load_batch(caffe::Batch<double>*) in window_data_layer.cpp.o
      caffe::ReadImageToCVMat(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, int, bool) in io.cpp.o
  "cv::imencode(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, cv::_InputArray const&, std::__1::vector<unsigned char, std::__1::allocator<unsigned char> >&, std::__1::vector<int, std::__1::allocator<int> > const&)", referenced from:
      caffe::ReadImageToDatum(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, int, int, bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, caffe::Datum*) in io.cpp.o
  "google::protobuf::MessageLite::ParseFromString(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)", referenced from:
      caffe::DataReader::Body::read_one(caffe::db::Cursor*, caffe::DataReader::QueuePair*) in data_reader.cpp.o
  "google::protobuf::MessageFactory::InternalRegisterGeneratedFile(char const*, void (*)(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&))", referenced from:
      caffe::protobuf_AddDesc_caffe_2eproto() in libproto.a(caffe.pb.cc.o)
  "google::protobuf::io::CodedOutputStream::WriteStringWithSizeToArray(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned char*)", referenced from:
      caffe::Datum::SerializeWithCachedSizesToArray(unsigned char*) const in libproto.a(caffe.pb.cc.o)
      caffe::FillerParameter::SerializeWithCachedSizesToArray(unsigned char*) const in libproto.a(caffe.pb.cc.o)
      caffe::NetParameter::SerializeWithCachedSizesToArray(unsigned char*) const in libproto.a(caffe.pb.cc.o)
      caffe::SolverParameter::SerializeWithCachedSizesToArray(unsigned char*) const in libproto.a(caffe.pb.cc.o)
      caffe::SolverState::SerializeWithCachedSizesToArray(unsigned char*) const in libproto.a(caffe.pb.cc.o)
      caffe::NetState::SerializeWithCachedSizesToArray(unsigned char*) const in libproto.a(caffe.pb.cc.o)
      caffe::NetStateRule::SerializeWithCachedSizesToArray(unsigned char*) const in libproto.a(caffe.pb.cc.o)
      ...
  "google::protobuf::internal::WireFormatLite::ReadString(google::protobuf::io::CodedInputStream*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*)", referenced from:
      caffe::FillerParameter::MergePartialFromCodedStream(google::protobuf::io::CodedInputStream*) in libproto.a(caffe.pb.cc.o)
      caffe::NetParameter::MergePartialFromCodedStream(google::protobuf::io::CodedInputStream*) in libproto.a(caffe.pb.cc.o)
      caffe::SolverParameter::MergePartialFromCodedStream(google::protobuf::io::CodedInputStream*) in libproto.a(caffe.pb.cc.o)
      caffe::SolverState::MergePartialFromCodedStream(google::protobuf::io::CodedInputStream*) in libproto.a(caffe.pb.cc.o)
      caffe::NetState::MergePartialFromCodedStream(google::protobuf::io::CodedInputStream*) in libproto.a(caffe.pb.cc.o)
      caffe::NetStateRule::MergePartialFromCodedStream(google::protobuf::io::CodedInputStream*) in libproto.a(caffe.pb.cc.o)
      caffe::ParamSpec::MergePartialFromCodedStream(google::protobuf::io::CodedInputStream*) in libproto.a(caffe.pb.cc.o)
      ...
  "google::protobuf::internal::WireFormatLite::WriteString(int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, google::protobuf::io::CodedOutputStream*)", referenced from:
      caffe::NetParameter::SerializeWithCachedSizes(google::protobuf::io::CodedOutputStream*) const in libproto.a(caffe.pb.cc.o)
      caffe::SolverParameter::SerializeWithCachedSizes(google::protobuf::io::CodedOutputStream*) const in libproto.a(caffe.pb.cc.o)
      caffe::NetState::SerializeWithCachedSizes(google::protobuf::io::CodedOutputStream*) const in libproto.a(caffe.pb.cc.o)
      caffe::NetStateRule::SerializeWithCachedSizes(google::protobuf::io::CodedOutputStream*) const in libproto.a(caffe.pb.cc.o)
      caffe::LayerParameter::SerializeWithCachedSizes(google::protobuf::io::CodedOutputStream*) const in libproto.a(caffe.pb.cc.o)
      caffe::V1LayerParameter::SerializeWithCachedSizes(google::protobuf::io::CodedOutputStream*) const in libproto.a(caffe.pb.cc.o)
  "google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, google::protobuf::io::CodedOutputStream*)", referenced from:
      caffe::Datum::SerializeWithCachedSizes(google::protobuf::io::CodedOutputStream*) const in libproto.a(caffe.pb.cc.o)
  "google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, google::protobuf::io::CodedOutputStream*)", referenced from:
      caffe::FillerParameter::SerializeWithCachedSizes(google::protobuf::io::CodedOutputStream*) const in libproto.a(caffe.pb.cc.o)
      caffe::NetParameter::SerializeWithCachedSizes(google::protobuf::io::CodedOutputStream*) const in libproto.a(caffe.pb.cc.o)
      caffe::SolverParameter::SerializeWithCachedSizes(google::protobuf::io::CodedOutputStream*) const in libproto.a(caffe.pb.cc.o)
      caffe::SolverState::SerializeWithCachedSizes(google::protobuf::io::CodedOutputStream*) const in libproto.a(caffe.pb.cc.o)
      caffe::ParamSpec::SerializeWithCachedSizes(google::protobuf::io::CodedOutputStream*) const in libproto.a(caffe.pb.cc.o)
      caffe::LayerParameter::SerializeWithCachedSizes(google::protobuf::io::CodedOutputStream*) const in libproto.a(caffe.pb.cc.o)
      caffe::TransformationParameter::SerializeWithCachedSizes(google::protobuf::io::CodedOutputStream*) const in libproto.a(caffe.pb.cc.o)
      ...
  "google::protobuf::internal::WireFormatLite::ReadBytes(google::protobuf::io::CodedInputStream*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*)", referenced from:
      caffe::Datum::MergePartialFromCodedStream(google::protobuf::io::CodedInputStream*) in libproto.a(caffe.pb.cc.o)
  "google::protobuf::internal::StringTypeHandlerBase::Delete(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*)", referenced from:
      caffe::NetParameter::NetParameter() in libproto.a(caffe.pb.cc.o)
      caffe::NetParameter::NetParameter(caffe::NetParameter const&) in libproto.a(caffe.pb.cc.o)
      caffe::NetParameter::~NetParameter() in libproto.a(caffe.pb.cc.o)
      caffe::SolverParameter::SolverParameter() in libproto.a(caffe.pb.cc.o)
      caffe::SolverParameter::SolverParameter(caffe::SolverParameter const&) in libproto.a(caffe.pb.cc.o)
      caffe::SolverParameter::~SolverParameter() in libproto.a(caffe.pb.cc.o)
      caffe::NetState::NetState() in libproto.a(caffe.pb.cc.o)
      ...
  "leveldb::DB::Open(leveldb::Options const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, leveldb::DB**)", referenced from:
      caffe::db::LevelDB::Open(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, caffe::db::Mode) in db_leveldb.cpp.o
  "google::protobuf::DescriptorPool::FindFileByName(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const", referenced from:
      caffe::protobuf_AssignDesc_caffe_2eproto() in libproto.a(caffe.pb.cc.o)
  "google::protobuf::Message::SerializeToOstream(std::__1::basic_ostream<char, std::__1::char_traits<char> >*) const", referenced from:
      caffe::WriteProtoToBinaryFile(google::protobuf::Message const&, char const*) in io.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [lib/libcaffe.1.0.0-rc3.dylib] Error 1
make[1]: *** [src/caffe/CMakeFiles/caffe.dir/all] Error 2
make: *** [all] Error 2

what should i do?

**Comment by shelhamer** [comment]
Please ask installation questions on the mailing list. If you're having trouble, you might want to try the Caffe [Dockerfile](https://github.com/BVLC/caffe/tree/master/docker) to take care of installation for you.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
