### ISSUE TITLE
How to draw the training curve in caffe-windows

### ISSUE THREAD

**Issue by cheer37** [BVLC/caffe#3928]
I tried to draw using plot_training_log.py in tools/extra.
But it calls linux bash shell script, so it fails.
How can i draw the training curve?

**Comment by sasagalic-MSFT** [comment]
I think it should be possible to make it work using Cygwin but I am not sure how python+Cygwin works. Please let us know your findings.

**Comment by cheer37** [comment]
I think so it's possible.
But I found a python code to draw the training curve other than plot_training_log.py somewhere.
I downloaded it, but forgot the link to post it.
How can i share this code?
