### ISSUE TITLE
RMSProp solver is different from the one described on the tutorial page?

### ISSUE THREAD

**Issue by cuihenggang** [BVLC/caffe#3930]
I find the RMSProp solver code is different from the RMSProp algorithm that is described in the Caffe tutorial page (http://caffe.berkeleyvision.org/tutorial/solver.html).

Actually I think they are very different. The tutorial page describe the RMSProp algorithm as:

(vt)i={(vt−1)i+δ,(vt−1)i⋅(1−δ),(∇L(Wt))i(∇L(Wt−1))i>0else
(vt)i={(vt−1)i+δ,(∇L(Wt))i(∇L(Wt−1))i>0(vt−1)i⋅(1−δ),else
(Wt+1)i=(Wt)i−α(vt)i,
(Wt+1)i=(Wt)i−α(vt)i,
If the gradient updates results in oscillations the gradient is reduced by times 1−δ1−δ. Otherwise it will be increased by δδ. The default value of δδ (rms_decay) is set to δ=0.02δ=0.02.

But the RMSProp implementation is:
CUDA_KERNEL_LOOP(i, N) {
    float gi = g[i];
    float hi = h[i] = rms_decay*h[i] + (1-rms_decay)*gi*gi;
    g[i] = local_rate * g[i] / (sqrt(hi) + delta);
  }

Which one is the true RMSProp algorithm?

**Comment by seanbell** [comment]
The tutorial description is wrong.  That looks like the slide titled "One	way	to	determine	the	individual	learning	rates" from the lecture http://www.cs.toronto.edu/~tijmen/csc321/slides/lecture_slides_lec6.pdf.

That same lecture contains a description of RMSprop, but it is later in the lecture.

**Comment by seanbell** [comment]
Feel free to submit a PR correcting the docs (https://github.com/BVLC/caffe/blob/master/docs/tutorial/solver.md)
