### ISSUE TITLE
Cannot compile internal src/caffe/internal_thread.cpp

### ISSUE THREAD

**Issue by renmengye** [BVLC/caffe#3931]
CXX src/caffe/internal_thread.cpp
src/caffe/internal_thread.cpp: In destructor ‘virtual caffe::InternalThread::~InternalThread()’:
src/caffe/internal_thread.cpp:10:22: error: ‘StopInternalThread’ was not declared in this scope
   StopInternalThread();
                      ^
src/caffe/internal_thread.cpp: At global scope:
src/caffe/internal_thread.cpp:13:6: error: redefinition of ‘bool caffe::InternalThread::is_started() const’
 bool InternalThread::is_started() const {
      ^
In file included from src/caffe/internal_thread.cpp:4:0:
./include/caffe/internal_thread.hpp:38:8: error: ‘bool caffe::InternalThread::is_started() const’ previously defined here
   bool is_started() const { return thread_ != NULL && thread_->joinable(); }
        ^
src/caffe/internal_thread.cpp:17:32: error: no ‘bool caffe::InternalThread::must_stop()’ member function declared in class ‘caffe::InternalThread’
 bool InternalThread::must_stop() {
                                ^
src/caffe/internal_thread.cpp:21:6: error: prototype for ‘void caffe::InternalThread::StartInternalThread()’ does not match any in class ‘caffe::InternalThread’
 void InternalThread::StartInternalThread() {
      ^
In file included from src/caffe/internal_thread.cpp:4:0:
./include/caffe/internal_thread.hpp:33:8: error: candidate is: bool caffe::InternalThread::StartInternalThread()
   bool StartInternalThread();
        ^
src/caffe/internal_thread.cpp:42:39: error: no ‘void caffe::InternalThread::entry(int, caffe::Caffe::Brew, int, int, bool)’ member function declared in class ‘caffe::InternalThread’
     int solver_count, bool root_solver) {
                                       ^
src/caffe/internal_thread.cpp:54:41: error: no ‘void caffe::InternalThread::StopInternalThread()’ member function declared in class ‘caffe::InternalThread’
 void InternalThread::StopInternalThread() {
                                         ^
In file included from /pkgs/boost-1.59/include/boost/system/system_error.hpp:14:0,
                 from /pkgs/boost-1.59/include/boost/thread/exceptions.hpp:22,
                 from /pkgs/boost-1.59/include/boost/thread/pthread/thread_data.hpp:10,
                 from /pkgs/boost-1.59/include/boost/thread/thread_only.hpp:17,
                 from /pkgs/boost-1.59/include/boost/thread/thread.hpp:12,
                 from /pkgs/boost-1.59/include/boost/thread.hpp:13,
                 from src/caffe/internal_thread.cpp:1:
/pkgs/boost-1.59/include/boost/system/error_code.hpp:221:36: warning: ‘boost::system::posix_category’ defined but not used [-Wunused-variable]
     static const error_category &  posix_category = generic_category();
                                    ^
/pkgs/boost-1.59/include/boost/system/error_code.hpp:222:36: warning: ‘boost::system::errno_ecat’ defined but not used [-Wunused-variable]
     static const error_category &  errno_ecat     = generic_category();
                                    ^
/pkgs/boost-1.59/include/boost/system/error_code.hpp:223:36: warning: ‘boost::system::native_ecat’ defined but not used [-Wunused-variable]
     static const error_category &  native_ecat    = system_category();
                                    ^
make: *** [.build_release/src/caffe/internal_thread.o] Error 1
mren@guppy12:~/third_party/caffe$ vim Makefile.config
mren@guppy12:~/third_party/caffe$ ls /pkgs/boost
boost_1_57_0/ boost-1.59/   
mren@guppy12:~/third_party/caffe$ vim Makefile.config^C
mren@guppy12:~/third_party/caffe$ vim Makefile.config
mren@guppy12:~/third_party/caffe$ make clean
mren@guppy12:~/third_party/caffe$ make all
PROTOC src/caffe/proto/caffe.proto
CXX .build_release/src/caffe/proto/caffe.pb.cc
CXX src/caffe/internal_thread.cpp
src/caffe/internal_thread.cpp: In destructor ‘virtual caffe::InternalThread::~InternalThread()’:
src/caffe/internal_thread.cpp:10:22: error: ‘StopInternalThread’ was not declared in this scope
   StopInternalThread();
                      ^
src/caffe/internal_thread.cpp: At global scope:
src/caffe/internal_thread.cpp:13:6: error: redefinition of ‘bool caffe::InternalThread::is_started() const’
 bool InternalThread::is_started() const {
      ^
In file included from src/caffe/internal_thread.cpp:4:0:
./include/caffe/internal_thread.hpp:38:8: error: ‘bool caffe::InternalThread::is_started() const’ previously defined here
   bool is_started() const { return thread_ != NULL && thread_->joinable(); }
        ^
src/caffe/internal_thread.cpp:17:32: error: no ‘bool caffe::InternalThread::must_stop()’ member function declared in class ‘caffe::InternalThread’
 bool InternalThread::must_stop() {
                                ^
src/caffe/internal_thread.cpp:21:6: error: prototype for ‘void caffe::InternalThread::StartInternalThread()’ does not match any in class ‘caffe::InternalThread’
 void InternalThread::StartInternalThread() {
      ^
In file included from src/caffe/internal_thread.cpp:4:0:
./include/caffe/internal_thread.hpp:33:8: error: candidate is: bool caffe::InternalThread::StartInternalThread()
   bool StartInternalThread();
        ^
src/caffe/internal_thread.cpp:42:39: error: no ‘void caffe::InternalThread::entry(int, caffe::Caffe::Brew, int, int, bool)’ member function declared in class ‘caffe::InternalThread’
     int solver_count, bool root_solver) {
                                       ^
src/caffe/internal_thread.cpp:54:41: error: no ‘void caffe::InternalThread::StopInternalThread()’ member function declared in class ‘caffe::InternalThread’
 void InternalThread::StopInternalThread() {
                                         ^
make: *** [.build_release/src/caffe/internal_thread.o] Error 1

**Comment by renmengye** [comment]
Figured out the reason. Having an outdated caffe include folder.

**Comment by lwye** [comment]
how did you solve this problem? @renmengye

**Comment by AliRaza21918** [comment]
i am also facing same problem 
how you solved this? @renmengye
