### ISSUE TITLE
Get “undefined symbol: cairo_surface_get_device_scale” when use caffe in python

### ISSUE THREAD

**Issue by mengcz13** [BVLC/caffe#3932]
After successfully compiled and installed caffe and pycaffe, I got undefined symbol: cairo_surface_get_device_scale when trying to import caffe in Python.
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/neozero/caffe/python/caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropSolver, AdaDeltaSolver, AdamSolver
  File "/home/neozero/caffe/python/caffe/pycaffe.py", line 13, in <module>
    from ._caffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, \
ImportError: /usr/lib/libgdk-3.so.0: undefined symbol: cairo_surface_get_device_scale`
I have googled that upgrade the cairo might help. But it did not help. I use Arch Linux and have every thing upgraded and reinstalled cairo-1.14.6, which is the latest version, but it still did not work.
So how to fix that?

**Comment by seanbell** [comment]
This problem looks unrelated to caffe.  Maybe you should search around more for a solution, or ask for help elsewhere?

**Comment by mengcz13** [comment]
Sorry... I have fixed it. The error may be caused by pyenv.

**Comment by anujkhare** [comment]
Hi, could you please share what was wrong in your setup? I am facing the same problem.

**Comment by mengcz13** [comment]
First I tried to run caffe under anaconda offered by pyenv and got the error, later I directly ran it with the python provided by arch linux. I doubt it was because that the libgdk was compiled with GCC 5.x but the anaconda was compiled with GCC 4.x... But I am not sure about that.
