### ISSUE TITLE
Obtain Error versus iteration plot, once trained the network in CAFFE. Have all the .solverstate files. Any help?

### ISSUE THREAD

**Issue by prathmeshrmadhu** [BVLC/caffe#3933]

**Comment by seanbell** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

**Comment by prathmeshrmadhu** [comment]
Sorry for the trouble, will take a note of  it henceforth.
