### ISSUE TITLE
OSX 10.11.4 Cannot install boost and boost python as the guide

### ISSUE THREAD

**Issue by jingliuvic** [BVLC/caffe#3936]
I tried to install caffe on OS X 10.11.4 following the guide [http://caffe.berkeleyvision.org/install_osx.html](http://caffe.berkeleyvision.org/install_osx.html)
But "brew install --build-from-source -vd boost boost-python" seems not work well.

My machine stuck and the screen is showing "...updated 13743 targets..." for around 12 hours.

**Comment by balakg** [comment]
Yes, I got the same issue with OS X 10.11, which didn't seem to happen with OS X 10.9. I think I worked around it for now by just doing 'brew install boost boost-python'. I'm assuming there is a better way to handle it though.

**Comment by mdelmans** [comment]
Same here, with:
`brew install boost --c++11`

**Comment by madcarrot** [comment]
Same here, with 
`brew install boost`
`brew install --build-from-source --fresh -vd \
    https://raw.githubusercontent.com/Homebrew/homebrew/6fd6a9b6b2f56139a44dd689d30b7168ac13effb/Library/Formula/boost.rb \
    https://raw.githubusercontent.com/Homebrew/homebrew/3141234b3473717e87f3958d4916fe0ada0baba9/Library/Formula/boost-python.rb
`
Was never able to solve it...

**Comment by kimsama** [comment]
same on here with OSX 10.11.4. both of 'boost' and 'boost-python'.

**Comment by madcarrot** [comment]
In the end I reinstalled the OS, then used the guide from here:
http://starsci.cn/blog/?p=262

So basically before I installed boost and boost-python from homebrew, I installed boost with macport and then `export PATH="/opt/local/bin:/opt/local/sbin:$PATH"` (this step should actually be written in your ~/.bash_profile by macports) and then brew installed boost and boost-python using the line provided in the webpage referenced before

**Comment by seanbell** [comment]
Closing since this is an installation question.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
