### ISSUE TITLE
Batch Normalization using cuDNN?

### ISSUE THREAD

**Issue by cuihenggang** [BVLC/caffe#3940]
I find MXNet implements Batch Normalization using cuDNN APIs (cudnnBatchNormalizationForward and cudnnBatchNormalizationBackward), while Caffe writes its own code. Is Caffe considering using cuDNN APIs also?

Thank you,
Cui

**Comment by ajtulloch** [comment]
See https://github.com/BVLC/caffe/pull/3919 from NVIDIA, you can patch that in now if you need it ASAP :)
