### ISSUE TITLE
Unable to build Caffe.sln correctly

### ISSUE THREAD

**Issue by ljyyoruhi** [BVLC/caffe#3946]
I am going to use the Windows Caffe and have followed the pre-build steps to build .\windows\Caffe.sln. However, when I run Debugger in Visual Studio, a message shows 'Unable to start program '<caffe_root>\windows\..\Build\x64\Release\libcaffe.lib''.

![default](https://cloud.githubusercontent.com/assets/15664444/14291366/da11d0c0-fb95-11e5-9e95-51f49058e8d1.png)

Someone mention that this is because a wrong startUp project is set, so I tried to change the startUp project from 'libcaffe' (the default one) to both 'caffe' and 'test_all'. It shows no error message but there are lots of warning of 'Cannot find or open the PDB file'. Should it be alright or there is still something wrong? The log is following:
![log](https://cloud.githubusercontent.com/assets/15664444/14291357/ce81528a-fb95-11e5-9939-2f04ba5fe30e.png)

I have seen others mention this issue and have got solved, so I wonder if someone can tell me how to deal with it. Thank you.

**Comment by pavlejosipovic** [comment]
Second log seems just fine, you have run caffe.exe which you should run for trainings.
It seems to me that you haven't passed any args to the caffe.exe

**Comment by ljyyoruhi** [comment]
@pavlejosipovic Thank you. I am new to this and don't know how to pass args. This time it looks like this:

![image](https://cloud.githubusercontent.com/assets/15664444/14304999/be284326-fbea-11e5-83fd-398a7ab614bd.png)

The last line means 'Press any key to continue'. What is the problem here?

**Comment by pavlejosipovic** [comment]
What exactly are you trying to do?
Maybe you should start reading about caffe in general here http://caffe.berkeleyvision.org/

**Comment by ljyyoruhi** [comment]
Sorry, I don't exactly know whether I should do this, but the cmd above appears during debugging project caffe. I am going to use caffe with MATLAB. And I think this problem may have been solved up to this step. Thank you!
