### ISSUE TITLE
Error parsing text-format caffe.NetParameter

### ISSUE THREAD

**Issue by edanamerchan** [BVLC/caffe#3947]
I'm trying to run an example but I get this error:

```
$ python caffe_feature_extractor.py -i test/temp.txt -o out.txt
<property object at 0x27495d0>
Reading images from " test/temp.txt
Writing vectors to " out.txt
WARNING: Logging before InitGoogleLogging() is written to STDERR
E0405 18:54:10.296026 33623 common.cpp:104] Cannot create Cublas handle. Cublas won't be available.
E0405 18:54:10.296254 33623 common.cpp:111] Cannot create Curand generator. Curand won't be available.
[libprotobuf ERROR google/protobuf/text_format.cc:274] Error parsing text-format caffe.NetParameter: 6:15: Message type "caffe.LayerParameter" has no field named "input_param".
F0405 18:54:10.311813 33623 upgrade_proto.cpp:68] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: /apps/testsuite/caffe/models/bvlc_googlenet/deploy.prototxt
*** Check failure stack trace: ***
Aborted
```
 
Thanks for your help.

**Comment by trandinh** [comment]
Did you solved your problem?
I got the same problem about parsing text-format. I use c++ not python.
Someone suggest the problem cause the version of libprotobuf is not correct with the format in .prototxt file. 
The solution is we have to upgrade proto, but I don't know how to upgrade proto in caffe.
If any one have experience about this please help me.
![error_libprotobuf](https://cloud.githubusercontent.com/assets/4454707/14339103/f4f2b324-fcb6-11e5-8dc5-e344a76a3213.png)

**Comment by lukeyeager** [comment]
> Message type "caffe.LayerParameter" has no field named "input_param".

You need to update your build of Caffe. `input_param` was added with https://github.com/BVLC/caffe/pull/3211 on 02/27.

**Comment by ajtulloch** [comment]
Yep, @lukeyeager  is correct.

**Comment by hana9090** [comment]
How to upgrade this?

**Comment by ajtulloch** [comment]
Run upgrade_net.cpp

**Comment by hana9090** [comment]
how to run?
cpp upgrade_net.cpp?
at which directory?

**Comment by anbai106** [comment]
Sorry to reopen this issue again, I had the same problem when i run olver = caffe.SGDSolver('fcn_solver.prototxt')

`WARNING: Logging before InitGoogleLogging() is written to STDERR
I1024 11:45:08.993687 2078609408 solver.cpp:48] Initializing solver from parameters: 
train_net: "fcn_train.prototxt"
test_net: "fcn_test.prototxt"
test_iter: 26
test_interval: 200
base_lr: 0.01
display: 200
max_iter: 15000
lr_policy: "multistep"
gamma: 0.1
momentum: 0.9
weight_decay: 0.0005
snapshot: 2500
snapshot_prefix: "./model_logs/fcn"
random_seed: 5
test_initialization: true
average_loss: 200
stepvalue: 10000
I1024 11:45:08.994006 2078609408 solver.cpp:81] Creating training net from train_net file: fcn_train.prototxt
[libprotobuf ERROR google/protobuf/text_format.cc:298] Error parsing text-format caffe.NetParameter: 256:5: Non-repeated field "name" is specified multiple times.
F1024 11:45:08.994349 2078609408 upgrade_proto.cpp:88] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: fcn_train.prototxt
*** Check failure stack trace: ***`

But I dont know how to upgrade the build of CAFFE, can anyone give me a hint??? and the reference you mentioned does not have the solution...
Thanks in advance:)

**Comment by gittigxuy** [comment]
@anbai106 I have the same question ,did you solve the problem?
