### ISSUE TITLE
Wired cuda error

### ISSUE THREAD

**Issue by yzk0281** [BVLC/caffe#3949]
Hi,
I use libcaffe in another nginx server to extract feature of images. 
When I run libcaffe in CPU-ONLY mode, it works fine; but when I turn to GPU mode, error accurs at this CaffeFreeHost function:
Check failed: error == cudaSuccess (3 vs. 0) initialization error.
But, When I run caffe alone with GPU mode, it works fine.
I think it is some kind of memory error, but I don't know how to solve it.
I tried to modify src/caffe/syncedmem.cpp and include/caffe/syncedmem.hpp as anfeng says, but still the same question.
Anybody has suggestions?

**Comment by ZhengRui** [comment]
when i user multiprocessing, i encounter this problem, haven't found a solution yet

**Comment by jingith** [comment]
how fix？
