### ISSUE TITLE
Can Caffe be used for classification without training?

### ISSUE THREAD

**Issue by SaadRiazQazi** [BVLC/caffe#3950]
I am sure some users will not agree with my problem being an issue, however, I am posting this as I cannot get a suitable answer anywhere else, including the users group.

Background:
1. I have installed all dependencies using Jetpack 2.0 on Nvidia TK1.
2. I have installed caffe and its dependencies successfully.
3. The MNIST example is working fine.

Task:
1. I have been given a convnet with all standard layers. (Not an opensource model)
2. The network weights and bias values etc are available with me after training. The training has not been done via caffe. (Pretrained Network)
3. The weights and bias are all in the form of MATLAB matrices. (Actually in a .txt file but I can easily write code to get them to be matrices)
4. I CANNOT do training of this network with caffe and must used the given weights and bias values ONLY for classification.
5. I have my own dataset in the form of 32x32 pixel images.

Issue:
In all tutorials, details are given on how to deploy and train a network, and then use the generated .proto and .caffemodel files to validate and classify. Is it possible to implement this network on caffe and directly use my weights/bias and training set to classify images? What are the available options here? I am a caffe-virgin so be kind. Thank you for the help!

**Comment by zeakey** [comment]
You can initialize a plain network and copy weights from your txt to the new initiated network.
Then testing is easy to do.

**Comment by ajtulloch** [comment]
1) Create a prototxt or NetSpec that has the structure of the network
2) Instantiate the net in Python
3) Fill in the weights (`for name, param in net.params.iteritems(): param[...] = <my-weights-for-name>`)
4) Save the net as a caffemodel (net.save(<path>)

Then you have a protoxt and a caffemodel that do what you want.

**Comment by shelhamer** [comment]
@SaadRiazQazi From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
