### ISSUE TITLE
blobs_lr doesn't exist?

### ISSUE THREAD

**Issue by DCurro** [BVLC/caffe#3956]
Hi caffe team,

I am trying to make sure certain layers don't learn. I am using the Alexnet Reference network and I want to not learn the convolutional layers. Google searching brought up an issue about blobs_lr but it doesn't seem to want to play along.

Here is my issue:
[libprotobuf ERROR google/protobuf/text_format.cc:245] Error parsing text-format caffe.NetParameter: 84:11: Message type "caffe.LayerParameter" has no field named "blobs_lr"

And the layer:

     layer {
      name: "conv2"
      type: "Convolution"
      bottom: "norm1"
      top: "conv2"
      param {
        lr_mult: 1
        decay_mult: 1
      }
      param {
        lr_mult: 2
        decay_mult: 0
      }
      convolution_param {
        num_output: 256
        pad: 2
        kernel_size: 5
        group: 2
        weight_filler {
          type: "gaussian"
          std: 0.01
        }
        bias_filler {
          type: "constant"
          value: 1
        }
      }
      blobs_lr: 0 
    }

**Comment by SvenTwo** [comment]
I think blobs_lr and weight_decay are outdated. Just set the lr_mult and decay_mult in the param struct instead.

**Comment by DCurro** [comment]
That's the route I've gone down, by some colleague's advice. Thanks!

The solution was to use 
    param { #weights
      lr_mult: 0
      decay_mult: 1
    }
    param { #bias
      lr_mult: 0
      decay_mult: 0
    }

**Comment by ajtulloch** [comment]
Looks like this is resolved? Thanks @SvenTwo. See https://github.com/BVLC/caffe/commit/78b02e5fd3a43912556796bf29f118e0dea7b45e for some more context as well.
