### ISSUE TITLE
There is a data blob of hdf5 [600000,1,7,256]. How to do mean subtraction using Caffe in matlab?

### ISSUE THREAD

**Issue by littleTwelve** [BVLC/caffe#3961]
There is a data blob of hdf5 [600000,1,7,256].The function 'compute_image_mean.cpp' in Caffe is not fit for HDF5. So how to do mean subtraction using Caffe in matlab?

**Comment by Enet4** [comment]
There's an answer to that in the Caffe Users group: https://groups.google.com/d/msg/caffe-users/9WHDx0Avrzo/L3gfEJa3CwAJ
Basically, HDF5InputLayer does not support mean subtraction, but it shouldn't be too hard to perform that manually under MatLab.

**Comment by littleTwelve** [comment]
Thank you for your help!Do you know how can I use CNN to train my data?As you can see,my data set is not square-matrix and it is also not image but 2-D signal.So how can I design my CNN net for training my data set?Should I code it at my own ?But I think it is too difficult for me to design a CNN net.

**Comment by Enet4** [comment]
I'm sorry, that goes beyond my scope and this issue tracker's. Please check out the [Caffe Users](https://groups.google.com/forum/#!forum/caffe-users) group the next time you have a question about using Caffe.

**Comment by littleTwelve** [comment]
Ok,thanks!
