### ISSUE TITLE
How can I train my data set in Matlab using Caffe?

### ISSUE THREAD

**Issue by littleTwelve** [BVLC/caffe#3964]
If I already have 'deploy.prototxt','solver.prototxt','train_val.prototxt'.How can I code in matlab to call function of Caffe to train my data set.I know 'caffe-master\matlab\demo' there is a demo code but it just for classsification not train.Who have a complete code about how to train one's own data set?

**Comment by seanbell** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
