### ISSUE TITLE
What layers/graph structures can be use to model relations like `x * y`, `x / y` or even more complex ones like `2 ^ x` or `x ^ y`?

### ISSUE THREAD

**Issue by royitaqi** [BVLC/caffe#3968]
I guess it's more like a usage question, but also kind of technical since the question is about whether such modeling ability is achievable with the current layer types and graph structure. If this question is better posted in another place (on GitHub or some other forum), please let me know - I will be more than happy to post the question there and close this issue.

Detailed answers will be appreciate. For example layers types, how to connect them, brief description of the input data, why this can work, and even a small example.

Thanks a lot, guys!

**Comment by seanbell** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
