### ISSUE TITLE
Cumulative eltwise layer

### ISSUE THREAD

**Issue by Quantad** [BVLC/caffe#3971]
Hey, how can I create a blob in caffe in which at each and every subsequent iteration the elements are multiplied by new values element-wise and replaced by the calculated new values? Thanks.

**Comment by seanbell** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

**Comment by seanbell** [comment]
You can use a Python data layer and generate what you want that way.
