### ISSUE TITLE
A problem during classification:Check failed: fd != -1 (-1 vs. -1) File not found:  examples/class/deploy.prototxt

### ISSUE THREAD

**Issue by ariexhyx** [BVLC/caffe#3972]
I have trained my model before,and I want to classify new images on my model
I type "./build/examples/cpp_classification/classification.bin \ examples/class/deploy.prototxt \ examples/class/banana.caffemodel \ examples/class/banana_mean.binaryproto \ examples/class/label.txt \ examples/class/01.jpg" in terminal, and run it.

An error occurs.
io.cpp:36] Check failed: fd != -1 (-1 vs. -1) File not found:  examples/class/deploy.prototxt

All files exist. And the path is correct. 
I don't know why.Can anyone help me?Many thanks.

Same problem happened before when I followed the usage below. I‘ve downloaded the caffemodel, meanfile and synset_words.txt.
http://caffe.berkeleyvision.org/gathered/examples/cpp_classification.html

hyx@ubuntu:~$ cd ./caffe
hyx@ubuntu:~/caffe$ ./build/examples/cpp_classification/classification.bin \ models/bvlc_reference_caffenet/deploy.prototxt \ models/bvlc_reference_caffenet/bvlc_reference_caffenet.caffemodel \ data/ilsvrc12/imagenet_mean.binaryproto \ data/ilsvrc12/synset_words.txt \ examples/images/cat.jpg 
F0410 22:50:10.167029  2790 io.cpp:36] Check failed: fd != -1 (-1 vs. -1) File not found:  models/bvlc_reference_caffenet/deploy.prototxt
*** Check failure stack trace: ***
    @     0x7f3e8df54daa  (unknown)
    @     0x7f3e8df54ce4  (unknown)
    @     0x7f3e8df546e6  (unknown)
    @     0x7f3e8df57687  (unknown)
    @     0x7f3e8e2fc9cd  caffe::ReadProtoFromTextFile()
    @     0x7f3e8e2f7f04  caffe::ReadNetParamsFromTextFileOrDie()
    @     0x7f3e8e3472d3  caffe::Net<>::Net()
    @           0x406dc8  Classifier::Classifier()
    @           0x403eab  main
    @     0x7f3e8c858ec5  (unknown)
    @           0x40434e  (unknown)
    @              (nil)  (unknown)

**Comment by ariexhyx** [comment]
I solve it.
I misstake the usage.
Delete the backslash.

**Comment by evgenity** [comment]
I'm seeing the same problem. What kind of backslash was that?

**Comment by inubushi** [comment]
The backslashes are needed when the cvommand is entered as a multi-line command at the prompt, but not so when we just copy and paste it from Caffe's website.

**Comment by FengYanjie1106** [comment]
I am not understand ,could you tell ma ?

**Comment by deepankverma** [comment]
Modify the solver path to absolute rather than relative.

**Comment by LolikaPadmanbhan** [comment]
hi all ,
Getting this error, someone help me please am stuck. why am i getting what i have done wrong?

/caffe-master$ ./build/examples/cpp_classification/classification.bin   models/bvlc_reference_caffenet/deploy.prototxt   models/bvlc_reference_caffenet/bvlc_reference_caffenet.caffemodel   data/ilsvrc12/imagenet_mean.binaryproto   data/ilsvrc12/synset_words.txt   examples/images/cat.jpg
F0704 18:00:11.347486 15734 classification.cpp:62] Check failed: net_->num_inputs() == 1 (0 vs. 1) Network should have exactly one input.
*** Check failure stack trace: ***
    @     0x7f1a5f5475cd  google::LogMessage::Fail()
    @     0x7f1a5f549433  google::LogMessage::SendToLog()
    @     0x7f1a5f54715b  google::LogMessage::Flush()
    @     0x7f1a5f549e1e  google::LogMessageFatal::~LogMessageFatal()
    @           0x408645  Classifier::Classifier()
    @           0x404863  main
    @     0x7f1a5deda830  __libc_start_main
    @           0x404fc9  _start
    @              (nil)  (unknown)
Aborted (core dumped)
thanks
