### ISSUE TITLE
segmentation fault (core dumped) in caffe

### ISSUE THREAD

**Issue by ramkumar-ganesan** [BVLC/caffe#3976]
*** SIGSEGV (@0x0) received by PID 32496 (TID 0x7fe0ba0e9700) from PID 0; stack trace: ***
    @     0x7fe0e4f86d40 (unknown)
    @     0x7fe0e623684a caffe::DataTransformer<>::Transform()
    @     0x7fe0e6236efc caffe::DataTransformer<>::Transform()
    @     0x7fe0e62c8e01 caffe::DataLayer<>::load_batch()
    @     0x7fe0e6270139 caffe::BasePrefetchingDataLayer<>::InternalThreadEntry()
    @     0x7fe0e636b4c0 caffe::InternalThread::entry()
    @     0x7fe0dddfda4a (unknown)
    @     0x7fe0dd6b5182 start_thread
    @     0x7fe0e504a47d (unknown)
    @                0x0 (unknown)
Segmentation fault (core dumped)

**Comment by ramkumar-ganesan** [comment]
Could anyone help me with this issue in caffe ?

**Comment by ShaggO** [comment]
You'll need to give additional information on your system configuration and what was executed. Ideally we should have enough information to replicate the segfault.

**Comment by seanbell** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> When reporting a bug, it's most helpful to provide the following information, where applicable:
> 
> * What steps reproduce the bug?
> * Can you reproduce the bug using the latest [master](https://github.com/BVLC/caffe/tree/master), compiled with the `DEBUG` make option?
> * What hardware and operating system/distribution are you running?
> * If the bug is a crash, provide the backtrace (usually printed by Caffe; always obtainable with `gdb`).

**Comment by ramkumar-ganesan** [comment]
Sorry guys i fixed the issue by clean and build again caffe. I got the issue when i prepared my own customized layer.

**Comment by Shellbye** [comment]
I got here because I missed `make install` & `make runtest`. 😢
