### ISSUE TITLE
Forward_cpu do not execute in new layer

### ISSUE THREAD

**Issue by hs3712993** [BVLC/caffe#3980]
Hi, I write a new layer under the instruction from
https://github.com/BVLC/caffe/wiki/Development#forward-only-layers, that's, three simple steps as follows:
1. declare new_layer_name.hpp in include/caffe/layers
attention this line, register new layers in similar way
INSTANTIATE_CLASS(ReshapeLayer);
REGISTER_LAYER_CLASS(Reshape);
2. implement your layer in layers/new_layer_name.cpp
3. proto/caffe.proto

After compilation, it can run. But it can not print something in Forward_cpu function. I set a breakpoint inside the Forward_cpu, this breakpoint can not be reached. So I guess the code do not run this Forward_cpu function. 
Similar problem occurred for Backward_cpu function. But no problem for LayerSetUp function.
Do any one meet the same problem? How could I solve it?

The head file of new layer is as follows:
template <typename Dtype>
class MyNewLayer : public Layer<Dtype> {
 public:
  explicit MyNewLayer(const LayerParameter& param)
      : Layer<Dtype>(param) {}
  virtual void LayerSetUp(const vector<Blob<Dtype>*>& bottom,
      const vector<Blob<Dtype>*>& top);
  virtual void Reshape(const vector<Blob<Dtype>*>& bottom,
      const vector<Blob<Dtype>*>& top);

  virtual inline const char* type() const { return "EncodeCenter"; }
  virtual inline int ExactNumBottomBlobs() const { return 1; }
  virtual inline int ExactNumTopBlobs() const { return 1; }

 protected:
  virtual void Forward_cpu(const vector<Blob<Dtype>*>& bottom,
      const vector<Blob<Dtype>*>& top);
  virtual void Forward_gpu(const vector<Blob<Dtype>*>& bottom,
      const vector<Blob<Dtype>*>& top) {}
  virtual void Backward_cpu(const vector<Blob<Dtype>*>& top,
      const vector<bool>& propagate_down, const vector<Blob<Dtype>*>& bottom);
  virtual void Backward_gpu(const vector<Blob<Dtype>*>& top,
      const vector<bool>& propagate_down, const vector<Blob<Dtype>*>& bottom) {}
};

**Comment by hs3712993** [comment]
I have find the problem. I solve it by comment
virtual void Forward_gpu(const vector>& bottom, const vector>& top) {}

**Comment by seanbell** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
