### ISSUE TITLE
No appropriate method, property, or field 'reshape_as_input' for class 'caffe.Net'.

### ISSUE THREAD

**Issue by automan000** [BVLC/caffe#3987]
Hello.Sorry to bother. I want to use the matlab interface but run into problems. After finish compiling, I try to run some demo from matlab r2015a but receive error message 'No appropriate method, property, or field 'reshape_as_input' for class 'caffe.Net'.'.Please help me.

**Comment by seanbell** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> When reporting a bug, it's most helpful to provide the following information, where applicable:
> 
> * What steps reproduce the bug?
> * Can you reproduce the bug using the latest [master](https://github.com/BVLC/caffe/tree/master), compiled with the `DEBUG` make option?
> * What hardware and operating system/distribution are you running?
> * If the bug is a crash, provide the backtrace (usually printed by Caffe; always obtainable with `gdb`).

**Comment by seanbell** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
