### ISSUE TITLE
C++ Style Question

### ISSUE THREAD

**Issue by DCurro** [BVLC/caffe#3989]
Hi Caffe Team,

I have a question regarding use of C++ coding style. Why does it seem that set-inputs are preferred to returns?

For example, what was the benefit in making the DataTransformer set the transformed_blob, rather than returning the transformed blob?

How it is now:

`void DataTransformer<Dtype>::Transform(Blob<Dtype>* input_blob, Blob<Dtype>* transformed_blob);`

Alternatively:

`Blob<Dtype>* DataTransformer<Dtype>::Transform(Blob<Dtype>* input_blob);`

I am okay with either way, but I do find the current approach (personally) unintuitive. I was wondering what is the merit in current approach?

**Comment by ajtulloch** [comment]
A bunch of cases (not this one, but perhaps for consistency) come from avoiding output allocations/relying on RVO. Caffe's C++ roughly follows the Google C++ style guide, which has the following:

https://google.github.io/styleguide/cppguide.html#Function_Parameter_Ordering


> When defining a function, parameter order is: inputs, then outputs.
> 
> Parameters to C/C++ functions are either input to the function, output from the function, or both. Input parameters are usually values or const references, while output and input/output parameters will be non-const pointers. When ordering function parameters, put all input-only parameters before any output parameters. In particular, do not add new parameters to the end of the function just because they are new; place new input-only parameters before the output parameters.
