### ISSUE TITLE
Matlab automatically closes when using net.forward

### ISSUE THREAD

**Issue by sepidehhosseinzadeh** [BVLC/caffe#3991]
I want to use net.forward, so, I am doing : 

load caffe/matlab/+caffe/imagenet/ilsvrc_2012_mean.mat; 
alexNet = caffe.Net('caffe/models/bvlc_alexnet/trunc_deploy.prototxt', 'caffe/models/bvlc_alexnet/bvlc_alexnet.caffemodel', 'test');

im_data = im(x:x+h, y:y+w, :); % load image in caffe's data format
im_data = im_data(:, :, [3, 2, 1]); % convert from RGB to BGR
im_data = single(im_data); % convert to single precision

res = alexNet.forward({im_data});

But, terminal's output at the end is: "
W0414 14:00:30.084293  2674 net.hpp:41] DEPRECATED: ForwardPrefilled() will be removed in a future version. Use Forward().    ldb must be >= MAX(N,1): ldb=0 N=0ldc must be >= MAX(N,1): ldc=0 N=0Parameter 11 to routine cblas_sgemm was incorrect"

and matlab closes itself.

Please help!

**Comment by sepidehhosseinzadeh** [comment]
Because when I reshaped the input by  alexNet.blobs('data').reshape([h+1 w+1 3 1]); 
It was trying to reshape a smaller data to a bigger one. So, every time, I load the alexNet again.

**Comment by Destinyzs** [comment]
Have you solved it？i meet the same problem too。
