### ISSUE TITLE
get current solver parameters in pycaffe

### ISSUE THREAD

**Issue by YingChenlu** [BVLC/caffe#3994]
Other guys have already asked this question. But I have not find a good answer. So I ask here again.
Is it possible to get the current parameters from eg an SGDsolver object when working with the python interface? I'd like to trace and print out he learning rate which may update over time depending on lr_policy.
Thank you!

**Comment by seanbell** [comment]
Feel free to PR a mechanism of doing this.

As a workaround, you can parse the log file which includes the learning rate.

**Comment by williford** [comment]
I'm going to close, as this already has open issues:
#2766 
#2686
