### ISSUE TITLE
pycaffe python3.5  compatible?

### ISSUE THREAD

**Issue by jiapei100** [BVLC/caffe#3999]
Hi, 

Is current pycaffe compatible with python3.5?
I met the following error message:
**RefactoringTool: Can't parse ./examples/pycaffe/caffenet.py: ParseError: bad input: type=22, value='=', context=('', (49, 57))**

It looks like the assignment **file=f** on line 49 is buggy:
**print(caffenet('/path/to/caffe-train-lmdb'), file=f)**

How can we adjust this for python3.5?

Cheers
Pei

**Comment by ajtulloch** [comment]
`print` in Python 3 (and with `future.__print_function__`) supports `file=f`: https://docs.python.org/3/library/functions.html#print

Have you tried compiling and running against 3.5 directly? The error you mentioned looks like a bug from 2to3, not a bug in the pycaffe code itself.

**Comment by untom** [comment]
FYI, pycaffe runs fine on my machines using Python 3.5.1

(haven't tried to run that specific example, though)

**Comment by jiapei100** [comment]
Thank you ... Yes, I am using 2to3 ...
`
from __future__ import print_function` 
this is what I added to the file caffenet.py, which seems to have solved my problem...
