### ISSUE TITLE
 Aborted at 1460790785 (unix time) try "date -d @1460790785" if you are using GNU date 

### ISSUE THREAD

**Issue by ashincarl** [BVLC/caffe#4000]
hi 
I'm using WindowData as the input data layer format. Here is the error I get every time:

I0416 15:13:05.601964 14017 window_data_layer.cpp:145] num: 900 /home/if510/Documents/caffe-master/CHUNxiao/_tmp/ECSSD_TrainPadding/0900.jpg 3 798 1200 windows to process: 96
I0416 15:13:05.601981 14017 window_data_layer.cpp:154] Number of images: 901
I0416 15:13:05.601986 14017 window_data_layer.cpp:158] class 0 has 6494 samples
I0416 15:13:05.601990 14017 window_data_layer.cpp:158] class 1 has 2281 samples
I0416 15:13:05.601995 14017 window_data_layer.cpp:162] Amount of context padding: 0
I0416 15:13:05.601999 14017 window_data_layer.cpp:165] Crop mode: warp
I0416 15:13:05.602056 14017 window_data_layer.cpp:177] output data size: 16,3,227,227
I0416 15:13:05.613304 14017 net.cpp:150] Setting up data
I0416 15:13:05.613353 14017 net.cpp:157] Top shape: 16 3 227 227 (2473392)
I0416 15:13:05.613360 14017 net.cpp:157] Top shape: 16 (16)
I0416 15:13:05.613384 14017 net.cpp:165] Memory required for data: 9893632
I0416 15:13:05.613391 14017 layer_factory.hpp:76] Creating layer label_data_1_split
I0416 15:13:05.613404 14017 net.cpp:106] Creating Layer label_data_1_split
I0416 15:13:05.613415 14017 net.cpp:454] label_data_1_split <- label
I0416 15:13:05.613423 14017 net.cpp:411] label_data_1_split -> label_data_1_split_0
I0416 15:13:05.613435 14017 net.cpp:411] label_data_1_split -> label_data_1_split_1
I0416 15:13:05.613602 14017 net.cpp:150] Setting up label_data_1_split
I0416 15:13:05.613629 14017 net.cpp:157] Top shape: 16 (16)
I0416 15:13:05.613636 14017 net.cpp:157] Top shape: 16 (16)
I0416 15:13:05.613641 14017 net.cpp:165] Memory required for data: 9893760
I0416 15:13:05.613646 14017 layer_factory.hpp:76] Creating layer conv1
I0416 15:13:05.613657 14017 net.cpp:106] Creating Layer conv1
I0416 15:13:05.613667 14017 net.cpp:454] conv1 <- data
I0416 15:13:05.613674 14017 net.cpp:411] conv1 -> conv1
I0416 15:13:05.616063 14017 cudnn_conv_layer.cpp:194] Reallocating workspace storage: 221796
I0416 15:13:05.616098 14017 net.cpp:150] Setting up conv1
I0416 15:13:05.616118 14017 net.cpp:157] Top shape: 16 96 111 111 (18925056)
I0416 15:13:05.616124 14017 net.cpp:165] Memory required for data: 85593984
I0416 15:13:05.616137 14017 layer_factory.hpp:76] Creating layer relu1
I0416 15:13:05.616147 14017 net.cpp:106] Creating Layer relu1
I0416 15:13:05.616153 14017 net.cpp:454] relu1 <- conv1
I0416 15:13:05.616159 14017 net.cpp:397] relu1 -> conv1 (in-place)
**\* Aborted at 1460790785 (unix time) try "date -d @1460790785" if you are using GNU date ***
I0416 15:13:05.616494 14017 net.cpp:150] Setting up relu1
I0416 15:13:05.616509 14017 net.cpp:157] Top shape: 16 96 111 111 (18925056)
I0416 15:13:05.616515 14017 net.cpp:165] Memory required for data: 161294208
I0416 15:13:05.616520 14017 layer_factory.hpp:76] Creating layer pool1
I0416 15:13:05.616528 14017 net.cpp:106] Creating Layer pool1
I0416 15:13:05.616533 14017 net.cpp:454] pool1 <- conv1
I0416 15:13:05.616540 14017 net.cpp:411] pool1 -> pool1
PC: @     0x7f43d7d9aaf6 (unknown)
**\* SIGSEGV (@0x445b7fed) received by PID 14017 (TID 0x7f43bdce9700) from PID 1146847213; stack trace: ***
I0416 15:13:05.616756 14017 net.cpp:150] Setting up pool1
I0416 15:13:05.616770 14017 net.cpp:157] Top shape: 16 96 55 55 (4646400)
I0416 15:13:05.616775 14017 net.cpp:165] Memory required for data: 179879808
I0416 15:13:05.616780 14017 layer_factory.hpp:76] Creating layer norm1
I0416 15:13:05.616788 14017 net.cpp:106] Creating Layer norm1
I0416 15:13:05.616793 14017 net.cpp:454] norm1 <- pool1
I0416 15:13:05.616799 14017 net.cpp:411] norm1 -> norm1
    @     0x7f43d7c7fd40 (unknown)
    @     0x7f43d7d9aaf6 (unknown)
I0416 15:13:05.617122 14017 net.cpp:150] Setting up norm1
I0416 15:13:05.617136 14017 net.cpp:157] Top shape: 16 96 55 55 (4646400)
I0416 15:13:05.617141 14017 net.cpp:165] Memory required for data: 198465408
I0416 15:13:05.617146 14017 layer_factory.hpp:76] Creating layer conv2
I0416 15:13:05.617156 14017 net.cpp:106] Creating Layer conv2
I0416 15:13:05.617161 14017 net.cpp:454] conv2 <- norm1
I0416 15:13:05.617168 14017 net.cpp:411] conv2 -> conv2
    @     0x7f43d8e346ea std::pair<>::pair()
    @     0x7f43d8e36389 caffe::WindowDataLayer<>::load_batch()
    @     0x7f43d8e5922c caffe::BasePrefetchingDataLayer<>::InternalThreadEntry()
    @     0x7f43d8d71d30 caffe::InternalThread::entry()
    @     0x7f43cf4fca4a (unknown)
    @     0x7f43cbd03182 start_thread
    @     0x7f43d7d4347d (unknown)
    @                0x0 (unknown)

Anyhelp will be useful, thanks!

CHUNxiao

**Comment by seanbell** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> When reporting a bug, it's most helpful to provide the following information, where applicable:
> 
> * What steps reproduce the bug?
> * Can you reproduce the bug using the latest [master](https://github.com/BVLC/caffe/tree/master), compiled with the `DEBUG` make option?
> * What hardware and operating system/distribution are you running?
> * If the bug is a crash, provide the backtrace (usually printed by Caffe; always obtainable with `gdb`).

**Comment by pengyulong** [comment]
hi,
  I was run the demo for ssd.
run "python ./example/ssd/ssd_pascal.py" meet this aborted.

I0908 11:16:24.929577 21974 layer_factory.hpp:77] Creating layer data
I0908 11:16:24.929716 21974 net.cpp:100] Creating Layer data
I0908 11:16:24.929728 21974 net.cpp:408] data -> data
I0908 11:16:24.929757 21974 net.cpp:408] data -> label
I0908 11:16:24.930238 21987 db_lmdb.cpp:35] Opened lmdb /home/vino/data/VOCdevkit/VOC0712/lmdb/VOC0712_trainval_lmdb
I0908 11:16:25.930119 21974 annotated_data_layer.cpp:62] output data size: 1,3,300,300
I0908 11:16:25.933876 21974 net.cpp:150] Setting up data
I0908 11:16:25.933899 21974 net.cpp:157] Top shape: 1 3 300 300 (270000)
I0908 11:16:25.933905 21974 net.cpp:157] Top shape: 1 1 4 8 (32)
I0908 11:16:25.933926 21974 net.cpp:165] Memory required for data: 1080128
I0908 11:16:25.933938 21974 layer_factory.hpp:77] Creating layer data_data_0_split
I0908 11:16:25.933954 21974 net.cpp:100] Creating Layer data_data_0_split
I0908 11:16:25.933961 21974 net.cpp:434] data_data_0_split <- data
I0908 11:16:25.933974 21974 net.cpp:408] data_data_0_split -> data_data_0_split_0
I0908 11:16:25.933986 21974 net.cpp:408] data_data_0_split -> data_data_0_split_1
I0908 11:16:25.933995 21974 net.cpp:408] data_data_0_split -> data_data_0_split_2
I0908 11:16:25.934006 21974 net.cpp:408] data_data_0_split -> data_data_0_split_3
I0908 11:16:25.934015 21974 net.cpp:408] data_data_0_split -> data_data_0_split_4
I0908 11:16:25.934022 21974 net.cpp:408] data_data_0_split -> data_data_0_split_5
I0908 11:16:25.934029 21974 net.cpp:408] data_data_0_split -> data_data_0_split_6
I0908 11:16:25.934105 21974 net.cpp:150] Setting up data_data_0_split
I0908 11:16:25.934113 21974 net.cpp:157] Top shape: 1 3 300 300 (270000)
I0908 11:16:25.934119 21974 net.cpp:157] Top shape: 1 3 300 300 (270000)
I0908 11:16:25.934126 21974 net.cpp:157] Top shape: 1 3 300 300 (270000)
I0908 11:16:25.934132 21974 net.cpp:157] Top shape: 1 3 300 300 (270000)
I0908 11:16:25.934137 21974 net.cpp:157] Top shape: 1 3 300 300 (270000)
I0908 11:16:25.934144 21974 net.cpp:157] Top shape: 1 3 300 300 (270000)
I0908 11:16:25.934149 21974 net.cpp:157] Top shape: 1 3 300 300 (270000)
I0908 11:16:25.934154 21974 net.cpp:165] Memory required for data: 8640128
I0908 11:16:25.934157 21974 layer_factory.hpp:77] Creating layer conv1_1
I0908 11:16:25.934173 21974 net.cpp:100] Creating Layer conv1_1
I0908 11:16:25.934177 21974 net.cpp:434] conv1_1 <- data_data_0_split_0
I0908 11:16:25.934185 21974 net.cpp:408] conv1_1 -> conv1_1
*** Aborted at 1504840586 (unix time) try "date -d @1504840586" if you are using GNU date ***
PC: @     0x7f16c9e815f3 (unknown)
*** SIGSEGV (@0x58) received by PID 21974 (TID 0x7f170f4a3a80) from PID 88; stack trace: ***
    @     0x7f170c7294b0 (unknown)
    @     0x7f16c9e815f3 (unknown)
    @     0x7f16ca47bf9d (unknown)
    @     0x7f16c9e84c24 (unknown)
    @     0x7f16c9e86391 (unknown)
    @     0x7f16c9e7caec __cuda_CallJitEntryPoint
    @     0x7f16d21bb5c2 fatBinaryCtl_Compile
    @     0x7f16d25a1ee2 (unknown)
    @     0x7f16d25a2a63 (unknown)
    @     0x7f16d24fb22e (unknown)
    @     0x7f16d24fb510 (unknown)
    @     0x7f16fcaa268d (unknown)
    @     0x7f16fca980b0 (unknown)
    @     0x7f16fcaa5906 (unknown)
    @     0x7f16fcaa8f11 (unknown)
    @     0x7f16fca9ca7c (unknown)
    @     0x7f16fca892d2 (unknown)
    @     0x7f16fcabea4f (unknown)
    @     0x7f16fc56c714 cudnnCreate
    @     0x7f170e7e0e51 caffe::CuDNNConvolutionLayer<>::LayerSetUp()
    @     0x7f170e63e8f2 caffe::Net<>::Init()
    @     0x7f170e640181 caffe::Net<>::Net()
    @     0x7f170e6d067a caffe::Solver<>::InitTrainNet()
    @     0x7f170e6d1977 caffe::Solver<>::Init()
    @     0x7f170e6d1d1a caffe::Solver<>::Solver()
    @     0x7f170e6e55a3 caffe::Creator_SGDSolver<>()
    @           0x40afb9 train()
    @           0x4077c8 main
    @     0x7f170c714830 __libc_start_main
    @           0x408099 _start
    @                0x0 (unknown)
Segmentation fault (core dumped)

and my os is ubuntun16.04,opencv_version=3.1.0,cuda_version=8.0,cudnn_version=5.1,GTX1060.
and I run the mnist demo is ok.

**Comment by baiyancheng20** [comment]
Have you solved this problem? I also met with this problem.

**Comment by pengyulong** [comment]
No,I changed computer with the same enviroment, this problem dismiss.
