### ISSUE TITLE
the imported project ...\CUDA 7.5.props was not found -- windows install

### ISSUE THREAD

**Issue by rshpeley** [BVLC/caffe#4001]
After getting the latest windows caffe, I get the error after starting a build from `.\windows\Caffe.sln`,

```
error MSB4019: The imported project
"C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\BuildCustomizations\CUDA 7.5.props" was
not found. Confirm that the path in the <Import> declaration is correct, and that the file exists
on disk. C:\Users\Raymond\caffe-windows\windows\libcaffe\libcaffe.vcxproj	42	5	caffe
```
The` libcaffe.vcxprog` file has the related `<Import>` declaration on line 42,

`<Import Project="$(VCTargetsPath)\BuildCustomizations\CUDA $(CudaVersion).props" />`

I've found `CUDA 7.5.props` at 
`"C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\BuildCustomizations"`. 

That means the `VCTargetsPath` is pointing to 
`"C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120"` and not 
`"C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0"` 

I don't have admin rights on this workstation and so I can't just copy the file over.

<hr>

CUDA toolkit 7.5, cuDNN 4, windows 10.

I've attached my CommonSettings.props file with a txt extension to upload it.

[CommonSettings.props.txt](https://github.com/BVLC/caffe/files/222405/CommonSettings.props.txt)

**Comment by Armixy** [comment]
I have gotten the same error, please make sure you have installed Visual Studio 2013, and then install CUDA7.5 again, make sure the install program can detect the Visual Studio 2013. Then this problem will be fixed

**Comment by rshpeley** [comment]
Thanks, but I am using visual studio 2013. I'll check if I can reinstall
cuda 7.5 again, but as I said I don't have admin rights.
--

**Comment by seanbell** [comment]
Please ask installation questions on the mailing list.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

**Comment by rshpeley** [comment]
Just want to confirm this is an install problem. The cuda 7.5 toolkit does not support vs2010, which is what nsight was previously configured for when 7.5 was installed, so it never set up properly. Files were put in a null PlatformToolset path instead of v120 and $(VCTargetsPath) was null.

Sean, I originally posted this issue because it was a build error that came up. It's still a build problem but related to install issues with cuda and visual studio as Armixy pointed out.

**Comment by hukangrong** [comment]
I use VS2015 to built it, whether It don't support VS2015?

**Comment by willyd** [comment]
No VS 2015 is not supported yet as the official CUDA 7.5 does not support it. When CUDA 8 is officially out we will start support VS 2015.

**Comment by hukangrong** [comment]
Thanks, maybe I need to use Vs2013 to deal with the problem.

**Comment by willyd** [comment]
Indeed, VS 2013 is the only supported compiler on Windows at this time.

**Comment by XunOuyang** [comment]
@willyd  , I have VS 2015 installed, and CUDA 8 does not support it. I got the same error as "CUDA 7.5.props was not found", well, but I did not have 7.5 installed on my computer. I got CUDA8. Should I uninstall the CUDA 7.5 ?

**Comment by willyd** [comment]
@XunOuyang As stated in the [README](https://github.com/BVLC/caffe/tree/windows#previous-visual-studio-based-build)

 > The previous windows build based on Visual Studio project files is now deprecated. However, it is still available in the windows folder. Please see the README.md in there for details.

You the CMake build with the build_win.cmd script instead.

**Comment by XunOuyang** [comment]
@willyd  ah ha, thank you very much. I should read the README.md and follow the offical guidance first. ^_^.
