### ISSUE TITLE
Problem 

### ISSUE THREAD

**Issue by eloyacosta** [BVLC/caffe#4006]
I got that error while trying to compile Caffe. 

What can be the problem?

```
Linking CXX executable cpp_classification/classification
[100%] Built target classification
/PHShome/ez957/work/Feb10_2016_caffe/caffe/python/caffe/_caffe.cpp: In function ‘void caffe::Net_SetInputArrays(caffe::Net<float>*, boost::python::api::object, boost::python::api:
:object)’:
/PHShome/ez957/work/Feb10_2016_caffe/caffe/python/caffe/_caffe.cpp:131: error: invalid static_cast from type ‘char*’ to type ‘caffe::Dtype*’
/PHShome/ez957/work/Feb10_2016_caffe/caffe/python/caffe/_caffe.cpp:132: error: invalid static_cast from type ‘char*’ to type ‘caffe::Dtype*’
make[2]: *** [python/CMakeFiles/pycaffe.dir/caffe/_caffe.cpp.o] Error 1
make[1]: *** [python/CMakeFiles/pycaffe.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by seanbell** [comment]
The relevant lines: https://github.com/BVLC/caffe/blob/master/python/caffe/_caffe.cpp#L131-L132

What OS/platform are you on, and what version of numpy are you using?

The docs for the offending function `PyArray_DATA` (http://docs.scipy.org/doc/numpy/reference/c-api.array.html) say that `PyArray_DATA` returns `void*`, which should be safe to `static_cast` to anything.

**Comment by eloyacosta** [comment]
I have finally succeeded by using boost 1.55 instead of 1.59... 
By the way, I'm running 
- redhat 6.5
- numpy 1.9
- Python 2.7.3

I've installed python and numpy by myself, should I better install anaconda? what would you recommend?

**Comment by eloyacosta** [comment]
Thank you so much @seanbell
