### ISSUE TITLE
How to train model in c++

### ISSUE THREAD

**Issue by zdczdcc** [BVLC/caffe#4011]
I have some multi_labels to classify,i want to train the model in c++.Is there any way to do this?

**Comment by seanbell** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
