### ISSUE TITLE
 .build_release/lib/libcaffe.so: undefined reference to `_Py_NoneStruct'

### ISSUE THREAD

**Issue by shwetgarg** [BVLC/caffe#4016]
Hello,

I have successfully installed the standard apollocaffe (http://apollocaffe.com/), but i need this one (https://github.com/jacobandreas/apollocaffe) for my work. This insallation is giving me attached error with and without anaconda both. Has anyone tried it or faced similar issues ? Please help me, I am stuck on this issue since last few days.

Regards,
Shweta

Error is :
.build_release/lib/libcaffe.so: undefined reference to `_Py_NoneStruct'
collect2: error: ld returned 1 exit status
make: *** [.build_release/tools/upgrade_net_proto_text.bin] Error 1
make: *** Waiting for unfinished jobs....
.build_release/lib/libcaffe.so: undefined reference to `_Py_NoneStruct'
collect2: error: ld returned 1 exit status
make: *** [.build_release/tools/upgrade_net_proto_binary.bin] Error 1
.build_release/lib/libcaffe.so: undefined reference to `_Py_NoneStruct'
collect2: error: ld returned 1 exit status
make: *** [.build_release/tools/caffe.bin] Error 1
.build_release/lib/libcaffe.so: undefined reference to `_Py_NoneStruct'
collect2: error: ld returned 1 exit status
make: *** [.build_release/tools/compute_image_mean.bin] Error 1
.build_release/lib/libcaffe.so: undefined reference to `_Py_NoneStruct'
collect2: error: ld returned 1 exit status
make: *** [.build_release/examples/cifar10/convert_cifar_data.bin] Error 1
.build_release/lib/libcaffe.so: undefined reference to `_Py_NoneStruct'
collect2: error: ld returned 1 exit status
make: *** [.build_release/examples/cpp_classification/classification.bin] Error 1
.build_release/lib/libcaffe.so: undefined reference to `_Py_NoneStruct'
.build_release/lib/libcaffe.so: undefined reference to `_Py_NoneStruct'
collect2: error: ld returned 1 exit status
collect2: error: ld returned 1 exit status
make: *** [.build_release/tools/extract_features.bin] Error 1
make: *** [.build_release/tools/convert_imageset.bin] Error 1

**Comment by seanbell** [comment]
Please ask the maintainers of `apollocaffe`.  This question seems unrelated to BVLC/caffe.
