### ISSUE TITLE
Caffe Installation 

### ISSUE THREAD

**Issue by ashutosh3308** [BVLC/caffe#4019]
I have a question regarding the caffe. I am using GoogleNet model for binary classification of my images. Earlier, I was using virtual machine and now I am using Ubuntu 14.04. Both are giving me different results. I tried to find out a lot where is the problem but couldnt succeed it. Any suggestions would be of great help.

**Comment by seanbell** [comment]
How are the results different?

**Comment by ashutosh3308** [comment]
I tried to find this answer but couldnt succeed. Do you think there might be installation problem?

**Comment by ashutosh3308** [comment]
And, if I run my model in virtual machine which I used in Ubuntu 14.04. I get the same results as of virtual machine.

**Comment by seanbell** [comment]
You haven't given us enough information to help you.  Were the two models trained separately?  Are both models using CPU? GPU?  Is cuDNN being used?  If so, which version?  What caffe version are you using?  If using CPU, are you using any BLAS libraries?

**Comment by ashutosh3308** [comment]
I have trained two models separately one in Ubuntu 14.04 and in virtual machine. 
Both models are using CPU.  cuDNN is not being used in both. Regarding BLAS library I am using default ATLAS. Please see the snapshot below.

![screenshot from 2016-04-20 15 44 08](https://cloud.githubusercontent.com/assets/18398620/14676864/8f4afd5c-070f-11e6-929c-e13a79bca5d8.png)
![screenshot from 2016-04-20 15 44 43](https://cloud.githubusercontent.com/assets/18398620/14676863/8f4ac18e-070f-11e6-8a23-917540292a38.png)

**Comment by ashutosh3308** [comment]
I am sorry for asking this simple question, but how to find out the version of caffe. And if you need any more information, please do let me know.

**Comment by machomachopadre** [comment]
Hi ashutosh. I am a bit confused with your question. Have you used googlenet (by this i assume tensorflow)  and caffe both and you are getting different results? What is different? And regarding your last comment, you seem to be saying something about caffe versions? Im sorry I couldnt help you with this reply but I would request you to frame your question better. Thanks!!!
Peace out :v:

**Comment by machomachopadre** [comment]
and could you please send a snap of your whole makefile?

**Comment by ashutosh3308** [comment]
Hi,

Please find my make file below in the attachment.
 
I am using GoogLeNet model for binary classification of my images. And I installed Caffe on three different machines, such as MAC, Linux and Windows. On windows I used virtual machine to install caffe. When I am training my model on these 3 different machines I am getting different results (different accuracies) and the difference between these accuracies are huge. 
Any suggestions would be of great help.


[MakeFile.txt](https://github.com/BVLC/caffe/files/279085/MakeFile.txt)

**Comment by ashutosh3308** [comment]
If you need any more information, I would be happy to provide more information.

**Comment by agarie** [comment]
@ashutosh3308 you probably should write a gist ([click here](https://gist.github.com/)) with everything you did on each of your machines. Right now it's almost impossible to deduce what could be wrong (if any) with your setup. :(

* You said you installed Caffe on a Mac, a computer with Linux and a VM running under Windows. How did you install Atlas on each one?
* Can you post the output you get from each of your machines?
* Can you post the commands you are using to run the GoogLeNet model? Just to make sure there isn't any difference in this.

**Comment by shelhamer** [comment]
Please ask installation and configuration questions on the mailing list. Consider [Docker installation](https://github.com/BVLC/caffe/tree/master/docker) if you have trouble installing on  your own.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
