### ISSUE TITLE
How to compute mean_file of imagedata type input?

### ISSUE THREAD

**Issue by warmestwind** [BVLC/caffe#4025]
I know how to compute mean_file of  data type input,but i don't know how to compute mean_file of imagedata type input. Must I convert images to lmdb or leveldb then compute  mean_file? Is there any way to compute mean_file from images directly? Thanks to give me some advice！

**Comment by seanbell** [comment]
Sure, you could just load the images and compute their mean.  Note that the exact mean isn't that important unless your images are very atypical.  You can use the mean from ImageNet and it will work just fine for other datasets.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
