### ISSUE TITLE
there is a very very small mistake in your caffe homepage

### ISSUE THREAD

**Issue by HeGaoYuan** [BVLC/caffe#4029]
In your caffe homepage,  in the LeNet MNIST Tutorial,  there is a sentence  in the Training and Testing the Model section, 

> Based on the solver setting, we will print the training loss function every 100 iterations, and test the network every 1000 iterations. You will see messages like this:

You said test the network every **1000** iterations, but actually you test the network every **500** iterations.

This is a very very small mistake, but I hope it is helpful for newer.

**Comment by seanbell** [comment]
Thanks for the catch -- please submit a PR making this change (to this file: https://github.com/BVLC/caffe/blob/master/examples/mnist/readme.md)

**Comment by seanbell** [comment]
Closing since a fix is in #4033
