### ISSUE TITLE
1d signal feature learning

### ISSUE THREAD

**Issue by LudoAcciai** [BVLC/caffe#4030]
How is possible to extract 1d signal features in unsupervised way?

**Comment by seanbell** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
