### ISSUE TITLE
If i use .jpg file to test, accuracy is different with lmdb case. (file list is exactly same.)

### ISSUE THREAD

**Issue by oanoelsis** [BVLC/caffe#4035]
I doing CNN image classification with caffe.

I encountered very weird thing. If i test my trained network with test lmdb accuracy is 98%, but when I test my trained network with .jpg files (exactly same files with test lmdb) accuracy is 95%... (I use cpp_classification example in caffe library, i just edited it little and not core part.) I don't know why this happen. (and nvidia DIGITS result is same with lmdb result, only c++ jpg file classification result is different.)

I checked my c++ classification code's cv::resize is same with what caffe doing at convert_imageset.

And i have really no idea why this is happen..

please hlp me..

**Comment by seanbell** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> When reporting a bug, it's most helpful to provide the following information, where applicable:
> 
> * What steps reproduce the bug?
> * Can you reproduce the bug using the latest [master](https://github.com/BVLC/caffe/tree/master), compiled with the `DEBUG` make option?
> * What hardware and operating system/distribution are you running?
> * If the bug is a crash, provide the backtrace (usually printed by Caffe; always obtainable with `gdb`).

**Comment by bhack** [comment]
There is also  https://github.com/BVLC/caffe/issues/3739

**Comment by oanoelsis** [comment]
I think this problem caused by /example/cpp_classificatioin/classification.cpp doing mean pixel value subtraction rather than mean image subtraction. I did mean image subtraction at train stage, because I didn't do crop. But this cpp_classification example is for imagenet and that doing crop. so i think this is the reason of the problem....
