### ISSUE TITLE
I have successfully run Caffe on Ubuntu. How can i running caffe on Windows vs2013?

### ISSUE THREAD

**Issue by plamecode** [BVLC/caffe#4037]
I want to running my trained file(trained file with ubuntu) on windows vs2013 
help me step by step.
it's so difficult for me. give your knowledge to me.

**Comment by seanbell** [comment]
You could try using the windows branch (https://github.com/BVLC/caffe/tree/windows).

Please ask usage/installation questions on the mailing list.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
