### ISSUE TITLE
Low accuracy (11%) on mnist with gpu

### ISSUE THREAD

**Issue by nnnrpq** [BVLC/caffe#4038]
Hi everyone, I am new to caffe and I have already compiled the [Microsoft windows version](https://github.com/Microsoft/caffe) with VS2013 community, Matlab 2015a, CUDA 7.5 and cuDNN v4. My PC is Win10 with GTX 765M. The compilation is successful without error.

The problem is that when I try to run the mnist example, I can get reasonable accuracy with CPU training (0.97 accuracy after 500 iterations). However, when I turn to GPU mode, it only gives 0.11 accuracy even after 10000 iterations. This is the same whether I use bat and run caffe.exe or run the corresponding matlab wrapper.

In both Cpu and Gpu mode, the solver and network structure is just the lenet in /example/mnist/. The log file for gpu training is attched.

[log_gpu.txt](https://github.com/BVLC/caffe/files/233292/log_gpu.txt)

If anyone has encountered similar problem, please help me out. Thank you!

**Comment by seanbell** [comment]
I'm closing this since your issue is with Microsoft/caffe and not BVLC/caffe (this repository).
