### ISSUE TITLE
I attempt to running caffe on windows vs2013 but i have some problem

### ISSUE THREAD

**Issue by plamecode** [BVLC/caffe#4039]
when i was build with caffe.sln with vs2013  i have some problem.
please give me advice. the error is this

LINK : fatal error LNK1104: cannot open input file 'libcaffe.lib'
and
C:\Users\kks\Desktop\caffe-master\caffe-master\include\caffe/util/rng.hpp : error C2220: warning treated as error is generated 'object' file does not exist.

**Comment by seanbell** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
