### ISSUE TITLE
Deconvolution layer not working in python interface

### ISSUE THREAD

**Issue by young-geng** [BVLC/caffe#4052]
When using python `NetSpec` to generate network prototxt, `layers.Deconvolution` would not accept any parameters. It produces this error: `AttributeError: 'LayerParameter' object has no attribute 'stride'`

A quick look through the source code indicates that this is likely caused by [the python interface getting the all the layer names by listing the fields of `LayerParameter` message in the protobuf.](https://github.com/BVLC/caffe/blob/master/python/caffe/net_spec.py#L35) However, since deconv layers uses `ConvolutionParameter`, it does not have a `DeconvolutionParameter` message and hence won't be listed in the python interface.

I've also uploaded a piece of code that would trigger the problem, and you can find it [here](https://gist.github.com/young-geng/96118be89636cbd5cd72ec58f6d3725f).

**Comment by shelhamer** [comment]
For these cases you explicitly include the relevant param in the net spec:

```
n.deconv = L.Deconvolution(n.input, 
    convolution_param=dict(num_output=21, kernel_size=64, stride=32))
```

See this example: https://github.com/shelhamer/fcn.berkeleyvision.org/blob/master/voc-fcn32s/net.py#L58-L61

Thanks for including all the details in your post, but this is working as expected. See #3954 for an extension that makes `Deconvolution` inherit the `convolution_param` to work as you have suggested.

**Comment by seanbell** [comment]
@shelhamer maybe #3954 should be merged, if it doesn't break anything?
