### ISSUE TITLE
making project after caffe windows successful compiling 

### ISSUE THREAD

**Issue by orientio** [BVLC/caffe#4053]
hello all

i am completely new to caffe. i am trying to use deep-learning in C++ project in vs winows.
i have successfully complied caffe windows with vs 2013 - windows 7. 
now i want to make new project to use caffe. however i do not have any idea how i should do that.
i mean where to create the project, how to include caffe required library and headers and ...

i would be please if someone can provide me an step by step instruction or reference in this regard.

thanks a lot

**Comment by seanbell** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
