### ISSUE TITLE
 undefined reference to `lzma_index_end@XZ_5.0'

### ISSUE THREAD

**Issue by neouyghur** [BVLC/caffe#4060]
/usr/lib/x86_64-linux-gnu/libunwind.so.8: undefined reference to `lzma_index_end@XZ_5.0'
/usr/lib/x86_64-linux-gnu/libunwind.so.8: undefined reference to`lzma_index_size@XZ_5.0'
/usr/lib/x86_64-linux-gnu/libunwind.so.8: undefined reference to `lzma_index_buffer_decode@XZ_5.0'
/usr/lib/x86_64-linux-gnu/libunwind.so.8: undefined reference to`lzma_stream_footer_decode@XZ_5.0'
/usr/lib/x86_64-linux-gnu/libunwind.so.8: undefined reference to `lzma_stream_buffer_decode@XZ_5.0'
/usr/lib/x86_64-linux-gnu/libunwind.so.8: undefined reference to`lzma_index_uncompressed_size@XZ_5.0'
collect2: error: ld returned 1 exit status
tools/CMakeFiles/finetune_net.dir/build.make:133: recipe for target 'tools/finetune_net' failed
make[2]: **\* [tools/finetune_net] Error 1
CMakeFiles/Makefile2:435: recipe for target 'tools/CMakeFiles/finetune_net.dir/all' failed
make[1]: **\* [tools/CMakeFiles/finetune_net.dir/all] Error 2
/usr/lib/x86_64-linux-gnu/libunwind.so.8: undefined reference to `lzma_index_end@XZ_5.0'
/usr/lib/x86_64-linux-gnu/libunwind.so.8: undefined reference to`lzma_index_size@XZ_5.0'
/usr/lib/x86_64-linux-gnu/libunwind.so.8: undefined reference to `lzma_index_buffer_decode@XZ_5.0'
/usr/lib/x86_64-linux-gnu/libunwind.so.8: undefined reference to`lzma_stream_footer_decode@XZ_5.0'
/usr/lib/x86_64-linux-gnu/libunwind.so.8: undefined reference to `lzma_stream_buffer_decode@XZ_5.0'
/usr/lib/x86_64-linux-gnu/libunwind.so.8: undefined reference to`lzma_index_uncompressed_size@XZ_5.0'
collect2: error: ld returned 1 exit status
tools/CMakeFiles/net_speed_benchmark.dir/build.make:133: recipe for target 'tools/net_speed_benchmark' failed
make[2]: **\* [tools/net_speed_benchmark] Error 1
CMakeFiles/Makefile2:625: recipe for target 'tools/CMakeFiles/net_speed_benchmark.dir/all' failed
make[1]: **\* [tools/CMakeFiles/net_speed_benchmark.dir/all] Error 2
/usr/lib/x86_64-linux-gnu/libunwind.so.8: undefined reference to `lzma_index_end@XZ_5.0'
/usr/lib/x86_64-linux-gnu/libunwind.so.8: undefined reference to`lzma_index_size@XZ_5.0'
/usr/lib/x86_64-linux-gnu/libunwind.so.8: undefined reference to `lzma_index_buffer_decode@XZ_5.0'
/usr/lib/x86_64-linux-gnu/libunwind.so.8: undefined reference to`lzma_stream_footer_decode@XZ_5.0'
/usr/lib/x86_64-linux-gnu/libunwind.so.8: undefined reference to `lzma_stream_buffer_decode@XZ_5.0'
/usr/lib/x86_64-linux-gnu/libunwind.so.8: undefined reference to`lzma_index_uncompressed_size@XZ_5.0'
collect2: error: ld returned 1 exit status
tools/CMakeFiles/train_net.dir/build.make:133: recipe for target 'tools/train_net' failed
make[2]: **\* [tools/train_net] Error 1
CMakeFiles/Makefile2:511: recipe for target 'tools/CMakeFiles/train_net.dir/all' failed
make[1]: **\* [tools/CMakeFiles/train_net.dir/all] Error 2
/usr/lib/x86_64-linux-gnu/libunwind.so.8: undefined reference to `lzma_index_end@XZ_5.0'
/usr/lib/x86_64-linux-gnu/libunwind.so.8: undefined reference to`lzma_index_size@XZ_5.0'
/usr/lib/x86_64-linux-gnu/libunwind.so.8: undefined reference to `lzma_index_buffer_decode@XZ_5.0'
/usr/lib/x86_64-linux-gnu/libunwind.so.8: undefined reference to`lzma_stream_footer_decode@XZ_5.0'
/usr/lib/x86_64-linux-gnu/libunwind.so.8: undefined reference to `lzma_stream_buffer_decode@XZ_5.0'
/usr/lib/x86_64-linux-gnu/libunwind.so.8: undefined reference to`lzma_index_uncompressed_size@XZ_5.0'
collect2: error: ld returned 1 exit status
tools/CMakeFiles/test_net.dir/build.make:133: recipe for target 'tools/test_net' failed
make[2]: **\* [tools/test_net] Error 1
CMakeFiles/Makefile2:549: recipe for target 'tools/CMakeFiles/test_net.dir/all' failed
make[1]: **\* [tools/CMakeFiles/test_net.dir/all] Error 2
[ 90%] Linking CXX executable extract_features
/usr/lib/x86_64-linux-gnu/libunwind.so.8: undefined reference to `lzma_index_size@XZ_5.0'
/usr/lib/x86_64-linux-gnu/libunwind.so.8: undefined reference to`lzma_stream_footer_decode@XZ_5.0'
/usr/lib/x86_64-linux-gnu/libunwind.so.8: undefined reference to `lzma_index_uncompressed_size@XZ_5.0'
/usr/lib/x86_64-linux-gnu/libunwind.so.8: undefined reference to`lzma_stream_buffer_decode@XZ_5.0'
/usr/lib/x86_64-linux-gnu/libunwind.so.8: undefined reference to `lzma_index_buffer_decode@XZ_5.0'
/usr/lib/x86_64-linux-gnu/libunwind.so.8: undefined reference to`lzma_index_end@XZ_5.0'
collect2: error: ld returned 1 exit status
tools/CMakeFiles/extract_features.dir/build.make:133: recipe for target 'tools/extract_features' failed
make[2]: **\* [tools/extract_features] Error 1
CMakeFiles/Makefile2:701: recipe for target 'tools/CMakeFiles/extract_features.dir/all' failed
make[1]: **\* [tools/CMakeFiles/extract_features.dir/all] Error 2
[ 90%] Linking CXX executable caffe
/usr/lib/x86_64-linux-gnu/libunwind.so.8: undefined reference to `lzma_index_size@XZ_5.0'
/usr/lib/x86_64-linux-gnu/libunwind.so.8: undefined reference to`lzma_stream_footer_decode@XZ_5.0'
/usr/lib/x86_64-linux-gnu/libunwind.so.8: undefined reference to `lzma_index_uncompressed_size@XZ_5.0'
/usr/lib/x86_64-linux-gnu/libunwind.so.8: undefined reference to`lzma_stream_buffer_decode@XZ_5.0'
/usr/lib/x86_64-linux-gnu/libunwind.so.8: undefined reference to `lzma_index_buffer_decode@XZ_5.0'
/usr/lib/x86_64-linux-gnu/libunwind.so.8: undefined reference to`lzma_index_end@XZ_5.0'
collect2: error: ld returned 1 exit status
tools/CMakeFiles/caffe.bin.dir/build.make:133: recipe for target 'tools/caffe' failed
make[2]: **\* [tools/caffe] Error 1
CMakeFiles/Makefile2:587: recipe for target 'tools/CMakeFiles/caffe.bin.dir/all' failed
make[1]: **\* [tools/CMakeFiles/caffe.bin.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: **\* [all] Error 2

**Comment by seanbell** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> When reporting a bug, it's most helpful to provide the following information, where applicable:
> 
> * What steps reproduce the bug?
> * Can you reproduce the bug using the latest [master](https://github.com/BVLC/caffe/tree/master), compiled with the `DEBUG` make option?
> * What hardware and operating system/distribution are you running?
> * If the bug is a crash, provide the backtrace (usually printed by Caffe; always obtainable with `gdb`).

**Comment by neouyghur** [comment]
as we know we could build caffe with two different option, one is make, another is cmake. In my problem, I always use cmake, and the problem have not solved in the end. Before I give up, I have used the make build, it have succeed.  Is it the problem of CMAKE configuration. Hope someone could answer this.

**Comment by manojpkr** [comment]
I face the same issue, albeit few nuances in the error message. 
```

//usr/lib/x86_64-linux-gnu/libavcodec-ffmpeg.so.56: undefined reference to `lzma_end@XZ_5.0'
collect2: error: ld returned 1 exit status
tools/CMakeFiles/upgrade_solver_proto_text.dir/build.make:128: recipe for target 'tools/upgrade_solver_proto_text' failed
make[2]: *** [tools/upgrade_solver_proto_text] Error 1
CMakeFiles/Makefile2:473: recipe for target 'tools/CMakeFiles/upgrade_solver_proto_text.dir/all' failed
make[1]: *** [tools/CMakeFiles/upgrade_solver_proto_text.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

I am using CMAKE. I have used the latest master. Unfortunately, I do not have debug enabled!

**Comment by shelhamer** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
