### ISSUE TITLE
System reboot after net.forward()

### ISSUE THREAD

**Issue by aghagol** [BVLC/caffe#4061]
I'm not sure what is the source of this problem (CUDA? hardware?) so I was hoping to get some feedback here. 

I'm using a pretrained Places205-AlexNet for testing (caffemodel and prototxt from http://places.csail.mit.edu/) using the python interface. 

The problem happens when I increase the batch size to 1000. I can load the images with `net.blobs['data'].data[...]=images` without problem. But the computer immediately reboots as soon as I do `net.forward()`. 

Has anyone experienced this? 

GPU is Titan X and I have Ubuntu 14.04, CUDA 7.5, CuDNNv4. No problem with small batch sizes (10 or smaller). I don't think this is an insufficient power issue since I have upgraded the PC (because of these restarts!) and it supports up to 300W for GPU (more than the 250W requirement of Titan X). I don't suppose this is a memory issue either since I'm not getting any memory errors. I can't find anything in the Ubuntu system logs about the cause of reboot. 

Help is very much appreciated!

**Comment by seanbell** [comment]
It could be an overheating problem?

**Comment by aghagol** [comment]
Oh I should have mentioned heating as a possible contender. But that is unlikely. Before I run `net.forward()`, `nvidia-smi` shows 41C which is normal. After I run `net.forward()`? Everything goes black! I really doubt the temperature could rise to more than 90C in a fraction of a (milli)second (or am I wrong?). Thanks.

**Comment by leonid-pishchulin** [comment]
I have very similar issue: after a few thousands training iterations system reboots. I use Nvidia Titan X Pascal and Cuda 8.0 on Ubuntun 14.04

**Comment by aghagol** [comment]
Well mine is probably different from yours @leonid-pishchulin . I solved it by putting the Nvidia Titan X GPU in a new desktop computer with a 1200W PSU and upgraded hardware. I could not even start training or testing with large batch sizes.

**Comment by LiberiFatali** [comment]
I also get this issue, when using Yahoo nsfw model to classify images.

**Comment by LiberiFatali** [comment]
I solved mine by switching to openblas (I was using atlas).

**Comment by DEUCEZ** [comment]
What is openblas? And do I find it?

**Comment by LiberiFatali** [comment]
@DEUCEZ if you use default Makefile.config, you already use atlas. No need to find openblas.
