### ISSUE TITLE
Reason behind Increased Accuracy in Digit Recognizer by increasing the test iterations

### ISSUE THREAD

**Issue by 345ishaan** [BVLC/caffe#4066]
Hi Caffe Community,

I have some doubts regarding the test phase methodology which we describe in our solver files. Here is the scenario which I created for digit recognition.

I took the csv files from Kaggle containing the train and test CSV. I stored the images in the HDF5 format. The train data set had correct labels in the CSV whereas test data doesn't have any labels. So I hardcoded all the labels in test dataset to 1 as i believe these labels will not contribute towards backward computation.

I wanted to perform some experiments with Gaussian Filler with different set of standard deviations. I had some images where the higher probabilities were not in favour of actual digit. But the moment I increased the frequency of test iteration from 1000 to 100 in 10000 total iterations, the probabilities start moving in the direction of actual digital value. 

My question is:-

If, giving wrong labels in the test material is effecting the backward computation of loss, then I should see degradation in performance as I increase the number of test iterations.

What is the actual impact of test iterations on the training of a net?

**Comment by seanbell** [comment]
Please ask questions about modeling, and how to train/test, on the mailing list.  Thanks!

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
