### ISSUE TITLE
Does the new release verify the MultiGPU Caffe?

### ISSUE THREAD

**Issue by linnanwang** [BVLC/caffe#4067]
The new release of multiGPU Caffe may not correct. But it is quite different from NVCaffe.

**Comment by seanbell** [comment]
Can you be more specific?

**Comment by lukeyeager** [comment]
Maybe the information you're looking for is the fact that NVcaffe uses strong scaling for multi-GPU training, whereas BVLC/Caffe uses weak scaling. We divide the batch size by the number of GPUs.

Pull request: https://github.com/NVIDIA/caffe/pull/78
Release notes: https://github.com/NVIDIA/caffe/releases/tag/v0.14.0-rc.3

**Comment by linnanwang** [comment]
**We divide the batch size by the number of GPUs.
**This was original NVIDIA design.

The prior Caffe release follows batch size* nGPUs. It looks that Caffe switches to NVIDIA way in this release. If this is true, another nasty problem starts emerging. Memory!

**Comment by linnanwang** [comment]
Ahh, I remember one thing now.

**Comment by linnanwang** [comment]
This is another minor bug hidden inside the forwardbackward. it is fixed now.
