### ISSUE TITLE
caffe make error    

### ISSUE THREAD

**Issue by lilinkang** [BVLC/caffe#4079]
CXX/LD -o .build_release/tools/upgrade_solver_proto_text.bin
.build_release/lib/libcaffe.so：对‘google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(int, std::string const&, google::protobuf::io::CodedOutputStream*)’未定义的引用
.build_release/lib/libcaffe.so：对‘google::protobuf::io::CodedOutputStream::WriteStringWithSizeToArray(std::string const&, unsigned char*)’未定义的引用
.build_release/lib/libcaffe.so：对‘google::protobuf::internal::WireFormatLite::ReadString(google::protobuf::io::CodedInputStream*, std::string*)’未定义的引用
.build_release/lib/libcaffe.so：对‘google::protobuf::Message::GetTypeName() const’未定义的引用
.build_release/lib/libcaffe.so：对‘google::protobuf::internal::StringTypeHandlerBase::Delete(std::string*)’未定义的引用
.build_release/lib/libcaffe.so：对‘google::protobuf::MessageFactory::InternalRegisterGeneratedFile(char const*, void (*)(std::string const&))’未定义的引用
.build_release/lib/libcaffe.so：对‘leveldb::DB::Open(leveldb::Options const&, std::string const&, leveldb::DB**)’未定义的引用
.build_release/lib/libcaffe.so：对‘google::protobuf::Message::DebugString() const’未定义的引用
.build_release/lib/libcaffe.so：对‘google::base::CheckOpMessageBuilder::NewString()’未定义的引用
.build_release/lib/libcaffe.so：对‘google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(int, std::string const&, google::protobuf::io::CodedOutputStream*)’未定义的引用
.build_release/lib/libcaffe.so：对‘google::protobuf::internal::StringTypeHandlerBase::New()’未定义的引用
.build_release/lib/libcaffe.so：对‘google::protobuf::MessageLite::ParseFromString(std::string const&)’未定义的引用
.build_release/lib/libcaffe.so：对‘google::protobuf::internal::empty_string_’未定义的引用
.build_release/lib/libcaffe.so：对‘google::protobuf::internal::NameOfEnum(google::protobuf::EnumDescriptor const*, int)’未定义的引用
.build_release/lib/libcaffe.so：对‘google::protobuf::internal::WireFormatLite::WriteString(int, std::string const&, google::protobuf::io::CodedOutputStream*)’未定义的引用
.build_release/lib/libcaffe.so：对‘leveldb::Status::ToString() const’未定义的引用
.build_release/lib/libcaffe.so：对‘google::protobuf::DescriptorPool::FindFileByName(std::string const&) const’未定义的引用
.build_release/lib/libcaffe.so：对‘google::protobuf::internal::WireFormatLite::ReadBytes(google::protobuf::io::CodedInputStream*, std::string*)’未定义的引用
.build_release/lib/libcaffe.so：对‘google::protobuf::Message::InitializationErrorString() const’未定义的引用
collect2: error: ld returned 1 exit status
Makefile:617: recipe for target '.build_release/tools/upgrade_solver_proto_text.bin' failed
make: *** [.build_release/tools/upgrade_solver_proto_text.bin] Error 1
llk@llk-ThinkPad-W541:~/caffe-master$ make ckean
make: *** No rule to make target 'ckean'。 停止。
llk@llk-ThinkPad-W541:~/caffe-master$ make clean

**Comment by lilinkang** [comment]
please have a look.请帮忙看看。

**Comment by seanbell** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> When reporting a bug, it's most helpful to provide the following information, where applicable:
> 
> * What steps reproduce the bug?
> * Can you reproduce the bug using the latest [master](https://github.com/BVLC/caffe/tree/master), compiled with the `DEBUG` make option?
> * What hardware and operating system/distribution are you running?
> * If the bug is a crash, provide the backtrace (usually printed by Caffe; always obtainable with `gdb`).

**Comment by machomachopadre** [comment]
Hi, Can you please be a bit clearer as to what you want to ask? Going on to answering whatever I got from your post. You should try reinstalling protobuf
Ciao and peace out :v:

**Comment by CDLuminate** [comment]
you should also report your compiler version and CUDA version

**Comment by kevin-coder** [comment]
From the build log, seems that some libs are missed. Please check the libs needed by Caffe.

**Comment by seanbell** [comment]
Closing as this is an installation question.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
