### ISSUE TITLE
Add support for opencl

### ISSUE THREAD

**Issue by bhack** [BVLC/caffe#408]
Hi Theano is adding support to opencl[1] trought CLBLAS[2]. 
Can caffe use this kind of solution to add opencl (more vendor neutral) support?

[1]https://github.com/Theano/libgpuarray
[2]https://github.com/clMathLibraries/clBLAS

**Comment by gururise** [comment]
Any progress on OpenCL support?  Its a shame that Caffe is locked to a single vendor for GPU support.

**Comment by jramapuram** [comment]
Alternatively you can use something like : 
 - https://github.com/viennacl/viennacl-dev or 
 - https://github.com/arrayfire/arrayfire

**Comment by bhack** [comment]
Another effort started at https://github.com/BVLC/caffe/pull/2195

**Comment by lemberger** [comment]
anybody tested this https://github.com/BVLC/caffe/pull/2610 https://github.com/naibaf7/caffe ?

**Comment by shelhamer** [comment]
Done by the official `opencl` branch of BVLC Caffe.
