### ISSUE TITLE
replace open by fopen in io.cpp

### ISSUE THREAD

**Issue by hevy-CC4477** [BVLC/caffe#4080]
Could we replace open by fopen ? I am ready to do it.

Why? faster, more portable, ...
take a look here: http://stackoverflow.com/questions/1658476/c-fopen-vs-open

**Comment by seanbell** [comment]
Sure, can you submit a PR making this change?

**Comment by hevy-CC4477** [comment]
done https://github.com/BVLC/caffe/pull/4085.

**Comment by agarie** [comment]
This issue should be closed.

**Comment by shelhamer** [comment]
Closing as #4085 was made and then closed as unnecessary.
