### ISSUE TITLE
why my accuracy always descent until 0

### ISSUE THREAD

**Issue by liuliuqiu** [BVLC/caffe#4086]
I design a new net ,when I use it ,the accuracy always descent until zero,that's why?

**Comment by seanbell** [comment]
Please ask usage questions on the mailing list.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
