### ISSUE TITLE
Some IOTest errors during make runtest 

### ISSUE THREAD

**Issue by ashr59** [BVLC/caffe#4088]
I am trying to install caffe in GPU mode.

Based on my previous experience in CPU mode, I noticed that, my caffe cannot import jpg files using cv2.imraed function.

I had this problem in python and ipython notebook too, in such way that when I used cv2.imread function to read jpg files, I got 'NoneType' error, so I thought that it might be related to some dependency problems in fedora.

At last, I found [the solution](http://stackoverflow.com/questions/36870234/is-there-any-possible-reason-to-have-some-difficulties-with-jpg-files-in-opencv) for that.

Therefore, at the moment I am able to read jpg images in python using cv2.imread.

But, when I wanted to continue caffe installation process in the make runtest step, I realized that test-io.cpp, test-db.cpp and  test_image_data_layer.cpp programs (in /path/to/caffe/src/caffe/test/ folder ) are not able to read jpg files from /path/to/caffe/examples/images/ folder . So, I still have problem with jpg files.

Then my temporary solution was to convert jpg imput images to png format and make corresponding changes in the aforementioned cpp files of the test process.

But, now I have these errors in the runtest step:

[----------] Global test environment tear-down
[==========] 1943 tests from 259 test cases ran. (383494 ms total)
[  PASSED  ] 1940 tests.
[  FAILED  ] 3 tests, listed below:
[  FAILED  ] IOTest.TestDecodeDatumNativeGray
[  FAILED  ] IOTest.TestDecodeDatumToCVMatNativeGray
[  FAILED  ] IOTest.TestReadFileToDatum

which is related to:

src/caffe/test/test_io.cpp:286: Failure
Value of: 140391
Expected: datum.data().size()
Which is: 284008
[  FAILED  ] IOTest.TestReadFileToDatum (0 ms)

src/caffe/test/test_io.cpp:398: Failure
Value of: 1
Expected: cv_img.channels()
Which is: 3
[  FAILED  ] IOTest.TestDecodeDatumToCVMatNativeGray (4 ms)

and

src/caffe/test/test_io.cpp:389: Failure
Value of: data[i] == data_ref[i]
 Actual: false
Expected: true
[  FAILED  ] IOTest.TestDecodeDatumNativeGray (9140 ms).

Any solution? Is this related to the previous problem with jpg files?

**Comment by seanbell** [comment]
This looks like a problem with image libraries on your computer (either the jpg libraries or OpenCV), not with caffe.  I'm going to close this for now, but please re-open if you find an issue with caffe itself (and not the libraries on your computer).

You can also follow up on the mailing list for installation/debugging help.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
