### ISSUE TITLE
make: /usr/local/bin/mexext: Command not found

### ISSUE THREAD

**Issue by kopxiong** [BVLC/caffe#4089]
When I enter "make pycaffe", it comes out (the same error when type "make all"):
make: /usr/local/bin/mexext: Command not found
CXX/LD -o python/caffe/_caffe.so python/caffe/_caffe.cpp
python/caffe/_caffe.cpp:1:52: fatal error: Python.h: No such file or directory
compilation terminated.
Makefile:498: recipe for target 'python/caffe/_caffe.so' failed
make: *** [python/caffe/_caffe.so] Error 1

I don't know what's wrong with the make?

**Comment by seanbell** [comment]
Please ask the mailing list for help with installing caffe.  As a start, you can turn on verbose mode at the end of the Makefile, to better see where building fails, and to see whether the right arguments are being used.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
