### ISSUE TITLE
a simple classification problem about white image and black image.

### ISSUE THREAD

**Issue by huzhenbang** [BVLC/caffe#4090]
I made a test for a simple classification problem about white image and black image. Its size is 28*28. Only two classes just like "mnist", one class is totally white image ,another is totally  black. I use a only one inner_product_layer to solve this problem. But its accuracy is not 100%. I have set the bias_filler.value as 1. It makes no help. Is it can be solved by only one inner_product_layer?

Thanks for your help.

**Comment by seanbell** [comment]
Please ask the mailing list for help with usage/modeling.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
