### ISSUE TITLE
Development of a new loss layer on caffe

### ISSUE THREAD

**Issue by acpn** [BVLC/caffe#4093]
Hi guys, I'm trying to reproduce a reconstruction process fillowing this paper:  http://arxiv.org/pdf/1603.07235v2.pdf

But they uses a new loss function describe in this paper, I need to implement this new function, is possible to do this on caffe?

Thanks.

**Comment by seanbell** [comment]
Yes, you can add new layers in caffe.  Please ask the mailing list for usage/modeling questions.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
