### ISSUE TITLE
Compilation errors during make on latest caffe build - Ubuntu 14.04

### ISSUE THREAD

**Issue by srawat** [BVLC/caffe#4095]
Getting the following compilation errors when using the latest on master.

CXX/LD -o .build_release/tools/upgrade_solver_proto_text.bin
.build_release/tools/upgrade_solver_proto_text.o: In function `main':
upgrade_solver_proto_text.cpp:(.text.startup+0x19b): undefined reference to `caffe::SolverNeedsTypeUpgrade(caffe::SolverParameter const&)'
upgrade_solver_proto_text.cpp:(.text.startup+0x1aa): undefined reference to `caffe::UpgradeSolverAsNeeded(std::string const&, caffe::SolverParameter*)'
collect2: error: ld returned 1 exit status
make: *** [.build_release/tools/upgrade_solver_proto_text.bin] Error 1

**Comment by seanbell** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> When reporting a bug, it's most helpful to provide the following information, where applicable:
> 
> * What steps reproduce the bug?
> * Can you reproduce the bug using the latest [master](https://github.com/BVLC/caffe/tree/master), compiled with the `DEBUG` make option?
> * What hardware and operating system/distribution are you running?
> * If the bug is a crash, provide the backtrace (usually printed by Caffe; always obtainable with `gdb`).

**Comment by CDLuminate** [comment]
Seems to be a LD flag issue (`-fPIC` or `-fPIE`), you can try and see if the `cmake` build system works.

**Comment by srawat** [comment]
that solved it for me .. Thanks @CDLuminate
