### ISSUE TITLE
asynchronous SGD

### ISSUE THREAD

**Issue by linnanwang** [BVLC/caffe#4097]
Hello,

Is there an ASGD solver in other branches of Caffe? I'm trying to find one to benchmark the results on my paper. Many  thanks.

**Comment by seanbell** [comment]
Please ask modeling/usage questions on the mailing list.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
