### ISSUE TITLE
Compilation error on OS X (opencl branch)

### ISSUE THREAD

**Issue by aman11dhanpat** [BVLC/caffe#4098]
Hi all
I was getting an error while compiling on OS X using OpenCL branch
Can someone please help me here?

**What steps reproduce the bug?**
I was just compiling from makefile
branch: opencl
command: make
**Can you reproduce the bug using the latest master, compiled with the DEBUG make option?**
No, the error is in file which is not available in master branch
**What hardware and operating system/distribution are you running?**
OS X Yosemite
Do I need to give more info here?
**If the bug is a crash, provide the backtrace (usually printed by Caffe; always obtainable with gdb).**
No crash

**Error:**
`CXX src/caffe/util/cl_fft.cpp

In file included from src/caffe/util/cl_fft.cpp:5:

In file included from ./include/caffe/common.hpp:25:

In file included from ./include/caffe/greentea/greentea.hpp:35:

In file included from /usr/local/include/viennacl/backend/opencl.hpp:28:

In file included from /usr/local/include/viennacl/ocl/backend.hpp:26:

In file included from /usr/local/include/viennacl/ocl/context.hpp:39:

/usr/local/include/viennacl/ocl/kernel.hpp:233:26: error: member reference base type 'const unsigned 
long' is not a structure or union

```
    cl_mem temp = val.handle().opencl_handle().get();
                  ~~~^~~~~~~
```

src/caffe/util/cl_fft.cpp:500:10: note: in instantiation of function template specialization 

'viennacl::ocl::kernel::arg<unsigned long>' requested here

  kernel.arg(argIdx++, (unsigned long)ch_gr \* local_work_size_x \* sizeof(Dtype) \* 4);

```
     ^
```

1 error generated.

make: **\* [.build_release/src/caffe/util/cl_fft.o] Error 1
`

**Comment by seanbell** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> When reporting a bug, it's most helpful to provide the following information, where applicable:
> 
> * What steps reproduce the bug?
> * Can you reproduce the bug using the latest [master](https://github.com/BVLC/caffe/tree/master), compiled with the `DEBUG` make option?
> * What hardware and operating system/distribution are you running?
> * If the bug is a crash, provide the backtrace (usually printed by Caffe; always obtainable with `gdb`).

**Comment by aman11dhanpat** [comment]
Updated the description

**Comment by naibaf7** [comment]
Either not the correct (latest) version of ViennaCL, or try disabling FFT in the makefile.config.

**Comment by naibaf7** [comment]
Should be fixed with viennacl-dev from GitHub and the latest version of Caffe-OpenCL.
