### ISSUE TITLE
Error 'fatal error: pyconfig.h: No such file or directory' when executing 'make pycaffe' on dev-branch

### ISSUE THREAD

**Issue by teknosains** [BVLC/caffe#410]
i have the following error when I run 'make pycaffe' on dev branch. im using CPU 

```
/usr/bin/g++ -shared -o python/caffe/_caffe.so python/caffe/_caffe.cpp \
        build/lib/libcaffe.a -pthread -fPIC -DNDEBUG -O2 -I/usr/local/include/python2.7 -          I/usr/local/lib/python2.7/dist-  packages/numpy/core/include -I/usr/local/include -Ibuild/src -I./src -I./include -I/usr/local/cuda/include -L/usr/local/lib -L/usr/local/lib -L/usr/lib -L/usr/local/cuda/lib64 - L/usr/local/cuda/lib -lcudart -lcublas -lcurand -lpthread -lglog -lprotobuf -lleveldb -lsnappy -lboost_system -lhdf5_hl -lhdf5 -lopencv_core -lopencv_highgui -lopencv_imgproc -lcblas -latlas -  lboost_python -lpython2.7
     In file included from /usr/include/boost/python/detail/prefix.hpp:13:0,
                  from /usr/include/boost/python/args.hpp:8,
                 from /usr/include/boost/python.hpp:11,
                 from python/caffe/_caffe.cpp:8:
          /usr/include/boost/python/detail/wrap_python.hpp:50:23: fatal error: pyconfig.h: No such file or         directory
       compilation terminated.
       make: *** [python/caffe/_caffe.so] Error 1
```

Can anybody help , thanks

SOLVED

**Comment by abrocod** [comment]
@codetrash Thanks! your suggestion works for me

**Comment by frombeijingwithlove** [comment]
@ghost thank you! it works for me!

**Comment by yuliliang** [comment]
Thanks @ghost and codetrash, It works after I tried the following 3 steps:
> make clean
> export CPLUS_INCLUDE_PATH=/usr/include/python2.7 
> make all -j8

**Comment by easonzhou** [comment]
Thanks @yuliliang  It works for me!

**Comment by HanuManuOm** [comment]
@ghost , Thanks. It worked for me. :+1:

**Comment by hnkulkarni** [comment]
@ghost, thanks. It worked for me. Just curious, how were you able to figure that out?

**Comment by Sharon686** [comment]
@yuliliang Thanks! It works for me too!

**Comment by adam-erickson** [comment]
Thanks **@ghost**!

**Comment by marquessbr** [comment]
thanks man!
work fine here!

**Comment by codingcainiao** [comment]
it works! thanks @ghost

**Comment by liuyijiang1994** [comment]
thanks  @ghost !

**Comment by vigneshrajaponnambalam** [comment]
thanks @ghost !

**Comment by dmedine** [comment]
@ghost is rad. One note, I am building with anaconda and the path on fedora (and probably most distros) is /path/to/anaconda3/include/python3.5m/

This threw me off because I am normally on Windoze and the anaconda directory structure is quite different there.

**Comment by FarnazJazayeri** [comment]
@dmedine Thanks! I was working with Anaconda as well, and I had forgotten to change my path with respect to Anaconda.

**Comment by kartik2112** [comment]
Woah! Magical! It worked! Thanks
I am using python3.5 
For this wont referencing python2.7 create problems?

**Comment by Pioneer-Linzi** [comment]
it worked for me! thx

**Comment by linuxjain** [comment]
Thanks @ghost!

**Comment by niraj-bhujel** [comment]
@ghost worked for me. Thanks!

**Comment by prateektiwari7** [comment]
#1505

**Comment by prateektiwari7** [comment]
Hi,

Can you please check this issue in rail blocks github

[See this issue](https://github.com/nanocurrency/raiblocks/issues/1505)

**Comment by suryawanshiswapnil** [comment]
> Thanks @ghost and codetrash, It works after I tried the following 3 steps:
> 
> > make clean
> > export CPLUS_INCLUDE_PATH=/usr/include/python2.7
> > make all -j8

Thank you made my Day i am laughing after some time

**Comment by suryawanshiswapnil** [comment]
This will solve your issue after many days i just solved my issue  Makefile.config link https://www.programmersought.com/article/9294315744/
 Verify anaconda location, sometimes it's in root.
 ANACONDA_HOME := /usr/local/anaconda3

comment below code
 Uncomment to use Python 3 (default is Python 2)
 PYTHON_LIBRARIES := boost_python39 python3.9
 PYTHON_INCLUDE := /usr/local/bin/python3.9/ \
/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/numpy/core/include

**Comment by rajhlinux** [comment]
Was having the same issue, nothing worked.

Need to make sure that the build directory where caffe is going to compile is completely fresh and empty.

Then need to do first:
`export CPLUS_INCLUDE_PATH=/usr/include/python3.9
`

Then do the cmake:
```
cmake \
-D OPENCL_LIBRARIES=/usr/local/lib/libOpenCL.so.1 \
-D CMAKE_BUILD_TYPE=Release \
-D CPU_ONLY=OFF \
-D USE_CUDA=OFF \
-D PYTHON_INCLUDE_DIR="/usr/local/include/python3.9/" \
-D PYTHON_LIBRARY="/usr/local/lib/libpython3.9.so" \
-D USE_OPENCL=ON \
-D BLAS=open ..
```

This is working for me on FreeBSD, Note: I had to disable python on the cmake command line using:
`-D BUILD_python=OFF \
`
Since Caffe building with Python does not work on FreeBSD for some reason...

**Comment by HenryQin** [comment]
> export CPLUS_INCLUDE_PATH=/usr/include/python2.7 it works for me

it also works for me
