### ISSUE TITLE
Change the batch_size by the method Reshape()

### ISSUE THREAD

**Issue by 7oud** [BVLC/caffe#4102]
I used a deploy.prototxt to initialize a new net, the batch_size is 256, loading from the deploy.prototxt

	input: "data"
	input_shape {
	  dim: 256
	  dim: 3
	  dim: 227
	  dim: 227
	}

when I use the following code:
	
	////
	int new_batch_size = 16;
	Blob<float>* input_layer = net_->input_blobs()[0];
	input_layer->Reshape(new_batch_size, num_channels_,input_geometry_.height, input_geometry_.width);
	net_->Reshape();
	////
	
As after I run the forward(),the runing time is about 13 ms.
But when I change the size in deploy.prototxt,the forward() runing time as follows:

prototxt_size: 256	new_batch_size: 16    runing time: 13ms
prototxt_size: 16	new_batch_size: 16	   runing time: 1.5ms
prototxt_size: 1024	new_batch_size: 16	    runing time: 60ms

the method Reshape() seems did not work.
Thanks~

**Comment by 7oud** [comment]
One probably reason I found in the code is : 

In blob.cpp:

template <typename Dtype>
void Blob<Dtype>::Reshape(const vector<int>& shape) {
	...
  }
  if (count_ > capacity_) {
    capacity_ = count_;
    data_.reset(new SyncedMemory(capacity_ * sizeof(Dtype)));
    diff_.reset(new SyncedMemory(capacity_ * sizeof(Dtype)));
  }
}

the line "if (count_ > capacity_) " means if the new batch_size is bigger than the old one, it will apply for more memory, and if the new batch_size is smaller than the old one , it will do nothing.
Why do like this?

**Comment by seanbell** [comment]
@7oud the reason is that constantly reallocating memory on the GPU can be inefficient if you are changing blob sizes every iteration.

If you want to hard-code a batchsize into your net `deploy.prototxt` and then change it at runtime, I recommend making the batchsize much smaller (e.g. 1).

In your above experiments, after calling `net.Reshape`, are the blobs reshaped correctly (the input blob, and all other intermediate blobs)?  Do they all have batchsize 16?

**Comment by 7oud** [comment]
@seanbell Yes, after calling `net.Reshape`, the blobs reshaped correctly. e.g. `Blob->shape_` has changed to the new batch size. But the `Blob->count_` may not equal to `Blob->capacity_`.
So when the batchsize changes to bigger, it must reallocate bigger memory on gpu and `Blob->count_ == Blob->capacity_, data_.reset(), diff_.reset()`. On the contray, when the batchsize changes to smaller, it won't  reallocate smaller memory for efficiency, so `Blob->count_ < Blob->capacity_` and the `net->forward` time may take more time when the new batchsize much smaller than the orginal one, because much computaition is wasted.

**Comment by ajtulloch** [comment]
Adding something like:

```
  static const int kShrinkageFactor = 2;
  if (count_ < capacity_ / kShrinkageFactor) {
    capacity_ = count_;
    data_.reset(new SyncedMemory(capacity_ * sizeof(Dtype)));
    diff_.reset(new SyncedMemory(capacity_ * sizeof(Dtype)));
  }
```

might help for this. It's a tradeoff that might or might not work for your problem.

**Comment by seanbell** [comment]
@7oud I don't understand why extra unused capacity will make things run slower.  Every layer uses the Blob shape metadata to index into the blobs, so any allocated but unused memory should not cause a slowdown in the computation.  If the unused memory is used by some function, then that's a bug in caffe.  Layers should not access data outside the blob shape metadata.

**Comment by 7oud** [comment]
@seanbell Actually it was slow down. you can do some experiments to verify the problem. I think the specific function (e.g. convolution) may run on the "capacity" not on the "blob", it means it won't distinguish "used" or "unused" memory.

@shelhamer Could you give some advice? Thanks!

**Comment by seanbell** [comment]
@7oud that's not possible since `capacity_` is a protected variable (https://github.com/BVLC/caffe/blob/14dc012b782c9296f370f8cb620104396fc1b414/include/caffe/blob.hpp#L274).  Layers can only use the `shape` and `count` as reported by the Blob.

**Comment by 7oud** [comment]
@seanbell Could you repeat the experiment and tell me your result?

**Comment by shelhamer** [comment]
@seanbell is right, and this does not seem to be reproducible.

**Comment by ronnyyoung** [comment]
@7oud I also met the same problem now, do you have any good advice?
