### ISSUE TITLE
Pycaffe on windows issue

### ISSUE THREAD

**Issue by tusharshar** [BVLC/caffe#4103]
Hi,
I successfully build ( assuming successfully as no error message was generated only some warnings were generated) the pycaffe package using VS 2013 on windows 8.1. The build generated the output at '<Build-Dir>Build/x64/Debug/pycaffe'.  
Now when I run the classify.py which was generated as part of the process using the simple command:
`python classify.py`
I get a runtime error message of assertion failed(The screenshot is attached).

![assertionfailure](https://cloud.githubusercontent.com/assets/10807433/15065699/ec5ab2ae-137f-11e6-8aad-a21c14b99210.JPG)

Please help me resolve this issue as no relevant information is available on it.

**Comment by tusharshar** [comment]
Can someone please verify is it the same as 
https://github.com/BVLC/caffe/pull/3575

**Comment by willyd** [comment]
Please confirm that the problem still exists with the latest CMake build
