### ISSUE TITLE
windows branch not building

### ISSUE THREAD

**Issue by ngaloppo** [BVLC/caffe#4105]
I'm running into nuget related issues: 

```
d:\dev\NugetPackages\OpenCV.2.4.10\build\native\OpenCV.targets(57,5): error MSB3030: Could not copy the file "d:\dev\N ugetPackages\OpenCV.2.4.10\build\native\../../build/native/bin/x64/v120/Release/opencv_calib3d2410.dll" because it was  not found. [d:\dev\caffe\windows\libcaffe\libcaffe.vcxproj]
...
```

I see that nuget packages are being pulled into `d:\dev\NugetPackages`, but the dlls are in `D:\dev\caffe\windows\libcaffe\OpenCV.overlay-x64_v120.2.4.10` etc.

@pavlejosipovic

**Comment by seanbell** [comment]
@pavlejosipovic are you still planning on supporting the windows branch?

Should I be directing people to the mailing list?  I can't tell if these are installation/library problems, or problems with your branch (because I don't use windows).

**Comment by seanbell** [comment]
@pavlejosipovic Should I be directing people to the mailing list?  I can't tell if these are installation/library problems, or problems with your branch (because I don't use windows).

**Comment by ngaloppo** [comment]
@seanbell Thanks. AFAIK this is a build issue specific to the windows branch.

**Comment by seanbell** [comment]
Yes, but my question was whether it is related to caffe, or whether it is an issue with getting the supporting libraries working.  The caffe maintainers have decided that the latter issues should be addressed on the mailing list, and not on the Issues page (to keep down bug reporting noise).

**Comment by ngaloppo** [comment]
Does @pavlejosipovic silence indicate that the windows branch has effectively been orphaned?

**Comment by dtmoodie** [comment]
If you're interested in a more updated windows branch that uses CMake for building, checkout my master fork.
http://github.com/dtmoodie/caffe

**Comment by willyd** [comment]
Nuget is not used anymore with the latest CMake build.
