### ISSUE TITLE
category mismatch in imagenet bvlc_googlenet.caffemodel

### ISSUE THREAD

**Issue by mikirui** [BVLC/caffe#4106]
Hi, I am wondering what the trainset is while training to get bvlc_googlenet.caffemodel.
I used imagenet ILSVRC2014 CLS-LOC dataset to test the trained net, but found label(category) mismatch (for example, the images which is class 1 in above dataset is classify to class 279). I don't konw whether my code or my validate data is wrong.

**Comment by seanbell** [comment]
See https://github.com/BVLC/caffe/tree/master/data/ilsvrc12 to download the ordering of the categories.

Please ask usage/modeling questions on the mailing list.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

**Comment by mikirui** [comment]
Thanks for your help.
