### ISSUE TITLE
Read data from lmdb incorrectly

### ISSUE THREAD

**Issue by dbysll** [BVLC/caffe#4109]
Hello, I am working on non-image data (floating point), and I saved the data into lmdb, which seems to work since I can read the correct values from the lmdb. (I guess this is because I am able to specify the correct type by using "np.fromstring(datum.data, dtype=np.float64)" )

However, the values in the data blob are messed up. I am wondering if this is a bug of Caffe? Or it is just a limitation of Caffe that it can only interpret datum.data saved in lmdb as uint8?

Btw, it seems to me that there is no way for Caffe to know that which data type to use to interpret datum.data. So I assume the unit8 is the default type? But this is not specified in any tutorials or examples.

Sorry for my ignorance in advance, I am a complete novice to Caffe. 

Lillian

**Comment by gpascualg** [comment]
You can actually write float data but to the `float_data` attribute rather than to `data` something like:

```python
datum.float_data.extend(vector.astype(float).flat)
```

Both caffe and it's python wrapper will correctly load from `float_data`  if `data` is empty, so no need to worry about that

**Comment by dbysll** [comment]
@gpascualg Thanks a lot for your prompt reply!!!  

A little bit confused (again, novice ....). Did you mean I need to do the following when I save my data to lmdb (btw, I am doing everything using python and pycaffe now)?
datum = caffe.proto.caffe_pb2.Datum()
datum.float_data = features.astype(float)


Or you meant that I need to modify any C code?

Thanks again!!!!

**Comment by gpascualg** [comment]
No need to modify any C code, that's all from python:

```python
    datum = caffe.proto.caffe_pb2.Datum()
    datum.channels = quant.shape[0]
    datum.height = 1
    datum.width = 1
    datum.float_data.extend(quant.astype(float).flat)
    datum.label = label
```
Then serialize it to the lmdb

**Comment by dbysll** [comment]
@gpascualg I truly appreciate your kind help!!! You are my superhero! It works! I check the data blob and the values are correct now.

May I ask where you find out to use "datum.float_data.extend(quant.astype(float).flat)"? Because I failed to find any useful information related to this on Caffe website.

And.... if I may ask another question....,  what does .flat mean? Seems that I somehow flatten my input features (your quant) into a 1-d vector. But if my features actual has datum.height and datum.width that are not 1, will that still be okay?

Thanks again !!!!!!!!

**Comment by gpascualg** [comment]
I don't exactly remember where I found that, but it was not on the official caffe website nor documentation.

Indeed `.flat` flattens your vector to a 1d vector. In case your vector was not originally 1d, you will have to tweak width/height accordingly, but remember to take channels as the first dimension, not height width.
If your vector was 2D/3D, you would simply set the height

**Comment by seanbell** [comment]
Please ask usage/modeling questions on the mailing list.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
