### ISSUE TITLE
Half precision for Pascal GPUs

### ISSUE THREAD

**Issue by olegklimov** [BVLC/caffe#4111]
Now that Pascal is out:

https://en.wikipedia.org/wiki/GeForce_10_series
http://www.nvidia.com/object/gpu-architecture.html

everyone's going to use half-precision floats, at least for deployment. 

Nvidia says it's twice as fast.

It's harder than `caffe::Net<float16>`, because C++14 [doesn't](http://en.cppreference.com/w/cpp/language/types) even have a type for float16. Things like `blob->cpu_data()` will get broken. Quick search on the internet gives the impression that people manually convert 32-bit floats to 16-bit and back. But I also found [Intel guide on using 16-bit floats](https://software.intel.com/en-us/articles/performance-benefits-of-half-precision-floats), it requires AVX instruction set.

So I can imagine very intrinsics-heavy support for float16 somewhere on blob level, leaving everything else intact. Or maybe I'm wrong and it cannot be solved this way.

Anyone care to solve this?

**Comment by ajtulloch** [comment]
https://github.com/drnikolaev/caffe/tree/experimental_v5/fp16
https://github.com/NVIDIA/caffe/tree/experimental/fp16

are some examples of work in this direction.

**Comment by shelhamer** [comment]
Closing as experimental and difficult to accomplish in the current design of Caffe. A more modular framework design that allows for heterogenous types and not monolithic templating of the whole `Net` is needed.
