### ISSUE TITLE
datum_height == data_mean_.height() when running solver.prototxt?

### ISSUE THREAD

**Issue by archanaram** [BVLC/caffe#4113]
Hey,

I'm relatively new to caffe and am trying to run solver.prototxt on my own data (./build/tools/caffe train --solver=path/to/solver.prototxt ) and am currently getting this issue: 

data_transformer.cpp:63] Check failed: datum_height == data_mean_.height() (760 vs. 256) 

So the dimensions of something are wrong but I'm not sure how to fix it. It's probably after the layer conv1. 

Here's my train_val.prototxt and solver.prototxt--slightly modified from what's here. 
My images are 256x256 -- some things are admittedly pretty weird in the files because my dataset is stupid levels of small at this point (I'm mainly using it to familiarize myself with using caffe for my own datasets).
[solver.txt](https://github.com/BVLC/caffe/files/253862/solver.txt)
[train_val.txt](https://github.com/BVLC/caffe/files/253863/train_val.txt)

Any help would be great!

**Comment by seanbell** [comment]
Please ask usage questions on the mailing list.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

**Comment by Coderx7** [comment]
your mean file does not match your pictures, to test that, remove or comment the mean file and test your network.
