### ISSUE TITLE
Can't run the training for more than 10 data.

### ISSUE THREAD

**Issue by ehsanik** [BVLC/caffe#4114]
I am using caffe for training my data for a project. I am pretty new to caffe. When I run the program for a training set of size 10 it works but when I increase the number of samples I get the following error:

F0508 16:31:57.835752  1168 math_functions.cu:79] Check failed: error == cudaSuccess (77 vs. 0)  an illegal memory access was encountered
**\* Check failure stack trace: ***
./run_script.sh: line 3:  1168 Aborted                 python /home/kianae/fasterrcnn/py-faster-rcnn/simple_fastrcnn/train.py --solver /home/kianae/fasterrcnn/py-faster-rcnn/simple_fastrcnn/model_defs/solver.prototxt --weights /home/kianae/fasterrcnn/py-faster-rcnn/imagenet/VGG_CNN_M_1024.caffemodel

Is there anything I can do about it?

**Comment by ashwin** [comment]
@ehsanik Were you able to solve this problem? I get this error if I run two trainings on the same GPU.

**Comment by ehsanik** [comment]
Yes. This means that your network is too big for your GPU. Run your code with just one training and on another command line run `nvidia-smi` to see how much of your GPU is involved with your current training. Then you will get a rough estimation of how many trainings you can run in parallel.

**Comment by ehsanik** [comment]
Yes. This means that your network is too big for your GPU. Run your code with just one training and on another command line run `nvidia-smi` to see how much of your GPU is involved with your current training. Then you will get a rough estimation of how many trainings you can run in parallel.
