### ISSUE TITLE
enable multi-gpu training with python interface ?

### ISSUE THREAD

**Issue by zeakey** [BVLC/caffe#4119]
Hey there,

I'm now trying out a training procedure with complicated internal operations, I plan to do it with caffe's python interface.

But I found it seems that caffe doesn't support multi-gpu training with python interface, am I right ?

Is it painful to implement such a multi-gpu support for python-interface ?

**Comment by trachelr** [comment]
+1 any insight about this issue??

**Comment by willyd** [comment]
You can have a look at this PR https://github.com/BVLC/caffe/pull/4563

**Comment by cypof** [comment]
It should work now, #4563 was merged.

**Comment by trachelr** [comment]
Thanks !

**Comment by soulslicer** [comment]
Is there any example code that shows you how to do this
