### ISSUE TITLE
Specifying the order of multiple in-place operations on the same blob

### ISSUE THREAD

**Issue by dineshj1** [BVLC/caffe#4120]
When applying multiple in-place operations to the same data blob (e.g., say, ReLU, dropout and batch normalization), there currently appears to be no way to specify the ordering of these operations in a network prototxt. Am I missing something?

These operations do not always commute. e.g. 
```
a->(batchNorm)->(ReLU)->b1
a->(ReLU)->(batchNorm)->b2
```
... do not produce equal b1 and b2 in general.

**Comment by ajtulloch** [comment]
The ordering of the layers in the NetParameter (the `prototxt`) is (currently) the evaluation order of the net - check `Net::Init` and `Net::ForwardFromTo`. I wouldn't expect that to change.

**Comment by seanbell** [comment]
Closing this since there already is a way to specify the order, as @ajtulloch replied.
