### ISSUE TITLE
How can I concatenate two symbols with adding a dimension?

### ISSUE THREAD

**Issue by helloworldlxb** [BVLC/caffe#4125]
For example, concatenate two (2, 1, 3) NDArrays into one (2, 2, 1, 3) NDArray in symbolic API?

**Comment by seanbell** [comment]
Please ask usage questions on the mailing list.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
