### ISSUE TITLE
How to involve multilabel using VocNet in the model zoo?

### ISSUE THREAD

**Issue by hugochan65** [BVLC/caffe#4126]
The full name at [https://github.com/BVLC/caffe/wiki/Model-Zoo#pascal-voc-2012-multilabel-classification-model](url) is **Pascal VOC 2012 Multilabel Classification Model**
The models definition in prototxt has a layer which has been commented:
```
#layer {
#  name: "loss"
#  type: "HingeLossMultiLabel"
#  bottom: "fc8voc"
#  bottom: "label"
#  top: "loss"
#}
```
This _bottom: "label"_ means it should has a layer has a top named 'label', am I right?
I have seen the this page [http://nbviewer.jupyter.org/github/BVLC/caffe/blob/master/examples/pascal-multilabel-with-datalayer.ipynb](url) which introduce how to involve multilabel classification in python, and the model  definition:
```
n.data, n.label = L.Python(module = 'pascal_multilabel_datalayers', layer = datalayer, 
                               ntop = 2, param_str=str(data_layer_params))
```
has a top named label, and in the 6th step, it uses:
`gtlist = test_net.blobs["label"].data[image_index, ...].astype(np.int)`
to get the predict label.
1.Then how can I do to let this model output multilabel? Just uncomment the code will get an error about the 'label' thing
2. There is no layer type called **HingeLossMultiLabel**,does it mean **HingeLoss**?
Thank you!

**Comment by seanbell** [comment]
Please ask usage questions on the mailing list.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
