### ISSUE TITLE
Does the model trained by cifar10 data set has inborn defects?

### ISSUE THREAD

**Issue by hugochan65** [BVLC/caffe#4127]
I'm using the model trained by cifar10 data set to classify images I collect on the Internet, but the accuracy is poor low. 
I guess the reason is because training images in cifar10 have a property that a large proportion of the total area is the object instance while images collected on the Internet don't have this property.
Am I guessing right? Has anyone used the cifar10 model on his own images having the same problem like me?

**Comment by seanbell** [comment]
Please ask usage questions on the mailing list.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
