### ISSUE TITLE
Return test accuracy during training in Python

### ISSUE THREAD

**Issue by kevin-li** [BVLC/caffe#4130]
Hi, I'm using the Python interface. There seems to be no way of returning test accuracy during training when test net is specified. The accuracies can only be printed out. Is this correct?

**Comment by seanbell** [comment]
Please ask usage questions on the mailing list.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

**Comment by kevin-li** [comment]
Please, can someone read before closing it without any comment. 

I am not referring to the accuracy accessible from the top blob of the Accuracy blob, that's just the acc of a single batch which does not mean much in terms of evaluation. 

I am referring to the accuracy of the **WHOLE DATASET** which is only printed to the console but never returned. Now one has to manually test it with a for loop, or access it by parsing the log. 

If this is the way intended by most people, close it as you wish.
