### ISSUE TITLE
Issue getting labels after calling set_input_arrays

### ISSUE THREAD

**Issue by d4nst** [BVLC/caffe#4131]
Consider this simple network definition:

```
layer {
  name: "input"
  type: "MemoryData"
  top: "data"
  top: "label"
  include {
    phase: TRAIN
  }
  memory_data_param {
    batch_size: 3
    channels: 1
    height: 100
    width: 100
  }
}
```

And this simple example in python: 

```
net_file = 'test_network.prototxt'
net = caffe.Net(net_file, caffe.TRAIN)

batch_size = 3
data = np.ones((batch_size, 1, 100, 100), dtype='float32')
labels = np.ones((batch_size), dtype='float32')

net.set_input_arrays(data, labels)
out = net.forward()

labels = net.blobs['label'].data
print labels
```

As expected, this returns: 

```
[[[[ 1.]]]
 [[[ 1.]]]
 [[[ 1.]]]]
```

Now, the issue is when I load the network through a solver like this:

```
solver_file = 'test_solver.prototxt'
solver = caffe.SGDSolver(solver_file)

batch_size = 3
data = np.ones((batch_size, 1, 100, 100), dtype='float32')
labels = np.ones((batch_size), dtype='float32')

solver.net.set_input_arrays(data, labels)
out = solver.net.forward()

labels = solver.net.blobs['label'].data
print labels
```

It returns: 

```
[[[[ 0.]]]
 [[[ 0.]]]
 [[[ 0.]]]]
```

In this second case, if I change the last line to `print labels.flatten()`, then it correctly returns `[ 1.  1.  1.]`

However, if I change the `batch size` to something big like `300`, then the `labels` array in the second example returns random numbers, some entries are `1` and some are not (only when I flatten the array, otherwise it keeps returning zeros). The first example still works fine.

I'm not that familiar with numpy to know what is going on here, but I guess it's some problem with the array dimensions in the second piece of code. The reason why this is only happening when loading the network through a solver, I have no idea.

**Comment by danst18** [comment]
For some reason I had to change
 ```
solver.net.set_input_arrays(data, labels)
```
to
``` 
net = solver.net
net.set_input_arrays(data, labels)
```
and everything works fine now.

**Comment by ZhengRui** [comment]
I don't know how you found the solution but yeah, it works and stops my headache now. Thanks.

**Comment by shelhamer** [comment]
Closing according to #5528.
