### ISSUE TITLE
caffe.exe无法正常启动

### ISSUE THREAD

**Issue by lishanlu136** [BVLC/caffe#4137]
你好，我按照你的步骤，在编译caffe的时候出现了，caffe.exe无法正常启动这个错误，你知道是什么地方错了吗？在这里说明，我把..\..\3rdparty\bin加入了环境变量哦，还有，你的最新的3rdparty20160510里面的lib文件夹，好像少了3个lib，其中libgflags.lib少了，在编译是时候会出现问题说找不到libgflags.lib。

**Comment by WifiSpy** [comment]
求问现在解决这个问题了吗？ 我也出现了这个问题
