### ISSUE TITLE
Typo:  arraylist_to_blobprotovecor_str()

### ISSUE THREAD

**Issue by millskyle** [BVLC/caffe#4138]
Line 49 in caffe/python/caffe/io.py reads:

`def arraylist_to_blobprotovecor_str(arraylist):`

and is missing a "t" in vector, which caused some confusion.

**Comment by seanbell** [comment]
Good catch!  Can you submit a PR making this change?

**Comment by millskyle** [comment]
I think I made a PR just now.  Never done this before, so please let me know if I did anything incorrectly.

**Comment by shelhamer** [comment]
Closed by #4138.
