### ISSUE TITLE
FFT2 layer in caffe

### ISSUE THREAD

**Issue by tyshiwo** [BVLC/caffe#4139]
Hi all,
I want to use FFT2 for 2D matrix in caffe.  Does anyone know how to make it or is there any existing caffe version that has already done this?

**Comment by ZhouYzzz** [comment]
To my knowledge, caffe template does not support complex data types(e.g. float2). So you should write your own functions for basic math operations. For GPU version, you can use `cufft` library and for CPU version libraries like `fftw` may be helpful.

**Comment by tyshiwo** [comment]
@ZhouYzzz Thanks for your comments. Do I need to install cufft and fftw libraries additionally? And is there any material on how to use cufft in caffe?

**Comment by ZhouYzzz** [comment]
@tyshiwo I've been working with `cufft` and you can find it's document at [Nvidia - cufft doc](http://docs.nvidia.com/cuda/cufft/index.html). `cufft` use different functions for single and double precision data(which may cause trouble when intergrate with caffe Layers), and requires datatypes decleared in `cuComplex.h` in `cuda/include`. You can write cuda kernels with basic functions like `add()` and `conj()`, provided by `cuComplex.h`.

**Comment by tyshiwo** [comment]
@ZhouYzzz Yeah, I have seen some functions in cufft. The problem is the datatypes in cufft and caffe are different. Have you ever used cufft in caffe?

**Comment by ZhouYzzz** [comment]
@tyshiwo I performed fft on the output data of caffe, not in caffe layers. Blobs does not support complex number, so it may be difficult.

**Comment by tyshiwo** [comment]
@ZhouYzzz I see. Thanks!

**Comment by saicoco** [comment]
Maybe you can see this https://github.com/gy20073/compact_bilinear_pooling, there are fft:https://github.com/gy20073/compact_bilinear_pooling/blob/master/caffe-20160312/src/caffe/layers/compact_bilinear_layer.cpp,

**Comment by pooyadavoodi** [comment]
What are you trying to achieve by doing FFT here?
Just want to know the application.

**Comment by shelhamer** [comment]
Closing as out-of-scope—further matrix multiplication routines need to be very strongly motivated by performance and integrate nicely into existing code.
