### ISSUE TITLE
test error:F Unknown V1LayerParameter layer type: 40 *** Check failure stack trace: ***

### ISSUE THREAD

**Issue by tangtangsiqi** [BVLC/caffe#4140]
i want to install the caffe for  faster rcnn,but when i make runtest -j 4,there is always an error like this and [runtest] Aborted (core dumped). my system is ubuntu 14.04,cuda 7.5 ,caffe is git cloned. the make and make test is okey,but make runtest always abort,what's wrong?
F0513 09:11:31.810065  6970 upgrade_proto.cpp:921] Unknown V1LayerParameter layer type: 40
*** Check failure stack trace: ***
    @     0x2b56ef7c6daa  (unknown)
    @     0x2b56ef7c6ce4  (unknown)
    @     0x2b56ef7c66e6  (unknown)
    @     0x2b56ef7c9687  (unknown)
    @     0x2b56f11e0b28  caffe::UpgradeV1LayerType()
    @           0x629105  caffe::NetUpgradeTest_TestUpgradeV1LayerType_Test::TestBody()
    @           0x7884e3  testing::internal::HandleExceptionsInMethodIfSupported<>()
    @           0x77f127  testing::Test::Run()
    @           0x77f1ce  testing::TestInfo::Run()
    @           0x77f2d5  testing::TestCase::Run()
    @           0x782618  testing::internal::UnitTestImpl::RunAllTests()
    @           0x7828a7  testing::UnitTest::Run()
    @           0x44e87a  main
    @     0x2b56f1e59ec5  (unknown)
    @           0x4546e9  (unknown)
    @              (nil)  (unknown)
make: *** [runtest] Aborted (core dumped)

**Comment by tangtangsiqi** [comment]
and i can make and runtest the caffe published by http://caffe.berkeleyvision.org/installation.html, is it okey to copy the ./caffe-faster-rcnn/matlab  to the caffe (published by berkeleyvision) that have already been compiled ,and make matcaffe?

**Comment by seanbell** [comment]
Please ask questions on the correct repository; this is for the caffe master branch, not R-CNN.  Also, for R-CNN, you need to use an old fork of caffe.  The most recent master branch does not use.  See Ross's instructions; caffe is obtained as a submodule.

You could also try the caffe mailing list.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
