### ISSUE TITLE
[SOLVED]RuntimeError: could not open file python/../model/bvlc_reference_caffenet/bvlc_reference_caffenet.caffemodel

### ISSUE THREAD

**Issue by machomachopadre** [BVLC/caffe#4142]
I am having errors running _python python/classify.py --print_results examples/images/cat.jpg foo_.
What I did...........
1. _cd caffe_
2. _ipython_ (while caffe was mounted)
3. _import numpy as np_
4. _import caffe_
5. _exit_ (ipython not terminal)
6. _python python/classify.py --print_results examples/images/cat.jpg foo_
_classify.py : error : unrecognised arguments: --print_results_
7. So I ran... _python python/classify.py examples/images/cat.jpg foo_
 _RuntimeError: could not open file python/../model/bvlc_reference_caffenet/bvlc_reference_caffenet.caffemodel_
8. And so... _sudo python python/classify.py examples/images/cat.jpg foo_
_ImportError : libcudart.so.7.5 : cannot find shared object file : no such file or directory_ :angry: 
9. Then _make clean_
10. _make all -j4_
11. _make test -j4_
12. _make runtest -j4_
13. _make pycaffe_
14. _make distribute_
                                           **NO ERRORS WITH CUDA WHATSOEVER**
Please help me :pray: :pray: :pray:

**Comment by lukeyeager** [comment]
> python python/classify.py examples/images/cat.jpg foo
RuntimeError: could not open file python/../model/bvlc_reference_caffenet/bvlc_reference_caffenet.caffemodel

You probably need to download the binary first:

    scripts/download_model_binary.py models/bvlc_reference_caffenet

> sudo python python/classify.py examples/images/cat.jpg foo
 ImportError : libcudart.so.7.5 : cannot find shared object file : no such file or directory

When you use `sudo`, you lose the value you had set for `LD_LIBRARY_PATH`. That's why you can't find CUDA.

BTW, these questions should be posted on the mailing list instead of on GitHub.

**Comment by machomachopadre** [comment]
Okay thanks for the tip! I still dont understand what to post here!! :P

**Comment by machomachopadre** [comment]
New error..... :angry:
1. i ran _scripts/download_model_binary.py models/bvlc_reference_caffenet_ and it said no such file or directory
2. after realizing i was an idiot: _cd caffe_
3. then _scripts/download_model_binary.py models/bvlc_reference_caffenet_ again
4. output: _import yaml, ImportError: no module named yaml_
5. tried _sudo apt-get install yaml_, _pip install yaml_ (did not work -_-)
6. Now whaaaatt???
Thanks :pray: :pray: :pray:

**Comment by machomachopadre** [comment]
okay i ran sudo apt-get install python-yaml and it is woking. Will give updates

**Comment by machomachopadre** [comment]
Another error has occurred after i solved the previous one. I haven't done anything except run _python python/classify.py examples/images/cat.jpg foo_ again and i have an error: _ValueError: Mean shape incompatible with value shape_ . Again, thanks for the help :+1:
