### ISSUE TITLE
classify.py: error: unrecognised arguments: --print_results

### ISSUE THREAD

**Issue by machomachopadre** [BVLC/caffe#4150]
After running _python python/classify.py --print_results examples/images/cat.jpg foo_ i have got an error saying- _classify.py: error: unrecognised arguments: --print_results_. I don't think ANYONE has had this error as my hours of searching are very unfruitful. Please tell me on how to solve this annoying error.

P.S Could you also reference me a good starters guide to caffe?(not on installation but on training and using pre-built nets)

**Comment by seanbell** [comment]
Rather than search around on the internet, why not just look inside `python/classify.py`?  You will see that `print_results` is not a valid argument (https://github.com/BVLC/caffe/blob/master/python/classify.py#L20-L89).

Where did you see the instruction to use `--print_results`?  Was it on an official caffe tutorial or documentation page?

**Comment by seanbell** [comment]
Closing as this is more of a usage question.  Please try the mailing list for help with getting started.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

**Comment by machomachopadre** [comment]
Thanks a bunch!! And btw I saw it on https://www.oreilly.com/learning/how-to-build-and-run-your-first-deep-learning-network

**Comment by kamakshi22** [comment]
Hi, I faced similar error. What should I write instead print_results?

**Comment by leemgs** [comment]
@kamakshi22, The issue https://github.com/BVLC/caffe/issues/5720#issue-239382104 will be helpful to you.
