### ISSUE TITLE
Can't make pycaffe, terminates with error 1.

### ISSUE THREAD

**Issue by Rich700000000000** [BVLC/caffe#4151]
I'm in the process of attempting to install caffe. After getting Boost to work, installing caffe itself was no problem. Pycaffe, on the other hand, is giving me trouble. 

I attempted to follow [Soundararaj's tutorial](https://github.com/saiprashanths/dl-setup), but when I tried to build pycaffe:

    make pycaffe -j $(($(nproc) + 1))

I got an error:

    CXX/LD -o python/caffe/_caffe.so python/caffe/_caffe.cpp
    python/caffe/_caffe.cpp:1:52: fatal error: Python.h: No such file or directory
     #include <Python.h>  // NOLINT(build/include_alpha)
                                                        ^
    compilation terminated.
    make: *** [python/caffe/_caffe.so] Error 1

At first I thought the command might be wrong, so I shortened it:

    make pycaffe

And tried running it with sudo, and I got the same result. What could be the problem here?

**Comment by seanbell** [comment]
Please ask installation questions on the mailing list; this problem looks like it is specific to your system.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

**Comment by chunbiao** [comment]
I wonder how you solved the problem, because I meet the same problem now
