### ISSUE TITLE
(Edited) The windows branch is compatible with cuDNN v5?

### ISSUE THREAD

**Issue by andrewssobral** [BVLC/caffe#4152]

**Comment by hengck23** [comment]
for those who are using windows caffe, here is a fork that support cudnnv5
https://github.com/TadaoYamaoka/caffe/tree/windows

For more information, refer to:
http://tadaoyamaoka.hatenablog.com/entry/2016/06/19/225038

**Comment by shelhamer** [comment]
The dedicated Windows branch is tracking master and usually compatible with many of the same versions.
