### ISSUE TITLE
"caffe.LayerParameter" has no field named "weight_filler"

### ISSUE THREAD

**Issue by machomachopadre** [BVLC/caffe#4153]
After modifying _lenet_train_test.prototxt_ according to instructions [here](http://caffe.berkeleyvision.org/gathered/examples/mnist.html), I am getting the following error: 
                             
`"caffe.LayerParameter" has no field named "weight_filler"`

I checked for typos, missing or extra brackets, etc and found nothing wrong.
Please help :pray: :pray: :pray:

**Comment by seanbell** [comment]
Please ask for usage help on the mailing list

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

**Comment by machomachopadre** [comment]
I have asked this question on caffe-users and stackoverflow, any other good forums? An answer would also be appreciated!!
Thanks :pray:
