### ISSUE TITLE
How to cite im2col?

### ISSUE THREAD

**Issue by hughperkins** [BVLC/caffe#4154]
How to cite im2col?

The only reference I can find to it is:

```
@article{jia2014learning,
  title={Learning Semantic Image Representations at a Large Scale},
  author={Jia, Yangqing},
  year={2014}
}
```
Did Yangqing invent the use of im2col to convert the convolutions into SGEMM products, and was the first to notice that this method is in general faster than one or two specific direct convolutions?

(Edit, ie page 72:

"Implementation of Convolution

"To perform convolution in an efficient way, we chose a path that is memory heavy: each local patch is expanded to a separate vector, and the whole image is converted to a matrix whose rows correspond to the multiple locations where filters will be applied. This effectively converts the convolution to a matrix-matrix multiplication (gemm) call, making it possible to utilize the commonly available, highly optimized BLAS (CUBLAS on Nvidia GPUs) libraries for dense computation.

"While one may question the speed of such operations, we note that the most time- consuming part of convolution is the dense gemm. Assuming we have an image of size N × N, a filter size of K × K and a total number of F filters, then the matrix expansion mentioned above will only account for O(N2K2) complexity while the matrix multiplication complexity is O(N2K2F). In the case of deep networks, F is usually very large (e.g. 256), effectively amortizing the expansion overhead. In practice, we observed a speedup of about 1.3 times on K20 compared to cuda-convnet4, which is optimized for GTX580."

(edit2: pretty sure its not in "Caffe: Convolutional Architecture for Fast Feature Embedding", right?
)

**Comment by shelhamer** [comment]
I believe Yangqing came up with the reduction of convolution to matrix-matrix multiplication independently. Once the GEMM method was popularized through Caffe, we eventually found an earlier reference to it in the literature [as noted on the Caffe site](http://caffe.berkeleyvision.org/tutorial/convolution.html):

*K. Chellapilla, S. Puri, P. Simard, et al. High performance convolutional neural networks for document processing. In Tenth International Workshop on Frontiers in Handwriting Recognition, 2006.*

See the [INRIA HAL archive version of the paper](https://hal.inria.fr/file/index/docid/112631/filename/p1038112283956.pdf) for more details.

This work is cited in the [NIPS workshop paper on cuDNN](http://arxiv.org/abs/1410.0759) for the idea of lowering convolution to matrix multiplication. It is the earliest reference to the technique that I could find.

History and attribution are important, but I am closing this as it is not a development issue. Please discuss further on the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead.

**Comment by hughperkins** [comment]
Thanks!

**Comment by ajtulloch** [comment]
Just for the record (and hopefully not to prolong the thread), isn't the correct reference just something like https://en.wikipedia.org/wiki/Toeplitz_matrix#Discrete_convolution?  The idea is certainly much older than 2006.

**Comment by hughperkins** [comment]
> Just for the record (and hopefully not to prolong the thread), isn't the correct reference just something like https://en.wikipedia.org/wiki/Toeplitz_matrix#Discrete_convolution? The idea is certainly much older than 2006.

Hmmm, I think I'll leave it at these two references for now.  The key insight is not just realizing that you can write a convolution as unrolled matrices, but realizing/noticing this actually gives pretty good performance.  I didnt see anything in the wikipedia article talking about convolution execution time on GPUs :-)
