### ISSUE TITLE
Logging system and throwing of exceptions instead of quitting.

### ISSUE THREAD

**Issue by dtmoodie** [BVLC/caffe#4158]
Hi,

Currently caffe quit's whenever a glog check fails.  This is undesirable when integrating into C++ applications, because now my whole program can quit for no apparent reason (to the user) when given bad input.  Furthermore it can be bad when I've already done a lot of processing in ipython, only to find a spelling error crashes my whole session.  
This may just be due to how glog works on window's, but I was under the impression that it's similar on Linux. I propose a shift to throwing exceptions instead.

Furthermore, since boost is already a requirement, why not use boost logging instead of glog?
It shouldn't be terribly difficult to write a set of equivalent macros using boost logging to throw an exception instead.

**Comment by lukeyeager** [comment]
For context, check out https://github.com/BVLC/caffe/pull/1683.

**Comment by shelhamer** [comment]
I hear the grievances against crashing, but switching to exceptions would require a lot of care and many of the errors can't be recovered from. That said, my stance has been that of https://github.com/BVLC/caffe/pull/1683#issuecomment-68945899. I'm closing this to keep the conversation at #1683.
