### ISSUE TITLE
Makefile:267: recipe for target 'matlab/caffe/caffe.mexa64' failed

### ISSUE THREAD

**Issue by panfengli** [BVLC/caffe#4162]
When I use make `matcaffe`, things go wrong. 
/usr/local/MATLAB/R2015b/bin/mex matlab/caffe/matcaffe.cpp build/lib/libcaffe.a \
        CXXFLAGS="\$CXXFLAGS -pthread -fPIC -DNDEBUG -O2 -DUSE_MKL -I/usr/include/python2.7 -I/usr/lib/python2.7/dist-packages/numpy/core/include -I/usr/local/include -I/usr/lib/x86_64-linux-gnu/hdf5/serial/include -Ibuild/src -I./src -I./include -I/usr/local/cuda/include -I/opt/intel/mkl/include -Wall" \
        CXXLIBS="\$CXXLIBS -L/usr/local/lib -L/usr/local/lib -L/usr/lib -L/usr/lib/x86_64-linux-gnu/hdf5/serial -L/usr/local/cuda/lib64 -L/usr/local/cuda/lib -L/opt/intel/mkl/lib -L/opt/intel/mkl/lib/intel64 -lcudart -lcublas -lcurand -lpthread -lglog -lprotobuf -lleveldb -lsnappy -lboost_system -lhdf5_hl -lhdf5 -lopencv_core -lopencv_highgui -lopencv_imgproc -lopencv_imgcodecs -lmkl_rt" -o matlab/caffe/caffe.mexa64
MEX  '-o' unknow 。
Makefile:267: recipe for target 'matlab/caffe/caffe.mexa64' failed
make: **\* [matlab/caffe/caffe.mexa64] Error 255

But `make all` and `make test` are all right, `make runtest` failed only two.
In order to use `rcnn`, I am using Caffe v0.999

**Comment by smajida** [comment]
@panfengli 

in Makefile in CAFFE_ROOT, find 			CXXLIBS="\$$CXXLIBS $(LDFLAGS)" -o $@ and instead of -o use -output

**Comment by shelhamer** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
