### ISSUE TITLE
error in creating imdb 

### ISSUE THREAD

**Issue by orientio** [BVLC/caffe#4166]
i am using the following command to convert and create lmdb 
GLOG_logtostderr=1 ~/caffe/build/tools/convert_imageset --resize_height=256 --resize_width=256 / ~/test/traint.txt ~/test/train_lmdb

i have checked the image names, text directories and all other possible misspellings.
all of them are correct but when running the comment i get  the following  

I0517 20:58:52.532954  3149 convert_imageset.cpp:86] A total of 0 images.

no image is converted.

can somebody tell me what is going wrong here 

here is my train.text contenet:

/home/lenovo/test/1.png 0
/home/lenovo/test/2.png 1
/home/lenovo/test/3.png 3
/home/lenovo/test/4.png 2

thanks alot

**Comment by seanbell** [comment]
Please ask usage questions on the mailing list

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
