### ISSUE TITLE
My problem is caffe  configuration

### ISSUE THREAD

**Issue by JHUKUAN** [BVLC/caffe#4168]
my problem is errorLNK1104:無法開啟檔案'leveldbd.lib'

![image](https://cloud.githubusercontent.com/assets/17906001/15343819/f34a9730-1cd2-11e6-9768-cf5b9e8cd5d7.png)

thanks

**Comment by seanbell** [comment]
Please ask usage questions on the mailing list

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
