### ISSUE TITLE
Adding new layer

### ISSUE THREAD

**Issue by sam-lass** [BVLC/caffe#4171]
Hi I want to create new layer in caffe named Load Layer. I created the respected hpp and cpp files for them. I added 
INSTANTIATE_CLASS(LoadLayer); at the end of cpp file,

in layer_factory.cpp I added

template <typename Dtype> shared_ptr<Layer<Dtype> > GetLoadLayer (const LayerParameter& param){
        return shared_ptr<Layer<Dtype> >(new LoadLayer<Dtype>(param));
}

REGISTER_LAYER_CREATOR(Load, GetLoadLayer);

in caffe.proto I added LOAD = 40 

to

message V1LayerParameter {
  ...
  enum LayerType {

In upgrade_proto.cpp, I added:

  case V1LayerParameter_LayerType_LOAD:
    return "Load";

to const char* UpgradeV1LayerType(const V1LayerParameter_LayerType type)

now when I try to do make all I get

In file included from ./include/caffe/layer.hpp:10:0,
                 from ./include/caffe/layers/load_layer.hpp:7,
                 from src/caffe/layers/load_layer.cpp:5:
src/caffe/layers/load_layer.cpp: In instantiation of ‘boost::shared_ptr<caffe::Layer<Dtype> > caffe::Creator_LoadLayer(const caffe::LayerParameter&) [with Dtype = float]’:
src/caffe/layers/load_layer.cpp:139:1:   required from here
./include/caffe/layer_factory.hpp:135:67: error: cannot allocate an object of abstract type ‘caffe::LoadLayer<float>’
     return shared_ptr<Layer<Dtype> >(new type##Layer<Dtype>(param));           \
                                                                   ^
src/caffe/layers/load_layer.cpp:139:1: note: in expansion of macro ‘REGISTER_LAYER_CLASS’
 REGISTER_LAYER_CLASS(Load);
 ^
In file included from src/caffe/layers/load_layer.cpp:5:0:
./include/caffe/layers/load_layer.hpp:13:7: note:   because the following virtual functions are pure within ‘caffe::LoadLayer<float>’:
 class LoadLayer : public Layer<Dtype> {
       ^
In file included from ./include/caffe/layers/load_layer.hpp:7:0,
                 from src/caffe/layers/load_layer.cpp:5:
./include/caffe/layer.hpp:351:16: note: 	void caffe::Layer<Dtype>::Backward_cpu(const std::vector<caffe::Blob<Dtype>*>&, const std::vector<bool>&, const std::vector<caffe::Blob<Dtype>*>&) [with Dtype = float]
   virtual void Backward_cpu(const vector<Blob<Dtype>*>& top,
                ^
In file included from ./include/caffe/layer.hpp:10:0,
                 from ./include/caffe/layers/load_layer.hpp:7,
                 from src/caffe/layers/load_layer.cpp:5:
src/caffe/layers/load_layer.cpp: In instantiation of ‘boost::shared_ptr<caffe::Layer<Dtype> > caffe::Creator_LoadLayer(const caffe::LayerParameter&) [with Dtype = double]’:
src/caffe/layers/load_layer.cpp:139:1:   required from here
./include/caffe/layer_factory.hpp:135:67: error: cannot allocate an object of abstract type ‘caffe::LoadLayer<double>’
     return shared_ptr<Layer<Dtype> >(new type##Layer<Dtype>(param));           \
                                                                   ^
src/caffe/layers/load_layer.cpp:139:1: note: in expansion of macro ‘REGISTER_LAYER_CLASS’
 REGISTER_LAYER_CLASS(Load);
 ^
In file included from src/caffe/layers/load_layer.cpp:5:0:
./include/caffe/layers/load_layer.hpp:13:7: note:   because the following virtual functions are pure within ‘caffe::LoadLayer<double>’:
 class LoadLayer : public Layer<Dtype> {
       ^
In file included from ./include/caffe/layers/load_layer.hpp:7:0,
                 from src/caffe/layers/load_layer.cpp:5:
./include/caffe/layer.hpp:351:16: note: 	void caffe::Layer<Dtype>::Backward_cpu(const std::vector<caffe::Blob<Dtype>*>&, const std::vector<bool>&, const std::vector<caffe::Blob<Dtype>*>&) [with Dtype = double]
   virtual void Backward_cpu(const vector<Blob<Dtype>*>& top,
                ^
In file included from ./include/caffe/layer.hpp:10:0,
                 from ./include/caffe/layers/load_layer.hpp:7,
                 from src/caffe/layers/load_layer.cpp:5:
src/caffe/layers/load_layer.cpp: In function ‘boost::shared_ptr<caffe::Layer<Dtype> > caffe::Creator_LoadLayer(const caffe::LayerParameter&) [with Dtype = double]’:
./include/caffe/layer_factory.hpp:136:3: warning: control reaches end of non-void function [-Wreturn-type]
   }                                                                            \
   ^
src/caffe/layers/load_layer.cpp:139:1: note: in expansion of macro ‘REGISTER_LAYER_CLASS’
 REGISTER_LAYER_CLASS(Load);
 ^
src/caffe/layers/load_layer.cpp: In function ‘boost::shared_ptr<caffe::Layer<Dtype> > caffe::Creator_LoadLayer(const caffe::LayerParameter&) [with Dtype = float]’:
./include/caffe/layer_factory.hpp:136:3: warning: control reaches end of non-void function [-Wreturn-type]
   }                                                                            \
   ^
src/caffe/layers/load_layer.cpp:139:1: note: in expansion of macro ‘REGISTER_LAYER_CLASS’
 REGISTER_LAYER_CLASS(Load);

 
Please help.

**Comment by sam-lass** [comment]
In the layer_factory.cpp if I add

return shared_ptr >(new PoolingLayer(param));
 in place of 

return shared_ptr >(new LoadLayer(param));


It compiles fine.

**Comment by sam-lass** [comment]
@pluskid

**Comment by sam-lass** [comment]
@shelhamer

**Comment by shelhamer** [comment]
Follow the new layer development guide: https://github.com/BVLC/caffe/wiki/Development#developing-new-layers and perhaps look at PRs that add layers for more examples. In particular note both lines

`
INSTANTIATE_CLASS(MyAwesomeLayer);
REGISTER_LAYER_CLASS(MyAwesome);
`
are needed with `REGISTER_LAYER_CLASS()` as a simpler alternative to adding a factory method.

While about layer development, this issue isn't so much about framework development or changing how layers are developed as it is about debugging end-user development of layer types, so I think it belongs on the mailing list.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
