### ISSUE TITLE
How to calculate magnitude with full size after using FFTW3 

### ISSUE THREAD

**Issue by tyshiwo** [BVLC/caffe#4173]
Hi all,

Recently, I used FFTW3 to calculate the 2D FFT of the image (function:fftw_plan_dft_r2c_2d). Since the output size of fft will be height*(width/2+1) due to the conjugate ability, while the input image size is height*width, how can I get the magnitude with size height*width from that output? I know there's some relation between the compressed output with the full size version, but it's a little bit complicated to do that in caffe. So is there any suggestion to solve my problem? Or is there any function in FFTW3 to get the full size of the FFT output from r2c?

**Comment by seanbell** [comment]
Please ask usage questions on the mailing list.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
