### ISSUE TITLE
Runtest fails - ViennaCL fatal error [opencl]

### ISSUE THREAD

**Issue by patmarks** [BVLC/caffe#4179]
Here's [my makefile](https://gist.github.com/patmarks/fab2dc3c95e5c384a59349a317f36f28) . It's a debian box with an ati radeon 6570, AMDAPPSDK2.9-1, and the latest catalyst driver. 16 tests fail on `runtest`. 15 look like some viennaCL issue in `test_convolution_layer_spatial.testbin`.  Here's an example of one of the failures:

```
[ RUN      ] ConvolutionLayerTest_Spatial/1.TestSimpleConvolution_Spatial5x5x1x2_caffenet_Conv2
unknown file: Failure
C++ exception with description "ViennaCL: FATAL ERROR: CL_INVALID_VALUE.
If you think that this is a bug in ViennaCL, please report it at viennacl-support@lists.sourceforge.net and supply at least the following information:
 * Operating System
 * Which OpenCL implementation (AMD, NVIDIA, etc.)
 * ViennaCL version
Many thanks in advance!" thrown in the test body.
[  FAILED  ] ConvolutionLayerTest_Spatial/1.TestSimpleConvolution_Spatial5x5x1x2_caffenet_Conv2, where TypeParam = caffe::GPUDevice<float> (8243 ms)

```
I suspect I just need the right release of viennacl, but I can't find a list of versions known to work, or what the recommended version is. 1.5 (from the debian repositories) failed to build caffe. Now I'm using 1.7.1 compiled from the github repository. All 73 viennacl tests passed before I installed it.

I also have clBLAS installed. Could that be causing the issue?

The other failure, I have no idea what's going on:
```
[ RUN      ] NetTest/0.TestSharedWeightsUpdate
src/caffe/test/test_net.cpp:1213: Failure
Value of: shared_params.cpu_diff()[i]
  Actual: 8.2940083
Expected: ip1_weights->cpu_diff()[i] + ip2_weights->cpu_diff()[i]
Which is: 8.2939987
src/caffe/test/test_net.cpp:1213: Failure
Value of: shared_params.cpu_diff()[i]
  Actual: 10.278276
Expected: ip1_weights->cpu_diff()[i] + ip2_weights->cpu_diff()[i]
Which is: 10.278267
src/caffe/test/test_net.cpp:1213: Failure
Value of: shared_params.cpu_diff()[i]
  Actual: 10.855959
Expected: ip1_weights->cpu_diff()[i] + ip2_weights->cpu_diff()[i]
Which is: 10.855949
src/caffe/test/test_net.cpp:1213: Failure
Value of: shared_params.cpu_diff()[i]
  Actual: 9.1899281
Expected: ip1_weights->cpu_diff()[i] + ip2_weights->cpu_diff()[i]
Which is: 9.1899185
src/caffe/test/test_net.cpp:1213: Failure
Value of: shared_params.cpu_diff()[i]
  Actual: 12.916765
Expected: ip1_weights->cpu_diff()[i] + ip2_weights->cpu_diff()[i]
Which is: 12.916756
src/caffe/test/test_net.cpp:1213: Failure
Value of: shared_params.cpu_diff()[i]
  Actual: 7.1070118
Expected: ip1_weights->cpu_diff()[i] + ip2_weights->cpu_diff()[i]
Which is: 7.1070023
src/caffe/test/test_net.cpp:1213: Failure
Value of: shared_params.cpu_diff()[i]
  Actual: 13.106203
Expected: ip1_weights->cpu_diff()[i] + ip2_weights->cpu_diff()[i]
Which is: 13.106194
src/caffe/test/test_net.cpp:1213: Failure
Value of: shared_params.cpu_diff()[i]
  Actual: 9.9245319
Expected: ip1_weights->cpu_diff()[i] + ip2_weights->cpu_diff()[i]
Which is: 9.9245224
[  FAILED  ] NetTest/0.TestSharedWeightsUpdate, where TypeParam = caffe::CPUDevice<float> (1 ms)
```

[The full test output.](https://gist.github.com/patmarks/06c60577568df7d5f6b8b1f3b266ec5c)

**Comment by naibaf7** [comment]
OK, seems like only ConvolutionLayerTest_Spatial is failing.
Don't worry about that, that layer is NOT used on actual Networks with AMD graphics cards right now, it's only enabled by default for Intel GPUs.

If you still want to get that working, you need to use the latest DEV version of ViennaCL I think (not quite sure, since that layer has been developed by Intel and not by me):
https://github.com/viennacl/viennacl-dev

Otherwise, all runtests pass and you are good go to.
