### ISSUE TITLE
About Training VGG

### ISSUE THREAD

**Issue by benny03** [BVLC/caffe#4180]
Hi All,

I wander if is it possible to make a batch learning with caffe on the VGG-16 layers trained on imagenet  ilsvrc-2014 classification Database.
I would like to add new categories for the ilsvrc-2014 classification challenge, without training all over the ImageNet(Zoo) ilsvrc-2015 Database .

Thanks in advance,

**Comment by shelhamer** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
