### ISSUE TITLE
hdf5 error when complie caffe

### ISSUE THREAD

**Issue by XiaXuehai** [BVLC/caffe#4185]
I use  Anaconda Python, HDF5 is bundled.
and when I use  `make runtest`. Caffe can't find the path of HDF5 lib.
```
$ make runtest
.build_release/tools/caffe
dyld: Library not loaded: @rpath/./libhdf5_hl.10.dylib
  Referenced from: /Users/xxh/caffe/.build_release/tools/caffe
  Reason: image not found
make: *** [runtest] Trace/BPT trap: 5
```
If I use `brew install hdf5`,the vision of lib and header are different .

In ` makefile.config` : 
```
# Verify anaconda location, sometimes it's in root.
 ANACONDA_HOME := $(HOME)/anaconda
 PYTHON_INCLUDE := $(ANACONDA_HOME)/include \
		 $(ANACONDA_HOME)/include/python2.7 \
		 $(ANACONDA_HOME)/lib/python2.7/site-packages/numpy/core/include \

# We need to be able to find libpythonX.X.so or .dylib.
#PYTHON_LIB := /usr/lib
 PYTHON_LIB := $(ANACONDA_HOME)/lib

# Whatever else you find you need goes here.
INCLUDE_DIRS := $(PYTHON_INCLUDE) /usr/local/include 
LIBRARY_DIRS := $(PYTHON_LIB) /usr/local/lib /usr/lib
```
and
```
 $ echo $DYLD_FALLBACK_LIBRARY_PATH
    /Users/xxh/anaconda/lib:/usr/local/lib:/usr/lib:
```
And in anaconda lib, libhdf5_hl.10.dylib is exit. What's wrong?

**Comment by XiaXuehai** [comment]
change the @rpath,using `sudo install_name_tool -change xxxx/libhdf5_hl.10.dylib @rpath/./libhdf5_hl.10.dylib /libhdf5_hl.10.dylib `

**Comment by anbai106** [comment]
I have the same errors, i followed your answer, but it does not work, maybe I did not understand what the command install_name_tool does here, is it to connect the dylib to caffe?

**Comment by anbai106** [comment]
You use the install_name_tool -change old new, i guess my old libhdf5 is in my anaconda, and the two new link should put where???

**Comment by XiaXuehai** [comment]
I don't remember it clearly.maybe you can use` otool -L` to check the link.
`install_name_tool -change new old target`

**Comment by anbai106** [comment]
even when I run otool -L, i can not get all the shared library used, its said that you at least should define one file:
 ~/Hao/Docker/Caffe/Caffe_source/caffe   master  otool -L
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/otool: at least one file must be specified
Usage: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/otool [-arch arch_type] [-fahlLDtdorSTMRIHGvVcXmqQjCP] [-mcpu=arg] [--version] <object file> ...
	-f print the fat headers
	-a print the archive header
	-h print the mach header
	-l print the load commands
	-L print shared libraries used
	-D print shared library id name
	-t print the text section (disassemble with -v)
	-p <routine name>  start dissassemble from routine name
	-s <segname> <sectname> print contents of section
	-d print the data section
	-o print the Objective-C segment
	-r print the relocation entries
	-S print the table of contents of a library
	-T print the table of contents of a dynamic shared library
	-M print the module table of a dynamic shared library
	-R print the reference table of a dynamic shared library
	-I print the indirect symbol table
	-H print the two-level hints table
	-G print the data in code table
	-v print verbosely (symbolically) when possible
	-V print disassembled operands symbolically
	-c print argument strings of a core file
	-X print no leading addresses or headers
	-m don't use archive(member) syntax
	-B force Thumb disassembly (ARM objects only)
	-q use llvm's disassembler (the default)
	-Q use otool(1)'s disassembler
	-mcpu=arg use `arg' as the cpu for disassembly
	-j print opcode bytes
	-P print the info plist section as strings
	-C print linker optimization hints
	--version print the version of /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/otool

and for the install_name_tool, I think the command line dont have the target option:

INSTALL_NAME_TOOL(1)                                                                                                                                                                                                            INSTALL_NAME_TOOL(1)



NAME
       install_name_tool - change dynamic shared library install names

SYNOPSIS
       install_name_tool [-change old new ] ... [-rpath old new ] ... [-add_rpath new ] ... [-delete_rpath new ] ... [-id name] file

DESCRIPTION
       Install_name_tool changes the dynamic shared library install names and or adds, changes or deletes the rpaths recorded in a Mach-O binary.  For this tool to work when the install names or rpaths are larger the binary should be built with
       the ld(1) -headerpad_max_install_names option.

       -change old new
              Changes the dependent shared library install name old to new in the specified Mach-O binary.  More than one of these options can be specified.  If the Mach-O binary does not contain the old install  name  in  a  specified  -change
              option the option is ignored.

       -id name
              Changes the shared library identification name of a dynamic shared library to name.  If the Mach-O binary is not a dynamic shared library and the -id option is specified it is ignored.

       -rpath old new
              Changes the rpath path name old to new in the specified Mach-O binary.  More than one of these options can be specified.  If the Mach-O binary does not contain the old rpath path name in a specified -rpath it is an error.

       -add_rpath new
              Adds the rpath path name new in the specified Mach-O binary.  More than one of these options can be specified.  If the Mach-O binary already contains the new rpath path name specified in -add_rpath it is an error.

       -delete_rpath old
              deletes the rpath path name old in the specified Mach-O binary.  More than one of these options can be specified.  If the Mach-O binary does not contains the old rpath path name specified in -delete_rpath it is an error.

I considered another choice, is to install brew hdf5, and right now, its version is 1.8.17, but the header of caffe requires 1.8.16, so there is a conflict for this, and I did not find a good way to install the specific version of hdf5(1.8.16), this is really annoying me...

Can you clarify the install_name_tool command to me a little more??

Thanks in advance

**Comment by XiaXuehai** [comment]
I use the anaconda to compile the caffe.And the hdf5's lib is `@rpath/./libhdf5_hl.10.dylib`,and the head is used anaconda's.The version is different. So I change the link to anaconda's lib.

`otool  -L file` to get the linking file.then change the link using `install_name_tool -change new old target`,the new is the path of anaconda's `libhdf5_hl.10.dylib` ,the old is the link you checked out the wrong link which is `@rpath/./libhdf5_hl.10.dylib` . the target maybe is` libcaffe.so.1.0.0-rc3
`.

**Comment by vlasenkov** [comment]
This works:
```
export DYLD_FALLBACK_LIBRARY_PATH=/Users/sansan/anaconda/lib:$DYLD_FALLBACK_LIBRARY_PATH
```

**Comment by lulitao1997** [comment]
use cmake to build, everything works, no need to change anything.
