### ISSUE TITLE
Segmentation fault training network with no image

### ISSUE THREAD

**Issue by doe300** [BVLC/caffe#4186]
When trying to load a network for training (e.g. models/bvlc_reference_caffenet) with no images in the data-set, 
`ImageDataLayer<Dtype>::DataLayerSetUp(const vector<Blob<Dtype>*>&, const vector<Blob<Dtype>*>&)`
 crashes in line 68 
`cv::Mat cv_img = ReadImageToCVMat(root_folder + lines_[lines_id_].first, new_height, new_width, is_color);` with a SIGSEGV (Segmentation fault)
since there are no entries in `lines_`.

Ergo: There should be a test before, to dump a useful error-message and gracefully exit the function.

Edit:
This also occurs in the today's master with DEBUG enabled

**Comment by seanbell** [comment]
Sure, please submit a PR making this change.
Add a `CHECK_GT` macro to check the size of `lines_`.

**Comment by malreddysid** [comment]
@seanbell 
Hey,
I've added a PR #4218  for the issue.

**Comment by doe300** [comment]
Done, thx!
