### ISSUE TITLE
Runtest fails - core dump [opencl]

### ISSUE THREAD

**Issue by YutaOtsuka** [BVLC/caffe#4188]
Hi, I'm trying to use OpenCL-Caffe on GeForce GTX TITAN X. I could pass "make all" and "make test".
But I had a "segmentation error" in "make runtest".My environment is ubuntu14.04, GeForece GTX TITAN X and OpenCL 1.2.I didn't change the Makefile.config. I'm using viennacl-dev. What do you think? 
```
[ RUN      ] ConvolutionLayerTest_Spatial/1.TestSimpleConvolution_Spatial3x3
*** Aborted at 1463757287 (unix time) try "date -d @1463757287" if you are using GNU date ***
PC: @     0x2b9f008cf172 caffe::ConvolutionLayerSpatial<>::timed_convolve()
*** SIGSEGV (@0x161) received by PID 4204 (TID 0x2b9efe33d3c0) from PID 353; stack trace: ***
    @     0x2b9f01350d40 (unknown)
    @     0x2b9f008cf172 caffe::ConvolutionLayerSpatial<>::timed_convolve()
    @     0x2b9f008cb1d8 caffe::ConvolutionLayerSpatial<>::setup_convolution()
    @     0x2b9f008ce47a caffe::ConvolutionLayerSpatial<>::Forward_gpu()
    @           0x47d922 caffe::Layer<>::Forward()
    @           0x4e9149 caffe::ConvolutionLayerTest_Spatial_TestSimpleConvolution_Spatial3x3_Test<>::TestBody_Impl()
    @           0x8ccd63 testing::internal::HandleExceptionsInMethodIfSupported<>()
    @           0x8c5b87 testing::Test::Run()
    @           0x8c5c2e testing::TestInfo::Run()
    @           0x8c5d35 testing::TestCase::Run()
    @           0x8c5fd8 testing::internal::UnitTestImpl::RunAllTests()
    @           0x8c6277 testing::UnitTest::Run()
    @           0x46e335 main
    @           0x2b9f0133bec5 (unknown)
    @           0x478829 (unknown)
    @           0x0 (unknown)
make: *** [runtest] Segmentation fault (core dumped)
```

**Comment by naibaf7** [comment]
Duplicate; see here:
https://github.com/BVLC/caffe/issues/4179

**Comment by naibaf7** [comment]
Oh ok sorry, I see you already use ViennaCL-DEV;
In that case we must ask @gongzg from Intel if he knows

This layer will not be used on actual networks though, if you can run the other tests, except for the ConvolutionLayerSpatial, it's fine.

**Comment by YutaOtsuka** [comment]
I could pass other run-tests but I couldn't execute actual classification. 
So I thought not passing runtest was the problem.
```
Loading file: ../../../pictures/101_ObjectCategories/airplanes/image_0001.jpg
Classifying 1 inputs.
ViennaCL: FATAL ERROR: Could not find kernel 'fillbuffer_float' from program ''
Number of kernels in program: 0
std::exception
Segmentation fault (core dumped)
```

**Comment by naibaf7** [comment]
@YutaOtsuka 
Ok, that's interesting, let's see then:
1. ./build/test/test_all.testbin --gtest_filter=*OpenCLKernelCompileTest* 0
2. clinfo
3. ./build/tools/caffe device_query

These outputs might give us a hint as to what is going on. I myself have a GTX 980 with the latest driver which works well in OpenCL mode, so the Titan X should be no different.

**Comment by YutaOtsuka** [comment]
I executed your command. It was following.
```
I0520 15:07:56.841437  5367 common.cpp:373] Total devices: 1
I0520 15:07:56.841604  5367 common.cpp:374] CUDA devices: 0
I0520 15:07:56.841610  5367 common.cpp:375] OpenCL devices: 1
I0520 15:07:56.841615  5367 common.cpp:399] Device id:                     0
I0520 15:07:56.841620  5367 common.cpp:401] Device backend:                OpenCL
I0520 15:07:56.841631  5367 common.cpp:403] Backend details:               NVIDIA Corporation: OpenCL 1.2 CUDA 7.5.23
I0520 15:07:56.841637  5367 common.cpp:405] Device vendor:                 NVIDIA Corporation
I0520 15:07:56.841681  5367 common.cpp:407] Name:                          GeForce GTX TITAN X
I0520 15:07:56.841718  5367 common.cpp:409] Total global memory:           12884705280
```

**Comment by naibaf7** [comment]
@YutaOtsuka 
What about the other commands?

**Comment by YutaOtsuka** [comment]
Oh, sorry.
It's ./build/test/test_all.testbin --gtest_filter=OpenCLKernelCompileTest 0
Note: Google Test filter = OpenCLKernelCompileTest
```
[==========] Running 0 tests from 0 test cases.
[==========] 0 tests from 0 test cases ran. (0 ms total)
[  PASSED  ] 0 tests.
```
It's clinfo.
```
Number of platforms:				 1
  Platform Profile:				 FULL_PROFILE
  Platform Version:				 OpenCL 1.2 CUDA 7.5.23
  Platform Name:				 NVIDIA CUDA
  Platform Vendor:				 NVIDIA Corporation
  Platform Extensions:				 cl_khr_byte_addressable_store cl_khr_icd cl_khr_gl_sharing cl_nv_compiler_options cl_nv_device_attribute_query cl_nv_pragma_unroll cl_nv_copy_opts 


  Platform Name:				 NVIDIA CUDA
Number of devices:				 1
  Device Type:					 CL_DEVICE_TYPE_GPU
  Device ID:					 4318
  Max compute units:				 24
  Max work items dimensions:			 3
    Max work items[0]:				 1024
    Max work items[1]:				 1024
    Max work items[2]:				 64
  Max work group size:				 1024
  Preferred vector width char:			 1
  Preferred vector width short:			 1
  Preferred vector width int:			 1
  Preferred vector width long:			 1
  Preferred vector width float:			 1
  Preferred vector width double:		 1
  Native vector width char:			 1
  Native vector width short:			 1
  Native vector width int:			 1
  Native vector width long:			 1
  Native vector width float:			 1
  Native vector width double:			 1
  Max clock frequency:				 1215Mhz
  Address bits:					 64
  Max memory allocation:			 3221176320
  Image support:				 Yes
  Max number of images read arguments:		 256
  Max number of images write arguments:		 16
  Max image 2D width:				 16384
  Max image 2D height:				 16384
  Max image 3D width:				 4096
  Max image 3D height:				 4096
  Max image 3D depth:				 4096
  Max samplers within kernel:			 32
  Max size of kernel argument:			 4352
  Alignment (bits) of base address:		 4096
  Minimum alignment (bytes) for any datatype:	 128
  Single precision floating point capability
    Denorms:					 Yes
    Quiet NaNs:					 Yes
    Round to nearest even:			 Yes
    Round to zero:				 Yes
    Round to +ve and infinity:			 Yes
    IEEE754-2008 fused multiply-add:		 Yes
  Cache type:					 Read/Write
  Cache line size:				 128
  Cache size:					 393216
  Global memory size:				 12884705280
  Constant buffer size:				 65536
  Max number of constant args:			 9
  Local memory type:				 Local
  Local memory size:				 49152
  Error correction support:			 0
  Unified memory for Host and Device:		 0
  Profiling timer resolution:			 1000
  Device endianess:				 Little
  Available:					 Yes
  Compiler available:				 Yes
  Execution capabilities:				 
    Execute OpenCL kernels:			 Yes
    Execute native function:			 No
  Queue properties:				 
    Out-of-Order:				 Yes
    Profiling :					 Yes
  Platform ID:					 0x252b560
  Name:						 GeForce GTX TITAN X
  Vendor:					 NVIDIA Corporation
  Device OpenCL C version:			 OpenCL C 1.2 
  Driver version:				 352.68
  Profile:					 FULL_PROFILE
  Version:					 OpenCL 1.2 CUDA
  Extensions:					 cl_khr_byte_addressable_store cl_khr_icd cl_khr_gl_sharing cl_nv_compiler_options cl_nv_device_attribute_query cl_nv_pragma_unroll cl_nv_copy_opts  cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_fp64 
```

**Comment by naibaf7** [comment]
@YutaOtsuka 
There is an error in executing `./build/test/test_all.testbin --gtest_filter=*OpenCLKernelCompileTest* 0`
Note that there must be *-s around the filter keyword.

**Comment by YutaOtsuka** [comment]
It was this. thank you.
```
Setting to use device 0
Note: Google Test filter = *OpenCLKernelCompileTest*
[==========] Running 2 tests from 2 test cases.
[----------] Global test environment set-up.
[----------] 1 test from OpenCLKernelCompileTest/0, where TypeParam = float
[ RUN      ] OpenCLKernelCompileTest/0.TestCompile
Kernel bundle: activation: OK
Kernel bundle: auxiliary: OK
Kernel bundle: batch_reindex: OK
Kernel bundle: benchmark: OK
Kernel bundle: bias: OK
Kernel bundle: bnll: OK
Kernel bundle: channel: OK
Kernel bundle: concat: OK
Kernel bundle: contrastive_loss: OK
Kernel bundle: conv_layer_spatial: OK
Kernel bundle: crop: OK
Kernel bundle: dropout: OK
Kernel bundle: eltwise: OK
Kernel bundle: elu: OK
Kernel bundle: embed: OK
Kernel bundle: fft: OK
Kernel bundle: fillbuffer: OK
Kernel bundle: im2col: OK
Kernel bundle: im2col_nd: OK
Kernel bundle: lrn: OK
Kernel bundle: math: OK
Kernel bundle: mergecrop: OK
Kernel bundle: pooling: OK
Kernel bundle: pooling_nd: OK
Kernel bundle: pooling_sk: OK
Kernel bundle: slice: OK
Kernel bundle: softmax_loss: OK
Kernel bundle: solvers: OK
Kernel bundle: tile: OK
[       OK ] OpenCLKernelCompileTest/0.TestCompile (8 ms)
[----------] 1 test from OpenCLKernelCompileTest/0 (8 ms total)

[----------] 1 test from OpenCLKernelCompileTest/1, where TypeParam = double
[ RUN      ] OpenCLKernelCompileTest/1.TestCompile
Kernel bundle: activation: OK
Kernel bundle: auxiliary: OK
Kernel bundle: batch_reindex: OK
Kernel bundle: benchmark: OK
Kernel bundle: bias: OK
Kernel bundle: bnll: OK
Kernel bundle: channel: OK
Kernel bundle: concat: OK
Kernel bundle: contrastive_loss: OK
Kernel bundle: conv_layer_spatial: OK
Kernel bundle: crop: OK
Kernel bundle: dropout: OK
Kernel bundle: eltwise: OK
Kernel bundle: elu: OK
Kernel bundle: embed: OK
Kernel bundle: fft: OK
Kernel bundle: fillbuffer: OK
Kernel bundle: im2col: OK
Kernel bundle: im2col_nd: OK
Kernel bundle: lrn: OK
Kernel bundle: math: OK
Kernel bundle: mergecrop: OK
Kernel bundle: pooling: OK
Kernel bundle: pooling_nd: OK
Kernel bundle: pooling_sk: OK
Kernel bundle: slice: OK
Kernel bundle: softmax_loss: OK
Kernel bundle: solvers: OK
Kernel bundle: tile: OK
[       OK ] OpenCLKernelCompileTest/1.TestCompile (8 ms)
[----------] 1 test from OpenCLKernelCompileTest/1 (8 ms total)

[----------] Global test environment tear-down
[==========] 2 tests from 2 test cases ran. (16 ms total)
[  PASSED  ] 2 tests.
```

**Comment by naibaf7** [comment]
@YutaOtsuka 
So it looks like everything is fine. That's odd.
What does your classification code look like? Share as much as possible.

**Comment by YutaOtsuka** [comment]
I just used provided classify.py like this.
```
   python ../../python/classify.py --model_def ./VGG_ILSVRC_16_layers_deploy.prototxt
                               --pretrained_model ./VGG_ILSVRC_16_layers.caffemodel                            
                               --gpu 
                               --raw_scale 255 ../../../pictures/101_ObjectCategories/airplanes/image_0001.jpg 
                               ./result.npy
```

**Comment by naibaf7** [comment]
@YutaOtsuka 
Ah yes, the PyCaffe code did not initialize the OpenCL GPU correctly. I fixed it now.
The downside of that PyCaffe code is that it only works with the first OpenCL/CUDA device present, which is a bit stupid but oh well, at least it should work for you now.

**Comment by YutaOtsuka** [comment]
Can I get new pycaffe code?

**Comment by naibaf7** [comment]
@YutaOtsuka Just pull the latest version of the OpenCL-Caffe repository.

**Comment by YutaOtsuka** [comment]
It worked correctly. Thank you very much!

**Comment by naibaf7** [comment]
@YutaOtsuka 
I wonder why you'd use OpenCL-Caffe instead of CUDA-Caffe on a Titan X though. It is quite a bit slower still.

**Comment by YutaOtsuka** [comment]
I just wanted to analyze the OpenCL movement. If possible I'd like to use it in FPGA. I'm just thinking.

**Comment by naibaf7** [comment]
@YutaOtsuka 
Sounds good. Yes big improvements on speed are in progress.

**Comment by buaapengbo** [comment]
Hi, i meet the same problems in opencl caffe with Nvidia GTX970.
I mv `test_convolution_layer_spatial.cpp` to "test_convolution_layer_spatial.log" , then:
> `make clean`
> `make test`
> `make runtest`
and I got this:

> `[----------] Global test environment tear-down
[==========] 2034 tests from 274 test cases ran. (480505 ms total)
[  PASSED  ] 2033 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] NetTest/0.TestSharedWeightsUpdate, where TypeParam = caffe::CPUDevice<float>
`

Then I try to train a LeNet following [http://caffe.berkeleyvision.org/gathered/examples/mnist.html](url)
I just add a line in layer conv1 of "examples/mnist/lenet_train_test.prototxt":
> `engine: SPATIAL`

when i train the net with `./examples/mnist/train_lenet.sh`
i got this:

`I0622 14:02:52.293876  2826 solver.cpp:111] Creating training net from net file: examples/mnist/lenet_train_test.prototxt
[libprotobuf ERROR google/protobuf/text_format.cc:245] Error parsing text-format caffe.NetParameter: 52:5: Unknown enumeration value of "SPATIAL" for field "engine".
F0622 14:02:52.294034  2826 upgrade_proto.cpp:79] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: examples/mnist/lenet_train_test.prototxt
*** Check failure stack trace: ***
    @     0x7faeca694daa  (unknown)
    @     0x7faeca694ce4  (unknown)
    @     0x7faeca6946e6  (unknown)
    @     0x7faeca697687  (unknown)
    @     0x7faecaa92ebe  caffe::ReadNetParamsFromTextFileOrDie()
    @     0x7faecaac99cb  caffe::Solver<>::InitTrainNet()
    @     0x7faecaac9eb6  caffe::Solver<>::Init()
    @     0x7faecaaca1c6  caffe::Solver<>::Solver()
    @     0x7faecaac3c03  caffe::Creator_SGDSolver<>()
    @           0x415c07  caffe::SolverRegistry<>::CreateSolver()
    @           0x40f323  train()
    @           0x40cd6c  main
    @     0x7faec979cf45  (unknown)
    @           0x40d56b  (unknown)
    @              (nil)  (unknown)
Aborted (core dumped)
`

what do you think?

**Comment by naibaf7** [comment]
@buaapengbo 
That the shared weights update test fails is fine. You can ignore it.
The SPATIAL engine is mainly for intel chips, and I believe the correct identifier is `INTEL_SPATIAL` now, see here for the available engines:
```
  enum Engine {
    DEFAULT = 0;
    CAFFE = 1;
    CUDNN = 2;
    LIBDNN = 3;
    INTEL_SPATIAL = 4;
    FFT = 5;
  }
```
And you have to enable `USE_INTEL_SPATIAL := 1 `in the Makefile.

this engine is mainly for Intel GPUs though. Use the CAFFE, DEFAULT or LIBDNN for most nVidia and AMD chips.

**Comment by buaapengbo** [comment]
@naibaf7 
Thank you for your quickly reply!
I understand the test `TestSharedWeightsUpdate` is unnecessary.

I just use Intel CPU `i7-6700` and Nvidia `GTX970`, is this mean that I donot need to set  `USE_INTEL_SPATIAL := 1` in the Makefile.config?

I set `engine: CAFFE` in the prototxt file and train:

> `./examples/mnist/train_lenet.sh`

I got these messages:

**I0622 14:32:23.470811  3920 solver.cpp:251] Iteration 800, loss = 0.216637
I0622 14:32:23.470849  3920 solver.cpp:267]     Train net output #0: loss = 0.216637 (* 1 = 0.216637 loss)
I0622 14:32:23.470856  3920 sgd_solver.cpp:112] Iteration 800, lr = 0.00943913
I0622 14:32:27.685243  3920 solver.cpp:251] Iteration 900, loss = 0.154349
I0622 14:32:27.685279  3920 solver.cpp:267]     Train net output #0: loss = 0.154349 (* 1 = 0.154349 loss)
I0622 14:32:27.685287  3920 sgd_solver.cpp:112] Iteration 900, lr = 0.00937411
I0622 14:32:31.858384  3920 solver.cpp:479] Snapshotting to binary proto file examples/mnist/lenet_iter_1000.caffemodel
I0622 14:32:31.869387  3920 sgd_solver.cpp:323] Snapshotting solver state to binary proto file examples/mnist/lenet_iter_1000.solverstate
I0622 14:32:31.909396  3920 solver.cpp:341] Iteration 1000, loss = 0.0869865
I0622 14:32:31.909431  3920 solver.cpp:362] Iteration 1000, Testing net (#0)
I0622 14:32:35.642645  3920 solver.cpp:429]     Test net output #0: accuracy = 0.981
I0622 14:32:35.642683  3920 solver.cpp:429]     Test net output #1: loss = 0.0592155 (* 1 = 0.0592155 loss)
I0622 14:32:35.642691  3920 solver.cpp:346] Optimization Done.
I0622 14:32:35.642696  3920 caffe.cpp:249] Optimization Done.**

I have a question, Have I used the Opencl nvidia?

**Comment by naibaf7** [comment]
@buaapengbo 
If you have disabled the CUDA backend in the Makefile.config or set the -gpu flag to 1 instead of 0, then yes, you used OpenCL.

You can also test which devices will be used with this command:
`./build/tools/caffe device_query`

**Comment by buaapengbo** [comment]
@naibaf7 
Thank you for your apply.

My Makefile.config is:
> `# USE_CUDA := 1`
> `USE_GREENTEA := 1`

I also run the command:
> `./build/tools/caffe device_query`

got this:
> pengbo@FPGA-Accel-Server:~/cnns/git/caffe$ ./build/tools/caffe device_query
> I0623 11:07:02.536579  5995 common.cpp:373] Total devices: 1
> I0623 11:07:02.536739  5995 common.cpp:374] CUDA devices: 0
> I0623 11:07:02.536747  5995 common.cpp:375] OpenCL devices: 1
> I0623 11:07:02.536752  5995 common.cpp:399] Device id:                     0
> I0623 11:07:02.536757  5995 common.cpp:401] Device backend:                OpenCL
> I0623 11:07:02.536769  5995 common.cpp:403] Backend details:               NVIDIA Corporation: OpenCL 1.2 CUDA 7.5.18
> I0623 11:07:02.536777  5995 common.cpp:405] Device vendor:                 NVIDIA Corporation
> I0623 11:07:02.536806  5995 common.cpp:407] Name:                          GeForce GTX 970
> I0623 11:07:02.536837  5995 common.cpp:409] Total global memory:           4294770688

I haven't install OpenCL SDK by Intel or beignet OpenCL.
Is this means I do use the OpenCL of GTX970 but donot use CUDA of GTX970 ?

and if I enable CUDA backend, I can use the command:

> ` ./examples/mnist/train_lenet.sh -gpu0` to use device 0(default is CUDA) to train and test .

> ` ./examples/mnist/train_lenet.sh -gpu1` to use device 1(default is OpenCL) to train and test

I understand, thank you very much!

**Comment by naibaf7** [comment]
@buaapengbo 
Exactly, you got that right :) cool, isn't it?

**Comment by buaapengbo** [comment]
@naibaf7 
That's very cool ! 
I modify my Makefile.config:
> `USE_CUDA := 1`
> `USE_GREENTEA := 1`

then

> `make clean`
> `make all`
> `make test`
> `make runtest`

> `.build_release/tools/caffe device_query`
I got this:

**pengbo@FPGA-Accel-Server:~/cnns/git/caffe$ .build_release/tools/caffe device_query
I0623 13:30:33.994971 14615 common.cpp:373] Total devices: 2
I0623 13:30:33.995152 14615 common.cpp:374] CUDA devices: 1
I0623 13:30:33.995160 14615 common.cpp:375] OpenCL devices: 1
I0623 13:30:33.995340 14615 common.cpp:382] Device id:                     0
I0623 13:30:33.995348 14615 common.cpp:384] Device backend:                CUDA
I0623 13:30:33.995368 14615 common.cpp:386] Backend details:               CUDA
I0623 13:30:33.995373 14615 common.cpp:388] Device vendor:                 NVIDIA Corporation
I0623 13:30:33.995376 14615 common.cpp:390] Name:                          GeForce GTX 970
I0623 13:30:33.995381 14615 common.cpp:392] Total global memory:           4294770688
I0623 13:30:33.995391 14615 common.cpp:399] Device id:                     1
I0623 13:30:33.995398 14615 common.cpp:401] Device backend:                OpenCL
I0623 13:30:33.995410 14615 common.cpp:403] Backend details:               NVIDIA Corporation: OpenCL 1.2 CUDA 7.5.18
I0623 13:30:33.995417 14615 common.cpp:405] Device vendor:                 NVIDIA Corporation
I0623 13:30:33.995440 14615 common.cpp:407] Name:                          GeForce GTX 970
I0623 13:30:33.995471 14615 common.cpp:409] Total global memory:           4294770688**

OK, I can train the net with `-gpu0` with CUDA and `-gpu1` with OpenCL!

Thank you very much for your help! @naibaf7

**Comment by ubergarm** [comment]
I was getting the same error `ViennaCL: FATAL ERROR: Could not find kernel 'fillbuffer_float' from program ''` despite having passing Caffe tests shown above etc.

Explicitly setting the device in the python code e.g. `caffe.set_device(0)` fixed the problem in my case.

Repo: BVLC/caffe
Branch: `opencl`
Commit: 72edcdc

Thanks!

**Comment by naibaf7** [comment]
@ubergarm 
Yes OpenCL Caffe requires explicit device initialization and cannot default to the primary device like CUDA Caffe.
