### ISSUE TITLE
Protobuf error while compiling Matlab wrapper.  undefined reference to 'google::protobuf::internal::kEmptyString'

### ISSUE THREAD

**Issue by amc-nu** [BVLC/caffe#419]
Hello, could some please help with this problem. I have tried the solutions suggested on issue #19 
Please help.
I am running Ubuntu 14.04 with CUDA Toolkit 5.5, I have installed all the dependencies and Caffe compiles correctly, but when I try to compile the Matlab wrapper I get the 'undefined reference' error
$ protoc --version
libprotoc 2.4.1
I have also tried with the latest 2.5.0

Any help is really appreciated. Here is the output of $make matcaffe

/usr/local/MATLAB/R2014a/bin/mex matlab/caffe/matcaffe.cpp build/lib/libcaffe.a \
                        CXXFLAGS="\$CXXFLAGS -pthread -fPIC -DNDEBUG -O2 -I/usr/include/python2.7 -I/usr/lib/python2.7/dist-packages/numpy/core/include -I/usr/local/include -Ibuild/src -I./src -I./include -I/usr/local/cuda/include -Wall" \
                        CXXLIBS="\$CXXLIBS -L/usr/lib/x86_64-linux-gnu/ -L/usr/local/lib -L/usr/lib -L/usr/local/cuda/lib64 -L/usr/local/cuda/lib -lcudart -lcublas -lcurand -lpthread -lglog -lprotobuf -lleveldb -lsnappy -lboost_system -lhdf5_hl -lhdf5 -lopencv_core -lopencv_highgui -lopencv_imgproc -lcblas -latlas" -output matlab/caffe/caffe.mexa64
Building with 'g++'.
/home/user1/Downloads/caffe-dev/matlab/caffe/matcaffe.cpp: In function ‘mxArray\* do_get_weights()’:
/home/user1/Downloads/caffe-dev/matlab/caffe/matcaffe.cpp:188:50: warning: narrowing conversion of ‘(& layer_blobs)->std::vector<_Tp, _Alloc>::sizeboost::shared_ptr<caffe::Blob<float >, std::allocatorboost::shared_ptr<caffe::Blob<float > > >()’ from ‘std::vectorboost::shared_ptr<caffe::Blob<float >, std::allocatorboost::shared_ptr<caffe::Blob<float > > >::size_type {aka long unsigned int}’ to ‘const mwSize {aka const int}’ inside { } is ill-formed in C++11 [-Wnarrowing]

build/lib/libcaffe.a(net.o): In function `caffe::Net<float>::ToProto(caffe::NetParameter*, bool)':
net.cpp:(.text._ZN5caffe3NetIfE7ToProtoEPNS_12NetParameterEb[_ZN5caffe3NetIfE7ToProtoEPNS_12NetParameterEb]+0x36): undefined reference to`google::protobuf::internal::kEmptyString'
net.cpp:(.text._ZN5caffe3NetIfE7ToProtoEPNS_12NetParameterEb[_ZN5caffe3NetIfE7ToProtoEPNS_12NetParameterEb]+0x82): undefined reference to `google::protobuf::internal::StringTypeHandlerBase::New()'
net.cpp:(.text._ZN5caffe3NetIfE7ToProtoEPNS_12NetParameterEb[_ZN5caffe3NetIfE7ToProtoEPNS_12NetParameterEb]+0x1d0): undefined reference to`google::protobuf::internal::StringTypeHandlerBase::New()'
net.cpp:(.text._ZN5caffe3NetIfE7ToProtoEPNS_12NetParameterEb[_ZN5caffe3NetIfE7ToProtoEPNS_12NetParameterEb]+0x298): undefined reference to `google::protobuf::internal::StringTypeHandlerBase::New()'
net.cpp:(.text._ZN5caffe3NetIfE7ToProtoEPNS_12NetParameterEb[_ZN5caffe3NetIfE7ToProtoEPNS_12NetParameterEb]+0x389): undefined reference to`google::protobuf::internal::RepeatedPtrFieldBase::Reserve(int)'
net.cpp:(.text._ZN5caffe3NetIfE7ToProtoEPNS_12NetParameterEb[_ZN5caffe3NetIfE7ToProtoEPNS_12NetParameterEb]+0x3a1): undefined reference to `google::protobuf::internal::RepeatedPtrFieldBase::Reserve(int)'
net.cpp:(.text._ZN5caffe3NetIfE7ToProtoEPNS_12NetParameterEb[_ZN5caffe3NetIfE7ToProtoEPNS_12NetParameterEb]+0x3c5): undefined reference to`google::protobuf::internal::RepeatedPtrFieldBase::Reserve(int)'
net.cpp:(.text._ZN5caffe3NetIfE7ToProtoEPNS_12NetParameterEb[_ZN5caffe3NetIfE7ToProtoEPNS_12NetParameterEb]+0x3d9): undefined reference to `google::protobuf::internal::RepeatedPtrFieldBase::Reserve(int)'
build/lib/libcaffe.a(net.o): In function`caffe::Net<double>::ToProto(caffe::NetParameter_, bool)':
net.cpp:(.text._ZN5caffe3NetIdE7ToProtoEPNS_12NetParameterEb[_ZN5caffe3NetIdE7ToProtoEPNS_12NetParameterEb]+0x36): undefined reference to `google::protobuf::internal::kEmptyString'
net.cpp:(.text._ZN5caffe3NetIdE7ToProtoEPNS_12NetParameterEb[_ZN5caffe3NetIdE7ToProtoEPNS_12NetParameterEb]+0x82): undefined reference to`google::protobuf::internal::StringTypeHandlerBase::New()'
net.cpp:(.text._ZN5caffe3NetIdE7ToProtoEPNS_12NetParameterEb[_ZN5caffe3NetIdE7ToProtoEPNS_12NetParameterEb]+0x1d0): undefined reference to `google::protobuf::internal::StringTypeHandlerBase::New()'
net.cpp:(.text._ZN5caffe3NetIdE7ToProtoEPNS_12NetParameterEb[_ZN5caffe3NetIdE7ToProtoEPNS_12NetParameterEb]+0x298): undefined reference to`google::protobuf::internal::StringTypeHandlerBase::New()'
net.cpp:(.text._ZN5caffe3NetIdE7ToProtoEPNS_12NetParameterEb[_ZN5caffe3NetIdE7ToProtoEPNS_12NetParameterEb]+0x389): undefined reference to `google::protobuf::internal::RepeatedPtrFieldBase::Reserve(int)'
net.cpp:(.text._ZN5caffe3NetIdE7ToProtoEPNS_12NetParameterEb[_ZN5caffe3NetIdE7ToProtoEPNS_12NetParameterEb]+0x3a1): undefined reference to`google::protobuf::internal::RepeatedPtrFieldBase::Reserve(int)'
net.cpp:(.text._ZN5caffe3NetIdE7ToProtoEPNS_12NetParameterEb[_ZN5caffe3NetIdE7ToProtoEPNS_12NetParameterEb]+0x3c5): undefined reference to `google::protobuf::internal::RepeatedPtrFieldBase::Reserve(int)'
net.cpp:(.text._ZN5caffe3NetIdE7ToProtoEPNS_12NetParameterEb[_ZN5caffe3NetIdE7ToProtoEPNS_12NetParameterEb]+0x3d9): undefined reference to`google::protobuf::internal::RepeatedPtrFieldBase::Reserve(int)'
build/lib/libcaffe.a(net.o): In function `caffe::Net<double>::Forward(std::string const&, double_)':
net.cpp:(.text._ZN5caffe3NetIdE7ForwardERKSsPd[_ZN5caffe3NetIdE7ForwardERKSsPd]+0x47): undefined reference to `google::protobuf::MessageLite::ParseFromString(std::string const&)'
net.cpp:(.text._ZN5caffe3NetIdE7ForwardERKSsPd[_ZN5caffe3NetIdE7ForwardERKSsPd]+0x18f): undefined reference to`google::protobuf::internal::RepeatedPtrFieldBase::Reserve(int)'
net.cpp:(.text._ZN5caffe3NetIdE7ForwardERKSsPd[_ZN5caffe3NetIdE7ForwardERKSsPd]+0x1b8): undefined reference to `google::protobuf::MessageLite::SerializeToString(std::string*) const'
build/lib/libcaffe.a(net.o): In function`caffe::Net<float>::Forward(std::string const&, float_)':
net.cpp:(.text._ZN5caffe3NetIfE7ForwardERKSsPf[_ZN5caffe3NetIfE7ForwardERKSsPf]+0x47): undefined reference to `google::protobuf::MessageLite::ParseFromString(std::string const&)'
net.cpp:(.text._ZN5caffe3NetIfE7ForwardERKSsPf[_ZN5caffe3NetIfE7ForwardERKSsPf]+0x18f): undefined reference to`google::protobuf::internal::RepeatedPtrFieldBase::Reserve(int)'
net.cpp:(.text._ZN5caffe3NetIfE7ForwardERKSsPf[_ZN5caffe3NetIfE7ForwardERKSsPf]+0x1b8): undefined reference to `google::protobuf::MessageLite::SerializeToString(std::string_) const'
build/lib/libcaffe.a(math_functions.o): In function `void caffe::caffe_cpu_gemm<float>(CBLAS_TRANSPOSE, CBLAS_TRANSPOSE, int, int, int, float, float const*, float const*, float, float*)':
math_functions.cpp:(.text+0x1ee): undefined reference to`cblas_sgemm'
build/lib/libcaffe.a(math_functions.o): In function `void caffe::caffe_cpu_gemm<double>(CBLAS_TRANSPOSE, CBLAS_TRANSPOSE, int, int, int, double, double const*, double const*, double, double*)':
math_functions.cpp:(.text+0x24e): undefined reference to`cblas_dgemm'
build/lib/libcaffe.a(math_functions.o): In function `void caffe::caffe_cpu_gemv<float>(CBLAS_TRANSPOSE, int, int, float, float const*, float const*, float, float*)':
math_functions.cpp:(.text+0x28f): undefined reference to`cblas_sgemv'
build/lib/libcaffe.a(math_functions.o): In function `void caffe::caffe_cpu_gemv<double>(CBLAS_TRANSPOSE, int, int, double, double const*, double const*, double, double*)':
math_functions.cpp:(.text+0x2cf): undefined reference to`cblas_dgemv'
build/lib/libcaffe.a(math_functions.o): In function `void caffe::caffe_cpu_axpby<float>(int, float, float const*, float, float*)':
math_functions.cpp:(.text+0x4af): undefined reference to`cblas_sscal'
build/lib/libcaffe.a(math_functions.o): In function `void caffe::caffe_cpu_axpby<double>(int, double, double const*, double, double*)':
math_functions.cpp:(.text+0x521): undefined reference to`cblas_dscal'
build/lib/libcaffe.a(math_functions.o): In function `void caffe::caffe_cpu_scale<float>(int, float, float const*, float*)':
math_functions.cpp:(.text+0x717): undefined reference to`cblas_scopy'
build/lib/libcaffe.a(math_functions.o): In function `void caffe::caffe_cpu_scale<double>(int, double, double const*, double*)':
math_functions.cpp:(.text+0x767): undefined reference to`cblas_dcopy'
build/lib/libcaffe.a(math_functions.o): In function `void caffe::caffe_gpu_gemm<float>(CBLAS_TRANSPOSE, CBLAS_TRANSPOSE, int, int, int, float, float const*, float const*, float, float*)':
math_functions.cpp:(.text+0x94f): undefined reference to`cublasSgemm_v2'
build/lib/libcaffe.a(math_functions.o): In function `void caffe::caffe_gpu_scale<float>(int, float, float const*, float*)':
math_functions.cpp:(.text+0xad5): undefined reference to`cublasScopy_v2'
math_functions.cpp:(.text+0xb09): undefined reference to `cublasSscal_v2'
build/lib/libcaffe.a(math_functions.o): In function`void caffe::caffe_gpu_asum<double>(int, double const_, double_)':
math_functions.cpp:(.text+0xd05): undefined reference to `cublasDasum_v2'
build/lib/libcaffe.a(math_functions.o): In function`void caffe::caffe_gpu_asum<float>(int, float const_, float_)':
math_functions.cpp:(.text+0xe45): undefined reference to `cublasSasum_v2'
build/lib/libcaffe.a(math_functions.o): In function`void caffe::caffe_gpu_dot<double>(int, double const_, double const_, double_)':
math_functions.cpp:(.text+0xf97): undefined reference to `cublasDdot_v2'
build/lib/libcaffe.a(math_functions.o): In function`void caffe::caffe_gpu_dot<float>(int, float const_, float const_, float_)':
math_functions.cpp:(.text+0x10e7): undefined reference to `cublasSdot_v2'
build/lib/libcaffe.a(math_functions.o): In function`void caffe::caffe_gpu_scal<double>(int, double, double_)':
math_functions.cpp:(.text+0x1226): undefined reference to `cublasDscal_v2'
build/lib/libcaffe.a(math_functions.o): In function`void caffe::caffe_gpu_scal<float>(int, float, float_)':
math_functions.cpp:(.text+0x1356): undefined reference to `cublasSscal_v2'
build/lib/libcaffe.a(math_function
make: **\* [matlab/caffe/caffe.mexa64] Error 255

Thank you.

**Comment by mgarbade** [comment]
@zszhong Can you provide a link to protobuf-2.5.0? On github the oldest version is 2.5.6 :(

**Comment by sharived** [comment]
You can get protobuf-2.5.0 from https://protobuf.googlecode.com/files/protobuf-2.5.0.tar.bz2 and follow the build instructions from  https://github.com/google/protobuf (sorry for posting to this closed thread, but wanted to make sure people solved this issue - this fixed the issue for me)
