### ISSUE TITLE
Saving weights to h5 in pycaffe

### ISSUE THREAD

**Issue by LisaAnne** [BVLC/caffe#4192]
There seems to be an issue where weights cannot be saved as h5 in the python interface.

**Comment by seanbell** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> When reporting a bug, it's most helpful to provide the following information, where applicable:
> 
> * What steps reproduce the bug?
> * Can you reproduce the bug using the latest [master](https://github.com/BVLC/caffe/tree/master), compiled with the `DEBUG` make option?
> * What hardware and operating system/distribution are you running?
> * If the bug is a crash, provide the backtrace (usually printed by Caffe; always obtainable with `gdb`).

**Comment by ajtulloch** [comment]
See https://github.com/BVLC/caffe/pull/4227 for load/save HDF5 in PyCaff.
