### ISSUE TITLE
Change log for each caffe release

### ISSUE THREAD

**Issue by Coderx7** [BVLC/caffe#4195]
Do we have a change log of some kind which denotes the changes since last version/release? 
if not, It would be a good addition since it makes it a alot easier to track the new /obsolete/fixed features and it would also speed up the documentation as well. currently the documentation is obsolete and doesnt reflect many new features/layers/changes, and one either needs to actively track the development, or find about it by chance! 
I also didnt see any milestone around here, do we have one as well?

**Comment by lukeyeager** [comment]
There's this: https://github.com/BVLC/caffe/releases

**Comment by ajtulloch** [comment]
Looks like the release notes should work for you @Coderx7?

**Comment by Coderx7** [comment]
I was actually looking for a more detailed log, like one for each commit to master branch, so that If I download the master branch like today, and come back and download it  a month later, I know what has changed in the course of one month.

**Comment by shelhamer** [comment]
@Coderx7 that is what `git log` or the [github commits view](https://github.com/BVLC/caffe/commits/master) reports. If you inspect the log you will see that we generally insist on informative commit messages.

**Comment by Coderx7** [comment]
@shelhamer : Thanks alot thats it:) Thats very nice :+1: 
by the way is there a way that you can somehow export those git logs into a text and accompany each release with such a log?
