### ISSUE TITLE
l use the deep-residual-networks/prototxt/ResNet-50-deploy.prototxt for train the cifar10 data set,but when l have write the configure file,some errers take place.here are they,please help me!!thanks

### ISSUE THREAD

**Issue by wqlw** [BVLC/caffe#4196]
hello,this is errer below.
I0523 12:09:26.262506 13681 solver.cpp:91] Creating training net from net file: examples/cifar10/cifar10_batch_norm_net.prototxt
[libprotobuf ERROR google/protobuf/text_format.cc:245] Error parsing text-format caffe.NetParameter: 7:1: Expected identifier.
F0523 12:09:26.262578 13681 upgrade_proto.cpp:79] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: examples/cifar10/cifar10_batch_norm_net.prototxt
*** Check failure stack trace: ***
    @     0x7f4bde0eb8bd  google::LogMessage::Fail()
    @     0x7f4bde0ed75d  google::LogMessage::SendToLog()
    @     0x7f4bde0eb4ac  google::LogMessage::Flush()
    @     0x7f4bde0ee07e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f4bde66b10e  caffe::ReadNetParamsFromTextFileOrDie()
    @     0x7f4bde655f3b  caffe::Solver<>::InitTrainNet()
    @     0x7f4bde65711c  caffe::Solver<>::Init()
    @     0x7f4bde65744a  caffe::Solver<>::Solver()
    @     0x7f4bde7e3593  caffe::Creator_SGDSolver<>()
    @           0x411276  caffe::SolverRegistry<>::CreateSolver()
    @           0x40a441  train()
    @           0x4082bc  main
    @     0x7f4bdd5b3ec5  (unknown)
    @           0x4089f1  (unknown)
Aborted (core dumped)

**Comment by ajtulloch** [comment]
You have a malformed prototxt - check line 7 of your prototxt.

```
Error parsing text-format caffe.NetParameter: 7:1: Expected identifier.
```

Please post usage questions on the caffe-users mailing list.
