### ISSUE TITLE
Building on OSX Mavericks

### ISSUE THREAD

**Issue by mayankjuneja** [BVLC/caffe#42]
Any pointers on getting it running on OSX 10.9 (Mavericks). I am getting the following OpenCV error while building caffe:

"ld: symbol(s) not found for architecture x86_64"

I found references to issues with OpenCV on Mavericks, but no solution has worked for me.

The complete error log can be seen here:
https://gist.github.com/mayankjuneja/8517932

**Comment by jackywang529** [comment]
Hi 
I'm wondering if anyone has run into issues with 
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [lib/libcaffe.dylib] Error 1
make[1]: *** [src/caffe/CMakeFiles/caffe.dir/all] Error 2
make: *** [all] Error 2

I was following the CMake compilation from caffe: http://caffe.berkeleyvision.org/installation.html#compilation

This error occurred when I was doing make all, and I'm on Mavericks 10.9.5.
I also tried to install libstdc++ following caffe instruction: http://caffe.berkeleyvision.org/install_osx.html
However, it still doesn't work. 

I also did not find lib/libcaffe.dylib or src/caffe/CMakeFiles/caffe.dir/all files in my build folder, not sure if those are missing as a result of my build failure or the cause. 

Full error log: https://github.com/jackywang529/myOpenCV/blob/master/OpenCV/OpenCVTutorial2/errorLog

Any suggestion is greatly appreciated! Thanks!

**Comment by rajish** [comment]
On Yosemite I've finally made it work using `cmake`:

    mkdir build & cd build
    cmake -DUSE_libstdcpp=ON ..
    make all

**Comment by 12rohanb** [comment]
I'm having the exact same issue as felixshiyong. I'm trying to build caffe with the python wrapper on Mac OSX 10.0, but keep getting the following error.

Check failed: error == cudaSuccess (35 vs. 0)  CUDA driver version is insufficient for CUDA runtime version

I've updated the CUDA driver to the latest. Tried uninstalling and reinstalling, but the error still persists. Any advice would be much appreciated. Thanks!

**Comment by SepidehAlassi** [comment]
Hi 
with make all I get the following error
Undefined symbols for architecture x86_64:
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
any suggestion?


complete error message:
Undefined symbols for architecture x86_64:
  "cv::imread(cv::String const&, int)", referenced from:
      caffe::WindowDataLayer<float>::load_batch(caffe::Batch<float>*) in window_data_layer.o
      caffe::WindowDataLayer<double>::load_batch(caffe::Batch<double>*) in window_data_layer.o
      caffe::ReadImageToCVMat(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, int, bool) in io.o
  "cv::imdecode(cv::_InputArray const&, int)", referenced from:
      caffe::DecodeDatumToCVMatNative(caffe::Datum const&) in io.o
      caffe::DecodeDatumToCVMat(caffe::Datum const&, bool) in io.o
  "cv::imencode(cv::String const&, cv::_InputArray const&, std::__1::vector<unsigned char, std::__1::allocator<unsigned char> >&, std::__1::vector<int, std::__1::allocator<int> > const&)", referenced from:
      caffe::ReadImageToDatum(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, int, int, bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, caffe::Datum*) in io.o
  "leveldb::DB::Open(leveldb::Options const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, leveldb::DB**)", referenced from:
      caffe::db::LevelDB::Open(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, caffe::db::Mode) in db_leveldb.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
