### ISSUE TITLE
Convert own dataset mean to numpy succeed but error when running the prediction.

### ISSUE THREAD

**Issue by teknosains** [BVLC/caffe#420]
Using this script, i successfully converty the binaryproto mean into numpy
import sys
from caffe.proto import caffe_pb2
from convert import blobproto_to_array
import numpy as np

blob = caffe_pb2.BlobProto()
data = open("../../examples/test/my_mean.binaryproto", "rb").read()
blob.ParseFromString(data)
nparray = blobproto_to_array(blob)
f = file("my_mean.npy","wb")
np.save(f,nparray)
f.close()

but when I run the prediction i got this error

Traceback (most recent call last):
  File "tester.py", line 23, in <module>
    scores = net.predict(caffe_root + 'examples/test/'+filename)
  File "/home/ubuntu/caffe/caffe-dev/python/caffe/imagenet/wrapper.py", line 85, in predict
    input_blob = [prepare_image(filename, self._center_only)]
  File "/home/ubuntu/caffe/caffe-dev/python/caffe/imagenet/wrapper.py", line 65, in prepare_image
    img_reshape -= IMAGENET_MEAN
ValueError: operands could not be broadcast together with shapes (256,256,3) (1,3,256,256) (256,256,3) 

The prediction is just fine when using ilsvrc12 mean, but its error when i run my own mean from my dataset 

Thx

**Comment by sleepsophia** [comment]
I convert the mean binaryproto to npy.
And when I want to use it in caffe.Classifier() I got error:
"mean shape incompatible with input shape"
and when i remove blob.num ,i got the same error,is there any solution?

**Comment by laotao** [comment]
@sunbaigui Where did you put convert_binaryproto2npy.py? Can you share it?

**Comment by adnan15110** [comment]
you can use the following code to convert between .binaryproto to .npy:

```
print "Usage: python convert_protomean.py proto.mean out.npy"
blob = caffe.proto.caffe_pb2.BlobProto()
BINARY_PROTO_FILE_NAME  ='image_mean.binaryproto'
BINARY_PROTO_FILE_PATH  = os.path.join(os.getcwd(),BINARY_PROTO_FILE_NAME)
NPY_FILE_NAME  ='image_mean.npy'
NPY_FILE_PATH  = os.path.join(os.getcwd(),NPY_FILE_NAME)

data = open( BINARY_PROTO_FILE_PATH, 'rb' ).read()
blob.ParseFromString(data)
arr = np.array( caffe.io.blobproto_to_array(blob) )
out = arr[0]
np.save( NPY_FILE_PATH , out )
```

**Comment by SongEsther** [comment]
@sleepsophia  Hi, I get the same problem with you ,have you already solved it ?

**Comment by SongEsther** [comment]
@Yangqing  Could you help me? I gengrate my own mean.npy and follow http://nbviewer.jupyter.org/github/BVLC/caffe/blob/master/examples/00-classification.ipynb .  But when I run the below:

# load the mean ImageNet image (as distributed with Caffe) for subtraction
mu = np.load(caffe_root + 'python/caffe/imagenet/ilsvrc_2012_mean.npy')
mu = mu.mean(1).mean(1)  # average over pixels to obtain the mean (BGR) pixel values
print 'mean-subtracted values:', zip('BGR', mu)

# create transformer for the input called 'data'
transformer = caffe.io.Transformer({'data': net.blobs['data'].data.shape})

transformer.set_transpose('data', (2,0,1))  # move image channels to outermost dimension
transformer.set_mean('data', mu)            # subtract the dataset-mean value in each channel
transformer.set_raw_scale('data', 255)      # rescale from [0, 1] to [0, 255]
transformer.set_channel_swap('data', (2,1,0))  # swap channels from RGB to BGR




my problem:

mean-subtracted values: [('B', array([ 211.32064002,  220.19243949,  226.30641338,  228.79393605,
        229.45166288,  228.21699033,  225.68690327,  222.26552255,
        218.41735295,  214.56371852,  210.7109702 ,  207.73977334,
        205.35947091,  203.82138116,  203.28422383,  203.61476408,
        205.16159385,  207.72180993,  211.22096089,  215.12253734,
        219.32449286,  223.22309222,  226.59998049,  228.92342867,
        230.11787251,  229.7456883 ,  224.77160536,  218.04600089]))]
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-5-dd23283a4d3b> in <module>()
      9 
     10 transformer.set_transpose('data', (2,0,1))  # move image channels to outermost dimension
---> 11 transformer.set_mean('data', mu)            # subtract the dataset-mean value in each channel
     12 transformer.set_raw_scale('data', 255)      # rescale from [0, 1] to [0, 255]
     13 transformer.set_channel_swap('data', (2,1,0))  # swap channels from RGB to BGR

/home/siat/caffe-master/python/caffe/io.py in set_mean(self, in_, mean)
    257                 raise ValueError('Mean shape invalid')
    258             if ms != self.inputs[in_][1:]:
--> 259                 raise ValueError('Mean shape incompatible with input shape.')
    260         self.mean[in_] = mean
    261 

ValueError: Mean shape incompatible with input shape.

**Comment by SongEsther** [comment]
@Yangqing Could you help me? I gengrate my own mean.npy and follow http://nbviewer.jupyter.org/github/BVLC/caffe/blob/master/examples/00-classification.ipynb . But when I run the below:
load the mean ImageNet image (as distributed with Caffe) for subtraction
mu = np.load(caffe_root + 'python/caffe/imagenet/mean.npy')
mu = mu.mean(1).mean(1) # average over pixels to obtain the mean (BGR) pixel values
print 'mean-subtracted values:', zip('BGR', mu)
transformer = caffe.io.Transformer({'data': net.blobs['data'].data.shape})
transformer.set_transpose('data', (2,0,1)) # move image channels to outermost dimension
transformer.set_mean('data', mu) # subtract the dataset-mean value in each channel
transformer.set_raw_scale('data', 255) # rescale from [0, 1] to [0, 255]
transformer.set_channel_swap('data', (2,1,0)) # swap channels from RGB to BGR

my problem:
mean-subtracted values: [('B', array([ 211.32064002, 220.19243949, 226.30641338, 228.79393605,
229.45166288, 228.21699033, 225.68690327, 222.26552255,
218.41735295, 214.56371852, 210.7109702 , 207.73977334,
205.35947091, 203.82138116, 203.28422383, 203.61476408,
205.16159385, 207.72180993, 211.22096089, 215.12253734,
219.32449286, 223.22309222, 226.59998049, 228.92342867,
230.11787251, 229.7456883 , 224.77160536, 218.04600089]))]
ValueError Traceback (most recent call last)
in ()
9 
10 transformer.set_transpose('data', (2,0,1)) # move image channels to outermost dimension
---> 11 transformer.set_mean('data', mu) # subtract the dataset-mean value in each channel
12 transformer.set_raw_scale('data', 255) # rescale from [0, 1] to [0, 255]
13 transformer.set_channel_swap('data', (2,1,0)) # swap channels from RGB to BGR
/home/siat/caffe-master/python/caffe/io.py in set_mean(self, in_, mean)
257 raise ValueError('Mean shape invalid')
258 if ms != self.inputs[in_][1:]:
--> 259 raise ValueError('Mean shape incompatible with input shape.')
260 self.mean[in_] = mean
261
ValueError: Mean shape incompatible with input shape.
