### ISSUE TITLE
compile the caffe,the errer:rodata.str1.1' can not be used when making a shared object; recompile with -fPIC

### ISSUE THREAD

**Issue by wqlw** [BVLC/caffe#4206]
please help me !!!! @longjon @ajtulloch
[ 80%] Linking CXX shared library ../../lib/libcaffe.so
/usr/bin/ld: /usr/local/lib/libpython2.7.a(object.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libpython2.7.a: error adding symbols: error value
collect2: error: ld returned 1 exit status
make[2]: **\* [lib/libcaffe.so.1.0.0-rc3]error 1
make[1]: **\* [src/caffe/CMakeFiles/caffe.dir/all] error 2
make: **\* [all] error 2

**Comment by xiamike** [comment]
same problem for me, @ericbarnhill could you provide more details?  

I'm also building on Heroku's one off instances in order to create a caffe buildpack, so certain things like apt or sudo are not available.

**Comment by shelhamer** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
