### ISSUE TITLE
Caffe build test fails with segmentation error

### ISSUE THREAD

**Issue by Subhankari** [BVLC/caffe#4208]
Hello,

I was just trying to install the latest version of Caffe on an AWS EC2 instance following the [tutorial](https://gist.github.com/baraldilorenzo/5cce8087dbae098aa5a6) by [Lorenzo Baraldi](https://gist.github.com/baraldilorenzo). I already have the older version of Caffe running in the instance so I just followed the last steps to clone and install Caffe.
I am getting a segmentation fault while running the last command i.e. `make runtest`. Below is the error:

```
[m8 tests from AdamSolverTest/3, where TypeParam = caffe::GPUDevice<double>
[0;32m[ RUN      ] [mAdamSolverTest/3.TestLeastSquaresUpdateWithEverythingAccum
[0;32m[       OK ] [mAdamSolverTest/3.TestLeastSquaresUpdateWithEverythingAccum (10 ms)
[0;32m[ RUN      ] [mAdamSolverTest/3.TestAdamLeastSquaresUpdateWithEverythingShare
*** Aborted at 1464124708 (unix time) try "date -d @1464124708" if you are using GNU date ***
PC: @     0x2b60507eda7c (unknown)
*** SIGSEGV (@0x642e000) received by PID 12366 (TID 0x2b6049a818c0) from PID 105046016; stack trace: ***
    @     0x2b605048e340 (unknown)
    @     0x2b60507eda7c (unknown)
    @     0x2b604f77c98c std::vector<>::erase()
    @     0x2b604f77b717 caffe::DevicePair::compute()
    @     0x2b604f78123c caffe::P2PSync<>::Prepare()
    @     0x2b604f7817bc caffe::P2PSync<>::Run()
    @           0x705755 caffe::GradientBasedSolverTest<>::RunLeastSquaresSolver()
    @           0x70d5ac caffe::GradientBasedSolverTest<>::TestLeastSquaresUpdate()
    @           0x70d8f4 caffe::AdamSolverTest_TestAdamLeastSquaresUpdateWithEverythingShare_Test<>::TestBody()
    @           0x891f43 testing::internal::HandleExceptionsInMethodIfSupported<>()
    @           0x888c27 testing::Test::Run()
    @           0x888cce testing::TestInfo::Run()
    @           0x888dd5 testing::TestCase::Run()
    @           0x88c118 testing::internal::UnitTestImpl::RunAllTests()
    @           0x88c3a7 testing::UnitTest::Run()
    @           0x46269f main
    @     0x2b60506bdec5 (unknown)
    @           0x469b69 (unknown)
    @                0x0 (unknown)
make: *** [runtest] Segmentation fault (core dumped)
```

Please help.

**Comment by Subhankari** [comment]
Also tried installing the [Release Candidate 3](https://github.com/BVLC/caffe/releases), still getting the same error.

**Comment by 12rohanb** [comment]
Having a similar issue. How did you fix it?

**Comment by vikiboy** [comment]
I am facing the same problem. Is this problem solved ?

**Comment by Subhankari** [comment]
For this issue as far as I remember I think I just did a make clean and make all, make test and make runtest again. I do remember that there was a post which mentioned a GNU version mismatch but I don't remember if that had helped. There should be some version compatibility issue if re-make does not work.

**Comment by shelhamer** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
