### ISSUE TITLE
Can't find the MemoryLayer in namespace caffe

### ISSUE THREAD

**Issue by sunshineInmoon** [BVLC/caffe#4210]
Hi,I can't find the MemroyLayer and other layers in namespace caffe from the lastest Caffe. But I can find them in old Caffe. What could I do?  Thanks!

**Comment by christingh** [comment]
What About the Other Layers of,Thanks!

**Comment by seanbell** [comment]
Please ask usage questions on the mailing list, thanks!

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

**Comment by christingh** [comment]
thanks!
