### ISSUE TITLE
Strange outcome when using MemoryData layer in Python

### ISSUE THREAD

**Issue by 13331151** [BVLC/caffe#4211]
Sorry to pose the problem here since I had posed it in caffe users group...

here is the link: 
   https://groups.google.com/forum/#!topic/caffe-users/iiCW13doTcs

Any help would be appreciated!

**Comment by seanbell** [comment]
Hi @13331151 -- sorry if you didn't get a response on the users group, but that doesn't change the fact that the Issues page is for bugs in caffe and not questions about how to use it.

If you found a bug, please include the minimal set of steps to reproduce it.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> When reporting a bug, it's most helpful to provide the following information, where applicable:
> 
> * What steps reproduce the bug?
> * Can you reproduce the bug using the latest [master](https://github.com/BVLC/caffe/tree/master), compiled with the `DEBUG` make option?
> * What hardware and operating system/distribution are you running?
> * If the bug is a crash, provide the backtrace (usually printed by Caffe; always obtainable with `gdb`).

**Comment by seanbell** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
