### ISSUE TITLE
CPU scaling with OpenBLAS - not working as expected

### ISSUE THREAD

**Issue by dimon777** [BVLC/caffe#4212]
Hi All,

I've compiled caffe with OpenBLAS and tried MNIST sample with OPENBLAS_NUM_THREADS=1, 2, 4, 6, 8 on 8 CPU cores machine. The results don't show any scalability at all with timings below:

OPENBLAS_NUM_THREADS=8 17m29s
OPENBLAS_NUM_THREADS=6 17m48s
OPENBLAS_NUM_THREADS=4 17m3s
OPENBLAS_NUM_THREADS=2 19m41s
OPENBLAS_NUM_THREADS=1 18m23s

At the same time I do observe the cores are getting busy according to OPENBLAS_NUM_THREADS value. Am I missing anything in configuration? Or this is by design? I'd appreciate if someone explains this or directs me to proper configuration.

**Comment by jczaja** [comment]
Caffe is designed that way so BLAS lib won't get full CPU utilisation. I cannot fully answer your question, why you are having such a particular results not knowing what your machine capabilities are (number of CPU cores)

But If you are interested in training using OpenBLAS or in general on CPU, then there is a fork of caffe
that is aiming to modify caffe so it runs faster on CPUs (mainly servers , but improvment should be visible on desktop CPUs as well).
Fork is here:
https://github.com/intelcaffe/caffe

**Comment by dimon777** [comment]
I have 8 physical cores on the machine. Thanks, for the link.

**Comment by naibaf7** [comment]
@dimon777 
An alternative is using OpenCL Caffe + OpenBLAS. This is a variant of the main Caffe branch, and scales quite well on multithreaded CPUs:
https://github.com/BVLC/caffe/tree/opencl
In order to use it, just compile with USE_GREENTEA option, and install an OpenCL implementation for your CPU (Intel OpenCL SDK or AMD APP SDK), and then you can select the CPU as a GPU device.

**Comment by flx42** [comment]
Just try a larger network first, MNIST is small.

**Comment by shelhamer** [comment]
Please ask configuration questions on the mailing list.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
