### ISSUE TITLE
proto.data_size() Check failed at blob.cpp

### ISSUE THREAD

**Issue by orchestor** [BVLC/caffe#4215]
I tried to run ros_caffe_test, but failed. Any one know the issue?

I0525 23:31:47.157732 10516 net.cpp:816] Ignoring source layer data
I0525 23:31:47.274988 10516 net.cpp:816] Ignoring source layer loss
F0525 23:31:47.374317 10516 blob.cpp:476] **Check failed: count_ == proto.data_size() (1 vs. 0)** 
*** Check failure stack trace: ***
Aborted

**Comment by seanbell** [comment]
What is `ros_caffe_test`?

**Comment by orchestor** [comment]
it is a roc means robotics operation system.  ros_caffe_test is test case for the integration

**Comment by seanbell** [comment]
This sounds like an issue with ROS, and not with this repository.  There is no `ros_caffe_test` in BVLC/caffe.  Please file the issue with the correct codebase.

**Comment by seanbell** [comment]
You could also try the users mailing list, though I think the right place is in the ROS community.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
