### ISSUE TITLE
[Caffe-OpenCL] Device in caffe::net constructor

### ISSUE THREAD

**Issue by wertig0n** [BVLC/caffe#4216]
Hi, quick question.

So I got some C++ code someone else wrote for stock caffe, creating a new net like so:

net_.reset(new Net<float>(model_file, TEST));

However openCL branch requires this to work:

net_.reset(new Net<float>(model_file, TEST, dev));

I am assuming the dev parameter indicates which device I'm supposed to use, would however like to know how to create one for the default GPU. Is it just something like:

device *dev = new device(0,0,Backend::GPU);

Or is it a bit worse than that?

**Comment by naibaf7** [comment]
It's actually easier than that.
Given your C++ correctly calls:
```C++
    Caffe::SetDevices(gpus);
    Caffe::set_mode(Caffe::GPU);
    Caffe::SetDevice(gpus[0]);
```
You can just do:
```C++
device* dev = Caffe::GetDefaultDevice()
```

**Comment by wertig0n** [comment]
Ok, so what type is the gpus variable? Sorry for being a newbie at this... ^^;

**Comment by naibaf7** [comment]
Instead of 0, push back the GPU ID you want to use. You can also initialize multiple GPUs and then use one GPU per CPU thread later on in your code (but that is fairly advanced).
```C++
std::vector<int> gpus;
gpus.push_back(0);
```

**Comment by wertig0n** [comment]
Ok, I think I got it, I'll give it a try, thanks! :)

**Comment by naibaf7** [comment]
@wertig0n Is it working, can we close this issue?
