### ISSUE TITLE
Can convert_imageset support deal with dicom files

### ISSUE THREAD

**Issue by wolfbill** [BVLC/caffe#4223]
Hi man:
     How are you doing ? Today I'd like to use convert_imageset to deal with dicom files but I found it didn't support, do you have any ideas about ?

**Comment by wolfbill** [comment]
Dicom files are use widely in medical for examples CT images , MR images and so on.

**Comment by ajtulloch** [comment]
I'd suggest modifying https://github.com/BVLC/caffe/blob/923e7e8b6337f610115ae28859408bc392d13136/tools/convert_imageset.cpp to use a DICOM C/C++ API to read your images to a CxHxW image (http://stackoverflow.com/questions/662591/what-c-library-can-i-use-to-read-pixels-from-dicom-images), and then it should work fine. Please post usage questions to the caffe-users mailing list.

**Comment by mongoose54** [comment]
@wolfbill Did you figure out a way to read in DICOMs and store them as LMDB ?

**Comment by Hzzone** [comment]
@wolfbill I will appreciate it if you can share your solution with me!

**Comment by Hzzone** [comment]
a Python version to convert dicom images to hdf5 data, LMDB is same as HDF5, for example, a pixel key with one or many label value!
`def generateHdf5(source, target):
    h5_file = hy.File(target, 'w')
    file_list = []
    for root, dirs, files in os.walk(source):
        for file in files:
            file_list.append(os.path.join(root, file))
    random.shuffle(file_list)
    random.shuffle(file_list)
    # change the image size to you want
    data = np.zeros((len(file_list), 3, 224, 224))
    labels = np.zeros(len(file_list), dtype=np.float32)
    for index, file in enumerate(file_list):
        age = info.getInfo(file)
        im = preprocess.process(file)
        data[index, :, :, :] = im
        labels[index] = age
        print(file)
    h5_file['data'] = data
    h5_file['label'] = labels

    print(labels)
    h5_file.close()`
