### ISSUE TITLE
Wrong implementation of Adam solver

### ISSUE THREAD

**Issue by sattlegger** [BVLC/caffe#4224]
In the caffe implementation of the Adam solver two crucial step are missing, namely the "bias-corrected first moment estimate" and the "bias-corrected second raw moment estimate"! 
Compare the original code: 
Algorithm 1 in [http://arxiv.org/abs/1412.6980](url) to
adam_solver.cpp and adam_solver.cu

(In my experience, Adam seems to perform worse than it should and this could be the reason for it.)

**Comment by ajtulloch** [comment]
https://github.com/BVLC/caffe/blob/923e7e8b6337f610115ae28859408bc392d13136/src/caffe/solvers/adam_solver.cpp#L40
