### ISSUE TITLE
Unpooling in latest caffe

### ISSUE THREAD

**Issue by 19mamur91** [BVLC/caffe#4226]
Hi all. I am trying to use "unpooling" but it is not added to latest caffe. Is there any way to unpool layer?

**Comment by kaaicheung** [comment]
I've tried several Caffes with unpooling implemented, seems like the one works best is from https://github.com/HyeonwooNoh

**Comment by 19mamur91** [comment]
thanks a lot.

**Comment by bharatsau** [comment]
Hi, @kaaicheung , @19mamur91 ,
The HyeonwooNoh's caffe version is very old and does not support many important functionalities that latest caffe version supports. It will be great if you can let me know how you managed to overcome this issue.
Thanks in advance.
