### ISSUE TITLE
Test accuracy miss match

### ISSUE THREAD

**Issue by dlwtojd26** [BVLC/caffe#4228]
When I trained data, I do test for checking accuracy.

After 10000 iteration, the accuracy of network was ~0.9. But when I tried to classify exactly same images(while training) using classify.py, the accuracy decrease

I don't know why this happened. 

I used grayscale images and no mean substraction. and I used Deep Features for Text Spotting
network ,Max Jaderberg, Andrea Vedaldi, Andrew Zisserman

**Comment by seanbell** [comment]
Please ask usage questions on the mailing list.  There is very likely a difference in the way your images are cropped between the two methods.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
