### ISSUE TITLE
Caffe cross compilation giving error SIGSEGV (@0x3f800000) received by PID 1030 (TID 0x36f90000) from PID 1065353216; stack trace: ***     @ 0x362df9d0 (unknown)

### ISSUE THREAD

**Issue by dnagaraju** [BVLC/caffe#4232]
Dear friends,
When i was cross compiling caffe to zynq processor i faced the error. 
**\* Aborted at 768 (unix time) try "date -d @768" if you are using GNU date ***
PC: @ 0x36625e14 (unknown)
**\* SIGSEGV (@0x3f800000) received by PID 1030 (TID 0x36f90000) from PID 1065353216; stack trace: ***
    @ 0x362df9d0 (unknown)

I tried make clean and make all but of no use.

Does any one suggest me an idea.

Thank you in advance

**Comment by seanbell** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> When reporting a bug, it's most helpful to provide the following information, where applicable:
> 
> * What steps reproduce the bug?
> * Can you reproduce the bug using the latest [master](https://github.com/BVLC/caffe/tree/master), compiled with the `DEBUG` make option?
> * What hardware and operating system/distribution are you running?
> * If the bug is a crash, provide the backtrace (usually printed by Caffe; always obtainable with `gdb`).

**Comment by dnagaraju** [comment]
Thank you for your reply,
Here are the details of steps which produced this error and it is reproduced with latest master also.
Firstly,
I cross compiled OpenBlas,Boost,protobuf,glog.gflags,hdf5,lmdB,leveldB,snappy with flag cpu only using arm-xilinx-linux-gnueabi-gcc/g++ compilers.
The platform is zedboard(zynq 7000 processor) with petalinux software. The host computer has ubuntu14.4 linux distribution.
Then i made changes to configure file as follows
CPU_ONLY := 1
USE_OPENCV := 0
USE_LEVELDB := 1
USE_LMDB := 1
ALLOW_LMDB_NOLOCK := 1
CUSTOM_CXX := arm-xilinx-linux-gnueabi-g++
Then I included all include and lib directories which are needed. 

make all
Then i moved/copied the folder all executable files along with .so files to sdcard.  
I exported path using export LD_LIBRARY_PATH= to/.sofiles
then followed mnist steps
./data/mnist/get_mnist.sh
./examples/mnist/create_mnist.sh
./examples/mnist/train_lenet.sh  //with cpu mode
*** Aborted at 451 (unix time) try "date -d @451" if you are using GNU date ***
PC: @ 0x365f6e14 (unknown)
*** SIGSEGV (@0x3f800000) received by PID 1051 (TID 0x36265450) from PID 1065353216; stack trace: ***
    @ 0x362b09d0 (unknown)
./examples/mnist/train_lenet.sh: line 3:  1051 Segmentation fault      ./build/tools/caffe train --solver=examples/mnist/lenet_solver.prototxt

**Comment by Momotyust** [comment]
Hi, I am need some help for cross compile caffe, because I want to use it on a embedded device. Did you have solved your problem? Even some tutorials of cross compiling those dependency libraries are also welcomed. Thanks！

**Comment by tomicfish** [comment]
Hi,  I also have the same need for cross compiler dependency Libraries. Can you tell me how to cross compile     hdf5 and OpenBlas?

**Comment by Momotyust** [comment]
Hi

Actually, I didn't finish this work, I gave it up. because my cross compile
tools lack Fortran compiler which is necessary for OpenBlas, but I think it
is not very difficult to cross-compile hdf5. If you finish this work, I
hope you will share your experience.

2017-04-03 23:15 GMT+08:00 Tomic <notifications@github.com>:

**Comment by shelhamer** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
