### ISSUE TITLE
Library not loaded: libmkl_rt.dylib

### ISSUE THREAD

**Issue by Andy0731** [BVLC/caffe#4233]
Hi,I am a newbie to caffe . I am following LeNet MNIST Tutorial.I have some trouble after running the following commands:
cd $CAFFE_ROOT
./data/mnist/get_mnist.sh
./examples/mnist/create_mnist.sh

I am facing the following issue:

Creating lmdb...
dyld: Library not loaded: libmkl_rt.dylib
  Referenced from: /Users/andy/caffe/build/examples/mnist/convert_mnist_data.bin
  Reason: image not found
./examples/mnist/create_mnist.sh: line 17:  3506 Trace/BPT trap: 5       $BUILD/convert_mnist_data.bin $DATA/train-images-idx3-ubyte $DATA/train-labels-idx1-ubyte $EXAMPLE/mnist_train_${BACKEND} --backend=${BACKEND}
dyld: Library not loaded: libmkl_rt.dylib
  Referenced from: /Users/andy/caffe/build/examples/mnist/convert_mnist_data.bin
  Reason: image not found
./examples/mnist/create_mnist.sh: line 19:  3507 Trace/BPT trap: 5       $BUILD/convert_mnist_data.bin $DATA/t10k-images-idx3-ubyte $DATA/t10k-labels-idx1-ubyte $EXAMPLE/mnist_test_${BACKEND} --backend=${BACKEND}
Done.

then,I run"locate libmkl_rt.dylib" and get these:
Andys-Mac-3:caffe Andy$ locate libmkl_rt.dylib
/Users/andy/anaconda/lib/libmkl_rt.dylib
/Users/andy/anaconda/pkgs/mkl-11.3.1-0/lib/libmkl_rt.dylib
/anaconda/lib/libmkl_rt.dylib
/anaconda/pkgs/mkl-11.3.1-0/lib/libmkl_rt.dylib
/opt/intel/composer_xe_2015.2.132/mkl/lib/libmkl_rt.dylib

I add all these paths to LD_LIBRARY_PATH and then run "echo $LD_LIBRARY_PATH" and get these:
Andys-Mac-3:caffe Andy$ echo $LD_LIBRARY_PATH 
:/opt/intel/composer_xe_2015.2.132/mkl/lib:/opt/intel/composer_xe_2015.2.132/mkl/lib:/Users/andy/anaconda/lib:/Users/andy/anaconda/pkgs/mkl-11.3.1-0/lib:/anaconda/lib:/anaconda/pkgs/mkl-11.3.1-0/lib:/usr/local/cuda/lib

After that, I run "./examples/mnist/create_mnist.sh" again and still get :
Creating lmdb...
dyld: Library not loaded: libmkl_rt.dylib
  Referenced from: /Users/andy/caffe/build/examples/mnist/convert_mnist_data.bin
  Reason: image not found
./examples/mnist/create_mnist.sh: line 17:  3521 Trace/BPT trap: 5       $BUILD/convert_mnist_data.bin $DATA/train-images-idx3-ubyte $DATA/train-labels-idx1-ubyte $EXAMPLE/mnist_train_${BACKEND} --backend=${BACKEND}
dyld: Library not loaded: libmkl_rt.dylib
  Referenced from: /Users/andy/caffe/build/examples/mnist/convert_mnist_data.bin
  Reason: image not found
./examples/mnist/create_mnist.sh: line 19:  3523 Trace/BPT trap: 5       $BUILD/convert_mnist_data.bin $DATA/t10k-images-idx3-ubyte $DATA/t10k-labels-idx1-ubyte $EXAMPLE/mnist_test_${BACKEND} --backend=${BACKEND}
Done.

Please help me procees with this issue.Any help would be greatly appreciated!

**Comment by seanbell** [comment]
Please ask installation/library questions on the mailing list.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
