### ISSUE TITLE
When ./create_mnist.sh, fault: convert_mnist_data.bin: not found #1251

### ISSUE THREAD

**Issue by mk521mk** [BVLC/caffe#4239]
i run ./examples/mnist/create_mnist.sh in the caffe root dir  but it also has this problem 
 How can i slove this ?and why it appear ?

**Comment by seanbell** [comment]
It looks like you didn't build caffe?  Please ask usage/installation questions on the mailing list, and follow up there.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
