### ISSUE TITLE
VGG 16 with 10 output classes and SIGMOID_CROSS_ENTROPY_LOSS using IMAGE_DATA

### ISSUE THREAD

**Issue by mateuszbuda** [BVLC/caffe#4240]
I managed to setup VGG16 train_val.prototxt provided by @karpathy [vgg_train_val.prototxt](http://cs.stanford.edu/people/karpathy/vgg_train_val.prototxt) to use IMAGE_DATA data layer.
I also managed to change 1000 output units layer to 10.
But how can I use SIGMOID_CROSS_ENTROPY_LOSS instead of SOFTMAX_LOSS?
Is it even possible in caffe?
How should the last layers be defined and how should my source file file image paths and labels look like?
Or if not specifically for VGG16 how in general can I use SIGMOID_CROSS_ENTROPY_LOSS with IMAGE_DATA data layer (how should my source file file image paths and labels look like)? 
I either got an error that layers dimension doesn't match or that it cannot read images specified from the source file.

**Comment by seanbell** [comment]
Please ask usage/modeling questions on the mailing list.  Thanks!

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
