### ISSUE TITLE
how to open the log function

### ISSUE THREAD

**Issue by achao2013** [BVLC/caffe#4241]
when i modified some code to train in gpu mode ，i suffered some program crashes，but i don't know  the specific reasons. So  how can i open the log function to  check the log info or how can i debug the gpu code?

**Comment by seanbell** [comment]
First, enable DEBUG mode, and then do a stacktrace.  You can log from "gpu" code as long as it's not inside a kernel.  Please ask debugging/usage questions on the mailing list, and follow up there.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
