### ISSUE TITLE
unknown layer type for custom layer

### ISSUE THREAD

**Issue by LinHungShi** [BVLC/caffe#4256]
I follow the step described there [https://github.com/BVLC/caffe/wiki/Development](url). Everything is fine until I train the model in terminal, it says 

> registry.count(type) == 1 (0 vs. 1) Unknown layer type

Do I need to re-make caffe? Any suggestions would be appreciated

**Comment by seanbell** [comment]
Please ask installation/help questions on the mailing list.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
