### ISSUE TITLE
How to access the gradient of the CNN in Caffe?

### ISSUE THREAD

**Issue by QingkaiLu** [BVLC/caffe#4260]
I am wondering, how to access the gradient of a certain layer of the CNN for back propagation in Caffe? Does anyone know which file/function should I check about this? Thank you.

**Comment by seanbell** [comment]
Please ask for help on the mailing list.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
