### ISSUE TITLE
Run 'make' with CUDNN reports error

### ISSUE THREAD

**Issue by ywu36** [BVLC/caffe#4261]
Hi Admins,
I am trying to build the newest version of Caffe with CUDNN. However, it reports an error:
'usr/bin/ld: cannot find -lcudnn'

I have double checked that the library of Cudnn are in the correct place and I also changed the soft-link based on this page: http://www.cnblogs.com/platero/p/4118139.html

I am using the version of CuDNN-v4. The Caffe code was pulled several hours before.

Thanks,
Best regards,
Rein Y. Wu

**Comment by seanbell** [comment]
Please ask for installation help on the mailing list.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
