### ISSUE TITLE
Is it possible that packing a function realized with caffe into a executable file?

### ISSUE THREAD

**Issue by gzhcv** [BVLC/caffe#4262]
I realized a function using the python interface of caffe. And i try to pack this function into a executable file with the help of Pyinstaller program, but there is some problem when the Pyinstaller program import some moudle of python. it takes me much time to find out the problem. is it possible to build a executable file so as to run this program in other PC.

**Comment by seanbell** [comment]
Why not build a docker container?  That will give you a portable artifact.  Caffe has existing dockerfiles that you can start from: https://github.com/BVLC/caffe/tree/master/docker

**Comment by gzhcv** [comment]
aha! thanks very much!

**Comment by shubjain26** [comment]
Docker is good for dependency issue, but to hide source code to some extent I am trying to use pyinstaller. 
Is it possible to compile caffe project with pyinstaller? or if there is any better solution to hide source code, pls suggest.
Darknet works fine.

**Comment by Wangweilai1** [comment]
Have some idea about pyinstaller pack pycaffe ? I have't pack pycaffe use pyinstaller, it's always have some error,that's been bothering me for days. Can you help me.
Thanks
