### ISSUE TITLE
Performance issue on POWER8E

### ISSUE THREAD

**Issue by CDLuminate** [BVLC/caffe#4266]
I've successfully build caffe `rc3` on a POWER8E porter machine, both CPU_ONLY and CUDA version works well. However I benchmarked the performance of caffe on POWER8E, which yielded a very strange result.

Here is result of 5 iterations on my laptop `Intel(R) Core(TM) i5-2430M CPU 2Core 4Thread@ 2.40GHz` for reference

```
I0604 03:53:52.721225  8757 caffe.cpp:353] Iteration: 1 forward-backward time: 1689 ms.
I0604 03:53:54.318548  8757 caffe.cpp:353] Iteration: 2 forward-backward time: 1597 ms.
I0604 03:53:55.915544  8757 caffe.cpp:353] Iteration: 3 forward-backward time: 1596 ms.
I0604 03:53:57.506559  8757 caffe.cpp:353] Iteration: 4 forward-backward time: 1590 ms.
I0604 03:53:59.096426  8757 caffe.cpp:353] Iteration: 5 forward-backward time: 1589 ms.
```

Here is result of 5 iterations on the POWER8E machine, `POWER8E 16Core 128Thread`

```
I0604 03:51:45.898308 28542 caffe.cpp:353] Iteration: 1 forward-backward time: 6493 ms.
I0604 03:51:52.162766 28542 caffe.cpp:353] Iteration: 2 forward-backward time: 6263 ms.
I0604 03:51:58.498518 28542 caffe.cpp:353] Iteration: 3 forward-backward time: 6334 ms.
I0604 03:52:04.096928 28542 caffe.cpp:353] Iteration: 4 forward-backward time: 5597 ms.
I0604 03:52:10.894606 28542 caffe.cpp:353] Iteration: 5 forward-backward time: 6796 ms.
```

Test network is deploy version of `bvlc_alexnet`. We can see that _POWER8E_ is about 4 times slower than _my laptop_.

Astonishing!

**Comment by CDLuminate** [comment]
The porter machine is POWER8E but my compilation and test environment is built on KVM, there are still many unknowns to me. But at least we know the caffe package won't FTBFS (fail to build from source) on ppc64el architecture.

**Comment by CDLuminate** [comment]
i.e. This combination passed
```
POWER8E + Debian/Ubuntu+ GCC-5.3 + CUDA 7.5
```

**Comment by naibaf7** [comment]
@CDLuminate 
Do you run it with a POWER8E optimized BLAS that supports multithreading?
Even if you do that, im2col / col2im will only run single-threaded unless you use CPU-OpenCL or CPU-Parallel branches of Caffe.

**Comment by sathish249** [comment]
@CDLuminate 

Best way to compare is try running one thread per core on X86 and POWER8E. 
Best performance is always is @ one thread per core... 
So on your 16Core have 16 threads and also Intel 16 threads on 16 cores.
On my Test POWER8E was better than X86.

**Comment by CDLuminate** [comment]
I'm out of access to the POWER machine. Closing this issue.
