### ISSUE TITLE
Facepoint regression query

### ISSUE THREAD

**Issue by apdd2003** [BVLC/caffe#4268]
Hi,
I am new to ML and Caffe. I am trying to code CNN_facepoint paper using regression.
I am training using 4000 images dataset and same hd5 file for testing.
My network is predicting same 10 values for different test images when I use deploy.prototxt

**Comment by ajtulloch** [comment]
Please use the caffe-users mailing list for usage questions.

**Comment by apdd2003** [comment]
name: "facepoint"
layer {
  name: "data"
  type: "HDF5Data"
  top: "data"
  top: "label"
  include: {
    phase: TRAIN
  }
  hdf5_data_param {
    source: "/home/smk/deep-learning/caffe/examples/facepoint/train_file_location.txt"
    batch_size: 10
  }
}
layer {
  name: "data"
  type: "HDF5Data"
  top: "data"
  top: "label"
  include: {
    phase: TEST
  }
  hdf5_data_param {
    source: "/home/smk/deep-learning/caffe/examples/facepoint/train_file_location.txt"
    batch_size: 10
  }
}
layer {
  name: "conv1"
  type: "Convolution"
  bottom: "data"
  top: "conv1"
  param {
    lr_mult: 1
  }
  param {
    lr_mult: 2
  }
  convolution_param {
    num_output: 20
    pad: 0
    kernel_size: 4
    stride: 1
    weight_filler {
      type: "gaussian"
      std: 0.0001
    }
    bias_filler {
      type: "constant"
    }
  }
}

layer {
  name: "tanh1"
  bottom: "conv1"
  top: "tanh1"
  type: "TanH"
}

layer {
  name: "abs1"
  type: "AbsVal"
  bottom: "tanh1"
  top: "abs1"
}

layer {
  name: "pool1"
  type: "Pooling"
  bottom: "abs1"
  top: "pool1"
  pooling_param {
    pool: MAX
    kernel_size: 2
    stride: 2
  }
}






layer {
  name: "conv2"
  type: "Convolution"
  bottom: "pool1"
  top: "conv2"
  param {
    lr_mult: 1
  }
  param {
    lr_mult: 2
  }
  convolution_param {
    num_output: 40
    pad: 0
    kernel_size: 3
    stride: 1
    weight_filler {
      type: "gaussian"
      std: 0.01
    }
    bias_filler {
      type: "constant"
    }
  }
}
layer {
  name: "tanh2"
  bottom: "conv2"
  top: "tanh2"
  type: "TanH"
}
layer {
  name: "abs2"
  type: "AbsVal"
  bottom: "tanh2"
  top: "abs2"
}

layer {
  name: "pool2"
  type: "Pooling"
  bottom: "abs2"
  top: "pool2"
  pooling_param {
    pool: MAX
    kernel_size: 2
    stride: 2
  }
}


layer {
  name: "conv3"
  type: "Convolution"
  bottom: "pool2"
  top: "conv3"
  param {
    lr_mult: 1
  }
  param {
    lr_mult: 2
  }
  convolution_param {
    num_output: 60
    pad: 0
    kernel_size: 3
    stride: 1
    weight_filler {
      type: "gaussian"
      std: 0.01
    }
    bias_filler {
      type: "constant"
    }
  }
}

layer {
  name: "tanh3"
  bottom: "conv3"
  top: "tanh3"
  type: "TanH"
}
layer {
  name: "abs3"
  type: "AbsVal"
  bottom: "tanh3"
  top: "abs3"
}

layer {
  name: "pool3"
  type: "Pooling"
  bottom: "abs3"
  top: "pool3"
  pooling_param {
    pool: MAX
    kernel_size: 2
    stride: 2
  }
}

##

layer {
  name: "conv4"
  type: "Convolution"
  bottom: "pool3"
  top: "conv4"
  param {
    lr_mult: 1
  }
  param {
    lr_mult: 2
  }
  convolution_param {
    num_output: 80
    pad: 0
    kernel_size: 2
    stride: 1
    weight_filler {
      type: "gaussian"
      std: 0.01
    }
    bias_filler {
      type: "constant"
    }
  }
}

layer {
  name: "tanh4"
  bottom: "conv4"
  top: "tanh4"
  type: "TanH"
}
layer {
  name: "abs4"
  type: "AbsVal"
  bottom: "tanh4"
  top: "abs4"
}


##

layer {
  name: "ip1"
  type: "InnerProduct"
  bottom: "abs4"
  top: "ip1"
  param {
    lr_mult: 1
  }
  param {
    lr_mult: 2
  }
  inner_product_param {
    num_output: 120
    weight_filler {
      type: "gaussian"
      std: 0.1
    }
    bias_filler {
      type: "constant"
    }
  }
}
layer {
  name: "relu2"
  type: "ReLU"
  bottom: "ip1"
  top: "ip1"
}

layer {
  name: "ip2"
  type: "InnerProduct"
  bottom: "ip1"
  top: "ip2"
  param {
    lr_mult: 1
  }
  param {
    lr_mult: 2
  }
  inner_product_param {
    num_output: 10
    weight_filler {
      type: "gaussian"
      std: 0.1
    }
    bias_filler {
      type: "constant"
    }
  }
}
layer {
  name: "relu2"
  type: "ReLU"
  bottom: "ip2"
  top: "ip2"
}
layer {
  name: "loss"
  type: "EuclideanLoss"
  bottom: "ip2"
  bottom: "label"
  top: "loss"
  
}

**Comment by seanbell** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

**Comment by apdd2003** [comment]
ok. thanks
https://groups.google.com/forum/#!topic/caffe-users/3t1QgQNZoWA
please help
