### ISSUE TITLE
Use caffe train myself data sets,I met a problem list below:

### ISSUE THREAD

**Issue by wolfbill** [BVLC/caffe#4269]
Use caffe train myself data sets,I met a problem list below:
        I0606 10:27:41.782120  6845 layer_factory.hpp:77] Creating layer data
I0606 10:27:41.782780  6845 net.cpp:91] Creating Layer data
I0606 10:27:41.782851  6845 net.cpp:399] data -> data
I0606 10:27:41.782887  6845 net.cpp:399] data -> label
I0606 10:27:41.782918  6845 data_transformer.cpp:25] Loading mean file from: /usr/local/caffe/data/deeppic/first_deep/train/bag/ilvsrc12/imagenet_mean.binaryproto
F0606 10:27:41.784195  6852 db_leveldb.cpp:16] Check failed: status.ok() Failed to open leveldb ilvsrc12_train_leveldb
Invalid argument: ilvsrc12_train_leveldb: does not exist (create_if_missing is false)
*** Check failure stack trace: ***
    @     0x7fdb2d2cf84d  google::LogMessage::Fail()
    @     0x7fdb2d2d161c  google::LogMessage::SendToLog()
    @     0x7fdb2d2cf43c  google::LogMessage::Flush()
    @     0x7fdb2d2d1f2e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fdb2e5f0faa  caffe::db::LevelDB::Open()
    @     0x7fdb2e4fac24  caffe::DataReader::Body::InternalThreadEntry()
    @     0x7fdb2e49b2ff  caffe::InternalThread::entry()
    @     0x7fdb2df4e24a  (unknown)
    @     0x7fdb2d4fadf3  start_thread
    @     0x7fdb2294f3dd  __clone

./train_caffenet.sh: line 2:  6845 Aborted                 (core dumped) /usr/local/caffe/build/tools/caffe train --solver=/usr/local/caffe/data/deeppic/first_deep/train/bag/imagenet_solver.prototxt

I don't know where the problem is,any suggestions will be appreciate.

**Comment by seanbell** [comment]
Does the leveldb database exist?  If not, you need to create it.  Please follow up on the mailing list.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
