### ISSUE TITLE
One mistake in making matcaffe or making all matcaffe

### ISSUE THREAD

**Issue by Wangxunzero** [BVLC/caffe#4271]
First ,sorry for my poor English
There is an error  when I make all matcaffe or make matcaffe ,and there is not any mistakes when I make all,make test,make runtest .
the path of matlab has been set correct in makefile.config
MATLAB_DIR := /home/wagnxun/matlab2014b-copy/NewFolder
And really there is mex and mexext file in NewFolder/bin.
However the error message occurred.

MEX matlab/+caffe/private/caffe_.cpp
/bin/sh: 1: /home/wagnxun/matlab2014b-copy/NewFolder/bin/mex: not found
make: *** [matlab/+caffe/private/caffe_.] 错误 127

**Comment by seanbell** [comment]
Please ask installation questions on the mailing list.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
