### ISSUE TITLE
Does the input timesteps of LstmLayer have to be fixed?

### ISSUE THREAD

**Issue by dianyancao** [BVLC/caffe#4272]
I look at the code in RecurrentLayer which LstmLayer inherit from, the  RecurrentLayer<Dtype>::LayerSetUp makes the input timesteps fixed,So how to process with variable timesteps input?Does it need to call LayerSetUp in every Reshape function?

**Comment by seanbell** [comment]
Please ask usage questions on the mailing list.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
