### ISSUE TITLE
Difference in the Validation and Evaluation Accuracy

### ISSUE THREAD

**Issue by ashutosh3308** [BVLC/caffe#4275]
I am using pre-trained GoogLeNet and then fine tuned it on my dataset for classifying 11 classes. Validation dataset seems to give the "loss3/top1" 86.5%. But when I evaluating the performance on my evaluation dataset it gives me 77% accuracy. Whatever changes I did it train_val.prototxt, I did the same changes in deploy.prototxt. Is this difference between the validation and evaluation accuracy is normal or did I do something wrong? Any suggestions?

The total number of samples in the validation dataset are 4123 and in evaluation is 4118. For each class, I have made sure that validation and evaluation dataset should contain the same number of images

**Comment by seanbell** [comment]
Most likely something is different between the way that you are running the classifier in the two modes.  Please ask usage questions on the mailing list, and follow up there.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
