### ISSUE TITLE
make: *** [.build_release/lib/libcaffe.so.1.0.0-rc3] Error 1 

### ISSUE THREAD

**Issue by yup111** [BVLC/caffe#4283]
I have struggled with Caffe for two days, and always stuck at the 'make test' step. For detail, please look the code.

       LD -o .build_release/lib/libcaffe.so.1.0.0-rc3
       /usr/bin/ld: /usr/local/lib/libglog.a(libglog_la-logging.o): relocation  R_X86_64_32S against `_ZTVN6google4base6LoggerE' can not be used when making a shared object; recompile with -fPIC
        /usr/local/lib/libglog.a: error adding symbols: Bad value
        collect2: error: ld returned 1 exit status
        make: *** [.build_release/lib/libcaffe.so.1.0.0-rc3] Error 1

I'm new to this and can't really figure out what should I do. Is there anyone have encountered this issue? Please help me to fix this issue. Any idea would be appreciated.

**Comment by seanbell** [comment]
Please ask installation questions on the mailing list.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
