### ISSUE TITLE
Does "convert_imageset" support multi-label?

### ISSUE THREAD

**Issue by AlecWong** [BVLC/caffe#4284]
Anyone can help me?

**Comment by ujjwal-researcher** [comment]
Of course it does. Imagenet is a multi-label dataset, and Caffe has an example on how to use convert_imageset in that case.

**Comment by seanbell** [comment]
Please ask usage questions on the mailing list.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

**Comment by AlecWong** [comment]
@seanbell Thanks for your reminder! 
And @ujjwal-researcher , is the label can be a vector of float numbers?
