### ISSUE TITLE
No rule to make target `matcaffe'.  Stop.

### ISSUE THREAD

**Issue by puneet336** [BVLC/caffe#4286]
Hi all,
I have downloaded caffe source from git clone --recurse-submodules https://github.com/BVLC/caffe.git , and trying to compile the same using instructions from http://caffe.berkeleyvision.org/installation.html. with cmake i got:

-- The C compiler identification is GNU 4.9.3
-- The CXX compiler identification is GNU 4.9.3
-- Check for working C compiler: /home/soft/gcc-4.9.3/bin/gcc
-- Check for working C compiler: /home/soft/gcc-4.9.3/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /home/soft/gcc-4.9.3/bin/c++
-- Check for working CXX compiler: /home/soft/gcc-4.9.3/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Boost version: 1.59.0
-- Found the following Boost libraries:
--   system
--   thread
--   filesystem
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found GFlags: /home/user/MATCAFFE/Matcaffe_Dependencies/include  
-- Found gflags  (include: /home/user/MATCAFFE/Matcaffe_Dependencies/include, library: /home/user/MATCAFFE/Matcaffe_Dependencies/lib/libgflags.a)
-- Found Glog: /home/user/MATCAFFE/Matcaffe_Dependencies/include  
-- Found glog    (include: /home/user/MATCAFFE/Matcaffe_Dependencies/include, library: /home/user/MATCAFFE/Matcaffe_Dependencies/lib/libglog.a)
-- Found PROTOBUF: /home/user/MATCAFFE/Matcaffe_Dependencies/lib/libprotobuf.a  
-- Found PROTOBUF Compiler: /home/user/MATCAFFE/Matcaffe_Dependencies/bin/protoc
-- Found HDF5: /home/apps/HDF/5/1.8.16/gnu/lib/libhdf5_hl.so;/home/apps/HDF/5/1.8.16/gnu/lib/libhdf5.so  
-- Found LMDB: /home/user/MATCAFFE/Matcaffe_Dependencies/include  
-- Found lmdb    (include: /home/user/MATCAFFE/Matcaffe_Dependencies/include, library: /home/user/MATCAFFE/Matcaffe_Dependencies/lib/liblmdb.a)
-- Found LevelDB: /home/user/MATCAFFE/Matcaffe_Dependencies/include  
-- Found LevelDB (include: /home/user/MATCAFFE/Matcaffe_Dependencies/include, library: /home/user/MATCAFFE/Matcaffe_Dependencies/lib/libleveldb.a)
-- Found Snappy: /home/user/MATCAFFE/Matcaffe_Dependencies/include  
-- Found Snappy  (include: /home/user/MATCAFFE/Matcaffe_Dependencies/include, library: /home/user/MATCAFFE/Matcaffe_Dependencies/lib/libsnappy.a)
-- CUDA detected: 7.0
-- Added CUDA NVCC flags for: sm_35
-- OpenCV found (/home/apps/LIBOPENCV/2/4.13/gnu/share/OpenCV)
-- Found OpenBLAS libraries: /home/user/MATCAFFE/Matcaffe_Dependencies/lib/libopenblas.so
-- Found OpenBLAS include: /home/user/MATCAFFE/Matcaffe_Dependencies/include
-- Found PythonInterp: /home/soft/python-2.7.10/bin/python2.7 (found suitable version "2.7.10", minimum required is "2.7") 
-- Could NOT find PythonLibs (missing:  PYTHON_LIBRARIES) (found suitable version "2.7.10", minimum required is "2.7")
-- Found NumPy: /home/soft/python-2.7.10/lib/python2.7/site-packages/numpy/core/include (found suitable version "1.7.1", minimum required is "1.7.1") 
-- NumPy ver. 1.7.1 found (include: /home/soft/python-2.7.10/lib/python2.7/site-packages/numpy/core/include)
-- Boost version: 1.59.0
-- Found the following Boost libraries:
--   python
-- Found MatlabMex: /home/apps/MATLAB/R2014b/bin/mex  
-- Found Doxygen: /usr/bin/doxygen (found version "1.6.1") 
-- Python interface is disabled or not all required dependencies found. Building without it...
-- Detected Doxygen OUTPUT_DIRECTORY: ./doxygen
-- Found Git: /usr/bin/git (found version "1.7.1") 
-- 
-- ******************* Caffe Configuration Summary *******************
-- General:
--   Version           :   1.0.0-rc3
--   Git               :   rc3-184-gdf412ac-dirty
--   System            :   Linux
--   C++ compiler      :   /home/soft/gcc-4.9.3/bin/c++
--   Release CXX flags :   -O3 -DNDEBUG -fPIC -fPIC -Wall -Wno-sign-compare -Wno-uninitialized
--   Debug CXX flags   :   -g -fPIC -fPIC -Wall -Wno-sign-compare -Wno-uninitialized
--   Build type        :   Release
-- 
--   BUILD_SHARED_LIBS :   ON
--   BUILD_python      :   ON
--   BUILD_matlab      :   ON
--   BUILD_docs        :   ON
--   CPU_ONLY          :   OFF
--   USE_OPENCV        :   ON
--   USE_LEVELDB       :   ON
--   USE_LMDB          :   ON
--   ALLOW_LMDB_NOLOCK :   OFF

-- Dependencies:
--   BLAS              :   Yes (open)
--   Boost             :   Yes (ver. 1.59)
--   glog              :   Yes
--   gflags            :   Yes
--   protobuf          :   Yes (ver. 3.0.0)
--   lmdb              :   Yes (ver. 0.9.70)
--   LevelDB           :   Yes (ver. 1.18)
--   Snappy            :   Yes (ver. 1.1.3)
--   OpenCV            :   Yes (ver. 2.4.13)
--   CUDA              :   Yes (ver. 7.0)

-- NVIDIA CUDA:
--   Target GPU(s)     :   Auto
--   GPU arch(s)       :   sm_35
--   cuDNN             :   Not found

-- Matlab:
--   Matlab            :   Yes (/home/apps/MATLAB/R2014b/bin/mex, /home/apps/MATLAB/R2014b/bin/mexext
--   Octave            :   No
-- 
-- Documentaion:
--   Doxygen           :   /usr/bin/doxygen (1.6.1)
--   config_file       :   /home/user/MATCAFFE/caffe/.Doxyfile
-- 
-- Install:
--   Install path      :   /home/user/MATCAFFE
-- 
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    OpenBLAS
    OpenBLAS_HOME
    PYTHON_NUMPY_INCLUDE_DIR

-- Build files have been written to: /home/user/MATCAFFE/caffe/build

but when i executed  **make matcaffe** as per website : http://caffe.berkeleyvision.org/installation.html

[puneet@host ~/MATCAFFE/caffe/build]$ make matcaffe 2>&1|tee makelogs
make: *** No rule to make target `matcaffe'.  Stop.
make distribute also ends up with same issue.
Am i missing something here?  Is the documentation old or do i need to download **caffe source** from somewhere else ?

**Comment by seanbell** [comment]
Please ask installation questions on the mailing list.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
