### ISSUE TITLE
Undefined function 'caffe_' for input arguments of type 'char'

### ISSUE THREAD

**Issue by cschuaa** [BVLC/caffe#4289]
Hi all. I am trying to run the classification_demo. I have completed the steps stated at https://github.com/BVLC/caffe/tree/windows. I only have Matlab enabled to true. My code is extremely simple

im = imread('cat.jpg');
[score, class] = classification_demo(im, 0);

But when I run it I get the following error. Undefined function 'caffe_' for input arguments of type 'char'
Can anyone help me on this ?

**Comment by seanbell** [comment]
Please ask usage/installation questions on the mailing list.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
