### ISSUE TITLE
New Data Layer

### ISSUE THREAD

**Issue by akumar14** [BVLC/caffe#4290]
Hi , 

I am trying to create a new Data layer which outputs two data blobs and one label blob. For example, as in this paper https://arxiv.org/abs/1411.6387 , where you need raw image patches as well as pairwise information among them to be fed into the CRF Loss layer. I have implemented the data layer which takes images and computed the patches and pairwise information among them and creates two top data blobs and one top label blob. While running,  the layers are setup correctly with proper shapes  but I get the following error in the unary network, just after pool5 and before fc6. 

Can someone help me understand where am I going wrong? 

 Setting up data
I0611 14:06:55.578420 21578 net.cpp:157] Top shape: 196 3 64 64 (2408448)
I0611 14:06:55.578430 21578 net.cpp:157] Top shape: 1 5 196 196 (192080)
I0611 14:06:55.578481 21578 net.cpp:157] Top shape: 196 21 1 1 (4116)
I0611 14:06:55.578490 21578 net.cpp:165] Memory required for data: 10418576
I0611 14:06:55.578513 21578 layer_factory.hpp:77] Creating layer pairwise_data_1_split
I0611 14:06:55.578552 21578 net.cpp:106] Creating Layer pairwise_data_1_split
I0611 14:06:55.578567 21578 net.cpp:454] pairwise_data_1_split <- pairwise
I0611 14:06:55.578588 21578 net.cpp:411] pairwise_data_1_split -> pairwise_data_1_split_0
I0611 14:06:55.578605 21578 net.cpp:411] pairwise_data_1_split -> pairwise_data_1_split_1
I0611 14:06:55.578690 21578 net.cpp:150] Setting up pairwise_data_1_split
I0611 14:06:55.578704 21578 net.cpp:157] Top shape: 1 5 196 196 (192080)
I0611 14:06:55.578771 21578 net.cpp:157] Top shape: 1 5 196 196 (192080)
I0611 14:06:55.578799 21578 net.cpp:165] Memory required for data: 11955216
I0611 14:06:55.578806 21578 layer_factory.hpp:77] Creating layer conv1
I0611 14:06:55.578866 21578 net.cpp:106] Creating Layer conv1
I0611 14:06:55.578882 21578 net.cpp:454] conv1 <- data
I0611 14:06:55.578892 21578 net.cpp:411] conv1 -> conv1
I0611 14:06:55.761188 21578 net.cpp:150] Setting up conv1
I0611 14:06:55.761248 21578 net.cpp:157] Top shape: 196 96 14 14 (3687936)
I0611 14:06:55.761307 21578 net.cpp:165] Memory required for data: 26706960
I0611 14:06:55.761350 21578 layer_factory.hpp:77] Creating layer relu1
I0611 14:06:55.761379 21578 net.cpp:106] Creating Layer relu1
I0611 14:06:55.761394 21578 net.cpp:454] relu1 <- conv1
I0611 14:06:55.761414 21578 net.cpp:397] relu1 -> conv1 (in-place)
I0611 14:06:55.761874 21578 net.cpp:150] Setting up relu1
I0611 14:06:55.761904 21578 net.cpp:157] Top shape: 196 96 14 14 (3687936)
I0611 14:06:55.761917 21578 net.cpp:165] Memory required for data: 41458704
I0611 14:06:55.761930 21578 layer_factory.hpp:77] Creating layer pool1
I0611 14:06:55.761971 21578 net.cpp:106] Creating Layer pool1
I0611 14:06:55.761984 21578 net.cpp:454] pool1 <- conv1
I0611 14:06:55.762001 21578 net.cpp:411] pool1 -> pool1
I0611 14:06:55.762097 21578 net.cpp:150] Setting up pool1
I0611 14:06:55.762118 21578 net.cpp:157] Top shape: 196 96 7 7 (921984)
I0611 14:06:55.762130 21578 net.cpp:165] Memory required for data: 45146640
I0611 14:06:55.762142 21578 layer_factory.hpp:77] Creating layer norm1
I0611 14:06:55.762173 21578 net.cpp:106] Creating Layer norm1
I0611 14:06:55.762189 21578 net.cpp:454] norm1 <- pool1
I0611 14:06:55.762207 21578 net.cpp:411] norm1 -> norm1
I0611 14:06:55.762522 21578 net.cpp:150] Setting up norm1
I0611 14:06:55.762547 21578 net.cpp:157] Top shape: 196 96 7 7 (921984)
I0611 14:06:55.762560 21578 net.cpp:165] Memory required for data: 48834576
I0611 14:06:55.762575 21578 layer_factory.hpp:77] Creating layer conv2
I0611 14:06:55.762601 21578 net.cpp:106] Creating Layer conv2
I0611 14:06:55.762616 21578 net.cpp:454] conv2 <- norm1
I0611 14:06:55.762635 21578 net.cpp:411] conv2 -> conv2
I0611 14:06:55.781648 21578 net.cpp:150] Setting up conv2
I0611 14:06:55.781718 21578 net.cpp:157] Top shape: 196 256 7 7 (2458624)
I0611 14:06:55.781730 21578 net.cpp:165] Memory required for data: 58669072
I0611 14:06:55.781824 21578 layer_factory.hpp:77] Creating layer relu2
I0611 14:06:55.781848 21578 net.cpp:106] Creating Layer relu2
I0611 14:06:55.781862 21578 net.cpp:454] relu2 <- conv2
I0611 14:06:55.781882 21578 net.cpp:397] relu2 -> conv2 (in-place)
I0611 14:06:55.782169 21578 net.cpp:150] Setting up relu2
I0611 14:06:55.782194 21578 net.cpp:157] Top shape: 196 256 7 7 (2458624)
I0611 14:06:55.782205 21578 net.cpp:165] Memory required for data: 68503568
I0611 14:06:55.782220 21578 layer_factory.hpp:77] Creating layer pool2
I0611 14:06:55.782241 21578 net.cpp:106] Creating Layer pool2
I0611 14:06:55.782253 21578 net.cpp:454] pool2 <- conv2
I0611 14:06:55.782268 21578 net.cpp:411] pool2 -> pool2
I0611 14:06:55.782343 21578 net.cpp:150] Setting up pool2
I0611 14:06:55.782362 21578 net.cpp:157] Top shape: 196 256 3 3 (451584)
I0611 14:06:55.782373 21578 net.cpp:165] Memory required for data: 70309904
I0611 14:06:55.782430 21578 layer_factory.hpp:77] Creating layer norm2
I0611 14:06:55.782456 21578 net.cpp:106] Creating Layer norm2
I0611 14:06:55.782470 21578 net.cpp:454] norm2 <- pool2
I0611 14:06:55.782490 21578 net.cpp:411] norm2 -> norm2
I0611 14:06:55.783020 21578 net.cpp:150] Setting up norm2
I0611 14:06:55.783047 21578 net.cpp:157] Top shape: 196 256 3 3 (451584)
I0611 14:06:55.783058 21578 net.cpp:165] Memory required for data: 72116240
I0611 14:06:55.783072 21578 layer_factory.hpp:77] Creating layer conv3
I0611 14:06:55.783103 21578 net.cpp:106] Creating Layer conv3
I0611 14:06:55.783115 21578 net.cpp:454] conv3 <- norm2
I0611 14:06:55.783133 21578 net.cpp:411] conv3 -> conv3
I0611 14:06:55.827277 21578 net.cpp:150] Setting up conv3
I0611 14:06:55.827332 21578 net.cpp:157] Top shape: 196 384 3 3 (677376)
I0611 14:06:55.827345 21578 net.cpp:165] Memory required for data: 74825744
I0611 14:06:55.827391 21578 layer_factory.hpp:77] Creating layer relu3
I0611 14:06:55.827455 21578 net.cpp:106] Creating Layer relu3
I0611 14:06:55.827476 21578 net.cpp:454] relu3 <- conv3
I0611 14:06:55.827497 21578 net.cpp:397] relu3 -> conv3 (in-place)
I0611 14:06:55.827736 21578 net.cpp:150] Setting up relu3
I0611 14:06:55.827760 21578 net.cpp:157] Top shape: 196 384 3 3 (677376)
I0611 14:06:55.827772 21578 net.cpp:165] Memory required for data: 77535248
I0611 14:06:55.827783 21578 layer_factory.hpp:77] Creating layer conv4
I0611 14:06:55.827827 21578 net.cpp:106] Creating Layer conv4
I0611 14:06:55.827854 21578 net.cpp:454] conv4 <- conv3
I0611 14:06:55.827870 21578 net.cpp:411] conv4 -> conv4
I0611 14:06:55.856413 21578 net.cpp:150] Setting up conv4
I0611 14:06:55.856442 21578 net.cpp:157] Top shape: 196 384 3 3 (677376)
I0611 14:06:55.856452 21578 net.cpp:165] Memory required for data: 80244752
I0611 14:06:55.856465 21578 layer_factory.hpp:77] Creating layer relu4
I0611 14:06:55.856480 21578 net.cpp:106] Creating Layer relu4
I0611 14:06:55.856490 21578 net.cpp:454] relu4 <- conv4
I0611 14:06:55.856501 21578 net.cpp:397] relu4 -> conv4 (in-place)
I0611 14:06:55.856705 21578 net.cpp:150] Setting up relu4
I0611 14:06:55.856724 21578 net.cpp:157] Top shape: 196 384 3 3 (677376)
I0611 14:06:55.856732 21578 net.cpp:165] Memory required for data: 82954256
I0611 14:06:55.856741 21578 layer_factory.hpp:77] Creating layer conv5
I0611 14:06:55.856770 21578 net.cpp:106] Creating Layer conv5
I0611 14:06:55.856781 21578 net.cpp:454] conv5 <- conv4
I0611 14:06:55.856802 21578 net.cpp:411] conv5 -> conv5
I0611 14:06:55.874984 21578 net.cpp:150] Setting up conv5
I0611 14:06:55.875010 21578 net.cpp:157] Top shape: 196 256 3 3 (451584)
I0611 14:06:55.875020 21578 net.cpp:165] Memory required for data: 84760592
I0611 14:06:55.875052 21578 layer_factory.hpp:77] Creating layer relu5
I0611 14:06:55.875069 21578 net.cpp:106] Creating Layer relu5
I0611 14:06:55.875080 21578 net.cpp:454] relu5 <- conv5
I0611 14:06:55.875092 21578 net.cpp:397] relu5 -> conv5 (in-place)
I0611 14:06:55.875288 21578 net.cpp:150] Setting up relu5
I0611 14:06:55.875308 21578 net.cpp:157] Top shape: 196 256 3 3 (451584)
I0611 14:06:55.875318 21578 net.cpp:165] Memory required for data: 86566928
I0611 14:06:55.875327 21578 layer_factory.hpp:77] Creating layer pool5
I0611 14:06:55.875347 21578 net.cpp:106] Creating Layer pool5
I0611 14:06:55.875360 21578 net.cpp:454] pool5 <- conv5
I0611 14:06:55.875377 21578 net.cpp:411] pool5 -> pool5
I0611 14:06:55.875433 21578 net.cpp:150] Setting up pool5
I0611 14:06:55.875449 21578 net.cpp:157] Top shape: 196 256 1 1 (50176)
I0611 14:06:55.875461 21578 net.cpp:165] Memory required for data: 86767632
I0611 14:06:55.875471 21578 layer_factory.hpp:77] Creating layer fc6
I0611 14:06:55.875502 21578 net.cpp:106] Creating Layer fc6
I0611 14:06:55.875515 21578 net.cpp:454] fc6 <- pool5
I0611 14:06:55.875532 21578 net.cpp:411] fc6 -> fc6
I0611 14:06:55.877804 21578 net.cpp:150] Setting up fc6
I0611 14:06:55.877822 21578 net.cpp:157] Top shape: 196 256 (50176)
I0611 14:06:55.877831 21578 net.cpp:165] Memory required for data: 86968336
I0611 14:06:55.877843 21578 layer_factory.hpp:77] Creating layer relu6
I0611 14:06:55.877894 21578 net.cpp:106] Creating Layer relu6
I0611 14:06:55.877904 21578 net.cpp:454] relu6 <- fc6
I0611 14:06:55.877917 21578 net.cpp:397] relu6 -> fc6 (in-place)
I0611 14:06:55.878253 21578 net.cpp:150] Setting up relu6
I0611 14:06:55.878274 21578 net.cpp:157] Top shape: 196 256 (50176)
I0611 14:06:55.878284 21578 net.cpp:165] Memory required for data: 87169040
I0611 14:06:55.878303 21578 layer_factory.hpp:77] Creating layer drop6
I0611 14:06:55.878319 21578 net.cpp:106] Creating Layer drop6
I0611 14:06:55.878329 21578 net.cpp:454] drop6 <- fc6
I0611 14:06:55.878346 21578 net.cpp:397] drop6 -> fc6 (in-place)
I0611 14:06:55.878399 21578 net.cpp:150] Setting up drop6
I0611 14:06:55.878414 21578 net.cpp:157] Top shape: 196 256 (50176)
I0611 14:06:55.878424 21578 net.cpp:165] Memory required for data: 87369744
I0611 14:06:55.878433 21578 layer_factory.hpp:77] Creating layer fc7
I0611 14:06:55.878451 21578 net.cpp:106] Creating Layer fc7
I0611 14:06:55.878460 21578 net.cpp:454] fc7 <- fc6
I0611 14:06:55.878478 21578 net.cpp:411] fc7 -> fc7
I0611 14:06:55.883369 21578 net.cpp:150] Setting up fc7
I0611 14:06:55.883391 21578 net.cpp:157] Top shape: 196 512 (100352)
I0611 14:06:55.883450 21578 net.cpp:165] Memory required for data: 87771152
I0611 14:06:55.883463 21578 layer_factory.hpp:77] Creating layer relu7
I0611 14:06:55.883493 21578 net.cpp:106] Creating Layer relu7
I0611 14:06:55.883504 21578 net.cpp:454] relu7 <- fc7
I0611 14:06:55.883527 21578 net.cpp:397] relu7 -> fc7 (in-place)
I0611 14:06:55.883719 21578 net.cpp:150] Setting up relu7
I0611 14:06:55.883738 21578 net.cpp:157] Top shape: 196 512 (100352)
I0611 14:06:55.883749 21578 net.cpp:165] Memory required for data: 88172560
I0611 14:06:55.883759 21578 layer_factory.hpp:77] Creating layer drop7
I0611 14:06:55.883771 21578 net.cpp:106] Creating Layer drop7
I0611 14:06:55.883781 21578 net.cpp:454] drop7 <- fc7
I0611 14:06:55.883805 21578 net.cpp:397] drop7 -> fc7 (in-place)
I0611 14:06:55.883843 21578 net.cpp:150] Setting up drop7
I0611 14:06:55.883858 21578 net.cpp:157] Top shape: 196 512 (100352)
I0611 14:06:55.883867 21578 net.cpp:165] Memory required for data: 88573968
I0611 14:06:55.883889 21578 layer_factory.hpp:77] Creating layer fc8_pascal
I0611 14:06:55.883903 21578 net.cpp:106] Creating Layer fc8_pascal
I0611 14:06:55.883913 21578 net.cpp:454] fc8_pascal <- fc7
I0611 14:06:55.883929 21578 net.cpp:411] fc8_pascal -> fc8_pascal
I0611 14:06:55.884397 21578 net.cpp:150] Setting up fc8_pascal
I0611 14:06:55.884414 21578 net.cpp:157] Top shape: 196 21 (4116)
I0611 14:06:55.884426 21578 net.cpp:165] Memory required for data: 88590432
I0611 14:06:55.884438 21578 layer_factory.hpp:77] Creating layer conv1_pw
I0611 14:06:55.884464 21578 net.cpp:106] Creating Layer conv1_pw
I0611 14:06:55.884479 21578 net.cpp:454] conv1_pw <- pairwise_data_1_split_0
I0611 14:06:55.884495 21578 net.cpp:411] conv1_pw -> conv1_pw
I0611 14:06:55.885731 21578 net.cpp:150] Setting up conv1_pw
I0611 14:06:55.885756 21578 net.cpp:157] Top shape: 1 1 196 196 (38416)
I0611 14:06:55.885767 21578 net.cpp:165] Memory required for data: 88744096
I0611 14:06:55.885802 21578 layer_factory.hpp:77] Creating layer ReLU1_pw
I0611 14:06:55.885818 21578 net.cpp:106] Creating Layer ReLU1_pw
I0611 14:06:55.885829 21578 net.cpp:454] ReLU1_pw <- conv1_pw
I0611 14:06:55.885848 21578 net.cpp:397] ReLU1_pw -> conv1_pw (in-place)
I0611 14:06:55.886178 21578 net.cpp:150] Setting up ReLU1_pw
I0611 14:06:55.886198 21578 net.cpp:157] Top shape: 1 1 196 196 (38416)
I0611 14:06:55.886210 21578 net.cpp:165] Memory required for data: 88897760
I0611 14:06:55.886224 21578 layer_factory.hpp:77] Creating layer norm1_pw
I0611 14:06:55.886243 21578 net.cpp:106] Creating Layer norm1_pw
I0611 14:06:55.886255 21578 net.cpp:454] norm1_pw <- conv1_pw
I0611 14:06:55.886279 21578 net.cpp:411] norm1_pw -> norm1_pw
I0611 14:06:55.886488 21578 net.cpp:150] Setting up norm1_pw
I0611 14:06:55.886507 21578 net.cpp:157] Top shape: 1 1 196 196 (38416)
I0611 14:06:55.886521 21578 net.cpp:165] Memory required for data: 89051424
I0611 14:06:55.886553 21578 layer_factory.hpp:77] Creating layer loss
I0611 14:06:55.886579 21578 net.cpp:106] Creating Layer loss
I0611 14:06:55.886593 21578 net.cpp:454] loss <- fc8_pascal
I0611 14:06:55.886608 21578 net.cpp:454] loss <- norm1_pw
I0611 14:06:55.886618 21578 net.cpp:454] loss <- pairwise_data_1_split_1
I0611 14:06:55.886631 21578 net.cpp:454] loss <- label_gauss
I0611 14:06:55.886649 21578 net.cpp:411] loss -> Loss
I0611 14:06:55.887176 21578 net.cpp:150] Setting up loss
I0611 14:06:55.887194 21578 net.cpp:157] Top shape: (1)
I0611 14:06:55.887207 21578 net.cpp:160]     with loss weight 1
I0611 14:06:55.887234 21578 net.cpp:165] Memory required for data: 89051428
I0611 14:06:55.887246 21578 net.cpp:226] loss needs backward computation.
I0611 14:06:55.887255 21578 net.cpp:226] norm1_pw needs backward computation.
I0611 14:06:55.887266 21578 net.cpp:226] ReLU1_pw needs backward computation.
I0611 14:06:55.887277 21578 net.cpp:226] conv1_pw needs backward computation.
I0611 14:06:55.887290 21578 net.cpp:226] fc8_pascal needs backward computation.
I0611 14:06:55.887302 21578 net.cpp:226] drop7 needs backward computation.
I0611 14:06:55.887317 21578 net.cpp:226] relu7 needs backward computation.
I0611 14:06:55.887326 21578 net.cpp:226] fc7 needs backward computation.
I0611 14:06:55.887338 21578 net.cpp:226] drop6 needs backward computation.
I0611 14:06:55.887346 21578 net.cpp:226] relu6 needs backward computation.
I0611 14:06:55.887357 21578 net.cpp:226] fc6 needs backward computation.
I0611 14:06:55.887365 21578 net.cpp:226] pool5 needs backward computation.
I0611 14:06:55.887377 21578 net.cpp:226] relu5 needs backward computation.
I0611 14:06:55.887388 21578 net.cpp:226] conv5 needs backward computation.
I0611 14:06:55.887398 21578 net.cpp:226] relu4 needs backward computation.
I0611 14:06:55.887411 21578 net.cpp:226] conv4 needs backward computation.
I0611 14:06:55.887424 21578 net.cpp:226] relu3 needs backward computation.
I0611 14:06:55.887433 21578 net.cpp:226] conv3 needs backward computation.
I0611 14:06:55.887444 21578 net.cpp:226] norm2 needs backward computation.
I0611 14:06:55.887452 21578 net.cpp:226] pool2 needs backward computation.
I0611 14:06:55.887465 21578 net.cpp:226] relu2 needs backward computation.
I0611 14:06:55.887477 21578 net.cpp:226] conv2 needs backward computation.
I0611 14:06:55.887485 21578 net.cpp:226] norm1 needs backward computation.
I0611 14:06:55.887496 21578 net.cpp:226] pool1 needs backward computation.
I0611 14:06:55.887506 21578 net.cpp:226] relu1 needs backward computation.
I0611 14:06:55.887516 21578 net.cpp:226] conv1 needs backward computation.
I0611 14:06:55.887526 21578 net.cpp:228] pairwise_data_1_split does not need backward computation.
I0611 14:06:55.887538 21578 net.cpp:228] data does not need backward computation.
I0611 14:06:55.887550 21578 net.cpp:270] This network produces output Loss
I0611 14:06:55.887576 21578 net.cpp:283] Network initialization done.
I0611 14:06:55.887765 21578 solver.cpp:60] Solver scaffolding done.
I0611 14:06:55.888425 21578 caffe.cpp:213] Starting Optimization
I0611 14:06:55.888443 21578 solver.cpp:280] Solving UnaryNetwork
I0611 14:06:55.888453 21578 solver.cpp:281] Learning Rate Policy: step
I0611 14:06:55.889749 21578 blocking_queue.cpp:50] Data layer prefetch queue empty
F0611 14:06:57.312163 21578 inner_product_layer.cpp:58] Check failed: K_ == new_K (256 vs. 9216) Input size incompatible with inner product parameters.
*** Check failure stack trace: ***
    @     0x7f915af69e6d  (unknown)
    @     0x7f915af6bced  (unknown)
    @     0x7f915af69a5c  (unknown)
    @     0x7f915af6c63e  (unknown)
    @     0x7f91609ab037  caffe::InnerProductLayer<>::Reshape()
    @     0x7f9160ab3096  caffe::Net<>::ForwardFromTo()
    @     0x7f9160ab3437  caffe::Net<>::ForwardPrefilled()
    @     0x7f9160979a65  caffe::Solver<>::Step()
    @     0x7f916097a369  caffe::Solver<>::Solve()
    @           0x4086fb  train()
    @           0x40608c  main
    @     0x7f91525bbb15  __libc_start_main
    @           0x4067c1  (unknown)
./train_crf.sh: line 5: 21578 Aborted                 (core dumped) GLOG_logtostderr=0 /scratch1/caffe_crf/caffe/build/tools/caffe.bin -gpu 1 train -solver solver_crf.prototxt

**Comment by seanbell** [comment]
Please ask modeling questions on the mailing list.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
