### ISSUE TITLE
How can I run examples of Caffe in windows?

### ISSUE THREAD

**Issue by aysegulucar2016** [BVLC/caffe#4296]
How can I run examples of Caffe in windows?
There are some examples (for example mnist).

Could you please  give step-by step instruction?

Are there anyone using cmake for official caffe-windows? or How do you design caffe projects?

Previously many thnanks

**Comment by seanbell** [comment]
Please ask for usage/installation help on the mailing list.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

**Comment by aysegulucar2016** [comment]
I cant run examples.
