### ISSUE TITLE
caffe matlab install windows

### ISSUE THREAD

**Issue by cschuaa** [BVLC/caffe#4297]
Hi anyone have video on how to install matlab caffe for windows ? The instructions here https://github.com/BVLC/caffe/tree/windows are not working for me. I have spent 1 week on this. someone please help me i beg you

**Comment by seanbell** [comment]
Please ask for installation help on the mailing list.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
