### ISSUE TITLE
How to train imagenet with reduced memory and batch size?

### ISSUE THREAD

**Issue by research2010** [BVLC/caffe#430]
Hi, thank you very much for this valuable library!

The hardware and software environments are as follows:
1. NVIDIA GTX 750 Ti (2G)
2. Ubuntu 12.04

When with the default train configuration file for imagenet data set, the train_net.bin will error with "out of memory". So I change the batch_size into 64 (128 also not valid). Then it works!
The following is the output of train_net.bin:
![qq20140521152144](https://cloud.githubusercontent.com/assets/1638818/3037133/ca33b4f6-e0b8-11e3-924d-cecb9bf6ec1f.jpg)

And the results are as follows after 2000 iterations:
![qq20140521155321](https://cloud.githubusercontent.com/assets/1638818/3037366/40a9cfcc-e0bd-11e3-993a-150a94b6a0e5.jpg)

It seems the testing scores are not changed. As indicated in https://github.com/BVLC/caffe/issues/218, @sguada said that the batch_size and the learning rate are linked. I have set the batch_size is 64, maybe the learning rate should also be modified. Could anyone give any advice on this subject, please?

**Comment by WoooHaa** [comment]
@research2010 Hello,I see the accuracy result you plot has "second increase phase" in iter 200000.
How did you do it? My training is running for one month but it dose not increase any more since it get first "bottleneck" .
Thanks

**Comment by DAIK0N** [comment]
@research2010 
hey you commented on Jul 12, 2014 with the 2 pictures of the caffenet and alexnet, did you parse the prototxt file and print them out via graphviz? or how did u produce these two images?

**Comment by jstaker7** [comment]
Sorry to chime in so late on a closed issue -- but I'm trying to understand the same think that WoooHaa commented about. What is the cause of the "bottlenecks" and how are these overcome? It seems dangerously easy to wait so long and think that training has converged to an optimal value, when it hasn't yet.

**Comment by DAIK0N** [comment]
thats the "step" a change in the learning rate. So when there is a failure it changes the weights with a stronger effect. When u would start with that higher learning rate from the beginning, your program would start to bounch and would never get better so you have to start with a lower learning rate and increase it when your system reaches saturation. In the plots you can see that he set his step value to 20 000 because you see these changes at 20 000, 40 000 and 60 000.

**Comment by jstaker7** [comment]
Thank you for the response! Just to clarify... I usually start with a higher learning rate and decrease it over time. But what you say is actually _increase_ the learning later on during training?

**Comment by DAIK0N** [comment]
https://github.com/BVLC/caffe/issues/430#issuecomment-48795443

**Comment by DAIK0N** [comment]
oh you are right.. you have to drop the learning rate ;)

**Comment by jstaker7** [comment]
Ah gotcha, it all makes sense now. Thank you!
