### ISSUE TITLE
caffe windows installation

### ISSUE THREAD

**Issue by aysegulucar2016** [BVLC/caffe#4306]
How to install Caffe in windows in 5 min

https://www.youtube.com/watch?v=nrzAF2sxHHM

**Comment by seanbell** [comment]
Thanks for the link, but this isn't really an issue, so I am going to close it.  Please feel free to post it to the mailing list.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
