### ISSUE TITLE
Is it possible to define lr_mult=0 for specific parameters in layer ?

### ISSUE THREAD

**Issue by yossibiton** [BVLC/caffe#4307]
Some model compression methods prune "weak" network connections and retrain the network (see DeepCompression for example).
In order to do that in caffe i have to define lr_mult=0 for specific parameters in layer. 
Is it possible to do that ?
If not, can anyone guide me what changes i have to add for making that possible. thanks.

(if this is not the right address for this post please tell me and i will post in the google group)

**Comment by seanbell** [comment]
Yes, please ask this kind of question on the mailing list.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
