### ISSUE TITLE
trainning MNIST error with rCDUA

### ISSUE THREAD

**Issue by gaoxian001** [BVLC/caffe#4312]
Environment：
OS:    CentOS 6.5
GPU:  Tesla K40m

Install Caffe in one Client Node that without GPU, when trainning MNIST there are some fatal errors happened, such as:

[root@Client caffe-master]# ./build/tools/caffe train --solver=examples/mnist/lenet_solver.prototxt -gpu 0
I0614 20:31:55.515300 20796 caffe.cpp:185] Using GPUs 0
I0614 20:31:55.516058 20796 caffe.cpp:190] GPU 0: Tesla K40m
I0614 20:31:55.622133 20796 solver.cpp:48] Initializing solver from parameters: 
...
I0614 20:31:56.035938 20796 net.cpp:425] loss <- ip2
I0614 20:31:56.035956 20796 net.cpp:425] loss <- label
I0614 20:31:56.035976 20796 net.cpp:399] loss -> loss
I0614 20:31:56.036015 20796 layer_factory.hpp:77] Creating layer loss
[rCUDA-1684] InfiniBand error: Verb ibv_reg_mr returned -1 (errno 22).
[rCUDA-874] rCUDA error: Socket peer closed connection.
*** Aborted at 1465907516 (unix time) try "date -d @1465907516" if you are using GNU date ***
PC: @       0x3396c32925 (unknown)
*** SIGABRT (@0x513c) received by PID 20796 (TID 0x7fa15de4c700) from PID 20796; stack trace: ***
    @       0x339740f710 (unknown)
    @       0x3396c32925 (unknown)
    @       0x3396c34105 (unknown)
    @     0x7fa1629aa571 rCUDAcommIB::waitCompletion<>()
    @     0x7fa1629aa733 rCUDAcommCliIB::getRemoteRes()
    @     0x7fa16537f565 ReceiveFunctionsResult()
    @       0x33974079d1 (unknown)
    @       0x3396ce8b6d (unknown)
Aborted (core dumped)

**Comment by flx42** [comment]
Doesn't look like a Caffe problem.

**Comment by seanbell** [comment]
Yes, closing since I don't think you are using the master branch of BVLC/caffe.  The string `rCUDA` appears nowhere in BVLC/caffe.

You should ask whoever is the maintainer of the your codebase for help.
