### ISSUE TITLE
how to change dimension of blob on proto

### ISSUE THREAD

**Issue by seokhoonboo** [BVLC/caffe#4313]
In the prototxt,
I want to chage dimension to connect "InnerProduct -> Convolusion". So i use ReshapeLayer, but I don know how to use it correctly.

i coded like below

   n.data, n.label = L.Data(batch_size=batch_size, backend=P.Data.LMDB, source=lmdb,
                             transform_param=dict(scale=1./255), ntop=2)
    
    n.ip1 =   L.InnerProduct(n.data, num_output=784, weight_filler=dict(type='xavier'))
    n.resh1 = L.Reshape(n.ip1,reshape_param=dict(shape=dict(dim=2)))
    n.conv1 = L.Convolution(n.resh1, kernel_size=5, num_output=20, weight_filler=dict(type='xavier'))

**Comment by seanbell** [comment]
Please ask usage questions on the mailing list.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
