### ISSUE TITLE
CUDA error on OS X

### ISSUE THREAD

**Issue by zdong01** [BVLC/caffe#4315]
DataLayerTest/2.TestReadCropTrainSequenceSeededLMDB
F0614 20:13:13.057540 2097754112 internal_thread.cpp:26] Check failed: error == cudaSuccess (35 vs. 0)  CUDA driver version is insufficient for CUDA runtime version
*** Check failure stack trace: ***
    @        0x10bcf8522  google::LogMessage::Fail()
    @        0x10bcf7c24  google::LogMessage::SendToLog()
    @        0x10bcf817b  google::LogMessage::Flush()
    @        0x10bcfb4c5  google::LogMessageFatal::~LogMessageFatal()
    @        0x10bcf880f  google::LogMessageFatal::~LogMessageFatal()
    @        0x11548301e  caffe::InternalThread::StartInternalThread()
    @        0x1154730a3  caffe::DataReader::Body::Body()
    @        0x11547237e  caffe::DataReader::DataReader()
    @        0x1154bad3c  caffe::DataLayer<>::DataLayer()
    @        0x10690c400  caffe::DataLayerTest<>::TestReadCropTrainSequenceSeeded()
    @        0x106e2e03a  testing::internal::HandleExceptionsInMethodIfSupported<>()
    @        0x106e1db1a  testing::Test::Run()
    @        0x106e1e922  testing::TestInfo::Run()
    @        0x106e1f043  testing::TestCase::Run()
    @        0x106e2484b  testing::internal::UnitTestImpl::RunAllTests()
    @        0x106e2e853  testing::internal::HandleExceptionsInMethodIfSupported<>()
    @        0x106e24549  testing::UnitTest::Run()
    @        0x1067ad27a  main
    @     0x7fff9b9f05ad  start
    @                0x3  (unknown)
make: *** [runtest] Abort trap: 6

I have installed latest CUDA-7.5 and CUDA driver, with cuDNN v5. 
OS X 10.11.5. 
![screen shot 2016-06-14 at 8 16 34 pm](https://cloud.githubusercontent.com/assets/11573892/16064193/ed29b138-326c-11e6-9ccc-ad5967abce1e.png)

**Comment by seanbell** [comment]
Based on that error message, I believe if you tried any other CUDA test or program, it would fail too (e.g. an example CUDA program, not caffe).

It looks like this question is related to CUDA installation on a Mac, and not related to caffe.  Please ask for help with installation on the mailing list.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
