### ISSUE TITLE
Problem with loading npy file of extracted features! unexpected output!!

### ISSUE THREAD

**Issue by SunMoonSea** [BVLC/caffe#4318]
Hello, I've used the tutorial of [[Caffe]](http://caffe.berkeleyvision.org/gathered/examples/feature_extraction.html) to extract successfully features from a set of images. Then, I used this code to convert the results stored in features file under leveldb format to npy file : 
```
import caffe 
import os
import leveldb
import caffe.proto
from caffe.proto import caffe_pb2
import caffe.io
import numpy as np

input_path='../examples/images/'
path='../examples/test/npy/'
files = os.listdir(input_path)

db = leveldb.LevelDB('../examples/_temp/features')

for k in range(len(files)): 
            datum = caffe_pb2.Datum.FromString(db.Get(str(k)))
            arr = caffe.io.datum_to_array(datum)
        file=files[k]
        out=np.save(path+file[0:len(file)-4],arr)
``` 

However, the results of each extraction from each image represented by vector arr is not 4096-dim vector as shown below
![image](https://cloud.githubusercontent.com/assets/19950733/16078489/8d8c48d8-32ff-11e6-93d7-e44cf062ac49.png)
I need the results as vectors to be inputs for LLSVM classifier. Did I miss something? How to get the correct vector feature from the extraction phase  (from results in leveldb format)? Thank you in advance for your help.

**Comment by seanbell** [comment]
I think you want `arr.ravel()` to flatten the array.  You may want to look at `arr.shape` to better understand the shape of the object before trying to slice into it.  Based on your screenshot, it just looks like you have a high-dimensional array and aren't indexing into it correctly.  `len(arr)` only returns the shape of the first dimension.

Please ask questions about how to use caffe on the mailing list.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

**Comment by SunMoonSea** [comment]
Okay, thank you @seanbell  for your reply.
