### ISSUE TITLE
How to add scale in deploy prototxt file

### ISSUE THREAD

**Issue by zdong01** [BVLC/caffe#4321]
I created my training and testing lmdb database from greyscale images, both with scaling factor of 1/255.0. 
During training and testing, I got expected accuracy. 
Now I want deploy pretrained caffemodel with C++ interface (classification.bin), and specified deploy version of prototxt file. I added 

    transform_param {
      scale: 0.00390625
    }

in the very beginning layer, similar to train_test version of prototxt, but it seems useless, and classification result is incorrect. 
I also tried to scale input image, but pixel values should be integer, and if I divide them by 255, they are all 0. 
How can I define a floating-point scaling in deploy prototxt file?

**Comment by seanbell** [comment]
Please ask the mailing list for help in using caffe.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
