### ISSUE TITLE
connectionist temporal classification

### ISSUE THREAD

**Issue by milanwen1983** [BVLC/caffe#4322]
Hello, everyone, 
recently I'm working on scene text recogniton, I've read some papers about using CNN, LSTM and connectionist temporal classification to solve this problem. LSTM layer has been merge to caffe,.Right now I am wondering that whether the CTC(connectionist temporal classification) would be implemented in    caffe framework, and is there any possible that some LSTM example applied in text recogniton will be created in the example directory.

**Comment by seanbell** [comment]
Please ask modeling questions on the mailing list.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

**Comment by wew2012** [comment]
I want to ask the same questiion. Do you have any idea? @milanwen1983
