### ISSUE TITLE
MemoryDataLayer with Labels for Regression 

### ISSUE THREAD

**Issue by MennatulSiam** [BVLC/caffe#4323]
I'm trying to use MemoryDataLayer in C++ but for a regression problem where the labels is not just int but a vector. I successfully used it before for a classification problem and I had no trouble with that, where I used the function AddMatVector(). But this code only supports int labels, is there a way to use that for regression?

Thanks,

**Comment by seanbell** [comment]
Please ask questions about how to use caffe on the mailing list.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

**Comment by MennatulSiam** [comment]
But it's not a question. The MemoryDataLayer doesn't support except int labels that wouldn't work with regression. So it's an issue that needs to be solved. 
AddMatVector(const vector<cv::Mat>& mat_vector, const vector<int>& labels)
It's accepting only int labels that's for classification. Unless you consider this as not an issue.

**Comment by artheru** [comment]
I think this is a historical issue. Don't use memory data layer, just use "input" layer, "input" layer generates a "blob", then you simply put data into this "blob".

for example:
```
layer{
type: "input"
top:"xxx"
input_param { shape: { dim: 1 dim: 123 dim: 1 dim: 1 } }
}
```

TADA

I think our developers really should rewrite the documentations.

**Comment by hmirzaei** [comment]
@artheru, I have the same issue. could you elaborate more or provide an example how to put data into a blob.

**Comment by artheru** [comment]
sure:

net.blobs["input"].data[0,...]=np.array([1,2,3,4,5,6])

TADA

**Comment by MennatulSiam** [comment]
@artheru  Can you please provide an example on how to use the input layer with float labels (for regression) in C++ not python.

Thanks

**Comment by artheru** [comment]
Sorry, I don't use cpp interfaces, I only use python.

**Comment by mrgloom** [comment]
@artheru in your example net get data directly from numpy array? Can you provide more complete python example?
