### ISSUE TITLE
CURAND_STATUS_LAUNCH_FAILURE with GTX 1080

### ISSUE THREAD

**Issue by danielgordon10** [BVLC/caffe#4324]
Running CUDA 7.5, CUDNN 5.
Test that fails: any involving the GPU random number generator. EG test_random_number_generator.testbin

Fails on master with or without the DEBUG flag.

F0616 13:17:34.736345 13420 math_functions.cu:408] Check failed: status == CURAND_STATUS_SUCCESS (201 vs. 0)  CURAND_STATUS_LAUNCH_FAILURE
*** Check failure stack trace: ***
    @     0x7f54481c1daa  (unknown)
    @     0x7f54481c1ce4  (unknown)
    @     0x7f54481c16e6  (unknown)
    @     0x7f54481c4687  (unknown)
    @     0x7f544737f6b1  caffe::caffe_gpu_rng_gaussian<>()
    @           0x416127  caffe::RandomNumberGeneratorTest<>::RngGaussianFillGPU()
    @           0x413566  caffe::RandomNumberGeneratorTest_TestRngGaussianGPU_Test<>::TestBody()
    @           0x434ebe  testing::internal::HandleSehExceptionsInMethodIfSupported<>()
    @           0x42fd4c  testing::internal::HandleExceptionsInMethodIfSupported<>()
    @           0x41ca07  testing::Test::Run()
    @           0x41d1a0  testing::TestInfo::Run()
    @           0x41d78e  testing::TestCase::Run()
    @           0x422618  testing::internal::UnitTestImpl::RunAllTests()
    @           0x436410  testing::internal::HandleSehExceptionsInMethodIfSupported<>()
    @           0x430cf8  testing::internal::HandleExceptionsInMethodIfSupported<>()
    @           0x4213ac  testing::UnitTest::Run()
    @           0x4096fd  main
    @     0x7f54463aaf45  (unknown)
    @           0x4094c9  (unknown)
    @              (nil)  (unknown)
Aborted (core dumped)

**Comment by flx42** [comment]
You need to download CUDA 8.0 for the GTX 1080, that's not a Caffe bug.

**Comment by danielgordon10** [comment]
Ooh. Good catch. Thanks.
