### ISSUE TITLE
Getting  Started with Caffe on Windows

### ISSUE THREAD

**Issue by ParhamKhojasteh** [BVLC/caffe#4326]
Hello everyone, 
I installed the windows version of caffe and set the flags for using just CPU.
But I don't know what I should do first. when I choose Caffe.sln file.by right clicking on the solution 'cafe' and choosing build solution , I face 11 errors in error list. Could you please help me I should install some files or doing something before this stage or not. is there any induction to install step by step the caffe?

**Comment by seanbell** [comment]
Please ask questions about installation and setup on the mailing list, thanks!

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
