### ISSUE TITLE
Installation issue on ubuntu 14.04

### ISSUE THREAD

**Issue by daemonSlayer** [BVLC/caffe#4332]
I want to install caffe on ubuntu 14.04. After following the compilation instructions (I was on `make all`),
I am getting this error on the console:
```
make: brew: Command not found
make: brew: Command not found
LD -o .build_release/lib/libcaffe.so.1.0.0-rc3
/usr/bin/ld: cannot find -lcblas
/usr/bin/ld: cannot find -latlas
collect2: error: ld returned 1 exit status
make: *** [.build_release/lib/libcaffe.so.1.0.0-rc3] Error 1
```
How can I resolve this issue ? (Sorry if this is an already raised issue, but I googled it and couldn't find anything that would help me resolve this.)

**Comment by seanbell** [comment]
`brew`?  It looks like you're trying to use some installation instructions for mac.

Please ask for help with installation on the mailing list, and follow up there.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

**Comment by jinfagang** [comment]
Actually, I encounterred same question:
```
LD -o .build_release/lib/libcaffe.so.1.0.0
/usr/bin/ld: cannot find -lcblas
/usr/bin/ld: cannot find -latlas
collect2: error: ld returned 1 exit status
Makefile:572: recipe for target '.build_release/lib/libcaffe.so.1.0.0' failed
```
I installed atlas and blas library, any idea about this?
