### ISSUE TITLE
LevelDb.lib(builder.obj) : warning LNK4099: PDB 'vc120.pdb' was not found with 'LevelDb.lib(builder.obj)' or at 'C:\Users\Kevin\dev\IPSight\caffe-windows\Build\x64\Debug\vc120.pdb'; linking object as if no debug info

### ISSUE THREAD

**Issue by KevinLucidyne** [BVLC/caffe#4340]
Get this error on the latest caffe build for windows.  How to fix so that can step into code with debugger?

**Comment by aizawak** [comment]
@KevinLucidyne How did you resolve this issue?

**Comment by KevinLucidyne** [comment]
@aizawak Downloaded LevelDb, recompiled in Debug mode, copied lib and pdb into Build directory.

**Comment by wandering007** [comment]
I got that warning too, does it matter?

**Comment by KevinLucidyne** [comment]
Issue is back.

**Comment by wandering007** [comment]
@KevinLucidyne  is this warning counted as error? why should we care about it?

**Comment by shelhamer** [comment]
Please ask installation questions on the mailing list. If you're having trouble, you might want to try the Caffe [Dockerfile](https://github.com/BVLC/caffe/tree/master/docker) to take care of installation for you.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
