### ISSUE TITLE
fork another user's caffe fork

### ISSUE THREAD

**Issue by wenwei202** [BVLC/caffe#4345]
Hi, all

I forked https://github.com/BVLC/caffe, but now I want to fork another caffe repo - https://github.com/intelcaffe/caffe which was also forked from https://github.com/BVLC/caffe. Is it supported? When I click to fork https://github.com/intelcaffe/caffe, it directly jumps to my fork https://github.com/wenwei202/caffe.
Is there other way to work on https://github.com/intelcaffe/caffe except create a new repo?

Thanks

**Comment by seanbell** [comment]
Hi, I think this is a question for github in general, not for BVLC/caffe, so I am closing it.  Please follow up on general github help forums.

**Comment by jdukat** [comment]
@wenwei202 as a side comment to this thread - if you have any improvements to Intel optimized Caffe*, please consider issuing a pull request for it.
