### ISSUE TITLE
Is it possible to combine multiple .caffemodel into one?

### ISSUE THREAD

**Issue by stickFigure1235** [BVLC/caffe#4350]
I want to be able to combine x.caffemodel with y.caffemodel. They both use the same model prototxt file. I plan to train the network separately in parallel and then combine the results in the end. Is that possible and are there any existing examples of this? 

I found an example. Not sure if it works correctly though.

https://gist.github.com/FranciscoCanas/844aab52fcff6b1c652a

Thanks.

**Comment by artheru** [comment]
How r u going to combine them? Do you mean letting them have the same weights?
I don't think it can be done with python, unless you use cpp instead of python. I have the same requirement, what I'm currently doing is to use pipe to transfer weights...

**Comment by malreddysid** [comment]
How do you plan to combine the results? Like an ensemble?

**Comment by shelhamer** [comment]
Please ask usage questions on the mailing list.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
