### ISSUE TITLE
error undefined reference to to cudaMemset cudaConfigureCall

### ISSUE THREAD

**Issue by aysegulucar2016** [BVLC/caffe#4354]
![img_5900](https://cloud.githubusercontent.com/assets/16757934/16299859/366aa68e-3945-11e6-9661-37849016c6d1.JPG)

collect2 error ld resturned 1 exit status
make: ** .build_release/tools/extract_features.bin Error1

Could you please give me an information about this?

**Comment by seanbell** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

**Comment by seanbell** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> When reporting a bug, it's most helpful to provide the following information, where applicable:
> 
> * What steps reproduce the bug?
> * Can you reproduce the bug using the latest [master](https://github.com/BVLC/caffe/tree/master), compiled with the `DEBUG` make option?
> * What hardware and operating system/distribution are you running?
> * If the bug is a crash, provide the backtrace (usually printed by Caffe; always obtainable with `gdb`).

**Comment by aysegulucar2016** [comment]
I am using Ubunto 14.04 and Nvdia GTX 950.

I obtained the error in the installation stage.

I download from caffee your page.

I run sudo make all.

repeatedly tried. I obtained same error. Please help me about this issue. I cant use caffe.

**Comment by aysegulucar2016** [comment]
![img_5899](https://cloud.githubusercontent.com/assets/16757934/16359735/a3bc0e66-3b49-11e6-85b9-470360b223bf.JPG)

**Comment by seanbell** [comment]
It looks like you're missing some of the dependencies (e.g., blas).  Please ask about installation on the mailing list.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
