### ISSUE TITLE
It is compatible with cudnn 5.1

### ISSUE THREAD

**Issue by smithdir101** [BVLC/caffe#4355]
Hi All,

I tried to compile it with cudnn 5.1 but I got an error.
I would like to verify if it is compatible with cudnn 5.1?

Thanks,

Jhon

**Comment by seanbell** [comment]
Please ask usage/installation questions on the mailing list.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
