### ISSUE TITLE
Visuals Studios Integrated

### ISSUE THREAD

**Issue by GGriva** [BVLC/caffe#4357]
I am having trouble integrating with visual studios - we follow the instructions completely however once we try to compile the program - it says there is a file missing.

**Comment by meicholtz** [comment]
What file is missing?

**Comment by seanbell** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
