### ISSUE TITLE
Running Python example in Caffe

### ISSUE THREAD

**Issue by GGriva** [BVLC/caffe#4362]
I am trying to run a python example in caffe - found [here](http://nbviewer.jupyter.org/github/BVLC/caffe/blob/master/examples/00-classification.ipynb). But when I run it it says that caffe is not found and cannot be imported.

I understand I need to change my python path, how exactly do I do that?

**Comment by Coderx7** [comment]
you should ask these question in the caffe-google group. 
you probably didnt copy the pycaffe folder, into Anaconda site packages. do that, then import caffe and its all good.

**Comment by seanbell** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
