### ISSUE TITLE
Caffe is not utilizing the full GPU memory

### ISSUE THREAD

**Issue by SivaramPrasadMudunuri** [BVLC/caffe#4363]
Hi all,
I am trying to train some network in caffe in linix 14.04. It has NVIDIA Graphics card (01:00.0 VGA compatible controller: NVIDIA Corporation GM200 [GeForce GTX TITAN X] (rev a1))  of 12GB. 
It looks like, the caffe is not using the whole (or majority of) GPU memory while I am training the network. The output of "nvidia-smi" is as follows:

+------------------------------------------------------+                       
| NVIDIA-SMI 346.46     Driver Version: 346.46         |                       
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Graphics Device     Off  | 0000:01:00.0      On |                  N/A |
| 50%   83C    P2   153W / 250W |   3797MiB / 12287MiB |     94%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0      1156    G   /usr/bin/X                                     428MiB |
|    0      1941    G   compiz                                         108MiB |
|    0     13484    C   ./build/tools/caffe                           3231MiB |
+-----------------------------------------------------------------------------+

Where as earlier (1 month back) when I tried the same program, it utilized the full memory. So I don't know why this behavior is happening now.
I tried with different batch sizes (64 and 256) but the same issue of underutilization of GPU memory is  happening, that leads to slow execution of the training.
Please let me know if anyone is having any suggestions. 
Thanks in advance.
Sivaram

**Comment by seanbell** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> When reporting a bug, it's most helpful to provide the following information, where applicable:
> 
> * What steps reproduce the bug?
> * Can you reproduce the bug using the latest [master](https://github.com/BVLC/caffe/tree/master), compiled with the `DEBUG` make option?
> * What hardware and operating system/distribution are you running?
> * If the bug is a crash, provide the backtrace (usually printed by Caffe; always obtainable with `gdb`).

**Comment by SivaramPrasadMudunuri** [comment]
Hi Seanbell,
Thanks for your suggestions.
One of my friend suggested me to increase the batch size and / or update the caffe.

I tried changing the batch size from 256 to 1024 and it is now utilizing the full GPU memory.

+------------------------------------------------------+                       
| NVIDIA-SMI 346.46     Driver Version: 346.46         |                       
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Graphics Device     Off  | 0000:01:00.0      On |                  N/A |
| 53%   82C    P2   125W / 250W |  10877MiB / 12287MiB |     95%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0      1157    G   /usr/bin/X                                     322MiB |
|    0      1965    G   compiz                                          67MiB |
|    0     13411    C   ./build/tools/caffe                          10458MiB |
+-----------------------------------------------------------------------------+

Thank You.

**Comment by seanbell** [comment]
Not using all the memory available isn't necessarily a problem; larger batchsizes are more stable but also slower to train.

But I'm glad you figured it out.
