### ISSUE TITLE
Multiple GPUs memory consummation

### ISSUE THREAD

**Issue by holyseven** [BVLC/caffe#4367]
Hi all,

I am trying to train a [FCN](https://github.com/shelhamer/fcn.berkeleyvision.org) model with quite large images (2000x2000) for semantic segmentation, noting that FCN originally trains on images of 500x500.  And I don't want to reduce the image resolution.

So I ran into the GPU memory problem. I have two GPUs of 12G for training, memory of one GPU is not enough for training with such large images. But I can't share memory with two GPUs. I searched some issues about GPU memory problem and I found that for classification problems, multiple GPUs can share memory use by reducing batch size. But for segmentation, batch size is 1 (while the real batch size is the number of pixels). 

I can't reduce batch size in the solver.prototxt to share memory with two or more GPUs. Can Caffe share memory in multiple GPUs in another way?

Thanks in advance

**Comment by seanbell** [comment]
There isn't anything implemented at the moment to share memory across GPUs.

However, there is no need to train with the entire 2k x 2k images, even if that is the resolution you want ultimately.  You can sub-sample patches and train on those.  It's possible to make them equivalent if you work out the padding/stride correctly.

At test time, you could probably fit a 2k x 2k image to get a single prediction.  If not, you can still break down the image into patches and combine them.

**Comment by ajtulloch** [comment]
At inference time you can also try the memory optimizer from fb-caffe-exts which will definitely reduce your memory consumption by 90% or so for ResNets, etc.

**Comment by holyseven** [comment]
Thanks, guys. I'll try it.
