### ISSUE TITLE
Import tools

### ISSUE THREAD

**Issue by FlyqiangHigh** [BVLC/caffe#4369]
tools is not defined when i import tools ,I wanna to know what is tools ,how i find it.

**Comment by FlyqiangHigh** [comment]
No module named tools

**Comment by seanbell** [comment]
Please ask for help with installation on the mailing list.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
