### ISSUE TITLE
Loss issue with GTX 1080, Ubuntu 14.04 and CUDA 8.0

### ISSUE THREAD

**Issue by zongyuange** [BVLC/caffe#4371]
**I ran the "Fine-tune Flicke Stytle" example comes with the Caffe, fine-tuning shows following performance. Any ideas about that? (I have tried CPU only later and it worked fine. Looks like Caffe might not support GTX 1080 yet. )

### I0627 17:28:25.989347 13757 solver.cpp:60] Solver scaffolding done.
I0627 17:28:25.989727 13757 caffe.cpp:129] Finetuning from models/bvlc_reference_caffenet/bvlc_reference_caffenet.caffemodel
I0627 17:28:26.282686 13757 upgrade_proto.cpp:43] Attempting to upgrade input file specified using deprecated transformation parameters: models/bvlc_reference_caffenet/bvlc_reference_caffenet.caffemodel
I0627 17:28:26.282734 13757 upgrade_proto.cpp:46] Successfully upgraded file specified using deprecated data transformation parameters.
W0627 17:28:26.282740 13757 upgrade_proto.cpp:48] Note that future Caffe releases will only support transform_param messages for transformation fields.
I0627 17:28:26.282835 13757 upgrade_proto.cpp:52] Attempting to upgrade input file specified using deprecated V1LayerParameter: models/bvlc_reference_caffenet/bvlc_reference_caffenet.caffemodel
I0627 17:28:26.421634 13757 upgrade_proto.cpp:60] Successfully upgraded file specified using deprecated V1LayerParameter
I0627 17:28:26.459056 13757 net.cpp:752] Ignoring source layer fc8
I0627 17:28:26.799187 13757 upgrade_proto.cpp:43] Attempting to upgrade input file specified using deprecated transformation parameters: models/bvlc_reference_caffenet/bvlc_reference_caffenet.caffemodel
I0627 17:28:26.799233 13757 upgrade_proto.cpp:46] Successfully upgraded file specified using deprecated data transformation parameters.
W0627 17:28:26.799242 13757 upgrade_proto.cpp:48] Note that future Caffe releases will only support transform_param messages for transformation fields.
I0627 17:28:26.799269 13757 upgrade_proto.cpp:52] Attempting to upgrade input file specified using deprecated V1LayerParameter: models/bvlc_reference_caffenet/bvlc_reference_caffenet.caffemodel
I0627 17:28:26.989821 13757 upgrade_proto.cpp:60] Successfully upgraded file specified using deprecated V1LayerParameter
I0627 17:28:27.031033 13757 net.cpp:752] Ignoring source layer fc8
I0627 17:28:27.053072 13757 parallel.cpp:392] GPUs pairs 0:1
I0627 17:28:27.329217 13757 net.cpp:84] Sharing layer data from root net
I0627 17:28:27.330121 13757 net.cpp:134] Created top blob 0 (shape: 50 3 227 227 (7729350)) for shared layer data
I0627 17:28:27.330164 13757 net.cpp:134] Created top blob 1 (shape: 50 (50)) for shared layer data
I0627 17:28:28.767381 13757 parallel.cpp:425] Starting Optimization
I0627 17:28:28.767431 13757 solver.cpp:279] Solving FlickrStyleCaffeNet
I0627 17:28:28.767438 13757 solver.cpp:280] Learning Rate Policy: step
I0627 17:28:28.767508 13757 solver.cpp:337] Iteration 0, Testing net (#0)
I0627 17:28:28.889348 13757 blocking_queue.cpp:50] Data layer prefetch queue empty
I0627 17:28:41.589354 13757 solver.cpp:404]     Test net output #0: accuracy = 0.049
I0627 17:28:41.589427 13757 solver.cpp:404]     Test net output #1: loss = 3.17032 (* 1 = 3.17032 loss)
I0627 17:28:41.678568 13757 solver.cpp:228] Iteration 0, loss = 3.33153
I0627 17:28:41.678627 13757 solver.cpp:244]     Train net output #0: loss = 3.33153 (* 1 = 3.33153 loss)
I0627 17:28:41.678678 13757 sgd_solver.cpp:106] Iteration 0, lr = 0.001
I0627 17:28:46.709012 13757 solver.cpp:228] Iteration 20, loss = 39.1876
I0627 17:28:46.709090 13757 solver.cpp:244]     Train net output #0: loss = 39.1876 (* 1 = 39.1876 loss)
I0627 17:28:46.873059 13757 sgd_solver.cpp:106] Iteration 20, lr = 0.001
I0627 17:28:51.886963 13757 solver.cpp:228] Iteration 40, loss = 56.4313
I0627 17:28:51.887042 13757 solver.cpp:244]     Train net output #0: loss = 56.4313 (* 1 = 56.4313 loss)
I0627 17:28:52.059569 13757 sgd_solver.cpp:106] Iteration 40, lr = 0.001
I0627 17:28:57.098466 13757 solver.cpp:228] Iteration 60, loss = 57.2605
I0627 17:28:57.098599 13757 solver.cpp:244]     Train net output #0: loss = 57.2605 (* 1 = 57.2605 loss)
I0627 17:28:57.259498 13757 sgd_solver.cpp:106] Iteration 60, lr = 0.001
I0627 17:29:02.274163 13757 solver.cpp:228] Iteration 80, loss = 48.1475
I0627 17:29:02.274240 13757 solver.cpp:244]     Train net output #0: loss = 48.1475 (* 1 = 48.1475 loss)
I0627 17:29:02.441429 13757 sgd_solver.cpp:106] Iteration 80, lr = 0.001
I0627 17:29:07.545466 13757 solver.cpp:228] Iteration 100, loss = 54.5364
I0627 17:29:07.545542 13757 solver.cpp:244]     Train net output #0: loss = 54.5364 (* 1 = 54.5364 loss)
I0627 17:29:07.715857 13757 sgd_solver.cpp:106] Iteration 100, lr = 0.001
I0627 17:29:12.754844 13757 solver.cpp:228] Iteration 120, loss = 54.8535
I0627 17:29:12.754919 13757 solver.cpp:244]     Train net output #0: loss = 54.8535 (* 1 = 54.8535 loss)
I0627 17:29:12.927150 13757 sgd_solver.cpp:106] Iteration 120, lr = 0.001
I0627 17:29:17.976701 13757 solver.cpp:228] Iteration 140, loss = 60.0615
I0627 17:29:17.976765 13757 solver.cpp:244]     Train net output #0: loss = 60.0615 (* 1 = 60.0615 loss)
I0627 17:29:18.143898 13757 sgd_solver.cpp:106] Iteration 140, lr = 0.001
I0627 17:29:23.169348 13757 solver.cpp:228] Iteration 160, loss = 47.6583
I0627 17:29:23.169431 13757 solver.cpp:244]     Train net output #0: loss = 47.6583 (* 1 = 47.6583 loss)
I0627 17:29:23.340852 13757 sgd_solver.cpp:106] Iteration 160, lr = 0.001
I0627 17:29:28.397027 13757 solver.cpp:228] Iteration 180, loss = 42.4696
I0627 17:29:28.397225 13757 solver.cpp:244]     Train net output #0: loss = 42.4696 (* 1 = 42.4696 loss)
I0627 17:29:28.571355 13757 sgd_solver.cpp:106] Iteration 180, lr = 0.001
I0627 17:29:33.604609 13757 solver.cpp:228] Iteration 200, loss = 45.3816
I0627 17:29:33.604697 13757 solver.cpp:244]     Train net output #0: loss = 45.3816 (* 1 = 45.3816 loss)
I0627 17:29:33.774047 13757 sgd_solver.cpp:106] Iteration 200, lr = 0.001
I0627 17:29:38.827091 13757 solver.cpp:228] Iteration 220, loss = 53.9854
I0627 17:29:38.827162 13757 solver.cpp:244]     Train net output #0: loss = 53.9854 (* 1 = 53.9854 loss)
I0627 17:29:38.997748 13757 sgd_solver.cpp:106] Iteration 220, lr = 0.001
I0627 17:29:44.020539 13757 solver.cpp:228] Iteration 240, loss = 51.5251
I0627 17:29:44.020617 13757 solver.cpp:244]     Train net output #0: loss = 51.5251 (* 1 = 51.5251 loss)
I0627 17:29:44.190858 13757 sgd_solver.cpp:106] Iteration 240, lr = 0.001
I0627 17:29:49.245833 13757 solver.cpp:228] Iteration 260, loss = 33.3634
I0627 17:29:49.245911 13757 solver.cpp:244]     Train net output #0: loss = 33.3634 (* 1 = 33.3634 loss)
I0627 17:29:49.413265 13757 sgd_solver.cpp:106] Iteration 260, lr = 0.001
I0627 17:29:54.435341 13757 solver.cpp:228] Iteration 280, loss = 38.3989
I0627 17:29:54.435420 13757 solver.cpp:244]     Train net output #0: loss = 38.3989 (* 1 = 38.3989 loss)
I0627 17:29:54.601680 13757 sgd_solver.cpp:106] Iteration 280, lr = 0.001
I0627 17:29:59.643909 13757 solver.cpp:228] Iteration 300, loss = 33.7158
I0627 17:29:59.644062 13757 solver.cpp:244]     Train net output #0: loss = 33.7158 (* 1 = 33.7158 loss)
I0627 17:29:59.808818 13757 sgd_solver.cpp:106] Iteration 300, lr = 0.001
I0627 17:30:04.836366 13757 solver.cpp:228] Iteration 320, loss = 40.641
I0627 17:30:04.836447 13757 solver.cpp:244]     Train net output #0: loss = 40.641 (* 1 = 40.641 loss)
I0627 17:30:05.003628 13757 sgd_solver.cpp:106] Iteration 320, lr = 0.001
I0627 17:30:10.054541 13757 solver.cpp:228] Iteration 340, loss = 37.4222
I0627 17:30:10.054630 13757 solver.cpp:244]     Train net output #0: loss = 37.4222 (* 1 = 37.4222 loss)
I0627 17:30:10.225177 13757 sgd_solver.cpp:106] Iteration 340, lr = 0.001
I0627 17:30:15.245543 13757 solver.cpp:228] Iteration 360, loss = 40.7337
I0627 17:30:15.245609 13757 solver.cpp:244]     Train net output #0: loss = 40.7337 (* 1 = 40.7337 loss)
I0627 17:30:15.413498 13757 sgd_solver.cpp:106] Iteration 360, lr = 0.001
I0627 17:30:20.462296 13757 solver.cpp:228] Iteration 380, loss = 25.9041
I0627 17:30:20.462378 13757 solver.cpp:244]     Train net output #0: loss = 25.9041 (* 1 = 25.9041 loss)
I0627 17:30:20.626408 13757 sgd_solver.cpp:106] Iteration 380, lr = 0.001
I0627 17:30:25.662118 13757 solver.cpp:228] Iteration 400, loss = 25.5015
I0627 17:30:25.662191 13757 solver.cpp:244]     Train net output #0: loss = 25.5015 (* 1 = 25.5015 loss)
I0627 17:30:25.819967 13757 sgd_solver.cpp:106] Iteration 400, lr = 0.001
I0627 17:30:30.859452 13757 solver.cpp:228] Iteration 420, loss = 29.3624
I0627 17:30:30.859619 13757 solver.cpp:244]     Train net output #0: loss = 29.3624 (* 1 = 29.3624 loss)
I0627 17:30:31.031383 13757 sgd_solver.cpp:106] Iteration 420, lr = 0.001
I0627 17:30:36.079686 13757 solver.cpp:228] Iteration 440, loss = 29.1726
I0627 17:30:36.079766 13757 solver.cpp:244]     Train net output #0: loss = 29.1726 (* 1 = 29.1726 loss)
I0627 17:30:36.241267 13757 sgd_solver.cpp:106] Iteration 440, lr = 0.001
I0627 17:30:39.407582 13757 blocking_queue.cpp:50] Data layer prefetch queue empty
I0627 17:30:41.286979 13757 solver.cpp:228] Iteration 460, loss = 21.5777
I0627 17:30:41.287065 13757 solver.cpp:244]     Train net output #0: loss = 21.5777 (* 1 = 21.5777 loss)
I0627 17:30:41.448297 13757 sgd_solver.cpp:106] Iteration 460, lr = 0.001
I0627 17:30:46.473575 13757 solver.cpp:228] Iteration 480, loss = 22.1506
I0627 17:30:46.473661 13757 solver.cpp:244]     Train net output #0: loss = 22.1506 (* 1 = 22.1506 loss)
I0627 17:30:46.636729 13757 sgd_solver.cpp:106] Iteration 480, lr = 0.001
I0627 17:30:51.695835 13757 solver.cpp:228] Iteration 500, loss = 18.8583
I0627 17:30:51.695907 13757 solver.cpp:244]     Train net output #0: loss = 18.8583 (* 1 = 18.8583 loss)
I0627 17:30:51.868037 13757 sgd_solver.cpp:106] Iteration 500, lr = 0.001
I0627 17:30:56.906007 13757 solver.cpp:228] Iteration 520, loss = 31.1658
I0627 17:30:56.906080 13757 solver.cpp:244]     Train net output #0: loss = 31.1658 (* 1 = 31.1658 loss)
I0627 17:30:57.067829 13757 sgd_solver.cpp:106] Iteration 520, lr = 0.001
I0627 17:31:02.101872 13757 solver.cpp:228] Iteration 540, loss = 23.8904
I0627 17:31:02.102092 13757 solver.cpp:244]     Train net output #0: loss = 23.8904 (* 1 = 23.8904 loss)
I0627 17:31:02.265771 13757 sgd_solver.cpp:106] Iteration 540, lr = 0.001
I0627 17:31:07.292980 13757 solver.cpp:228] Iteration 560, loss = 20.727
I0627 17:31:07.293059 13757 solver.cpp:244]     Train net output #0: loss = 20.727 (* 1 = 20.727 loss)
I0627 17:31:07.451300 13757 sgd_solver.cpp:106] Iteration 560, lr = 0.001
I0627 17:31:12.511204 13757 solver.cpp:228] Iteration 580, loss = 23.5145
I0627 17:31:12.511282 13757 solver.cpp:244]     Train net output #0: loss = 23.5145 (* 1 = 23.5145 loss)
I0627 17:31:12.682027 13757 sgd_solver.cpp:106] Iteration 580, lr = 0.001
I0627 17:31:17.708083 13757 solver.cpp:228] Iteration 600, loss = 24.1441
I0627 17:31:17.708161 13757 solver.cpp:244]     Train net output #0: loss = 24.1441 (* 1 = 24.1441 loss)
I0627 17:31:17.872030 13757 sgd_solver.cpp:106] Iteration 600, lr = 0.001
I0627 17:31:22.913214 13757 solver.cpp:228] Iteration 620, loss = 22.3861
I0627 17:31:22.913290 13757 solver.cpp:244]     Train net output #0: loss = 22.3861 (* 1 = 22.3861 loss)
I0627 17:31:23.080052 13757 sgd_solver.cpp:106] Iteration 620, lr = 0.001
I0627 17:31:28.115006 13757 solver.cpp:228] Iteration 640, loss = 27.35
I0627 17:31:28.115082 13757 solver.cpp:244]     Train net output #0: loss = 27.35 (* 1 = 27.35 loss)
I0627 17:31:28.276921 13757 sgd_solver.cpp:106] Iteration 640, lr = 0.001
I0627 17:31:33.325803 13757 solver.cpp:228] Iteration 660, loss = 28.5684
I0627 17:31:33.325965 13757 solver.cpp:244]     Train net output #0: loss = 28.5684 (* 1 = 28.5684 loss)
I0627 17:31:33.490202 13757 sgd_solver.cpp:106] Iteration 660, lr = 0.001
I0627 17:31:38.537484 13757 solver.cpp:228] Iteration 680, loss = 24.353
I0627 17:31:38.537560 13757 solver.cpp:244]     Train net output #0: loss = 24.353 (* 1 = 24.353 loss)
I0627 17:31:38.694838 13757 sgd_solver.cpp:106] Iteration 680, lr = 0.001
I0627 17:31:43.740885 13757 solver.cpp:228] Iteration 700, loss = 9.94272
I0627 17:31:43.740962 13757 solver.cpp:244]     Train net output #0: loss = 9.94272 (* 1 = 9.94272 loss)
I0627 17:31:43.905923 13757 sgd_solver.cpp:106] Iteration 700, lr = 0.001
I0627 17:31:48.934519 13757 solver.cpp:228] Iteration 720, loss = 11.1827
I0627 17:31:48.934597 13757 solver.cpp:244]     Train net output #0: loss = 11.1827 (* 1 = 11.1827 loss)
I0627 17:31:49.099699 13757 sgd_solver.cpp:106] Iteration 720, lr = 0.001
I0627 17:31:54.142824 13757 solver.cpp:228] Iteration 740, loss = 8.77624
I0627 17:31:54.142879 13757 solver.cpp:244]     Train net output #0: loss = 8.77624 (* 1 = 8.77624 loss)
I0627 17:31:54.310125 13757 sgd_solver.cpp:106] Iteration 740, lr = 0.001
I0627 17:31:59.368945 13757 solver.cpp:228] Iteration 760, loss = 7.01498
I0627 17:31:59.369022 13757 solver.cpp:244]     Train net output #0: loss = 7.01498 (* 1 = 7.01498 loss)
I0627 17:31:59.530441 13757 sgd_solver.cpp:106] Iteration 760, lr = 0.001
I0627 17:32:04.569309 13757 solver.cpp:228] Iteration 780, loss = 11.1969
I0627 17:32:04.569512 13757 solver.cpp:244]     Train net output #0: loss = 11.1969 (* 1 = 11.1969 loss)
I0627 17:32:04.733536 13757 sgd_solver.cpp:106] Iteration 780, lr = 0.001
I0627 17:32:09.750181 13757 solver.cpp:228] Iteration 800, loss = 8.36618
I0627 17:32:09.750257 13757 solver.cpp:244]     Train net output #0: loss = 8.36618 (* 1 = 8.36618 loss)
I0627 17:32:09.907382 13757 sgd_solver.cpp:106] Iteration 800, lr = 0.001
I0627 17:32:14.948182 13757 solver.cpp:228] Iteration 820, loss = 9.359
I0627 17:32:14.948259 13757 solver.cpp:244]     Train net output #0: loss = 9.359 (* 1 = 9.359 loss)
I0627 17:32:15.112267 13757 sgd_solver.cpp:106] Iteration 820, lr = 0.001
I0627 17:32:20.145644 13757 solver.cpp:228] Iteration 840, loss = 8.94534
I0627 17:32:20.145725 13757 solver.cpp:244]     Train net output #0: loss = 8.94534 (* 1 = 8.94534 loss)
I0627 17:32:20.307148 13757 sgd_solver.cpp:106] Iteration 840, lr = 0.001
I0627 17:32:25.350371 13757 solver.cpp:228] Iteration 860, loss = 8.49337
I0627 17:32:25.350446 13757 solver.cpp:244]     Train net output #0: loss = 8.49337 (* 1 = 8.49337 loss)
I0627 17:32:25.510411 13757 sgd_solver.cpp:106] Iteration 860, lr = 0.001
I0627 17:32:30.545888 13757 solver.cpp:228] Iteration 880, loss = 12.3596
I0627 17:32:30.545965 13757 solver.cpp:244]     Train net output #0: loss = 12.3596 (* 1 = 12.3596 loss)
I0627 17:32:30.703120 13757 sgd_solver.cpp:106] Iteration 880, lr = 0.001
I0627 17:32:35.761350 13757 solver.cpp:228] Iteration 900, loss = 11.9632
I0627 17:32:35.761530 13757 solver.cpp:244]     Train net output #0: loss = 11.9632 (* 1 = 11.9632 loss)
I0627 17:32:35.929239 13757 sgd_solver.cpp:106] Iteration 900, lr = 0.001
I0627 17:32:40.987048 13757 solver.cpp:228] Iteration 920, loss = 14.3371
I0627 17:32:40.987125 13757 solver.cpp:244]     Train net output #0: loss = 14.3371 (* 1 = 14.3371 loss)
I0627 17:32:41.147824 13757 sgd_solver.cpp:106] Iteration 920, lr = 0.001
I0627 17:32:46.195822 13757 solver.cpp:228] Iteration 940, loss = 19.1135
I0627 17:32:46.195899 13757 solver.cpp:244]     Train net output #0: loss = 19.1135 (* 1 = 19.1135 loss)
I0627 17:32:46.359680 13757 sgd_solver.cpp:106] Iteration 940, lr = 0.001
I0627 17:32:49.528616 13757 blocking_queue.cpp:50] Data layer prefetch queue empty
I0627 17:32:51.416328 13757 solver.cpp:228] Iteration 960, loss = 19.3412
I0627 17:32:51.416385 13757 solver.cpp:244]     Train net output #0: loss = 19.3412 (* 1 = 19.3412 loss)
I0627 17:32:51.570894 13757 sgd_solver.cpp:106] Iteration 960, lr = 0.001
I0627 17:32:56.630486 13757 solver.cpp:228] Iteration 980, loss = 21.5572
I0627 17:32:56.630527 13757 solver.cpp:244]     Train net output #0: loss = 21.5572 (* 1 = 21.5572 loss)
I0627 17:32:56.795877 13757 sgd_solver.cpp:106] Iteration 980, lr = 0.001
I0627 17:33:01.763159 13757 solver.cpp:337] Iteration 1000, Testing net (#0)
I0627 17:33:13.950453 13757 solver.cpp:404]     Test net output #0: accuracy = 0.063
I0627 17:33:13.950625 13757 solver.cpp:404]     Test net output #1: loss = 18.7367 (* 1 = 18.7367 loss)

**Comment by ajtulloch** [comment]
What problem are you seeing? Are you saying that the loss numbers are inconsistent between GPU versions for the exact same code/model? Please reopen with a clearer bug report if so.

**Comment by thatguymike** [comment]
For 1080, you MUST use cudnnv5.

**Comment by zongyuange** [comment]
Thanks @thatguymike . I will update the CUDNN V5 and recompile. A quick question, do I have to compile with CUDA 8.0 with 1080 or CUDA 7.5 also works fine?

**Comment by thatguymike** [comment]
Safest to move compilation to CUDA 8 and update the makefile to include sm60

**Comment by zongyuange** [comment]
Thanks again, the issue has been solved. To update, my system works with the following setups:
GTX 1080; UBUNTU 14.04; CUDA 8.0RC; CUDNN V5; Caffe commit f28f5ae

**Comment by yileo19920925** [comment]
@zongyuange Hi,i met some problems with Nvidia Driver 367.27 when build Nvidia Driver & cuda 8.0 .
my software is the same as yours(ubuntu14.04 gtx1080).
plz tell me how u did when build cuda and Nvidia Driver.thanks a lot~

**Comment by yileo19920925** [comment]
@zongyuange Hi,i met some problems with Nvidia Driver when build Nvidia Driver & cuda 8.0 .
my software & hardware is the same as yours(ubuntu14.04 gtx1080).
plz tell me how u did when build cuda and Nvidia Driver(how to build all of it will be better).thanks a lot~

**Comment by yileo19920925** [comment]
@zongyuange Hi,i met some problems with Nvidia Driver 367.27 when build Nvidia Driver & cuda 8.0 .
my software & hardware is the same as yours(ubuntu14.04 gtx1080).
my e-mail is 412203179@qq.com
plz tell me how u did when build cuda and Nvidia Driver(how to build all of it will be better).
thanks a lot~

**Comment by zongyuange** [comment]
Hi @yileo19920925 , Please make sure you compile with the correct CUDNN V5 version for cuda 8.0.
Let me know if any further issues exist.

**Comment by yileo19920925** [comment]
@zongyuange i did not build CUDNN V5 yet . Problem occured when build  Nvidia Driver 367.27 and cuda 8.0 .
if i build Nvidia Driver 367.27 first .it will be covered by cuda 8.0(with Nvidia Driver 361). 
if i build cuda 8.0 first Driver 367 can not be installed .(OS crash)
should i build CUDNN V5 before cuda 8.0&Nvidia Driver 367 's compile ?

**Comment by zongyuange** [comment]
@yileo19920925 
Follow the following procedure:
1. Install the latest 367.27 driver
2. Download the CUDA 8 run file (this is important, not deb file) and run it , it will ask if you would to install the 361 driver, answer no
3. Install CUDNN V5 
4. Compile

let me know if that works for you.

**Comment by Orlaiviai** [comment]
Same problem:
I0814 22:13:29.958272  1698 solver.cpp:228] Iteration 3660, loss = 0.388157
I0814 22:13:29.958317  1698 solver.cpp:244]     Train net output #0: loss = 0.388157 (* 1 = 0.388157 loss)
I0814 22:13:29.958328  1698 sgd_solver.cpp:106] Iteration 3660, lr = 0.01
I0814 22:13:33.468246  1698 solver.cpp:228] Iteration 3680, loss = **0.36455**
I0814 22:13:33.468291  1698 solver.cpp:244]     Train net output #0: loss = 0.36455 (* 1 = 0.36455 loss)
I0814 22:13:33.468302  1698 sgd_solver.cpp:106] Iteration 3680, lr = 0.01
I0814 22:13:36.975204  1698 solver.cpp:228] Iteration 3700, loss = **87.3365**
I0814 22:13:36.975255  1698 solver.cpp:244]     Train net output #0: loss = 87.3365 (* 1 = 87.3365 loss)
I0814 22:13:36.975267  1698 sgd_solver.cpp:106] Iteration 3700, lr = 0.01
I0814 22:13:40.479406  1698 solver.cpp:228] Iteration 3720, loss = **87.3365**
I0814 22:13:40.479454  1698 solver.cpp:244]     Train net output #0: loss = 87.3365 (* 1 = 87.3365 loss)
I0814 22:13:40.479466  1698 sgd_solver.cpp:106] Iteration 3720, lr = 0.01
I0814 22:13:43.985945  1698 solver.cpp:228] Iteration 3740, loss = 87.3365
I0814 22:13:43.985991  1698 solver.cpp:244]     Train net output #0: loss = 87.3365 (* 1 = 87.3365 loss)
I0814 22:13:43.986004  1698 sgd_solver.cpp:106] Iteration 3740, lr = 0.01
I0814 22:13:47.490635  1698 solver.cpp:228] Iteration 3760, loss = 87.3365
I0814 22:13:47.490684  1698 solver.cpp:244]     Train net output #0: loss = 87.3365 (* 1 = 87.3365 loss)
I0814 22:13:47.490697  1698 sgd_solver.cpp:106] Iteration 3760, lr = 0.01
I0814 22:13:50.994946  1698 solver.cpp:228] Iteration 3780, loss = 87.3365
I0814 22:13:50.994989  1698 solver.cpp:244]     Train net output #0: loss = 87.3365 (* 1 = 87.3365 loss)
I0814 22:13:50.995003  1698 sgd_solver.cpp:106] Iteration 3780, lr = 0.01

No problems with CPU learning.
GeForce GTX 760
Cuda compilation tools, release 8.0, V8.0.26
cuDNN 5.1 (same problem was with cuDNN 4)
GCC 5.4 (same problem with Clang 3.8)
367.27 video driver
imagenet solver

**Comment by unozo** [comment]
Hi，
I meet the same issue with you. When I use CPU or GPU, it works well. But when I enable cudnn, loss is very large. Similar environment, 14.04+1080+cuda 8.0+cudnn7.0v4, driver version 367.57.
I have already install the deb of CUDA 8.0 and I found you said that what we need is  CUDA 8 run file......
What should I do next ? "apt remove cuda" and excute run file , or I have to reinstall ubuntu? 
Thanks
