### ISSUE TITLE
Error in sudo make test and  make pycaffe

### ISSUE THREAD

**Issue by aysegulucar2016** [BVLC/caffe#4372]
Hi.

I run sudo make test. I obtained the following error.
What is problem? Could you give a information about this ?

Ubunto 14.04 and Nvdia GTX 950
Thanks
![img_5905](https://cloud.githubusercontent.com/assets/16757934/16377653/07a64f46-3c70-11e6-98e4-15fc7f22c5c1.JPG)

selman@selman-Inspiron-7559:/usr/local/caffe$ make pycaffe
CXX/LD -o python/caffe/_caffe.so python/caffe/_caffe.cpp
python/caffe/_caffe.cpp:1:52: fatal error: Python.h: No such file or directory
compilation terminated.
make: *** [python/caffe/_caffe.so] Error 1
selman@selman-Inspiron-7559:/usr/local/caffe$ 
selman@selman-Inspiron-7559:/usr/local/caffe$ sudo make test
CXX/LD -o .build_release/test/test_all.testbin src/caffe/test/test_caffe_main.cpp
/usr/bin/ld: /usr/local/lib/libcaffe.a(common.o): undefined reference to symbol '_ZN6google21ParseCommandLineFlagsEPiPPPcb'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libgflags.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make: *** [.build_release/test/test_all.testbin] Error 1
selman@selman-Inspiron-7559:/usr/local/caffe$

**Comment by alessandroferrari** [comment]
Maybe caffe include directory is wrong. Try with 'locate Python.h' and see whether the include dir of python in the Makefile.configure is correct.

**Comment by seanbell** [comment]
Please ask for help with installation on the mailing list.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
