### ISSUE TITLE
Make cProfile results more informative for pycaffe

### ISSUE THREAD

**Issue by grisaitis** [BVLC/caffe#4373]
cProfile is a very useful development tool for python programming. Unfortunately, cProfile doesn't appear to detect calls made to functions in pycaffe, like Solver.step(). Or, it doesn't recognize properly how long they take (with cpu time, wall time, etc)

I wonder if pycaffe could be refactored so that is has the same interface but where the calls to caffe functions, like Solver.step(), are wrapped in native python functions. This would have the advantage that cProfile would fully recognize and log the time spent in such functions (e.g. wall, cpu). Profiling results would be more informative. And I think it could be done with no change to the python API.

The current behavior I see is that caffe calls do not show up in cProfile at all. Or, when they do, they show up as taking 0.000s per call, which I know is false (e.g. Solver.step() for a 6GB network on a GPU). 

Thoughts?

**Comment by ajtulloch** [comment]
I'm not sure this is that useful TBH. If you want this for a project, just wrap them yourself? And all it would tell you is that you're spending time inside an opaque C function, so you need something like perf, pprof to get any visibility into what layers you're spending time in (which will just say stuff like sgemm, ...)

**Comment by grisaitis** [comment]
Cool, no worries - I'll wrap things myself as needed. I'll look into the tools you mentioned. Thanks for the suggestions.
