### ISSUE TITLE
make runtest error

### ISSUE THREAD

**Issue by KeeganRen** [BVLC/caffe#4376]
GTX970 Cuda7.0 cudnn4.0 opencv2.4.12
I don't know how to solve this problem!
**\* Aborted at 1467078048 (unix time) try "date -d @1467078048" if you are using GNU date ***
PC: @     0x2b3690e4b897 cudnnAddTensor
**\* SIGSEGV (@0x703105204) received by PID 31656 (TID 0x2b3682bce3c0) from PID 51401220; stack trace: ***
    @     0x2b3689a1f340 (unknown)
    @     0x2b3690e4b897 cudnnAddTensor
    @     0x2b3688de8463 caffe::CuDNNConvolutionLayer<>::Forward_gpu()
    @           0x48df76 caffe::Layer<>::Forward()
    @           0x93bd0f caffe::CuDNNConvolutionLayerTest_TestSimpleConvolutionCuDNN_Test<>::TestBody()
    @           0x9a4e53 testing::internal::HandleExceptionsInMethodIfSupported<>()
    @           0x99bb37 testing::Test::Run()
    @           0x99bbde testing::TestInfo::Run()
    @           0x99bce5 testing::TestCase::Run()
    @           0x99f028 testing::internal::UnitTestImpl::RunAllTests()
    @           0x99f2b7 testing::UnitTest::Run()
    @           0x473c7f main
    @     0x2b3689c4eec5 __libc_start_main
    @           0x47ca69 (unknown)
make: **\* [runtest] Segmentation fault (core dumped)

**Comment by KeeganRen** [comment]
any people can help me?
不开心@_@

**Comment by primaryst** [comment]
I met the same problem like you.Hope someone can help..

**Comment by 12rohanb** [comment]
Having the same problem. Was anyone able to solve this one?

**Comment by shelhamer** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
