### ISSUE TITLE
follow gp335

### ISSUE THREAD

**Issue by LiutongGenius** [BVLC/caffe#4381]
I have the same "segmentation fault python" problem.And I try to "sudo mv /System/Library/Frameworks/Python.framework /System/Library/Frameworks/Python.framework_bak" in my mac,but returns" Operation not permitted"  
How to rename the framework?
Anyone help,Thanks a lot!

**Comment by shelhamer** [comment]
Please ask installation and compilation questions on the mailing list.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
