### ISSUE TITLE
What is caffe-master used for？

### ISSUE THREAD

**Issue by caolusg** [BVLC/caffe#4384]
After I installed caffe on ubuntu, I found there is a folder named caffe-master, what is this used for? It seems I need to run MNIST example in this directory.

**Comment by shelhamer** [comment]
Please ask installation and usage questions on the mailing list.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
