### ISSUE TITLE
Does image size matters?

### ISSUE THREAD

**Issue by caolusg** [BVLC/caffe#4385]
From BVLC:

"Speed makes Caffe perfect for research experiments and industry deployment. Caffe can process over 60M images per day with a single NVIDIA K40 GPU*. That’s 1 ms/image for inference and 4 ms/image for learning. We believe that Caffe is the fastest convnet implementation available."

I wonder does image size matters in learning? 

Thank you.

**Comment by seanbell** [comment]
Please ask usage questions on the mailing list.  (Yes, image size matters.)

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
