### ISSUE TITLE
Learnable custom layer caffe

### ISSUE THREAD

**Issue by n3011** [BVLC/caffe#4386]
I am trying to develop a custom caffe python layer. The layer needs to learn parameters associated with it. I have come across the below example from caffe test python layer. But here still its not clear how to initialize the parameters of the layer and updating layer parameters. 
Any help will be appreciated. 

   `class ParameterLayer(caffe.Layer):

    def setup(self, bottom, top):
        self.blobs.add_blob(1)
        self.blobs[0].data[0] = 0

    def reshape(self, bottom, top):
        top[0].reshape(*bottom[0].data.shape)

    def forward(self, bottom, top):
        pass

    def backward(self, top, propagate_down, bottom):
        self.blobs[0].diff[0] = 1`

**Comment by artheru** [comment]
my guess:
self.A=some parameters
