### ISSUE TITLE
power_layer computed in-place overwrites gradients

### ISSUE THREAD

**Issue by isvoboda** [BVLC/caffe#4388]
In case the power_layer is used inplace i.e.:

```
layer { name: "Scale" type: "Power"
        bottom: "conv-5" top: "conv-5"
        power_param { power: 1 scale: 1024 shift: 128 }
}
```

The gradients are overridden.
In case of the layer above the bottom[0] is overridden [`caffe_set(count, diff_scale_, bottom_diff);`](https://github.com/BVLC/caffe/blob/master/src/caffe/layers/power_layer.cpp#L52) and later multiplied by itself [`caffe_mul(count, top_diff, bottom_diff, bottom_diff);`](https://github.com/BVLC/caffe/blob/master/src/caffe/layers/power_layer.cpp#L90)

Excuse this message in case the power layer is not intended to be used in-place.

**Comment by seanbell** [comment]
Most layers cannot be used in-place.  Only those that you verify are safe can be used.  Even then, it is necessary to inspect whether the next and/or previous layer makes assumptions preventing in-place.

See #2015.
