### ISSUE TITLE
How to get the result of the output classes.

### ISSUE THREAD

**Issue by montekristo1946** [BVLC/caffe#4395]
I use the example code:
https://github.com/yankailab/OpenKAI/blob/master/src/AI/_SegNet.cpp

```
>	net_->ForwardPrefilled();
> 	Blob<float>* output_layer = net_->output_blobs()[0];
> 	const float* begin = output_layer->cpu_data();
> 	Mat segIdx = Mat(m_InputSize.height, m_InputSize.width, CV_32FC1, (void*)begin);
```
I want to get a segmented image
Running the code in the class variable segIdx be "0" (class output is correct)
Please tell me how to get results with other classes?

**Comment by seanbell** [comment]
I think you have the wrong repository; this is BVLC/caffe.  Please file an issue with the author of the code (https://github.com/yankailab/OpenKAI).
