### ISSUE TITLE
Cannot use Caffe on another GPU when GPU 0 has full memory

### ISSUE THREAD

**Issue by jamt9000** [BVLC/caffe#440]
When GPU 0 is out of action, Cublas and Curand fail to initialise

```
E0522 16:04:44.114862 27133 common.cpp:31] Cannot create Cublas handle. Cublas won't be available.
E0522 16:04:44.427568 27133 common.cpp:38] Cannot create Curand generator. Curand won't be available.
```

Then, even if a different device is chosen, training or testing a net fails:

```
F0522 16:07:19.198012 27133 math_functions.cpp:50] Check failed: status == CUBLAS_STATUS_SUCCESS (13 vs. 0)  CUBLAS_STATUS_EXECUTION_FAILED
```

A workaround is to manually do cudaSetDevice(x) before starting Caffe, however this is not possible with the Python API.

**Comment by argman** [comment]
Just a tip, I find the reason for this is that I have some cuda libraries in some corner before I reinstall a new one, that caused caffe use the old libraries, so you maye try "locate libcuda*" and remove all the old ones, then installl a new cuda library.

Best.

**Comment by asa008** [comment]
F1030 16:15:43.990840 1937 math_functions.cu:28] Check failed: status == CUBLAS_STATUS_SUCCESS (13 vs. 0) CUBLAS_STATUS_EXECUTION_FAILED

The above error will occur when installing CUDA9.0
By installing [patchesPatch 2](https://developer.nvidia.com/cuda-90-download-archive?target_os=Windows&target_arch=x86_64&target_version=10&target_type=exelocal) (Released Mar 5, 2018)solve
