### ISSUE TITLE
Incorrect Reporting of Accuracy 

### ISSUE THREAD

**Issue by supriya-k** [BVLC/caffe#4403]
I am using caffe with the ristretto add on. When I use train_val.prototxt, I get accuracy of over 100%. How do I fix this error, and is there a way to also display the top 5 accuracy?

**Comment by seanbell** [comment]
What is the ristretto add-on?  If your issue isn't with the main BVLC/master branch, please contact the maintainers of whatever add-ons/modification you are using.

You could also try the mailing list.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
