### ISSUE TITLE
The accuracy has never changed on GPU model

### ISSUE THREAD

**Issue by cjsure** [BVLC/caffe#4405]
The accuracy has never changed on GPU model when i trained, but it's no problem when i switch to CPU model. Both the images and parameter files are the same(I mean i have the same lmdb,lenet_train_test.prototxt,lenet_solver.prototxt). This kind of situation only occurs 64 bit caffe, but 32 bit caffe is correct.

My PC :
NVIDIA:GTX1070
windows7/x64
Cuda Version:7.5
CUDNN version 5.1

**Comment by seanbell** [comment]
Does this happen without cuDNN?

**Comment by cjsure** [comment]
It's never happened without cudnn.

**Comment by naibaf7** [comment]
@cjsure 
I think you should try CUDA 8.0RC with cuDNN for Pascal (this is either 5.0@8.0RC or 5.1RC@8.0RC, not sure which one is the latest).

**Comment by cjsure** [comment]
I've tried complied with cuda8.0RC and CUDNN5.0, but failes. error: cuda parameters count is not correct. I will paste error message later.

**Comment by cjsure** [comment]
1.error : argument of type "int" is incompatible with parameter of type "cudnnNanPropagation_t"	 
2.error : too few arguments in function call

**Comment by cjsure** [comment]
Thanks a lot. I've solved the problem as your suggestion. I reinstalled the CUDA8.0RC with cuDNN5.0 and updated some code according to this issue:
https://git.codingcafe.org/xkszltl/Caffe/commit/7cf3538407f183fc277479f434acf7086a9cc34f
