### ISSUE TITLE
3D CNN,up sampling.deconvolution

### ISSUE THREAD

**Issue by xuhuaren** [BVLC/caffe#4412]
Does caffe support 3D CNN function, such as CNN, up sampling, deconvolution now?

**Comment by seanbell** [comment]
Please ask questions on the mailing list, thanks!

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
