### ISSUE TITLE
using caffe in visual studio c++ project

### ISSUE THREAD

**Issue by ssamira** [BVLC/caffe#4413]
Hello,

I am trying to use Caffe API in my project in visual studio but the find_package(caffe) is not working in cmake because of this warning :

CMake Warning at (find_package):
By not providing "FindCaffe.cmake" in CMAKE_MODULE_PATH this project has
asked CMake to find a package configuration file provided by "Caffe", but
CMake did not find one.

Could not find a package configuration file provided by "Caffe" with any of
the following names:

CaffeConfig.cmake
caffe-config.cmake
Add the installation prefix of "Caffe" to CMAKE_PREFIX_PATH or set
"Caffe_DIR" to a directory containing one of the above files. If "Caffe"
provides a separate development package or SDK, be sure it has been
installed.

Any suggestions?

Thanks,

**Comment by seanbell** [comment]
Please ask installation questions on the mailing list, thanks!

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

**Comment by ssamira** [comment]
Thank you, Couldn't find the mailing list first.
