### ISSUE TITLE
Huge log file caused by caffe

### ISSUE THREAD

**Issue by Lyken17** [BVLC/caffe#4414]
Today when I logged in my gpu server, I notice my disk is full.
<img width="1175" alt="finder finder today at 18 42 31" src="https://cloud.githubusercontent.com/assets/7783214/16571827/1883f58c-4217-11e6-8516-43a6f6e5aa51.png">

I find it's the caffe's log files occupy most of my disk.
<img width="500" alt="screenshot_2016-07-04_18_35_55" src="https://cloud.githubusercontent.com/assets/7783214/16571908/91c652a0-4217-11e6-9748-6244f5c9c1bc.png">

After deleting those log, my disk becomes empty again.
<img width="1100" alt="telegram telegram today at 18 54 00" src="https://cloud.githubusercontent.com/assets/7783214/16572027/e7c0563c-4218-11e6-8f4d-4bf0d78ff507.png">

The log file name is like `caffe.[pc-name].[user].log.INFO.20160425-165320.6192`. You can find [one sample](https://gist.github.com/Lyken17/e43e1e6df0a56ba61183e40c839e66f5) here. The content seems to be a copy of normal log file. But these occupy more than 150gb. 

Usually I use following script to train model. `nohup $caffe_dir/build/tools/caffe train -weights=temp/pre_trained.caffemodel -solver=models/solver.prototxt -gpu 0 > "$log_dir/$LOG_FILE"`, and never redirect the output to /tmp folder. I wonder, is any setting can avoid this?

**Comment by CDLuminate** [comment]
Those logs are just generated by glog.
One way to reduce the log size is to increase the `display` value in your `solver.prototxt`.  

Apart from that, `caffe --help` will tell you more command line flags available, and the option 
```
    -log_dir (If specified, logfiles are written into this directory instead of
      the default logging directory.) type: string default: ""
```
may be what you want -- redirecting nohup to `/dev/null` and setting `-log_dir` to your log directory. (I didn't try this).
