### ISSUE TITLE
Why does CNN's convolution kernel number increase layer by layer?

### ISSUE THREAD

**Issue by thesby** [BVLC/caffe#4415]
I find that no matter in lenet or vgg, the convolution kernel number is increasing layer by layer. And kernels in the shallow layers are much less than in the deep layers. Could anyone can give an explanation to this ? 

And in my experiments, i find that the kernel number affects the backward values a lot. Is this a reason that the less kernel number can mitigate the dimish of gradient?

**Comment by seanbell** [comment]
Please ask modeling/usage questions on the mailing list, thanks!

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

**Comment by thesby** [comment]
Thank you for your remind. I will do it.
