### ISSUE TITLE
Loss stuck at 0

### ISSUE THREAD

**Issue by AlperenAydin** [BVLC/caffe#4416]
Hello. New caffe-user here. 

I have been having this particularly annoying bug that I can't seem to solve.

I have a CNN that takes two images (one of them is the GT). When I start the training, the loss starts at 0 and stays there. 

I tried to play on the parameters of the solver to no avil. I also tried to change the parameters. 

The model is defined here: http://pastebin.com/t9Q7i0iZ 

An image of the model: http://imgur.com/RBBlvfb

The solver: http://pastebin.com/sUjg8mpe

And the command I used was:

    caffe train -solver solver.prototxt

And lastly the log: http://pastebin.com/B5DhJYVg

NOTE: I have been having this problem for a week and I did ask this question on stackoverflow, and on the google group (twice). I hope it is okay to ask it here.

**Comment by seanbell** [comment]
In general, I suggest visualizing the output (write a layer to print it out, or use the Python layer to inspect the results).  Chances are, your data and/or labels are bad somehow.  Sorry if you didn't get a response on the mailing list, but that doesn't change the fact that this isn't the right place to discuss modeling difficulties.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
