### ISSUE TITLE
TileLayer Usage

### ISSUE THREAD

**Issue by haihaoshen** [BVLC/caffe#4422]
Hi,

Is there any proto example on TileLayer usage? I have two layers (layer1, layer2) that need to be element-wised. The layer1 comes from conv+pool, which has shape 64 * 64 * 200 * 200, and layer2 comes from fc layer, which has shape 64 * 64. I thought the layer2 data could be replicated to meet layer2. How should I write the TileLayer proto here? Thanks.

**Comment by seanbell** [comment]
Please ask usage questions on the mailing list.  If you think the docs are insufficient, please feel free to submit a PR that better explains the layers.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
