### ISSUE TITLE
Is it possible to train model in some GPUs and validate the model use another GPU?

### ISSUE THREAD

**Issue by wangxianliang** [BVLC/caffe#4428]
refer to #3512: Multi gpu: one gpu use significantly more memory than others

Caffe really consumes lots of memory, in order to use large batch size, is it possible to train model in some GPUs and validate the model use another GPU?

**Comment by shelhamer** [comment]
Currently only training is parallelized, but you can disable validation during training by not defining a test net in the solver and then validate separately from the snapshotted `.caffemodel`s.
