### ISSUE TITLE
Error parsing text-format caffe.NetParameter

### ISSUE THREAD

**Issue by ktak199** [BVLC/caffe#4429]
I tried an example(https://github.com/pulkitag/ief) and got the error below.

> [libprotobuf ERROR google/protobuf/text_format.cc:245] Error parsing text-format caffe.NetParameter: 133:28: Message type "caffe.PoolingParameter" has no field named "round_below".
WARNING: Logging before InitGoogleLogging() is written to STDERR
F0708 03:12:45.061872 17362 upgrade_proto.cpp:932] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: models/vgg_s.prototxt
*** Check failure stack trace: ***

This issue is similar to https://github.com/BVLC/caffe/issues/3947 .
I use the latest caffe.

My environment is below.
Ubuntu 14.04+CUDA7.0+cudnn4.0

Thank you in advance.

**Comment by seanbell** [comment]
There is no parameter `round_below` in the BVLC/master branch of caffe.  Please ask the author of the example you found.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
