### ISSUE TITLE
destructor for python layer

### ISSUE THREAD

**Issue by karas84** [BVLC/caffe#4432]
Would it be possible to add a destructor call to the python layer c++ code so that when the object is destroyed a function is called in python? That would be very useful for closing files etc. like it is done in the hdf5_output_layer.

**Comment by seanbell** [comment]
Does the `__del__` method not work?

**Comment by karas84** [comment]
Unfortunately no, or at least in my case the `__del__` method is not called.

**Comment by samarth-robo** [comment]
@karas84 Did you find a solution?

**Comment by shelhamer** [comment]
Sorry, this cannot be done in a reliable manner (at least simply).
