### ISSUE TITLE
Error in installing Caffe with OpenCV 3.1.0  on Ubuntu 16.04 

### ISSUE THREAD

**Issue by sjsy** [BVLC/caffe#4436]
I want to install CAFFE in ubuntu 16.04 with OpenCV 3.1. I am getting the following error:

> $ make all
> [  1%] Built target proto
> [ 82%] Built target caffe
> [ 82%] Built target finetune_net
> [ 82%] Linking CXX executable compute_image_mean
> /usr/local/lib/libopencv_imgcodecs.so.3.1.0: undefined reference to `TIFFReadDirectory@LIBTIFF_4.0'
> /usr/local/lib/libopencv_imgcodecs.so.3.1.0: undefined reference to`TIFFWriteEncodedStrip@LIBTIFF_4.0'
> /usr/local/lib/libopencv_imgcodecs.so.3.1.0: undefined reference to `TIFFIsTiled@LIBTIFF_4.0'
> /usr/local/lib/libopencv_imgcodecs.so.3.1.0: undefined reference to`TIFFOpen@LIBTIFF_4.0'
> /usr/local/lib/libopencv_imgcodecs.so.3.1.0: undefined reference to `TIFFReadEncodedStrip@LIBTIFF_4.0'
> /usr/local/lib/libopencv_imgcodecs.so.3.1.0: undefined reference to`TIFFSetField@LIBTIFF_4.0'
> /usr/local/lib/libopencv_imgcodecs.so.3.1.0: undefined reference to `TIFFWriteScanline@LIBTIFF_4.0'
> /usr/local/lib/libopencv_imgcodecs.so.3.1.0: undefined reference to`TIFFGetField@LIBTIFF_4.0'
> /usr/local/lib/libopencv_imgcodecs.so.3.1.0: undefined reference to `TIFFScanlineSize@LIBTIFF_4.0'
> /usr/local/lib/libopencv_imgcodecs.so.3.1.0: undefined reference to`TIFFNumberOfStrips@LIBTIFF_4.0'
> /usr/local/lib/libopencv_imgcodecs.so.3.1.0: undefined reference to `TIFFSetWarningHandler@LIBTIFF_4.0'
> /usr/local/lib/libopencv_imgcodecs.so.3.1.0: undefined reference to`TIFFSetErrorHandler@LIBTIFF_4.0'
> /usr/local/lib/libopencv_imgcodecs.so.3.1.0: undefined reference to `TIFFReadEncodedTile@LIBTIFF_4.0'
> /usr/local/lib/libopencv_imgcodecs.so.3.1.0: undefined reference to`TIFFReadRGBATile@LIBTIFF_4.0'
> /usr/local/lib/libopencv_imgcodecs.so.3.1.0: undefined reference to `TIFFClose@LIBTIFF_4.0'
> /usr/local/lib/libopencv_imgcodecs.so.3.1.0: undefined reference to`TIFFRGBAImageOK@LIBTIFF_4.0'
> /usr/local/lib/libopencv_imgcodecs.so.3.1.0: undefined reference to `TIFFReadRGBAStrip@LIBTIFF_4.0'
> collect2: error: ld returned 1 exit status
> tools/CMakeFiles/compute_image_mean.dir/build.make:134: recipe for target 'tools/compute_image_mean' failed
> make[2]: **\* [tools/compute_image_mean] Error 1
> CMakeFiles/Makefile2:473: recipe for target 'tools/CMakeFiles/compute_image_mean.dir/all' failed
> make[1]: **\* [tools/CMakeFiles/compute_image_mean.dir/all] Error 2
> Makefile:127: recipe for target 'all' failed
> make: **\* [all] Error 2

Any help will be appreciated.

**Comment by sjsy** [comment]
I found that my Makefile have been cluttered by cmake. Fortunately by 'making all' from scratch I did not encounter the mentioned issue.

**Comment by sjsy** [comment]
Recently I forced to use cmake again and the problem came back!

> [ 84%] Linking CXX executable compute_image_mean
> /usr/local/lib/libopencv_imgcodecs.so.3.1.0: undefined reference to `TIFFReadDirectory@LIBTIFF_4.0'
> /usr/local/lib/libopencv_imgcodecs.so.3.1.0: undefined reference to `TIFFWriteEncodedStrip@LIBTIFF_4.0'
> /usr/local/lib/libopencv_imgcodecs.so.3.1.0: undefined reference to `TIFFIsTiled@LIBTIFF_4.0'
> /usr/local/lib/libopencv_imgcodecs.so.3.1.0: undefined reference to `TIFFOpen@LIBTIFF_4.0'
> /usr/local/lib/libopencv_imgcodecs.so.3.1.0: undefined reference to `TIFFReadEncodedStrip@LIBTIFF_4.0'
> /usr/local/lib/libopencv_imgcodecs.so.3.1.0: undefined reference to `TIFFSetField@LIBTIFF_4.0'
> /usr/local/lib/libopencv_imgcodecs.so.3.1.0: undefined reference to `TIFFWriteScanline@LIBTIFF_4.0'
> /usr/local/lib/libopencv_imgcodecs.so.3.1.0: undefined reference to `TIFFGetField@LIBTIFF_4.0'
> /usr/local/lib/libopencv_imgcodecs.so.3.1.0: undefined reference to `TIFFScanlineSize@LIBTIFF_4.0'
> /usr/local/lib/libopencv_imgcodecs.so.3.1.0: undefined reference to `TIFFNumberOfStrips@LIBTIFF_4.0'
> /usr/local/lib/libopencv_imgcodecs.so.3.1.0: undefined reference to `TIFFSetWarningHandler@LIBTIFF_4.0'
> /usr/local/lib/libopencv_imgcodecs.so.3.1.0: undefined reference to `TIFFSetErrorHandler@LIBTIFF_4.0'
> /usr/local/lib/libopencv_imgcodecs.so.3.1.0: undefined reference to `TIFFReadEncodedTile@LIBTIFF_4.0'
> /usr/local/lib/libopencv_imgcodecs.so.3.1.0: undefined reference to `TIFFReadRGBATile@LIBTIFF_4.0'
> /usr/local/lib/libopencv_imgcodecs.so.3.1.0: undefined reference to `TIFFClose@LIBTIFF_4.0'
> /usr/local/lib/libopencv_imgcodecs.so.3.1.0: undefined reference to `TIFFRGBAImageOK@LIBTIFF_4.0'
> /usr/local/lib/libopencv_imgcodecs.so.3.1.0: undefined reference to `TIFFReadRGBAStrip@LIBTIFF_4.0'
> collect2: error: ld returned 1 exit status
> tools/CMakeFiles/compute_image_mean.dir/build.make:134: recipe for target 'tools/compute_image_mean' failed
> make[2]: *** [tools/compute_image_mean] Error 1
> CMakeFiles/Makefile2:473: recipe for target 'tools/CMakeFiles/compute_image_mean.dir/all' failed
> make[1]: *** [tools/CMakeFiles/compute_image_mean.dir/all] Error 2
> Makefile:127: recipe for target 'all' failed
> make: *** [all] Error 2
> sjalal@IPDM-linux-server:~/Softwares/deepLearninig/caffe-master/build$  Linking CXX executable compute_image_mean
> Linking: command not found
> sjalal@IPDM-linux-server:~/Softwares/deepLearninig/caffe-master/build$ /usr/local/lib/libopencv_imgcodecs.so.3.1.0: undefined reference to `TIFFReadDirectory@LIBTIFF_4.0'^C
> sjalal@IPDM-linux-server:~/Softwares/deepLearninig/caffe-master/build$

Can anyone help me please?
Thanks.

**Comment by hawklucky** [comment]
I met the same problem, I checked that the opencv build without tiff=ON, so I turn it on and remake opencv, and then make the caffe successfully, hope that can help you.

**Comment by leo2105** [comment]
What is tiff = ON? How do you do that?

**Comment by hawklucky** [comment]
I forget the details. The tiff is one module in opencv,  we set the tiff ON to build opencv with tiff support. I think it's the main idea. Then when you build caffe with opencv, it may not raise issues.

**Comment by Roll920** [comment]
hi all,

I had the same error, but succeed by removing Anaconda form LD_LIBRARY_PATH.
see https://groups.google.com/forum/#!msg/caffe-users/wKYe45FKSqE/HcFMlGS-M8gJ for more details.

Wish this would help anyone who met the same problems:)

**Comment by agoramachina** [comment]
Thank you Roll920! I've been working on this problem for hours but removing Anaconda from LD_LIBRARY_PATH fixed everything immediately.

**Comment by shelhamer** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

**Comment by juwikuang** [comment]
@leo2105,

I found TIFF=off in my CMakeCache.txt file.

I successfully installed Open CV after setting it to ON.

I was installing only openCV. Not caffe.

My environment: Ubuntu 16.04

**Comment by Eniac-Xie** [comment]
Thank you LuoBo! @Roll920

**Comment by toby5box** [comment]
None of the above workarounds have helped me get past this problem; not even disabling OpenCV in the `Makefile.config`.

**Comment by amilapsn** [comment]
Thanks @Roll920 I had to remove anaconda from PATH too.

**Comment by Coldmooon** [comment]
#1559 [my solution](https://github.com/BVLC/caffe/issues/1559#issuecomment-507967219)

**Comment by lfydegithub** [comment]
conda remove libtiff

**Comment by WW2401** [comment]
When I make mattest，I met the follow problem.
Invalid MEX-file
'/home/caffe/matlab/+caffe/private/caffe_.mexa64':
/usr/local/lib/libopencv_imgcodecs.so.3.4: undefined symbol:
ZN2cv6detail17check_failed_autoEmmRKNS0_12CheckContextE.
Error in caffe.set_mode_cpu (line 5)
caffe('set_mode_cpu');
Error in caffe.run_tests (line 6)
caffe.set_mode_cpu();

Anyone knows how to solve it? Thanks a lot @Roll920 
ubuntu
matlab:R2018b
cuda:10.0
opencv:3.4.7
gcc/g++:5.5

**Comment by xieliy** [comment]
THE ULTIMATE SOLUTION IS THAT WE SHOULD PREVENT USING caffe,  most stupid package ever exist in this world.

**Comment by GuoleiSun** [comment]
agree

**Comment by GuoleiSun** [comment]
100% agree

**Comment by leo2105** [comment]
worked in the past and was a good pioneer in AI frameworks, but it has not been too developed currently.
