### ISSUE TITLE
Caffe installation in Linux mint

### ISSUE THREAD

**Issue by vardhan0806** [BVLC/caffe#4437]
Can caffe software be installed in Linux mint Sarah? I could not find any document in caffe webpage about Linux mint?

**Comment by shelhamer** [comment]
Please ask installation questions on the mailing list. As mint is based on ubuntu you might try following the ubuntu instructions.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
