### ISSUE TITLE
A doubt about contrastive loss layer

### ISSUE THREAD

**Issue by Jieeee** [BVLC/caffe#4438]
when doing backward computing, in the 95th line in src/caffe/layers/contrastive_loss_layer.cpp, why should -alpha * mdist be divided by dist?Is it a bug?

**Comment by seanbell** [comment]
I haven't derived it myself, but that's most likely from the chain rule when taking the derivative of the loss, which has a square root.  `d/dx sqrt(x) = 0.5 / sqrt(x)`.

If you want to double-check the unit test for the gradient, run only with `double` and make the thresholds much smaller.  If it still passes, then the gradient is likely correct.

**Comment by Jieeee** [comment]
Thank you! I have made it out.

**Comment by seanbell** [comment]
Thanks for helping check for correctness.
