### ISSUE TITLE
How to use a probability distribution as output label

### ISSUE THREAD

**Issue by rmsalinas** [BVLC/caffe#4440]
HI all,

I new using caffe. I am trying to train my net to provide as output a probability distribution over a set of classes. I do not want to train for a specific class to be the winner, but a known distribution on them.

My problem is that I do not know how to set the data and output layer to do so.

Can some one help me please?

**Comment by shelhamer** [comment]
Please ask modeling questions on the mailing list.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
