### ISSUE TITLE
Problem installing caffe on centOs, undefined reference to `ompi_mpi_cxx_op_intercept'

### ISSUE THREAD

**Issue by szm2015** [BVLC/caffe#4441]
Hi everyone
I first asked this question on caffe users group two days ago but nobody suggested anything so I decided to give it try here! please don't say here's not for answering installation issues!!!
I have installed caffe on ubuntu before and it works just fine, but now I need to install it on centOs. because I can't use yum for some reasons I have installed all the dependencies from source and added the required include or library directories to my Makefile.config, the following are the changed lines:

BLAS := open
# Custom (MKL/ATLAS/OpenBLAS) include and lib directories.
# Leave commented to accept the defaults for your choice of BLAS
# (which should work)!

BLAS_INCLUDE := /export/apps/openBLAS/include
BLAS_LIB := /export/apps/openBLAS/lib

.
.
.
# Whatever else you find you need goes here.

INCLUDE_DIRS := $(PYTHON_INCLUDE) /home/mousavi/boost_1_59_0 /home/mousavi/include \
        /export/apps/openBLAS/include /export/apps/hdf5/1.8.16/include \
        /export/apps/opencv/2.4.12/include /home/mousavi/openMPI/include /home/mousavi/leveldb-master/include
LIBRARY_DIRS := $(PYTHON_LIB) /usr/local/lib /usr/lib /home/mousavi/boost_1_59_0/stage/lib /home/mousavi/lib \
        /export/apps/hdf5/1.8.16/lib /home/mousavi/leveldb-master/out-shared /export/apps/opencv/2.4.12/lib \
        /export/apps/openBLAS/lib /export/apps/mpich2/gnu/lib /home/mousavi/openMPI/lib

When running make all I get the following errors:
      .build_release/lib/libcaffe.so: undefined reference to `ompi_mpi_cxx_op_intercept'
      .build_release/lib/libcaffe.so: undefined reference to`MPI::Win::Free()'

I tried to install open mpi manually and added the include and library directories but with no change. I also tried to use cmake as mentioned in https://github.com/BVLC/caffe/issues/2855. because I have installed the dependencies manually I had to mess with dependencies.cmake (it detects some of my installed dependencies like glog and gflags ok but for some like levelDB I had to add the libraries manually). the thing is to manually specify a library for cmake you need to name it completely like:
set (LIB "/home/mousavi/openMPI/lib/libvt-hyb.so")
or at least that's what I have found and it works ok for things like levelDB but not for mpi, actually I don't know which libraries I should add exactly to resolve this error and there are many of them and practically impossible to add them all. (note that I don't have access to the cmake GUI).

I really appreciate any help as I have searched much for this issue but with no success.

**Comment by xxw345** [comment]
I got the similar issue using MKL, I am still searching solution

**Comment by szm2015** [comment]
kindly send whatever you find here too, thank you.

**Comment by shelhamer** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
