### ISSUE TITLE
Hyperspectral image regression using Caffe Multilayer Perceptron Neural Network

### ISSUE THREAD

**Issue by Davar1990** [BVLC/caffe#4447]
Hi,

I have a hyperspectral image with the dimensions 600 × 600 × 1626 where the 600 × 600 are the spatial dimensions and the 1626 is the number of bands. I use every single pixel as a sample and the 1626 band values of that pixel as features for that pixel (sample). Alongside this hyperspectral image I have a 600 × 600 grayscale image whose normalized pixel values I use as target values for the corresponding pixels of my hyperspectral image. So what I'm trying to do is after training my neural network, when I pass along another hyperspectral image_ in this case the very same hyperspectral image I used for training_ the network will predict values similar to the normalized values of my grayscale response image by which I generate a grayscale image which is similar to the response image. Now the problems I have are as follows.

1) Since I don’t want to do classification and I just want to do regression, using Caffe framework, how can I access those predicted values by which I will attempt to generate an image?

2) Is it better to convert both my hyperspectral image and grayscale image into HDF5 format to pass along the network as data input or manipulate the source code, net prototxt file and the solver file to read my data? What do you think will be a good solution or what other solutions do you suggest?

I tried to find someone who has done hyperspectral image regression using Caffe (c++) to find a solution but unfortunately I couldn’t find anyone. Also the reason I mentioned to convert to HDF5 not LevelDB or LMDB is becasue I read in one of the posts here that float regression is not possible with these two formats. I apologize for asking such long questions in advance and would very much appreciate your help.

**Comment by seanbell** [comment]
Please ask modeling/usage questions on the mailing list, thanks!

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
