### ISSUE TITLE
How to train my model use *.py 

### ISSUE THREAD

**Issue by yechaochen** [BVLC/caffe#4450]
I have got a project that its train process was built by a ---.py file.I don't know how to complete the train with python programe because I always triain my model with `./build/tools/caffe train --solver=---`.

Can someone tell me how to do it.

**Comment by xxw345** [comment]
Why you need to use python wrapper to start training if you can use the compiled caffe directly from terminal? Can you pass the shell commands from python script to terminal? (like calling system command from python)

**Comment by yechaochen** [comment]
The project has deconvolution layer.I have browsed some blog and noticed that the parameter of deconvolution layer can't be initialized when we use the method `./build/tools/caffe train --solver=---`.And I have found a python file in the project which seems like to call CUDA to complete the train according to the code in it.

**Comment by wadefelix** [comment]
wrap the code as a Python Layer.
and have a loot at https://github.com/rbgirshick/py-faster-rcnn
