### ISSUE TITLE
ND convolution not working, again?

### ISSUE THREAD

**Issue by jrasi** [BVLC/caffe#4456]
Hi,

I am trying to use FCN model. The model is giving error that it can not handle more than 4 axes.

F0713 14:12:04.008546 32691 blob.hpp:140] Check failed: num_axes() <= 4 (5 vs. 4) Cannot use legacy accessors on Blobs with > 4 axes.

does the current latest caffe work with Nd data? If not how to fix this?

Tried with and without CuDNN (v4.0). 

Best,

**Comment by jrasi** [comment]
Hey! would anybody please reflect on this problem? If i use 2D groundtruth matrices (i.e. HxW) then it doesn't generate error but when i use it with singleton dimension (i.e. 1xHxW), it generates the above eror. Since loss is ridiculously large 3xe8 and comments in the layer code mentions that singleton dimension is necessary for loss computation therefore, i m trying to feed it with singleton dimension but in that case it just generates error that it can not handle more than 4 dimensions.

**Comment by antran89** [comment]
Hi,
> F0713 14:12:04.008546 32691 blob.hpp:140] Check failed: num_axes() <= 4 (5 vs. 4) Cannot use legacy accessors on Blobs with > 4 axes.

You should not use any methods/interface that use legacy blob index which support maximum 4 dims. Instead you should use the function compatible with modern ND-blob, for example, [offset function](https://github.com/BVLC/caffe/blob/master/include/caffe/blob.hpp#L166])

**Comment by jrasi** [comment]
Sorry, i didn't understand completely. Are you saying that i should change FCN code? Where do you want me to change - the layer code? In this file?
https://github.com/shelhamer/fcn.berkeleyvision.org/blob/master/nyud_layers.py

**Comment by wolfbill** [comment]
@antran89 so it need to be compiled again ?

**Comment by thigitogatiamas** [comment]
I have the same error. Cloned the github master branch today (2nd of December 2016) and exectued  make clean and make all. And I receive the same error! Could anyone help?

**Comment by thigitogatiamas** [comment]
@antran89 What do you mean by "not use any methods that use legacy blob index". I am just using HDF5Data Layer and in the next layer I try to convolve my data and then I get this error.
