### ISSUE TITLE
issue with running caffe model bvlc_alexnet

### ISSUE THREAD

**Issue by madhumitabehera** [BVLC/caffe#4460]
hi all
 i am trying to install caffe 0.15 to use with digits 4.1 beta.
i was successful in running make all make test make runtest.
i just want run alexnet model with the following  command to see how an exiting model is run.  
build/tools/caffe time --model=models/bvlc_alexnet/deploy-prototxt --gpu=1
however i am getting the following error.

I0714 23:51:37.208534 20416 caffe.cpp:343] Use GPU with device ID 1
F0714 23:51:37.524791 20416 io.cpp:36] Check failed: fd != -1 (-1 vs. -1) File not found: models/bvlc_alexnet/deploy-prototxt
*** Check failure stack trace: ***
    @     0x7f23dd792daa  (unknown)
    @     0x7f23dd792ce4  (unknown)
    @     0x7f23dd7926e6  (unknown)
    @     0x7f23dd795687  (unknown)
    @     0x7f23dddb6a3d  caffe::ReadProtoFromTextFile()
    @     0x7f23ddd90064  caffe::ReadNetParamsFromTextFileOrDie()
    @     0x7f23dddf038f  caffe::Net<>::Net()
    @           0x408b4f  time()
    @           0x405b3c  main
    @     0x7f23dc79ef45  (unknown)
    @           0x4063ab  (unknown)
    @              (nil)  (unknown)
Aborted (core dumped)

**Comment by shelhamer** [comment]
Please ask Caffe usage questions on the mailing list, and ask the DIGITS project about DIGITS questions. In this case the 

> File not found: models/bvlc_alexnet/deploy-prototxt

is telling you the file doesn't exist.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
