### ISSUE TITLE
Download failed: https://protobuf.googlecode.com/svn/rc/protobuf-2.6.0.tar.bz2

### ISSUE THREAD

**Issue by HuaizhengZhang** [BVLC/caffe#4463]
sudo brew install --with-python --fresh -vd protobuf

**Comment by seanbell** [comment]
Not sure why this is posted here; this appears to be unrelated to BVLC/caffe.

**Comment by seanbell** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
