### ISSUE TITLE
I don't understand the function of mirror parameter in the Data layer, is there anything to explain that?

### ISSUE THREAD

**Issue by Amsturdy** [BVLC/caffe#4469]

**Comment by seanbell** [comment]
It is random left-right flipping, a common operating when training models.  Please ask questions on the mailing list.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
