### ISSUE TITLE
problems on understanding parameters of 00-classification in examples.

### ISSUE THREAD

**Issue by primaryst** [BVLC/caffe#4475]
I started learning CNNs and Caffe a few days ago, when I learn the example 00-classification I met problems on understanding the parameters of the network.

data	(50, 3, 227, 227)
conv1	(50, 96, 55, 55)
pool1	(50, 96, 27, 27)
norm1	(50, 96, 27, 27)
conv2	(50, 256, 27, 27)
pool2	(50, 256, 13, 13)
norm2	(50, 256, 13, 13)
conv3	(50, 384, 13, 13)
conv4	(50, 384, 13, 13)
conv5	(50, 256, 13, 13)
pool5	(50, 256, 6, 6)
fc6	(50, 4096)
fc7	(50, 4096)
fc8	(50, 1000)
prob	(50, 1000)

above are the activation shapes.And the next are the param shapes.

conv1	(96, 3, 11, 11) (96,)
conv2	(256, 48, 5, 5) (256,)
conv3	(384, 256, 3, 3) (384,)
conv4	(384, 192, 3, 3) (384,)
conv5	(256, 192, 3, 3) (256,)
fc6	(4096, 9216) (4096,)
fc7	(4096, 4096) (4096,)
fc8	(1000, 4096) (1000,)

I think,if the shape of data is [227,227] for each channel,and the filter size of conv1 is [11,11],should not the shape of activation in conv1 be [217,217] ? For 227 + 1 - 11 = 217, and why is [55,55]?

Besides, what is the size of pooling unit in layer pool1 so that it can pooling the conv1 [55,55] to pool1 [27,27], is the last column or the row unpooled?

Any help would be really appreciated!

**Comment by seanbell** [comment]
You're missing the stride parameter; some layers also have padding.  The stride introduces downsampling.  Please ask questions on the mailing list, thanks!

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
