### ISSUE TITLE
how to usw two difference GPU (980 and 980ti) to train？

### ISSUE THREAD

**Issue by janemyleng** [BVLC/caffe#4477]
I bought two difference gpus, i thought  the 980  was the same with 980ti. When i train with the two gpus, howover, only one gpu work. How can i solve this problem? thank you!!
when i add "--gpu 0,1" ,show : I0718 11:31:29.220492 3568 parallel.cpp:234] GPU 1 does not have p2p access to GPU 0

**Comment by wdx04** [comment]
You may add "--gpu 0,1" to your caffe.exe command line arguments.
The actual performance would be  identical to two 980s(980ti has to wait for the slower 980).

**Comment by janemyleng** [comment]
when i add "--gpu 0,1" ,show : I0718 11:31:29.220492  3568 parallel.cpp:234] GPU 1 does not have p2p access to GPU 0

**Comment by wdx04** [comment]
This is normal, since you don't have SLI bridge between you GPUs(SLI only works for cards of the same model).

**Comment by seanbell** [comment]
Please ask usage questions on the mailing list, thanks!

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
