### ISSUE TITLE
 could not broadcast input array from shape (3,224,224) into shape (50,3,227,227)

### ISSUE THREAD

**Issue by Simon4john** [BVLC/caffe#4480]
When I run "Image Classification and Filter Visualization" by using Google-net, I get some trouble:
My code:

net.blobs['data'].data[...] = transformed_image
output = net.forward()
output_prob = output['prob'][0] # the output probability vector for the first image in the batch
print 'predicted class is:', output_prob.argmax()
error:

ValueError Traceback (most recent call last)
in ()
1 # copy the image data into the memory allocated for the net
----> 2 net.blobs['data'].data[...] = transformed_image
3 ### perform classification
4 output = net.forward()
5 output_prob = output['prob'][0] # the output probability vector for the first image in the batch

ValueError: could not broadcast input array from shape (3,224,224) into shape (50,3,227,227)
but when I comment this part code, everything is okay!

net.blobs['data'].reshape(50, # batch size
3, # 3-channel (BGR) images
227, 227) # image size is 227x227

**Comment by seanbell** [comment]
If you are only running 1 image, change the batch size to 1 instead of 50.  Even if you fix the indexing problem, you are computing the answer for 50 dummy images and throwing 49 away.  Closing since this is a usage question.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

**Comment by huge123** [comment]
I encountered the same problem，how to solve it？I even set the code like this：
`net.blobs['data'].reshape( 3,
                          277,
                          277)`

and it still showed 

ValueError Traceback (most recent call last)
<ipython-input-14-e83df0926a8e> in <module>()
      1 #copy the image data into the memory allocated for the net
----> 2 net.blobs['data'].data[...] = transformed_image
      3 
      4 #perform classification
      5 output = net.forward()

ValueError: could not broadcast input array from shape (3,227,227) into shape (3,277,277)

**Comment by yzsatgithub** [comment]
> I encountered the same problem，how to solve it？I even set the code like this：
> `net.blobs['data'].reshape( 3, 277, 277)`
> 
> and it still showed
> 
> ValueError Traceback (most recent call last)
> in ()
> 1 #copy the image data into the memory allocated for the net
> ----> 2 net.blobs['data'].data[...] = transformed_image
> 3
> 4 #perform classification
> 5 output = net.forward()
> 
> ValueError: could not broadcast input array from shape (3,227,227) into shape (3,277,277)

I came across similar problem.   Did you find the solution?

**Comment by paulapbrooks** [comment]
> > I encountered the same problem，how to solve it？I even set the code like this：
> > `net.blobs['data'].reshape( 3, 277, 277)`
> > and it still showed
> > ValueError Traceback (most recent call last)
> > in ()
> > 1 #copy the image data into the memory allocated for the net
> > ----> 2 net.blobs['data'].data[...] = transformed_image
> > 3
> > 4 #perform classification
> > 5 output = net.forward()
> > ValueError: could not broadcast input array from shape (3,227,227) into shape (3,277,277)
> 
> I came across similar problem. Did you find the solution? @huge123

I have also come across a similar problem. Has anyone found a solution for this? @huge123 @yzsatgithub Thank you!!!
