### ISSUE TITLE
Excuse me ,can I ask a question about Caffe installation on OS X 10.11?

### ISSUE THREAD

**Issue by yuqiGao** [BVLC/caffe#4483]
Here are the logs of `make all -j8`
`clang: warning: argument unused during compilation: '-pthread'
ld: warning: directory not found for option '-L/opt/intel/composer_xe_2015.2.132/mkl/lib'
CXX/LD -o .build_release/tools/caffe.bin
CXX/LD -o .build_release/tools/compute_image_mean.bin
CXX/LD -o .build_release/tools/convert_imageset.bin
CXX/LD -o .build_release/tools/device_query.bin
CXX/LD -o .build_release/tools/extract_features.bin
CXX/LD -o .build_release/tools/finetune_net.bin
clang: warning: argument unused during compilation: '-pthread'
clang: warning: argument unused during compilation: '-pthread'
clang: warning: argument unused during compilation: '-pthread'
clang: warning: argument unused during compilation: '-pthread'
clang: warning: argument unused during compilation: '-pthread'
ld: warning: directory not found for option '-L/opt/intel/composer_xe_2015.2.132/mkl/lib'
ld: warning: directory not found for option '-L/opt/intel/composer_xe_2015.2.132/mkl/lib'
ld: warning: directory not found for option '-L/opt/intel/composer_xe_2015.2.132/mkl/lib'ld: warning: 
directory not found for option '-L/opt/intel/composer_xe_2015.2.132/mkl/lib'
ld: warning: directory not found for option '-L/opt/intel/composer_xe_2015.2.132/mkl/lib'
CXX/LD -o .build_release/tools/net_speed_benchmark.bin
clang: warning: argument unused during compilation: '-pthread'
clang: warning: argument unused during compilation: '-pthread'
ld: warning: directory not found for option '-L/opt/intel/composer_xe_2015.2.132/mkl/lib'
ld: warning: directory not found for option '-L/opt/intel/composer_xe_2015.2.132/mkl/lib'
CXX/LD -o .build_release/tools/test_net.bin
clang: warning: argument unused during compilation: '-pthread'
CXX/LD -o .build_release/tools/train_net.bin
ld: warning: directory not found for option '-L/opt/intel/composer_xe_2015.2.132/mkl/lib'
clang: warning: argument unused during compilation: '-pthread'
ld: warning: directory not found for option '-L/opt/intel/composer_xe_2015.2.132/mkl/lib'
CXX/LD -o .build_release/tools/upgrade_net_proto_binary.bin
CXX/LD -o .build_release/tools/upgrade_net_proto_text.bin
clang: warning: argument unused during compilation: '-pthread'
CXX/LD -o .build_release/tools/upgrade_solver_proto_text.bin
ld: warning: directory not found for option '-L/opt/intel/composer_xe_2015.2.132/mkl/lib'
clang: warning: argument unused during compilation: '-pthread'
ld: warning: directory not found for option '-L/opt/intel/composer_xe_2015.2.132/mkl/lib'
clang: warning: argument unused during compilation: '-pthread'
ld: warning: directory not found for option '-L/opt/intel/composer_xe_2015.2.132/mkl/lib'
CXX/LD -o .build_release/examples/cifar10/convert_cifar_data.bin
CXX/LD -o .build_release/examples/cpp_classification/classification.bin
CXX/LD -o .build_release/examples/mnist/convert_mnist_data.bin
CXX/LD -o .build_release/examples/siamese/convert_mnist_siamese_data.bin
clang: warning: argument unused during compilation: '-pthread'
clang: warning: argument unused during compilation: '-pthread'
clang: warning: argument unused during compilation: '-pthread'
clang: warning: argument unused during compilation: '-pthread'
ld: warning: ld: warning: directory not found for option '-L/opt/intel/composer_xe_2015.2.132/mkl/lib'directory not found for option '-L/opt/intel/composer_xe_2015.2.132/mkl/lib'

ld: warning: directory not found for option '-L/opt/intel/composer_xe_2015.2.132/mkl/lib'
ld: warning: directory not found for option '-L/opt/intel/composer_xe_2015.2.132/mkl/lib'`

Then after this ,when `make runtest`
error occurs
` .build_release/tools/caffe
dyld: Library not loaded: @rpath/libmkl_rt.dylib
  Referenced from: /Users/gaoyuqi/Downloads/caffe/.build_release/tools/caffe
  Reason: image not found
make: *** [runtest] Trace/BPT trap: 5`
But 'L/opt/intel/composer_xe_2015.2.132/mkl/lib' not in my path
Thx for your help

**Comment by brianscroggins24** [comment]
Was there every answer to this question. I've installed the recent version of mkl but I don't have a composer_xe_2015 folder. Has something changed?
