### ISSUE TITLE
Filler in ND Convolutions use legacy shape

### ISSUE THREAD

**Issue by rogertrullo** [BVLC/caffe#4485]
Hi, 
I am not sure if Xavier initialization does not make sense for 3D data,
but if it does, 
There will be this error:
Check failed: num_axes() <= 4 (5 vs. 4) Cannot use legacy accessors on Blobs with > 4 axes.

Which happens because in the filler we use the legacy shape (but we only use num and channels which would be shape[0] san shape[1])

Is xavier initiallization only for 2d data, or can it just use the new shape accessors?

Thanks!

**Comment by antran89** [comment]
I think currently it only support 2D data, ND conv is not complete yet. You can modify the cpp code, if you want to make it working.
