### ISSUE TITLE
write lmdb with non-uint8 type very slow

### ISSUE THREAD

**Issue by jiuerbujie** [BVLC/caffe#4489]
I am writing about 3000 float type image to lmdb, use code like this

```
db = lmdb.open(path_dst, map_size=int(1e12))
with db.begin(write=True) as in_txn:
    for idx, img_name in enumerate(src_imgs):
    sp_img = loadmat(os.path.join(sp_path_src, img_name) + '.mat')['data'].astype(float)
    img_dat = caffe.io.array_to_datum(sp_img)
    in_txn.put('{:0>10d}'.format(idx), img_dat.SerializeToString())
```

It turns out to be very slow, at least 50 times slower than uint8 type images. I am wondering what is going on, is there any solution to speed up?

**Comment by vanpersie32** [comment]
@jiuerbujie hey,how did you solve the problem?

**Comment by shelhamer** [comment]
This seems to be inherent in LMDB and its python interface. Closing as not a Caffe issue. You could directly load the data through a Python data layer instead and bypass LMDB.
