### ISSUE TITLE
Adding TEST phase doubles the GPU memory required

### ISSUE THREAD

**Issue by mathmanu** [BVLC/caffe#4494]
I am running FCN for segmentation and requires large amount of GPU memory. 

During the training if I use the TEST phase, the GPU memory doubles and my training crashes due to lack of memory. Is this expected behaviour? 

Is there some way to work around it? For example, 
(1) is it possible to share the GPU memory between the TRAIN phase and TEST phase? OR 
(2) is it possible to run the TEST phase in a different GPU?

Thanks,

**Comment by shelhamer** [comment]
Please ask usage questions on the mailing list.

> (2) is it possible to run the TEST phase in a different GPU?

This can be done by splitting the evaluation code from the solving code and running the separate script on whatever GPU you like. You can for instance save models in the solving script then load the saved models for scoring in the evaluation script.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
