### ISSUE TITLE
Dead links for "Fully Convolutional Networks for Semantic Segmentation" .caffemodel files

### ISSUE THREAD

**Issue by 9thDimension** [BVLC/caffe#4496]
URLs like this 

https://github.com/shelhamer/fcn.berkeleyvision.org/blob/master/nyud-fcn32s-color/caffemodel-url

are dead and so weight files are unavailable.

**Comment by shelhamer** [comment]
I just checked both the fcn.berkeleyvision.org and dl.caffe.berkeleyvision.org links and everything is up. Check your connection?
