### ISSUE TITLE
Caffe cifar10: High false negative rate

### ISSUE THREAD

**Issue by YouKnowGJB** [BVLC/caffe#4500]
Hi, recently I'm doing a project which uses the modified cifar10 model to do binary classifications. After the model is trained, I used the cpp_classification to do binary classifications. However, although the accuracy during the training process converges to 95%, I still got high false negative rate (~40%) during the classification process.

I will be very appreciated if someone could point out the potential problems. Thanks in advance!

**Comment by seanbell** [comment]
Please ask usage questions on the mailing list, thanks!

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
