### ISSUE TITLE
How can i use multi gpu option in matcaffe?

### ISSUE THREAD

**Issue by pride0724** [BVLC/caffe#4504]
At pycaffe, it has a multi-gpu usage option.
But matcaffe has only GPU device ID option 

ex)
caffe.set_mode_gpu();
gpu_id = 0; % we will use the first gpu
caffe.set_device(gpu_id);

 Is it possible to use multi-gpu at matcaffe?

**Comment by seanbell** [comment]
Please ask usage questions on the mailing list, thanks!

(Also, I'm not sure if it is supported in matlab, but I know it is for Python).

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
