### ISSUE TITLE
Asynchronous pascal_multilabel_with_datalayer taken out

### ISSUE THREAD

**Issue by aurotripathy** [BVLC/caffe#4505]
I have a training situation where the synchronous python data layer just takes too long. Since my version is built on the reference (tutorial) code of `pascal_multilabel_with_datalayer`, it would be great if there  was a working version of the _asynchronous_ `pascal_multilabel_with_datalayer`.

From the comments and history, it was taken out before finalizing the tutorial. 

What was the reason? Did it work?

Thank you.

**Comment by aurotripathy** [comment]
Clarifying title since no one responded

**Comment by shelhamer** [comment]
As implemented it did not work and deliver a speed-up. Parallelizing a Python data layer needs to be done carefully to be effective. A multiprocessing pool is a good place to start.
