### ISSUE TITLE
osx error install  unknown type name 'HDF5DataLayer'

### ISSUE THREAD

**Issue by johndpope** [BVLC/caffe#4506]
caffe git:(master) ✗ make all
CXX src/caffe/layers/hdf5_data_layer.cpp
src/caffe/layers/hdf5_data_layer.cpp:25:1: error: unknown type name 'HDF5DataLayer'
HDF5DataLayer<Dtype>::~HDF5DataLayer<Dtype>() { }
^
src/caffe/layers/hdf5_data_layer.cpp:25:14: error: expected unqualified-id
HDF5DataLayer<Dtype>::~HDF5DataLayer<Dtype>() { }
             ^
src/caffe/layers/hdf5_data_layer.cpp:165:19: error: explicit instantiation of non-template class 'HDF5DataLayer'
INSTANTIATE_CLASS(HDF5DataLayer);
~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~
./include/caffe/common.hpp:39:18: note: expanded from macro 'INSTANTIATE_CLASS'
  template class classname<float>; \
                 ^        ~~~~~~~
src/caffe/layers/hdf5_data_layer.cpp:165:19: error: explicit instantiation of non-template class 'HDF5DataLayer'
INSTANTIATE_CLASS(HDF5DataLayer);
~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~
./include/caffe/common.hpp:40:18: note: expanded from macro 'INSTANTIATE_CLASS'
  template class classname<double>
                 ^        ~~~~~~~~
src/caffe/layers/hdf5_data_layer.cpp:166:1: error: allocation of incomplete type 'caffe::HDF5DataLayer'
REGISTER_LAYER_CLASS(HDF5Data);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./include/caffe/layer_factory.hpp:121:42: note: expanded from macro 'REGISTER_LAYER_CLASS'
    return shared_ptr<Layer<Dtype> >(new type##Layer<Dtype>(param));           \
                                         ^~~~~~~~~~~
<scratch space>:23:1: note: expanded from here
HDF5DataLayer
^~~~~~~~~~~~~
src/caffe/layers/hdf5_data_layer.cpp:165:19: note: forward declaration of 'caffe::HDF5DataLayer'
INSTANTIATE_CLASS(HDF5DataLayer);
                  ^
src/caffe/layers/hdf5_data_layer.cpp:166:1: error: 'Dtype' does not refer to a value
REGISTER_LAYER_CLASS(HDF5Data);
^
./include/caffe/layer_factory.hpp:121:54: note: expanded from macro 'REGISTER_LAYER_CLASS'
    return shared_ptr<Layer<Dtype> >(new type##Layer<Dtype>(param));           \
                                                     ^
src/caffe/layers/hdf5_data_layer.cpp:166:1: note: declared here
./include/caffe/layer_factory.hpp:118:22: note: expanded from macro 'REGISTER_LAYER_CLASS'
  template <typename Dtype>                                                    \
                     ^
6 errors generated.
make: *** [.build_release/src/caffe/layers/hdf5_data_layer.o] Error 1

I followed these instructions 
http://caffe.berkeleyvision.org/install_osx.html

including updating paths...  brew install....


brew install hdf5
Warning: homebrew/science/hdf5-1.8.16_1 already installed

Tried to install using ports / HDH5 but no joy. 
I'm pretty sure I don't have anaconda installed.

**Comment by johndpope** [comment]
wait a second - would this impact the install? 
<img width="1022" alt="screen shot 2016-07-22 at 5 14 01 pm" src="https://cloud.githubusercontent.com/assets/289994/17071475/b82f970a-502f-11e6-9bf6-d6fbeab21a6c.png">

**Comment by johndpope** [comment]
how does one 'skip the hdf5 formula' / does that mean don't install it via homebrew  ?

<img width="720" alt="screen shot 2016-07-22 at 5 17 19 pm" src="https://cloud.githubusercontent.com/assets/289994/17071550/31a17c02-5030-11e6-89d7-8e01de9974e5.png">

**Comment by johndpope** [comment]
I uninstalled anaconda - reinstalled hdf5 - but no joy.

**Comment by seanbell** [comment]
Please ask installation questions on the mailing list, thanks!

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
