### ISSUE TITLE
How to decide the  param 'offset' in 'crop_layer'.

### ISSUE THREAD

**Issue by jy9387** [BVLC/caffe#4507]
Hi, all
I notice that the crop_layer has added a new parameter 'offset' to decide how to crop the feature map after the deconvolutional layer. I think 'offset' may be relative with the network architecture. How can I get the proper offset with own network?

**Comment by shelhamer** [comment]
Please ask usage questions on the mailing list. See for instance [this thread on the crop layer](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/caffe-users/IgSBtsg5vfg/EJlvfoNWCgAJ) or the net definition code showing how to have the offset calculated automatically by net specification: https://github.com/shelhamer/fcn.berkeleyvision.org/blob/master/voc-fcn32s/net.py#L62

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
