### ISSUE TITLE
the error is “CXX/LD -o .build_release/test/test_all.testbin src/caffe/test/test_caffe_main.cpp .build_release/lib/libcaffe.so: undefined reference to `fLS::FLAGS_step' collect2: error: ld returned 1 exit status”，what should i do？

### ISSUE THREAD

**Issue by boyflytobeman** [BVLC/caffe#4508]

**Comment by shelhamer** [comment]
Please ask installation questions on the mailing list. If you're having trouble, you might want to try the Caffe [Dockerfile](https://github.com/BVLC/caffe/tree/master/docker) to take care of installation for you.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
