### ISSUE TITLE
CPU mode issue in Sample code matcaffe

### ISSUE THREAD

**Issue by wajahatamin** [BVLC/caffe#4509]
Showing error in running the sample code of matcaffe 
![screenshot from 2016-07-23 15-37-15](https://cloud.githubusercontent.com/assets/17565374/17077490/8f718eb0-50eb-11e6-9b97-a3bc7e64874b.png)

**Comment by yhldhit** [comment]
From the Error, it seems that Caffe is not correctly installed

**Comment by seanbell** [comment]
Please ask for help in installing caffe on the mailing list, thanks!

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
