### ISSUE TITLE
ask for help

### ISSUE THREAD

**Issue by fish145** [BVLC/caffe#4511]
When using caffe for trianing, can I fix the parameters for some layers and only train other layers??? If possible, can you give me some advice? I will be great thankful.

**Comment by ParitoshParmar** [comment]
@fish145 Yes, you can freeze a layer by setting its learning rate to 0.

**Comment by fish145** [comment]
@ParitoshParmar  Thanks very much for your answer! Can you tell me where to set the specfic layer learning rate? We usually set the learning rate in the solver.prototxt and this is for the whole network

**Comment by ParitoshParmar** [comment]
@fish145 In addition to Solver.prototxt, you can specify learning rates for individual layers as well. There are 2 learning rates for a layer, one for weights and other for bias. You can set them through 'lr_mult.' Does this answer your question ?

**Comment by fish145** [comment]
@ParitoshParmar Oh,I know,I know.Thank you very much!!
