### ISSUE TITLE
Protobuf 3.0.0 beta4 support

### ISSUE THREAD

**Issue by ibmua** [BVLC/caffe#4512]
I've successfully compiled caffe (make all) with standard protobuf, but then I read in http://caffe.berkeleyvision.org/installation.html that pycaffe requires protobuf 3.0 so I manually installed 3.0.0 beta4. I successfully compiled pycaffe, but now that I'm trying to reinstall it all I get problems like 

```
PROTOC src/caffe/proto/caffe.proto
CXX .build_release/src/caffe/proto/caffe.pb.cc
In file included from .build_release/src/caffe/proto/caffe.pb.cc:5:0:
.build_release/src/caffe/proto/caffe.pb.h:12:2: error: #error This file was generated by a newer version of protoc which is
 #error This file was generated by a newer version of protoc which is
  ^
.build_release/src/caffe/proto/caffe.pb.h:13:2: error: #error incompatible with your Protocol Buffer headers. Please update
 #error incompatible with your Protocol Buffer headers.  Please update
  ^
.build_release/src/caffe/proto/caffe.pb.h:14:2: error: #error your headers.
 #error your headers.
  ^
.build_release/src/caffe/proto/caffe.pb.h:22:35: fatal error: google/protobuf/arena.h: No such file or directory
 #include <google/protobuf/arena.h>
                                   ^
compilation terminated.
make: *** [.build_release/src/caffe/proto/caffe.pb.o] Error 1

```

When I don't include protoc v3 in PATH and "make all" with protoc v2.5 and then "make pycaffe" with protoc v3, everything's okay.

So you are using old v2 pb for everything except Python, is that right? If so, could you elaborate more on this topic in appropriate instructions? Because, this will definitely get more people confused.

**Comment by crowsonkb** [comment]
Are you sure you don't have header files hanging around somewhere from an older version of protobuf, or maybe an OS protobuf package installed as well? It sounds like you still have v2.5 installed somewhere and this is not a good idea. I've been using protobuf 3 with Caffe for a long time and have never seen this issue. But then I make sure I *only* have protobuf 3 installed in /usr/local.

**Comment by ibmua** [comment]
Thanks! Changing "google" folder inside /usr/include to the one from protobuf 3.0 (protobuf-3.0.0-beta-4/src/google) helped `make all` with protoc 3.0.0!

**Comment by ibmua** [comment]
Actually, not so fast...
But I'm digging into the other things that seem to be in need of fixing. That thing alone didn't fix everything, just the said errors. Getting errors like

.build_release/lib/libcaffe.so: undefined reference to `google::protobuf::internal::ArenaStringPtr::AssignWithDefault(std::string const*, google::protobuf::internal::ArenaStringPtr)'
.build_release/lib/libcaffe.so: undefined reference to `google::protobuf::io::CodedOutputStream::WriteLittleEndian64(unsigned long long)'
collect2: error: ld returned 1 exit status
make: *** [.build_release/tools/upgrade_solver_proto_text.bin] Error 1

later during compilation. Searching for an answer myself.
