### ISSUE TITLE
pthread issue // HDF5_hdf5_cpp_LIBRARY not found

### ISSUE THREAD

**Issue by Trig0n** [BVLC/caffe#4513]
I have two issues:
First thing is that after i cmake the project it shows me:

"""
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
HDF5_hdf5_cpp_LIBRARY
    linked by target "caffe" in directory /home/xxx/tools/caffe/src/caffe
"""

and I have no idea how to fix it.

Another issue I'm having is with pthread.
Since right below the above lines, it also shows this:

"""
-- Configuring incomplete, errors occurred!
See also "/home/xxx/tools/caffe/build/CMakeFiles/CMakeOutput.log".
See also "/home/xxx/tools/caffe/build/CMakeFiles/CMakeError.log".
"""

And if i check the CMakeError.log it says:

"""
Determining if the function pthread_create exists in the pthreads failed with the following output:
Change Dir: /home/insane/tools/caffe/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_84714/fast"
/usr/bin/make -f CMakeFiles/cmTC_84714.dir/build.make CMakeFiles/cmTC_84714.dir/build
make[1]: Verzeichnis »/home/xxx/tools/caffe/build/CMakeFiles/CMakeTmp« wird betreten
Building C object CMakeFiles/cmTC_84714.dir/CheckFunctionExists.c.o
/usr/bin/cc    -DCHECK_FUNCTION_EXISTS=pthread_create   -o CMakeFiles/cmTC_84714.dir/CheckFunctionExists.c.o   -c /usr/local/share/cmake-3.6/Modules/CheckFunctionExists.c
Linking C executable cmTC_84714
/usr/local/bin/cmake -E cmake_link_script CMakeFiles/cmTC_84714.dir/link.txt --verbose=1
/usr/bin/cc   -DCHECK_FUNCTION_EXISTS=pthread_create    CMakeFiles/cmTC_84714.dir/CheckFunctionExists.c.o  -o cmTC_84714 -rdynamic -lpthreads
/usr/bin/ld: cannot find -lpthreads
collect2: error: ld returned 1 exit status
make[1]: *** [cmTC_84714] Fehler 1
make[1]: Verzeichnis »/home/xxx/tools/caffe/build/CMakeFiles/CMakeTmp« wird verlassen
make: *** [cmTC_84714/fast] Fehler 2
"""

Which apparently roughly translates into pthread cannot be found.

Is that a bug or am I doing something wrong?

**Comment by drawoc** [comment]
The HDF5 issue is a bug that is solved by pull request #4516, which hasn't been merged yet. I'm not sure about the pthread issue.

**Comment by shelhamer** [comment]
Please ask installation questions on the mailing list. If you're having trouble, you might want to try the Caffe [Dockerfile](https://github.com/BVLC/caffe/tree/master/docker) to take care of installation for you.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
