### ISSUE TITLE
make pycaffe gives “no rule to make target”

### ISSUE THREAD

**Issue by edbarbaro** [BVLC/caffe#4521]
I want to import caffe to my python 2.7 (anaconda/mac). I managed to do the make (all, test, and runtest), all passed with success. Here's a snippet of the make runtest command:

    [----------] Global test environment tear-down
    [==========] 1096 tests from 150 test cases ran. (49316 ms total)
    [  PASSED  ] 1096 tests.

The next step according to the [caffe manual][1] is to run the command: 

    make pycaffee

There I get the error:

> make: *** No rule to make target `python/caffe/_caffe.cpp', needed by
> 'python/caffe/_caffe.so'.  Stop.

I believe that this has to do with the **pythonpath**, however I cannot figure out what I am missing.

Here's a piece of my bash_profile:

> export PATH="//anaconda/bin:$PATH" export

> PATH="/home/XXX/anaconda/bin:$PATH" export

> PYTHONPATH=~/Desktop/Google_deepDream/caffe-master/python:$PYTHONPATH

Also, a piece of my makefile looks like:

    # NOTE: this is required only if you will compile the python interface.
    # We need to be able to find Python.h and numpy/arrayobject.h.
    #PYTHON_INCLUDE := /usr/include/python2.7 \
    #		/usr/lib/python2.7/dist-packages/numpy/core/include
    # Anaconda Python distribution is quite popular. Include path:
    # Verify anaconda location, sometimes it's nin root.
     ANACONDA_HOME := ~/../../anaconda
     PYTHON_INCLUDE := $(ANACONDA_HOME)/include \
    		 $(ANACONDA_HOME)/include/python2.7 \
    		 $(ANACONDA_HOME)/lib/python2.7/site-packages/numpy/core/include \

    # We need to be able to find libpythonX.X.so or .dylib.
    #PYTHON_LIB := /usr/lib
    PYTHON_LIB := $(ANACONDA_HOME)/lib
 
I also have all the python dependencies:

    for req in $(cat requirements.txt); do pip install $req; done

[1]: http://caffe.berkeleyvision.org/tutorial/interfaces.html

**Comment by seanbell** [comment]
Please ask for help in installing caffe on the mailing list, thanks!

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
