### ISSUE TITLE
How to do transfer learning with my own data ?  

### ISSUE THREAD

**Issue by AlexandraAMC** [BVLC/caffe#4522]
Hello, 

I want to train a existing network with my data but I don't really understand how to define my data layer.
I use a HDF5 file. 
Do I have to use a deploy.prototxt file or the 'normal'.prototxt file ? 
How do I define where my data is and the size of the network input ? 

If I just use a data layer type:HDF5 and give the source, when I create my net the input cell is 0x1.
I tried to use a deploy file where I just define the input size, in that case the input cell is 1x1 but I don't say where the data is. 

Could anyone give me some advice ? 

I work on Ubuntu 14.04 and Matlab R2015a

**Comment by seanbell** [comment]
Please ask usage questions on the mailing list, thanks!

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
