### ISSUE TITLE
Can be used .dcm  file training network? If you can data set should be how to save or read? thank  you !

### ISSUE THREAD

**Issue by tjpuzhaolei** [BVLC/caffe#4524]

**Comment by seanbell** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
