### ISSUE TITLE
CPU_ONLY mode - test_convolution_layer_spatial issue (opencl)

### ISSUE THREAD

**Issue by kris-hu** [BVLC/caffe#4529]
Hi,

I'm a complete beginner to caffe and trying to use caffe-opencl on Intel CPU (only change CPU_ONLY := 1 in Makefile.config). 
It could pass "make all", but failed in "make test", there were many errors in src/caffe/test/test_convolution_layer_spatial.cpp.

$make test
CXX src/caffe/test/test_dummy_data_layer.cpp
CXX src/caffe/test/test_reshape_layer.cpp
CXX src/caffe/test/test_sigmoid_cross_entropy_loss_layer.cpp
CXX src/caffe/test/test_eltwise_layer.cpp
CXX src/caffe/test/test_reduction_layer.cpp
CXX src/caffe/test/test_db.cpp
CXX src/caffe/test/test_infogain_loss_layer.cpp
CXX src/caffe/test/test_io.cpp
CXX src/caffe/test/test_embed_layer.cpp
CXX src/caffe/test/test_rnn_layer.cpp
CXX src/caffe/test/test_hinge_loss_layer.cpp
CXX src/caffe/test/test_mvn_layer.cpp
CXX src/caffe/test/test_layer_factory.cpp
CXX src/caffe/test/test_pooling_layer.cpp
CXX src/caffe/test/test_ocl_kernel_compile.cpp
CXX src/caffe/test/test_data_transformer.cpp
CXX src/caffe/test/test_hdf5data_layer.cpp
CXX src/caffe/test/test_data_layer.cpp
CXX src/caffe/test/test_slice_layer.cpp
CXX src/caffe/test/test_benchmark.cpp
CXX src/caffe/test/test_threshold_layer.cpp
CXX src/caffe/test/test_flatten_layer.cpp
CXX src/caffe/test/test_contrastive_loss_layer.cpp
CXX src/caffe/test/test_syncedmem.cpp
CXX src/caffe/test/test_filter_layer.cpp
CXX src/caffe/test/test_convolution_layer_FFT.cpp
CXX src/caffe/test/test_concat_layer.cpp
CXX src/caffe/test/test_batch_norm_layer.cpp
CXX src/caffe/test/test_random_number_generator.cpp
CXX src/caffe/test/test_spp_layer.cpp
CXX src/caffe/test/test_tile_layer.cpp
CXX src/caffe/test/test_accuracy_layer.cpp
CXX src/caffe/test/test_pooling_nd_layer.cpp
CXX src/caffe/test/test_softmax_with_loss_layer.cpp
CXX src/caffe/test/test_filler.cpp
CXX src/caffe/test/test_inner_product_layer.cpp
CXX src/caffe/test/test_convolution_nd_layer.cpp
CXX src/caffe/test/test_math_functions.cpp
CXX src/caffe/test/test_euclidean_loss_layer.cpp
CXX src/caffe/test/test_power_layer.cpp
CXX src/caffe/test/test_hdf5_output_layer.cpp
CXX src/caffe/test/test_upgrade_proto.cpp
CXX src/caffe/test/test_common.cpp
CXX src/caffe/test/test_blob.cpp
CXX src/caffe/test/test_lrn_layer.cpp
CXX src/caffe/test/test_convolution_layer.cpp
CXX src/caffe/test/test_bias_layer.cpp
CXX src/caffe/test/test_im2col_layer.cpp
CXX src/caffe/test/test_maxpool_dropout_layers.cpp
CXX src/caffe/test/test_solver.cpp
CXX src/caffe/test/test_multinomial_logistic_loss_layer.cpp
CXX src/caffe/test/test_util_blas.cpp
CXX src/caffe/test/test_lstm_layer.cpp
CXX src/caffe/test/test_gradient_based_solver.cpp
CXX src/caffe/test/test_batch_reindex_layer.cpp
CXX src/caffe/test/test_pooling_ndsk_layer.cpp
CXX src/caffe/test/test_argmax_layer.cpp
CXX src/caffe/test/test_mergecrop_layer.cpp
CXX src/caffe/test/test_libdnn_conv.cpp
CXX src/caffe/test/test_convolution_layer_spatial.cpp
src/caffe/test/test_convolution_layer_spatial.cpp: In member function ‘virtual void caffe::ConvolutionLayerTest_Spatial_TestSetup_Spatial_Test<gtest_TypeParam_>::TestBody()’:
src/caffe/test/test_convolution_layer_spatial.cpp:178:13: error: expected type-specifier before ‘ConvolutionLayerSpatial’
         new ConvolutionLayerSpatial<Dtype>(layer_param));
             ^
src/caffe/test/test_convolution_layer_spatial.cpp:191:21: error: expected type-specifier before ‘ConvolutionLayerSpatial’
     layer.reset(new ConvolutionLayerSpatial<Dtype>(layer_param));
                     ^
src/caffe/test/test_convolution_layer_spatial.cpp: In member function ‘virtual void caffe::ConvolutionLayerTest_Spatial_TestSimpleConvolution_Spatial_Test<gtest_TypeParam_>::TestBody()’:
src/caffe/test/test_convolution_layer_spatial.cpp:219:13: error: expected type-specifier before ‘ConvolutionLayerSpatial’
         new ConvolutionLayerSpatial<Dtype>(layer_param));
             ^
src/caffe/test/test_convolution_layer_spatial.cpp: In member function ‘virtual void caffe::ConvolutionLayerTest_Spatial_TestSimpleConvolution_Spatial3x3_Test<gtest_TypeParam_>::TestBody()’:
src/caffe/test/test_convolution_layer_spatial.cpp:257:13: error: expected type-specifier before ‘ConvolutionLayerSpatial’
         new ConvolutionLayerSpatial<Dtype>(layer_param));
             ^
src/caffe/test/test_convolution_layer_spatial.cpp: In member function ‘virtual void caffe::ConvolutionLayerTest_Spatial_TestSimpleConvolution_Spatial3x3xPad1_Test<gtest_TypeParam_>::TestBody()’:
src/caffe/test/test_convolution_layer_spatial.cpp:298:13: error: expected type-specifier before ‘ConvolutionLayerSpatial’
         new ConvolutionLayerSpatial<Dtype>(layer_param));
             ^
src/caffe/test/test_convolution_layer_spatial.cpp: In member function ‘virtual void caffe::ConvolutionLayerTest_Spatial_TestSimpleConvolution_Spatial11x11x1x2_caffenet_Conv1_Test<gtest_TypeParam_>::TestBody()’:
src/caffe/test/test_convolution_layer_spatial.cpp:339:13: error: expected type-specifier before ‘ConvolutionLayerSpatial’
         new ConvolutionLayerSpatial<Dtype>(layer_param));
             ^
src/caffe/test/test_convolution_layer_spatial.cpp: In member function ‘virtual void caffe::ConvolutionLayerTest_Spatial_TestSimpleConvolution_Spatial5x5x1x2_caffenet_Conv2_Test<gtest_TypeParam_>::TestBody()’:
src/caffe/test/test_convolution_layer_spatial.cpp:381:13: error: expected type-specifier before ‘ConvolutionLayerSpatial’
         new ConvolutionLayerSpatial<Dtype>(layer_param));
             ^
src/caffe/test/test_convolution_layer_spatial.cpp: In member function ‘virtual void caffe::ConvolutionLayerTest_Spatial_TestSimpleConvolution_Spatial3x3x1_caffenet_Conv3_Test<gtest_TypeParam_>::TestBody()’:
src/caffe/test/test_convolution_layer_spatial.cpp:422:13: error: expected type-specifier before ‘ConvolutionLayerSpatial’
         new ConvolutionLayerSpatial<Dtype>(layer_param));
             ^
src/caffe/test/test_convolution_layer_spatial.cpp: In member function ‘virtual void caffe::ConvolutionLayerTest_Spatial_TestSimpleConvolution_Spatial3x3x1_caffenet_Conv4_Test<gtest_TypeParam_>::TestBody()’:
src/caffe/test/test_convolution_layer_spatial.cpp:463:13: error: expected type-specifier before ‘ConvolutionLayerSpatial’
         new ConvolutionLayerSpatial<Dtype>(layer_param));
             ^
src/caffe/test/test_convolution_layer_spatial.cpp: In member function ‘virtual void caffe::ConvolutionLayerTest_Spatial_TestSimpleConvolution_Spatial3x3x2_caffenet_Conv5_Test<gtest_TypeParam_>::TestBody()’:
src/caffe/test/test_convolution_layer_spatial.cpp:504:13: error: expected type-specifier before ‘ConvolutionLayerSpatial’
         new ConvolutionLayerSpatial<Dtype>(layer_param));
             ^
src/caffe/test/test_convolution_layer_spatial.cpp: In member function ‘virtual void caffe::ConvolutionLayerTest_Spatial_TestSimpleConvolution_Spatial5x5_Test<gtest_TypeParam_>::TestBody()’:
src/caffe/test/test_convolution_layer_spatial.cpp:544:13: error: expected type-specifier before ‘ConvolutionLayerSpatial’
         new ConvolutionLayerSpatial<Dtype>(layer_param));
             ^
src/caffe/test/test_convolution_layer_spatial.cpp: In member function ‘virtual void caffe::ConvolutionLayerTest_Spatial_Test1x1Convolution_Spatial_Test<gtest_TypeParam_>::TestBody()’:
src/caffe/test/test_convolution_layer_spatial.cpp:580:13: error: expected type-specifier before ‘ConvolutionLayerSpatial’
         new ConvolutionLayerSpatial<Dtype>(layer_param));
             ^
src/caffe/test/test_convolution_layer_spatial.cpp: In member function ‘virtual void caffe::ConvolutionLayerTest_Spatial_TestSimpleConvolutionGroup_Spatial_Test<gtest_TypeParam_>::TestBody()’:
src/caffe/test/test_convolution_layer_spatial.cpp:610:13: error: expected type-specifier before ‘ConvolutionLayerSpatial’
         new ConvolutionLayerSpatial<Dtype>(layer_param));
             ^
src/caffe/test/test_convolution_layer_spatial.cpp: In member function ‘virtual void caffe::ConvolutionLayerTest_Spatial_TestSobelConvolution_Spatial_Test<gtest_TypeParam_>::TestBody()’:
src/caffe/test/test_convolution_layer_spatial.cpp:648:13: error: expected type-specifier before ‘ConvolutionLayerSpatial’
         new ConvolutionLayerSpatial<Dtype>(layer_param));
             ^
src/caffe/test/test_convolution_layer_spatial.cpp:682:21: error: expected type-specifier before ‘ConvolutionLayerSpatial’
     layer.reset(new ConvolutionLayerSpatial<Dtype>(layer_param));
                     ^
src/caffe/test/test_convolution_layer_spatial.cpp:704:21: error: expected type-specifier before ‘ConvolutionLayerSpatial’
     layer.reset(new ConvolutionLayerSpatial<Dtype>(layer_param));
                     ^
src/caffe/test/test_convolution_layer_spatial.cpp: In member function ‘virtual void caffe::ConvolutionLayerTest_Spatial_TestGradient_Spatial_Test<gtest_TypeParam_>::TestBody()’:
src/caffe/test/test_convolution_layer_spatial.cpp:735:5: error: ‘ConvolutionLayerSpatial’ was not declared in this scope
     ConvolutionLayerSpatial<Dtype> layer(layer_param);
     ^
src/caffe/test/test_convolution_layer_spatial.cpp:735:34: error: expected primary-expression before ‘>’ token
     ConvolutionLayerSpatial<Dtype> layer(layer_param);
                                  ^
src/caffe/test/test_convolution_layer_spatial.cpp:735:53: error: there are no arguments to ‘layer’ that depend on a template parameter, so a declaration of ‘layer’ must be available [-fpermissive]
     ConvolutionLayerSpatial<Dtype> layer(layer_param);
                                                     ^
src/caffe/test/test_convolution_layer_spatial.cpp:735:53: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)
src/caffe/test/test_convolution_layer_spatial.cpp:737:38: error: ‘layer’ was not declared in this scope
     checker.CheckGradientExhaustive(&layer, this->blob_bottom_vec_,
                                      ^
src/caffe/test/test_convolution_layer_spatial.cpp: In member function ‘virtual void caffe::ConvolutionLayerTest_Spatial_Test1x1Gradient_Spatial_Test<gtest_TypeParam_>::TestBody()’:
src/caffe/test/test_convolution_layer_spatial.cpp:755:5: error: ‘ConvolutionLayerSpatial’ was not declared in this scope
     ConvolutionLayerSpatial<Dtype> layer(layer_param);
     ^
src/caffe/test/test_convolution_layer_spatial.cpp:755:34: error: expected primary-expression before ‘>’ token
     ConvolutionLayerSpatial<Dtype> layer(layer_param);
                                  ^
src/caffe/test/test_convolution_layer_spatial.cpp:755:53: error: there are no arguments to ‘layer’ that depend on a template parameter, so a declaration of ‘layer’ must be available [-fpermissive]
     ConvolutionLayerSpatial<Dtype> layer(layer_param);
                                                     ^
src/caffe/test/test_convolution_layer_spatial.cpp:757:38: error: ‘layer’ was not declared in this scope
     checker.CheckGradientExhaustive(&layer, this->blob_bottom_vec_,
                                      ^
src/caffe/test/test_convolution_layer_spatial.cpp: In member function ‘virtual void caffe::ConvolutionLayerTest_Spatial_TestGradientGroup_Spatial_Test<gtest_TypeParam_>::TestBody()’:
src/caffe/test/test_convolution_layer_spatial.cpp:774:5: error: ‘ConvolutionLayerSpatial’ was not declared in this scope
     ConvolutionLayerSpatial<Dtype> layer(layer_param);
     ^
src/caffe/test/test_convolution_layer_spatial.cpp:774:34: error: expected primary-expression before ‘>’ token
     ConvolutionLayerSpatial<Dtype> layer(layer_param);
                                  ^
src/caffe/test/test_convolution_layer_spatial.cpp:774:53: error: there are no arguments to ‘layer’ that depend on a template parameter, so a declaration of ‘layer’ must be available [-fpermissive]
     ConvolutionLayerSpatial<Dtype> layer(layer_param);
                                                     ^
src/caffe/test/test_convolution_layer_spatial.cpp:776:38: error: ‘layer’ was not declared in this scope
     checker.CheckGradientExhaustive(&layer, this->blob_bottom_vec_,
                                      ^
src/caffe/test/test_convolution_layer_spatial.cpp: In instantiation of ‘void caffe::ConvolutionLayerTest_Spatial_TestGradientGroup_Spatial_Test<gtest_TypeParam_>::TestBody() [with gtest_TypeParam_ = caffe::CPUDevice<float>]’:
src/caffe/test/test_convolution_layer_spatial.cpp:781:1:   required from here
src/caffe/test/test_convolution_layer_spatial.cpp:774:53: error: ‘layer’ was not declared in this scope
     ConvolutionLayerSpatial<Dtype> layer(layer_param);
                                                     ^
src/caffe/test/test_convolution_layer_spatial.cpp: In instantiation of ‘void caffe::ConvolutionLayerTest_Spatial_Test1x1Gradient_Spatial_Test<gtest_TypeParam_>::TestBody() [with gtest_TypeParam_ = caffe::CPUDevice<float>]’:
src/caffe/test/test_convolution_layer_spatial.cpp:781:1:   required from here
src/caffe/test/test_convolution_layer_spatial.cpp:755:53: error: ‘layer’ was not declared in this scope
     ConvolutionLayerSpatial<Dtype> layer(layer_param);
                                                     ^
src/caffe/test/test_convolution_layer_spatial.cpp: In instantiation of ‘void caffe::ConvolutionLayerTest_Spatial_TestGradient_Spatial_Test<gtest_TypeParam_>::TestBody() [with gtest_TypeParam_ = caffe::CPUDevice<float>]’:
src/caffe/test/test_convolution_layer_spatial.cpp:781:1:   required from here
src/caffe/test/test_convolution_layer_spatial.cpp:735:53: error: ‘layer’ was not declared in this scope
     ConvolutionLayerSpatial<Dtype> layer(layer_param);
                                                     ^
make: **\* [.build_release/src/caffe/test/test_convolution_layer_spatial.o] Error 1

My environment is ubuntu14.04 64-bit and Intel® Core™ i7-4770 CPU @ 3.40GHz × 8. 
I've download the Intel opencl backend from https://software.intel.com/en-us/articles/opencl-drivers#latest_linux_driver. Now I want to try the Intel opencl backend on this CPU using caffe-opencl, then how to configure? And why the issue above happens?

Best Regards,
Kris

**Comment by naibaf7** [comment]
@kris-hu 
If you want to use the CPU with OpenCL, you should NOT compile with CPU_ONLY.

To OpenCL, all devices, whether they are CPU, GPU or APU, are all considered as OpenCL GPUs.
So you should compile with:
- USE_GREENTEA := 1
- USE_CUDA := 0 (or commented out)
- CPU_ONLY := 0 (or commented out)

**Comment by kris-hu** [comment]
@naibaf7 
Yes, it passed "make test" now.
But should also set USE_INTEL_SPATIAL := 1 (commented out) on my PC (Intel CPU and HD Graphics), or the similar issue will happen again.

Thanks very much for your help,  I really appreciate it.

**Comment by naibaf7** [comment]
@kris-hu 
Take care with USE_INTEL_SPATIAL, it is intended for HD Graphics, but it will also be selected for the CPU when enabled, and it's not really good on CPUs. Using MKL would be better for the CPU.

**Comment by kris-hu** [comment]
@naibaf7 
Thanks for that hint!
One more question about USE_INTEL_SPATIAL that confuse me:
When I set USE_INTEL_SPATIAL := 0, it could pass "make all", but failed in "make test", seems that the convolution spatial tests were still inculded.
Is it reasonable? Or is it due to that the spatial domain convolution is enabled by default for Intel Gen Graphics paltform?

**Comment by naibaf7** [comment]
No this is indeed a small #ifdef guard that is missing.

**Comment by kris-hu** [comment]
@naibaf7 
Got it, thanks.
