### ISSUE TITLE
How to change top blob names with Python net_spec interface

### ISSUE THREAD

**Issue by taoari** [BVLC/caffe#4531]
How can I change top blob names? For example, 

```
data, label = L.Data(source='lmdb', backend=P.Data.LMDB, batch_size=batch_size, ntop=2, 
    top=['data', 'label'],
    transform_param=dict(crop_size=227, mean_value=[104, 117, 123], mirror=True))
```

gives me:

```
layer {
  name: "Data1"
  type: "Data"
  top: "Data1"
  top: "Data2"
  top: "data"
  top: "label"
  transform_param {
    mirror: true
    crop_size: 227
    mean_value: 104
    mean_value: 117
    mean_value: 123
  }
  data_param {
    source: "lmdb"
    batch_size: 256
    backend: LMDB
  }
}
```

What I am expecting is two blobs rather than four blobs.

**Comment by shelhamer** [comment]
```
n = caffe.NetSpec()
n.data, n.label = ...
print(str(n.to_proto()))
```

will name the tops. Please ask usage questions on the mailing list.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
