### ISSUE TITLE
Use of LSTM

### ISSUE THREAD

**Issue by anirbanrayhci** [BVLC/caffe#4534]
Hi,
I was wondering if there is a way around where I can use any arbitrary vector input in an LSTM layer without committing on batch size or time step from before hand. The number of LSTM layer I use is equal to the number of total time step with each LSTM layer denoting a single time step.

**Comment by seanbell** [comment]
Hi, please ask questions about how to use caffe on the mailing list, thanks!

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
