### ISSUE TITLE
Writing test for custom layer

### ISSUE THREAD

**Issue by Sowasa** [BVLC/caffe#4535]
I have trouble writing the tests for custom layers correctly. 
When executing make runtest, I see the following error:

[ RUN      ] LayerFactoryTest/0.TestCreateLayer
src/caffe/test/test_layer_factory.cpp:47: Failure
Value of: layer->type()
  Actual: ""
Expected: iter->first
Which is: "MyLayer"
[  FAILED  ] LayerFactoryTest/0.TestCreateLayer, where TypeParam = caffe::CPUDevice<float> (142 ms)

4 times, so I see this in the summary:

[  FAILED  ] 4 tests, listed below:
[  FAILED  ] LayerFactoryTest/0.TestCreateLayer, where TypeParam = caffe::CPUDevice<float>
[  FAILED  ] LayerFactoryTest/1.TestCreateLayer, where TypeParam = caffe::CPUDevice<double>
[  FAILED  ] LayerFactoryTest/2.TestCreateLayer, where TypeParam = caffe::GPUDevice<float>
[  FAILED  ] LayerFactoryTest/3.TestCreateLayer, where TypeParam = caffe::GPUDevice<double>

It seems the layer can't be created in the test. However, it is registered and works well in models, I have also done all tests manually, to make sure it works as intended.

Some pointer to what is missing would be very much appreciated!

**Comment by jcastagneri** [comment]
In your header file for `MyLayer` you should have a public method called type() that looks like this:
`virtual inline const char* type() const { return "MyLayer"; } `

The factory has registered your layer by the tag `MyLayer` and this tag must match the type given by your layer's interface. The `Actual: ""` shows that caffe does not know what type your layer is.

**Comment by seanbell** [comment]
Please ask debug/help questions on the mailing list, thanks!

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
