### ISSUE TITLE
Faster way to zero out blobs on GPU?

### ISSUE THREAD

**Issue by crowsonkb** [BVLC/caffe#4539]
In my Python code I do the following inside my inner loop:

```python
for blob in self.net.blobs:
    self.net.blobs[blob].diff[:] = 0
```

which I suspect involves a lot of host-to-GPU data transfers. Taking these lines out speeds up my code significantly but at the expense of correctness (leftover diffs from previous runs of the function mess things up). It would be nice if there were some Python-accessible function that would cause the GPU to zero out blobs itself without data transfers.

**Comment by shelhamer** [comment]
There is a method to clear the parameter diffs through pycaffe: `net.clear_param_diffs()`, but there is not a corresponding method for clearing top/bottom diffs. The top/bottom diffs are actually overwritten on backward, so these should not need manual clearing in this way as you're doing with your `net.blobs` loop. Are you making use of custom layers that don't follow this behavior?

Please ask pycaffe usage questions on our mailing list. From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
