### ISSUE TITLE
homebrew leveldb dyld: Library not loaded (image not found)

### ISSUE THREAD

**Issue by shelhamer** [BVLC/caffe#454]
The homebrew install of leveldb seems to not properly package the dylib name or else it's missing a symlink. Caffe compiles properly, but crashes instantly:

```
dyld: Library not loaded: /usr/local/opt/leveldb/lib/libleveldb.dylib.1
  Referenced from: /Users/shelhamer/h/desk/caffe/caffe/build/test/test_all.testbin
  Reason: image not found
make: *** [runtest] Trace/BPT trap: 5
```

The solution is to make a libleveldb.dylib.1 symlink to libleveldb.1.15.dylib in /usr/local/opt/leveldb/lib either manually or by appending

```
    lib.install_symlink lib/'libleveldb.1.15.dylib' => 'libleveldb.dylib.1'
```

to the install method of the leveldb formula by `brew edit leveldb`.

An upstream fix is probably best, but I'm merely documenting it here for lack of time.

**Comment by Jessespace** [comment]
when I use "sudo make runtest",error occured

**error while loading shared libraries: libhdf5_hl.so.100: cannot open shared object file: No such file or directory make: *** [runtest] error 127**

This is my ~/.bashrc text.


**export PATH=/usr/local/cuda-8.0/bin${PATH:+:${PATH}}  
export LD_LIBRARY_PATH=/usr/local/cuda8.0/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}} 
export CUDA_HOME=/usr/local/cuda

export PATH=/home/jesse/software/Matlab2017a/Installer/bin${PATH:+:${PATH}}  

export PATH=/home/jesse/anaconda2/bin:$PATH
export LD_LIBARY_PATH=/home/jesse/anaconda2/lib:$LD_LIBRARY_PATH**

What should i do
