### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by KeeganRen** [BVLC/caffe#4540]
Caffe能不能像opencv那种编译之后直接安装到系统里，我发现很多研究者都会在caffe里面增加一些自己的代码，然后别人在使用他们代码的时候还要把他们的整个caffe下下来编译，很不方便，经常会造成版本混乱出错，很麻烦。

**Comment by PENGUINLIONG** [comment]
Caffe is designated to _be installed_ in an OS, No program can be executed without _being installed_.  Those who append their own code to Caffe just have a poor programming habit. It is not Caffe's fault that it can be easily modified! OpenCV's code can also be modified easily, but there are obviously fewer people doing like that. And, it seems not a issue of Berkeley Caffe.

(Please raise issues in English)

**Comment by seanbell** [comment]
@PENGUINLIONG I disagree; I think that quite a lot of users will end up modifying their own version of caffe, and there should be good versioning systems to deal with that.  Right now there are none.  If you want a properly-versioned fork of caffe, I would look at NVIDIA's `NVIDIA/caffe` fork.

Either way, installation questions belong on the mailing list, and issues should be in English, so I am closing the issue for now.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

**Comment by KeeganRen** [comment]
I just think we are chinese, so I write Chinese. If the person is English-speaking friends, I will write in English.

**Comment by KeeganRen** [comment]
When I want run rcnn, I will compile a caffe,
When I want run fast-rcnn, I will compile another caffe,
When I want run faster-rcnn, I will compile ...
SSD ...
and so on.
