### ISSUE TITLE
CUDA driver shutting down failure.

### ISSUE THREAD

**Issue by PENGUINLIONG** [BVLC/caffe#4541]
I generated a DLL which helps me interop my MATLAB codes with C#.  But a problem emerged: Once I have finished computation (with the Dispose() method called to release my generated MATLAB object), the application crashes. My application will print these two lines as ending before it goes out of response.

```
F0729 11:47:14.163569  1196 syncedmem.hpp:31] Check failed: error == cudaSuccess (29 vs. 0)  driver shutting down
*** Check failure stack trace: ***
```

I have run the app on two computer with GT 735M and GT 745 respectively (with cuDNN installed). The computation results are perfect but the error kills the entire process, although I have tried using try/catch blocks to capture the exceptions. Which makes it more weird, is the previous versions of DLL generated with no MATLAB code changed DID NOT have such a problem.

**Comment by PENGUINLIONG** [comment]
Okay... I solved this problem by rebuilding the DLL and then the app (I didn't modify the code), but why the previous rebuildings generates invalid app?

**Comment by appyfizzA** [comment]
@PENGUINLIONG how did you rebuild the DLL and the app ? I am using Caffe, and am facing the same problem on a 980 Ti GPU.

**Comment by PENGUINLIONG** [comment]
@appyfizzA It's been two years, and I can barely remember all the details. But it was clear that I didn't change anything (codes, configs...) and the rebuilt app worked properly.
