### ISSUE TITLE
Check failed: registry.count(type) == 1 (0 vs. 1) Unknown layer type: Input (known types: MemoryData)

### ISSUE THREAD

**Issue by orchestor** [BVLC/caffe#4542]
Have working on caffe in my Mac for two day,  failed!!!!

My system info:
ProductName:    Mac OS X
ProductVersion: 10.11.6
BuildVersion:   15G31

>   top: "fc8"
>   inner_product_param {
>     num_output: 1000
>   }
> }
> layer {
>   name: "prob"
>   type: "Softmax"
>   bottom: "fc8"
>   top: "prob"
> }
> I0730 00:35:54.936161 1989984256 layer_factory.hpp:77] Creating layer input
> F0730 00:35:54.936193 1989984256 layer_factory.hpp:81] Check failed: registry.count(type) == 1 (0 vs. 1) Unknown layer type: Input (known types: MemoryData)
> **\* Check failure stack trace: ***
> Abort trap: 
> 
> 6

The only direction I have is here: 
(http://stackoverflow.com/questions/30325108/caffe-layer-creation-failure) , but I don't know how to change makefile, anyone have pointers on this?

thanks

**Comment by osom8979** [comment]
If it static compilation, change it to the shared compilation flags.
