### ISSUE TITLE
Can i use external memory in caffe?

### ISSUE THREAD

**Issue by SoroorM** [BVLC/caffe#4544]
Hi dear
 I have some questions and want to know this software can support all of the Neural Networks, specially LSTM? and Could I implement every kind of specific Networks with it?And also if I want to add external memory, how can I do it?
i really need it for my researches, please guide me.

Thank you for your attention

Best Regards

**Comment by seanbell** [comment]
Please ask questions about how to use caffe on the mailing list, thanks!

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
