### ISSUE TITLE
caffe error when using registry

### ISSUE THREAD

**Issue by caozhangjie** [BVLC/caffe#4545]
I implement a new RBM layer in caffe and I have created the rbm_layer.hpp, rbm_layer.cpp and rbm_layer.cu files. I can use the RBM layer in the C++ interface but when I use the python interface, I encounter a error as follows: 

Check failed: registry.count(type) == 1 (0 vs. 1) Unknown layer type: RBM (known types: AbsVal, Accuracy, ArgMax, BNLL, Concat, ConsineLoss, ContrastiveLoss, Convolution, CosPairLoss, Data, Deconvolution, Dropout, DummyData, Eltwise, Embed, EuclideanLoss, Exp, Filter, Flatten, HDF5Data, HDF5Output, HingeLoss, Im2col, ImageData, InfogainLoss, InnerProduct, InnerProductLoss, LRN, LSTM, LSTMUnit, Log, MMDLoss, MVN, MatrixPairwiseLoss, MemoryData, MultinomialLogisticLoss, PReLU, PairwiseLoss, Pooling, Power, RNN, ReLU, Reduction, Reshape, SPP, Scalar, Sigmoid, SigmoidCrossEntropyLoss, Silence, Slice, Softmax, SoftmaxWithLoss, Softsign, Split, TanH, Threshold, Tile, TransferForm, WindowData)

I'm sure I register the layer in the rbm_layer.cpp as in other .cpp file. So does anyone can help me? I think my RBM layer is like a neuron_layer. So I tried to find all the occurrence of the "TanH", which is also a neuron_layer and add similar code to the corresponding files. But this dosen't work. Thank you for help. My os is centos.

**Comment by austingg** [comment]
have you rebuilt pycaffe after you make c++ interface?
