### ISSUE TITLE
can anyone add mil layer to this repository?

### ISSUE THREAD

**Issue by eriche2016** [BVLC/caffe#4546]
i am currently using mil with caffe, see [mil layer](https://github.com/imisra/caffe-icnm/blob/3c582433fb9d23925530e2465f3ce2abf47313cf/include/caffe/common_layers.hpp#L501), however, i find that you have dismantled common_layers.hpp. So i cannot use it directly. Can any one add this layer to this repository.

**Comment by eriche2016** [comment]
Problem solved.

**Comment by BruceJing2017** [comment]
How did you solve it? I have the same issue...

**Comment by eriche2016** [comment]
here is the link https://github.com/eriche2016/caffe

**Comment by BruceJing2017** [comment]
Thanks

**Comment by lunaliu1001** [comment]
Hi, I am very new to caffe. Could you please give me some idea of how can I use the MIL layer, like what is the input and parameter, and how can I make it into a common caffe layer with {}? Thank you!
