### ISSUE TITLE
problems I encounter when “sudo make runtest”

### ISSUE THREAD

**Issue by dachenxiaoai** [BVLC/caffe#4548]
“sudo make all”
“sudo make test”

The above two steps is OK！ 
But “sudo make runtest”, returns the following error!
I was hoping everyone could help me. 
Many thanks !!!!!!

zz@zz:~/work/caffe-opencl$ sudo make runtest
[sudo] password for zz:
.build_release/tools/caffe
caffe: command line brew
usage: caffe <command> <args>

commands:
  train           train or finetune a model
  test            score a model
  device_query    show GPU diagnostic information
  time            benchmark model execution time  autotune        autotune a model

  Flags from tools/caffe.cpp:
    -gpu (Optional; run in GPU mode on given device IDs separated by ','.Use
      '-gpu all' to run on all available GPUs. The effective training batch
      size is multiplied by the number of devices.) type: string default: ""
    -iterations (The number of iterations to run.) type: int32 default: 50
    -level (Optional; network level.) type: int32 default: 0
    -model (The model definition protocol buffer text file.) type: string
      default: ""
    -phase (Optional; network phase (TRAIN or TEST). Only used for 'time'.)
      type: string default: ""
    -sighup_effect (Optional; action to take when a SIGHUP signal is received:
      snapshot, stop or none.) type: string default: "snapshot"
    -sigint_effect (Optional; action to take when a SIGINT signal is received:
      snapshot, stop or none.) type: string default: "stop"
    -snapshot (Optional; the snapshot solver state to resume training.)
      type: string default: ""
    -solver (The solver definition protocol buffer text file.) type: string
      default: ""
    -stage (Optional; network stages (not to be confused with phase), separated
      by ','.) type: string default: ""
    -weights (Optional; the pretrained weights to initialize finetuning,
      separated by ','. Cannot be set simultaneously with snapshot.)
      type: string default: ""
.build_release/test/test_all.testbin 0 --gtest_shuffle
Setting to use device 0
terminate called after throwing an instance of 'OCLRT::xcb_error'
  what():  XCB ERROR: X session is not running!
*** Aborted at 1470188799 (unix time) try "date -d @1470188799" if you are using GNU date ***
PC: @     0x2b6bcf2adcc9 (unknown)
*** SIGABRT (@0x7d73) received by PID 32115 (TID 0x2b6bcc3d9c40) from PID 32115; stack trace: ***
    @     0x2b6bcf069340 (unknown)
    @     0x2b6bcf2adcc9 (unknown)
    @     0x2b6bcf2b10d8 (unknown)
    @     0x2b6bcdfa46b5 (unknown)
    @     0x2b6bcdfa2836 (unknown)
    @     0x2b6bcdfa2863 (unknown)
    @     0x2b6bcdfa2aa2 (unknown)
    @     0x2b6be31628b8 (unknown)
    @     0x2b6be315ec57 (unknown)
    @     0x2b6be3104447 (unknown)
    @     0x2b6be30ef7db (unknown)
    @     0x2b6be2067c94 (unknown)
    @     0x2b6be20469f0 (unknown)
    @     0x2b6bce24a77e (unknown)
    @     0x2b6bce24c6cf (unknown)
    @     0x2b6bcf066a90 __GI___pthread_once
    @     0x2b6bce24ad21 (unknown)
    @     0x2b6bce7d7a5e viennacl::ocl::get_platforms()
    @     0x2b6bce7d613e caffe::Caffe::SetDevices()
    @           0x471292 main
    @     0x2b6bcf298ec5 (unknown)
    @           0x47b9b9 (unknown)
make: *** [runtest] Aborted (core dumped)

**Comment by shelhamer** [comment]
Please ask installation questions on the mailing list. If you're having trouble, you might want to try the Caffe [Dockerfile](https://github.com/BVLC/caffe/tree/master/docker) to take care of installation for you.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

**Comment by AlexandreBriot** [comment]
Hi dachenxiaoai !
I got the exact same error as you.
Did you manage to fix it ?
Thanks in advance 
Alex
