### ISSUE TITLE
Python tool for generating popular networks

### ISSUE THREAD

**Issue by jay-mahadeokar** [BVLC/caffe#4551]
Hello,
Wanted to point you to [pynetbuilder](https://github.com/jay-mahadeokar/pynetbuilder), a modular tool to programmatically generate / stitch together caffe networks, with modules for popular classification and detection networks.  Currently it includes legos for residual networks, VGG, inception v1, squeezenet and SSD object detection.

Quick start guides to generate [residual networks](https://github.com/jay-mahadeokar/pynetbuilder/tree/master/models/imagenet) and SSD [based detection](https://github.com/jay-mahadeokar/pynetbuilder/tree/master/models/voc2007_ssd) networks are available.

Do you think something like this could be useful for caffe community in general and become part of pycaffe? If so, I would be glad to work on a PR, collaborate with interested people.

Any feedback is welcome.
Thanks!

**Comment by shelhamer** [comment]
Thanks for sharing your work, but please do so on the mailing list or the wiki, not on the issue tracker.
