### ISSUE TITLE
Please update install instructions for (K)ubuntu 

### ISSUE THREAD

**Issue by JDJoe** [BVLC/caffe#4554]
libblas and some other stuff is required. Please add:  

`sudo apt-get install libblas-dev libatlas-base-dev`

Also, there is no libhdf5.so with that name so link must be created: 

```
cd /usr/lib/x86_64-linux-gnu/
ln -s libhdf5_serial.so.10 libhdf5.so
ln -s libhdf5_serial_hl.so.10 libhdf5_hl.so
```

update your Makefile and add:

` /usr/include/hdf5/serial/`

to INCLUDE_DIRS += ...

**Comment by zwets** [comment]
@JDJoe: _Never_ manually create symlinks in system directories. On Ubuntu as on most unixy systems, everything below `/usr` except `/usr/local` is managed by the package manager. Changing things there is bound to break things. Putting a development library in the system library path certainly will.

If you must, you could create the symlink in `/usr/local/lib`. However, the proper way is not to change your system but to fix the build configuration (else how would it work on anyone else's system?):

    INCLUDE_DIRS := $(PYTHON_INCLUDE) /usr/local/include /usr/include/hdf5/serial
    LIBRARY_DIRS := $(PYTHON_LIB) /usr/local/lib /usr/lib /usr/lib/x86_64-linux-gnu/hdf5/serial

**Comment by shelhamer** [comment]
Please ask installation questions on the mailing list. If you're having trouble, you might want to try the Caffe [Dockerfile](https://github.com/BVLC/caffe/tree/master/docker) to take care of installation for you.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
