### ISSUE TITLE
make: ***[.build_release/src/caffe/syncedmem.0] error

### ISSUE THREAD

**Issue by kiseungjung** [BVLC/caffe#4556]
Hello everyone,
I need your helps.
I have problem when I tried installing about TX1 in ubuntu.
make: ***[.build_release/src/caffe/syncedmem.0] error
This error makes me crazy please help [me...

**Comment by shelhamer** [comment]
Please ask installation questions on the mailing list.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
