### ISSUE TITLE
Caffe compile error: undefined reference to `google::protobuf

### ISSUE THREAD

**Issue by kkog** [BVLC/caffe#4558]
I am trying to compile Caffe on my ubuntu 16.04. I have successfully installed several times before, but it failed this time for some reason returning the below error messages. I have tried every solution I found in the web corresponding to this issue, nothing worked unfortunately. Any help would be appreciated.

$ make all
CXX/LD -o .build_release/tools/upgrade_net_proto_text.bin
/usr/bin/ld: warning: libprotobuf.so.9, needed by .build_release/lib/libcaffe.so, not found (try using -rpath or -rpath-link)
.build_release/lib/libcaffe.so: undefined reference to `google::protobuf::internal::WireFormatLite::ReadString(google::protobuf::io::CodedInputStream*, std::string*)'
.build_release/lib/libcaffe.so: undefined reference to`google::base::CheckOpMessageBuilder::NewString()'
.build_release/lib/libcaffe.so: undefined reference to `google::protobuf::io::CodedInputStream::ReadVarint64Fallback(unsigned long*)'
.build_release/lib/libcaffe.so: undefined reference to`google::protobuf::io::CodedInputStream::ReadTagFallback()'
.build_release/lib/libcaffe.so: undefined reference to `cv::imread(std::string const&, int)'
.build_release/lib/libcaffe.so: undefined reference to`google::protobuf::io::CodedInputStream::ReadVarint32Fallback(unsigned int_)'
.build_release/lib/libcaffe.so: undefined reference to `google::protobuf::internal::GeneratedMessageReflection::GeneratedMessageReflection(google::protobuf::Descriptor const_, google::protobuf::Message const_, int const_, int, int, int, google::protobuf::DescriptorPool const_, google::protobuf::MessageFactory_, int)'
.build_release/lib/libcaffe.so: undefined reference to `google::protobuf::internal::StringTypeHandlerBase::Delete(std::string*)'
.build_release/lib/libcaffe.so: undefined reference to`leveldb::DB::Open(leveldb::Options const&, std::string const&, leveldb::DB*_)'
.build_release/lib/libcaffe.so: undefined reference to `cv::imencode(std::string const&, cv::_InputArray const&, std::vector<unsigned char, std::allocator<unsigned char> >&, std::vector<int, std::allocator<int> > const&)'
.build_release/lib/libcaffe.so: undefined reference to`google::protobuf::internal::StringTypeHandlerBase::New()'
.build_release/lib/libcaffe.so: undefined reference to `google::protobuf::io::CodedOutputStream::WriteVarint32(unsigned int)'
.build_release/lib/libcaffe.so: undefined reference to`google::protobuf::UnknownFieldSet::UnknownFieldSet()'
.build_release/lib/libcaffe.so: undefined reference to `google::protobuf::Message::~Message()'
.build_release/lib/libcaffe.so: undefined reference to`google::protobuf::internal::RepeatedPtrFieldBase::Swap(google::protobuf::internal::RepeatedPtrFieldBase_)'
.build_release/lib/libcaffe.so: undefined reference to `google::protobuf::UnknownFieldSet::~UnknownFieldSet()'
.build_release/lib/libcaffe.so: undefined reference to`leveldb::Status::ToString() const'
.build_release/lib/libcaffe.so: undefined reference to `google::protobuf::io::CodedOutputStream::WriteVarint32FallbackToArray(unsigned int, unsigned char_)'
collect2: error: ld returned 1 exit status
Makefile:616: recipe for target '.build_release/tools/upgrade_net_proto_text.bin' failed
make: *_\* [.build_release/tools/upgrade_net_proto_text.bin] Error 1

**Comment by ShoyhongYau** [comment]
I just came across absolutely the same problem and felt helpless. It's just the first time for me to install caffe.

**Comment by djebm2** [comment]
It's the 1.58 version of boost that seems not being supported by caffe so far. I am trying to compile it with the 1.55 version.

**Comment by bybabo92** [comment]
have one get the answer?

**Comment by diggerdu** [comment]
Remove protobuf-compiler
Compile protobuf 2.5 from source

**Comment by shelhamer** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

**Comment by andrewjong** [comment]
There is no clear answer for this question in the caffe-users list.
