### ISSUE TITLE
"Make all" error

### ISSUE THREAD

**Issue by bond992** [BVLC/caffe#4564]
Hi!
  I have installed all prerequsites for Caffe, created Makefile.config and added extra lines in Makefile.config and Makefile to solve problems with hdf5. However, when I execute "make all" I still get an error that says this:
  CXX src/caffe/test/test_hdf5data_layer.cpp
src/caffe/test/test_hdf5data_layer.cpp:4:18: fatal error: hdf5.h: There is no such file or directory
compilation terminated.
Makefile:574: recipe for target '.build_release/src/caffe/test/test_hdf5data_layer.o' failed
make: *** [.build_release/src/caffe/test/test_hdf5data_layer.o] Error 1

  How could I solve that?

**Comment by zwets** [comment]
The hdf5 headers are located in `/usr/include/hdf5/serial` (Ubuntu, libhdf5-dev version 1.8.16). The fix is to add that directory to the `INCLUDE_DIRS` directive in `Makefile.config`, so it becomes:

    INCLUDE_DIRS := $(PYTHON_INCLUDE) /usr/local/include /usr/include/hdf5/serial

I suggest this change be added to `Makefile.config.example` in `master`.

**Comment by shelhamer** [comment]
Please ask installation questions on the mailing list. If you're having trouble, you might want to try the Caffe [Dockerfile](https://github.com/BVLC/caffe/tree/master/docker) to take care of installation for you.

Note that the alternative path you suggest is indicated in a comment in the Makefile.config.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
