### ISSUE TITLE
“make error”

### ISSUE THREAD

**Issue by gailysun** [BVLC/caffe#4565]
Hi, I have installed all the Prerequisites and change the Makefile.config for OpenBLAS and python_lib path and Python_include. When I run "make all",  the error appears as following:
/usr/bin/g++ src/caffe/blob.cpp -pthread -fPIC -DNDEBUG -O2 -I/usr/local/include -I./src -I./include -I/usr/local/cuda/include -I/include -c -o build/src/caffe/blob.o
In file included from ./include/caffe/blob.hpp:6:0,
                 from src/caffe/blob.cpp:6:
./include/caffe/common.hpp:13:21: fatal error: mkl_vsl.h: No such file or directory
 #include <mkl_vsl.h>
Could anyone give me help?
Thank you very much.

**Comment by shelhamer** [comment]
Please ask installation questions on the mailing list. If you're having trouble, you might want to try the Caffe [Dockerfile](https://github.com/BVLC/caffe/tree/master/docker) to take care of installation for you.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
