### ISSUE TITLE
ImportError, libcaffe.so.1.0.0-rc3: undefined symbol: undefined symbol: _ZN5caffe5LayerIfE7ReshapeERKSt6vectorIPNS_4BlobIfEESaIS5_EES9_

### ISSUE THREAD

**Issue by sunformoon** [BVLC/caffe#4568]
Hi, I wrote a new layer. The compilation looks fine but when I imported the caffe, it came out the error: undefined symbol: _ZN5caffe5LayerIfE7ReshapeERKSt6vectorIPNS_4BlobIfEESaIS5_EES9_. Does anyone know about the _ZN5caffe5Layer clues?

Platform: 
CUDA 7.5, GTX TITAN, Python 2.7

**Comment by shelhamer** [comment]
Please ask installation questions on the mailing list. If you're having trouble, you might want to try the Caffe [Dockerfile](https://github.com/BVLC/caffe/tree/master/docker) to take care of installation for you.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

**Comment by xiao1228** [comment]
@sunformoon hi did you fix the problem? I am getting the same issue. Thanks
