### ISSUE TITLE
About opencl kernels

### ISSUE THREAD

**Issue by kris-hu** [BVLC/caffe#4569]
@naibaf7 

Hi,
I'm debugging the caffe-opencl now, using spatial convolution. And I'm not familiar with the source code for the moment.
Here is my question: how can I see the ocl kernels (kernel body)? 
For example, I stepped into  function _ConvolutionLayerSpatial<float>::convolve()_, after this line
_viennacl::ocl::kernel &kernel = program.get_kernel(config->kernelName);_
I could only got a kernel name from _kernel_: U11_11_3_1_4_4_1_227_227_50_1_96_2_2_5_1_SIMD16
I need more info about this kernel (the full kernel body, for instance), could you help on it?
And is the kernel generated from the template?

Best regards,
Kris

**Comment by naibaf7** [comment]
@kris-hu 
Intel's spatial kernels are developed by Intel.
I only know that the kernel source is based on these files:
https://github.com/BVLC/caffe/blob/opencl/src/caffe/greentea/cl_kernels/conv_layer_spatial.cl
https://github.com/BVLC/caffe/blob/opencl/src/caffe/greentea/cl_kernels/conv_spatial_helper.cl

Otherwise, also check out what the output is on Line 145 (sources) in this file:
https://github.com/BVLC/caffe/blob/opencl/src/caffe/greentea/cl_kernels.cpp

If that doesn't help, maybe @gongzg (from Intel) can help you out here.

**Comment by kris-hu** [comment]
@naibaf7   @gongzg

In the page https://github.com/BVLC/caffe/tree/opencl, it says:
**The spatial domain convolution kernel supports all OpenCL platforms now.**
Does it means that the spatial conv kernel can be used on other cards (not Intel)?

In file https://github.com/BVLC/caffe/blob/opencl/src/caffe/greentea/cl_kernels/conv_layer_spatial.cl, 
there's a function call _intel_sub_group_shuffle()_ in kernel _convolve_simd16()_ which seems Intel only. Can this function be called by other platforms?

Regards,
Kris

**Comment by naibaf7** [comment]
@kris-hu 
Yes the kernels work on other platforms, BUT the performance will not be optimal. The autotuned version of these kernels relies on the intel_sub_group_shuffle() in kernel convolve_simd16() functions, which are Intel only.

For AMD and nVidia chip I'd recommend the LibDNN kernels. Those are faster for high-end GPUs. On beignet/Intel GPUs, the Intel spatial kernels are currently the best performing.

Regards

Fabian

**Comment by kris-hu** [comment]
@naibaf7 
I'm confused, do you mean other platforms can also call these functions that are Intel only?

Currently I'm researching the CNN performance on our own card that supports OpenCL, so my focus is the optimization of OpenCL implementation. Hope the spatial convolution kernel could work on our card.

Thanks very much for your help!

Kris

**Comment by gongzg** [comment]
@naibaf7 I agree that spatial domain engine is for Intel. Other platform should use libDNN. As to the spatial domain engine itself. @kris-hu The subgroup extension is Intel only so other platform will not enter this code path. Other platform will use other type of kernels to do the auto-tuning. It should work. But will not get good performance.

**Comment by gongzg** [comment]
@kris-hu The performance number in the clcaffe wiki page is for batch size 128. actually, When batch size is equal or larger than 32, it will get about the same performance number. If batch size is less than 32, the performance will be lower.

**Comment by kris-hu** [comment]
@gongzg 
Got it, thank you very much!
