### ISSUE TITLE
Ubuntu16.04 "make all" CXX/LD compile error

### ISSUE THREAD

**Issue by ShoyhongYau** [BVLC/caffe#4572]
Ubuntu 16.04 with caffe 7.5 installed. (I have successfully run tensorflow)
I have all things already but I can't make it.
CXX and NVCC compilation both works at first.

When it comes here in the Terminal, the last line "CXX/LD -o...",
- CXX examples/siamese/convert_mnist_siamese_data.cpp
- AR -o .build_release/lib/libcaffe.a
- LD -o .build_release/lib/libcaffe.so.1.0.0-rc3
- CXX/LD -o .build_release/tools/upgrade_solver_proto_text.bin

an error comes out as,
- collect2: error: ld returned 1 exit status
- Makefile:617: recipe for target '.build_release/tools/upgrade_net_proto_binary.bin' failed
- make: *** [.build_release/tools/upgrade_net_proto_binary.bin] Error 1

I found that some guys just came across this before but no one gave a solution, so I just get frustrated orz.

**Comment by shelhamer** [comment]
Please ask installation questions on the mailing list. If you're having trouble, you might want to try the Caffe [Dockerfile](https://github.com/BVLC/caffe/tree/master/docker) to take care of installation for you.

CUDA 8 is required on Ubuntu 16.04.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
