### ISSUE TITLE
install caffe in windows 7 with vs 2013 cannot find "hdf5.h" when build "test_all" item

### ISSUE THREAD

**Issue by wandering007** [BVLC/caffe#4573]
Errors as follows:
    
```
    1>  test_hdf5data_layer.cpp
    1>..\..\src\caffe\test\test_hdf5data_layer.cpp(4): fatal error C1083: Cannot open include file: 'hdf5.h': No such file or directory
    1>  test_hdf5_output_layer.cpp
    1>D:\Program Files\caffe\include\caffe/layers/hdf5_output_layer.hpp(4): fatal error C1083: Cannot open include file: 'hdf5.h': No such file or directory (..\..\src\caffe\test\test_hdf5_output_layer.cpp)
```

The weird thing is that when I build "caffe" item, it can locate `hdf5.h` in `hdf5_data_layer.hpp`  and `hdf5_output_layer.cpp`(lies in `D:\Program Files\caffe\include\caffe\layers`). 

I have to replace `#include "hdf5.h"` with absolute path `include "D:\Program Files\NugetPackages\hdf5-v120-complete.1.8.15.2\lib\native\include\hdf5.h"` in `test_hdf5data_layer.cpp` and  `test_hdf5_output_layer.cpp` (lie in directory `D:\Program Files\caffe\src\caffe\test`) to avoid errors.
Or manually add `D:\Program Files\NugetPackages\hdf5-v120-complete.1.8.15.2\lib\native\include` to `include libraries`.
Why that happens? I am so confused.  Needing help, Thanks!

**Comment by shelhamer** [comment]
Please ask installation questions on the mailing list. If you're having trouble, you might want to try the Caffe [Dockerfile](https://github.com/BVLC/caffe/tree/master/docker) to take care of installation for you.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
