### ISSUE TITLE
Error on Centos with caffe 0.15 install "error: ‘UINT8_MAX’ was not declared in this scope"

### ISSUE THREAD

**Issue by GeorgeStorm** [BVLC/caffe#4580]
Hi,
As above, trying to install caffe 0.15 in order to go through the kitti detection tutorial and getting this error with the caffe/src/caffe/layers/detectnet_transform_layer.cpp file.

Was following this guide:
https://gist.github.com/lukeyeager/ba948f1d56e4ab407874

Which worked for the default branch of caffe but not this one.
Any ideas?

Thanks

**Comment by xxw345** [comment]
Hi @GeorgeStorm , did you fix this issue? I also got same error with V0.15.

**Comment by lukeyeager** [comment]
This is a question for [NVIDIA/caffe](https://github.com/NVIDIA/caffe).

**Comment by GeorgeStorm** [comment]
Sorry I did ask it over there as well:
https://github.com/NVIDIA/caffe/issues/207
