### ISSUE TITLE
SQL with caffe as a data layer?

### ISSUE THREAD

**Issue by TuringsEgo** [BVLC/caffe#4587]
Does this exist anywhere? This would be extremely useful for what I am doing.

**Comment by wadefelix** [comment]
Export SQL data to LMDB, withPython.

**Comment by faust1706** [comment]
That is what we are doing now, but it is essentially adding a middle man, causing a major slow down.

**Comment by shelhamer** [comment]
Closing as better handled by a Python data layer, as it could interface with SQL, turn the data into arrays, and then output through the top(s).
