### ISSUE TITLE
[libprotobuf ERROR \text_format.cc:274] Error parsing text-format caffe.SolverParameter

### ISSUE THREAD

**Issue by githubzpp123** [BVLC/caffe#4588]
I use protoc.exe compile *.prototxt file, give me this error, could anyone know what's the problem?

**Comment by shelhamer** [comment]
Please ask usage questions on the mailing list. prototxt do not need compilation—`protoc` is for compiling the .proto schema.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
