### ISSUE TITLE
Allow num_output" as 

### ISSUE THREAD

**Issue by inferrna** [BVLC/caffe#4597]
As for now impossible to use num_output=xxx for RNN and LSTM layers, unlike  other layers supporting this parameter.
recurrent_param=dict(num_output=xxx) does thing, but it seems non obvious and non standard. Since this bug still present, it seems that no one using recurrent layers in caffe at this time (through NetSpec() at least) - it would be nice to see any simple example in ipynb format.

**Comment by shelhamer** [comment]
The situation is the same for any layer that shares parameters, like the `convolution_param` shared by the `Convolution` and `Deconvolution` layer. If the layer `type` does not match the proto param name, it needs to be explicitly passed as in your example `recurrent_param=(num_output=xxx)`. This is working as expected.

See #3954 for discussion.
