### ISSUE TITLE
Boost build issue (sp_counted_impl_pda)

### ISSUE THREAD

**Issue by usptact** [BVLC/caffe#461]
/opt/local/include/boost/smart_ptr/detail/sp_counted_impl.hpp:231:48: error: 
      'sp_counted_impl_pda' does not refer to a type name in pseudo-destructor expression;
      expected the name of type 'sp_counted_impl_pda<P, D, A>'
this->detail::sp_counted_impl_pda< P, D, A> ::~sp_counted_impl_pda();

Running Mac OS X 10.9.3 with Boost version 1.55

**Comment by atique81** [comment]
Hi junwang4,

I am encoutering the same problem of "Import Error: no module named google.protobuf" while trying to run this python script (http://nbviewer.ipython.org/github/BVLC/caffe/blob/master/examples/filter_visualization.ipynb) for feature extraction. However - 

1. I have installed protobuf-2.5.0, but I don't know where it has been installed.
2. After installing it, do I nedd to build caffe again?

I would highly appreciate if you kindly reply

**Comment by waelHamdan** [comment]
@atique81

I have the same problem now, did you solve it?

**Comment by anguyen8** [comment]
@waelHamdan : this solved this issue for me `sudo pip install protobuf`.
