### ISSUE TITLE
caffe compilation error (on make all step) "[.build_release/lib/libcaffe.so.1.0.0-rc3] Error 1"

### ISSUE THREAD

**Issue by pasindubawantha** [BVLC/caffe#4610]
this is what i get 

`user@computer:~/path/to/caffee/git/clone/files$ make all`

`LD -o .build_release/lib/libcaffe.so.1.0.0-rc3
/usr/bin/ld: /lib/atlas-3-10-3/lib/libcblas.a(cblas_dgemm.o): relocation R_X86_64_32 against``.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC
/lib/atlas-3-10-3/lib/libcblas.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
Makefile:563: recipe for target '.build_release/lib/libcaffe.so.1.0.0-rc3' failed
make: *** [.build_release/lib/libcaffe.so.1.0.0-rc3] Error 1`

after building atlas i copied all atlas build files to `/lib/atlas-3-10-3/`
and made the changes to **Makefile.config** as

BLAS_INCLUDE := /lib/atlas-3-10-3/include
BLAS_LIB := /lib/atlas-3-10-3/lib

please help

**Comment by EmpireofQin** [comment]
i got exactly the same error!
```
/usr/bin/ld: /usr/local/lib/libcblas.a(cblas_sgemv.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libcblas.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
make[2]: *** [lib/libcaffe-d.so.1.0.0-rc3] Error 1
make[1]: *** [src/caffe/CMakeFiles/caffe.dir/all] Error 2
make: *** [all] Error 2
```
i have libcblas.a and libcblas.so in /usr/lib.

**Comment by EmpireofQin** [comment]
i have solved this problem. hope it can help u. see[#4802](https://github.com/BVLC/caffe/issues/4802)

**Comment by shelhamer** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
