### ISSUE TITLE
Windows Branch - Creates a MEX with Malfunctioning Solve (Windows 7 64 Bit, VS 2013, MATLAB R2016a)

### ISSUE THREAD

**Issue by RoyiAvital** [BVLC/caffe#4613]
Hello,
I created MEX file from the Windows Branch (Only MATLAB Support, no CUDA / CudCNN).
It created a MEX file which can do all but "Solve" and "Solver" (It crashes).

Since the network works in Command Line I think the MEX has some issue.

To replicate it, use this:

https://groups.google.com/forum/#!topic/caffe-users/Wc8J2hlXLCA

Thank You.

**Comment by RoyiAvital** [comment]
It seems that the MATLAB Mex requires absolute path to the Solver .prototxt file and not the relative path (Relative to the Script Running it).

**Comment by RoyiAvital** [comment]
@shelhamer , Why did you close?
Do you know for a fact it works now?

**Comment by shelhamer** [comment]
No, I don't but given other windows branch usage and the continued efforts of the windows branch lead @willyd I expect it might now. If not, re-open the issue.
