### ISSUE TITLE
Why does my loss stay fixed while doing semantic segmentation?

### ISSUE THREAD

**Issue by liuwenling** [BVLC/caffe#4617]
I'm really sorry to post a personal problem here agian. The caffe users groups is not active enough and can't help me solve this. (One of them says he/she faced the same problem).
My purpose is very simple: the do semantic segmentation without python layer, just use data layers which take lmdb as input.
I made the lmdb for my images and groud truths, and both of them with --gray, which means they are one-channel images. And the ground truths, the gray level is strictly {0,1,2,3,4,5} (I used {0,16,32,48,64,80} before, but to avoid problems I changed them.)
I modifed the voc-fcn32s, I changed the python layer to two data layers, both of them will read imgs from lmdb. One for raw image, and one for ground truths. And of course the label of output to 6.
I'm really confused that, the loss always stays fixed. And experimentally, I set the scale of my ground truth data layer to 255, the loss finally start to "change"! I don't know why. But by furthur research, I just found the loss of each image stays fix. (Because my batch_size is one so I found this).
I think some process of my train must be wrong, or maybe I miss understand all the process of doing semantic segmentation.
Is there anybody who wants to discuss this with me?

Please check on google group:
https://groups.google.com/forum/#!topic/caffe-users/iO8iDRhj2SM
https://groups.google.com/forum/#!topic/caffe-users/EDpMKALlBT4

**Comment by shelhamer** [comment]
Please ask usage questions on the mailing list, and continue your threads there.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
