### ISSUE TITLE
fast-r-cnn: caffe.LayerParameter" has no field named "roi_pooling_param

### ISSUE THREAD

**Issue by hana9090** [BVLC/caffe#4619]
When I tried to run ./tools/demo.py of [fast-r-cnn][1]. working on UBUNTU 16.04
I got the following error, although the caffe is successfully installed!!

> ./tools/demo.py

 

    WARNING: Logging before InitGoogleLogging() is written to STDERR
    W0823 14:12:46.105280  4444 _caffe.cpp:122] DEPRECATION WARNING - deprecated use of Python interface
    W0823 14:12:46.105316  4444 _caffe.cpp:123] Use this instead (with the named "weights" parameter):
    W0823 14:12:46.105319  4444 _caffe.cpp:125] Net('/home/hana/Documents/try/fast-rcnn-master/models/VGG16/test.prototxt', 1, weights='/home/hana/Documents/try/fast-rcnn-master/data/fast_rcnn_models/vgg16_fast_rcnn_iter_40000.caffemodel')
    [libprotobuf ERROR google/protobuf/text_format.cc:274] Error parsing text-format caffe.NetParameter: 392:21: Message type "caffe.LayerParameter" has no field named "roi_pooling_param".
    F0823 14:12:46.106595  4444 upgrade_proto.cpp:79] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: /home/hana/Documents/try/fast-rcnn-master/models/VGG16/test.prototxt
    *** Check failure stack trace: ***
    Aborted (core dumped)

Please any help?

  [1]: https://github.com/rbgirshick/fast-rcnn

**Comment by pythonnewer** [comment]
hello friend：
        
      I have the same confusion . I'd like to ask that have you solved it?

**Comment by shelhamer** [comment]
Please ask usage questions on the mailing list and refer to the py-faster-rcnn project. It requires you to compile its own Caffe branch with its own layers.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
