### ISSUE TITLE
#define duplication between CMakeLists and caffe_config.h

### ISSUE THREAD

**Issue by intelfx** [BVLC/caffe#4625]
While refactoring the buildsystem I've noticed that several `USE_xxx` definitions are duplicated in `caffe_config.h` (via `#cmakedefine`) and in CMake code (via `add_definitions()` or equivalent).

What is the reason for this? Is it on purpose? I can't see any reason because the `caffe_config.h` file is not exported to library clients and not used in the alternative Makefile buildsystem.

Furthermore, the `add_definitions()` calls in CMakeLists cannot be removed because the definitions (at least some of them) need to be exported to library clients (hence, BTW, the TODO at [cmake/Dependencies.cmake:66](https://github.com/BVLC/caffe/blob/master/cmake/Dependencies.cmake#L66) is incorrect). So I propose that duplicated and unused definitions in `caffe_config.h` are removed instead.

I am implementing this in PR #4609.

**Comment by intelfx** [comment]
Alternatively, we may move all `add_definitions()` calls to #cmakedefines in `caffe_config.h.in`, probably splitting that file in two (for private and public definitions) and then installing the public part and including it from all public headers. However, this is more complicated.

**Comment by shelhamer** [comment]
Closed by #4609
