### ISSUE TITLE
Latest caffe master and v0.15

### ISSUE THREAD

**Issue by lasandcris** [BVLC/caffe#4627]
I successfully merged the latest caffe master with the Windows branch but I noticed that v.015 caffe branch is different - are there plans merging them in the future? There are also layers (such as rnn) that are not included in v.015 and vice versa. 

thanks 
_laszlo

**Comment by shelhamer** [comment]
I don't know what fork you're referring to (perhaps NVcaffe?), but this issue tracker is for BVLC/caffe:master. The windows branch is now regularly maintained by @willyd and tracks master.
