### ISSUE TITLE
Both Cmake and Make fail on 'make runtest'

### ISSUE THREAD

**Issue by skolouri** [BVLC/caffe#4628]
Hi, 

I am using Ubuntu 14.04, Python 2.7, NVIDIA Driver 367, Cuda-8.0, CudNN-5.0, GTX-1080, and I am trying to install Caffe on my system. I am currently using Tensorflow on my system with no issues. I have installed all prerequisites as advised by http://caffe.berkeleyvision.org and I believe I have chosen the right configuration (including library paths, etc.). The initial stage,

make all
make test 

runs with no error or warning. Then at 'make runtest' I get the following error

make: execvp: .build_release/tools/caffe permission denied

OK I thought this is simply a permission issue and ran it with 'sudo make runtest' and got the exact same error. I also used 'sudo su -' and ran 'make runtest' as root and the same problem persists. 

Then I tried to use cmake to build Caffe and similarly 

make all
make install

run with no warnings or errors but when I run 'make runtest' I get: 

[100%] Built target proto
[100%] Built target caffe
[100%] Built target gtest
[100%] Built target test.testbin
/bin/sh: 1: /media/MainStorage/caffe-master/build/test/test.testbin: Permission denied
make[3]: *** [src/caffe/test/CMakeFiles/runtest] Error 126
make[2]: *** [src/caffe/test/CMakeFiles/runtest.dir/all] Error 2
make[1]: *** [src/caffe/test/CMakeFiles/runtest.dir/rule] Error 2
make: *** [runtest] Error 2

Running it as root did not fix the issue. I would highly appreciate any input.

**Comment by prabindh** [comment]
Its not clear without the log where it failed. To confirm if testbin is really created, try running it directly from command line as below - `cd /media/MainStorage/caffe-master && /media/MainStorage/caffe-master/build/test/test.testbin --gtest_shuffle` .  Also, make sure you did not install the caffe-master folder with higher privileges. It could also be possible that CUDA is not installed properly. Above step will show the real cause.

**Comment by shelhamer** [comment]
Please ask installation questions on the mailing list. If you're having trouble, you might want to try the Caffe [Dockerfile](https://github.com/BVLC/caffe/tree/master/docker) to take care of installation for you.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
