### ISSUE TITLE
Large GPU RAM consumption

### ISSUE THREAD

**Issue by winstywang** [BVLC/caffe#463]
Hi, all
  I have tried both cuda-convnet and caffe on large imagenet model. It seems that Caffe will consume significantly larger RAM than cuda-convnet, which makes it impossible to train a even larger model (say using stride 2 in the first conv layer). Any idea on this issue?

**Comment by Coderx7** [comment]
@shelhamer : Caffe still takes much more memory compared to e.g torch, did you impelment what you intended to back in 2014? 
Is there yet a way to reduce the memory consumption in caffe ? ( I have a GTX980 with 4GIg vram and yet still I'm not able to train alex net! ) 
Thanks for your attention in advance
