### ISSUE TITLE
caffe for windows build errors

### ISSUE THREAD

**Issue by br2711** [BVLC/caffe#4632]
I get the following errors when I try to build .\windows\Caffe.sln -
error LNK1104: cannot open libcaffe.lib
error C1083: Cannot open include file: 'pyconfig.h': No such file or directory

Any help would be appreciated.
Thanks!

**Comment by DEKHTIARJonathan** [comment]
I also have the same issue ...

**Comment by shelhamer** [comment]
Please ask installation questions on the mailing list. If you're having trouble, you might want to try the Caffe [Dockerfile](https://github.com/BVLC/caffe/tree/master/docker) to take care of installation for you. The error you reported usually means Python or its development libraries are not installed.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
