### ISSUE TITLE
Does Caffe support the negative labels?

### ISSUE THREAD

**Issue by yechaochen** [BVLC/caffe#4633]
I have a dataset and each image in the dataset has two labels. One is negative and another is positive.
I'm not sure whether Caffe support the negetive label or not. I have to change the negative label to the positive.

Can someone help me?

**Comment by shelhamer** [comment]
For classification losses like `SoftmaxWithLossLayer` the labels need to be in `{0, ..., K-1}` where `K` is the number of labels.

Please ask usage questions on the mailing list.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
