### ISSUE TITLE
make all: /usr/bin/ld: cannot find -lhdf5_hl

### ISSUE THREAD

**Issue by dukn** [BVLC/caffe#4635]
`AR -o .build_release/lib/libcaffe.a
LD -o .build_release/lib/libcaffe.so.1.0.0-rc3
/usr/bin/ld: cannot find -lhdf5_hl
/usr/bin/ld: cannot find -lhdf5
collect2: error: ld returned 1 exit status
Makefile:565: recipe for target '.build_release/lib/libcaffe.so.1.0.0-rc3' failed
make: *** [.build_release/lib/libcaffe.so.1.0.0-rc3] Error 1`

https://photos.google.com/share/AF1QipMBV21Irc4Kb5o0GzWFxlryAhGmnY2TlesVhMSt_t53PrwDSQfhpx-xeL3yvXU4Ew?key=alhhTHZIOFVEN2lXcUluT0lQZEE1N3lxTURMUnh3
Help me!

**Comment by sameerkhurana10** [comment]
Can you share the solution.

Facing the same issue.

**Comment by dukn** [comment]
Sorry! I do not know the solution. but I think the problem in my version ubuntu 16:04. I am using theano now.
