### ISSUE TITLE
error 134 when make runtest 

### ISSUE THREAD

**Issue by Zhouyh2016** [BVLC/caffe#4639]
I want to install caffe without GPU，ubuntu 14.04，(using Win10 bash)so I follow this guide：
1.sudo apt-get install libatlas-base-dev
2.sudo apt-get install libprotobuf-dev libleveldb-dev libsnappy-dev libopencv-dev libboost-all-dev libhdf5-serial-dev protobuf-compiler liblmdb-dev libgflags-dev libgoogle-glog-dev liblmdb-dev
3.git clone git://github.com/BVLC/caffe.git
4.install Caffe：
(1)cp Makefile.config.example Makefile.config 
(2)modify Makefile.config ， Uncomment ‘’CPU_ONLY:= 1 ‘’
(3)、$ make all 
(4)、$ make test 
(5)、$ make runtest
but when I make runtest，I met an error：
[----------] 5 tests from DBTest/1, where TypeParam = caffe::TypeLMDB
[ RUN      ] DBTest/1.TestNext
F0827 14:57:23.613095  2730 db_lmdb.hpp:15] Check failed: mdb_status == 0 (8 vs. 0) Exec format error
*** Check failure stack trace: ***
    @     0x7fcd225dbdbd  google::LogMessage::Fail()
    @     0x7fcd225ddc5d  google::LogMessage::SendToLog()
    @     0x7fcd225db9ac  `google::LogMessage::Flush()`
    @     0x7fcd225de57e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fcd206d9db1  caffe::db::LMDB::Open()
    @           0x50892e  caffe::DBTest<>::SetUp()
    @           0x6fa693  testing::internal::HandleExceptionsInMethodIfSupported<>()
    @           0x6f12b0  testing::Test::Run()
    @           0x6f13be  testing::TestInfo::Run()
    @           0x6f14c5  testing::TestCase::Run()
    @           0x6f4808  testing::internal::UnitTestImpl::RunAllTests()
    @           0x6f4a97  testing::UnitTest::Run()
    @           0x459c52  main
    @     0x7fcd1f921f45  (unknown)
    @           0x460e89  (unknown)
Aborted (core dumped)
make: *** [runtest] Error 134

Who can help me？Thanks

**Comment by Zhouyh2016** [comment]
OK, win10 bash cannot support caffe,(sad)

**Comment by howard0su** [comment]
it is problem of LMDB. if you change database backend to leveldb, you should be able to pass.

**Comment by allenmtr** [comment]
@howard0su  how make it in details, step by step. thanks

**Comment by howard0su** [comment]
Disable LMDB in makefile.conf and enable LevelDB. And also CPU only should be reasonable for you as well.

CPU_ONLY := 1
USE_LEVELDB := 1
USE_LMDB := 0

**Comment by allenmtr** [comment]
@howard0su Hi ,thanks, but my errors still existed, did not be solved.  when i make runtest, the error is like below:

*** Aborted at 1477402011 (unix time) try "date -d @1477402011" if you are using GNU date ***
PC: @     0x7f5968553418 gsignal
*** SIGABRT (@0x6840) received by PID 26688 (TID 0x7f596b689ac0) from PID 26688; stack trace: ***
    @     0x7f59688f83d0 (unknown)
    @     0x7f5968553418 gsignal
    @     0x7f596855501a abort
    @     0x7f596a6b8c5b H5check_version
    @     0x7f59692375ed caffe::HDF5DataLayer<>::LoadHDF5FileData()
    @     0x7f5969233157 caffe::HDF5DataLayer<>::LayerSetUp()
    @     0x7f5969319212 caffe::Net<>::Init()
    @     0x7f596931aaa1 caffe::Net<>::Net()
    @     0x7f59692fe75a caffe::Solver<>::InitTrainNet()
    @     0x7f59692ffac7 caffe::Solver<>::Init()
    @     0x7f59692ffe6a caffe::Solver<>::Solver()
    @           0x569594 caffe::SGDSolverTest<>::InitSolver()
    @           0x5671c0 caffe::GradientBasedSolverTest<>::InitSolverFromProtoString()
    @           0x55ac4b caffe::GradientBasedSolverTest<>::RunLeastSquaresSolver()
    @           0x56520d caffe::GradientBasedSolverTest<>::TestSnapshot()
    @           0x566df3 caffe::SGDSolverTest_TestSnapshot_Test<>::TestBody()
    @           0x720283 testing::internal::HandleExceptionsInMethodIfSupported<>()
    @           0x71989a testing::Test::Run()
    @           0x7199e8 testing::TestInfo::Run()
    @           0x719ac5 testing::TestCase::Run()
    @           0x71ad9f testing::internal::UnitTestImpl::RunAllTests()
    @           0x71b0c3 testing::UnitTest::Run()
    @           0x459662 main
    @     0x7f596853e830 __libc_start_main
    @           0x4604e9 _start
    @                0x0 (unknown)
Aborted (core dumped)
Makefile:526: recipe for target 'runtest' failed
make: *** [runtest] Error 134

My  environment: caffe without GPU，ubuntu 16.04,    and i followed this tutorial:   https://github.com/BVLC/caffe/wiki/Ubuntu-16.04-or-15.10-Installation-Guide

thanks again

**Comment by kunsa** [comment]
I face the same problem.
