### ISSUE TITLE
How to convert float data to leveldb?

### ISSUE THREAD

**Issue by thbupt** [BVLC/caffe#464]
In the function ReadImageToDatum, I found it only support for raw image data （uint8）, but I preprocessed the image data， then it became float data.

``` c++
string* datum_string = datum->mutable_data();
  for (int c = 0; c < 3; ++c) {
    for (int h = 0; h < cv_img.rows; ++h) {
      for (int w = 0; w < cv_img.cols; ++w) {
        datum_string->push_back(
            static_cast<char>(cv_img.at<cv::Vec3b>(h, w)[c]));
      }
    }
  }
```

If it was float data, how should I change the code in ReadImageToDatum?

Solved！

**Comment by andoum** [comment]
I have a similar issue, I want to train with float data other than 0-255. Is it possible to have a data layer that reads blobprotos with floats as input without modifying caffe code ? Or is there any other way of doing it ?

Thank you

**Comment by apollo-time** [comment]
@thbupt  I have the same problem. How do you solved your problem?
Please help me. Thanks.

**Comment by apollo-time** [comment]
I convert the float data into Datum with datum.add_float_data(...) function.
Is this Ok?

**Comment by ginobilinie** [comment]
@apollo-time Do you make it by using datum.add_float_data()?
