### ISSUE TITLE
error during ZF training for COCO dataset

### ISSUE THREAD

**Issue by chankim** [BVLC/caffe#4642]
Hello, everyone,

I'm trying to train ZF network with COCO data set in py-faster-rcnn. Because there was no .pt file given in the git, I copied the files from models/pascal_voc/ZF/faster_rcnn_end2end directory. After setting TRAIN.BBOX_REG to 'False', and setting PROPOSAL_METHOD to 'gt',  I'm using the command 
experiments/scripts/faster_rcnn_end2end2.sh 0 ZF coco --set RNG_SEED 42 TRAIN.SCALES "[400,500,600,700]"
But seeing this error below. (the rpn_loss_cls layer is being created twice, I don't know why).
...
I0828 18:15:47.228282 31154 layer_factory.hpp:76] Creating layer rpn_loss_cls
I0828 18:15:47.228324 31154 net.cpp:114] Creating Layer rpn_loss_cls
I0828 18:15:47.228340 31154 net.cpp:481] rpn_loss_cls <- rpn_cls_score_reshape_rpn_cls_score_reshape_0_split_0
I0828 18:15:47.228366 31154 net.cpp:481] rpn_loss_cls <- rpn_labels
I0828 18:15:47.228394 31154 net.cpp:437] rpn_loss_cls -> rpn_cls_loss
I0828 18:15:47.228431 31154 layer_factory.hpp:76] Creating layer rpn_loss_cls
F0828 18:15:47.229197 31154 loss_layer.cpp:25] Check failed: bottom[0]->num() == bottom[1]->num() (2 vs. 1) The data and label should have the same number.
*** Check failure stack trace: ***
experiments/scripts/faster_rcnn_end2end2.sh: line 57: 31154 Aborted                 (core dumped) ./tools/train_net_e2e.py --gpu ${GPU_ID} --solver models/${PT_DIR}/${NET}/faster_rcnn_end2end/solver.prototxt --weights data/imagenet_models/${NET}.v2.caffemodel --imdb ${TRAIN_IMDB} --iters ${ITERS} --cfg experiments/cfgs/faster_rcnn_end2end.yml ${EXTRA_ARGS}

Has any one any idea? Thanks!

**Comment by LiviuMarina** [comment]
Hi chankim,

I am having the same issue.
Did you found a solution?

Thank you!
Liviu.

**Comment by shelhamer** [comment]
Please ask usage questions on the mailing list and refer to the py-faster-fcnn project repo for details.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
