### ISSUE TITLE
malloc segfault

### ISSUE THREAD

**Issue by jeremy-rutman** [BVLC/caffe#4643]
hi
I blv this is a caffe issue.  I do use a python layer to load/distort my images but afaik I cannot cause malloc issues from python.

```
#caffe --version
caffe version 1.0.0-rc3
Debug build (NDEBUG not #defined)

#caffe train -solver solver.prototxt -gpu 1
....
DEBUG:root:batchsize 20 datasize (20, 3, 128, 128) labelsize (20, 1, 128, 128)
I0828 07:01:18.358548 20103 solver.cpp:454] Snapshotting to binary proto file snapshot/minimal_net_iter_50.caffemodel
I0828 07:02:07.409184 20103 sgd_solver.cpp:273] Snapshotting solver state to binary proto file snapshot/minimal_net_iter_50.solverstate
*** Aborted at 1472385727 (unix time) try "date -d @1472385727" if you are using GNU date ***
PC: @     0x7fb267a2a294 caffe::BlobProto::SerializeWithCachedSizesToArray()
*** Error in `caffe': malloc(): memory corruption: 0x000000001e5bb7a0 ***
Segmentation fault (core dumped)
```

**Comment by robonrrd** [comment]
I too have this issue with the latest caffe (running on Ubuntu 14.04. repro with both CUDA 7.5 and 8.0, using a Titan X, both Maxwell and Pascal architectures).  I narrowed it down to the fact that my snapshot would be more than 2,147,483,647 bytes long.
I worked around it by reducing the size of one of my fully-connected layers, which is suboptimal but unblocks me.

**Comment by naibaf7** [comment]
@robonrrd 
You can try to use the OpenCL-Caffe branch. You can compile it with USE_CUDA, disable USE_GREENTEA (disables OpenCL) and enable USE_INDEX64. This will change the addressable sizes beyond 2,147,483,647 bytes in all critical areas.
A word of caution, I don't know to what extent cuDNN and certain BLAS libraries supports this, but it is a viable workaround for those who want to use HUGE networks.

**Comment by shelhamer** [comment]
`malloc` issues in Python are symptomatic of an Ubuntu 14.04 issue that can solved by gperftools as seen in TF discussions:

```
sudo apt-get install google-perftools
export LD_PRELOAD=“/usr/lib/libtcmalloc.so.4”
```
