### ISSUE TITLE
Why caffe::NetStateRule has no member named phase?

### ISSUE THREAD

**Issue by AIROBOTAI** [BVLC/caffe#4644]
Hi all, 

When I added the following code in image_data_layer.cpp:
`if (this->layer_param_.phase() == TEST) { //DO SOMETHING}`
I got the following compiling error:
class google::protobuf::RepeatedPtrField<caffe::NetStateRule>’ has no member named ‘phase'
I'm confused on this error since 'phase' is a defined member of 'NetStateRule' in the caffe.proto. Could anyone please help me solve this problem? Thanks a lot!

**Comment by lukeyeager** [comment]
That's a repeated field

**Comment by AIROBOTAI** [comment]
@lukeyeager Thx for your reply! Another related question: if I use the following code:
`if (this->layer_param_.phase() == TEST) { //DO SOMETHING}`
The compiling error is: 
class google::protobuf::RepeatedPtrFieldcaffe::NetStateRule’ has no member named ‘phase'.
Could you please tell me where is wrong? Thx a lot!

**Comment by AIROBOTAI** [comment]
@lukeyeager I have figured out that's due to some stupid error I made elsewhere. It's supposed to be no problem..
