### ISSUE TITLE
caffe users google group not accessible

### ISSUE THREAD

**Issue by lopho** [BVLC/caffe#4651]
https://groups.google.com/forum/#!forum/caffe-users
is not accessible. Returns the following message:

```
You do not have permission to access this content. (#418)
```

**Comment by belgraviton** [comment]
I have the same issue.

**Comment by mpralat** [comment]
Me too! Do you know if it's permanent? The whole group disappeared from the search tool :<

**Comment by xdtl** [comment]
https://productforums.google.com/forum/#!topic/apps/6P_eHIgih0w

I read from the above link:

"Just heard back from Google Support.  They wrote:

------------------------------------
I understand that you are unable to access groups as you're getting the following error message: ''You do not have permission to access this content (#418)". This is currently an issue on our end and our back end team is working on resolving this issue as soon as possible.

As a workaround, have a group owner/manager visit the group in the Groups web UI and and change any setting for the affected group. For example, you can change the description of the group to something, and then change it back. This will fix that specific group. Engineering will work to fix all groups.
------------------------------------

This seems to have fixed the group in question for us..."

So I really hope the Caffe group manager could help us on this.

**Comment by naibaf7** [comment]
@shelhamer @jeffdonahue 
could one you please take care of this? Not that the Caffe users flood the GIT issues with user questions.

**Comment by shelhamer** [comment]
@xdtl I switched the group description as advised by the workaround. Fingers-crossed that fixes it for you.

@naibaf7 nothing more we can do about it, so I hope it is fixed now, as I agree we don't want all of these questions on the issue tracker.

**Comment by xdtl** [comment]
It works! Thanks so much Evan!

**Comment by lopho** [comment]
Seems to work.
Thanks for taking care of this @shelhamer.
