### ISSUE TITLE
InfogainLoss doesn't support multidimensional labels

### ISSUE THREAD

**Issue by sherifshehata** [BVLC/caffe#4652]
Hello,

I was trying to use InfogainLoss to set weights to the cost during training. My label is Nx1xHxW, which works well with SoftMaxLoss, but it doesn't work with InfogainLoss. I checked "infogain_loss_layer.cpp" and it seems it only supports Nx1x1x1 labels.

**Comment by shelhamer** [comment]
Fixed by #3855 thanks to @shaibagon!
