### ISSUE TITLE
Problem seting up CAFFE with CUDA 8 please help!

### ISSUE THREAD

**Issue by Hidden-dreamz** [BVLC/caffe#4653]
Hi there! 
I have just upgraded to ububtu 16.0.1 and cuda 8 with cudnn 5.1 and driver 367.44. Because i am using gtx 1070. I want to run deep dream on caffe and all the nvidia stuff is in ok except some libuarys for cuda 8, like glu and x11? But i tryed to install those manualy. Now i try to compule caffe and  get this error. Can anyone help please? See picture for error. Sais domething about newer version of protobuf? Please help! Thanks! #
![tmp_5427-20160829_145143884429903](https://cloud.githubusercontent.com/assets/20837487/18053964/cdc5f450-6df9-11e6-8730-7f181d79a372.jpg)

**Comment by npanpaliya** [comment]
Hi @Hidden-dreamz , 
Which version of protobuf compiler are you using? 
-> protoc --version 

Looks like you are compiling using protobuf compiler 3.0 or above. Protoc 2.5 or 2.6 works well.

**Comment by mrgloom** [comment]
If Ubuntu 16.0.1 is not a must, you can get Ubuntu 14.04.
I have tested gtx 1070 with CUDA 8.0, CUDNN 5.1, Driver Version: 367.44.

**Comment by shelhamer** [comment]
Please ask installation questions on the mailing list. If you're having trouble, you might want to try the Caffe [Dockerfile](https://github.com/BVLC/caffe/tree/master/docker) to take care of installation for you.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
