### ISSUE TITLE
Windows Branch Build Failure

### ISSUE THREAD

**Issue by JayTheYggdrasil** [BVLC/caffe#4656]
its giving me an error code the likes of MSB4126 when i try to build ./windows Caffe.sln
I'm attempting this with CPU_ONLY with both useCUDA and UseCuDNN set to false and CPU_ONLY true, i also have python support set to true and i did the steps shown in that section being, 
"conda install --yes numpy scipy matplotlib scikit-image pip
pip install protobuf"
Im on windows 10, using MSBuild Command Prompt for VS2015 i input the following commands
"cd (path to windows folder where Caffe.sln is located)"
"msbuild Caffe.sln"

I'm kind of new at this so im not entirley sure what a lot of this means and its very likley that this is an error on my part but any help would be greatly appreicated. ps i won't be available at the time of posting this until later the next day

**Comment by willyd** [comment]
The README of the Windows branch clearly states that Visual Studio 2103 is a requirements. Visual Studio 2015 is not yet a supported configuration.
