### ISSUE TITLE
error LNK1104: cannot open file 'libboost_thread-vc120-mt-1_61.lib'

### ISSUE THREAD

**Issue by shubhwicked** [BVLC/caffe#4658]
While compiling caffe, i am getting this error. where i have to defined this and from where i can get this lib.

**Comment by shelhamer** [comment]
Please ask installation questions on the mailing list. If you're having trouble, you might want to try the Caffe [Dockerfile](https://github.com/BVLC/caffe/tree/master/docker) to take care of installation for you.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
