### ISSUE TITLE
caffe-windows   python problem

### ISSUE THREAD

**Issue by wdbsf** [BVLC/caffe#4659]
win7 install Anaconda2 64 bit,
I compile caffe branch:windows, support python, 
set environment variable PythonPath is f:\caffe-window\Build\x64\Release\pycaffe\,

open Anaconda prompt, 
<d:\Anaconda2 C:\Users\lx> python

> > > import caffe 
> > >  but long time no response,
> > > what's problem?

**Comment by shelhamer** [comment]
Closing for lack of detail.
