### ISSUE TITLE
Make all error  - undefined reference to `caffe::BlockingQueue

### ISSUE THREAD

**Issue by mpralat** [BVLC/caffe#4661]
Hey there!
I am currently having an issue while installing caffe on my Arch linux. 
Using cmake, I managed to complete configuring and generating, but when trying to execute make all I get an error.
```
./lib/libcaffe.so.1.0.0-rc3: undefined reference to `caffe::BlockingQueue<caffe::Batch<double>*>::pop(std::string const&)'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to `google::base::CheckOpMessageBuilder::NewString()'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to `google::protobuf::internal::NameOfEnum(google::protobuf::EnumDescriptor const*, int)'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to `caffe::BlockingQueue<caffe::Batch<float>*>::pop(std::string const&)'
collect2: error: ld returned 1 exit status
```
I am using CUDA 7.5, Boost 1.60, cuDNN 4.0.7, protobuf 3.0.0, gcc4.4.
I've read that might be a problem with protobuf, but I've tried compiling it from scratch but to no avail.

**Comment by eugenefunny** [comment]
Same problem

**Comment by shelhamer** [comment]
Please ask installation questions on the mailing list. If you're having trouble, you might want to try the Caffe [Dockerfile](https://github.com/BVLC/caffe/tree/master/docker) to take care of installation for you.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

**Comment by eugenefunny** [comment]
I installed caffe with CUDA8 + protobuf2.5 and it works well
