### ISSUE TITLE
Initializing two channels of siamese networks with the same pretrained weights , but without sharing weights during training

### ISSUE THREAD

**Issue by SivaramPrasadMudunuri** [BVLC/caffe#4662]
I was trying to implement the siamese network described in "[Seeing the Forest from the Trees: A Holistic Approach to Near-infrared Heterogeneous Face Recognition, CVPRW 2016](http://www.cv-foundation.org/openaccess/content_cvpr_2016_workshops/w9/papers/Reale_Seeing_the_Forest_CVPR_2016_paper.pdf)". The approach involves initializing the two channels of siamese network with the same pretrained weights of a single channel model. This is pretty straigtforward in caffe when the weights are shared. But I'm looking to implement it in such a way that the weights are not shared (has to learn individually by employing the contrastive loss as mentioned in the above paper, but the initializations on both channels has to be the same). I couldn't find a way to implement it in caffe. 

Any of you have any suggestions for neat approaches or hacks to do this in caffe? 

Thanks in advance.

**Comment by shelhamer** [comment]
Please ask usage questions on the mailing list. You can assign the same weights to two separate branches of a net through net surgery in pycaffe.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
