### ISSUE TITLE
On Mac 10 ,make all  make[2]: *** [src/caffe/CMakeFiles/cuda_compile.dir/layers/cuda_compile_generated_base_data_layer.cu.o] Error 1 make[1]: *** [src/caffe/CMakeFiles/caffe.dir/all] Error 2 make: *** [all] Error 2

### ISSUE THREAD

**Issue by anthonyyuan** [BVLC/caffe#4663]
/System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/Headers/vBasicOps.h(693): error: return value type does not match the function type

/System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/Headers/vBasicOps.h(760): error: argument of type "vUInt32" is incompatible with parameter of type "__m128i"

/System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/Headers/vBasicOps.h(760): error: argument of type "vUInt32" is incompatible with parameter of type "__m128i"

/System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/Headers/vBasicOps.h(760): error: return value type does not match the function type

/System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/Headers/vBasicOps.h(825): error: argument of type "vSInt32" is incompatible with parameter of type "__m128i"

/System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/Headers/vBasicOps.h(825): error: argument of type "vSInt32" is incompatible with parameter of type "__m128i"

/System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/Headers/vBasicOps.h(825): error: return value type does not match the function type

/System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/Headers/vBasicOps.h(925): error: argument of type "vUInt8" is incompatible with parameter of type "__m128i"

/System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/Headers/vBasicOps.h(924): error: argument of type "vUInt32" is incompatible with parameter of type "__m128i"

/System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/Headers/vBasicOps.h(924): error: argument of type "vUInt32" is incompatible with parameter of type "__m128i"

/System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/Headers/vBasicOps.h(924): error: return value type does not match the function type

/System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/Headers/vBasicOps.h(963): error: argument of type "vUInt8" is incompatible with parameter of type "__m128i"

/System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/Headers/vBasicOps.h(924): error: return value type does not match the function type

/System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/Headers/vBasicOps.h(963): error: argument of type "vUInt8" is incompatible with parameter of type "__m128i"

/System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/Headers/vBasicOps.h(347): error: argument of type "vUInt16" is incompatible with parameter of type "__m128i"

/System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/Headers/vBasicOps.h(347): error: argument of type "vUInt16" is incompatible with parameter of type "__m128i"

/System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/Headers/vBasicOps.h(347): error: return value type does not match the function type

/System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/Headers/vBasicOps.h(372): error: argument of type "vSInt16" is incompatible with parameter of type "__m128i"

/System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/Headers/vBasicOps.h(372): error: argument of type "vSInt16" is incompatible with parameter of type "__m128i"

/System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/Headers/vBasicOps.h(372): error: return value type does not match the function type

/System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/Headers/vBasicOps.h(427): error: argument of type "vUInt32" is incompatible with parameter of type "__m128i"

/System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/Headers/vBasicOps.h(427): error: a value of type "__m128i" cannot be assigned to an entity of type "vUInt32"

/System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/Headers/vBasicOps.h(428): error: argument of type "vUInt32" is incompatible with parameter of type "__m128i"

/System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/Headers/vBasicOps.h(428): error: a value of type "__m128i" cannot be assigned to an entity of type "vUInt32"

/System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/Headers/vBasicOps.h(429): error: argument of type "vUInt32" is incompatible with parameter of type "__m128i"

/System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/Headers/vBasicOps.h(429): error: argument of type "vUInt32" is incompatible with parameter of type "__m128i"

/System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/Headers/vBasicOps.h(429): error: return value type does not match the function type

/System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/Headers/vBasicOps.h(454): error: argument of type "vUInt32" is incompatible with parameter of type "__m128i"

/System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/Headers/vBasicOps.h(454): error: argument of type "vUInt32" is incompatible with parameter of type "__m128i"

/System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/Headers/vBasicOps.h(454): error: return value type does not match the function type

/System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/Headers/vBasicOps.h(623): error: argument of type "vUInt32" is incompatible with parameter of type "__m128i"

/System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/Headers/vBasicOps.h(623): error: argument of type "vUInt32" is incompatible with parameter of type "__m128i"

/System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/Headers/vBasicOps.h(623): error: return value type does not match the function type

/System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/Headers/vBasicOps.h(693): error: argument of type "vSInt32" is incompatible with parameter of type "__m128i"

/System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/Headers/vBasicOps.h(693): error: argument of type "vSInt32" is incompatible with parameter of type "__m128i"

/System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/Headers/vBasicOps.h(693): error: return value type does not match the function type

/System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/Headers/vBasicOps.h(760): error: argument of type "vUInt32" is incompatible with parameter of type "__m128i"

/System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/Headers/vBasicOps.h(760): error: argument of type "vUInt32" is incompatible with parameter of type "__m128i"

/System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/Headers/vBasicOps.h(760): error: return value type does not match the function type

/System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/Headers/vBasicOps.h(825): error: argument of type "vSInt32" is incompatible with parameter of type "__m128i"

/System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/Headers/vBasicOps.h(825): error: argument of type "vSInt32" is incompatible with parameter of type "__m128i"

/System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/Headers/vBasicOps.h(825): error: return value type does not match the function type

/System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/Headers/vBasicOps.h(925): error: argument of type "vUInt8" is incompatible with parameter of type "__m128i"

/System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/Headers/vBasicOps.h(962): error: argument of type "vUInt32" is incompatible with parameter of type "__m128i"

/System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/Headers/vBasicOps.h(924): error: argument of type "vUInt32" is incompatible with parameter of type "__m128i"

/System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/Headers/vBasicOps.h(962): error: argument of type "vUInt32" is incompatible with parameter of type "__m128i"

/System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/Headers/vBasicOps.h(962): error: return value type does not match the function type

/System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/Headers/vBasicOps.h(924): error: return value type does not match the function type

/System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/Headers/vBasicOps.h(963): error: argument of type "vUInt8" is incompatible with parameter of type "__m128i"

/System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/Headers/vBasicOps.h(962): error: return value type does not match the function type

/System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/Headers/vBasicOps.h(962): error: argument of type "vUInt32" is incompatible with parameter of type "__m128i"

/System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/Headers/vBasicOps.h(962): error: return value type does not match the function type

/usr/include/dispatch/object.h(143): error: expected an identifier

/usr/include/dispatch/object.h(362): error: identifier "dispatch_block_t" is undefined

/usr/include/dispatch/object.h(143): error: expected an identifier

/usr/include/dispatch/object.h(362): error: identifier "dispatch_block_t" is undefined

/usr/include/dispatch/object.h(143): error: expected an identifier

/usr/include/dispatch/object.h(362): error: identifier "dispatch_block_t" is undefined

/System/Library/Frameworks/CoreFoundation.framework/Headers/CFBundle.h(148): error: format argument does not have string type

/System/Library/Frameworks/CoreFoundation.framework/Headers/CFBundle.h(148): error: format argument does not have string type

/usr/include/dispatch/object.h(143): error: expected an identifier

/usr/include/dispatch/object.h(362): error: identifier "dispatch_block_t" is undefined

/usr/include/dispatch/object.h(143): error: expected an identifier

/usr/include/dispatch/object.h(362): error: identifier "dispatch_block_t" is undefined

/System/Library/Frameworks/CoreFoundation.framework/Headers/CFBundle.h(148): error: format argument does not have string type

/usr/include/dispatch/object.h(143): error: expected an identifier

/usr/include/dispatch/object.h(362): error: identifier "dispatch_block_t" is undefined

/usr/include/dispatch/object.h(143): error: expected an identifier

/usr/include/dispatch/object.h(362): error: identifier "dispatch_block_t" is undefined

/usr/include/dispatch/object.h(143): error: expected an identifier

/usr/include/dispatch/object.h(362): error: identifier "dispatch_block_t" is undefined

/System/Library/Frameworks/CoreFoundation.framework/Headers/CFBundle.h(148): error: format argument does not have string type

/System/Library/Frameworks/CoreFoundation.framework/Headers/CFBundle.h(148): error: format argument does not have string type

/System/Library/Frameworks/CoreFoundation.framework/Headers/CFBundle.h(148): error: format argument does not have string type

/System/Library/Frameworks/CoreFoundation.framework/Headers/CFBundle.h(148): error: format argument does not have string type

/System/Library/Frameworks/CoreFoundation.framework/Headers/CFBundle.h(148): error: format argument does not have string type

37 errors detected in the compilation of "/var/folders/nj/zxfjzp2153ld3q1y7tpf3qgh0000gn/T//tmpxft_00000d5d_00000000-7_absval_layer.cpp1.ii".
37 errors detected in the compilation of "/var/folders/nj/zxfjzp2153ld3q1y7tpf3qgh0000gn/T//tmpxft_00000d6a_00000000-7_contrastive_loss_layer.cpp1.ii".
37 errors detected in the compilation of "/var/folders/nj/zxfjzp2153ld3q1y7tpf3qgh0000gn/T//tmpxft_00000d66_00000000-7_concat_layer.cpp1.ii".
CMake Error at cuda_compile_generated_absval_layer.cu.o.Release.cmake:267 (message):
  Error generating file
  /Users/anthonyyuan/desktop/src/caffe-master/src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_absval_layer.cu.o

make[2]: *** [src/caffe/CMakeFiles/cuda_compile.dir/layers/cuda_compile_generated_absval_layer.cu.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMake Error at cuda_compile_generated_contrastive_loss_layer.cu.o.Release.cmake:267 (message):
  Error generating file
  /Users/anthonyyuan/desktop/src/caffe-master/src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_contrastive_loss_layer.cu.o

make[2]: *** [src/caffe/CMakeFiles/cuda_compile.dir/layers/cuda_compile_generated_contrastive_loss_layer.cu.o] Error 1
37 errors detected in the compilation of "/var/folders/nj/zxfjzp2153ld3q1y7tpf3qgh0000gn/T//tmpxft_00000d81_00000000-7_bnll_layer.cpp1.ii".
CMake Error at cuda_compile_generated_concat_layer.cu.o.Release.cmake:267 (message):
  Error generating file
  /Users/anthonyyuan/desktop/src/caffe-master/src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_concat_layer.cu.o

make[2]: *** [src/caffe/CMakeFiles/cuda_compile.dir/layers/cuda_compile_generated_concat_layer.cu.o] Error 1
37 errors detected in the compilation of "/var/folders/nj/zxfjzp2153ld3q1y7tpf3qgh0000gn/T//tmpxft_00000d7d_00000000-7_bias_layer.cpp1.ii".
CMake Error at cuda_compile_generated_bnll_layer.cu.o.Release.cmake:267 (message):
  Error generating file
  /Users/anthonyyuan/desktop/src/caffe-master/src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_bnll_layer.cu.o

make[2]: *** [src/caffe/CMakeFiles/cuda_compile.dir/layers/cuda_compile_generated_bnll_layer.cu.o] Error 1
37 errors detected in the compilation of "/var/folders/nj/zxfjzp2153ld3q1y7tpf3qgh0000gn/T//tmpxft_00000d76_00000000-7_batch_norm_layer.cpp1.ii".
37 errors detected in the compilation of "/var/folders/nj/zxfjzp2153ld3q1y7tpf3qgh0000gn/T//tmpxft_00000d8f_00000000-7_batch_reindex_layer.cpp1.ii".
37 errors detected in the compilation of "/var/folders/nj/zxfjzp2153ld3q1y7tpf3qgh0000gn/T//tmpxft_00000d90_00000000-7_base_data_layer.cpp1.ii".
CMake Error at cuda_compile_generated_bias_layer.cu.o.Release.cmake:267 (message):
  Error generating file
  /Users/anthonyyuan/desktop/src/caffe-master/src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_bias_layer.cu.o

make[2]: *** [src/caffe/CMakeFiles/cuda_compile.dir/layers/cuda_compile_generated_bias_layer.cu.o] Error 1
CMake Error at cuda_compile_generated_batch_norm_layer.cu.o.Release.cmake:267 (message):
  Error generating file
  /Users/anthonyyuan/desktop/src/caffe-master/src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_batch_norm_layer.cu.o

make[2]: *** [src/caffe/CMakeFiles/cuda_compile.dir/layers/cuda_compile_generated_batch_norm_layer.cu.o] Error 1
CMake Error at cuda_compile_generated_batch_reindex_layer.cu.o.Release.cmake:267 (message):
  Error generating file
  /Users/anthonyyuan/desktop/src/caffe-master/src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_batch_reindex_layer.cu.o

make[2]: *** [src/caffe/CMakeFiles/cuda_compile.dir/layers/cuda_compile_generated_batch_reindex_layer.cu.o] Error 1
CMake Error at cuda_compile_generated_base_data_layer.cu.o.Release.cmake:267 (message):
  Error generating file
  /Users/anthonyyuan/desktop/src/caffe-master/src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_base_data_layer.cu.o

make[2]: *** [src/caffe/CMakeFiles/cuda_compile.dir/layers/cuda_compile_generated_base_data_layer.cu.o] Error 1
make[1]: *** [src/caffe/CMakeFiles/caffe.dir/all] Error 2
make: *** [all] Error 2

**Comment by shelhamer** [comment]
Please ask installation questions on the mailing list. If you're having trouble, you might want to try the Caffe [Dockerfile](https://github.com/BVLC/caffe/tree/master/docker) to take care of installation for you. (I have personally had better luck on OS X with the Makefile build than CMake.)

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

**Comment by hlzz** [comment]
I have the same issue.
