### ISSUE TITLE
Pycaffe and matplotlib Issue 

### ISSUE THREAD

**Issue by wzleong** [BVLC/caffe#4664]
Would like to know is there any problem of using pycaffe and python matplotlib together? 
Because I have facing the problem as shown below when my python interface (which imports both pycaffe and matplotlib). The error persists whenever I import both modules if I solely "import caffe" then I will not get the following problem. I am using python 2.7.11+ (as indicated by python -V)

![matplotlib_caffe](https://cloud.githubusercontent.com/assets/20381221/18127094/e2029078-6fb0-11e6-8641-8ac61569941c.png)

**Comment by shelhamer** [comment]
No, there is no general incompatibility between pycaffe and matplotlib. In fact many of our bundled examples make use of both.

Please ask questions about installation and compatibility on our mailing list.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
