### ISSUE TITLE
Deploy a trained model 

### ISSUE THREAD

**Issue by JordanPeltier** [BVLC/caffe#4665]
Hi everyone, 

We we want to deploy a CNN according to this page : https://github.com/BVLC/caffe/wiki/Using-a-Trained-Network:-Deploy, what about the preprocessing done in the  transform_param during training and testing ? Can we keep it in the deploy net ? Something like that : 

```
input: "data"
input_shape {
  dim: 1 # batchsize
  dim: 3 # number of colour channels - rgb
  dim: 32 # width
  dim: 32 # height
}
 transform_param {
    scale: 0.00390625
  }

```

Thanks

**Comment by shelhamer** [comment]
No, `Input` layers do not handle pre-processing. You have to do it yourself in the deployment code.
