### ISSUE TITLE
cannot addpath caffe/matlab/+caffe

### ISSUE THREAD

**Issue by zw88** [BVLC/caffe#4666]
make matcaffe success.
make mattest success.
run classification_demo success.
But when I use caffe matlab interface in another project, I addpath '$path_to_caffe/matlab', I get issue "Undefined function or variable 'caffe'"! I found out that matlab cannot add /matlab/+caffe into search path. 
Then I used "ln -sf $CAFFE_ROOT/caffe/matlab/+caffe $CAFFE_ROOT/caffe/matlab/caffe" to create a symlink but cannot solve this problem. Can someone help?

**Comment by musicrainie** [comment]
Maybe just caffe/matlab is ok.

**Comment by mickeyli09** [comment]
@zw88 Hi, I have the same problem. Did you solve this problem? I need your help, thanks!

**Comment by zw88** [comment]
just addpath /caffepath/matlab is OK

2016-12-30 19:57 GMT+08:00 mickeyli09 <notifications@github.com>:
