### ISSUE TITLE
Problems with CPU-ONLY

### ISSUE THREAD

**Issue by CSJDeveloper** [BVLC/caffe#4667]
After finishing all the steps, finally i run the demo.py under tools/,
Instead I get thsi problem:
...
faster-rcnn/tools/../lib/fast_rcnn/nms_wrapper.py", line 10, in <module>
    from nms.cpu_nms import cpu_nms
ImportError: No module named cpu_nms

I did everything correctly..
Any help will be appreciate

**Comment by npanpaliya** [comment]
Could you give little more details about the problem and steps you did?

**Comment by mojovski** [comment]
same here. 
On my laptop with Ubuntu 14 everything ran ok (GPU disabled).
On my desktop however with Ubuntu 15 I receive the same error.

What is this module? Are the some details about it?

Thank you very much in advance!

**Comment by shelhamer** [comment]
Please ask issues about forks at the fork and not here. This issue tracker is for BVLC/caffe.

**Comment by jasonlee27** [comment]
Hi @CSJDeveloper 
I had a same issue and I solved it by checking the owner and group to use files in nms and nms directory. For me my ownership of cpu_nms was not for me, and I add me in owner and group and it works.
