### ISSUE TITLE
potential bug: about sharing parameter between layers

### ISSUE THREAD

**Issue by Kai-46** [BVLC/caffe#4668]
Hey guys! Recently, I've been reading caffe source codes. I got one question about the function 'AppendParam' in file 'net.cpp'. This function will detect whether a layer's parameter is shared from another layer's parameter.  There are two lines of code which get pointers of two blobs. **this_blob** is  a parameter which is shared from another layer's **owner_blob**. 
 **Blob<Dtype>\* this_blob = layers_[layer_id]->blobs()[param_id].get();
 Blob<Dtype>\* owner_blob = layers_[owner_layer_id]->blobs()[owner_param_id].get();**
The function then use these two pointers to check the shape of the two blobs. My question is that this function seems to lack the code to really let two layers share the same parameter blobs. Should there be another code line like:
**layers_[layer_id]->blobs()[param_id].reset(owner_blob);**
?
I would appreciate it very much if anyone can help.

**Comment by Noiredd** [comment]
This function only makes some safety checks. The actual sharing happens a little later: `Net::Init` first calls `Net::AppendParam` for every layer, and finally calls `Net::ShareWeights` which actually performs the exchange.
