### ISSUE TITLE
Can lmdb writing or reading program be faster?

### ISSUE THREAD

**Issue by yzldw333** [BVLC/caffe#4672]
I am now helping someone implementing lmdb writing and reading program, I found that only few CPU resource was being used, when I use multi-threading tec, I met some problems like dead-locking.  I wish u can give me some advice.

**Comment by shelhamer** [comment]
Sorry, but this is more of an LMDB question than Caffe issue.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
