### ISSUE TITLE
gist id

### ISSUE THREAD

**Issue by George19890617** [BVLC/caffe#4676]
i have no idea about gist id, for example if I want to download vgg 16 pertained model, how to input in the command line? like, usage: download_model_from_gist.sh <gist_id> <dirname>
what is a gist id, how do i get it ?

**Comment by shelhamer** [comment]
Please ask usage questions on the mailing list. The gist ID is the `username/hash` part of a `gist.github.com` url like https://gist.github.com/ksimonyan/211839e770f7b538e2d8.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
