### ISSUE TITLE
EmbedLatest Test failure

### ISSUE THREAD

**Issue by spandanagella** [BVLC/caffe#4678]
I was able run make all and make test. When I run make runtest EmbedLayer test cases failed with this error message. Any idea what could the issue be?

[----------] 5 tests from EmbedLayerTest/0, where TypeParam = caffe::FloatCPU
[ RUN      ] EmbedLayerTest/0.TestForwardWithBias
[       OK ] EmbedLayerTest/0.TestForwardWithBias (0 ms)
[ RUN      ] EmbedLayerTest/0.TestGradient
F0902 16:52:25.853350 57966 embed_layer.cpp:88] Check failed: !propagate_down[0] Can't backpropagate to EmbedLayer input.
**\* Check failure stack trace: ***
    @     0x2afaab92adaa  (unknown)
    @     0x2afaab92ace4  (unknown)
    @     0x2afaab92a6e6  (unknown)
    @     0x2afaab92d687  (unknown)
    @     0x2afaad2e5bcc  caffe::EmbedLayer<>::Backward_cpu()
    @           0x45570a  caffe::GradientChecker<>::CheckGradientSingle()
    @           0x455aeb  caffe::GradientChecker<>::CheckGradientExhaustive()
    @           0x6a3a8d  caffe::EmbedLayerTest_TestGradient_Test<>::TestBody()
    @           0x73a393  testing::internal::HandleExceptionsInMethodIfSupported<>()
    @           0x730fd7  testing::Test::Run()
    @           0x73107e  testing::TestInfo::Run()
    @           0x731185  testing::TestCase::Run()
    @           0x7344c8  testing::internal::UnitTestImpl::RunAllTests()
    @           0x734757  testing::UnitTest::Run()
    @           0x4474ca  main
    @     0x2afaadd63ec5  (unknown)
    @           0x44ca39  (unknown)
    @              (nil)  (unknown)
make: **\* [runtest] Aborted (core dumped)

**Comment by getengqing** [comment]
I have got the problem, do you have solver it?

**Comment by itallow** [comment]
*bump*

**Comment by spandanagella** [comment]
If you are running into similar problem while building a model make sure you enable back propagation for your inputs.

If you just have one bottom layer

setting propogate_down:0  should make it work.

layer {
 type: “Embed”
 bottom: "words"
 top: "embed"
 propagate_down: 0
 embed_param {
 input_dim: 8000
 num_output: 500
 }
}
