### ISSUE TITLE
Crash with cv::resize() and OpenCL

### ISSUE THREAD

**Issue by SajjadB** [BVLC/caffe#4680]
Hi. I compile caffe and hav not any warning  , but in make runtest i have this problem
anyone can help ?
Nvidia GTX 1070
Cuda-8.0
ubuntu 16.04.1
.
.
[ RUN      ] ImageDataLayerTest/0.TestShuffle
[       OK ] ImageDataLayerTest/0.TestShuffle (61 ms)
[ RUN      ] ImageDataLayerTest/0.TestSpace
[       OK ] ImageDataLayerTest/0.TestSpace (21 ms)
[ RUN      ] ImageDataLayerTest/0.TestResize
*** Aborted at 1472932722 (unix time) try "date -d @1472932722" if you are using GNU date ***
PC: @     0x7f79eb212d84 __GI___pthread_mutex_lock
*** SIGSEGV (@0x3038) received by PID 10525 (TID 0x7f79f497c740) from PID 12344; stack trace: ***
    @     0x7f79eb21a3d0 (unknown)
    @     0x7f79eb212d84 __GI___pthread_mutex_lock
    @     0x7f79c27add98 (unknown)
    @     0x7f79c2863c41 (unknown)
    @     0x7f79c2863db5 (unknown)
    @     0x7f79c27b3ad4 (unknown)
    @     0x7f79c27b5327 (unknown)
    @     0x7f79c27894f6 (unknown)
    @     0x7f79c2688d7d (unknown)
    @     0x7f79c2688d18 (unknown)
    @     0x7f79d0142022 (unknown)
    @     0x7f79d0143d42 (unknown)
    @     0x7f79d01434d0 clGetPlatformIDs
    @     0x7f79ee8b98d5 (anonymous namespace)::opencl_fn3<>::switch_fn()
    @     0x7f79ee99ceea cv::ocl::haveOpenCL()
    @     0x7f79ee9ac288 cv::ocl::useOpenCL()
    @     0x7f79ece56a6c cv::resize()
    @     0x7f79ebaffb47 caffe::ReadImageToCVMat()
    @     0x7f79ebb8f12e caffe::ImageDataLayer<>::DataLayerSetUp()
    @     0x7f79ebbaa203 caffe::BasePrefetchingDataLayer<>::LayerSetUp()
    @           0x48ab2f caffe::Layer<>::SetUp()
    @           0x707fe7 caffe::ImageDataLayerTest_TestResize_Test<>::TestBody()
    @           0x917183 testing::internal::HandleExceptionsInMethodIfSupported<>()
    @           0x91079a testing::Test::Run()
    @           0x9108e8 testing::TestInfo::Run()
    @           0x9109c5 testing::TestCase::Run()
    @           0x911c9f testing::internal::UnitTestImpl::RunAllTests()
    @           0x911fc3 testing::UnitTest::Run()
    @           0x46d47d main
    @     0x7f79eae60830 __libc_start_main
    @           0x474ee9 _start
    @                0x0 (unknown)
Makefile:526: recipe for target 'runtest' failed
make: *** [runtest] Segmentation fault (core dumped)

**Comment by stephenlombardi** [comment]
I think this is an OpenCV or OpenCL issue. Try setting the following environment variable to null: OPENCV_OPENCL_RUNTIME=

**Comment by shelhamer** [comment]
Agreed, this is not a core Caffe issue but a problem with OpenCV GPU usage.

**Comment by TheTazza** [comment]
I get exactly the same error when trying to run caffe, but running the core OpenCV tests gives no problems. Has this issue been resolved?

**Comment by jarvis-huang** [comment]
Setting **OPENCV_OPENCL_RUNTIME=** solves the problem for me.
Thanks to @stephenlombardi 
Just curious why this is.
