### ISSUE TITLE
noisy label-cnn

### ISSUE THREAD

**Issue by Zellar209** [BVLC/caffe#4682]
When I build noisy label-master in the subdirectory ./external/caffe-mydev "make all", I encountered the mistake like this:
src/caffe/common.cpp:5:17: fatal error: mpi.h: No such file or directory
 #include <mpi.h>
                 ^
compilation terminated.
make: **\* [.build_release/src/caffe/common.o] Error 1
make: **\* Waiting for unfinished jobs....
In file included from src/caffe/util/mpi_job_queue.cpp:5:0:
./include/caffe/util/mpi_templates.hpp:5:17: fatal error: mpi.h: No such file or directory
 #include "mpi.h"
                 ^
compilation terminated.
make: **\* [.build_release/src/caffe/util/mpi_job_queue.o] Error 1

Here, I must illustrate that I installed the openmpi in /etc/openmpi, I don't know how I can do next.

**Comment by shelhamer** [comment]
Issues are for BVLC/caffe:master. Please ask questions about a fork at the fork instead of upstream.
