### ISSUE TITLE
Can caffe reshape a input data for unequal height and width, such as 200*100

### ISSUE THREAD

**Issue by terminats17** [BVLC/caffe#4683]
So far, what I have realized is that caffe should reshape the input image for the equal height and width, can caffe train a input image of unequal height and width? such as 200x100

**Comment by shelhamer** [comment]
Please ask usage questions on the mailing list. Inputs and kernels do not need to have equal dimensions in Caffe, so an input size of 200 x 100 is fine.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
