### ISSUE TITLE
float vector labels in data layer

### ISSUE THREAD

**Issue by esason** [BVLC/caffe#4684]
hi,
I am trying to create an lmdb database which each example is composed from an image and a float vector label.
- the set of images i am working on is very big so I have to use an efficent database.
- I have seen that Datum object has a field called float_data which has a repeated modifer . I wonder if I store the labels there.

- how should I implement it?
thx

**Comment by shelhamer** [comment]
Please ask usage questions on the mailing list.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
