### ISSUE TITLE
how to merge caffe with own lstm?

### ISSUE THREAD

**Issue by liuliuqiu** [BVLC/caffe#4685]
I want to merge github the new caffe, but I not kown how to build the new caffe?

**Comment by shelhamer** [comment]
Please ask installation questions on the mailing list. You can always download the latest version of Caffe by `git clone git@github.com:BVLC/caffe.git`. Refer to the [installation instructions](http://caffe.berkeleyvision.org/installation.html) for how to build.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
