### ISSUE TITLE
pycaffe build issue with visual studio

### ISSUE THREAD

**Issue by madshi** [BVLC/caffe#4689]
For some reason, the MSVC++ build process fails to copy the "proto" folder and the "_caffe.pyd" files to the right folder. Doing that manually fixed all problems for me. Just thought I'd give you a heads-up on this issue.

**Comment by gitxdf** [comment]
When I build libcaffe with VS2013, my problem is ".\windows\libcaffe\libcaffe.vcxproj(379,5): error : This project references NuGet package(s) that are missing on this computer. Enable NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\..\..\NugetPackages\OpenCV.2.4.10\build\native\OpenCV.props."
Do you know how fix it? Thx

**Comment by willyd** [comment]
Closing. If the issue still persists with the CMake build please reopen.
