### ISSUE TITLE
Why is the magnitude of XavierFiller hard-coded

### ISSUE THREAD

**Issue by cuihenggang** [BVLC/caffe#4690]
Hello,

I find that the XavierFiller is hard-coded with a magnitude of 3.0

https://github.com/BVLC/caffe/blob/master/include/caffe/filler.hpp#L160
Dtype scale = sqrt(Dtype(3) / n);

While I find using different magnitude values for the XavierFiller can sometimes improve convergence speed (or even converged validation accuracy), having this value hard-coded makes it hard to change it.

So shall we make it a filler param?

Thank you!
Cui

**Comment by shelhamer** [comment]
The `xavier` initialization follows the paper referenced in the source comments. It might be confusing to diverge from the equation from the paper, so it seems reasonable to keep it as it is. Compare the `msra` for a similar but distinct filler that may or may not work better for your use case.
