### ISSUE TITLE
running caffe example gives glog related build errors

### ISSUE THREAD

**Issue by AdritaBarari** [BVLC/caffe#4696]
Hi, I am a complete beginner in caffe. I am using caffe with C++ on Visual Studio 2013 in CPU_ONLY mode and have been able to successfully  build the Caffe solution. Next, I am trying to run an example from the examples provided (classification.cpp). So I have created a new project testClassification and have copy pasted the classification.cpp file there.
When I run the program I get the following errors related to google logs
`Error	3	error LNK2019: unresolved external symbol "__declspec(dllimport) public: __thiscall google::base::CheckOpMessageBuilder::CheckOpMessageBuilder(char const *)" (__imp_??0CheckOpMessageBuilder@base@google@@QAE@PBD@Z) referenced in function "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > * __cdecl google::MakeCheckOpString<int,int>(int const &,int const &,char const *)" (??$MakeCheckOpString@HH@google@@YAPAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@ABH0PBD@Z)	D:\MyExperimentalWorkspace\VSS2013\Projects\testingCaffe\testingCaffe\testClassificationExample.obj	testingCaffe
`
What might be the issue here?
What I observe is that unlike other packages (boost_date_time, gflags etc),  glog.0.3.3.0 package does not have a dll or a lib. In the glog package folder, I find just these files and folders - build, glog.03.3.0.nupkg,  NuGet-Overlay.cmd. Even within the build folder I can just find the header files, logging.h, raw_logging.h (within the include), but I do not find any dlls/libs.   I have included these in the project properties but I still get the errors. 

I would like to know 1. How to resolve these errors
2. How to turn off the logs

Awaiting a response. Thanks in advance.

**Comment by shelhamer** [comment]
Please ask compilation and installation questions on the mailing list. You might try the Caffe [Dockerfile](https://github.com/BVLC/caffe/tree/master/docker) if you are having trouble.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
