### ISSUE TITLE
Practical tutorial how to implement Deep Compression for a network in Caffe

### ISSUE THREAD

**Issue by kamadforge** [BVLC/caffe#4697]
Is there any practical (step by step) tutorial how to speed up the network in Caffe in a way similar to the paper on the Deep Compresion or the alike. There is an issue [#4294](https://github.com/BVLC/caffe/pull/4294) that touches on pruning by means of using a sparse layer but I am not sure about the details (e.g. prototxt sample) how to use it. Also, here is a link on [quantization](https://petewarden.com/2016/05/03/how-to-quantize-neural-networks-with-tensorflow/) with TensorFlow. Is it possible to do it in Caffe, as well?

**Comment by shelhamer** [comment]
There is not currently a bundled tutorial on how to do model compression, though there are several options. Please ask modeling and usage questions on the mailing list.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

**Comment by yiakwy** [comment]
This is a great direction where we can contribute to !!!
