### ISSUE TITLE
gpu_util.cuh  __longlong_as_double undefined

### ISSUE THREAD

**Issue by xwg031459** [BVLC/caffe#4698]
./include/caffe/util/gpu_util.cuh(12): error: no instance of overloaded function "atomicAdd" matches the argument list argument types are: (float *, const float)

./include/caffe/util/gpu_util.cuh(28): error: identifier "__longlong_as_double" is undefined

./include/caffe/util/gpu_util.cuh(28): error: identifier "__double_as_longlong" is undefined

./include/caffe/util/gpu_util.cuh(30): error: identifier "__longlong_as_double" is undefined

**Comment by shelhamer** [comment]
Please ask installation and compilation issues on the mailing list. Include the OS version and details on dependencies.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
