### ISSUE TITLE
installation CAFFE on my CPU (NO gpu) and Ubuntu – 14.04 and Python 2.7.6

### ISSUE THREAD

**Issue by ShibaPrasad** [BVLC/caffe#4707]
Hi,

I am trying to install caffe on my CPU (NO gpu) and Ubuntu – 14.04 and Python 2.7.6.

I am getting below error

/caffe$ make pycaffe
CXX/LD -o python/caffe/_caffe.so python/caffe/_caffe.cpp
/usr/bin/ld: /usr/local/lib/libpython2.7.a(abstract.o): relocation R_X86_64_32S against `_Py_NotImplementedStruct' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libpython2.7.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
make: *** [python/caffe/_caffe.so] Error 1

I just followed the steps at : http://sunshineatnoon.github.io/How-to-install-caffe/

Please help me on this. I am totally stuck on my work.

**Comment by ShibaPrasad** [comment]
Hi ALL,
Cuurently i am getting below error while executing "make all" command - on my above "CPU (NO gpu) and Ubuntu – 14.04 and Python 2.7". PLease somebody help on this. I am stuck on my work.

AR -o .build_release/lib/libcaffe.a
LD -o .build_release/lib/libcaffe.so.1.0.0-rc3
CXX tools/upgrade_net_proto_binary.cpp
CXX/LD -o .build_release/tools/upgrade_net_proto_binary.bin
.build_release/lib/libcaffe.so: undefined reference to `cv::imread(cv::String const&, int)'
.build_release/lib/libcaffe.so: undefined reference to `cv::imencode(cv::String const&, cv::_InputArray const&, std::vector<unsigned char, std::allocator<unsigned char> >&, std::vector<int, std::allocator<int> > const&)'
.build_release/lib/libcaffe.so: undefined reference to `cv::imdecode(cv::_InputArray const&, int)'
collect2: error: ld returned 1 exit status
make: *** [.build_release/tools/upgrade_net_proto_binary.bin] Error 1
shiba@shiba:~/caffe$

**Comment by shelhamer** [comment]
Please ask compilation and installation questions on the mailing list. You might try the Caffe [Dockerfile](https://github.com/BVLC/caffe/tree/master/docker) if you are having trouble.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

**Comment by ShibaPrasad** [comment]
For my above problem - I just typed: 
                sudo ln -s "/usr/lib/x86_64-linux-gnu/libpython2.7.so.1" "/usr/lib/libpython2.7.so"
as given on this link: http://stackoverflow.com/questions/22990769/libpython-error-while-building-youcompleteme

Opened >> Python prompt >> "Import caffe"   
i Trained LeNet on MNIST dataset  with Caffe
