### ISSUE TITLE
failed to make runtest on El Capitan

### ISSUE THREAD

**Issue by popoko2** [BVLC/caffe#4709]
When I tried to install the latest caffe, I got following errors.
What's wrong?
At first, I brewed the protobuf from source according to the installation instructions. Result was same. 

bash-3.2$ make runtest
make runtest
.build_release/tools/caffe
[libprotobuf ERROR google/protobuf/descriptor_database.cc:57] File already exists in database: caffe.proto
[libprotobuf FATAL google/protobuf/descriptor.cc:1164] CHECK failed: generated_database_->Add(encoded_file_descriptor, size): 
libc++abi.dylib: terminating with uncaught exception of type google::protobuf::FatalException: CHECK failed: generated_database_->Add(encoded_file_descriptor, size): 
make: *** [runtest] Abort trap: 6

bash-3.2$ brew info protobuf
brew info protobuf
protobuf: stable 3.0.2 (bottled), HEAD
Protocol buffers (Google's data interchange format)
https://github.com/google/protobuf/
/usr/local/Cellar/protobuf/3.0.2 (250 files, 15.8M) *
  Poured from bottle on 2016-09-11 at 06:51:18

**Comment by shelhamer** [comment]
Please ask installation questions on the mailing list. You might try the Caffe [Dockerfile](https://github.com/BVLC/caffe/tree/master/docker) if you are having trouble.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

**Comment by popoko2** [comment]
Thank you for your advice.
I'll do so.
