### ISSUE TITLE
Caffe make all issue on ubuntu 16.04

### ISSUE THREAD

**Issue by balajithoshkahna** [BVLC/caffe#4714]
Hi all,
I am running ubuntu 16.04. I tried the installation approach of https://github.com/BVLC/caffe/wiki/Ubuntu-16.04-or-15.10-Installation-Guide for installing caffe. The " make all " step fails with the following error.
CXX/LD -o .build_release/tools/extract_features.bin
.build_release/tools/extract_features.o: In function `std::string* google::MakeCheckOpString<int, int>(int const&, int const&, char const*)':
extract_features.cpp:(.text._ZN6google17MakeCheckOpStringIiiEEPSsRKT_RKT0_PKc[_ZN6google17MakeCheckOpStringIiiEEPSsRKT_RKT0_PKc]+0x50): undefined reference to `google::base::CheckOpMessageBuilder::NewString()'
.build_release/tools/extract_features.o: In function `std::string* google::MakeCheckOpString<unsigned long, unsigned long>(unsigned long const&, unsigned long const&, char const*)':
extract_features.cpp:(.text._ZN6google17MakeCheckOpStringImmEEPSsRKT_RKT0_PKc[_ZN6google17MakeCheckOpStringImmEEPSsRKT_RKT0_PKc]+0x51): undefined reference to `google::base::CheckOpMessageBuilder::NewString()'
.build_release/tools/extract_features.o: In function `int feature_extraction_pipeline<float>(int, char**)':
extract_features.cpp:(.text._Z27feature_extraction_pipelineIfEiiPPc[_Z27feature_extraction_pipelineIfEiiPPc]+0xc68): undefined reference to `google::protobuf::internal::empty_string_'
extract_features.cpp:(.text._Z27feature_extraction_pipelineIfEiiPPc[_Z27feature_extraction_pipelineIfEiiPPc]+0x12f3): undefined reference to `google::protobuf::MessageLite::SerializeToString(std::string*) const'
.build_release/lib/libcaffe.so: undefined reference to `google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(int, std::string const&, google::protobuf::io::CodedOutputStream*)'
.build_release/lib/libcaffe.so: undefined reference to `jas_stream_close'
.build_release/lib/libcaffe.so: undefined reference to `jas_image_writecmpt'
.build_release/lib/libcaffe.so: undefined reference to `tbb::task_scheduler_init::initialize(int)'
.build_release/lib/libcaffe.so: undefined reference to `google::protobuf::io::CodedOutputStream::WriteStringWithSizeToArray(std::string const&, unsigned char*)'
.build_release/lib/libcaffe.so: undefined reference to `TIFFReadEncodedStrip'
.build_release/lib/libcaffe.so: undefined reference to `png_set_filter'
.build_release/lib/libcaffe.so: undefined reference to `Imf_2_2::globalThreadCount()'
.build_release/lib/libcaffe.so: undefined reference to `png_error'
.build_release/lib/libcaffe.so: undefined reference to `png_set_rgb_to_gray'
.build_release/lib/libcaffe.so: undefined reference to `jpeg_read_scanlines'
.build_release/lib/libcaffe.so: undefined reference to `tbb::task::note_affinity(unsigned short)'
.build_release/lib/libcaffe.so: undefined reference to `png_set_palette_to_rgb'
.build_release/lib/libcaffe.so: undefined reference to `jpeg_alloc_huff_table'
.build_release/lib/libcaffe.so: undefined reference to `png_set_packing'
.build_release/lib/libcaffe.so: undefined reference to `google::protobuf::internal::WireFormatLite::ReadString(google::protobuf::io::CodedInputStream*, std::string*)'
.build_release/lib/libcaffe.so: undefined reference to `Imf_2_2::ChannelList::insert(char const*, Imf_2_2::Channel const&)'
.build_release/lib/libcaffe.so: undefined reference to `jpeg_set_defaults'
.build_release/lib/libcaffe.so: undefined reference to `jas_image_readcmpt'
.build_release/lib/libcaffe.so: undefined reference to `jpeg_write_scanlines'
.build_release/lib/libcaffe.so: undefined reference to `jas_image_encode'
.build_release/lib/libcaffe.so: undefined reference to `png_set_gray_to_rgb'
.build_release/lib/libcaffe.so: undefined reference to `Imf_2_2::InputFile::header() const'
.build_release/lib/libcaffe.so: undefined reference to `tbb::task_group_context::is_group_execution_cancelled() const'
.build_release/lib/libcaffe.so: undefined reference to `Imf_2_2::hasChromaticities(Imf_2_2::Header const&)'
.build_release/lib/libcaffe.so: undefined reference to `google::protobuf::Message::GetTypeName() const'
.build_release/lib/libcaffe.so: undefined reference to `jas_image_decode'
.build_release/lib/libcaffe.so: undefined reference to `png_set_strip_16'
.build_release/lib/libcaffe.so: undefined reference to `tbb::internal::allocate_continuation_proxy::allocate(unsigned long) const'
.build_release/lib/libcaffe.so: undefined reference to `jas_cleanup'
.build_release/lib/libcaffe.so: undefined reference to `jpeg_finish_compress'
.build_release/lib/libcaffe.so: undefined reference to `google::protobuf::internal::StringTypeHandlerBase::Delete(std::string*)'
.build_release/lib/libcaffe.so: undefined reference to `Imf_2_2::OutputFile::writePixels(int)'
.build_release/lib/libcaffe.so: undefined reference to `TIFFReadEncodedTile'
.build_release/lib/libcaffe.so: undefined reference to `tbb::task_scheduler_init::terminate()'
.build_release/lib/libcaffe.so: undefined reference to `png_create_write_struct'
.build_release/lib/libcaffe.so: undefined reference to `Imf_2_2::InputFile::setFrameBuffer(Imf_2_2::FrameBuffer const&)'
.build_release/lib/libcaffe.so: undefined reference to `TIFFGetField'
.build_release/lib/libcaffe.so: undefined reference to `jas_image_strtofmt'
.build_release/lib/libcaffe.so: undefined reference to `TIFFReadRGBATile'
.build_release/lib/libcaffe.so: undefined reference to `png_read_update_info'
.build_release/lib/libcaffe.so: undefined reference to `png_create_read_struct'
.build_release/lib/libcaffe.so: undefined reference to `Imf_2_2::InputFile::readPixels(int, int)'
.build_release/lib/libcaffe.so: undefined reference to `TIFFScanlineSize'
.build_release/lib/libcaffe.so: undefined reference to `google::protobuf::MessageFactory::InternalRegisterGeneratedFile(char const*, void (*)(std::string const&))'
.build_release/lib/libcaffe.so: undefined reference to `typeinfo for tbb::task'
.build_release/lib/libcaffe.so: undefined reference to `leveldb::DB::Open(leveldb::Options const&, std::string const&, leveldb::DB**)'
.build_release/lib/libcaffe.so: undefined reference to `TIFFSetField'
.build_release/lib/libcaffe.so: undefined reference to `Imf_2_2::Channel::Channel(Imf_2_2::PixelType, int, int, bool)'
.build_release/lib/libcaffe.so: undefined reference to `png_set_bgr'
.build_release/lib/libcaffe.so: undefined reference to `png_destroy_read_struct'
.build_release/lib/libcaffe.so: undefined reference to `jas_image_create'
.build_release/lib/libcaffe.so: undefined reference to `png_set_expand_gray_1_2_4_to_8'
.build_release/lib/libcaffe.so: undefined reference to `png_get_IHDR'
.build_release/lib/libcaffe.so: undefined reference to `png_write_image'
.build_release/lib/libcaffe.so: undefined reference to `jpeg_set_quality'
.build_release/lib/libcaffe.so: undefined reference to `png_set_read_fn'
.build_release/lib/libcaffe.so: undefined reference to `google::protobuf::Message::DebugString() const'
.build_release/lib/libcaffe.so: undefined reference to `jas_image_getcmptbytype'
.build_release/lib/libcaffe.so: undefined reference to `TIFFSetWarningHandler'
.build_release/lib/libcaffe.so: undefined reference to `jas_cmprof_destroy'
.build_release/lib/libcaffe.so: undefined reference to `png_write_info'
.build_release/lib/libcaffe.so: undefined reference to `jpeg_resync_to_restart'
.build_release/lib/libcaffe.so: undefined reference to `png_read_end'
.build_release/lib/libcaffe.so: undefined reference to `tbb::internal::allocate_root_with_context_proxy::free(tbb::task&) const'
.build_release/lib/libcaffe.so: undefined reference to `TIFFIsTiled'
.build_release/lib/libcaffe.so: undefined reference to `png_read_image'
.build_release/lib/libcaffe.so: undefined reference to `png_set_compression_strategy'
.build_release/lib/libcaffe.so: undefined reference to `google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(int, std::string const&, google::protobuf::io::CodedOutputStream*)'
.build_release/lib/libcaffe.so: undefined reference to `tbb::task_group_context::init()'
.build_release/lib/libcaffe.so: undefined reference to `google::protobuf::internal::StringTypeHandlerBase::New()'
.build_release/lib/libcaffe.so: undefined reference to `TIFFWriteScanline'
.build_release/lib/libcaffe.so: undefined reference to `Imf_2_2::Slice::Slice(Imf_2_2::PixelType, char*, unsigned long, unsigned long, int, int, double, bool, bool)'
.build_release/lib/libcaffe.so: undefined reference to `jpeg_destroy_decompress'
.build_release/lib/libcaffe.so: undefined reference to `TIFFRGBAImageOK'
.build_release/lib/libcaffe.so: undefined reference to `TIFFOpen'
.build_release/lib/libcaffe.so: undefined reference to `jas_init'
.build_release/lib/libcaffe.so: undefined reference to `Imf_2_2::OutputFile::setFrameBuffer(Imf_2_2::FrameBuffer const&)'
.build_release/lib/libcaffe.so: undefined reference to `jpeg_CreateDecompress'
.build_release/lib/libcaffe.so: undefined reference to `jpeg_read_header'
.build_release/lib/libcaffe.so: undefined reference to `TIFFReadRGBAStrip'
.build_release/lib/libcaffe.so: undefined reference to `glXGetProcAddressARB'
.build_release/lib/libcaffe.so: undefined reference to `TIFFSetErrorHandler'
.build_release/lib/libcaffe.so: undefined reference to `jas_cmprof_createfromclrspc'
.build_release/lib/libcaffe.so: undefined reference to `google::protobuf::MessageLite::ParseFromString(std::string const&)'
.build_release/lib/libcaffe.so: undefined reference to `Imf_2_2::Header::dataWindow() const'
.build_release/lib/libcaffe.so: undefined reference to `jpeg_stdio_src'
.build_release/lib/libcaffe.so: undefined reference to `png_set_strip_alpha'
.build_release/lib/libcaffe.so: undefined reference to `png_get_io_ptr'
.build_release/lib/libcaffe.so: undefined reference to `jas_stream_fopen'
.build_release/lib/libcaffe.so: undefined reference to `jas_matrix_create'
.build_release/lib/libcaffe.so: undefined reference to `tbb::task_scheduler_init::default_num_threads()'
.build_release/lib/libcaffe.so: undefined reference to `jpeg_destroy_compress'
.build_release/lib/libcaffe.so: undefined reference to `Imf_2_2::Header::channels()'
.build_release/lib/libcaffe.so: undefined reference to `jpeg_stdio_dest'
.build_release/lib/libcaffe.so: undefined reference to `half::_eLut'
.build_release/lib/libcaffe.so: undefined reference to `Imf_2_2::Header::channels() const'
.build_release/lib/libcaffe.so: undefined reference to `google::protobuf::internal::NameOfEnum(google::protobuf::EnumDescriptor const*, int)'
.build_release/lib/libcaffe.so: undefined reference to `tbb::internal::get_initial_auto_partitioner_divisor()'
.build_release/lib/libcaffe.so: undefined reference to `Imf_2_2::Header::~Header()'
.build_release/lib/libcaffe.so: undefined reference to `Imf_2_2::Header::Header(int, int, float, Imath_2_2::Vec2<float> const&, float, Imf_2_2::LineOrder, Imf_2_2::Compression)'
.build_release/lib/libcaffe.so: undefined reference to `Imf_2_2::InputFile::InputFile(char const*, int)'
.build_release/lib/libcaffe.so: undefined reference to `png_write_end'
.build_release/lib/libcaffe.so: undefined reference to `Imf_2_2::OutputFile::OutputFile(char const*, Imf_2_2::Header const&, int)'
.build_release/lib/libcaffe.so: undefined reference to `tbb::task_scheduler_init::initialize(int, unsigned long)'
.build_release/lib/libcaffe.so: undefined reference to `Imf_2_2::FrameBuffer::insert(char const*, Imf_2_2::Slice const&)'
.build_release/lib/libcaffe.so: undefined reference to `Imf_2_2::ChannelList::findChannel(char const*) const'
.build_release/lib/libcaffe.so: undefined reference to `Imf_2_2::chromaticities(Imf_2_2::Header const&)'
.build_release/lib/libcaffe.so: undefined reference to `TIFFClose'
.build_release/lib/libcaffe.so: undefined reference to `jpeg_finish_decompress'
.build_release/lib/libcaffe.so: undefined reference to `png_read_info'
.build_release/lib/libcaffe.so: undefined reference to `png_set_write_fn'
.build_release/lib/libcaffe.so: undefined reference to `jpeg_start_decompress'
.build_release/lib/libcaffe.so: undefined reference to `png_set_swap'
.build_release/lib/libcaffe.so: undefined reference to `png_get_tRNS'
.build_release/lib/libcaffe.so: undefined reference to `png_set_interlace_handling'
.build_release/lib/libcaffe.so: undefined reference to `tbb::task_group_context::~task_group_context()'
.build_release/lib/libcaffe.so: undefined reference to `tbb::internal::allocate_child_proxy::allocate(unsigned long) const'
.build_release/lib/libcaffe.so: undefined reference to `jas_matrix_destroy'
.build_release/lib/libcaffe.so: undefined reference to `png_init_io'
.build_release/lib/libcaffe.so: undefined reference to `png_set_IHDR'
.build_release/lib/libcaffe.so: undefined reference to `jas_image_chclrspc'
.build_release/lib/libcaffe.so: undefined reference to `half::convert(int)'
.build_release/lib/libcaffe.so: undefined reference to `google::protobuf::internal::WireFormatLite::WriteString(int, std::string const&, google::protobuf::io::CodedOutputStream*)'
.build_release/lib/libcaffe.so: undefined reference to `png_destroy_write_struct'
.build_release/lib/libcaffe.so: undefined reference to `leveldb::Status::ToString() const'
.build_release/lib/libcaffe.so: undefined reference to `jpeg_start_compress'
.build_release/lib/libcaffe.so: undefined reference to `Imf_2_2::Chromaticities::Chromaticities(Imath_2_2::Vec2<float> const&, Imath_2_2::Vec2<float> const&, Imath_2_2::Vec2<float> const&, Imath_2_2::Vec2<float> const&)'
.build_release/lib/libcaffe.so: undefined reference to `jas_image_destroy'
.build_release/lib/libcaffe.so: undefined reference to `tbb::internal::allocate_root_with_context_proxy::allocate(unsigned long) const'
.build_release/lib/libcaffe.so: undefined reference to `jpeg_CreateCompress'
.build_release/lib/libcaffe.so: undefined reference to `google::protobuf::DescriptorPool::FindFileByName(std::string const&) const'
.build_release/lib/libcaffe.so: undefined reference to `Imf_2_2::OutputFile::~OutputFile()'
.build_release/lib/libcaffe.so: undefined reference to `google::protobuf::internal::WireFormatLite::ReadBytes(google::protobuf::io::CodedInputStream*, std::string*)'
.build_release/lib/libcaffe.so: undefined reference to `png_create_info_struct'
.build_release/lib/libcaffe.so: undefined reference to `jpeg_std_error'
.build_release/lib/libcaffe.so: undefined reference to `google::protobuf::Message::InitializationErrorString() const'
.build_release/lib/libcaffe.so: undefined reference to `png_set_compression_level'
collect2: error: ld returned 1 exit status
Makefile:619: recipe for target '.build_release/tools/extract_features.bin' failed
make: *** [.build_release/tools/extract_features.bin] Error 1

Could somebody please help me figure this out? 
I installed gcc 4.9 instead of the 5.4 version to enable easy installation of opencv 2.4 on my machine.
Any pointers/hints will be helpful.Thank you

**Comment by sbrugman** [comment]
Have you installed gcc because of the "unsupported GNU version! gcc versions later than 5.3 are not supported!" error?

This page has a solution for that, which works just fine for me:
https://github.com/BVLC/caffe/wiki/GeForce-GTX-1080,---CUDA-8.0,---Ubuntu-16.04,---Caffe

**Comment by balajithoshkahna** [comment]
@sbrugman  Thanks for your reply.Unfortunately i had to downgrade to 4.9 to enable opencv 2.4.11 installation on my machine. There are a lot of interdependencies on libraries for installing caffe,theano etc. and i am struggling with caffe now. I have gtx960m.

**Comment by shelhamer** [comment]
Please ask installation questions on the mailing list. You might try the Caffe [Dockerfile](https://github.com/BVLC/caffe/tree/master/docker) if you are having trouble, especially if there are conflicting dependencies, since the container encapsulates the dependencies for Caffe.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

**Comment by CDLuminate** [comment]
the base system had already migrated to gcc-5 ABI which is not quite compatible with gcc-4 ABI.
gcc-4 linkage failure is not surprise.
