### ISSUE TITLE
Why I still get the Error: Duplicate blobs produced by multiple sources?

### ISSUE THREAD

**Issue by WHUT-Liang** [BVLC/caffe#4722]
when I try to load the xx.prototxt and xx.caffemodel to the opencv in the window,the error occur.
and I try hard to search in internet but seem it is a bug.why I downloads and make the latest caffe still get the problems? help!

**Comment by shaibagon** [comment]
Please use the [caffe-users list][1] for usage, installation, or modeling questions, or other requests for help.
You may also post questions on [stackoverflow][3], make sure you tag them with `caffe` tag.  
There is also [caffe.help][4] documenting the different layers of caffe.
Do not post such requests to Issues. Doing so interferes with the development of Caffe.

Please read the [guidelines for contributing][2] before submitting this issue.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
 [3]: http://stackoverflow.com/questions/tagged/caffe
 [4]: http://caffe.help/manual/layers.html
