### ISSUE TITLE
Caffe Instalation problems in Ubuntu 16.04

### ISSUE THREAD

**Issue by rajathmb** [BVLC/caffe#4725]
Hi everyone,
I am a newbie to Deep Learning and Caffe so my doubts may be very silly but i need everyone's help and guidance to install Caffe successfully on my Laptop.
I have a dell laptop with Ubuntu 16.04 installed and trying to install Caffe but unfortunately end up without installing the Caffe software.
I followed all the steps given in the Caffe deep learning website but the compilation failed and did not go further then i came across this website where all the steps where given very clearly so i started following it but the very first NVDIA driver installation failed.

My Questions:

1) Is the system hardware configuration good enough to install Caffe.
2) I am following the below Link to install the Caffe is this sufficient.
http://www.computervisionbytecnalia.com/en/2016/06/deep-learning-development-setup-for-ubuntu-16-04-xenial/
3) I need help and guidance on how to install the Caffe in Ubuntu.
 Thank you very much.
![screenshot from 2016-09-13 22-51-38](https://cloud.githubusercontent.com/assets/22188391/18501788/bfbef176-7a07-11e6-8165-8d27a55c5ae5.png)

**Comment by 12rohanb** [comment]
Make sure that your NVIDIA driver is up to date (367 or 370) and you have CUDA 8.0 and that you pass the deviceQuery test included in CUDA samples.

**Comment by rajathmb** [comment]
Hi,
Thank you for your response.
Before going further is my System configuration sufficient enough to run this and the link which i posted in the previous post is the right one.

**Comment by 12rohanb** [comment]
I'm not sure if is enough but you can give it a try. The link you posted is fine but it assumes you have an NVIDIA graphics drivers which it doesn't seem like you have. Try the caffe wiki on the github page. It has good instructions.

**Comment by rajathmb** [comment]
Hi,
I saw the Github link and it gives a bit clear picture on how to go about it. I will try to follow their procedure and see how it works.
Thank you for your precious time.

**Comment by shelhamer** [comment]
Please ask installation questions on the mailing list.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
