### ISSUE TITLE
How can I do classification without meanfile

### ISSUE THREAD

**Issue by terminats17** [BVLC/caffe#4726]
The googleNet mean value is set as mean_value: 104, mean_value: 117, mean_value: 123,however, how can I do classification with caffe then

**Comment by allanpk716** [comment]
I got same problem, can anyone talk us ?

**Comment by williford** [comment]
You can use a Scale layer with constant values:
http://caffe.help/manual/layers/scale.html

For more details, please ask on StackOverflow or write the question on the bottom of the caffe.help page.

> Please use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) for usage, installation, or modeling questions, or other requests for help.
> _Do not post such requests to Issues._ Doing so interferes with the development of Caffe.
