### ISSUE TITLE
Caffe with GTX1080 in windows 7

### ISSUE THREAD

**Issue by Guangye** [BVLC/caffe#4733]
Hello Everybody,

I am trying to run caffe with a GTX1080 card under windows 7.

Here is the set up:

BVLC/caffe master + cudnn-8.0-windows7-x64-v5.0-ga + graphics driver: 372.70

I compiled the caffe project under vs2013 in porting manually the necessary commits from caffe-windows branch.

However during execution, I got an **error from the cudnn.hpp** createFilterDesc/cudnnSetFilter4dDescriptor function: Check failed: status == CUDNN_STATUS_SUCCESS (3 vs. 0) CUDNN_STATUS_BAD_PARAM.

**My doubt** is that I might not have ported the CommonSettings.props file properly for using cudnn v5. As the file alerts that .

Thank you in advance for your help!

Guangye

**Comment by Guangye** [comment]
Hello Everybody,

I changed back to BVLC/caffe windows branch and ported in the cudnn v5 support from the master branch. The Caffe model **finally runs** on the GTX1080 card.

I tested both the (cuda7.5 + cudnn-7.5-windows7-x64-v5.0-ga) and the (cuda8.0 + cudnn-8.0-windows7-x64-v5.0-ga) combinations, and both works fine with relatively same performance.

Apparently the BVLC/caffe windows branch has done other jobs than just making it compile and link under windows visual studio environment by simple replacing some io macros (which is what I did in the first try).

Can the BVLC/caffe windows branch experts give some hints as **why** my first try with the master branch failed?

Thank you very much!

Guangye

**Comment by messcode** [comment]
Hi @Guangye  I tried to install caffe on windows 7 with a GTX 1080 card. But I always got error  message

 **"error C1083: 无法打开包括文件: “cublas_v2.h”: No such file or directory" .** 

I have searched in issues list. However, it seems there is no solution for windows.
Have you ever got this message?

PS: I am using windows branch too.
 
messcode

**Comment by sabirdvd** [comment]
I'm having this problem as well, and I'm running Linux 
In file included from ./include/caffe/common.hpp:19:0,
                 from ./include/caffe/blob.hpp:8,
                 from src/caffe/blob.cpp:4:
./include/caffe/util/device_alternate.hpp:34:23: error fatal: cublas_v2.h: No existe

**Comment by Guangye** [comment]
Dear Messcode,

I didn't encounter the error message you mentioned.

What I did was porting the following commit of cudnn5 from the master branch to the windows branch.

(1 parent bb0c1a5 commit b43c8e43a95608a00033f8f8867d32a201e5eed4  flx42 committed May 16, 2016)

You could probably try a search of the missing file on your disk and check the project config as whether the file path is added.

Guangye

**Comment by messcode** [comment]
Dear Guangye,

Thanks for you generous help.

I think I might compile it successfully, but I didn't figure out how it works.

**Comment by roipony** [comment]
Hello,
I having gtx 1080 , cuda8 , cudnn. I compiled caffe on windows and I getting strange behavior during simple training (mnist), the net is not converging. When I complied without cudnn everything is normal. 
Anyone know the problem and how to deal with?
Thanks

**Comment by willyd** [comment]
Closing as resolved.
