### ISSUE TITLE
Importing 2 different caffe libraries in single python program

### ISSUE THREAD

**Issue by codecolony** [BVLC/caffe#4750]
Hi,

Can somebody guide me as to how I can work with 2 different versions of caffe in a single python program? It imports only one library all the time no matter what I tried. I tried renaming the output library binaries to see if I can import them into different namespaces but didn't work. If anyone has done this before or has any ideas or suggestions then can you please guide me?

Thanks in advance.

**Comment by codecolony** [comment]
Anyone any help?

**Comment by naibaf7** [comment]
@codecolony 
Would you mind explaining what you try to do? Maybe there is a more elegant solution to it.

**Comment by wadefelix** [comment]
using multiprocessing.Process

**Comment by codecolony** [comment]
@wadefelix  - Thank you very much. Your suggestion worked quite well.

**Comment by zhoupan9109** [comment]
@codecolony Can you tell me how to use multiprocessing in loading two different branches of caffe? Thank you very much!
