### ISSUE TITLE
get confused by  implement of hinge loss layer

### ISSUE THREAD

**Issue by sgxu** [BVLC/caffe#4751]
Hello, I get confused by this implement of hinge loss.  It seems that you are using this formula:

![ddd](http://img.blog.csdn.net/20150627162037549)

but ref to wiki, the formulation of hinge loss is:
![ddd](https://cloud.githubusercontent.com/assets/5069487/18699352/7cdc11a2-8003-11e6-9452-43577ac3894a.png), 
they have the same effect ? can any one explain it for me? thanks

**Comment by shelhamer** [comment]
Please ask modeling and usage questions on the mailing list.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
