### ISSUE TITLE
Is there a layer that can load pixel-wise labeled image and RGB images?

### ISSUE THREAD

**Issue by ChiZhangRIT** [BVLC/caffe#4753]
I am new in Caffe and now working on pixel-wise image segmentation. I am planning to train my network using PASCAL VOC 2012. Is there a layer type that can load RGB images as data and pixel-wise segmented image as labels?

The type of `ImageData` takes one single number as a label for an image. But what I want is a segmented image as label.

I tried to load data and label separately in the following way but it seems that they are not paired, even if I turn the shuffle off, i.e., they are representing different images in the same batch. How should I deal with problem? Any help is appreciated.

```
layer {
  name: "data"		
  type: "ImageData"				
  top: "data"
  top: "dummy1"
  transform_param {
    crop_size: 224
    mean_value: 104.007
    mean_value: 116.669
    mean_value: 122.679
    mirror: true
  }
  image_data_param {
    source: "data/pascal_voc2012/voc2012_train_data.txt"
    batch_size: 5
    shuffle: false
    new_height: 224
    new_width: 224
  }
}
layer {
  name: "silence_1"	
  type: "Silence"		
  bottom: "dummy1"
}

layer {
  name: "label"		
  type: "ImageData"				
  top: "seg_label"
  top: "dummy2"
  transform_param {
    crop_size: 224
    mirror: true
  }
  image_data_param {
    source: "data/pascal_voc2012/voc2012_train_label.txt"
    is_color: 0
    batch_size: 5
    shuffle: false
    new_height: 224
    new_width: 224
  }
}
layer {
  name: "silence_2"	
  type: "Silence"		
  bottom: "dummy2"
}
```

**Comment by shelhamer** [comment]
Please ask usage questions on the mailing list.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
