### ISSUE TITLE
How to set the params of Deconvolution in Caffe prototxt?

### ISSUE THREAD

**Issue by csyking** [BVLC/caffe#4755]
Hi All,

If the size of feature map is 4*4, how to set the params of Deconvolution to make the feature map to 7*7?

The Deconvolution layer is as follows:

layer {
  name: "deconv5_2"
  type: "Deconvolution"
  bottom: "conv5_2"
  top: "deconv5_2"
  param {
    lr_mult: 1
    decay_mult: 0
  }
  param {
    lr_mult: 2
    decay_mult: 0
  }
  convolution_param {
    num_output: 512
    pad: 1 # is right?
    stride: 1 # is right?
    kernel_size: 6 # is right?
    weight_filler {
      type: "xavier"
    }
    bias_filler {
      type: "constant"
      value: 0
    }
  }
}

What is the mathematical formula of deconvolution？

Any help I will be grateful!

**Comment by zeakey** [comment]
you cannot set these parameters in prototxt, you should do net surgery, see [net_surgery](https://github.com/zeakey/DeepSkeleton/blob/master/examples/DeepSkeleton/solve.py)

**Comment by shelhamer** [comment]
Please ask usage questions on the mailing list.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

The deconv weights can be initialized with the `bilinear` weight filler with the right setting of `group`, but I do so by net surgery as suggested.
