### ISSUE TITLE
Error Compiling Caffe

### ISSUE THREAD

**Issue by cleversonledur** [BVLC/caffe#4760]
I am having the following error when compiling caffe in Debian 8.

`LD -o .build_release/lib/libcaffe.so.1.0.0-rc3
/usr/bin/ld: /usr/local/lib/libglog.a(logging.cc.o): relocation R_X86_64_32 against`.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libglog.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
Makefile:566: recipe for target '.build_release/lib/libcaffe.so.1.0.0-rc3' failed
make: **\* [.build_release/lib/libcaffe.so.1.0.0-rc3] Error 1`

**Comment by gombru** [comment]
I'm having the same error in Ubuntu 15.04

**Comment by halamri1** [comment]
I'm having the same error too in Ubuntu 16.04, Python 2.7

**Comment by sjean** [comment]
did anyone figure this out? please teach me

**Comment by jmsardoy** [comment]
someone find a  fix for this? i can't pass compilation

**Comment by Noiredd** [comment]
Duplicate of #2171, where it was also solved.
