### ISSUE TITLE
Error when compiling Caffe

### ISSUE THREAD

**Issue by lfpolani** [BVLC/caffe#4762]
When I entered 'make all' in my terminal (my machine is CentOS 7.2_), I get the following error:
/usr/bin/ld: cannot find -latlas
collect2: error: ld returned 1 exit status
make: *** [.build_release/tools/caffe.bin] Error 1

Any ideas on how to solve it? Thanks

**Comment by wk910930** [comment]
Try install ATLAS by `sudo yum install atlas-devel` . Will it help?

**Comment by lfpolani** [comment]
Atlas is already installed.

**Comment by codes-kzhan** [comment]
@lfpolani how do you solve it?
