### ISSUE TITLE
run crnn on caffe

### ISSUE THREAD

**Issue by wolfbill** [BVLC/caffe#4765]
Hi all:
     I'd like to run c-rnn on caffe. The result of cnn will be the input of rnn.I don't know how to deal with it

**Comment by shelhamer** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
