### ISSUE TITLE
There's no one maintain caffe now?

### ISSUE THREAD

**Issue by hjc1028** [BVLC/caffe#4770]

**Comment by diggerdu** [comment]
You are right.

**Comment by naibaf7** [comment]
@diggerdu 
Reviewing new code takes a lot of time, and some pull requests are also not (yet) suitable for a merge.
No one is maintainig Caffe as a full time task. So if you wait for some new features either be patient or make easy-to-merge pull requests with new features yourself. :)

**Comment by shelhamer** [comment]
Thanks for the good attitude @naibaf7 and the work you do yourself for Caffe. I'll note further that the [project pulse](https://github.com/BVLC/caffe/pulse) always shows the latest development efforts.
