### ISSUE TITLE
Link problems while building caffe

### ISSUE THREAD

**Issue by koustavb** [BVLC/caffe#4771]
Hello,

I am getting a link error like this while building caffe:

/usr/bin/ld: /usr/local/atlas/lib//libcblas.a(cblas_xerbla.o): relocation R_AARCH64_ADR_PREL_PG_HI21 against external symbol `stderr@@GLIBC_2.17' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/atlas/lib//libcblas.a(cblas_xerbla.o)(.text+0x28): unresolvable R_AARCH64_ADR_PREL_PG_HI21 relocation against symbol `stderr@@GLIBC_2.17'
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status

I tried rebuilding atlas/cblas with -fPIC on but it didnt help. Any ideas? Thanks in advance.

**Comment by LorddBaelish** [comment]
Not the solution but you could build easily from caffe root folder..

**Comment by koustavb** [comment]
Yeah I tried remaking HDF5 with a cmake which built it with fPIC. That solved it.

**Comment by EmpireofQin** [comment]
i have the same problem, please give me some advice more clearly@koustavb

**Comment by koustavb** [comment]
Just re-build hdf5 with -FPIC. make script hdf5 doesnt do it by default. cmake build that ships with it does that. So either update make script or rebuild with cmake. That solved the issue for me.
