### ISSUE TITLE
when i new project in caffe.sh solution , it can't register the layers. but using classification ,it's ok

### ISSUE THREAD

**Issue by FishermanZzhang** [BVLC/caffe#4778]
#4470 
when i new a project in caffe.sh solution , it can't register the layers. but using classification ,it's ok.
 in layer_factory.hpp
` CreatorRegistry& registry = Registry();`
`  CHECK_EQ(registry.count(type), 1) << "Unknown layer type: " << type
        << " (known types: " << LayerTypeListString() << ")";`
the classification project show the registry.size() is 54, but my project is 0

**Comment by willyd** [comment]
You need to set the option "Use Library Dependency Inputs" to true. See https://github.com/BVLC/caffe/issues/4746 and https://github.com/BVLC/caffe/blob/windows/windows/caffe/caffe.vcxproj#L73
