### ISSUE TITLE
make runtest error

### ISSUE THREAD

**Issue by qinhaifangpku** [BVLC/caffe#4782]
hello~
i git clone caffe from https://github.com/ddetone/caffe.git  and make it work
and i checkout to a branch name 3dconv,  because i want to use a 3Dconvolutional layer
now i make it ,  but i hanppend a error in "make runtest"

[----------] 8 tests from ConvolutionLayerTest/2, where TypeParam = caffe::FloatGPU
[ RUN      ] ConvolutionLayerTest/2.TestSetup
[       OK ] ConvolutionLayerTest/2.TestSetup (0 ms)
[ RUN      ] ConvolutionLayerTest/2.TestSobelConvolution
[       OK ] ConvolutionLayerTest/2.TestSobelConvolution (0 ms)
[ RUN      ] ConvolutionLayerTest/2.TestGradient
[       OK ] ConvolutionLayerTest/2.TestGradient (791 ms)
[ RUN      ] ConvolutionLayerTest/2.TestGradientGroup
[       OK ] ConvolutionLayerTest/2.TestGradientGroup (239 ms)
[ RUN      ] ConvolutionLayerTest/2.Test1x1Convolution
F0928 21:55:00.493454 14689 blob.hpp:168] Check failed: indices.size() <= num_axes() (5 vs. 4) 
**\* Check failure stack trace: ***
    @     0x2b8430a1ddaa  (unknown)
    @     0x2b8430a1dce4  (unknown)
    @     0x2b8430a1d6e6  (unknown)
    @     0x2b8430a20687  (unknown)
    @           0x74bcf9  caffe::Blob<>::offset()
    @           0x74c32f  caffe::caffe_conv<>()
    @           0x929800  caffe::ConvolutionLayerTest_Test1x1Convolution_Test<>::TestBody()
    @           0x977ca3  testing::internal::HandleExceptionsInMethodIfSupported<>()
    @           0x96e4c7  testing::Test::Run()
    @           0x96e56e  testing::TestInfo::Run()
    @           0x96e675  testing::TestCase::Run()
    @           0x9713c8  testing::internal::UnitTestImpl::RunAllTests()
    @           0x971667  testing::UnitTest::Run()
    @           0x67168a  main
    @     0x2b84361fcf45  (unknown)
    @           0x674782  (unknown)
    @              (nil)  (unknown)
Aborted (core dumped)
make[3]: **\* [src/caffe/test/CMakeFiles/runtest] 错误 134
make[2]: **\* [src/caffe/test/CMakeFiles/runtest.dir/all] 错误 2
make[1]: **\* [src/caffe/test/CMakeFiles/runtest.dir/rule] 错误 2
make: **\* [runtest] 错误 2

is there any body know why it happend and how can it be solved?
thank you!

**Comment by shelhamer** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
