### ISSUE TITLE
Make test Errors

### ISSUE THREAD

**Issue by KKNakka** [BVLC/caffe#4784]
Makeall is compiling correctly.

But there are errors while compiling make test.

Particularly at gtest-all.cpp

![caffe_error](https://cloud.githubusercontent.com/assets/20205235/18949406/e2e96520-8658-11e6-8c32-10d3ebbdb172.PNG)

**Comment by shelhamer** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
