### ISSUE TITLE
List of deopendancies for caffe c++ project?

### ISSUE THREAD

**Issue by LorddBaelish** [BVLC/caffe#4794]
Can anyone post a list of dependancies for a caffe project? Im compiling outside caffe root directory. Thanks

**Comment by CDLuminate** [comment]
https://anonscm.debian.org/cgit/debian-science/packages/caffe.git/tree/debian/control

**Comment by LorddBaelish** [comment]
@CDLuminate thanks...👌

**Comment by shelhamer** [comment]
Thanks for that @CDLuminate; closing.
