### ISSUE TITLE
Cmake and make libgflags error

### ISSUE THREAD

**Issue by piteight** [BVLC/caffe#4797]
Hello :)
I have tried to make caffe on Ubuntu 16.04, and once I did it for cuda 7.5, but then, after some time I had login loop and had to install different graphic card drivers. When I installed them, caffe worked only in CPU mode, so I tried to recompile it again, and it didn't worked. 
This time I have installed cuda 8.0 and all other stuff, so it could be compiled with gcc 5 not 4.9.

Tried to google the error output, but didnt find anything like that:

[ 81%] Linking CXX shared library ../../lib/libcaffe.so
/usr/bin/ld: /usr/local/lib/libgflags.a(gflags.cc.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libgflags.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
src/caffe/CMakeFiles/caffe.dir/build.make:3283: recipe for target 'lib/libcaffe.so.1.0.0-rc3' failed
make[2]: **\* [lib/libcaffe.so.1.0.0-rc3] Error 1
CMakeFiles/Makefile2:272: recipe for target 'src/caffe/CMakeFiles/caffe.dir/all' failed
make[1]: **\* [src/caffe/CMakeFiles/caffe.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: **\* [all] Error 2

**Comment by fujihuang** [comment]
Hi,i encounter this error too,have you solved?and how do you solve this error~?

**Comment by piteight** [comment]
Well, I had to clean the caffe and install it only by make not cmake. There is an "error" when you compile caffe and then pycaffe, ubuntu builds a new kernel, and at this kernel, graphics drivers dont work, so i had to load previous kernel from advanced booting in grub. 
I also had to manually add some paths to makefile, and correct some softlinks like libcudart.so. I will write more about it when I remember something new.

**Comment by fujihuang** [comment]
uh,thx,the make is sure worked,i have install caffe by ' make ' ,but i have
to use the caffe builded by cmake, i am looking forward to your reply~(like
something which you just did and can fix this bug~).thx again~

2016-11-25 7:24 GMT-05:00 piteight <notifications@github.com>:

**Comment by xelmirage** [comment]
In this thread there is a solution
[https://code.google.com/archive/p/google-glog/issues/201](url)

> Posted on Jul 23, 2014 by Happy Dog

> Same

 issue on Ubuntu 14.04, 64 bit, g++ 4.8.2, glibc 2.19 Solved by compiling gflags-2.1.1 with -fPIC:

> $

 tar -xvf gflags-2.1.1.tar.gz $ cd gflags-2.1.1 && mkdir build && cd build $ CXXFLAGS="-fPIC" cmake .. -DGFLAGS_NAMESPACE=google $ sudo make install

> Then

 install glog-0.3.3 as usual.


and it works, hope this will help

**Comment by shelhamer** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
