### ISSUE TITLE
problem to compile caffe with cmake

### ISSUE THREAD

**Issue by EmpireofQin** [BVLC/caffe#4802]
I have installed caffe using make. Now i want to install it with cmake, but i meet a problem hard for me to solve.

firstly, i type
`make ..`
got an error: 
`CMake Error at CMakeLists.txt:85 (add_dependencies):`
`  The dependency target "pycaffe" of target "pytest" does not exist.`
i ignored and type：
`cmake . -DCMAKE_BUILD_TYPE=Debug`
got the same result
then type:
`make -j 4 && make install`
got error:
```
Linking CXX shared library ../../lib/libcaffe-d.so
/usr/bin/ld: /usr/local/lib/libcblas.a(cblas_sgemv.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libcblas.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
make[2]: *** [lib/libcaffe-d.so.1.0.0-rc3] Error 1
make[1]: *** [src/caffe/CMakeFiles/caffe.dir/all] Error 2
make: *** [all] Error 2
```
please give me some help, thanks

**Comment by EmpireofQin** [comment]
I have solved this problem. I tried to edit CMakeCache.txt in the build file and changed
```
//Path to a library.
Atlas_CBLAS_LIBRARY:FILEPATH=<path to libcblas.a>
```
into
```
//Path to a library.
Atlas_CBLAS_LIBRARY:FILEPATH=/usr/lib/libcblas.so //<path to libcblas.so in my machine>
```
and it works.

**Comment by kevgeo** [comment]
@EmpireofQin Hi, even I got the same error but for me I didn't have to edit  the  CMakeCache.txt  file as it was already correct. I'm not sure how to correct this error  about pycaffe not being found?

**Comment by EmpireofQin** [comment]
I solved this error by reinstall my OS and caffe. I did not find out the exactly reason for this error. It is probably caused by wrongly installing some dependence. @kevgeo

**Comment by zheergen** [comment]
I solved this by installing boost-python which was missing.

**Comment by xelmirage** [comment]
In this thread there is a solution for the same error but libgflags
[https://code.google.com/archive/p/google-glog/issues/201](url)

> Posted on Jul 23, 2014 by Happy Dog

> Same issue on Ubuntu 14.04, 64 bit, g++ 4.8.2, glibc 2.19 Solved by compiling gflags-2.1.1 with -fPIC:

> $ tar -xvf gflags-2.1.1.tar.gz $ cd gflags-2.1.1 && mkdir build && cd build $ CXXFLAGS="-fPIC" cmake .. -DGFLAGS_NAMESPACE=google $ sudo make install

> Then install glog-0.3.3 as usual.


and it works, hope this will help

**Comment by jgoenetxea** [comment]
In my case, I am using anaconda, and I have solved this issue defining the paths of glog, boost, gflags and python interpreter to the same conda environment. 

I have created a new environment for caffe called "caffe", and I have installed glog, boost and gflags using the command "conda install [dependency name]".

I have redirected all the paths (using CMake gui) to the path "/home/user/anaconda3/envs/caffe/" instead of "/usr/local/" and "/usr/".

Good look.

**Comment by torrison5** [comment]
In my case installing python-numpy solved this issue.

> sudo apt-get install python-numpy

**Comment by phdsky** [comment]
Same problem occurs to my OSX Sierra, but the solutions above does not solve...
Anyone have another solutions? Thanks

**Comment by rajhlinux** [comment]
I have the same issue on FreeBSD 13.1, any solutions?

Thanks.

**Comment by MOLOCH-dev** [comment]
I faced this issue when my installed python version did not match the version of python set in the [CMakeLists.txt file](https://github.com/BVLC/caffe/blob/9b891540183ddc834a02b2bd81b31afae71b2153/CMakeLists.txt#L35). Changing version 2 to 3 here solved this issue for me.
