### ISSUE TITLE
Question about the binary protocal buffer

### ISSUE THREAD

**Issue by derickshi** [BVLC/caffe#4809]
Hello all,

I have successfully ran the mnist example and got the "lenet_iter_10000.caffemodel" file. My question is:
how can I retrieve the data(weights and bias) of the trained model from this file?  I've looked the protobuf webpage but didn't find a elaborate tutorial.

Thanks!

**Comment by lukeyeager** [comment]
@BVLC prefers that these questions be asked on the mailing list, as explained here:
https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md

But here's how to do it:
```py
from caffe.proto import caffe_pb2

net = caffe_pb2.NetParameter()
with open(filename, 'rb') as infile:
    net.ParseFromString(infile.read())

for layer in net.layer:
    print 'Layer name:', layer.name
    for i, blob in enumerate(layer.blobs):
        print '> Blob #%d shape:' % i, blob.shape.dim
```
```
Layer name: mnist
Layer name: conv1
> Blob #0 shape: [20L, 1L, 5L, 5L]
> Blob #1 shape: [20L]
Layer name: pool1
Layer name: conv2
> Blob #0 shape: [50L, 20L, 5L, 5L]
> Blob #1 shape: [50L]
Layer name: pool2
Layer name: ip1
> Blob #0 shape: [500L, 800L]
> Blob #1 shape: [500L]
Layer name: relu1
Layer name: ip2
> Blob #0 shape: [10L, 500L]
> Blob #1 shape: [10L]
Layer name: loss
```

**Comment by derickshi** [comment]
@lukeyeager  thanks! I'll use the mailing list instead of posting question here.
