### ISSUE TITLE
Inconsistent loss in shallow networks with MemoryData as input layer

### ISSUE THREAD

**Issue by ilkerkesen** [BVLC/caffe#4810]
Hi all,

I am playing with Caffe in last weeks. Actually my intention behind playing with Caffe was benchmarking and I discovered something interesting. You know Lenet is the simplest example in the repository, but I tried much more simple models like Softmax/MLP on MNIST and linear regression on the old good housing data. Anyway, when I trained my linear regression models which consists of a MemoryData layer, an InnerProduct layer and EuclideanLoss layer, I observed that loss value of train set (actually my train data is whole dataset as a single batch) converges to different values. I set random state before each individual training by using random_seed parameter in the solver.prototxt file. What's more, it does not converge sometimes and holds a _nan_ value. I repeated this problem with the latest revision also.

Besides, I really don't understand the intention behind the memory data layer. In my understanding, it should be supposed to work in this way: Allocate data from GPU and read data from directly GPU memory in the training procedure without any CPU->GPU memory data transfer. However, when I watched GPU memory usage via nvidia-smi interface, it does not work in that way. I weren't be able to load all MNIST data with usage of MemoryData layer. Also I've seen that Caffe uses memory in a very inefficient way so when I tried to use all MNIST train data as a single batch, I got an _out of memory_ error. While _ideal_ plain MNIST data with float32 entries is supposed to take up ~180 MB according to my calculations, Caffe needed more than 10 GB. Is it really normal?

By the way, I am running my examples on the Amazon AWS EC2 clusters (g2.2xlarge instance) and this link [0] includes all necessary code and logs. Maybe I've performed something wrong, it is not a bug. Maybe it's just because of using an Amazon instance. I really don't know. In the other implementations (MLP, Softmax and Lenet), I didn't come across a problem like that.

[0] [https://gist.github.com/ilkerkesen/400cc5cd1a9cfd3bcc5eac4365d81cc2](https://gist.github.com/ilkerkesen/400cc5cd1a9cfd3bcc5eac4365d81cc2)

**Comment by ilkerkesen** [comment]
I forgot to talk about something. In addition to this issue, I was able to train MNIST models with just only one single .set_input_arrays call and it generalizes test set well enough. However, I needed to perform that call after every iteration in housing example. Otherwise, loss value gets _nan_ always.

**Comment by shelhamer** [comment]
Closing according to #5528.
