### ISSUE TITLE
Not able to download pretrianed caffe model files - Error: No route to host

### ISSUE THREAD

**Issue by tumusudheer** [BVLC/caffe#4817]
Hi,

I'm trying to download pre-trained caffemodel file 

by typing $ ./scripts/download_model_binary.py models/bvlc_reference_caffenet.

from my caffe_root folder. I'm getting an error 'failed: No route to host' error

I looked up the URL from read.me file and tried to do
$ wget <url> 

but ended up getting the same error. Is the site down (when I'm trying) ? Any one has similar issues ? Please let me know if I'm doing anything wrong....

**Comment by ttang852** [comment]
Yes. I am having the exact same problem!!

**Comment by shelhamer** [comment]
The site went down but now it's back up! Thanks for raising this issue.

**Comment by ttang852** [comment]
It works now. Thanks!
