### ISSUE TITLE
Caffe on Windows maintained?

### ISSUE THREAD

**Issue by PaulDufort** [BVLC/caffe#4818]
Hi, I would love to start using Caffe but only have Windows machines available, and I'd prefer to avoid the issues that come with a VM. The Windows branch seems like the solution, but I noticed it hasn't been merged with the master in over five months, and therefore lacks newer additions like the LSTM node.

Is the Windows branch being actively maintained? Has it been abandoned?

Thanks,
Paul

**Comment by willyd** [comment]
Hi @PaulDufort. You are right that the Windows branch is lagging behind. Microsoft used to maintain it but it is now a community based effort only. I just got the responsibility of the branch so I haven't had time to update it yet as I am still stabilizing the changes I want to make to it. My plan is to switch to a CMake based build instead of the VS solutions so it is easier to keep up with master. This switch should happen soon enough (a few weeks from now). I will keep you posted whenever the changes are available. Any help in testing the changes or improving the windows build process are appreciated.

**Comment by naibaf7** [comment]
@willyd 
Looking forward to it. If the CMake solution works, it would probably also be easy to integrate it to the OpenCL branch that I maintain. This would ultimately make Caffe accessible to everyone regardless of hardware & software.

**Comment by willyd** [comment]
@naibaf7 Great! I'll keep you posted too.

**Comment by PaulDufort** [comment]
Thanks very much to both @willyd and @naibaf7, that will be tremendously helpful and a great benefit to the community! I'm afraid I am not especially knowledgeable about CMake or build systems, but I will be happy to help test anything you send my way if you can explain enough for me to figure out how to do it. I can try it out and report back the results.

**Comment by PaulDufort** [comment]
Hi @willyd, quick question: if I were to download and install the current Windows branch just to start getting some experience, would that cause problems when I migrate to your updated/upgraded version?

Thanks,
Paul

**Comment by willyd** [comment]
@PaulDufort My branch does not add a lot of functionality to the current Windows branch only the build system changes. The most notable difference that I know of are:

- My branch uses a more up to date version of LMDB. The current version of LMDB in the windows branch has some limitations of file sizes I beleive.
- Linting works in my branch and does not in the current Windows branch
- I did not test MATLAB support in my branch so I can't tell if it works or not, I think it does in the windows branch.
- I am using opencv 3.x, but the current windows branch is using 2.4.x
- My branch can build a DLL the windows branch can't.

Other than that everything should be pretty similar. Using caffe from the command line, or pycaffe should work pretty much the same.

**Comment by PaulDufort** [comment]
@willyd  Oh, so you will not be merging the new layer types etc. in the master branch (e.g. LSTM) into your Windows branch?

**Comment by willyd** [comment]
@PaulDufort Sorry if my comment was misleading. I was only stating the current differences between my windows-cmake branch and the BVLC/windows branch. Here is what is going to happen:

1. Once I get confirmation that most features work with the CMake build with the current status of the windows branch I will merge the changes in BVLC/windows.
2. Then I will update the windows branch with the latest master thereby integrating the new layer types.

So if you want to help me get the LSTM layer working on windows as fast as possible test my current windows-cmake branch and report the results.
