### ISSUE TITLE
Installing caffe on ubuntu 16.04 with 2 versions of Cuda installed (7.5 and 8)

### ISSUE THREAD

**Issue by maystroh** [BVLC/caffe#4819]
I'm trying to install Caffe on my machine where I have Ubuntu 16.04 installed and have TensorFlow and Theano libraries installed as well. I also installed Cuda 8.0 since it's required for Caffe on Ubuntu 16.04 but I didn't install the CUDA Driver for my GTX 1080 since we already have the Cuda driver 7.5 installed and we're using it for TensorFlow and Theano. I said I don't need to mess up everything. So, I just followed the installation instructions for Caffe and when I run "make all" I'm always getting the following error:

> AR -o .build_release/lib/libcaffe.a
> LD -o .build_release/lib/libcaffe.so.1.0.0-rc3
> CXX/LD -o .build_release/tools/upgrade_solver_proto_text.bin
> .build_release/lib/libcaffe.so: undefined reference « google::base::CheckOpMessageBuilder::NewString() »
> .build_release/lib/libcaffe.so: undefined reference « leveldb::DB::Open(leveldb::Options const&, std::string const&, leveldb::DB*_) »
> .build_release/lib/libcaffe.so: undefined reference « leveldb::Status::ToString() const »
> collect2: error: ld returned 1 exit status
> Makefile:621 : recipe for target « .build_release/tools/upgrade_solver_proto_text.bin » failed
> make: *_\* [.build_release/tools/upgrade_solver_proto_text.bin] Error 1

I'm newbie on Ubuntu so don't know how to manage this kinda things. Thanks in advance for any help.

**Comment by fujihuang** [comment]
There are many people i know said that cuda 8.0 is fit well with 1080,perhaps you can try to remove 7.5,install 8.0 instead.

**Comment by maystroh** [comment]
I should keep them both because I already have code running on 7.5 and it does not work on 8.0 so I'm trying to keep them both installed.

**Comment by maystroh** [comment]
Right now, I'm trying to build it differently by starting with ccmake . then sudo make install and I got the following problem
 
xxx@xxx-GTX1080:~/caffe-master$ sudo make install
[  1%] Built target proto
[  1%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/solvers/cuda_compile_generated_rmsprop_solver.cu.o
nvcc fatal   : Unsupported gpu architecture 'compute_61'
CMake Error at cuda_compile_generated_rmsprop_solver.cu.o.cmake:207 (message):
  Error generating
  /home/hassan/caffe-master/src/caffe/CMakeFiles/cuda_compile.dir/solvers/./cuda_compile_generated_rmsprop_solver.cu.o


src/caffe/CMakeFiles/caffe.dir/build.make:63 : the recipe of target « src/caffe/CMakeFiles/cuda_compile.dir/solvers/cuda_compile_generated_rmsprop_solver.cu.o » failed
make[2]: *** [src/caffe/CMakeFiles/cuda_compile.dir/solvers/cuda_compile_generated_rmsprop_solver.cu.o] Erreur 1
CMakeFiles/Makefile2:272 : the recipe of target  « src/caffe/CMakeFiles/caffe.dir/all »  failed
make[1]: *** [src/caffe/CMakeFiles/caffe.dir/all] Error 2
Makefile:127 :the recipe of target  « all » failed
make: *** [all] Error 2

**Comment by MathiasStokholm** [comment]
Hi @maystroh,

I have both CUDA 7.5 (w/ CuDNN 3) and CUDA 8.0 (w/ CuDNN 5) on my machine. They way my system is set up, I have both versions installed to /usr/local/cuda-[VERSION]. Whenever I want to switch, I simply create a symlink from the appropriate version to /usr/local/cuda.

Hope this helps

**Comment by shelhamer** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
