### ISSUE TITLE
question about deploy.prototxt

### ISSUE THREAD

**Issue by effielikesmilk** [BVLC/caffe#4820]
I am trying to generate the deploy.prototxt based on my own model. In the alexnet model, the deploy.prototxt contains 'lr_mult' in the convolution layer, while in caffenet, it doesn't contain that. 
So I am confused that whether the 'lr_mult' in the convolution layer is a must in the deploy.prototxt.
Any thoughts would be greatly appreciated!
Thanks.

**Comment by fujihuang** [comment]
I think it is not necessary,in fact there is no "lr_mult" in my deploy.prototxt for mnist.

**Comment by effielikesmilk** [comment]
@fujihuang  Yeah, I have tried the deploy.prototxt. It works. Thank you for your answer.

**Comment by williford** [comment]
@effielikesmilk, would you mind closing this issue?

Such questions should be sent to https://groups.google.com/forum/#!forum/caffe-users or stackoverflow.

**Comment by effielikesmilk** [comment]
@williford I don't mind.

**Comment by williford** [comment]
@effielikesmilk I don't actually have permission to close it. Could you close it? Otherwise, one of the core developers needs to do it.
