### ISSUE TITLE
TimerTest Fails for GPUDevice on Windows

### ISSUE THREAD

**Issue by apiszcz** [BVLC/caffe#4822]
Observation:

== Following tests failed, perhaps a mS issue vs float from the actual:
[ RUN      ] BenchmarkTest/2.TestTimerMilliSeconds
....\src\caffe\test\test_benchmark.cpp(68): error: Expected: (timer.MilliSeconds()) >= (300 - kMillisecondsThreshold), actual: 0.002528 vs 270
[  FAILED  ] BenchmarkTest/2.TestTimerMilliSeconds, where TypeParam = struct caffe::GPUDevice<float> (300 ms)
[ RUN      ] BenchmarkTest/2.TestTimerSeconds
....\src\caffe\test\test_benchmark.cpp(83): error: Expected: (timer.Seconds()) >= (0.3 - kMillisecondsThreshold / 1000.), actual: 2.528e-006 vs 0.27
[  FAILED  ] BenchmarkTest/2.TestTimerSeconds, where TypeParam = struct caffe::GPUDevice<float> (301 ms)
[----------] 5 tests from BenchmarkTest/2 (603 ms total)
[ RUN      ] BenchmarkTest/3.TestTimerMilliSeconds
....\src\caffe\test\test_benchmark.cpp(68): error: Expected: (timer.MilliSeconds()) >= (300 - kMillisecondsThreshold), actual: 0.00256 vs 270
[  FAILED  ] BenchmarkTest/3.TestTimerMilliSeconds, where TypeParam = struct caffe::GPUDevice<double> (300 ms)
[ RUN      ] BenchmarkTest/3.TestTimerSeconds
....\src\caffe\test\test_benchmark.cpp(83): error: Expected: (timer.Seconds()) >= (0.3 - kMillisecondsThreshold / 1000.), actual: 1.856e-006 vs 0.27
[  FAILED  ] BenchmarkTest/3.TestTimerSeconds, where TypeParam = struct caffe::GPUDevice<double> (301 ms)
[----------] 5 tests from BenchmarkTest/3 (602 ms total)

**Comment by willyd** [comment]
Thanks for reporting. This is a known issue. If you happen to find a fix for it. Please send a pull request.

**Comment by apiszcz** [comment]
Hello:

https://github.com/BVLC/caffe/issues/4288 suggest adding a line of code for benchmark.cpp, which I tested on Windows 10/64 with VS2013 and it works, at least as far as passing the Timer tests are concerned:
util\benchmark.cpp
AFTER LINE 46:
CUDA_CHECK(cudaEventSynchronize(start_gpu_));

Other items to note: concerning test_benchmark.cpp is boost changes concerning timers
boost::sleep is deprecated after boost v1.56, it seems sleep_for is suggested.


REF:
https://github.com/BVLC/caffe/issues/4288
https://svn.boost.org/trac/boost/ticket/11331
https://svn.boost.org/trac/boost/ticket/9856

[----------] 5 tests from BenchmarkTest/0, where TypeParam = struct caffe::CPUDevice<float>
[ RUN      ] BenchmarkTest/0.TestTimerConstructor
[       OK ] BenchmarkTest/0.TestTimerConstructor (0 ms)
[ RUN      ] BenchmarkTest/0.TestTimerStart
[       OK ] BenchmarkTest/0.TestTimerStart (0 ms)
[ RUN      ] BenchmarkTest/0.TestTimerStop
[       OK ] BenchmarkTest/0.TestTimerStop (0 ms)
[ RUN      ] BenchmarkTest/0.TestTimerMilliSeconds
[       OK ] BenchmarkTest/0.TestTimerMilliSeconds (301 ms)
[ RUN      ] BenchmarkTest/0.TestTimerSeconds
[       OK ] BenchmarkTest/0.TestTimerSeconds (300 ms)
[----------] 5 tests from BenchmarkTest/0 (608 ms total)

[----------] 5 tests from BenchmarkTest/1, where TypeParam = struct caffe::CPUDevice<double>
[ RUN      ] BenchmarkTest/1.TestTimerConstructor
[       OK ] BenchmarkTest/1.TestTimerConstructor (0 ms)
[ RUN      ] BenchmarkTest/1.TestTimerStart
[       OK ] BenchmarkTest/1.TestTimerStart (0 ms)
[ RUN      ] BenchmarkTest/1.TestTimerStop
[       OK ] BenchmarkTest/1.TestTimerStop (0 ms)
[ RUN      ] BenchmarkTest/1.TestTimerMilliSeconds
[       OK ] BenchmarkTest/1.TestTimerMilliSeconds (300 ms)
[ RUN      ] BenchmarkTest/1.TestTimerSeconds
[       OK ] BenchmarkTest/1.TestTimerSeconds (301 ms)
[----------] 5 tests from BenchmarkTest/1 (608 ms total)

[----------] 5 tests from BenchmarkTest/2, where TypeParam = struct caffe::GPUDevice<float>
[ RUN      ] BenchmarkTest/2.TestTimerConstructor
[       OK ] BenchmarkTest/2.TestTimerConstructor (0 ms)
[ RUN      ] BenchmarkTest/2.TestTimerStart
[       OK ] BenchmarkTest/2.TestTimerStart (0 ms)
[ RUN      ] BenchmarkTest/2.TestTimerStop
[       OK ] BenchmarkTest/2.TestTimerStop (1 ms)
[ RUN      ] BenchmarkTest/2.TestTimerMilliSeconds
[       OK ] BenchmarkTest/2.TestTimerMilliSeconds (300 ms)
[ RUN      ] BenchmarkTest/2.TestTimerSeconds
[       OK ] BenchmarkTest/2.TestTimerSeconds (300 ms)
[----------] 5 tests from BenchmarkTest/2 (609 ms total)

[----------] 5 tests from BenchmarkTest/3, where TypeParam = struct caffe::GPUDevice<double>
[ RUN      ] BenchmarkTest/3.TestTimerConstructor
[       OK ] BenchmarkTest/3.TestTimerConstructor (0 ms)
[ RUN      ] BenchmarkTest/3.TestTimerStart
[       OK ] BenchmarkTest/3.TestTimerStart (0 ms)
[ RUN      ] BenchmarkTest/3.TestTimerStop
[       OK ] BenchmarkTest/3.TestTimerStop (1 ms)
[ RUN      ] BenchmarkTest/3.TestTimerMilliSeconds
[       OK ] BenchmarkTest/3.TestTimerMilliSeconds (300 ms)
[ RUN      ] BenchmarkTest/3.TestTimerSeconds
[       OK ] BenchmarkTest/3.TestTimerSeconds (301 ms)
[----------] 5 tests from BenchmarkTest/3 (611 ms total)

**Comment by apiszcz** [comment]
Reviewing the GIT repository I see a comment , but not the change recommended by #4288 
https://github.com/BVLC/caffe/tree/master/src/caffe/util

benchmark.cpp	Benchmarking should not impact perf until timer is read	a month ago

**Comment by willyd** [comment]
Closing as a duplicated of #4177.
