### ISSUE TITLE
how to regression in caffe

### ISSUE THREAD

**Issue by soodabehzz** [BVLC/caffe#4823]
Hi 
I want to finetune the cifar10 on a dataset that the labels are probability , and are between 0 and 1 . like this : 
00043849.jpg 0.838710
00027457.jpg 0.739130
00019558.jpg 0.750000
I convert this data to lmdb format by changing the c++ code in caffe instead of HDF5 , that used for regression . 
and I changed the prototxt file in two steps : 
1 - I deleted the accuracy layer 
2- I changed the type of last fc layer to euclidean loss , as you can see 
`layer {
  name: "ip2-eucliean"
  type: "InnerProduct"
  bottom: "ip1"
  top: "ip2-eucliean"
  param {
    lr_mult: 1
    decay_mult:1
  }
  param {
    lr_mult: 2
    decay_mult:0
  }
  inner_product_param {
    num_output: 1
    weight_filler {
      type: "gaussian"
      std: 0.1
    }
    bias_filler {
      type: "constant"
      value : 0
    }
  }
}

layer {
  name: "loss"
  type: "EuclideanLoss"
  bottom: "ip2-eucliean"
  bottom: "label"
  #top: "loss"
}`
these are my last fc layer and loss layer . 
but my problem is the value of loss , that is very little at the begining of the training and when i test the net , all the results are zero . 
and I atthached my solver file. 
I'm really thankful if someone help me . 
Thanks in advance . 
[solver.txt](https://github.com/BVLC/caffe/files/518140/solver.txt)

**Comment by williford** [comment]
Would you mind moving your question to the Caffe user mailing list?
https://groups.google.com/forum/#!forum/caffe-users

**Comment by chunfengshiliburuni** [comment]
Hello, soodabehzz. Excuse me, I am so sorry to bother you. Can you give me some advice on converting that dataset to lmdb format by changing the c++ code in caffe instead of HDF5?
Looking forward to your reply.
