### ISSUE TITLE
Check failed too many resources requested for launch for pooling_layer.cu

### ISSUE THREAD

**Issue by Crefeda** [BVLC/caffe#4829]
Hello,

I have been trying to install Caffe on the Jetson TX1, 
Its has Ubuntu 16.04, Cuda 8 and CuDNN (I am not sure if some additional information is required here)
I have done make all, make test successfully and I have an error shown below while executing make runtest. 

F1010 16:24:55.615147  4993 pooling_layer.cu:212] Check failed: error == cudaSuccess (7 vs. 0)  too many resources requested for launch
*** Check failure stack trace: ***
    @       0x7faa033718  google::LogMessage::Fail()
    @       0x7faa035614  google::LogMessage::SendToLog()
    @       0x7faa033290  google::LogMessage::Flush()
    @       0x7faa035eb4  google::LogMessageFatal::~LogMessageFatal()
    @       0x7fa8e2e080  caffe::PoolingLayer<>::Forward_gpu()
    @           0x57af38  caffe::Layer<>::Forward()
    @       0x7fa8cec874  caffe::LRNLayer<>::WithinChannelForward()
    @       0x7fa8e0ade0  caffe::LRNLayer<>::Forward_gpu()
    @           0x57af38  caffe::Layer<>::Forward()
    @           0x5c1208  caffe::LRNLayerTest_TestForwardWithinChannel_Test<>::TestBody()
    @           0x9fc614  testing::internal::HandleSehExceptionsInMethodIfSupported<>()
    @           0x9f71d4  testing::internal::HandleExceptionsInMethodIfSupported<>()
    @           0x9e0eb0  testing::Test::Run()
    @           0x9e16e0  testing::TestInfo::Run()
    @           0x9e1d54  testing::TestCase::Run()
    @           0x9e7304  testing::internal::UnitTestImpl::RunAllTests()
    @           0x9fd864  testing::internal::HandleSehExceptionsInMethodIfSupported<>()
    @           0x9f7f5c  testing::internal::HandleExceptionsInMethodIfSupported<>()
    @           0x9e5ff8  testing::UnitTest::Run()
    @           0x56bc10  main
    @       0x7fa86e48a0  __libc_start_main
Makefile:526: recipe for target 'runtest' failed

Could anyone point me in the right direction.

Thanks!

**Comment by beastedboy88** [comment]
Hhhhh

**Comment by ouceduxzk** [comment]
are you on debug mode?

**Comment by coocoky** [comment]
how do you solve? @Crefeda
