### ISSUE TITLE
Question about learn rate in lenet net.

### ISSUE THREAD

**Issue by jonathanxixu** [BVLC/caffe#4831]
I have a question about learn rate, below is some part in lenet_train_test.prototxt. Two lr_mults are defined in layer conv1,  I find that only the first lr_mult is used in layer conv1 to upgrade weight, the second lr_mult is used in layer Insanity1 to upgrade bias.  Do I have an exact understanding?

layer {
  name: "conv1"
  type: "Convolution"
  bottom: "data"
  top: "conv1"
  param {
    lr_mult: 1
  }
  param {
    lr_mult: 2
  }
  convolution_param {
    num_output: 20
    kernel_size: 5
    stride: 1
    weight_filler {
      type: "xavier"
    }
    bias_filler {
      type: "constant"
    }
  }
}
layer {
  name: "pool1"
  type: "Pooling"
  bottom: "conv1"
  top: "pool1"
  pooling_param {
    pool: MAX
    kernel_size: 2
    stride: 2
  }
}
layer {
  name: "Insanity1"
  type: "Insanity"
  bottom: "pool1"
  top: "pool1"
}

**Comment by zeakey** [comment]
Yes you are right, the first `lr_mult` refers to the weight and the other refers to bias.

But NOTE that `lr_mult` is not the real learning rate, it is a factor, the real learning rate is global learning rate multiplies lr_mult.

**Comment by jonathanxixu** [comment]
@zeakey Thanks for your answer. It's a little weird. Why not put lr_mult2 into layer insanity?

**Comment by jonathanxixu** [comment]
Got it. I had a wrong understanding.

**Comment by shelhamer** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
