### ISSUE TITLE
Running Caffe on Titan x Pascal - Windows

### ISSUE THREAD

**Issue by mkyaqub** [BVLC/caffe#4834]
Hi,
I have been trying to compile Caffe on Windows with the new GPU Titan X Pascal. I have managed to make it compile by using Cuda 7.5, cuDNN 4, Visual studio 2013 and with Python and Matlab support. However, when I try to train a model, I keep getting the following error:

F1012 08:24:58.364405  6516 math_functions.cu:375] Check failed: status == CURAND_STATUS_SUCCESS (201 vs. 0)  CURAND_STATUS_LAUNCH_FAILURE

I tried the following and also got the same error:
1- I tried disabling cuDNN and then recompiled Caffe which was fine but when I tried to train a model, I got the same error.

2- I uninstalled Cuda, then installed installed Cuda 8.0, cuDNN 5.2. I managed to compile Caffe (with and without cuDNN) but again got the same error when I tried to train a model.

3- I tried to train the same model on a different PC which has Palit NVIDIA GTX TITAN X, Cuda 7.5, cuDNN 4, visual studio 2013, with Python support. Everything was fine and managed to train the same model and got reasonable accuracy on my problem.

4- I tried to train a model using MatConvNet using the Titan X Pascal and Cuda 8 and it worked fine.

If you have any suggestion, please advise. Thanks!

Regards,

**Comment by willyd** [comment]
@mkyaqub

> 3- I tried to train the same model on a different PC which has Palit NVIDIA GTX TITAN X, Cuda 7.5, cuDNN 4, visual studio 2013, with Python support. Everything was fine and managed to train the same model and got reasonable accuracy on my problem.

Did you rebuild caffe on this machine? If so, to me it looks like nvcc does not compile the cuda code with a compatible architecture. Please review the nvcc compiler flags to make sure that you generate PTX files with the correct architecture.

> 2- I uninstalled Cuda, then installed installed Cuda 8.0, cuDNN 5.2. I managed to compile Caffe (with and without cuDNN) but again got the same error when I tried to train a model.

Were you able to build the windows branch with CUDA 8, and cuDNN 5.2 without making any changes?

**Comment by mkyaqub** [comment]
Thanks Willyd,

Can you please elaborate on how to review  the nvcc compiler flags?

Yes, I managed to compile Caffe on Windows with Cuda 8.0. The steps are:
Install Cuda 8.0, disable cuDNN in the CommonSettings file (apologies I said I succeeded with cuDNN but I did not. I got confused with the many things I tried). Launch the caffe solution in VS2013 and compile. I tested by training an FCN model on the CPU and it was fine.
Here are the two changes you need to do in the CommonSettings file
<UseCuDNN>false</UseCuDNN>
        <CudaVersion>8.0</CudaVersion>

BTW, I realized that Titan X Pascal uses compute 6.1 architecture while the older GTX Titan X uses 5.2 architecture so I tried to change cuda architecture tag in the CommonSettings file to 6.1. Caffe compiled fine after a few iterations but I still got the same error.
I changed this line <CudaArchitecture>compute_35,sm_35;compute_52,sm_52</CudaArchitecture> to 
<CudaArchitecture>compute_61,sm_61</CudaArchitecture>

,

**Comment by willyd** [comment]
@mkyaqub 

Check the CUDA C/C++ settings and look for NVCC Compilation Type. 

Here is what I think is happening:

CUDA 7.5 does not know about compute_61,sm_61 s changing will either generate an error of fail silently. 

So in order to run on a pascal GPU you need to either build with CUDA 8 or change the nvcc flags so that it generates PTX instead of obj.

So if you really change the CommonSettings to use CUDA 8 and added the correct 6.1 architecture I have no idea what is wrong here. 

Check the Command Line section in the CUDA C/C++ to make sure what verison of nvcc is called.

Alternatively, you may want to check my PR https://github.com/BVLC/caffe/pull/3990 and try the cmake build instead.

**Comment by mkyaqub** [comment]
Thanks willyd,

I was frustrated as I was not been able to resolve this. So I stopped experimenting any other solution and kept my Caffe windows configuration as Cuda 8, no cuDNN, Python and Matlab support. Today, for no obvious reason, I ran a Caffe training code on the GPU and it worked. I am totally surprised but happy. 

Sorry I don't have a proper route to the solution but I can confirm that I managed (after many tries) to compile and run FCN training experiments using Caffe on Windows with Titan X Pascal GPU. Here is the list of packages I used: Caffe from the Window branch, MS visual studio 2013, Cuda 8.0, No cuDNN support, Python and Matlab support.  I had to change the following in the CommonSettings file:

```
<UseCuDNN>false</UseCuDNN>
<CudaVersion>8.0</CudaVersion>
<PythonSupport>True</PythonSupport>
<MatlabSupport>True</MatlabSupport>
<CudaArchitecture>compute_61,sm_61</CudaArchitecture> <!-- this is probably the most important thing-->

PropertyGroup Condition="'$(PythonSupport)'=='true'">
        <PythonDir>C:\Anaconda2\</PythonDir>
        <LibraryPath>$(PythonDir)\libs;$(LibraryPath)</LibraryPath>
        <IncludePath>$(PythonDir)\include;$(IncludePath)</IncludePath>
    </PropertyGroup>

    <PropertyGroup Condition="'$(MatlabSupport)'=='true'">
        <MatlabDir>C:\Program Files\MATLAB\R2015b</MatlabDir>
        <LibraryPath>$(MatlabDir)\extern\lib\win64\microsoft;$(LibraryPath)</LibraryPath>
        <IncludePath>$(MatlabDir)\extern\include;$(IncludePath)</IncludePath>
    </PropertyGroup>
```

I hope this helps

**Comment by raymondsa** [comment]
I had  the same error when i run faster CNN+WIN10+MATLAB2015+CUDA 8.0 GPU  GTX1080.
The solution was:
https://github.com/ShaoqingRen/caffe/tree/faster-R-CNN

**Comment by willyd** [comment]
Closing because the VS build is now deprecated.
