### ISSUE TITLE
Should there be a Reshape function for contrastive_loss_layer 

### ISSUE THREAD

**Issue by s455176** [BVLC/caffe#4835]
It seems that there is no Reshape function implemented for contrastive_loss_layer. 
So the batch size will be determined during the layer setup and cannot be changed, otherwise the calculation of loss will be incorrect.  
Is it reasonable or convenient to add Reshape function so that we can have a dynamic batch size? 

Thanks!

**Comment by shaibagon** [comment]
There is no need for mem allocation in contrastive loss layer, therefore there is no need for **explicit** reshape function. During loss computation (`forward`) caffe takes into account the current batch size of the input.
