### ISSUE TITLE
Undefined variable or function 'caffe'

### ISSUE THREAD

**Issue by samad968** [BVLC/caffe#4837]
I successfully compiled caffe on ubuntu 14.04, but  runnig code on matlab R2015b, stoped with error "Undefined variable or function 'caffe'. NET_SURGERY line 13. caffe('reset')".
How can I solve this problem? Any help would be appreciated.

Thanks.

**Comment by shelhamer** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
