### ISSUE TITLE
To Brodyh

### ISSUE THREAD

**Issue by blasheroy** [BVLC/caffe#4838]
Hello guys, I was facing an runtime error while I was trying to run the filter_visualization_car_deeppy provided by you in Brodyh/caffe. 
RuntimeError: Could not open file /deep/u/willsong/caffe/models/brody/deploy_deeppy.prototxt
Is it anyway I can find the models?

**Comment by shelhamer** [comment]
Please direct questions about forks to the relevant fork. The issue tracker is only for BVLC/caffe.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
