### ISSUE TITLE
Error when using  “fcn.berkeleyvision.org”

### ISSUE THREAD

**Issue by liruihao** [BVLC/caffe#4841]
Dear Shelhamer,

I could not pull issues in shelhamer/fcn.berkeleyvision.org, so I come here to ask for help.

I try to use your FCN within fcn.berkeleyvision.org. And when I try "python ./ruihao_file/fcn.berkeleyvision.org/voc-fcn32s/solve.py ", it told me that 

"line 5, in <module>
    import surgery, score
ImportError: No module named surgery".

Then I copy "../surgery.py" and "../score.py" to file "voc-fcn32" and try again. “surgery” and  "score" are imported successfully. However, there is a new error.

"import setproctitle
ImportError: No module named setproctitle"

I have already installed setproctitle. Do you know how can I solve this problem? Do you use Python3 in caffe? Should I compile python3 with caffe? 

Thank you very much for help.

Regards,

Ruihao

**Comment by MathiasStokholm** [comment]
Hey @liruihao,

Caffe looks for custom layers in your PYTHONPATH environment variable, or in your current directory. In your case when running
```bash
python ./ruihao_file/fcn.berkeleyvision.org/voc-fcn32s/solve.py
```
Caffe will search `ruihao_file/..` for the surgery.py file, but the file is really located in the `fcn.berkeleyvision.org` directory. 
To remedy this issue, you can:
1. Change directory to `fcn.berkeleyvision.org` and run the script
2. Add `fcn.berkeleyvision.org` to your PYTHONPATH

**Comment by liruihao** [comment]
Dear @MathiasStokholm : 

Thank you very much for your reply.

I added  fcn.berkeleyvision.org to my PYTHONPATH by revising the file "solve.py"

`import os,sys
sys.path.append('./ruihao_file/fcn.berkeleyvision.org')`

It can import surgery and score, but It can still not import setproctitle. Do you how could  I solve it? Should I compile python3 with caffe?

Thank you very much for help.

Regards,

Ruihao

**Comment by MathiasStokholm** [comment]
@liruihao,

You need to install the `setproctitle` library, e.g. by using pip:
```bash
pip install setproctitle
```

**Comment by liruihao** [comment]
@MathiasStokholm  I am very appreciated for your help. But I have new problems as blow. And I think it is an caffe version problem. But from (https://groups.google.com/forum/#!topic/caffe-users/0ySY1PLf3pM) @Shelhamer said that the reference models posted to http://fcn.berkeleyvision.org are compatible with master.  Could you help me ?

WARNING: Logging before InitGoogleLogging() is written to STDERR
I1014 11:32:34.881177 27398 solver.cpp:48] Initializing solver from parameters: 
train_net: "train.prototxt"
test_net: "val.prototxt"
test_iter: 736
test_interval: 999999999
base_lr: 1e-10
display: 20
max_iter: 100000
lr_policy: "fixed"
momentum: 0.99
weight_decay: 0.0005
snapshot: 4000
snapshot_prefix: "snapshot/train"
test_initialization: false
average_loss: 20
iter_size: 1
I1014 11:32:34.881278 27398 solver.cpp:81] Creating training net from train_net file: train.prototxt
[libprotobuf ERROR google/protobuf/text_format.cc:245] Error parsing text-format caffe.NetParameter: 515:14: Message type "caffe.LayerParameter" has no field named "crop_param".
F1014 11:32:34.881671 27398 upgrade_proto.cpp:68] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: train.prototxt
*** Check failure stack trace: ***
Aborted (core dumped)


Thank you very much for your help.

Kind regards,

Ruihao

**Comment by liruihao** [comment]
Thank you very much for your help.

Finally, I can train and test FCN. However, the output of FCN is 1*w*h. Shelhamer added "voc_helper.py" for loading images + labels and paletting output. Could you tell me how could I tranfer 1-channel output to 3-channels output(colorized) ?

Thank you very much for your patience.

Regards,

Ruihao

**Comment by shelhamer** [comment]
Please ask usage questions on the mailing list.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

**Comment by sara-eb** [comment]
@liruihao @shelhamer @MathiasStokholm   I have downloaded fcn.berkeleyvision.org and I have set up caffe-master. Could you please let me know how can I start running FCN and from which point should I start? I have read the paper and would like to understand the code and running steps. I googled a lot, unfortunately, I could not find an answer to help me since I am beginner. 

Thank you very much for your help

Regards
Sara

**Comment by momozizi** [comment]
Dear Shelhamer
when I run solve.py there is bellow error:
`I0731 11:16:22.524452  6172 layer_factory.cpp:58] Creating layer data
I0731 11:16:22.579455  6172 net.cpp:84] Creating Layer data
I0731 11:16:22.580456  6172 net.cpp:380] data -> data
I0731 11:16:22.580456  6172 net.cpp:380] data -> label
> c:\users\mohsen\desktop\propozal\deeplearning\installcaffe\caffe-windows\semantic_segmentation\fcn_berkeleyvision_org-master\pascalcontext_layers.py(48)setup()
-> self.labels_400 = [label.replace(' ','') for idx, label in np.genfromtxt(self.context_dir + '/labels.txt', delimiter=':', dtype=None)]
(Pdb) c
Traceback (most recent call last):
  File "C:\Users\mohsen\Desktop\Propozal\DeepLearning\InstallCaffe\caffe-windows\semantic_segmentation\fcn_berkeleyvision_org-master\pascalcontext-fcn8s\solve.py", line 20, in <module>
    solver = caffe.SGDSolver('C:/Users/mohsen/Desktop/Propozal/DeepLearning/InstallCaffe/caffe-windows/semantic_segmentation/fcn_berkeleyvision_org-master/pascalcontext-fcn8s/solver.prototxt')
  File "C:/Users/mohsen/Desktop/Propozal/DeepLearning/InstallCaffe/caffe-windows/semantic_segmentation/fcn_berkeleyvision_org-master\pascalcontext_layers.py", line 48, in setup
    self.labels_400 = [label.replace(' ','') for idx, label in np.genfromtxt(self.context_dir + '/labels.txt', delimiter=':', dtype=None)]
  File "C:\Users\mohsen\Anaconda3\envs\firstEnvironment\lib\site-packages\numpy\lib\npyio.py", line 1512, in genfromtxt
    fhd = iter(np.lib._datasource.open(fname, 'rb'))
  File "C:\Users\mohsen\Anaconda3\envs\firstEnvironment\lib\site-packages\numpy\lib\_datasource.py", line 151, in open
    return ds.open(path, mode)
  File "C:\Users\mohsen\Anaconda3\envs\firstEnvironment\lib\site-packages\numpy\lib\_datasource.py", line 501, in open
    raise IOError("%s not found." % path)
OSError: ../../data/pascal-context/labels.txt not found.`
