### ISSUE TITLE
Purpose of set -e and $@ in train_quick.sh in cifar10 example

### ISSUE THREAD

**Issue by manisoftwartist** [BVLC/caffe#4845]
What do set -e and $@ in train_quick.sh in cifar10 example serve?

**Comment by lukeyeager** [comment]
See https://github.com/BVLC/caffe/pull/4459.

**Comment by manisoftwartist** [comment]
So it is to specify multiple GPUs. But in which code is this handled exactly?

**Comment by lukeyeager** [comment]
It's just basic shell scripting. http://tldp.org/LDP/abs/html/othertypesv.html#POSPARAMREF1

**Comment by manisoftwartist** [comment]
thanks @lukeyeager
