### ISSUE TITLE
How to online fine-tune a model?

### ISSUE THREAD

**Issue by fslzj** [BVLC/caffe#4846]
How to online fine-tune a model with C++? Is there any examples?

**Comment by shelhamer** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
