### ISSUE TITLE
Is there a relation between the number of iterations needed and the amount of training data provide ?

### ISSUE THREAD

**Issue by GeorgiAngelov** [BVLC/caffe#4847]
My question is as follow:

If I have only 700 images, would I need a lot of iterations for my model learn as opposed to when I provide say 2000 images ? For example: 50,000 iterations are needed when training with 2000 images and 160,000 iterations are needed when I am training with 2000 images. Does such a relationship exist?

The reason I am asking is because I am currently training a model with only 700 images( many objects in the images ) and 160,000 iterations but the model is really not doing good at all ( I tried both training from scratch and using existing weights ).

Thanks!

**Comment by williford** [comment]
This question should be moved to the Caffe User mailing list or to a stackexchange website (such as stats.stackexchange.com or stackoverflow.com). Please close your question and re-ask it in an appropriate place.

700 images seems like way too few. If you don't have enough training data, showing the same data over and over is only going to make your model over-fit it. You should provide more information on what you are doing. What output is your model giving? Are you making multiple example from a single image (for example, the input could be a location and an image, and the output could be the classification of the input at that image). Are you doing dense labeling (segmentation)? How many parameters are you training with the 700 images?

**Comment by shelhamer** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
