### ISSUE TITLE
"dyld: lazy symbol binding failed" when i ran make runtest on Mac OS 10.9.3

### ISSUE THREAD

**Issue by h1abuirmeileh** [BVLC/caffe#4852]
I have followed the following tutorial:
[http://hoondy.com/2015/04/03/how-to-install-caffe-on-mac-os-x-10-10-for-dummies-like-me/](url)

In the Makefile.config, i have used Atlas instead of intel MKL. The error after running "make runtest" : 

dyld: lazy symbol binding failed: Symbol not found: _OSAtomicDecrement32Barrier
  Referenced from: /usr/local/cuda/lib/libcudnn.5.dylib
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _OSAtomicDecrement32Barrier
  Referenced from: /usr/local/cuda/lib/libcudnn.5.dylib
  Expected in: /usr/lib/libSystem.B.dylib

I have attached the Makefile.config below:
[Makefile.config.txt](https://github.com/BVLC/caffe/files/534012/Makefile.config.txt)

**Comment by shelhamer** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
