### ISSUE TITLE
protoc compiler not found

### ISSUE THREAD

**Issue by maystroh** [BVLC/caffe#4853]
To be able to compile protobuf manually  I was forced to do the following (as suggested in many forums/questions to get caffe works on ubuntu 16.04):

> sudo apt-get autoremove libprotobuf-dev protobuf-compiler

Then, I just grab the source of protobuf library and compiled it manually without any problem and I put it under /usr/local/myprotobuf/

But when I just hit make all to compile caffe, it gives me the following error:

> PROTOC src/caffe/proto/caffe.proto
> make: protoc : command not found
> Makefile:636 : the target of .. « .build_release/src/caffe/proto/caffe.pb.cc » failed
> make: **\* [.build_release/src/caffe/proto/caffe.pb.cc] Error 127

If I do locate libprotoc I got the following:

> /usr/local/myprotobuf/lib/libprotoc.a
> /usr/local/myprotobuf/lib/libprotoc.la
> /usr/local/myprotobuf/lib/libprotoc.so
> /usr/local/myprotobuf/lib/libprotoc.so.9
> /usr/local/myprotobuf/lib/libprotoc.so.9.0.1

So, it's there but not sure why it's not linked properly since I already added the following to my bashrc file:

> export PATH=$PATH:/usr/local/myprotobuf/
> export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/myprotobuf/lib"

That's why I think it should be there but it seems that I'm missing something but not sure what it's. Any clue please..

**Comment by arthur-tacca** [comment]
Considering how you've installed it, I would expect you need a slightly different path:

    export PATH=$PATH:/usr/local/myprotobuf/bin/

Note the trailing `bin/`. It would have been more normal to install the `protobuf` library directly in `/usr/local/` rather than a subdirectory; then you wouldn't need to change any environment variables at all.

**Comment by shelhamer** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
