### ISSUE TITLE
AttributeError: 'module' object has no attribute 'io'

### ISSUE THREAD

**Issue by aquibjaved** [BVLC/caffe#4858]
I am trying a code for gender recognition in real time, If I pass an Image through it, It's working absolutely fine, but when I am trying to pass webcam frames. it Showing me an error:
     `a = caffe.io.caffe_pb2.BlobProto.FromString(proto_data)
        AttributeError: 'module' object has no attribute 'io'`

**Comment by shelhamer** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
