### ISSUE TITLE
model zoo gone?

### ISSUE THREAD

**Issue by EvanWeiner** [BVLC/caffe#4859]
Nothing here:
https://github.com/BVLC/caffe/wiki/Model-Zoo

**Comment by maximus009** [comment]
I'm wondering the same...

**Comment by jeffdonahue** [comment]
Thanks for reporting this. Someone deleted the whole page (apparently intentionally based on the commit message...).  I reverted the change so it's back.  Let me know if anyone knows how to ban users from editing the wiki...
