### ISSUE TITLE
Use the semantic versioning and add a version header file

### ISSUE THREAD

**Issue by kloudkl** [BVLC/caffe#486]
Recently released versions are called 0.9, 0.99 and 0.999. Another popular method to set the number is the [semantic versioning](http://semver.org/). Even HBase, one of the Hadoop ecosystem projects, that has been approaching version 1.0 for a long time names its recent versions as 0.9x.x.

OpenCV updates its version in a [header file](https://github.com/Itseez/opencv/blob/master/modules/core/include/opencv2/core/version.hpp) for the users to know the current version they are using. It also enables CMake to [automatically version some other files](https://github.com/Itseez/opencv/blob/95006af17076e4787e38eb56e5d716d892779daf/cmake/OpenCVVersion.cmake).

**Comment by boaz001** [comment]
:+1:

**Comment by shelhamer** [comment]
Keeping open to remind us of the version header.

**Comment by shelhamer** [comment]
Caffe now declares a version, but we haven't followed semantic versioning practices. Closing as close enough for now.
