### ISSUE TITLE
make runtest errro: 

### ISSUE THREAD

**Issue by anbai106** [BVLC/caffe#4861]
I use Anaconda2 Python, HDF5 is bundled.( at the beginning, I install HDF5 with brew, they give me some warning, the vision of lib and header are different .
so I unistall it)
and when I use make runtest. Caffe can't find the path of HDF5 lib.

$ make runtest
.build_release/tools/caffe
dyld: Library not loaded: libhdf5_hl.10.dylib
  Referenced from: /Users/junhao.wen/Hao/Docker/Caffe/Caffe_source/caffe/.build_release/tools/caffe
  Reason: image not found
make: **\* [runtest] Trace/BPT trap: 5

And in anaconda lib, libhdf5_hl.10.dylib is exit. What's wrong?

In makefile.config :
# Verify anaconda location, sometimes it's in root.

 ANACONDA_HOME := $(HOME)/anaconda2
 PYTHON_INCLUDE := $(ANACONDA_HOME)/include \
         $(ANACONDA_HOME)/include/python2.7 \
         $(ANACONDA_HOME)/lib/python2.7/site-packages/numpy/core/include \
# We need to be able to find libpythonX.X.so or .dylib.
# PYTHON_LIB := /usr/lib

 PYTHON_LIB := $(ANACONDA_HOME)/lib
# Whatever else you find you need goes here.

INCLUDE_DIRS := $(PYTHON_INCLUDE) /usr/local/include 
LIBRARY_DIRS := $(PYTHON_LIB) /usr/local/lib /usr/lib
and

 $ echo $DYLD_FALLBACK_LIBRARY_PATH
/Users/junhao.wen/anaconda2/lib:/usr/local/lib:/usr/lib

Solution 1)
I know there is another post which has the same problem with me, but the answer install_name_tool does not work for me, maybe I use the command in the run way:
sudo install_name_tool -change /Users/junhao.wen/anaconda2/lib/libhdf5_hl.10.dylib @rpath/./libhdf5_hl.10.dylib /libhdf5_hl.10.dylib

here is the output: 
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool: can't open file: /libhdf5_hl.10.dylib (No such file or directory) 
so I guess I use the command in the wrong way:)

Solution 2)
Many people said that we should set the environment variable DYLD_FALLBACK_LIBRARY_PATH, and Ive tried, it doest not work.

Please help me, i have wasted one day to install caffe for my Mac, and I have been stucked by this problem...
Thanks in advance

**Comment by anbai106** [comment]
So if I reinstall brew hdf5, and i rerun make runtest, i got the error:

Warning! ***HDF5 library version mismatched error***
The HDF5 header files used to compile this application do not match
the version used by the HDF5 library to which this application is linked.
Data corruption or segmentation faults may occur if the application continues.
This can happen when an application was compiled by one version of HDF5 but
linked with a different version of static or shared HDF5 library.
You should recompile the application or check your shared library related
settings such as 'LD_LIBRARY_PATH'.
You can, at your own risk, disable this warning by setting the environment
variable 'HDF5_DISABLE_VERSION_CHECK' to a value of '1'.
Setting it to 2 or higher will suppress the warning messages totally.
Headers are 1.8.16, library is 1.8.17
	    SUMMARY OF THE HDF5 CONFIGURATION
	    =================================

General Information:
-------------------
		   HDF5 Version: 1.8.17
		  Configured on: Sun Sep 11 09:55:06 BST 2016
		  Configured by: brew@elcapitanvm.local
		 Configure mode: production
		    Host system: x86_64-apple-darwin15.6.0
	      Uname information: Darwin elcapitanvm.local 15.6.0 Darwin Kernel Version 15.6.0: Mon Aug 29 20:21:34 PDT 2016; root:xnu-3248.60.11~1/RELEASE_X86_64 x86_64
		       Byte sex: little-endian
		      Libraries: static, shared
	     Installation point: /usr/local/Cellar/hdf5/1.8.17

Compiling Options:
------------------
               Compilation Mode: production
                     C Compiler: /usr/local/Library/Homebrew/shims/super/clang ( Apple LLVM version 7.3.0 )
                         CFLAGS:
                      H5_CFLAGS:
                      AM_CFLAGS:
                       CPPFLAGS:
                    H5_CPPFLAGS:   -DNDEBUG -UH5_DEBUG_API
                    AM_CPPFLAGS:  -I/usr/include -I/usr/local/opt/szip/include
               Shared C Library: yes
               Static C Library: yes
  Statically Linked Executables: no
                        LDFLAGS:
                     H5_LDFLAGS:
                     AM_LDFLAGS:  -L/usr/lib -L/usr/local/opt/szip/lib
 	 	Extra libraries: -lsz -lz -ldl -lm
 		       Archiver: ar
 		 	 Ranlib: ranlib
 	      Debugged Packages:
		    API Tracing: no

Languages:
----------
                        Fortran: no

                            C++: yes
                   C++ Compiler: /usr/local/Library/Homebrew/shims/super/clang++ ( Apple LLVM version 7.3.0 )
                      C++ Flags:
                   H5 C++ Flags:
                   AM C++ Flags:
             Shared C++ Library: yes
             Static C++ Library: yes

Features:
---------
                  Parallel HDF5: no
             High Level library: yes
                   Threadsafety: no
            Default API Mapping: v18
 With Deprecated Public Symbols: yes
         I/O filters (external): deflate(zlib),szip(encoder)
                            MPE: no
                     Direct VFD: no
                        dmalloc: no
Clear file buffers before write: yes
           Using memory checker: no
         Function Stack Tracing: no
      Strict File Format Checks: no
   Optimization Instrumentation: no

**Comment by anbai106** [comment]
Ok, I solved the problem by install brew hdf5 with the newest version 1.8.17 and later, i installed hdf5 1.8.16 with the source code, so I copy the 16 to /usr/local/Cellar/hdf5/ and name it to 1.8.16
and run the command brew switch 1.8.16, and it run successfully for make runtest.

But I got another error when I run python -c "import caffe", after I complier pycaffe without error:

python -c 'import caffe'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropSolver, AdaDeltaSolver, AdamSolver
  File "caffe/pycaffe.py", line 15, in <module>
    import caffe.io
  File "caffe/io.py", line 8, in <module>
    from caffe.proto import caffe_pb2
  File "caffe/proto/caffe_pb2.py", line 7, in <module>
    from google.protobuf import descriptor as _descriptor
  File "/Users/junhao.wen/anaconda2/lib/python2.7/site-packages/protobuf-3.1.0-py2.7-macosx-10.6-x86_64.egg/google/protobuf/descriptor.py", line 46, in <module>
    from google.protobuf.pyext import _message
ImportError: dlopen(/Users/junhao.wen/anaconda2/lib/python2.7/site-packages/protobuf-3.1.0-py2.7-macosx-10.6-x86_64.egg/google/protobuf/pyext/_message.so, 2): Symbol not found: __ZNK6google8protobuf10TextFormat17FieldValuePrinter10PrintBytesERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
  Referenced from: /Users/junhao.wen/anaconda2/lib/python2.7/site-packages/protobuf-3.1.0-py2.7-macosx-10.6-x86_64.egg/google/protobuf/pyext/_message.so
  Expected in: flat namespace
 in /Users/junhao.wen/anaconda2/lib/python2.7/site-package


Give me a hand

Thanks in advance

**Comment by shelhamer** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

**Comment by Laowai01** [comment]
i have compiled caffe on Ubuntu 16.04 LTS both with python 2 and python, it is really a hectic process for beginners, for caffe with python 2.7 make sure that your /.local/lib/python2.7/site-packages only contains a version same as you protoc version. protoc version can be checked by entering

`protoc --version`

for me i got problems with python 2.7 because by mistake i installed protbuf 3.0 alpha in python 2.7 site packages, so there was a protobuf error after removing it from python 2.7 site packages everything worked fine
also install python-dev version

`apt-get install the python3.x-dev`

and for python 3.5 make sure you have python 3.0 alpha, if you have both python 2.7 and python 3.x in the system use pip3 otherwise use pip

`pip3 install protobuf==3.0.0-alpha-3`

or another protobuf such as 3.5 version of protobuf.
also do this

`pip3 install python-dateutil --upgrade`

after that do 

`make clean`

`make all -j8`
`make runtest -j8`

`make pycaffe`

after performing make all make runtest steps don't forget to do that

`sudo ldconfig`

hope everything works OK for you.
