### ISSUE TITLE
Segmentation fault while running under .py file. 

### ISSUE THREAD

**Issue by dipanshawucr** [BVLC/caffe#4862]
I have write a new layer as described in wiki page of development. After implementation it give me following segmentation error while saving file into binary proto. I have tried without using the implemented layer. But gives me same error. 
I have only skip Test phase of implementation means didn't implemented test/test_your_layer.cpp. Is it needed to complete the final implementation? Can anyone show me how to do that?
Thanks.

...
...
...
I1019 08:31:24.205308  6239 solver.cpp:244]     Train net output #42258: target_feature = 2.11439
I1019 08:31:24.205325  6239 solver.cpp:244]     Train net output #42259: target_feature = -0.0908065
I1019 08:31:24.205417  6239 sgd_solver.cpp:106] Iteration 0, lr = 0.01
I1019 08:31:24.257143  6239 solver.cpp:454] Snapshotting to binary proto file examples/testclassification/data/train_iter_500.caffemodel
Segmentation fault

Update: I found that the problem occurs when I run it through a .py file with python command.
But it is solved when run with script file. Any one have any idea why this is happening?

Thanks

**Comment by lolongcovas** [comment]
it also happens to me. the new layers were compiled correctly.

**Comment by lolongcovas** [comment]
I solved this issue by change the new layer Id in caffe.proto to the $lastId + 1, 

for example, in this case: https://github.com/BVLC/caffe/blob/master/src/caffe/proto/caffe.proto#L309

**_// LayerParameter next available layer-specific ID: 147 (last added: recurrent_param)_**

you should put 148 for your new layer.
