### ISSUE TITLE
Computational error with K40

### ISSUE THREAD

**Issue by ngmanhei** [BVLC/caffe#4867]
Recently, I tried to run my code on 2 newly bought Tesla K40C GPUs (Single-GPU experiment). Although there was no running error, it produced a wrong computational result (mAP=0.33, while the correct mAP is 0.8 ). However, my code runs normally as usual on other GPU, such as Titan X(not Pascal), GTX980 etc. 
Someone told me that it might be caused by ECC-off GPU mode, so I attempted to turn on it follow [this tutorial](http://caffe.berkeleyvision.org/performance_hardware.html). Unfortunately, it doesn't work !
Is there anyone can help?

**Comment by shelhamer** [comment]
The arch for the GPU type may be incorrect. ECC is essentially irrelevant for deep learning use cases. For K40 check your build to be sure you have compute capability 3.5 enabled. Please ask compilation questions on the mailing list.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
