### ISSUE TITLE
ImportError when implementing Python Layer in Caffe

### ISSUE THREAD

**Issue by yannadani** [BVLC/caffe#4869]
I'm trying to incorporate a custom python data layer to a network in `caffe`. I have built `caffe` with `WITH_PYTHON_LAYER=1` and have added the caffe python modules and the custom python data layer module to `PYTHONPATH`. However, when I try to run it, it gives the following error:
I1020 16:13:35.672911 24362 layer_factory.hpp:74]             
    ImportError: Import by filename is not supported.
    terminate called after throwing an instance of boost::python::error_already_set'
   *** Aborted at 1476960215 (unix time) try "date -d @1476960215" if you are using GNU date ***
   PC: @     0x7fea94390c37 (unknown)     *** SIGABRT (@0x3e800005f2a) received by PID 24362 (TID 0x7fea95db7a40)  from PID 24362; stack trace: ***
        @     0x7fea94390cb0 (unknown)
        @     0x7fea94390c37 (unknown)
        @     0x7fea94394028 (unknown)
        @     0x7fea94995535 (unknown)
        @     0x7fea949936d6 (unknown)
        @     0x7fea94993703 (unknown)
        @     0x7fea94993976 (unknown)
        @     0x7fea955ffe22 caffe::GetPythonLayer<>()
        @     0x7fea95616326 caffe::LayerRegistry<>::CreateLayer()
        @     0x7fea9561b4cc caffe::Net<>::Init()
        @     0x7fea9561d262 caffe::Net<>::Net()
        @     0x7fea955f9139 caffe::Solver<>::InitTrainNet()
        @     0x7fea955fa2f3 caffe::Solver<>::Init()
        @     0x7fea955fa4c6 caffe::Solver<>::Solver()
        @           0x40d030 caffe::GetSolver<>()
        @           0x407143 train()
        @           0x4056e1 main
        @     0x7fea9437bf45 (unknown)
        @           0x405c8d (unknown)
        @                0x0 (unknown)
        Aborted (core dumped)

Any idea why I'm running into this problem? Thanks in advance.

**Comment by lukeyeager** [comment]
Check your value of `python_param { module: }`. It should be a module like `layers.my_layer`, not a file like `layers/my_layer.py`.
https://gist.github.com/lukeyeager/5ae183044d96ef1540f2

**Comment by saicoco** [comment]
Give you a example which is my implement, I input the audio and image data to the network,  https://github.com/saicoco/_practice/tree/master/pycaffe/example_bigbang/build

**Comment by yannadani** [comment]
Thanks all for your responses. I was able to sort this out. My mistake was that I was giving the path to the module as well in `python_param { module: }` in the prototxt. However, this was not required. Just the module name  `python_param { module: }` which was in the `$PYTHONPATH` sufficed.

**Comment by lhoangan** [comment]
I reopen just to expand the question a bit further. Is there a way that we can point to the desired python module "locally", instead of setting $PYTHONPATH, which has quite a global effect on the whole system.

**Comment by sajjo79** [comment]
@lhoangan could you solve this problem.

**Comment by sajjo79** [comment]
Hi, I am writing a python layer and it is used in train.prototxt file. Both files are present in same directory and here is the code used in 
'layer {
  name: "data"
  type: "Python"
  top: "data"
  top: "label"

  python_param {
    module: "seg_input"
    layer: "MySegDataLayer"
    param_str:"{...}"
    }
 }
'
however it is not working and i am getting following message that "seg_input" module not found.

**Comment by lhoangan** [comment]
@sajjo79 unfortunately that I didn't find any way to solve the issue in my question. I am still waiting for contribution and discussion. In my case, I had to manually set ```$PYTHONPATH``` to where my module was for the network to find it.

**Comment by sajjo79** [comment]
Hi, I am using pycharm to compile and run my project. Instead of running from command prompt i used following code:

**> solver = None
> solver = caffe.SGDSolver(solver_file)
> for i in range(2):
>     solver.step(2)
> print 'done'**
it recompiled the instructions and made my program to read seg_input file from current working directory. I think there is something wrong with compilation process. 
However this solution worked for me.

**Comment by Limestones** [comment]
@sajjo79 Hi, what about the method compiled and run by pycharm？could you support a tutorial or guide for the details？
3ku！
