### ISSUE TITLE
Fast R-CNN for caffe-opencl

### ISSUE THREAD

**Issue by SHEKOLDA** [BVLC/caffe#4872]
Hi, I thought of trying to run Faster R-CNN with OpenCL but there only seems to be CUDA implementation for ROI pooling layer and SmoothL1LossLayer. Has anyone tried to implement them for Greentea?

**Comment by naibaf7** [comment]
@SHEKOLDA 
Those layers do not seem to be part of the official BVLC Caffe, is that right?
Can you link me to the CUDA implementation you are referring to?

**Comment by SHEKOLDA** [comment]
@naibaf7 I'm talking about this PR: https://github.com/BVLC/caffe/pull/4163

**Comment by naibaf7** [comment]
@SHEKOLDA 
OK I see... well I will adapt it once it's merged to avoid duplicated work.
But if you already want/need it now then you could of course try to adapt it yourself, analogous to how other OpenCL layers work.
I'm happy to assist you if you have any questions.

**Comment by SHEKOLDA** [comment]
@naibaf7 Thanks a lot. I'll try to figure it out but I'm not very experienced so it might take time.

**Comment by naibaf7** [comment]
@shelhamer Do you have a timeline for #4163 ? Is this close to a merge?

**Comment by SHEKOLDA** [comment]
@naibaf7 So I tried to implement these layers. The problem I faced is with greentea math functions.
So suppose there is a function for CUDA in Fast R-CNN :

`caffe_gpu_mul(
          count,
          bottom[3]->gpu_data(),
          errors_.gpu_data(),
          errors_.mutable_gpu_data());`

Judging by what I'd seen in other files I changed it to be:

`greentea_gpu_mul(this->device_->id(),
          count,
          (cl_mem)(bottom[3]->gpu_data()),
          (cl_mem)(errors_.gpu_data()),
          (cl_mem)(errors_.mutable_gpu_data()));`

Quite reasonably, I get following errors during make:

> src/caffe/layers/smooth_l1_loss_layer.cu:95:23: error: no matching function for call to ‘greentea_gpu_mul(int, int32_t&, cl_mem, cl_mem, cl_mem)’
       greentea_gpu_mul(this->device_->id(),
                                    ^
In file included from ./include/caffe/blob.hpp:18:0,
                 from ./include/caffe/layers/smooth_l1_loss_layer.hpp:6,
                 from src/caffe/layers/smooth_l1_loss_layer.cu:3:
./include/caffe/greentea/greentea_math_functions.hpp:71:6: note: candidate: template<class Dtype> void caffe::greentea_gpu_mul(int32_t, int32_t, cl_mem, int32_t, cl_mem, int32_t, cl_mem, int32_t)
 void greentea_gpu_mul(const int_tp ctx_id, const int_tp N, const cl_mem a,
        ^
./include/caffe/greentea/greentea_math_functions.hpp:71:6: note:   template argument deduction/substitution failed:
src/caffe/layers/smooth_l1_loss_layer.cu:95:23: note:   cannot convert ‘(cl_mem)((caffe::SmoothL1LossLayer<double>*)this)->caffe::SmoothL1LossLayer<double>::errors_.caffe::Blob<Dtype>::gpu_data<double>()’ (type ‘cl_mem {aka _cl_mem*}’) to type ‘int32_t {aka int}’
       greentea_gpu_mul(this->device_->id(),
                                    ^

> 

So I'd like a little advice on using these math functions since I don't quite get how they work.

**Comment by naibaf7** [comment]
Ok, so, you can look these up here: https://github.com/BVLC/caffe/blob/opencl/include/caffe/greentea/greentea_math_functions.hpp

For example, for mul, it is:
```
void greentea_gpu_mul(const int_tp ctx_id, const int_tp N, const cl_mem a,
                      const int_tp offa, const cl_mem b, const int_tp offb,
                      cl_mem y, const int_tp offy) {
```

so you'd need to also send the offsets, so:
```
greentea_gpu_mul(this->device_->id(), count, (cl_mem)(bottom[3]->gpu_data()), 0, (cl_mem)(errors_.gpu_data()), 0, (cl_mem)(errors_.mutable_gpu_data()), 0);
```

Feel free to ask if there are any more issues :) great that you're trying to do it on your own! :)

**Comment by SHEKOLDA** [comment]
@naibaf7 Thanks a lot, that and some other minor changes heiped and 'make' ran smoothly. It's wierd, though, since I've seen calling such functions without sending offsets in softmax loss layer (at least it seemed so, idk). I haven't made test files yet and couldn't run caffe though. There seem to be some problems related to https://github.com/BVLC/caffe/issues/4188 which I'm going to investigate now.

**Comment by naibaf7** [comment]
@SHEKOLDA 
Sure, just let me know what the errors are that you are getting.

**Comment by SHEKOLDA** [comment]
@naibaf7 Well I ran `./build/test/test_all.testbin --gtest_filter=*OpenCLKernelCompileTest* 0` as you suggested and got errors related to syntax for *.cl files I added but I was able to fix them so that this command results in 2 successful tests. However, running 'make runtest' results in 736 failed tests which is new. Yet it seems to be the problem with drivers - error messages tell 

> ViennaCL: FATAL ERROR: Could not find kernel 'fillbuffer_float' from program 'kernel_program'
Number of kernels in program: 0
unknown file: Failure
C++ exception with description "Kernel not found" thrown in the test body.


and

> Error: Fail to load fglrx kernel module!


which I guess is the result of me using Linux Mint, where fglrx drivers are not supported.

**Comment by naibaf7** [comment]
@SHEKOLDA 
Yes, what GPU are you using? First you should get AlexNet or something else simple to work.
Another tool that's really good for debugging is this command, especially when you want to check if your RNN kernels compile:
```./build/test/test_all.testbin --gtest_filter=*OpenCLKernelCompileTest* X ``` where you replace X by your GPU ID.
To find out what GPUs are available, use:
```./build/tools/caffe device_query ```

But if your GPU supports it, you should really upgrade to a Linux 4.8 kernel and use AMDGPU-PRO instead of FGLRX http://support.amd.com/en-us/kb-articles/Pages/AMD-Radeon-GPU-PRO-Linux-Beta-Driver%E2%80%93Release-Notes.aspx (works at least on Ubuntu and Linux Mint).

**Comment by SHEKOLDA** [comment]
@naibaf7 
Thanks for your advice. Running `./build/tools/caffe device_query` results in following:

> modprobe: FATAL: Module fglrx not found in directory /lib/modules/4.4.0-21-generic
Error: Fail to load fglrx kernel module!
Error! Fail to load fglrx kernel module! Maybe you can switch to root user to load kernel module directly
modprobe: FATAL: Module fglrx not found in directory /lib/modules/4.4.0-21-generic
Error: Fail to load fglrx kernel module!
Error! Fail to load fglrx kernel module! Maybe you can switch to root user to load kernel module directly
modprobe: FATAL: Module fglrx not found in directory /lib/modules/4.4.0-21-generic
Error: Fail to load fglrx kernel module!
Error! Fail to load fglrx kernel module! Maybe you can switch to root user to load kernel module directly
I1026 03:03:19.090320  2634 common.cpp:373] Total devices: 1
I1026 03:03:19.090543  2634 common.cpp:374] CUDA devices: 0
I1026 03:03:19.090553  2634 common.cpp:375] OpenCL devices: 1
I1026 03:03:19.090558  2634 common.cpp:399] Device id:                     0
I1026 03:03:19.090566  2634 common.cpp:401] Device backend:                OpenCL
I1026 03:03:19.090595  2634 common.cpp:403] Backend details:               Advanced Micro Devices, Inc.: OpenCL 2.0 AMD-APP (1912.5)
I1026 03:03:19.090606  2634 common.cpp:405] Device vendor:                 GenuineIntel
I1026 03:03:19.090615  2634 common.cpp:407] Name:                          Intel(R) Core(TM) i7-4500U CPU @ 1.80GHz
I1026 03:03:19.090621  2634 common.cpp:409] Total global memory:           8246550528


which obviously indicates that caffe only 'recognises' my CPU. Running `inxi -G` gives the following:

> Graphics:  Card-1: Intel Haswell-ULT Integrated Graphics Controller
           Card-2: Advanced Micro Devices [AMD/ATI] Venus XT [Radeon HD 8870M / R9 M270X/M370X]
           Display Server: X.Org 1.18.4 drivers: ati,radeon,intel (unloaded: fbdev,vesa)
           Resolution: 1600x900@60.01hz
           GLX Renderer: Mesa DRI Intel Haswell Mobile GLX Version: 3.0 Mesa 12.1.0-devel

So, I know quite little about hardware. I guess the first card is integrated with Intel CPU and the second one is the one I'm interested in, but lacks the appropriate driver. I believe using Intel SDK with integrated device wouldn't help much in speeding up the computation.

Really sorry to bother you with such off-topic questions. Attaching the testing log file, maybe there is some useful info but seems that my problem is not related to caffe.
 
[log.txt](https://github.com/BVLC/caffe/files/552081/log.txt)

**Comment by shelhamer** [comment]
@naibaf7 https://github.com/BVLC/caffe/issues/4872#issuecomment-255534470 will have a look after the ICLR/CVPR deadlines. no reason not to include the layers in principle since fast(er) R-CNN is a popular application.

**Comment by naibaf7** [comment]
@SHEKOLDA 
Yes unfortunately your system is not very well suited for OpenCL under Linux, due to the current state of AMD's neglected drivers.
For Intel, you can try this: https://software.intel.com/en-us/articles/opencl-drivers
For AMD, please try this, but I need to warn you it could result in catastrophic non-working graphics: http://support.amd.com/en-us/kb-articles/Pages/AMD-Radeon-GPU-PRO-Linux-Beta-Driver%E2%80%93Release-Notes.aspx

**Comment by naibaf7** [comment]
@SHEKOLDA 
You can try to get this done with the windows branch now if you want.
