### ISSUE TITLE
How to resize mean_file instead of resizing my lmdb?

### ISSUE THREAD

**Issue by Shine41** [BVLC/caffe#4873]
Here is the problem, I hope to fine-tune a network and when I do this, the error comes out:

_I1020 21:58:32.243350 15732 layer_factory.hpp:77] Creating layer data
I1020 21:58:32.267315 15732 net.cpp:91] Creating Layer data
I1020 21:58:32.267349 15732 net.cpp:399] data -> data
I1020 21:58:32.267393 15732 data_transformer.cpp:25] Loading mean file from: /home/ying/Desktop/My_RenderForCNN/caffe_models/imagenet_mean.binaryproto
I1020 21:58:32.341429 15737 db_lmdb.cpp:35] Opened lmdb /home/ying/Desktop/My_RenderForCNN/data/syn_lmdbs/syn_lmdb_train_image
I1020 21:58:32.590544 15732 data_layer.cpp:41] output data size: 64,3,227,227
I1020 21:58:32.649722 15732 net.cpp:141] Setting up data
I1020 21:58:32.649780 15732 net.cpp:148] Top shape: 64 3 227 227 (9893568)
I1020 21:58:32.649791 15732 net.cpp:156] Memory required for data: 39574272
I1020 21:58:32.649802 15732 layer_factory.hpp:77] Creating layer label
I1020 21:58:32.649905 15732 net.cpp:91] Creating Layer label
I1020 21:58:32.649924 15732 net.cpp:399] label -> label
I1020 21:58:32.652168 15739 db_lmdb.cpp:35] Opened lmdb /home/ying/Desktop/My_RenderForCNN/data/syn_lmdbs/syn_lmdb_train_label_
**F1020 21:58:32.655133 15738 data_transformer.cpp:63] Check failed: datum_height == data_mean_.height() (227 vs. 256)** 

I understand that it is because the shape of my input image lmdb and the mean_file does not match (227 vs. 256), but **how can I resize the file imagenet_mean.binaryproto? Is there any off-the-shelf code to do this?** 

I know and I surely can resize my lmdb but I'm afraid the previous parameters in the network like _num_output in convolution layer_ may not be appropriate anymore, but if I adjust these parameters to cope with the new lmdb size, I'm not fine-tuning on the previous caffemodel because the number of previous weights and bias or something else does not match my current settings. This is only my guess, correct me if I am wrong, please.

**Comment by cypof** [comment]
You could compute the mean for your new data set, e.g. adapting make_imagenet_mean.sh.
