### ISSUE TITLE
How to check the layer type in Caffe source code

### ISSUE THREAD

**Issue by dalishi** [BVLC/caffe#4874]
Hi sorry if this is not an appropriate place to ask such questions but I really was not able to get an answer in caffe-user.

The BVLC documentation is way too out of date. So every time I want to check some new layers I don't know where to go except checking the source code. For example, if I want check how to use the Euclidean loss layer in prototxt.

Where should I check in source code the layer type that I should put in the prototxt? Is it defined in **caffe.proto**? But I can not find anything about this word "**EuclideanLoss**" (given by BVLC documentation) type in **caffe.proto**. The only thing I can find in **caffe.proto** is **EUCLIDEAN_LOSS = 7** under message **V1LayerParameter**. So or should I directly put the layer **type: EUCLIDEAN_LOSS**??

```
layer {
  name: "pool1"
  type: "EuclideanLoss"  # or EUCLIDEAN_LOSS
  ....
}
```

**Comment by cypof** [comment]
There is a REGISTER_LAYER_CLASS macro used by each layer, that's the name to use.
