### ISSUE TITLE
Python function problem: no error information provides when prototxt parses error.

### ISSUE THREAD

**Issue by thesby** [BVLC/caffe#4876]
There is a problem that no error info provides when prototxt parses error in python. Beacause I want to use python to test my model, I create a `deploy.prototxt`. Maybe there is something wrong in it, but I cannot find out the exact line. The stack trace is empty, maybe it's not printed in time while the program exits. I think it's the problem of python, since in c++ the stack trace should be printed.

**Comment by shelhamer** [comment]
Please ask usage questions on the mailing list. It sounds like your error output for Python might not be configured as you like. Normally pycaffe will likewise report traces.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
