### ISSUE TITLE
Is it symbolic link about libcudart.so.5.5 or then cuda version problem?

### ISSUE THREAD

**Issue by linrio** [BVLC/caffe#4877]
Hi,
My computer has CentOS system, when I executed `make all`. It appear following error:

```
NVCC src/caffe/solvers/rmsprop_solver.cu
NVCC src/caffe/solvers/adam_solver.cu
AR -o .build_release/lib/libcaffe.a
LD -o .build_release/lib/libcaffe.so
CXX tools/test_net.cpp
CXX/LD -o .build_release/tools/test_net.bin
/usr/bin/ld: warning: libcudart.so.5.5, needed by /usr/local/lib/libopencv_core.so, may conflict with libcudart.so.6.0
```

I guess then version of cuda has problem. after `$nvcc -V`,

```
nvcc: NVIDIA (R) Cuda compiler driver Copyright (c) 2005-2013 NVIDIA Corporation Built on Wed_Jul_17_18:36:13_PDT_2013 Cuda compilation tools, release 5.5, V5.5.0
```

And then I run `$whereis cuda`, it shows
`cuda: /usr/local/cuda/lib` . In this file, it has **libcudart.so.6.0** (Why after executing `whereis cuda`, it return above ? However, **libcudart.so.5.5** is in  _/usr/local/cuda-5.5/lib_

in the LD_LIBRARY_PATH, I export the _usr/local/cuda-5.5.0/lib_ to it, but it still throw out above problem, how to solve it?

**Comment by linrio** [comment]
Do this problem is the same as #3787 ? But I do not want to rebuild the opencv.

**Comment by JonBoyle87** [comment]
All that warning means is that you've got two versions of CUDA installed, and OpenCV has been compiled by one. It might cause some problems down the line, but personally I've never had problems when those warnings appear.

If you do want to get rid of it, you will have to rebuild OpenCV, and make sure it's pointing to the newer version of CUDA.
