### ISSUE TITLE
Convolution padding check

### ISSUE THREAD

**Issue by fps7806** [BVLC/caffe#4879]
I was playing around with the convolution paddings, for my case I wanted to add uneven padding to left and right of the image.  Which is not possible in the current implementation.

Then I went on with adding extra padding to left and right, but the convolution layer doesn't properly handle large paddings. In my case, a 4x4 filter can only have 2 padding pixels on each side. More than 2 pixels of padding is just ignored (Although the reshape layer doesn't ignore it).

If that is by design, the reshape layer should account for that.

**Comment by cypof** [comment]
Thks, unlikely to implement at this point.

**Comment by hcharaya** [comment]
I am also facing the same issue. Even if caffe doesn't support uneven padding is there any alternate way to achieve this(computation complexity doesn't matter)
