### ISSUE TITLE
caffe installation error with protobuf 

### ISSUE THREAD

**Issue by ouceduxzk** [BVLC/caffe#4880]
I install caffe on centos with non-root server, all those decencies are built locally. I have sucessfully intalled caffe with protobuf before. But recently, I install the newest caffe with protobuf 3.1,  there is one error : 

generated_message_util.h:120: error: undefined reference to 'google::protobuf::internal::fixed_address_empty_string'

I even tried other 2.5, 2.6 of protobuf, there are other problems popping out.
Not sure why this happens. 
Thanks in advance.

**Comment by shelhamer** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
