### ISSUE TITLE
Modifying padded values for convolution layer

### ISSUE THREAD

**Issue by TianweiXing** [BVLC/caffe#4881]
I want to modify the Caffe code for specific use: change padded values from 0 to 1
Originally, in "ConvolutionLayer", the feature map can be padded with zeros to extend the output size.
However, I want to change the padded value----pad the feature map with "1" instead of "0".

I looked at the source code, it seems that "conv_layer.cpp/.hpp/.cu" all need modification.
But I didn't find where the "0" padded value is defined in the codes.

So I'm not sure which file should I modify to get a different padding value for ConvolutionLayer...

Thanks!

**Comment by williford** [comment]
Wouldn't it be equivalent to subtract the input to the layer by 1?

**Comment by TianweiXing** [comment]
@williford , Hi,
1,Do you mean keep the source code, and modify the network structure? Or modify the input of "conv_layer.cpp"? Could you be more specific about it? 
2, I think it should be "add the input by 1", is that right?
Thanks

**Comment by williford** [comment]
Yes, keep the source code and modify the network structure or parameters.

I'm guessing you want to pad the input by its mean value. So if the mean(input)=1, then subtracting one from it makes mean(input-1)=0. So then, when the network is padded by 0, it is being padded by its mean value. Typically, the input of networks is subtracted by its mean value.

I think this conversation should be redirected to the Caffe user mailing list, and you should close this issue.
