### ISSUE TITLE
Achieve more pooling type

### ISSUE THREAD

**Issue by 09876qwrte** [BVLC/caffe#4882]
Hi，I find there only three types of pooling in caffe，Can you achieve more pooling type,such as Lp-pooling Mixed pooling and Spatial pyramid pooling

**Comment by williford** [comment]
Spatial pyramid pooling: https://github.com/BVLC/caffe/pull/2177

**Comment by 09876qwrte** [comment]
@williford Thank you very much，Do you know the implement of s Lp-pooling and Mixed pooling

**Comment by williford** [comment]
From what I could find, they are not implemented yet. I might be interested in implementing either Lp or L2 pooling at some point, but no promises 😄 .

Regarding mixed pooling, the answer seems to be no:
#2318

You might want to reference the papers for posteriority's sake, but you should close this issue and, if desired, follow up on the Caffe user group. There might be someone who has already implemented them and did want to merge it into the main Caffe fork (which can take a lot of time).
