### ISSUE TITLE
make pycaffe error1

### ISSUE THREAD

**Issue by ysyscool** [BVLC/caffe#4891]
Hi all, 

I have  already done successfully make all, make test and make runtest.

When I make pycaffe, I get the following problems:

CXX/LD -o python/caffe/_caffe.so python/caffe/_caffe.cpp
python/caffe/_caffe.cpp: In function ‘boost::shared_ptrcaffe::Net<float > caffe::Net_Init(std::string, int, int, const boost::python::api::object&, const boost::python::api::object&)’:
python/caffe/_caffe.cpp:107:57: error: no matching function for call to ‘caffe::Net<float>::Net(std::string&, caffe::Phase, const int&, std::vectorstd::basic_string<char >_)’
         static_cast<Phase>(phase), level, &stages_vector));
                                                         ^
python/caffe/_caffe.cpp:107:57: note: candidates are:
In file included from ./include/caffe/blob.hpp:8:0,
                 from ./include/caffe/caffe.hpp:7,
                 from python/caffe/_caffe.cpp:17:
./include/caffe/net.hpp:320:27: note: caffe::Net<Dtype>::Net(const caffe::Net<Dtype>&) [with Dtype = float]
   DISABLE_COPY_AND_ASSIGN(Net);
                           ^
./include/caffe/common.hpp:37:3: note: in definition of macro ‘DISABLE_COPY_AND_ASSIGN’
   classname(const classname&);\
   ^
./include/caffe/net.hpp:320:27: note:   candidate expects 1 argument, 4 provided
   DISABLE_COPY_AND_ASSIGN(Net);
                           ^
./include/caffe/common.hpp:37:3: note: in definition of macro ‘DISABLE_COPY_AND_ASSIGN’
   classname(const classname&);\
   ^
In file included from ./include/caffe/caffe.hpp:12:0,
                 from python/caffe/_caffe.cpp:17:
./include/caffe/net.hpp:27:12: note: caffe::Net<Dtype>::Net(const string&, caffe::Phase, const caffe::Net<Dtype>_) [with Dtype = float; std::string = std::basic_string<char>]
   explicit Net(const string& param_file, Phase phase,
            ^
./include/caffe/net.hpp:27:12: note:   candidate expects 3 arguments, 4 provided
./include/caffe/net.hpp:26:12: note: caffe::Net<Dtype>::Net(const caffe::NetParameter&, const caffe::Net<Dtype>_) [with Dtype = float]
   explicit Net(const NetParameter& param, const Net_ root_net = NULL);
            ^
./include/caffe/net.hpp:26:12: note:   candidate expects 2 arguments, 4 provided
make: **\* [python/caffe/_caffe.so] Error 1

Anyone can help me?

**Comment by williford** [comment]
Did you ask your question on the caffe-user mailing list.
