### ISSUE TITLE
Check failed: data_

### ISSUE THREAD

**Issue by JonBoyle87** [BVLC/caffe#4893]
I've been having numerous problems with getting Caffe to work right. I've got a slightly modified AlexNet implementation from NVIDIA Digits (note, I'm not using digits right now, I'm trying to do things with just pure Caffe). When I try to train, I'm getting the following error/stack trace.

I'm using master branch as of a few days ago.

F1021 15:31:23.666375 30299 blob.cpp:115] Check failed: data_ 
*** Check failure stack trace: ***
    @     0x7f72e4994274  google::LogMessage::Fail()
    @     0x7f72e49941bb  google::LogMessage::SendToLog()
    @     0x7f72e4993b92  google::LogMessage::Flush()
    @     0x7f72e4996bef  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f72e4764a6e  caffe::Blob<>::mutable_cpu_data()
    @     0x7f72e47811ca  caffe::GaussianFiller<>::Fill()
    @     0x7f72e47cdb3e  caffe::InnerProductLayer<>::LayerSetUp()
    @     0x7f72e48c7915  caffe::Net<>::Init()
    @     0x7f72e48c87b5  caffe::Net<>::Net()
    @     0x7f72e48ad8fa  caffe::Solver<>::InitTrainNet()
    @     0x7f72e48aeb0c  caffe::Solver<>::Init()
    @     0x7f72e48aee3a  caffe::Solver<>::Solver()
    @     0x7f72e48a1973  caffe::Creator_SGDSolver<>()
    @           0x411fd6  caffe::SolverRegistry<>::CreateSolver()
    @           0x40af52  train()
    @           0x40898c  main
    @     0x7f72e2e19f45  __libc_start_main
    @           0x409293  (unknown)
Aborted (core dumped)

I have no idea what this means, would someone be able to help me figure out what's going on?

I've currently got Caffe built (Ubuntu 14.04) from the github master, and I've attached the prototxt files I'm using. The training set of images I'm using are of numpy shape (3, 256, 256) each before placing them in the lmdb. If any more information is needed, let me know and I'll try to get back asap.

(Just to note, I tried asking on the google groups here https://groups.google.com/forum/#!topic/caffe-users/KGNyqg2hs4s.)

These are I think the relevant files showing the setup/log. I put .txt on the end of them as github wouldn't allow an upload of .prototxt files.
[testout.txt](https://github.com/BVLC/caffe/files/550171/testout.txt)
[digits-alex.lmdb.prototxt.txt](https://github.com/BVLC/caffe/files/550172/digits-alex.lmdb.prototxt.txt)
[solver.prototxt.txt](https://github.com/BVLC/caffe/files/550173/solver.prototxt.txt)

Thanks in advance.

**Comment by williford** [comment]
I've responded to your email on caffe-users (your link included a period, but should be https://groups.google.com/forum/#!topic/caffe-users/KGNyqg2hs4s). You might also want to try StackOverflow.

Unfortunately, the Caffe maintainers are not able to debug everyone's code and posting such requests here interferes with the ability of the maintainers to work on improving Caffe.

**Comment by JonBoyle87** [comment]
Thank you for your response. In the end, it turns out that I was missing a num_output parameter in the final innerproduct layer.

I would like to suggest Caffe should have more diagnostics checks to determine if the network it's about to run is valid, and tell the use if it's missing parameters necessary to run. However, that is not a topic for this issue, hence closing.
