### ISSUE TITLE
blobs_lr vs lr_mult in caffe?

### ISSUE THREAD

**Issue by junglezax** [BVLC/caffe#4896]
I was confused about the difference of blobs_lr and lr_mult.

And now I think they are both have same meaning, and blobs_lr has been deprecated already.
When updating photo, blobs_lr will replaced by lr_mult.

It my understanding right?

I Know it because of this line:
./caffe/util/upgrade_proto.cpp:728:
             layer_param->mutable_param(i)->set_lr_mult(v1_layer_param.blobs_lr(i));

**Comment by williford** [comment]
This is correct, `lr_mult` replaces `blobs_lr`.

This is the old format for specifying the weights and bias for both the learning rate and decay (where `{{ var_name }}` should be replaced as a number - this is from my Jinja2 templates I use to help create prototxts for different versions of Caffe):

    blobs_lr: {{ weight_lr_mult }} blobs_lr: {{ bias_lr_mult }} weight_decay: {{ weight_decay }} weight_decay: {{ bias_decay }}

And this is the new format:

    param { lr_mult: {{ weight_lr_mult }} decay_mult: {{ weight_decay }} } param { lr_mult: {{ bias_lr_mult }} decay_mult: {{ bias_decay }} }

**Comment by shelhamer** [comment]
Thanks @williford for fielding the question and reminding that caffe-users is the right venue!

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
