### ISSUE TITLE
Caffe installation error on Mac

### ISSUE THREAD

**Issue by anbai106** [BVLC/caffe#4898]
16:07 (1 hour ago)

Hello, I have a problem to install caffe on my Mac, I have to say that it is really annoyed to install, when I installed protobuf(which is also a disaster) use the brew that you recommanded, but I got error, and I got answer from protobuf group, they told me that they dont maintain protobuf for brew now, they suggested me to install protobuf from the source, which is a mess from their website, but finally I made it for several days,
So here is the problem, when i run make all from caffe root, I got this error:

> clang: warning: argument unused during compilation: '-pthread'
> Undefined symbols for architecture x86_64:
>   "leveldb::DB::Open(leveldb::Options const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, leveldb::DB*_)", referenced from:
>       caffe::db::LevelDB::Open(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, caffe::db::Mode) in db_leveldb.o
> ld: symbol(s) not found for architecture x86_64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> make: *_\* [.build_release/lib/libcaffe.so.1.0.0-rc3] Error 1

I searched from google and I put some posters for caffe and protobuf, but rarely got answer, because i am not familiar with C/C++, so this kind of installation is really disaster for me, and your installation instruction is not so good to follow, I really want to say that it is not so user-friendly.....

If there is someone who is kind enough to help me, thanks in advance

**Comment by dhruvkakadiya** [comment]
@anbai106 First fix would be, if you're using CPU-only mode, then set **use_libstdcpp** to **false** in your cmake config.
In CMakeCache.txt :
`USE_libstdcpp:BOOL=FALSE`
Still for more information visit [this](https://github.com/BVLC/caffe/issues/2018) thread.

**Comment by shelhamer** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
