### ISSUE TITLE
Using Matcaffe, Solver scaffolding done then matlab crashed.

### ISSUE THREAD

**Issue by kalyo-zjl** [BVLC/caffe#4899]
Hello, I am in trouble, and need your help!!!
when I'm use caffe with matlab interface, I can successfully run the code

caffe_net = caffe.Net(train_val.prototxt, 'train');

but, when I use 

caffe_solver = caffe.Solver(solver.prototxt);

It showed 'Solver scaffolding done' then matlab crashed.  Is anyone has the same problem? 

solver.prototxt is like below.

net: "PATH/TO/train_val.prototxt"
test_iter: 1000
test_interval: 1000
base_lr: 0.01
lr_policy: "step"
gamma: 0.1
stepsize: 100000
display: 20
max_iter: 450000
momentum: 0.9
weight_decay: 0.0005
solver_mode: GPU

I really need your help, thanks! T_T

**Comment by Syf1993** [comment]
I am also facing the same problem,can you tell me how to solve this problem?

**Comment by kalyo-zjl** [comment]
@Syf1993 
I wrote a new layer in caffe with some bug in cpp file which caused the problem. I solved it by debugger the bug in cpp file.

**Comment by Syf1993** [comment]
I still don't know where I went wrong. But thank you very much
