### ISSUE TITLE
Something wrong with `make runtest`

### ISSUE THREAD

**Issue by Narukamiko** [BVLC/caffe#4902]
7fad7c574000-7fad7c578000 rw-p 00000000 00:00 0 
7fad7c578000-7fad7c58e000 r-xp 00000000 08:03 4928727                    /usr/local/lib/libboost_filesystem.so.1.61.0
7fad7c58e000-7fad7c78e000 ---p 00016000 08:03 4928727                    /usr/local/lib/libboost_filesystem.so.1.61.0
7fad7c78e000-7fad7c78f000 rw-p 00016000 08:03 4928727                    /usr/local/lib/libboost_filesystem.so.1.61.0
7fad7c78f000-7fad7c7b1000 r-xp 00000000 08:03 4928719                    /usr/local/lib/libboost_thread.so.1.61.0
7fad7c7b1000-7fad7c9b0000 ---p 00022000 08:03 4928719                    /usr/local/lib/libboost_thread.so.1.61.0
7fad7c9b0000-7fad7c9b3000 rw-p 00021000 08:03 4928719                    /usr/local/lib/libboost_thread.so.1.61.0
7fad7c9b3000-7fad7c9b5000 r-xp 00000000 08:03 4928713                    /usr/local/lib/libboost_system.so.1.61.0
7fad7c9b5000-7fad7cbb5000 ---p 00002000 08:03 4928713                    /usr/local/lib/libboost_system.so.1.61.0
7fad7cbb5000-7fad7cbb6000 rw-p 00002000 08:03 4928713                    /usr/local/lib/libboost_system.so.1.61.0
7fad7cbb6000-7fad7d31f000 r-xp 00000000 08:21 32770910                   /adddisk/yang/Repos/caffe/build/lib/libcaffe.so.1.0.0-rc3
7fad7d31f000-7fad7d51f000 ---p 00769000 08:21 32770910                   /adddisk/yang/Repos/caffe/build/lib/libcaffe.so.1.0.0-rc3
7fad7d51f000-7fad7d539000 rw-p 00769000 08:21 32770910                   /adddisk/yang/Repos/caffe/build/lib/libcaffe.so.1.0.0-rc3
7fad7d539000-7fad7d53b000 rw-p 00000000 00:00 0 
7fad7d53b000-7fad7d55b000 r-xp 00000000 08:03 2359360                    /lib64/ld-2.12.so/bin/sh: line 1: 17207 Aborted                 (core dumped) /adddisk/yang/Repos/caffe/build/test/test.testbin --gtest_shuffle
make[3]: **\* [src/caffe/test/CMakeFiles/runtest] Error 134
make[2]: **\* [src/caffe/test/CMakeFiles/runtest.dir/all] Error 2
make[1]: **\* [src/caffe/test/CMakeFiles/runtest.dir/rule] Error 2
make: **\* [runtest] Error 2

How can I solve it ?

**Comment by shelhamer** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
