### ISSUE TITLE
how to classify 1-channel input with python wrapper

### ISSUE THREAD

**Issue by shuokay** [BVLC/caffe#491]
I am trying to classify handwritten Chinese characters using caffe. 
My dataset is grayscale. I have trained my net and now I want to make predications. 
However I met problems when using python wrapper. For example: channel_swapper. I have been trying to make  python wrapper flexible to 1-channel input, but I am not very familiar with caffe.
I have found #462 , but that solution can not handle my problem completely.
so, can anyone kindly tell me how to modify the python wrapper to handle 1-channel input?

**Comment by yinyuebabay** [comment]
Hi friend @shuokay 
I have the same error as your 
1. if I unset input_scale, the wrapper complain:
Traceback (most recent call last):
File "pred.py", line 24, in 
predictions = classifier.predict(inputs,oversample=False)
File "/home/gys/caffe/python/caffe/classifier.py", line 77, in predict
for in_ in inputs])
File "/home/gys/caffe/python/caffe/pycaffe.py", line 260, in _Net_preprocess
input_scale = self.input_scale.get(input_name)
AttributeError: 'Classifier' object has no attribute 'input_scale'

2.if I set the input_scale=255: classifier = caffe.Classifier(my_model_file, my_pretrained_file,input_scale=255)
the wrapper complain:
Traceback (most recent call last):
File "pred.py", line 24, in 
predictions = classifier.predict(inputs,oversample=False)
File "/home/gys/caffe/python/caffe/classifier.py", line 77, in predict
for in_ in inputs])
File "/home/gys/caffe/python/caffe/pycaffe.py", line 261, in _Net_preprocess
channel_order = self.channel_swap.get(input_name)
AttributeError: 'Classifier' object has no attribute 'channel_swap'
3. if I set channel_swap(you have tell me unset channel_swap, I just want to see what will happen), the wrapper give similar complain:AttributeError: 'Classifier' object has no attribute 'mean'

could you please tell me how did you do to solve this problem??
