### ISSUE TITLE
Exception: “dot” not found in path in python on mac

### ISSUE THREAD

**Issue by XiaXuehai** [BVLC/caffe#4911]
I want to use `python ./python/draw_net.py ../models/bvlc_reference_caffenet/train_val.prototxt caffenet.png`to draw the caffe net by anaconda python on mac. But I got the error like this:
Traceback (most recent call last):

```
  File "caffe/distribute/python/draw_net.py", line 45, in <module>
    main()
  File "caffe/distribute/python/draw_net.py", line 41, in main
    caffe.draw.draw_net_to_file(net, args.output_image_file, args.rankdir)
  File "/Users/xxh/caffe/distribute/python/caffe/draw.py", line 222, in draw_net_to_file
    fid.write(draw_net(caffe_net, rankdir, ext))
  File "/Users/xxh/caffe/distribute/python/caffe/draw.py", line 204, in draw_net
    return get_pydot_graph(caffe_net, rankdir).create(format=ext)
  File "/Users/xxh/anaconda2/lib/python2.7/site-packages/pydot.py", line 1883, in create
    prog=prog))
Exception: "dot" not found in path.
```

I have installed pydot and graphviz ,and how can I add the dot's path to python path?

**Comment by valentinkozhevnik** [comment]
You don't have "dot" install from source http://www.graphviz.org/pub/graphviz/CURRENT/graphviz-working.tar.gz and all works

**Comment by GabLeRoux** [comment]
As explained here:
http://stackoverflow.com/questions/13987353/python-valueerror-program-dot-not-found-in-path

You need to have `graphviz` installed on your system. Ex, on fedora, run
```bash
sudo dnf install -y graphviz
```

**Comment by ayushiag17** [comment]
If you are still getting the error, I suppose you installed pydot and graphviz using pip. 
Please use : 
>> sudo apt-get install graphviz
>> pip install pydot
If this gives you permission issues please use: 
>> sudo pip install pydot
This will install the complete graphviz from Ubuntu. 

After this the draw_net.py runs correctly. 
<Tested on my system>

**Comment by benxgh1996** [comment]
I had a similar issue, which occurred after I ran `make pytest`. After reading over several discussions/posts, it seems to be due to you not installing graphviz to your system. Installing graphviz merely through `pip install graphviz` is not enough, since the graphviz python module seems to be only a python wrapper. For my case, I did `brew install graphviz` and it solved my problem. See: https://stackoverflow.com/a/36890526/5859802.

**Comment by patriciars** [comment]
Hello,

How can I do this on windows?
I have the same problem.. I'm using spyder python.

I saw the  https://stackoverflow.com/a/36890526/5859802.
But I didn't understand what I need to do.
Can you help me?

**Comment by Jatinsinghbhati** [comment]
> I had a similar issue, which occurred after I ran `make pytest`. After reading over several discussions/posts, I found it seems to be due to you not installing graphviz to your system. Installing graphviz merely through `pip install graphviz` is not enough, since the graphviz python module seems to be only a python wrapper. For my case, I did `brew install graphviz` and it solved my problem. See: https://stackoverflow.com/a/36890526/5859802.
In my case too, same happened. Thanks for the solution!

**Comment by unclepieman** [comment]
for OSX please use `brew install graphviz` to solve your problem

**Comment by GerardoRTobar** [comment]
brew install graphviz didn’t work for me in OSX. What can I do?

**Comment by GabLeRoux** [comment]
give docker a try maybe
