### ISSUE TITLE
compared with caffe engine, can cudnn  save gpu memory?

### ISSUE THREAD

**Issue by thesby** [BVLC/caffe#4912]
my network often makes the gpu out of memory. compared with caffe engine, can cudnn  save gpu memory?

**Comment by naibaf7** [comment]
Yes it can, as Caffe convolutions need an intermediate "column buffer" for convolutions. How much you can save depends on the cuDNN kernel/method chosen and what network you are trying to run.

**Comment by thesby** [comment]
OK, I got it. thank you.
