### ISSUE TITLE
test_gradient_based_solver.testbin gives memory corruption

### ISSUE THREAD

**Issue by sattlegger** [BVLC/caffe#4917]
The test of the gradient based solvers on the GPU fails and produces a memory corruption (see below). This did only happen after I pulled and built the newest version. The problem does not occur if I build Caffe without GPU support. 

Setup: NVIDIA TITAN X GPU on Ubuntu 14.04.5 LTS with CUDA 8.0.44 and cuDNN 5.1. 

$ build/test/test_gradient_based_solver.testbin 
Current device id: 0
Current device name: TITAN X (Pascal)
[==========] Running 240 tests from 24 test cases.
[----------] Global test environment set-up.
[----------] 12 tests from SGDSolverTest/0, where TypeParam = caffe::CPUDevice<float>
[ RUN      ] SGDSolverTest/0.TestLeastSquaresUpdate
[       OK ] SGDSolverTest/0.TestLeastSquaresUpdate (690 ms)
[ RUN      ] SGDSolverTest/0.TestLeastSquaresUpdateLROneHundredth
[       OK ] SGDSolverTest/0.TestLeastSquaresUpdateLROneHundredth (14 ms)
[ RUN      ] SGDSolverTest/0.TestLeastSquaresUpdateWithWeightDecay
[       OK ] SGDSolverTest/0.TestLeastSquaresUpdateWithWeightDecay (26 ms)
[ RUN      ] SGDSolverTest/0.TestLeastSquaresUpdateWithWeightDecayMultiIter
[       OK ] SGDSolverTest/0.TestLeastSquaresUpdateWithWeightDecayMultiIter (59 ms)
[ RUN      ] SGDSolverTest/0.TestLeastSquaresUpdateWithMomentum
[       OK ] SGDSolverTest/0.TestLeastSquaresUpdateWithMomentum (22 ms)
[ RUN      ] SGDSolverTest/0.TestLeastSquaresUpdateWithMomentumMultiIter
[       OK ] SGDSolverTest/0.TestLeastSquaresUpdateWithMomentumMultiIter (50 ms)
[ RUN      ] SGDSolverTest/0.TestLeastSquaresUpdateWithEverything
[       OK ] SGDSolverTest/0.TestLeastSquaresUpdateWithEverything (47 ms)
[ RUN      ] SGDSolverTest/0.TestLeastSquaresUpdateWithEverythingShare
[       OK ] SGDSolverTest/0.TestLeastSquaresUpdateWithEverythingShare (47 ms)
[ RUN      ] SGDSolverTest/0.TestLeastSquaresUpdateWithEverythingAccum
[       OK ] SGDSolverTest/0.TestLeastSquaresUpdateWithEverythingAccum (4 ms)
[ RUN      ] SGDSolverTest/0.TestLeastSquaresUpdateWithEverythingAccumShare
[       OK ] SGDSolverTest/0.TestLeastSquaresUpdateWithEverythingAccumShare (6 ms)
[ RUN      ] SGDSolverTest/0.TestSnapshot
[       OK ] SGDSolverTest/0.TestSnapshot (23 ms)
[ RUN      ] SGDSolverTest/0.TestSnapshotShare
[       OK ] SGDSolverTest/0.TestSnapshotShare (35 ms)
[----------] 12 tests from SGDSolverTest/0 (1023 ms total)

[----------] 12 tests from SGDSolverTest/1, where TypeParam = caffe::CPUDevice<double>
[ RUN      ] SGDSolverTest/1.TestLeastSquaresUpdate
[       OK ] SGDSolverTest/1.TestLeastSquaresUpdate (13 ms)
[ RUN      ] SGDSolverTest/1.TestLeastSquaresUpdateLROneHundredth
[       OK ] SGDSolverTest/1.TestLeastSquaresUpdateLROneHundredth (11 ms)
[ RUN      ] SGDSolverTest/1.TestLeastSquaresUpdateWithWeightDecay
[       OK ] SGDSolverTest/1.TestLeastSquaresUpdateWithWeightDecay (22 ms)
[ RUN      ] SGDSolverTest/1.TestLeastSquaresUpdateWithWeightDecayMultiIter
[       OK ] SGDSolverTest/1.TestLeastSquaresUpdateWithWeightDecayMultiIter (51 ms)
[ RUN      ] SGDSolverTest/1.TestLeastSquaresUpdateWithMomentum
[       OK ] SGDSolverTest/1.TestLeastSquaresUpdateWithMomentum (18 ms)
[ RUN      ] SGDSolverTest/1.TestLeastSquaresUpdateWithMomentumMultiIter
[       OK ] SGDSolverTest/1.TestLeastSquaresUpdateWithMomentumMultiIter (42 ms)
[ RUN      ] SGDSolverTest/1.TestLeastSquaresUpdateWithEverything
[       OK ] SGDSolverTest/1.TestLeastSquaresUpdateWithEverything (40 ms)
[ RUN      ] SGDSolverTest/1.TestLeastSquaresUpdateWithEverythingShare
[       OK ] SGDSolverTest/1.TestLeastSquaresUpdateWithEverythingShare (44 ms)
[ RUN      ] SGDSolverTest/1.TestLeastSquaresUpdateWithEverythingAccum
[       OK ] SGDSolverTest/1.TestLeastSquaresUpdateWithEverythingAccum (4 ms)
[ RUN      ] SGDSolverTest/1.TestLeastSquaresUpdateWithEverythingAccumShare
[       OK ] SGDSolverTest/1.TestLeastSquaresUpdateWithEverythingAccumShare (4 ms)
[ RUN      ] SGDSolverTest/1.TestSnapshot
[       OK ] SGDSolverTest/1.TestSnapshot (19 ms)
[ RUN      ] SGDSolverTest/1.TestSnapshotShare
[       OK ] SGDSolverTest/1.TestSnapshotShare (26 ms)
[----------] 12 tests from SGDSolverTest/1 (294 ms total)

[----------] 12 tests from SGDSolverTest/2, where TypeParam = caffe::GPUDevice<float>
[ RUN      ] SGDSolverTest/2.TestLeastSquaresUpdate
**\* Aborted at 1477667475 (unix time) try "date -d @1477667475" if you are using GNU date ***
PC: @     0x7f8c1b32e677 (unknown)
**\* SIGSEGV (@0xc7ee000) received by PID 29792 (TID 0x7f8c1e061a40) from PID 209641472; stack trace: ***
    @     0x7f8c1b5b2330 (unknown)
    @     0x7f8c1b32e677 (unknown)
    @     0x7f8c1bfac86c std::vector<>::erase()
    @     0x7f8c1bfab6f1 caffe::DevicePair::compute()
    @     0x7f8c1bfb0a9c caffe::P2PSync<>::Prepare()
    @     0x7f8c1bfb101c caffe::P2PSync<>::Run()
    @           0x4395c5 caffe::GradientBasedSolverTest<>::RunLeastSquaresSolver()
    @           0x44a20b caffe::GradientBasedSolverTest<>::TestLeastSquaresUpdate()
    @           0x46e9c3 testing::internal::HandleExceptionsInMethodIfSupported<>()
    @           0x465297 testing::Test::Run()
    @           0x46533e testing::TestInfo::Run()
    @           0x465445 testing::TestCase::Run()
    @           0x468788 testing::internal::UnitTestImpl::RunAllTests()
    @           0x468a17 testing::UnitTest::Run()
    @           0x40da6f main
    @     0x7f8c1b1fef45 (unknown)
    @           0x40e6f9 (unknown)
    @                0x0 (unknown)
**\* Error in `build/test/test_gradient_based_solver.testbin': malloc(): memory corruption (fast): 0x000000000b52d6c0 ***
Aborted (core dumped)

**Comment by ShaggO** [comment]
I encounter this problem as well. It happens when running any of the gradient solver tests on GPU (not only SGDSolverTest).
I have a cluster of four mirrored machines but with slightly different hardware. The problem only occurs on 2/4 machines and it doesn't seem to be connected to any specific GPU architecture.

Graphics cards: Titan X, GTX 1080, K20c, K40c
OS: RHEL 7.2, CUDA 8.0.44, cuDNN 5.0.5

**Comment by jwgu** [comment]
It may be an issue of multi-GPU. Try to run the test by setting export CUDA_VISIBLE_DEVICES=0 (only run single GPU test on GPU 0). See the previous issue https://github.com/BVLC/caffe/issues/3109

**Comment by sattlegger** [comment]
Thank you @jwgu ! That did the trick! Still, it seems rather strange to me that multi-GPU is a problem since the test only run on a single CPU in any case.
