### ISSUE TITLE
I met a trouble while trying to "import caffe"

### ISSUE THREAD

**Issue by melo58** [BVLC/caffe#4921]
# I met a strange problem while trying to "import caffe"  in Ipython after finishing the  compilation.I am sure there is nothing wrong happend in the compilation,and All the dependencies are supported.But I can not use caffe in python.

**In [1]: import caffe
python(38480,0x7ffff290a3c0) malloc: **\* malloc_zone_unregister() failed for 0x7ffff2900000
/Users/melo/anaconda/bin/python.app: line 3: 38480 Segmentation fault: 11  /Users/melo/anaconda/python.app/Contents/MacOS/python "$@"**

I have never met an error like that,though I am sure I am familiar with python language.My OS is MacOS  Sierra(10.12).Does anyone meet the same problem?Should I blame the new MacOs?

**Comment by logic1988** [comment]
Yes, I met the same error in using pycaffe.

**Comment by nuoqish** [comment]
this may help: 
comment out the line USE_LEVELDB := 0 in Makefile.config

[https://github.com/BVLC/caffe/issues/4783](url)
