### ISSUE TITLE
I'm new here, thanks for your help!

### ISSUE THREAD

**Issue by amenglar** [BVLC/caffe#4922]
Amenglars-MacBook-Pro:caffe mac$ make runtest
.build_release/tools/caffe
dyld: Library not loaded: @rpath/libmkl_rt.dylib
  Referenced from: /Users/mac/workspace/caffe/caffe/.build_release/tools/caffe
  Reason: image not found
make: **\* [runtest] Abort trap: 6

**Comment by williford** [comment]
Questions like these should be asked on the [Caffe user mailing list](https://groups.google.com/forum/#!forum/caffe-users) or on another website, such as http://stackoverflow.com/ or http://stats.stackexchange.com/. Please **close this issue** and move your question to one of these places.
