### ISSUE TITLE
Unknown CMake command "caffe_protobuf_generate_cpp_py"

### ISSUE THREAD

**Issue by rrrzzz** [BVLC/caffe#4923]
Hi! I do everything as specified in instructions but for some reason cmake doesn't see *.cmake files. 
Any help is greatly appreciated. My os is win10 x64,
```
C:\caffe-windows\scripts>python.exe download_prebuilt_dependencies.py
Downloading dependencies. Please wait...
...100%, 142 MB, 3867 KB/s, 37 seconds passed
Done.
Extracting dependencies. Please wait...
Done.

C:\caffe-windows\scripts>call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64

C:\caffe-windows\scripts>set CMAKE_GENERATOR=Ninja

C:\caffe-windows\scripts>set CMAKE_CONFIGURATION=Release

C:\caffe-windows\scripts>mkdir build

C:\caffe-windows\scripts>cd build

C:\caffe-windows\scripts\build>set CAFFE_DEPENDENCIES=C:\caffe-windows\scripts\libraries
C:\caffe-windows\scripts\build>cd C:\caffe-windows\src\caffe

C:\caffe-windows\src\caffe>mkdir build

C:\caffe-windows\src\caffe>cd build

C:\caffe-windows\src\caffe\build>cmake -G%CMAKE_GENERATOR% -DCMAKE_MAKE_PROGRAM=C:\ninja.exe -DBLAS=Open -DCMAKE_BUILD_TYPE=%CMAKE_CONFIGURATION% -DBUILD_SHARED_LIBS=OFF -DCMAKE_INSTALL_PREFIX=Z:\Downloads\caffe -C %CAFFE_DEPENDENCIES%\caffe-builder-config.cmake  ..\
loading initial cache file C:\caffe-windows\scripts\libraries\caffe-builder-config.cmake
-- The C compiler identification is MSVC 19.0.24213.1
-- The CXX compiler identification is MSVC 19.0.24213.1
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:3 (caffe_protobuf_generate_cpp_py):
  Unknown CMake command "caffe_protobuf_generate_cpp_py".


CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.6)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring incomplete, errors occurred!
See also "C:/caffe-windows/src/caffe/build/CMakeFiles/CMakeOutput.log".

```

**Comment by nihiladrem** [comment]
rrrzzz, you closed this.  I am having the same issue what was the solution?

**Comment by nihiladrem** [comment]
Ahh nevermind, I also figured out what rrrzzz must have.  The CmakeLists.txt that should be used is in the root folder, not the file in the <root>\src\caffe folder.  the commands in the Readme file do not work verbatim.

**Comment by rrrzzz** [comment]
Actually I closed the issue because read that all questions regarding configuration should be posted in google group so that devs won't be distracted. Ended up using this older version https://github.com/happynear/caffe-windows . It was easier to build and worked nicely

**Comment by willyd** [comment]
Indeed @nihiladrem is right. CMake must be given the root directory as  the last argument. Also since VS 2015 is used the right dependencies must be downloads by passing --msvc_version v140 to the download script.

**Comment by Vega24** [comment]
Hi, I am new to caffe and I am trying to set it on Win10, 64, with VS2013. I have the same problem and I am not sure how to fix it. Do I need to move the CmakeLists.txt to another directory or do I need to change something in this command:

cmake -G%CMAKE_GENERATOR% -DBLAS=Open -DCMAKE_BUILD_TYPE=%CMAKE_CONFIGURATION% -DBUILD_SHARED_LIBS=OFF -DCMAKE_INSTALL_PREFIX=C:\deepL -C %CAFFE_DEPENDENCIES%\caffe-builder-config.cmake  ..\

Thanks for an answer.

**Comment by willyd** [comment]
You don't need to move anything anywhere. Just run the above command from a build folder located in the same directory as the root CMakeLists.txt.

BTW, I am currently reworking the appveyor build script so it can be used outside of appveyor. You can see it there: https://github.com/willyd/caffe/tree/build-script

Building caffe with this should be as simple as running `build_win.cmd`

I will let you know when this is merged.
