### ISSUE TITLE
How to modify the model to fit in your demand?

### ISSUE THREAD

**Issue by zccoder** [BVLC/caffe#4924]
```
 I am new here,and I want to make contributions to the development of caffe and DP as long as I can.However,for most the searching pages,they do not tell you how to modify a model to fit in your demand and improve the effect .Is it necessary to debug and test in Linux,or can  I modify and then train my data in window?This problem maybe very stupid,but it is a quesion for me,thanks for everyone who can answer my question.
```

**Comment by shelhamer** [comment]
Please ask usage questions on the mailing list and check out the Caffe tutorials and documentation on the home page: http://caffe.berkeleyvision.org/

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
