### ISSUE TITLE
Caffe installation issue with 'libculibos'.

### ISSUE THREAD

**Issue by gautamkrishna** [BVLC/caffe#4925]
I try to compile 'Caffe' with 'cuDnn', but I'm stuck at this point. I run this on Ubuntu 16.04, with CUDA 8.0 and OpenCV 3.1.0.
``
Scanning dependencies of target upgrade_solver_proto_text
[ 81%] Building CXX object tools/CMakeFiles/upgrade_solver_proto_text.dir/upgrade_solver_proto_text.cpp.o
[ 83%] Linking CXX executable upgrade_solver_proto_text
../lib/libcaffe.so.1.0.0-rc3: undefined reference to`culibosInitializeCriticalSection'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to `culibosLeaveCriticalSection'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to`culibosOnce'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to `culibosInit'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to`culibosEnterCriticalSection'
collect2: error: ld returned 1 exit status
tools/CMakeFiles/upgrade_solver_proto_text.dir/build.make:139: recipe for target 'tools/upgrade_solver_proto_text' failed
make[2]: **\* [tools/upgrade_solver_proto_text] Error 1
CMakeFiles/Makefile2:435: recipe for target 'tools/CMakeFiles/upgrade_solver_proto_text.dir/all' failed
make[1]: **\* [tools/CMakeFiles/upgrade_solver_proto_text.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: **\* [all] Error 2

```
```

**Comment by globalcaos** [comment]
Same here (as far as I can tell). Ubuntu 16.04 and CUDA 8.0

[ 84%] Linking CXX executable compute_image_mean
CMakeFiles/compute_image_mean.dir/compute_image_mean.cpp.o: In function `main':
compute_image_mean.cpp:(.text.startup+0x309): undefined reference to `google::protobuf::MessageLite::ParseFromString(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
compute_image_mean.cpp:(.text.startup+0x49b): undefined reference to `google::protobuf::MessageLite::ParseFromString(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
../lib/libcaffe-nv.so.0.15.14: undefined reference to `google::protobuf::DescriptorPool::FindFileByName(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
../lib/libcaffe-nv.so.0.15.14: undefined reference to `google::protobuf::Message::DebugString[abi:cxx11]() const'
../lib/libcaffe-nv.so.0.15.14: undefined reference to `google::protobuf::MessageFactory::InternalRegisterGeneratedFile(char const*, void (*)(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&))'
../lib/libcaffe-nv.so.0.15.14: undefined reference to `google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, google::protobuf::io::CodedOutputStream*)'
../lib/libcaffe-nv.so.0.15.14: undefined reference to `google::protobuf::internal::WireFormatLite::ReadBytes(google::protobuf::io::CodedInputStream*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)'
../lib/libcaffe-nv.so.0.15.14: undefined reference to `google::protobuf::Message::GetTypeName[abi:cxx11]() const'
../lib/libcaffe-nv.so.0.15.14: undefined reference to `google::protobuf::io::CodedOutputStream::WriteStringWithSizeToArray(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned char*)'
../lib/libcaffe-nv.so.0.15.14: undefined reference to `google::protobuf::Message::InitializationErrorString[abi:cxx11]() const'
../lib/libcaffe-nv.so.0.15.14: undefined reference to `google::protobuf::internal::NameOfEnum[abi:cxx11](google::protobuf::EnumDescriptor const*, int)'
../lib/libcaffe-nv.so.0.15.14: undefined reference to `google::protobuf::internal::empty_string_[abi:cxx11]'
../lib/libcaffe-nv.so.0.15.14: undefined reference to `google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, google::protobuf::io::CodedOutputStream*)'
../lib/libcaffe-nv.so.0.15.14: undefined reference to `google::protobuf::internal::WireFormatLite::WriteString(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, google::protobuf::io::CodedOutputStream*)'
../lib/libcaffe-nv.so.0.15.14: undefined reference to `google::protobuf::internal::ArenaStringPtr::AssignWithDefault(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const*, google::protobuf::internal::ArenaStringPtr)'
collect2: error: ld returned 1 exit status
tools/CMakeFiles/compute_image_mean.dir/build.make:135: recipe for target 'tools/compute_image_mean' failed
make[2]: *** [tools/compute_image_mean] Error 1
CMakeFiles/Makefile2:549: recipe for target 'tools/CMakeFiles/compute_image_mean.dir/all' failed
make[1]: *** [tools/CMakeFiles/compute_image_mean.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 86%] Linking CXX executable convert_imageset
CMakeFiles/convert_imageset.dir/convert_imageset.cpp.o: In function `main':
convert_imageset.cpp:(.text.startup+0x1185): undefined reference to `google::protobuf::MessageLite::SerializeToString(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*) const'
../lib/libcaffe-nv.so.0.15.14: undefined reference to `google::protobuf::DescriptorPool::FindFileByName(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
../lib/libcaffe-nv.so.0.15.14: undefined reference to `google::protobuf::Message::DebugString[abi:cxx11]() const'
../lib/libcaffe-nv.so.0.15.14: undefined reference to `google::protobuf::MessageFactory::InternalRegisterGeneratedFile(char const*, void (*)(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&))'
../lib/libcaffe-nv.so.0.15.14: undefined reference to `google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, google::protobuf::io::CodedOutputStream*)'
../lib/libcaffe-nv.so.0.15.14: undefined reference to `google::protobuf::internal::WireFormatLite::ReadBytes(google::protobuf::io::CodedInputStream*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)'
../lib/libcaffe-nv.so.0.15.14: undefined reference to `google::protobuf::MessageLite::ParseFromString(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
../lib/libcaffe-nv.so.0.15.14: undefined reference to `google::protobuf::Message::GetTypeName[abi:cxx11]() const'
../lib/libcaffe-nv.so.0.15.14: undefined reference to `google::protobuf::io::CodedOutputStream::WriteStringWithSizeToArray(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned char*)'
../lib/libcaffe-nv.so.0.15.14: undefined reference to `google::protobuf::Message::InitializationErrorString[abi:cxx11]() const'
../lib/libcaffe-nv.so.0.15.14: undefined reference to `google::protobuf::internal::NameOfEnum[abi:cxx11](google::protobuf::EnumDescriptor const*, int)'
../lib/libcaffe-nv.so.0.15.14: undefined reference to `google::protobuf::internal::empty_string_[abi:cxx11]'
../lib/libcaffe-nv.so.0.15.14: undefined reference to `google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, google::protobuf::io::CodedOutputStream*)'
../lib/libcaffe-nv.so.0.15.14: undefined reference to `google::protobuf::internal::WireFormatLite::WriteString(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, google::protobuf::io::CodedOutputStream*)'
../lib/libcaffe-nv.so.0.15.14: undefined reference to `google::protobuf::internal::ArenaStringPtr::AssignWithDefault(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const*, google::protobuf::internal::ArenaStringPtr)'
collect2: error: ld returned 1 exit status
tools/CMakeFiles/convert_imageset.dir/build.make:135: recipe for target 'tools/convert_imageset' failed
make[2]: *** [tools/convert_imageset] Error 1
CMakeFiles/Makefile2:473: recipe for target 'tools/CMakeFiles/convert_imageset.dir/all' failed
make[1]: *** [tools/CMakeFiles/convert_imageset.dir/all] Error 2
[ 86%] Linking CXX executable upgrade_net_proto_binary
[ 87%] Linking CXX executable upgrade_solver_proto_text
../lib/libcaffe-nv.so.0.15.14: undefined reference to `google::protobuf::DescriptorPool::FindFileByName(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
../lib/libcaffe-nv.so.0.15.14: undefined reference to `google::protobuf::Message::DebugString[abi:cxx11]() const'
../lib/libcaffe-nv.so.0.15.14: undefined reference to `google::protobuf::MessageFactory::InternalRegisterGeneratedFile(char const*, void (*)(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&))'
../lib/libcaffe-nv.so.0.15.14: undefined reference to `google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, google::protobuf::io::CodedOutputStream*)'
../lib/libcaffe-nv.so.0.15.14: undefined reference to `google::protobuf::internal::WireFormatLite::ReadBytes(google::protobuf::io::CodedInputStream*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)'
../lib/libcaffe-nv.so.0.15.14: undefined reference to `google::protobuf::MessageLite::ParseFromString(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
../lib/libcaffe-nv.so.0.15.14: undefined reference to `google::protobuf::Message::GetTypeName[abi:cxx11]() const'
../lib/libcaffe-nv.so.0.15.14: undefined reference to `google::protobuf::io::CodedOutputStream::WriteStringWithSizeToArray(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned char*)'
../lib/libcaffe-nv.so.0.15.14: undefined reference to `google::protobuf::Message::InitializationErrorString[abi:cxx11]() const'
../lib/libcaffe-nv.so.0.15.14: undefined reference to `google::protobuf::internal::NameOfEnum[abi:cxx11](google::protobuf::EnumDescriptor const*, int)'
../lib/libcaffe-nv.so.0.15.14: undefined reference to `google::protobuf::internal::empty_string_[abi:cxx11]'
../lib/libcaffe-nv.so.0.15.14: undefined reference to `google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, google::protobuf::io::CodedOutputStream*)'
../lib/libcaffe-nv.so.0.15.14: undefined reference to `google::protobuf::internal::WireFormatLite::WriteString(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, google::protobuf::io::CodedOutputStream*)'
../lib/libcaffe-nv.so.0.15.14: undefined reference to `google::protobuf::internal::ArenaStringPtr::AssignWithDefault(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const*, google::protobuf::internal::ArenaStringPtr)'
collect2: error: ld returned 1 exit status
tools/CMakeFiles/upgrade_net_proto_binary.dir/build.make:135: recipe for target 'tools/upgrade_net_proto_binary' failed
make[2]: *** [tools/upgrade_net_proto_binary] Error 1
CMakeFiles/Makefile2:511: recipe for target 'tools/CMakeFiles/upgrade_net_proto_binary.dir/all' failed
make[1]: *** [tools/CMakeFiles/upgrade_net_proto_binary.dir/all] Error 2
../lib/libcaffe-nv.so.0.15.14: undefined reference to `google::protobuf::DescriptorPool::FindFileByName(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
../lib/libcaffe-nv.so.0.15.14: undefined reference to `google::protobuf::Message::DebugString[abi:cxx11]() const'
../lib/libcaffe-nv.so.0.15.14: undefined reference to `google::protobuf::MessageFactory::InternalRegisterGeneratedFile(char const*, void (*)(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&))'
../lib/libcaffe-nv.so.0.15.14: undefined reference to `google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, google::protobuf::io::CodedOutputStream*)'
../lib/libcaffe-nv.so.0.15.14: undefined reference to `google::protobuf::internal::WireFormatLite::ReadBytes(google::protobuf::io::CodedInputStream*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)'
../lib/libcaffe-nv.so.0.15.14: undefined reference to `google::protobuf::MessageLite::ParseFromString(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
../lib/libcaffe-nv.so.0.15.14: undefined reference to `google::protobuf::Message::GetTypeName[abi:cxx11]() const'
../lib/libcaffe-nv.so.0.15.14: undefined reference to `google::protobuf::io::CodedOutputStream::WriteStringWithSizeToArray(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned char*)'
../lib/libcaffe-nv.so.0.15.14: undefined reference to `google::protobuf::Message::InitializationErrorString[abi:cxx11]() const'
../lib/libcaffe-nv.so.0.15.14: undefined reference to `google::protobuf::internal::NameOfEnum[abi:cxx11](google::protobuf::EnumDescriptor const*, int)'
../lib/libcaffe-nv.so.0.15.14: undefined reference to `google::protobuf::internal::empty_string_[abi:cxx11]'
../lib/libcaffe-nv.so.0.15.14: undefined reference to `google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, google::protobuf::io::CodedOutputStream*)'
../lib/libcaffe-nv.so.0.15.14: undefined reference to `google::protobuf::internal::WireFormatLite::WriteString(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, google::protobuf::io::CodedOutputStream*)'
../lib/libcaffe-nv.so.0.15.14: undefined reference to `google::protobuf::internal::ArenaStringPtr::AssignWithDefault(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const*, google::protobuf::internal::ArenaStringPtr)'
collect2: error: ld returned 1 exit status
tools/CMakeFiles/upgrade_solver_proto_text.dir/build.make:135: recipe for target 'tools/upgrade_solver_proto_text' failed
make[2]: *** [tools/upgrade_solver_proto_text] Error 1
CMakeFiles/Makefile2:435: recipe for target 'tools/CMakeFiles/upgrade_solver_proto_text.dir/all' failed
make[1]: *** [tools/CMakeFiles/upgrade_solver_proto_text.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by lullabee** [comment]
Hi gautamkrishna
Did you solve the problem?

**Comment by IvyGongoogle** [comment]
@gautamkrishna @globalcaos  how to solve this?

**Comment by MartinFultot** [comment]
check this guy. I'm about to try his solution 
https://devtalk.nvidia.com/default/topic/1032775/cuda-programming-and-performance/cudnn-static-linking-error/
