### ISSUE TITLE
Typo in include/caffe/layers/accuracy_layer.hpp

### ISSUE THREAD

**Issue by karas84** [BVLC/caffe#4930]
In file `include/caffe/layers/accuracy_layer.hpp` the function `MaxTopBlobs` has been mispelled as `MaxTopBlos`.

**Comment by willyd** [comment]
Hi @karas84 thanks for reporting. Would you be so kind to send a PR with the right function name?

**Comment by karas84** [comment]
Done

**Comment by jeffdonahue** [comment]
Fixed by #4941
