### ISSUE TITLE
error when installing caffe

### ISSUE THREAD

**Issue by raditha** [BVLC/caffe#4932]
I get the following error on lmdb when installing caffe.

CXX/LD -o .build_release/tools/upgrade_net_proto_text.bin
.build_release/lib/libcaffe.so: undefined reference to `mdb_txn_begin'
.build_release/lib/libcaffe.so: undefined reference to `mdb_cursor_get'
.build_release/lib/libcaffe.so: undefined reference to `mdb_cursor_close'
.build_release/lib/libcaffe.so: undefined reference to `mdb_put'
.build_release/lib/libcaffe.so: undefined reference to `leveldb::WriteBatch::WriteBatch()'
.build_release/lib/libcaffe.so: undefined reference to `mdb_txn_abort'
.build_release/lib/libcaffe.so: undefined reference to `mdb_strerror'
.build_release/lib/libcaffe.so: undefined reference to `mdb_txn_commit'
.build_release/lib/libcaffe.so: undefined reference to `mdb_env_open'
.build_release/lib/libcaffe.so: undefined reference to `mdb_cursor_open'
.build_release/lib/libcaffe.so: undefined reference to `mdb_env_set_mapsize'
.build_release/lib/libcaffe.so: undefined reference to `mdb_dbi_close'
.build_release/lib/libcaffe.so: undefined reference to `leveldb::Status::ToString[abi:cxx11]() const'
.build_release/lib/libcaffe.so: undefined reference to `mdb_env_create'
.build_release/lib/libcaffe.so: undefined reference to `leveldb::WriteBatch::~WriteBatch()'
.build_release/lib/libcaffe.so: undefined reference to `leveldb::Options::Options()'
.build_release/lib/libcaffe.so: undefined reference to `mdb_env_close'
.build_release/lib/libcaffe.so: undefined reference to `leveldb::DB::Open(leveldb::Options const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, leveldb::DB**)'
.build_release/lib/libcaffe.so: undefined reference to `mdb_dbi_open'
.build_release/lib/libcaffe.so: undefined reference to `leveldb::WriteBatch::Put(leveldb::Slice const&, leveldb::Slice const&)'
collect2: error: ld returned 1 exit status
Makefile:559: recipe for target '.build_release/tools/upgrade_net_proto_text.bin' failed
make: *** [.build_release/tools/upgrade_net_proto_text.bin] Error 1

**Comment by raditha** [comment]
anyone facing this problem?

**Comment by raditha** [comment]
fixed it by using cmake.

**Comment by deepaksharma36** [comment]
check LMDB lib path in make file or use ccmake for setting correct path.

**Comment by bunbunbunbunbunny** [comment]
> 
> 
> fixed it by using cmake.

How did you do it ?? I'm stuck with same error, i have no clue how to use cmake
