### ISSUE TITLE
I couldn't import  _caffe, while I could import caffe. With the help of cmake, I couldn't found _caffe.py.

### ISSUE THREAD

**Issue by hukangrong** [BVLC/caffe#4934]
I couldn't import  _caffe, while I could import caffe. With the help of cmake, I couldn't found _caffe.py.
I used cmake to building caffe
make -j 4 && make install
with this step, I could import caffe successful.
And when I do "make runtest", It response 
make[3]: *** [src/caffe/test/CMakeFiles/runtest] 已放弃 (core dumped)
make[2]: *** [src/caffe/test/CMakeFiles/runtest.dir/all] 错误 2
make[1]: *** [src/caffe/test/CMakeFiles/runtest.dir/rule] 错误 2
make: *** [runtest] 错误 2
how could I deal with this problem?

**Comment by hukangrong** [comment]
Module nvidia-uvm not found

**Comment by hukangrong** [comment]
[ RUN      ] HingeLossLayerTest/2.TestGradientL2
F1031 23:12:21.878526 31593 syncedmem.hpp:18] Check failed: error == cudaSuccess (30 vs. 0)  unknown error
*** Check failure stack trace: ***
    @     0x2b180a3ebdaa  (unknown)
    @     0x2b180a3ebce4  (unknown)
    @     0x2b180a3eb6e6  (unknown)
    @     0x2b180a3ee687  (unknown)
    @     0x2b180939d3f5  caffe::SyncedMemory::mutable_cpu_data()
    @     0x2b18093ac278  caffe::Blob<>::Reshape()
    @     0x2b18093ac6d9  caffe::Blob<>::Reshape()
    @     0x2b18093ac76c  caffe::Blob<>::Blob()
    @           0xae4f2d  caffe::HingeLossLayerTest<>::HingeLossLayerTest()
    @           0xae52ab  testing::internal::TestFactoryImpl<>::CreateTest()
    @           0xd925e3  testing::internal::HandleExceptionsInMethodIfSupported<>()
    @           0xd88f85  testing::TestInfo::Run()
    @           0xd890a5  testing::TestCase::Run()
    @           0xd8bdf8  testing::internal::UnitTestImpl::RunAllTests()
    @           0xd8c097  testing::UnitTest::Run()
    @           0x890bcf  main
    @     0x2b1810031f45  (unknown)
    @           0x897202  (unknown)
    @              (nil)  (unknown)
make[3]: *** [src/caffe/test/CMakeFiles/runtest] 已放弃 (core dumped)
make[2]: *** [src/caffe/test/CMakeFiles/runtest.dir/all] 错误 2
make[1]: *** [src/caffe/test/CMakeFiles/runtest.dir/rule] 错误 2
make: *** [runtest] 错误 2

**Comment by shelhamer** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
