### ISSUE TITLE
File for {} is missing. Should be at: {}".format(key, val))

### ISSUE THREAD

**Issue by mesutpiskin** [BVLC/caffe#4940]
I'm getting this error trying to run the sample web_demo python application. What could be the reason?
C:\caffe-master\examples\web_demo>python app.py
Traceback (most recent call last):
  File "app.py", line 99, in <module>
    class ImagenetClassifier(object):
  File "app.py", line 115, in ImagenetClassifier
    "File for {} is missing. Should be at: {}".format(key, val))
Exception: File for class_labels_file is missing. Should be at: C:\caffe-master/data/ilsvrc12/synset_words.txt

**Comment by willyd** [comment]
From the error message it looks like you need to run the app demo from the caffe root directory:
```
C:\caffe-master> python examples\web_demo\app.py
```
You may need to download data files (.caffemodel, .prototxt, etc.) beforehand.

@mesutpiskin Please send usage questions to the mailing list https://groups.google.com/forum/#!forum/caffe-users.

**Comment by metinaydar** [comment]
Hi, @mesutpiskin ,

   The error is about ilsvrc12 data package. So, simply try to run the shell file under your $CAFFE_HOME:
`./data/ilsvrc12/get_ilsvrc_aux.sh` and then try again to run python example:
`python examples/web_demo/app.py` 

You should be able to view the demo page in your browser on port 5000.
