### ISSUE TITLE
Training weight dump out

### ISSUE THREAD

**Issue by yuanxue001** [BVLC/caffe#4943]
During training, I want to observe every weight changes in networks, can you give me a breif guide how can I dump out these weight info during training?Thank you.

**Comment by Noiredd** [comment]
Solver parameter `snapshot` defines how often (once every how many iterations) to write a snapshot of the network. This lets you do exactly what you want, that is regularly dump all of the weights into a file. Look at the [lenet solver example](https://github.com/BVLC/caffe/blob/master/examples/mnist/lenet_solver.prototxt).

An alternative would be to carry out the entire training from within Python and manually extract weights inbetween calls to `solver.step` or as a callback. More work but more flexibility.
