### ISSUE TITLE
Ubuntu 16.04 “/usr/bin/ld: cannot find -llmdb” error in Caffe compilation

### ISSUE THREAD

**Issue by Payuing** [BVLC/caffe#4956]
CXX src/caffe/layers/cudnn_relu_layer.cpp
    AR -o .build_release/lib/libcaffe.a
    LD -o .build_release/lib/libcaffe.so
    /usr/bin/ld: cannot find -l -llmdb
    /usr/bin/ld: cannot find -l -lopencv_core 
    collect2: error: ld returned 1 exit status
    Makefile:526: recipe for target '.build_release/lib/libcaffe.so' failed

I have installed `liblmdb-dev` and `libopencv_core.so.X` 
but I cannot find lmdb using`locate lmdb`

**Comment by farazfazli** [comment]
This is related to compilation. Please move this to the [Caffe mailing list](https://groups.google.com/forum/#!forum/caffe-users).

**Comment by curry111** [comment]
@Payuing  please tell me, did you find a solution because i really have the same issue

**Comment by Payuing** [comment]
@curry111 I `make clean` and reinstall the caffe `make all`. This solves my problem, but your mileage may vary

**Comment by Suraj59** [comment]
i got same problem any one have perfect solution 
AR -o .build_release/lib/libcaffe.a
LD -o .build_release/lib/libcaffe.so.1.0.0
/usr/bin/ld: cannot find -l -llmdb
collect2: error: ld returned 1 exit status
Makefile:575: recipe for target '.build_release/lib/libcaffe.so.1.0.0' failed
make: *** [.build_release/lib/libcaffe.so.1.0.0] Error 1

**Comment by UdayMegdap** [comment]
AR -o .build_release/lib/libcaffe.a
LD -o .build_release/lib/libcaffe.so.1.0.0
/usr/bin/ld: cannot find -lhdf5_hl
/usr/bin/ld: cannot find -lhdf5
collect2: error: ld returned 1 exit status
Makefile:572: recipe for target '.build_release/lib/libcaffe.so.1.0.0' failed
make: *** [.build_release/lib/libcaffe.so.1.0.0] Error 1
uday@uday-X550LC:~/.local/install/caffe$

**Comment by UdayMegdap** [comment]
give me solution on that problem

**Comment by jiayifang1** [comment]
> i got same problem any one have perfect solution
> AR -o .build_release/lib/libcaffe.a
> LD -o .build_release/lib/libcaffe.so.1.0.0
> /usr/bin/ld: cannot find -l -llmdb
> collect2: error: ld returned 1 exit status
> Makefile:575: recipe for target '.build_release/lib/libcaffe.so.1.0.0' failed
> make: *** [.build_release/lib/libcaffe.so.1.0.0] Error 1

Now I have the same problem and please give me a solution.I install the llmdb with a apt-get hand,no use for that
