### ISSUE TITLE
matcaffe compilation error- unrecognized command line option "-std=c++11"

### ISSUE THREAD

**Issue by puneet336** [BVLC/caffe#4959]
Hi all,
I am having issues compiling matcaffe for caffe rc3. Though i was able to make caffe & pycaffe successfully.
Here is the error log: 

**time make -j 12  matcaffe 2>&1|tee makepycaffe.log**
```

MEX matlab/+caffe/private/caffe_.cpp
/home/apps/MATLAB/r2015b/mdcs/bin/mex matlab/+caffe/private/caffe_.cpp \
			CXX="g++" \
			CXXFLAGS="\$CXXFLAGS -fPIC" \
			CXXLIBS="\$CXXLIBS -Wl,--whole-archive .build_release/lib/libcaffe.a -Wl,--no-whole-archive -L/home/soft/intel2015/composer_xe_2015.3.187/mkl/lib/intel64/ -L/home/apps/HDF/5/1.8.16/gnu/lib -L/home/apps/BOOST/1.59.0/gnu//lib -L/home/apps/LIBOPENCV/2/4.13/gnu/lib -L/home/apps/JASPER/1.900.1/gnu/lib -L/home/apps/LIBTIFF/3.8.2/gnu/lib -L/home/apps/LIBJPEG/6b/gnu/lib -L/home/apps/ZLIB/1.2.8/gnu/lib -L/home/apps/LIBPNG/1.6.19/gnu/lib -L/home/apps/LIBCUDNN/7.0.4.0/precompiled//lib -L/home/soft/cuda-7.0/lib64 -L/home/soft/cuda-7.0/lib -L/home/apps/LIBGLOG/0.3.4/gnu//lib -L/home/apps/LIBGFLAGS/2.1.2/gnu//lib -L/home/apps/SNAPPY/1.1.3/gnu/lib -L/home/apps/LEVELDB/1.19/gnu//lib -L/home/apps/LMDB/0.9.18/gnu//lib -L/home/apps/PROTOBUF/3.1.0/gnu//lib -L/home/soft/python-2.7.10/lib -L/home/soft/intel2015/composer_xe_2015.3.187/compiler/lib/intel64 -L/home/soft/intel2015/composer_xe_2015.3.187/mkl/lib/intel64 -L/home/soft/cuda-7.0/lib64 -L/home/soft/cuda-7.0/lib -L/opt/intel/mkl/lib -L/opt/intel/mkl/lib/intel64 -L.build_release/lib  -lcudart -lcublas -lcurand -lglog -lgflags -lprotobuf -lboost_system -lboost_filesystem -lm -lhdf5_hl -lhdf5 -lleveldb -lsnappy -llmdb -lopencv_core -lopencv_highgui -lopencv_imgproc -lboost_thread -lstdc++ -lcudnn -lmkl_rt" -output matlab/+caffe/private/caffe_.mexa64
Building with 'g++'.
cc1plus: error: unrecognized command line option "-std=c++11"
make: *** [matlab/+caffe/private/caffe_.mexa64] Error 255
real	0m3.986s
user	0m1.267s
sys	0m1.417s
```

i have searched(grep) "std=c++11" in caffe source directory , but it seems caffe source doesnot have one. How could i **remove/disable** this flag. Is there some setting i need to carry out in matlab installation directory(since issue crops up only during matcaffe build!)?

Please let me know if any other information needed from my side.
Eagerly awaiting your replies.

### Your system configuration
Operating system: RHEL 6.5
Compiler: g++ 4.4.7
CUDA version (if applicable): 7.0
CUDNN version (if applicable): 7.0.4.0
BLAS: mkl
Python or MATLAB version (for pycaffe and matcaffe respectively): 2.7.10

**Comment by progirep** [comment]
I'm not a Caffe user, but your g++ version is *very* old and lacks C++11 support (according to http://stackoverflow.com/questions/23523634/compiling-c11-on-g-4-4-7-in-red-hat-linux) - you may need to update your compiler.

**Comment by puneet336** [comment]
thankyou for quick reply, 
i am now retrying with an older verion of matlab, now i have some different issue.
