### ISSUE TITLE
matcaffe compilation error- No such "header" file or directory

### ISSUE THREAD

**Issue by puneet336** [BVLC/caffe#4960]
Hi all,
I am having issues compiling matcaffe for caffe rc3. Though i was able to make caffe & pycaffe successfully.
Error log is attached herewith.
I understand that this is a simple error , but i am unable to debug it yet. Though this error crops up only when i do **make matcaffe**, whereas **make pycaffe and -simple make- ran fine.**

I have all prerequisite libraries(glog protobuf etc.) at **non standard path**, so, I tried putting all the include paths within **C_INCLUDE_PATH,** and similarily my LD_LIBRARY_PATH points to lib/lib64.
I tried providing paths in Makefile.config(attached) also  via **INCLUDE_DIRS**  variable,
but i end up with same error.

Since this issue crops up when matlab(matcaffe) is involved , so  **i guess** mexopts.sh 's setting are at fault here, but i cannot modify its setting(matlab installation is shared with other users).

Though i retried after creating soft link for all CUDA header files within  /home/user/CAFFE/caffe/include/, and all CUDA related errors disapeared. But there should be a better way than this. 

Please let me know if any other information is needed from my side.
Eagerly awaiting your replies.
[error1.log.txt](https://github.com/BVLC/caffe/files/578540/error1.log.txt)
[Makefile.config.txt](https://github.com/BVLC/caffe/files/578542/Makefile.config.txt)

### Your system configuration
Operating system: RHEL 6.5
Compiler: g++ 4.4.7
CUDA version (if applicable): 7.0
CUDNN version (if applicable): 7.0.4.0
BLAS: mkl
MATLAB: R2014b
Python or MATLAB version (for pycaffe and matcaffe respectively): 2.7.10

**Comment by williford** [comment]
Does `make clean`, `make all -j 12`, `make test`, `make runtest` all build successfully?

The first line of your error1.log.txt it says:

    common.hpp:5:27: error: gflags/gflags.h: No such file or directory

What is the result to:

    ls /home/apps/LIBGFLAGS/2.1.2/gnu//include/gflags/

?

Perhaps you should remove the double slashes, just in case matlab chokes on it?

**Comment by shelhamer** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
