### ISSUE TITLE
I have two identical GPUs in my machine but when fine tune it seems only one of them is used #3

### ISSUE THREAD

**Issue by abner2015** [BVLC/caffe#4967]
I have two identical GPUs in my machine but when fine tune resnet56 it seems only one of them is used.h
i had try the two cmd
$caffe train -solver solver.prototxt -weight restnet56.caffemodel -gpu all
$caffe train -solver solver.prototxt -weight restnet56.caffemodel -gpu 0,1
watch  the cmd
$nvidia-smi
it only show gpu 0 use 89% memory ,and the 1 is 0%
at last, get the error: check failed:error == cudasuccess(2 vs. 0) out of memory
thanks for u help!

**Comment by Luonic** [comment]
>check failed:error == cudasuccess(2 vs. 0) out of memory
Reduce batch size

**Comment by abner2015** [comment]
when the batch size is 1, but it did not work.  only one gpu working

**Comment by shelhamer** [comment]
Testing currently only makes use of a single GPU while training can parallelize over multiple GPUs. See the new parallelism in #4563.
