### ISSUE TITLE
Segmentation fault (core dumped) after add a new python layer

### ISSUE THREAD

**Issue by NHZlX** [BVLC/caffe#4968]
**I added a new data layer using python,   but there was this bug*

I1111 14:14:26.862687 11970 layer_factory.hpp:77] Creating layer data
I1111 14:14:26.927407 11970 net.cpp:109] Creating Layer data
I1111 14:14:26.927490 11970 net.cpp:418] data -> data
I1111 14:14:26.927522 11970 net.cpp:418] data -> rois
I1111 14:14:26.927554 11970 net.cpp:418] data -> labels
Segmentation fault (core dumped)

**By positioning，I found the place that caused bug.**

   if (share_from_root) {
      // Set up size of top blobs using root_net_
      
      cout << "hello1" << endl;
      const vector<Blob<Dtype>*>& base_top = root_net_->top_vecs_[layer_id];
      const vector<Blob<Dtype>*>& this_top = this->top_vecs_[layer_id];
      for (int top_id = 0; top_id < base_top.size(); ++top_id) {
        this_top[top_id]->ReshapeLike(*base_top[top_id]);
        LOG(INFO) << "Created top blob " << top_id << " (shape: "
            << this_top[top_id]->shape_string() <<  ") for shared layer "
            << layer_param.name();
      }
    } else {
     // it' here
      layers_[layer_id]->SetUp(bottom_vecs_[layer_id], top_vecs_[layer_id]);
    }

could u help me, thanks

**Comment by mjjdick** [comment]
so, How did you solve this porblem? I met the same error! thx for you help
