### ISSUE TITLE
I set the channel in deploy.txt =1 because my images are grayscal images. I need to add is_color=false in data_image_param. First of all in the Alexnet train_val.prototxt there is data_param and not data_image_param!!!! and when I add is_color in data_param I get this error "caffe.DataParameter" has no field named "is_color". Can you please help me?

### ISSUE THREAD

**Issue by masaff** [BVLC/caffe#4972]
Please use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) for usage, installation, or modeling questions, or other requests for help.
_Do not post such requests to Issues._ Doing so interferes with the development of Caffe.

Please read the [guidelines for contributing](https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md) before submitting this issue.

### Steps to reproduce

If you are having difficulty building Caffe or training a model, please ask the caffe-users mailing list. If you are reporting a build error that seems to be due to a bug in Caffe, please attach your build configuration (either Makefile.config or CMakeCache.txt) and the output of the make (or cmake) command.

### Your system configuration
Operating system:
Compiler:
CUDA version (if applicable):
CUDNN version (if applicable):
BLAS:
Python or MATLAB version (for pycaffe and matcaffe respectively):

**Comment by williford** [comment]
Please use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) for usage, installation, or modeling questions, or other requests for help.
_Do not post such requests to Issues._ Doing so interferes with the development of Caffe.

**Comment by williford** [comment]
We are happy to help you on caffe-users or stackoverflow.com (tag questions with caffe). Closing issue.
