### ISSUE TITLE
make: *** [runtest] aborted (core dumped)

### ISSUE THREAD

**Issue by IronDroid2088** [BVLC/caffe#4974]
Operating system:Ubuntu14.04
CUDA version (if applicable):7.5

I have succeeded in 'make' and 'make test' in caffe, but when i 'make runtest', here comes an error.Could someone help me?
Here is my error log:
```
[ RUN      ] RandomNumberGeneratorTest/1.TestRngGaussianTimesGaussianGPU
F1112 22:17:28.007340 14019 math_functions.cu:415] Check failed: status == CURAND_STATUS_SUCCESS (201 vs. 0)  CURAND_STATUS_LAUNCH_FAILURE
*** Check failure stack trace: ***
    @     0x2b6bb5a04daa  (unknown)
    @     0x2b6bb5a04ce4  (unknown)
    @     0x2b6bb5a046e6  (unknown)
    @     0x2b6bb5a07687  (unknown)
    @     0x2b6bb816b95e  caffe::caffe_gpu_rng_gaussian<>()
    @           0x59d579  caffe::RandomNumberGeneratorTest_TestRngGaussianTimesGaussianGPU_Test<>::TestBody()
    @           0x8c5713  testing::internal::HandleExceptionsInMethodIfSupported<>()
    @           0x8bc3f7  testing::Test::Run()
    @           0x8bc49e  testing::TestInfo::Run()
    @           0x8bc5a5  testing::TestCase::Run()
    @           0x8bf8e8  testing::internal::UnitTestImpl::RunAllTests()
    @           0x8bfb77  testing::UnitTest::Run()
    @           0x467aaf  main
    @     0x2b6bb9028f45  (unknown)
    @           0x46f2a9  (unknown)
    @              (nil)  (unknown)
make: *** [runtest] aborted (core dumped)
```

**Comment by williford** [comment]
Google "CURAND_STATUS_LAUNCH_FAILURE" and if the first couple of results don't help, please ask on the caffe user list. It looks like a configuration error and not a bug in Caffe.

**Comment by shelhamer** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
