### ISSUE TITLE
unable to import caffe even after setting PYTHONPATH correctly

### ISSUE THREAD

**Issue by varshaneya** [BVLC/caffe#4976]
I have done the installation as per the procedure mentioned in http://caffe.berkeleyvision.org/installation.html and have also set PYTHONPATH to /path/to/caffe/python

Still I am unable to import caffe in python. Please help.

Operating system: Ubuntu 16.04
Python:2.7.12

**Comment by williford** [comment]
If you post this question on the caffe user mailing list or on stackoverflow (with Caffe tag) and close this issue, I can help. Cheers.

**Comment by williford** [comment]
Issue was resolved (https://groups.google.com/d/topic/caffe-users/UHD3LmeSkns/discussion).
