### ISSUE TITLE
The Windows version is the worst project I've ever seen in github

### ISSUE THREAD

**Issue by pobingwanghai** [BVLC/caffe#4989]
The Windows version is the worst project I've ever seen in github, I doubt whether it is tested before the commit is accepted. The code seems to be some kind of contradictory ,the additional package's version it required is different from the code in cmake files itself required .The required dir is also very weird ,I have to set the dir's value by myself in cmake . Have anyone succeed to build the caffe in windows according to the guild windows branch?

**Comment by willyd** [comment]
@pobingwanghai The windows branch is an experimental feature of caffe, a work in progress and a community based effort so you can expect some bumps. I am sorry to hear that it did not not work for you. 

I am in the process of adding a build script that will make the build process easier. If you are interested you can find it here: https://github.com/willyd/caffe/tree/build-script. Follow the TL;DR instructions in the README. This build script works on the [appveyor CI platform](https://ci.appveyor.com/project/willyd/caffe) so it should in theory work on similarly configured machines.

If you wish to have support from the community and/or active maintainers, please make constructive comments and suggest ways things can be improved.

**Comment by pobingwanghai** [comment]
Have succeed using caffe in windows ,thanks a lot
