### ISSUE TITLE
it is not easy to compile and debug windows branch caffe now.

### ISSUE THREAD

**Issue by xiaoxiongli** [BVLC/caffe#4995]
it is not easy to compile and debug windows branch caffe now.

i remember that we can use VS2013 and NUGET to compile and debug several days ago, it is so easy.

BUT, now .... how to say... 

i just wonder why not use the VS project since it is in windows platform.

**Comment by willyd** [comment]
*Please do not post usage, installation, or modeling questions, or other requests for help to Issues*. Use the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) list instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

Post your installation problems there and I or the community will be more than happy to help you with it.

As for your question, maintaining more than one build system leads to a duplication of efforts which in turn makes it more difficult to keep a working cross-platform build. CMake makes this possible while VS cannot build projects on Unix platforms. AFAIK Nuget packages tend to be out of date and lack VS 2015 support. That being said if you want to update the VS projects so they still work with the latest master I will be more that happy to merge the changes if you submit a PR.
