### ISSUE TITLE
python: import caffe failed

### ISSUE THREAD

**Issue by JakeRenn** [BVLC/caffe#4997]
### Issue summary
`Python 2.7.12 |Anaconda 4.2.0 (64-bit)| (default, Jul  2 2016, 17:42:40) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import caffe
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver
  File "caffe/pycaffe.py", line 13, in <module>
    from ._caffe import Net, SGDSolver
ImportError: /home/jake/TT100L/code/caffe/build/lib/libcaffe.so: undefined symbol: _ZN2cv8imencodeERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS_11_InputArrayERSt6vectorIhSaIhEERKSB_IiSaIiEE
>>> `

### Steps to reproduce
Since I am using Ubuntu 16.04, the version of default g++ is too high to compile caffe using **make** successfully. Instead, I compile caffe with **cmake**. Following the official instructions, I did not modify other files but this problem occurs. 

**When I import caffe within python, the error message shows as above** while I am in the directory `CAFFE_DIR/python`.

### Your system configuration
Operating system: Ubuntu 16.04
Compiler:g++ 5.4.0 (the default one of Ubuntu 16.04)
CUDA version (if applicable):CUDA-8.0
CUDNN version (if applicable): libcudnn.so.4.0.7
BLAS:
Python or MATLAB version (for pycaffe and matcaffe respectively):
pycaffe

**Comment by williford** [comment]
Questions like these should be asked on the [Caffe user mailing list](https://groups.google.com/forum/#!forum/caffe-users) or on another website, such as http://stackoverflow.com/. Please ask your question to one of these places. You will probably need to provide more information that what you did here.
