### ISSUE TITLE
make pycaffe error

### ISSUE THREAD

**Issue by simmers** [BVLC/caffe#50]
on the boost-eigen branch. 
I was able to make and make runtest and all was good. (ubuntu12.04, gtx580)

But when I ran "make pycaffe"(in the same dir), I got the following errors...

python/caffe/pycaffe.cpp: In member function ‘boost::python::api::object CaffeBlobWrap::get_data()’:
python/caffe/pycaffe.cpp:72:74: error: ‘PyArray_SetBaseObject’ was not declared in this scope
python/caffe/pycaffe.cpp: In member function ‘boost::python::api::object CaffeBlobWrap::get_diff()’:
python/caffe/pycaffe.cpp:85:74: error: ‘PyArray_SetBaseObject’ was not declared in this scope
make: **\* [py] Error 1

any ideas?

THANKS!! for making this available by the way.

**Comment by evolu8** [comment]
Would be great for this to make its way into the recommended install procedure documents.

**Comment by sealfoss** [comment]
It is, sorta.  They recommend using Anaconda.  Do that.
