### ISSUE TITLE
How to define this network

### ISSUE THREAD

**Issue by dbrazey** [BVLC/caffe#5000]
Hello, 

I am writing because I don't know how to define the last layers of my network and I hope I will find some help here :)
 
I would like to read 4 digits in an image (always 4 digits from left to right). 
One solution could be to segment the image to get the characters and then apply an OCR algorithm. 
But I would like to try to directly read the 4 digits with a CNN. 

If I use a CNN with 4 * 10 outputs, then the sum of the probabilities won't be 1 for each digit. 
I think that it will be better to have 10 outputs for each digit (the number of digits is fixed to 4 in my case). 

How may I define such a network ? 

Thanks in advance for your help :)

**Comment by williford** [comment]
Please ask your question on the [Caffe user mailing list](https://groups.google.com/forum/#!forum/caffe-users) or on another website, such as http://stackoverflow.com/ or http://stats.stackexchange.com/.

> Please use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) for usage, installation, or modeling questions, or other requests for help.
> _Do not post such requests to Issues._ Doing so interferes with the development of Caffe.
