### ISSUE TITLE
Make all error:undefined reference to `boost::thread::join()'

### ISSUE THREAD

**Issue by guody5** [BVLC/caffe#5003]
Operating system:Ubuntu14.04

When I "make all",some error come here:

CXX/LD -o .build_release/tools/upgrade_net_proto_binary.bin
.build_release/lib/libcaffe.so: undefined reference to `boost::thread::join()'
.build_release/lib/libcaffe.so: undefined reference to `boost::thread::start_thread()'
collect2: error: ld returned 1 exit status
make: *** [.build_release/tools/upgrade_net_proto_binary.bin] Error 1

I have installed libboost-dev,and there's also same error.
I don't know what I should do,and could someone help me?

**Comment by shelhamer** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
