### ISSUE TITLE
win10 install error  for cmake --target install

### ISSUE THREAD

**Issue by BianTyrion** [BVLC/caffe#5004]
I do this:
cmake --build . --config %CMAKE_CONFIGURATION% --target install

and I got an error :
ninja: error: unknown target 'install'

@willyd please help me ,thanks! I'm the new one who like caffe most.

**Comment by willyd** [comment]
_Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

That being said, I just wrote a single batch script that should do everything that is needed to build caffe. You can get it there: https://github.com/willyd/caffe/tree/build-script. With this branch theses steps should get you going:
```
C:\Projects> git clone https://github.com/willyd/caffe.git
C:\Projects> cd caffe
C:\Projects\caffe> git checkout build-script
:: Edit any of the options inside build_win.cmd to suit your needs
C:\Projects\caffe> scripts\build_win.cmd
```

Open a topic on the user mailing list to follow up on this. Thanks.
