### ISSUE TITLE
VS2013 CUDA7.5 compiling error C2059 and C4146

### ISSUE THREAD

**Issue by PFSWcas** [BVLC/caffe#5005]
When I compile the caffe-windows in VS2013, the compiling fails with output information as follows:

F:/Caffe/caffe-master/src/caffe/layers/batch_reindex_layer.cu(30): **error C2146: syntax error: missing“;”**(before identifier“CAFFE_GET_BLOCKS”)
F:/Caffe/caffe-master/src/caffe/layers/batch_reindex_layer.cu(30): **error C2059: syntax error:“>”**
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\BuildCustomizations\CUDA 7.5.targets(604,9): **error MSB3721**: “"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.5\bin\nvcc.exe" -gencode=arch=compute_35,code="sm_35,compute_35" -gencode=arch=compute_52,code="sm_52,compute_52" --use-local-env --cl-version 2013 -ccbin "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\x86_amd64" -I"F:\Caffe\NugetPackages\lmdb-v120-clean.0.9.14.0\build\native....\lib\native\include" -I"F:\Caffe\NugetPackages\LevelDB-vc120.1.2.0.0\build\native../..//build/native/include/" -I"F:\Caffe\NugetPackages\protobuf-v120.2.6.1\build\native../..//build/native/include/" -IF:\Caffe\NugetPackages\glog.0.3.3.0\build\native../..//build/native/include/ -IF:\Caffe\NugetPackages\gflags.2.1.2.1\build\native../..///build/native/include/ -IF:\Caffe\NugetPackages\boost.1.59.0.0\build\native....\lib\native\include\ -I"F:\Caffe\NugetPackages\hdf5-v120-complete.1.8.15.2\build\native....\lib\native\include" -IF:\Caffe\NugetPackages\OpenBLAS.0.2.14.1\build\native....\lib\native\include -IF:\Caffe\NugetPackages\OpenCV.2.4.10\build\native../../build/native/include/ -I"F:\Caffe\caffe-master\windows\libcaffe\....\src\" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.5\include" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.5\include" -G -lineinfo --keep-dir F:\Caffe\caffe-master\windows..\Build\Int\libcaffe\x64\Debug -maxrregcount=0 --machine 64 --compile -cudart static -Xcudafe "--diag_suppress=exception_spec_override_incompat --diag_suppress=useless_using_declaration --diag_suppress=field_without_dll_interface" -D_SCL_SECURE_NO_WARNINGS -DGFLAGS_DLL_DECL= -g -DHAS_LMDB -DHAS_HDF5 -DHAS_OPENBLAS -DHAS_OPENCV -D_DEBUG -D_SCL_SECURE_NO_WARNINGS -DUSE_OPENCV -DUSE_LEVELDB -DUSE_LMDB -DWITH_PYTHON_LAYER -DBOOST_PYTHON_STATIC_LIB -DUSE_CUDNN -D_UNICODE -DUNICODE -Xcompiler "/EHsc /W1 /nologo /Od /Zi /RTC1 /MDd " -o F:\Caffe\caffe-master\windows..\Build\Int\libcaffe\x64\Debug\batch_reindex_layer.cu.obj "F:\Caffe\caffe-master\src\caffe\layers\batch_reindex_layer.cu"”

I have tried to recompile CAffe-windows many times. but all failed. The basic platform info is shown below:

- OS version: windows 7 64 bit

- CUDA 7.5

- CuDNN 5.0

- VS2013 professional

- Caffe is downloaded from "https://github.com/BVLC/caffe/tree/master"

I would appreciate if you could give me some suggestions.

**Comment by willyd** [comment]
@PFSWcas You need to clone or download the windows branch: https://github.com/BVLC/caffe/tree/windows.

**Comment by PFSWcas** [comment]
Hello @willyd, I have tried the windows branch. However the compiling still failed with the same error. I also tried to reinstall VS2013, but it did not work.

**Comment by mechenghn** [comment]
Did you follow the instruction in https://github.com/BVLC/caffe/tree/windows? 

3 steps:
1. Working environment check: GPU compute capacity (must support CUDA), CuDNN requires Compute Capacity >=4.0. See https://developer.nvidia.com/cuda-gpus
2. Edit CommonSetting.prop to fit with your working environment (CUDA version, CuDNN usage, CUDA arrchitecture). Reload caffe.sln. 
3. Hit Build!

**Comment by willyd** [comment]
Closing since VS build is now deprecated.

**Comment by cheyuanxiaozi** [comment]
Hello @PFSWcas  ,the same problem is faced by me. Did you solver it?
