### ISSUE TITLE
problems of training py-R-FCN : "Check failed: error == cudaSuccess (9 vs. 0) invalid configuration argument"

### ISSUE THREAD

**Issue by chenxiang204** [BVLC/caffe#5006]

**Comment by williford** [comment]
Please ask your question on the [Caffe user mailing list](https://groups.google.com/forum/#!forum/caffe-users) or on another website, such as http://stackoverflow.com/. When you do, more information would probably be needed.

> Please use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) for usage, installation, or modeling questions, or other requests for help.
> _Do not post such requests to Issues._ Doing so interferes with the development of Caffe.

**Comment by hackershi** [comment]
As far as I know, there are two possibilities. 
(1) Your image is not jpg, but gif
(2)Your image size is smaller than 200x200(at least one dimension)
