### ISSUE TITLE
How to set Cuda Architecture manually in windows branch

### ISSUE THREAD

**Issue by Bosnigl** [BVLC/caffe#5007]
It seems that the cuda architecture (compute_, sm_) is detected automatically in the cmake based windows branch. However I want to use caffe on a different pc than the one I use for compling. Is there a way how I can set the compute_ and sm_ options manually for a GTX970 card (Cuda compute capability 5.2) in the cmake windows branch?

**Comment by dtmoodie** [comment]
Have you tried setting CUDA_ARCH_NAME to "Manual"?

**Comment by Bosnigl** [comment]
My asumption that the cuda architecture is detected automatically is based on two indicators:

1.) caffe crashes with the error message "invalid device function" when I try to use it on my 2nd computer which has a GTX970 card

2.) In the file "CMake_Cache.txt" that is generated during the compilation there is a line
CUDA_ARCH_NAME:STRING=Auto

So I dont have an idea where I could set CUDA_ARCH_NAME to "Manual".

**Comment by ShaggO** [comment]
By looking at the source code in https://github.com/BVLC/caffe/blob/master/cmake/Cuda.cmake,
It seems you should be able to set CUDA_ARCH_NAME to "Fermi", "Kepler", "Maxwell", "All", or "Manual". If you further look at the cmake manual ("man cmake"), you see that you can specify the variable by adding -DCUDA_ARCH_NAME="Manual" or whatever architecture you need to your cmake command. I believe GTX970 is a Maxwell card.

**Comment by willyd** [comment]
You can set the variable using cmake-gui. You may have to check the advanced check box.

**Comment by Bosnigl** [comment]
Thank you for your help!
I solved the issue by modifying the Cuda.cmake file.
I changed the line
set(Caffe_known_gpu_archs "20 21(20) 30 35 50")
into
set(Caffe_known_gpu_archs "52")
and I compiled with the command
-DCUDA_ARCH_NAME=All

Now it works my 2nd computer with the GTX970 card.

**Comment by erayberger** [comment]
Enable advanced mode if necessary.
ccmake gui settings:
CUDA_ARCH_BIN                    30 35 50 60 61
