### ISSUE TITLE
Standard exception MEX file upon caffe.run_tests()

### ISSUE THREAD

**Issue by mblokker** [BVLC/caffe#5012]
I have successfully compiled matcaffe on Windows 10 x64 by downloading latest caffe from here: https://github.com/BVLC/caffe/tree/windows and applying the changes from this PR: https://github.com/BVLC/caffe/pull/4928/files.

I build this using Visual Studio 2015, CMake 3.7 and MATLAB R2016a.

Build for CPU only, shared library and MATLAB interface only.

Successfully obtained caffe_.mexw64, and after putting the necessary .dlls in the same folder MATLAB recognizes the caffe command and is good to go (demo works: https://github.com/BVLC/caffe/blob/windows/matlab/demo/classification_demo.m).

After a fresh MATLAB restart, if I run `caffe.run_tests()`, MATLAB will successfully run the `test_net.m` test, but fails at the `test_solver.m` test:
```
Unexpected Standard exception from MEX file.
What() is:CHECK failed: file != NULL:
..

Error in caffe.get_solver (line 7)
pSolver = caffe_('get_solver', solver_file);

Error in caffe.Solver (line 21)
        self = caffe.get_solver(varargin{:});

Error in caffe.test.test_solver (line 22)
      self.solver = caffe.Solver(solver_file);

Error in caffe.run_tests (line 14)
  run(caffe.test.test_solver) ...
```

Rerunning the command results in a loop/freeze.

Restarting MATLAB, and running the command `run(caffe.test.test_solver)` alone, will result in a successful test run. If I run `caffe.run_tests()` after this, MATLAB will execute all tests without problems.

**Comment by willyd** [comment]
@mblokker Thanks for reporting. I will soon merge the MATLAB PR into the windows branch and will try to reproduce this. I will keep you posted.

**Comment by willyd** [comment]
@mblokker I could not reproduce this issue. Does it still exist for you?

**Comment by codecrystal** [comment]
I have a similar issue. 
I tried as below,
https://github.com/BVLC/caffe/tree/windows
with modification
https://github.com/BVLC/caffe/issues/5219

I use GPU, windows 10, cuda, cudnn, VC13, no Ninja, python 2.7, but no python layer,
With CMake generated caffe_.mexw64, I can only run caffe from matlab with  forward neural network calculation, but If I run solver for learning, matlab shuts down, something wrong with caffe_.mexw64 for solver.
Any help is appreciated.

**Comment by PENGUINLIONG** [comment]
@codecrystal It might be caused by a mismatched GPU architecture. cuDNN has codes generated for different architectures so the forward process works normally. But, according to my experience, when automatic detection fails, or the project is cross compiled without arch correction, you might receive message like this if you use the command line interface:

```
F0420 15:49:39.610424 14044 sgd_solver.cu:19] Check failed: error == cudaSuccess (8 vs. 0)  invalid device function
```

The program will then crash. So it seems you have met the same problem as well.
Try generating code for all arch platforms by adding

```
      -DCUDA_ARCH_NAME:STRING=All ^
```

after [this line](https://github.com/BVLC/caffe/blob/windows/scripts/build_win.cmd#L165).
