### ISSUE TITLE
pooling doesn't support nd-pooling.

### ISSUE THREAD

**Issue by thesby** [BVLC/caffe#5015]
pooling doesn't support nd-pooling in master branch while convolution supports. Could you please upgrade the pooling ?
#3983

**Comment by naibaf7** [comment]
@thesby 
In the meantime, there is CUDA ND-pooling support in LibDNN on the Caffe-OpenCL branch. You can disable OpenCL and just use it like the normal master branch otherwise.

**Comment by Noiredd** [comment]
There's a larger conversation about this under #5048 - let's keep it in one place.
