### ISSUE TITLE
How to do this? “then from the caffe source folder you need to configure the cmake build”

### ISSUE THREAD

**Issue by jyzhou05** [BVLC/caffe#5017]
I'm a newcomer and I've download cmake 3.7.Where should I configure the cmake?

**Comment by williford** [comment]
Please ask your question on the [Caffe user mailing list](https://groups.google.com/forum/#!forum/caffe-users) or on another website, such as http://stackoverflow.com/.

> Please use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) for usage, installation, or modeling questions, or other requests for help.
> _Do not post such requests to Issues._ Doing so interferes with the development of Caffe.
