### ISSUE TITLE
Could not find the following boost libraries

### ISSUE THREAD

**Issue by PkuRainBow** [BVLC/caffe#5023]
I just follow the instructions in [official doc](https://github.com/BVLC/caffe/tree/windows) , but when i run the 

**

> cmake -G%CMAKE_GENERATOR% -DBLAS=Open -DCMAKE_BUILD_TYPE=%CMAKE_CONFIGURATION% -DBUILD_SHARED_LIBS=OFF -DCMAKE_INSTALL_PREFIX=<install_path> -C %CAFFE_DEPENDENCIES%\caffe-builder-config.cmake  ..\

**

I always get the below error information, but I have follow the previous commands to download the libraries folder and get all the required boost library file. This is really wired! 

My computer is Windows-sever-2012-64-bit. I also tried to use the boost build by myself, but it still does not work !

![wechatimg14](https://cloud.githubusercontent.com/assets/4639578/20592268/83a7c24c-b267-11e6-88cf-63cb0dd59f09.jpeg)

**Comment by willyd** [comment]
@PkuRainBow CMake found gcc.exe on your path. You need to it tell it to use cl.exe either by executing:
```
set CC=cl
set CXX=cl
```
in a command prompt before you execute CMake or by adding `-DCMAKE_C_COMPILER=cl` and `-DCMAKE_CXX_COMPILER=cl` on the cmake command. 

Make sure to delete the build folder and start over.

**Comment by PkuRainBow** [comment]
@willyd I will try it tomorrow, thanks for your advice. I will give more information if I still suffer similar problem

**Comment by PkuRainBow** [comment]
@willyd  Hi, I meet this problem after setting 

> set CC=cl
> set CXX=cl

![problem_3](https://cloud.githubusercontent.com/assets/4639578/20613966/14f2f2ac-b304-11e6-9633-c4b3337d557b.PNG)

**Comment by PkuRainBow** [comment]
@willyd  Thanks a lot !!! The problem seems have been solved !!

**Comment by PkuRainBow** [comment]
@willyd  Hi, I meet other problem, It works OK for the original caffe. But when I add many layers implemented by myself. These layers have been tested OK in the previous VS versions. Here is the bug information :

![problem_3](https://cloud.githubusercontent.com/assets/4639578/20615111/32a06854-b311-11e6-8938-fea895ea8f6b.PNG)
