### ISSUE TITLE
Ninja : build stopped : subcommand failed

### ISSUE THREAD

**Issue by PkuRainBow** [BVLC/caffe#5027]
I have test the original caffe is Ok. So I try to add some layers implemented by myself, which all have been tested. But I meet this problem 

![problem_3](https://cloud.githubusercontent.com/assets/4639578/20615393/8007e83a-b314-11e6-8b1c-b63196f87168.PNG)

**Comment by PkuRainBow** [comment]
@willyd

**Comment by Xizario** [comment]
@PkuRainBow , Did you find a solution, I have similar problem
```
[112/156] Building CXX object tools\CMakeFiles\caffe.bin.dir\caffe.cpp.obj
C:\Users\vasil\.caffe\dependencies\libraries_v140_x64_py27_1.1.0\libraries\include\google/protobuf/message_lite.h(247): warning C4267: 'return': conversion from 'size_t' to 'int', possible loss of data
..\include\caffe/util/io.hpp(53): warning C4244: 'argument': conversion from 'uint64_t' to 'int', possible loss of data
..\tools\caffe.cpp(230): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data
..\tools\caffe.cpp(397): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data
ninja: build stopped: subcommand failed.
ERROR: Build failed
C:\git\caffe [windows]>
```

**Comment by willyd** [comment]
I often find it useful to redirect the output of ninja to a file to be able to track down errors. Otherwise you may not be able to scroll up to the error since ninja waits for all tasks to finish before reporting the failure.
