### ISSUE TITLE
When specify the solver type in the solver.prototxt, CheckType failed.

### ISSUE THREAD

**Issue by wadefelix** [BVLC/caffe#5028]
When specify the solver type in the solver.prototxt, CheckType failed.

#5009 is wrong @shelhamer 

virtual function type() shouldn't be called in constructors.
http://stackoverflow.com/questions/962132/calling-virtual-functions-inside-constructors

**Comment by shelhamer** [comment]
@wadefelix Thanks for catching this! I thought the tests would have caught this mistake regarding virtuals but apparently not. `get_solver()` continues to work but direct instantiation by `caffe.AdamSolver()` for instance does not.

I'll try to remedy this as soon as possible. For now I've reverted the commit by b644a87.

@cypof we can't rely on this for parallel solvers.
