### ISSUE TITLE
the built caffe.exe in the bin folder can not work

### ISSUE THREAD

**Issue by PkuRainBow** [BVLC/caffe#5029]
I just follow all the instruction step by step and get 5 folders without any error output.

>  {bin/    include/     lib/   python/  share/ }

So I want to test the caffe.exe to run a network.

I just call the command like this : 

> "D:\users\t-yuhyua\caffe-windows\output_build\bin\caffe.exe" train --solver=./binomial_deviance_solver.prototxt  --weights=../bvlc_googlenet.caffemodel --gpu=3  

But the caffe.exe can not work and return the error information like this : 

I am not sure if anyone could help me ? Could you show me how to use the compiled caffe.exe correctly ? @willyd 

![problem_3](https://cloud.githubusercontent.com/assets/4639578/20624567/97670360-b348-11e6-8a77-6aac8a0b37b1.PNG)

**Comment by willyd** [comment]
https://github.com/BVLC/caffe/tree/windows#running-the-tests-or-the-caffe-exectuable

**Comment by PkuRainBow** [comment]
@willyd 

I add the 3 dll files but get worse error like this   

![problem_3](https://cloud.githubusercontent.com/assets/4639578/20625596/400dc566-b34f-11e6-91d8-5b9d05b6bf0b.PNG)
