### ISSUE TITLE
The caffe.exe can not read test.jpg file correctly!

### ISSUE THREAD

**Issue by PkuRainBow** [BVLC/caffe#5030]
Hi, @willyd  the caffe.exe could run now, but I meet the problem that it can not read the *.jpg file correctly for all the script that works ok previously. The image files do exist in the corresponding paths.

I could run the caffe.exe that are built with the visual studio. I only change the path to the caffe.exe produced by Cmake. It failed to read the *.jpg files.  Could anyone help me ??

![problem_3](https://cloud.githubusercontent.com/assets/4639578/20625840/afdea0d0-b350-11e6-97ac-adf78ccf37f4.PNG)

**Comment by willyd** [comment]
@PkuRainBow 

Please use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) for usage, installation, or modeling questions, or other requests for help.
_Do not post such requests to Issues._ Doing so interferes with the development of Caffe.

Build the caffe.exe in debug and try to debug the code to see what is going on.

**Comment by PkuRainBow** [comment]
@willyd   Thanks for you advice. I will close this issue.
