### ISSUE TITLE
Error occurs when make

### ISSUE THREAD

**Issue by Narukamiko** [BVLC/caffe#5032]
CMakeFiles/caffe.bin.dir/caffe.cpp.o: In function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >* google::MakeCheckOpString<cudaError, cudaError>(cudaError const&, cudaError const&, char const*)':
caffe.cpp:(.text._ZN6google17MakeCheckOpStringI9cudaErrorS1_EEPNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKT_RKT0_PKc[_ZN6google17MakeCheckOpStringI9cudaErrorS1_EEPNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKT_RKT0_PKc]+0x40): undefined reference to `_ZN6google4base21CheckOpMessageBuilder9NewStringB5cxx11Ev'
CMakeFiles/caffe.bin.dir/caffe.cpp.o: In function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >* google::MakeCheckOpString<unsigned long, int>(unsigned long const&, int const&, char const*)':
caffe.cpp:(.text._ZN6google17MakeCheckOpStringImiEEPNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKT_RKT0_PKc[_ZN6google17MakeCheckOpStringImiEEPNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKT_RKT0_PKc]+0x40): undefined reference to `_ZN6google4base21CheckOpMessageBuilder9NewStringB5cxx11Ev'
CMakeFiles/caffe.bin.dir/caffe.cpp.o: In function `main':
caffe.cpp:(.text.startup+0x38): undefined reference to `google::SetVersionString(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
caffe.cpp:(.text.startup+0x62): undefined reference to `google::SetUsageMessage(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to `_ZNK7leveldb6Status8ToStringB5cxx11Ev'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to `leveldb::DB::Open(leveldb::Options const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, leveldb::DB**)'
collect2: error: ld returned 1 exit status
make[2]: *** [tools/caffe] Error 1
make[1]: *** [tools/CMakeFiles/caffe.bin.dir/all] Error 2
make: *** [all] Error 2

Operating system: centos 6
Compiler: gcc-5.2
CUDA version (if applicable): 8.0

**Comment by amir-abdi** [comment]
My make runs with no problem. But when I import python, I get the following error:
ImportError: /home/amir/caffe/python/caffe/../../build/lib/libcaffe.so.1.0.0-rc3: undefined symbol: _ZNK7leveldb6Status8ToStringB5cxx11Ev

It seems to have something to do with leveldb, and I have tried reinstalling leveldb which didn't work.

**Comment by Narukamiko** [comment]
Well, I think I've solved this problem. I re-compiled gflags glog and leveldb. 
I think the reason is that leveldb is not compiled gcc-5.2 as same as caffe.

**Comment by shelhamer** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
