### ISSUE TITLE
Issue with build Win10 following instructions

### ISSUE THREAD

**Issue by walgalen** [BVLC/caffe#5034]
### Issue summary
I am trying to install Caffe on my Windows, and I am following steps presented in the README, but I am unable to install.

I am also new to all of this stuff, so I am not sure whether I am doing things correctly.

### Steps to reproduce

So I have downloaded and configured conda , and also downloaded Ninja using this command:
```
> conda config --add channels conda-forge
> conda install ninja --yes
```
Then I downloaded all the dependencies ( because I have VS 2015) :
`python scripts\download_prebuilt_dependencies.py --msvc_version=v140`

Then I have set up Ninja generator:

`call "%VS120COMNTOOLS%..\..\VC\vcvarsall.bat" amd64`

And then I tried running this:

```
> set CMAKE_GENERATOR=Ninja
> set CMAKE_CONFIGURATION=Release
> mkdir build
> cd build
> cmake -G%CMAKE_GENERATOR% -DBLAS=Open -DCMAKE_BUILD_TYPE=%CMAKE_CONFIGURATION% -DBUILD_SHARED_LIBS=OFF -DCMAKE_INSTALL_PREFIX=<install_path> -C %CAFFE_DEPENDENCIES%\caffe-builder-config.cmake  ..\
> cmake --build . --config %CMAKE_CONFIGURATION%
```
I assume that **CMAKE_INSTALL_PREFIX** is a path to where my CMake is installed, right? or is path to cmake folder within main directory?

So this is what happens:
       1) when I run this command, it first complained that there is no folder called **Release** ( so I       created one)
       2) Then it complained that CMakeList.txt is not present, so I copied the one from the main folder and placed it inside the Release folder
       3) Then I was finally able to execute the command, but I am getting these errors:
      
![image](https://cloud.githubusercontent.com/assets/24197754/20645247/3491142c-b458-11e6-821f-667ab1d2be5f.png)

I know that there is a cmake folder inside the main directory, but not sure whether I should try to build from there, or from a different spot; and what should I possibly change.

### Your system configuration
Operating system: WIndows 10
Tried using Ninja

**_EDIT1:_**
I have tried modifying all the include paths by appending "../../" to the start of each one of them and that seems to resolve most of the cases, but many files need to be changed.

**_Am I still doing something wrong ( is there a faster way) in case I need to use a different machine, or someone else decides to run my code?_**

Moreover, I am now getting  additional errors:

![image](https://cloud.githubusercontent.com/assets/24197754/20645494/b232082a-b460-11e6-8872-fcc076706d6a.png)

and I have no clue how to solve those issues.

**Comment by walgalen** [comment]
I have tried modifying all the include paths by appending "../../" to the start of each one of them and that seems to resolve most of the cases, but many files need to be changed.

Am I still doing something wrong ( is there a faster way) in case I need to use a different machine, or someone else decides to run my code?


Moreover, I am now getting an additional error:

![image](https://cloud.githubusercontent.com/assets/24197754/20645382/28172376-b45d-11e6-88d6-9d14372b4d3f.png)
Is it required to install those additional libraries?

**Comment by willyd** [comment]
> call "%VS120COMNTOOLS%..\..\VC\vcvarsall.bat" amd64

You need (notice the 120 to 140 change)
```
> call "%VS140COMNTOOLS%..\..\VC\vcvarsall.bat" amd64
```

> I assume that CMAKE_INSTALL_PREFIX is a path to where my CMake is installed, right? or is path to cmake folder within main directory?

No it is the directory where all the caffe files will get installed after you build the install target. It can be any directory you have write access to. It defaults to a folder called install in your build directory.

> I know that there is a cmake folder inside the main directory, but not sure whether I should try to build from there, or from a different spot; and what should I possibly change.

No all commands should be executed from the build directory.

Can you:

- Download this [script](https://raw.githubusercontent.com/willyd/caffe/build-script/scripts/build_win.cmd) to your caffe\scripts folder
- And execute it `call scripts\build_win.cmd`

Try to work from a directory that does not contain spaces and/or special characters.

**Comment by walgalen** [comment]
Oh yeah, I actually ran it, just forgot to mention that I have actually changed it.

I ran build_win, but I am getting this error:
![image](https://cloud.githubusercontent.com/assets/24197754/20649290/5f8bab10-b4bc-11e6-98d2-ab48d2a9c970.png)

**Comment by willyd** [comment]
@walgalen Please attach a text file with the output of the build_win.cmd.

**Comment by walgalen** [comment]
This is the text file
[output.txt](https://github.com/BVLC/caffe/files/614820/out.txt)

**Comment by willyd** [comment]
>   nvcc fatal   : nvcc cannot find a supported version of Microsoft Visual Studio. Only the versions 2010, 2012, and 2013 are supported

You are trying to build using VS 2015 and CUDA 7.5. If you want to use VS 2015 you need to use CUDA 8.0. Otherwise, you need to downgrade to VS 2013.

**Comment by walgalen** [comment]
Yes, so I have updated to CUDA 8.0, but still could not build. Turns out I had to delete that folder and redownload the repo. 
Afterwards, it went smoothly.
Thank You.

**Comment by Jumabek** [comment]
I believe, there was some leftover from your previous attempts to build. and that leftover was gone when you downloaded a fresh repo.
