### ISSUE TITLE
dose caffe group want to add  hdfs support

### ISSUE THREAD

**Issue by qingzew** [BVLC/caffe#5046]
I add hdfs support to caffe in [here](https://github.com/qingzew/caffe_hdfs/tree/direct_hdfs), below is something I do:
1. extract tensorflow's hdfs lib
2. rewrite caffe's `src/caffe/util/io.cpp`
3. write `tools/convert_image_to_hdfs.cpp`
4. wirte  layer `hdfs_data_layer`
5. example in [here](https://github.com/qingzew/caffe_hdfs/tree/direct_hdfs/examples/mnist_hdfs)

and some bugs to fix.

so anyone is interested in this?

**Comment by shelhamer** [comment]
Thanks for asking, but this is not a common request so I'm closing for now.
