### ISSUE TITLE
Has anyone implmented this paper "CNN: Single-label to Multi-label"?

### ISSUE THREAD

**Issue by bitwangdan** [BVLC/caffe#5050]
I want to use multi-label on my image dataset ,does anyone implment this paper?

**CNN: Single-label to Multi-label**

**Comment by shelhamer** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

**Comment by ravikrn** [comment]
@bitwangdan were you able to implement this paper?
