### ISSUE TITLE
Install pycaffe caffe-windows

### ISSUE THREAD

**Issue by walgalen** [BVLC/caffe#5053]
### Issue summary
I am trying to run a certain NN, but straightaway I am getting error that:

> no module named 'caffe' exists.

I am also using Anaconda, which does not create PYTHONPATH, so I am not sure how to add it.

How are you able to install pycaffe on the windows distro?

### Steps to reproduce

I have added caffe-windows/python to path, but that seems to have no effect. 

### Your system configuration
Operating system: Win10 
Compiler: VS2015
CUDA version (if applicable): 8.0
CUDNN version (if applicable):5.1
Python or MATLAB version (for pycaffe and matcaffe respectively): Python 2.7

**Comment by willyd** [comment]
From a cmd.exe terminal in the root of the caffe source directory try:
```
C:\Projects\caffe\> build\libraries\prependpath.bat
C:\Projects\caffe\> cd python
C:\Projects\caffe\python\> copy "%path_to_cudnn%\cudnn-8.0-windows10-x64-v5.1\cuda\bin"\cudnn64_5.dll caffe
C:\Projects\caffe\python\> python -c "import caffe; print(caffe.__version__)" 
```
you should get `1.0.0-rc3`

**Comment by walgalen** [comment]
@willyd thank You. However, does that mean that I need to run all my code from this directory?

**Comment by willyd** [comment]
No. You need to things:
1. Python needs to be able to find the caffe package in your python path
2. The OS needs to able to find the dependencies (DLLs) of your package in its usual search folders.
You have many options to get this working:
1.
 - Copy the caffe package (the caffe directory inside caffe\python) to your site-packages folder inside your python install.
- Use the following **before** importing caffe in your script
```
import sys
sys.append(r'full\path\to\caffe\python')
```
- Write a [caffe.pth](https://docs.python.org/2/library/site.html) file to point your python.exe to the location of the caffe package. 
2. 
- Use the prependpath.bat to update your PATH temporarily and work from that terminal.
- Add the paths in the prependpath.bat to your PATH variable permanently by using setx of by using the Environment Variables dialog in the Computer properties
- Copy the required DLLs next to caffe_.pyd in your caffe\python\caffe folder.

If this works for your I would accept a PR updating the README.md to help others having trouble to get pycaffe working.

**Comment by walgalen** [comment]
I will give it a try and report on the progress.

**Comment by nikAleksandr** [comment]
Also along these lines, you write regarding the pycaffe install in the main README, "Also, you need to edit your PATH or copy the required DLLs next to the caffe.pyd file." Could you explain that in more detail for me, please?

**Comment by nikAleksandr** [comment]
Figured this out. Needed to use `sys.path.append` instead of `sys.append`

**Comment by willyd** [comment]
Updated my comment accordingly.

**Comment by nikAleksandr** [comment]
Thanks, so along this same issue, I now can't seem to get the build to be incorporated as a module. I'm sure I'm missing something very obvious, but I don't know whether I copied the appropriate folder into my python site-packages folder (Side Question: If we are only using caffe/python/caffe, why was the build required at all?). I also don't know where to find "the required DLLs" to copy. Apologies for being in over my head. Trying to learn something new.

This is the readout I'm getting in cmd:
`Traceback (most recent call last):
  File "style.py", line 39, in <module>
    import caffe
  File "C:\...\Anaconda2\lib\site-packages\caffe\__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropSolver, AdaDeltaSolver, AdamSolver
  File "C:\...\Anaconda2\lib\site-packages\caffe\pycaffe.py", line 13, in <module>
    from ._caffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, \
ImportError: DLL load failed: The specified module could not be found.`

**Comment by willyd** [comment]
> Thanks, so along this same issue, I now can't seem to get the build to be incorporated as a module. I'm sure I'm missing something very obvious, but I don't know whether I copied the appropriate folder into my python site-packages folder

Assuming you cloned the caffe repo in C:\Projects\caffe, when you build caffe it will copy the caffe.pyd (the compiled part of the caffe python package into) C:\Projects\caffe\python\caffe. To make caffe available in your python install you can copy the C:\Projects\caffe\python\caffe  folder into your site-packages folder. 

This will make the caffe package available to your python executable.

> (Side Question: If we are only using caffe/python/caffe, why was the build required at all?)

caffe-builder is a bit of a misnomer since it does not actually build caffe but only its dependencies. So you can't download a pre-built version of caffe from this project. I will soon make a download available from the CI server but this is not available as we speak.

> I also don't know where to find "the required DLLs" to copy.

You can use dependency walker to find the required dlls and only copy those. Alternatively you can copy all the dlls in C:\Projects\caffe\build\libraries\bin, C:\Projects\caffe\build\libraries\lib and C:\Projects\caffe\build\libraries\x64\vc[12|14]\bin and you should be good to go. You need to copy those DLLs next to caffe.pyd.

If any of this helps you solve the issue you are having and would be so kind to send a PR updating the README so that other people can benefit from it that would be great.

**Comment by nikAleksandr** [comment]
Obviously other people got this to work, I'm unsure exactly what is missing here. I'm happy to send a PR once we get this figured out.

I went ahead and copied over all the DLLs, in the ...\site-packages\caffe\ folder, next to _caffe.pyd

I'm still getting the same error when I try to import caffe:
`Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\...\Anaconda2\lib\site-packages\caffe\__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropSolver, AdaDeltaSolver, AdamSolver
  File "C:\...\Anaconda2\lib\site-packages\caffe\pycaffe.py", line 13, in <module>
    from ._caffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, \
ImportError: DLL load failed: The specified module could not be found.`

**Comment by willyd** [comment]
Did you compile with cudnn? If so copy the cudnn dll too. 

Did you use the shared library build? If so copy the caffe.dll too.

If that does not solve it download [dependency walker](http://www.dependencywalker.com/depends22_x64.zip) and drag and drop the _caffe.pyd into it. Then look for missing dlls in there.

**Comment by nikAleksandr** [comment]
Yes, I did! That was the issue. Thanks so much for your help and patience!
I'll submit a PR with the updated advice for this repo.

On Tue, Dec 20, 2016 at 4:05 PM Guillaume Dumont <notifications@github.com>
wrote:

Did you compile with cudnn? If so copy the cudnn dll too.

Did you use the shared library build? If so copy the caffe.dll too.

If that does not solve it download dependency walker
<http://www.dependencywalker.com/depends22_x64.zip> and drag and drop the
_caffe.pyd into it. Then look for missing dlls in there.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/BVLC/caffe/issues/5053#issuecomment-268359328>, or mute
the thread

**Comment by nikAleksandr** [comment]
Was missing the cudnn DLL files. Thanks for your help and patience. Will submit a PR asap.

**Comment by avipars** [comment]
I have the same exact issue but in ubuntu 16.04. How can I fix it?

**Comment by aureosun** [comment]
I have the same problem as nikAleksandr above,and I still cannot solve it ,The specific dll is what?I really don't konw,please help me,Sir!
windows server 2012 R2 standard miniconda2
build with vs2013 no gpu

Traceback (most recent call last): File "<string>", line 1, in <module> File "C:\...\Anaconda2\lib\site-packages\caffe\__init__.py", line 1, in <module> from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropSolver, AdaDeltaSolver, AdamSolver File "C:\...\Anaconda2\lib\site-packages\caffe\pycaffe.py", line 13, in <module> from ._caffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, \ ImportError: DLL load failed: The specified module could not be found.

**Comment by amwallis** [comment]
Moving the `python\caffe` folder to `...\site-packages\` and then copying all the .dll files in `caffe-windows\build\bin` next to _caffe.pyd worked for me

Windows 7 with miniconda2
Built with vs2015 and no gpu

**Comment by megh500** [comment]
i copied caffe folder into site-packages but i do not have build/bin to copy
i face with error when i want to import caffe
![caffe](https://cloud.githubusercontent.com/assets/25628213/26186167/6a8fd716-3b44-11e7-8874-4fa0877cd0a3.png)
what should i do?

**Comment by willyd** [comment]
From README.md:

https://github.com/BVLC/caffe/tree/windows#using-the-python-interface

**Comment by NaveenBandi** [comment]
@willyd ,
I am new to caffe, I have installed caffe in windows with CPU, there is no CUDA and got all the binaries built. But when I import caffe from python I get the DLL loading Error.
In my /build/tools/release , I have all the binaries. In my caffe/python I have all the DLL's and _.caffe.pyd file.
I have installed VS2015, python 2.7, cmake and git. I have attached few folder kindly refer through them and suggest. 

I have copied the files shown in pycaffe pic to my python/lib/site_packages.
The contents in the caffe_pic  pic are the binaries built and present in release folder.
The contents in the python pic are the binaries present in the caffe/python/caffe folder.

I am try to build only for python in windows CPU_only system.

Please help.
Eagerly waiting for your reply.

The error I get when I import caffe is shown in error pic.
![error](https://user-images.githubusercontent.com/23726777/33652214-879f76b0-da8e-11e7-9c12-bb607e8a24fd.JPG)

![pycaffe](https://user-images.githubusercontent.com/23726777/33651995-b567fc12-da8d-11e7-8742-c6a911281d66.JPG)
![caffe_pic](https://user-images.githubusercontent.com/23726777/33651996-b5a479b2-da8d-11e7-9fad-79881a48e9ee.JPG)
![python](https://user-images.githubusercontent.com/23726777/33651997-b5e10346-da8d-11e7-9cb7-f1bbcdbcadd7.JPG)

**Comment by willyd** [comment]
@NaveenBandi Looks like you compiled using python 3.5 and are trying to use this build with python 2.7. Do you have both installed? Make sure CMake finds the right python version when you buiild. You may need to set the [PYTHON_EXECUTABLE](https://cmake.org/cmake/help/v3.10/module/FindPythonInterp.html) variable for that.

**Comment by NaveenBandi** [comment]
@willyd Thank You. I sorted the issue, it was the same problem....
I request you to check an issue I have posted, while i create lmdb.
