### ISSUE TITLE
How to implement VAE/DCGAN with upsampling (aka. backward convolution or fractional striding) in caffe? 

### ISSUE THREAD

**Issue by darkAlert** [BVLC/caffe#5055]
How to implement VAE/DCGAN (decoder/generator) with upsampling layer (aka. backward convolution or fractional striding) in caffe?

I was able to implement the GAN (because only InnerProductLayer is needed). But I encountered a problem with upsampling operation while implementing decoder/generator net.

**Comment by vra** [comment]
Hi @darkAlert, can you share your solution to implement the GAN using caffe? Thanks!

**Comment by zhangqianhui** [comment]
@darkAlert Thanks for your sharing your solution to implement the gan ?

**Comment by jeremy-rutman** [comment]
There is a deconvolution layer available out of the box - did you get somewhere with dcgan?

**Comment by shelhamer** [comment]
Please discuss modeling and usage on the mailing list.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
