### ISSUE TITLE
Check failed: data_ MemoryDataLayer needs to be initialized by calling Reset

### ISSUE THREAD

**Issue by twmht** [BVLC/caffe#5059]
### Issue summary
When forwarding,  caffe throws the exception

```
F1203 21:59:44.501570  7156 memory_data_layer.cpp:110] Check failed: data_ MemoryDataLayer needs to be initialized by calling Reset
```

### Steps to reproduce
```
    Net<float>* net2_(new caffe::Net<float>(DEEP_DRIVE_NET, caffe::TEST));
    std::vector<cv::Mat> frames;
    frames.push_back(image);
    std::vector<int> labels(frames.size());
    MemoryDataLayer<float> *m_layer = (MemoryDataLayer<float> *)net2_->layers()[0].get();  
    m_layer->AddMatVector(frames, labels);

    net2_->Forward();
```

### Your system configuration
Operating system: Windows 10
Compiler: msvc 2013
CUDA version (if applicable): 8.0
CUDNN version (if applicable): 5.1

I found that `Reset` function is called in `AddMatVector`

Here is the source of memory data layer
https://github.com/BVLC/caffe/blob/master/src/caffe/layers/memory_data_layer.cpp

Is this a bug?

Thank you.

**Comment by willyd** [comment]
No idea, I actually never used the MemoryDataLayer. Are you able to reproduce this on a UNIX system? That would at least disambiguate if this is a windows only issue.

**Comment by twmht** [comment]
@willyd 

I think this is maybe a windows only problem, since I am using shared library of caffe.

And You claim that the shared library has some test failure.

**Comment by twmht** [comment]
hi @willyd 

I have built a minimal example which can reproduce my problem (https://github.com/twmht/forTesting).

**Comment by willyd** [comment]
Closing use InputLayer instead. See https://github.com/BVLC/caffe/issues/5493#issuecomment-292289183
