### ISSUE TITLE
It looks like the fps would decrease when run caffe model even the mnist

### ISSUE THREAD

**Issue by tangjiuqi097** [BVLC/caffe#5061]
### Issue summary
When run the caffe model ,it seems the fps will decrease .And sometimes the fps would not increase untill restart the computer. I try to reinstall ubuntu14.04 and caffe  ,but it can not help .

### Your system configuration
Operating system:utuntu14.04
Compiler:
CUDA version (if applicable):8.0.44
CUDNN version (if applicable):non
BLAS:
Python or MATLAB version (for pycaffe and matcaffe respectively):MATLAB

I am sorry for I do not know how to find out what the compiler and BLAS is.

**Comment by williford** [comment]
Please ask your question on the [Caffe user mailing list](https://groups.google.com/forum/#!forum/caffe-users) or on another website, such as http://stackoverflow.com/.

> Please use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) for usage, installation, or modeling questions, or other requests for help.
> _Do not post such requests to Issues._ Doing so interferes with the development of Caffe.

**Comment by tangjiuqi097** [comment]
I am so sorry.Thank you all the way.

**Comment by tangjiuqi097** [comment]
I am so sorry .I have misunderstood it.Thank you all the way.
