### ISSUE TITLE
How to use Redis as backend DB?

### ISSUE THREAD

**Issue by marcoippolito** [BVLC/caffe#5064]
Hi ,
after putting some samples of into Redis DB, I extracted one Minibatch (32 examples).

  stringsVect firstKeysMinibatch = keysbatchesList.at(0);
  for(auto k : firstKeysMinibatch) {
    client.get(k, [](cpp_redis::reply& reply) {
      snaPairsVectsStringVectTuple resultingTuple = convertBinaryToSnaPairsVectsStringVectTuple(reply.as_string());
    });
    client.sync_commit();
  }
resultingTuple contains all the data of one single example.

I'm setting the .protxt up as follows:
name: "Proto"
layer {
  name: passage
  # Data layer loads leveldb DB for high-thoughput
  type: "Data"
  # the 1st top is the data itself : the name is only convention
  top: "data"
  # the 2nd top is the ground truth : the name is only convention
  top: "label"
  # The Data layer configuration
  data_param {
    # path to the DB
    source: "/home/marco/disco_vecchio/CNN_Tut/textComprehension/passagesDB"
    # type of DB: LEVELDB or LMDB
    backend: REDIS
    # batch processing improves efficiency
    batch_size: 32
  }
}
layer {
  name: bidirectionalRNN
  type: "RNN"
  bottom: "Data"
  top: "RNN"

  rnn_param {
    num_output:
    clipping_threashold: 10
    dropout_rate=0.2
  }
}

The question is: how to pass this example to the subsequent NN layer?

Looking forward to your kind help.
Marco
PS: I'm using Ubuntu 16.04 , cpu-only mode

**Comment by williford** [comment]
Questions like these should be asked on the [Caffe user mailing list](https://groups.google.com/forum/#!forum/caffe-users) or on another website, such as http://stackoverflow.com/. Please ask your question to one of these places.
