### ISSUE TITLE
Problem saving mean image as binaryproto in python

### ISSUE THREAD

**Issue by mary-alegro** [BVLC/caffe#5065]
I'm  trying to save my mean image as a binaryproto file using Python. I'm using the following code

    blob = caffe.io.array_to_blobproto(np.asarray([mean_img]))
    binaryproto_file = open(binary_file, 'wb+')
    binaryproto_file.write(blob.SerializeToString())
    binaryproto_file.close())

where the mean_image shape is [3,227,227]. I followed the suggestion in this post: https://groups.google.com/forum/#!searchin/caffe-users/binaryproto|sort:relevance/caffe-users/6eK459nwvMQ/Zx35GSbDWG8J

However, when I try to read the file I get the following error:
**F1205 14:04:29.775773 2752512 data_transformer.cpp:257] Check failed: img_channels == data_mean_.channels() (3 vs. 227)** 

I'm using the code in the fine-tuning jupyter notebook that comes with caffe and my mean_image file as input for transform_param:

`transform_param = dict(mirror=train, crop_size=227, mean_file='my_mean_image.binaryproto')`

My caffe was compiled in mac os El Capitan using Anaconda. 

Would anybody know how to fix this?

Thank you!

**Comment by williford** [comment]
Try to reshape mean_image to be [1,3,277,277].

**Comment by mary-alegro** [comment]
It worked!
Instead of using
`blob = caffe.io.array_to_blobproto(np.asarray([mean_img]))`
I used
`    mean_img = mean_img.reshape([1,3,227,227])
    blob = caffe.io.array_to_blobproto(np.asarray(mean_img))
    binaryproto_file = open(binary_file, 'wb+')
    binaryproto_file.write(blob.SerializeToString())
    binaryproto_file.close()`

**Comment by dashesy** [comment]
I had grayscale data `cifar10` in png format using `ImageData` data reader, and had the same problem. I had to reshape to `[1,1,28,28]`. Tried both `[1,28,28]` and `[28,28,1]` and neither worked. The original shape is just `[28,28]`.
