### ISSUE TITLE
convert .raw files into lmdb or leveldb

### ISSUE THREAD

**Issue by phoenix1992** [BVLC/caffe#5071]
Hi , I want to input medical image  into Caffe framework. The medical image is .raw file and can not be compressed cause I want to keep the integrity of image data. During the converting process, it came some errors through running convert_imageset.exe. 
It seems that .raw files cannot be converted to lmdb or leveldb. How can I solve this problem?

**Comment by willyd** [comment]
Questions like these should be asked on the [Caffe user mailing list](https://groups.google.com/forum/#!forum/caffe-users) or on another website, such as http://stackoverflow.com/. Please ask your question to one of these places.
