### ISSUE TITLE
caffe.set_mode_gpu() stuck.

### ISSUE THREAD

**Issue by hzh8311** [BVLC/caffe#5072]
Suddenly, I stucked with my program, and test on python console:
```
import caffe
caffe.set_mode_gpu()
```
it stucked for a very long time, and Ctrl-C could even not kill it.
and `set_mode_cpu()` stucked too. 
Besides, I ran the `$CAFFE_ROOT/examples/mnist/train_lenet.sh`, it print
```
[...]Using GPUs 0
[...]GPU 0: Tesla K80
```
and stucked.
### My system configuration
Operating system: Ubuntu 14.04 server
Compiler:
CUDA 7.5 (if applicable):
BLAS:
Python 2.7

**Comment by shelhamer** [comment]
This is likely a CUDA driver issue. Please check your system configuration and ask for help on the mailing list.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
