### ISSUE TITLE
Create lmdb from matrix of doubles

### ISSUE THREAD

**Issue by Monk-** [BVLC/caffe#5076]
Hey, 

I have images from the ImageNet. I'm pre-processing each image in Matlab (for each image get matrix of doubles and create image from that matrix). So, Original Image -> Matrix of doubles -> Result Image

After that I create lmdb from pre-processed images and train network. 

However, I think that if I could create lmdb from matrices of doubles, instead of result images, accuracy of my network could be better.  

Thus, here comes the question. Is it possible to create lmdb, that will work with caffe, using matrices of doubles instead of images?

**Comment by shelhamer** [comment]
Please ask usage questions on the mailing list. For what it's worth, higher precision than float is almost entirely irrelevant for deep learning applications.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
