### ISSUE TITLE
caffe with openblas

### ISSUE THREAD

**Issue by tachiang** [BVLC/caffe#5079]
### Issue summary
runtime error when using caffe+openblas 

### Steps to reproduce
1. openblas installation 
 git clone https://github.com/xianyi/OpenBLAS.git
 cd OpenBLAS 
 make -j4
 make install
2. edit Caffe Makefile.config
 BLAS := open
 BLAS_INCLUDE :=  /opt/OpenBLAS/include
BLAS_LIB := /opt/OpenBLAS/lib
3. Make Caffe again
4. export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/OpenBLAS/lib
5. train my network using Caffe
6. core dump
Core was generated by `./build/tools/caffe train --solver=examples/spatialmapping/liunet_solver.protot'.
Program terminated with signal 11, Segmentation fault.
#0  0x00007fbe57bf3c07 in sched_yield () from /lib/x86_64-linux-gnu/libc.so.6
(gdb) bt
#0  0x00007fbe57bf3c07 in sched_yield () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007fbe55c698ed in blas_thread_server () from /opt/OpenBLAS/lib/libopenblas.so.0
#2  0x00007fbe57ef0e9a in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#3  0x00007fbe57c1d73d in clone () from /lib/x86_64-linux-gnu/libc.so.6
#4  0x0000000000000000 in ?? ()

p.s. caffe train works well when using caffe+atlas

### Your system configuration
Operating system: Ubuntu Linux bakup 3.13.0-34-generic #60~precise1-Ubuntu SMP Wed Aug 13 15:55:33 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
Compiler: g++ 4.6.3
CUDA version (if applicable): no
CUDNN version (if applicable): no
BLAS: open
Python or MATLAB version (for pycaffe and matcaffe respectively): no

**Comment by shelhamer** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
