### ISSUE TITLE
how to convert gray images for AlexNet fine tuning.

### ISSUE THREAD

**Issue by forloverj** [BVLC/caffe#5081]
Alexnet is three channel. But my data set is gray images, how should I do to fine tuning the Alexnet model. Can caffe input layer come true the translation from gray image to RGB images? thanks for you help.

**Comment by mblokker** [comment]
I believe the best approach is duplicating your grayscale image three times to create the required input array. Shouldn't be too hard with the interface (Python, MATLAB?) you're using.

**Comment by forloverj** [comment]
thank you @mblokker . I will have a try.
