### ISSUE TITLE
Problem in contrastive_loss_layer.cu

### ISSUE THREAD

**Issue by 1292765944** [BVLC/caffe#5082]
in the code [https://github.com/BVLC/caffe/blob/master/src/caffe/layers/contrastive_loss_layer.cu#L67](url)
I think the code should be:
`beta = -alpha * diff[i];`
Anything I did't notice?

**Comment by shaibagon** [comment]
The GPU implementation is consistent with CPU. Why do you think it should multiply by `diff[i]`? Note that this is "legacy" part of code with somewhat different way of computing the loss.
