### ISSUE TITLE
CPU usage quicly become 99%-100%

### ISSUE THREAD

**Issue by marcoippolito** [BVLC/caffe#5087]
Hi all,
in order to understand the C++ API, I ran on my Ubuntu 16.04 with INTEL Processor Core i7-4790K this example:
[https://github.com/shi-yan/caffe/tree/master/examples/cpp_tictactoe]
But with my great suprise I found the CPU load quickly become almost 99%-100% ...

Are there any ways to improve this situation?

Marco

**Comment by williford** [comment]
Please ask your question on the [Caffe user mailing list](https://groups.google.com/forum/#!forum/caffe-users) or on another website, such as http://stackoverflow.com/.

> Please use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) for usage, installation, or modeling questions, or other requests for help.
> _Do not post such requests to Issues._ Doing so interferes with the development of Caffe.
