### ISSUE TITLE
/usr/bin/ld: cannot find -lgstpbutils-1.0 issue

### ISSUE THREAD

**Issue by xiwai** [BVLC/caffe#5091]
when i was compiling caffe on the server with the OS of Ubuntu 16.04.
there occurred an error  asfollows:
/usr/bin/ld: cannot find -lgstpbutils-1.0
/usr/bin/ld: cannot find -lgstriff-1.0
/usr/bin/ld: cannot find -lgstapp-1.0
/usr/bin/ld: cannot find -lgstvideo-1.0
/usr/bin/ld: cannot find -lgstreamer-1.0
/usr/bin/ld: cannot find -lgstbase-1.0

I have located those libraries on my system ,the results are shown below:
./anaconda2/lib/libgstpbutils-1.0.so
./anaconda2/lib/libgstpbutils-1.0.la
./anaconda2/lib/libgstpbutils-1.0.so.0.800.0
./anaconda2/lib/libgstpbutils-1.0.so.0

and added the path to the LD_PATH as well. There seems to have the right symbol link and I cd to the root and find the same .so files in the path as following : 

/usr/lib/x86_64-linux-gnu/libgstpbutils-1.0.so.0.802.0
/usr/lib/x86_64-linux-gnu/libgstpbutils-1.0.so.0
There is no .so file in that path ,does it causes this error? could someone give me a solution.Thanks for your help.

**Comment by shelhamer** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
