### ISSUE TITLE
Cannot open input file "libcaffe.lib"

### ISSUE THREAD

**Issue by jazzscout** [BVLC/caffe#5094]
I am trying to build caffe for windows using Visual Studio 13. But the compilation failed wit hte error:

Error	232	error LNK1181: cannot open input file 'libcaffe.lib'	   LINK	  matcaffe.

I followed the instructions mentioned here:

"https://github.com/Microsoft/caffe/tree/master"

I am trying only "CpuOnlyBuild", henceforth I have set "UseCuDNN" to "false".
I only want ot build matlab wrapper, consequently I also set "PythonSupport" to "false".

I checked the  ".\caffe-windows\Build\x64\Release" path for "libcaffe.lib". Althoug the .lib file is there, yet I get the compilation error "Cannot open input file libcaffe.lib".

Any help in this regard will be appreciated. 

System configuration:
Operating system: Windows 7 (x64)
Compiler: Visual Sutdio 13
CUDA version (if applicable): NA
CUDNN version (if applicable): NA
MATLAB version (for matcaffe): MATLAB version R2016b

**Comment by willyd** [comment]
If you have a problem with Microsoft's fork I suggest you open an issue there.
