### ISSUE TITLE
getting AttributeError: 'LayerParameter' object has no attribute 'weight_filter'

### ISSUE THREAD

**Issue by Sunyouh** [BVLC/caffe#5096]
### Issue summary
I am just running pycaffe lenet example code (https://github.com/BVLC/caffe/blob/master/examples/01-learning-lenet.ipynb) , and getting 

**[AttributeError: 'LayerParameter' object has no attribute 'weight_filter']**

My code is exactly same with _2. Creating the net - in[4]_ for net part, slightly different for 1. Setup part because of caffe path.

I've found few similar issues and tried with "convolution_param=dict(weight_filter...)" thing (someone said it is a quick fix) then I got another error, [AttributeError: 'ConvolutionParameter' object has no attribute 'weight_filter']

_Trace as follows:_
$ python ex_classification.py 
Traceback (most recent call last):
  File "ex_classification.py", line 37, in <module>
    lenet('mnist/mnist_train_lmdb', 64)
  File "ex_classification.py", line 35, in lenet
    return n.to_proto()
  File "/home/sunyou/Downloads/caffe-master/python/caffe/net_spec.py", line 189, in to_proto
    top._to_proto(layers, names, autonames)
  File "/home/sunyou/Downloads/caffe-master/python/caffe/net_spec.py", line 97, in _to_proto
    return self.fn._to_proto(layers, names, autonames)
  File "/home/sunyou/Downloads/caffe-master/python/caffe/net_spec.py", line 158, in _to_proto
    assign_proto(layer, k, v)
  File "/home/sunyou/Downloads/caffe-master/python/caffe/net_spec.py", line 64, in assign_proto
    is_repeated_field = hasattr(getattr(proto, name), 'extend')
AttributeError: 'LayerParameter' object has no attribute 'weight_filter'

running on Ubuntu 14.04 LTS with Python 2.7.6.
caffe-master from git repo, libprotobuf-dev from apt-get (2.5.0-9ubuntu1)

**Comment by Sunyouh** [comment]
I'm so sorry. It was totally my bad(typo)

**Comment by tongsong91** [comment]
I got the same problem these days. I did know why?

**Comment by Noiredd** [comment]
It's called `weight_filler`, double L, not `filter`.
