### ISSUE TITLE
building problem

### ISSUE THREAD

**Issue by titopuertolara** [BVLC/caffe#5100]
Hi, im trying to make caffe but i got this error:
CXX/LD -o .build_release/tools/upgrade_net_proto_binary.bin
.build_release/lib/libcaffe.so: undefined reference to `jas_stream_close'
.build_release/lib/libcaffe.so: undefined reference to `jas_image_writecmpt'
.build_release/lib/libcaffe.so: undefined reference to `tbb::task_scheduler_init::initialize(int)'
.build_release/lib/libcaffe.so: undefined reference to `TIFFReadEncodedStrip'
.build_release/lib/libcaffe.so: undefined reference to `png_set_filter'
.build_release/lib/libcaffe.so: undefined reference to `Imf_2_2::globalThreadCount()'
.build_release/lib/libcaffe.so: undefined reference to `png_error'
.build_release/lib/libcaffe.so: undefined reference to `png_set_rgb_to_gray'
.build_release/lib/libcaffe.so: undefined reference to `jpeg_read_scanlines'
.build_release/lib/libcaffe.so: undefined reference to `tbb::task::note_affinity(unsigned short)'
.build_release/lib/libcaffe.so: undefined reference to `png_set_palette_to_rgb'
.build_release/lib/libcaffe.so: undefined reference to `jpeg_alloc_huff_table'
.build_release/lib/libcaffe.so: undefined reference to `png_set_packing'
.build_release/lib/libcaffe.so: undefined reference to `Imf_2_2::ChannelList::insert(char const*, Imf_2_2::Channel const&)'
.build_release/lib/libcaffe.so: undefined reference to `jpeg_set_defaults'
.build_release/lib/libcaffe.so: undefined reference to `jas_image_readcmpt'
.build_release/lib/libcaffe.so: undefined reference to `jpeg_write_scanlines'
.build_release/lib/libcaffe.so: undefined reference to `jas_image_encode'
.build_release/lib/libcaffe.so: undefined reference to `png_set_gray_to_rgb'
.build_release/lib/libcaffe.so: undefined reference to `Imf_2_2::InputFile::header() const'
.build_release/lib/libcaffe.so: undefined reference to `tbb::task_group_context::is_group_execution_cancelled() const'
.build_release/lib/libcaffe.so: undefined reference to `Imf_2_2::hasChromaticities(Imf_2_2::Header const&)'
.build_release/lib/libcaffe.so: undefined reference to `jas_image_decode'
.build_release/lib/libcaffe.so: undefined reference to `png_set_strip_16'
.build_release/lib/libcaffe.so: undefined reference to `tbb::internal::allocate_continuation_proxy::allocate(unsigned long) const'
.build_release/lib/libcaffe.so: undefined reference to `jas_cleanup'
.build_release/lib/libcaffe.so: undefined reference to `jpeg_finish_compress'
.build_release/lib/libcaffe.so: undefined reference to `Imf_2_2::OutputFile::writePixels(int)'
.build_release/lib/libcaffe.so: undefined reference to `TIFFReadEncodedTile'
.build_release/lib/libcaffe.so: undefined reference to `tbb::task_scheduler_init::terminate()'
.build_release/lib/libcaffe.so: undefined reference to `png_create_write_struct'
.build_release/lib/libcaffe.so: undefined reference to `Imf_2_2::InputFile::setFrameBuffer(Imf_2_2::FrameBuffer const&)'
.build_release/lib/libcaffe.so: undefined reference to `TIFFGetField'
.build_release/lib/libcaffe.so: undefined reference to `jas_image_strtofmt'
.build_release/lib/libcaffe.so: undefined reference to `TIFFReadRGBATile'
.build_release/lib/libcaffe.so: undefined reference to `png_read_update_info'
.build_release/lib/libcaffe.so: undefined reference to `png_create_read_struct'
.build_release/lib/libcaffe.so: undefined reference to `Imf_2_2::InputFile::readPixels(int, int)'
.build_release/lib/libcaffe.so: undefined reference to `TIFFScanlineSize'
.build_release/lib/libcaffe.so: undefined reference to `typeinfo for tbb::task'
.build_release/lib/libcaffe.so: undefined reference to `TIFFSetField'
.build_release/lib/libcaffe.so: undefined reference to `Imf_2_2::Channel::Channel(Imf_2_2::PixelType, int, int, bool)'
.build_release/lib/libcaffe.so: undefined reference to `png_set_bgr'
.build_release/lib/libcaffe.so: undefined reference to `png_destroy_read_struct'
.build_release/lib/libcaffe.so: undefined reference to `jas_image_create'
.build_release/lib/libcaffe.so: undefined reference to `png_set_expand_gray_1_2_4_to_8'
.build_release/lib/libcaffe.so: undefined reference to `png_get_IHDR'
.build_release/lib/libcaffe.so: undefined reference to `png_write_image'
.build_release/lib/libcaffe.so: undefined reference to `jpeg_set_quality'
.build_release/lib/libcaffe.so: undefined reference to `png_set_read_fn'
.build_release/lib/libcaffe.so: undefined reference to `jas_image_getcmptbytype'
.build_release/lib/libcaffe.so: undefined reference to `TIFFSetWarningHandler'
.build_release/lib/libcaffe.so: undefined reference to `jas_cmprof_destroy'
.build_release/lib/libcaffe.so: undefined reference to `png_write_info'
.build_release/lib/libcaffe.so: undefined reference to `jpeg_resync_to_restart'
.build_release/lib/libcaffe.so: undefined reference to `png_read_end'
.build_release/lib/libcaffe.so: undefined reference to `tbb::internal::allocate_root_with_context_proxy::free(tbb::task&) const'
.build_release/lib/libcaffe.so: undefined reference to `TIFFIsTiled'
.build_release/lib/libcaffe.so: undefined reference to `png_read_image'
.build_release/lib/libcaffe.so: undefined reference to `png_set_compression_strategy'
.build_release/lib/libcaffe.so: undefined reference to `tbb::task_group_context::init()'
.build_release/lib/libcaffe.so: undefined reference to `TIFFWriteScanline'
.build_release/lib/libcaffe.so: undefined reference to `Imf_2_2::Slice::Slice(Imf_2_2::PixelType, char*, unsigned long, unsigned long, int, int, double, bool, bool)'
.build_release/lib/libcaffe.so: undefined reference to `jpeg_destroy_decompress'
.build_release/lib/libcaffe.so: undefined reference to `TIFFRGBAImageOK'
.build_release/lib/libcaffe.so: undefined reference to `TIFFOpen'
.build_release/lib/libcaffe.so: undefined reference to `jas_init'
.build_release/lib/libcaffe.so: undefined reference to `Imf_2_2::OutputFile::setFrameBuffer(Imf_2_2::FrameBuffer const&)'
.build_release/lib/libcaffe.so: undefined reference to `jpeg_CreateDecompress'
.build_release/lib/libcaffe.so: undefined reference to `jpeg_read_header'
.build_release/lib/libcaffe.so: undefined reference to `TIFFReadRGBAStrip'
.build_release/lib/libcaffe.so: undefined reference to `glXGetProcAddressARB'
.build_release/lib/libcaffe.so: undefined reference to `TIFFSetErrorHandler'
.build_release/lib/libcaffe.so: undefined reference to `jas_cmprof_createfromclrspc'
.build_release/lib/libcaffe.so: undefined reference to `Imf_2_2::Header::dataWindow() const'
.build_release/lib/libcaffe.so: undefined reference to `jpeg_stdio_src'
.build_release/lib/libcaffe.so: undefined reference to `png_set_strip_alpha'
.build_release/lib/libcaffe.so: undefined reference to `png_get_io_ptr'
.build_release/lib/libcaffe.so: undefined reference to `jas_stream_fopen'
.build_release/lib/libcaffe.so: undefined reference to `jas_matrix_create'
.build_release/lib/libcaffe.so: undefined reference to `tbb::task_scheduler_init::default_num_threads()'
.build_release/lib/libcaffe.so: undefined reference to `jpeg_destroy_compress'
.build_release/lib/libcaffe.so: undefined reference to `Imf_2_2::Header::channels()'
.build_release/lib/libcaffe.so: undefined reference to `jpeg_stdio_dest'
.build_release/lib/libcaffe.so: undefined reference to `half::_eLut'
.build_release/lib/libcaffe.so: undefined reference to `Imf_2_2::Header::channels() const'
.build_release/lib/libcaffe.so: undefined reference to `tbb::internal::get_initial_auto_partitioner_divisor()'
.build_release/lib/libcaffe.so: undefined reference to `Imf_2_2::Header::~Header()'
.build_release/lib/libcaffe.so: undefined reference to `Imf_2_2::Header::Header(int, int, float, Imath_2_2::Vec2<float> const&, float, Imf_2_2::LineOrder, Imf_2_2::Compression)'
.build_release/lib/libcaffe.so: undefined reference to `Imf_2_2::InputFile::InputFile(char const*, int)'
.build_release/lib/libcaffe.so: undefined reference to `png_write_end'
.build_release/lib/libcaffe.so: undefined reference to `Imf_2_2::OutputFile::OutputFile(char const*, Imf_2_2::Header const&, int)'
.build_release/lib/libcaffe.so: undefined reference to `tbb::task_scheduler_init::initialize(int, unsigned long)'
.build_release/lib/libcaffe.so: undefined reference to `Imf_2_2::FrameBuffer::insert(char const*, Imf_2_2::Slice const&)'
.build_release/lib/libcaffe.so: undefined reference to `Imf_2_2::ChannelList::findChannel(char const*) const'
.build_release/lib/libcaffe.so: undefined reference to `Imf_2_2::chromaticities(Imf_2_2::Header const&)'
.build_release/lib/libcaffe.so: undefined reference to `TIFFClose'
.build_release/lib/libcaffe.so: undefined reference to `jpeg_finish_decompress'
.build_release/lib/libcaffe.so: undefined reference to `png_read_info'
.build_release/lib/libcaffe.so: undefined reference to `png_set_write_fn'
.build_release/lib/libcaffe.so: undefined reference to `jpeg_start_decompress'
.build_release/lib/libcaffe.so: undefined reference to `png_set_swap'
.build_release/lib/libcaffe.so: undefined reference to `png_get_tRNS'
.build_release/lib/libcaffe.so: undefined reference to `png_set_interlace_handling'
.build_release/lib/libcaffe.so: undefined reference to `tbb::task_group_context::~task_group_context()'
.build_release/lib/libcaffe.so: undefined reference to `tbb::internal::allocate_child_proxy::allocate(unsigned long) const'
.build_release/lib/libcaffe.so: undefined reference to `jas_matrix_destroy'
.build_release/lib/libcaffe.so: undefined reference to `png_init_io'
.build_release/lib/libcaffe.so: undefined reference to `png_set_IHDR'
.build_release/lib/libcaffe.so: undefined reference to `jas_image_chclrspc'
.build_release/lib/libcaffe.so: undefined reference to `half::convert(int)'
.build_release/lib/libcaffe.so: undefined reference to `png_destroy_write_struct'
.build_release/lib/libcaffe.so: undefined reference to `jpeg_start_compress'
.build_release/lib/libcaffe.so: undefined reference to `Imf_2_2::Chromaticities::Chromaticities(Imath_2_2::Vec2<float> const&, Imath_2_2::Vec2<float> const&, Imath_2_2::Vec2<float> const&, Imath_2_2::Vec2<float> const&)'
.build_release/lib/libcaffe.so: undefined reference to `jas_image_destroy'
.build_release/lib/libcaffe.so: undefined reference to `tbb::internal::allocate_root_with_context_proxy::allocate(unsigned long) const'
.build_release/lib/libcaffe.so: undefined reference to `jpeg_CreateCompress'
.build_release/lib/libcaffe.so: undefined reference to `Imf_2_2::OutputFile::~OutputFile()'
.build_release/lib/libcaffe.so: undefined reference to `png_create_info_struct'
.build_release/lib/libcaffe.so: undefined reference to `jpeg_std_error'
.build_release/lib/libcaffe.so: undefined reference to `png_set_compression_level'
collect2: error: ld returned 1 exit status
Makefile:618: recipe for target '.build_release/tools/upgrade_net_proto_binary.bin' failed
make: *** [.build_release/tools/upgrade_net_proto_binary.bin] Error 1

i do not what to with that

thanks

Please use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) for usage, installation, or modeling questions, or other requests for help.
_Do not post such requests to Issues._ Doing so interferes with the development of Caffe.

Please read the [guidelines for contributing](https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md) before submitting this issue.

### Steps to reproduce

If you are having difficulty building Caffe or training a model, please ask the caffe-users mailing list. If you are reporting a build error that seems to be due to a bug in Caffe, please attach your build configuration (either Makefile.config or CMakeCache.txt) and the output of the make (or cmake) command.

### Your system configuration
Operating system:ubuntu 16.04
Compiler:gcc
CUDA version (if applicable):no
CUDNN version (if applicable):no
BLAS:
Python or MATLAB version (for pycaffe and matcaffe respectively):

**Comment by titopuertolara** [comment]
Solved, uncomment USE_PKG_CONFIG := 1

**Comment by liujian883** [comment]
thank you very much! I solved the error with you method

**Comment by wanghuogen** [comment]
@titopuertolara Thank you very much. The errors can be solved as your answer.
