### ISSUE TITLE
In classification, the prediction result always outputs same prediction.

### ISSUE THREAD

**Issue by kento0926** [BVLC/caffe#5102]
Hello, everyone. I use caffe windows on windows 10.
I have a question about classification.exe. I made a trained model which has 30 object class. And, I tried to evaluate an image(for example, apple). But, when I input any image to classification.exe, the prediction result always outputs same prediction. Here is the result. 

G:\caffe-windows\Build\x64\Release>classification model1/deploy.prototxt model1/caffe_alexnet_train_iter_300000.caffemodel model1/mean_lmdb model1/label.txt model1/img1.jpg
---------- Prediction for model1/img1.jpg ----------
0.0333 - "baseball-bat"
0.0333 - "baseball-glove"
0.0333 - "backpack"
0.0333 - "apple"
0.0333 - "banana"

How can I resolve it?
Thank you.

**Comment by rtgoring** [comment]
Having this same issue, what was your fix?

**Comment by kento0926** [comment]
I resolved it to change the structure in deploy.prototxt.
In my case, structure of train_val.prototxt was different from structure of deploy.prototxt. These structure must be same each other except the first layer.
