### ISSUE TITLE
LMDB Open error when make runtest on Bash on Ubuntu on Windows

### ISSUE THREAD

**Issue by ExonRen** [BVLC/caffe#5103]
I was trying to compile Caffe on Ubuntu bash on Windows 10, and get such error:
```bash
[----------] 12 tests from DataLayerTest/1, where TypeParam = caffe::CPUDevice<double>
[ RUN      ] DataLayerTest/1.TestReadCropTrainSequenceUnseededLMDB
F1218 10:50:54.662576 27876 db_lmdb.hpp:15] Check failed: mdb_status == 0 (8 vs. 0) Exec format error
*** Check failure stack trace: ***
    @     0x7f98a59d0daa  (unknown)
    @     0x7f98a59d0ce4  (unknown)
    @     0x7f98a59d06e6  (unknown)
    @     0x7f98a59d3687  (unknown)
    @     0x7f98a3ace251  caffe::db::LMDB::Open()
    @           0x4f049e  caffe::DataLayerTest<>::Fill()
    @           0x4f27b3  caffe::DataLayerTest_TestReadCropTrainSequenceUnseededLMDB_Test<>::TestBody()
    @           0x6fbc33  testing::internal::HandleExceptionsInMethodIfSupported<>()
    @           0x6f28b7  testing::Test::Run()
    @           0x6f295e  testing::TestInfo::Run()
    @           0x6f2a65  testing::TestCase::Run()
    @           0x6f5da8  testing::internal::UnitTestImpl::RunAllTests()
    @           0x6f6037  testing::UnitTest::Run()
    @           0x459fa2  main
    @     0x7f98a2d11f45  (unknown)
    @           0x4611f9  (unknown)
    @              (nil)  (unknown)
Aborted (core dumped)
make: *** [runtest] Error 134
```

If I uncomment USE_LMDB = 0 in Makefile.config, everything works well without any error. But If I insist a complete installation, things go wrong.
I've reproduced this error on windows 10 on both my laptop as well as VirtualBox.
As for my Makefile.config, CPU-only is enabled, and I use OpenBLAS. None of other options changed.

**Comment by ExonRen** [comment]
@williford Actually I'm not sure if this issue should be labelled **windows**, because the Bash on Ubuntu on Windows seems to be based on Ubuntu 14.04. I just use the original Caffe source code, instead of the Windows version, and follow the Ubuntu installation instructions.
But it should be kind of different with the "direct" Ubuntu because such error never occurs on that, although I don't know what the differences are.

**Comment by kwende** [comment]
Has anyone made any progress on this error? I'm seeing this still. 

I'm trying to do the lenet examples, and I'm unable to proceed on Bash for Windows.

```
root@BRUSH-WIN10:~/repos/caffe# build/examples/mnist/convert_mnist_data.bin data/mnist/train-images-idx3-ubyte data/mnist/train-labels-idx1-ubyte examples/mnist/mnist_train_lmdb --backend=lmdb
libdc1394 error: Failed to initialize libdc1394
F0130 13:06:10.518640  1447 db_lmdb.hpp:15] Check failed: mdb_status == 0 (8 vs. 0) Exec format error
*** Check failure stack trace: ***
    @     0x7f5ebe070daa  (unknown)
    @     0x7f5ebe070ce4  (unknown)
    @     0x7f5ebe0706e6  (unknown)
    @     0x7f5ebe073687  (unknown)
    @     0x7f5ebe546671  caffe::db::LMDB::Open()
    @           0x402989  convert_dataset()
    @           0x40242d  main
    @     0x7f5ebd251f45  (unknown)
    @           0x402476  (unknown)
    @              (nil)  (unknown)
Aborted (core dumped) 
```

**Comment by zhouphd** [comment]
Please  change to leveldb, due to the file system, lmdb may cause some issue on NTFS of  any Windows NT OS, if you insist to try to fix it, please see https://github.com/willyd/caffe-builder/issues/16 & https://github.com/BVLC/caffe/issues/2709 for more details.
Bash for Windows is just build-in OS, its API is just built upon windows, maybe can be solved by posting an issue on https://github.com/Microsoft/BashOnWindows/issues.

:)

**Comment by willyd** [comment]
LMDB now works with the current windows build. However, I could not use any official release since only the master lmdb branch contains the required fixes for LMDB to work on windows. The main issue was related to the map size of 1 TB that would actually try to create a file of this size. Since those fixes use the Win32 API I doubt that they apply here... So your best shot is to use a different backend or raise an issue with MS as suggested by @zhouphd.

**Comment by kwende** [comment]
Am I misunderstanding the commands I'm running to test the lenet examples, then? Isn't the sample data stored in LMDB? Or am I repackaging the data into LMDB with the concert binary? 

See the command I executed to get the error.

**Comment by kwende** [comment]
Convert, not concert. Sorry. I'm typing this out on my phone.

**Comment by shelhamer** [comment]
It's converting the MNIST data into lmdb. Closing as @willyd's advice sounds conclusive.
