### ISSUE TITLE
Realtime Object Detection with SSD on Nvidia Jetson TX1 not working caffe error

### ISSUE THREAD

**Issue by akilawickey** [BVLC/caffe#5104]
### Issue summary

I tried this example on Jeson TX1

https://myurasov.github.io/2016/11/27/ssd-tx1.html

ubuntu@tegra-ubuntu:~/SSD_deep_learning/ssd-tx1$ sudo ~ubuntu/SSD_deep_learning/caffe-ssd/build/tools/caffe test --model="test.prototxt" --weights="VGG_VOC0712_SSD_300x300_iter_60000.caffemodel" --iterations="10000" --gpu 0
[sudo] password for ubuntu: 
I1219 03:21:37.389559  2046 caffe.cpp:270] Use GPU with device ID 0
I1219 03:21:37.423753  2046 caffe.cpp:274] GPU device name: NVIDIA Tegra X1
[libprotobuf ERROR google/protobuf/text_format.cc:274] Error parsing text-format caffe.NetParameter: 10:18: Message type "caffe.TransformationParameter" has no field named "resize_param".
F1219 03:21:38.238714  2046 upgrade_proto.cpp:88] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: test.prototxt
*** Check failure stack trace: ***
    @       0x7f7a456718  google::LogMessage::Fail()
    @       0x7f7a458614  google::LogMessage::SendToLog()
    @       0x7f7a456290  google::LogMessage::Flush()
    @       0x7f7a458eb4  google::LogMessageFatal::~LogMessageFatal()
    @       0x7f7a70537c  caffe::ReadNetParamsFromTextFileOrDie()
    @       0x7f7a6b896c  caffe::Net<>::Net()
    @           0x409f00  test()
    @           0x408330  main
    @       0x7f7a0088a0  __libc_start_main
Aborted

### Your system configuration
Operating system: Ubuntu 16.04 LTS

**Comment by williford** [comment]
It looks like it is a mistake on the blog post, as also indicated in the comments of the blog post. The error seems pretty clear (go Caffe dev!). I'm sure you can either figure it out or contact the author of the blog.
