### ISSUE TITLE
Unexplained size mismatch in blob and param size in caffenet 

### ISSUE THREAD

**Issue by harjatinsingh** [BVLC/caffe#5106]
I am using the blvc reference caffenet for a classification problem. The code runs fine, however i am having a tough time understanding the size difference in blobs being passed from layer 4 to layer 5 without there being no intermediate layer.

layer {
  name: "conv4"
  type: "Convolution"
  bottom: "conv3"
  top: "conv4"
  param {
    lr_mult: 1
    decay_mult: 1
  }
  param {
    lr_mult: 2
    decay_mult: 0
  }
  convolution_param {
    num_output: 384
    pad: 1
    kernel_size: 3
    group: 2
    weight_filler {
      type: "gaussian"
      std: 0.01
    }
    bias_filler {
      type: "constant"
      value: 1
    }
  }
}
layer {
  name: "relu4"
  type: "ReLU"
  bottom: "conv4"
  top: "conv4"
}
layer {
  name: "conv5"
  type: "Convolution"
  bottom: "conv4"
  top: "conv5"
  param {
    lr_mult: 1
    decay_mult: 1
  }
  param {
    lr_mult: 2
    decay_mult: 0
  }
  convolution_param {
    num_output: 256
    pad: 1
    kernel_size: 3
    group: 2
    weight_filler {
      type: "gaussian"
      std: 0.01
    }
    bias_filler {
      type: "constant"
      value: 1
    }
  }
}

 These are the layer definitions, according to which the depth of blob output of layer 4 should match the input dimension size of layer 5.

However print(net.blobs['conv4'].data.shape)
gives output (50, 384, 13, 13)
and print(net.params['conv5'][0].data.shape)
gives output (256, 192, 3, 3).

Shouldn't the second param be 384 instead of 192 ?

**Comment by williford** [comment]
Please ask your question on the [Caffe user mailing list](https://groups.google.com/forum/#!forum/caffe-users) or on another website, such as http://stackoverflow.com/.

> Please use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) for usage, installation, or modeling questions, or other requests for help.
> _Do not post such requests to Issues._ Doing so interferes with the development of Caffe.
