### ISSUE TITLE
Import caffe error

### ISSUE THREAD

**Issue by DarkNavrel** [BVLC/caffe#5108]
Error:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named caffe

I'm add export PYTHONPATH=/path/to/caffe-master/python:$PYTHONPATH in ~/.bashrc
I'm  execute 
make all
make test
make runtest
make pycaffe      
make distribute

Using debian jessie, and I followed this tutorial.: https://github.com/BVLC/caffe/wiki/Ubuntu-16.04-or-15.10-Installation-Guide
Everything worked completely well during the installation but when I run a project that uses the import caffe this error happens. I've tried everything but nothing works, can anyone help me? Thank you in advance.
Already tried:
https://github.com/BVLC/caffe/issues/720
https://github.com/BVLC/caffe/issues/263
https://github.com/BVLC/caffe/issues/4389

**Comment by williford** [comment]
What does `echo $PYTHONPATH` print?

What happens when you go to /path/to/caffe-master/python and type `python -c 'import caffe'`?

You can also try dynamically adding the path (if the above works):

```
import os
import sys
caffe_root = os.environ['CAFFE_ROOT']
sys.path.insert(0, caffe_root + '/python')
import caffe
```

I'm marking this as closed, since it should have been sent to caffe-users mailing list instead or stackoverflow.

**Comment by DarkNavrel** [comment]
I got this error:
in <module>
    caffe_root = os.environ['CAFFE_ROOT']
  File "/root/anaconda2/lib/python2.7/UserDict.py", line 40, in __getitem__
    raise KeyError(key)
KeyError: 'CAFFE_ROOT'

**Comment by williford** [comment]
You need to define the environment variable CAFFE_ROOT or replace it with the path.

**Comment by DarkNavrel** [comment]
Thaks williford 
I'm define variable:
export CAFFE_ROOT=/path/to/caffe-master/python$CAFFE_ROOT  in ~/.bashrc
 Got this error:
in <module>
    import caffe
ImportError: No module named caffe

**Comment by williford** [comment]
Ask on the  [Caffe user mailing list](https://groups.google.com/forum/#!forum/caffe-users)  and I will answer you there. I don't want to keep spamming the BVLC core developers.
