### ISSUE TITLE
caffe compilation error on windows: cannot open input file '..\lib\Release\caffe.lib'

### ISSUE THREAD

**Issue by tumusudheer** [BVLC/caffe#5110]
### Issue summary
Got windows branch from here: https://github.com/BVLC/caffe/tree/windows
Using visual studio 2013
When I ran build_win.cmd > scripts\build_win.cmd
Getting the following error:

cannot open input file '..\lib\Release\caffe.lib

### Steps to reproduce
Used following build_win.cmd configuration

    if NOT DEFINED MSVC_VERSION set MSVC_VERSION=12;
    if NOT DEFINED WITH_NINJA set WITH_NINJA=0
    if NOT DEFINED CPU_ONLY set CPU_ONLY=1
    if NOT DEFINED CMAKE_CONFIG set CMAKE_CONFIG=Release
    if NOT DEFINED CMAKE_BUILD_SHARED_LIBS set CMAKE_BUILD_SHARED_LIBS=1
    if NOT DEFINED BUILD_PYTHON set BUILD_PYTHON=1
    if NOT DEFINED BUILD_PYTHON_LAYER set BUILD_PYTHON_LAYER=1
    if NOT DEFINED BUILD_MATLAB set BUILD_MATLAB=0
    if NOT DEFINED PYTHON_EXE set PYTHON_EXE=python
    if NOT DEFINED RUN_TESTS set RUN_TESTS=1
    if NOT DEFINED RUN_LINT set RUN_LINT=0
    if NOT DEFINED RUN_INSTALL set RUN_INSTALL=0`

Ran > scripts\build_win.cmd

Got following error:

"c:\caffe-windows\build\ALL_BUILD.vcxproj" (default target) (1) ->
"C:\caffe-windows\build\tools\upgrade_solver_proto_text.vcxproj" (default target) (21) ->
  LINK : fatal error LNK1181: cannot open input file '..\lib\Release\caffe.lib' [C:\caffe-windows\build\tools\upgrade_solver_proto_text.vcxproj]

Attaching compilation log (piped) and CMakeCache.txt.

### Your system configuration
Operating system: Win 10
Compiler: Visual Studio 2013 64-bit
CUDA version (if applicable): None
CUDNN version (if applicable): None
BLAS:
Python or MATLAB version (for pycaffe and matcaffe respectively):

[CMakeCache.txt](https://github.com/BVLC/caffe/files/665365/CMakeCache.txt)

[compile_log.txt](https://github.com/BVLC/caffe/files/665366/compile_log.txt)

**Comment by Sudheer-Flipkart** [comment]
I was able to figure out the resolution, not sure what the issue though:
Previously I was using CMake 3.3.7 when I was getting above error. Now I used CMake 3.7 (as the requirements say > 3.4 version), I was able to compile caffe successfully with CMake 3.7 version.

Thank you..

**Comment by tumusudheer** [comment]
I was able to find resolution not sure what the issue though.
Previously I was using CMake 3.3 version. Now when I used CMake 3.7 (as requirements say CMake > 3.4), I was able to successfully compile Caffe.

Thank you...

**Comment by naibaf7** [comment]
@tumusudheer 
I see you don't use CUDA. If you want acceleration using AMD GPUs or Intel onboard GPUs you might also want to try the OpenCL branch. It works on Windows the same way as the Windows branch.
