### ISSUE TITLE
.build_release/lib/libcaffe.so: undefined reference to `google::protobuf::internal::kEmptyString'

### ISSUE THREAD

**Issue by WenqiangJiang** [BVLC/caffe#5113]
.build_release/lib/libcaffe.so: undefined reference to `google::protobuf::internal::kEmptyString'
.build_release/lib/libcaffe.so: undefined reference to `google::protobuf::io::CodedInputStream::BytesUntilLimit()'
collect2: error: ld returned 1 exit status
make: *** [.build_release/tools/upgrade_net_proto_text.bin] Error 1
make: *** Waiting for unfinished jobs....
.build_release/lib/libcaffe.so: undefined reference to `google::protobuf::internal::kEmptyString'
.build_release/lib/libcaffe.so: undefined reference to `google::protobuf::io::CodedInputStream::BytesUntilLimit()'
collect2: error: ld returned 1 exit status
make: *** [.build_release/tools/upgrade_net_proto_binary.bin] Error 1
.build_release/lib/libcaffe.so: undefined reference to `google::protobuf::internal::kEmptyString'
.build_release/lib/libcaffe.so: undefined reference to `google::protobuf::io::CodedInputStream::BytesUntilLimit()'
collect2: error: ld returned 1 exit status
make: *** [.build_release/tools/compute_image_mean.bin] Error 1
.build_release/lib/libcaffe.so: undefined reference to `google::protobuf::internal::kEmptyString'
.build_release/lib/libcaffe.so: undefined reference to `google::protobuf::io::CodedInputStream::BytesUntilLimit()'
collect2: error: ld returned 1 exit status
make: *** [.build_release/tools/convert_imageset.bin] Error 1
.build_release/lib/libcaffe.so: undefined reference to `google::protobuf::internal::kEmptyString'
.build_release/lib/libcaffe.so: undefined reference to `google::protobuf::io::CodedInputStream::BytesUntilLimit()'
collect2: error: ld returned 1 exit status
make: *** [.build_release/tools/upgrade_solver_proto_text.bin] Error 1
.build_release/lib/libcaffe.so: undefined reference to `google::protobuf::internal::kEmptyString'
.build_release/lib/libcaffe.so: undefined reference to `google::protobuf::io::CodedInputStream::BytesUntilLimit()'
collect2: error: ld returned 1 exit status
make: *** [.build_release/tools/caffe.bin] Error 1
.build_release/tools/extract_features.o: In function `int feature_extraction_pipeline<float>(int, char**)':
extract_features.cpp:(.text._Z27feature_extraction_pipelineIfEiiPPc[_Z27feature_extraction_pipelineIfEiiPPc]+0xc31): undefined reference to `google::protobuf::internal::kEmptyString'
.build_release/lib/libcaffe.so: undefined reference to `google::protobuf::io::CodedInputStream::BytesUntilLimit()'
collect2: error: ld returned 1 exit status
make: *** [.build_release/tools/extract_features.bin] Error 1
root@anjiang-System-Product-Name:/home/anjiang/Downloads/py-R-FCN/caffe# rm ~/anaconda/lib/libm.*
rm: cannot remove ‘/root/anaconda/lib/libm.*’: No such file or directory
root@anjiang-System-Product-Name:/home/anjiang/Downloads/py-R-FCN/caffe# rm /usr/local/lib/libm.*
rm: cannot remove ‘/usr/local/lib/libm.*’: No such file or directory
root@anjiang-System-Product-Name:/home/anjiang/Downloads/py-R-FCN/caffe# rm /usr/local/lib/
Display all 143 possibilities? (y or n)
root@anjiang-System-Product-Name:/home/anjiang/Downloads/py-R-FCN/caffe# rm /usr/local/lib/
rm: cannot remove ‘/usr/local/lib/’: Is a directory

**Comment by shelhamer** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
