### ISSUE TITLE
why: datum_channels > 0 (0 vs. 0) 

### ISSUE THREAD

**Issue by Bonsen** [BVLC/caffe#5114]
First, I create lmdb files by using SSD/create_annoset.py,and run:

  1 cur_dir=$(cd $( dirname ${BASH_SOURCE[0]}  ) && pwd )
  2 root_dir=$cur_dir/../..
  3     
  4 cd $root_dir
  5     
  6 redo=1
  7 data_root_dir="$HOME/git/shenzhou"
  8 dataset_name="shenzhou"
  9 mapfile="$root_dir/data/$dataset_name/shenzhou.prototxt"
 10 anno_type="detection"
 11 db="lmdb"
 12 min_dim=0
 13 max_dim=0
 14 width=0
 15 height=0
 16     
 17 extra_cmd="--encode-type=jpg --encoded"
 18 if [ $redo ]
 19 then
 20   extra_cmd="$extra_cmd --redo"
 21 fi  
 22 for subset in trainval test
 23 do  
 24   python $root_dir/scripts/create_annoset.py  \
 25     --anno-type=$anno_type \
 26     --label-map-file=$mapfile \
 27     --min-dim=$min_dim \
 28     --max-dim=$max_dim \
 29     --resize-width=$width \
 30     --resize-height=$height \
 31     $extra_cmd \
 32     $data_root_dir \
 33     $root_dir/data/$dataset_name/$subset.txt \
 34     $data_root_dir/$dataset_name/$db/$dataset_name"_"$subset"_"$db \
 35     examples/$dataset_name
 36 done

second, I run :

cd ~/git/caffe-ssd
./build/tools/caffe train \
--solver="models/resnet152/solver.prototxt" \
--weights="models/resnet152/ResNet-152-model2.caffemodel" \
--gpu 0,1 >&1 | tee jobs/resnet152/shenzhou/SSDbonsen_512x512/Res_shenzhou_SSDbonsen_512x512.log 

I get:
_________________________________________________________________
I1222 17:33:31.462895 31226 net.cpp:408] data -> label
I1222 17:33:31.467051 31346 db_lmdb.cpp:35] Opened lmdb examples/shenzhou/shenzhou_trainval_lmdb
F1222 17:33:31.467703 31226 data_transformer.cpp:1036] Check failed: datum_channels > 0 (0 vs. 0) 
*** Check failure stack trace: ***
    @     0x7fc0fa04384d  google::LogMessage::Fail()
    @     0x7fc0fa04561c  google::LogMessage::SendToLog()
    @     0x7fc0fa04343c  google::LogMessage::Flush()

**Comment by RyanCV** [comment]
@Bonsen Hi, I also have the same problem, did you solve it??

**Comment by adamwkraft** [comment]
Be sure to double check that data was actually written to the lmdb. I just ran into this recently where the lmdb path was written correctly and even had the `data.mdb` and `lock.mdb` files. However, no data had been written to the lmdb, so the size was only like 16K.

**Comment by shanYanGuan** [comment]
@RyanCV have you  solved it？ I meet the same question.

**Comment by Bonsen** [comment]
@RyanCV Yes, I solved it three months ago.....But now I only remember little things, may the data format caused the problem.

**Comment by khalilo** [comment]
@RyanCV  How you solved the problem ?  I meet the same question.

**Comment by siminghua** [comment]
@Bonsen  It is the Picture format jpg or png  ?

**Comment by dedoogong** [comment]
@adamwkraft  hello, I met the same problem even there is the right lmdb with size of 1.8GB dat.mdb/8.2kb lock.mdb. it comes from VOC 0712 as the caffe-ssd guided. can you let me know any hint? I checked the datum's C, H, W are all 0.;;;

**Comment by shaibagon** [comment]
Please use the [caffe-users list][1] for usage, installation, or modeling questions, or other requests for help.
You may also post questions on [stackoverflow][3], make sure you tag them with `caffe` tag.  
There is also [caffe.help][4] documenting the different layers of caffe.
Do not post such requests to Issues. Doing so interferes with the development of Caffe.

Please read the [guidelines for contributing][2] before submitting this issue.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
 [3]: http://stackoverflow.com/questions/tagged/caffe
 [4]: http://caffe.help/manual/layers.html

**Comment by 179253849** [comment]
How you solved the problem ? I meet the same question.

**Comment by 179253849** [comment]
@Bonsen Can you tell me the solution of that problem?

**Comment by 179253849** [comment]
@dedoogong I have met the same problem with you. Have you s olved this problem? If you have done it ,I want you to tell me how you solved it. Thank you very much!

**Comment by liwanchong** [comment]
I have met the same problem with you. Have you solved this problem? If you have done it ,I want you to tell me how you solved it. Thank you very much!

**Comment by pengzh86** [comment]
@liwanchong I solved this problem yesterday by changing data type from "AnnotatedData" to “Data”， maybe you can have a try.

**Comment by BalajiB197** [comment]
@pengzh86  Thanks it fixed my issue.

**Comment by MeisonP** [comment]
@pengzh86 thank you, I solved the issue using your suggestion

**Comment by angeladzl** [comment]
@pengzh86 thank u very much. it works.

**Comment by angeladzl** [comment]
@pengzh86 wechat Djiangnan007
