### ISSUE TITLE
How to create a project myself with libcaffe.lib

### ISSUE THREAD

**Issue by duongnamduong** [BVLC/caffe#5118]
After build the solutions. I want to create new project using libcaffe. But I always have the problems with NugetPackages, include,... Can you help me?

**Comment by shelhamer** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
