### ISSUE TITLE
Training Caffe for Scene Parsing: Find the indices of the maximum values across the dimensions.

### ISSUE THREAD

**Issue by SivaramPrasadMudunuri** [BVLC/caffe#5129]
Hi Everyone,

I am tying to train caffe for scene parsing. My network takes input RGB image and the final layer as of now has 26 channel output (there are 26 classes in the dataset). Now I want to add one more layer to the network that takes all these 26 outputs as input and gives the output as the index of the maximum values across all the 26 channels. So that, this will be given to the Euclidean loss against the GroundTruth scene parsing map. Please let me know if there is any caffe layer that can do this task.

Input image size: Nx3x256x256 :  (no.of samples, RGB, width,height)

The output layer as of now: Nx26x256x256  : (no.of samples, no.of classes, width,height)

Output that is needed: Nx1x256x256  : (no.of samples, 1, width,height): Plz note that the values in this are nothing but the indices of the maximum values across all the 26 channels. [ie, the values of this output matrix ranges from 1 to 26]

Thank You in advance.

**Comment by shelhamer** [comment]
Please ask usage questions on the mailing list. For scene parsing you might want to try fully convolutional networks: [fcn.berkeleyvision.org](http://fcn.berkeleyvision.org).

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
