### ISSUE TITLE
I  run the exaple in caffe/examples/mnist,but how to use the model that the exmples generated?

### ISSUE THREAD

**Issue by dony616** [BVLC/caffe#5133]
please help,thank you.

**Comment by dony616** [comment]
i run the example mnist，and it works,but it just trainnig .i want how to use caffe to identify some pic，that all

**Comment by shelhamer** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
