### ISSUE TITLE
cannot use GPU inCPU-only caffe:checek mode

### ISSUE THREAD

**Issue by MVLSQ584** [BVLC/caffe#5135]
### Issue summary
runing in dos:E:\caffe\fcn.berkeleyvision.org-master\siftflow-fcn32s\solve.py
and will get this qustion:
     cannot use GPU inCPU-only caffe:check mode
but i have changed to this:
   #CPU-only switch (uncomment to build without GPU support)
  #CPU_only := 1

Any clues?give me a some help ,please

### Your system configuration
Operating system:windows
Compiler:dos
CUDA version (if applicable):
CUDNN version (if applicable):
BLAS:
Python or MATLAB version (for pycaffe and matcaffe respectively):python2.7

**Comment by willyd** [comment]
Please use the CMake build. The setting you are referring to is in the Makefile.
