### ISSUE TITLE
caffe doesn't work for dqn after setempbre 2015

### ISSUE THREAD

**Issue by joyousrabbit** [BVLC/caffe#5145]
Hello, everyone
I'm learning https://github.com/watts4speed/fast-dqn-caffe, a deep reinforcement project. However, I tried and approved that, the recent caffe cannot converge on it.

The author of the project said:"
fast_dqn doesn't work with the current head of caffe/master since something changed since September 2015 that blows up the net during training. Let me know if you find the problem, or if the current code works for you."

Do you think that it's a bug of caffe?

Hope help.

**Comment by shelhamer** [comment]
I don't believe there was an error introduced in that time and other training has kept working, so I imagine it was some untracked interface difference across the projects.
