### ISSUE TITLE
How can I get the distribution of each training data and to compute the KL divergence ?

### ISSUE THREAD

**Issue by YuetianLiu** [BVLC/caffe#5151]
Hi,

I am a new learner of caffe. Recently I have some trouble to use caffe to get the distribution of each training data and to compute the KL divergence? 
![_290](https://cloud.githubusercontent.com/assets/8369046/21599123/b995f77a-d1a2-11e6-881f-ba65df24d4a8.png)

How can I get the distribution A and B , and then compute the KL divergence between the distribution A and B ?

Thanks

**Comment by knsong** [comment]
This [SO question](http://stackoverflow.com/q/38070104/6281477) may help.

**Comment by shelhamer** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
