### ISSUE TITLE
Failed to resume training for LSTM with multi GPU

### ISSUE THREAD

**Issue by SIshijima** [BVLC/caffe#5154]
As mentioned in [#4851](https://github.com/BVLC/caffe/issues/4851) , training of lstm with multi GPU fails. 

So I'm trying caffe master with [PR#4563](https://github.com/BVLC/caffe/pull/4563) . 
It successfully train lstm with multi GPU, but it fails to resume training with the snapshot and multi GPU.

Multi GPU training --> Success.
Snapshot by MultiGPU ---> Resume with multi GPU -->Fail.
Snapshot by MultiGPU ---> Resume with single GPU -->Success.

Could anyone help me?

-----Error message when failed ------
I0101 20:55:55.651378 6305 recurrent_layer.cpp:20] Initializing recurrent layer: assuming input batch contains 10 timesteps of 30 independent streams.
I0101 20:55:56.042740 6305 recurrent_layer.cpp:150] Adding parameter 0: W_xc
I0101 20:55:56.042780 6305 recurrent_layer.cpp:150] Adding parameter 1: b_c
I0101 20:55:56.042794 6305 recurrent_layer.cpp:150] Adding parameter 2: W_hc
I0101 20:55:56.043316 6305 recurrent_layer.cpp:20] Initializing recurrent layer: assuming input batch contains 10 timesteps of 30 independent streams.
I0101 20:55:56.462378 6305 recurrent_layer.cpp:150] Adding parameter 0: W_xc
I0101 20:55:56.462421 6305 recurrent_layer.cpp:150] Adding parameter 1: b_c
I0101 20:55:56.462432 6305 recurrent_layer.cpp:150] Adding parameter 2: W_xc_static
I0101 20:55:56.462441 6305 recurrent_layer.cpp:150] Adding parameter 3: W_hc
F0101 20:55:56.544127 6305 solver.cpp:465] Check failed: Caffe::root_solver()

Thanks.

**Comment by cypof** [comment]
Not sure what's going on. Do you have a model proto and snapshot to help look? thanks

**Comment by SIshijima** [comment]
Thank you @cypof 

When resuming from snapshot with two GPUs, `Solver::Restore()` in src/caffe/solver.cpp is called twice.
At the second call, `CHECK(Caffe::root_solver());`  in the function fails.
If check removed, resuming works successfully. 
I guess it may not be proper check for PR#4563.

I'm trying [coco captioning with LSTM](https://github.com/jeffdonahue/caffe/tree/recurrent/examples/coco_caption).

**Comment by SIshijima** [comment]
I checked the master branch PR #4563 merged.
Although it works for multi-GPU training, this issue occurs still.
As mentioned before, if `CHECK(Caffe::root_solver()); `  removed, resuming works successfully.

**Comment by cypof** [comment]
Thanks, I forgot to remove it on the master version. I'm waiting on the tests for #5215 and will merge.

**Comment by SIshijima** [comment]
@cypof  Thank you.
This issue can be closed.
