### ISSUE TITLE
Caffe fails on QT  with errors  /lib/libcaffe-d.so.1.0.0-rc3: undefined reference to `cv::String::allocate(unsigned long) / cv::imread(cv::String const&, int)'/cv::String::deallocate.  No such files  /lib/libcaffe-d.so.1.0.0-rc3  

### ISSUE THREAD

**Issue by caney1989** [BVLC/caffe#5155]
I am trying to compile caffe on QT5.4.1 by cmake,  but i am getting these errors:

[ 90%] Built target caffe
Linking CXX executable caffe-d
../lib/libcaffe-d.so.1.0.0-rc3: undefined reference to `cv::String::allocate(unsigned long)'
../lib/libcaffe-d.so.1.0.0-rc3: undefined reference to `cv::imread(cv::String const&, int)'
../lib/libcaffe-d.so.1.0.0-rc3: undefined reference to `cv::String::deallocate()'
../lib/libcaffe-d.so.1.0.0-rc3: undefined reference to `cv::imencode(cv::String const&, cv::_InputArray const&, std::vector<unsigned char, std::allocator<unsigned char> >&, std::vector<int, std::allocator<int> > const&)'
collect2: error: ld returned 1 exit status
make[2]: *** [tools/caffe-d] Error 1
make[1]: *** [tools/CMakeFiles/caffe.bin.dir/all] Error 2
make: *** [all] Error 2
tools/CMakeFiles/caffe.bin.dir/build.make:123: recipe for target 'tools/caffe-d' failed
CMakeFiles/Makefile2:406: recipe for target 'tools/CMakeFiles/caffe.bin.dir/all' failed
Makefile:117: recipe for target 'all' failed

My Configuration is ubuntu15.04 and  opencv3.0.  I can get through the test and runtest on command line by cmake, but fails on QT. This problem has trouble me  for several days.  Sincerely appreciate for your help and advance.

**Comment by shelhamer** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

**Comment by SHUWEISHEN** [comment]
All paths must be in English，  and it works then.
