### ISSUE TITLE
GPU Device IDs Not Honored

### ISSUE THREAD

**Issue by ensafi** [BVLC/caffe#5156]
### Issue summary

Specifying --gpu=2,4,5,6 does not have the intended effect.  In the latest master, the code simply calls Caffe::SetDevice(gpus[0]) when testing, where the vector gpus = {2,4,5,6} and gpus[0] = 2, so only the first GPU in the list is used.  When training, the code also calls Caffe::set_solver_count(gpus.size()) which apparently allows the solver to create one worker per GPU, but the actual GPU device IDs are not propagated to the workers.

### Steps to reproduce

Run Caffe on a machine with at least 3 GPUs, and specify --gpu=N,M where M-N > 1 (i.e. do not specify consecutive GPUs).

### Your system configuration
Operating system: Ubuntu 14.04
Compiler: GCC 4.8.4
CUDA version (if applicable): 7.0, 7.5 and 8.0 tested
CUDNN version (if applicable): 4.0.7 and 5.1 tested
BLAS: Atlas and MKL tested
Python or MATLAB version (for pycaffe and matcaffe respectively): N/A

**Comment by cypof** [comment]
Caffe cannot test in parallel, it's only used for training. It keeps getting requested, so we might look at that. For now I will put a warning.

**Comment by cypof** [comment]
During training it should work. Caffe::SetDevice is thread-local, so it should actually work the same way as cudaSetDevice.

**Comment by ensafi** [comment]
You are absolutely correct.  It was an initial user error further compounded by looking at the code and believing incorrectly that I found a bug.  In that case, the only issue is the missing warning to make it clear that testing does not use multiple GPUs.  Of course, support for multiple GPUs during testing is more than welcome!
