### ISSUE TITLE
Makefile:619: recipe for target '.build_release/tools/convert_imageset.bin' failed error at caffe installation on Ubuntu 16.04

### ISSUE THREAD

**Issue by ozgegunaydin** [BVLC/caffe#5158]
### Your system configuration
Operating system: Ubuntu 16.04 LTS
CUDA version (if applicable): 8.0
Python or MATLAB version (for pycaffe and matcaffe respectively): Python27

Following : https://github.com/BVLC/caffe/wiki/Ubuntu-16.04-or-15.10-Installation-Guide
When I type "make all" I get this errors :

> CXX/LD -o .build_release/tools/convert_imageset.bin /usr/bin/ld: cannot find -lLIBRARIES /usr/bin/ld: cannot find -l+= /usr/bin/ld: cannot find -lopencv_imgcodecs collect2: error: ld returned 1 exit status Makefile:619: recipe for target '.build_release/tools/convert_imageset.bin' failed make: *** [.build_release/tools/convert_imageset.bin] Error 1

I search about it and tried

```
cd build
cmake ..
make all
make test
make runtest
make pycaffe
make distribute
```
It works fine for me and I add caffe to PYTHONPATH then I can use "import caffe" line. But when I tried one of pre-trained caffe models from this site and write that to console :

`caffe % ./examples/finetune_flickr_style/assemble_data.py -h`
I get this error:

> No command 'caffe' found, did you mean: Command 'caff' from package 'signing-party' (universe) caffe: command not found

**Comment by shelhamer** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
