### ISSUE TITLE
site outages: dl.caffe.berkeleyvision.org and demo.caffe.berkeleyvision.org

### ISSUE THREAD

**Issue by shelhamer** [BVLC/caffe#5159]
The main Caffe site is up but the auxiliary sites for the demo and downloads (including reference models) are down during maintenance to campus infrastructure at Berkeley. These sites will return on Jan. 9th.

**Comment by atlury** [comment]
Thanks I was trying for the last few hours and was wondering what was happening. Can we please have a mirror? Say google drive???

**Comment by shelhamer** [comment]
The sites are now back. #1672 is there to remind us to switch to cloud hosting.
