### ISSUE TITLE
Hi want to use Caffe windows10  but ı have some errors

### ISSUE THREAD

**Issue by gmYusuf** [BVLC/caffe#5160]
Error	4	error C1083: Cannot open include file: 'caffe/proto/caffe.pb.h': No such file or directory	 
Error	5	error C1083: Cannot open include file: 'cublas_v2.h': No such file or directory	 

Anyone have this files.
 
Operating system: Windows 10 
Compiler:
CUDA version  8.0:
CUDNN version 8.0 v5.1:
BLAS:

**Comment by shelhamer** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
