### ISSUE TITLE
Fails at make runtest

### ISSUE THREAD

**Issue by Alexivia** [BVLC/caffe#5166]
### Issue summary
I'm using Caffe for my Masters Thesis, and can't procede to use the software...

Upon compilation, this warning message appears in many of the compilation steps:
`./include/caffe/net.hpp: In member function 'const std::vector<caffe::Blob<Dtype>*>& caffe::Net<Dtype>::ForwardPrefilled(Dtype*)':
./include/caffe/net.hpp:42:116: warning: typedef 'INVALID_REQUESTED_LOG_SEVERITY' locally defined but not used [-Wunused-local-typedefs]
     LOG_EVERY_N(WARNING, 1000) << "DEPRECATED: ForwardPrefilled() “`
though, the compilation process terminates without errors. While performing "make runtest" it fails over 200 tests (tried several times, and got different number of failures) with this message in the failures:
`unknown file: Failure
C++ exception with description "locale::facet::_S_create_c_locale name not valid" thrown in the test body.`

I'm not an expert in operating systems' messages due to compilation errors or anything, so I asked my system administrator and he said that while the warning was not problematic, the error is and that I should get in touch with the developers to try and solve it.

### Steps to reproduce

Makefile files attached

### Your system configuration
Operating system: Fedora 21
Compiler: gcc (GCC) 4.9.2 20150212
CUDA version (if applicable): CUDA Driver Version = 8.0, CUDA Runtime Version = 7.5
CUDNN version (if applicable):
BLAS: atlas-devel.x86_64          3.10.1-18.fc21
Python or MATLAB version (for pycaffe and matcaffe respectively): python.x86_64               2.7.8-15.fc21

[Makefile.config.txt](https://github.com/BVLC/caffe/files/693186/Makefile.config.txt)
[Makefile.txt](https://github.com/BVLC/caffe/files/693187/Makefile.txt)

**Comment by j-haj** [comment]
@Alexivia This is question is probably more appropriate for the caffe-users group mailing list as it seems this is probably a configuration issue on your end, not an issue with caffe itself. You may want to try posting this to the users-group.

As an aside, did you follow every step of the installation guide? It seems your Makefile.config isn't modified at all (for example, do you want to include GPU acceleration or CPU only?).

**Comment by Alexivia** [comment]
@j-haj Hi. Ok, I'll try posting to the other group.
Yes, I did edit my Makefile.config, specially the paths. And yes, I do want GPU acceleration, my system has 2 GTX980's and I want to use them to speed up training. Why do you ask?

Thanks for the reply!

**Comment by j-haj** [comment]
@Alexivia You have USE_CUDNN commented out (line 5) which, may be intentional, but I'm guessing was not.

**Comment by Alexivia** [comment]
@j-haj cuDNN is just a library to accelerate some matrix operations developed by NVIDIA, I think. And my system doesn't have said library installed, so I left it commented. To use only CPU you have another option, which I left untouched because the default configuration is to compile for both CPU and GPU.
But thanks for your remark ;)

**Comment by j-haj** [comment]
@Alexivia of course, I was just surprised it wasn't being used. Make sense to not use it if you don't own the system and it isn't installed. Good luck!

**Comment by Alexivia** [comment]
@j-haj Thank you! I have posted in the user-groups, but so far nobody has replied... I really need help with this...

**Comment by shelhamer** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

**Comment by lifematrix** [comment]
maybe  locale environment is set inappropriate. You can set it:
```
export LC_ALL="C"
```
then run ```make runtest```

reference from [this](http://blog.csdn.net/Fly2Leo/article/details/78537127).

**Comment by anubhav-nd** [comment]
thanks @lifematrix .. this works
