### ISSUE TITLE
vmware ubuntu16 undefined issue

### ISSUE THREAD

**Issue by Jayhello** [BVLC/caffe#5173]
the step make all, the following error

build_release/lib/libcaffe.so：对‘jpeg_CreateCompress’未定义的引用
.build_release/lib/libcaffe.so：对‘google::protobuf::DescriptorPool::FindFileByName(std::string const&) const’未定义的引用
.build_release/lib/libcaffe.so：对‘Imf_2_2::OutputFile::~OutputFile()’未定义的引用
.build_release/lib/libcaffe.so：对‘google::protobuf::internal::WireFormatLite::ReadBytes(google::protobuf::io::CodedInputStream*, std::string*)’未定义的引用   (  undefine ref  )
.build_release/lib/libcaffe.so：对‘png_create_info_struct’未定义的引用
.build_release/lib/libcaffe.so：对‘jpeg_std_error’未定义的引用
.build_release/lib/libcaffe.so：对‘google::protobuf::Message::InitializationErrorString() const’未定义的引用
.build_release/lib/libcaffe.so：对‘png_set_compression_level’未定义的引用
collect2: error: ld returned 1 exit status
Makefile:620: recipe for target '.build_release/tools/compute_image_mean.bin' failed
make: *** [.build_release/tools/compute_image_mean.bin] Error 1

**Comment by shelhamer** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
