### ISSUE TITLE
How to achieve different channels with shared weights in caffe

### ISSUE THREAD

**Issue by czxklxq** [BVLC/caffe#5178]
Please list the network file to tell me how to how to achieve different channels with shared weights if convenient. Thank you

**Comment by shelhamer** [comment]
This doesn't make sense—to share weights they have to be the same and cannot have different numbers of channels.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
