### ISSUE TITLE
db_lmdb.hpp:15] Check failed: mdb_status == 0 (21 vs. 0) Is a directory

### ISSUE THREAD

**Issue by mayurjain0312** [BVLC/caffe#5182]
Please use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) for usage, installation, or modeling questions, or other requests for help.
_Do not post such requests to Issues._ Doing so interferes with the development of Caffe.

Please read the [guidelines for contributing](https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md) before submitting this issue.

### Issue summary
I am getting the following error:
I0113 12:04:28.762876 31998 layer_factory.hpp:77] Creating layer data
F0113 12:04:28.854418 32010 db_lmdb.hpp:15] Check failed: mdb_status == 0 (21 vs. 0) Is a directory
*** Check failure stack trace: ***
    @     0x7f16b1f2f863  google::LogMessage::SendToLog()
    @     0x7f16b1f2fd48  google::LogMessage::Flush()
    @     0x7f16b1f339cd  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f16b1b83571  caffe::db::LMDB::Open()
    @     0x7f16b1d8a89d  caffe::DataReader<>::Body::InternalThreadEntry()
    @     0x7f16b1ae802d  caffe::InternalThread::entry()
    @     0x7f16b1f0e7eb  boost::(anonymous namespace)::thread_proxy()
    @     0x7f16b15a0e9a  start_thread
    @     0x7f16b065a36d  clone
/prj/icecad/lsfgridsdccspool/x/1484337864.6635374: line 8: 31998 Aborted                 (core dumped) caffe train -gpu 0 -solver /prj/neo-nas/mayurj/tif/solver_file.prototxt

### Steps to reproduce

If you are having difficulty building Caffe or training a model, please ask the caffe-users mailing list. If you are reporting a build error that seems to be due to a bug in Caffe, please attach your build configuration (either Makefile.config or CMakeCache.txt) and the output of the make (or cmake) command.

### Your system configuration
Operating system: Linux 64
Compiler:
CUDA version (if applicable):
CUDNN version (if applicable):
BLAS:
Python

**Comment by shelhamer** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
