### ISSUE TITLE
Errors related to HDFS, TIFF and googleprotobuf when compiling release 3 from source

### ISSUE THREAD

**Issue by bsangee** [BVLC/caffe#5183]
### Issue summary
I am seeing the below errors when compiling caffe from source.
Could you please suggest as to how I can fix this problem.
I referred to related questions on the forum but I was not able to fix my issue.

Scanning dependencies of target caffe.bin
[ 81%] Building CXX object tools/CMakeFiles/caffe.bin.dir/caffe.cpp.o
[ 81%] Linking CXX executable device_query
../lib/libcaffe.so: undefined reference to `google::protobuf::internal::WireFormatLite::WriteBytes(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, google::protobuf::io::CodedOutputStream*)'
../lib/libcaffe.so: undefined reference to `H5LTget_dataset_ndims'
../lib/libcaffe.so: undefined reference to `google::protobuf::DescriptorPool::FindFileByName(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
../lib/libcaffe.so: undefined reference to `leveldb::Status::ToString[abi:cxx11]() const'
../lib/libcaffe.so: undefined reference to `H5LTread_dataset_int'
../lib/libcaffe.so: undefined reference to `google::protobuf::internal::StringTypeHandlerBase::Delete(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)'

.
.
.
.
.
.
/opt/apps/gcc5_2/opencv/2.4.13/lib/libopencv_highgui.so.2.4.13: undefined reference to `TIFFClose@LIBTIFF_4.0'
/opt/apps/gcc5_2/opencv/2.4.13/lib/libopencv_highgui.so.2.4.13: undefined reference to `TIFFRGBAImageOK@LIBTIFF_4.0'
../lib/libcaffe.so: undefined reference to `google::protobuf::MessageLite::SerializeToString(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*) const'
/opt/apps/gcc5_2/opencv/2.4.13/lib/libopencv_highgui.so.2.4.13: undefined reference to `TIFFReadRGBAStrip@LIBTIFF_4.0'
collect2: error: ld returned 1 exit status
make[2]: *** [tools/device_query] Error 1
make[1]: *** [tools/CMakeFiles/device_query.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 83%] Linking CXX executable compute_image_mean
CMakeFiles/compute_image_mean.dir/compute_image_mean.cpp.o: In function `main':
compute_image_mean.cpp:(.text.startup+0x1ac): undefined reference to `gflags::SetUsageMessage(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
compute_image_mean.cpp:(.text.startup+0x2e0): undefined reference to `google::protobuf::MessageLite::ParseFromString(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
.
.
.
.
.
.
/opt/apps/gcc5_2/opencv/2.4.13/lib/libopencv_highgui.so.2.4.13: undefined reference to `TIFFClose@LIBTIFF_4.0'
/opt/apps/gcc5_2/opencv/2.4.13/lib/libopencv_highgui.so.2.4.13: undefined reference to `TIFFRGBAImageOK@LIBTIFF_4.0'
/opt/apps/gcc5_2/opencv/2.4.13/lib/libopencv_highgui.so.2.4.13: undefined reference to `TIFFReadRGBAStrip@LIBTIFF_4.0'
collect2: error: ld returned 1 exit status
make[2]: *** [tools/convert_imageset] Error 1
make[1]: *** [tools/CMakeFiles/convert_imageset.dir/all] Error 2
[ 85%] Linking CXX executable upgrade_net_proto_text
[ 87%] Linking CXX executable test_net
[ 88%] Linking CXX executable train_net
[ 90%] Linking CXX executable upgrade_net_proto_binary
../lib/libcaffe.so: undefined reference to `google::protobuf::internal::WireFormatLite::WriteBytes(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, google::protobuf::io::CodedOutputStream*)'
../lib/libcaffe.so: undefined reference to `H5LTget_dataset_ndims'
../lib/libcaffe.so: undefined reference to `google::protobuf::DescriptorPool::FindFileByName(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
../lib/libcaffe.so: undefined reference to `leveldb::Status::ToString[abi:cxx11]() const'
../lib/libcaffe.so: undefined reference to `H5LTread_dataset_int'
../lib/libcaffe.so: undefined reference to `google::protobuf::internal::StringTypeHandlerBase::Delete(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)'
/opt/apps/gcc5_2/Anaconda-boost/1.58.0/lib/libboost_python.so: undefined reference to `PyUnicodeUCS2_FromEncodedObject'
../lib/libcaffe.so: undefined reference to `google::protobuf::internal::WireFormatLite::ReadString(google::protobuf::io::CodedInputStream*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)'
/opt/apps/gcc5_2/opencv/2.4.13/lib/libopencv_highgui.so.2.4.13: undefined reference to `TIFFIsTiled@LIBTIFF_4.0'
/opt/apps/gcc5_2/opencv/2.4.13/lib/libopencv_highgui.so.2.4.13: undefined reference to `TIFFOpen@LIBTIFF_4.0'
../lib/libcaffe.so: undefined reference to `google::protobuf::Message::DebugString[abi:cxx11]() const'
../lib/libcaffe.so: undefined reference to `google::protobuf::internal::kEmptyString[abi:cxx11]'
../lib/libcaffe.so: undefined reference to `google::protobuf::MessageFactory::InternalRegisterGeneratedFile(char const*, void (*)(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&))'

**Comment by shelhamer** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
