### ISSUE TITLE
How to set "WITH_PYTHON_LAYER := 1"?

### ISSUE THREAD

**Issue by shansiliu** [BVLC/caffe#5188]
Hi, I want to use a Python layer. I think I need to set "WITH_PYTHON_LAYER := 1" and rebuilt Caffe again. But I don't know where to set "WITH_PYTHON_LAYER := 1" in this Windows version of Caffe: https://github.com/BVLC/caffe/tree/windows.

**Comment by BobLiu20** [comment]
try to search it in this [file](https://github.com/BVLC/caffe/blob/windows/Makefile.config.example)

**Comment by shansiliu** [comment]
@BobLiu20 Thanks. I have uncommented it and rebuild Caffe agian, but still Caffe cannot recognize Python layer. I think I must have missed some operations....

**Comment by williford** [comment]
Please ask your question on the [Caffe user mailing list](https://groups.google.com/forum/#!forum/caffe-users) or on another website, such as http://stackoverflow.com/.

> Please use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) for usage, installation, or modeling questions, or other requests for help.
> _Do not post such requests to Issues._ Doing so interferes with the development of Caffe.
