### ISSUE TITLE
Why there is no libcaffe.lib in windows branch installation.

### ISSUE THREAD

**Issue by taeguk-sualab** [BVLC/caffe#5194]
I did installation in windows with https://github.com/BVLC/caffe/blob/86425b1ecba7f324b90dd82872c5bca570e38863/README.md

But there is no libcaffe.lib.
Why??

**Comment by willyd** [comment]
You should have a caffe.lib in the build/lib folder. Otherwise, something went wrong in your build.

Please ask installation questions on the user mailing list [caffe-users group](https://groups.google.com/forum/#!forum/caffe-users).
