### ISSUE TITLE
label < colors.size() (10 vs. 10) 

### ISSUE THREAD

**Issue by shawncheeer** [BVLC/caffe#5202]
F0120 14:16:21.719866  9250 bbox_util.cpp:1190] Check failed: label < colors.size() (10 vs. 10) 
*** Check failure stack trace: ***
    @     0x7f2fe46e99fd  google::LogMessage::Fail()
    @     0x7f2fe46eb89d  google::LogMessage::SendToLog()
    @     0x7f2fe46e95ec  google::LogMessage::Flush()
    @     0x7f2fe46ec1be  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f2fe4e5a6e7  caffe::VisualizeBBox<>()
    @     0x7f2fe4f2ff51  caffe::DetectionOutputLayer<>::Forward_gpu()
    @     0x7f2fe4ed51ca  caffe::Net<>::ForwardFromTo()
    @     0x7f2fe4ed53ff  caffe::Net<>::Forward()
    @           0x40d6cb  test()
    @           0x40c384  main
    @     0x7f2fe2ccef45  (unknown)
    @           0x40c455  (unknown)
Aborted (core dumped)

**Comment by shelhamer** [comment]
This is not a layer in BVLC/caffe:master. Please ask at the fork this layer is from.
