### ISSUE TITLE
Issue with test_more_sparse_im2col_layer.cpp while doing make runtest

### ISSUE THREAD

**Issue by dm02** [BVLC/caffe#5208]
@tianzhi0549 
I followed the instruction mentioned to build caffe. make -j4, make pycaffe and make test ; all work fine.However make runtest fails. I get the following error on make runtest:
[  0%] Built target proto
[ 65%] Built target caffe
[ 65%] Built target gtest
[ 65%] Building CXX object src/caffe/test/CMakeFiles/test.testbin.dir/test_more_sparse_im2col_layer.cpp.o
/home/env114/Desktop/Imges/deeplearning/CTPN/caffe/src/caffe/test/test_more_sparse_im2col_layer.cpp: In member function ‘virtual void caffe::MoreSparseIm2colLayerTest_TestSetup_Test<gtest_TypeParam_>::TestBody()’:
/home/env114/Desktop/Imges/deeplearning/CTPN/caffe/src/caffe/test/test_more_sparse_im2col_layer.cpp:47:3: error: ‘MoreSparseIm2colLayer’ was not declared in this scope
   MoreSparseIm2colLayer<Dtype> layer(layer_param);
   ^
/home/env114/Desktop/Imges/deeplearning/CTPN/caffe/src/caffe/test/test_more_sparse_im2col_layer.cpp:47:30: error: expected primary-expression before ‘>’ token
   MoreSparseIm2colLayer<Dtype> layer(layer_param);
                              ^
/home/env114/Desktop/Imges/deeplearning/CTPN/caffe/src/caffe/test/test_more_sparse_im2col_layer.cpp:47:49: error: there are no arguments to ‘layer’ that depend on a template parameter, so a declaration of ‘layer’ must be available [-fpermissive]
   MoreSparseIm2colLayer<Dtype> layer(layer_param);
                                                 ^
/home/env114/Desktop/Imges/deeplearning/CTPN/caffe/src/caffe/test/test_more_sparse_im2col_layer.cpp:47:49: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)
/home/env114/Desktop/Imges/deeplearning/CTPN/caffe/src/caffe/test/test_more_sparse_im2col_layer.cpp:48:3: error: ‘layer’ was not declared in this scope
   layer.SetUp(this->blob_bottom_vec_, this->blob_top_vec_);
   ^
/home/env114/Desktop/Imges/deeplearning/CTPN/caffe/src/caffe/test/test_more_sparse_im2col_layer.cpp: In member function ‘virtual void caffe::MoreSparseIm2colLayerTest_TestGradient_Test<gtest_TypeParam_>::TestBody()’:
/home/env114/Desktop/Imges/deeplearning/CTPN/caffe/src/caffe/test/test_more_sparse_im2col_layer.cpp:62:3: error: ‘MoreSparseIm2colLayer’ was not declared in this scope
   MoreSparseIm2colLayer<Dtype> layer(layer_param);
   ^
/home/env114/Desktop/Imges/deeplearning/CTPN/caffe/src/caffe/test/test_more_sparse_im2col_layer.cpp:62:30: error: expected primary-expression before ‘>’ token
   MoreSparseIm2colLayer<Dtype> layer(layer_param);
                              ^
/home/env114/Desktop/Imges/deeplearning/CTPN/caffe/src/caffe/test/test_more_sparse_im2col_layer.cpp:62:49: error: there are no arguments to ‘layer’ that depend on a template parameter, so a declaration of ‘layer’ must be available [-fpermissive]
   MoreSparseIm2colLayer<Dtype> layer(layer_param);
                                                 ^
/home/env114/Desktop/Imges/deeplearning/CTPN/caffe/src/caffe/test/test_more_sparse_im2col_layer.cpp:64:36: error: ‘layer’ was not declared in this scope
   checker.CheckGradientExhaustive(&layer, this->blob_bottom_vec_,
                                    ^
/home/env114/Desktop/Imges/deeplearning/CTPN/caffe/src/caffe/test/test_more_sparse_im2col_layer.cpp: In member function ‘virtual void caffe::MoreSparseIm2colLayerTest_TestRectGradient_Test<gtest_TypeParam_>::TestBody()’:
/home/env114/Desktop/Imges/deeplearning/CTPN/caffe/src/caffe/test/test_more_sparse_im2col_layer.cpp:77:3: error: ‘MoreSparseIm2colLayer’ was not declared in this scope
   MoreSparseIm2colLayer<Dtype> layer(layer_param);
   ^
/home/env114/Desktop/Imges/deeplearning/CTPN/caffe/src/caffe/test/test_more_sparse_im2col_layer.cpp:77:30: error: expected primary-expression before ‘>’ token
   MoreSparseIm2colLayer<Dtype> layer(layer_param);
                              ^
/home/env114/Desktop/Imges/deeplearning/CTPN/caffe/src/caffe/test/test_more_sparse_im2col_layer.cpp:77:49: error: there are no arguments to ‘layer’ that depend on a template parameter, so a declaration of ‘layer’ must be available [-fpermissive]
   MoreSparseIm2colLayer<Dtype> layer(layer_param);
                                                 ^
/home/env114/Desktop/Imges/deeplearning/CTPN/caffe/src/caffe/test/test_more_sparse_im2col_layer.cpp:79:36: error: ‘layer’ was not declared in this scope
   checker.CheckGradientExhaustive(&layer, this->blob_bottom_vec_,
                                    ^
/home/env114/Desktop/Imges/deeplearning/CTPN/caffe/src/caffe/test/test_more_sparse_im2col_layer.cpp: In instantiation of ‘void caffe::MoreSparseIm2colLayerTest_TestRectGradient_Test<gtest_TypeParam_>::TestBody() [with gtest_TypeParam_ = caffe::GPUDevice<double>]’:
/home/env114/Desktop/Imges/deeplearning/CTPN/caffe/src/caffe/test/test_more_sparse_im2col_layer.cpp:83:1:   required from here
/home/env114/Desktop/Imges/deeplearning/CTPN/caffe/src/caffe/test/test_more_sparse_im2col_layer.cpp:77:49: error: ‘layer’ was not declared in this scope
   MoreSparseIm2colLayer<Dtype> layer(layer_param);
                                                 ^
/home/env114/Desktop/Imges/deeplearning/CTPN/caffe/src/caffe/test/test_more_sparse_im2col_layer.cpp: In instantiation of ‘void caffe::MoreSparseIm2colLayerTest_TestGradient_Test<gtest_TypeParam_>::TestBody() [with gtest_TypeParam_ = caffe::GPUDevice<double>]’:
/home/env114/Desktop/Imges/deeplearning/CTPN/caffe/src/caffe/test/test_more_sparse_im2col_layer.cpp:83:1:   required from here
/home/env114/Desktop/Imges/deeplearning/CTPN/caffe/src/caffe/test/test_more_sparse_im2col_layer.cpp:62:49: error: ‘layer’ was not declared in this scope
   MoreSparseIm2colLayer<Dtype> layer(layer_param);
                                                 ^
/home/env114/Desktop/Imges/deeplearning/CTPN/caffe/src/caffe/test/test_more_sparse_im2col_layer.cpp: In instantiation of ‘void caffe::MoreSparseIm2colLayerTest_TestSetup_Test<gtest_TypeParam_>::TestBody() [with gtest_TypeParam_ = caffe::GPUDevice<double>]’:
/home/env114/Desktop/Imges/deeplearning/CTPN/caffe/src/caffe/test/test_more_sparse_im2col_layer.cpp:83:1:   required from here
/home/env114/Desktop/Imges/deeplearning/CTPN/caffe/src/caffe/test/test_more_sparse_im2col_layer.cpp:47:49: error: ‘layer’ was not declared in this scope
   MoreSparseIm2colLayer<Dtype> layer(layer_param);
                                                 ^
/home/env114/Desktop/Imges/deeplearning/CTPN/caffe/src/caffe/test/test_more_sparse_im2col_layer.cpp: In instantiation of ‘void caffe::MoreSparseIm2colLayerTest_TestRectGradient_Test<gtest_TypeParam_>::TestBody() [with gtest_TypeParam_ = caffe::GPUDevice<float>]’:
/home/env114/Desktop/Imges/deeplearning/CTPN/caffe/src/caffe/test/test_more_sparse_im2col_layer.cpp:83:1:   required from here
/home/env114/Desktop/Imges/deeplearning/CTPN/caffe/src/caffe/test/test_more_sparse_im2col_layer.cpp:77:49: error: ‘layer’ was not declared in this scope
   MoreSparseIm2colLayer<Dtype> layer(layer_param);
                                                 ^
/home/env114/Desktop/Imges/deeplearning/CTPN/caffe/src/caffe/test/test_more_sparse_im2col_layer.cpp: In instantiation of ‘void caffe::MoreSparseIm2colLayerTest_TestGradient_Test<gtest_TypeParam_>::TestBody() [with gtest_TypeParam_ = caffe::GPUDevice<float>]’:
/home/env114/Desktop/Imges/deeplearning/CTPN/caffe/src/caffe/test/test_more_sparse_im2col_layer.cpp:83:1:   required from here
/home/env114/Desktop/Imges/deeplearning/CTPN/caffe/src/caffe/test/test_more_sparse_im2col_layer.cpp:62:49: error: ‘layer’ was not declared in this scope
   MoreSparseIm2colLayer<Dtype> layer(layer_param);
                                                 ^
/home/env114/Desktop/Imges/deeplearning/CTPN/caffe/src/caffe/test/test_more_sparse_im2col_layer.cpp: In instantiation of ‘void caffe::MoreSparseIm2colLayerTest_TestSetup_Test<gtest_TypeParam_>::TestBody() [with gtest_TypeParam_ = caffe::GPUDevice<float>]’:
/home/env114/Desktop/Imges/deeplearning/CTPN/caffe/src/caffe/test/test_more_sparse_im2col_layer.cpp:83:1:   required from here
/home/env114/Desktop/Imges/deeplearning/CTPN/caffe/src/caffe/test/test_more_sparse_im2col_layer.cpp:47:49: error: ‘layer’ was not declared in this scope
   MoreSparseIm2colLayer<Dtype> layer(layer_param);
                                                 ^
/home/env114/Desktop/Imges/deeplearning/CTPN/caffe/src/caffe/test/test_more_sparse_im2col_layer.cpp: In instantiation of ‘void caffe::MoreSparseIm2colLayerTest_TestRectGradient_Test<gtest_TypeParam_>::TestBody() [with gtest_TypeParam_ = caffe::CPUDevice<double>]’:
/home/env114/Desktop/Imges/deeplearning/CTPN/caffe/src/caffe/test/test_more_sparse_im2col_layer.cpp:83:1:   required from here
/home/env114/Desktop/Imges/deeplearning/CTPN/caffe/src/caffe/test/test_more_sparse_im2col_layer.cpp:77:49: error: ‘layer’ was not declared in this scope
   MoreSparseIm2colLayer<Dtype> layer(layer_param);
                                                 ^
/home/env114/Desktop/Imges/deeplearning/CTPN/caffe/src/caffe/test/test_more_sparse_im2col_layer.cpp: In instantiation of ‘void caffe::MoreSparseIm2colLayerTest_TestGradient_Test<gtest_TypeParam_>::TestBody() [with gtest_TypeParam_ = caffe::CPUDevice<double>]’:
/home/env114/Desktop/Imges/deeplearning/CTPN/caffe/src/caffe/test/test_more_sparse_im2col_layer.cpp:83:1:   required from here
/home/env114/Desktop/Imges/deeplearning/CTPN/caffe/src/caffe/test/test_more_sparse_im2col_layer.cpp:62:49: error: ‘layer’ was not declared in this scope
   MoreSparseIm2colLayer<Dtype> layer(layer_param);
                                                 ^
/home/env114/Desktop/Imges/deeplearning/CTPN/caffe/src/caffe/test/test_more_sparse_im2col_layer.cpp: In instantiation of ‘void caffe::MoreSparseIm2colLayerTest_TestSetup_Test<gtest_TypeParam_>::TestBody() [with gtest_TypeParam_ = caffe::CPUDevice<double>]’:
/home/env114/Desktop/Imges/deeplearning/CTPN/caffe/src/caffe/test/test_more_sparse_im2col_layer.cpp:83:1:   required from here
/home/env114/Desktop/Imges/deeplearning/CTPN/caffe/src/caffe/test/test_more_sparse_im2col_layer.cpp:47:49: error: ‘layer’ was not declared in this scope
   MoreSparseIm2colLayer<Dtype> layer(layer_param);
                                                 ^
/home/env114/Desktop/Imges/deeplearning/CTPN/caffe/src/caffe/test/test_more_sparse_im2col_layer.cpp: In instantiation of ‘void caffe::MoreSparseIm2colLayerTest_TestRectGradient_Test<gtest_TypeParam_>::TestBody() [with gtest_TypeParam_ = caffe::CPUDevice<float>]’:
/home/env114/Desktop/Imges/deeplearning/CTPN/caffe/src/caffe/test/test_more_sparse_im2col_layer.cpp:83:1:   required from here
/home/env114/Desktop/Imges/deeplearning/CTPN/caffe/src/caffe/test/test_more_sparse_im2col_layer.cpp:77:49: error: ‘layer’ was not declared in this scope
   MoreSparseIm2colLayer<Dtype> layer(layer_param);
                                                 ^
/home/env114/Desktop/Imges/deeplearning/CTPN/caffe/src/caffe/test/test_more_sparse_im2col_layer.cpp: In instantiation of ‘void caffe::MoreSparseIm2colLayerTest_TestGradient_Test<gtest_TypeParam_>::TestBody() [with gtest_TypeParam_ = caffe::CPUDevice<float>]’:
/home/env114/Desktop/Imges/deeplearning/CTPN/caffe/src/caffe/test/test_more_sparse_im2col_layer.cpp:83:1:   required from here
/home/env114/Desktop/Imges/deeplearning/CTPN/caffe/src/caffe/test/test_more_sparse_im2col_layer.cpp:62:49: error: ‘layer’ was not declared in this scope
   MoreSparseIm2colLayer<Dtype> layer(layer_param);
                                                 ^
/home/env114/Desktop/Imges/deeplearning/CTPN/caffe/src/caffe/test/test_more_sparse_im2col_layer.cpp: In instantiation of ‘void caffe::MoreSparseIm2colLayerTest_TestSetup_Test<gtest_TypeParam_>::TestBody() [with gtest_TypeParam_ = caffe::CPUDevice<float>]’:
/home/env114/Desktop/Imges/deeplearning/CTPN/caffe/src/caffe/test/test_more_sparse_im2col_layer.cpp:83:1:   required from here
/home/env114/Desktop/Imges/deeplearning/CTPN/caffe/src/caffe/test/test_more_sparse_im2col_layer.cpp:47:49: error: ‘layer’ was not declared in this scope
   MoreSparseIm2colLayer<Dtype> layer(layer_param);
                                                 ^
make[3]: *** [src/caffe/test/CMakeFiles/test.testbin.dir/test_more_sparse_im2col_layer.cpp.o] Error 1
make[2]: *** [src/caffe/test/CMakeFiles/test.testbin.dir/all] Error 2
make[1]: *** [src/caffe/test/CMakeFiles/runtest.dir/rule] Error 2
make: *** [runtest] Error 2

Please help me with the above issue. Thanks in advance. 

Operating system:Ubuntu 14.04
Compiler:gcc version 4.8.4
CUDA version: 7.0
CUDNN version :3.0.8
Python : 2.4.7

**Comment by shelhamer** [comment]
This issue is about a fork of Caffe—this issue tracker is only for BVLC/caffe:master. Please ask at the fork.
