### ISSUE TITLE
training loss always 6.9 when using my calculated mean file in ILSVRC12 data

### ISSUE THREAD

**Issue by fancyerii** [BVLC/caffe#5212]
I follow all the steps of http://caffe.berkeleyvision.org/gathered/examples/imagenet.html.
the training loss is always 6.9 and accuracy is 0.001. 
I searched and found this issue https://github.com/BVLC/caffe/issues/4482
So I tried to download the hosted mean file and trained again. It's ok! I got accuracy of 58% after 450000 iteration.
it seems the problem is my calculated mean file(I tried many times with it to avoid  bad parameter initialization). What's wrong with it?

**Comment by shelhamer** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
