### ISSUE TITLE
Error in LeNet on MNIST example

### ISSUE THREAD

**Issue by xNx2** [BVLC/caffe#5214]
Hi 
I followed the guidance under the Training LeNet on MNIST with Caffe but  I've got a error when creating lmdb..

$ ./examples/mnist/create_mnist.sh
Creating lmdb...
F:/program files/caffe/build/examples/mnist/convert_mnist_data.exe: error while loading shared libraries: boost_python-vc140-mt-1_61.dll: cannot open shared object file: No such file or directory

what is wrong?

**Comment by willyd** [comment]
Please ask your question on the [Caffe user mailing list](https://groups.google.com/forum/#!forum/caffe-users) or on another website, such as http://stackoverflow.com/.

> Please use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) for usage, installation, or modeling questions, or other requests for help.
> _Do not post such requests to Issues._ Doing so interferes with the development of Caffe.
