### ISSUE TITLE
Multi-Source Training with Multi-Loss

### ISSUE THREAD

**Issue by CongWeilin** [BVLC/caffe#5217]
I wish to train a net that can both recognize face\not face and calculate bounding box offset at the same time. So, my training process is split into 2 tasks: classify task( face data and not face data by softmax), regression task( bounding box's left top and right down points by euclidean).
![train_val](https://cloud.githubusercontent.com/assets/18029500/22236734/805fb558-e242-11e6-9af8-54016a0f5be0.png)
Since classify task's nonface data do not need bounding box update, so i wish to block the euclidean backward propagate and only update softmaxLoss. Similarly, block the softmax backward propagate when training regression task.
Now, I have two lists for these two tasks. I take turns read 'image data and label' and 'image data and bounding box position' and block loss layer.
however, i do not know how to take turns block backward propagate. Should i switch 1 or 2 to propagate_down[i] ? How can I make that? I guess i could change propagate_down[i] in reshape Function or forward Function...
Could anyone help me???
Thanks

**Comment by happyharrycn** [comment]
This is very similar to fast/faster R-CNN. You can take a look at Ross's implementation (in particular, smooth_l1_loss). In brief, you will need to implement some sort of masking function for your regression loss.

**Comment by shelhamer** [comment]
Please ask modeling questions on the mailing list.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
