### ISSUE TITLE
make runtest fails due to OpenCL kernel compilation

### ISSUE THREAD

**Issue by fab128** [BVLC/caffe#5218]
### Issue summary

Caffe (opencl) branch installs and compiles properly.
However, "make runtest" fails due to errors in the kernel compilation phase:

"/tmp/OCL13460T2.cl", line 10716: error: more than one instance of overloaded
          function "native_powr" matches the argument list:
            function "native_powr(float, float) C++"
            function "native_powr(float2, float2) C++"
            function "native_powr(float3, float3) C++"
            function "native_powr(float4, float4) C++"
            function "native_powr(float8, float8) C++"
            function "native_powr(float16, float16) C++"
            argument types are: (double, double)
  v = native_powr((Dtype)mad(scale, v, eps), (Dtype)-0.5);

It seems that the opencl kernel is not compatible with my compiler (AMD APP sdk).

### Steps to reproduce

Compile caffe with all default parameters. Make runtest. (log file attached)
[test.log.gz](https://github.com/BVLC/caffe/files/726677/test.log.gz)

NB: I actually had to add "atlcblas" and "atllapack" in "cmake/Modules/FindAtlas.cmake" in order for cmake to correctly find CBlas and Lapack atlas libraries on my system.

NB2: I'm unable to compile caffe with "USE_INDEX_64 := 1" (compile error)

### Your system configuration
Operating system: Gentoo linux-4.4.39
OpenCL: AMDAPP 3.0-r1
ViennaCL: latest from github
BLAS: Atlas 3.10.2

**Comment by naibaf7** [comment]
@fab128 Thanks, noted. I'll have a look after the 3rd of February. May I know your hardware as well?

**Comment by fab128** [comment]
I'm on a Core i5-4670K with two AMD Radeon R9 200 GPUs.

**Comment by gat3way** [comment]
Please note that as per the OpenCL specs, native_powr() can only accept float or float vectors. I guess NV's implementation is more relaxed, but it fails to build on AMD and is violating the standard.

**Comment by naibaf7** [comment]
@gat3way Not too sure about that. As I said, it compiles and runs fine on my AMD W9100, RX 480 using AMDGPU-RRO (Linux) driver (and on Windows), fine on nVidia with CUDA 8 (OpenCL 1.2) and also fine on Intel i7 4790K and i7 6560U with the open and closed source drivers. 
I am therefore completely unable to reproduce the issue experienced here and can for now only suggest you to try casting the double to float, disable the double support or try another driver and OpenCL implementation.

**Comment by gat3way** [comment]
Yes, it is in the same document, just a little bit below:

"This built-in math function takes scalar or vector arguments. The generic type name gentype is used to indicate that the function can take float, float2, float4, float8, or float16 as the type for the arguments. "

**Comment by naibaf7** [comment]
@gat3way 
The software tests with the macro if `cl_khr_fp64` is present and only then allows double support and `native_powr` with double, and it should work with all recent OpenCL implementations as stated above.
If it's not working, change the driver or disable double support at compile time (since most people won't use that anyways).

**Comment by naibaf7** [comment]
Updated code for those who still have issues.
