### ISSUE TITLE
MEX File Missing during Installation

### ISSUE THREAD

**Issue by PENGUINLIONG** [BVLC/caffe#5219]
(Under Windows 10 Anniversary, 1607)
(Generated with CMake 3.7.2, Compile with VS2015)

The following error may occur after a successful compilation:

```
MSB3073 Command "setlocal
S:\CMake\bin\cmake.exe -DBUILD_TYPE=Release -P cmake_install.cmake
if %errorlevel% neq 0 goto :cmEnd
:cmEnd
endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone
:cmErrorLevel
exit /b %1
:cmDone
if %errorlevel% neq 0 goto :VCEnd
:VCEnd” exited with code: 1
```

CMake is unable to find the generated mex file, it's expected the caffe_.mexw64 exists in `/path/to/caffe/matlab/+caffe/private` , while it is generated in `/path/to/caffe/matlab/+caffe/private/${Configuration}` (`Debug` or `Release` as default).

See generated cmake file `/path/to/caffe/build/Matlab/cmake_install.cmake`, (may be) at line 31.

**Comment by willyd** [comment]
Can you try to change the code at:

https://github.com/BVLC/caffe/blob/windows/matlab/CMakeLists.txt#L61-L63

From:
```CMake
set_target_properties(matlab PROPERTIES 
                                 RUNTIME_OUTPUT_DIRECTORY ${PROJECT_SOURCE_DIR}/matlab/+caffe/private)
```
to:
```CMake
set_target_properties(matlab PROPERTIES 
                                 RUNTIME_OUTPUT_DIRECTORY ${PROJECT_SOURCE_DIR}/matlab/+caffe/private
                                 RUNTIME_OUTPUT_DIRECTORY_DEBUG ${PROJECT_SOURCE_DIR}/matlab/+caffe/private
                                 RUNTIME_OUTPUT_DIRECTORY_RELEASE ${PROJECT_SOURCE_DIR}/matlab/+caffe/private
)
```

**Comment by PENGUINLIONG** [comment]
Great, it's solved after the modification.
