### ISSUE TITLE
caffe ipy example problems

### ISSUE THREAD

**Issue by yzilong96** [BVLC/caffe#5222]
Please use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) for usage, installation, or modeling questions, or other requests for help.
_Do not post such requests to Issues._ Doing so interferes with the development of Caffe.

Please read the [guidelines for contributing](https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md) before submitting this issue.

### Issue summary
In  caffe-master/examples/ Classification: Instant Recognition with Caffe.ipy
when I run transformed_image = transformer.preprocess('data',image)
there come the mistake,I google but didn't find answer.
TypeError                                 Traceback (most recent call last)
<ipython-input-31-320103345567> in <module>()
      1 image = caffe.io.load_image(caffe_root + 'examples/images/cat.jpg')
----> 2 transformed_image = transformer.preprocess('data',image)
      3 plt.imshow(image)

/home/yzl/Download/caffe-master/python/caffe/io.pyc in preprocess(self, in_, data)
    151             caffe_in = resize_image(caffe_in, in_dims)
    152         if transpose is not None:
--> 153             caffe_in = caffe_in.transpose(transpose)
    154         if channel_swap is not None:
    155             caffe_in = caffe_in[channel_swap, :, :]

TypeError: 'set' object does not support indexing

### Steps to reproduce

If you are having difficulty building Caffe or training a model, please ask the caffe-users mailing list. If you are reporting a build error that seems to be due to a bug in Caffe, please attach your build configuration (either Makefile.config or CMakeCache.txt) and the output of the make (or cmake) command.

### Your system configuration
Operating system: ubuntu16.04
Compiler:
CUDA version (if applicable): 
CUDNN version (if applicable):
BLAS:
Python or MATLAB version (for pycaffe and matcaffe respectively):

**Comment by shelhamer** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
