### ISSUE TITLE
Web Demo Installation link broken

### ISSUE THREAD

**Issue by avipars** [BVLC/caffe#5226]
### Issue summary
I wanted to run the web demo on my local machine. I followed the guide, but the installation link is broken (https://github.com/BVLC/caffe/blob/tutorial/installation.html) on this page: (https://github.com/BVLC/caffe/tree/tutorial/examples/web_demo)

### Your system configuration
Operating system: Ubuntu
Compiler:
CUDA version (if applicable): 
CUDNN version (if applicable):
BLAS: openBLAS
Python or MATLAB version (for pycaffe and matcaffe respectively):

**Comment by williford** [comment]
Thanks for your report. I submitted a fix. In the mean time, you can visit:

http://caffe.berkeleyvision.org/installation.html

**Comment by williford** [comment]
The link is correct when viewed from:
http://caffe.berkeleyvision.org/gathered/examples/web_demo.html

The links are not intended to work from the github.com site.
