### ISSUE TITLE
make runtest fails with "gpu_memory.cpp:137] Check failed: error == cudaSuccess (35 vs. 0)  CUDA driver version is insufficient for CUDA runtime version"

### ISSUE THREAD

**Issue by svanschalkwyk** [BVLC/caffe#5229]
$ make runtest
_.build_release/test/test_all.testbin 0 --gtest_shuffle 
Cuda number of devices: **9406365**
Setting to use device 0
Current device id: 0
Current device name: 
F0126 14:05:10.530360 36174 gpu_memory.cpp:137] Check failed: 
error == cudaSuccess (35 vs. 0)  **CUDA driver version is insufficient for CUDA runtime version**
*** Check failure stack trace: ***
    @     0x7f4ea32c25cd  google::LogMessage::Fail()
    @     0x7f4ea32c4433  google::LogMessage::SendToLog()
    @     0x7f4ea32c215b  google::LogMessage::Flush()
    @     0x7f4ea32c4e1e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f4e9ee33902  caffe::GPUMemory::Manager::update_dev_info()
    @     0x7f4e9ee33f7f  caffe::GPUMemory::Manager::init()
    @           0x46b0ee  main
    @     0x7f4e9e01e830  __libc_start_main
    @           0x472a39  _start
    @              (nil)  (unknown)
Makefile:542: recipe for target 'runtest' failed

NVIDIA-SMI 378.09                 Driver Version: 378.09                    |
0  GeForce GTX 960     Off  | 0000:04:00.0      On |                  N/A |
1  GeForce GTX 760     Off  | 0000:83:00.0     N/A |                  N/A |

Linux Mint 18.1 Serena
g++ (Ubuntu 5.4.1-2ubuntu1~16.04) 5.4.1 20160904
MKL: 2017 Update 1
CUDA 8.0
Python 2.7

**Comment by shelhamer** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
