### ISSUE TITLE
set different learning rate for different loss task

### ISSUE THREAD

**Issue by CongWeilin** [BVLC/caffe#5230]
I have 2 loss layer, classify and regression. I wish to set different lr to them since the lr for cls is too high for regression

**Comment by williford** [comment]
Please ask your question on the [Caffe user mailing list](https://groups.google.com/forum/#!forum/caffe-users) or on another website, such as http://stackoverflow.com/.

> Please use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) for usage, installation, or modeling questions, or other requests for help.
> _Do not post such requests to Issues._ Doing so interferes with the development of Caffe.
