### ISSUE TITLE
MKL with CMake build on macOS 10.12.1

### ISSUE THREAD

**Issue by yiakwy** [BVLC/caffe#5232]
I am using macOS Sierra 10.12.1 (just updated!) . I am inspecting a very UNUSUAL problem : 

I have already set up intel mkl but always end up with "vecLib"

Let us see cmake codes first:

in CMake Dependencies.cmake (cmake folder) we have : 

```
# ---[ BLAS
if(NOT APPLE)
  set(BLAS "Atlas" CACHE STRING "Selected BLAS library")
  set_property(CACHE BLAS PROPERTY STRINGS "Atlas;Open;MKL")

  if(BLAS STREQUAL "Atlas" OR BLAS STREQUAL "atlas")
    find_package(Atlas REQUIRED)
    include_directories(SYSTEM ${Atlas_INCLUDE_DIR})
    list(APPEND Caffe_LINKER_LIBS ${Atlas_LIBRARIES})
  elseif(BLAS STREQUAL "Open" OR BLAS STREQUAL "open")
    find_package(OpenBLAS REQUIRED)
    include_directories(SYSTEM ${OpenBLAS_INCLUDE_DIR})
    list(APPEND Caffe_LINKER_LIBS ${OpenBLAS_LIB})
  elseif(BLAS STREQUAL "MKL" OR BLAS STREQUAL "mkl")
    find_package(MKL REQUIRED)
    include_directories(SYSTEM ${MKL_INCLUDE_DIR})
    list(APPEND Caffe_LINKER_LIBS ${MKL_LIBRARIES})
    add_definitions(-DUSE_MKL)
  endif()
elseif(APPLE)
  find_package(vecLib REQUIRED)
  include_directories(SYSTEM ${vecLib_INCLUDE_DIR})
  list(APPEND Caffe_LINKER_LIBS ${vecLib_LINKER_LIBS})

  if(VECLIB_FOUND)
    if(NOT vecLib_INCLUDE_DIR MATCHES "^/System/Library/Frameworks/vecLib.framework.*")
      add_definitions(-DUSE_ACCELERATE)
    endif()
  endif()
endif()
```

Then comes to Summary part, 

```
caffe_status("  BLAS              : " APPLE THEN "Yes (vecLib)" ELSE "Yes (${BLAS})")
```

I have checked "FindMKL.cmake" and I am sure that my configuration including environment variables setting, package pat, alias is correct. As a result you can easily figure out the Truth:

"If you are a macOS user, you can only choose vecLib; Else you can choose what you like ... for accelerate packages"

I need an excuse to explain why this happens because this waste my a lot of time.

**Comment by PENGUINLIONG** [comment]
Not really, you can find that the macro definition of `USE_ACCELERATE` is used in `/path/to/caffe/include/caffe/util/mkl_alternative.hpp`. [As you can see](https://github.com/BVLC/caffe/blob/master/include/caffe/util/mkl_alternate.hpp#L6), it's obviously that MKL support is provided.
Please check you have:
1. Installed MKL properly;
2. Enabled MKL through `BLAS := mkl` in `Makefile.config`;
3. Tried manually assign MKL include directory;
4. Forced the use of MKL in `Makefile` by commenting out decision branches, including [these lines](https://github.com/BVLC/caffe/blob/master/Makefile#L376-L402), and by changing `blas ?= atlas` to `blas := mkl`
5. Remove CMake cache files and rebuild in a clean environment if necessary.

You should know that the output problem of `Summary.cmake` is simply inherited [from the past](https://github.com/BVLC/caffe/commit/9358247014eb8322160c7feaad46091412d75d3f#diff-e9e3d4ff28c1b4017b8088030d61bcd0R118), it has not been changed after it's born, and that is `17 Dec 2014`!

**Comment by avipars** [comment]
If you are using Intel's tech because of no GPU, try openBLAS, I used it and it seems to work fine.

**Comment by yiakwy** [comment]
@PENGUINLIONG 

I have tested my MKL tests according to intel document with running environment setting script
BLAS is set
I use the following environment settings:
```
  2 # export MKLROOT=/opt/intel/composer_xe_2015.2.132/mkl
  3 export INTEL_ROOT=/opt/intel/
  4 export MKLROOT=/opt/intel/mkl
  14 export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:$INTEL_ROOT/compiler/lib:$INTEL_    ROOT/lib
  18 export DYLD_FALLBACK_LIBRARY_PATH=/usr/local/cuda/lib:$HOME/anaconda/lib:/us    r/local/lib:/usr/lib:$MKLROOT/lib
```

To summarize, `BLAS` set to "atlas" works but does not work with intel mkl. If you choose intel mkl, an error will be fired when run tests : 

```
_mklxx.dylib not found ...
```

**Comment by PENGUINLIONG** [comment]
Of course, it works if you set your `BLAS` to `atlas` because veclib and Accelerate framework are both implementation of Atlas and they are ready to go all the time. I'm not sure whether you have followed my recommendation. Please ensure that you have tried my procedure. If it doesn't work, post more information, such as, the BLAS part of your Makefile.config and the install path of your MKL if you didn't use the default one. According to [these lines](https://github.com/BVLC/caffe/blob/master/Makefile#L369-L375), it shouldn't happen if you have properly installed your MKL.

**Comment by shelhamer** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
