### ISSUE TITLE
Error while trying to deploy Caffe on EC2 instance

### ISSUE THREAD

**Issue by rahulkulhalli** [BVLC/caffe#5235]
I'm trying to integrate my Ubuntu 14.04 EC2 instance with Caffe, and running a pre-trained caffemodel onto it. I've also integrrated Flask on top of my EC2 instance, so as to listen to incoming HTTP POST requests.

I believe I've done everything that is required to brew Caffe properly. I performed the following steps:

1) Installed all the dependencies
2) Cloned the repo onto my EC2
3) Copied Makefile.config.example to a new Makefile.config
4) Uncommented the CPU_ONLY flag, and verified the PYTHONPATH
5) ran the command 'make -j4 all'
6) ran the command 'make -j4 pycaffe'
7) ran the command 'make -j4 distribute'
8) make runtest

I then opened up python and tried importing caffe, but it gave me the following traceback:

Traceback (most recent call last):
  File "/home/ubuntu/model/example.py", line 19, in <module>
    import caffe  # noqa
  File "/usr/local/lib/python2.7/dist-packages/caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropSolver, AdaDeltaSolver, AdamSolver, NCCL, Timer
  File "/usr/local/lib/python2.7/dist-packages/caffe/pycaffe.py", line 13, in <module>
    from ._caffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, \
ImportError: libcaffe.so.1.0.0-rc3: cannot open shared object file: No such file or directory

After searching the issues thread for a long time, I found a temporary workaround:

set PYTHONPATH=$PYTHONPATH:/path/to/caffe/python

After doing this, and trying to import caffe into python, it worked. However, after restarting the instance, I'm getting the same error over and over again.

I've also tried the CMake alternative, but it doesn't seem to work.

Can someone please tell me a permanent solution for this?

These are my caffe directory contents:

total 196
lrwxrwxrwx  1 ubuntu ubuntu    14 Jan 27 07:29 build -> .build_release
-rw-rw-r--  1 ubuntu ubuntu  1180 Jan 27 07:18 caffe.cloc
-rw-rw-r--  1 root   root    1858 Jan 30 05:23 CaffeConfig.cmake
-rw-rw-r--  1 root   root     759 Jan 30 05:23 caffe_config.h
-rw-r--r--  1 root   root    3705 Jan 30 05:23 CaffeTargets.cmake
drwxrwxr-x  5 ubuntu ubuntu  4096 Jan 30 05:23 cmake
-rw-r--r--  1 root   root   38377 Jan 30 05:23 CMakeCache.txt
drwxr-xr-x  8 root   root    4096 Jan 30 05:29 CMakeFiles
-rw-r--r--  1 root   root    3304 Jan 30 05:23 cmake_install.cmake
-rw-rw-r--  1 ubuntu ubuntu  3079 Jan 27 07:18 CMakeLists.txt
-rw-rw-r--  1 ubuntu ubuntu  1917 Jan 27 07:18 CONTRIBUTING.md
-rw-rw-r--  1 ubuntu ubuntu   620 Jan 27 07:18 CONTRIBUTORS.md
drwxrwxr-x  5 ubuntu ubuntu  4096 Jan 27 07:18 data
drwxrwxr-x  7 ubuntu ubuntu  4096 Jan 28 11:39 distribute
drwxrwxr-x  4 ubuntu ubuntu  4096 Jan 27 07:18 docker
drwxrwxr-x  7 ubuntu ubuntu  4096 Jan 30 05:23 docs
drwxrwxr-x 16 ubuntu ubuntu  4096 Jan 30 05:23 examples
drwxrwxr-x  3 ubuntu ubuntu  4096 Jan 27 07:18 include
-rw-r--r--  1 root   root       0 Jan 30 05:23 __init__.py
-rw-r--r--  1 ubuntu ubuntu   104 Jan 30 05:33 __init__.pyc
-rw-rw-r--  1 ubuntu ubuntu   210 Jan 27 07:18 INSTALL.md
drwxr-xr-x  2 root   root    4096 Jan 30 05:27 lib
-rw-rw-r--  1 ubuntu ubuntu  2092 Jan 27 07:18 LICENSE
-rw-r--r--  1 root   root   17147 Jan 30 05:23 Makefile
-rw-rw-r--  1 ubuntu ubuntu  4520 Jan 28 11:47 Makefile.config
-rw-rw-r--  1 ubuntu ubuntu  4427 Jan 27 07:20 Makefile.config.example
-rw-rw-r--  1 ubuntu ubuntu  4451 Jan 27 08:40 Makefile.config.save
drwxrwxr-x  6 ubuntu ubuntu  4096 Jan 30 05:23 matlab
drwxrwxr-x  7 ubuntu ubuntu  4096 Jan 27 07:18 models
drwxrwxr-x  4 ubuntu ubuntu  4096 Jan 30 05:23 python
-rw-rw-r--  1 ubuntu ubuntu  2102 Jan 27 07:18 README.md
drwxrwxr-x  3 ubuntu ubuntu  4096 Jan 27 07:18 scripts
drwxrwxr-x  4 ubuntu ubuntu  4096 Jan 27 07:18 src
drwxr-xr-x  2 root   root    4096 Jan 30 05:29 test
drwxrwxr-x  4 ubuntu ubuntu  4096 Jan 30 05:26 tools

**Comment by mblokker** [comment]
pycaffe relies on libraries like libcaffe. So everytime you will try to use it, it will look for these libraries. Setting an environment variable (in your case PYTHONPATH) tells the OS where to look for external dependencies. This environment variable is flushed upon restart.

You can edit the `.bash_profile` file in your home directory to set the PYTHONPATH variable upon each login,  e.g.:
`export PYTHONPATH=/path/to/caffe/python:$PYTHONPATH`

**Comment by shelhamer** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
