### ISSUE TITLE
Memory leak in PyCaffe: _forward

### ISSUE THREAD

**Issue by Nytrox** [BVLC/caffe#5238]
### Issue summary
I'm using Yahoo's open_nsfw library which uses the forward_all function in a for loop. However, doing this causes the memory on my server to rise without lowering and eventually OS Errors before it is run to completion. Using the memory profiler, I've determined the error is in forward_all, most likely the forward function, which is essentially ForwardFromTo.

### Steps to reproduce

In pycaffe, calling _Net_foward_all multiple times. More specifically, this is from Yahoo's [open_nsfw](https://github.com/yahoo/open_nsfw) in their function caffe_preprocess_and_compute 

### Your system configuration
Operating system: Ubuntu 14.04
Compiler:
CUDA version (if applicable): CUDA 8.0
CUDNN version (if applicable):
BLAS: From Apt-Get. libatlas-base-dev 3.10.1-4
Python or MATLAB version (for pycaffe and matcaffe respectively): Python 2.7.5

**Comment by shelhamer** [comment]
Sorry, I can't reproduce this in Caffe master. The pycaffe `forward()` is a thin wrapper around `Net::Forward()` and if that was leaking memory then nearly everything would be crashing.
