### ISSUE TITLE
Static linking error building on FreeBSD

### ISSUE THREAD

**Issue by PeterSprague** [BVLC/caffe#5239]
### Issue summary
$ gmake
produces error: Makefile:314: *** Cannot static link with the c++ compiler.  Stop.

Both Clang & GCC are installed

### Steps to reproduce
On FreeBSD host:
vi Makefile

##############################
# Configure build
##############################

# Determine platform
UNAME := $(shell uname -s)
ifeq ($(UNAME), FreeBSD)
        FreeBSD := 1
else ifeq ($(UNAME), Darwin)
        OSX := 1
        OSX_MAJOR_VERSION := $(shell sw_vers -productVersion | cut -f 1 -d .)
        OSX_MINOR_VERSION := $(shell sw_vers -productVersion | cut -f 2 -d .)
endif

# FreeBSD
ifeq ($(FreeBSD), 1)
        CXX ?= /usr/local/bin/g++
        GCCVERSION := $(shell $(CXX) -dumpversion | cut -f1,2 -d.)
        # older versions of gcc are too dumb to build boost with -Wuninitalized
        ifeq ($(shell echo | awk '{exit $(GCCVERSION) < 4.6;}'), 1)
                WARNINGS += -Wno-uninitialized
        endif
        # boost::thread is reasonably called boost_thread (compare OS X)
        # We will also explicitly add stdc++ to the link target.
        LIBRARIES += boost_thread stdc++
        VERSIONFLAGS += -Wl,-soname,$(DYNAMIC_VERSIONED_NAME_SHORT) -Wl,-rpath,$(ORIGIN)/../lib
endif

$ gmake

### Your system configuration
Operating system: FreeBSD/TrueOS 12.0
Compiler: GCC 4.9.4
CUDA version (if applicable): only building for CPU now
CUDNN version (if applicable):
BLAS: openblas-0.2.19,1
Python or MATLAB version (for pycaffe and matcaffe respectively):

**Comment by shelhamer** [comment]
Sorry, FreeBSD is not a supported platform. As a workaround you could run Caffe through Docker with our Ubuntu image.

**Comment by bsdelf** [comment]
@PeterSprague 

Please use cmake, and link against quadmath library shipped with gcc.

I sucessfully built caffe on FreeBSD 11 with openmp support.

On my machine, `train_lenet.sh` takes 6 minutes. (CPU: E3-1245 v5)
