### ISSUE TITLE
make test error

### ISSUE THREAD

**Issue by AlexandraToropova** [BVLC/caffe#5247]
Hi, I tryed to run  'make test' and got the following:

CXX src/caffe/test/test_io.cpp
In file included from src/caffe/test/test_io.cpp:8:0:
src/caffe/test/test_io.cpp: In member function ‘virtual void caffe::IOTest_TestDecodeDatumToCVMatContent_Test::TestBody()’:
src/caffe/test/test_io.cpp:325:71: error: no matching function for call to ‘ReadImageToDatum(std::__cxx11::string&, int, std::__cxx11::string, caffe::Datum*)’
   EXPECT_TRUE(ReadImageToDatum(filename, 0, std::string("jpg"), &datum));
                                                                       ^
./src/gtest/gtest.h:7859:34: note: in definition of macro ‘GTEST_TEST_BOOLEAN_’
       ::testing::AssertionResult(expression)) \
                                  ^
src/caffe/test/test_io.cpp:325:3: note: in expansion of macro ‘EXPECT_TRUE’
   EXPECT_TRUE(ReadImageToDatum(filename, 0, std::string("jpg"), &datum));
   ^
In file included from src/caffe/test/test_io.cpp:11:0:
./include/caffe/util/io.hpp:123:6: note: candidate: bool caffe::ReadImageToDatum(const string&, int, int, int, bool, const string&, caffe::Datum*)
 bool ReadImageToDatum(const string& filename, const int label,
      ^
./include/caffe/util/io.hpp:123:6: note:   candidate expects 7 arguments, 4 provided
./include/caffe/util/io.hpp:126:6: note: candidate: bool caffe::ReadImageToDatum(const string&, int, int, int, bool, caffe::Datum*)
 bool ReadImageToDatum(const string& filename, const int label,
      ^
./include/caffe/util/io.hpp:126:6: note:   candidate expects 6 arguments, 4 provided
./include/caffe/util/io.hpp:129:13: note: candidate: bool caffe::ReadImageToDatum(const string&, int, int, int, caffe::Datum*)
 inline bool ReadImageToDatum(const string& filename, const int label,
             ^
./include/caffe/util/io.hpp:129:13: note:   candidate expects 5 arguments, 4 provided
./include/caffe/util/io.hpp:134:13: note: candidate: bool caffe::ReadImageToDatum(const string&, int, bool, caffe::Datum*)
 inline bool ReadImageToDatum(const string& filename, const int label,
             ^
./include/caffe/util/io.hpp:134:13: note:   no known conversion for argument 3 from ‘std::__cxx11::string {aka std::__cxx11::basic_string<char>}’ to ‘bool’
./include/caffe/util/io.hpp:139:13: note: candidate: bool caffe::ReadImageToDatum(const string&, int, caffe::Datum*)
 inline bool ReadImageToDatum(const string& filename, const int label,
             ^
./include/caffe/util/io.hpp:139:13: note:   candidate expects 3 arguments, 4 provided
In file included from src/caffe/test/test_io.cpp:8:0:
src/caffe/test/test_io.cpp: In member function ‘virtual void caffe::IOTest_TestDecodeDatumToCVMatContentNative_Test::TestBody()’:
src/caffe/test/test_io.cpp:405:71: error: no matching function for call to ‘ReadImageToDatum(std::__cxx11::string&, int, std::__cxx11::string, caffe::Datum*)’
   EXPECT_TRUE(ReadImageToDatum(filename, 0, std::string("jpg"), &datum));
                                                                       ^
./src/gtest/gtest.h:7859:34: note: in definition of macro ‘GTEST_TEST_BOOLEAN_’
       ::testing::AssertionResult(expression)) \
                                  ^
src/caffe/test/test_io.cpp:405:3: note: in expansion of macro ‘EXPECT_TRUE’
   EXPECT_TRUE(ReadImageToDatum(filename, 0, std::string("jpg"), &datum));
   ^
In file included from src/caffe/test/test_io.cpp:11:0:
./include/caffe/util/io.hpp:123:6: note: candidate: bool caffe::ReadImageToDatum(const string&, int, int, int, bool, const string&, caffe::Datum*)
 bool ReadImageToDatum(const string& filename, const int label,
      ^
./include/caffe/util/io.hpp:123:6: note:   candidate expects 7 arguments, 4 provided
./include/caffe/util/io.hpp:126:6: note: candidate: bool caffe::ReadImageToDatum(const string&, int, int, int, bool, caffe::Datum*)
 bool ReadImageToDatum(const string& filename, const int label,
      ^
./include/caffe/util/io.hpp:126:6: note:   candidate expects 6 arguments, 4 provided
./include/caffe/util/io.hpp:129:13: note: candidate: bool caffe::ReadImageToDatum(const string&, int, int, int, caffe::Datum*)
 inline bool ReadImageToDatum(const string& filename, const int label,
             ^
./include/caffe/util/io.hpp:129:13: note:   candidate expects 5 arguments, 4 provided
./include/caffe/util/io.hpp:134:13: note: candidate: bool caffe::ReadImageToDatum(const string&, int, bool, caffe::Datum*)
 inline bool ReadImageToDatum(const string& filename, const int label,
             ^
./include/caffe/util/io.hpp:134:13: note:   no known conversion for argument 3 from ‘std::__cxx11::string {aka std::__cxx11::basic_string<char>}’ to ‘bool’
./include/caffe/util/io.hpp:139:13: note: candidate: bool caffe::ReadImageToDatum(const string&, int, caffe::Datum*)
 inline bool ReadImageToDatum(const string& filename, const int label,
             ^
./include/caffe/util/io.hpp:139:13: note:   candidate expects 3 arguments, 4 provided
Makefile:501: recipe for target '.build_debug/src/caffe/test/test_io.o' failed
make: *** [.build_debug/src/caffe/test/test_io.o] Error 1

Operating system: ununtu -16.04
Compiler: gcc  5.4.0 
CUDA version (if applicable): 8.0
CUDNN version (if applicable): v1

What can I do?

**Comment by shaibagon** [comment]
Please use the [caffe-users list][1] for usage, installation, or modeling questions, or other requests for help.
You may also post questions on [stackoverflow][3], make sure you tag them with `caffe` tag.  
Do not post such requests to Issues. Doing so interferes with the development of Caffe.

Please read the [guidelines for contributing][2] before submitting this issue.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
 [3]: http://stackoverflow.com/questions/tagged/caffe

**Comment by williford** [comment]
When you post on caffe-users list, be sure to include enough information. It doesn't look like you are using the latest Caffe version. Make sure to give the Caffe version (ie. `git rev-parse HEAD`), and what other steps you use (what steps did you follow to build the source). Also state whether you can build without CUDNN and CUDA (CUDNN v1 cannot be correct).
