### ISSUE TITLE
Slow issue when merging and shuffling two lmdb files

### ISSUE THREAD

**Issue by RileyLee** [BVLC/caffe#5256]
Hello, 

I'm trying to merge and shuffle two exiting lmdb files with my code below:

`def combMat2lmdb(lmdbOutPath, dataPath, label, imageSize, picList=[]):
    totalFiles = 0;
    totalImages = 0;
    outFileName = Path2NameParser(lmdbOutPath);
    print('Reading dictionary...')
    for root, dirs, files in os.walk(dataPath):
        for file in files:
            if file.endswith(".mat") and ( len(picList)==0 or Name2IdxICPR(file) in picList ):
                mat = loadmat(root + '/' + file)
                totalFiles += 1;
                totalImages += mat['ImageSet'].shape[1];

    mapSize = np.zeros((101, 101, 3), dtype = np.uint8).nbytes * totalImages * 10;
    print('Total ' + str(totalFiles) + ' files detected, inlcuding ' + str(totalImages) + ' images.')
    env = lmdb.open(lmdbOutPath, map_size=mapSize)
    idx = 0;
    with env.begin(write=True) as txn:
        for root, dirs, files in os.walk(dataPath):
            for file in files:
                if file.endswith(".mat") and ( len(picList)==0 or Name2IdxICPR(file) in picList ):
                    mat = loadmat(root + '/' + file)
                    for im in range(0, mat['ImageSet'].shape[1]):
                        data1 = mat['ImageSet'][0, im].transpose((2,0,1));
                        data = np.zeros(data1.shape, dtype=np.uint8);
                        data[0,:,:] = data1[2,:,:].copy();
                        data[1,:,:] = data1[1,:,:].copy();
                        data[2,:,:] = data1[0,:,:].copy();
                        datum = caffe.proto.caffe_pb2.Datum()
                        datum.channels = imageSize[2]
                        datum.height = imageSize[0]
                        datum.width = imageSize[1]
                        datum.data = data.tobytes()  # or .tostring() if numpy < 1.9
                        datum.label = int(label)
                        str_id = '{:08}'.format(idx)
                        txn.put(str_id.encode('ascii'), datum.SerializeToString())
                        idx += 1;
    print(outFileName + ' created....')`

The merged lmdb includes 1 million 101*101 sized patches in RGB. However, the data accessing takes forever. Each iteration in caffe training takes very long time to read data. The program is getting stuck at "[Blocking_queue.cpp 50]Data layer prefetch queue empty" or "[Blocking_queue.cpp 50]Waiting for data."

Does anyone know what's going on here or have a better way to merge and shuffle two lmdb files?

**Comment by shelhamer** [comment]
Merging and shuffling lmdbs is slow—that is a reason for the common practice of shuffling once than iterating.
