### ISSUE TITLE
Googlenet training error

### ISSUE THREAD

**Issue by barkntuncer** [BVLC/caffe#5257]
I0206 13:44:41.683648 29874 net.cpp:165] Memory required for data: 166183040
I0206 13:44:41.683655 29874 layer_factory.hpp:77] Creating layer inception_3a/relu_3x3_reduce
I0206 13:44:41.683662 29874 net.cpp:100] Creating Layer inception_3a/relu_3x3_reduce
I0206 13:44:41.683665 29874 net.cpp:434] inception_3a/relu_3x3_reduce <- inception_3a/3x3_reduce
I0206 13:44:41.683670 29874 net.cpp:395] inception_3a/relu_3x3_reduce -> inception_3a/3x3_reduce (in-place)
I0206 13:44:41.683675 29874 net.cpp:150] Setting up inception_3a/relu_3x3_reduce
I0206 13:44:41.683677 29874 net.cpp:157] Top shape: 8 96 28 28 (602112)
I0206 13:44:41.683679 29874 net.cpp:165] Memory required for data: 168591488
I0206 13:44:41.683692 29874 layer_factory.hpp:77] Creating layer inception_3a/3x3
I0206 13:44:41.683711 29874 net.cpp:100] Creating Layer inception_3a/3x3
I0206 13:44:41.683714 29874 net.cpp:434] inception_3a/3x3 <- inception_3a/3x3_reduce
I0206 13:44:41.683719 29874 net.cpp:408] inception_3a/3x3 -> inception_3a/3x3
    @     0x7f1bd3964b5d  clone
    @              (nil)  (unknown)
Aborted (core dumped)

Hello everyone I am trying to train Googlenet which is in the models file but I am getting the error above. Is there any solution ? This link is also showing the error http://imgur.com/a/v5igW
My solver file is like that :

net: "../lab2/caffe/models/bvlc_googlenet/train_val.prototxt"
test_iter: 100
test_interval: 200
test_initialization: false
display: 40
average_loss: 40
base_lr: 0.01
lr_policy: "step"
stepsize: 3200
gamma: 0.96
max_iter: 10000
momentum: 0.9
weight_decay: 0.0002
snapshot: 4000
snapshot_prefix: "../lab2/caffe/models/bvlc_googlenet/bvlc_googlenet"
solver_mode: GPU

and I use batch size 8 for near 375 images with gray scale

**Comment by shaibagon** [comment]
Please use the [caffe-users list][1] for usage, installation, or modeling questions, or other requests for help.
You may also post questions on [stackoverflow][3], make sure you tag them with `caffe` tag.  
Do not post such requests to Issues. Doing so interferes with the development of Caffe.

Please read the [guidelines for contributing][2] before submitting this issue.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
 [3]: http://stackoverflow.com/questions/tagged/caffe

**Comment by shelhamer** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

**Comment by shelhamer** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
