### ISSUE TITLE
caffe cuda 8.0 fmake runtest failing

### ISSUE THREAD

**Issue by xsbymz** [BVLC/caffe#5259]
Operating system: ubuntu 16.04
cuda 8.0

 5204.386081] NVRM: The NVIDIA probe routine was not called for 1 device(s).
[ 5204.386082] NVRM: This can occur when a driver such as: 
               NVRM: nouveau, rivafb, nvidiafb or rivatv 
               NVRM: was loaded and obtained ownership of the NVIDIA device(s).
[ 5204.386083] NVRM: Try unloading the conflicting kernel module (and/or
               NVRM: reconfigure your kernel without the conflicting
               NVRM: driver(s)), then try loading the NVIDIA kernel module
               NVRM: again.
[ 5204.386085] NVRM: No NVIDIA graphics adapter probed!
[ 5204.386086] nvidia-nvlink: Unregistered the Nvlink Core, major device number 243
[ 5204.386157] NVRM: NVIDIA init module failed!

.build_release/test/test_all.testbin 0 --gtest_shuffle 
modprobe: ERROR: could not insert 'nvidia_367_uvm': No such device
Cuda number of devices: 0
Setting to use device 0
Current device id: 0
Current device name: 
Note: Randomizing tests' orders with a seed of 58468 .
[==========] Running 2037 tests from 267 test cases.
[----------] Global test environment set-up.
[----------] 3 tests from SplitLayerTest/3, where TypeParam = caffe::GPUDevice<double>
[ RUN      ] SplitLayerTest/3.TestGradient
modprobe: ERROR: could not insert 'nvidia_367_uvm': Unknown symbol in module, or unknown parameter (see dmesg)
E0206 18:28:59.480386  5241 common.cpp:114] Cannot create Cublas handle. Cublas won't be available.
modprobe: ERROR: could not insert 'nvidia_367_uvm': No such device
E0206 18:28:59.544909  5241 common.cpp:121] Cannot create Curand generator. Curand won't be available.
F0206 18:28:59.544991  5241 syncedmem.hpp:22] Check failed: error == cudaSuccess (30 vs. 0)  unknown error
*** Check failure stack trace: ***
    @     0x7f776edbc5cd  google::LogMessage::Fail()
    @     0x7f776edbe433  google::LogMessage::SendToLog()
    @     0x7f776edbc15b  google::LogMessage::Flush()
    @     0x7f776edbee1e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f776c990751  caffe::SyncedMemory::mutable_cpu_data()
    @     0x7f776c98aa70  caffe::Blob<>::Reshape()
    @     0x7f776c98aeea  caffe::Blob<>::Reshape()
    @     0x7f776c98af9c  caffe::Blob<>::Blob()
    @           0x5dc47e  caffe::SplitLayerTest<>::SplitLayerTest()
    @           0x5dc87b  testing::internal::TestFactoryImpl<>::CreateTest()
    @           0x8e2a23  testing::internal::HandleExceptionsInMethodIfSupported<>()
    @           0x8dbf83  testing::TestInfo::Run()
    @           0x8dc0e5  testing::TestCase::Run()
    @           0x8dd3bf  testing::internal::UnitTestImpl::RunAllTests()
    @           0x8dd6e3  testing::UnitTest::Run()
    @           0x46692d  main
    @     0x7f776bbf1830  __libc_start_main
    @           0x46dfc9  _start
    @              (nil)  (unknown)
Makefile:532: recipe for target 'runtest' failed

**Comment by xsbymz** [comment]
fixed

**Comment by kbibi99** [comment]
how ?
 i need to fix it
