### ISSUE TITLE
Windows build issue commands not found

### ISSUE THREAD

**Issue by dhruvilbadani** [BVLC/caffe#5261]
### Issue summary
I get the following error when trying to scripts/run build_win.cmd

```
scripts/build_win.cmd: line 1: @echo: command not found
scripts/build_win.cmd: line 2: @setlocal: command not found
scripts/build_win.cmd: line 4: ::: command not found
scripts/build_win.cmd: line 5: syntax error near unexpected token `('
scripts/build_win.cmd: line 5: `if DEFINED APPVEYOR ('
```

### Steps to reproduce

`cd /c/`
`mkdir Projects`
`cd Projects/`
`git clone https://github.com/BVLC/caffe.git`
`cd caffe/`
`git checkout windows`
`scripts/build_win.cmd`

### Your system configuration
Operating system: Windows 10
Compiler:
CUDA version (if applicable): 8.0
CUDNN version (if applicable): 2.5
BLAS:
Python or MATLAB version (for pycaffe and matcaffe respectively): Python 3.5 (Anaconda)

**Comment by willyd** [comment]
Looks like you are not executing the script from cmd.exe prompt.
