### ISSUE TITLE
draw_net : received Illegal instruction: 4

### ISSUE THREAD

**Issue by ch02190** [BVLC/caffe#5264]
Having attempted to draw the net by 
`
python draw_net.py --rankdir TB ../examples/mnist/lenet.prototxt ../example
s/mnist/lenet.png
`

I received the error:
`
Python(12320,0x7fffb03393c0) malloc: *** malloc_zone_unregister() failed for 0x7fffb032f000
`
`
Drawing net to ../examples/mnist/lenet.png
`
`
Illegal instruction: 4
`

I have checked the python files, and notice that the error was generated when I called the method _create_ from _draw_net(caffe_net, rankdir, ext, phase)_, which is the pydotplus.graphviz.Dot object in the python file _caffe/python/draw.py_:
`
draw_net(caffe_net, rankdir, ext, phase).create(format=ext) 
`

Without calling the method _create_ and without creating a new file, there was no error generated but could not convert the format to 'png' and hence no net was drawn.

I wonder if that is the problem of my versions of module:
pydotplus-2.0.2
pyparsing version 2.0.1
graphviz version 2.40.1
Even when I tried to install pydot instead of pydotplus, still I got the same problem.

How to fix this problem? Thanks.

### Your system configuration
Operating system: macOS Sierra version 10.12.3
Compiler: GCC 4.2.1
Python or MATLAB version (for pycaffe and matcaffe respectively): Python 2.7.12

**Comment by QiaoWenfan** [comment]
I have same problem, how to fix this problem? Thanks!

**Comment by shelhamer** [comment]
Sorry, this seems to be a Python/dot/graphviz issue and not about Caffe. On OS X you could try our Docker installation.
