### ISSUE TITLE
Caffe rc4 tag shows rc3 as dynamic lib's and binaries' version

### ISSUE THREAD

**Issue by npanpaliya** [BVLC/caffe#5265]
### Issue summary
Caffe rc4 tag generates libcaffe.so and caffe binary with rc3 as version. Changing it to rc4 breaks backward compatibility. We tried running the old caffe binary against libcaffe.so.*rc4 name, and linux loader complained about not finding the rc3 library.

Please let us know if you've intentionally kept the version as rc3.

### Steps to reproduce
Build rc4 tag of caffe using make.

### Your system configuration
Operating system: Linux pp64le
Compiler: gcc 5.4
CUDA version (if applicable): 8.0
CUDNN version (if applicable): 5
BLAS: Openblas 0.2.19
Python or MATLAB version (for pycaffe and matcaffe respectively): Python 2.7

**Comment by shelhamer** [comment]
Right, I forgot to bump the version when I made the tag. We could switch the tag to https://github.com/BVLC/caffe/commit/4056f79f9d8ebf261db45883470a0e2939f725e9 to fix the version, fix multi-GPU restore #5215 and include the latest docker setup #5153 or call it yet another RC.

**Comment by hartb** [comment]
@shelhamer, Thank you.  I'm on @npanpaliya 's team. Did you mean to suggest moving the tag to 1354403 as the version fix? And would a further change be needed to update DYNAMIC_VERSION_REVISION in Makefile (we currently build with make rather than cmake)?

I don't think we have strong opinion either way on moving the tag vs creating a new one.

**Comment by shelhamer** [comment]
To be fixed soon by #5296. Sorry for the trouble!

**Comment by hartb** [comment]
Thank you!

**Comment by shelhamer** [comment]
Fixed by #5296 and the latest release https://github.com/BVLC/caffe/releases/tag/rc5
