### ISSUE TITLE
How can I  solve this build error?

### ISSUE THREAD

**Issue by nourlaban** [BVLC/caffe#5266]
[  0%] Performing update step for 'MKLDNN_Build'
[  0%] Performing configure step for 'MKLDNN_Build'
-- MKLDNN_Build configure command succeeded.  See also /Downloads/build/MKLDNN_Build-prefix/src/MKLDNN_Build-stamp/MKLDNN_Build-configure-*.log
[  0%] Performing build step for 'MKLDNN_Build'
-- MKLDNN_Build build command succeeded.  See also /Downloads/build/MKLDNN_Build-prefix/src/MKLDNN_Build-stamp/MKLDNN_Build-build-*.log
[  0%] Performing install step for 'MKLDNN_Build'
CMake Error at /Downloads/build/MKLDNN_Build-prefix/src/MKLDNN_Build-stamp/MKLDNN_Build-install-Release.cmake:16 (message):
  Command failed: 2

   'make' 'install'

  See also
/Downloads/build/MKLDNN_Build-prefix/src/MKLDNN_Build-stamp/MKLDNN_Build-install-*.log

CMakeFiles/MKLDNN_Build.dir/build.make:73: recipe for target 'MKLDNN_Build-prefix/src/MKLDNN_Build-stamp/MKLDNN_Build-install' failed
make[2]: *** [MKLDNN_Build-prefix/src/MKLDNN_Build-stamp/MKLDNN_Build-install] Error 1
CMakeFiles/Makefile2:99: recipe for target 'CMakeFiles/MKLDNN_Build.dir/all' failed
make[1]: *** [CMakeFiles/MKLDNN_Build.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by jdukat** [comment]
Are you using Intel's fork of Caffe rather than this BVLC's Caffe?
If yes, please report the issue here:
https://github.com/intel/caffe/issues

Also please make sure that you're using the latest code published and provide command lines that lead to the first error.

**Comment by nourlaban** [comment]
Thanks very much 
After I re-download the BVLC code and reinstall VC++ 15, Caffe has   built successfully.
