### ISSUE TITLE
Ubuntu 14.04 requiring "protobuf-compiler"

### ISSUE THREAD

**Issue by Yangqing** [BVLC/caffe#527]
It seems that the binary protoc is no longer installed by libprotobuf-dev, and one has to additionally do

sudo apt-get install protobuf-compiler

to install that. Just a note and I'll update the doc later.

**Comment by jenifferYingyiWu** [comment]
On Ubuntu 14.04, I executed the command "make all -j $(($(nproc) + 1))
"under $CAFFE_HOME, then I encountered the following errors.
Could you pls help to give me some suggestions about how to resolve it?
.build_release/src/caffe/proto/caffe.pb.h:12:2: error: #error This file was generated by a newer version of protoc which is
 #error This file was generated by a newer version of protoc which is
  ^"

**Comment by jenifferYingyiWu** [comment]
On Ubuntu 14.04, I executed the command "make all -j $(($(nproc) + 1))
"under $CAFFE_HOME, then I encountered the following errors.
Could you pls help to give me some suggestions about how to resolve it?
.build_release/src/caffe/proto/caffe.pb.h:12:2: error: #error This file was generated by a newer version of protoc which is
 #error This file was generated by a newer version of protoc which is
  ^"

**Comment by jenifferYingyiWu** [comment]
On Ubuntu 14.04, I executed the command "make all -j $(($(nproc) + 1))
"under $CAFFE_HOME, then I encountered the following errors.
Could you pls help to give me some suggestions about how to resolve it?
.build_release/src/caffe/proto/caffe.pb.h:12:2: error: #error This file was generated by a newer version of protoc which is
 #error This file was generated by a newer version of protoc which is
  ^"

**Comment by jenifferYingyiWu** [comment]
On Ubuntu 14.04, I executed the command "make all -j $(($(nproc) + 1))
"under $CAFFE_HOME, then I encountered the following errors.
Could you pls help to give me some suggestions about how to resolve it?
.build_release/src/caffe/proto/caffe.pb.h:12:2: error: #error This file was generated by a newer version of protoc which is
 #error This file was generated by a newer version of protoc which is
  ^"
