### ISSUE TITLE
Failed to parse NetParameter file: Error parsing text-format caffe.NetParameter: 4:9: Expected integer or identifier

### ISSUE THREAD

**Issue by mayurjain0312** [BVLC/caffe#5271]
I am getting the following error message:

I0209 11:05:43.446990 27505 solver.cpp:94] Creating training net from net file: /prj/neo-nas/mayurj/tif/model_file.prototxt^M
[libprotobuf ERROR /local/mnt/workspace/jenkins-slave/workspace/Morpheus_CI/build/x86_64-linux-clang/ThirdParty/protobuf-2.6.1/src/protobuf_tp/src/google/protobuf/text_format.cc:274] Error parsing text-format caffe.NetParameter: 4:9: Expected integer or identifier.^M
F0209 11:05:43.468014 27505 upgrade_proto.cpp:79] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: /prj/neo-nas/mayurj/tif/model_file.prototxt^M
*** Check failure stack trace: ***^M
    @     0x7fb048ca92c3  google::LogMessage::SendToLog()^M
    @     0x7fb048ca97a8  google::LogMessage::Flush()^M
    @     0x7fb048cad42d  google::LogMessageFatal::~LogMessageFatal()^M
    @     0x7fb0488d456e  caffe::ReadNetParamsFromTextFileOrDie()^M
    @     0x7fb048929beb  caffe::Solver<>::InitTrainNet()^M
    @     0x7fb04892ac1c  caffe::Solver<>::Init()^M
    @     0x7fb04892af4a  caffe::Solver<>::Solver()^M
    @     0x7fb048b01dd3  caffe::Creator_SGDSolver<>()^M
    @           0x4115b6  caffe::SolverRegistry<>::CreateSolver()^M
    @           0x40a2a0  train()^M
    @           0x40e59c  main^M
    @     0x7fb0472aa7ed  __libc_start_main^M
    @           0x408479  (unknown)^M
/prj/icecad/lsfgridsdccspool/x/1486667138.7190108: line 8: 27505 Aborted                 (core dumped) caffe train -gpu 0 -solver /prj/neo-nas/mayurj/tif/solver_file.prototxt^M

**Comment by mayurjain0312** [comment]
Model_file.txt:

name: "Oxford102_CaffeNet"
layers {
  name: "data"
  type: "TifData"
  top: "data"
  top: "label"
  include {
    phase: TRAIN
  }
  data_param {
    source: "/prj/neo-nas/mayurj/tif/training/exampletest/TIF_image_data"
    batch_size: 20
    backend: LMDB
  }

  transform_param {
    force_color: true
    crop_params {
      crop_height: 200
      crop_width: 320
    }
  }
}


layers {
  name: "data"
  type: "TifData"
  top: "data"
  top: "label"
  include {
    phase: TEST
  }
  data_param {
    source: "/prj/neo-nas/mayurj/tif/validation/exampletest/TIF_image_data"
    batch_size: 1
    backend: LMDB
  }

  transform_param {
    force_color: true
    crop_params {
      crop_height: 200
      crop_width: 320
    }
  }
}

**Comment by shaibagon** [comment]
Please use the [caffe-users list][1] for usage, installation, or modeling questions, or other requests for help.
You may also post questions on [stackoverflow][3], make sure you tag them with `caffe` tag.  
Do not post such requests to Issues. Doing so interferes with the development of Caffe.

Please read the [guidelines for contributing][2] before submitting this issue.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
 [3]: http://stackoverflow.com/questions/tagged/caffe
