### ISSUE TITLE
Problem of using MemoryDataLayer to test

### ISSUE THREAD

**Issue by freedomabcd** [BVLC/caffe#5273]
Now I want to load a image from memory then pass it to network to test on it.

So I write code like this(judging https://medium.com/@shiyan/caffe-c-helloworld-example-with-memorydata-input-20c692a82a22#.nqoycpgsn ):

      bottom_in.push_back(this->bottom_vec);
      caffe::MemoryDataLayer<Dtype> *m_layer_ =  (caffe::MemoryDataLayer<Dtype> *)(this->caffe_net.layer_by_name("data").get());
      m_layer_->Reset(this->bottom, this->bottom, 1);
      this->caffe_net.Forward(bottom_in);

But it core dump.I check the data and ensure the data is passed OK.
So I check into the caffe and find that in Net class:

    vector<Blob<Dtype>*> net_input_blobs_;

The size of net_input_blobs_ is 0, so 

    net_input_blobs_[i]->CopyFrom(*bottom[i]);

in Forward function in Net class goes wrong.

this is my proto about MemoryDataLayer:

    layer {
  

    name: "data"
      # type: "ImageSegData"
      type: "MemoryData"
      top: "data"
      top: "label"
      # top: "data_dim"
      include {
        phase: TEST
      }
      transform_param {
        mirror: false
        crop_size: 513
        mean_value: 104.008
        mean_value: 116.669
        mean_value: 122.675
      }
      memory_data_param {
        batch_size: 1
        channels: 3
        height: 480  
        width: 640 
      }
    }

I am confused for this question for several days, Can you give me some advice or some example of MemoryDataLayer?

**Comment by shelhamer** [comment]
Closing according to #5528 since `Input` layers cover this use case.
