### ISSUE TITLE
using model to classify image sometimes get “nan” values

### ISSUE THREAD

**Issue by junedgar** [BVLC/caffe#5274]
### Issue summary
I use pre-trained model to classify some image , sometimes get "nan" values.If I retry classification in case of "nan" values one or two times I get correct classification. 

I copy the code to another mac(without GPU), try more than 10 times, it can get the correct classification  steadily.

when i get the "nan" result i find  conv2/3x3_reduce layer output have "nan" data  which different to when i get the right result.  The model i use is googlenet.

.......self.blobs['conv2/3x3_reduce'].data[...]

### my system configuration
Operating system: OS X EI Capitan 10.11.3
Compiler:intel core i5
BLAS:cblas version 1.0.0
Python or MATLAB version (for pycaffe and matcaffe respectively):pycaffe

**Comment by shaibagon** [comment]
Please use the [caffe-users list][1] for usage, installation, or modeling questions, or other requests for help.
You may also post questions on [stackoverflow][3], make sure you tag them with `caffe` tag.  
Do not post such requests to Issues. Doing so interferes with the development of Caffe.

Please read the [guidelines for contributing][2] before submitting this issue.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
 [3]: http://stackoverflow.com/questions/tagged/caffe
