### ISSUE TITLE
Caffe Re-Install, Clean Uninstall and Finding Double Installs

### ISSUE THREAD

**Issue by ArturoDeza** [BVLC/caffe#5275]
What is the proper way to uninstall Caffe, if I want to either permanently uninstall it or reinstall it?

I tried  `$ make clean`,but I am not sure if that worked, because after rebuilding caffe, with different flag modifications, it did not seem to fetch the new updated built version. The other possibility for this happening is that it is looked up a previous caffe install (from about a year ago), that was compiled from another folder. 

How can I find if there is more than one caffe install version available? Would it suffice to just delete the other folder?

**Comment by jasjuang** [comment]
Well, if my pull request https://github.com/BVLC/caffe/pull/3825 is merged it will be easier for you to uninstall

**Comment by shelhamer** [comment]
Fixed by #3825.
