### ISSUE TITLE
Cmake Error while generating solution file in windows

### ISSUE THREAD

**Issue by Prakash19921206** [BVLC/caffe#5280]
followed this tutorial, to add cuda path and libraries 
https://www.youtube.com/watch?v=AN2uXGRvw9E

then i used cmake to generate visual studio sln files
i get the following output
```
Boost version: 1.61.0
Found the following Boost libraries:
  system
  thread
  filesystem
  chrono
  date_time
  atomic
Found gflags  (include: C:/Users/Admin/Desktop/Caffe Build/libraries/include, library: gflags_shared)
CMake Warning at cmake/Modules/FindGlog.cmake:21 (find_package):
  Could not find a configuration file for package "glog" that is compatible
  with requested version "".

  The following configuration files were considered but not accepted:

    C:/Users/Admin/Desktop/Caffe Build/libraries/lib/cmake/glog/glog-config.cmake, version: 0.3.4 (64bit)

Call Stack (most recent call first):
  cmake/External/glog.cmake:8 (find_package)
  cmake/Dependencies.cmake:21 (include)
  CMakeLists.txt:77 (include)


Could NOT find Glog (missing:  GLOG_LIBRARY) 
CMake Error at cmake/ProtoBuf.cmake:6 (find_package):
  Could not find a configuration file for package "Protobuf" that is
  compatible with requested version "".

  The following configuration files were considered but not accepted:

    C:/Users/Admin/Desktop/Caffe Build/libraries/CMake/protobuf-config.cmake, version: 3.1.0 (64bit)

Call Stack (most recent call first):
  cmake/Dependencies.cmake:31 (include)
  CMakeLists.txt:77 (include)


Configuring incomplete, errors occurred!
See also "C:/Users/Admin/Desktop/Caffe Build/CMakeFiles/CMakeOutput.log".
See also "C:/Users/Admin/Desktop/Caffe Build/CMakeFiles/CMakeError.log".
```
note: i also downloaded protobuf (source from github) and pointed its directory yet output/error from cmake is same..
do i have to build protobuf and then point its build directory in cmake ?

### Issue summary

looks like issue is with Glug and protobuf
### Steps to reproduce

i'm attaching build_win.cmd, apart from this file i didn't make any changes.
[build_win.txt](https://github.com/BVLC/caffe/files/771625/build_win.txt)

### Your system configuration
Operating system: Windows 7
Compiler: visual studio 14 2015 (community edition)
CUDA version (if applicable): 8.0
CUDNN version (if applicable): 5
BLAS: 
Python or MATLAB version (for pycaffe and matcaffe respectively): Python

**Comment by Prakash19921206** [comment]
detailed issue posted [here](https://groups.google.com/forum/#!topic/caffe-users/JOQdnYcXd1Y)

**Comment by Surakshaajith** [comment]
I have the same problem

**Comment by shelhamer** [comment]
Closing in preference of the `windows` branch build.
