### ISSUE TITLE
OpenMP Linking Error

### ISSUE THREAD

**Issue by sohamm17** [BVLC/caffe#5281]
I'm using GCC 4.8.5
I've the following error when using make all:
```
[ 90%] Linking CXX executable upgrade_net_proto_text
//usr/lib/x86_64-linux-gnu/libsoxr.so.0: undefined reference to `GOMP_parallel@GOMP_4.0'
collect2: error: ld returned 1 exit status
tools/CMakeFiles/upgrade_net_proto_text.dir/build.make:131: recipe for target 'tools/upgrade_net_proto_text' failed
make[2]: *** [tools/upgrade_net_proto_text] Error 1
```
 Is it an intel problem because I have an intel processor. However, I've not installed related to intel's openmp. I found the following [intel post about gcc 4.9](https://software.intel.com/en-us/articles/gcc-49-openmp-code-cannot-be-linked-with-intel-openmp-runtime)

**Comment by artBoffin** [comment]
Same issue here, using cmake following default instructions:

> [ 81%] Linking CXX shared library ../../lib/libcaffe-nv.so
[ 81%] Built target caffe
Scanning dependencies of target test_net
[ 81%] Building CXX object tools/CMakeFiles/test_net.dir/test_net.cpp.o
[ 82%] Linking CXX executable test_net
[ 82%] Built target test_net
Scanning dependencies of target net_speed_benchmark
[ 83%] Building CXX object tools/CMakeFiles/net_speed_benchmark.dir/net_speed_benchmark.cpp.o
[ 83%] Linking CXX executable net_speed_benchmark
[ 83%] Built target net_speed_benchmark
Scanning dependencies of target finetune_net
[ 83%] Building CXX object tools/CMakeFiles/finetune_net.dir/finetune_net.cpp.o
[ 85%] Linking CXX executable finetune_net
[ 85%] Built target finetune_net
Scanning dependencies of target upgrade_net_proto_text
[ 85%] Building CXX object tools/CMakeFiles/upgrade_net_proto_text.dir/upgrade_net_proto_text.cpp.o
[ 86%] Linking CXX executable upgrade_net_proto_text
//usr/lib/x86_64-linux-gnu/libsoxr.so.0: undefined reference to `GOMP_parallel@GOMP_4.0'
collect2: error: ld returned 1 exit status
tools/CMakeFiles/upgrade_net_proto_text.dir/build.make:134: recipe for target 'tools/upgrade_net_proto_text' failed
make[2]: *** [tools/upgrade_net_proto_text] Error 1
CMakeFiles/Makefile2:549: recipe for target 'tools/CMakeFiles/upgrade_net_proto_text.dir/all' failed
make[1]: *** [tools/CMakeFiles/upgrade_net_proto_text.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by shelhamer** [comment]
Try the Makefile build instead—CMake can pull in weird dependencies.

**Comment by fbadaud** [comment]
hello , I faced exactly the same issue as artBoffin today and by adding -fopenmp to the line 50  for CMAKE_CXX_FLAGS of the CMakeLists.txt and then use the Cmake .. and make all , I finally succeeded in compiling (still without reference to anaconda installation).I  hope it will help next user.

**Comment by juiceboxjoe** [comment]
@fbadaud 
> adding -fopenmp to the line 50 for CMAKE_CXX_FLAGS of the CMakeLists.txt and then use the Cmake .. and make all.

Worked like a charm!
