### ISSUE TITLE
In a convolutional neural network, a conv layer's multiplication calculation is higher than 2 orders of magnitude than the fully connected layer. but print the GPU calculation time of each layers , find the conv layer's run time is  also less more than fully connected layer , why?

### ISSUE THREAD

**Issue by so-as** [BVLC/caffe#5291]
Please use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) for usage, installation, or modeling questions, or other requests for help.
_Do not post such requests to Issues._ Doing so interferes with the development of Caffe.

Please read the [guidelines for contributing](https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md) before submitting this issue.

### Steps to reproduce

If you are having difficulty building Caffe or training a model, please ask the caffe-users mailing list. If you are reporting a build error that seems to be due to a bug in Caffe, please attach your build configuration (either Makefile.config or CMakeCache.txt) and the output of the make (or cmake) command.

### Your system configuration
Operating system:
Compiler:
CUDA version (if applicable):
CUDNN version (if applicable):
BLAS:
Python or MATLAB version (for pycaffe and matcaffe respectively):

**Comment by williford** [comment]
Please make the title shorter and put the details in the body of the comment (replacing the default / template text). You also need to give a complete example that can be used for reproduction. Without this, you issue will be closed.
