### ISSUE TITLE
Issues with 'make runtest' for Caffe + cuDNN v4

### ISSUE THREAD

**Issue by passion-creativity-enthusiasm** [BVLC/caffe#5292]
### Issue summary
Hi all,

I am building caffe with cuDNN and I could compile successfully. However when I try doing 'make runtest', I encountered this problem:

**SoftmaxWithLossLayerTest/3.TestForwardIgnoreLabel
F0216 16:31:25.835396  2116 cudnn_softmax_layer.cpp:15] Check failed: status == CUDNN_STATUS_SUCCESS (6 vs. 0)  CUDNN_STATUS_ARCH_MISMATCH**

![caffe cudnn problem](https://cloud.githubusercontent.com/assets/6077015/23013637/716d33c8-f466-11e6-998d-575ec98d6eeb.png)

May I ask what I could do to resolve this issue? My system parameters are found below. Thank you all for your help!

### Your system configuration
Operating system: Ubuntu 14.04
Compiler: gcc 4.8.4
CUDA version (if applicable): Cuda Toolkit 7.0
CUDNN version (if applicable): 4
BLAS: ATLAS
Python or MATLAB version (for pycaffe and matcaffe respectively): pycaffe

**Comment by shelhamer** [comment]
Please ask installation questions on the mailing list. Your Caffe was most likely compiled for the wrong GPU arch.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
