### ISSUE TITLE
how to design a simple net?

### ISSUE THREAD

**Issue by micklexqg** [BVLC/caffe#5293]
Hi,
In MNIST examples. the net is lenet.
I want to know that how to design a simple net with only a single conv layer?
and must the kernel size in last layer be 1*1?
sorry for a dump question, any help appreciated.

**Comment by williford** [comment]
Please ask your question on the [Caffe user mailing list](https://groups.google.com/forum/#!forum/caffe-users) or on another website, such as http://stackoverflow.com/.

> Please use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) for usage, installation, or modeling questions, or other requests for help.
> _Do not post such requests to Issues._ Doing so interferes with the development of Caffe.
