### ISSUE TITLE
Windows 7 + gtx 1080 + cudnn 5 - strange behavior 

### ISSUE THREAD

**Issue by roipony** [BVLC/caffe#5298]
Hello,
I having gtx 1080 , cuda8 , cudnn5. I compiled caffe on windows and I getting strange behavior during simple training (mnist), the net is not converging. When I compiled without cudnn everything is normal.
Anyone know the problem and how to deal with it?
Thanks

**Comment by shelhamer** [comment]
Closing as likely hardware/driver/Windows incompatibility issue.
