### ISSUE TITLE
Problems in installing Caffe

### ISSUE THREAD

**Issue by fh985** [BVLC/caffe#5301]
Please use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) for usage, installation, or modeling questions, or other requests for help.
_Do not post such requests to Issues._ Doing so interferes with the development of Caffe.

Please read the [guidelines for contributing](https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md) before submitting this issue.

### Issue summary
CXX .build_release/src/caffe/proto/caffe.pb.cc
AR -o .build_release/lib/libcaffe.a
LD -o .build_release/lib/libcaffe.so.1.0.0-rc3
CXX/LD -o .build_release/tools/caffe.bin
CXX/LD -o .build_release/tools/extract_features.bin
/usr/bin/ld: warning: libIlmImf.so.6, needed by /usr/local/lib/libopencv_imgcodecs.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libHalf.so.6, needed by /usr/local/lib/libopencv_imgcodecs.so, not found (try using -rpath or -rpath-link)
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `Imf::hasChromaticities(Imf::Header const&)'
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `Imf::Chromaticities::Chromaticities(Imath::Vec2<float> const&, Imath::Vec2<float> const&, Imath::Vec2<float> const&, Imath::Vec2<float> const&)'
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `Imf::ChannelList::insert(char const*, Imf::Channel const&)'
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `Imf::globalThreadCount()'
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `Imf::chromaticities(Imf::Header const&)'
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `Imf::OutputFile::setFrameBuffer(Imf::FrameBuffer const&)'
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `Imf::InputFile::header() const'
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `Imf::InputFile::InputFile(char const*, int)'
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `Imf::OutputFile::~OutputFile()'
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `Imf::InputFile::setFrameBuffer(Imf::FrameBuffer const&)'
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `Imf::Header::channels() const'
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `Imf::Header::channels()'
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `Imf::Header::~Header()'
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `Imf::OutputFile::OutputFile(char const*, Imf::Header const&, int)'
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `Imf::Header::Header(int, int, float, Imath::Vec2<float> const&, float, Imf::LineOrder, Imf::Compression)'
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `Imf::OutputFile::writePixels(int)'
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `Imf::Header::dataWindow() const'
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `Imf::Channel::Channel(Imf::PixelType, int, int, bool)'
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `Imf::Slice::Slice(Imf::PixelType, char*, unsigned long, unsigned long, int, int, double, bool, bool)'
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `Imf::ChannelList::findChannel(char const*) const'
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `Imf::InputFile::readPixels(int, int)'
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `Imf::FrameBuffer::insert(char const*, Imf::Slice const&)'
collect2: error: ld returned 1 exit status
Makefile:627: recipe for target '.build_release/tools/extract_features.bin' failed
make: *** [.build_release/tools/extract_features.bin] Error 1
make: *** Waiting for unfinished jobs....
/usr/bin/ld: warning: libIlmImf.so.6, needed by /usr/local/lib/libopencv_imgcodecs.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libHalf.so.6, needed by /usr/local/lib/libopencv_imgcodecs.so, not found (try using -rpath or -rpath-link)
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `Imf::hasChromaticities(Imf::Header const&)'
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `Imf::Chromaticities::Chromaticities(Imath::Vec2<float> const&, Imath::Vec2<float> const&, Imath::Vec2<float> const&, Imath::Vec2<float> const&)'
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `Imf::ChannelList::insert(char const*, Imf::Channel const&)'
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `Imf::globalThreadCount()'
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `Imf::chromaticities(Imf::Header const&)'
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `Imf::OutputFile::setFrameBuffer(Imf::FrameBuffer const&)'
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `Imf::InputFile::header() const'
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `Imf::InputFile::InputFile(char const*, int)'
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `Imf::OutputFile::~OutputFile()'
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `Imf::InputFile::setFrameBuffer(Imf::FrameBuffer const&)'
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `Imf::Header::channels() const'
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `Imf::Header::channels()'
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `Imf::Header::~Header()'
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `Imf::OutputFile::OutputFile(char const*, Imf::Header const&, int)'
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `Imf::Header::Header(int, int, float, Imath::Vec2<float> const&, float, Imf::LineOrder, Imf::Compression)'
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `Imf::OutputFile::writePixels(int)'
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `Imf::Header::dataWindow() const'
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `Imf::Channel::Channel(Imf::PixelType, int, int, bool)'
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `Imf::Slice::Slice(Imf::PixelType, char*, unsigned long, unsigned long, int, int, double, bool, bool)'
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `Imf::ChannelList::findChannel(char const*) const'
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `Imf::InputFile::readPixels(int, int)'
/usr/local/lib/libopencv_imgcodecs.so: undefined reference to `Imf::FrameBuffer::insert(char const*, Imf::Slice const&)'
collect2: error: ld returned 1 exit status
Makefile:627: recipe for target '.build_release/tools/caffe.bin' failed
make: *** [.build_release/tools/caffe.bin] Error 1

### Steps to reproduce

If you are having difficulty building Caffe or training a model, please ask the caffe-users mailing list. If you are reporting a build error that seems to be due to a bug in Caffe, please attach your build configuration (either Makefile.config or CMakeCache.txt) and the output of the make (or cmake) command.

### Your system configuration
Operating system: Ubuntu 16.04
Compiler: make
CUDA version (if applicable): no CUDA
CUDNN version (if applicable):
BLAS: ATLAS
Python or MATLAB version (for pycaffe and matcaffe respectively):

**Comment by shelhamer** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
