### ISSUE TITLE
a pb error,what'is meaning? gcc verrsion?

### ISSUE THREAD

**Issue by Ambier** [BVLC/caffe#5304]
/home/zulong.czl/caffe-master/build/include/caffe/proto/caffe.pb.cc: In member function ‘virtual bool caffe::BlobShape::MergePartialFromCodedStream(google::p
rotobuf::io::CodedInputStream*)’:
/home/zulong.czl/caffe-master/build/include/caffe/proto/caffe.pb.cc:2918:24: error: expected ‘<’ before ‘<:’ token
         if (static_cast<::google::protobuf::uint8>(tag) ==
                        ^
/home/zulong.czl/caffe-master/build/include/caffe/proto/caffe.pb.cc:2918:24: error: expected type-specifier before ‘<:’ token
/home/zulong.czl/caffe-master/build/include/caffe/proto/caffe.pb.cc:2918:24: error: expected ‘>’ before ‘<:’ token
/home/zulong.czl/caffe-master/build/include/caffe/proto/caffe.pb.cc:2918:24: error: expected ‘(’ before ‘<:’ token
/home/zulong.czl/caffe-master/build/include/caffe/proto/caffe.pb.cc:2918:26: error: expected identifier before ‘:’ token
         if (static_cast<::google::protobuf::uint8>(tag) ==
                          ^
/home/zulong.czl/caffe-master/build/include/caffe/proto/caffe.pb.cc:2919:58: error: expected ‘]’ before ‘{’ token
             static_cast<::google::protobuf::uint8>(10u)) {

**Comment by zeakey** [comment]
Please post your `gcc` version and `proto compiler` version.

**Comment by orzyt** [comment]
@zeakey hi, zeakey. I also occur this error and post my config below, could you give me some suggestion? thx  :)
- Ubuntu version: 16.04
- gcc version: 5.4.0
- protobuf version: 3.2.0
- caffe config: [caffe config](https://github.com/BVLC/caffe/files/809724/caffe.config.txt)
- error message: [caffe.pb.o.warnings](https://github.com/BVLC/caffe/files/809836/caffe.pb.o.warnings.txt)
