### ISSUE TITLE
/home/zulong.czl/caffe-master/build/include/caffe/proto/caffe.pb.cc:2918:24: error

### ISSUE THREAD

**Issue by Ambier** [BVLC/caffe#5305]
Please use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) for usage, installation, or modeling questions, or other requests for help.
_Do not post such requests to Issues._ Doing so interferes with the development of Caffe.

Please read the [guidelines for contributing](https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md) before submitting this issue.

### Issue summary
/home/zulong.czl/caffe-master/build/include/caffe/proto/caffe.pb.cc: In member function ‘virtual bool caffe::BlobShape::MergePartialFromCodedStream(google::p
rotobuf::io::CodedInputStream*)’:
/home/zulong.czl/caffe-master/build/include/caffe/proto/caffe.pb.cc:2918:24: error: expected ‘<’ before ‘<:’ token
         if (static_cast<::google::protobuf::uint8>(tag) ==
                        ^
/home/zulong.czl/caffe-master/build/include/caffe/proto/caffe.pb.cc:2918:24: error: expected type-specifier before ‘<:’ token
/home/zulong.czl/caffe-master/build/include/caffe/proto/caffe.pb.cc:2918:24: error: expected ‘>’ before ‘<:’ token
/home/zulong.czl/caffe-master/build/include/caffe/proto/caffe.pb.cc:2918:24: error: expected ‘(’ before ‘<:’ token
/home/zulong.czl/caffe-master/build/include/caffe/proto/caffe.pb.cc:2918:26: error: expected identifier before ‘:’ token
         if (static_cast<::google::protobuf::uint8>(tag) ==
                          ^
/home/zulong.czl/caffe-master/build/include/caffe/proto/caffe.pb.cc:2919:58: error: expected ‘]’ before ‘{’ token
             static_cast<::google::protobuf::uint8>(10u)) {
                                                          ^
In file included from /usr/local/include/google/protobuf/stubs/common.h:40:0,
                 from /home/zulong.czl/caffe-master/build/include/caffe/proto/caffe.pb.h:9,
                 from /home/zulong.czl/caffe-master/build/include/caffe/proto/caffe.pb.cc:5:
/home/zulong.czl/caffe-master/build/include/caffe/proto/caffe.pb.cc: In lambda function:
/home/zulong.czl/caffe-master/build/include/caffe/proto/caffe.pb.cc:2922:18: error: ‘input’ is not captured
                  input, this->mutable_dim())));
                  ^
/home/zulong.czl/caffe-master/build/include/caffe/proto/caffe.pb.cc:2920:11: note: in expansion of macro ‘DO_’
           DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
           ^
/home/zulong.czl/caffe-master/build/include/caffe/proto/caffe.pb.cc:2922:25: error: ‘this’ was not captured for this lambda function
                  input, this->mutable_dim())));
                         ^
/home/zulong.czl/caffe-master/build/include/caffe/proto/caffe.pb.cc:2920:11: note: in expansion of macro ‘DO_’
           DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
           ^
/home/zulong.czl/caffe-master/build/include/caffe/proto/caffe.pb.cc:2908:68: error: label ‘failure’ used but not defined
 #define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
                                                                    ^
/home/zulong.czl/caffe-master/build/include/caffe/proto/caffe.pb.cc:2920:11: note: in expansion of macro ‘DO_’
           DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<

### Steps to reproduce

If you are having difficulty building Caffe or training a model, please ask the caffe-users mailing list. If you are reporting a build error that seems to be due to a bug in Caffe, please attach your build configuration (either Makefile.config or CMakeCache.txt) and the output of the make (or cmake) command.

### Your system configuration
Operating system:rehat
Compiler:
CUDA version (if applicable):
CUDNN version (if applicable):
BLAS:Atlas
Python or MATLAB version (for pycaffe and matcaffe respectively):

**Comment by shelhamer** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
