### ISSUE TITLE
Caffe Compilation error

### ISSUE THREAD

**Issue by pnambiar** [BVLC/caffe#5308]
I think I pretty much followed all the instructions on:
https://github.com/BVLC/caffe/wiki/Ubuntu-16.04-or-15.10-Installation-Guide.

I still get the error:

/usr/bin/ld: cannot find -lopenblas
collect2: error: ld returned 1 exit status
Makefile:567: recipe for target '.build_release/lib/libcaffe.so.1.0.0-rc3' failed
make: *** [.build_release/lib/libcaffe.so.1.0.0-rc3] Error

Any leads will be appreciated

-P

Please use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) for usage, installation, or modeling questions, or other requests for help.
_Do not post such requests to Issues._ Doing so interferes with the development of Caffe.

Please read the [guidelines for contributing](https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md) before submitting this issue.

### Steps to reproduce

If you are having difficulty building Caffe or training a model, please ask the caffe-users mailing list. If you are reporting a build error that seems to be due to a bug in Caffe, please attach your build configuration (either Makefile.config or CMakeCache.txt) and the output of the make (or cmake) command.

### Your system configuration
Operating system:
Compiler:
CUDA version (if applicable):
CUDNN version (if applicable):
BLAS:
Python or MATLAB version (for pycaffe and matcaffe respectively):

**Comment by wadefelix** [comment]
> /usr/bin/ld: cannot find -lopenblas
Did you `apt-get install libopenblas-base libopenblas-dev ` ?

**Comment by pnambiar** [comment]
Thanks that helped!

**Comment by shelhamer** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

**Comment by Suraj59** [comment]
make clean
make all
![screenshot from 2017-09-04 17-41-59](https://user-images.githubusercontent.com/11031352/30025996-abc06b56-9198-11e7-9130-6705be26b9ca.png)

AR -o .build_release/lib/libcaffe.a
LD -o .build_release/lib/libcaffe.so.1.0.0
/usr/bin/ld: cannot find -l -llmdb
collect2: error: ld returned 1 exit status
Makefile:575: recipe for target '.build_release/lib/libcaffe.so.1.0.0' failed
make: *** [.build_release/lib/libcaffe.so.1.0.0] Error 1
any one have solution thank you

**Comment by irsyadtc** [comment]
This provide the answer for /usr/bin/ld: cannot find -l -llmdb
[https://github.com/BVLC/caffe/wiki/Commonly-encountered-build-issues](url)
