### ISSUE TITLE
caffe Prebuilt binaries errors

### ISSUE THREAD

**Issue by aligoglos** [BVLC/caffe#5309]
favorite
i download caffe prebuilt binaries from : https://github.com/BVLC/caffe/tree/windows

create project property sheet for add caffe in my project :

AdditionalIncludeDirectories = D:\caffe_2\include;
AdditionalLibraryDirectories = D:\caffe_2\lib;
AdditionalDependencies = caffe.lib;proto.lib;
and write simple code to test caffe like this :

#include <caffe/caffe.hpp>

using namespace caffe;

void main() {
    Caffe::set_mode(Caffe::Brew::CPU);
}
but when i want build project a lot of error occur:

![image](https://cloud.githubusercontent.com/assets/3922472/23126510/1d02667c-f78c-11e6-9e8a-650eb8eda1b0.png)

Operating system: windows 10

visual studio: 2015 update3

CUDA version (if applicable): 8.0

CUDNN version (if applicable): 8.0

Python version :2.7, 3.5, 3.6

**Comment by willyd** [comment]
You will need to download the right dependencies. From caffe-builder releases page: https://github.com/willyd/caffe-builder/releases/tag/v1.0.1

**Comment by aligoglos** [comment]
hi i download dependencies and add to my project now this errors appears :
[image: Inline image 1]

i install cuda 8.0 but i don't why this errors occurred?
>
> my cuda in cmd :
[image: Inline image 2]

thanks.

**Comment by willyd** [comment]
You need to add the CUDA include directories or use the CUDA build customization. Please read the CUDA documentation.

Please use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) for usage, installation, or modeling questions, or other requests for help.
_Do not post such requests to Issues._ Doing so interferes with the development of Caffe.
