### ISSUE TITLE
Undefined function 'caffe_' for input arguments of type 'char'.

### ISSUE THREAD

**Issue by wenmingli** [BVLC/caffe#5314]
When I use matlab+caffe to run the extractDeepFeature.m ,this is the error:

Undefined function 'caffe_' for input arguments of type 'char'.

Error in caffe.reset_all (line 5)
caffe_('reset');

Error in extractDeepFeature (line 3)
caffe.reset_all();

I have add the path('matlab')

### Your system configuration
Operating system:Ubuntu 14.04
Compiler: gcc version 4.7.3
CUDA version (if applicable):
CUDNN version (if applicable):
BLAS:
Python or MATLAB version (for pycaffe and matcaffe respectively):matcaffe
Thanks!

**Comment by tejaswikasarla** [comment]
You have to add this path in matlab: ```addpath('/path/to/caffe/matlab')```

**Comment by ckun5** [comment]
I also met this. I solved it by compiling matcaffe:  make all matcaffe
