### ISSUE TITLE
python interface to do classifycation is much lower than 'digits classify many' accuracy

### ISSUE THREAD

**Issue by c437yuyang** [BVLC/caffe#5316]
### Issue summary
my dataset is 8classes,and when i use digits or commond line to train the net,i got a very nice result.
(sorry guys,i am not familiar with how to use github.i dont know how to upload a image),in total,the train-accuracy and val-accuracy are both about 96%,and then i use classifymany function in digits to do classification with my val data,it can also get a accuracy near to 96%. 
But when i use python interface (and i have tried classification.bin got the same results) to do classify with the same data,it can only get about 70% accuracy.
and i'm sure the image pre-processing is correct(i copyed the deploy.txt from digits jobs,and the image size,meanfile are all the same as i used in train step).Is there any one can help me...thank you very much!

### Your system configuration
Operating system:ubuntu14.04
Compiler:
CUDA version (if applicable):7.5
CUDNN version (if applicable):v5
BLAS:
Python or MATLAB version (for pycaffe and matcaffe respectively):
pycaffe

**Comment by PENGUINLIONG** [comment]
Did you read images with caffe's image reading methods? If you read them with PIL, the order of dimensions should be adjusted. You might also need to make sure the order of color channels are the same. incase RGB channels are passed in BGR nets.

**Comment by c437yuyang** [comment]
@PENGUINLIONG Thankyou，but im sure the image reading methods are right,because when i use the other dataset it could work correctly. only when i use this dataset it would occur this problem

**Comment by shelhamer** [comment]
Please ask usage questions on the mailing list. As mentioned, having the same deploy net is not enough as the pre-processing varies with the choice of library and interface such as Pillow vs. OpenCV or C++ vs. Python.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
