### ISSUE TITLE
Python module shouldn't force logging to stderr

### ISSUE THREAD

**Issue by ferrouswheel** [BVLC/caffe#5317]
The fix in 2317fa1 attempts to provide a method to make sure the Google logging module can be initialised.

This change partially fixed #4715, but `init_log` forces logging to stderr. Instead of assuming what the user wants, it should respect the GLOG environment variables if they are set.

**Comment by shelhamer** [comment]
This is a totally reasonable request. @cypof do you think you could improve the behavior?

**Comment by shelhamer** [comment]
Mostly fixed by #5515 which allows pycaffe to set the logging level although it does not respect the env vars automatically.

**Comment by cypof** [comment]
The env vars work too, if python doesn't set the value glog uses the env var.

**Comment by ferrouswheel** [comment]
Sweet - thanks!
