### ISSUE TITLE
E0222 19:19:30.967144  1133 common.cpp:115] Cannot create Cublas handle. Cublas won't be available. E0222 19:19:31.521263  1133 common.cpp:122] Cannot create Curand generator. Curand won't be available. F0222 19:19:32.073035  1133 benchmark.cpp:112] Check failed: error == cudaSuccess (2 vs. 0)  out of memory

### ISSUE THREAD

**Issue by Ambier** [BVLC/caffe#5319]
Please use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) for usage, installation, or modeling questions, or other requests for help.
_Do not post such requests to Issues._ Doing so interferes with the development of Caffe.

Please read the [guidelines for contributing](https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md) before submitting this issue.

### Issue summary

I0222 19:19:30.400809  1133 caffe.cpp:218] Using GPUs 0
I0222 19:19:30.408557  1133 caffe.cpp:223] GPU 0: Tesla M40
E0222 19:19:30.967144  1133 common.cpp:115] Cannot create Cublas handle. Cublas won't be available.
E0222 19:19:31.521263  1133 common.cpp:122] Cannot create Curand generator. Curand won't be available.
F0222 19:19:32.073035  1133 benchmark.cpp:112] Check failed: error == cudaSuccess (2 vs. 0)  out of memory
### Steps to reproduce

If you are having difficulty building Caffe or training a model, please ask the caffe-users mailing list. If you are reporting a build error that seems to be due to a bug in Caffe, please attach your build configuration (either Makefile.config or CMakeCache.txt) and the output of the make (or cmake) command.

### Your system configuration
Operating system:red hat 6.5
Compiler: cmake 3.5
CUDA version (if applicable):
CUDNN version (if applicable):
BLAS:
Python or MATLAB version (for pycaffe and matcaffe respectively):
i have installed caffe successfuly,and run many examples.but today,i encounter a mistake,what should i do?

**Comment by shelhamer** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
