### ISSUE TITLE
caffe python3.5 no attribute available, I'm crazy now!!!

### ISSUE THREAD

**Issue by chibai** [BVLC/caffe#5322]
I compiled caffe with python3.5 on Ubuntu 16.04 successfully
import caffe without any error
but the problem is, there're no attributes in caffe
when I import caffe.io or caffe.proto
there's no module called caffe.io or caffe.proto

I press TAB after caffe, only default attributes showed up, like _doc_,  _nane_,  _package_ and so on
Anyone met the same problem as me???
I guess I can not have a comfortable weekend

**Comment by chibai** [comment]
When I do pytest, the program automatically use python2.7, but I configured the makefile.config to python 3.5, and I import caffe successfully......

**Comment by JobJob** [comment]
Were you possibly in a directory which had a child directory called caffe?

**Comment by shelhamer** [comment]
Closing as a Python environment issue. Please ask usage and installation questions on the mailing list.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
