### ISSUE TITLE
mac cannot draw net (pydot installed)

### ISSUE THREAD

**Issue by ToTheBeginning** [BVLC/caffe#5324]
File "/Users/wyz/caffe/python/caffe/draw.py", line 107, in get_layer_label
    layer.pooling_param.kernel_size[0] if len(layer.pooling_param.kernel_size._values) else 1,
AttributeError: 'int' object has no attribute '_values'

Can anyone help me ?

**Comment by ToTheBeginning** [comment]
Problem solved. It seems that the latest version of 'draw.py' has some BUGS , and when change it to the previous version , finally i can draw net.

**Comment by NoneLand** [comment]
Thanks! I met the same problem.

**Comment by Zyj061** [comment]
Thanks!

**Comment by eejackliu** [comment]
Same problem, solved by change  it to the previous version

**Comment by reena96** [comment]
Kindly please tell me how you changed it to the previous version?

**Comment by eejackliu** [comment]
just use the previous version of draw.py instead of it

**Comment by jeasinema** [comment]
Could you please tell me the relative link about the right version of "previous version"?

**Comment by ToTheBeginning** [comment]
@reena96 @jeasinema [link](https://github.com/BVLC/caffe/commit/db6cf0a728cad63c93b345f2203f3ad1f5d5c2f4) ,in the left

**Comment by WangKai9608** [comment]
Could anyone please teach me how to change it to the previous version?

**Comment by NoneLand** [comment]
[release](https://github.com/BVLC/caffe/releases)

**Comment by wanger-02** [comment]
I find this file is created while build the project. but i did'nt compile the previous edtion. anyone please teach me to solue it?
