### ISSUE TITLE
How I can delete some convolution filters from one layer in pre-trained deep architecture

### ISSUE THREAD

**Issue by BBAUniversity** [BVLC/caffe#5326]
How I can delete some convolution filters from one layer in pre-trained deep architecture

**Comment by shelhamer** [comment]
Define the new net with fewer channels, and then transplant the weights you want into it from the old net. See the net surgery example on the homepage for the relevant techniques.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
