### ISSUE TITLE
How to make a image pose estimation network

### ISSUE THREAD

**Issue by thuanvh** [BVLC/caffe#533]
Hi all,
I am trying to use caffe to estimage the pose points of an image.
Input data is an image and label is a list of points (x,y) coordinate.
Could I model it by using caffe? and How do I ?

**Comment by zirohut** [comment]
Does the label go like

.jpg  x1_coordinate  y1_coordinate  x2_coordinate  y2_coordinate

in the train.txt?

And may I ask how did you convert those data into hdf5 files? Will it work with lmdb?

Thanks !
