### ISSUE TITLE
Numerical instability on GTX 1060

### ISSUE THREAD

**Issue by kostaskk** [BVLC/caffe#5332]
### Issue summary
Hi All,

I'm training fcn8s-at-once on my own dataset using the pre-learned weights.

While my model runs fine(training) on GPU AWS g2.2x instances OR on my local machine on CPU-only mode, the weights and loss are turning to NaN after a few iterations when running exactly the same code on my GTX 1060 GPU. I have tried lowering the learning rate further and it only runs on my own GPU setup if it's low enough so that the model stops learning (1e-15). I've also tried a few different driver, cuda and cudnn configurations but nothing seems to work. 

Please help! 

btw. I've also tried using the docker version of caffe but the same things happens.

### Steps to reproduce

These are the setups I've tried so far:

**Amazon - GPU training works**

Cuda compilation tools, release 7.5, V7.5.17
Cudnn 4.0.7
Nvidia Driver Version: 352.93

**Own setup 1 - doesn't work in GPU (works for CPU)**

Cuda compilation tools, release 8.0, V8.0.61
Cudnn 5.0.5
Nvidia Driver:378.13
Python 2.7.13 :: Anaconda custom (64-bit)

**Own setup 2 - doesn't work in GPU (works for CPU)**

Cuda compilation tools, release 8.0, V8.0.61
Cudnn 5.1.10
Driver Version: 375.26
Python 2.7.12

### Your system configuration

See above. Additional details:
Operating system: Ubuntu 16.04.2 LTS
BLAS: openblas and atlas tried

**Comment by shelhamer** [comment]
This might be a case of bad hardware or compiling the wrong GPU arch. The GTX 1060 has compute capability 6.1, so have you built with that arch? https://github.com/BVLC/caffe/blob/master/Makefile.config.example#L43-L44

Closing as a downstream issue, as Caffe has been tested on 6.1 hardware including the GTX 1080 and Pascal Titan X.
