### ISSUE TITLE
"make matcaffe" results in OpenCV error

### ISSUE THREAD

**Issue by SETANDGET** [BVLC/caffe#5335]
![Uploading IMG_1079.JPG…]()
## when i do "make matcaffe"...
how can i  resolve it??#

**Comment by SETANDGET** [comment]
**`src/caffe/layers/window_data_layer.cpp:26:11: error: ‘const int CV_LOAD_IMAGE_COLOR’ redeclared as different kind of symbol
 const int CV_LOAD_IMAGE_COLOR = cv::IMREAD_COLOR;
           ^
In file included from /usr/local/include/opencv2/highgui/highgui_c.h:47:0,
                 from /usr/local/include/opencv2/highgui.hpp:701,
                 from /usr/local/include/opencv2/highgui/highgui.hpp:48,
                 from src/caffe/layers/window_data_layer.cpp:10:
/usr/local/include/opencv2/imgcodecs/imgcodecs_c.h:62:5: error: previous declaration of ‘<anonymous enum> CV_LOAD_IMAGE_COLOR’
     CV_LOAD_IMAGE_COLOR      =1,
     **^**
`**

**Comment by shelhamer** [comment]
Please ask installation questions on the mailing list. You have multiple, incompatible versions of OpenCV.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
