### ISSUE TITLE
Anyone Encounter this problem？ plot loss curve ？

### ISSUE THREAD

**Issue by joyivan** [BVLC/caffe#5336]
when I 

> sudo ./parse_log.sh log-data.log 

the result is 
````

> raceback (most recent call last):
>   File "/home/joyivan/py-faster-rcnn/experiments/logs/extract_seconds.py", line 64, in <module>
>     extract_seconds(sys.argv[1], sys.argv[2])
>   File "/home/joyivan/py-faster-rcnn/experiments/logs/extract_seconds.py", line 49, in extract_seconds
>     assert start_datetime, 'Start time not found'
> AssertionError: Start time not found
> paste: aux4.txt: No such file or directory
> rm: cannot remove 'aux4.txt': No such file or directory
> Traceback (most recent call last):
>   File "/home/joyivan/py-faster-rcnn/experiments/logs/extract_seconds.py", line 64, in <module>
>     extract_seconds(sys.argv[1], sys.argv[2])
>   File "/home/joyivan/py-faster-rcnn/experiments/logs/extract_seconds.py", line 49, in extract_seconds
>     assert start_datetime, 'Start time not found'
> AssertionError: Start time not found
> paste: aux3.txt: No such file or directory
> rm: cannot remove 'aux3.txt': No such file or directory

```
`
anybody can answer me ?

thanks

**Comment by shelhamer** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

**Comment by whitewalker007** [comment]
Hey joyivan, did you able to solve the above posted issue? If yes, do enlighten me too on 'how'. Thanks in advance.

**Comment by joyivan** [comment]
@whitewalker007 I didn't use the original code of the project from GitHub  to plot the loss curve. I code it my self, after your read the log file, U can use 'cat' and 'awk' to analysis in the shell ,and plot the curve. There are lots of e.g. in Google .

**Comment by 714586886** [comment]
I get the same error!
I really want to know how to fix it!

**Comment by larklili** [comment]
Have you solved yet?I have the same problem

**Comment by Zoey321** [comment]
I solved this problem by changing the permission by:
chmod 777 extract_seconds.py 
chmod 777 parse_log.sh
