### ISSUE TITLE
issue with build_win.cmd

### ISSUE THREAD

**Issue by satishknl** [BVLC/caffe#5338]
Followed the below link to install Caffe 
https://github.com/BVLC/caffe/tree/windows

### Issue summary
Imported targets not available for Boost version

### Output:

C:\Users\zenlab\caffe\scripts>build_win.cmd
The system cannot find the drive specified.
INFO: ============================================================
INFO: Summary:
INFO: ============================================================
INFO: MSVC_VERSION               = 14
INFO: WITH_NINJA                 = 1
INFO: CMAKE_GENERATOR            = "Ninja"
INFO: CPU_ONLY                   = 0
INFO: CMAKE_CONFIG               = Release
INFO: USE_NCCL                   = 0
INFO: CMAKE_BUILD_SHARED_LIBS    = 0
INFO: PYTHON_VERSION             = 2
INFO: BUILD_PYTHON               = 1
INFO: BUILD_PYTHON_LAYER         = 1
INFO: BUILD_MATLAB               = 0
INFO: PYTHON_EXE                 = "python"
INFO: RUN_TESTS                  = 0
INFO: RUN_LINT                   = 0
INFO: RUN_INSTALL                = 0
INFO: ============================================================
CMake Warning at C:/Program Files/CMake/share/cmake-3.8/Modules/FindBoost.cmake:
761 (message):
  Imported targets not available for Boost version
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.8/Modules/FindBoost.cmake:865 (_Boost_COM
PONENT_DEPENDENCIES)
  C:/Program Files/CMake/share/cmake-3.8/Modules/FindBoost.cmake:1456 (_Boost_MI
SSING_DEPENDENCIES)
  cmake/Dependencies.cmake:5 (find_package)
  CMakeLists.txt:78 (include)

CMake Warning at C:/Program Files/CMake/share/cmake-3.8/Modules/FindBoost.cmake:
761 (message):
  Imported targets not available for Boost version
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.8/Modules/FindBoost.cmake:865 (_Boost_COM
PONENT_DEPENDENCIES)
  C:/Program Files/CMake/share/cmake-3.8/Modules/FindBoost.cmake:1456 (_Boost_MI
SSING_DEPENDENCIES)
  cmake/Dependencies.cmake:5 (find_package)
  CMakeLists.txt:78 (include)

CMake Warning at C:/Program Files/CMake/share/cmake-3.8/Modules/FindBoost.cmake:
761 (message):
  Imported targets not available for Boost version
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.8/Modules/FindBoost.cmake:865 (_Boost_COM
PONENT_DEPENDENCIES)
  C:/Program Files/CMake/share/cmake-3.8/Modules/FindBoost.cmake:1456 (_Boost_MI
SSING_DEPENDENCIES)
  cmake/Dependencies.cmake:5 (find_package)
  CMakeLists.txt:78 (include)

CMake Error at C:/Program Files/CMake/share/cmake-3.8/Modules/FindBoost.cmake:18
12 (message):
  Unable to find the requested Boost libraries.

  Unable to find the Boost header files.  Please set BOOST_ROOT to the root
  directory containing Boost or BOOST_INCLUDEDIR to the directory containing
  Boost's headers.
Call Stack (most recent call first):
  cmake/Dependencies.cmake:5 (find_package)
  CMakeLists.txt:78 (include)

-- Could NOT find GFlags (missing:  GFLAGS_INCLUDE_DIR GFLAGS_LIBRARY)
-- Could NOT find Glog (missing:  GLOG_INCLUDE_DIR GLOG_LIBRARY)
-- Found PROTOBUF Compiler: C:/Anaconda/Library/bin/protoc.exe
CMake Error at C:/Program Files/CMake/share/cmake-3.8/Modules/FindPackageHandleS
tandardArgs.cmake:137 (message):
  Could NOT find LMDB (missing: LMDB_INCLUDE_DIR LMDB_LIBRARIES)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.8/Modules/FindPackageHandleStandardArgs.c
make:377 (_FPHSA_FAILURE_MESSAGE)
  cmake/Modules/FindLMDB.cmake:23 (find_package_handle_standard_args)
  cmake/Dependencies.cmake:50 (find_package)
  CMakeLists.txt:78 (include)

CMake Error: The following variables are used in this project, but they are set
to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake file
s:
Boost_INCLUDE_DIR (ADVANCED)
   used as include directory in directory C:/Users/zenlab/caffe
   used as include directory in directory C:/Users/zenlab/caffe
   used as include directory in directory C:/Users/zenlab/caffe
   used as include directory in directory C:/Users/zenlab/caffe

-- Configuring incomplete, errors occurred!
See also "C:/Users/zenlab/caffe/scripts/build/CMakeFiles/CMakeOutput.log".
ERROR: Configure failed
[CMakeOutput.docx](https://github.com/BVLC/caffe/files/810864/CMakeOutput.docx)

### Your system configuration
Operating system: Windows Server 2012 R2
Compiler:
CUDA version (if applicable): 8
CUDNN version (if applicable): 5
BLAS:
Python or MATLAB version (for pycaffe and matcaffe respectively): Python

**Comment by willyd** [comment]
From your CMake output I see that your detected compiler is gcc. Try this: https://github.com/BVLC/caffe/issues/5248#issuecomment-279226614.

**Comment by satishknl** [comment]
am new to this installation. Please tell me how to change this

Set CMAKE_C_COMPILER=cl.exe and CMAKE_CXX_COMPILER=cl.exe
Use the Visual Studio Generator (WITH_NINJA=0)

**Comment by willyd** [comment]
To use VS instead of Ninja in a cmd command prompt
```
> set WITH_NINJA=0
> scripts\build_win.cmd
```
to use cl instead of gcc replace:
```
cmake -G"!CMAKE_GENERATOR!" ^
      -DBLAS=Open ^
      -DCMAKE_BUILD_TYPE:STRING=%CMAKE_CONFIG% ^
      -DBUILD_SHARED_LIBS:BOOL=%CMAKE_BUILD_SHARED_LIBS% ^
      -DBUILD_python:BOOL=%BUILD_PYTHON% ^
      -DBUILD_python_layer:BOOL=%BUILD_PYTHON_LAYER% ^
      -DBUILD_matlab:BOOL=%BUILD_MATLAB% ^
      -DCPU_ONLY:BOOL=%CPU_ONLY% ^
      -DCOPY_PREREQUISITES:BOOL=1 ^
      -DINSTALL_PREREQUISITES:BOOL=1 ^
      -DUSE_NCCL:BOOL=!USE_NCCL! ^
      "%~dp0\.."
```
with
```
cmake -G"!CMAKE_GENERATOR!" ^
      -DBLAS=Open ^
      -DCMAKE_BUILD_TYPE:STRING=%CMAKE_CONFIG% ^
      -DBUILD_SHARED_LIBS:BOOL=%CMAKE_BUILD_SHARED_LIBS% ^
      -DBUILD_python:BOOL=%BUILD_PYTHON% ^
      -DBUILD_python_layer:BOOL=%BUILD_PYTHON_LAYER% ^
      -DBUILD_matlab:BOOL=%BUILD_MATLAB% ^
      -DCPU_ONLY:BOOL=%CPU_ONLY% ^
      -DCOPY_PREREQUISITES:BOOL=1 ^
      -DINSTALL_PREREQUISITES:BOOL=1 ^
      -DUSE_NCCL:BOOL=!USE_NCCL! ^
      -DCMAKE_C_COMPILER=cl.exe ^
      -DCMAKE_CXX_COMPILER=cl.exe ^
      "%~dp0\.."
```

**Comment by satishknl** [comment]
Willyd....new error

CMake Error: Error: generator : Visual Studio 14 2015 Win64
Does not match the generator used previously: Ninja
Either remove the CMakeCache.txt file and CMakeFiles directory or choose a diffe
rent binary directory.
ERROR: Configure failed

**Comment by willyd** [comment]
Remove the build directory and start over.

**Comment by satishknl** [comment]
Thanks Willyd......it works, but in the end it says 

    1354 Warning(s)
    0 Error(s)

Time Elapsed 00:11:27.35

I want to install Digits as well. Please let me know or suggest me if you have any appropriate link

**Comment by satishknl** [comment]
when I am trying to execute the below command, am facing this error:
conda install --yes protobuf==3.1.0.vc14

UnsatisfiableError: The following specifications were found to be in conflict:
  - protobuf ==3.1.0.vc14
  - python 2.7*
Use "conda info <package>" to see the dependencies for each package.

**Comment by alialaobali** [comment]
hi i have this error 
CMake Error: Error: generator : Visual Studio 14 2015 Win64
Does not match the generator used previously: Ninja
Either remove the CMakeCache.txt file and CMakeFiles directory or choose a different binary directory.
ERROR: Configure failed

**Comment by alialaobali** [comment]
hi i find a solution 
we must delete build folder
in my path is C:\Users\ali alaobali\Downloads\caffe\caffe
then write the order in cmd 
scripts\build_win.cmd

**Comment by anewusername77** [comment]
i got a problem is that:
enter in cmd line: ```build_win.cmd```
report: ```Incorrect syntax command```
