### ISSUE TITLE
A Simple and Efficient Implementation of im2col in Convolution Neural Networks

### ISSUE THREAD

**Issue by HaoMood** [BVLC/caffe#5341]
Hi, 

I proposed a simple and efficient implementation of im2col which can take place the Caffe’s implementation. When training MNIST on LeNet, it is 20.6% faster than Caffe’s implementation. For more details, please refer to the attachment pdf.
[A Simple and Efficient Implementation of im2col in Convolution Neural Networks.pdf](https://github.com/BVLC/caffe/files/813582/A.Simple.and.Efficient.Implementation.of.im2col.in.Convolution.Neural.Networks.pdf)

Best regards, 

Hao Zhang

**Comment by naibaf7** [comment]
Not bad, but I fail to see the advantage, with algorithms such as im2col+gemm fused kernels being 300% faster (opensource) and cuDNN being 400% faster... and they do not only work in a particular 2D case, but also 3D (and possibly higher). Both are readily available in CUDA for Caffe as well.

**Comment by HaoMood** [comment]
Hi naibaf7,

Thank you for you comment.

Yes, it is. For many input and filter regimes the cuDNN engine is faster than the Caffe engine, but for some models the Caffe engine can be faster. In those cases, a faster Caffe implementaion may be appreciated.

Best regards,

Hao

**Comment by naibaf7** [comment]
@HaoMood Ok. Can you show us some of those cases?
Ideally any faster im2col+col2im implementation should not be hard-coded for a special case, but rather interesting would be if it could cover all cases by JIT/RT code generation and compilation.
Note here that current Caffe implementations for col2im implement also ND-cases.

**Comment by HaoMood** [comment]
Hi, naiba7,

Thank you for you promote reply.

These two lines are quoted from Caffe:
- "cuDNN is sometimes but not always faster than Caffe's GPU acceleration."
- "For fully-convolutional models and large inputs the Caffe engine can be faster as long as it fits in memory."

My implementation is for 3D cases, which are the most common use cases in computer vision. Faster code is always attractive.

Your work is quite interesting. I may do some benchmark test in the future. 

Best regards, 

Hao Zhang

**Comment by naibaf7** [comment]
Ok thanks for your answer.
Please note though that fully convolutional layers do not use im2col.
The note that cuDNN is not always faster was true for cuDNN v2/v3, but with v5 this is certainly (almost) never the case.
Please feel free to add a comprehensive benchmark overview though :)

**Comment by HaoMood** [comment]
Hi naibaf7,

Thank you for your reply.

I think fully convolutional model indicates that the neural network is composed of convolution layers without any fully-connected layers. It seems that the only case we do not need im2col is that the corresponding convolution layer has kernel size 1 by 1, stride 1, pad 0. 

Best regards,

Hao

**Comment by naibaf7** [comment]
@HaoMood Oh yeah right, sorry for that.
I'd suggest you make a pull request of your version after providing comprehensive performance numbers so that everyone can have a look at the actual implementation differences..

**Comment by HaoMood** [comment]
Hi naibaf7,

I have a plan to release the code, but it is not completely ready for release at present. However, since the pseudo code is given in the pdf, implementing by oneself will not be hard.

Thank you very much.

Best regards,

Hao

**Comment by shelhamer** [comment]
Closing—if you are interested in further benchmarking and contributing your code then please send a PR. Note that the quotes about the relative speed of im2col+gemm and cuDNN were for the v2 era, and further versions have closed the gap or passed im2col+gemm across different feature map and kernel sizes (even those appearing in fully convolutional networks).
