### ISSUE TITLE
where should i add caffe.set_mode_gpu?

### ISSUE THREAD

**Issue by CongWeilin** [BVLC/caffe#5343]
i want to use gpu mode to test with python interface. i add `caffe.set_mode_gpu` before net initialize, the gpu util is almost 0. where should i add them? before each forward process?

**Comment by shelhamer** [comment]
Setting it once before instantiating the net is correct. Please ask usage questions on the mailing list.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
