### ISSUE TITLE
F0303 10:32:18.867789 30760 blob.cpp:121] Check failed: data_ 

### ISSUE THREAD

**Issue by Wonder233** [BVLC/caffe#5349]
Hi,

Does someone know why this message appears?
F0303 10:32:18.867789 30760 blob.cpp:121] Check failed: data_ 
*** Check failure stack trace: ***
    @     0x7f038079c9fd  google::LogMessage::Fail()
    @     0x7f038079e89d  google::LogMessage::SendToLog()
    @     0x7f038079c5ec  google::LogMessage::Flush()
    @     0x7f038079f1be  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f0380e11a5e  caffe::Blob<>::mutable_gpu_data()
    @     0x7f0380f57f96  caffe::TripletLossLayer<>::Forward_gpu()
    @     0x7f0380dd42a5  caffe::Net<>::ForwardFromTo()
    @     0x7f0380dd4617  caffe::Net<>::Forward()
    @     0x7f0380e0cd57  caffe::Solver<>::Step()
    @     0x7f0380e0d619  caffe::Solver<>::Solve()
    @           0x4086cb  train()
    @           0x405acc  main
    @     0x7f037f7adf45  (unknown)
    @           0x40633b  (unknown)
Aborted (core dumped)

Please give me some solutions.
ps:I checked my Inner layer as follow:
layer {
  name: "fc4_t2"
  type: "InnerProduct"
  bottom: "pool3_t2"
  top: "fc4_t2"
  param {
    name: "fc4_w"
    lr_mult: 1
  }
  param {
    name: "fc4_b"
    lr_mult: 2
  }
  inner_product_param {
    num_output: 1024
    weight_filler {
      type: "xavier"
    }
    bias_filler {
      type: "constant"
    }
  }
}

**Comment by shelhamer** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
