### ISSUE TITLE
Obtain a low top-5 accuracy based on caffe reference imagenet model

### ISSUE THREAD

**Issue by shuye-cheung** [BVLC/caffe#535]
I try caffe reference imageNet model to test the validation set of ImageNet 2012 competition. The top one accuracy is  56.89% and the top five accuracy is 70.24%. Yet the Alex' paper published in NIPS 2012 reported that the top 1 accuracy is 59.3% and the top 5 accuracy is 81.8%. This is a big gap (70.24% vs 81.8%). I doubt that if caffe reference model is not trained completely or I have done some mistakes? I'm looking forward to receiving your attention and reply.

**Comment by hiwonjoon** [comment]
@sguada Is there any built-in features or easy way to make 10 crops((4corners+1center)*2) and do accuracy evaluation? Or, do I need to implement this with my own in c++ or python?

Thanks!
