### ISSUE TITLE
Is there anyway to use the libcaffe.a?

### ISSUE THREAD

**Issue by Lone5267** [BVLC/caffe#5350]
Is there any sample?

**Comment by shelhamer** [comment]
There aren't exampled bundled of linking with Caffe, but the `.a` and `.so` are static and shared libraries like any other.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
