### ISSUE TITLE
Data sets missing from ROCKSDB

### ISSUE THREAD

**Issue by koushikpaul1** [BVLC/caffe#5351]
Some sets of data which were available on rocksdb on 28/02/2017 went missing on 01/02/2017. 

Also some data which were available on 27/02/2017 went missing on 28/02/2017 and again reappeared on
 01/02/2017.

Is it possible for rocksdb to malfunction because sensitive customer data is there?

The below two data set information provided below went missing after 28/02/2017 but was present on 28/02/2017

       "itemId": 1614781,
          "itemType": 6,
          "folderType": 0,
          "IsLatestSet": 0,
          "parentId": 0,
          "rootFolderId": 0,
          "pathFolderId": "",
          "activityType": 3,
          "actionDesc": "Permission change",
          "modifyTS": "1488227353564",
          "containerId": 1614781,
          "containerType": 11,
          "properties": "",
          "pwAccountId": 0
        },
        {
          "itemId": 1614781,
          "itemType": 6,
          "folderType": 0,
          "IsLatestSet": 0,
          "parentId": 0,
          "rootFolderId": 0,
          "pathFolderId": "",
          "activityType": 3,
          "actionDesc": "Permission change",
          "modifyTS": "1485358966294",
          "containerId": 1614781,
          "containerType": 11,
          "properties": "",
          "pwAccountId": 0
        },

**Comment by shelhamer** [comment]
Closing as accidental—this is the issue tracker for Caffe.
