### ISSUE TITLE
RNN + LSTM Layers - on WINDOWS branch?

### ISSUE THREAD

**Issue by marcelstange** [BVLC/caffe#5352]
Please use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) for usage, installation, or modeling questions, or other requests for help.
_Do not post such requests to Issues._ Doing so interferes with the development of Caffe.

Please read the [guidelines for contributing](https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md) before submitting this issue.

### Issue summary

LSTM Layers not working on Windows branch. Any ideas?

### Steps to reproduce

If you are having difficulty building Caffe or training a model, please ask the caffe-users mailing list. If you are reporting a build error that seems to be due to a bug in Caffe, please attach your build configuration (either Makefile.config or CMakeCache.txt) and the output of the make (or cmake) command.

### Your system configuration
Operating system:
Compiler:
CUDA version (if applicable):
CUDNN version (if applicable):
BLAS:
Python or MATLAB version (for pycaffe and matcaffe respectively):

**Comment by shelhamer** [comment]
@willyd is this a usage issue or is there a problem with recurrence in the Windows branch?

**Comment by willyd** [comment]
@shelhamer To be honest I have not tried any of the recurrent layers so I can't confirm for sure. AFAIK there are no examples for LSTMs or RNNs, if someone can contribute one I can give it a try on Windows and report back.

That being said all tests pass with or without GPU support (expect for Timer related tests) so my guess would be that this is a usage issue. Plus there is not enough information in the issue to provide any help, *not working* is not specific enough.

**Comment by shelhamer** [comment]
Closing for lack of detail.
