### ISSUE TITLE
Is there anyway to save training log file for matlab interface users?

### ISSUE THREAD

**Issue by littleTwelve** [BVLC/caffe#5354]
I am using MatCaffe interface for training DNN and was wondering how I could collect training/testing log to for plotting the loss and accuracy v.s. iter/time. I haven't found the command or function for generating loss .log for Matlab interface. For command line interface the command is "2>&1 | tee xxx.log" at the end, but it's unknown for matCaffe as limited instruction could be found.

**Comment by shelhamer** [comment]
Please ask usage questions on the mailing list. For matcaffe the same logging should be done to stderr of the matlab process (if I recall correctly).

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
