### ISSUE TITLE
Check failed: mdb_status == 0 (70 vs. 0) Communication error on send

### ISSUE THREAD

**Issue by ludovicdmt** [BVLC/caffe#5356]
### Issue summary :
I get this message when I try to launch my net.

F0304 13:58:49.881284 23190 db_lmdb.hpp:15] Check failed: mdb_status == 0 (70 vs. 0) "

The LMDB database was generated by me and I'm sure of the path : 
[darmet@zeus train_lmdb]$ ls -s /workdir/darmet/Input/train_lmdb
total 40114608
40114600 data.mdb         8 lock.mdb

 I found nothing about "Communication error on send" error? Am I the only one with this issue ?

### System configuration : 
Caffe was installed on a cluster (not by me). Although I have the MakeFile (see attached). The installation was tricky so it may be the cause but nothing sure. 

Thank you for the help.

[Makefile.config.txt](https://github.com/BVLC/caffe/files/818642/Makefile.config.txt)

**Comment by shelhamer** [comment]
Sorry, I've never seen this error but I expect it's an installation issue with lmdb.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
