### ISSUE TITLE
Reset multiple MemoryData layers using the Python interface

### ISSUE THREAD

**Issue by thertweck** [BVLC/caffe#5358]
Caffe allows resetting memory data layers using the Python interface with `net.set_input_arrays`. Currently this only works for a single `MemoryDataLayer` ([here](https://github.com/BVLC/caffe/blob/master/python/caffe/_caffe.cpp#L167)). It would be a nice addition to allow resetting memory data layers by name.

I'd be happy to provide a PR for this. A simple and backward compatible solution might be to add an optional `layer` argument to `set_input_arrays`:

```
def _Net_set_input_arrays(self, data, labels, layer=None):
    ...
```

and call it like this:

```
net.set_input_arrays(x1, y1, layer='data1')
net.set_input_arrays(x2, y2, layer='data2')
```

A more consistent solution would be to use `kwargs` (similar to forward, forward_all, backward, ...):

```
def _Net_set_memory_data(self, kwargs):
    ...
```

Where keys are blob names and values are (data, labels) tuples:

```
net.set_memory_data(data1=(x1, y1), data2=(x2, y2))

# or like this:
dataset = {'data1': (x1, y1), 'data2': (x2, y2)}
net.set_memory_data(**dataset)
```

**Comment by shelhamer** [comment]
Closing according to #5528 as `Input` layers suffice for this use case.
