### ISSUE TITLE
window branch has no file that compiler requires

### ISSUE THREAD

**Issue by taecheon** [BVLC/caffe#5359]
I downloaded caffe at https://github.com/BVLC/caffe/tree/windows

and I complied it using 'visual studio 2013'

I use cuda 8.0 because of my graphic driver. (I know cuda 8.0 should use visual studio 2015. but the code on window branch is for 2013)

(later, I used visual studio 2015. but I still have this issue)

My issue is as follows
When I try to build solution, I got errors like below

(소스 파일을 열 수 없습니다. means 'cannot open source file')
1 error C1083: 소스 파일을 열 수 없습니다. '..\..\src\caffe\data_reader.cpp': No such file or directory C:\Users\D533-1\Desktop\caffe-windows\caffe-windows\windows\libcaffe\c1xx libcaffe

(파일을 열 수 없습니다. means 'cannot open file')
2 error LNK1104: 'libcaffe.lib' 파일을 열 수 없습니다. C:\Users\D533-1\Desktop\caffe-windows\caffe-windows\windows\classification\LINK classification
3 error LNK1104: 'libcaffe.lib' 파일을 열 수 없습니다. C:\Users\D533-1\Desktop\caffe-windows\caffe-windows\windows\convert_cifar_data\LINK convert_cifar_data
4 error LNK1104: 'libcaffe.lib' 파일을 열 수 없습니다. C:\Users\D533-1\Desktop\caffe-windows\caffe-windows\windows\caffe\LINK caffe
5 error LNK1104: 'libcaffe.lib' 파일을 열 수 없습니다. C:\Users\D533-1\Desktop\caffe-windows\caffe-windows\windows\convert_mnist_siamese_data\LINK convert_mnist_siamese_data
6 error LNK1104: 'libcaffe.lib' 파일을 열 수 없습니다. C:\Users\D533-1\Desktop\caffe-windows\caffe-windows\windows\upgrade_net_proto_binary\LINK upgrade_net_proto_binary
7 error LNK1104: 'libcaffe.lib' 파일을 열 수 없습니다. C:\Users\D533-1\Desktop\caffe-windows\caffe-windows\windows\compute_image_mean\LINK compute_image_mean
8 error LNK1104: 'libcaffe.lib' 파일을 열 수 없습니다. C:\Users\D533-1\Desktop\caffe-windows\caffe-windows\windows\convert_imageset\LINK convert_imageset
9 error LNK1104: 'libcaffe.lib' 파일을 열 수 없습니다. C:\Users\D533-1\Desktop\caffe-windows\caffe-windows\windows\extract_features\LINK extract_features
10 error LNK1104: 'libcaffe.lib' 파일을 열 수 없습니다. C:\Users\D533-1\Desktop\caffe-windows\caffe-windows\windows\convert_mnist_data\LINK convert_mnist_data
11 error LNK1104: 'libcaffe.lib' 파일을 열 수 없습니다. C:\Users\D533-1\Desktop\caffe-windows\caffe-windows\windows\matcaffe\LINK matcaffe
12 error LNK1104: 'libcaffe.lib' 파일을 열 수 없습니다. C:\Users\D533-1\Desktop\caffe-windows\caffe-windows\windows\test_all\LINK test_all
13 error LNK1104: 'libcaffe.lib' 파일을 열 수 없습니다. C:\Users\D533-1\Desktop\caffe-windows\caffe-windows\windows\upgrade_net_proto_text\LINK upgrade_net_proto_text
14 error LNK1104: 'libcaffe.lib' 파일을 열 수 없습니다. C:\Users\D533-1\Desktop\caffe-windows\caffe-windows\windows\upgrade_solver_proto_text\LINK upgrade_solver_proto_text

and when I tried build libcaffe project separately, I got error like this.

2 error C1083: 소스 파일을 열 수 없습니다. '..\..\src\caffe\data_reader.cpp': No such file or directory C:\Users\D533-1\Desktop\caffe-windows\caffe-windows\windows\libcaffe\c1xx libcaffe

Actually, data_reader.cpp was not in that path.

So I get 'data_reader.cpp'and 'data_reader.hpp' at https://github.com/intel/caffe/blob/master/src/caffe/data_reader.cpp and other way respectively.

but I got new errors that requires me to modify source code.

I cannot do that, and I think it's not appropriate solution.

please tell me what should I do to solve this problem.

**Comment by willyd** [comment]
Please use the CMake build. 

Please use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) for usage, installation, or modeling questions, or other requests for help.
_Do not post such requests to Issues._ Doing so interferes with the development of Caffe.

Please read the [guidelines for contributing](https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md) before submitting this issue.

**Comment by herleeyandi** [comment]
I am new in caffe, but I also have same problem, when it said that it can not find `data_reader.cpp `and `data_reader.hpp`. 

1. My solution is try to build one by one, begin from `libcaffe` browse file `caffe/windows/libcaffe/libcaffe.vcxproj` open it using text editor. Delete line: ` <ClCompile Include="..\..\src\caffe\data_reader.cpp" />` and `<ClInclude Include="..\..\include\caffe\data_reader.hpp" />` after that try `Rebuild` your project, also you can do it by `Clean` it first then `Build` it. It works for me. 

2. This is optional, if you still find error about OpenCV, just go to `Tools/NuGet Package Manager/Package Manager Console ` then type `Update-Package opencv -reinstall`  wait moment, after finish try rebuild your project.

Hope this solution can help the people who have same problem with me. Good luck.
I am using Visual Studio 2013 and CUDA Toolkit 8.0

**Comment by willyd** [comment]
@herleeyandi Use the CMake build. The Visual Studio based build is not supported anymore and will be removed in the next days.

**Comment by herleeyandi** [comment]
@willyd Wow I just know that, I think using CMake will much better, but where I can find the tutorial step by step in CMake, since I am new in caffe?, Thanks for the information.

**Comment by willyd** [comment]
https://github.com/BVLC/caffe/tree/windows#configuring-and-building-caffe

**Comment by herleeyandi** [comment]
Thank you @willyd .
