### ISSUE TITLE
Does anyone make a multi-label classfication test using caffe? 

### ISSUE THREAD

**Issue by wuqiangch** [BVLC/caffe#536]
I am working on a project about multi-label classfication. For example, there is a picture with a dog, a cat and a person. How can I  use caffe to finish it. Does anyone have the same problem  with me ?Thanks.

**Comment by liuxiaya** [comment]
@wuqiangch 我也遇到了这个问题，请问您是怎么做的？

**Comment by liuxiaya** [comment]
@sguada hdf5 data 能用您的PR吗

**Comment by liuxiaya** [comment]
@sguada HDF5 data can use your PR？？

**Comment by liuxiaya** [comment]
@wuqiangch I also encountered this problem, how do you do?
