### ISSUE TITLE
matlab crash when use anything about caffe

### ISSUE THREAD

**Issue by ethanlmx** [BVLC/caffe#5360]
cpu only ,matlabR2016b ,osX 
make matlab is ok
but in make mattest
Stack Trace (from fault):
[  0] 0x0000000104547d04 /Applications/MATLAB_R2016b.app/bin/maci64/libmwfl.dylib+00036100 _ZN2fl4diag15stacktrace_base7captureERKNS0_14thread_contextEm+00000052
[  1] 0x000000010454af9a /Applications/MATLAB_R2016b.app/bin/maci64/libmwfl.dylib+00049050 _ZN2fl4test17terminate_handledEv+00000810
[  2] 0x000000010454aa09 /Applications/MATLAB_R2016b.app/bin/maci64/libmwfl.dylib+00047625 _ZN2fl4diag13terminate_logEPKcPK17__darwin_ucontext+00000185
[  3] 0x0000000107498ba8 /Applications/MATLAB_R2016b.app/bin/maci64/libmwmcr.dylib+00420776 _Z32mnRunPathDependentInitializationN6mlutil10contextmgr5McrIDE+00003016
[  4] 0x00000001074984e0 /Applications/MATLAB_R2016b.app/bin/maci64/libmwmcr.dylib+00419040 _Z32mnRunPathDependentInitializationN6mlutil10contextmgr5McrIDE+00001280
[  5] 0x000000010749945a /Applications/MATLAB_R2016b.app/bin/maci64/libmwmcr.dylib+00423002 _Z32mnRunPathDependentInitializationN6mlutil10contextmgr5McrIDE+00005242
[  6] 0x0000000107497e6e /Applications/MATLAB_R2016b.app/bin/maci64/libmwmcr.dylib+00417390 _Z22mnInstallCrashHandlersv+00000350
......
MATLAB is exiting because of fatal error
/bin/sh: line 1: 14220 Killed: 9               /Applications/MATLAB_R2016b.app/bin/matlab -nodisplay -r 'caffe.run_tests(), exit()'
make: *** [mattest] Error 137

and in matlab
caffe.set_mode_cpu();
the matlab crash
------------------------------------------------------------------------
              abort() detected at Sun Mar  5 15:23:15 2017
------------------------------------------------------------------------

Configuration:
  Crash Decoding      : Disabled - No sandbox or build area path
  Crash Mode          : continue (default)
  Current Graphics Driver: Unknown hardware
  Current Visual      : Quartz
  Default Encoding    : US-ASCII
  Deployed            : false
  Host Name           : Liu-Mac.local
  MATLAB Architecture : maci64
  MATLAB Entitlement ID: 6257193
  MATLAB Root         : /Applications/MATLAB_R2016b.app
  MATLAB Version      : 9.1.0.441655 (R2016b)
  OpenGL              : hardware
  Operating System    : Darwin 16.4.0 Darwin Kernel Version 16.4.0: Thu Dec 22 22:53:21 PST 2016; root:xnu-3789.41.3~3/RELEASE_X86_64 x86_64
  Processor ID        : x86 Family 6 Model 61 Stepping 4, GenuineIntel
  Virtual Machine     : Java 1.7.0_75-b13 with Oracle Corporation Java HotSpot(TM) 64-Bit Server VM mixed mode
  Window System       : Quartz

Fault Count: 1

Abnormal termination:
abort()

Register State (from fault):
  RAX = 4000000000003062  RBX = 0000000000000003
  RCX = 0000000000000000  RDX = 000070000814d03c
  RSP = 0000000000000016  RBP = 00007fffe88704dc
  RSI = 000070000814d020  RDI = 000070000814e000

   R8 = 0000000000000006   R9 = 0000000000000045
  R10 = 0000000192375c10  R11 = 000070000814e000
  R12 = 000070000814d0b8  R13 = 000070000814d050
  R14 = 00007fffe8872787  R15 = 000070000814d070

  RIP = 0000f20700000045  RFL = 000070000814d070

   CS = 0000000192352d01   FS = 000070000814d080   GS = 00007fffe86ec420

Stack Trace (from fault):
[  0] 0x000000010da36d04 /Applications/MATLAB_R2016b.app/bin/maci64/libmwfl.dylib+00036100 _ZN2fl4diag15stacktrace_base7captureERKNS0_14thread_contextEm+00000052
[  1] 0x000000010da39f9a /Applications/MATLAB_R2016b.app/bin/maci64/libmwfl.dylib+00049050 _ZN2fl4test17terminate_handledEv+00000810
[  2] 0x000000010da39a09 /Applications/MATLAB_R2016b.app/bin/maci64/libmwfl.dylib+00047625 _ZN2fl4diag13terminate_logEPKcPK17__darwin_ucontext+00000185
[  3] 0x0000000110dd1ba8 /Applications/MATLAB_R2016b.app/bin/maci64/libmwmcr.dylib+00420776 _Z32mnRunPathDependentInitializationN6mlutil10contextmgr5McrIDE+00003016
[  4] 0x0000000110dd14e0 /Applications/MATLAB_R2016b.app/bin/maci64/libmwmcr.dylib+00419040 _Z32mnRunPathDependentInitializationN6mlutil10contextmgr5McrIDE+00001280
[  5] 0x0000000110dd245a /Applications/MATLAB_R2016b.app/bin/maci64/libmwmcr.dylib+00423002 _Z32mnRunPathDependentInitializationN6mlutil10contextmgr5McrIDE+00005242
[  6] 0x0000000110dd0e6e /Applications/MATLAB_R2016b.app/bin/maci64/libmwmcr.dylib+00417390 _Z22mnInstallCrashHandlersv+00000350
[  7] 0x00007fffe8865bba           /usr/lib/system/libsystem_platform.dylib+00011194 _sigtramp+00000026
[  8] 0x0000000000000000                                   <unknown-module>+00000000
[  9] 0x00007fffe86ec420                  /usr/lib/system/libsystem_c.dylib+00390176 abort+00000129
[ 10] 0x000000019233d369  /usr/local/opt/gperftools/lib/libtcmalloc.4.dylib+00029545 _ZN8tcmalloc3LogENS_7LogModeEPKciNS_7LogItemES3_S3_S3_+00000649
[ 11] 0x000000019234d1f3  /usr/local/opt/gperftools/lib/libtcmalloc.4.dylib+00094707 tc_free+00001085
[ 12] 0x00007fffd31cf185 /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation+01401221 _CFRelease+00001093
[ 13] 0x00007fffe1d7eaea /System/Library/PrivateFrameworks/IOAccelerator.framework/Versions/A/IOAccelerator+00010986 IOAccelContextSubmitDataBuffersExt2+00000203
[ 14] 0x00007fffe0d0d436 /System/Library/PrivateFrameworks/GPUSupport.framework/Versions/A/Libraries/libGPUSupportMercury.dylib+00013366 gpusSubmitDataBuffers+00000156
[ 15] 0x000000011f9da19a /System/Library/Extensions/AppleIntelBDWGraphicsGLDriver.bundle/Contents/MacOS/AppleIntelBDWGraphicsGLDriver+00016794 _ZN18IntelCommandBuffer6getNewEP13GLDContextRec+00000178
[ 16] 0x000000011faaa97b /System/Library/Extensions/AppleIntelBDWGraphicsGLDriver.bundle/Contents/MacOS/AppleIntelBDWGraphicsGLDriver+00870779 intelSubmitCommands+00000171
[ 17] 0x000000011fe703f4 /System/Library/Extensions/AppleIntelBDWGraphicsGLDriver.bundle/Contents/MacOS/AppleIntelBDWGraphicsGLDriver+04826100 glrFlushContextToken+00000196
[ 18] 0x0000000129028d56 /Applications/MATLAB_R2016b.app/sys/java/jre/maci64/jre/lib/lwawt/liblwawt.dylib+00032086 Java_sun_java2d_opengl_OGLRenderQueue_flushBuffer+00002886
[ 19] 0x000000012248b758                                   <unknown-module>+00000000

### Your system configuration
Operating system:OS X 10.12.3
Compiler:clang++
BLAS:open
Python or MATLAB version (for pycaffe and matcaffe respectively):matcaffe

thinks for help

**Comment by yunhao94** [comment]
What's the version of your opencv? I'v faced the same problem with the opencv 2.4.9 on Ubuntu 16.04.2, and solved this when I installed the opencv 3.2.0.

**Comment by ethanlmx** [comment]
@yunhao94  
还是不好用啊

**Comment by XavierCHEN34** [comment]
anyone solved this problem?
