### ISSUE TITLE
Make runtest fault

### ISSUE THREAD

**Issue by RuaYahya** [BVLC/caffe#5367]
Dear All , I am  new learner on deep learning and I am trying to install caffe on ubuntu 16 but unfortunately I fault at this point (attached ). Any advice is highly appreciated . 

![problem 1](https://cloud.githubusercontent.com/assets/25819990/23698368/3656c772-03e3-11e7-978a-c4fc3ad90a30.png)

**Comment by deepali-c** [comment]
Please check - [Stackoverflow thread](http://stackoverflow.com/questions/3253257/cuda-driver-version-is-insufficient-for-cuda-runtime-version)

**Comment by shelhamer** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
