### ISSUE TITLE
FCN inference - Net.__init__(Net, str, int, str) did not match C++ signature

### ISSUE THREAD

**Issue by GaryKT** [BVLC/caffe#5373]
### Issue summary

infer.py from https://github.com/shelhamer/fcn.berkeleyvision.org example code throws the following error and warning. Does the FCN code example need to be changed? Is there an example in the master caffe branch to get this to work? Note that the FCN example also did not include a deploy.prototxt, but only solver.prototxt.

Traceback (most recent call last):
python infer.py
WARNING: Logging before InitGoogleLogging() is written to STDERR
W0308 15:59:04.955081 14024 _caffe.cpp:172] DEPRECATION WARNING - deprecated use of Python interface
W0308 15:59:04.956086 14024 _caffe.cpp:173] Use this instead (with the named "weights" parameter):
W0308 15:59:04.956588 14024 _caffe.cpp:175] Net('solver.prototxt', 1, weights='fcn32s-heavy-pascal.caffemodel')
[libprotobuf ERROR D:\build\caffe-builder\build_v140_x64\packages\protobuf\protobuf_download-prefix\src\protobuf_download\src\google\protobuf\text_format.cc:298] Error parsing text-format caffe.NetParameter: 1:10: Message type "caffe.NetParameter" has no field named "train_net".
F0308 15:59:04.958593 14024 upgrade_proto.cpp:88] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: solver.prototxt
*** Check failure stack trace: ***

### Steps to reproduce

Run infer.py with an example image and the fcn32s-heavy-pascal.caffemodel.

### Your system configuration
Operating system: Windows
Compiler: Ninja / VS14
CUDA version (if applicable): 8
CUDNN version (if applicable): 5.1
BLAS: ?
Python or MATLAB version (for pycaffe and matcaffe respectively): Python 3.5.2

**Comment by shelhamer** [comment]
There is a deploy for FCN-8s as identified in infer.py: https://github.com/shelhamer/fcn.berkeleyvision.org/blob/master/voc-fcn8s/deploy.prototxt
At some point I hope to generalize the [example net spec](https://github.com/shelhamer/fcn.berkeleyvision.org/blob/master/voc-fcn8s/net.py) to make all the different variants for clarity.

Please ask usage questions on the mailing list.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
