### ISSUE TITLE
fcn32s-heavy-pascal.caffemodel protocol message warning and all 0 output

### ISSUE THREAD

**Issue by GaryKT** [BVLC/caffe#5374]
### Issue summary
The resulting segmented output / image is all 0s (regardless of the input image) when running infer.py with fcn32s-heavy-pascal.caffemodel. (using val.prototxt - no deploy.prototxt was provided in the FCN32 sample)

There is also a warning or error on protocol message size limit when trying to making a FCN inference from fcn32s-heavy-pascal.caffemodel.

**[libprotobuf WARNING D:\build\caffe-builder\build_v140_x64\packages\protobuf\protobuf_download-prefix\src\protobuf_download\src\google\protobuf\io\coded_stream.cc:605] Reading dangerously large protocol message.  If the message turns out to be larger than 2147483647 bytes, parsing will be halted for security reasons.  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
[libprotobuf WARNING D:\build\caffe-builder\build_v140_x64\packages\protobuf\protobuf_download-prefix\src\protobuf_download\src\google\protobuf\io\coded_stream.cc:82] The total number of bytes read was 544614787**
[[0 0 0 ..., 0 0 0]
 [0 0 0 ..., 0 0 0]
 [0 0 0 ..., 0 0 0]
 ...,
 [0 0 0 ..., 0 0 0]
 [0 0 0 ..., 0 0 0]
 [0 0 0 ..., 0 0 0]]

### Steps to reproduce

Run infer.py image.jpg
where image.jpg is some sample image to segment.
Download model from here: http://dl.caffe.berkeleyvision.org/fcn32s-heavy-pascal.caffemodel
Download val.prototxt from here: https://github.com/shelhamer/fcn.berkeleyvision.org/blob/master/voc-fcn32s/val.prototxt

infer.py:
---------
import numpy as np
from PIL import Image

import caffe
import sys

caffe.set_mode_gpu()

image_file = sys.argv[1]

# load image, switch to BGR, subtract mean, and make dims C x H x W for Caffe
im = Image.open(image_file )
in_ = np.array(im, dtype=np.float32)
in_ = in_[:,:,::-1]
in_ -= np.array((104.00698793,116.66876762,122.67891434))
in_ = in_.transpose((2,0,1))

# load net
net = caffe.Net('val.prototxt', 'fcn32s-heavy-pascal.caffemodel', caffe.TEST)
# shape for input (data blob is N x C x H x W), set data
net.blobs['data'].reshape(1, *in_.shape)
net.blobs['data'].data[...] = in_
# run net and take argmax for prediction
net.forward()
out = net.blobs['score'].data[0].argmax(axis=0)
print (out)
out_8 = np.empty_like(out, dtype=np.uint8)
np.copyto(out_8, out, casting='unsafe')
img = Image.fromarray(out_8)
img.save("infer_out.png")

### Your system configuration
Operating system: Windows 10
Compiler: Ninja
CUDA version (if applicable): 8
CUDNN version (if applicable): 5.1
BLAS: ?
Python or MATLAB version (for pycaffe and matcaffe respectively): Python 3.5.2

**Comment by shelhamer** [comment]
Please ask usage questions on the mailing list. To assign the data it's simplest to make use of a deploy net with `Input` layer(s). Please ask usage questions on the mailing list.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
