### ISSUE TITLE
How to solve this erorr  using codeblocks 

### ISSUE THREAD

**Issue by nourlaban** [BVLC/caffe#5377]
||=== Build: all in Caffe (compiler: GNU GCC Compiler) ===|
CMakeFiles/MKLDNN_Build.dir/build.make|73|recipe for target 'MKLDNN_Build-prefix/src/MKLDNN_Build-stamp/MKLDNN_Build-install' failed|
CMakeFiles/Makefile2|99|recipe for target 'CMakeFiles/MKLDNN_Build.dir/all' failed|
/caffe-build-march3/Makefile|127|recipe for target 'all' failed|
||=== Build failed: 3 error(s), 0 warning(s) (0 minute(s), 0 second(s)) ===|
||=== Run: all in Caffe (compiler: GNU GCC Compiler) ===|

**Comment by shelhamer** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
