### ISSUE TITLE
ImageDataParameter has no field specify whether input images are color or grayscale

### ISSUE THREAD

**Issue by shuokay** [BVLC/caffe#538]
I am doing classification task using caffe. My images are grayscale(Chinese charactors), Now I can convert those image to 1-channel input using the method #469 , but it is not suit to the online system for I have to convert one image to leveldb format first, and then put the leveldb file path to the proto file. #251 is a pretty good solution, by adding an image_data_layer, but it seems the imae_data_layer can not handle grayscale images, so can someone give me some suggests to make imae_data_layer suit for grayscale images? @sguada

**Comment by dingcius** [comment]
@sguada Will this strategy (set all is_color=false) make caffe only handle gayscale images? I ask this because there seems to be no interface to read the color/chanel parameter in "image_data_layer.cpp".

**Comment by michael-george-hart** [comment]
I have been basically an error that I assumed had something to do with this thread and followed sguada recommendation and nothing changed; I still get the erro

F0411 22:00:37.583753 31071 blob.cpp:454] Check failed: ShapeEquals(proto) shape mismatch (reshape not set)
If I was wrong about the error having to do with this thread; my apologies and any help would be appreciated..... my version of caffe was a pull from the master branch 3/31/2015

**Comment by hagaygazuli** [comment]
Hi, 
I have the same error (ShapeEquals(proto) shape mismatch (reshape not set) ). Does anyone knows how to solve this?

Appreciate any help
hagay.

**Comment by atique81** [comment]
me too stuck with this error...

**Comment by mateuszbuda** [comment]
The issue is closed but none of suggested solutions worked for me.
Tried `is_color: 0`, `is_color: false`, `images_in_color: false` and `images_in_color: 0`.
In each case jpeg image was loaded as 3 channel data.
Did anyone solve this?
