### ISSUE TITLE
Error when training cifar10  using my own dataset【用自己的数据集训练cifar10时出错】

### ISSUE THREAD

**Issue by BUAAkong** [BVLC/caffe#5392]
When I run the train command ,it breaks down.
The error is like:
 
F0312 23:17:37.941721  9344 upgrade_proto.cpp:1063] Check failed: ReadProtoFromT
extFile(param_file, param) Failed to parse SolverParameter file: data\image1000t
est200\cifar10_quick_solver.prototxt
*** Check failure stack trace: *** 

Any help is appreciated!

**Comment by shelhamer** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
