### ISSUE TITLE
Error linking CXX executables

### ISSUE THREAD

**Issue by machomachopadre** [BVLC/caffe#5396]
Hi,
I just had a weird experience while building caffe..

I executed `make --jobs=4` and it ran all well till it reached 92%. Then while it was linking the CXX executable compute_image_mean, convert_image set, extract_features, and caffe it threw the same error- `../lib/libcaffe.so.1.0.0-rc3: undefined reference to 'cudnnConvolutionBackwardData_v3'`.

What worries me here is..I have successfully built caffe before, with the same installation, same paths, the same device..basically the same everything. What exactly is going on? I haven't touched cudnn and installed DIGITS yesterday. I had some installation errors because of the caffe path not being recognized (that's why I'm here and building it again), but no issue in its requirement for cudnn, which proves nothing is wrong with cudnn.

Aside from advice on how to fix it, I would like to know if caffe automatically resets its paths over time or something similar.

Operating system: Ubuntu 14.04 LTS
CUDA version: 7.5

This is the full output:
```
Linking CXX shared library ../../lib/libcaffe.so
[ 90%] Built target caffe
Scanning dependencies of target caffe.bin
[ 91%] Building CXX object tools/CMakeFiles/caffe.bin.dir/caffe.cpp.o
Linking CXX executable caffe
../lib/libcaffe.so.1.0.0-rc3: undefined reference to `cudnnConvolutionBackwardData_v3'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to `cudnnConvolutionBackwardFilter_v3'
collect2: error: ld returned 1 exit status
make[2]: *** [tools/caffe] Error 1
make[1]: *** [tools/CMakeFiles/caffe.bin.dir/all] Error 2
make: *** [all] Error 2

```
Thanks

**Comment by shelhamer** [comment]
The DIGITS installation might have changed your environment?

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
