### ISSUE TITLE
python prediction error when no crop used.

### ISSUE THREAD

**Issue by SenJia** [BVLC/caffe#5397]
Hi, I have used caffe for a long time and it works perfectly in the demo. But recently when I train a model without cropping (training on whole image), the argmax of output is always the first.

I just removed "crop_size: xxx" in the train_val.prototxt and specified "dim: 200 dim:100" in the deploy file. (yes, my data is not square.)

The test loss during training process looks ok but all the output is misclassified as the first class when I use python.

But when I added "crop_size: 80" to the train_val.prototxt, the saved model looks more reasonable. 
I am not sure if this is a bug. If not, my apology that I wrongly put it here.

Thanks in advance
Sen

**Comment by shelhamer** [comment]
This is likely a usage issue due to differences in pre-processing between the data layer and pycaffe usage. Please ask usage questions on the mailing list and refer to the ipython notebooks bundled in Caffe for some examples of pycaffe usage.
