### ISSUE TITLE
Using train.py results in cryptic nccl error under windows

### ISSUE THREAD

**Issue by willyd** [BVLC/caffe#5401]
As reported in #5353.

> F0303 23:23:01.868011 30044 parallel.cpp:135] Check failed: result == ncclSuccess (2 vs. 0) system error
 *** Check failure stack trace: ***

**Comment by willyd** [comment]
Should be fixed by https://github.com/BVLC/caffe/pull/5400.

**Comment by shelhamer** [comment]
Closing as presumed fixed until we hear otherwise.
