### ISSUE TITLE
AN ERROR in using classification_demo.m to classify my test data with the trained net[测试结果出错]

### ISSUE THREAD

**Issue by woshizjt** [BVLC/caffe#5405]
when i  do testing by using matlab/demo/classification_demo.m ,i load my own trained net and the depoly.prototxt (no error when i using them to extract features, the classifier i trained using the extracted feature can reach a good test result),then the output scores  remains  a row of fixed  numbers so the predict label never change.......

Any help is appreciated!!!!!THANKS  A LOT!

**Comment by shelhamer** [comment]
It takes care to reproduce the same pre-processing between libcaffe, matcaffe, and pycaffe. For usage questions about how to do so please ask on the mailing list.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
