### ISSUE TITLE
The meaning of result of caffe output:"8inputs+9480outputs (1major+29375minor)pagefaults 0swaps"

### ISSUE THREAD

**Issue by zanghao2** [BVLC/caffe#5409]
What is the meaning of result of caffe output :"8inputs+9480outputs (1major+29375minor)pagefaults 0swaps"?     
                                                       
                                                                                                                                  THANKS A LOT!!!

**Comment by shelhamer** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
