### ISSUE TITLE
Training Siamese with caffe failed-Check failed: channels == datum_channels (2 vs. 1)

### ISSUE THREAD

**Issue by deweilow** [BVLC/caffe#5412]
Hi Guy, i am training a siamese network with my own data. I used my python code to convert image, image1 to grayscale and merge them into a two channel image. Then i convert them into lmdb format. However i keep facing this issue for a number of weeks and i have no idea how to solve it.  It reached the data transform layer, and it seems like expecting a 1 channel image instead of two channels. Please provide some assistance for me to overcome this issue

I0316 12:50:31.446934 31638 solver.cpp:279] Solving mnist_siamese_train_test
I0316 12:50:31.446939 31638 solver.cpp:280] Learning Rate Policy: inv
I0316 12:50:31.447700 31638 solver.cpp:337] Iteration 0, Testing net (#0)
I0316 12:50:31.448484 31638 blocking_queue.cpp:50] Data layer prefetch queue empty
 12:50:31.460836 31675 data_transformer.cpp:167] Check failed: channels == datum_channels (2 vs. 1) 
*** Check failure stack trace: ***
    @     0x7f3b11379daa  (unknown)
    @     0x7f3b11379ce4  (unknown)
    @     0x7f3b113796e6  (unknown)
    @     0x7f3b1137c687  (unknown)
    @     0x7f3b118df851  caffe::DataTransformer<>::Transform()
    @     0x7f3b118fe245  caffe::DataLayer<>::load_batch()
    @     0x7f3b1190b7dc  caffe::BasePrefetchingDataLayer<>::InternalThreadEntry()
    @     0x7f3b11a5c04f  caffe::InternalThread::entry()
    @     0x7f3b0f94ea4a  (unknown)
    @     0x7f3b0f72d184  start_thread
    @     0x7f3b0fc5337d  (unknown)
    @              (nil)  (unknown)

**Comment by hgaiser** [comment]
Hi there, please post your usage questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) group.

That being said, you could attempt to write your own data layer which produces three top blobs (image1, image2, similarity) in python for example. I did this and personally I liked it more than the lmdb data layer.

**Comment by shelhamer** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
