### ISSUE TITLE
Hope we could have a Dockerfile for CentOS.

### ISSUE THREAD

**Issue by guotong1988** [BVLC/caffe#5413]
https://github.com/BVLC/caffe/blob/master/docker/gpu/Dockerfile

**Comment by cypof** [comment]
You know you can run an Ubuntu image on a CentOS host? Do you need the image itself to be CentOS?

**Comment by shelhamer** [comment]
Closing in preference of keeping the Ubuntu Dockerfile the standard for master as it is the most common platform for Caffe usage. Further Dockerfiles can be contributed to the wiki.
