### ISSUE TITLE
libcudart.so.7.5 => not found

### ISSUE THREAD

**Issue by IvyGongoogle** [BVLC/caffe#5414]
hello, I use ubuntu14.04,cuda8.0 and I have also cuda7.5 in my system. after I do command `make pycaffe`, I do command` import caffe` in python, it shows error:

```
from ._caffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, \
ImportError: libcudart.so.7.5: cannot open shared object file: No such file or directory
```
then I do command `ldd python/caffe/_caffe.so | grep libcu`, it shows:

```
libcudart.so.7.5 => not found
libcublas.so.8.0 => /usr/local/cuda/lib64/libcublas.so.8.0 (0x00007f57dcfdc000)
libcurand.so.8.0 => /usr/local/cuda/lib64/libcurand.so.8.0 (0x00007f57d9066000)
libcudnn.so.5 => /usr/local/cuda/lib64/libcudnn.so.5 (0x00007f57d3862000)
```
why caffe find and uses libcudart.so.7.5 rather than libcudart.so.8.0 when doing `make pycaffe`??

thankyou in advance!!

**Comment by IvyGongoogle** [comment]
when I do `make all -j`, it success. But it shows some extra information in the compile process:

`nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).`

I think this warning is not the cause of above problem. Is It ?

**Comment by IvyGongoogle** [comment]
and I do not add `cuda-7.5/lib64` into `.bashrc`.

**Comment by RSly** [comment]
hi @IvyGongoogle ,
do you compile caffe with nccl checked? 
look in build > cmake-gui ..
if yes, then you need to re-compile nccl with the same cuda version (8.0) as the one you use for caffe

**Comment by IvyGongoogle** [comment]
@ I have only one GPU. I use `make` to compile caffe-v0.9999 and do not uncomment the line `# USE_NCCL := 1`

**Comment by shelhamer** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
