### ISSUE TITLE
how to merge the caffemodel and meanfile and analyse the merged file

### ISSUE THREAD

**Issue by briantse100** [BVLC/caffe#5415]
I need to make a tool which can write a file including caffemodel and meanfile.  Read one caffemodel and one  meanfile, merge them to one file successfully by calling the protobuffer API ReadProtoFromBinaryFile and WriteProtoToTextFile. But how to analyse the merged file? I try to define one class MergeParameter which inherits the google::protobuf::Message. The MergeParameter includes two variables NetParameter and BlobProto. But it doesnot success. Does it has anyother solution? Thanks!

**Comment by shelhamer** [comment]
The proto definition is extended by editing `caffe.proto`, not by editing the generated code or inheriting from protobuf classes.

Please discuss this further on the mailing list.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
