### ISSUE TITLE
F0316 20:32:57.644039 22666 syncedmem.hpp:39] Check failed: error == cudaSuccess (29 vs. 0)  driver shutting down

### ISSUE THREAD

**Issue by zgsxwsdxg** [BVLC/caffe#5416]
HI，my configuration environment as follow：
Operating system: ubuntu16.04
Compiler: 5.4.0
CUDA version (if applicable): gtx1080
CUDNN version (if applicable): 5.0
BLAS: openblas

When I use my pre-trianed model to classifiy image, error has occurred as follow：

WARNING: Logging before InitGoogleLogging() is written to STDERR
F0316 20:32:57.644039 22666 syncedmem.hpp:39] Check failed: error == cudaSuccess (29 vs. 0)  driver shutting down
*** Check failure stack trace: ***
    @     0x7f777bc515cd  google::LogMessage::Fail()
    @     0x7f777bc53433  google::LogMessage::SendToLog()
    @     0x7f777bc5115b  google::LogMessage::Flush()
    @     0x7f777bc53e1e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f777a016293  caffe::SyncedMemory::~SyncedMemory()
    @     0x7f777a0b9952  boost::detail::sp_counted_impl_p<>::dispose()
    @     0x7f7779fa906a  boost::detail::sp_counted_base::release()
    @     0x7f7779fa946d  boost::detail::sp_counted_impl_p<>::dispose()
    @     0x7f7779fa906a  boost::detail::sp_counted_base::release()
    @     0x7f7779fb63bc  caffe::Net<>::~Net()
    @     0x7f7779fb6639  caffe::Net<>::~Net()
    @           0x42a951  boost::checked_delete<>()
    @           0x42c6ae  boost::detail::sp_counted_impl_p<>::dispose()
    @           0x423ad6  boost::detail::sp_counted_base::release()
    @           0x423b69  boost::detail::shared_count::~shared_count()
    @           0x424126  boost::shared_ptr<>::~shared_ptr()
    @           0x420151  Classifier::~Classifier()
    @     0x7f77791ffff8  (unknown)
    @     0x7f7779200045  exit
    @     0x7f77791e6837  __libc_start_main
    @           0x41f2a9  _start
    @              (nil)  (unknown)
Aborted (core dumped)

who can help me？ thanks.

**Comment by Lyken17** [comment]
what's your output for command "nvidia-smi" and "nvcc --version"?

**Comment by zgsxwsdxg** [comment]
Hi lyken,
my nvidia-smi output as follow:
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 375.26                 Driver Version: 375.26                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1080    Off  | 0000:01:00.0      On |                  N/A |
| 42%   28C    P8    12W / 200W |    186MiB /  8105MiB |      1%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0       936    G   /usr/lib/xorg/Xorg                             141MiB |
|    0      1825    G   compiz                                          42MiB |
+-----------------------------------------------------------------------------+

my nvcc --version as follow:
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Tue_Jan_10_13:22:03_CST_2017
Cuda compilation tools, release 8.0, V8.0.61

**Comment by zgsxwsdxg** [comment]
@Lyken17 
Hi，my nvidia-smi output as follow:
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 375.26 Driver Version: 375.26 |
|-------------------------------+----------------------+----------------------+
| GPU Name Persistence-M| Bus-Id Disp.A | Volatile Uncorr. ECC |
| Fan Temp Perf Pwr:Usage/Cap| Memory-Usage | GPU-Util Compute M. |
|===============================+======================+======================|
| 0 GeForce GTX 1080 Off | 0000:01:00.0 On | N/A |
| 42% 28C P8 12W / 200W | 186MiB / 8105MiB | 1% Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes: GPU Memory |
| GPU PID Type Process name Usage |
|=============================================================================|
| 0 936 G /usr/lib/xorg/Xorg 141MiB |
| 0 1825 G compiz 42MiB |
+-----------------------------------------------------------------------------+

my nvcc --version as follow:
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Tue_Jan_10_13:22:03_CST_2017
Cuda compilation tools, release 8.0, V8.0.61

**Comment by Lyken17** [comment]
seems your cuda have been installed properly. It is weird, because "error == cudaSuccess" is usually caused by GPU driver.

Two potential reasons, first, try to run `make runtest -j$(nproc)` under caffe root. If tests all pass, then it should be caused by your model.

**Comment by zgsxwsdxg** [comment]
@Lyken17 
Hi, thank for you.
first, I run make runtest -j$(nproc) , status is successful.
second, I use my pre-trianed model to classifiy image, the model can predict right result. But only after it shows result, the error occurs.I don.t know why it causes.

Best wishes.

**Comment by Lyken17** [comment]
Then I have no idea what is happening before you provide more details about your code.

Your log shows the cuda runtime error (29), maybe the cuda official doc will help you.

**Comment by shelhamer** [comment]
As mentioned, this seems to be a driver rather than Caffe issue.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
