### ISSUE TITLE
How to see C++ function invocations behind the python interface

### ISSUE THREAD

**Issue by chakpongchung** [BVLC/caffe#5421]
https://github.com/rmekdma/python_misc/blob/master/caffe/caffe_ftr.py

I need to do some system integration in C++(has to be) and the whole details in C++ of  python code. Given the above caffe code,

how can I track the C++ code being used behind each caffe function in python?

Can I generate the C++ code so that I can compile and run?

Similarly, it will be interesting to know whether I can do the same from python to c++ in tensorflow , mxnet or other python binding code, if it is easier to do it than caffe.

Here is a sister problem in tensorflow:

http://stackoverflow.com/questions/41210347/how-to-see-c-function-invocations-behind-the-swig-interface-tensorflow

**Comment by yangbo** [comment]
Caffe python wrapper use Boost.Python to bridge C++ and Python, so you can write c++ and using boost-python to wrapper it just like Caffe python wrapper. The Boost.Python code of caffe is '<caffe>/python/caffe/_caffe.cpp'.

Hope this help, cheers.

**Comment by chakpongchung** [comment]
For example, 
https://github.com/rmekdma/python_misc/blob/master/caffe/caffe_ftr.py
line 197 in the link above: scores = net.predict(img_batch, oversample=False)

I tried to track all the way down to this:

   `self._forward(start_ind, end_ind)` 
**python/caffe/pycaffe.py:131:    self._forward(start_ind, end_ind)**

Then I used 
**grep -inr "_forward("**


found no place for this definition. Anything wrong in my search?

**Comment by shelhamer** [comment]
I don't know of particular tools to bridge boost-python and python, sorry.
