### ISSUE TITLE
unable to use multi cpu on google cloud

### ISSUE THREAD

**Issue by karandeepdps** [BVLC/caffe#5423]
I tried every method still i am not able to use all the cpu's can someone guide me.

**Comment by shelhamer** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
