### ISSUE TITLE
get error when training mnist use amd card MacBook pro [opencl]

### ISSUE THREAD

**Issue by iamqk** [BVLC/caffe#5424]
### Steps to reproduce
compiled with configure ：

```
## Refer to http://caffe.berkeleyvision.org/installation.html
# Contributions simplifying and improving our build system are welcome!

# 32 bit / 64 bit indexing
# USE_INDEX_64 := 1

# GreenTea (ViennaCL/OpenCL) backend switch

# Enable the CUDA backend
# USE_CUDA := 1

# Enable the OpenCL/Greentea backend
USE_GREENTEA := 1
DISABLE_DEVICE_HOST_UNIFIED_MEMORY := 0
# Enable the Greentea-LibDNN convolution backend
# USE_LIBDNN := 1

# Enable the Intel spatial convolutions
# USE_INTEL_SPATIAL := 1

# Folder of the ViennaCL header-only library
VIENNACL_DIR = ../ViennaCL

# Override BLAS, use CLBlast instead of ViennacLBLAS.
# USE_CLBLAST := 1
# Custom CLBlast lib and include directories.
# CLBLAST_INCLUDE := /usr/local/include
# CLBLAST_LIB     := /usr/local/lib

# Override BLAS, use clBLAS insead of ViennaclBLAS.
#USE_CLBLAS := 1
# Custom clBLAS lib and include directories.
#CLBLAS_INCLUDE := /usr/local/include
#CLBLAS_LIB     := /usr/local/lib

# Override BLAS, use ISAAC instead of ViennaclBLAS.
# USE_ISAAC := 1

# Uncomment for FFT
# USE_FFT := 1

# cuDNN acceleration switch (uncomment to build with cuDNN).
# USE_CUDNN := 1

# CPU-only switch (uncomment to build without GPU support).
# CPU_ONLY := 1

# CPU OpenMP switch. Do not use OpenMP on dual socket systems!
USE_OPENMP := 1

# uncomment to disable IO dependencies and corresponding data layers
# USE_OPENCV := 0
USE_LEVELDB := 1
USE_LMDB := 1
# This code is taken from https://github.com/sh1r0/caffe-android-lib
# USE_HDF5 := 0

# uncomment to allow MDB_NOLOCK when reading LMDB files (only if necessary)
#	You should not set this flag if you will be reading LMDBs with any
#	possibility of simultaneous read and write
# ALLOW_LMDB_NOLOCK := 1

# Uncomment if you're using OpenCV 3
# OPENCV_VERSION := 3

# To customize your choice of compiler, uncomment and set the following.
# N.B. the default for Linux is g++ and the default for OSX is clang++
# CUSTOM_CXX := g++

# CUDA directory contains bin/ and lib/ directories that we need.
CUDA_DIR := /usr/local/cuda
# On Ubuntu 14.04, if cuda tools are installed via
# "sudo apt-get install nvidia-cuda-toolkit" then use this instead:
# CUDA_DIR := /usr

# CUDA architecture setting: going with all of them.
# For CUDA < 6.0, comment the *_50 through *_61 lines for compatibility.
# For CUDA < 8.0, comment the *_60 and *_61 lines for compatibility.
CUDA_ARCH := -gencode arch=compute_20,code=sm_20 \
		-gencode arch=compute_20,code=sm_21 \
		-gencode arch=compute_30,code=sm_30 \
		-gencode arch=compute_35,code=sm_35 \
		-gencode arch=compute_50,code=sm_50 \
		-gencode arch=compute_52,code=sm_52 \
		-gencode arch=compute_60,code=sm_60 \
		-gencode arch=compute_61,code=sm_61 \
		-gencode arch=compute_61,code=compute_61

# BLAS choice:
# atlas for ATLAS (default)
# mkl for MKL
# open for OpenBlas
BLAS := atlas
# Custom (MKL/ATLAS/OpenBLAS) include and lib directories.
# Leave commented to accept the defaults for your choice of BLAS
# (which should work)!
# BLAS_INCLUDE := /path/to/your/blas
# BLAS_LIB := /path/to/your/blas

# Homebrew puts openblas in a directory that is not on the standard search path
# BLAS_INCLUDE := $(shell brew --prefix openblas)/include
# BLAS_LIB := $(shell brew --prefix openblas)/lib

# This is required only if you will compile the matlab interface.
# MATLAB directory should contain the mex binary in /bin.
# MATLAB_DIR := /usr/local
# MATLAB_DIR := /Applications/MATLAB_R2012b.app

# NOTE: this is required only if you will compile the python interface.
# We need to be able to find Python.h and numpy/arrayobject.h.
PYTHON_INCLUDE := /usr/include/python2.7 \
		/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/numpy/core/include/numpy
# by qk
#		/usr/lib/python2.7/dist-packages/numpy/core/include

# Anaconda Python distribution is quite popular. Include path:
# Verify anaconda location, sometimes it's in root.
# ANACONDA_HOME := $(HOME)/anaconda
# PYTHON_INCLUDE := $(ANACONDA_HOME)/include \
		# $(ANACONDA_HOME)/include/python2.7 \
		# $(ANACONDA_HOME)/lib/python2.7/site-packages/numpy/core/include

# Uncomment to use Python 3 (default is Python 2)
# PYTHON_LIBRARIES := boost_python3 python3.5m
# PYTHON_INCLUDE := /usr/include/python3.5m \
#                 /usr/lib/python3.5/dist-packages/numpy/core/include

# We need to be able to find libpythonX.X.so or .dylib.
PYTHON_LIB := /usr/lib
# PYTHON_LIB := $(ANACONDA_HOME)/lib

# Homebrew installs numpy in a non standard path (keg only)
# PYTHON_INCLUDE += $(dir $(shell python -c 'import numpy.core; print(numpy.core.__file__)'))/include
# PYTHON_LIB += $(shell brew --prefix numpy)/lib

# Uncomment to support layers written in Python (will link against Python libs)
# WITH_PYTHON_LAYER := 1

# Whatever else you find you need goes here.
INCLUDE_DIRS := $(PYTHON_INCLUDE) /usr/local/include
LIBRARY_DIRS := $(PYTHON_LIB) /usr/local/lib /usr/lib

# If Homebrew is installed at a non standard location (for example your home directory) and you use it for general dependencies
# INCLUDE_DIRS += $(shell brew --prefix)/include
# LIBRARY_DIRS += $(shell brew --prefix)/lib

# NCCL acceleration switch (uncomment to build with NCCL)
# https://github.com/NVIDIA/nccl (last tested version: v1.2.3-1+cuda8.0)
# USE_NCCL := 1

# Uncomment to use `pkg-config` to specify OpenCV library paths.
# (Usually not necessary -- OpenCV libraries are normally installed in one of the above $LIBRARY_DIRS.)
# USE_PKG_CONFIG := 1

# N.B. both build and distribute dirs are cleared on `make clean`
BUILD_DIR := build
DISTRIBUTE_DIR := distribute

# Uncomment for debugging. Does not work on OSX due to https://github.com/BVLC/caffe/issues/171
# DEBUG := 1
# VIENNACL_DEBUG := 0

# The ID of the GPU that 'make runtest' will use to run unit tests.
TEST_GPUID := 0

# enable pretty build (comment to see full commands)
Q ?= @


```

then modified /examples/mnist/train_lenet.sh 
./build/tools/caffe train -gpu "2" --solver=examples/mnist/lenet_solver.prototxt $@

then ./examples/mnist/train_lenet.sh 
get error:
ViennaCL: FATAL ERROR: Could not find kernel 'null_kernel_float' from program ''
Number of kernels in program: 0
libc++abi.dylib: terminating with uncaught exception of type viennacl::ocl::kernel_not_found: Kernel not found
*** Aborted at 1489930395 (unix time) try "date -d @1489930395" if you are using GNU date ***
PC: @     0x7fffb0d74dd6 __pthread_kill
*** SIGABRT (@0x7fffb0d74dd6) received by PID 41240 (TID 0x7fffb9a933c0) stack trace: ***
    @     0x7fffb0e53bba _sigtramp
    @        0x4b9a77240 (unknown)
    @     0x7fffb0cda420 abort
    @     0x7fffaf83585a abort_message
    @     0x7fffaf85ac37 default_terminate_handler()
    @     0x7fffb0364f33 _objc_terminate()
    @     0x7fffaf857d69 std::__terminate()
    @     0x7fffaf8577de __cxa_throw
    @        0x10dea61c2 viennacl::ocl::program::get_kernel()
    @        0x10dfefea7 caffe::Timer::Start()
    @        0x10dfdb88a caffe::Solver<>::Step()
    @        0x10dfdb3ed caffe::Solver<>::Solve()
    @        0x10ddaa80d train()
    @        0x10ddad51a main
    @     0x7fffb0c46255 start
./examples/mnist/train_lenet.sh: line 4: 41240 Abort trap: 6           ./build/tools/caffe train -gpu "2" --solver=examples/mnist/lenet_solver.prototxt $@

### Your system configuration
Operating system:
mac os 10.12.3
amd m370x
Compiler:
CUDA version (if applicable): 8.0.61 (brew install)
CUDNN version (if applicable):?
BLAS:?

**Comment by iamqk** [comment]
I0319 21:40:48.052963 3114873792 common.cpp:379] Total devices: 3
I0319 21:40:48.053529 3114873792 common.cpp:380] CUDA devices: 0
I0319 21:40:48.053536 3114873792 common.cpp:381] OpenCL devices: 3
I0319 21:40:48.053540 3114873792 common.cpp:405] Device id:                     0
I0319 21:40:48.053544 3114873792 common.cpp:407] Device backend:                OpenCL
I0319 21:40:48.053546 3114873792 common.cpp:409] Backend details:               Apple: OpenCL 1.2 (Jan  4 2017 22:35:59)
I0319 21:40:48.053575 3114873792 common.cpp:411] Device vendor:                 Intel
I0319 21:40:48.053581 3114873792 common.cpp:413] Name:                          Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
I0319 21:40:48.053586 3114873792 common.cpp:415] Total global memory:           17179869184
I0319 21:40:48.053591 3114873792 common.cpp:405] Device id:                     1
I0319 21:40:48.053593 3114873792 common.cpp:407] Device backend:                OpenCL
I0319 21:40:48.053596 3114873792 common.cpp:409] Backend details:               Apple: OpenCL 1.2 (Jan  4 2017 22:35:59)
I0319 21:40:48.053601 3114873792 common.cpp:411] Device vendor:                 Intel
I0319 21:40:48.053604 3114873792 common.cpp:413] Name:                          Iris Pro
I0319 21:40:48.053608 3114873792 common.cpp:415] Total global memory:           1610612736
I0319 21:40:48.053612 3114873792 common.cpp:405] Device id:                     2
I0319 21:40:48.053617 3114873792 common.cpp:407] Device backend:                OpenCL
I0319 21:40:48.053619 3114873792 common.cpp:409] Backend details:               Apple: OpenCL 1.2 (Jan  4 2017 22:35:59)
I0319 21:40:48.053623 3114873792 common.cpp:411] Device vendor:                 AMD
I0319 21:40:48.053627 3114873792 common.cpp:413] Name:                          AMD Radeon R9 M370X Compute Engine
I0319 21:40:48.053630 3114873792 common.cpp:415] Total global memory:           2147483648

**Comment by iamqk** [comment]
src/caffe/test/test_ocl_kernel_compile.cpp:79: Failure
Value of: failure
  Actual: true
Expected: false
[  FAILED  ] OpenCLKernelCompileTest/1.TestCompile, where TypeParam = d (10712 ms)
[----------] 1 test from OpenCLKernelCompileTest/1 (10712 ms total)

[----------] Global test environment tear-down
[==========] 2 tests from 2 test cases ran. (30379 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 2 tests, listed below:
[  FAILED  ] OpenCLKernelCompileTest/0.TestCompile, where TypeParam = f
[  FAILED  ] OpenCLKernelCompileTest/1.TestCompile, where TypeParam = d

 2 FAILED TESTS

**Comment by naibaf7** [comment]
Okay please reformat the first post, it's almost unbearable to read.
Try the following:
- Compile with USE_CUDA := 0, USE_INDEX_64 := 0 and USE_NCCL:= 0, only enable OpenCL.
- Uninstall CUDA from your system (it's not needed or useful).
- Try to use device 0 and 1, if they work there's probably a faulty driver for device 2.
- Make sure you grab the latest viennacl-dev from here: https://github.com/viennacl/viennacl-dev

Unfortunately I don't have any Mac devices myself, so I can't reproduce the error. Please report back after you've done the steps above.

**Comment by iamqk** [comment]
then modified /examples/mnist/train_lenet.sh
./build/tools/caffe train -gpu "2" --solver=examples/mnist/lenet_solver.prototxt $@

only use AMD card still failed
```
I0320 08:59:49.383883 2978980800 solver.cpp:296] Solving LeNet
I0320 08:59:49.383888 2978980800 solver.cpp:297] Learning Rate Policy: inv
ViennaCL: FATAL ERROR: Could not find kernel 'null_kernel_float' from program ''
Number of kernels in program: 0
libc++abi.dylib: terminating with uncaught exception of type viennacl::ocl::kernel_not_found: Kernel not found
*** Aborted at 1489971589 (unix time) try "date -d @1489971589" if you are using GNU date ***
PC: @     0x7fffa8bdbdd6 __pthread_kill
*** SIGABRT (@0x7fffa8bdbdd6) received by PID 31101 (TID 0x7fffb18fa3c0) stack trace: ***
    @     0x7fffa8cbabba _sigtramp
    @        0x4b18de240 (unknown)
    @     0x7fffa8b41420 abort
    @     0x7fffa769c85a abort_message
    @     0x7fffa76c1c37 default_terminate_handler()
    @     0x7fffa81cbf33 _objc_terminate()
    @     0x7fffa76bed69 std::__terminate()
    @     0x7fffa76be7de __cxa_throw
    @        0x10607ec62 viennacl::ocl::program::get_kernel()
    @        0x1061c99f7 caffe::Timer::Start()
    @        0x1061b53da caffe::Solver<>::Step()
    @        0x1061b4f3d caffe::Solver<>::Solve()
    @        0x105f8880d train()
    @        0x105f8b51a main
    @     0x7fffa8aad255 start
./examples/mnist/train_lenet.sh: line 4: 31101 Abort trap: 6           ./build/tools/caffe train -gpu "2" --solver=examples/mnist/lenet_solver.prototxt $@
```


only use Intel cpu or Iris Pro successes

any combination(two or three card) stop quickly like  follows:
```
I0320 08:58:47.581748 2978980800 net.cpp:223] mnist does not need backward computation.
I0320 08:58:47.581750 2978980800 net.cpp:266] This network produces output accuracy
I0320 08:58:47.581754 2978980800 net.cpp:266] This network produces output loss
I0320 08:58:47.581835 2978980800 net.cpp:280] Network initialization done.
I0320 08:58:47.581856 2978980800 net.cpp:281] Memory required for data: 8086808
I0320 08:58:47.581910 2978980800 solver.cpp:65] Solver scaffolding done.
I0320 08:58:47.582005 2978980800 caffe.cpp:272] Starting Optimization
I0320 08:58:47.582010 2978980800 caffe.cpp:285] Optimization Done.
```

**Comment by iamqk** [comment]
./build/test/test_all.testbin --gtest_filter=*OpenCLKernelCompileTest* 2
still failed

```
[----------] Global test environment tear-down
[==========] 2 tests from 2 test cases ran. (40232 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 2 tests, listed below:
[  FAILED  ] OpenCLKernelCompileTest/0.TestCompile, where TypeParam = f
[  FAILED  ] OpenCLKernelCompileTest/1.TestCompile, where TypeParam = d

 2 FAILED TESTS

```

**Comment by iamqk** [comment]
strange ：
when i modify lenet_solver.prototxt and remove -gpu option in /examples/mnist/train_lenet.sh
found solver_mode: CPU is faster than solver_mode: GPU

**Comment by naibaf7** [comment]
@iamqk 
OK this seems like a very Mac specific issue. I'm afraid it seems like Apple has broken OpenCL support for OS X, so this is not a Caffe issue, and you might have to look 
https://forums.developer.apple.com/thread/12034
One way you can test this is download another OpenCL software and test it on your Mac with the AMD GPU. If it also fails, this confirms the problem. Some possibilities:
https://www.tonymacx86.com/threads/apples-opengl-opencl-test-app-galaxies.98626/
Or you can also compile the ViennaCL examples and try to run them.

Yes you might get faster CPU solver if the GPU you use is slow (onboard GPU) or you use GPU mode on the CPU. The AMD GPU however should be much faster. And the Intel onboard GPU with intel_spatial kernels enabled should also be much faster in inference (but not necessarily training).

**Comment by iamqk** [comment]
@naibaf7 
many thx for you help

**Comment by iamqk** [comment]
error goes with sierra 10.12.4 updated
it seems apple fix OpenCL drive in this version

**Comment by naibaf7** [comment]
Great, good to know :)

**Comment by xiaoyunl** [comment]
ViennaCL: FATAL ERROR: Could not find kernel 'null_kernel_float' from program '' 
Have you solved this problem? I have the  same problem with you.can you tell me how to solve it @iamqk

**Comment by iamqk** [comment]
@xiaoyunl  
error goes with sierra 10.12.4 updated
it seems apple fix OpenCL drive in this version

**Comment by soulslicer** [comment]
Hi Guys, is OpenCL still broken on OSX?
