### ISSUE TITLE
 __version__ to return current caffe version.

### ISSUE THREAD

**Issue by shanYanGuan** [BVLC/caffe#5426]
Due to mystudy,I need to change the caffe version.But I don't know which places I need to rewrite.

could you help me?

Operating system:ubuntu 16.04

**Comment by deepali-c** [comment]
Please update `CAFFE_TARGET_VERSION` and `CAFFE_TARGET_SOVERSION`  in `CMakeLists.txt` and `DYNAMIC_VERSION_REVISION` in `Makefile`.

**Comment by shanYanGuan** [comment]
YEAH! It worked,thank you very much!

And I take another method to solve this question.Just change CAFFE_VERSION in /python/caffe/_caffe.cpp
`  bp::scope().attr("__version__") = AS_STRING(CAFFE_VERSION);` .
