### ISSUE TITLE
Issue in compiling Caffe 

### ISSUE THREAD

**Issue by shariquesha** [BVLC/caffe#5427]
Operating system: Ubuntu 14.04
Compiler:Python 2.7.6
CUDA version : 8.0.61-1

after executing make command i got this error

CXX src/caffe/layer_factory.cpp
In file included from ./include/caffe/blob.hpp:8:0,
                 from ./include/caffe/layer.hpp:8,
                 from src/caffe/layer_factory.cpp:8:
./include/caffe/common.hpp:4:32: fatal error: boost/shared_ptr.hpp: No such file or directory
 #include <boost/shared_ptr.hpp>
                                ^
compilation terminated.
make: *** [.build_release/src/caffe/layer_factory.o] Error 1

**Comment by shelhamer** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
