### ISSUE TITLE
Windows branch build failed using commit SHA-1: ca360a148f70a254a7246490eccc85905e75afa0

### ISSUE THREAD

**Issue by XupingZHENG** [BVLC/caffe#5430]
### Issue summary
running of scripts\win_build.bat failed at almost the last step, command window outputs something as follows:
“E:\CaffeWindows\caffeCUDA-\build\ALL_BUILD.vcxproj”(默认目标) (1) ->
“E:\CaffeWindows\caffeCUDA-\build\src\caffe\caffe.vcxproj”(默认目标) (3) ->
(ClCompile 目标) ->
  C:\Users\Wenba\.caffe\dependencies\libraries_v120_x64_py27_1.1.0\libraries\include\boost-1_61\boost/type_traits/common_type.hpp(43): fatal error C1001: An internal error has occurred in the compiler. [E:\CaffeWindows\caffeCUDA-\build\src\caffe\caffe.vcxproj]

    7056 个警告 :: 7056 wanrings
    1 个错误 :: 1 error

已用时间 00:07:08.34
ERROR: Build failed

### Steps to reproduce

build using commit  on March 17, 2017
SHA-1: ca360a148f70a254a7246490eccc85905e75afa0

### Your system configuration

Operating system: Windows7 x64
Compiler: MSVC 2013
CUDA version: 8.0
CUDNN version: None
BLAS: prebuilt dependencies
Python version: 2.7

-- ******************* Caffe Configuration Summary *******************
-- General:
--   Version           :   1.0.0-rc5
--   Git               :   unknown
--   System            :   Windows
--   C++ compiler      :   C:/Program Files (x86)/Microsoft Visual Studio 12.0/VC/bin/x86_amd64/cl.exe
--   Release CXX flags :   /MD /O2 /Ob2 /DNDEBUG /DWIN32 /D_WINDOWS /W3 /GR /EHsc
--   Debug CXX flags   :   /D_DEBUG /MDd /Zi /Ob0 /Od /RTC1 /DWIN32 /D_WINDOWS /W3 /GR /EHsc
--   Build type        :   Release
--
--   BUILD_SHARED_LIBS :   0
--   BUILD_python      :   1
--   BUILD_matlab      :   0
--   BUILD_docs        :
--   CPU_ONLY          :   0
--   USE_OPENCV        :   ON
--   USE_LEVELDB       :   ON
--   USE_LMDB          :   ON
--   USE_NCCL          :   0
--   ALLOW_LMDB_NOLOCK :   OFF
--
-- Dependencies:
--   BLAS              :   Yes (Open)
--   Boost             :   Yes (ver. 1.61)
--   glog              :   Yes
--   gflags            :   Yes
--   protobuf          :   Yes (ver. 3.1.0)
--   lmdb              :   Yes (ver. 0.9.70)
--   LevelDB           :   Yes (ver. 1.18)
--   Snappy            :   Yes (ver. 1.1.1)
--   OpenCV            :   Yes (ver. 3.1.0)
--   CUDA              :   Yes (ver. 8.0)
--
-- NVIDIA CUDA:
--   Target GPU(s)     :   Auto
--   GPU arch(s)       :   sm_52
--   cuDNN             :   Not found
--
-- Python:
--   Interpreter       :   D:/Anaconda2/python.exe (ver. 2.7.13)
--   Libraries         :   D:/Anaconda2/libs/python27.lib (ver 2.7.13)
--   NumPy             :   D:/Anaconda2/lib/site-packages/numpy/core/include (ver 1.11.3)
--
-- Install:
--   Install path      :   E:/CaffeWindows/caffeCUDA-/build/install
--

**Comment by willyd** [comment]
What is your full compiler version (with update)? In a visual studio command prompt what is the output of the cl.exe command.

**Comment by willyd** [comment]
The problem might be related to this line https://github.com/BVLC/caffe/blob/windows/cmake/Dependencies.cmake#L13

**Comment by XupingZHENG** [comment]
cl.exe version is 18.00.21005.1
My dev tools worked well on an earlier commit on Feb 19 2017 SHA-1: cc0614d34794eaa0772303eb1c428c9c13479c9e
I noticed that some cmake files changed a lot since then.

**Comment by willyd** [comment]
Ok. Can you try with this [branch](https://github.com/willyd/caffe/tree/vs2013-up5-fix) and see if this issue is gone?

**Comment by XupingZHENG** [comment]
@willyd  Build succeeded, thank you! :)

**Comment by willyd** [comment]
Thanks. I will merge the change in.

**Comment by willyd** [comment]
Fixed by 5441.
