### ISSUE TITLE
can not import caffe in python2.7

### ISSUE THREAD

**Issue by kli017** [BVLC/caffe#5431]
Please use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) for usage, installation, or modeling questions, or other requests for help.
_Do not post such requests to Issues._ Doing so interferes with the development of Caffe.

Please read the [guidelines for contributing](https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md) before submitting this issue.

### Issue summary
I compiled caffe under windows7. 
After I copy the caffe folder to site-pakeges and import caffe the cmd seems down like this...and i can not input any command anymore

![image](https://cloud.githubusercontent.com/assets/14877573/24186427/30c56008-0f13-11e7-9767-4fd06d1161b7.png)

### Steps to reproduce

If you are having difficulty building Caffe or training a model, please ask the caffe-users mailing list. If you are reporting a build error that seems to be due to a bug in Caffe, please attach your build configuration (either Makefile.config or CMakeCache.txt) and the output of the make (or cmake) command.

### Your system configuration
Operating system:
Compiler:
CUDA version (if applicable):
CUDNN version (if applicable):
BLAS:
Python or MATLAB version (for pycaffe and matcaffe respectively):

**Comment by williford** [comment]
Please ask your question on the [Caffe user mailing list](https://groups.google.com/forum/#!forum/caffe-users) or http://stackoverflow.com/.

You can then provide the link for your question on this thread. I will try to follow up, although if it is a Windows specific issue I may not be able to help.
