### ISSUE TITLE
Feature request: Export CMake targets 

### ISSUE THREAD

**Issue by jasjuang** [BVLC/caffe#5436]
### Issue summary

Please add in the functionality to [export](https://cmake.org/Wiki/CMake/Tutorials/Exporting_and_Importing_Targets) CMake targets when `sudo make install` is invoked. This will enable external users to directly use caffe with `find_package` of cmake in [config](https://cmake.org/cmake/help/v3.0/command/find_package.html) mode, for example 

``````
find_package(Caffe REQUIRED)
target_link_libraries(${PROJECT_NAME} Caffe)
``````

Now I had to write my own FindCaffe.cmake and manually find where caffe is installed in order to use `find_package` of cmake in module mode, which is very inconvenient.

### Your system configuration
Operating system: Ubuntu 16.04
Compiler: GCC 5.4
CUDA version: 8.0

**Comment by hgaiser** [comment]
Wouldn't this work:

```
target_link_libraries(${PROJECT_NAME} ${Caffe_LIBRARIES})
```

It seems to work for me in [this](https://github.com/delftrobotics-forks/caffe/blob/layer-modules/examples/modular_layer/CMakeLists.txt) code.

**Comment by jasjuang** [comment]
@hgaiser That is within the Caffe repository, hence it recognize the target. If you do it in your own repository `find_package(Caffe REQUIRED)` won't work unless you write your own `FindCaffe.cmake`

**Comment by hgaiser** [comment]
It looks as if it is within the Caffe repository but it is a separate project. Similar code is [here](https://github.com/delftrobotics-forks/py-faster-rcnn/blob/layer-modules/lib/faster_rcnn/CMakeLists.txt), which definitely isn't in the Caffe repository.

**Comment by jasjuang** [comment]
I cloned and compile the code. It shows the below for me

``````
CMake Error at CMakeLists.txt:6 (find_package):
  By not providing "FindCaffe.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Caffe", but
  CMake did not find one.

  Could not find a package configuration file provided by "Caffe" with any of
  the following names:

    CaffeConfig.cmake
    caffe-config.cmake

  Add the installation prefix of "Caffe" to CMAKE_PREFIX_PATH or set
  "Caffe_DIR" to a directory containing one of the above files.  If "Caffe"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring incomplete, errors occurred!
See also "/home/jasjuang/test/py-faster-rcnn/lib/faster_rcnn/build/CMakeFiles/CMakeOutput.log".
``````

**Comment by hgaiser** [comment]
But in that case you don't have Caffe as a system package? I have a file `/usr/share/Caffe/CaffeConfig.cmake` which is used to locate Caffe. Do you have Caffe installed as a system package or did you compile it locally?

**Comment by jasjuang** [comment]
You are right, so Caffe actually does export targets, thanks for your help. Now I just hope someone will merge https://github.com/BVLC/caffe/pull/3825 so it won't be such a trouble to uninstall Caffe when it's installed as a system package.
