### ISSUE TITLE
ShareInParallel() needs to be removed?

### ISSUE THREAD

**Issue by ZoroDerVonCodier** [BVLC/caffe#5446]
Since ShareInParallel() has been removed from layer.hpp, shouldn't it also be removed from the files listed below as well?

base_data_layer.hpp
data_layer.hpp
dummy_data_layer.hpp
hdf5_data_layer.hpp
hdf5_output_layer.hpp
input_layer.hpp
python_layer.hpp

**Comment by cypof** [comment]
You're right, thanks for pointing out.

**Comment by shelhamer** [comment]
@cypof could you make this change?
