### ISSUE TITLE
Error when upgrade a train_val.prototxt file for the new version.

### ISSUE THREAD

**Issue by wanger-02** [BVLC/caffe#5459]
I want  to upgrade a train file for eailer version of caffe. But got some errors. anyone could help me  to solve it?

     upgrade_net_proto_text-d.exe D:/net_train_val.prototxt b.prototxt
     [libprotobuf ERROR C:\Users\guillaume\work\caffe-  builder\build_v140_x64\packages\protobuf\protobuf_download- prefix\src\protobuf_download\src\google\protobuf\text_format.cc:298] Error parsing text-format  caffe.NetParameter: 16:15: Message type "caffe.TransformationParameter" has no field named "fixed_crop".
    E0328 23:01:38.529631 10972 upgrade_net_proto_text.cpp:30] Failed to parse input text file as  NetParameter: D:/net_train_val.prototxt

**Comment by williford** [comment]
Are you sure it works for older versions of Caffe (and not a fork)? It seems the error message is pretty straight forward. Where does the fixed_crop parameter come from?

Please ask your question on the [Caffe user mailing list](https://groups.google.com/forum/#!forum/caffe-users) or on another website, such as http://stackoverflow.com/.

> Please use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) for usage, installation, or modeling questions, or other requests for help.
> _Do not post such requests to Issues._ Doing so interferes with the development of Caffe.
