### ISSUE TITLE
Wrong result with the classification.bin

### ISSUE THREAD

**Issue by leaderofring** [BVLC/caffe#5463]
Hi,
I have trained a caffemodel for my own images.
I convert my images into LMDB.
And i get a 100% accuracy on my test images.
But when i test one picture on the caffemodel with the "classification.bin", i can't get the right answer.
What is the problem with the "classification.bin"?

**Comment by williford** [comment]
Please ask your question on the [Caffe user mailing list](https://groups.google.com/forum/#!forum/caffe-users) or on another website, such as http://stackoverflow.com/ or http://stats.stackexchange.com/.

> Please use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) for usage, installation, or modeling questions, or other requests for help.
> _Do not post such requests to Issues._ Doing so interferes with the development of Caffe.
