### ISSUE TITLE
TestPReLUForward failure on CPU

### ISSUE THREAD

**Issue by 389148742** [BVLC/caffe#5465]
[----------] Global test environment tear-down
[==========] 1104 tests from 150 test cases ran. (158443 ms total)
[  PASSED  ] 1103 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] NeuronLayerTest/0.TestPReLUForward, where TypeParam = caffe::CPUDevice<float>

 1 FAILED TEST
src/caffe/test/CMakeFiles/runtest.dir/build.make:57: recipe for target 'src/caffe/test/CMakeFiles/runtest' failed
make[3]: *** [src/caffe/test/CMakeFiles/runtest] Error 1
CMakeFiles/Makefile2:362: recipe for target 'src/caffe/test/CMakeFiles/runtest.dir/all' failed
make[2]: *** [src/caffe/test/CMakeFiles/runtest.dir/all] Error 2
CMakeFiles/Makefile2:369: recipe for target 'src/caffe/test/CMakeFiles/runtest.dir/rule' failed
make[1]: *** [src/caffe/test/CMakeFiles/runtest.dir/rule] Error 2
Makefile:253: recipe for target 'runtest' failed
make: *** [runtest] Error 2

**Comment by shelhamer** [comment]
Without system information it's impossible to pinpoint this, but I suspect it's due to a little noise past the test tolerance (especially since this failure isn't seen elsewhere).
