### ISSUE TITLE
Caffe image_data_layer fail to read image for test data

### ISSUE THREAD

**Issue by czkg** [BVLC/caffe#5471]
### Issue summary

When I use image_data_layer to read depth images, everything works fine at first. The prototxt is like this:

    layer {
      name: "data"
      type: "HeatmapImageData"
      top: "data"
      top: "label"
      include { 
        phase: TRAIN
      }
      transform_param {
        mirror: true
        is_rotate: true
        angle: 20
      }
      heatmap_image_data_param {
        source: "/home/zhi/caffe-cz/data/hands/data/80/result.txt"
        root_folder: "/home/zhi/caffe-cz/data/hands/data/80/image/"
        batch_size: 20
        label_height: 40
        label_width: 40
        shuffle: false
      }
    }
    
    layer {
      name: "data"
      type: "HeatmapImageData"
      top: "data"
      top: "label"
      include {
        phase: TEST
      }
      heatmap_image_data_param {
        source: "/home/zhi/caffe-cz/data/hands/test_data/80/result.txt"
        root_folder: "/home/zhi/caffe-cz/data/hands/test_data/80/image/"
        batch_size: 20
        label_height: 40
        label_width: 40
        shuffle: false
      }
    }

At beginning, this works fine, but then I choose another 20 images as test set(I am pretty sure these images are valid), but caffe failed to process and gave the error "OpenCV Error: Assertion failed (!fixedType() || ((Mat*)obj)->type() == mtype) in create", is this a bug?

**Comment by shelhamer** [comment]
This data layer is not part of the Caffe master branch. Please ask the fork author.

Note that the OpenCV assertion is unlikely to be the fault of the Caffe fork, but more likely to be due to loading a format that OpenCV is not compiled for or for an image type that requires special flags.
