### ISSUE TITLE
Question about 0D convolution test.

### ISSUE THREAD

**Issue by tsocha** [BVLC/caffe#5475]
Unit test Test0DConvolution from test_convolution_layer.cpp
I have so questions about it.

1. What is a main purpose of this test?
2. What kind of calculations is done here?
3. Is there any paper You can point me to, describing this idea of 0DConvolution ?

**Comment by jeffdonahue** [comment]
"0D convolution" is "convolution" with no spatial axes: matrix multiplication.  It's there to test the generality of the ND convolution implementation.

> Please use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) for usage, installation, or modeling questions, or other requests for help.
>
> _Do not post such requests to Issues._ Doing so interferes with the development of Caffe.
