### ISSUE TITLE
caffe.managed error while compiling Caffe

### ISSUE THREAD

**Issue by pariay** [BVLC/caffe#5476]
I am beginner and I was trying to install Caffe on windows. I have no Cuda and Cudnn (as GPU), so I changed the CpuOnlyBuild and the UseCuDNN in the CommonSetting.props to be true and false, relatively, as it is mentioned in installation instruction. But I have this error when I am building Caffe. I do not know where I did wrong? 

Severity	Code	Description	Project	File	Line	Suppression State
Error	C2976	'std::array': too few template arguments	caffe.managed	C:\caffe-master\windows\caffe.managed\caffelib.cpp	127	
Error	C2976	'std::array': too few template arguments	caffe.managed	C:\caffe-master\windows\caffe.managed\caffelib.cpp	61	
Error	C3699	'^': cannot use this indirection on type 'std::array'	caffe.managed	C:\caffe-master\windows\caffe.managed\caffelib.cpp	62	
Error	C2976	'std::array': too few template arguments	caffe.managed	C:\caffe-master\windows\caffe.managed\caffelib.cpp	68	
Error	C3699	'^': cannot use this indirection on type 'std::array'	caffe.managed	C:\caffe-master\windows\caffe.managed\caffelib.cpp	68	
Error	C3699	'^': cannot use this indirection on type 'std::array'	caffe.managed	C:\caffe-master\windows\caffe.managed\caffelib.cpp	69	
Error	C3699	'^': cannot use this indirection on type 'std::array'	caffe.managed	C:\caffe-master\windows\caffe.managed\caffelib.cpp	128	
Error	C2976	'std::array': too few template arguments	caffe.managed	C:\caffe-master\windows\caffe.managed\caffelib.cpp	136	
Error	C3699	'^': cannot use this indirection on type 'std::array'	caffe.managed	C:\caffe-master\windows\caffe.managed\caffelib.cpp	136	
Error	C3699	'^': cannot use this indirection on type 'std::array'	caffe.managed	C:\caffe-master\windows\caffe.managed\caffelib.cpp	137	
Error	C2976	'std::array': too few template arguments	caffe.managed	C:\caffe-master\windows\caffe.managed\caffelib.cpp	64	
Error	C2027	use of undefined type 'std::array'	caffe.managed	C:\caffe-master\windows\caffe.managed\caffelib.cpp	64	
Error	C3536	'outputs': cannot be used before it is initialized	caffe.managed	C:\caffe-master\windows\caffe.managed\caffelib.cpp	64	
Error	C2109	subscript requires array or pointer type	caffe.managed	C:\caffe-master\windows\caffe.managed\caffelib.cpp	64	
Error	C2440	'return': cannot convert from 'int' to 'std::array *'	caffe.managed	C:\caffe-master\windows\caffe.managed\caffelib.cpp	65	
Error	C3285	for each statement cannot operate on variables of type 'std::array *'	caffe.managed	C:\caffe-master\windows\caffe.managed\caffelib.cpp	71	
Error	C2065	'name': undeclared identifier	caffe.managed	C:\caffe-master\windows\caffe.managed\caffelib.cpp	72	
Error	C2976	'std::array': too few template arguments	caffe.managed	C:\caffe-master\windows\caffe.managed\caffelib.cpp	74	
Error	C3699	'^': cannot use this indirection on type 'std::array'	caffe.managed	C:\caffe-master\windows\caffe.managed\caffelib.cpp	74	
Error	C2027	use of undefined type 'std::array'	caffe.managed	C:\caffe-master\windows\caffe.managed\caffelib.cpp	74	
Error	C2976	'std::array': too few template arguments	caffe.managed	C:\caffe-master\windows\caffe.managed\caffelib.cpp	78	
Error	C2027	use of undefined type 'std::array'	caffe.managed	C:\caffe-master\windows\caffe.managed\caffelib.cpp	78	
Error	C3536	'values': cannot be used before it is initialized	caffe.managed	C:\caffe-master\windows\caffe.managed\caffelib.cpp	78	
Error	C2109	subscript requires array or pointer type	caffe.managed	C:\caffe-master\windows\caffe.managed\caffelib.cpp	78	
Error	C3536	'outputs': cannot be used before it is initialized	caffe.managed	C:\caffe-master\windows\caffe.managed\caffelib.cpp	79	
Error	C2109	subscript requires array or pointer type	caffe.managed	C:\caffe-master\windows\caffe.managed\caffelib.cpp	79	
Error	C2440	'return': cannot convert from 'int' to 'std::array *'	caffe.managed	C:\caffe-master\windows\caffe.managed\caffelib.cpp	81	
Error	C2976	'std::array': too few template arguments	caffe.managed	C:\caffe-master\windows\caffe.managed\caffelib.cpp	132	
Error	C2027	use of undefined type 'std::array'	caffe.managed	C:\caffe-master\windows\caffe.managed\caffelib.cpp	132	
Error	C3536	'outputs': cannot be used before it is initialized	caffe.managed	C:\caffe-master\windows\caffe.managed\caffelib.cpp	132	
Error	C2109	subscript requires array or pointer type	caffe.managed	C:\caffe-master\windows\caffe.managed\caffelib.cpp	132	
Error	C2440	'return': cannot convert from 'int' to 'std::array *'	caffe.managed	C:\caffe-master\windows\caffe.managed\caffelib.cpp	133	
Error	C3285	for each statement cannot operate on variables of type 'std::array *'	caffe.managed	C:\caffe-master\windows\caffe.managed\caffelib.cpp	141	
Error	C2065	'name': undeclared identifier	caffe.managed	C:\caffe-master\windows\caffe.managed\caffelib.cpp	142	
Error	C2976	'std::array': too few template arguments	caffe.managed	C:\caffe-master\windows\caffe.managed\caffelib.cpp	144	
Error	C3699	'^': cannot use this indirection on type 'std::array'	caffe.managed	C:\caffe-master\windows\caffe.managed\caffelib.cpp	144	
Error	C2027	use of undefined type 'std::array'	caffe.managed	C:\caffe-master\windows\caffe.managed\caffelib.cpp	144	
Error	C2976	'std::array': too few template arguments	caffe.managed	C:\caffe-master\windows\caffe.managed\caffelib.cpp	148	
Error	C2027	use of undefined type 'std::array'	caffe.managed	C:\caffe-master\windows\caffe.managed\caffelib.cpp	148	
Error	C3536	'values': cannot be used before it is initialized	caffe.managed	C:\caffe-master\windows\caffe.managed\caffelib.cpp	148	
Error	C2109	subscript requires array or pointer type	caffe.managed	C:\caffe-master\windows\caffe.managed\caffelib.cpp	148	
Error	C3536	'outputs': cannot be used before it is initialized	caffe.managed	C:\caffe-master\windows\caffe.managed\caffelib.cpp	149	
Error	C2109	subscript requires array or pointer type	caffe.managed	C:\caffe-master\windows\caffe.managed\caffelib.cpp	149	
Error	C2440	'return': cannot convert from 'int' to 'std::array *'	caffe.managed	C:\caffe-master\windows\caffe.managed\caffelib.cpp	151	
Error	C4430	missing type specifier - int assumed. Note: C++ does not support default-int	caffe.managed	C:\caffe-master\windows\caffe.managed\caffelib.cpp	159	
Warning	C4508	'CaffeModel': function should return a value; 'void' return type assumed	caffe.managed	C:\caffe-master\windows\caffe.managed\caffelib.cpp	167	
Error	C4430	missing type specifier - int assumed. Note: C++ does not support default-int	caffe.managed	C:\caffe-master\windows\caffe.managed\caffelib.cpp	175	
Error	C2065	'm_net': undeclared identifier	caffe.managed	C:\caffe-master\windows\caffe.managed\caffelib.cpp	176	
Warning	C4508	'CaffeModel': function should return a value; 'void' return type assumed	caffe.managed	C:\caffe-master\windows\caffe.managed\caffelib.cpp	177	
Error	C2588	'::~CaffeModel': illegal global destructor	caffe.managed	C:\caffe-master\windows\caffe.managed\caffelib.cpp	180	
Error	C4430	missing type specifier - int assumed. Note: C++ does not support default-int	caffe.managed	C:\caffe-master\windows\caffe.managed\caffelib.cpp	181	
Error	C2084	function 'int CaffeModel(void)' already has a body	caffe.managed	C:\caffe-master\windows\caffe.managed\caffelib.cpp	181	
Error	C2355	'this': can only be referenced inside non-static member functions or non-static data member initializers	caffe.managed	C:\caffe-master\windows\caffe.managed\caffelib.cpp	182	
Error	C2588	'::!CaffeModel': illegal global finalizer	caffe.managed	C:\caffe-master\windows\caffe.managed\caffelib.cpp	186	
Error	C4430	missing type specifier - int assumed. Note: C++ does not support default-int	caffe.managed	C:\caffe-master\windows\caffe.managed\caffelib.cpp	187	
Error	C2065	'm_net': undeclared identifier	caffe.managed	C:\caffe-master\windows\caffe.managed\caffelib.cpp	188	
Error	C2541	'delete': cannot delete objects that are not pointers	caffe.managed	C:\caffe-master\windows\caffe.managed\caffelib.cpp	188	
Error	C2065	'm_net': undeclared identifier	caffe.managed	C:\caffe-master\windows\caffe.managed\caffelib.cpp	189	
Error	C2976	'std::array': too few template arguments	caffe.managed	C:\caffe-master\windows\caffe.managed\caffelib.cpp	192	
Error	C3699	'^': cannot use this indirection on type 'std::array'	caffe.managed	C:\caffe-master\windows\caffe.managed\caffelib.cpp	193	
Error	C2065	'm_net': undeclared identifier	caffe.managed	C:\caffe-master\windows\caffe.managed\caffelib.cpp	194	
Error	C2227	left of '->ExtractOutputs' must point to class/struct/union/generic type	caffe.managed	C:\caffe-master\windows\caffe.managed\caffelib.cpp	194	
Error	C2512	'FloatArray': no appropriate default constructor available	caffe.managed	C:\caffe-master\windows\caffe.managed\caffelib.cpp	194	
Error	C2976	'std::array': too few template arguments	caffe.managed	C:\caffe-master\windows\caffe.managed\caffelib.cpp	195	
Error	C2027	use of undefined type 'std::array'	caffe.managed	C:\caffe-master\windows\caffe.managed\caffelib.cpp	195	
Error	C3536	'outputs': cannot be used before it is initialized	caffe.managed	C:\caffe-master\windows\caffe.managed\caffelib.cpp	195	
Error	C2109	subscript requires array or pointer type	caffe.managed	C:\caffe-master\windows\caffe.managed\caffelib.cpp	195	
Error	C2440	'return': cannot convert from 'int' to 'std::array *'	caffe.managed	C:\caffe-master\windows\caffe.managed\caffelib.cpp	196	
Error	C2976	'std::array': too few template arguments	caffe.managed	C:\caffe-master\windows\caffe.managed\caffelib.cpp	199	
Error	C3699	'^': cannot use this indirection on type 'std::array'	caffe.managed	C:\caffe-master\windows\caffe.managed\caffelib.cpp	199	
Error	C3699	'^': cannot use this indirection on type 'std::array'	caffe.managed	C:\caffe-master\windows\caffe.managed\caffelib.cpp	200	
Error	C3285	for each statement cannot operate on variables of type 'std::array *'	caffe.managed	C:\caffe-master\windows\caffe.managed\caffelib.cpp	202	
Error	C2065	'name': undeclared identifier	caffe.managed	C:\caffe-master\windows\caffe.managed\caffelib.cpp	203	
Error	C2065	'm_net': undeclared identifier	caffe.managed	C:\caffe-master\windows\caffe.managed\caffelib.cpp	204	
Error	C2227	left of '->ExtractOutputs' must point to class/struct/union/generic type	caffe.managed	C:\caffe-master\windows\caffe.managed\caffelib.cpp	204	
Error	C2976	'std::array': too few template arguments	caffe.managed	C:\caffe-master\windows\caffe.managed\caffelib.cpp	205	
Error	C3699	'^': cannot use this indirection on type 'std::array'	caffe.managed	C:\caffe-master\windows\caffe.managed\caffelib.cpp	205	
Error	C2027	use of undefined type 'std::array'	caffe.managed	C:\caffe-master\windows\caffe.managed\caffelib.cpp	205	
Error	C2976	'std::array': too few template arguments	caffe.managed	C:\caffe-master\windows\caffe.managed\caffelib.cpp	209	
Error	C2027	use of undefined type 'std::array'	caffe.managed	C:\caffe-master\windows\caffe.managed\caffelib.cpp	209	
Error	C3536	'values': cannot be used before it is initialized	caffe.managed	C:\caffe-master\windows\caffe.managed\caffelib.cpp	209	
Error	C2109	subscript requires array or pointer type	caffe.managed	C:\caffe-master\windows\caffe.managed\caffelib.cpp	209	
Error	C3536	'outputs': cannot be used before it is initialized	caffe.managed	C:\caffe-master\windows\caffe.managed\caffelib.cpp	210	
Error	C2109	subscript requires array or pointer type	caffe.managed	C:\caffe-master\windows\caffe.managed\caffelib.cpp	210	
Error	C2440	'return': cannot convert from 'int' to 'std::array *'	caffe.managed	C:\caffe-master\windows\caffe.managed\caffelib.cpp	212	
Error	C2065	'm_net': undeclared identifier	caffe.managed	C:\caffe-master\windows\caffe.managed\caffelib.cpp	219	
Error	C2227	left of '->GetInputImageWidth' must point to class/struct/union/generic type	caffe.managed	C:\caffe-master\windows\caffe.managed\caffelib.cpp	219	
Error	C2065	'm_net': undeclared identifier	caffe.managed	C:\caffe-master\windows\caffe.managed\caffelib.cpp	220	
Error	C2227	left of '->GetInputImageHeight' must point to class/struct/union/generic type	caffe.managed	C:\caffe-master\windows\caffe.managed\caffelib.cpp	220	
Error	C2976	'std::array': too few template arguments	caffe.managed	C:\caffe-master\windows\caffe.managed\caffelib.cpp	258	
Error	C3699	'^': cannot use this indirection on type 'std::array'	caffe.managed	C:\caffe-master\windows\caffe.managed\caffelib.cpp	259	
Error	C2065	'm_net': undeclared identifier	caffe.managed	C:\caffe-master\windows\caffe.managed\caffelib.cpp	262	
Error	C2227	left of '->ExtractBitmapOutputs' must point to class/struct/union/generic type	caffe.managed	C:\caffe-master\windows\caffe.managed\caffelib.cpp	262	
Error	C2512	'FloatArray': no appropriate default constructor available	caffe.managed	C:\caffe-master\windows\caffe.managed\caffelib.cpp	262	
Error	C2976	'std::array': too few template arguments	caffe.managed	C:\caffe-master\windows\caffe.managed\caffelib.cpp	263	
Error	C2027	use of undefined type 'std::array'	caffe.managed	C:\caffe-master\windows\caffe.managed\caffelib.cpp	263	
Error	C3536	'outputs': cannot be used before it is initialized	caffe.managed	C:\caffe-master\windows\caffe.managed\caffelib.cpp	263	
Error	C2109	subscript requires array or pointer type	caffe.managed	C:\caffe-master\windows\caffe.managed\caffelib.cpp	263	
Error	C2440	'return': cannot convert from 'int' to 'std::array *'	caffe.managed	C:\caffe-master\windows\caffe.managed\caffelib.cpp	264	
Error	C2976	'std::array': too few template arguments	caffe.managed	C:\caffe-master\windows\caffe.managed\caffelib.cpp	267	
Error	C3699	'^': cannot use this indirection on type 'std::array'	caffe.managed	C:\caffe-master\windows\caffe.managed\caffelib.cpp	267	
Error	C3699	'^': cannot use this indirection on type 'std::array'	caffe.managed	C:\caffe-master\windows\caffe.managed\caffelib.cpp	268	
Error	C3285	for each statement cannot operate on variables of type 'std::array *'	caffe.managed	C:\caffe-master\windows\caffe.managed\caffelib.cpp	272	
Error	C2065	'name': undeclared identifier	caffe.managed	C:\caffe-master\windows\caffe.managed\caffelib.cpp	273	
Error	C2065	'm_net': undeclared identifier	caffe.managed	C:\caffe-master\windows\caffe.managed\caffelib.cpp	274	
Error	C2227	left of '->ExtractBitmapOutputs' must point to class/struct/union/generic type	caffe.managed	C:\caffe-master\windows\caffe.managed\caffelib.cpp	274	
Error	C2976	'std::array': too few template arguments	caffe.managed	C:\caffe-master\windows\caffe.managed\caffelib.cpp	275	
Error	C1003	error count exceeds 100; stopping compilation	caffe.managed	C:\caffe-master\windows\caffe.managed\caffelib.cpp	275	

### My system configuration
Operating system: windows 7, 64bits
Compiler: visual studion15
MATLAB version

Thank you

**Comment by willyd** [comment]
VS based build system is not supported anymore. Use the CMake build system instead. See instructions [here](https://github.com/BVLC/caffe/tree/windows#configuring-and-building-caffe).

From CONTRIBUTING:

Please use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) for usage, installation, or modeling questions, or other requests for help.
_Do not post such requests to Issues._ Doing so interferes with the development of Caffe.
