### ISSUE TITLE
Pycaffe: Undefined symbols for architecture x86_64:   "_PyUnicode_FromStringAndSize"

### ISSUE THREAD

**Issue by zsong** [BVLC/caffe#5483]
I am on Python 3. I can successfully compile Caffe and run test locally but I got this error when compiling pycaffe.

I installed boost for python 3 and all stuff seemed to be wired up. Still, I got this error.

    CXX/LD -o python/caffe/_caffe.so python/caffe/_caffe.cpp
    In file included from python/caffe/_caffe.cpp:17:
    In file included from ./include/caffe/caffe.hpp:12:
    ./include/caffe/net.hpp:41:5: warning: unused typedef 'INVALID_REQUESTED_LOG_SEVERITY' [-Wunused-local-typedef]
        LOG_EVERY_N(WARNING, 1000) << "DEPRECATED: ForwardPrefilled() "
        ^
    /usr/local/include/glog/logging.h:917:30: note: expanded from macro 'LOG_EVERY_N'
                                 INVALID_REQUESTED_LOG_SEVERITY);           \
                                 ^
    1 warning generated.
    Undefined symbols for architecture x86_64:
      "_PyUnicode_FromStringAndSize", referenced from:
          boost::python::str::str<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in _caffe-a90126.o
          boost::python::detail::no_proxy_helper<std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >, boost::python::detail::final_vector_derived_policies<std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >, false>, boost::python::detail::container_element<std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >, unsigned long, boost::python::detail::final_vector_derived_policies<std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >, false> >, unsigned long>::base_get_item_(boost::python::back_reference<std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >&> const&, _object*) in _caffe-a90126.o
          boost::python::detail::caller_arity<1u>::impl<boost::python::objects::iterator_range<boost::python::return_value_policy<boost::python::return_by_value, boost::python::default_call_policies>, std::__1::__wrap_iter<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*> >::next, boost::python::return_value_policy<boost::python::return_by_value, boost::python::default_call_policies>, boost::mpl::vector2<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, boost::python::objects::iterator_range<boost::python::return_value_policy<boost::python::return_by_value, boost::python::default_call_policies>, std::__1::__wrap_iter<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*> >&> >::operator()(_object*, _object*) in _caffe-a90126.o
    ld: symbol(s) not found for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    make: *** [python/caffe/_caffe.so] Error 1

**Comment by shelhamer** [comment]
Sorry, I've never seen this build error. Try a different version of boost python?

Please ask installation questions on the mailing list.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

**Comment by shuangyu** [comment]
I get exactly the same error.

Mac 10.12, Python 3.6.1 :: Anaconda 4.4.0 (x86_64)

**Comment by zsong** [comment]
Switch to Karas or Pytorch. Caffe is just too hard to install.

**Comment by zjjjz** [comment]
modify the “PYTHON_LIBRARIES” in Makefile(not Makefile.config),at the end of ”PYTHON_LIBRARIES“ is python2.7，u need modity to yourself python lib

**Comment by dragonQian** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
