### ISSUE TITLE
No “build” folder in apollocaffe

### ISSUE THREAD

**Issue by Samaneh1994** [BVLC/caffe#5484]
Hi,
I installed caffe on windows 8, and now I'm trying to install apollocaffe from [http://apollocaffe.com/](url) guideline, as it says in step 3, I should create a variable for "libcaffe.so" in the "build" folder of apollocaffe . In my case there is no "build" folder, what should I do?
this is my apollocaffe's folder.

![1](https://cloud.githubusercontent.com/assets/23655749/24584191/9a72e876-177a-11e7-8961-f3e8fb89dd9a.JPG)

I appreciate any help.

**Comment by Samaneh1994** [comment]
I installed caffe on windows 8, and now I'm trying to install apollocaffe from [http://apollocaffe.com/](url) guideline, as it says in step 3, I should create a variable for "libcaffe.so" in the "build" folder of apollocaffe . In my case there is no "build" folder, whate should I do?
this is my apollocaffe's folder.
[https://i.stack.imgur.com/1kXD2.jpg](url)
I appreciate any help.

**Comment by williford** [comment]
This is Caffe repository. Apollocaffe's repo is here:
https://github.com/Russell91/apollocaffe

Reading their website, it doesn't look like they support Windows.

**Comment by williford** [comment]
.so files are only used on Unix-like systems. Step 4 in the process actually builds the libcaffe.so.
