### ISSUE TITLE
Add cuDNN v6 to the Dockerfile

### ISSUE THREAD

**Issue by flx42** [BVLC/caffe#5486]
Now that #5478 (cuDNN v6 support) was merged, a new version needs to be tagged and the GPU Dockerfile should be modified.

@cypof

**Comment by cypof** [comment]
Tested with nvidia/cuda:8.0-cudnn6-devel, seems OK. I cannot reproduce the speed issue in #5490. GoogleNet is about 3% faster. We will update for the next tag.
