### ISSUE TITLE
Copyright permission letter required

### ISSUE THREAD

**Issue by monjoybme** [BVLC/caffe#5488]
Hi All,

We did some modifications and created a new layer in Caffe. Now we are planning to upload our layers along with whole Caffe set up (downloaded from Github) as supplementary documents in an open access journal. Please let me know what is the procedure to get the permission to use whole Caffe setup. I already cited in the main manuscript. Kindly reply as early as possible. 

Please use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) for usage, installation, or modeling questions, or other requests for help.
_Do not post such requests to Issues._ Doing so interferes with the development of Caffe.

Please read the [guidelines for contributing](https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md) before submitting this issue.

### Steps to reproduce

If you are having difficulty building Caffe or training a model, please ask the caffe-users mailing list. If you are reporting a build error that seems to be due to a bug in Caffe, please attach your build configuration (either Makefile.config or CMakeCache.txt) and the output of the make (or cmake) command.

### Your system configuration
Operating system:
Compiler:
CUDA version (if applicable):
CUDNN version (if applicable):
BLAS:
Python or MATLAB version (for pycaffe and matcaffe respectively):

**Comment by shelhamer** [comment]
Issues is not the right place for this request—it is for framework development. The Caffe [license](https://github.com/BVLC/caffe/blob/master/LICENSE) covers use, extension and so on. Letters for use and redistribution are not necessary.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
