### ISSUE TITLE
Caffe is dead?

### ISSUE THREAD

**Issue by darkAlert** [BVLC/caffe#5489]
I heard that caffe no longer supports and almost died. It is right?
Maybe it's time to switch to other frameworks? (tensorFlow, for example)

**Comment by naibaf7** [comment]
No, it's not dead.
Most people just don't get that they should ask user questions in the Google groups and not here as "issues". "Issues" should only be opened for apparent bugs.

**Comment by elgalu** [comment]
![image](https://user-images.githubusercontent.com/111569/57847613-29888e80-77d7-11e9-939a-2320e318d109.png)
