### ISSUE TITLE
Issue Caffe Windows: Could not find a configuration file for package "Protobuf" that is   compatible with requested version "".

### ISSUE THREAD

**Issue by slorena** [BVLC/caffe#5500]
Hello,

I'm trying to build caffe on Windows 7 and I have this issue when I run "cmake .." from caffe\build folder.

-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PythonInterp: C:/Users/Lorena/Anaconda2/python.exe (found suitable vers
ion "2.7.13", minimum required is "2.7")
-- Looking for pthread.h
-- Looking for pthread.h - not found
-- Found Threads: TRUE
-- Boost version: 1.61.0
-- Found the following Boost libraries:
--   system
--   thread
--   filesystem
--   chrono
--   date_time
--   atomic
-- Found GFlags: C:/Users/Lorena/.caffe/dependencies/libraries_v120_x64_py27_1.1
.0/libraries/include
-- Found gflags  (include: C:/Users/Lorena/.caffe/dependencies/libraries_v120_x6
4_py27_1.1.0/libraries/include, library: gflags_shared)
-- Could NOT find Glog (missing:  GLOG_LIBRARY)
CMake Error at cmake/ProtoBuf.cmake:6 (find_package):
  Could not find a configuration file for package "Protobuf" that is
  compatible with requested version "".

  The following configuration files were considered but not accepted:

    C:/Users/Lorena/.caffe/dependencies/libraries_v120_x64_py27_1.1.0/libraries/
cmake/protobuf-config.cmake, version: 3.1.0 (64bit)
    C:/Users/Lorena/Anaconda2/Library/cmake/protobuf-config.cmake, version: 3.1.
0 (64bit)

Call Stack (most recent call first):
  cmake/Dependencies.cmake:48 (include)
  CMakeLists.txt:79 (include)

-- Configuring incomplete, errors occurred!
See also "D:/Master/Disertatie/framework/caffe/build/CMakeFiles/CMakeOutput.log"
.
See also "D:/Master/Disertatie/framework/caffe/build/CMakeFiles/CMakeError.log".

How can I fix it?

**Comment by willyd** [comment]
From CONTRIBUTING.md

> Please do not post usage, installation, or modeling questions, or other requests for help to Issues. Use the caffe-users list instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

Looks like you are trying to compile caffe with a 32 bit configuration. Use cmake -G"Visual Studio 12 2013 **Win64**" ..

**Comment by huang-wang** [comment]
why，but i mean to compile caffe with a 32 bit configuration.

**Comment by willyd** [comment]
@huang-wang  The 32-bit build is not supported on Windows. That does not mean it won't work but I cannot support it. If you get it to work I will gladly accept contributions.
