### ISSUE TITLE
Low rank deep neural networks for fast evaluation

### ISSUE THREAD

**Issue by wenwei202** [BVLC/caffe#5505]
### Issue summary
I am working on low rank deep neural networks, to speedup the testing for better deployability. Anyone is working on similar stuff? 

### Steps to reproduce

Code is in https://github.com/wenwei202/caffe/tree/sfm.

**Comment by naibaf7** [comment]
This belongs to the google group of Caffe. Issues are for... bugs, discussions about development and so on. Please do not spam the issues.
