### ISSUE TITLE
undefined function 'caffe_'for input arguments of type 'char'

### ISSUE THREAD

**Issue by bianlongpeng** [BVLC/caffe#5508]
when I run code in matlab2014a,there is always an error:
Undefined function 'caffe_'for input arguments of type'char'.
Error in net_surgery(line10)
caffe_('reset');

The PC resource: ubuntu 14.04
and I have add the matcaffe path to matlab .The code as follows:
if exist(fullfile(caffe_root,'/matlab/+caffe/private'),'dir')
   addpath(fullfile(caffe_root,'/matlab/+caffe/private'));
else
 warnning('Please install Caffe in %s',caffe_root);
end
what can I do for it?Someone can help me?Thanks very much

**Comment by shelhamer** [comment]
Sorry, this sounds like an installation issue.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
