### ISSUE TITLE
problem in install caffe 

### ISSUE THREAD

**Issue by noronet** [BVLC/caffe#5511]
hello . Im install caffe in windows 10 with cuda8 and visual 2015 ... but I when enter this command
"scripts\build_win.cmd" .. the cmd preview this message
"CMake Error: The source directory "E:/caffe/caffe/build/Toolkit/CUDA/v8.0" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
The filename, directory name, or volume label syntax is incorrect.
ERROR: Configure failed" 
what does my problem? please help me. thanks.

**Comment by willyd** [comment]
_Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

Please repost there with the following:

- build_win.cmd script if you have made any modifications to it
- build_win.cmd output by piping it to a file like so: build_win.cmd > buildlog.txt
- CMakeCache.txt located in the build folder.
