### ISSUE TITLE
Problem when building caffe with CPU only

### ISSUE THREAD

**Issue by JoanYu** [BVLC/caffe#5516]
I met this problem when I build caffe with CPU only
```
CXX/LD -o .build_release/tools/compute_image_mean.bin
CXX tools/convert_imageset.cpp
CXX tools/upgrade_solver_proto_text.cpp
CXX tools/caffe.cpp
.build_release/lib/libcaffe.so：对‘cv::imread(cv::String const&, int)’未定义的引用
.build_release/lib/libcaffe.so：对‘cv::imencode(cv::String const&, cv::_InputArray const&, std::vector<unsigned char, std::allocator<unsigned char> >&, std::vector<int, std::allocator<int> > const&)’未定义的引用
.build_release/lib/libcaffe.so：对‘cv::imdecode(cv::_InputArray const&, int)’未定义的引用
collect2: error: ld returned 1 exit status
Makefile:625: recipe for target '.build_release/tools/compute_image_mean.bin' failed
make: *** [.build_release/tools/compute_image_mean.bin] Error 1
make: *** 正在等待未完成的任务....
```
I've install opencv3.1 **in [this way](http://www.pyimagesearch.com/2016/10/24/ubuntu-16-04-how-to-install-opencv/)**. I don't know if this method affect the problem

Operating system:Ubuntu 16.04 LTS
Compiler:GCC 5.4
CUDA version (if applicable):
CUDNN version (if applicable):
BLAS:
Python or MATLAB version (for pycaffe and matcaffe respectively):

**Comment by shelhamer** [comment]
It's most likely an OpenCV issue. Please ask installation questions on the mailing list.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
