### ISSUE TITLE
Pycaffe partial inference/backprop fails for certain networks

### ISSUE THREAD

**Issue by Noiredd** [BVLC/caffe#5518]
### Background
Network prototxt examples commonly name layers and their respective output blobs identically. Yet we often change layer names - if only to prevent loading their weights from a pretrained model, allowing partial transfer. Renaming their top blobs with them is tedious and error-prone, since in general case it is not straightforward to track which of the further layers will be using those blobs. Therefore, I often end up renaming only the layer, while its blob is left intact.

Another feature I make extensive use of is partial inference/backprop, that is call similar to `Net.forward(start='data', end='fc7')` - I can alter the activations in the middle of inference and analyze the subsequent change in prediction, for example. It turns out, both forward() and backward() passes result in a KeyError if the `end` layer's name does not match the name of the blob it produces.

### Issue summary
Both `caffe.Net()` and `caffe.Classifier()` work just fine for a standard setup where a layer's top blob name equals its own. But try to use the following [deploy.prototxt](https://gist.github.com/Noiredd/4b3692245501c989e368e6c7ed581675) - it is just an AlexNet setup whose `fc` layers were renamed, but their top blobs were not. Run the following code in your python terminal:
`import caffe`
`model = 'deploy.prototxt'`
`network = caffe.Net(model, caffe.TRAIN)`
`network.forward(end='fc6_renamed')`  
You should get an error similar to this:
`Traceback (most recent call last):`
`  File "<stdin>", line 1, in <module>`
`  File "/usr/local/caffe/python/caffe/pycaffe.py", line 183, in _Net_backward`
`    return {out: self.blobs[out].diff for out in outputs}`
`  File "/usr/local/caffe/python/caffe/pycaffe.py", line 183, in <dictcomp>`
`    return {out: self.blobs[out].diff for out in outputs}`
`KeyError: 'fc6_renamed'`

### Explanation and fix
Functions `_Net_forward` and `_Net_backward` in [pycaffe.py](../blob/master/python/caffe/pycaffe.py#L88) take a named, string type argument `end` to decide the extent of partial execution. The bug is caused by using the same string to decide the blob whose data is to be output. Therefore, if a layer's name does not match its top blob's name, two errors happen:  
KeyError is thrown if the correct layer name is passed, since a blob of this name does not exist  
ValueError is thrown if the correct blob name is passed, since a layer of this name does not exist.  
I have solved this issue (#5519) by retrieving the name of a blob the given layer produces, before attempting to extract its data.

### My system configuration
Operating system: Ubuntu 14.04 LTS
Compiler: gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4
CUDA version (if applicable): 7.0
CUDNN version (if applicable): 5.1
BLAS: atlas
Python version: 2.7.6

**Comment by Noiredd** [comment]
My fix is pending in #5519. Please close this upon merging.

**Comment by shelhamer** [comment]
First raised in #2829
