### ISSUE TITLE
looking for a link to download fast rcnn models

### ISSUE THREAD

**Issue by Liangxianggithub** [BVLC/caffe#5522]
Please use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) for usage, installation, or modeling questions, or other requests for help.
_Do not post such requests to Issues._ Doing so interferes with the development of Caffe.

Please read the [guidelines for contributing](https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md) before submitting this issue.

### Issue summary
I am a new fast-rcnn learner and could not find the links to download fast-rcnn models in this page. I don't know why, but could you please provide me the links? 

### Steps to reproduce

If you are having difficulty building Caffe or training a model, please ask the caffe-users mailing list. If you are reporting a build error that seems to be due to a bug in Caffe, please attach your build configuration (either Makefile.config or CMakeCache.txt) and the output of the make (or cmake) command.

### Your system configuration
Operating system:ubuntu14.04
Compiler:
CUDA version (if applicable):cuda 8.0
CUDNN version (if applicable):
BLAS:ATLAS
Python or MATLAB version (for pycaffe and matcaffe respectively):Python

**Comment by shelhamer** [comment]
Please ask model and usage questions on the mailing list. The [Faster R-CNN](https://github.com/rbgirshick/py-faster-rcnn) site includes model links as does the older [Fast R-CNN](https://github.com/rbgirshick/fast-rcnn) site.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
