### ISSUE TITLE
python caffe can not use gpu train 

### ISSUE THREAD

**Issue by gxd1994** [BVLC/caffe#5525]
I have already config caffe
mnist can run use c++ caffe.exe
but i can't use python interface to trian use gpu ,but can  use cpu

**Comment by shelhamer** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
