### ISSUE TITLE
caffe:AttributeError: 'module' object has no attribute 'LabelMap'

### ISSUE THREAD

**Issue by tianke0711** [BVLC/caffe#5533]
The caffe is installed on the Ubuntu server,and it test is ok, and python is python 2.7. I just run the following code on the Ubutun(16.04) cloud server:

 

      import caffe
       from caffe.proto import caffe_pb2
    
    
       label_map = caffe_pb2.LabelMap()

    
and I have run the command as following which provided by the internet, but there is still error:

command:
   
   

    export PYTHONPATH=$/home2/challenge98/caffe/python:$PYTHONPATH

error:
     
   
   

    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    AttributeError: 'module' object has no attribute 'LabelMap'

Could you guys give me some advices how to solve it. Thanks!

**Comment by shelhamer** [comment]
This question seems to be about a fork of Caffe since there is no `LabelMap` in BVLC/Caffe:master. Please ask your question at the fork.

**Comment by tianke0711** [comment]
what is you meaning of fork, I don` t know fork, could you tell me in detail! thanks!

**Comment by shelhamer** [comment]
A [fork](https://guides.github.com/activities/forking/) is a different edition of a project, or to put it another way it's a distinct copy of Caffe with its own changes. Your question is not about this version of Caffe—BVLC/Caffe—but about some other version of Caffe. You should ask questions wherever you found the edition of Caffe that you're using.

**Comment by Tahirhan** [comment]
thanks for information shelhamer

**Comment by wxhqw** [comment]
I also meet this problem,have you ever solved this problem?
