### ISSUE TITLE
Common test failure on Ubuntu (> 16.04), segfault in an OpenCV call according to backtrace

### ISSUE THREAD

**Issue by cdluminate** [BVLC/caffe#5540]
As reported here: https://github.com/BVLC/caffe/issues/2601#issuecomment-294066314 , Ubuntu (> 16.04) users suffer from a test failure where an OpenCV call caused segfault.

https://launchpad.net/ubuntu/+source/opencv
https://tracker.debian.org/pkg/opencv

Debian and Ubuntu both ship `opencv 2.4.9.1+dfsg1-2`, but this problem didn't appear on Debian.

The test failure looks like this (no debug symbol since this is copied from the launchpad buildlog):
```
[----------] 5 tests from ImageDataLayerTest/0, where TypeParam = caffe::CPUDevice<float>
[ RUN      ] ImageDataLayerTest/0.TestResize
*** Aborted at 1485019567 (unix time) try "date -d @1485019567" if you are using GNU date ***
PC: @     0x7facc82c00ba (unknown)
*** SIGSEGV (@0xfffffffffffffff7) received by PID 20719 (TID 0x7facb38bf700) from PID 18446744073709551607; stack trace: ***
    @     0x7facd0d42620 (unknown)
    @     0x7facc82c00ba (unknown)
    @     0x7facc82c018b (unknown)
    @     0x7facc82c1ce8 (unknown)
    @     0x7facc82c0692 (unknown)
    @     0x7facc82bb020 (unknown)
    @     0x7facc82b9165 tbb::internal::allocate_root_with_context_proxy::allocate()
    @     0x7faccf7fae22 cv::parallel_for_()
    @     0x7faccfbbeb2a (unknown)
    @     0x7faccfbbbbb7 cv::resize()
    @     0x7facd18240f7 caffe::ReadImageToCVMat()
    @     0x7facd173b82b caffe::ImageDataLayer<>::load_batch()
    @     0x7facd16c9d46 caffe::BasePrefetchingDataLayer<>::InternalThreadEntry()
    @     0x7facd16a58eb boost::detail::thread_data<>::run()
    @     0x7facd1179576 (unknown)
    @     0x7facd0d386ca start_thread
    @     0x7facceb100ff clone
    @                0x0 (unknown)
Segmentation fault (core dumped)
```

For more information, see https://github.com/BVLC/caffe/issues/2601#issuecomment-294066314
Similar issue: #5077 

This issue affects: Ubuntu { 16.10, 17.04 , devel }

**Comment by CDLuminate** [comment]
The good news is this unit test error disappeared on ubuntu devel (i.e. the under-development 17.10).

https://launchpadlibrarian.net/317138567/buildlog_ubuntu-artful-amd64.caffe_1.0.0-1_BUILDING.txt.gz

So this issue only affects Ubuntu 16.10 and 17.04, and will hopefully disappear since >= 17.10 .

**Comment by aimhabo** [comment]
So... on ubuntu 16.04, Do you have any way to solve segmentation fault? I've rewrote the cv::resize, cv::Mat::convertTo and changed the header file to <opencv.hpp>, now I face the issue of "malloc memory corruption" with cv::subtract

**Comment by aimhabo** [comment]
after reinstall libtbb2 (Clean up all about opencv2.4+ at once) and reinstall opencv3.4.1(working well in console), the error become so...
`
*** Error in `/home/aimhabo/caffe/build/examples/cpp_classification/classification.bin': corrupted size vs. prev_size: 0x0000000037e977f0 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7f8e14c9e7e5]
/lib/x86_64-linux-gnu/libc.so.6(+0x7e9dc)[0x7f8e14ca59dc]
/lib/x86_64-linux-gnu/libc.so.6(+0x81cde)[0x7f8e14ca8cde]
/lib/x86_64-linux-gnu/libc.so.6(+0x82c0a)[0x7f8e14ca9c0a]
/lib/x86_64-linux-gnu/libc.so.6(posix_memalign+0x11d)[0x7f8e14cae71d]
/usr/local/lib/libopencv_world.so.3.4(_ZN2cv10fastMallocEm+0x2b)[0x7f8e15c493cb]
/usr/local/lib/libopencv_world.so.3.4(_ZN2cv3Mat6createEiPKii+0x57f)[0x7f8e15af406f]
/home/aimhabo/caffe/build/examples/cpp_classification/classification.bin[0x405b4a]
/home/aimhabo/caffe/build/examples/cpp_classification/classification.bin[0x407db1]
/home/aimhabo/caffe/build/examples/cpp_classification/classification.bin[0x408443]
/home/aimhabo/caffe/build/examples/cpp_classification/classification.bin[0x404af4]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0)[0x7f8e14c47830]
/home/aimhabo/caffe/build/examples/cpp_classification/classification.bin[0x404f69]
======= Memory map: ========
`

otherside, now ` sudo sh examples/mnist/train_lenet.sh ` will error with  ' Check failed: status == CUBLAS_STATUS_SUCCESS (14 vs. 0) ' or ' 77 vs. 0 ' (random...), but it still can ' caffe.cpp:250] Optimization Done. ' and refresh the '.caffemodel' , just end with memory error：

> *** Error in `./build/tools/caffe': double free or corruption (out): 0x0000000000dd7f40 ***
> ======= Backtrace: =========
> /lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7f8c888bc7e5]
> /lib/x86_64-linux-gnu/libc.so.6(+0x8037a)[0x7f8c888c537a]
> /lib/x86_64-linux-gnu/libc.so.6(cfree+0x4c)[0x7f8c888c953c]
> /usr/lib/x86_64-linux-gnu/libprotobuf.so.9(_ZN6google8protobuf8internal28DestroyDefaultRepeatedFieldsEv+0x1f)[0x7f8c899ca8af]
> /usr/lib/x86_64-linux-gnu/libprotobuf.so.9(_ZN6google8protobuf23ShutdownProtobufLibraryEv+0x8b)[0x7f8c899c9b3b]
> /usr/lib/x86_64-linux-gnu/libmirprotobuf.so.3(+0x233b9)[0x7f8c122653b9]
> /lib64/ld-linux-x86-64.so.2(+0x10de7)[0x7f8c8aaf0de7]
> /lib/x86_64-linux-gnu/libc.so.6(+0x39ff8)[0x7f8c8887eff8]
> /lib/x86_64-linux-gnu/libc.so.6(+0x3a045)[0x7f8c8887f045]
> /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf7)[0x7f8c88865837]
> ./build/tools/caffe[0x407d59]
>

**Comment by aimhabo** [comment]
14.04√
