### ISSUE TITLE
test_backward_start_end flakiness and logging

### ISSUE THREAD

**Issue by brunobowden** [BVLC/caffe#5546]
In preparing PR #5545, the Travis-CI has repeatedly failed on the same test: `test_backward_start_end (test_net.TestNet)`. At the same time, virtually all builds pass successfully and the 1 or 2 builds that fail are different each time (e.g. default-cmake one time and then no-io-make the next).

The natural question is whether PR #5545 is adding the flakiness? Given that it's just 9 lines and only impacts logging on some `CHECK(...)` calls, I find it hard to believe that given there's minimal possible side effects from the calls to `inline Blob::shape_string()`:
https://github.com/BVLC/caffe/blob/master/include/caffe/blob.hpp#L54

Has anyone see this heisenbug before? I couldn't find any references to `test_backward_start_end` in other GitHub issues or recent Travis-CI builds on other PRs, so it seems new. Also, given that it only prints out part of the two unequal tensors, it's not possible to see where the inequality occurs. It tests within a tolerance of 0.001 but doesn't indicate by how much the tolerance fails - it would be great to add better logging on this if possible. Finally, the data is somehow randomly generated for the test, so is it just bad luck on the randomness? Again, any insights would be much appreciated.

### Example failures:

`python2-cmake` failure (8 others succeeded)
https://travis-ci.org/BVLC/caffe/builds/222985072

`default-cmake` failure (8 others succeeded)
https://travis-ci.org/BVLC/caffe/builds/222966189

`no-io-make` and `default-cmake` failures (7 others succeeded)
https://travis-ci.org/BVLC/caffe/builds/222963908

```
https://github.com/BVLC/caffe/blob/master/include/caffe/blob.hpp#L54
======================================================================
FAIL: test_backward_start_end (test_net.TestNet)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/BVLC/caffe/python/caffe/test/test_net.py", line 109, in test_backward_start_end
    np.testing.assert_allclose(conv_blob.diff,manual_backward,rtol=1e-3);
  File "/usr/lib/python2.7/dist-packages/numpy/testing/utils.py", line 1183, in assert_allclose
    verbose=verbose, header=header)
  File "/usr/lib/python2.7/dist-packages/numpy/testing/utils.py", line 644, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=0.001, atol=0
(mismatch 100.0%)
 x: array([[[[  1.78245485e+00,   1.57610071e+00,  -2.99948263e+00, ...,
           -3.60107183e+00,   1.31478143e+00,   2.76347733e+00],
         [  2.94090390e+00,  -1.37327123e+00,  -3.75043845e+00, ...,...
 y: array([[[[  1.78245485e+00,   1.57610071e+00,  -2.99948263e+00, ...,
           -3.60107183e+00,   1.31478143e+00,   2.76347733e+00],
         [  2.94090390e+00,  -1.37327123e+00,  -3.75043845e+00, ...,...
```
Also seen with different values...
```
 x: array([[[[  3.28327680e+00,  -1.52982831e-01,   3.88426805e+00, ...,
            3.70303440e+00,  -1.60803556e-01,   1.53703606e+00],
         [  6.21540022e+00,   1.20835197e+00,   6.76525831e+00, ...,...
 y: array([[[[  3.28327680e+00,  -1.52982831e-01,   3.88426805e+00, ...,
            3.70303440e+00,  -1.60803556e-01,   1.53703606e+00],
         [  6.21540022e+00,   1.20835197e+00,   6.76525831e+00, ...,...
```

### Steps to reproduce
Unclear but new Travis-CI builds on PR #5545 seems to do it. 

### Your system configuration
Caffe Travis-CI build system

**Comment by Noiredd** [comment]
Solved in #5973.
