### ISSUE TITLE
Building API with Caffe WINDOWS

### ISSUE THREAD

**Issue by klopezlinar** [BVLC/caffe#5551]
### Issue summary
I haved compiled caffe successfully in windows but when I include caffe headers in my project I got compiling errors.

### Steps to reproduce

I have the following class structure:

api.h
#include "dl_handler.h"
...

dl_handler.h
#include "classifier.h"
...

classifier.h
#include <caffe/caffe.hpp>
...

When I try to complite it, however, I got the following 2 errors twice:
C:\Source\caffe\scripts\build\include\caffe/proto/caffe.pb.h(2734): error C2059: syntax error: "="
C:\Source\caffe\scripts\build\include\caffe/proto/caffe.pb.h(2735): error C2238: unexpected token before ';'

Which refer to these lines in caffe.pb.h:

static const DimCheckMode STRICT =
    ParamSpec_DimCheckMode_STRICT;
static const DimCheckMode STRICT =
    V1LayerParameter_DimCheckMode_STRICT;

I have already tried to add in my classifier.h 

#define GLOG_NO_ABBREVIATED_SEVERITIES
#define NOMINMAX
#define WIN32_LEAN_AND_MEAN
#define NO_STRICT
#include "windows.h"

as explained in https://github.com/BVLC/caffe/issues/5043, but the errors persist. Does anybody know how to solve this?

Thanks!

### Your system configuration
Operating system: WIndows 10
Compiler: Visual studio 14 2015 Win64
CUDA version (if applicable): v 8.0

I my cmake I have:

find_package(Caffe)
if (Caffe_FOUND)
    INCLUDE_DIRECTORIES( ${Caffe_INCLUDE_DIRS} )
    MESSAGE("Found!; ${Caffe_INCLUDE_DIRS}")
else()
    message(FATAL_ERROR "Caffe libraries not found. Please set Caffe_INCLUDE_DIR.")
endif()

TARGET_LINK_LIBRARIES( prototype
  ${Caffe_LIBRARIES})

**Comment by willyd** [comment]
You may try to define the above preprocessor definitions in your project file using `add_defintions` for example. Also, you should probably install Caffe by building the install target and point your CMake build to the install directory using `Caffe_DIR`.

From CONTRIBUTING.md

> Specific Caffe design and development issues, bugs, and feature requests are maintained by GitHub Issues.

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
