### ISSUE TITLE
convert_mnist_data.cpp:101] Check failed: mdb_env_open(mdb_env, db_path, 0, 0664) == 0 (38 vs. 0) mdb_env_open failed

### ISSUE THREAD

**Issue by shengye205** [BVLC/caffe#5552]
when I run the create_mnist.sh, I see the report "caffe lmdb db::LMDB:open() failed and reported 'mdb_status == 0 (38 vs. 0) Cannot allocate memory'"
if I  write the mnist_train_lmdb in local disk, it run ok;
but if I write the  mnist_train_lmdb in a network disk(or remote dist), the above problem appears.
here is the output:

[xxxxxxxxx@gpu04 caffetest1]$ ./example/mnist/create_mnist.sh 
Creating lmdb...
F0420 20:22:16.687211 24281 convert_mnist_data.cpp:101] Check failed: mdb_env_open(mdb_env, db_path, 0, 0664) == 0 (38 vs. 0) mdb_env_open failed
*** Check failure stack trace: ***
    @     0x2aaab0980e6d  (unknown)
    @     0x2aaab0982ced  (unknown)
    @     0x2aaab0980a5c  (unknown)
    @     0x2aaab098363e  (unknown)
    @           0x403e94  convert_dataset()
    @           0x4025e3  main
    @     0x2aaab9774b35  __libc_start_main
    @           0x40262d  (unknown)
./example/mnist/create_mnist.sh: line 19: 24281 Aborted                 (core dumped) $BUILD/convert_mnist_data.bin $DATA/train-images-idx3-ubyte $DATA/train-labels-idx1-ubyte $EXAMPLE/mnist_train_${BACKEND} --backend=${BACKEND}

**Comment by shengye205** [comment]
I get the answer. In lustre file system, The fcntl function is denied occasionally. This is test code:
int fd;
	//524354:MDB_O_MASK & MDB_O_LOCKS
	fd = open("/lustre/xxx", 524354, 436);
	struct flock lock_info;
	lock_info.l_type = F_WRLCK;
	lock_info.l_whence = SEEK_SET;
	lock_info.l_start = 0;
	lock_info.l_len = 1;
	int rc = fcntl(fd, F_SETLK, &lock_info);
	printf("%d\n", errno);

**Comment by Noiredd** [comment]
Related issue: #6120, also a StackOverflow [answer](https://stackoverflow.com/a/26608820/6919631).
