### ISSUE TITLE
isssue when pycaffe classify 4 channel images

### ISSUE THREAD

**Issue by busyyyDog** [BVLC/caffe#5554]
Hi ALL;

I am now using caffe training many 4-channel image (RGB-IR). for the task i separated the 4-channels into 3 channels (RGB) as data0, and IR channel as data1. All data has format LMDB.  After this I use concat layer to comine them as 4 channels images to train.

The training was very fine. And inference with LMDB data format was fine as well. inference is like:
layer {
  name: "data"
  type: "Data"
  top: "data0"
  top: "label"
  transform_param {
    mirror: false
    mean_file: "RGB_MEAN.binaryproto"
  }
  data_param {
    source: "LMDB\\tmp_rgb"
    batch_size: 1
    backend: LMDB
  }
}
layer {
  name: "data"
  type: "Data"
  top: "data1"
  transform_param {
    mirror: false
    mean_file: IR_MEAN.binaryproto"
  }
  data_param {
    source: "LMDB\\tmp_ir"
    batch_size: 1
    backend: LMDB
  }
}
layer{
    name: "concat" 
    bottom: "data0"  
    bottom: "data1" 
    top: "data" 
    type: "Concat"
    concat_param { 
        concat_dim: 1
    } 
}

Now the issue comes:
When I use pycaffe to classify, the result is totally false. In Pycaffe I use caffe.io.Transformer like this:
        transformer[0] = caffe.io.Transformer({'data0': net.blobs['data0'].data.shape})
        transformer[0].set_mean('data0', np.load(mean_file[0]).mean(1).mean(1))
        transformer[0].set_transpose('data0', (2,0,1))
        transformer[0].set_channel_swap('data0', (2,1,0))
        transformer[0].set_raw_scale('data0', 255)
        
        transformer[1] = caffe.io.Transformer({'data1':net.blobs['data1'].data.shape})
        transformer[1].set_transpose('data1', (2,0,1))
        transformer[1].set_mean('data1', np.load(mean_file[1]).mean(1).mean(1))
        transformer[1].set_raw_scale('data1', 255) 

the first some lines in deploy.prototxt: 
layer {
  name: "data"
  type: "Input"
  top: "data0"
  input_param { shape: { dim: 1 dim: 3 dim: 64 dim: 64 } }
}
layer {
  name: "data"
  type: "Input"
  top: "data1"
  input_param { shape: { dim: 1 dim: 1 dim: 64 dim: 64 } }
}
layer{
    name: "concat" 
    bottom: "data0"  
    bottom: "data1" 
    top: "data" 
    type: "Concat"
    concat_param { 
        concat_dim: 1
    } 
}

The result was very bad, all images are estimated as same class.
I would like to ask if someone encountered the same issues when classify multichannel Images by Pycaffe?
Where is the problem actually?

Thanks Thanks!!!

**Comment by shaibagon** [comment]
Please use the [caffe-users list][1] for usage, installation, or modeling questions, or other requests for help.
You may also post questions on [stackoverflow][3], make sure you tag them with `caffe` tag.  
Do not post such requests to Issues. Doing so interferes with the development of Caffe.

Please read the [guidelines for contributing][2] before submitting this issue.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
 [3]: http://stackoverflow.com/questions/tagged/caffe
