### ISSUE TITLE
src/caffe/proto/caffe.proto:310:1: Expected "required", "optional", or "repeated".

### ISSUE THREAD

**Issue by jx1100370217** [BVLC/caffe#5556]
Please use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) for usage, installation, or modeling questions, or other requests for help.
_Do not post such requests to Issues._ Doing so interferes with the development of Caffe.

Please read the [guidelines for contributing](https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md) before submitting this issue.

### Steps to reproduce

If you are having difficulty building Caffe or training a model, please ask the caffe-users mailing list. If you are reporting a build error that seems to be due to a bug in Caffe, please attach your build configuration (either Makefile.config or CMakeCache.txt) and the output of the make (or cmake) command.

### Your system configuration
Operating system:
Compiler:
CUDA version (if applicable):
CUDNN version (if applicable):
BLAS:
Python or MATLAB version (for pycaffe and matcaffe respectively):

**Comment by PENGUINLIONG** [comment]
Please check if you have modified `./src/caffe/proto/caffe.proto` for extensions. [Google's protobuf documentations](https://developers.google.com/protocol-buffers/) might help you make proper modifications.

But also notice Github issue page is not ready for such usage questions, especially a customized version. Use this [mailing list](https://groups.google.com/forum/#!forum/caffe-users) instead.
