### ISSUE TITLE
Allow images of different sizes as inputs

### ISSUE THREAD

**Issue by sguada** [BVLC/caffe#557]
Bases in recent experiments, cropping from images with smallest size = 256 perform better. 
http://arxiv.org/pdf/1405.3531v2.pdf

The idea is allowing that images have different sizes before cropping, but became same size after cropping. This would require remove the mean_file and replace it with a mean_value.

LevelDB, LMDB and Image_Data_Layer should not assume that the images have the same size.

**Comment by hayderm** [comment]
Please, I want to use SPP-Net and it works well. However, when I change the number of layers it givers error !! so do I need to compile caffe ? or just use the given caffe.mex ?

**Comment by longjon** [comment]
Closing as we now have per-channel mean so this should work, and should be doable with gradient accumulation. (If it's broken for batch size > 1, you're welcome to open a new issue for that.)
