### ISSUE TITLE
Ubuntu ,compiler caffe error!

### ISSUE THREAD

**Issue by MrZhangCF** [BVLC/caffe#5572]
after download the caffe , use "sudo make all" to compiler the caffe,but the output shows as bellow:

so how to solve that?

**Comment by PENGUINLIONG** [comment]
What's the output? Have you properly finished settings in `Makefile.config`?

And, you should go [here](https://groups.google.com/forum/#!forum/caffe-users) to ask such question.

**Comment by williford** [comment]
Please ask your question on the [Caffe user mailing list](https://groups.google.com/forum/#!forum/caffe-users) or on another website, such as http://stackoverflow.com/ or http://stats.stackexchange.com/.

> Please use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) for usage, installation, or modeling questions, or other requests for help.
> _Do not post such requests to Issues._ Doing so interferes with the development of Caffe.
