### ISSUE TITLE
How can I know Caffe is installed on my system?

### ISSUE THREAD

**Issue by Samaneh1994** [BVLC/caffe#5579]
Hi, I used [https://github.com/BVLC/caffe/wiki/Ubuntu-16.04-or-15.10-Installation-Guide](url) for installing caffe, I installed it on my system.Now how can I know caffe is installed? I write ( import caffe) in python but it says there is no module.Is caffe installed?

**Comment by PENGUINLIONG** [comment]
Are you sure you have added pycaffe to your python path? Or you might need to update bash cache.
