### ISSUE TITLE
opencv: error when compiling Caffe-1.0 with opencv

### ISSUE THREAD

**Issue by lionel3** [BVLC/caffe#5582]
Issue summary

I came into a bug when compiling the latest Caffe-1.0 with opencv.

 The error is as follows:
In file included from /usr/local/include/cblas.h:5:0,
                 from ./include/caffe/util/mkl_alternate.hpp:14,
                 from ./include/caffe/util/math_functions.hpp:11,
                 from ./include/caffe/filler.hpp:13,
                 from ./include/caffe/caffe.hpp:9,
                 from examples/cpp_classification/classification.cpp:1:
/usr/include/opencv2/core/core.hpp:4127:9: error: expected identifier before ‘float’
         FLOAT=REAL, //!< synonym or REAL
         ^
/usr/include/opencv2/core/core.hpp:4127:9: error: expected ‘}’ before ‘float’
In file included from examples/cpp_classification/classification.cpp:3:0:
/usr/include/opencv2/core/core.hpp:4127:14: error: expected unqualified-id before ‘=’ token
         FLOAT=REAL, //!< synonym or REAL
              ^
/usr/include/opencv2/core/core.hpp:4140:22: error: expected unqualified-id before ‘)’ token
     CV_WRAP FileNode();
                      ^
/usr/include/opencv2/core/core.hpp:4142:14: error: expected unqualified-id before ‘const’
     FileNode(const CvFileStorage* fs, const CvFileNode* node);
              ^
/usr/include/opencv2/core/core.hpp:4142:14: error: expected ‘)’ before ‘const’
/usr/include/opencv2/core/core.hpp:4144:14: error: expected unqualified-id before ‘const’
     FileNode(const FileNode& node);
              ^
/usr/include/opencv2/core/core.hpp:4144:14: error: expected ‘)’ before ‘const’
/usr/include/opencv2/core/core.hpp:4146:49: error: non-member function ‘cv::FileNode cv::operator[](const string&)’ cannot have cv-qualifier
     FileNode operator[](const string& nodename) const;
                                                 ^
/usr/include/opencv2/core/core.hpp:4146:49: error: ‘cv::FileNode cv::operator[](const string&)’ must be a nonstatic member function
/usr/include/opencv2/core/core.hpp:4148:55: error: non-member function ‘cv::FileNode cv::operator[](const char*)’ cannot have cv-qualifier
     CV_WRAP FileNode operator[](const char* nodename) const;
                                                       ^
/usr/include/opencv2/core/core.hpp:4148:55: error: ‘cv::FileNode cv::operator[](const char*)’ must be a nonstatic member function
/usr/include/opencv2/core/core.hpp:4150:40: error: non-member function ‘cv::FileNode cv::operator[](int)’ cannot have cv-qualifier
     CV_WRAP FileNode operator[](int i) const;
                                        ^
/usr/include/opencv2/core/core.hpp:4150:40: error: ‘cv::FileNode cv::operator[](int)’ must be a nonstatic member function
/usr/include/opencv2/core/core.hpp:4152:24: error: non-member function ‘int cv::type()’ cannot have cv-qualifier
     CV_WRAP int type() const;
                        ^
/usr/include/opencv2/core/core.hpp:4155:26: error: non-member function ‘bool cv::empty()’ cannot have cv-qualifier
     CV_WRAP bool empty() const;
                          ^
/usr/include/opencv2/core/core.hpp:4157:27: error: non-member function ‘bool cv::isNone()’ cannot have cv-qualifier
     CV_WRAP bool isNone() const;
                           ^
/usr/include/opencv2/core/core.hpp:4159:26: error: non-member function ‘bool cv::isSeq()’ cannot have cv-qualifier
     CV_WRAP bool isSeq() const;
                          ^
/usr/include/opencv2/core/core.hpp:4161:26: error: non-member function ‘bool cv::isMap()’ cannot have cv-qualifier
     CV_WRAP bool isMap() const;
                          ^
/usr/include/opencv2/core/core.hpp:4163:26: error: non-member function ‘bool cv::isInt()’ cannot have cv-qualifier
     CV_WRAP bool isInt() const;
                          ^
/usr/include/opencv2/core/core.hpp:4165:27: error: non-member function ‘bool cv::isReal()’ cannot have cv-qualifier
     CV_WRAP bool isReal() const;
                           ^
/usr/include/opencv2/core/core.hpp:4167:29: error: non-member function ‘bool cv::isString()’ cannot have cv-qualifier
     CV_WRAP bool isString() const;
                             ^
/usr/include/opencv2/core/core.hpp:4169:28: error: non-member function ‘bool cv::isNamed()’ cannot have cv-qualifier
     CV_WRAP bool isNamed() const;
                            ^
/usr/include/opencv2/core/core.hpp:4171:27: error: non-member function ‘std::string cv::name()’ cannot have cv-qualifier
     CV_WRAP string name() const;
                           ^
/usr/include/opencv2/core/core.hpp:4173:27: error: non-member function ‘size_t cv::size()’ cannot have cv-qualifier
     CV_WRAP size_t size() const;
                           ^
/usr/include/opencv2/core/core.hpp:4175:25: error: expected constructor, destructor, or type conversion before ‘;’ token
     operator int() const;
                         ^

It's too long so I just copied part of it.

Steps to reproduce

I compiled it using  gcc4.8.5 on Ubuntu14.04 with cuda 8.0 and cudnn 5.1.  
I tried opencv2.4.8 by installing  libopencv-dev and later opencv2.4.13, opencv3.2.0 compiled by myself. 
 But the error still occured. 
I tried openblas first and changed it to atlas later, but the error continued.
I googled a lot but stiill couldn't find the answer. 
Maybe someone here can help me.

System configuration
Operating system: ubuntu14.04
OpenCV version :  2.4.8, 2.4,13 and 3.2.0. all tried 
Compiler: gcc 4.8.5
CUDA version : 8.0
CUDNN version : 5.1
BLAS: openblas and atlas(both tried)
Python or MATLAB version (for pycaffe and matcaffe respectively): python2.7

**Comment by kartheekmedathati** [comment]
Aq

Thanks & Regards,
N V Kartheek Medathati.

**Comment by lionel3** [comment]
I have solved the problem now. The error occured because I compiled mad installed the latest openblas library. 
I just renamed the cblas.h in /usr/local/include and succeeded finally.
