### ISSUE TITLE
make all error 

### ISSUE THREAD

**Issue by rmanor** [BVLC/caffe#559]
I get the following errors when I do 'make all', although I installed all the required dependencies. 

/usr/bin/ld: cannot find -lcblas
/usr/bin/ld: cannot find -latlas

Using Ubuntu 12.10. Thanks.

**Comment by inexxt** [comment]
Had the same problem on Ubuntu 15.04, the solution from ^link hasn't worked, it appeared that one has to install libatlas-base-dev. Maybe it's worth to add it to dependencies.

**Comment by wenliang** [comment]
install `libatlas-base-dev` solve my problem. Thanks @inexxt .

**Comment by tharun2011** [comment]
libcblas.so may also present in subdirectory of /usr/lib. Check whether libcblas.so is present in /usr/lib/atlas. If exists, then include this path.

**Comment by habemen** [comment]
I had this problem any one with solution...
CXX src/caffe/layer.cpp
CXX src/caffe/data_reader.cpp
AR -o .build_release/lib/libcaffe.a
LD -o .build_release/lib/libcaffe.so.1.0.0-rc3
/usr/bin/ld: cannot find -lopencv_imgcodecs
collect2: error: ld returned 1 exit status
Makefile:566: recipe for target '.build_release/lib/libcaffe.so.1.0.0-rc3' failed
make: *** [.build_release/lib/libcaffe.so.1.0.0-rc3] Error 1

**Comment by auxiliary** [comment]
Ubuntu 14.04, installing libatlas-base-dev solved my problem too.

**Comment by lygstate** [comment]
Ubuntu 16.04, installing libatlas-base-dev solved my problem too.

**Comment by duygusar** [comment]
@habemen 
Long shot but I have the same problem, any ideas how to fix it?

**Comment by nerdykamil** [comment]
@duygusar pkg-config --modversion opencv run this command on terminal to check opencv version if it is not version 3 then comment out OPENCV_VERSION := 3 in makefile.config

**Comment by duygusar** [comment]
@nerdykamil thanks but it is opencv3.3 as I intended, I installed it from build myself and as far as I know 3 is recommended for computation > 6.0 GPUs. Opencv 3.3 has some changes Caffe build doesn't support yet (can't refer to some files as opencv separated them but content is the same) but what I did solves the problem.

**Comment by marcelovicentegc** [comment]
On Ubuntu 18.04, installing `lib-atlas-dev` solved my problem as well.

**Comment by Rheza001** [comment]
Can you take a look at this problem?

This is the error that i got when i tried to make caffe:

```
rheza@rheza-VirtualBox:~/Documents/BirdWatcher/caffe$ make all
AR -o .build_release/lib/libcaffe.a
LD -o .build_release/lib/libcaffe.so.1.0.0-rc3
/usr/bin/ld: cannot find -lhdf5_hl
collect2: error: ld returned 1 exit status
Makefile:566: recipe for target '.build_release/lib/libcaffe.so.1.0.0-rc3' failed
make: *** [.build_release/lib/libcaffe.so.1.0.0-rc3] Error 1
```
Any help will be appreciated. Thank you!
