### ISSUE TITLE
I wrote my own clustering algorithm function in the convolution layer and the whole layer, and the hpp file is also declared, but the compiler has a problem

### ISSUE THREAD

**Issue by leixingxing1** [BVLC/caffe#5591]
.build_release/lib/libcaffe.so：对‘caffe::InnerProductLayer<float>::kmeans_cluster(std::vector<int, std::allocator<int> >&, std::vector<float, std::allocator<float> >&, float*, int, std::vector<int, std::allocator<int> >&, int, int)’未定义的引用
.build_release/lib/libcaffe.so：对‘caffe::ConvolutionLayer<double>::kmeans_cluster(std::vector<int, std::allocator<int> >&, std::vector<double, std::allocator<double> >&, double*, int, std::vector<int, std::allocator<int> >&, int, int)’未定义的引用
.build_release/lib/libcaffe.so：对‘caffe::InnerProductLayer<double>::kmeans_cluster(std::vector<int, std::allocator<int> >&, std::vector<double, std::allocator<double> >&, double*, int, std::vector<int, std::allocator<int> >&, int, int)’未定义的引用
.build_release/lib/libcaffe.so：对‘caffe::ConvolutionLayer<float>::kmeans_cluster(std::vector<int, std::allocator<int> >&, std::vector<float, std::allocator<float> >&, float*, int, std::vector<int, std::allocator<int> >&, int, int)’未定义的引用
collect2: error: ld returned 1 exit status
Makefile:625: recipe for target '.build_release/tools/convert_imageset.bin' failed
make: *** [.build_release/tools/convert_imageset.bin] Error 1

**Comment by Noiredd** [comment]
It's an issue of your own code, not Caffe.
