### ISSUE TITLE
Cmake build with malab

### ISSUE THREAD

**Issue by andreanicastro** [BVLC/caffe#5606]
### Issue summary
I tried to compile caffe and matcaffe but i get the following error
```
[100%] Building Matlab interface: /home/an4915/software/caffe/matlab/+caffe/private/caffe_.mexa64
Building with 'g++-4.9'.
/home/an4915/software/caffe/matlab/+caffe/private/caffe_.cpp:18:27: fatal error: caffe/caffe.hpp: No such file or directory
 #include "caffe/caffe.hpp"
                           ^
compilation terminated.

make[2]: *** [matlab/CMakeFiles/matlab.dir/build.make:61: ../matlab/+caffe/private/caffe_.mexa64] Error 255
make[1]: *** [CMakeFiles/Makefile2:1173: matlab/CMakeFiles/matlab.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

```

### Steps to reproduce
Build commands
`cmake  -DCUDA_HOST_COMPILER:STRING=gcc-5 -DBUILD_matlab=ON ..`
`make -j `

### system configuration
Operating system: Arch Linux
CUDA version : 8.0.61
CUDNN version : 6.0.21
BLAS: OpenBlas
Matlab : R2017a

**Comment by Joe136** [comment]
Some include paths in CMakeLists.txt are missing:
- <source_root>/include
- \<cuda>/include

I (dirty) fixed it by including this into the CMakeLists.txt:
``set (cflags ${cflags} -I${Caffe_INCLUDE_DIR} -I/usr/local/cuda/include)``

**Comment by jjpark** [comment]
I'm encountering the same problem. Has anyone come up with a solution other than Joe136 is suggesting.

**Comment by DruidWu** [comment]
Has anyone come up with a solution other than Joe136 is suggesting?

**Comment by DruidWu** [comment]
andreanicastro,Have you solved the problem?Can you share your solution with me?

**Comment by MustafaArikan** [comment]
Solution by Joe136 is ok, you have to add the missing include files.
You have to edit ../matlab/CMakeLists.txt

**Comment by Deastan** [comment]
I added this line as Joe136 said : 
# prepare linker flag lists
string(REPLACE ";" ";-L" link_folders "-L${folders}")
string(REPLACE ";" ":"  rpath_folders   "${folders}")

if(build_using MATCHES "Matlab")
  set(libflags -lcaffe${Caffe_POSTFIX} ${libflags}) # Matlab R2014a complans for -Wl,--whole-archive
  **set (cflags ${cflags} -I${Caffe_INCLUDE_DIR} -I/usr/local/cuda/include) #add this line!!!!** 
  caffe_fetch_and_set_proper_mexext(Matlab_caffe_mex)
  add_custom_command(OUTPUT ${Matlab_caffe_mex} COMMAND ${Matlab_mex}
      ARGS -output ${Matlab_caffe_mex} ${Matlab_srcs} ${cflags} ${link_folders} ${libflags}
      DEPENDS caffe COMMENT "Building Matlab interface: ${Matlab_caffe_mex}" VERBATIM)
  add_custom_target(matlab ALL DEPENDS ${Matlab_caffe_mex} SOURCES ${Matlab_srcs})

And works!!! Thank you!
