### ISSUE TITLE
group parameter

### ISSUE THREAD

**Issue by zhly0** [BVLC/caffe#5612]
I found a interesting thing in caffe,I have a net with 28 layers,which has about 14 3x3 convolotion layers,and these layers has the same input and output layers,and the group parameter I set it to the same number of the input number.I run this network the caffe said out of memory,but when I set all the group parameter to 1,It could run.My pc memory is 32Gb with a nvidia 1080 ti.Is there something wrong in my processdure???

**Comment by zhly0** [comment]
the caffe is really have bad maintains,it's rare to see its update,and never think about solving known issue.

**Comment by hchen1024** [comment]
About this problem, what causes it?

**Comment by willyd** [comment]
AFAIK this is due to the cuDNN engine. Caffe allocates 3 cudnn handles per group so when to the number of groups is large the memory consumption goes up really fast. Using the caffe engine solves the problem but it is much slower than cudnn.

**Comment by hchen1024** [comment]
@willyd  Thanks.
When we use caffe engine, the group convolution is much slower than standard convolution. Is there a way to improve this problem?
All the best,

**Comment by willyd** [comment]
Yes. But you will need to modify the caffe source code. Currently caffe allocates one cudnn handle and 3 cuda streams per group. You need to change that and reuse the handles and streams for different groups. One way of doing it would be to add a new parameter in the convolution param that limits the number of handles and streams that are allocated and make sure that this parameter is an integer multiple of groups. Then you can use a modulo operator on the group index wherever you need to get the right handle or stream. See this: https://github.com/BVLC/caffe/blob/master/src/caffe/layers/cudnn_conv_layer.cpp#L22-L23

HTH

**Comment by zhly0** [comment]
@willyd,thanks for your advice,but I not familiar with cuda or cudnn.Does it complicate?can your provide the code?Thanks

**Comment by willyd** [comment]
Sorry I can't provide the code. The simplest thing you can do is to allocate only 3 handles and 3 streams, i.e. replace `this->group_` by `1` here:
```
stream_  = new cudaStream_t[this->group_ * CUDNN_STREAMS_PER_GROUP];
handle_ = new cudnnHandle_t[this->group_ * CUDNN_STREAMS_PER_GROUP];
```
And then index the array appropriately where it is used.

**Comment by zhly0** [comment]
@willyd ,thanks for your advice,I tried,but I get error on the gpu memory check on function math_functions.cu:79,I think the reason is different stream in cudnn has different memory space,and if I simply limits the steam num and share the stream with different group,it has memory conflicts.And I think to let it work,It need more effort and someone who is familiar with the caffe's  code
