### ISSUE TITLE
Performance impact on object detection

### ISSUE THREAD

**Issue by Shrey2** [BVLC/caffe#5646]
What is the performance impact if the object recognition is performed on different image size/resolution?
How the processing for object detection time changes from 256x256 image to 4K image ?

**Comment by naibaf7** [comment]
The speed with neural networks oftne scales linearly. So from 256x256 to 4K, you'd be about ~120 times slower. It's often advised to choose smarter algorithms and work on scaled-down versions of images initially (i.e. pyramidal images, refine the region of interest in every step).
Also, having 4K images in Caffe will lead to integer overflow, it's too big. And you'll likely run out of GPU memory.

**Comment by Shrey2** [comment]
Is there some source from which the impact can be measured , for example this impact of ~120 times. How you came up with this number. What is the source to this result. If performed personally can you share the results about the performance impact on various image sizes.

**Comment by naibaf7** [comment]
How I came up with the number? It's approximately (3840*2160)/(256*256) ~ 120.
The reason it will be about that much slower is just the fact that you have to convolve about 120 times more pixels. So it takes that much longer. You can test this yourself with any of the Caffe example networks by for example doubling the input sizes.
