### ISSUE TITLE
Need documentation about caffe data format

### ISSUE THREAD

**Issue by jrabary** [BVLC/caffe#565]
Hi all,

Where can I find some documentation about the data format that caffe use.  I need to translate our data into caffe compatible format (leveled) but just don't know how to do this.

Best regards,

Jaonary

**Comment by urakagi** [comment]
I still don't get the point, as the documents still describe nothing about the data structure.
Can anyone writes like this: (with the correct format, of course)

key: data sequence number
value: label string followed by '\0' then data

or something? I want to convert non-image (PCM) byte arrays into leveldb.

**Comment by ronakgupta** [comment]
@shelhamer I tried to generate the leveldb files from CIFAR-10 binary data using create_cifar10.sh with DBTYPE=leveldb. But, I got four empty files (lock, log, and log.old, MANIFEST) and no .sst files in both training and testing data folder. There was no error generated while execution.
