### ISSUE TITLE
Caffe CLR for C#

### ISSUE THREAD

**Issue by hanbim520** [BVLC/caffe#5655]
Hello, I use caffe API to C #, through the CLR way, but found that caffe's boost version of a function is not supported by the CLR

1>E:\Pro\dependencies\libraries_v140_x64_py27_1.1.0\libraries\include\google/protobuf/message_lite.h(247): warning C4267: “return”: 从“size_t”转换到“int”，可能丢失数据
1>E:\Pro\dependencies\libraries_v140_x64_py27_1.1.0\libraries\include\boost-1_61\boost/filesystem/path.hpp(458): error C2059: 语法错误:“generic”
1>E:\Pro\dependencies\libraries_v140_x64_py27_1.1.0\libraries\include\boost-1_61\boost/filesystem/path.hpp(460): error C2334: “{”的前面有意外标记；跳过明显的函数体

![image](https://cloud.githubusercontent.com/assets/7490792/26522686/a6f5b2ec-4338-11e7-8be0-d92d3a837dab.png)

Do you consider upgrading the boost version? I see someone saying that the API for this version has been changed

**Comment by hanbim520** [comment]
![image](https://cloud.githubusercontent.com/assets/7490792/26522789/f378866a-433a-11e7-91c3-f1d17351ebbe.png)
yes  ,in boost 1.64 this api has been changed.

**Comment by willyd** [comment]
It should be relatively easy to replace boost 1.61 by 1.64 in the prebuilt dependencies. Or else, you could use caffe-builder and replace the boost tar ball link to use 1.64 and build the dependencies yourself.

**Comment by hanbim520** [comment]
Well, I osx and ubuntu on the caffe compiler version is my own choice, windows is the download, I was afraid of direct upgrade api will be changed, I used the vs2015 compiler.
