### ISSUE TITLE
./include/caffe/util/hdf5.hpp:6:18: fatal error: hdf5.h: No such file or directory

### ISSUE THREAD

**Issue by usama6832** [BVLC/caffe#5658]
I am facing this problem when I run 'make all' command during compilation of caffe.
please help me to solve this issue?

In file included from src/caffe/solver.cpp:8:0:
./include/caffe/util/hdf5.hpp:6:18: fatal error: hdf5.h: No such file or directory
compilation terminated.
Makefile:581: recipe for target '.build_release/src/caffe/solver.o' failed
make: *** [.build_release/src/caffe/solver.o] Error 1

### Your system configuration
Operating system: ubuntu16.04 
Compiler: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
CUDA version : cuda-8.0
BLAS:
Python or MATLAB version (for pycaffe and matcaffe respectively):

**Comment by juwikuang** [comment]
I fixed this by the following 
https://askubuntu.com/questions/629654/building-caffe-failed-to-see-hdf5-h

hope that will solve your problem.

**Comment by Brionnic** [comment]
The following helped me with this same issue.

From:
https://gist.github.com/wangruohui/679b05fcd1466bb0937f#fix-hdf5-naming-problem

**Comment by Noiredd** [comment]
Also see the wiki entry on commonly encountered build problems, it might contain some solutions gathered by the community.

I will close the issue for now, basing on the upvotes of @juwikuang's answer. Feel free to reopen if the problem persists, though.
