### ISSUE TITLE
Check failed: mdb_status == 0 (2 vs. 0) No such file or directory

### ISSUE THREAD

**Issue by leo2105** [BVLC/caffe#5666]
Hi 
I have some problems in one instruction on NVIDIA Tegra TX1

INPUT
$ /home/ubuntu/caffe/tools/caffe train --solver /home/ubuntu/deeplearning-cats-dogs-tutorial/caffe_models/caffe_model_1/solver_1.prototxt 2>&1 | tee /home/ubuntu/deeplearning-cats-dogs-tutorial/caffe_models/caffe_model_1/model_1_train.log

OUTPUT:
I0602 18:39:42.838120 12188 layer_factory.hpp:77] Creating layer data
F0602 18:39:42.838515 12188 db_lmdb.hpp:15] Check failed: mdb_status == 0 (2 vs. 0) No such file or directory
*** Check failure stack trace: ***
    @       0x7fa158a718  google::LogMessage::Fail()
    @       0x7fa158c614  google::LogMessage::SendToLog()
    @       0x7fa158a290  google::LogMessage::Flush()
    @       0x7fa158ceb4  google::LogMessageFatal::~LogMessageFatal()
    @       0x7fa18aa4ac  caffe::db::LMDB::Open()
    @       0x7fa17dfb50  caffe::DataLayer<>::DataLayer()
    @       0x7fa17dfd6c  caffe::Creator_DataLayer<>()
    @       0x7fa175e270  caffe::LayerRegistry<>::CreateLayer()
    @       0x7fa1889118  caffe::Net<>::Init()
    @       0x7fa188abcc  caffe::Net<>::Net()
    @       0x7fa1872684  caffe::Solver<>::InitTrainNet()
    @       0x7fa1873764  caffe::Solver<>::Init()
    @       0x7fa1873a24  caffe::Solver<>::Solver()
    @       0x7fa1864388  caffe::Creator_SGDSolver<>()
    @           0x40bcac  train()
    @           0x408d50  main
    @       0x7fa10bf8a0  __libc_start_main

**Comment by zchrissirhcz** [comment]
is your lmdb data created correctly? is that path correct?

**Comment by leo2105** [comment]
I found the mistakes. I had initialized variables incorrectly in solver_1.prototxt
When I specified location.

**Comment by tsger** [comment]
hello！Can you describe in detail how you solved it?@leo2105

**Comment by xiaoyanzhuo** [comment]
Make sure you have set the right dir of i.e. XX_train_val.prototxt(model definition) and also check in the model definition (XX_train_val.prototxt), mean_file and data_param setting are correct.
