### ISSUE TITLE
failed in making runtest and when I train hdf5 data in multi-gpu

### ISSUE THREAD

**Issue by SnailTyan** [BVLC/caffe#5668]
[ RUN      ] RMSPropSolverTest/2.TestRMSPropLeastSquaresUpdateWithEverythingShare
*** Aborted at 1496570742 (unix time) try "date -d @1496570742" if you are using GNU date ***
PC: @     0x7f7196b0ad86 (unknown)
*** SIGSEGV (@0x35) received by PID 121931 (TID 0x7f717ccc2700) from PID 53; stack trace: ***
    @     0x7f7189db8370 (unknown)
    @     0x7f7196b0ad86 (unknown)
    @     0x7f7196b0e8cc (unknown)
    @     0x7f71969e450c (unknown)
    @     0x7f719698e900 (unknown)
    @     0x7f719696afd7 (unknown)
    @     0x7f7196ee0f42 (unknown)
    @     0x7f718a94ffcc caffe::hdf5_load_nd_dataset_helper<>()
    @     0x7f718a94f067 caffe::hdf5_load_nd_dataset<>()
    @     0x7f718a8878a2 caffe::HDF5DataLayer<>::LoadHDF5FileData()
    @     0x7f718a886f34 caffe::HDF5DataLayer<>::LayerSetUp()
    @           0x4cf4dc caffe::Layer<>::SetUp()
    @     0x7f718a8fb213 caffe::Net<>::Init()
    @     0x7f718a8f97ea caffe::Net<>::Net()
    @     0x7f718a92c1e1 caffe::Solver<>::InitTrainNet()
    @     0x7f718a92ba75 caffe::Solver<>::Init()
    @     0x7f718a92b5a7 caffe::Solver<>::Solver()
    @           0x67ac20 caffe::SGDSolver<>::SGDSolver()
    @           0x6797c8 caffe::RMSPropSolver<>::RMSPropSolver()
    @     0x7f718a93d506 caffe::Creator_RMSPropSolver<>()
    @           0x929018 caffe::SolverRegistry<>::CreateSolver()
    @     0x7f718a91de26 caffe::Worker<>::InternalThreadEntry()
    @     0x7f718a81e99b caffe::InternalThread::entry()
    @     0x7f718a8221bc boost::_mfi::mf6<>::operator()()
    @     0x7f718a822091 boost::_bi::list7<>::operator()<>()
    @     0x7f718a821eb3 boost::_bi::bind_t<>::operator()()
    @     0x7f718a821d9a boost::detail::thread_data<>::run()
    @     0x7f719556927a (unknown)
    @     0x7f7189db0dc5 start_thread
    @     0x7f7189adf73d __clone
make: *** [runtest] Segmentation fault

**Comment by SnailTyan** [comment]
It works in single gpu.

**Comment by SnailTyan** [comment]
@shelhamer 
When I use lmdb as training data it works well in multi-gpu, but when I use hdf5 as training data caffe failed in multi-gpu. I use hdf5 as training data in single gpu, it works well.
The error is similar to the error of making runtest.

**Comment by jby1993** [comment]
@SnailTyan @shelhamer 
I also met the problem before, and I used old version Caffe to avoid the problem. 
Have you found the reason or solved it?
