### ISSUE TITLE
ImportError: No module named model_libs on windows 10

### ISSUE THREAD

**Issue by suji104** [BVLC/caffe#5691]
My Environment : CUDA 8.0 / CuDnn 5.1 / Windows 

I want to use a cafe in the windows 10 to try to use Python.
The following error occurs when you install the caffe installation and activate the py code

> Traceback (most recent call last):
> File "examples/ssd/ssd_detect.py", line 7, in 
> from caffe.model_libs import *
> ImportError: No module named model_libs

Search is an environmental configuration error.
How do I register environment variables?
Or are there any other solutions?
I would really appreciate it if you could help. Thanks

**Comment by willyd** [comment]
model_libs.py is not fro BVLC/caffe it comes from the ssd fork. Please ask your question there or on the caffe mailing list.
