### ISSUE TITLE
Check failed: mdb_status == 0(13 vs. 0) Permission denied

### ISSUE THREAD

**Issue by Splayshell** [BVLC/caffe#5696]
When I try to run the Training LeNet on MNIST with Caffe according to the tutorial example, then this problem occurred. I founded that rebuilding the Caffe and reloading the mnist dataset are both helpless. Is there any idea about this problem?

**Comment by deepali-c** [comment]
I have seen this problem once on my setup and it was resolved by changing the permissions to the folder, where the data-set was located.

**Comment by Splayshell** [comment]
@deepali-c 
Thanks for your help! But I cannot understand how to change the permission to the folder, could you explain more details about this?

**Comment by deepali-c** [comment]
Simplest is to give all permissions using - `chmod -R 777 [path to the dataset]`

**Comment by shaibagon** [comment]
Please use the [caffe-users list][1] for usage, installation, or modeling questions, or other requests for help.
You may also post questions on [stackoverflow][3], make sure you tag them with `caffe` tag.  
Do not post such requests to Issues. Doing so interferes with the development of Caffe.

Please read the [guidelines for contributing][2] before submitting this issue.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
 [3]: http://stackoverflow.com/questions/tagged/caffe
