### ISSUE TITLE
Problem with deploying a trained network - CuDNN vs Caffe engine

### ISSUE THREAD

**Issue by AlexTS1980** [BVLC/caffe#5698]
While deploying a trained network in Python I keep getting the following error: 

> Check failed: 2 == this->num_spatial_axes_ (2 vs. 1) CuDNNConvolution input must have 2 spatial axes (e.g., height and width). Use 'engine: CAFFE' for general ND convolution.

I of course added

engine: CAFFE to the relevant layer in the prototxt file and set caffe to cpu, but for some reason it changes the wrong dimension! The previous layer is 

4096x19x32

and the new one should be convolved to 
2x19x32

Instead it becomes 

4096x2x32.

How can I fix it? 

### Your system configuration
Operating system: Ubuntu 16.04
Compiler: nvcc
CUDA version (if applicable): 8.0
CUDNN version (if applicable): 5.1
BLAS:
Python or MATLAB version (for pycaffe and matcaffe respectively): 2.7.6

**Comment by srbnghosh99** [comment]
Hi.. I am getting the same error.. how did u solve this problem @AlexTS1980

**Comment by HainKUL** [comment]
I also get stuck in the similar problem. did you finally solve this problem?
