### ISSUE TITLE
Installing caffe on Windows

### ISSUE THREAD

**Issue by Dingo64** [BVLC/caffe#5699]
I downloaded a zip from "Prebuilt binaries" --> "Visual Studio 2015, CPU only, Python 3.5".
When I try to install it:
`pip3 install caffe.zip`
I get:
```
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\python35\lib\tokenize.py", line 454, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\USERNAME\\AppDa
ta\\Local\\Temp\\pip-5mzqk1dw-build\\setup.py'
```
How can I install this package if not with pip?

**Comment by willyd** [comment]
Just copy the `caffe` folder in `python/caffe` to your `site-packages` folder and it should work.

From CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
