### ISSUE TITLE
./create_list_kitti.sh: 行 41: /home/mpc/caffe/build/tools/get_image_size: no such file or diretory

### ISSUE THREAD

**Issue by MhiauGe** [BVLC/caffe#5702]
why don't i have get_image_size file in /caffe/build/tools?

i already compiled caffe successfully ！。。

**Comment by Noiredd** [comment]
`get_image_size` is not a tool provided by the master branch of Caffe - it looks like you want to be using [Wei Liu's SSD branch](https://github.com/weiliu89/caffe).

**Comment by shubhamblue** [comment]
Need more clarification, still, I'm getting such error, I have checked out SSD branch
