### ISSUE TITLE
Is it possible to Fine Tune a caffe model with one class of the pretrained model

### ISSUE THREAD

**Issue by Dean-TianZhang** [BVLC/caffe#5707]
Hi all,

Recently, I am thinking about is it possible to fine tune a Caffe model with only one class or few classes? 

Specifically, for example, I got a pre-trained model of semantic segmentation, and I found that this model can segment some of the classes precisely, but some of the classes poorly. Thus, now I want to strengthen the segmentation performance of some classes not the whole classes in the predefined class list. Is there any method, like Fine Tune, to make my idea came true?

Thanks~

**Comment by shaibagon** [comment]
Please use the [caffe-users list][1] for usage, installation, or modeling questions, or other requests for help.
You may also post questions on [stackoverflow][3], make sure you tag them with `caffe` tag.  
There is also [caffe.help][4] documenting the different layers of caffe.
Do not post such requests to Issues. Doing so interferes with the development of Caffe.

Please read the [guidelines for contributing][2] before submitting this issue.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
 [3]: http://stackoverflow.com/questions/tagged/caffe
 [4]: http://caffe.help/manual/layers.html
