### ISSUE TITLE
New Data Layer

### ISSUE THREAD

**Issue by kvmanohar22** [BVLC/caffe#5708]
Similar to [ImageDataParameter](https://github.com/BVLC/caffe/blob/master/src/caffe/proto/caffe.proto#L784), which is used for image classification task, I have come up with `BboxDataParameter` which can be used for the task of object detection. Everything is same as ImageDataParameter except that in the [source_file](https://github.com/BVLC/caffe/blob/master/src/caffe/proto/caffe.proto#L786), instead of specifying the `class_idx`, we can specify an `annotations-file` which is a text file containing the bounding box information.

Eg:
<source_file> 
```
Images/0001.png Annotations/0001.txt
Images/0002.png Annotations/0002.txt
...
```
Say 0001.png contains `one` object and 0002.png contains `two` objects, the corresponding Annotations files would be like:

Annotations/0001.txt
```
<xmin> <ymin> <xmax> <ymax> <class_idx>
```
Annotations/0002.txt
```
<xmin_1> <ymin_1> <xmax_1> <ymax_1> <class_idx_1> <xmin_2> <ymin_2> <xmax_2> <ymax_2> <class_idx_2>
```
All the details are explained in caffe.proto message file.

**Comment by shaibagon** [comment]
Thank you for making  a PR #5709. closing this issue. further discussions should be made under said PR
