### ISSUE TITLE
ImportError: No module named skimage.io

### ISSUE THREAD

**Issue by tyrant0604** [BVLC/caffe#5716]
### Issue summary
1. when I run 'make pytest'
the Error is :
ERROR: test_solver (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_solver
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/Users/xueding/caffe/python/caffe/test/test_solver.py", line 7, in <module>
    import caffe
  File "caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropSolver, AdaDeltaSolver, AdamSolver, NCCL, Timer
  File "caffe/pycaffe.py", line 15, in <module>
    import caffe.io
  File "caffe/io.py", line 2, in <module>
    import skimage.io
**ImportError: No module named skimage.io**

----------------------------------------------------------------------
Ran 10 tests in 0.001s

FAILED (errors=10)
make[3]: *** [CMakeFiles/pytest] Error 1
make[2]: *** [CMakeFiles/pytest.dir/all] Error 2
make[1]: *** [CMakeFiles/pytest.dir/rule] Error 2
make: *** [pytest] Error 2

2.then run 'sudo pip install scikit-image'
the Error is :
Requirement already satisfied: scikit-image in /Users/xueding/anaconda3/lib/python3.6/site-packages
Requirement already satisfied: six>=1.7.3 in /Users/xueding/anaconda3/lib/python3.6/site-packages (from scikit-image)
Requirement already satisfied: networkx>=1.8 in /Users/xueding/anaconda3/lib/python3.6/site-packages (from scikit-image)
Requirement already satisfied: pillow>=2.1.0 in /Users/xueding/anaconda3/lib/python3.6/site-packages (from scikit-image)
Requirement already satisfied: PyWavelets>=0.4.0 in /Users/xueding/anaconda3/lib/python3.6/site-packages (from scikit-image)
Requirement already satisfied: decorator>=3.4.0 in /Users/xueding/anaconda3/lib/python3.6/site-packages (from networkx>=1.8->scikit-image)
Requirement already satisfied: olefile in /Users/xueding/anaconda3/lib/python3.6/site-packages (from pillow>=2.1.0->scikit-image)
Requirement already satisfied: numpy>=1.9.1 in /Users/xueding/anaconda3/lib/python3.6/site-packages (from PyWavelets>=0.4.0->scikit-image)

### Your system configuration
Operating system: Darwin APPLE.local 16.6.0 Darwin Kernel Version 16.6.0:  root:xnu-3789.60.24~6/RELEASE_X86_64 x86_64
Compiler: 
CUDA version (if applicable):
CUDNN version (if applicable):
BLAS:
Python or MATLAB version (for pycaffe and matcaffe respectively):
python2.7 : /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7
python3.6(default): /Users/xxxx/anaconda3/lib/python3.6

It seems that the dependencies have just been used by python3.6, so I don't know how to install the dependencies of python2.7.

**Comment by deepali-c** [comment]
Do you have the package `python-skimage` installed?

**Comment by Noiredd** [comment]
Installation of scikit-image might be non-obvious: consult the [instructions](https://github.com/scikit-image/scikit-image/blob/master/INSTALL.rst).

I will close this issue as it is more installation/usage related. In case of further problems, please ask on the [caffe-users list][1]. All usage, installation, or modeling questions, or other requests for help should be asked there instead of Issues. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe. Please read the [guidelines for contributing][2] before submitting an issue or a pull request.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
