### ISSUE TITLE
ValueError: Mean shape incompatible with input shape in case of "./examples/images/cat.jpg"

### ISSUE THREAD

**Issue by leemgs** [BVLC/caffe#5718]
### Issue summary
We can not run `$ python python/classify.py  examples/images/cat.jpg foo` command. 

Below is an error messages. 

```
 . . . . Upper Omission . . . . 
09:30:47.006155  5678 net.cpp:744] Ignoring source layer loss
Traceback (most recent call last):
  File "python/classify.py", line 138, in <module>
    main(sys.argv)
  File "python/classify.py", line 110, in main
    channel_swap=channel_swap)
  File "/work/sdc/caffe/python/caffe/classifier.py", line 34, in __init__
    self.transformer.set_mean(in_, mean)
  File "/work/sdc/caffe/python/caffe/io.py", line 259, in set_mean
    raise ValueError('Mean shape incompatible with input shape.')
ValueError: Mean shape incompatible with input shape.
```

### Steps to reproduce
 It is a procedure to train & test imagenet data set with ImageNet model

** Train **
We have to run below command to get model and label data. (It tooks long time. Approximately, 10m, 232MB, 405KB/s ). We can download the data files that was used at 2012 ILSVRC (ImageNet Large-Scale Visual Recognition Challenge) with the below commands.

```
$ time python scripts/download_model_binary.py models/bvlc_reference_caffenet
$ sh data/ilsvrc12/get_ilsvrc_aux.sh
```

** Test **
`$ python python/classify.py  examples/images/cat.jpg foo`

 

### Your system configuration
Operating system: Ubuntu 16.04.1 LT64bit
Compiler: GCC 5.4.0
CUDA version (if applicable):  8.0
CUDNN version (if applicable): 8.0
BLAS: 3.6.0
Python or MATLAB version (for pycaffe and matcaffe respectively): Python 2.7.12

**Comment by Noiredd** [comment]
I assume #5719 resolved this? Please reopen if the issue persists.
