### ISSUE TITLE
Different ouput style between python and cpp for cat.jpeg

### ISSUE THREAD

**Issue by leemgs** [BVLC/caffe#5720]
### Issue summary
 There are different output style between python code and cpp code to test training result with cat.jpeg file. Which language is better between python and cpp? It seems that we can print a test result with ["--print-results"](https://github.com/jetpacapp/caffe/blob/master/python/classify.py#L94) option in case of python/classify.py command. 

### Steps to reproduce

**Train**
$ time python scripts/download_model_binary.py models/bvlc_reference_caffenet 
$ sh data/ilsvrc12/get_ilsvrc_aux.sh

**Test**
* for python
$ python python/classify.py examples/images/cat.jpg foo

* for cpp
$ ./build/examples/cpp_classification/classification.bin \
  models/bvlc_reference_caffenet/deploy.prototxt \
  models/bvlc_reference_caffenet/bvlc_reference_caffenet.caffemodel \
  data/ilsvrc12/imagenet_mean.binaryproto \
  data/ilsvrc12/synset_words.txt \
  examples/images/cat.jpg

### Your system configuration
Operating system: Ubuntu 16.04.1
Compiler: gcc 5.4
CUDA version (if applicable): 8.0
CUDNN version (if applicable): 8.0
BLAS: 3.6
Python or MATLAB version (for pycaffe and matcaffe respectively): python 2.7.12

**Comment by Noiredd** [comment]
Your link points to a (**very** old) fork of Caffe - the `--print-results` option is not present in master. I will close this question for now. Please clarify and reopen if you need more answers, but consider asking on [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead if this is only a usage issue.
