### ISSUE TITLE
Execution time of running Alexnet on GTX Titan 

### ISSUE THREAD

**Issue by hyungwonchoi** [BVLC/caffe#574]
I am now currently executing alexnet on my local machine. 
It has 32Gb of memory with i7 CPU X 990 3.47GHz x 12 with GTX Titan.

However, when I execute ./train_alexnet.sh , with the same setting , it takes about 60 seconds per 20 iterations which is relatively slower than the performance according to 
http://caffe.berkeleyvision.org/performance_hardware.html (26.26secs / 20 iterations)
During tranining, nvidia-smi command shows the memory usage of my GPU as 4493MiB / 6143MiB.

I do not understand where this performance difference comes from. 
Like K40, do I have to configure my Titan somehow? 

Any helps will be appreciated. 

Hyungwon

**Comment by sunilrao43** [comment]
@shelhamer @hyungwonchoi  can i know the procedure to run alexnet using caffe
