### ISSUE TITLE
/home/wenqiang/code/caffe-ssd/tools/get_image_size.cpp:89:52: error: 'GetImageSize' was not declared in this scope

### ISSUE THREAD

**Issue by jiangwqcooler** [BVLC/caffe#5742]
When i compile code， i got this error. How can i solve this?

**Comment by EasonTong** [comment]
make sure your code owns function GetImageSize in io.cpp，if there is no this function , you'd better download a newest one

**Comment by Noiredd** [comment]
You seem to be using some fork of Caffe - there is no get_image_size.cpp in master. Please consult with the fork repository.
