### ISSUE TITLE
Check failed: mdb_status == 0 (2 vs. 0) No such file or directory

### ISSUE THREAD

**Issue by jiangwqcooler** [BVLC/caffe#5748]
I0707 16:48:46.332346 16677 layer_factory.hpp:77] Creating layer data
I0707 16:48:46.332937 16677 net.cpp:100] Creating Layer data
I0707 16:48:46.332957 16677 net.cpp:408] data -> data
I0707 16:48:46.333135 16677 net.cpp:408] data -> label
F0707 16:48:46.336623 16692 db_lmdb.hpp:15] Check failed: mdb_status == 0 (2 vs. 0) No such file or directory
*** Check failure stack trace: ***
    @     0x7f4524eb0daa  (unknown)
    @     0x7f4524eb0ce4  (unknown)
    @     0x7f4524eb06e6  (unknown)
    @     0x7f4524eb3687  (unknown)
    @     0x7f4525702c90  caffe::db::LMDB::Open()
    @     0x7f45257535e3  caffe::DataReader<>::Body::InternalThreadEntry()
    @     0x7f4525766185  caffe::InternalThread::entry()
    @     0x7f451b172a4a  (unknown)
    @     0x7f451aa2a184  start_thread
    @     0x7f4523f86bed  (unknown)
    @              (nil)  (unknown)
Aborted (core dumped)

**Comment by datamonday** [comment]
Hello I met this same error ,can you tell me how to process? thanks!
