### ISSUE TITLE
caffe_ilsvrc12.tar.gz - File does not exist

### ISSUE THREAD

**Issue by sHyShcA** [BVLC/caffe#5749]
Link inside https://github.com/BVLC/caffe/blob/master/data/ilsvrc12/get_ilsvrc_aux.sh is broken.
Detail:
http://dl.caffe.berkeleyvision.org/caffe_ilsvrc12.tar.gz - File does not exist

**Comment by knipping** [comment]
A similar problem occurs with scripts/download_model_binary.py ("ERROR: model did not download correctly").  I think dl.caffe.berkeleyvision.org is down (temporarily, I hope) as it does not answer on being pinged.

**Comment by sHyShcA** [comment]
Works

**Comment by LordonCN** [comment]
> Works

File does not exist again
