### ISSUE TITLE
download_model_binary.py - Error: No route to host

### ISSUE THREAD

**Issue by sHyShcA** [BVLC/caffe#5750]
caffe/scripts/download_model_binary.py doesn't work
[Error 113]: No route to host.

**Comment by yulongtzzz** [comment]
I also can't access to this site "http://dl.caffe.berkeleyvision.org/ "

**Comment by sHyShcA** [comment]
Works.

**Comment by shelhamer** [comment]
The site occasionally goes down due to campus networking issues, but it usually comes back up in short order.
