### ISSUE TITLE
Is the available any Java wrapper for this framework? 

### ISSUE THREAD

**Issue by Bahramudin** [BVLC/caffe#5756]
### Issue summary
It will be great if we can use this framework in Java too.  If there is available any wrapper for Java, please suggest me to get the wrapper. Thanks

**Comment by Noiredd** [comment]
The closest thing I've heard of is via [JavaCPP](https://github.com/bytedeco/javacpp) - check the [javacpp-presets/caffe](https://github.com/bytedeco/javacpp-presets) repository.
