### ISSUE TITLE
Scale Invariant CNN (SICNN)

### ISSUE THREAD

**Issue by kloudkl** [BVLC/caffe#576]
The Spatial Pyramid Pooling net of #548 improves the speed of [Regions with Convolutional Neural Network Features](https://github.com/rbgirshick/rcnn) by extracting features for each image only once while [R-CNN](https://github.com/BVLC/caffe/search?q=r-cnn&type=Issues) does so for each region of interest in an image. The most important insight of SPP-net is that only the classifiers or the fully-connected layers require fixed-length vector. The convolution layers do not have to constrain the sizes of the images. The experiments show that full image is better than cropped ones and larger scales lead to higher accuracy.

The SPP-net simulate the multiple scales with fixed-size networks. The "scale-mismatch" problem is not solved. In #308, [multi-scale feature extraction](#189) is achieved by packing the multiple scales of a image in a single large image. They can only process pre-defined discrete scales. 

The authentic scale invariant CNN means that the extracted features can be scaled up or down to get the features of the images undergoing the same scaling. The feature of an image only has to be extracted once by the network.

Any ideas about the existing works in this direction?

**Comment by akanazawa** [comment]
Hi, 
the code for the locally scale-invariant ConvNet paper is available [here](https://github.com/akanazawa/si-convnet),
Thanks.

**Comment by etienne87** [comment]
Must be great, but wouldn't that take much more time? i mean you need to transform every blob several time for max-pooling out right?

**Comment by akanazawa** [comment]
Yeah, it does take more memory and time. Now I recommend you checking out this recent arxiv paper http://arxiv.org/abs/1506.02025
