### ISSUE TITLE
FCN Binary Segmentation with Scattered Segments, Is It Overfiting?

### ISSUE THREAD

**Issue by Dean-TianZhang** [BVLC/caffe#5766]
Please use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) for usage, installation, or modeling questions, or other requests for help.
_Do not post such requests to Issues._ Doing so interferes with the development of Caffe.

Please read the [guidelines for contributing](https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md) before submitting this issue.

### Issue summary
Recently, I am working on a project related with 2-class segmentation(0 for background, 1 for object). And I am using the pretrained caffe model to fine tune my model. But after training my model for 100000 iterations, the prediction performance is really bad with Scattered Segments. I have modified the following part of FCN-8s model:

1. number_output: 21 -> 2
2. add weight filter and bias_filter to each convnet. and choosing "type: gaussian" for  weight_filler, "type: "constant" for bias_filler.

And here is a output:

![image](https://user-images.githubusercontent.com/18567646/28112744-c48fcb90-672c-11e7-8d82-366ec6a40d38.png)

Actually, the grey area in the above image should be continuous.

Does anyone have the same problem? Is it causing by overfitting, since I just use unseen images to predict?

### Steps to reproduce

If you are having difficulty building Caffe or training a model, please ask the caffe-users mailing list. If you are reporting a build error that seems to be due to a bug in Caffe, please attach your build configuration (either Makefile.config or CMakeCache.txt) and the output of the make (or cmake) command.

### Your system configuration
Operating system:
Compiler:
CUDA version (if applicable):
CUDNN version (if applicable):
BLAS:
Python or MATLAB version (for pycaffe and matcaffe respectively):

**Comment by shaibagon** [comment]
Please use the [caffe-users list][1] for usage, installation, or modeling questions, or other requests for help.
You may also post questions on [stackoverflow][3], make sure you tag them with `caffe` tag.  
There is also [caffe.help][4] documenting the different layers of caffe.
Do not post such requests to Issues. Doing so interferes with the development of Caffe.

Please read the [guidelines for contributing][2] before submitting this issue.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
 [3]: http://stackoverflow.com/questions/tagged/caffe
 [4]: http://caffe.help/manual/layers.html
