### ISSUE TITLE
forward_all with error objective as output

### ISSUE THREAD

**Issue by kevin-w-li** [BVLC/caffe#5769]
This might be a misuse, but at least there should be some warning.

The PyCaffe function forward_all assumes that, in each batch,  the `blobs` have the same outermost dimension as the input. But if the network has the error objective as the output, which will be singleton returned by `forward` not matter how many input there is, then the line at line 204

`all_outs[out].extend(out_blob.copy())`

will complain `out_blob` is not an array. Also, when checking for padding before this function returns, `six.next` does not look for the correct output (error output or blob value). 

I guess this `pad` value should be calculated using the batch size of the network, and deal with the error value differently...

The same problem is also in other 'all' functions

**Comment by shaibagon** [comment]
Indeed this is a misuse. Caffe's `forward_all()` assumes one output per example in batch (i.e., batch examples are independent of each other).  If you are trying to mess things around you should use the lower level `forward()` interface and handle all the outputs yourself.
