### ISSUE TITLE
During Caffe.net

### ISSUE THREAD

**Issue by qaz99** [BVLC/caffe#5774]
Please use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) for usage, installation, or modeling questions, or other requests for help.
_Do not post such requests to Issues._ Doing so interferes with the development of Caffe.

Please read the [guidelines for contributing](https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md) before submitting this issue.

### Steps to reproduce

If you are having difficulty building Caffe or training a model, please ask the caffe-users mailing list. If you are reporting a build error that seems to be due to a bug in Caffe, please attach your build configuration (either Makefile.config or CMakeCache.txt) and the output of the make (or cmake) command.

### Your system configuration
Operating system: Ubantu
Compiler:
CUDA version (if applicable):
CUDNN version (if applicable):
BLAS:
Python or MATLAB version (for pycaffe and matcaffe respectively):

>>> net = caffe.Net(model_def,model_weights,caffe.TEST)    W0714 12:50:09.298867  3983 _caffe.cpp:122] DEPRECATION WARNING - deprecated use of Python interface
W0714 12:50:09.298913  3983 _caffe.cpp:123] Use this instead (with the named "weights" parameter):
W0714 12:50:09.298924  3983 _caffe.cpp:125] Net('/home/user/code/caffemodels/bvlc_reference_caffenet/deploy.prototxt', 1, weights='/home/user/code/caffemodels/bvlc_reference_caffenet/bvlc_reference_caffenet.caffemodel')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: Could not open file /home/user/code/caffemodels/bvlc_reference_caffenet/deploy.prototxt

**Comment by shaibagon** [comment]
Please use the [caffe-users list][1] for usage, installation, or modeling questions, or other requests for help.
You may also post questions on [stackoverflow][3], make sure you tag them with `caffe` tag.  
There is also [caffe.help][4] documenting the different layers of caffe.
Do not post such requests to Issues. Doing so interferes with the development of Caffe.

Please read the [guidelines for contributing][2] before submitting this issue.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
 [3]: http://stackoverflow.com/questions/tagged/caffe
 [4]: http://caffe.help/manual/layers.html
