### ISSUE TITLE
problem compiling with vl_compilenn

### ISSUE THREAD

**Issue by pavelsinha** [BVLC/caffe#5782]
Hi,
I am having trouble compiling MatConvNet with cuDNN option. It fails to compile 'nnconv_cudnn.cu'. I am using windows 7 platform with Matlab R2017a version and CUDA v8.0. I have copied the details of my graphics card below along with the cmd to compile and the error message

Compile command used:

vl_compilenn('enableGpu', true, 'cudaMethod', 'nvcc', 'EnableCudnn', true, 'verbose', 2, 'cudaRoot', 'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0','enableCudnn', true, 'cudnnRoot', 'local/');

(the following cuDNN files have been copied to the folder \matconvnet\local )
cudnn.h
cudnn.lib
cudnn64_6.dll

gpuDevice
  CUDADevice with properties:

                      Name: 'GeForce GTX 1080'
                     Index: 1
         ComputeCapability: '6.1'
            SupportsDouble: 1
             DriverVersion: 8
            ToolkitVersion: 8
        MaxThreadsPerBlock: 1024
          MaxShmemPerBlock: 49152
        MaxThreadBlockSize: [1024 1024 64]
               MaxGridSize: [2.1475e+09 65535 65535]
                 SIMDWidth: 32
               TotalMemory: 8.5899e+09
           AvailableMemory: 6.6385e+09
       MultiprocessorCount: 20
              ClockRateKHz: 1847500
               ComputeMode: 'Default'
      GPUOverlapsTransfers: 1
    KernelExecutionTimeout: 1
          CanMapHostMemory: 1
           DeviceSupported: 1
            DeviceSelected: 1
			
			

			

nnconv_cudnn.cu 
#$ cl.exe @"C:\Users\PAVELS~1\AppData\Local\Temp/tmpxft_0000356c_00000000-9.res" > "C:/Users/PAVELS~1/AppData/Local/Temp/tmpxft_0000356c_00000000-8_nnconv_cudnn.cpp1.ii"  
nnconv_cudnn.cu 
#$ erase C:\Users\PAVELS~1\AppData\Local\Temp/tmpxft_0000356c_00000000-9.res 
#$ cudafe --allow_managed --m64 --microsoft_version=1800 --msvc_target_version=1800 --compiler_bindir "C:/Program Files (x86)/Microsoft Visual Studio 12.0/VC/../VC/bin/../.." --sdk_dir "C:/Program Files (x86)/Windows Kits/8.1/" -tused --no_remove_unneeded_entities --gen_c_file_name "C:/Users/PAVELS~1/AppData/Local/Temp/tmpxft_0000356c_00000000-5_nnconv_cudnn.cudafe1.c" --stub_file_name "C:/Users/PAVELS~1/AppData/Local/Temp/tmpxft_0000356c_00000000-5_nnconv_cudnn.cudafe1.stub.c" --gen_device_file_name "C:/Users/PAVELS~1/AppData/Local/Temp/tmpxft_0000356c_00000000-5_nnconv_cudnn.cudafe1.gpu" --nv_arch "compute_61" --gen_module_id_file --module_id_file_name "C:/Users/PAVELS~1/AppData/Local/Temp/tmpxft_0000356c_00000000-4_nnconv_cudnn.module_id" --include_file_name "tmpxft_0000356c_00000000-3_nnconv_cudnn.fatbin.c" "C:/Users/PAVELS~1/AppData/Local/Temp/tmpxft_0000356c_00000000-8_nnconv_cudnn.cpp1.ii"  
D:/workspace/matlab/matconvnet/matlab/src/bits/impl/nnconv_cudnn.cu(137): error: too few arguments in function call 
          detected during instantiation of "vl::ErrorCode vl::impl::nnconv_cudnn<dataType>::forward(vl::Context &, vl::Tensor, double, vl::Tensor, double, vl::Tensor, vl::Tensor, int, int, int, int, int, int, int, int) [with dataType=vl::VLDT_Float]"  
(544): here 
 
D:/workspace/matlab/matconvnet/matlab/src/bits/impl/nnconv_cudnn.cu(356): error: too few arguments in function call 
          detected during instantiation of "vl::ErrorCode vl::impl::nnconv_cudnn<dataType>::backward(vl::Context &, vl::Tensor, vl::Tensor, vl::Tensor, vl::Tensor, vl::Tensor, vl::Tensor, int, int, int, int, int, int, int, int) [with dataType=vl::VLDT_Float]"  
(544): here 
 
D:/workspace/matlab/matconvnet/matlab/src/bits/impl/nnconv_cudnn.cu(137): error: too few arguments in function call 
          detected during instantiation of "vl::ErrorCode vl::impl::nnconv_cudnn<dataType>::forward(vl::Context &, vl::Tensor, double, vl::Tensor, double, vl::Tensor, vl::Tensor, int, int, int, int, int, int, int, int) [with dataType=vl::VLDT_Double]"  
(547): here 
 
D:/workspace/matlab/matconvnet/matlab/src/bits/impl/nnconv_cudnn.cu(356): error: too few arguments in function call 
          detected during instantiation of "vl::ErrorCode vl::impl::nnconv_cudnn<dataType>::backward(vl::Context &, vl::Tensor, vl::Tensor, vl::Tensor, vl::Tensor, vl::Tensor, vl::Tensor, int, int, int, int, int, int, int, int) [with dataType=vl::VLDT_Double]"  
(547): here 
 
4 errors detected in the compilation of "C:/Users/PAVELS~1/AppData/Local/Temp/tmpxft_0000356c_00000000-8_nnconv_cudnn.cpp1.ii". 
# --error 0x2 -- 
Error using vl_compilenn>nvcc_compile (line 540)
Command "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin\nvcc" -c "D:\workspace\matlab\matconvnet\matlab\src\bits\impl\nnconv_cudnn.cu"
-v -DNDEBUG -DENABLE_GPU -DENABLE_CUDNN -I"local\include" -DENABLE_DOUBLE -D__SSSE3__ -gencode=arch=compute_61,code=\"sm_61,compute_61\"
-I"C:\Program Files\MATLAB\R2017a\extern\include" -I"C:\Program Files\MATLAB\R2017a\toolbox\distcomp\gpu\extern\include"
-gencode=arch=compute_61,code=\"sm_61,compute_61\"  -O3 -Xcompiler /MD --compiler-bindir "C:\Program Files (x86)\Microsoft Visual Studio
12.0\VC\..\VC\bin" -o "D:\workspace\matlab\matconvnet\matlab\mex\.build\bits\impl\nnconv_cudnn.obj" failed.

Error in vl_compilenn (line 485)
      nvcc_compile(opts, srcs{i}, objfile, flags.nvcc) ;

**Comment by Noiredd** [comment]
This belongs to the [MatConvNet](https://github.com/vlfeat/matconvnet) repo.
