### ISSUE TITLE
problem with dropout after data data layer

### ISSUE THREAD

**Issue by lizhiyuanUSTC** [BVLC/caffe#5784]
Hey, guys. I'm trying to train a CNN model. I added a dropout layer(dropout_ratio is 0.5) after the data layer. When I test my model, the testing accracy is about 0.74. But if the input timed by 2, the testing accuracy is about 94% which is closer to training accuracy. I read the code in caffe:

scale_ = 1. / (1. - threshold_);
 
if (this->phase_ == TRAIN) {
// Create random numbers
caffe_rng_bernoulli(count, 1. - threshold_, mask);
for (int i = 0; i < count; ++i) {
top_data[i] = bottom_data[i] * mask[i] * scale_;
}
} else {
caffe_copy(bottom[0]->count(), bottom_data, top_data);
}

I don't know why this happens.

**Comment by PENGUINLIONG** [comment]
What do you mean, `input timed by 2`? Caffe's code has been tested and used for time. Such infrastructure layer is not going to crash easily. What you wanted to ask might be characteristics of CNN. Maybe you can ask your tutor or [join the user group](https://groups.google.com/forum/#!forum/caffe-users) for help.

**Comment by weiliu89** [comment]
Because during training, drop out will multiply your data by 2 if drop_out  ration is 50%. But test would just copy your original input. So if you multiply input by 2, your test input would match your training input.

**Comment by nano1900** [comment]
Right

**Comment by zli79** [comment]
@lizhiyuanUSTC How did you "the input timed 2" ? Change the original code? Thanks!
