### ISSUE TITLE
share parameters between caffe layers

### ISSUE THREAD

**Issue by anguoyang** [BVLC/caffe#5798]
Hi all, what if I want to re-use the parameters in other layers?
for example, I created a new convolution layer(different with the default conv_layer),  in this layer I need the param in the input_layer(height,width),  in the input layer I could get them by 
const InputParameter& param = this->layer_param_.input_param();
but how could I get it inside my customized layer? I dont want to re-add the same params into prototxt in my layer as hyper parameter.
thank you.

**Comment by PENGUINLIONG** [comment]
So, I assume your question is that, you want to fetch the original size of input from an input layer in other layers.

It can be done in many ways. One of them is to wrap an input layer and spit another blob out with your dimensions kept inside. Other approaches like a layer in-the-middle and global variables (dirty!) are also acceptable.

You can also prevent such repeated work with shell or PowerShell scripts. It's a nice solution.

**Comment by shaibagon** [comment]
Please use the [caffe-users list][1] for usage, installation, or modeling questions, or other requests for help.
You may also post questions on [stackoverflow][3], make sure you tag them with `caffe` tag.  
There is also [caffe.help][4] documenting the different layers of caffe.
Do not post such requests to Issues. Doing so interferes with the development of Caffe.

Please read the [guidelines for contributing][2] before submitting this issue.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
 [3]: http://stackoverflow.com/questions/tagged/caffe
 [4]: http://caffe.help/manual/layers.html
