### ISSUE TITLE
More results than accuracy?

### ISSUE THREAD

**Issue by rmanor** [BVLC/caffe#580]
Hi,

I'm doing binary classification and I would like to get the true positive rate, false positive rate, AUC and so on..
Is there an easy way to get those?
or to implement another layer instead of the accuracy layer?
Thanks.

**Comment by ChenSiqin** [comment]
@rmanor  Could you post your solution of printing the true positive accuracy in the AccuracyLayer ? Thank you !

**Comment by rmanor** [comment]
@ChenSiqin I recently submitted https://github.com/BVLC/caffe/pull/2935 which allows you to output accuracy per class, so you can compute true positive etc.
