### ISSUE TITLE
loss while validation is jumping and training is decreasing

### ISSUE THREAD

**Issue by vishnureghu007** [BVLC/caffe#5800]
what might be the reason for the below loss vs iteration.
blue:training
green:validation
![figure_1](https://user-images.githubusercontent.com/15410424/28561638-cea606e8-713c-11e7-8805-8b46de37f01d.png)

**Comment by PENGUINLIONG** [comment]
What's your dataset? The loss was rather high and I can't say it's converging. If it's a classification task, was the accuracy raising significantly overall?
