### ISSUE TITLE
Undefined function or variable 'caffe_'

### ISSUE THREAD

**Issue by serfaniane** [BVLC/caffe#5803]
I downloaded caffe from the repository and followed the installation guidelines [here](http://caffe.berkeleyvision.org/install_apt.html), and the compilation guidelines [here](http://caffe.berkeleyvision.org/installation.html#compilation) with CMake Build. System info:

```
Matlab R2017a
Ubuntu 16.04 LTS
```

When I run the classification_demo.m in `caffe/matlab/demo` I get the following error.

```
Undefined function or variable 'caffe_'.

Error in caffe.set_mode_cpu (line 5)
caffe_('set_mode_cpu');

Error in classification_demo (line 72)
  caffe.set_mode_cpu();
```

Running the following commands in Matlab yields:

```
>> which caffe_
'caffe_' not found.

>> which caffe.set_mode_gpu()
/usr/caffe/matlab/+caffe/set_mode_gpu.m  % static method or package function
```

If this is a missing path issue, how could I add this to path? I have tried to manually change the following line in `classification_demo.m `

```
if exist('../+caffe', 'dir')  
  addpath('..');
else
  error('Please run this demo from caffe/matlab/demo');
end
```

to 

```
if exist('/usr/caffe/matlab/+caffe', 'dir')    
  addpath('..');
else
  error('Please run this demo from caffe/matlab/demo');
end

```
But still no success.

**Comment by MikeChenfu** [comment]
Have the same problem, do you find a solution? Thanks.

**Comment by PENGUINLIONG** [comment]
It seems MATLAB was unable to find matcaffe. If your caffe was built successfully, there shouldn't be any error. Check if the directory `/usr/caffe/matlab/+caffe` really exists.

**Comment by shaibagon** [comment]
Please use the [caffe-users list][1] for usage, installation, or modeling questions, or other requests for help.
You may also post questions on [stackoverflow][3], make sure you tag them with `caffe` tag.  
There is also [caffe.help][4] documenting the different layers of caffe.
Do not post such requests to Issues. Doing so interferes with the development of Caffe.

Please read the [guidelines for contributing][2] before submitting this issue.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
 [3]: http://stackoverflow.com/questions/tagged/caffe
 [4]: http://caffe.help/manual/layers.html

**Comment by mojoee** [comment]
I solved it by explicitly building matcaffe in the caffe directory.
command: make matcaffe
