### ISSUE TITLE
Caffe compilation error for version 0.15

### ISSUE THREAD

**Issue by gunju** [BVLC/caffe#5805]
I get following compilation error while building caffe version 0.15.

```
[  0%] Running C++/Python protocol buffer compiler on /home/ubuntu/caffe/src/caffe/proto/caffe.proto
Scanning dependencies of target proto
[  1%] Building CXX object src/caffe/CMakeFiles/proto.dir/__/__/include/caffe/proto/caffe.pb.cc.o
Linking CXX static library ../../lib/libproto.a
[  1%] Built target proto
[  2%] [  2%] [  2%] [  4%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir//./cuda_compile_generated_data_transformer.cu.o
Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/util/./cuda_compile_generated_im2col.cu.o
Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/util/./cuda_compile_generated_math_functions.cu.o
Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_cudnn_sigmoid_layer.cu.o
nvcc fatal   : Unsupported gpu architecture 'compute_50'
nvcc fatal   : Unsupported gpu architecture 'compute_50'
CMake Error at cuda_compile_generated_data_transformer.cu.o.cmake:206 (message):
  Error generating
  /home/ubuntu/caffe/build/src/caffe/CMakeFiles/cuda_compile.dir//./cuda_compile_generated_data_transformer.cu.o


CMake Error at cuda_compile_generated_im2col.cu.o.cmake:206 (message):
  Error generating
  /home/ubuntu/caffe/build/src/caffe/CMakeFiles/cuda_compile.dir/util/./cuda_compile_generated_im2col.cu.o


nvcc fatal   : Unsupported gpu architecture 'compute_50'
CMake Error at cuda_compile_generated_math_functions.cu.o.cmake:206 (message):
  Error generating
  /home/ubuntu/caffe/build/src/caffe/CMakeFiles/cuda_compile.dir/util/./cuda_compile_generated_math_functions.cu.o

```

The previous steps were successfully executed but while making I am getting error

**Comment by deepali-c** [comment]
What is the `CUDA` version?

**Comment by gunju** [comment]
Doing nvcc --version I got following:
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2013 NVIDIA Corporation
Built on Wed_Jul_17_18:36:13_PDT_2013
Cuda compilation tools, release 5.5, V5.5.0

So the version is 5.5.0.

**Comment by deepali-c** [comment]
You can modify Makefile.config to get this working   - https://github.com/BVLC/caffe/blob/master/Makefile.config.example#L34

**Comment by Noiredd** [comment]
Always make sure your CUDA version allows you to compile the code for a given architecture - CUDA 5.5 is *very* outdated by now. For `compute_50` I think you need version 7.5 at least. I can't find a more comprehensive source on this, but Wikipedia has a basic [entry](https://en.wikipedia.org/wiki/CUDA#GPUs_supported) on which CUDA SDK version supports which CCs. Unless you need to use a GPU with compute capability below 3.0, I suggest using CUDA 9.0 (there is still one unsolved bug related to v9.1)
