### ISSUE TITLE
Caffe Installation Error- windows

### ISSUE THREAD

**Issue by pmann88** [BVLC/caffe#5808]
@willyd 
I am getting the following error while installing caffe on windows 7.

**Issue summary**
C:\MachineLearning\Projects\caffe>scripts\build_win.cmd
The system cannot find the drive specified.
The system cannot find the drive specified.
INFO: ============================================================
INFO: Summary:
INFO: ============================================================
INFO: MSVC_VERSION               = 14
INFO: WITH_NINJA                 = 0
INFO: CMAKE_GENERATOR            = "Visual Studio 14 2015 Win64"
INFO: CPU_ONLY                   = 1
INFO: CUDA_ARCH_NAME             = Auto
INFO: CMAKE_CONFIG               = Release
INFO: USE_NCCL                   = 0
INFO: CMAKE_BUILD_SHARED_LIBS    = 0
INFO: PYTHON_VERSION             = 3
INFO: BUILD_PYTHON               = 0
INFO: BUILD_PYTHON_LAYER         = 0
INFO: BUILD_MATLAB               = 1
INFO: PYTHON_EXE                 = "python"
INFO: RUN_TESTS                  = 0
INFO: RUN_LINT                   = 0
INFO: RUN_INSTALL                = 0
INFO: ============================================================
'"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\..\..\VC\vcv
arsall.bat"' is not recognized as an internal or external command,
operable program or batch file.
CMake Error at CMakeLists.txt:18 (project):
  Failed to run MSBuild command:

    C:/Program Files (x86)/MSBuild/14.0/bin/MSBuild.exe

  to get the value of VCTargetsPath:

    Microsoft (R) Build Engine version 14.0.25420.1
    Copyright (C) Microsoft Corporation. All rights reserved.

    Build started 7/28/2017 1:34:53 PM.
    Project "C:\MachineLearning\Projects\caffe\build\CMakeFiles\3.9.0\VCTa
rgetsPath.vcxproj" on node 1 (default targets).
    C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Platforms\x64\Platfor
mToolsets\v140\Toolset.targets(36,5): error MSB8036: The Windows SDK version 8.1
 was not found. Install the required version of Windows SDK or change the SDK ve
rsion in the project property pages or by right-clicking the solution and select
ing "Retarget solution". [C:\MachineLearning\Projects\caffe\build\CMakeFil
es\3.9.0\VCTargetsPath.vcxproj]
    Done Building Project "C:\MachineLearning\Projects\caffe\build\CMakeFi
les\3.9.0\VCTargetsPath.vcxproj" (default targets) -- FAILED.

    Build FAILED.

    "C:\MachineLearning\Projects\caffe\build\CMakeFiles\3.9.0\VCTargetsPat
h.vcxproj" (default target) (1) ->
    (Desktop_PlatformPrepareForBuild target) ->
      C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Platforms\x64\Platf
ormToolsets\v140\Toolset.targets(36,5): error MSB8036: The Windows SDK version 8
.1 was not found. Install the required version of Windows SDK or change the SDK
version in the project property pages or by right-clicking the solution and sele
cting "Retarget solution". [C:\MachineLearning\Projects\caffe\build\CMakeF
iles\3.9.0\VCTargetsPath.vcxproj]

        0 Warning(s)
        1 Error(s)

    Time Elapsed 00:00:00.18

  Exit code: 1

-- Configuring incomplete, errors occurred!
See also "C:/MachineLearning/Projects/caffe/build/CMakeFiles/CMakeOutput.l
og".
ERROR: Configure failed

### Your system configuration
Operating system: windows 7
Compiler: VS2015
CUDA version (if applicable): NA
CUDNN version (if applicable): NA
Python or MATLAB version (for pycaffe and matcaffe respectively): Matlab 2014b

**Comment by pmann88** [comment]
I am able to resolve the above problem by using VS2013 as compiler instead of VS2015.

**Comment by fzhuang3** [comment]
For those who wish to continue using VS2015, Windows SDK 8.1 is not included in it. You will need to install it separately: https://social.msdn.microsoft.com/Forums/en-US/4d035e42-0618-476b-b309-ae2673f14de4/the-windows-sdk-version-81-was-not-found-in-vs-2015-update-3?forum=vssetup
