### ISSUE TITLE
OpenCV 3.0 issue

### ISSUE THREAD

**Issue by DanielGr** [BVLC/caffe#581]
In OpenCV 3.0 CV_LOAD_IMAGE_COLOR is not defined (used in window_data_layer.cpp).

I added to window_data_layer.cpp:

#ifndef CV_LOAD_IMAGE_COLOR
#define CV_LOAD_IMAGE_COLOR 1
#endif

works fine.

**Comment by shelhamer** [comment]
This should be fixed in #1849 by way of #1667.
