### ISSUE TITLE
do someone think the caffe has some problems in design when we load the params from pre-trained model?

### ISSUE THREAD

**Issue by unsky** [BVLC/caffe#5811]
do someone think the caffe has some problems in design when we load the params from pre-trained model?
a example, old model: conv1(10 10 10 10)->conv2(10 10 10 10)->conv3(10 10 10) and i use the model generate my first model params
but now,i adjust the new model: conv1(10 10 10 10)->conv2(10 1000 1000 10)->conv3(10 10 10)
but i want load the params from the old model  i must rename the conv2 layer

if the model is very small,i think it work well, but when my  model is very big and the number of redesign layers is very big ,i think this method is very boring.
my suggestion is ignore the layer if the number of params is different in train phase and report error in test phase. i think the suggestion can help us adjust the params more efficient

**Comment by shaibagon** [comment]
Please use the [caffe-users list][1] for usage, installation, or modeling questions, or other requests for help.
You may also post questions on [stackoverflow][3], make sure you tag them with `caffe` tag.  
There is also [caffe.help][4] documenting the different layers of caffe.
Do not post such requests to Issues. Doing so interferes with the development of Caffe.

Please read the [guidelines for contributing][2] before submitting this issue.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
 [3]: http://stackoverflow.com/questions/tagged/caffe
 [4]: http://caffe.help/manual/layers.html
