### ISSUE TITLE
Error while running "make runtest" ( CUDA related )

### ISSUE THREAD

**Issue by hyungwonchoi** [BVLC/caffe#582]
I am currently using GTX Titan and as mentioned in #574 , I am now trying different configurations of nvidia driver and CUDA version on Ubuntu 12.04 LTS.

I downgraded CUDA 6.0 to CUDA 5.5 and installed nvidia driver version of 319.76.

(At first, I tried to install 319.37, but it consistently outputs error saying "kernel source is not found" even if the kernel source exists in /usr/src . )

I could install driver with version >= 319.72 since there was no such errors. I still don't know why. Anyways, I installed 319.76 and CUDA 5.5 and tried to compile caffe with this configuration.

However, when I run "make runtest", it outputs error like below. 

F0702 20:22:03.616968  1247 syncedmem.cpp:47] Check failed: error == cudaSuccess (35 vs. 0)  CUDA driver version is insufficient for CUDA runtime version
**\* Check failure stack trace: ***
    @     0x2b998d149b7d  google::LogMessage::Fail()
    @     0x2b998d14bc7f  google::LogMessage::SendToLog()
    @     0x2b998d14976c  google::LogMessage::Flush()
    @     0x2b998d14c51d  google::LogMessageFatal::~LogMessageFatal()
    @           0x61e504  caffe::SyncedMemory::mutable_gpu_data()
    @           0x5b0751  caffe::Blob<>::mutable_gpu_data()
    @           0x632369  caffe::ConcatLayer<>::Forward_gpu()
    @           0x44db10  caffe::GradientChecker<>::CheckGradientSingle()
    @           0x4d5a44  caffe::ConcatLayerTest_TestGPUGradient_Test<>::TestBody()
    @           0x58dc7d  testing::internal::HandleExceptionsInMethodIfSupported<>()
    @           0x585aa1  testing::Test::Run()
    @           0x585b86  testing::TestInfo::Run()
    @           0x585cc7  testing::TestCase::Run()
    @           0x58601e  testing::internal::UnitTestImpl::RunAllTests()
    @           0x58d7fd  testing::internal::HandleExceptionsInMethodIfSupported<>()
    @           0x5850fe  testing::UnitTest::Run()
    @           0x4434dd  main
    @     0x2b999027376d  (unknown)
    @           0x4481ad  (unknown)
make: **\* [runtest] Aborted (core dumped)

According to #338 , it seems no big problem so I tried to train alexnet, but it outputs the same error. Has anybody gone through the same problem? 

Any helps would be appreciated. 

Hyungwon

**Comment by codecolony** [comment]
@kloudkl Thanks! You saved me :)

**Comment by sarkeribrahim** [comment]
hi, can anyone help me for this error?

[----------] 2 tests from BatchReindexLayerTest/1, where TypeParam = caffe::CPUDevice
[ RUN ] BatchReindexLayerTest/1.TestForward
[ OK ] BatchReindexLayerTest/1.TestForward (0 ms)
[ RUN ] BatchReindexLayerTest/1.TestGradient
[ OK ] BatchReindexLayerTest/1.TestGradient (87 ms)
[----------] 2 tests from BatchReindexLayerTest/1 (87 ms total)

[----------] 5 tests from ImageDataLayerTest/1, where TypeParam = caffe::CPUDevice
[ RUN ] ImageDataLayerTest/1.TestReshape
[ OK ] ImageDataLayerTest/1.TestReshape (46 ms)
[ RUN ] ImageDataLayerTest/1.TestShuffle
[ OK ] ImageDataLayerTest/1.TestShuffle (106 ms)
[ RUN ] ImageDataLayerTest/1.TestRead
[ OK ] ImageDataLayerTest/1.TestRead (103 ms)
[ RUN ] ImageDataLayerTest/1.TestResize
[ OK ] ImageDataLayerTest/1.TestResize (122 ms)
[ RUN ] ImageDataLayerTest/1.TestSpace
[ OK ] ImageDataLayerTest/1.TestSpace (63 ms)
[----------] 5 tests from ImageDataLayerTest/1 (440 ms total)

[----------] Global test environment tear-down
[==========] 1096 tests from 150 test cases ran. (68513 ms total)
[ PASSED ] 1095 tests.
[ FAILED ] 1 test, listed below:
[ FAILED ] NeuronLayerTest/0.TestPReLUForward, where TypeParam = caffe::CPUDevice

1 FAILED TEST
make[3]: *** [src/caffe/test/CMakeFiles/runtest] Error 1
make[2]: *** [src/caffe/test/CMakeFiles/runtest.dir/all] Error 2
make[1]: *** [src/caffe/test/CMakeFiles/runtest.dir/rule] Error 2
make: *** [runtest] Error 2
