### ISSUE TITLE
LINK1104 error: can not open file "python35.lib"  whin building classfication example

### ISSUE THREAD

**Issue by wanggao1990** [BVLC/caffe#5826]
Project classfication can built successfully with Release configuration. When it comes to Debug, there's an error LNK1104 that can not open file "python35.lib" .
I wonder that how it could be link library "python35.lib" when AdditionalDependencies has include "python35_d.lib".

**Comment by willyd** [comment]
Duplicate of #5814

**Comment by wangpengabc** [comment]
I ceate an environment of python3.5 and copy the "python35.lib" in the folder python36/libs to the current python environment folder /libs.
