### ISSUE TITLE
I wanna test CIFAR-10 with Alexnet model.

### ISSUE THREAD

**Issue by seongkyun** [BVLC/caffe#5831]
Please use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) for usage, installation, or modeling questions, or other requests for help.
_Do not post such requests to Issues._ Doing so interferes with the development of Caffe.

Please read the [guidelines for contributing](https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md) before submitting this issue.

### Issue summary

I just want to test CIFAT-10 with Alexnet model.
I made Alexnet's deploy.prototxt and solver.prototxt using caffe's example folders like 
`$CAFFE_ROOT/models/bvlc_alexnet/` files
 and used example lmdb dataset
`$CAFFE_ROOT/examples/cifar10/create_cifar10.sh`

finally i got 
`iteration.caffemodel` file.

now i am trying to validate my training code. but i dont know how to, and even i tried to follow classification examples in caffe homepage, but errors occurs everywhere...

can anybody tell me how to test my network with dataset??

i am newbie in deep learning even caffe toolkit.

help me guyz :)

### Steps to reproduce

If you are having difficulty building Caffe or training a model, please ask the caffe-users mailing list. If you are reporting a build error that seems to be due to a bug in Caffe, please attach your build configuration (either Makefile.config or CMakeCache.txt) and the output of the make (or cmake) command.

### Your system configuration
Operating system: Ubuntu 16.04LTS
Compiler: i don't know
CUDA version (if applicable): 8.0
CUDNN version (if applicable): 5.1
BLAS: i don't know
Python or MATLAB version (for pycaffe and matcaffe respectively):
python version

**Comment by shaibagon** [comment]
Please use the [caffe-users list][1] for usage, installation, or modeling questions, or other requests for help.
You may also post questions on [stackoverflow][3], make sure you tag them with `caffe` tag.  
Do not post such requests to Issues. Doing so interferes with the development of Caffe.

Please read the [guidelines for contributing][2] before submitting this issue.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
 [3]: http://stackoverflow.com/questions/tagged/caffe
