### ISSUE TITLE
Problems with moving models to Caffe

### ISSUE THREAD

**Issue by system123** [BVLC/caffe#5837]
I have a pseudo-siamese model which I created in Keras with Tensoflow backend and trained using Adam and a batch size of 64. The model takes in two 1x112x122 images patches which have been preprocessed and are float32 type, stored in an HDF5 dataset. 

I recently converted this Keras model to Caffe as Caffe is meant to be faster for training. I am training the model on a machine with a Nvidia Titan X GPU. However, I am having problems with Caffe which throws an Out of Memory error when trying to train the model with a batch size of 32 (half of what my Keras model uses) 

'''
I0810 10:53:48.619500    50 caffe.cpp:248] Starting Optimization
I0810 10:53:48.619520    50 solver.cpp:272] Solving sarptical_train_test
I0810 10:53:48.619527    50 solver.cpp:273] Learning Rate Policy: fixed
F0810 10:53:49.498266    50 syncedmem.cpp:71] Check failed: error == cudaSuccess (2 vs. 0)  out of memory
*** Check failure stack trace: ***
    @     0x7f9ac3c1c5cd  google::LogMessage::Fail()
    @     0x7f9ac3c1e433  google::LogMessage::SendToLog()
    @     0x7f9ac3c1c15b  google::LogMessage::Flush()
    @     0x7f9ac3c1ee1e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f9ac421d1e8  caffe::SyncedMemory::mutable_gpu_data()
    @     0x7f9ac4206aa3  caffe::Blob<>::mutable_gpu_diff()
    @     0x7f9ac43f8a7b  caffe::ConvolutionLayer<>::Backward_gpu()
    @     0x7f9ac41ef9a8  caffe::Net<>::BackwardFromTo()
    @     0x7f9ac41ef9ff  caffe::Net<>::Backward()
    @     0x7f9ac41896d4  caffe::Solver<>::Step()
    @     0x7f9ac418a3fa  caffe::Solver<>::Solve()
    @           0x40be3f  train()
    @           0x408450  main
    @     0x7f9ac2909830  __libc_start_main
    @           0x408c79  _start
    @              (nil)  (unknown)
Aborted (core dumped)
'''

Furthermore, if I reduce the batch size to 16 the model starts to train but does not learn anything, and the accuracy just stays at 50% (binary classification problem).

My model and solver can be found here: https://gist.github.com/system123/d0735f2ffd3be3bd63c443309be081a2

I'm not sure if I am doing something wrong or not, perhaps someone has some insights for me?

**Comment by shaibagon** [comment]
Please use the [caffe-users list][1] for usage, installation, or modeling questions, or other requests for help.
You may also post questions on [stackoverflow][3], make sure you tag them with `caffe` tag.  
Do not post such requests to Issues. Doing so interferes with the development of Caffe.

Please read the [guidelines for contributing][2] before submitting this issue.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
 [3]: http://stackoverflow.com/questions/tagged/caffe
