### ISSUE TITLE
Reload weights into fc layer after saving in csr matrix format

### ISSUE THREAD

**Issue by pgadosey** [BVLC/caffe#5847]
### Issue summary
Hi,
    I am trying to store weights in a the fc layers in a compressed sparse row format. When I retrieve the weights and convert them to csr matrix format , it's size in memory 
reduces drastically but when I load it back into caffe my model size remains the same. Basically this is what I'm doing:
                                                             temp2 = net.params['ip1'][0].data.shape
                                                             sparse_csr1 = sparse.scr_matrix(temp2, shape)
                                                             net.params['ip1'][0].data[...] = sparse_csr1
                                                             net.save('compressed.caffemodel')

Any suggestions will be appreciated

### Your system configuration
Operating system: Ubuntu Server 16.0w
Compiler:
CUDA version (if applicable):8.0
CUDNN version (if applicable):7
BLAS:
Python or MATLAB version (for pycaffe and matcaffe respectively):Python 2.7

**Comment by shaibagon** [comment]
[Seems like stackoverflow has already addressed this ](https://stackoverflow.com/q/45686472)
