### ISSUE TITLE
Video Examples

### ISSUE THREAD

**Issue by tamnicer** [BVLC/caffe#5856]
Please use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) for usage, installation, or modeling questions, or other requests for help.
_Do not post such requests to Issues._ Doing so interferes with the development of Caffe.

Please read the [guidelines for contributing](https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md) before submitting this issue.

### Issue summary
errors on 'test.prototxt' for video based result (visualization)

### Steps to reproduce
I modify 'examples/ssd/ssd_pascal_video.py'  
this file create 'test.py' for video input data. ( *.avi)  ( I'll call this test.py as 'A')
i want to use that codes for the other networks which is used for video input data classification.

previously, my network file is works well for './build/tools/caffe -test -model -weight -gpu'
here is my test.prototxt file.

`

      name: "my-SSD"
      layer {
      name: "data"
      type: "VideoData"
      top: "data"
      top: "label"
      include {
         phase: TEST
      }
      transform_param {
        scale: 0.007843
        mean_value: 127.5
        mean_value: 127.5
        mean_value: 127.5
        resize_param {
          prob: 1.0
          resize_mode: WARP
          height: 300
          width: 300
          interp_mode: LINEAR
         }
       }
       data_param {
         batch_size: 1
       }
       video_data_param {
         video_type: VIDEO
         video_file: "examples/videos/test.avi"
       }
     }
 
     ... networks
     
     layer {
       name: "detection_out"
       type: "DetectionOutput"
       bottom: "mbox_loc"
       bottom: "mbox_conf_flatten"
       bottom: "mbox_priorbox"
       top: "detection_out"
       include {
         phase: TEST
       }
       transform_param {
         scale: 0.007843
         mean_value: 127.5
         mean_value: 127.5
         mean_value: 127.5
         resize_param {
           prob: 1.0
           resize_mode: WARP
           height: 300
           width: 300
           interp_mode: LINEAR
         }
       }
       detection_output_param {
         num_classes: 21
         share_location: true
         background_label_id: 0
         nms_param {
           nms_threshold: 0.45
           top_k: 400
         }
         save_output_param {
           label_map_file: "data/VOC0712/labelmap_voc.prototxt"
         }
         code_type: CENTER_SIZE
         keep_top_k: 200
         confidence_threshold: 0.01
         visualize: true
         visualize_threshold: 0.3
       }
     }
     layer {
       name: "silence"
       type: "Silence"
       bottom: "detection_out"
       include {
         phase: TEST
       }
     }

`

**but after i change the input and output layer based on the 'test.py' (A),
i got a errors regarding on the num_axes.** 

I0818 10:34:07.130676  7595 caffe.cpp:289] Running for 50 iterations.
F0818 10:34:07.203449  7595 blob.hpp:140] Check failed: num_axes() <= 4 (161982260 vs. 4) Cannot use legacy accessors on Blobs with > 4 axes.
*** Check failure stack trace: ***
    @     0x7f12f0e95daa  (unknown)
    @     0x7f12f0e95ce4  (unknown)
    @     0x7f12f0e956e6  (unknown)
    @     0x7f12f0e98687  (unknown)
    @     0x7f12f1584656  caffe::Blob<>::LegacyShape()
    @     0x7f12f1589899  caffe::DataTransformer<>::TransformInv()
    @     0x7f12f17cdb51  caffe::DetectionOutputLayer<>::Forward_gpu()
    @     0x7f12f1531db2  caffe::Net<>::ForwardFromTo()
    @     0x7f12f1531ec7  caffe::Net<>::Forward()
    @           0x4082d9  test()
    @           0x406528  main
    @     0x7f12efe8df45  (unknown)
    @           0x406d00  (unknown)
    @              (nil)  (unknown)

please help me 

### Your system configuration
Operating system: ubuntu 14.04
Compiler: gcc
CUDA version (if applicable): 8.0
CUDNN version (if applicable): 6.0
BLAS: atlas

**Comment by shaibagon** [comment]
Please use the [caffe-users list][1] for usage, installation, or modeling questions, or other requests for help.
You may also post questions on [stackoverflow][3], make sure you tag them with `caffe` tag.  
There is also [caffe.help][4] documenting the different layers of caffe.
Do not post such requests to Issues. Doing so interferes with the development of Caffe.

Please read the [guidelines for contributing][2] before submitting this issue.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
 [3]: http://stackoverflow.com/questions/tagged/caffe
 [4]: http://caffe.help/manual/layers.html
