### ISSUE TITLE
Errors of conflits between protobuf 3.2.0 and 2.6.1 in caffe via python

### ISSUE THREAD

**Issue by gerald4** [BVLC/caffe#5861]
Can people help me ?
I installed caffe on ubuntu 16.04 with CUDA and CUDNN, protobuf 3.2.0. It was working fine but when I installed others packages in my system, i have problems with caffe in python.
import caffe gives me this error 

>>> import caffe
[libprotobuf FATAL google/protobuf/stubs/common.cc:61] This program requires version 3.2.0 of the Protocol Buffer runtime library, but the installed version is 2.6.1.  Please update your library.  If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.  (Version verification failed in "google/protobuf/descriptor.pb.cc".)
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  This program requires version 3.2.0 of the Protocol Buffer runtime library, but the installed version is 2.6.1.  Please update your library.  If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.  (Version verification failed in "google/protobuf/descriptor.pb.cc".)

**Comment by arvids-p** [comment]
I have a similar problem. I did get past this warning with  [protobuf 3.3](https://github.com/google/protobuf/releases) and followed [these instructions](https://github.com/google/protobuf/blob/master/src/README.md), then reinstalled everything.

**Comment by gerald4** [comment]
Yes, I have already reinstalled everything with this protobuf.

**Comment by arvids-p** [comment]
No further errors? I have a lot of trouble with protobuf throwing segfaults now. What version is working for you?

**Comment by gerald4** [comment]
I used version 3.3.2.
