### ISSUE TITLE
make runtest error

### ISSUE THREAD

**Issue by HellerFang** [BVLC/caffe#5863]
I make caffe had no any error and make test too, but make runtest failed.
Environment: GTX1070(notebook), CUDA7.5, cudnn-7.5-linux-x64-v5.1, Ubuntu14.04, opencv3.3
My Makefile.config:
USE_CUDNN := 1
OPENCV_VERSION := 3
CUDA_ARCH := -gencode arch=compute_20,code=sm_20 \
                -gencode arch=compute_20,code=sm_21 \
                -gencode arch=compute_30,code=sm_30 \
                -gencode arch=compute_35,code=sm_35 \
                -gencode arch=compute_50,code=sm_50 \
                -gencode arch=compute_52,code=sm_52 \
        #       -gencode arch=compute_60,code=sm_60 \
        #       -gencode arch=compute_61,code=sm_61 \
        #       -gencode arch=compute_61,code=compute_61
BLAS := atlas
make runtest result:
[ RUN      ] AdaGradSolverTest/2.TestLeastSquaresUpdateWithEverythingAccum
F0820 19:35:52.804003 16606 adagrad_solver.cu:21] Check failed: error == cudaSuccess (8 vs. 0)  invalid device function
*** Check failure stack trace: ***
    @     0x2b3f78c66dbd  google::LogMessage::Fail()
    @     0x2b3f78c68c5d  google::LogMessage::SendToLog()
    @     0x2b3f78c669ac  google::LogMessage::Flush()
    @     0x2b3f78c6957e  google::LogMessageFatal::~LogMessageFatal()
    @     0x2b3f7fb9476d  caffe::adagrad_update_gpu<>()
    @     0x2b3f7fb46819  caffe::AdaGradSolver<>::ComputeUpdateValue()
    @     0x2b3f7fb4983b  caffe::SGDSolver<>::ApplyUpdate()
    @     0x2b3f7f9f31dc  caffe::Solver<>::Step()
    @     0x2b3f7f9f392a  caffe::Solver<>::Solve()
    @           0x6f13cc  caffe::GradientBasedSolverTest<>::RunLeastSquaresSolver()
    @           0x702c2b  caffe::GradientBasedSolverTest<>::CheckAccumulation()
    @           0x900193  testing::internal::HandleExceptionsInMethodIfSupported<>()
    @           0x8f6e77  testing::Test::Run()
    @           0x8f6f1e  testing::TestInfo::Run()
    @           0x8f7025  testing::TestCase::Run()
    @           0x8fa368  testing::internal::UnitTestImpl::RunAllTests()
    @           0x8fa5f7  testing::UnitTest::Run()
    @           0x46ca2f  main
    @     0x2b3f80b11f45  (unknown)
    @           0x474739  (unknown)
make: *** [runtest] Aborted (core dumped)
Why?

**Comment by daodao316** [comment]
if you use GTX1070 ,  compute_61

**Comment by Noiredd** [comment]
In general, make sure to check the [compute capability](https://developer.nvidia.com/cuda-gpus) of your device and select the appropriate architecture for CUDA build.

**Comment by HellerFang** [comment]
run test worked well when the CUDA is CUDA8.0, my device's compute capability is 61, but CUDA7.5 can only support less 52, our project needs CUDA7.5, maybe the test codes can't wrok well for CUDA7.5 ? @Noiredd
