### ISSUE TITLE
Could caffe work with cudnn v7 now?

### ISSUE THREAD

**Issue by 7oud** [BVLC/caffe#5868]
Cudnn v7 has released for a few days, some deep learning frameworks have already integrated it. It seemed  caffe has a little lag. The tensor core and grouped convolution in cudnn v7 has large attraction

**Comment by CDLuminate** [comment]
https://github.com/BVLC/caffe/pull/5869

**Comment by gineshidalgo99** [comment]
Once #5869 is added yes, it'll be working nicely. I'm using it following #5869 (and I have 2 servers, one with cuDNN 7 and one with 5.1, same code works nicely in both)

**Comment by Noiredd** [comment]
Since #5972 you can now build Caffe with cuDNN v7. For the grouped convolution feature, please look at #5879.
