### ISSUE TITLE
when I  build caffe, It displays as following wrong.

### ISSUE THREAD

**Issue by daicoolb** [BVLC/caffe#5870]
### Issue summary
**after I input " make all " , it displays as follow**
AR -o .build_release/lib/libcaffe.a
LD -o .build_release/lib/libcaffe.so.1.0.0-rc5
/usr/bin/ld: cannot find -l -lopencv_core
collect2: error: ld returned 1 exit status
Makefile:573: recipe for target '.build_release/lib/libcaffe.so.1.0.0-rc5' failed
make: *** [.build_release/lib/libcaffe.so.1.0.0-rc5] Error 1

### Steps to reproduce
make all -j8

### Your system configuration
Operating system: Ubuntu 16.04
pycaffe

**Comment by Noiredd** [comment]
Please do not post usage, installation, or modeling questions, or other requests for help to Issues. Use the [caffe-users list][1] instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe. Please read the [guidelines for contributing][2] before submitting an issue or a pull request.

Questions about missing libraries have been asked multiple times. Please research the meaning of `/usr/bin/ld: cannot find -l<library>` message and how to install missing libraries.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
