### ISSUE TITLE
cafe-face failed on detecting an image containing faces from LFW!

### ISSUE THREAD

**Issue by yiakwy** [BVLC/caffe#5871]
In face ML problems, we have three basic problems:

(1) finding universal face feature vector (independent on dataset )
(2) faces comparison
(3) face identification

I am doing face identification on Labeled Faces in The Wild (LFW) dataset.

I.E. giving me a 3-channel image containing faces from LFW, I need to detect which face it is.

My procedure: 

1. find a face model: caffemodel + deploy.prototxt
2. do scaling, crop, and so on.
3.1 if the output model is label, i.e. softamx, I need to identify how it determines label from LFW
3.2 if the output is feature vector, i.e. fc7 or fc5, 
for img in lfw_people.images:
  ...
  curr_fea = net.forward()
  score = cosing(target_fea, curr_fea)
  if (score > 0.5):
     ret.append((curr_fea, score))

Output the largest score. 

One experiment for caffe-face, I used "face_model" to perform above actions. But I cannot not get the right image I need.

I am seriously doubt whether the model is as good as what they claimed in papers.

Updated on 25th Aug 2017
===================

I have figured out how to align the batched size 20 for "light_CNN" model. By referring to [NVIDIA's implementation](https://github.com/NVIDIA/DIGITS/blob/digits-2.0/examples/classification/example.py), I need to do:

``` python
    if img.ndim == 2:
        img = img[:,:,np.newaxis]
    print("before transforming, image : ", img.shape)
    transformed_image = transformer.preprocess('data', img)
    print("transformed image shape is : (%s,%s,%s)" % transformed_image.shape)
    net.blobs['data'].data[0] = transformed_image
```

Before I tackle the problem using above method, I have reviewed the paper and find several problems related to the MFM op. I will open a new thread to deal with it.

Now I can got predicted face id. But I still need to figure out what is LFW mean file, it seems that the label is not correct. The image is a sum of five images. I cannot clearly figure out they the label is correct.

**Comment by shaibagon** [comment]
Please use the [caffe-users list][1] for usage, installation, or modeling questions, or other requests for help.
You may also post questions on [stackoverflow][3], make sure you tag them with `caffe` tag.  
There is also [caffe.help][4] documenting the different layers of caffe.
Do not post such requests to Issues. Doing so interferes with the development of Caffe.

Please read the [guidelines for contributing][2] before submitting this issue.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
 [3]: http://stackoverflow.com/questions/tagged/caffe
 [4]: http://caffe.help/manual/layers.html
