### ISSUE TITLE
Check failed: K_ == new_K (10240 vs. 100352) Input size incompatible with inner product parameters.

### ISSUE THREAD

**Issue by July0zhu** [BVLC/caffe#5874]
I had get this mistake when i was trained:Check failed: K_ == new_K (10240 vs. 100352) Input size incompatible with inner product parameters.i want known that what caused this mistake and how can I solve this problem？Please help me，thanks！

**Comment by shaibagon** [comment]
Please use the [caffe-users list][1] for usage, installation, or modeling questions, or other requests for help.
You may also post questions on [stackoverflow][3], make sure you tag them with `caffe` tag.  
Do not post such requests to Issues. Doing so interferes with the development of Caffe.

Please read the [guidelines for contributing][2] before submitting this issue.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
 [3]: http://stackoverflow.com/questions/tagged/caffe
