### ISSUE TITLE
Caffe compiler

### ISSUE THREAD

**Issue by YangBain** [BVLC/caffe#5878]
Hi everyone:
I ran
cd caffe 
cp Makefile.config.example Makefile.config
make -j8
***********************************************************************
CXX/LD -o .build_release/tools/finetune_net.bin
.build_release/lib/libcaffe.so: undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
/home/beans/anaconda2/lib/libgio-2.0.so.0: undefined reference to `g_strv_contains'
/home/beans/anaconda2/lib/libgobject-2.0.so.0: undefined reference to `g_option_group_unref'
/home/beans/anaconda2/lib/libgobject-2.0.so.0: undefined reference to `g_option_group_ref'
/home/beans/anaconda2/lib/libgio-2.0.so.0: undefined reference to `g_sequence_is_empty'
/home/beans/anaconda2/lib/libgio-2.0.so.0: undefined reference to `g_thread_pool_move_to_front'
collect2: error: ld returned 1 exit status
make: *** [.build_release/tools/get_image_size.bin] Error 1
make: *** Waiting for unfinished jobs....
.build_release/tools/extract_features.o: In function `int feature_extraction_pipeline<float>(int, char**)':
extract_features.cpp:(.text._Z27feature_extraction_pipelineIfEiiPPc[_Z27feature_extraction_pipelineIfEiiPPc]+0x1f1b): undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
extract_features.cpp:(.text._Z27feature_extraction_pipelineIfEiiPPc[_Z27feature_extraction_pipelineIfEiiPPc]+0x259b): undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
extract_features.cpp:(.text._Z27feature_extraction_pipelineIfEiiPPc[_Z27feature_extraction_pipelineIfEiiPPc]+0x25b6): undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
extract_features.cpp:(.text._Z27feature_extraction_pipelineIfEiiPPc[_Z27feature_extraction_pipelineIfEiiPPc]+0x2786): undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
extract_features.cpp:(.text._Z27feature_extraction_pipelineIfEiiPPc[_Z27feature_extraction_pipelineIfEiiPPc]+0x2797): undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
.build_release/tools/extract_features.o:extract_features.cpp:(.text._Z27feature_extraction_pipelineIfEiiPPc[_Z27feature_extraction_pipelineIfEiiPPc]+0x27a8): more undefined references to `std::__throw_out_of_range_fmt(char const*, ...)' follow
/home/beans/anaconda2/lib/libgio-2.0.so.0: undefined reference to `g_strv_contains'
/home/beans/anaconda2/lib/libgobject-2.0.so.0: undefined reference to `g_option_group_unref'
/home/beans/anaconda2/lib/libgobject-2.0.so.0: undefined reference to `g_option_group_ref'
/home/beans/anaconda2/lib/libgio-2.0.so.0: undefined reference to `g_sequence_is_empty'
/home/beans/anaconda2/lib/libgio-2.0.so.0: undefined reference to `g_thread_pool_move_to_front'
collect2: error: ld returned 1 exit status
make: *** [.build_release/tools/extract_features.bin] Error 1
.build_release/lib/libcaffe.so: undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
/home/beans/anaconda2/lib/libgio-2.0.so.0: undefined reference to `g_strv_contains'
/home/beans/anaconda2/lib/libgobject-2.0.so.0: undefined reference to `g_option_group_unref'
/home/beans/anaconda2/lib/libgobject-2.0.so.0: undefined reference to `g_option_group_ref'
/home/beans/anaconda2/lib/libgio-2.0.so.0: undefined reference to `g_sequence_is_empty'
/home/beans/anaconda2/lib/libgio-2.0.so.0: undefined reference to `g_thread_pool_move_to_front'
collect2: error: ld returned 1 exit status
.build_release/lib/libcaffe.so: undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
/home/beans/anaconda2/lib/libgio-2.0.so.0: undefined reference to `g_strv_contains'
/home/beans/anaconda2/lib/libgobject-2.0.so.0: undefined reference to `g_option_group_unref'
/home/beans/anaconda2/lib/libgobject-2.0.so.0: undefined reference to `g_option_group_ref'
/home/beans/anaconda2/lib/libgio-2.0.so.0: undefined reference to `g_sequence_is_empty'
/home/beans/anaconda2/lib/libgio-2.0.so.0: undefined reference to `g_thread_pool_move_to_front'
collect2: error: ld returned 1 exit status
make: *** [.build_release/tools/compute_image_mean.bin] Error 1
make: *** [.build_release/tools/create_label_map.bin] Error 1
.build_release/lib/libcaffe.so: undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
/home/beans/anaconda2/lib/libgio-2.0.so.0: undefined reference to `g_strv_contains'
/home/beans/anaconda2/lib/libgobject-2.0.so.0: undefined reference to `g_option_group_unref'
/home/beans/anaconda2/lib/libgobject-2.0.so.0: undefined reference to `g_option_group_ref'
/home/beans/anaconda2/lib/libgio-2.0.so.0: undefined reference to `g_sequence_is_empty'
/home/beans/anaconda2/lib/libgio-2.0.so.0: undefined reference to `g_thread_pool_move_to_front'
collect2: error: ld returned 1 exit status
make: *** [.build_release/tools/upgrade_solver_proto_text.bin] Error 1
.build_release/lib/libcaffe.so: undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
/home/beans/anaconda2/lib/libgio-2.0.so.0: undefined reference to `g_strv_contains'
/home/beans/anaconda2/lib/libgobject-2.0.so.0: undefined reference to `g_option_group_unref'
/home/beans/anaconda2/lib/libgobject-2.0.so.0: undefined reference to `g_option_group_ref'
/home/beans/anaconda2/lib/libgio-2.0.so.0: undefined reference to `g_sequence_is_empty'
/home/beans/anaconda2/lib/libgio-2.0.so.0: undefined reference to `g_thread_pool_move_to_front'
collect2: error: ld returned 1 exit status
make: *** [.build_release/tools/caffe.bin] Error 1
.build_release/tools/convert_annoset.o: In function `main':
convert_annoset.cpp:(.text.startup+0x25c0): undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
/home/beans/anaconda2/lib/libgio-2.0.so.0: undefined reference to `g_strv_contains'
/home/beans/anaconda2/lib/libgobject-2.0.so.0: undefined reference to `g_option_group_unref'
/home/beans/anaconda2/lib/libgobject-2.0.so.0: undefined reference to `g_option_group_ref'
/home/beans/anaconda2/lib/libgio-2.0.so.0: undefined reference to `g_sequence_is_empty'
/home/beans/anaconda2/lib/libgio-2.0.so.0: undefined reference to `g_thread_pool_move_to_front'
collect2: error: ld returned 1 exit status
make: *** [.build_release/tools/convert_annoset.bin] Error 1
****************************************************************************************************
I try many solutions, but finally this problem can not be solved. So anyone who has idea for this problem. Any help from you will be appreciated. Thank you.
Bin Yang

**Comment by znmeb** [comment]
It looks like your PATHs are using Anaconda, specifically Python *2* Anaconda. The default `Makefile.config.example` is set up to use the system Python, not the one in Anaconda, so there might be missing dependencies. Try editing `Makefile.config` after the copy to use Anaconda's Python.

By the way, `caffe` is included in the Anaconda distribution already compiled! Just activate the environment you want to run `caffe` in and typing `conda install caffe`.

**Comment by Noiredd** [comment]
Please post usage, installation, or modeling questions, or other requests for help to the [caffe-users list][1] instead of Issues. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe. Please read the [guidelines for contributing][2] before submitting an issue or a pull request.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
