### ISSUE TITLE
Formula to calculate dimensions of output of Deconvolution filter given kernel filter size and stride. 

### ISSUE THREAD

**Issue by chowkamlee81** [BVLC/caffe#5897]
Formula to calculate dimensions of output of Deconvolution filter given kernel filter size and stride
How the stride factor is related to the upsampling factor?
Kindly suggest

**Comment by tiwaria9034** [comment]
Please refer to this link: https://adeshpande3.github.io/A-Beginner%27s-Guide-To-Understanding-Convolutional-Neural-Networks-Part-2/

Convolved (output) image is downsized by the value of stride factor.

**Comment by chowkamlee81** [comment]
Convolution downsize the image based on image parameters using the formula new_dim =(old_dim+2P-K)/Stride+1.
Whether the same formula holds good for deconvolution operation as deconvolution does upsampling?
Kindly suggest us.

**Comment by shaibagon** [comment]
You can find the formula for `"Deconvolution"` layer [here](http://disq.us/p/1kjm04s).

Please use the [caffe-users list][1] for usage, installation, or modeling questions, or other requests for help.
You may also post questions on [stackoverflow][3], make sure you tag them with `caffe` tag.  
Do not post such requests to Issues. Doing so interferes with the development of Caffe.

Please read the [guidelines for contributing][2] before submitting this issue.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
 [3]: http://stackoverflow.com/questions/tagged/caffe
