### ISSUE TITLE
Caffe Import Error:  ../ caffe/_caffe.so: undefined symbol: _ZN5caffe10PyErrFatalEv

### ISSUE THREAD

**Issue by anilsathyan7** [BVLC/caffe#5899]
I'am facing an caffe import error problem similar to 
"ImportError:caffe.so: undefined symbol: _ZN5caffe4mtx_E #3834"

I have tried Uncommenting the line:
WITH_PYTHON_LAYER := 1 and recompiled everything..
Still the problem persists.

Using CUDA 8,,NVIDIA Caffe 0.16,Ubuntu 16.04
Everything worked correctly; prior to this step..

Installation reference: https://github.com/BVLC/caffe/wiki/Ubuntu-16.04-or-15.10-Installation-Guide

**Comment by shaibagon** [comment]
Please use the [caffe-users list][1] for usage, installation, or modeling questions, or other requests for help.
You may also post questions on [stackoverflow][3], make sure you tag them with `caffe` tag.  
Do not post such requests to Issues. Doing so interferes with the development of Caffe.

Please read the [guidelines for contributing][2] before submitting this issue.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
 [3]: http://stackoverflow.com/questions/tagged/caffe
