### ISSUE TITLE
caffe multigpu training

### ISSUE THREAD

**Issue by gerald4** [BVLC/caffe#5908]
I have installed caffe for gpu.
It works well and i have already trained some models.

I have a gpu with 4gigas Ram and I have a model which required memory is more than 5gigas.

I want to know that if I am connected to a distant machine with gpu, i can train my net on multi-gpu (my one + its distant machine).

**Comment by qilinli** [comment]
have a look with nccl from nvidia

**Comment by gerald4** [comment]
I will see

**Comment by gerald4** [comment]
Is it possible to train a net on a local caffe with a distant gpu via ssh ?

**Comment by Noiredd** [comment]
I do not think this is possible without Caffe installed on the remote machine. For details, please post on the [caffe-users list][1], as this is the place for usage, installation, or modeling questions, or other requests for help

Please read the [guidelines for contributing][2] before submitting an issue or a pull request.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
