### ISSUE TITLE
label wrong in imagenet 2012 test data split txt

### ISSUE THREAD

**Issue by MingSun-Tse** [BVLC/caffe#5909]
I downloaded the `caffe_ilsvrc12.tar.gz` in `data/ilsvrc12` via `get_ilsvrc_aux.sh` and unzipped it, but found the label in `test.txt` is ALL 0.  Anyone has the right `test.txt`?

**Comment by shaibagon** [comment]
Please use the [caffe-users list][1] for usage, installation, or modeling questions, or other requests for help.
You may also post questions on [stackoverflow][3], make sure you tag them with `caffe` tag.  
Do not post such requests to Issues. Doing so interferes with the development of Caffe.

Please read the [guidelines for contributing][2] before submitting this issue.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
 [3]: http://stackoverflow.com/questions/tagged/caffe
