### ISSUE TITLE
create_cifar10.sh: 13: create_cifar10.sh: ./build/examples/cifar10/convert_cifar_data.bin: not found

### ISSUE THREAD

**Issue by pangyanhui923** [BVLC/caffe#5910]
Hello there! I was trying to run the cifar10 caffar10 example, the implementation of create_cifar10.sh regardless of the caffe directory or in the caffe / examples / cifar10 directory implementation, the system is always error: ./ build / examples / cifar10 / convert_cifar_data. bin: not found. Please help the big god to help doubts.

**Comment by shaibagon** [comment]
Have you compiled caffe tools (`make tools`)?

Please use the [caffe-users list][1] for usage, installation, or modeling questions, or other requests for help.
You may also post questions on [stackoverflow][3], make sure you tag them with `caffe` tag.  
Do not post such requests to Issues. Doing so interferes with the development of Caffe.

Please read the [guidelines for contributing][2] before submitting this issue.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
 [3]: http://stackoverflow.com/questions/tagged/caffe
