### ISSUE TITLE
Error with make matcaffe 

### ISSUE THREAD

**Issue by chendingyan** [BVLC/caffe#5911]
Please use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) for usage, installation, or modeling questions, or other requests for help.
_Do not post such requests to Issues._ Doing so interferes with the development of Caffe.

Please read the [guidelines for contributing](https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md) before submitting this issue.

### Issue summary
**after I use "make matcaffe" 
The following error log comes:**

MEX matlab/+caffe/private/caffe_.cpp
Building with 'Xcode Clang++'.
In file included from /usr/local/Cellar/caffe/matlab/+caffe/private/caffe_.cpp:18:
In file included from ./include/caffe/caffe.hpp:12:
./include/caffe/net.hpp:41:5: warning: unused typedef 'INVALID_REQUESTED_LOG_SEVERITY' [-Wunused-local-typedef]
    LOG_EVERY_N(WARNING, 1000) << "DEPRECATED: ForwardPrefilled() "
    ^
/usr/local/include/glog/logging.h:943:30: note: expanded from macro 'LOG_EVERY_N'
                             INVALID_REQUESTED_LOG_SEVERITY);           \
                             ^
1 warning generated.

Undefined symbols for architecture x86_64:
  "_mxArrayToString", referenced from:
      get_solver(int, mxArray_tag**, int, mxArray_tag const**) in caffe_.o
      solver_restore(int, mxArray_tag**, int, mxArray_tag const**) in caffe_.o
      get_net(int, mxArray_tag**, int, mxArray_tag const**) in caffe_.o
      net_copy_from(int, mxArray_tag**, int, mxArray_tag const**) in caffe_.o
      net_save(int, mxArray_tag**, int, mxArray_tag const**) in caffe_.o
      read_mean(int, mxArray_tag**, int, mxArray_tag const**) in caffe_.o
      write_mean(int, mxArray_tag**, int, mxArray_tag const**) in caffe_.o
      ...
  "_mxCreateCellMatrix_700", referenced from:
      str_vec_to_mx_strcell(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) in caffe_.o
  "_mxCreateDoubleMatrix_700", referenced from:
      net_get_attr(int, mxArray_tag**, int, mxArray_tag const**) in caffe_.o
      blob_get_shape(int, mxArray_tag**, int, mxArray_tag const**) in caffe_.o
  "_mxCreateDoubleScalar", referenced from:
      get_solver(int, mxArray_tag**, int, mxArray_tag const**) in caffe_.o
      solver_get_attr(int, mxArray_tag**, int, mxArray_tag const**) in caffe_.o
      solver_get_iter(int, mxArray_tag**, int, mxArray_tag const**) in caffe_.o
      get_net(int, mxArray_tag**, int, mxArray_tag const**) in caffe_.o
      net_get_attr(int, mxArray_tag**, int, mxArray_tag const**) in caffe_.o
      get_init_key(int, mxArray_tag**, int, mxArray_tag const**) in caffe_.o
      mxArray_tag* ptr_vec_to_handle_vec<caffe::Blob<float> >(std::__1::vector<boost::shared_ptr<caffe::Blob<float> >, std::__1::allocator<boost::shared_ptr<caffe::Blob<float> > > > const&) in caffe_.o
      ...
  "_mxCreateNumericArray_700", referenced from:
      blob_to_mx_mat(caffe::Blob<float> const*, WhichMemory) in caffe_.o
  "_mxCreateNumericMatrix_700", referenced from:
      get_solver(int, mxArray_tag**, int, mxArray_tag const**) in caffe_.o
      solver_get_attr(int, mxArray_tag**, int, mxArray_tag const**) in caffe_.o
      get_net(int, mxArray_tag**, int, mxArray_tag const**) in caffe_.o
      net_get_attr(int, mxArray_tag**, int, mxArray_tag const**) in caffe_.o
      mxArray_tag* ptr_vec_to_handle_vec<caffe::Blob<float> >(std::__1::vector<boost::shared_ptr<caffe::Blob<float> >, std::__1::allocator<boost::shared_ptr<caffe::Blob<float> > > > const&) in caffe_.o
  "_mxCreateString", referenced from:
      layer_get_type(int, mxArray_tag**, int, mxArray_tag const**) in caffe_.o
      version(int, mxArray_tag**, int, mxArray_tag const**) in caffe_.o
      str_vec_to_mx_strcell(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) in caffe_.o
  "_mxCreateStructMatrix_700", referenced from:
      get_solver(int, mxArray_tag**, int, mxArray_tag const**) in caffe_.o
      solver_get_attr(int, mxArray_tag**, int, mxArray_tag const**) in caffe_.o
      get_net(int, mxArray_tag**, int, mxArray_tag const**) in caffe_.o
      net_get_attr(int, mxArray_tag**, int, mxArray_tag const**) in caffe_.o
      layer_get_attr(int, mxArray_tag**, int, mxArray_tag const**) in caffe_.o
      mxArray_tag* ptr_vec_to_handle_vec<caffe::Blob<float> >(std::__1::vector<boost::shared_ptr<caffe::Blob<float> >, std::__1::allocator<boost::shared_ptr<caffe::Blob<float> > > > const&) in caffe_.o
  "_mxFree", referenced from:
      get_solver(int, mxArray_tag**, int, mxArray_tag const**) in caffe_.o
      solver_restore(int, mxArray_tag**, int, mxArray_tag const**) in caffe_.o
      get_net(int, mxArray_tag**, int, mxArray_tag const**) in caffe_.o
      net_copy_from(int, mxArray_tag**, int, mxArray_tag const**) in caffe_.o
      net_save(int, mxArray_tag**, int, mxArray_tag const**) in caffe_.o
      read_mean(int, mxArray_tag**, int, mxArray_tag const**) in caffe_.o
      write_mean(int, mxArray_tag**, int, mxArray_tag const**) in caffe_.o
      ...
  "_mxGetData", referenced from:
      get_solver(int, mxArray_tag**, int, mxArray_tag const**) in caffe_.o
      solver_get_attr(int, mxArray_tag**, int, mxArray_tag const**) in caffe_.o
      get_net(int, mxArray_tag**, int, mxArray_tag const**) in caffe_.o
      net_get_attr(int, mxArray_tag**, int, mxArray_tag const**) in caffe_.o
      caffe::Solver<float>* handle_to_ptr<caffe::Solver<float> >(mxArray_tag const*) in caffe_.o
      caffe::Net<float>* handle_to_ptr<caffe::Net<float> >(mxArray_tag const*) in caffe_.o
      mxArray_tag* ptr_vec_to_handle_vec<caffe::Blob<float> >(std::__1::vector<boost::shared_ptr<caffe::Blob<float> >, std::__1::allocator<boost::shared_ptr<caffe::Blob<float> > > > const&) in caffe_.o
      ...
  "_mxGetDimensions_700", referenced from:
      write_mean(int, mxArray_tag**, int, mxArray_tag const**) in caffe_.o
  "_mxGetField_700", referenced from:
      caffe::Solver<float>* handle_to_ptr<caffe::Solver<float> >(mxArray_tag const*) in caffe_.o
      caffe::Net<float>* handle_to_ptr<caffe::Net<float> >(mxArray_tag const*) in caffe_.o
      caffe::Layer<float>* handle_to_ptr<caffe::Layer<float> >(mxArray_tag const*) in caffe_.o
      caffe::Blob<float>* handle_to_ptr<caffe::Blob<float> >(mxArray_tag const*) in caffe_.o
  "_mxGetNumberOfDimensions_700", referenced from:
      write_mean(int, mxArray_tag**, int, mxArray_tag const**) in caffe_.o
  "_mxGetNumberOfElements", referenced from:
      blob_reshape(int, mxArray_tag**, int, mxArray_tag const**) in caffe_.o
      mx_mat_to_blob(mxArray_tag const*, caffe::Blob<float>*, WhichMemory) in caffe_.o
  "_mxGetPr", referenced from:
      net_get_attr(int, mxArray_tag**, int, mxArray_tag const**) in caffe_.o
      blob_get_shape(int, mxArray_tag**, int, mxArray_tag const**) in caffe_.o
      blob_reshape(int, mxArray_tag**, int, mxArray_tag const**) in caffe_.o
  "_mxGetScalar", referenced from:
      solver_step(int, mxArray_tag**, int, mxArray_tag const**) in caffe_.o
      set_device(int, mxArray_tag**, int, mxArray_tag const**) in caffe_.o
      caffe::Solver<float>* handle_to_ptr<caffe::Solver<float> >(mxArray_tag const*) in caffe_.o
      caffe::Net<float>* handle_to_ptr<caffe::Net<float> >(mxArray_tag const*) in caffe_.o
      caffe::Layer<float>* handle_to_ptr<caffe::Layer<float> >(mxArray_tag const*) in caffe_.o
      caffe::Blob<float>* handle_to_ptr<caffe::Blob<float> >(mxArray_tag const*) in caffe_.o
  "_mxIsChar", referenced from:
      get_solver(int, mxArray_tag**, int, mxArray_tag const**) in caffe_.o
      solver_restore(int, mxArray_tag**, int, mxArray_tag const**) in caffe_.o
      get_net(int, mxArray_tag**, int, mxArray_tag const**) in caffe_.o
      net_copy_from(int, mxArray_tag**, int, mxArray_tag const**) in caffe_.o
      net_save(int, mxArray_tag**, int, mxArray_tag const**) in caffe_.o
      read_mean(int, mxArray_tag**, int, mxArray_tag const**) in caffe_.o
      write_mean(int, mxArray_tag**, int, mxArray_tag const**) in caffe_.o
      ...
  "_mxIsDouble", referenced from:
      solver_step(int, mxArray_tag**, int, mxArray_tag const**) in caffe_.o
      blob_reshape(int, mxArray_tag**, int, mxArray_tag const**) in caffe_.o
      set_device(int, mxArray_tag**, int, mxArray_tag const**) in caffe_.o
  "_mxIsSingle", referenced from:
      blob_set_data(int, mxArray_tag**, int, mxArray_tag const**) in caffe_.o
      blob_set_diff(int, mxArray_tag**, int, mxArray_tag const**) in caffe_.o
      write_mean(int, mxArray_tag**, int, mxArray_tag const**) in caffe_.o
  "_mxIsStruct", referenced from:
      delete_solver(int, mxArray_tag**, int, mxArray_tag const**) in caffe_.o
      solver_get_attr(int, mxArray_tag**, int, mxArray_tag const**) in caffe_.o
      solver_get_iter(int, mxArray_tag**, int, mxArray_tag const**) in caffe_.o
      solver_restore(int, mxArray_tag**, int, mxArray_tag const**) in caffe_.o
      solver_solve(int, mxArray_tag**, int, mxArray_tag const**) in caffe_.o
      solver_step(int, mxArray_tag**, int, mxArray_tag const**) in caffe_.o
      delete_net(int, mxArray_tag**, int, mxArray_tag const**) in caffe_.o
      ...
  "_mxIsUint64", referenced from:
      caffe::Solver<float>* handle_to_ptr<caffe::Solver<float> >(mxArray_tag const*) in caffe_.o
      caffe::Net<float>* handle_to_ptr<caffe::Net<float> >(mxArray_tag const*) in caffe_.o
      caffe::Layer<float>* handle_to_ptr<caffe::Layer<float> >(mxArray_tag const*) in caffe_.o
      caffe::Blob<float>* handle_to_ptr<caffe::Blob<float> >(mxArray_tag const*) in caffe_.o
  "_mxSetCell_700", referenced from:
      str_vec_to_mx_strcell(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) in caffe_.o
  "_mxSetField_700", referenced from:
      get_solver(int, mxArray_tag**, int, mxArray_tag const**) in caffe_.o
      solver_get_attr(int, mxArray_tag**, int, mxArray_tag const**) in caffe_.o
      get_net(int, mxArray_tag**, int, mxArray_tag const**) in caffe_.o
      net_get_attr(int, mxArray_tag**, int, mxArray_tag const**) in caffe_.o
      layer_get_attr(int, mxArray_tag**, int, mxArray_tag const**) in caffe_.o
      mxArray_tag* ptr_vec_to_handle_vec<caffe::Blob<float> >(std::__1::vector<boost::shared_ptr<caffe::Blob<float> >, std::__1::allocator<boost::shared_ptr<caffe::Blob<float> > > > const&) in caffe_.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

make: *** [matlab/+caffe/private/caffe_.mexmaci64] Error 255

### Steps to reproduce

If you are having difficulty building Caffe or training a model, please ask the caffe-users mailing list. If you are reporting a build error that seems to be due to a bug in Caffe, please attach your build configuration (either Makefile.config or CMakeCache.txt) and the output of the make (or cmake) command.

### Your system configuration
Operating system: Mac
Compiler: Xcode 8.3.3
CUDA version (if applicable):
CUDNN version (if applicable):
BLAS: openblas
Python or MATLAB version (for pycaffe and matcaffe respectively):
matlab2016a

**Comment by tuning** [comment]
exactly the same issue here - CPU only build, macOS sierra 10.12.6 with xcode 8.3.3 , system Python, passed runtest and pytest

however stuck with matcaffe and the same error as above

**Comment by tuning** [comment]
check this out: https://github.com/BVLC/caffe/issues/915

**Comment by Noiredd** [comment]
If after trying the suggested solution you're still encountering problems, do post to the [caffe-users list][1].

Please do not post usage, installation, or modeling questions, or other requests for help to Issues. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe. Please read the [guidelines for contributing][2] before submitting an issue or a pull request.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
