### ISSUE TITLE
'../lib/libcaffe.so.1.0.0: undefined reference to `forkpty'' caffe build error, can anyone help me?

### ISSUE THREAD

**Issue by Qunxiang** [BVLC/caffe#5912]
Linking CXX executable device_query
Linking CXX executable cifar10/convert_cifar_data
[100%] Built target device_query
../lib/libcaffe.so.1.0.0: undefined reference to `forkpty'
../lib/libcaffe.so.1.0.0: undefined reference to `openpty'
collect2: error: ld returned 1 exit status
make[2]: *** [examples/cifar10/convert_cifar_data] Error 1
make[1]: *** [examples/CMakeFiles/convert_cifar_data.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
Linking CXX executable mnist/convert_mnist_data
../lib/libcaffe.so.1.0.0: undefined reference to `forkpty'
../lib/libcaffe.so.1.0.0: undefined reference to `openpty'
collect2: error: ld returned 1 exit status
make[2]: *** [examples/mnist/convert_mnist_data] Error 1
make[1]: *** [examples/CMakeFiles/convert_mnist_data.dir/all] Error 2
Linking CXX executable siamese/convert_mnist_siamese_data
Linking CXX executable compute_image_mean
../lib/libcaffe.so.1.0.0: undefined reference to `forkpty'
../lib/libcaffe.so.1.0.0: undefined reference to `openpty'
collect2: error: ld returned 1 exit status
make[2]: *** [examples/siamese/convert_mnist_siamese_data] Error 1
make[1]: *** [examples/CMakeFiles/convert_mnist_siamese_data.dir/all] Error 2
../lib/libcaffe.so.1.0.0: undefined reference to `forkpty'
../lib/libcaffe.so.1.0.0: undefined reference to `openpty'
collect2: error: ld returned 1 exit status
make[2]: *** [tools/compute_image_mean] Error 1
make[1]: *** [tools/CMakeFiles/compute_image_mean.dir/all] Error 2
Linking CXX executable convert_imageset
Linking CXX executable upgrade_net_proto_binary
../lib/libcaffe.so.1.0.0: undefined reference to `forkpty'
../lib/libcaffe.so.1.0.0: undefined reference to `openpty'
collect2: error: ld returned 1 exit status
make[2]: *** [tools/convert_imageset] Error 1
make[1]: *** [tools/CMakeFiles/convert_imageset.dir/all] Error 2
Linking CXX executable finetune_net
Linking CXX executable upgrade_solver_proto_text
../lib/libcaffe.so.1.0.0: undefined reference to `forkpty'
../lib/libcaffe.so.1.0.0: undefined reference to `openpty'
collect2: error: ld returned 1 exit status
make[2]: *** [tools/upgrade_net_proto_binary] Error 1
make[1]: *** [tools/CMakeFiles/upgrade_net_proto_binary.dir/all] Error 2
[100%] Built target finetune_net
Linking CXX executable net_speed_benchmark
Linking CXX executable test_net
[100%] Built target net_speed_benchmark
../lib/libcaffe.so.1.0.0: undefined reference to `forkpty'
../lib/libcaffe.so.1.0.0: undefined reference to `openpty'
collect2: error: ld returned 1 exit status
make[2]: *** [tools/upgrade_solver_proto_text] Error 1
make[1]: *** [tools/CMakeFiles/upgrade_solver_proto_text.dir/all] Error 2
[100%] Built target test_net
Linking CXX executable train_net
Linking CXX executable upgrade_net_proto_text
[100%] Built target train_net
Linking CXX executable extract_features
../lib/libcaffe.so.1.0.0: undefined reference to `forkpty'
../lib/libcaffe.so.1.0.0: undefined reference to `openpty'
collect2: error: ld returned 1 exit status
make[2]: *** [tools/upgrade_net_proto_text] Error 1
make[1]: *** [tools/CMakeFiles/upgrade_net_proto_text.dir/all] Error 2
../lib/libcaffe.so.1.0.0: undefined reference to `forkpty'
../lib/libcaffe.so.1.0.0: undefined reference to `openpty'
collect2: error: ld returned 1 exit status
make[2]: *** [tools/extract_features] Error 1
make[1]: *** [tools/CMakeFiles/extract_features.dir/all] Error 2
Linking CXX executable cpp_classification/classification
../lib/libcaffe.so.1.0.0: undefined reference to `forkpty'
../lib/libcaffe.so.1.0.0: undefined reference to `openpty'
collect2: error: ld returned 1 exit status
make[2]: *** [examples/cpp_classification/classification] Error 1
make[1]: *** [examples/CMakeFiles/classification.dir/all] Error 2
Linking CXX executable caffe
../lib/libcaffe.so.1.0.0: undefined reference to `forkpty'
../lib/libcaffe.so.1.0.0: undefined reference to `openpty'
collect2: error: ld returned 1 exit status
make[2]: *** [tools/caffe] Error 1
make[1]: *** [tools/CMakeFiles/caffe.bin.dir/all] Error 2
Linking CXX shared library ../lib/_caffe.so
Creating symlink /home/wangqunxiang/deepLearning/caffe/python/caffe/_caffe.so -> /home/wangqunxiang/deepLearning/caffe/build/lib/_caffe.so
[100%] Built target pycaffe
make: *** [all] Error 2

**Comment by Noiredd** [comment]
Please do not post usage, installation, or modeling questions, or other requests for help to Issues. Use the [caffe-users list][1] instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe. Please read the [guidelines for contributing][2] before submitting an issue or a pull request.

If this still poses an issue for you, please post on caffe-users list. Include your system specs (versions of: OS, Python/MATLAB, compiler, BLAS, CUDA & cuDNN if you're using them) and attach the Makefile.config along with the full output log.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md

**Comment by PhillipHuang2017** [comment]
I meet this error too, have you solved it?
