### ISSUE TITLE
How can I write the training log to my specified floder with Pycaffe？

### ISSUE THREAD

**Issue by bigyaofei** [BVLC/caffe#5920]
How can I write the training log to my specified floder with Pycaffe？ like ‘/home/xxx/caffe-master/mylog/’. I know how to do it in command line.

**Comment by shaibagon** [comment]
Please use the [caffe-users list][1] for usage, installation, or modeling questions, or other requests for help.
You may also post questions on [stackoverflow][3], make sure you tag them with `caffe` tag.  
Do not post such requests to Issues. Doing so interferes with the development of Caffe.

Please read the [guidelines for contributing][2] before submitting this issue.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
 [3]: http://stackoverflow.com/questions/tagged/caffe
