### ISSUE TITLE
How to create a training/testing dataset using bounding boxes around the objects instead of the full image?

### ISSUE THREAD

**Issue by didulle** [BVLC/caffe#5921]
Hi

I would like to train a caffe model to detect cars and pedestrians in gray level images. I have a huge annotated dataset with the category of each object and the coordinates of the rectangle that bounds it.

I am used to convert the training and testing set to lmdb file using "convert_imageset" command using a txt file that contains the path of each image and the label of the full image. I would like to have an example of a line of this txt file that should contain the coordinates of the object and its label. Does the command line that I should use to convert my dataset to lmdb has to be changed to handle bounding boxes?

Thanks!!!

**Comment by shaibagon** [comment]
I am afraid [`convert_imageset`](https://stackoverflow.com/q/31427094/1714410) is designed to process whole images and not to crop specific bounding boxes within each image. 
You may find [examples of writing LMDB for caffe using python](https://stackoverflow.com/q/31649216/1714410). It should not be too difficult to modify python code to accommodate for cropping bounding boxes from images.

Please use the [caffe-users list][1] for usage, installation, or modeling questions, or other requests for help.
You may also post questions on [stackoverflow][3], make sure you tag them with `caffe` tag.  
Do not post such requests to Issues. Doing so interferes with the development of Caffe.

Please read the [guidelines for contributing][2] before submitting this issue.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
 [3]: http://stackoverflow.com/questions/tagged/caffe
