### ISSUE TITLE
How  to adjust the shortest side of the image to 256?

### ISSUE THREAD

**Issue by 408550969** [BVLC/caffe#5922]
When the resnet34 training in the imagenet, the shortest will be adjusted to 256, how to adjust under Linux?
I can transfer the image to a fixed size, for example --resize = 224。
or who can provide resnet34 solver.prototxt or caffemodel

**Comment by 408550969** [comment]
another question: Does the caffe default crop is center crop?

**Comment by shaibagon** [comment]
Please use the [caffe-users list][1] for usage, installation, or modeling questions, or other requests for help.
You may also post questions on [stackoverflow][3], make sure you tag them with `caffe` tag.  
Do not post such requests to Issues. Doing so interferes with the development of Caffe.

Please read the [guidelines for contributing][2] before submitting this issue.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
 [3]: http://stackoverflow.com/questions/tagged/caffe
