### ISSUE TITLE
fcn during training loss function doesn' t decrease after reducig image's size

### ISSUE THREAD

**Issue by GioEspo** [BVLC/caffe#5928]
Hi all, I' m training nyud-fcn32s-color-d with nyud-v2 dataset. I had to reduce the depht, images and labes data to 200x15 in order to prevent cudo out of memory (my gpu has only 2 Gb). In the original trainval.prototxt file I've only modified the pad parameter of the first convolutional layer (for the same memory limitation problem) conv1_1_bgrd pad:100 --> pad_h:64, pad_w=66, and the kerner size of fc6 layer. 7-->5.
The training has done several iterations (20k), but the loss value doesn't decrease, it oscillates around 100.000 (95000-101000-99000...and so on) If anyone has an idea about how to fix this problem I'll be very gratefull.

**Comment by shaibagon** [comment]
Please use the [caffe-users list][1] for usage, installation, or modeling questions, or other requests for help.
You may also post questions on [stackoverflow][3], make sure you tag them with `caffe` tag.  
Do not post such requests to Issues. Doing so interferes with the development of Caffe.

Please read the [guidelines for contributing][2] before submitting this issue.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
 [3]: http://stackoverflow.com/questions/tagged/caffe
