### ISSUE TITLE
Issue with caffe, getting "ld: library not found for -lcudnn"

### ISSUE THREAD

**Issue by RandhirMSingh** [BVLC/caffe#5931]
After running `$ make all -j8` command
i'm getting this error
```
LD -o .build_release/lib/libcaffe.so.1.0.0
clang: warning: argument unused during compilation: '-pthread'
ld: library not found for -lcudnn
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [.build_release/lib/libcaffe.so.1.0.0] Error 1
```

### Your system configuration
Operating system: MAC OS Sierra
Compiler:
CUDA version (if applicable): 8
CUDNN version (if applicable):8.0
BLAS:
Python or MATLAB version (for pycaffe and matcaffe respectively): MATLAB 2017
@pluskid @sergeyk @Franck-Dernoncourt @darxriggs @gut

**Comment by Noiredd** [comment]
Please do not post usage, installation, or modeling questions, or other requests for help to Issues. Use the [caffe-users list][1] instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe. Please read the [guidelines for contributing][2] before submitting an issue or a pull request.

In your case, linker was unable to locate cuDNN library. Look up how to set the library path, then post to caffe-users if you need further help.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
