### ISSUE TITLE
MacOS10.12 build caffe failed

### ISSUE THREAD

**Issue by henrybit** [BVLC/caffe#5933]
$ make all
No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.
/bin/sh: line 0: [: -gt: unary operator expected
/bin/sh: line 0: [: -gt: unary operator expected
CXX .build_release/src/caffe/proto/caffe.pb.cc
In file included from .build_release/src/caffe/proto/caffe.pb.cc:5:
.build_release/src/caffe/proto/caffe.pb.h:17:2: error: This file was generated by an older version of protoc which is
#error This file was generated by an older version of protoc which is
.build_release/src/caffe/proto/caffe.pb.h:18:2: error: incompatible with your Protocol Buffer headers.  Please
#error incompatible with your Protocol Buffer headers.  

------------------------------------------------------------
how to fix it?

**Comment by Noiredd** [comment]
Do you have multiple versions of Google Protocol Buffer installed? Consult #5645 and #5078. If still unable to fix the issue, describe your attempts and updated state of the problem on [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users).
