### ISSUE TITLE
C++ template  separate compilation 

### ISSUE THREAD

**Issue by QiYueFeiXue** [BVLC/caffe#5937]
Hello, In my mind, C++ template can not separate compilation, but today I find caffe use separate compilation, such as blob.cpp 、 blob.hpp. I find no solution in internet, and I want to know how to complete it!
Thank you!

**Comment by trivialfis** [comment]
Explicit instantiation. For example, the last few lines of blob.cpp file:

INSTANTIATE_CLASS(Blob);
template class Blob<int_tp>;
template class Blob<uint_tp>;

**Comment by QiYueFeiXue** [comment]
Thank you help me!

At2017-09-27 13:04:19，trivialfisnotifications@github.comwrote:

Explicit instantiation. For example, the last few lines of blob.cpp file:

INSTANTIATE_CLASS(Blob);
template class Blob<int_tp>;
template class Blob<uint_tp>;

**Comment by QiYueFeiXue** [comment]
Thank you!
