### ISSUE TITLE
Unknown database backend

### ISSUE THREAD

**Issue by whuhxb** [BVLC/caffe#5943]
Please use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) for usage, installation, or modeling questions, or other requests for help.
_Do not post such requests to Issues._ Doing so interferes with the development of Caffe.

Please read the [guidelines for contributing](https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md) before submitting this issue.

### Steps to reproduce

If you are having difficulty building Caffe or training a model, please ask the caffe-users mailing list. If you are reporting a build error that seems to be due to a bug in Caffe, please attach your build configuration (either Makefile.config or CMakeCache.txt) and the output of the make (or cmake) command.

### Your system configuration
Operating system:
Compiler:
CUDA version (if applicable):
CUDNN version (if applicable):
BLAS:
Python or MATLAB version (for pycaffe and matcaffe respectively):

When I run my own dataset with caffe, I don't know why this problem happens. Could any body help me?

I0924 12:14:56.311817  5057 layer_factory.hpp:77] Creating layer data
F0924 12:14:56.311969  5057 db.cpp:20] Unknown database backend
*** Check failure stack trace: ***
    @     0x7f9a72d9ed6d  google::LogMessage::Fail()
    @     0x7f9a72da0c0d  google::LogMessage::SendToLog()
    @     0x7f9a72d9e988  google::LogMessage::Flush()
    @     0x7f9a72da146e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f9a735f63a4  caffe::db::GetDB()
    @     0x7f9a736844dd  caffe::DataLayer<>::DataLayer()
    @     0x7f9a73686715  caffe::Creator_DataLayer<>()
    @     0x7f9a735b5ac5  caffe::LayerRegistry<>::CreateLayer()
    @     0x7f9a735a0ef5  caffe::Net<>::Init()
    @     0x7f9a7359f8a6  caffe::Net<>::Net()
    @     0x7f9a735710fb  caffe::Solver<>::InitTrainNet()
    @     0x7f9a73570960  caffe::Solver<>::Init()
    @     0x7f9a735704b9  caffe::Solver<>::Solver()
    @     0x7f9a7355f4d8  caffe::SGDSolver<>::SGDSolver()
    @     0x7f9a7356526e  caffe::Creator_SGDSolver<>()
    @           0x41b6e0  caffe::SolverRegistry<>::CreateSolver()
    @           0x416940  train()
    @           0x418f21  main
    @     0x7f9a718ecf45  (unknown)
    @           0x415539  (unknown)

**Comment by whuhxb** [comment]
When I running caffe on my own, I don't know why this problem happens.
I0924 12:14:56.311817  5057 layer_factory.hpp:77] Creating layer data
F0924 12:14:56.311969  5057 db.cpp:20] Unknown database backend
*** Check failure stack trace: ***
    @     0x7f9a72d9ed6d  google::LogMessage::Fail()
    @     0x7f9a72da0c0d  google::LogMessage::SendToLog()
    @     0x7f9a72d9e988  google::LogMessage::Flush()
    @     0x7f9a72da146e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f9a735f63a4  caffe::db::GetDB()
    @     0x7f9a736844dd  caffe::DataLayer<>::DataLayer()
    @     0x7f9a73686715  caffe::Creator_DataLayer<>()
    @     0x7f9a735b5ac5  caffe::LayerRegistry<>::CreateLayer()
    @     0x7f9a735a0ef5  caffe::Net<>::Init()
    @     0x7f9a7359f8a6  caffe::Net<>::Net()
    @     0x7f9a735710fb  caffe::Solver<>::InitTrainNet()
    @     0x7f9a73570960  caffe::Solver<>::Init()
    @     0x7f9a735704b9  caffe::Solver<>::Solver()
    @     0x7f9a7355f4d8  caffe::SGDSolver<>::SGDSolver()
    @     0x7f9a7356526e  caffe::Creator_SGDSolver<>()
    @           0x41b6e0  caffe::SolverRegistry<>::CreateSolver()
    @           0x416940  train()
    @           0x418f21  main
    @     0x7f9a718ecf45  (unknown)
    @           0x415539  (unknown)

**Comment by shaibagon** [comment]
Please use the [caffe-users list][1] for usage, installation, or modeling questions, or other requests for help.
You may also post questions on [stackoverflow][3], make sure you tag them with `caffe` tag.  
Do not post such requests to Issues. Doing so interferes with the development of Caffe.

Please read the [guidelines for contributing][2] before submitting this issue.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
 [3]: http://stackoverflow.com/questions/tagged/caffe
