### ISSUE TITLE
accuracy = -nan(ind)

### ISSUE THREAD

**Issue by drdrpyan** [BVLC/caffe#5949]
### Issue summary
A result of a accuracy layer is -nan(ind) when all of a label blob (bottom[1]) elements (target labels) are 
 equal to a 'ignore label'.

When all of a label blob elements are equal to the 'ignore label', the 'count' variable in Forward_cpu() is not increased. Then 'divide by zero' is occurred.
(line 61, line 94, src/layers/accuracy_layer.cpp)

I think the accuracy layer should show some information messages instead of outputting "-nan(ind)", and I can implement it with a few lines of code.
Should I make the accuracy layer to print 1 or 0? or make it to print warning message? What message is appropriate?

### Steps to reproduce
1. Attach a accuracy layer to certain net. Then define a 'ignore label' for the accuracy layer.
2. Feed a label blob that filled with the 'ignore label' into the accuracy layer.

### Your system configuration
Operating system: Win10 64
Compiler: VS14
CUDA version (if applicable):
CUDNN version (if applicable):
BLAS:
Python or MATLAB version (for pycaffe and matcaffe respectively):

**Comment by Noiredd** [comment]
By the looks of it, the bug will persist even after #5836. Strangely, the GPU version [does check](https://github.com/BVLC/caffe/blob/62e0c8559045cb2b5a12e0d6c41acd25d4122630/src/caffe/layers/accuracy_layer.cu#L93) against total count being positive, outputting a zero if `count==0`, but the CPU simply [divides by it](https://github.com/BVLC/caffe/blob/62e0c8559045cb2b5a12e0d6c41acd25d4122630/src/caffe/layers/accuracy_layer.cpp#L89). I'll fix it shortly.
