### ISSUE TITLE
compile error on caffe windows without GPU

### ISSUE THREAD

**Issue by Jane310** [BVLC/caffe#5961]
[Output-Build.txt](https://github.com/BVLC/caffe/files/1352442/Output-Build.txt)
I got the error: C2220: 將警告視為錯誤處理 - 沒有產生 'object' 檔案 (..\..\src\caffe\data_transformer.cpp) when building the libcaffe project.
The attached file is the log file.
I download caffe on this website: https://github.com/Microsoft/caffe

environment:Windows7 (64bits), visual 2013, Miniconda(python2.7) , no CUDA

I try to save the rng.hpp file as unicode format, but it still can't work.
How can I fix it? 

Thanks!

**Comment by Noiredd** [comment]
If you are using Microsoft's fork of Cafee, consider opening an issue there and closing this one.

**Comment by AurusHuang** [comment]
@Jane310 It's a rather old release. Guillaume Dumont (@willyd) has a more recent branch that works for me.
