### ISSUE TITLE
Wiki "Development hints" is a markdown Hello World

### ISSUE THREAD

**Issue by matthieu-labas** [BVLC/caffe#5963]
### Issue summary

Wiki "[Development hint](https://github.com/BVLC/caffe/wiki/Development-Hints)" was good until revision [`e7b01f2`](https://github.com/BVLC/caffe/wiki/Development-Hints/e7b01f2b99120891dc799f0810453aeccb7a1481) by @shelhamer but is garbage since then.

### Steps to reproduce

Go to https://github.com/BVLC/caffe/wiki/Development-Hints and see the Hello World markdown by @DaFengXiong.

### Your system configuration

N/A

**Comment by shelhamer** [comment]
Thanks for reporting this—it has been restored and further edited at https://github.com/BVLC/caffe/wiki/Development
