### ISSUE TITLE
Building 32 bit GPU applications in windows

### ISSUE THREAD

**Issue by patrickrbrandao** [BVLC/caffe#5966]
I need to caffe code to run in 32 bit applications. I was able to compile all the dependencies but when I try to build windows-caffe cudnn isn't recognized. After a little bit of research it appears that cudnn isnt supported for 32bit systems. 
Is there any way I can work around this, and still compile GPU caffe applications for 32 bit applications?

Best regards,

Patrick

**Comment by willyd** [comment]
I never tried to compile caffe using 32-bits so you're on your own here. You can work around the cudnn issue by switching it off (`-DUSE_CUDNN=OFF` https://github.com/BVLC/caffe/blob/windows/CMakeLists.txt#L41) . I believe CUDA has dropped support for 32 bit after CUDA 6.5 so you should try to use this version or earlier.
