### ISSUE TITLE
How to initialize a blob with a certain value  by using input_layer.cpp ?

### ISSUE THREAD

**Issue by yangzhikai** [BVLC/caffe#5967]
Excuse me. 
   There is a question，if I want to initialize a blob with a certain value by using input_layer.cpp . As I know , 
we  can  initialize a blob with a certain value  like this(src/scale.cpp):  
  this->blobs_.resize(1);
    const vector<int>::const_iterator& shape_start =
        bottom[0]->shape().begin() + axis_;
    const vector<int>::const_iterator& shape_end =
        (num_axes == -1) ? bottom[0]->shape().end() : (shape_start + num_axes);
    vector<int> scale_shape(shape_start, shape_end);
    this->blobs_[0].reset(new Blob<Dtype>(scale_shape));
    FillerParameter filler_param(param.filler());
    if (!param.has_filler()) {
      // Default to unit (1) filler for identity operation.
      filler_param.set_type("constant");
      filler_param.set_value(1);
    }
    shared_ptr<Filler<Dtype> > filler(GetFiller<Dtype>(filler_param));
    filler->Fill(this->blobs_[0].get());
  }
BUT，  blobs  ,such as blobs_[0]  dosen't exist in the  input_layer.cpp. And I have written some command as follows ,dose it right?

#include <vector>
#include "caffe/layers/input_layer.hpp"
namespace caffe {

template <typename Dtype>
void InputLayer<Dtype>::LayerSetUp(const vector<Blob<Dtype>*>& bottom,
      const vector<Blob<Dtype>*>& top) {
  const int num_top = top.size();                      //top num
  const InputParameter& param = this->layer_param_.input_param();
  const int num_shape = param.shape_size();              
  CHECK(num_shape == 0 || num_shape == 1 || num_shape == num_top)
      << "Must specify 'shape' once, once per top blob, or not at all: "
      << num_top << " tops vs. " << num_shape << " shapes.";
  if (num_shape > 0) {
    for (int i = 0; i < num_top; ++i) {
      const int shape_index = (param.shape_size() == 1) ? 0 : i;  //shape_index = i
      // top[i]->Reshape(param.shape(shape_index));                // form here  modified by myself ;
      this->blobs_.resize(1);                                                       // form here  modified by myself ;
      this->blobs_[0].reset(new Blob<Dtype>(param.shape(shape_index)));
      FillerParameter filler_param(param.filler());
     if (!param.has_filler()) {
     // Default to unit (1) filler for identity operation.
     filler_param.set_type("constant");
     filler_param.set_value(1);
     }
     shared_ptr<Filler<Dtype> > filler(GetFiller<Dtype>(filler_param));
     filler->Fill(this->blobs_[i].get());
     top[i]->blobs_[i]
    }                                                            
  }                                                              

}                                                                

INSTANTIATE_CLASS(InputLayer);
REGISTER_LAYER_CLASS(Input);

}  // namespace caffe

**Comment by shaibagon** [comment]
Please use the [caffe-users list][1] for usage, installation, or modeling questions, or other requests for help.
You may also post questions on [stackoverflow][3], make sure you tag them with `caffe` tag.  
Do not post such requests to Issues. Doing so interferes with the development of Caffe.

Please read the [guidelines for contributing][2] before submitting this issue.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
 [3]: http://stackoverflow.com/questions/tagged/caffe
