### ISSUE TITLE
Caffe_OpenCL+ViennaCL+ROCm_OpenCL does not work

### ISSUE THREAD

**Issue by jackyh** [BVLC/caffe#5980]
### Issue summary
Caffe_OpenCL+ViennaCL+ROCm_OpenCL does not work

### Steps to reproduce
I compiled all the packages over and try to train LeNet:
./examples/mnist/train_lenet.sh
it failed with:
I1014 21:55:32.809759 28063 solver.cpp:295] Solving LeNet
I1014 21:55:32.809763 28063 solver.cpp:296] Learning Rate Policy: inv
I1014 21:55:32.810170 28063 solver.cpp:354] Iteration 0, Testing net (#0)
I1014 21:55:32.810181 28063 net.cpp:731] Copying source layer mnist
I1014 21:55:32.810194 28063 net.cpp:731] Copying source layer conv1
I1014 21:55:32.810211 28063 net.cpp:731] Copying source layer pool1
I1014 21:55:32.810214 28063 net.cpp:731] Copying source layer conv2
I1014 21:55:32.810220 28063 net.cpp:731] Copying source layer pool2
I1014 21:55:32.810223 28063 net.cpp:731] Copying source layer ip1
I1014 21:55:32.810228 28063 net.cpp:731] Copying source layer relu1
I1014 21:55:32.810231 28063 net.cpp:731] Copying source layer ip2
I1014 21:55:32.810237 28063 net.cpp:731] Copying source layer loss
I1014 21:55:32.810328 28063 net.cpp:634]     [Forward] Layer mnist, top blob data data: 0.119415
I1014 21:55:32.810335 28063 net.cpp:634]     [Forward] Layer mnist, top blob label data: 4.34
I1014 21:55:32.810343 28063 net.cpp:634]     [Forward] Layer label_mnist_1_split, top blob label_mnist_1_split_0 data: 4.34
I1014 21:55:32.810348 28063 net.cpp:634]     [Forward] Layer label_mnist_1_split, top blob label_mnist_1_split_1 data: 4.34
Memory access fault by GPU node-1 on address 0x5020bc000. Reason: Page not present or supervisor privilege.
Aborted (core dumped)

any hints of how to debug it or advice? @naibaf7 

### Your system configuration
Operating system: Ubuntu16.04
GPU card: AMD Wx7100 (R9 Series)

**Comment by naibaf7** [comment]
Nope no fix at the moment, the next version of OpenCL Caffe will add full ROCm compatibility, working on it.

**Comment by jackyh** [comment]
Do you mean MIOPEN as the middleware of computing? What's the status of this? Can I try it?

**Comment by naibaf7** [comment]
You could try https://github.com/ROCmSoftwarePlatform/hipCaffe for the moment until OpenCL Caffe has full ROCm integration.

**Comment by naibaf7** [comment]
ROCm 1.8 compatibility is working.
