### ISSUE TITLE
would the instance of caffe  running on gpu 1 with pythonlayer always take some memory of gpu 0?

### ISSUE THREAD

**Issue by 646677064** [BVLC/caffe#5983]
###with python layer ,the instance running on gpu 1, take some memory of gpu 0,about 100M
why?

### Your system configuration
Operating system: ubuntu 14.04
Compiler: gcc 4.8.4
CUDA version (if applicable): 7.5
CUDNN version (if applicable): 5.1
BLAS:openblas
Python or MATLAB version (for pycaffe and matcaffe respectively): python 2.7

**Comment by 646677064** [comment]
the same pid ocuppy both gpu0 with memory of 100M and gpu1 with memory of 4000M，but I only run on gpu 1

**Comment by 646677064** [comment]
[question here](https://github.com/BVLC/caffe/issues/2186)

**Comment by Noiredd** [comment]
Re-closing this as an answer has been given already. Further conversation should be moved to the [caffe-users list][1].
 [1]: https://groups.google.com/forum/#!forum/caffe-users

**Comment by 646677064** [comment]
similar question，but not exactly the same .would you please show a PR link?thanks very much. @Noiredd

**Comment by 646677064** [comment]
`void Caffe::SetDevice(const int device_id) {
  int current_device;
  CUDA_CHECK(cudaGetDevice(&current_device));
  if (current_device == device_id) {
    return;
  }
  // The call to cudaSetDevice must come before any calls to Get, which
  // may perform initialization using the GPU.
  CUDA_CHECK(cudaSetDevice(device_id));
  if (Get().cublas_handle_) CUBLAS_CHECK(cublasDestroy(Get().cublas_handle_));
  if (Get().curand_generator_) {
    CURAND_CHECK(curandDestroyGenerator(Get().curand_generator_));
  }
  CUBLAS_CHECK(cublasCreate(&Get().cublas_handle_));
  CURAND_CHECK(curandCreateGenerator(&Get().curand_generator_,
      CURAND_RNG_PSEUDO_DEFAULT));
  CURAND_CHECK(curandSetPseudoRandomGeneratorSeed(Get().curand_generator_,
      cluster_seedgen()));
}`
`	    Caffe::SetDevice(GPUID);
      Caffe::set_mode(Caffe::GPU);`  
it can not work.The memory of gpu 0 have been taked

**Comment by 646677064** [comment]
1. ```
void Caffe::SetDevice(const int device_id)
 {
 int current_device; 
CUDA_CHECK(cudaGetDevice(&current_device)); if (current_device == device_id) { return; } // The call to cudaSetDevice must come before any calls to Get, which // may perform initialization using the GPU. CUDA_CHECK(cudaSetDevice(device_id)); if (Get().cublas_handle_) CUBLAS_CHECK(cublasDestroy(Get().cublas_handle_)); if (Get().curand_generator_) { CURAND_CHECK(curandDestroyGenerator(Get().curand_generator_)); } CUBLAS_CHECK(cublasCreate(&Get().cublas_handle_)); CURAND_CHECK(curandCreateGenerator(&Get().curand_generator_, CURAND_RNG_PSEUDO_DEFAULT)); CURAND_CHECK(curandSetPseudoRandomGeneratorSeed(Get().curand_generator_, cluster_seedgen())); 
}
```
2. ```
Caffe::SetDevice(GPUID); 
Caffe::set_mode(Caffe::GPU);
```


it can not work.The memory of gpu 0 have been taked
