### ISSUE TITLE
error in compiling pycaffe for caffe-fast-rcnn ## ubutun16.04 cuda8.0

### ISSUE THREAD

**Issue by MeowMeowLady** [BVLC/caffe#5985]
### I try compiling py-caffe for caffe-fast-rcnn. But below errors show:

CXX/LD -o python/caffe/_caffe.so python/caffe/_caffe.cpp
python/caffe/_caffe.cpp: In function ‘void caffe::init_module__caffe()’:
python/caffe/_caffe.cpp:398:1: error: expected primary-expression before ‘<<’ token
 <<<<<<< HEAD
 ^
python/caffe/_caffe.cpp:398:3: error: expected primary-expression before ‘<<’ token
 <<<<<<< HEAD
   ^
python/caffe/_caffe.cpp:398:5: error: expected primary-expression before ‘<<’ token
 <<<<<<< HEAD
     ^
python/caffe/_caffe.cpp:398:7: error: expected primary-expression before ‘<’ token
 <<<<<<< HEAD
       ^
python/caffe/_caffe.cpp:398:9: error: ‘HEAD’ was not declared in this scope
 <<<<<<< HEAD
         ^
python/caffe/_caffe.cpp:400:1: error: expected primary-expression before ‘==’ token
 =======
 ^
python/caffe/_caffe.cpp:400:3: error: expected primary-expression before ‘==’ token
 =======
   ^
python/caffe/_caffe.cpp:400:5: error: expected primary-expression before ‘==’ token
 =======
     ^
python/caffe/_caffe.cpp:400:7: error: expected primary-expression before ‘=’ token
 =======
       ^
python/caffe/_caffe.cpp:406:1: error: expected primary-expression before ‘>>’ token
 >>>>>>> caffe/master
 ^
python/caffe/_caffe.cpp:406:3: error: expected primary-expression before ‘>>’ token
 >>>>>>> caffe/master
   ^
python/caffe/_caffe.cpp:406:5: error: expected primary-expression before ‘>>’ token
 >>>>>>> caffe/master
     ^
python/caffe/_caffe.cpp:406:7: error: expected primary-expression before ‘>’ token
 >>>>>>> caffe/master
       ^
python/caffe/_caffe.cpp:406:14: error: expected primary-expression before ‘/’ token
 >>>>>>> caffe/master
              ^
python/caffe/_caffe.cpp:406:15: error: ‘master’ was not declared in this scope
 >>>>>>> caffe/master
               ^
Makefile:507: recipe for target 'python/caffe/_caffe.so' failed
make: *** [python/caffe/_caffe.so] Error 1

**Comment by Noiredd** [comment]
This does not seem to be related to main branch of Caffe. Consider posting the issue to relevant fork.

Please do not post usage, installation, or modeling questions, or other requests for help to Issues. Use the [caffe-users list][1] instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

Please read the [guidelines for contributing][2] before submitting an issue or a pull request.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md

**Comment by shengsr** [comment]
> ### _**environment: ubutun16.04 cuda8.0 cudnn5.1**_
> ### I have installed caffe with python interface.
> ### I try compiling py-caffe for caffe-fast-rcnn. But below errors show:
> # CXX/LD -o python/caffe/_caffe.so python/caffe/_caffe.cpp
> python/caffe/_caffe.cpp: In function ‘void caffe::init_module__caffe()’:
> python/caffe/_caffe.cpp:398:1: error: expected primary-expression before ‘<<’ token
> <<<<<<< HEAD
> ^
> python/caffe/_caffe.cpp:398:3: error: expected primary-expression before ‘<<’ token
> <<<<<<< HEAD
> ^
> python/caffe/_caffe.cpp:398:5: error: expected primary-expression before ‘<<’ token
> <<<<<<< HEAD
> ^
> python/caffe/_caffe.cpp:398:7: error: expected primary-expression before ‘<’ token
> <<<<<<< HEAD
> ^
> python/caffe/_caffe.cpp:398:9: error: ‘HEAD’ was not declared in this scope
> <<<<<<< HEAD
> ^
> python/caffe/_caffe.cpp:400:1: error: expected primary-expression before ‘==’ token
> # ^
> python/caffe/_caffe.cpp:400:3: error: expected primary-expression before ‘==’ token
> # ^
> python/caffe/_caffe.cpp:400:5: error: expected primary-expression before ‘==’ token
> ```
>  ^
> ```
> # python/caffe/_caffe.cpp:400:7: error: expected primary-expression before ‘=’ token
> ```
>    ^
> ```
> python/caffe/_caffe.cpp:406:1: error: expected primary-expression before ‘>>’ token
> 
> > > > > > > > caffe/master
> > > > > > > > ^
> > > > > > > > python/caffe/_caffe.cpp:406:3: error: expected primary-expression before ‘>>’ token
> > > > > > > > caffe/master
> > > > > > > > ^
> > > > > > > > python/caffe/_caffe.cpp:406:5: error: expected primary-expression before ‘>>’ token
> > > > > > > > caffe/master
> > > > > > > > ^
> > > > > > > > python/caffe/_caffe.cpp:406:7: error: expected primary-expression before ‘>’ token
> > > > > > > > caffe/master
> > > > > > > > ^
> > > > > > > > python/caffe/_caffe.cpp:406:14: error: expected primary-expression before ‘/’ token
> > > > > > > > caffe/master
> > > > > > > > ^
> > > > > > > > python/caffe/_caffe.cpp:406:15: error: ‘master’ was not declared in this scope
> > > > > > > > caffe/master
> > > > > > > > ^
> > > > > > > > Makefile:507: recipe for target 'python/caffe/_caffe.so' failed
> > > > > > > > make: *** [python/caffe/_caffe.so] Error 1
> 
> ### I have no idea how to deal with it. Anyone could please help me to solve it ? Thanks a lot!

Have you fixed this problem? I have exactly the same error and got stuck, please help me!

**Comment by IreneMa97** [comment]
> > ### _**environment: ubutun16.04 cuda8.0 cudnn5.1**_
> > ### I have installed caffe with python interface.
> > ### I try compiling py-caffe for caffe-fast-rcnn. But below errors show:
> > # CXX/LD -o python/caffe/_caffe.so python/caffe/_caffe.cpp
> > python/caffe/_caffe.cpp: In function ‘void caffe::init_module__caffe()’:
> > python/caffe/_caffe.cpp:398:1: error: expected primary-expression before ‘<<’ token
> > <<<<<<< HEAD
> > ^
> > python/caffe/_caffe.cpp:398:3: error: expected primary-expression before ‘<<’ token
> > <<<<<<< HEAD
> > ^
> > python/caffe/_caffe.cpp:398:5: error: expected primary-expression before ‘<<’ token
> > <<<<<<< HEAD
> > ^
> > python/caffe/_caffe.cpp:398:7: error: expected primary-expression before ‘<’ token
> > <<<<<<< HEAD
> > ^
> > python/caffe/_caffe.cpp:398:9: error: ‘HEAD’ was not declared in this scope
> > <<<<<<< HEAD
> > ^
> > python/caffe/_caffe.cpp:400:1: error: expected primary-expression before ‘==’ token
> > # ^
> > python/caffe/_caffe.cpp:400:3: error: expected primary-expression before ‘==’ token
> > # ^
> > python/caffe/_caffe.cpp:400:5: error: expected primary-expression before ‘==’ token
> > ```
> >  ^
> > ```
> > 
> > 
> > # python/caffe/_caffe.cpp:400:7: error: expected primary-expression before ‘=’ token
> > ```
> >    ^
> > ```
> > 
> > 
> > python/caffe/_caffe.cpp:406:1: error: expected primary-expression before ‘>>’ token
> > > > > > > > > caffe/master
> > > > > > > > > ^
> > > > > > > > > python/caffe/_caffe.cpp:406:3: error: expected primary-expression before ‘>>’ token
> > > > > > > > > caffe/master
> > > > > > > > > ^
> > > > > > > > > python/caffe/_caffe.cpp:406:5: error: expected primary-expression before ‘>>’ token
> > > > > > > > > caffe/master
> > > > > > > > > ^
> > > > > > > > > python/caffe/_caffe.cpp:406:7: error: expected primary-expression before ‘>’ token
> > > > > > > > > caffe/master
> > > > > > > > > ^
> > > > > > > > > python/caffe/_caffe.cpp:406:14: error: expected primary-expression before ‘/’ token
> > > > > > > > > caffe/master
> > > > > > > > > ^
> > > > > > > > > python/caffe/_caffe.cpp:406:15: error: ‘master’ was not declared in this scope
> > > > > > > > > caffe/master
> > > > > > > > > ^
> > > > > > > > > Makefile:507: recipe for target 'python/caffe/_caffe.so' failed
> > > > > > > > > make: *** [python/caffe/_caffe.so] Error 1
> > 
> > 
> > ### I have no idea how to deal with it. Anyone could please help me to solve it ? Thanks a lot!
> 
> Have you fixed this problem? I have exactly the same error and got stuck, please help me!

Hi! I have encountered the same issue and I've solved it.
It turns out that what caused the problem is when I use the command 'git fetch caffe' and 'git merge caffe/master' to solve the incompatible with caffe, the conflict happens and I ignored it. So the git marked the place where conflict happened and you should correct that file. See '_caffe.cpp' and correct it in accordance with the same file in the newest version of caffe.
'<<<<HEAD' or '===' are marks you should delete, see details in https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/resolving-a-merge-conflict-using-the-command-line
