### ISSUE TITLE
fine-tuning with two caffemodel

### ISSUE THREAD

**Issue by longmao-yiran** [BVLC/caffe#5988]
As we know, caffe can use one or more caffemodel for fine-tuning，but if when I  fine-tuning with tow  caffemode which have same name about caffe-layer, what will be happened.Is the fine-tuning layer  which have same name with caffemdoel's layer will accepts the weight in the first caffemodel file or the average value of the two caffemodel ?
thank all

**Comment by Noiredd** [comment]
There is no need to duplicate posts from [caffe-users list][1] into issues. Please read the [guidelines for contributing][2] before submitting an issue or a pull request to help developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
