### ISSUE TITLE
InfogainLossLayer: description of the bottom blobs 

### ISSUE THREAD

**Issue by anmikh** [BVLC/caffe#5991]
It seems that the description of the bottoms blobs is out of date for the Infogain loss layer. 

At [this PR](https://github.com/BVLC/caffe/pull/3855) SoftmaxLoss layer was integrated to the InfogainLoss for numerical stability, and after that InfogainLoss takes just scores as one of the the bottoms blobs rather than probabilities. Thereafter it's equivalent to SoftmaxWithLoss layer rather than MultinominalLogisticLoss layer when Infogain matrix is the identity.

I've updated description at #5990

**Comment by shaibagon** [comment]
PR #5990  was merged. Thank you for your contribution!
