### ISSUE TITLE
failed to use caffe on matlab in ubuntu

### ISSUE THREAD

**Issue by HoiweCheng** [BVLC/caffe#5996]
### Issue summary
I installed caffe on ubuntu14.04, and i have the command ```make mattest``` passed. But while use caffe in matlab. I got the error ``` undefined function or variable 'caffe'```. I have ```add path of caffe to matlab```, is anybody know how to solve it?

**Comment by shaibagon** [comment]
Please use the [caffe-users list][1] for usage, installation, or modeling questions, or other requests for help.
You may also post questions on [stackoverflow][3], make sure you tag them with `caffe` tag.  
There is also [caffe.help][4] documenting the different layers of caffe.
Do not post such requests to Issues. Doing so interferes with the development of Caffe.

Please read the [guidelines for contributing][2] before submitting this issue.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
 [3]: http://stackoverflow.com/questions/tagged/caffe
 [4]: http://caffe.help/manual/layers.html
