### ISSUE TITLE
Swish activation function

### ISSUE THREAD

**Issue by anmikh** [BVLC/caffe#6003]
Do you have any plans of adding a novel activation function named Swish? It was introduced at [this paper](https://arxiv.org/abs/1710.05941). It was shown in the paper that Swish tends to work better than ReLU on the plenty of models and datasets. 
I've implemented Swish layer at the #6002

**Comment by Noiredd** [comment]
I set the `focus` label on your PR as it looks quite complete. Would you mind if we closed this issue and moved the discussion over there to keep it coherent?

**Comment by anmikh** [comment]
Ok, for sure

**Comment by anmikh** [comment]
@Noiredd Do you have any news about the plans to implement this layer? I have no response in #6002 so should I reopen/create a new issue or something else?
