### ISSUE TITLE
GPU Memory disappears

### ISSUE THREAD

**Issue by WenmuZhou** [BVLC/caffe#6012]
Please use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) for usage, installation, or modeling questions, or other requests for help.
_Do not post such requests to Issues._ Doing so interferes with the development of Caffe.

Please read the [guidelines for contributing](https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md) before submitting this issue.

### Issue summary
In the python  and matlabinterface, when I call `net = caffe.Net ()` to initialize a network, and then, I use `del net` in python or  `clear net` or `caffe.reset_all()` in matlab to delete the net , however, there will be 2M of GPU memory is not released.

### Steps to reproduce
```
import caffe
net_file = '15-conv.prototxt'
caffe_model = '15-conv.caffemodel'
caffe.set_mode_gpu()
net = caffe.Net(net_file, 1, weights=caffe_model)
del net
```

### Your system configuration
Operating system: Ubuntu 16.04 LTS
Compiler:
CUDA version (if applicable): 8.0
CUDNN version (if applicable): 6.0
BLAS:
Python or MATLAB version (for pycaffe and matcaffe respectively):
python 3.5 matlab2016b

**Comment by Noiredd** [comment]
Every application using CUDA will allocate some memory on the GPU for management and communication with the devide (see [CUDA context](https://stackoverflow.com/a/43251276)).

Please do not post usage, installation, or modeling questions, or other requests for help to Issues. Use the [caffe-users list][1] instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe. Please read the [guidelines for contributing][2] before submitting an issue or a pull request.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
