### ISSUE TITLE
(Solved) Training hangs with its process at "uninterruptible sleep" (D) state

### ISSUE THREAD

**Issue by ngmq** [BVLC/caffe#6020]
**Update (04 - Nov): I found the way to get rid of this issue. When this error happened, the lmdb data file and the training was run on a network drive. Since the network was not very stable during that time, at some point the network went down and the training process lost its connection to the lmdb data file. When the network came back, it failed to re-gain the connection and kept waiting for input from the lmdb.**

**The solution is to simply move everything - data and code - to a local drive. Since the local drive is physically attached to the pc, the connection is stable and the training works as expected.**

**My suggestion would be to have some sort of timeout threshold on the time the training process waits for input signal from lmdb file, or any data source to the input layer for that matter. Since the Memory Data layer already has some message like that ("Waiting for data"), I believe the normal Data layer can do the same.**

**Update (01 - Nov): this issue also happens when using only lmdb layer. The waiting channel of the process checked by "ps -eo ..." gives "futex_wait_queue_me".** 

### Issue summary

Training a CNN model gets stuck (hang) after running for about 25,000 iterations. No logs is displayed afterwards. Checking the status of the process with htop always display a red 'D' which I believe stands for "Disk sleep" and indicates a "uninterruptible sleep" process.

The model uses both MemoryDataLayer and LMDB Data layer.

After it hangs, I can kill the process (Ctrl + C) and then restart the training (from a previously saved solverstate). The training continues but only lasts for a few thousands more iterations and gets stuck again.

When training was running the status of its process alternates between 'S', 'D' and 'R'. After it hangs the status remains at 'D' infinitely (I killed it after 2 hours).

This happens with the latest code on master branch.

### Steps to reproduce

- Define a model like this: [Link](https://github.com/ngmq/Notes/blob/master/ELDObject_train.prototxt) or any model that uses a MemoryDataLayer and a LMDB layer.
- Train that model by iterating over a number of iterations (e.g iter 0 to 25,000). In each iteration, use AddDatumVector to put data into the MemoryDataLayer and call solver->Step(1) to train the model (instead of using solver->Solve()). The size of the datum vector is equal to batch_size (i.e. 100). 

### Your system configuration
**Swappiness set to 0.**
Operating system: Ubuntu 16.04
Compiler: GCC / NVCC
CUDA version (if applicable): 7.5
CUDNN version (if applicable): 4.0.7
Python or MATLAB version (for pycaffe and matcaffe respectively): Not relevant as I am using C++

**Comment by salmansamie** [comment]
Just curious, how could you kill a D-state process?
