### ISSUE TITLE
"BatchNormParameter" has no field named "scale_bias"

### ISSUE THREAD

**Issue by Zasy** [BVLC/caffe#6024]
I try to run a caffe.NetParameter for a example and find **Error parsing text-format caffe.NetParameter**
the logging like this:
[libprotobuf ERROR google/protobuf/text_format.cc:245] Error parsing text-format caffe.NetParameter: 52:15: Message type "caffe.BatchNormParameter" has no field named "scale_bias".
WARNING: Logging before InitGoogleLogging() is written to STDERR
F1102 09:40:47.271351 37064 upgrade_proto.cpp:122] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: /home/zhezhan2/pymodel/train_val_gpu.prototxt
*** Check failure stack trace: ***
run_gpu.sh: line 2: 37064 Aborted                 (core dumped) python compare_two_model.py --tool_1 caffe --file_1 /home/zhezhan2/pymodel/train_val_gpu.prototxt --tool_2 caffe --file_2 /home/zhezhan2/pymodel/train_val_mkl.prototxt

**Comment by shaibagon** [comment]
Please use the [caffe-users list][1] for usage, installation, or modeling questions, or other requests for help.
You may also post questions on [stackoverflow][3], make sure you tag them with `caffe` tag.  
There is also [caffe.help][4] documenting the different layers of caffe.
Do not post such requests to Issues. Doing so interferes with the development of Caffe.

Please read the [guidelines for contributing][2] before submitting this issue.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
 [3]: http://stackoverflow.com/questions/tagged/caffe
 [4]: http://caffe.help/manual/layers.html
