### ISSUE TITLE
Caffe build\Libraries folder Missing

### ISSUE THREAD

**Issue by Sarah635** [BVLC/caffe#6035]
Hello

I am building Caffe on Windows. When it is compiled caffe -help command works fine. But the folder caffe\build\Libraries is Missing. It does not allow me to interface Caffe with MATLAB.

Any Suggestion ? How to Resolve ?

**Comment by Noiredd** [comment]
Closing this in favor of discussion in [this thread](https://groups.google.com/forum/#!topic/caffe-users/uWwib172ADk).

Please do not post usage, installation, or modeling questions, or other requests for help to Issues. Use the [caffe-users list][1] instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe. Please read the [guidelines for contributing][2] before submitting an issue or a pull request.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
