### ISSUE TITLE
nd conv and nd pooling’s parameters

### ISSUE THREAD

**Issue by NonvolatileMemory** [BVLC/caffe#6039]
I want ask how to set a (3,3,3) conv kernel or (1,2,2) stride？

**Comment by Noiredd** [comment]
N-D pooling is, as of yet, unavailable. For convolution, you set kernel size and stride for each dimension by repeating the `kernel_size` or `stride` parameter. More reading: [caffe.help](http://caffe.help/manual/layers/convolution.html).

Please do not post usage, installation, or modeling questions, or other requests for help to Issues. Use the [caffe-users list][1] instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe. Please read the [guidelines for contributing][2] before submitting an issue or a pull request.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md

**Comment by NonvolatileMemory** [comment]
this url has nothing to help with this question,anyway thx for help.And I have to say the caffe's doc is so bad,and why the example folder doesn't contain c3d-vgg or other network use nd conv, I implement c3d-vgg and can I pull request?

**Comment by NonvolatileMemory** [comment]
@Noiredd  I don't think n-d pooling is unavailable, I use pre-trained c3d-vgg weights from c3d and modify it to bvlc/caffe, get the same output!
