### ISSUE TITLE
error == cudaSuccess (38 vs. 0)  no CUDA-capable device is detected

### ISSUE THREAD

**Issue by qixianbiao** [BVLC/caffe#604]
Hello, I have successfully compiled the caffe, when I run the example on mnist, I get the error 'error == cudaSuccess (38 vs. 0)  no CUDA-capable device is detected'.  Anybody can give me some suggestions?

**Comment by cfh3c** [comment]
Maybe you can try to switch to root (or use sudo)

**Comment by lidongxuan** [comment]
If your device is a mac with nvidia grapic card, download the lalatest driver from http://www.nvidia.com/object/mac-driver-archive.html 
It helps

**Comment by mechenghn** [comment]
Try to reduce the batch size.
