### ISSUE TITLE
How to run a test caffe net on GPU mode in Android device?

### ISSUE THREAD

**Issue by yungs2017** [BVLC/caffe#6040]
Now, I can run my test caffe net on my Android phone, is it possible to run in GPU mode in Android?

**Comment by Noiredd** [comment]
You will probably need to use the OpenCL branch of Caffe, as I don't suppose your Android phone has a CUDA-capable GPU (Caffe's main GPU code uses CUDA).

Please do not post usage, installation, or modeling questions, or other requests for help to Issues. Use the [caffe-users list][1] instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe. Please read the [guidelines for contributing][2] before submitting an issue or a pull request.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
