### ISSUE TITLE
how to use the cudnn implementation of max pooling?

### ISSUE THREAD

**Issue by my777777** [BVLC/caffe#6041]
Please use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) for usage, installation, or modeling questions, or other requests for help.
_Do not post such requests to Issues._ Doing so interferes with the development of Caffe.

Please read the [guidelines for contributing](https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md) before submitting this issue.

### Issue summary
I noted that caffe has the the cudnn implementation of pooling layer, but when I run the models (for example, lenet for mnist), I find it doesn't use the cudnn implementation, does not it support? or other reason?

I'm sure that I make caffe with cudnn, because the conv layer use the  cudnn implementation when I run the model.

### Your system configuration
Operating system: ubuntu 14.04
Compiler: g++
CUDA version (if applicable): 8.0
CUDNN version (if applicable): 6.0
BLAS: atlas
Python or MATLAB version (for pycaffe and matcaffe respectively): python 2.7

**Comment by Noiredd** [comment]
I'll redirect you to [caffe.help](http://caffe.help/manual/layers/pooling.html) - read the PoolingParameter proto message.

Please do not post usage, installation, or modeling questions, or other requests for help to Issues. Use the [caffe-users list][1] instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe. Please read the [guidelines for contributing][2] before submitting an issue or a pull request.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
