### ISSUE TITLE
I set device id not 0, but caffe always use gpu0 

### ISSUE THREAD

**Issue by aaronshan** [BVLC/caffe#6042]
### Issue summary
I set device id not 0, but caffe always use gpu0. firstly, I set gpu configure like this:
```
caffe.set_mode_gpu()
caffe.set_device(1)
```
And I find it always use a little resource of gpu0 when I init a model. I google this problem, and someone advice change the step order:
```
caffe.set_device(1)
caffe.set_mode_gpu()
```
Now, when I init a mode, It will only use the gpu that I specified. 

But I find that gpu0 always be used when    start execute python code `net.forward()`. 

![image](https://user-images.githubusercontent.com/5170947/32641029-9b671730-c606-11e7-90c7-ded6d9ac817a.png)

### Steps to reproduce
1. set gpu number not 0
2. set test mode to gpu
3. start test caffe model
4. when  start execute code `net.forward()`, gpu0 will be used.

### Your system configuration
Operating system:centos 6.5
Compiler:gcc 5.3.0
CUDA version (if applicable):8.0.44
CUDNN version (if applicable):6
BLAS:openblas
Python or MATLAB version (for pycaffe and matcaffe respectively):python 2.7.5

**Comment by aaronshan** [comment]
I solved the problem by specifying environment variable:
```
import os
os.environ["CUDA_DEVICE_ORDER"]="PCI_BUS_ID"
os.environ["CUDA_VISIBLE_DEVICES"]="1"
```

**Comment by OMG59E** [comment]
if you build opencv  with opencl ？ try build opencv  " -DWITH_OPENCL=OFF " .
