### ISSUE TITLE
Inconsistent results with FCN for different input patch sizes

### ISSUE THREAD

**Issue by cesans** [BVLC/caffe#6044]
### Issue summary
For a Fully Convolutional Network, the input patch size affects the outputs in undesired ways. 
This is a problem found when using Caffe to predict large images by splitting them into smaller 
subimages, as changing the subimage size changes the results.

### Steps to reproduce

1) Create a simple FCN with only two layers (prototxt attached):
[deploy_fcn.prototxt.txt](https://github.com/BVLC/caffe/files/1460913/deploy_fcn.prototxt.txt)

```
net = caffe.Net('deploy_fcn.prototxt', caffe.TEST, weights=None)
```
Layer 1: Convolution with kernel_size=7, stride=1
Layer 2: Convolution with kernel_size=11, stride=1

The receptive field of this network is 17, so the first output of the second convolution should only be affected by the first 17x17 pixels of the input patch.

2) Create two patches:

```
rf_input = np.ones((3, 17, 17))
larger_input = np.ones((3, 25, 25))
```

3) Predict both of them:
```
net.blobs['data'].reshape(1, 3, 17, 17)
net.blobs['data'].data[0] = rf_input
r = net.forward()['conv2'][0,0,0,0]
print  '{0:.13f}'.format(r)
```
113.8469314575195

```
net.blobs['data'].reshape(1, 3, 25, 25)
net.blobs['data'].data[0] = larger_input
r = net.forward()['conv2'][0,0,0,0]
print  '{0:.13f}'.format(r)
```
113.8366546630859

**No input affecting the first output have been changed, but the output is still different.**

3) Changing the values out of the receptive field to any other value does not change
the outputs, so it it doesn't look like the network is using extra pixels in the second case:
```
rf_input[:, 17:, :] = 80
larger_input[:, :,17:] = 80
```

### Your system configuration
Operating system: Ubuntu 16.04
Compiler: gcc 5.4.0
CUDA version (if applicable): 8.0
CUDNN version (if applicable): -
BLAS: Atlas
Python or MATLAB version (for pycaffe and matcaffe respectively): Python 2.7

**Comment by wenyangchu** [comment]
I have the same here!!

**Comment by shaibagon** [comment]
Please use the [caffe-users list][1] for usage, installation, or modeling questions, or other requests for help.
You may also post questions on [stackoverflow][3], make sure you tag them with `caffe` tag.  
There is also [caffe.help][4] documenting the different layers of caffe.
Do not post such requests to Issues. Doing so interferes with the development of Caffe.

Please read the [guidelines for contributing][2] before submitting this issue.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
 [3]: http://stackoverflow.com/questions/tagged/caffe
 [4]: http://caffe.help/manual/layers.html

**Comment by cesans** [comment]
@shaibagon The issue opened here is not intended as a request for help regarding the usage, installation or modeling but just the report of what looks like a wrong output for a network. Considering the definition of the convolutional layer, the output in both cases must be the same (unless I made a mistake) but I get different values.

Could the issue be opened again?
