### ISSUE TITLE
The version ('90000') of the host compiler ('Apple clang') is not supported

### ISSUE THREAD

**Issue by zhangchunsheng** [BVLC/caffe#6049]
### Issue summary

nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
nvcc fatal   : The version ('90000') of the host compiler ('Apple clang') is not supported
make: *** [.build_release/cuda/src/caffe/layers/absval_layer.o] Error 1

### Steps to reproduce
make

### Your system configuration
Operating system:MacOS 10.12.6
Compiler: Xcode 9.1
CUDA version (if applicable): 9.0.222
CUDNN version (if applicable): 8.0
BLAS:
Python or MATLAB version (for pycaffe and matcaffe respectively):

**Comment by dnbaker** [comment]
I am also encountering this issue. How did you solve it?
