### ISSUE TITLE
Check failed: data_ when feature extraction with bn layer

### ISSUE THREAD

**Issue by longmao-yiran** [BVLC/caffe#6062]
### Issue summary
when I use the feature_extraction code to look the feature map with [resnet-50](https://github.com/KaimingHe/deep-residual-networks), it report an error `blob.cpp:163] Check failed: data_`. After I checked the prototxt, I think that BN layer cause this error. How can I do?

### Your system configuration
Operating system:ubuntu 16.04
Compiler:
CUDA version (if applicable):cuda8.0
CUDNN version (if applicable):no
BLAS:
Python or MATLAB version (for pycaffe and matcaffe respectively):python 2.7

**Comment by Noiredd** [comment]
Please do not post usage, installation, or modeling questions, or other requests for help to Issues. Use the [caffe-users list][1] instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe. Please read the [guidelines for contributing][2] before submitting an issue or a pull request.

When making a post on users list, please attach the complete output log and network prototxt. Also, make sure it is clear which version of Caffe are you using - the latest master, or the b590f1d snapshot suggested by Kaiming He in his repo (or whichever else).

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
