### ISSUE TITLE
caffe make all error, /usr/bin/ld: cannot find -lboost_python3

### ISSUE THREAD

**Issue by Sam813** [BVLC/caffe#6063]
Dear All, 

During the compilation of caffe from source i got this error:

AR -o .build_release/lib/libcaffe.a
LD -o .build_release/lib/libcaffe.so.1.0.0
/usr/bin/ld: cannot find -lboost_python3
collect2: error: ld returned 1 exit status
Makefile:572: recipe for target '.build_release/lib/libcaffe.so.1.0.0' failed
make: *** [.build_release/lib/libcaffe.so.1.0.0] Error 1

Any one can help how to solve it?

**Comment by cicido** [comment]
MacOS?

**Comment by storylike** [comment]
You need to create symbolic links to redirect "libboost_python3.so" to "libboost_python-py35.so", in /usr/lib/x86_64-linux-gnu.
Please refer to this article for more details:
[](https://github.com/BVLC/caffe/issues/4843)

**Comment by Hesam621** [comment]
@cicido  its Ubuntu 17.10

**Comment by Hesam621** [comment]
@storylike 
I followed the steps mentioned in that article and seems that issue is solved but it hit to another error 
it seems never ending.. 
Can I have the sample of your makefile.config so i follow the way you set the paths. i guess there should be a problem in that part. it doesn't make sense to have this much errors.

**Comment by storylike** [comment]
What kind of errors are you encountering?
Have you set INCLUDE_DIRS and LIBRARY_DIRS correctly?
In fact, I followed the steps form this link:
https://chunml.github.io/ChunML.github.io/project/Installing-Caffe-CPU-Only/
This article reveals several common obstacles during caffe build, and provides solutions, thanks to @ChunML.
The Makefile.config may vary, according different personalized settings, anyway, I post my settings here, hope it help. And good luck with you.
[Makefile.config.log](https://github.com/BVLC/caffe/files/1502802/Makefile.config.log)

**Comment by Sam813** [comment]
@storylike 
thanks for the make file and the link. my make.config is almost same except im trying to compile it on anaconda and python3.
The recent issue is:
libpng16.so.16, needed by /home/Sam/anaconda3/lib/libopencv_imgcodecs.so, not found (try using -rpath or -rpath-link)
seems some of the opencv libraries are missing

**Comment by Noiredd** [comment]
This is not an issue with Caffe itself but an installation problem. When compiling from source, please make sure you've got all [dependencies][3] installed.

Please do not post usage, installation, or modeling questions, or other requests for help to Issues. Use the [caffe-users list][1] instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe. Please read the [guidelines for contributing][2] before submitting an issue or a pull request.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
 [3]: https://github.com/BVLC/caffe/blob/master/docs/install_apt.md#for-ubuntu--1704-1

**Comment by JFishLover** [comment]
thanks, your method is right for me @storylike

**Comment by cpp2016** [comment]
> You need to create symbolic links to redirect "libboost_python3.so" to "libboost_python-py35.so", in /usr/lib/x86_64-linux-gnu.
> Please refer to this article for more details:
> #4843

i just can not find files whose name contains "python3.so" or "python-py35.so".  I use 

find / -name "*_python*.so"

and got 

/usr/lib64/libboost_python-mt.so
/usr/lib64/libboost_python.so

None of them seem to be the right one. But I have python3.5.0 in my ubuntu 16.04 well.

**Comment by amoazeni75** [comment]
I wanted to build Caffe and faced the same issue. Unfortunately, none of the answers work in my case. I checked the location of lboost_python by the following command:
<br>
<code> find /usr/lib -name libboost_python-py </code>

I found the lboost_python libraries and here are some of them:
<ul>
<li>libboost_python37.a</li>
<li>libboost_python37-mt.a</li>
<li>libboost_python37-mt.so</li>
<li>libboost_python37-mt.so.1.68.0</li>
</ul>

Then in the **Makefile.config** file I changed the following line: <br>
PYTHON_LIBRARIES := **boost_python** python3.7m   <br>to <br>
PYTHON_LIBRARIES := **boost_python37-mt** python3.7m
