### ISSUE TITLE
Add CUDA>8.0 comments in Makefile.config.example 

### ISSUE THREAD

**Issue by sm176357** [BVLC/caffe#6068]
### Issue summary
[Minor] The compilation fails when using a system with CUDA 9.0 as the architectures 'compute_20', 'sm_20', and 'sm_21' are deprecated. It might be helpful to add it as comment inside the Makefile.config.example directly where the comments for CUDA < 6.0 and CUDA < 8.0 are placed. 

### Reproduce 
`make all` leads to

```
NVCC src/caffe/layers/inner_product_layer.cu
nvcc fatal   : Unsupported gpu architecture 'compute_20'
```

### System 
Operating system: Ubuntu 16.04
CUDA version (if applicable): 9.0
CUDNN version (if applicable): 7.0
BLAS: atlas
Python or MATLAB version (for pycaffe and matcaffe respectively):

### Links
[nvidia-forum](https://devtalk.nvidia.com/default/topic/995286/nvcc-compiler-warning-compute_20-/)
[opencv-FindCuda not working](https://github.com/opencv/opencv/issues/9535)

**Comment by plgkm6** [comment]
You can simple remove the line which 'compute_20' and 'sm_20' in Makefile.config, then you can compile it.
But, it will fail 'make runtest'.

**Comment by sm176357** [comment]
Yes I know. 

Since similar compatibility comments are already in place for the other CUDA versions, it makes sense to do likewise for CUDA 9.0.

**Comment by Noiredd** [comment]
Thanks for the catch!

**Comment by mememimis** [comment]
There is any way to install caffe-cuda without the cuda? It downloads the cuda 10 but my Nvidia driver can support only cuda 9.
