### ISSUE TITLE
 Adam solver makes MATLAB crash.

### ISSUE THREAD

**Issue by lawpdas** [BVLC/caffe#6069]
### Issue summary
"Adam" and other solver methods will make MATLAB crash with "Segmentation violation". Only "SGD" can be used in MATLAB.

### Steps to reproduce

Change solver type to "Adam". MATLAB will crash at `solver.step(1);`

### system configuration
Ubuntu16.04
g++5.4
CUDA 8.0
CUDNN 5.1
BLAS: MKL
Python 2.7 
MATLAB 2016b&2014b

**Comment by gasvn** [comment]
I got the samilar issure as you do, do you solve it?

**Comment by HaojieCoding** [comment]
My codes run well on another computer (ubuntu14, matlab2016a, gtx1080, cuda8, cudnn5.1, mkl).

**Comment by gasvn** [comment]
I avoid this problem by using sudo, thanks.

**Comment by HaojieCoding** [comment]
`sudo matlab`？ It can‘t solve my issue.
