### ISSUE TITLE
Error in importing caffe

### ISSUE THREAD

**Issue by Sam813** [BVLC/caffe#6074]
Hi guys, 
I have successfully make caffe and then make test followed by make runtest.
the last part of runtest results:
.
.
### [----------] 5 tests from EmbedLayerTest/1, where TypeParam = caffe::CPUDevice<double>
[ RUN      ] EmbedLayerTest/1.TestForward
[       OK ] EmbedLayerTest/1.TestForward (0 ms)
[ RUN      ] EmbedLayerTest/1.TestGradient
[       OK ] EmbedLayerTest/1.TestGradient (7 ms)
[ RUN      ] EmbedLayerTest/1.TestGradientWithBias
[       OK ] EmbedLayerTest/1.TestGradientWithBias (11 ms)
[ RUN      ] EmbedLayerTest/1.TestSetUp
[       OK ] EmbedLayerTest/1.TestSetUp (0 ms)
[ RUN      ] EmbedLayerTest/1.TestForwardWithBias
[       OK ] EmbedLayerTest/1.TestForwardWithBias (0 ms)
[----------] 5 tests from EmbedLayerTest/1 (18 ms total)

[----------] Global test environment tear-down
[==========] 1106 tests from 150 test cases ran. (43596 ms total)
[  PASSED  ] 1106 tests.

but when i do the make pycaffe i got some error which i solved them and ultimately after make pycaffe i got the message: 
make: Nothing to be done for 'pycaffe'.
I  thought everything is alright 

but when I try to import the caffe in python, hit to error below :
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'caffe'

Any idea whats the problem?
Thanks

**Comment by Noiredd** [comment]
Check [this][3] or any of the various previous posts relating to Python being unable to find Caffe. If none of the available solutions work for you, do reopen the issue providing more information.

Please do not post usage, installation, or modeling questions, or other requests for help to Issues. Use the [caffe-users list][1] instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe. Please read the [guidelines for contributing][2] before submitting an issue or a pull request.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
 [3]: https://github.com/BVLC/caffe/issues/263#issuecomment-38771502

**Comment by triple-tam** [comment]
Actually I suggest you to try adding "caffe_root/python/caffe" to your PYTHONPATH. It just didn't work appropriately for me because of some boost/boost-python package issues.
