### ISSUE TITLE
make runtest error .

### ISSUE THREAD

**Issue by YingXiuHe** [BVLC/caffe#6076]
Operating system:ubuntu16.04
CUDA version (if applicable):8.0
CUDNN version (if applicable):8.0

  it was passed make all and make test when i build caffe ,but when i make runtest,there some errors.i do not how to solve it ,i need some help. thanks a lot.
  the error codes as follows:
`*** SIGABRT (@0x7a38) received by PID 31288 (TID 0x7fbb91098b00) from PID 31288; stack trace: ***
    @     0x7fbb7c21c390 (unknown)
    @     0x7fbb7be76428 gsignal
    @     0x7fbb7be7802a abort
    @     0x7fbb7beb87ea (unknown)
    @     0x7fbb7bec137a (unknown)
    @     0x7fbb7bec553c cfree
    @     0x7fbb88e068af google::protobuf::internal::DestroyDefaultRepeatedFields()
    @     0x7fbb88e05b3b google::protobuf::ShutdownProtobufLibrary()
    @     0x7fbb56b3c3b9 (unknown)
    @     0x7fbb90faade7 (unknown)
    @     0x7fbb7be7aff8 (unknown)
    @     0x7fbb7be7b045 exit
    @     0x7fbb7be61837 __libc_start_main
    @           0x4081f9 _start
    @                0x0 (unknown)
Makefile:532: recipe for target 'runtest' failed
make: *** [runtest] Aborted (core dumped)
`

**Comment by Akanichi** [comment]
Hi, 
I get the same problem, did anyone find a solution for this problem?

[----------] 1 test from HDF5OutputLayerTest/0, where TypeParam = caffe::CPUDevice<float>
[ RUN      ] HDF5OutputLayerTest/0.TestForward
unknown file: Failure
C++ exception with description "locale::facet::_S_create_c_locale name not valid" thrown in the test fixture's constructor.
*** Aborted at 1515762253 (unix time) try "date -d @1515762253" if you are using GNU date ***
PC: @   0x35ac58 DeleteThreadLocalValue
*** SIGSEGV (@0x0) received by PID 2918 (TID 0x6e12d000) from PID 0; stack trace: ***
    @ 0x7402e6c0 (unknown)
Segmentation fault
Makefile:532: recipe for target 'runtest' failed
make: *** [runtest] Error 139

**Comment by xiangyun-hz** [comment]
have you solevd?help me?

**Comment by dragonQian** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by LordonCN** [comment]
> have you solevd?help me?

have you solevd?
