### ISSUE TITLE
Unable to reset caffe.Net object instance without consuming extra memory

### ISSUE THREAD

**Issue by slothkong** [BVLC/caffe#6077]
I'm trying to experiment with model pruning. At each iteration of a loop I modify the model weights , run net.forward()  and reload the object by calling caffe.Net(...). However this eats up my VRAM. I have not been able to find any documentation and there closes thing I found was  an open issue on how to properly delete the net object on C++ #5327 .

I there simply need to reset the weights reading from the caffemodel. Is this supported by the python API?

**Comment by roeyjohn** [comment]
Did you find a solution for this issue ? I am also facing the same memory leak issue.

**Comment by slothkong** [comment]
I copied the network parameters to np arrays, one for each layer I needed to modify.  Whenever I needed to restart the net I copied form the extra np array to the model. O only instantiated the net object once.
