### ISSUE TITLE
make pycaffe failed

### ISSUE THREAD

**Issue by Sam813** [BVLC/caffe#6080]
I have run
make all
make test
make runtest, successfully and make runtest passed all tests. ![image](https://user-images.githubusercontent.com/33405497/33352689-32e9983e-d4fe-11e7-8a5a-a74f8a0c46ea.png)

but to make pycaffe i got the error below: 

CXX/LD -o python/caffe/_caffe.so python/caffe/_caffe.cpp
touch python/caffe/proto/__init__.py
PROTOC (python) src/caffe/proto/caffe.proto

Any idea what is this about?

**Comment by Noiredd** [comment]
This is not an error - looks like you successfully build pycaffe, congrats! :)  
If you run into any issues when doing `import caffe` in Python, let us know on the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users).
