### ISSUE TITLE
create_imagenet.sh: line 41: C:/caffe/tools/convert_imageset: No such file or directory

### ISSUE THREAD

**Issue by NaveenBandi** [BVLC/caffe#6090]
### Issue summary
While running caffe in windows. I execute the create_imagenet.sh using cygwin bash. It gives an error telling No such file or directory. 
I have configured my system using Cmake 3.7 version. And built the solution using VS2015. But in caffe the build/tools folder is not created and the binaries like "convert_imageset " are not created.  I think the absence of binaries is causing problem. 

Kindly tell me how build binaries and use them.
I have installed VS2015, cmake 3,7, and cygwin, python 2.7
I want to run windows-caffe without GPU, only CPU mode I want to run.
I am attaching the CMakeCache.txt and make in CMD prompt.
Also I face trouble in make pycaffe. Please guide me..

[CMakeCache.txt](https://github.com/BVLC/caffe/files/1521597/CMakeCache.txt)
![make](https://user-images.githubusercontent.com/23726777/33483237-e75ff522-d6c2-11e7-8433-4c3a137f45c5.JPG)

### Steps to reproduce

If you are having difficulty building Caffe or training a model, please ask the caffe-users mailing list. If you are reporting a build error that seems to be due to a bug in Caffe, please attach your build configuration (either Makefile.config or CMakeCache.txt) and the output of the make (or cmake) command.

### Your system configuration
Operating system: Windows 7
Compiler: cl.exe from VS2015
CUDA version (if applicable): NIL
CUDNN version (if applicable): NIL
BLAS: open
Python or MATLAB version (for pycaffe and matcaffe respectively):python 2.7

**Comment by Noiredd** [comment]
Please do not post usage, installation, or modeling questions, or other requests for help to Issues. Use the [caffe-users list][1] instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe. Please read the [guidelines for contributing][2] before submitting an issue or a pull request.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md

**Comment by NaveenBandi** [comment]
[image: Inline image 1]
While import caffe I get this error kindly help....
