### ISSUE TITLE
The function "bool ReadProtoFromTextFile(const char* filename, Message* proto)" in util/io.cpp, what if given a bad filename parameter, the function will not return false?

### ISSUE THREAD

**Issue by adty1992** [BVLC/caffe#6094]
### Issue summary
The function below in io.cpp, while function open() return -1, that means given a bad filename parameter, it will not return false but just give a log message. Will that cause crash? 

bool ReadProtoFromTextFile(const char* filename, Message* proto) {
  int fd = open(filename, O_RDONLY);
  CHECK_NE(fd, -1) << "File not found: " << filename;
  FileInputStream* input = new FileInputStream(fd);
  bool success = google::protobuf::TextFormat::Parse(input, proto);
  delete input;
  close(fd);
  return success;
}

bool ReadProtoFromBinaryFile(const char* filename, Message* proto) {
  int fd = open(filename, O_RDONLY);
  CHECK_NE(fd, -1) << "File not found: " << filename;
  ZeroCopyInputStream* raw_input = new FileInputStream(fd);
  CodedInputStream* coded_input = new CodedInputStream(raw_input);
  coded_input->SetTotalBytesLimit(kProtoReadBytesLimit, 536870912);

  bool success = proto->ParseFromCodedStream(coded_input);

  delete coded_input;
  delete raw_input;
  close(fd);
  return success;
}

**Comment by Noiredd** [comment]
CHECK_NE (and all CHECK, CHECK_xx expressions) act as assertions that terminate the execution if the condition is not met - not just log a failure. So we don't have to care about what the function outputs - the whole program is stopped at this point.
