### ISSUE TITLE
Unknown error message

### ISSUE THREAD

**Issue by MrWanter** [BVLC/caffe#6099]
I'm running a demo script which has been successfully running on another machine of mine, after set up caffe, and run the same demo, it gives:

```
WARNING: Logging before InitGoogleLogging() is written to STDERR
W1210 21:17:11.100247  4136 _caffe.cpp:139] DEPRECATION WARNING - deprecated use of Python interface
W1210 21:17:11.100286  4136 _caffe.cpp:140] Use this instead (with the named "weights" parameter):
W1210 21:17:11.100291  4136 _caffe.cpp:142] Net('/usr/local/fast-rcnn/models/CaffeNet/test.prototxt', 1, weights='/usr/local/fast-rcnn/data/fast_rcnn_models/caffenet_fast_rcnn_iter_40000.caffemodel')
[libprotobuf ERROR google/protobuf/text_format.cc:274] Error parsing text-format caffe.NetParameter: 195:21: Message type "caffe.LayerParameter" has no field named "roi_pooling_param".
F1210 21:17:11.127717  4136 upgrade_proto.cpp:88] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: /usr/local/fast-rcnn/models/CaffeNet/test.prototxt
*** Check failure stack trace: ***
Aborted (core dumped)
```
someone give me some hint?

### Your system configuration
Operating system: ubuntu 16.04
Compiler: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.5) 5.4.0 20160609
CUDA version (if applicable): 9.0
CUDNN version (if applicable):7
BLAS:3.10.2-9
Python or MATLAB version (for pycaffe and matcaffe respectively): python2.7.14

**Comment by MrWanter** [comment]
seems caused by incompatibility between current caffe version and the version of the dedicated one in the script

**Comment by Noiredd** [comment]
You are using a demo that was designed to run under [Fast-RCNN](https://github.com/rbgirshick/caffe-fast-rcnn). Caffe master has no `roi_pooling` layer, and hence no `roi_pooling_param` - you will need to compile the dedicated fork.
