### ISSUE TITLE
Caffe New layer for Eigenvectors decomposition

### ISSUE THREAD

**Issue by redhat12345** [BVLC/caffe#6105]
I have extracted features from fc8 layer of alexNet and I am using ImageNet pre-trained model. I would like to calculate the eigenvectors of the fc8 features. How can I do that? Can you create a layer that will calculate eigenvectors and eigenvalues automatically?

**Comment by Noiredd** [comment]
This is something you can do yourself in Python with minimum coding - just extract your features using the standard interface and do something like [numpy.linalg.eig](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.linalg.eig.html). I don't think we need a whole new layer for that.
