### ISSUE TITLE
make runtest failed 

### ISSUE THREAD

**Issue by QuantumLiu** [BVLC/caffe#6106]
### Issue summary
make all -j48
sudo make runtest -j48
got error:
E1214 15:12:34.670022 18015 io.cpp:80] Could not open or find file examples/images/cat.jpg
F1214 15:12:34.670155 18015 image_data_layer.cpp:77] Check failed: cv_img.data Could not load examples/images/cat.jpg
*** Check failure stack trace: ***
    @     0x7f0250c475cd  google::LogMessage::Fail()
    @     0x7f0250c49433  google::LogMessage::SendToLog()
    @     0x7f0250c4715b  google::LogMessage::Flush()
    @     0x7f0250c49e1e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f024b6008ed  caffe::ImageDataLayer<>::DataLayerSetUp()
    @     0x7f024b69567e  caffe::BasePrefetchingDataLayer<>::LayerSetUp()
    @           0x4840d0  caffe::Layer<>::SetUp()
    @           0x65b714  caffe::ImageDataLayerTest_TestRead_Test<>::TestBody()
    @           0x92cfd3  testing::internal::HandleExceptionsInMethodIfSupported<>()
    @           0x9265ea  testing::Test::Run()
    @           0x926738  testing::TestInfo::Run()
    @           0x926815  testing::TestCase::Run()
    @           0x927aef  testing::internal::UnitTestImpl::RunAllTests()
    @           0x927e13  testing::UnitTest::Run()
    @           0x46df1d  main
    @     0x7f024a8c7830  __libc_start_main
    @           0x475a79  _start
    @              (nil)  (unknown)
Makefile:534: recipe for target 'runtest' failed
make: *** [runtest] 已放弃 (core dumped)

### Steps to reproduce
makefile.config:
```
## Refer to http://caffe.berkeleyvision.org/installation.html
# Contributions simplifying and improving our build system are welcome!

# cuDNN acceleration switch (uncomment to build with cuDNN).
 USE_CUDNN := 1

# CPU-only switch (uncomment to build without GPU support).
# CPU_ONLY := 1

# uncomment to disable IO dependencies and corresponding data layers
 USE_OPENCV := 1
# USE_LEVELDB := 0
# USE_LMDB := 0

# uncomment to allow MDB_NOLOCK when reading LMDB files (only if necessary)
#	You should not set this flag if you will be reading LMDBs with any
#	possibility of simultaneous read and write
# ALLOW_LMDB_NOLOCK := 1

# Uncomment if you're using OpenCV 3
 OPENCV_VERSION := 3

# To customize your choice of compiler, uncomment and set the following.
# N.B. the default for Linux is g++ and the default for OSX is clang++
# CUSTOM_CXX := g++

# CUDA directory contains bin/ and lib/ directories that we need.
CUDA_DIR := /usr/local/cuda-8.0
# On Ubuntu 14.04, if cuda tools are installed via
# "sudo apt-get install nvidia-cuda-toolkit" then use this instead:
# CUDA_DIR := /usr

# CUDA architecture setting: going with all of them.
# For CUDA < 6.0, comment the *_50 through *_61 lines for compatibility.
# For CUDA < 8.0, comment the *_60 and *_61 lines for compatibility.
# For CUDA >= 9.0, comment the *_20 and *_21 lines for compatibility.
CUDA_ARCH := -gencode arch=compute_61,code=sm_61 \
		-gencode arch=compute_61,code=compute_61

# BLAS choice:
# atlas for ATLAS (default)
# mkl for MKL
# open for OpenBlas
BLAS := open
# Custom (MKL/ATLAS/OpenBLAS) include and lib directories.
# Leave commented to accept the defaults for your choice of BLAS
# (which should work)!
# BLAS_INCLUDE := /path/to/your/blas
# BLAS_LIB := /path/to/your/blas

# Homebrew puts openblas in a directory that is not on the standard search path
# BLAS_INCLUDE := $(shell brew --prefix openblas)/include
# BLAS_LIB := $(shell brew --prefix openblas)/lib

# This is required only if you will compile the matlab interface.
# MATLAB directory should contain the mex binary in /bin.
# MATLAB_DIR := /usr/local
# MATLAB_DIR := /Applications/MATLAB_R2012b.app

# NOTE: this is required only if you will compile the python interface.
# We need to be able to find Python.h and numpy/arrayobject.h.
#PYTHON_INCLUDE := /usr/include/python2.7 \
		/usr/lib/python2.7/dist-packages/numpy/core/include
# Anaconda Python distribution is quite popular. Include path:
# Verify anaconda location, sometimes it's in root.
 ANACONDA_HOME := $(HOME)/anaconda3
 PYTHON_INCLUDE := $(ANACONDA_HOME)/include \
		 $(ANACONDA_HOME)/include/python3.5m \
		# $(ANACONDA_HOME)/lib/python2.7/site-packages/numpy/core/include

# Uncomment to use Python 3 (default is Python 2)
 PYTHON_LIBRARIES := boost_python3 python3.5m
# PYTHON_INCLUDE := /usr/include/python3.5m \
#                 /usr/lib/python3.5/dist-packages/numpy/core/include

# We need to be able to find libpythonX.X.so or .dylib.
#PYTHON_LIB := /usr/lib
 PYTHON_LIB := $(ANACONDA_HOME)/lib

# Homebrew installs numpy in a non standard path (keg only)
# PYTHON_INCLUDE += $(dir $(shell python -c 'import numpy.core; print(numpy.core.__file__)'))/include
# PYTHON_LIB += $(shell brew --prefix numpy)/lib

# Uncomment to support layers written in Python (will link against Python libs)
 WITH_PYTHON_LAYER := 1

# Whatever else you find you need goes here.
INCLUDE_DIRS := $(PYTHON_INCLUDE) /usr/local/include
LIBRARY_DIRS := $(PYTHON_LIB) /usr/local/lib /usr/lib /usr/lib/x86_64-linux-gnu /usr/lib/x86_64-linux-gnu/hdf5/serial

# If Homebrew is installed at a non standard location (for example your home directory) and you use it for general dependencies
# INCLUDE_DIRS += $(shell brew --prefix)/include
# LIBRARY_DIRS += $(shell brew --prefix)/lib

# NCCL acceleration switch (uncomment to build with NCCL)
# https://github.com/NVIDIA/nccl (last tested version: v1.2.3-1+cuda8.0)
# USE_NCCL := 1

# Uncomment to use `pkg-config` to specify OpenCV library paths.
# (Usually not necessary -- OpenCV libraries are normally installed in one of the above $LIBRARY_DIRS.)
# USE_PKG_CONFIG := 1

# N.B. both build and distribute dirs are cleared on `make clean`
BUILD_DIR := build
DISTRIBUTE_DIR := distribute

# Uncomment for debugging. Does not work on OSX due to https://github.com/BVLC/caffe/issues/171
# DEBUG := 1

# The ID of the GPU that 'make runtest' will use to run unit tests.
TEST_GPUID := 0

# enable pretty build (comment to see full commands)
Q ?= @

```
### Your system configuration
Operating system:ubuntu16.04
Compiler:gcc
CUDA version (if applicable):8
CUDNN version (if applicable):5.1
BLAS:openblas
Python or MATLAB version (for pycaffe and matcaffe respectively):python3.5 anaconda

**Comment by Thomio-Watanabe** [comment]
You had no problem to compile, right ?
Does the file **examples/images/cat.jpg** exists ?

**Comment by QuantumLiu** [comment]
Yes,it already exists.
I solved this problem by rebuilding opencv with -D build jpeg

**Comment by Tclz** [comment]
> Yes,it already exists.
> I solved this problem by rebuilding opencv with -D build jpeg

Hi, i have met the same problem. Could you please tell me the details about "-D build jpeg", i just don't know how to operate it.
the command i used for building opencv is 
**cmake -D CMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_PREFIX=/usr/local ..**
Thanks in advance!!!

**Comment by Tclz** [comment]
> > Yes,it already exists.
> > I solved this problem by rebuilding opencv with -D build jpeg
> 
> Hi, i have met the same problem. Could you please tell me the details about "-D build jpeg", i just don't know how to operate it.
> the command i used for building opencv is
> **cmake -D CMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_PREFIX=/usr/local ..**
> Thanks in advance!!!

Ok，I finally via the following command to rebuild OpenCV and succeed.
`cmake -D CMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_PREFIX=/usr/local -DBUILD_JPEG=ON -DBUILD_PNG=ON -DBUILD_TIFF=ON -DBUILD_ZLIB=ON ..`
