### ISSUE TITLE
Check failed: result[j]->width() == 5 (1 vs. 5)

### ISSUE THREAD

**Issue by SmartMachineBay** [BVLC/caffe#6108]
after i add a layer to caffe , train network is ok. But when i try to use train_val ,the error has come. The error message is as follows :
I1214 21:54:06.552299 11832 net.cpp:693] Ignoring source layer loss
F1214 21:54:06.728137 11832 solver.cpp:464] Check failed: result[j]->width() == 5 (1 vs. 5) 
*** Check failure stack trace: ***
    @     0x7fee5acf6daa  (unknown)
    @     0x7fee5acf6ce4  (unknown)
    @     0x7fee5acf66e6  (unknown)
    @     0x7fee5acf9687  (unknown)
    @     0x7fee5b394cf0  caffe::Solver<>::TestDetection()
    @     0x7fee5b394f99  caffe::Solver<>::TestAll()
    @     0x7fee5b3950c0  caffe::Solver<>::Step()
    @     0x7fee5b3958ce  caffe::Solver<>::Solve()
    @           0x408e7a  train()
    @           0x40627c  main
    @     0x7fee59cfef45  (unknown)
    @           0x406aeb  (unknown)
    @              (nil)  (unknown)
Aborted (core dumped)

What should i do to fix it ? Your help is greatly appreciated.

**Comment by Noiredd** [comment]
Please do not post usage, installation, or modeling questions, or other requests for help to Issues. Use the [caffe-users list][1] instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe. Please read the [guidelines for contributing][2] before submitting an issue or a pull request.

When posting to the user list, please provide more details, like your solver and net definitions, as well as the code of your new layer.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md

**Comment by mathmanu** [comment]
You can visualize your net train.prototxt and test.prototxt with netscope tool. The error is saying that 5 outputs are expected, but only one is obtained.
