### ISSUE TITLE
3 Failed Tests - CompileNetTest

### ISSUE THREAD

**Issue by JohnSmithyy** [BVLC/caffe#6113]
I ran sudo make runtest and encountered the following 3 failed tests:

[  FAILED  ] 3 tests, listed below:
[  FAILED  ] CompileNetTest.TestCompileNetLayerParamEngineConvolution
[  FAILED  ] CompileNetTest.TestCompileNetConvolution
[  FAILED  ] CompileNetTest.TestCompileNetBatchNormConvolution

How do I go about to resolving this?

I'm on Ubuntu 16.04 and Python 2.7.12.

**Comment by larryluo619** [comment]
I had the same results:

[----------] Global test environment tear-down
[==========] 1322 tests from 200 test cases ran. (135672 ms total)
[  PASSED  ] 1319 tests.
[  FAILED  ] 3 tests, listed below:
[  FAILED  ] CompileNetTest.TestCompileNetLayerParamEngineConvolution
[  FAILED  ] CompileNetTest.TestCompileNetBatchNormConvolution
[  FAILED  ] CompileNetTest.TestCompileNetConvolution

 3 FAILED TESTS
  YOU HAVE 1 DISABLED TEST

Makefile:734: recipe for target 'runtest' failed
make: *** [runtest] Error 1

Anybody know this and have a solution?

Ubuntu 16.04
Python 2.7.12
Intel-caffe

**Comment by Noiredd** [comment]
Please do not post usage, installation, or modeling questions, or other requests for help to Issues. Use the [caffe-users list][1] instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe. Please read the [guidelines for contributing][2] before submitting an issue or a pull request.

Also, consider posting the issue to Intel's repository for Caffe, as it does not seem to be related with the master build.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
