### ISSUE TITLE
CMake Error: The source directory "D:/caffe/caffe/build/Toolkit/CUDA/v8.0" does not exist.

### ISSUE THREAD

**Issue by wuheng199112068** [BVLC/caffe#6118]
When execute scripts\build_win.cmd，a error happend. How to Solve?

**Comment by FinalAgito** [comment]
Check this path Whether it existed.
 : )

**Comment by FinalAgito** [comment]
This  step always try to find the Nivida Tookit in the path, you can check if it have exist or turn off the GPU  
option.

**Comment by wuheng199112068** [comment]
the path is existed and  Nivida Tookit path  is also ture.
why it refers to "D:/projects/caffe/build/Toolkit/CUDA/v8.0"? my default cuda path is in C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0? How solve?

**Comment by FinalAgito** [comment]
-  Maybe you have set this value in the caffe configuration file, Find this value and change to 
“C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0”
- Or, your can change the  Nivida Toolkit default path in your 
**Computer environment variables**

**Comment by wuheng199112068** [comment]
thank！ 
another error!


-- Selecting Windows SDK version  to target Windows 10.0.16299.
CMake Error at CMakeLists.txt:18 (project):
  Failed to run MSBuild command:

    C:/Program Files (x86)/MSBuild/14.0/bin/MSBuild.exe

  to get the value of VCTargetsPath:

    Microsoft (R) 生成引擎版本 14.0.25420.1
    版权所有(C) Microsoft Corporation。保留所有权利。

    生成启动时间为 2017/12/19 23:11:38。
    节点 1 上的项目“D:\caffe\caffe\build\CMakeFiles\3.10.1\VCTargetsPath.vcxproj”(默认目标)。
    C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Platforms\x64\PlatformToolsets\v140\Toolset.targets(36,5): error MSB8036: The Windows SDK version 8.1 was not found. Install the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution". [D:\caffe\caffe\build\CMakeFiles\3.10.1\VCTargetsPath.vcxproj]
    已完成生成项目“D:\caffe\caffe\build\CMakeFiles\3.10.1\VCTargetsPath.vcxproj”(默认目标)的操作 - 失败。

    生成失败。

    “D:\caffe\caffe\build\CMakeFiles\3.10.1\VCTargetsPath.vcxproj”(默认目标) (1) ->
    (Desktop_PlatformPrepareForBuild 目标) ->
      C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Platforms\x64\PlatformToolsets\v140\Toolset.targets(36,5): error MSB8036: The Windows SDK version 8.1 was not found. Install the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution". [D:\caffe\caffe\build\CMakeFiles\3.10.1\VCTargetsPath.vcxproj]
       0 个警告
        1 个错误
    已用时间 00:00:00.47
  Exit code: 1
-- Configuring incomplete, errors occurred!
See also "D:/caffe/caffe/build/CMakeFiles/CMakeOutput.log".

How solve?thank

**Comment by FinalAgito** [comment]
It couldn't find the Win Phone sdk 8.1.
Install it.

**Comment by FinalAgito** [comment]
Please read the logs info and try to search these problem in issue and searching engine, my friends.
They always help you to know how to do.

**Comment by Noiredd** [comment]
Please do not post usage, installation, or modeling questions, or other requests for help to Issues. Use the [caffe-users list][1] instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe. Please read the [guidelines for contributing][2] before submitting an issue or a pull request.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md

**Comment by vishal-noob** [comment]
Stuck with the same error. I have added the environmental variable for CUDA and still this error pops up.

**Comment by algidus** [comment]
For me, changing python version to 3.5 helped (I'm using PYTHON_VERSION=3)
