### ISSUE TITLE
create lmdb error

### ISSUE THREAD

**Issue by Feywell** [BVLC/caffe#6120]
### Issue summary
I want use sh to create lmdb data. But I encounter this questions:
![image](https://user-images.githubusercontent.com/24384298/34189161-28303178-e575-11e7-8632-19e17607269f.png)
```
F1220 09:45:23.233382  5018 db_lmdb.hpp:15] Check failed: mdb_status == 0 (38 vs. 0) Function not implemented
*** Check failure stack trace: ***
    @     0x2b5393ac403d  google::LogMessage::Fail()
    @     0x2b5393ac5cbd  google::LogMessage::SendToLog()
    @     0x2b5393ac3c23  google::LogMessage::Flush()
    @     0x2b5393ac66ee  google::LogMessageFatal::~LogMessageFatal()
    @     0x2b538c7da220  caffe::db::LMDB::Open()
    @           0x407317  main
    @       0x37cf21f92d  (unknown)
    @           0x404699  (unknown)

```

### Your system configuration
Operating system: **Centos 6.4 (Red Hat Enterprise Linux Server release 6.4 (Santiago)**
 )   
Hardware：**High Performance Computing**
Compiler:
CUDA version (if applicable): **8.0**
CUDNN version (if applicable):**5.0**
BLAS: **intel2015 mkl**
Python or MATLAB version (for pycaffe and matcaffe respectively):
**python 2.7.13 （don't use matlab）**
ps： use another gcc 5.4.0 in $HOME/usr/local (without root)

**Comment by Noiredd** [comment]
This issue belongs to the SSD fork of Caffe ([weiliu89/caffe](https://github.com/weiliu89/caffe)) as the error occurs within `convert_annoset.cpp` which does not exist in the master branch.

**Comment by Feywell** [comment]
@Noiredd   Thank you!
I have fix that question. Actually, it's not only the question with SSD fork of Caffe. 
Because of I use cluster, it is happened. I try to change the flags of **$CAFFE_ROOT/src/caffe/util/db_lmdb.cpp**  to **MDB_RDONLY | MDB_NOLOCK**. It is said Lustre filesystem cannot use LOCK .
