### ISSUE TITLE
Can't create layer "data" of type "Input"

### ISSUE THREAD

**Issue by prabhundps** [BVLC/caffe#6126]
I've trained the GoogleNet model on custom datasets and trying to deploy in raspberry pi for image classification.
Following code for image predictions:
_import cv2
net = cv2.dnn.readNetFromCaffe(
'deploy.prototxt',
'cyrrup_googlenet_iter_1110.caffemodel')
frame = cv2.imread('frame.jpg', cv2.IMREAD_GRAYSCALE)
image=cv2.resize(frame, (224, 224))
blob = cv2.dnn.blobFromImage(image,1, (224, 224), (104, 117, 123))
net.setInput(blob)
detections = net.forward()
print(detections)_

The following error I'm getting. _______________________________________________________________________________
**OpenCV Error: Unspecified error (Can't create layer "data" of type "Input") in getLayerInstance, file /home/pi/opencv-3.3.0/modules/dnn/src/dnn.cpp, line 365**
Traceback (most recent call last):
  File "image_detection.py", line 9, in <module>
    detections = net.forward()
**cv2.error: /home/pi/opencv-3.3.0/modules/dnn/src/dnn.cpp:365: error: (-2) Can't create layer "data" of type "Input" in function getLayerInstance**
_________________________________________________________________________________

Will anyone please help me? If required more information I would like to discuss.

Thanks.

**Comment by avinashsingh2** [comment]
I am having the same issue. Did you find the solution for this?

**Comment by prabhundps** [comment]
@avinashsingh2:- Could you please upload your deploy.prototxt file? I've got the solution but still, I haven't solved the issues. Probably upgrading your OpenCV 3.4 might help you to solve this problem.

**Comment by Noiredd** [comment]
Please do not post usage, installation, or modeling questions, or other requests for help to Issues. Use the [caffe-users list][1] instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe. Please read the [guidelines for contributing][2] before submitting an issue or a pull request.

If you decide to post your issue on the users list, please attach the network prototext.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
