### ISSUE TITLE
Can caffe be installed on ubuntu16.04 with CUDA9.0?

### ISSUE THREAD

**Issue by yuhenry** [BVLC/caffe#6135]
### Issue summary
I've seen that "CUDA 8.0 is required on Ubuntu 16.04" in installation tips. But still tried to install Caffe on Ubuntu 16.04 with CUDA 9.0.
When make all/test, it warns that:
 `/usr/bin/ld: warning: libcudart.so.7.5, needed by /usr/local/lib/libopenncv_core.so, may conflict with libcudart.so.8.0`
BTW, OpenCV version is 3.3.0
### Your system configuration
Operating system:Ubuntu16.04
Compiler:Make
CUDA version (if applicable):CUDA 9.0
CUDNN version (if applicable):CUDNN 3
BLAS:ATLAS
Python or MATLAB version (for pycaffe and matcaffe respectively):Python3.5

**Comment by zhangxiaolin5213** [comment]
CUDNN version is too low, recommend cudnn version is cudnn 6.0

**Comment by yuhenry** [comment]
@zhangxiaolin5213 Thank U for reply. I'll try to uprade the cudnn version...
Still want to know anything problem with CUDA9.0. Is its version too high for Ubuntu 16.04?
Have you tested successfully with this configuration? Is it essential to install CUDA8.0 on Ubuntu 16.04?
I'm a freshman in this area. Many thanks!

**Comment by Noiredd** [comment]
It looks like you have two versions of CUDA installed - ld is telling you that it sees two versions of its runtime library. This has been observed before, you might want to consult some existing sources eg. #683, #3787.

I am closing the issue for now (please read the [guidelines for contributing][2] before submitting an issue or a pull request). If you still can't solve it, please open a thread on the [caffe-users list][1].

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
