### ISSUE TITLE
make runtest failed

### ISSUE THREAD

**Issue by srikar8** [BVLC/caffe#6140]
Please use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) for usage, installation, or modeling questions, or other requests for help.
_Do not post such requests to Issues._ Doing so interferes with the development of Caffe.

Please read the [guidelines for contributing](https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md) before submitting this issue.

### Issue summary

[  FAILED  ] 2 tests, listed below:
[  FAILED  ] BatchReindexLayerTest/2.TestGradient, where TypeParam = caffe::GPUDevice<float>
[  FAILED  ] BatchReindexLayerTest/3.TestGradient, where TypeParam = caffe::GPUDevice<double>

 2 FAILED TESTS
Makefile:532: recipe for target 'runtest' failed
make: *** [runtest] Error 1

### Steps to reproduce

If you are having difficulty building Caffe or training a model, please ask the caffe-users mailing list. If you are reporting a build error that seems to be due to a bug in Caffe, please attach your build configuration (either Makefile.config or CMakeCache.txt) and the output of the make (or cmake) command.

### Your system configuration
Operating system: ubuntu 16.04
Compiler: gcc - 5.4
CUDA version (if applicable): V 9.1
CUDNN version (if applicable): cudnn-9.0
BLAS:
Python or MATLAB version (for pycaffe and matcaffe respectively):

**Comment by SCH923** [comment]
same me

**Comment by kongmo** [comment]
same with me

**Comment by SCH923** [comment]
I used docker.
It is a better way.

**Comment by ayooshkathuria** [comment]
I'm getting the same issue as well. 2 of 2121 tests fail. Here's my config:

Ubuntu 16.04 LTS
Quadro K1200
Cuda 9.1
CuDNN v7.0.5

I used Cmake to generate the makefile using the command 

`cmake -D python_version=3 ..`

Have these errors resulted in problems in day to day use of Caffe for you so far?

**Comment by Noiredd** [comment]
This has been given some more explanation in #6164 - please follow that issue instead. I will close this one in its favor.
