### ISSUE TITLE
 Could not find url for MSVC version = 1900 and Python version = 3.6.

### ISSUE THREAD

**Issue by amudha1** [BVLC/caffe#6144]
Please use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) for usage, installation, or modeling questions, or other requests for help.
_Do not post such requests to Issues._ Doing so interferes with the development of Caffe.

Please read the [guidelines for contributing](https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md) before submitting this issue.

### Steps to reproduce

If you are having difficulty building Caffe or training a model, please ask the caffe-users mailing list. If you are reporting a build error that seems to be due to a bug in Caffe, please attach your build configuration (either Makefile.config or CMakeCache.txt) and the output of the make (or cmake) command.

### Your system configuration
Operating system:
Compiler:
CUDA version (if applicable):
CUDNN version (if applicable):
BLAS:
Python or MATLAB version (for pycaffe and matcaffe respectively):

**Comment by amudha1** [comment]
As I had the following error
 Could not find url for MSVC version = 1900 and Python version = 3.6.
To solve this ,
I created a new environment in anaconda ,with python 2.7 ,however even  when  i am  in this environment i still get the same error.Not able to understand why does it still have  to use 3.6.:(

**Comment by cianhwang** [comment]
Try this: activate root and degrade python to 3.5

**Comment by TinusChen** [comment]
only 2.7 and 3.5 are supported.
You should change python to 3.5
