### ISSUE TITLE
Check failed: data_ in blob.cpp: 103

### ISSUE THREAD

**Issue by lutein** [BVLC/caffe#6145]
I installed caffe to use fast-rcnn to train data in Pascal VOC dataset. How does this happen? Does anyone encounter the same problem?
```shell
minty@minty:~/fast-rcnn$ ./tools/train_net.py --gpu 0 --solver models/VGG16/solver.prototxt --weights data/fast_rcnn_models/vgg16_fast_rcnn_iter_40000.caffemodel
F0101 18:11:58.348556 20203 blob.cpp:103] Check failed: data_ 
*** Check failure stack trace: ***
```

**Comment by shaibagon** [comment]
Please use the [caffe-users list][1] for usage, installation, or modeling questions, or other requests for help.
You may also post questions on [stackoverflow][3], make sure you tag them with `caffe` tag.  
There is also [caffe.help][4] documenting the different layers of caffe.
Do not post such requests to Issues. Doing so interferes with the development of Caffe.

Please read the [guidelines for contributing][2] before submitting this issue.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
 [3]: http://stackoverflow.com/questions/tagged/caffe
 [4]: http://caffe.help/manual/layers.html

**Comment by Truthuleave** [comment]
Hello? I have the same issue with you.Do you get any solutions for this error?
