### ISSUE TITLE
How to deal with that data do not belongs to any of existed classes in model when use softmax to classify

### ISSUE THREAD

**Issue by 139419qw** [BVLC/caffe#6147]
Hello guys, I'm thinking about that in test phase, if test data don't belongs to any of existed classes in model, the output would be incorrect. 
I tried to modify the num_output = num_output+1, intends to create a "dummy" class to contain this kind of data which belongs to non-classes. But it didn't work.
Can anyone please tell me how to solve this problem?

**Comment by fengpingbaustem** [comment]
I met the same question with you. I googled that how to add an unknown class in caffe, but got no answer. I noticed some of them said to adjust the threshold of the prob layer, but  I found sometimes the prob of the unknown class is quite high(>0.9, even reached 1). :-(

**Comment by 139419qw** [comment]
@fengpingbaustem Yeah, I'm also found this situation (that non-classes data could be very high). But I also found this paper:
https://arxiv.org/abs/1511.03719 maybe help to solve this problem.

**Comment by Noiredd** [comment]
Please do not post usage, installation, or **modeling** questions, or other requests for help to Issues. Use the [caffe-users list][1] instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe. Please read the [guidelines for contributing][2] before submitting an issue or a pull request.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
