### ISSUE TITLE
Error in layer_factory.hpp during compilation

### ISSUE THREAD

**Issue by thestrawh8** [BVLC/caffe#6154]
Hi,
     thanks for spending your time in helping us, make matcaffe , make pycaffe everything was successful but when I tried to run a Matlab code which was using caffe net I am facing this issue. I am unable to trace out what's the cause of this problem. And also this was resulting in mex file stack trace error and MATLAB crashes.  

I0107 23:04:16.703588 19569 layer_factory.hpp:77] Creating layer indSub_data_6_split
I0107 23:04:16.703595 19569 net.cpp:84] Creating Layer indSub_data_6_split
I0107 23:04:16.703600 19569 net.cpp:406] indSub_data_6_split <- indSub
I0107 23:04:16.703610 19569 net.cpp:380] indSub_data_6_split -> indSub_data_6_split_0
I0107 23:04:16.703619 19569 net.cpp:380] indSub_data_6_split -> indSub_data_6_split_1
I0107 23:04:16.703629 19569 net.cpp:380] indSub_data_6_split -> indSub_data_6_split_2
I0107 23:04:16.703639 19569 net.cpp:380] indSub_data_6_split -> indSub_data_6_split_3
I0107 23:04:16.703649 19569 net.cpp:380] indSub_data_6_split -> indSub_data_6_split_4
I0107 23:04:16.703657 19569 net.cpp:380] indSub_data_6_split -> indSub_data_6_split_5
I0107 23:04:16.703666 19569 net.cpp:380] indSub_data_6_split -> indSub_data_6_split_6
I0107 23:04:16.703677 19569 net.cpp:122] Setting up indSub_data_6_split
I0107 23:04:16.703683 19569 net.cpp:129] Top shape: 1 34 (34)
I0107 23:04:16.703691 19569 net.cpp:129] Top shape: 1 34 (34)
I0107 23:04:16.703697 19569 net.cpp:129] Top shape: 1 34 (34)
I0107 23:04:16.703703 19569 net.cpp:129] Top shape: 1 34 (34)
I0107 23:04:16.703709 19569 net.cpp:129] Top shape: 1 34 (34)
I0107 23:04:16.703716 19569 net.cpp:129] Top shape: 1 34 (34)
I0107 23:04:16.703722 19569 net.cpp:129] Top shape: 1 34 (34)
I0107 23:04:16.703727 19569 net.cpp:137] Memory required for data: 880282368
I0107 23:04:16.703732 19569 layer_factory.hpp:77] Creating layer Pose0LL1
F0107 23:04:16.703752 19569 layer_factory.hpp:81] Check failed: registry.count(type) == 1 (0 vs. 1) Unknown layer type: Pose (known types: AbsVal, Accuracy, ArgMax, BNLL, BatchNorm, BatchReindex, Bias, Concat, ContrastiveLoss, Convolution, Crop, Data, Deconvolution, Dropout, DummyData, ELU, Eltwise, Embed, EuclideanLoss, Exp, Filter, Flatten, HDF5Data, HDF5Output, HingeLoss, Im2col, ImageData, InfogainLoss, InnerProduct, Input, LRN, LSTM, LSTMUnit, Log, MVN, MemoryData, MultinomialLogisticLoss, PReLU, Parameter, Pooling, Power, Python, RNN, ReLU, Reduction, Reshape, SPP, Scale, Sigmoid, SigmoidCrossEntropyLoss, Silence, Slice, Softmax, SoftmaxWithLoss, Split, TanH, Threshold, Tile, WindowData)
*** Check failure stack trace: ***

**mex-file error**

Abnormal termination:
abort()

Register State (from fault):
  RAX = 0000000000000000  RBX = 00007f1ba4250420
  RCX = 00007f1c800e9428  RDX = 0000000000000006
  RSP = 00007f1c62721668  RBP = 00007f1c62721940
  RSI = 0000000000004c71  RDI = 0000000000004c47

   R8 = 0000000000000081   R9 = 00007f1ba4250440
  R10 = 0000000000000008  R11 = 0000000000000206
  R12 = 00007f1ba4250480  R13 = 00000000000002bf
  R14 = 00007f1ba4250420  R15 = 00007f1ba4257de0

  RIP = 00007f1c800e9428  EFL = 0000000000000206

   CS = 0033   FS = 0000   GS = 0000

Stack Trace (from fault):
[  0] 0x00007f1c800e9428                    /lib/x86_64-linux-gnu/libc.so.6+00218152 gsignal+00000056
[  1] 0x00007f1c800eb02a                    /lib/x86_64-linux-gnu/libc.so.6+00225322 abort+00000362
[  2] 0x00007f1ba403be49             /usr/lib/x86_64-linux-gnu/libglog.so.0+00040521
[  3] 0x00007f1ba403d5cd             /usr/lib/x86_64-linux-gnu/libglog.so.0+00046541
[  4] 0x00007f1ba403f433             /usr/lib/x86_64-linux-gnu/libglog.so.0+00054323 _ZN6google10LogMessage9SendToLogEv+00000643
[  5] 0x00007f1ba403d15b             /usr/lib/x86_64-linux-gnu/libglog.so.0+00045403 _ZN6google10LogMessage5FlushEv+00000187
[  6] 0x00007f1ba403fe1e             /usr/lib/x86_64-linux-gnu/libglog.so.0+00056862 _ZN6google15LogMessageFatalD2Ev+00000014
[  7] 0x00007f1bab13de9c /home/ace-luffy/caffe/matlab/+caffe/private/caffe_.mexa64+02379420
[  8] 0x00007f1bab13fe20 /home/ace-luffy/caffe/matlab/+caffe/private/caffe_.mexa64+02387488
[  9] 0x00007f1baaf40d77 /home/ace-luffy/caffe/matlab/+caffe/private/caffe_.mexa64+00294263
[ 10] 0x00007f1baaf40fef /home/ace-luffy/caffe/matlab/+caffe/private/caffe_.mexa64+00294895 mexFunction+00000169
[ 11] 0x00007f1c6f6e7caa     /usr/local/MATLAB/R2016b/bin/glnxa64/libmex.so+00175274 mexRunMexFile+00000106
[ 12] 0x00007f1c6f6e01a3     /usr/local/MATLAB/R2016b/bin/glnxa64/libmex.so+00143779
[ 13] 0x00007f1c6f6e1345     /usr/local/MATLAB/R2016b/bin/glnxa64/libmex.so+00148293
[ 14] 0x00007f1c6e9e08a3 /usr/local/MATLAB/R2016b/bin/glnxa64/libmwm_dispatcher.so+00768163 _ZN8Mfh_file16dispatch_fh_implEMS_FviPP11mxArray_tagiS2_EiS2_iS2_+00000947
[ 15] 0x00007f1c6e9e116e /usr/local/MATLAB/R2016b/bin/glnxa64/libmwm_dispatcher.so+00770414 _ZN8Mfh_file11dispatch_fhEiPP11mxArray_tagiS2_+00000030
[ 16] 0x00007f1c6b81b847 /usr/local/MATLAB/R2016b/bin/glnxa64/libmwm_lxe.so+11675719
[ 17] 0x00007f1c6b81baab /usr/local/MATLAB/R2016b/bin/glnxa64/libmwm_lxe.so+11676331
[ 18] 0x00007f1c6b881411 /usr/local/MATLAB/R2016b/bin/glnxa64/libmwm_lxe.so+12092433
[ 19] 0x00007f1c6b1a7930 /usr/local/MATLAB/R2016b/bin/glnxa64/libmwm_lxe.so+04909360
[ 20] 0x00007f1c6b1a9c3c /usr/local/MATLAB/R2016b/bin/glnxa64/libmwm_lxe.so+04918332
[ 21] 0x00007f1c6b1a6410 /usr/local/MATLAB/R2016b/bin/glnxa64/libmwm_lxe.so+04903952
[ 22] 0x00007f1c6b1a1855 /usr/local/MATLAB/R2016b/bin/glnxa64/libmwm_lxe.so+04884565
[ 23] 0x00007f1c6b1a1b69 /usr/local/MATLAB/R2016b/bin/glnxa64/libmwm_lxe.so+04885353
[ 24] 0x00007f1c6b1a620d /usr/local/MATLAB/R2016b/bin/glnxa64/libmwm_lxe.so+04903437
[ 25] 0x00007f1c6b1a62e2 /usr/local/MATLAB/R2016b/bin/glnxa64/libmwm_lxe.so+04903650
[ 26] 0x00007f1c6b29d688 /usr/local/MATLAB/R2016b/bin/glnxa64/libmwm_lxe.so+05916296
[ 27] 0x00007f1c6b29fb2f /usr/local/MATLAB/R2016b/bin/glnxa64/libmwm_lxe.so+05925679
[ 28] 0x00007f1c6b71e10e /usr/local/MATLAB/R2016b/bin/glnxa64/libmwm_lxe.so+10637582
[ 29] 0x00007f1c6b80cb60 /usr/local/MATLAB/R2016b/bin/glnxa64/libmwm_lxe.so+11615072
[ 30] 0x00007f1c6e9e08a3 /usr/local/MATLAB/R2016b/bin/glnxa64/libmwm_dispatcher.so+00768163 _ZN8Mfh_file16dispatch_fh_implEMS_FviPP11mxArray_tagiS2_EiS2_iS2_+00000947
[ 31] 0x00007f1c6e9e116e /usr/local/MATLAB/R2016b/bin/glnxa64/libmwm_dispatcher.so+00770414 _ZN8Mfh_file11dispatch_fhEiPP11mxArray_tagiS2_+00000030
[ 32] 0x00007f1c60e78337 /usr/local/MATLAB/R2016b/bin/glnxa64/libmwmcos_impl.so+02097975
[ 33] 0x00007f1c60e8cc09 /usr/local/MATLAB/R2016b/bin/glnxa64/libmwmcos_impl.so+02182153
[ 34] 0x00007f1c60e8d68d /usr/local/MATLAB/R2016b/bin/glnxa64/libmwmcos_impl.so+02184845
[ 35] 0x00007f1c60e946c6 /usr/local/MATLAB/R2016b/bin/glnxa64/libmwmcos_impl.so+02213574
[ 36] 0x00007f1c60e11643 /usr/local/MATLAB/R2016b/bin/glnxa64/libmwmcos_impl.so+01676867
[ 37] 0x00007f1c60e11b6b /usr/local/MATLAB/R2016b/bin/glnxa64/libmwmcos_impl.so+01678187
[ 38] 0x00007f1c60e1381b /usr/local/MATLAB/R2016b/bin/glnxa64/libmwmcos_impl.so+01685531
[ 39] 0x00007f1c60e1a077 /usr/local/MATLAB/R2016b/bin/glnxa64/libmwmcos_impl.so+01712247
[ 40] 0x00007f1c60e106c8 /usr/local/MATLAB/R2016b/bin/glnxa64/libmwmcos_impl.so+01672904
[ 41] 0x00007f1c60e1096c /usr/local/MATLAB/R2016b/bin/glnxa64/libmwmcos_impl.so+01673580
[ 42] 0x00007f1c60e1113c /usr/local/MATLAB/R2016b/bin/glnxa64/libmwmcos_impl.so+01675580
[ 43] 0x00007f1c60e1143d /usr/local/MATLAB/R2016b/bin/glnxa64/libmwmcos_impl.so+01676349
[ 44] 0x00007f1c60e9ffb2 /usr/local/MATLAB/R2016b/bin/glnxa64/libmwmcos_impl.so+02260914
[ 45] 0x00007f1c60f2edd0 /usr/local/MATLAB/R2016b/bin/glnxa64/libmwmcos_impl.so+02846160
[ 46] 0x00007f1c6e976878 /usr/local/MATLAB/R2016b/bin/glnxa64/libmwm_dispatcher.so+00333944 _ZN13Mfh_MATLAB_fn11dispatch_fhEiPP11mxArray_tagiS2_+00000616
[ 47] 0x00007f1c60f2fcde /usr/local/MATLAB/R2016b/bin/glnxa64/libmwmcos_impl.so+02850014
[ 48] 0x00007f1c6b817412 /usr/local/MATLAB/R2016b/bin/glnxa64/libmwm_lxe.so+11658258
[ 49] 0x00007f1c684c576b /usr/local/MATLAB/R2016b/bin/glnxa64/libmwlxeindexing.so+00403307
[ 50] 0x00007f1c6850e260 /usr/local/MATLAB/R2016b/bin/glnxa64/libmwlxeindexing.so+00701024
[ 51] 0x00007f1c6850d7b4 /usr/local/MATLAB/R2016b/bin/glnxa64/libmwlxeindexing.so+00698292
[ 52] 0x00007f1c684d4900 /usr/local/MATLAB/R2016b/bin/glnxa64/libmwlxeindexing.so+00465152
[ 53] 0x00007f1c684da910 /usr/local/MATLAB/R2016b/bin/glnxa64/libmwlxeindexing.so+00489744 _ZN9MathWorks3lxe9at_rparenEPvNS_2ts4TypeEPKvS1_S1_+00000224
[ 54] 0x00007f1c6b8815f1 /usr/local/MATLAB/R2016b/bin/glnxa64/libmwm_lxe.so+12092913
[ 55] 0x00007f1c6b1a7930 /usr/local/MATLAB/R2016b/bin/glnxa64/libmwm_lxe.so+04909360
[ 56] 0x00007f1c6b1a9c3c /usr/local/MATLAB/R2016b/bin/glnxa64/libmwm_lxe.so+04918332
[ 57] 0x00007f1c6b1a6410 /usr/local/MATLAB/R2016b/bin/glnxa64/libmwm_lxe.so+04903952
[ 58] 0x00007f1c6b1a1855 /usr/local/MATLAB/R2016b/bin/glnxa64/libmwm_lxe.so+04884565
[ 59] 0x00007f1c6b1a1b69 /usr/local/MATLAB/R2016b/bin/glnxa64/libmwm_lxe.so+04885353
[ 60] 0x00007f1c6b1a620d /usr/local/MATLAB/R2016b/bin/glnxa64/libmwm_lxe.so+04903437
[ 61] 0x00007f1c6b1a62e2 /usr/local/MATLAB/R2016b/bin/glnxa64/libmwm_lxe.so+04903650
[ 62] 0x00007f1c6b29d688 /usr/local/MATLAB/R2016b/bin/glnxa64/libmwm_lxe.so+05916296
[ 63] 0x00007f1c6b29fb2f /usr/local/MATLAB/R2016b/bin/glnxa64/libmwm_lxe.so+05925679
[ 64] 0x00007f1c6b71e10e /usr/local/MATLAB/R2016b/bin/glnxa64/libmwm_lxe.so+10637582
[ 65] 0x00007f1c6b80de33 /usr/local/MATLAB/R2016b/bin/glnxa64/libmwm_lxe.so+11619891
[ 66] 0x00007f1c6e9e08a3 /usr/local/MATLAB/R2016b/bin/glnxa64/libmwm_dispatcher.so+00768163 _ZN8Mfh_file16dispatch_fh_implEMS_FviPP11mxArray_tagiS2_EiS2_iS2_+00000947
[ 67] 0x00007f1c6e9e116e /usr/local/MATLAB/R2016b/bin/glnxa64/libmwm_dispatcher.so+00770414 _ZN8Mfh_file11dispatch_fhEiPP11mxArray_tagiS2_+00000030
[ 68] 0x00007f1c6b81b847 /usr/local/MATLAB/R2016b/bin/glnxa64/libmwm_lxe.so+11675719
[ 69] 0x00007f1c6b81baab /usr/local/MATLAB/R2016b/bin/glnxa64/libmwm_lxe.so+11676331
[ 70] 0x00007f1c6b881461 /usr/local/MATLAB/R2016b/bin/glnxa64/libmwm_lxe.so+12092513
[ 71] 0x00007f1c6b1a7930 /usr/local/MATLAB/R2016b/bin/glnxa64/libmwm_lxe.so+04909360
[ 72] 0x00007f1c6b1a9c3c /usr/local/MATLAB/R2016b/bin/glnxa64/libmwm_lxe.so+04918332
[ 73] 0x00007f1c6b1a6410 /usr/local/MATLAB/R2016b/bin/glnxa64/libmwm_lxe.so+04903952
[ 74] 0x00007f1c6b1a1855 /usr/local/MATLAB/R2016b/bin/glnxa64/libmwm_lxe.so+04884565
[ 75] 0x00007f1c6b1a1b69 /usr/local/MATLAB/R2016b/bin/glnxa64/libmwm_lxe.so+04885353
[ 76] 0x00007f1c6b1a620d /usr/local/MATLAB/R2016b/bin/glnxa64/libmwm_lxe.so+04903437
[ 77] 0x00007f1c6b1a62e2 /usr/local/MATLAB/R2016b/bin/glnxa64/libmwm_lxe.so+04903650
[ 78] 0x00007f1c6b29d688 /usr/local/MATLAB/R2016b/bin/glnxa64/libmwm_lxe.so+05916296
[ 79] 0x00007f1c6b29fb2f /usr/local/MATLAB/R2016b/bin/glnxa64/libmwm_lxe.so+05925679
[ 80] 0x00007f1c6b71e10e /usr/local/MATLAB/R2016b/bin/glnxa64/libmwm_lxe.so+10637582
[ 81] 0x00007f1c6b6e5eab /usr/local/MATLAB/R2016b/bin/glnxa64/libmwm_lxe.so+10407595
[ 82] 0x00007f1c6b6e5fb3 /usr/local/MATLAB/R2016b/bin/glnxa64/libmwm_lxe.so+10407859
[ 83] 0x00007f1c6b6e80d9 /usr/local/MATLAB/R2016b/bin/glnxa64/libmwm_lxe.so+10416345
[ 84] 0x00007f1c6b760bbe /usr/local/MATLAB/R2016b/bin/glnxa64/libmwm_lxe.so+10910654
[ 85] 0x00007f1c6b760f4a /usr/local/MATLAB/R2016b/bin/glnxa64/libmwm_lxe.so+10911562
[ 86] 0x00007f1c6dc853db /usr/local/MATLAB/R2016b/bin/glnxa64/libmwbridge.so+00189403
[ 87] 0x00007f1c6dc8607d /usr/local/MATLAB/R2016b/bin/glnxa64/libmwbridge.so+00192637 _Z8mnParserv+00000829
[ 88] 0x00007f1c6eca2243   /usr/local/MATLAB/R2016b/bin/glnxa64/libmwmcr.so+00537155
[ 89] 0x00007f1c6eca41ce   /usr/local/MATLAB/R2016b/bin/glnxa64/libmwmcr.so+00545230
[ 90] 0x00007f1c6eca4849   /usr/local/MATLAB/R2016b/bin/glnxa64/libmwmcr.so+00546889 _ZN5boost6detail17task_shared_stateINS_3_bi6bind_tIvPFvRKNS_8functionIFvvEEEENS2_5list1INS2_5valueIS6_EEEEEEvE6do_runEv+00000025
[ 91] 0x00007f1c6eca3236   /usr/local/MATLAB/R2016b/bin/glnxa64/libmwmcr.so+00541238
[ 92] 0x00007f1c6f46ab49   /usr/local/MATLAB/R2016b/bin/glnxa64/libmwiqm.so+00863049
[ 93] 0x00007f1c6f45751c   /usr/local/MATLAB/R2016b/bin/glnxa64/libmwiqm.so+00783644 _ZN5boost6detail8function21function_obj_invoker0ISt8functionIFNS_3anyEvEES4_E6invokeERNS1_15function_bufferE+00000028
[ 94] 0x00007f1c6f4571fc   /usr/local/MATLAB/R2016b/bin/glnxa64/libmwiqm.so+00782844 _ZN3iqm18PackagedTaskPlugin7executeEP15inWorkSpace_tagRN5boost10shared_ptrIN14cmddistributor17IIPCompletedEventEEE+00000428
[ 95] 0x00007f1c6f436a0a   /usr/local/MATLAB/R2016b/bin/glnxa64/libmwiqm.so+00649738
[ 96] 0x00007f1c6f422690   /usr/local/MATLAB/R2016b/bin/glnxa64/libmwiqm.so+00566928
[ 97] 0x00007f1c6f425048   /usr/local/MATLAB/R2016b/bin/glnxa64/libmwiqm.so+00577608
[ 98] 0x00007f1c8192240a /usr/local/MATLAB/R2016b/bin/glnxa64/libmwservices.so+02634762
[ 99] 0x00007f1c819239af /usr/local/MATLAB/R2016b/bin/glnxa64/libmwservices.so+02640303
[100] 0x00007f1c819240e6 /usr/local/MATLAB/R2016b/bin/glnxa64/libmwservices.so+02642150 _Z25svWS_ProcessPendingEventsiib+00000102
[101] 0x00007f1c6eca28c6   /usr/local/MATLAB/R2016b/bin/glnxa64/libmwmcr.so+00538822
[102] 0x00007f1c6eca2c42   /usr/local/MATLAB/R2016b/bin/glnxa64/libmwmcr.so+00539714
[103] 0x00007f1c6ec908d6   /usr/local/MATLAB/R2016b/bin/glnxa64/libmwmcr.so+00465110
[104] 0x00007f1c804856ba              /lib/x86_64-linux-gnu/libpthread.so.0+00030394
[105] 0x00007f1c801bb3dd                    /lib/x86_64-linux-gnu/libc.so.6+01078237 clone+00000109
[106] 0x0000000000000000                                   <unknown-module>+00000000

This error was detected while a MEX-file was running. If the MEX-file
is not an official MathWorks function, please examine its source code
for errors. Please consult the External Interfaces Guide for information
on debugging MEX-files.

Please use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) for usage, installation, or modeling questions, or other requests for help.
_Do not post such requests to Issues._ Doing so interferes with the development of Caffe.

Please read the [guidelines for contributing](https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md) before submitting this issue.

### Steps to reproduce

If you are having difficulty building Caffe or training a model, please ask the caffe-users mailing list. If you are reporting a build error that seems to be due to a bug in Caffe, please attach your build configuration (either Makefile.config or CMakeCache.txt) and the output of the make (or cmake) command.

### Your system configuration
Operating system: Ubuntu 16.04
Compiler:gcc-5,
CUDA version (if applicable): 8.0
CUDNN version (if applicable):5.1
BLAS:
Python or MATLAB version (for pycaffe and matcaffe respectively): Matlab version 2016b

**Comment by gangooteli** [comment]
I also had lot of problems while doing setup for GPU. Wasted around three weeks. Then figured out a way to do setup in an easy way using docker.

You can look at this blog which I wrote just in case want simple installation of caffe in docker.
https://medium.com/@gangooteli/ultimate-guide-to-installing-caffe-gpu-in-3-simple-steps-bde36c52e38f
Please also let me know if this is any help to you.
Though this does not include installation of Matlab version.

**Comment by Noiredd** [comment]
There is no such layer as "Pose" in Caffe - that's where the error comes from. Perhaps you are using some special network which should come with a dedicated fork?

If you need assistance, please open a thread on [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) and give us some more info (what network are you trying to run? consider attaching the prototext).

**Comment by thestrawh8** [comment]
Thanks for clearing this for me I was unsure if it was from caffe's net or from the model's code which I was trying to use
