### ISSUE TITLE
Building Caffe on Ubuntu 16.04 fails.

### ISSUE THREAD

**Issue by gautamkmr** [BVLC/caffe#6156]
I am trying to install Caffe on Ubuntu 16.04  with Cuda 8.
I am using the following version
          "gcc": "4.8.5",
          "libgcc": "5.2.0",
          "lmdb": "0.9.21",
          "leveldb": "1.20"

../lib/libcaffe.so.1.0.0: undefined reference to `leveldb::DB::Open(leveldb::Options const&, std::string const&, leveldb::DB**)'
../lib/libcaffe.so.1.0.0: undefined reference to `leveldb::Status::ToString() const'

Can some one help me to fix this ?

**Comment by gangooteli** [comment]
I also had lot of problems while doing setup for gpu. Wasted around three weeks. Then figured out a way to do setup in an easy way using docker.

You can look at this blog which I wrote just in case want simple installation of caffe in docker.
https://medium.com/@gangooteli/ultimate-guide-to-installing-caffe-gpu-in-3-simple-steps-bde36c52e38f
Please also let me know if this is any help to you

**Comment by Noiredd** [comment]
Cannot reproduce the behavior. Perhaps you forgot to install `leveldb`? Consult the [Ubuntu 16.04 Installation Guide](https://github.com/BVLC/caffe/wiki/Ubuntu-16.04-Installation-Guide). In case the issue persists, please post on the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
