### ISSUE TITLE
Caffe error out of memory and only use 3g of memory.

### ISSUE THREAD

**Issue by kyuhyong** [BVLC/caffe#6160]
### Issue summary
Trying to train CNN with 12000 images with all 227x227 size packed in a 21Gig LMDB file.
The batch size is set to 256 and output batch is set to 50
my system is
os: ubuntu 16.04
cpu: Intel i7 4720 @2.6GHz x8
gpu: GTX980M
ram: 16G
With whatever settings, I get following error and stop.

> I0110 09:00:43.417537 19353 data_layer.cpp:45] output data size: 50,3,227,227
> I0110 09:00:43.457173 19353 net.cpp:122] Setting up data
> I0110 09:00:43.457209 19353 net.cpp:129] Top shape: 50 3 227 227 (7729350)
> I0110 09:00:43.457216 19353 net.cpp:129] Top shape: 50 (50)
> I0110 09:00:43.457217 19353 net.cpp:137] Memory required for data: 30917600
> I0110 09:00:43.457223 19353 layer_factory.hpp:77] Creating layer label_data_1_split
> ...
> I0110 09:01:31.314333 19353 sgd_solver.cpp:105] Iteration 0, lr = 0.001
> F0110 09:01:31.320479 19353 syncedmem.cpp:71] Check failed: error == cudaSuccess (2 vs. 0)  out of memory
> 

Weird problem is that while monitoring the system with ubuntu system monitor, the memory usage never exceed 3Gig of memory when 16 gig memory + 4gig of gpu memory exist. 
Any help would be much appreciated.

### Steps to reproduce

If you are having difficulty building Caffe or training a model, please ask the caffe-users mailing list. If you are reporting a build error that seems to be due to a bug in Caffe, please attach your build configuration (either Makefile.config or CMakeCache.txt) and the output of the make (or cmake) command.

### Your system configuration
Operating system: ubuntu 16.04
Compiler:gcc
CUDA version (if applicable):8.0
CUDNN version (if applicable):7.0
BLAS: atlas 3.10.2-9
Python or MATLAB version (for pycaffe and matcaffe respectively): 2.7

**Comment by lubagov** [comment]
This is VRAM.... Same situation....

Before i try use DLib framework, and when train network in GPU Nvidia GT1030 (2GB VRAM), batch size was 20 images. and it working. Now i try train ResNet34 (same network) in Caffe, maximal batch size i have 9 images. Next i gave this error. And while i don't know why...
Try to set batch size to 20, it should work.
