### ISSUE TITLE
ImportError: cannot import name '_hough_circle'

### ISSUE THREAD

**Issue by AliceDinh** [BVLC/caffe#6161]
### Issue summary
ImportError: cannot import name '_hough_circle'
### Your system configuration
Operating system: Window 10 64 bit
Compiler: Python 3.5.4
CUDA version (if applicable): nope
CUDNN version (if applicable): nope

**Comment by Noiredd** [comment]
Please do not post usage, installation, or modeling questions, or other requests for help to Issues. Use the [caffe-users list][1] instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe. Please read the [guidelines for contributing][2] before submitting an issue or a pull request.

If you feel like opening a thread on caffe-users, please post more information about the error. Just the last line from the log is not enough for us to help you.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
