### ISSUE TITLE
Nvida 1080, CUDA 8, Ubuntu 16.04 make issue

### ISSUE THREAD

**Issue by PrinceP** [BVLC/caffe#6163]
Please use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) for usage, installation, or modeling questions, or other requests for help.
_Do not post such requests to Issues._ Doing so interferes with the development of Caffe.

Please read the [guidelines for contributing](https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md) before submitting this issue.

### Issue summary
CUDA 8.0
Ubuntu 16.04
Nvidia 1080
Alienware 
https://github.com/BVLC/caffe/wiki/GeForce-GTX-1080,---CUDA-8.0,---Ubuntu-16.04,---Caffe

### Steps to reproduce

make all -j8

### Your system configuration
Operating system: Ubuntu 16.04
CUDA version 8.0
.build_release/src/caffe/proto/caffe.pb.h: In member function ‘void caffe::ReshapeParameter::set_allocated_shape(caffe::BlobShape*)’:
.build_release/src/caffe/proto/caffe.pb.h:23893:15: error: ‘GetOwnedMessage’ is not a member of ‘google::protobuf::internal’
       shape = ::google::protobuf::internal::GetOwnedMessage(
               ^
.build_release/src/caffe/proto/caffe.pb.h: In member function ‘bool caffe::ReshapeParameter::has_axis() const’:
.build_release/src/caffe/proto/caffe.pb.h:23906:11: error: ‘_has_bits_’ was not declared in this scope
   return (_has_bits_[0] & 0x00000002u) != 0;
           ^
.build_release/src/caffe/proto/caffe.pb.h: In member function ‘void caffe::ReshapeParameter::set_has_axis()’:
.build_release/src/caffe/proto/caffe.pb.h:23909:3: error: ‘_has_bits_’ was not declared in this scope
   _has_bits_[0] |= 0x00000002u;
   ^
.build_release/src/caffe/proto/caffe.pb.h: In member function ‘void caffe::ReshapeParameter::clear_has_axis()’:
.build_release/src/caffe/proto/caffe.pb.h:23912:3: error: ‘_has_bits_’ was not declared in this scope
   _has_bits_[0] &= ~0x00000002u;
   ^
.build_release/src/caffe/proto/caffe.pb.h: In member function ‘bool caffe::ReshapeParameter::has_num_axes() const’:
.build_release/src/caffe/proto/caffe.pb.h:23930:11: error: ‘_has_bits_’ was not declared in this scope
   return (_has_bits_[0] & 0x00000004u) != 0;
           ^
.build_release/src/caffe/proto/caffe.pb.h: In member function ‘void caffe::ReshapeParameter::set_has_num_axes()’:
.build_release/src/caffe/proto/caffe.pb.h:23933:3: error: ‘_has_bits_’ was not declared in this scope
   _has_bits_[0] |= 0x00000004u;
   ^
.build_release/src/caffe/proto/caffe.pb.h: In member function ‘void caffe::ReshapeParameter::clear_has_num_axes()’:
.build_release/src/caffe/proto/caffe.pb.h:23936:3: error: ‘_has_bits_’ was not declared in this scope
   _has_bits_[0] &= ~0x00000004u;
   ^
.build_release/src/caffe/proto/caffe.pb.h: In member function ‘bool caffe::ScaleParameter::has_axis() const’:
.build_release/src/caffe/proto/caffe.pb.h:23958:11: error: ‘_has_bits_’ was not declared in this scope
   return (_has_bits_[0] & 0x00000008u) != 0;
           ^
.build_release/src/caffe/proto/caffe.pb.h: In member function ‘void caffe::ScaleParameter::set_has_axis()’:
.build_release/src/caffe/proto/caffe.pb.h:23961:3: error: ‘_has_bits_’ was not declared in this scope
   _has_bits_[0] |= 0x00000008u;
   ^
.build_release/src/caffe/proto/caffe.pb.h: In member function ‘void caffe::ScaleParameter::clear_has_axis()’:
.build_release/src/caffe/proto/caffe.pb.h:23964:3: error: ‘_has_bits_’ was not declared in this scope
   _has_bits_[0] &= ~0x00000008u;
   ^
.build_release/src/caffe/proto/caffe.pb.h: In member function ‘bool caffe::ScaleParameter::has_num_axes() const’:
.build_release/src/caffe/proto/caffe.pb.h:23982:11: error: ‘_has_bits_’ was not declared in this scope
   return (_has_bits_[0] & 0x00000010u) != 0;
           ^
.build_release/src/caffe/proto/caffe.pb.h: In member function ‘void caffe::ScaleParameter::set_has_num_axes()’:
.build_release/src/caffe/proto/caffe.pb.h:23985:3: error: ‘_has_bits_’ was not declared in this scope
   _has_bits_[0] |= 0x00000010u;
   ^
.build_release/src/caffe/proto/caffe.pb.h: In member function ‘void caffe::ScaleParameter::clear_has_num_axes()’:
.build_release/src/caffe/proto/caffe.pb.h:23988:3: error: ‘_has_bits_’ was not declared in this scope
   _has_bits_[0] &= ~0x00000010u;
   ^
.build_release/src/caffe/proto/caffe.pb.h: In member function ‘bool caffe::ScaleParameter::has_filler() const’:
.build_release/src/caffe/proto/caffe.pb.h:24006:11: error: ‘_has_bits_’ was not declared in this scope
   return (_has_bits_[0] & 0x00000001u) != 0;
           ^
.build_release/src/caffe/proto/caffe.pb.h: In member function ‘void caffe::ScaleParameter::set_has_filler()’:
.build_release/src/caffe/proto/caffe.pb.h:24009:3: error: ‘_has_bits_’ was not declared in this scope
   _has_bits_[0] |= 0x00000001u;
   ^
.build_release/src/caffe/proto/caffe.pb.h: In member function ‘void caffe::ScaleParameter::clear_has_filler()’:
.build_release/src/caffe/proto/caffe.pb.h:24012:3: error: ‘_has_bits_’ was not declared in this scope
   _has_bits_[0] &= ~0x00000001u;
   ^
.build_release/src/caffe/proto/caffe.pb.h: In member function ‘void caffe::ScaleParameter::set_allocated_filler(caffe::FillerParameter*)’:
.build_release/src/caffe/proto/caffe.pb.h:24048:16: error: ‘GetOwnedMessage’ is not a member of ‘google::protobuf::internal’
       filler = ::google::protobuf::internal::GetOwnedMessage(
                ^
.build_release/src/caffe/proto/caffe.pb.h: In member function ‘bool caffe::ScaleParameter::has_bias_term() const’:
.build_release/src/caffe/proto/caffe.pb.h:24061:11: error: ‘_has_bits_’ was not declared in this scope
   return (_has_bits_[0] & 0x00000004u) != 0;
           ^
.build_release/src/caffe/proto/caffe.pb.h: In member function ‘void caffe::ScaleParameter::set_has_bias_term()’:
.build_release/src/caffe/proto/caffe.pb.h:24064:3: error: ‘_has_bits_’ was not declared in this scope
   _has_bits_[0] |= 0x00000004u;
   ^
.build_release/src/caffe/proto/caffe.pb.h: In member function ‘void caffe::ScaleParameter::clear_has_bias_term()’:
.build_release/src/caffe/proto/caffe.pb.h:24067:3: error: ‘_has_bits_’ was not declared in this scope
   _has_bits_[0] &= ~0x00000004u;
   ^
.build_release/src/caffe/proto/caffe.pb.h: In member function ‘bool caffe::ScaleParameter::has_bias_filler() const’:
.build_release/src/caffe/proto/caffe.pb.h:24085:11: error: ‘_has_bits_’ was not declared in this scope
   return (_has_bits_[0] & 0x00000002u) != 0;
           ^
.build_release/src/caffe/proto/caffe.pb.h: In member function ‘void caffe::ScaleParameter::set_has_bias_filler()’:
.build_release/src/caffe/proto/caffe.pb.h:24088:3: error: ‘_has_bits_’ was not declared in this scope
   _has_bits_[0] |= 0x00000002u;
   ^
.build_release/src/caffe/proto/caffe.pb.h: In member function ‘void caffe::ScaleParameter::clear_has_bias_filler()’:
.build_release/src/caffe/proto/caffe.pb.h:24091:3: error: ‘_has_bits_’ was not declared in this scope
   _has_bits_[0] &= ~0x00000002u;
   ^
.build_release/src/caffe/proto/caffe.pb.h: In member function ‘void caffe::ScaleParameter::set_allocated_bias_filler(caffe::FillerParameter*)’:
.build_release/src/caffe/proto/caffe.pb.h:24127:21: error: ‘GetOwnedMessage’ is not a member of ‘google::protobuf::internal’
       bias_filler = ::google::protobuf::internal::GetOwnedMessage(

**Comment by gangooteli** [comment]
You can look at this blog which I wrote just in case want simple installation of caffe in docker.
[https://medium.com/@gangooteli/ultimate-guide-to-installing-caffe-gpu-in-3-simple-steps-bde36c52e38f](url)

**Comment by Noiredd** [comment]
It looks like you don't have `protobuf` installed. There is a wonderful [installation guide](https://github.com/BVLC/caffe/wiki/Ubuntu-16.04-Installation-Guide) for Ubuntu 16.04 - please consult that and post on the google groups with any problems.

Please do not post usage, installation, or modeling questions, or other requests for help to Issues. Use the [caffe-users list][1] instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe. Please read the [guidelines for contributing][2] before submitting an issue or a pull request.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
