### ISSUE TITLE
when I resave the googlenet'  caffemodel , something maybe lost

### ISSUE THREAD

**Issue by WendyDong** [BVLC/caffe#6167]
I want to edit the googlenet'  caffemodel, so I resave it first. here is my python code:
```
net = caffe.Net('../models/bvlc_googlenet/deploy.prototxt', 
                '../models/bvlc_googlenet/bvlc_googlenet.caffemodel', 
                caffe.TRAIN)
net.save('../models/bvlc_googlenet/bvlc_googlenet_test.caffemodel')
```
but googlenet‘s size is 53M  
the model I save was just 28M .Where did I wrong?

**Comment by Noiredd** [comment]
Compare the `deploy.prototxt` (the model you're using to generate the caffemodel) and `train_val.prototxt` (the one used to create the source), for example using the `draw_net.py`. You will find that the deploy net does not have the secondary classifier layers (`loss1...` and `loss2...` layers), only the final `loss3` section. Therefore, those layers are not imported from the original weights file, and are not stored in your output.
