### ISSUE TITLE
 protoc: No such file or directory  when running make all on MAC

### ISSUE THREAD

**Issue by cookyecat** [BVLC/caffe#617]
I followed the instructions to install caffe on mac. But I have got the error while running `make all`.  The error message is :

```
$ make all
protoc --proto_path=src --cpp_out=build/src src/caffe/proto/caffe.proto
make: protoc: No such file or directory
make: *** [build/src/caffe/proto/caffe.pb.cc] Error 1
```

Then I cd the directory , `src/caffe/proto/caffe`, checking if there is caffe.proto. There is. 
I've installed prerequisites. Here is my brew list:

```
$ brew list
arpack      ctags       gmp4        mpfr2       python
boost       gdb             hdf5                openblas            readline
brew-cask   gdbm        isl011      openssl     snappy
cloog018            gflags      leveldb     pkg-config  sqlite
cmake       glog                libmpc08            protobuf             szip
```

Can anyone help me solve this ? Many thanks ~~

**Comment by kerkilchoi** [comment]
@shelhamer I am getting the same error as @Coldmooon despite that I brew installed OpenCV (2.4.10) with the modified formula to build with `libstdc++.` I am currently running Mac OSX Yosemite and buildling Caffe with cuDNN R2 and CUDA 7.0. Could you provide some help?

**Comment by Coldmooon** [comment]
@kerkilchoi, if you are sure you built opencv with `libstdc++`, this error might be due to other dependences built with `libc++`. I've solved this problem by uninstalling all of related dependences and reinstall them. You can run the following command in terminal to quickly uninstall dependences.
`rm -rf /usr/local/Cellar && brew prune ` I refer you to the issue 1740, 1210, 1310, 915, 1212, 1358, 454

**Comment by zarzen** [comment]
I've got the similar problem. I followed the installation instruction, which says that "CUDA 7 is strongly suggested. Older CUDA require libstdc++ while clang++ is the default compiler and libc++ the default standard library on OS X 10.9+. ". So I installed cuda7, by updating from cuda6.5. Then install opencv via `brew install opencv` after `brew tap homebrew/science`.
When I step to compilation, run `make all` at caffe root, I got this error message:
```
No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.
CXX src/caffe/blob.cpp
In file included from src/caffe/blob.cpp:4:
In file included from ./include/caffe/blob.hpp:10:
In file included from ./include/caffe/syncedmem.hpp:7:
In file included from ./include/caffe/util/math_functions.hpp:11:
./include/caffe/util/mkl_alternate.hpp:11:10: fatal error: 'cblas.h' file not found
#include <cblas.h>
         ^
1 error generated.
make: *** [.build_release/src/caffe/blob.o] Error 1
```
I've searched for solution, someone says that `Makefile` should be modified. But seems that solution is out of date.

**Comment by Hiyorimi** [comment]
I'm encountering error

Undefined symbols for architecture x86_64:
  "cv::imread(std::string const&, int)", referenced from:
      caffe::WindowDataLayer<float>::InternalThreadEntry() in window_data_layer.o
      caffe::WindowDataLayer<double>::InternalThreadEntry() in window_data_layer.o

Though all packets were installed with brew

$ brew list:
boost
cmake
eigen
gcc
gflags
glog
gmp
hdf5
ilmbase
isl
jpeg
leveldb
libmpc
libpng
libtiff
lmdb
mpfr
numpy
openblas
opencv
openexr
openssl
protobuf
snappy
szip
wget

**Comment by keltysf** [comment]
In response to the error
```
./include/caffe/util/mkl_alternate.hpp:13:10: fatal error: 'cblas.h' file not  found
#include <cblas.h>
```

I found simply running
```
brew install openblas
```

fixed it for me.

**Comment by christopher5106** [comment]
xcode-select --install did solve the error 'cblas.h' file not found for me

http://christopher5106.github.io/big/data/2015/07/16/deep-learning-install-caffe-cudnn-cuda-for-digits-python-on-mac-osx.html
