### ISSUE TITLE
Python caffe NetSpec Class , Problem with __getattr__ function.

### ISSUE THREAD

**Issue by stavBodik** [BVLC/caffe#6171]
Hello , 

I am using some code which is creating NetSpec Class instance:

//Create train net.
net = caffe.NetSpec()

Now whenever I try to call :

net.keys()

Which must return net.top.keys()

This operation fails, anyone may help me to understand why ?

  File "C:\Anaconda3\lib\site-packages\caffe\net_spec.py", line 180, in __getattr__
    return self.tops[name]
KeyError: 'keys'

I also don't understand this syntax, tops is a dictionary inside NetSpec
Now when calling this function on NetSpec : 

    def __getattr__(self, name):
        return self.tops[name]

name = "keys"

So this is actually asking to return element with the key = "keys"  from tops dictionary ? 

Thanks !

**Comment by shaibagon** [comment]
You do not have any `"top"` named `"keys"`. 

Please use the [caffe-users list][1] for usage, installation, or modeling questions, or other requests for help.
You may also post questions on [stackoverflow][3], make sure you tag them with `caffe` tag.  
There is also [caffe.help][4] documenting the different layers of caffe.
Do not post such requests to Issues. Doing so interferes with the development of Caffe.

Please read the [guidelines for contributing][2] before submitting this issue.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
 [3]: http://stackoverflow.com/questions/tagged/caffe
 [4]: http://caffe.help/manual/layers.html

**Comment by stavBodik** [comment]
But this call :
net.keys()

I see in many implementations.
I don't think "keys" is "top" .... its a away to get pointer to keys list in "tops" dictionary inside  NetSpec class, Am I wrong ?

**Comment by Tveek** [comment]
@stavBodik replace net.keys() by net.tops.keys() .
