### ISSUE TITLE
Error: MDB_INVALID: File is not an LMDB file

### ISSUE THREAD

**Issue by AliceDinh** [BVLC/caffe#6173]
I built caffe successfully in my system and am following the tutorial at:
http://christopher5106.github.io/deep/learning/2015/09/04/Deep-learning-tutorial-on-Caffe-Technology.html
Everything work fine till I load the solver in python:
solver = caffe.get_solver('models/bvlc_reference_caffenet/solver.prototxt')
It raised the error:
```
I0115 10:13:29.053575  8956 layer_factory.cpp:58] Creating layer data
F0115 10:13:29.136234  8956 db_lmdb.hpp:15] Check failed: mdb_status == 0 (-30793 vs. 0) MDB_INVALID: File is not an LMDB file
*** Check failure stack trace: ***
```
**My system:**

- Window 10 64bit
- Python 3.5.4
- Caffe

**Comment by Noiredd** [comment]
Most likely you are passing a wrong path to your LMDB. It would be useful to see your solver.prototxt as well as the network itself. Please open a thread on [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) and attach said files so we can help you troubleshoot the issue.  
I will [close](https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md#issues) this issue now for now.
