### ISSUE TITLE
1300 Warnings

### ISSUE THREAD

**Issue by Yagun** [BVLC/caffe#6182]
Built Caffe with MSVC 14 on Windows, Python 3.5, CUDA 8. Got this message:
1352 Warning(s)
0 Error(s)

Is it all right that there are more than 1000 warnings? Looks scary. Or it is ok?

**Comment by naibaf7** [comment]
Should be OK as long as the runtest and examples run. Otherwise post a few warnings to see what they're about.

**Comment by Noiredd** [comment]
I'll close this due to lack of further activity, but feel free to reopen in case of problems (or better yet, raise a new issue about a specific problem).
