### ISSUE TITLE
OpenCL Caffe - Why does it need to link to pthread

### ISSUE THREAD

**Issue by soulslicer** [BVLC/caffe#6188]
Please use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) for usage, installation, or modeling questions, or other requests for help.
_Do not post such requests to Issues._ Doing so interferes with the development of Caffe.

Please read the [guidelines for contributing](https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md) before submitting this issue.

### Issue summary

I notice that the OpenCL version, if being used by a c++ program, requires pthread to be linked to it. However, pthread is specific to Linux/Unix. Does this mean that OpenCL branch of Caffe cannot be used in Windows?

**Comment by naibaf7** [comment]
@soulslicer No, pthreads is optional (can be used by gtest I think). OpenCL Caffe does indeed work on Windows.
