### ISSUE TITLE
/usr/bin/ld: cannot find -lnccl

### ISSUE THREAD

**Issue by claudiogreco** [BVLC/caffe#6191]
Hello,

when I execute the command "make -j8" in the "caffe" folder, after some time I get the following error:

/usr/bin/ld: cannot find -lnccl
collect2: error: ld returned 1 exit status
Makefile:572: recipe for target '.build_release/lib/libcaffe.so.1.0.0-rc3' failed
make: *** [.build_release/lib/libcaffe.so.1.0.0-rc3] Error 1

Do you know how I could fix the problem?

Thanks,
Claudio

**Comment by ethanjperez** [comment]
@claudiogreco How did you fix the issue? I am also running into the issue. Any help would be really appreciated!
