### ISSUE TITLE
make runtest error

### ISSUE THREAD

**Issue by xianefeng** [BVLC/caffe#6198]
### Issue summary
make all -j12
make test -j12
above was sucess, but when run 'make runtest -j12', error appear:

[----------] 5 tests from ImageDataLayerTest/2, where TypeParam = caffe::GPUDevice<float>
[ RUN      ] ImageDataLayerTest/2.TestReshape
E0125 21:48:17.837638  7342 io.cpp:80] Could not open or find file examples/images/cat.jpg
F0125 21:48:17.837720  7342 image_data_layer.cpp:77] Check failed: cv_img.data Could not load examples/images/cat.jpg
*** Check failure stack trace: ***
    @     0x7f87ef9155cd  google::LogMessage::Fail()
    @     0x7f87ef917433  google::LogMessage::SendToLog()
    @     0x7f87ef91515b  google::LogMessage::Flush()
    @     0x7f87ef917e1e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f87e93d782f  caffe::ImageDataLayer<>::DataLayerSetUp()
    @     0x7f87e9460ace  caffe::BasePrefetchingDataLayer<>::LayerSetUp()
    @           0x485d20  caffe::Layer<>::SetUp()
    @           0x56be56  caffe::ImageDataLayerTest_TestReshape_Test<>::TestBody()
    @           0x9216c3  testing::internal::HandleExceptionsInMethodIfSupported<>()
    @           0x91b24a  testing::Test::Run()
    @           0x91b398  testing::TestInfo::Run()
    @           0x91b475  testing::TestCase::Run()
    @           0x91b72f  testing::internal::UnitTestImpl::RunAllTests()
    @           0x91ba63  testing::UnitTest::Run()
    @           0x46e35d  main
    @     0x7f87e86c3830  __libc_start_main
    @           0x475eb9  _start
    @              (nil)  (unknown)
Makefile:532: recipe for target 'runtest' failed
make: *** [runtest] 已放弃

### system configuration
Operating system:ubuntu16.04
Compiler:
CUDA version (if applicable):8.0
CUDNN version (if applicable):7.0
BLAS:
Python or MATLAB version (for pycaffe and matcaffe respectively):matlab2017a

**Comment by Noiredd** [comment]
Is your clone of the Caffe repository complete? You should have a file named `cat.jpg` in `examples/images`. Does it exist? Do you have read access to it?

Please ask further usage, installation, or modeling questions to the [caffe-users list][1] instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe. Please read the [guidelines for contributing][2] before submitting an issue or a pull request.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
