### ISSUE TITLE
Problem with libtiff and libjasper in make

### ISSUE THREAD

**Issue by ValoisKhanh** [BVLC/caffe#6213]
I am new to caffe. I ran "make" and get the following errors:

CXX/LD -o .build_release/tools/extract_features.bin
/usr/bin/ld: cannot find -llibjasper
/usr/bin/ld: cannot find -llibtiff
/usr/bin/ld: cannot find -lextra_component-NOTFOUND
collect2: error: ld returned 1 exit status
Makefile:625: recipe for target '.build_release/tools/extract_features.bin' failed
make: *** [.build_release/tools/extract_features.bin] Error 1

I have already installed libtiff5-dev, libtiff5-tools and libjasper-dev but still get the same error.
I use Ubuntu 16.04.
Any help will be appreciated. Thank you.

**Comment by TianxinTse** [comment]
In file Makefile.config. At line 94 `LIBRARY_DIRS`. Append the path to your libtiff5.

If you come across the same problem, just append the paths to your libraries to `LIBRARY_DIRS`.

For demonstration, this is my `LIBRARY_DIRS`:
```
LIBRARY_DIRS := $(PYTHON_LIB) /usr/local/lib /usr/lib /usr/lib/x86_64-linux-gnu/hdf5/serial /usr/lib/x86_64-linux-gnu
```

**Comment by ValoisKhanh** [comment]
How about /usr/bin/ld: cannot find lextra_component-NOTFOUND? It still remains error.
Thanks that I have solved the libtiff and libjasper.

**Comment by TianxinTse** [comment]
@ValoisKhanh Have you installed all the prerequisites described in the official doc? If did, there shouldn't be any error.

**Comment by ValoisKhanh** [comment]
I installed all the requirements on: https://github.com/BVLC/caffe/wiki/Ubuntu-16.04-or-15.10-Installation-Guide
But still get this error:

LD -o .build_release/lib/libcaffe.so.1.0.0
/usr/bin/ld: cannot find -lextra_component-NOTFOUND
collect2: error: ld returned 1 exit status
Makefile:572: recipe for target '.build_release/lib/libcaffe.so.1.0.0' failed
make: *** [.build_release/lib/libcaffe.so.1.0.0] Error 1

**Comment by TianxinTse** [comment]
@ValoisKhanh Sorry, bro. I have no idea about this error.
