### ISSUE TITLE
The protobuf problem when I run 'make all ' command

### ISSUE THREAD

**Issue by TemiLee** [BVLC/caffe#6217]
my environment is : 

`(tensorflow) ➜  caffe git:(master) ✗ python --version
Python 3.6.3 :: Anaconda, Inc.`
`(tensorflow) ➜  caffe git:(master) ✗ protoc --version
libprotoc 2.6.0`

but when I run make all in the path : caffe
`(tensorflow) ➜  caffe git:(master) ✗ pwd
/Users/temi/pro/caffe`

the error is : 
`(tensorflow) ➜  caffe git:(master) ✗ make all
PROTOC src/caffe/proto/caffe.proto
CXX .build_release/src/caffe/proto/caffe.pb.cc
In file included from .build_release/src/caffe/proto/caffe.pb.cc:5:
.build_release/src/caffe/proto/caffe.pb.h:9:10: fatal error: 'google/protobuf/stubs/common.h' file not found
#include <google/protobuf/stubs/common.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [.build_release/src/caffe/proto/caffe.pb.o] Error 1`

**Comment by kdtmac** [comment]
same problem, how to fix
