### ISSUE TITLE
OpenCL Windows - Unable to link to project

### ISSUE THREAD

**Issue by soulslicer** [BVLC/caffe#6220]
I have successfully compiled the OpenCL branch on Windows. However, when I attempt to link it to my C++ project and compile, it gives these linker errors:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol "public: void __cdecl caffe::Blob<float>::Reshape(class std::vector<int,class std::allocator<int> > const &)" (?Reshape@?$Blob@M@caffe@@QEAAXAEBV?$vector@HV?$allocator@H@std@@@std@@@Z) referenced in function "public: virtual void __cdecl op::MaximumCaffe<float>::Reshape(class std::vector<class caffe::Blob<float> *,class std::allocator<class caffe::Blob<float> *> > const &,class std::vector<class caffe::Blob<float> *,class std::allocator<class caffe::Blob<float> *> > const &)" (?Reshape@?$MaximumCaffe@M@op@@UEAAXAEBV?$vector@PEAV?$Blob@M@caffe@@V?$allocator@PEAV?$Blob@M@caffe@@@std@@@std@@0@Z)		1	
Error	LNK2001	unresolved external symbol "public: void __cdecl caffe::Blob<float>::Reshape(class std::vector<int,class std::allocator<int> > const &)" (?Reshape@?$Blob@M@caffe@@QEAAXAEBV?$vector@HV?$allocator@H@std@@@std@@@Z)	openpose	C:\Users\raaj\Documents\GitHub\openpose\buildcl\src\openpose\nmsCaffe.obj	1	
Error	LNK2001	unresolved external symbol "public: void __cdecl caffe::Blob<float>::Reshape(class std::vector<int,class std::allocator<int> > const &)" (?Reshape@?$Blob@M@caffe@@QEAAXAEBV?$vector@HV?$allocator@H@std@@@std@@@Z)		1
```	

And a few more. Why would this be happening?

**Comment by naibaf7** [comment]
Thansk, I will investigate.

**Comment by soulslicer** [comment]
Sorry it is a class i use. I would request if you could compile caffe on windows, and attempt to link a simple c++ project against it

**Comment by naibaf7** [comment]
@soulslicer Hmmm... it's odd since Blob<float>::Reshape is defined like that on line 29/30 of blob.cpp, declared in blob.hpp.

I think what might happen is that you do not use the same compiler flags for compiling Caffe and your C++ project. For example, do you enable C++11 for both projects? That'd be required, to start with.

**Comment by soulslicer** [comment]
Definitely. I am using the ninja build tool to build the opencl branch, followed by visual studio to build mine. The built type (x64 / Release) is all correct as well. I have selected the correct libraries etc. Were  you able to compile and link a simple cpp project in Visual Studio? Because the error seems similar to this:

https://github.com/BVLC/caffe/issues/4907

**Comment by naibaf7** [comment]
@soulslicer No, I currently only compile the Caffe built-in binaries and Python interface on Windows. I don't have a workflow for linking Visual Studio projects right now.
Maybe I should add @willyd to the discussion, since the Windows code in the OpenCL branch comes from his (Windows) branch.

**Comment by soulslicer** [comment]
Can I check your build process. Did you use Ninja as your build tool or MSVC 201N

**Comment by soulslicer** [comment]
Hello all, is there any update to this.

**Comment by naibaf7** [comment]
@soulslicer I don't have time to set-up a windows compile at the moment, so this I can't diagnose currently, sorry.
As I said, maybe @willyd knows what's up.
Your error indicates the expected signature of your target program is different from the symbol signature in the Caffe library - the most likely explanation being that you do NOT pass the same compiler/linker flags to the Caffe library and to your project (i.e. C++11; https://blogs.msdn.microsoft.com/vcblog/2016/06/07/standards-version-switches-in-the-compiler/)
Especially if it works on Linux but not on Windows. Please check that again.

**Comment by soulslicer** [comment]
I will look into using the same build system for my project

**Comment by soulslicer** [comment]
I took a look at the symbol dump of the opencl dll i built: I have this for reshape:

?$vector@HV?$allocator@H@std@@@std@@@Z (public: bool __cdecl caffe::Blob<float>::Reshape(class std::vector<int,class std::allocator<int> > const &))
                  ?Reshape@?$Blob@I@caffe@@QEAA_NHHHH@Z 

However, the reshape that my code seems to look for is this:

"public: void __cdecl caffe::Blob<float>::Reshape(class std::vector<int,class std::allocator<int> > const &)" (?Reshape@?$Blob@M@caffe@@QEAAXAEBV?$vector@HV?$allocator@H@std@@@std@@@Z) 

As you can see the id QEAA_NHHHH does not match QEAAXAEBV

**Comment by soulslicer** [comment]
Wow, it turns out i was compiling in Debug mode on VS. That was the issue, my apologies

**Comment by soulslicer** [comment]
My bad, upon compiling and running it, I get a runtime error with:

Procedure entry points

?Reshape@?$Blob@N@caffe@@QEAA_NAEBV not found

**Comment by naibaf7** [comment]
@soulslicer Oh nice. Yeah probably the symbol for std::vector is different for MSVC in Debug as from Release...
