### ISSUE TITLE
Install caffe by Cmake failed

### ISSUE THREAD

**Issue by zeshaoaaa** [BVLC/caffe#6223]
When I typed "cmake .." on terminal trying to install caffe, following information will occur. I already installed numpy use pip. I've tried every solution I found on Google and Github, I'm using OS X 10.12, how can I fix that? Thanks in advance.

If my description is not clear enough, please tell me.

--------------------------------------------------------------------------------------------

CMake Warning at /opt/local/share/cmake-3.10/Modules/FindBoost.cmake:801 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  /opt/local/share/cmake-3.10/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
  /opt/local/share/cmake-3.10/Modules/FindBoost.cmake:1542 (_Boost_MISSING_DEPENDENCIES)
  cmake/Dependencies.cmake:8 (find_package)
  CMakeLists.txt:46 (include)

CMake Warning at /opt/local/share/cmake-3.10/Modules/FindBoost.cmake:801 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  /opt/local/share/cmake-3.10/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
  /opt/local/share/cmake-3.10/Modules/FindBoost.cmake:1542 (_Boost_MISSING_DEPENDENCIES)
  cmake/Dependencies.cmake:8 (find_package)
  CMakeLists.txt:46 (include)

CMake Warning at /opt/local/share/cmake-3.10/Modules/FindBoost.cmake:801 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  /opt/local/share/cmake-3.10/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
  /opt/local/share/cmake-3.10/Modules/FindBoost.cmake:1542 (_Boost_MISSING_DEPENDENCIES)
  cmake/Dependencies.cmake:8 (find_package)
  CMakeLists.txt:46 (include)

CMake Warning at /opt/local/share/cmake-3.10/Modules/FindBoost.cmake:801 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  /opt/local/share/cmake-3.10/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
  /opt/local/share/cmake-3.10/Modules/FindBoost.cmake:1542 (_Boost_MISSING_DEPENDENCIES)
  cmake/Dependencies.cmake:8 (find_package)
  CMakeLists.txt:46 (include)

CMake Warning at /opt/local/share/cmake-3.10/Modules/FindBoost.cmake:801 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  /opt/local/share/cmake-3.10/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
  /opt/local/share/cmake-3.10/Modules/FindBoost.cmake:1542 (_Boost_MISSING_DEPENDENCIES)
  cmake/Dependencies.cmake:8 (find_package)
  CMakeLists.txt:46 (include)

CMake Warning at /opt/local/share/cmake-3.10/Modules/FindBoost.cmake:801 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  /opt/local/share/cmake-3.10/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
  /opt/local/share/cmake-3.10/Modules/FindBoost.cmake:1542 (_Boost_MISSING_DEPENDENCIES)
  cmake/Dependencies.cmake:8 (find_package)
  CMakeLists.txt:46 (include)

Boost version: 1.66.0
Found the following Boost libraries:
  system
  thread
  filesystem
  chrono
  date_time
  atomic
Found gflags  (include: /usr/local/include, library: /usr/local/lib/libgflags.dylib)
Found glog    (include: /usr/local/include, library: /usr/local/lib/libglog.dylib)
Found PROTOBUF Compiler: /usr/local/bin/protoc
HDF5: Using hdf5 compiler wrapper to determine C configuration
HDF5: Using hdf5 compiler wrapper to determine CXX configuration
Found lmdb    (include: /usr/local/include, library: /usr/local/lib/liblmdb.dylib)
Found LevelDB (include: /usr/local/include, library: /usr/local/lib/libleveldb.dylib)
Found Snappy  (include: /usr/local/include, library: /usr/local/lib/libsnappy.dylib)
CUDA detected: 9.0
Added CUDA NVCC flags for: sm_35
OpenCV found (/usr/local/share/OpenCV)
Found vecLib as part of Accelerate.framework
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named numpy

Could NOT find NumPy (missing: NUMPY_INCLUDE_DIR NUMPY_VERSION) (Required is at least version "1.7.1")
CMake Warning at /opt/local/share/cmake-3.10/Modules/FindBoost.cmake:801 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  /opt/local/share/cmake-3.10/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
  /opt/local/share/cmake-3.10/Modules/FindBoost.cmake:1542 (_Boost_MISSING_DEPENDENCIES)
  cmake/Dependencies.cmake:172 (find_package)
  CMakeLists.txt:46 (include)

Boost version: 1.66.0
Found the following Boost libraries:
  python
Found Doxygen: /usr/local/bin/doxygen (found version "1.8.14") found components:  doxygen missing components:  dot
Python interface is disabled or not all required dependencies found. Building without it...
Detected Doxygen OUTPUT_DIRECTORY: ./doxygen/

******************* Caffe Configuration Summary *******************
General:
  Version           :   1.0.0
  Git               :   1.0-76-g87e15128
  System            :   Darwin
  C++ compiler      :   /Library/Developer/CommandLineTools/usr/bin/c++
  Release CXX flags :   -O3 -DNDEBUG -fPIC -Wall -Wno-sign-compare -Wno-uninitialized
  Debug CXX flags   :   -g -fPIC -Wall -Wno-sign-compare -Wno-uninitialized
  Build type        :   Release

  BUILD_SHARED_LIBS :   ON
  BUILD_python      :   ON
  BUILD_matlab      :   OFF
  BUILD_docs        :   ON
  CPU_ONLY          :   OFF
  USE_OPENCV        :   ON
  USE_LEVELDB       :   ON
  USE_LMDB          :   ON
  USE_NCCL          :   OFF
  ALLOW_LMDB_NOLOCK :   OFF

Dependencies:
  BLAS              :   Yes (vecLib)
  Boost             :   Yes (ver. 1.66)
  glog              :   Yes
  gflags            :   Yes
  protobuf          :   Yes (ver. 3.5.1)
  lmdb              :   Yes (ver. 0.9.21)
  LevelDB           :   Yes (ver. 1.20)
  Snappy            :   Yes (ver. 1.1.7)
  OpenCV            :   Yes (ver. 3.4.0)
  CUDA              :   Yes (ver. 9.0)

NVIDIA CUDA:
  Target GPU(s)     :   Auto
  GPU arch(s)       :   sm_35
  cuDNN             :   Not found

Documentaion:
  Doxygen           :   /usr/local/bin/doxygen (1.8.14)
  config_file       :   /users/jay/Documents/caffe/.Doxyfile

Install:
  Install path      :   /users/jay/Documents/caffe/build/install

Configuring done

**Comment by Lxyzgf** [comment]
how to solve this problem, thankyou
