### ISSUE TITLE
Ximpp compile error 

### ISSUE THREAD

**Issue by Sktewarybt1993** [BVLC/caffe#6234]
Hi I am trying to compile the Xmipp using Scipion on my Macbook.

I am getting errors

scons: Reading SConscript files ...
Mkdir("/Applications/Software/scipion1.1/software/em/xmipp/java/build")
scons: done reading SConscript files.
scons: Building targets ...
scons: `software/lib/libXmippAlglib.so' is up to date.
scons: `software/lib/libXmippBilib.so' is up to date.
scons: `software/lib/libXmippCondor.so' is up to date.
scons: `software/lib/libXmippDelaunay.so' is up to date.
scons: `software/lib/libXmippSqliteExt.so' is up to date.
g++ -o software/em/xmipp/external/gtest/gtest-all.os -c -O3 -fPIC -Isoftware/em/xmipp/external -Isoftware/em/xmipp/libraries -Isoftware/include software/em/xmipp/external/gtest/gtest-all.cc
In file included from software/em/xmipp/external/gtest/gtest-all.cc:39:
software/em/xmipp/external/gtest/gtest.h:1561:13: fatal error: 'tr1/tuple' file not found
#   include <tr1/tuple>  // NOLINT
            ^~~~~~~~~~~
1 error generated.
scons: *** [software/em/xmipp/external/gtest/gtest-all.os] Error 1
scons: building terminated because of errors.

Please suggest me what to do.

**Comment by Noiredd** [comment]
Closing as this does not seem related to Caffe.
