### ISSUE TITLE
importing caffe with sudo not working

### ISSUE THREAD

**Issue by msiraj83** [BVLC/caffe#6241]
Hi
I have installed caffe with `python`. When enter to python promp and import caffe, its work, the output is below.
![python_caffe](https://user-images.githubusercontent.com/8863047/36348460-e9d0c2dc-14a2-11e8-8855-7581885a2703.png)
But when i run python with `sudo python` than import caffe does not work and produce error as shown below 
![python_caffe_sudo](https://user-images.githubusercontent.com/8863047/36348471-0c08037e-14a3-11e8-830a-aefe2386414b.png)  As i need to run the caffe with sudo. 
I set the caffe path in .bashrc and .profile file but still not working. Can any body help me ?

Thanks

**Comment by Noiredd** [comment]
Superuser has its own environment variables and its own .bashrc - by going `sudo python` you are no longer running it as your user (which had `PYTHONPATH` set in .bashrc) but as the superuser.  
To be able to `import caffe` in python as a superuser, you should set the same envvars in the root's .bashrc as well - it's probably `/root/.bashrc` but do look it up if I'm wrong.

I'm closing this as it is not an issue with Caffe itself.

PS: Is there any reason why you need to run Python with elevated privileges?
