### ISSUE TITLE
ImportError: dynamic module does not define module export function (PyInit__caffe)  Debian python3-caffe-cuda

### ISSUE THREAD

**Issue by LupinDefense** [BVLC/caffe#6252]
Please use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) for usage, installation, or modeling questions, or other requests for help.
_Do not post such requests to Issues._ Doing so interferes with the development of Caffe.

Please read the [guidelines for contributing](https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md) before submitting this issue.

### Steps to reproduce
debian unstable
apt-get install caffe-cuda
apt-get install python3-caffe-cuda

Description-en: Python3 interface of Caffe (CUDA)
Description-md5: 8021491599b899a645cb4dbf574347d2
Multi-Arch: foreign
Homepage: http://caffe.berkeleyvision.org
Section: contrib/python
Priority: optional
Filename: pool/contrib/c/caffe-contrib/python3-caffe-cuda_1.0.0~rc4-1_amd64.deb
Size: 699342
MD5sum: 90101bf2792f61bb81cfb0d24a453580
SHA256: b27934f69a05d0f04c40d7ae8e609d79d48387c2a29a7bab78f7d7a8fa3847ea

 python3 -c 'import caffe'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/javier/Caffe/caffe/python/caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropSolver, AdaDeltaSolver, AdamSolver, NCCL, Timer
  File "/home/javier/Caffe/caffe/python/caffe/pycaffe.py", line 13, in <module>
    from ._caffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, \
ImportError: dynamic module does not define module export function (PyInit__caffe)

https://stackoverflow.com/questions/34295136/importerror-dynamic-module-does-not-define-module-export-function-pyinit-caff

but all seems be in its place, /usr/lib/python3/dist-packages/caffe/

If you are having difficulty building Caffe or training a model, please ask the caffe-users mailing list. If you are reporting a build error that seems to be due to a bug in Caffe, please attach your build configuration (either Makefile.config or CMakeCache.txt) and the output of the make (or cmake) command.

### Your system configuration
Operating system: Debian unstable
Compiler:
CUDA version (if applicable): 9
CUDNN version (if applicable):
BLAS:
Python or MATLAB version (for pycaffe and matcaffe respectively):

**Comment by LupinDefense** [comment]
sorry, .bashrc export with different path . All right. Thanks

**Comment by K-G-1** [comment]
How to modify the .bashrc file?

**Comment by DNXie** [comment]
@K-G-1  vim ~/.bashrc

**Comment by DNXie** [comment]
@K-G-1 
`vim ~/.bashrc`  
After you modified and exit  
`source ~/.bashrc`
