### ISSUE TITLE
Caffe version '1.0.0-rc5' can't understand repack_param?

### ISSUE THREAD

**Issue by rohun-tripathi** [BVLC/caffe#6257]
caffe Net loading failed with the following error message:

[libprotobuf ERROR google/protobuf/text_format.cc:288] Error parsing text-format caffe.NetParameter: 40:16: Message type "caffe.LayerParameter" has no field named "repack_param".
WARNING: Logging before InitGoogleLogging() is written to STDERR
F0226 19:11:31.490649   643 upgrade_proto.cpp:88] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: net/feat.prototxt
*** Check failure stack trace: ***
Aborted

Any help with be appreciated, Thanks

**Comment by naibaf7** [comment]
You are probably running a network that was designed for a specialized version of Caffe.
`repack_param` is not available in BVLC/caffe, so this won't work.
Could it be this branch?:
https://github.com/philkr/caffe/tree/repack

**Comment by rohun-tripathi** [comment]
You are right. I works on that branch. Thanks
