### ISSUE TITLE
Missleading example calculations on Imagenet tutorial

### ISSUE THREAD

**Issue by flanaras** [BVLC/caffe#6261]
Hello,

I would like to report a problem on the documentation of caffe, specifically on [ImageNet's example](https://github.com/BVLC/caffe/blob/gh-pages/gathered/examples/imagenet.html).

The author states:
>On a K40 machine, every 20 iterations take about 26.5 seconds to run (while a on a K20 this takes 36 seconds), so effectively about 5.2 ms per image for the full forward-backward pass. About 2 ms of this is on forward, and the rest is backward. If you are interested in dissecting the computation time, you can run (...)

Saying that it takes 5.2 ms for the full forward-backward pass is missleading, this considers all operations being executed sequentially.

Running `./build/tools/caffe time --model=models/bvlc_reference_caffenet/train_val.prototxt` reports  Average Forward-Backward: 281.01 ms on a nvidia tesla v100, while going through 20 iterations faster than 26 seconds on the same batch size

**Comment by Noiredd** [comment]
It does say "**effectively** about 5.2 ms per image", not that a full forward-backward pass takes this long -
 this is openly stated to take 26.5 seconds per 20 iterations (so a single iteration is ~1.3 s). Earlier in the tutorial we read that the network used has a batch size of 256 - this is how much work you do over those 1.3 seconds. For the purpose of learning on ImageNet it is of little importance how long does a single iteration take, but *how long will one need to process N images*; knowing the effective time per image you can make estimates on the total learning time.

I hope this clears your doubts about this paragraph? If you still feel like the tutorial itself could be changed to be more clear, feel free to suggest a change by opening a pull request.
