### ISSUE TITLE
 Does caffe multi-gpu inference support?

### ISSUE THREAD

**Issue by sankim90** [BVLC/caffe#6265]
Hi 
I run caffe in an embedded environment.
(NVIDIA Jetston TX2, DRIVE PX 2)

The Jetson TX2 has one gpu core.
The Drive PX2 has multi gpu core.

I inferred HD images using a caffe framework SSD (Single Shot Multibox detector) algorithm

The Jetson TX2 achieved 8.5 fps,
The drive PX2 got 3.5 fps.

This is nonsense. 
This is because Drive px2 has better hardware specs.

I think caffe can't use all multi GPU cores of DRIVE PX2 when inferring.
so, does caffe multi-gpu inference support?

My environment 
Ubuntu 16.04 for tegra
CUDA 8.0
CUDNN 6.1
OPEN CV 3.3

**Comment by naibaf7** [comment]
@sankim90 Multi-GPU inference is most easily done by using multiple network instances (one per GPU) and alternating the prediction between the GPUs.

**Comment by sankim90** [comment]
@naibaf7 Thanks for your help. I will try using multiple network instances
