### ISSUE TITLE
bvlc/caffe:gpu docker image running slow / run with no speed differences with P100 GPU

### ISSUE THREAD

**Issue by heng2j** [BVLC/caffe#6267]
Hi Caffe team,

I have posted a detailed issue on the [nvidia-docker issues post](https://github.com/NVIDIA/nvidia-docker/issues/649)

I have question about why the process on my caffe docker run with no differences between CPU and GPU mode to simply classify a single image. 

I am currently using this docker container from BVLC

 **bvlc/caffe:gpu** 

When running the sample testing for the [example from NVDIA DIGITS](https://github.com/NVIDIA/DIGITS/tree/master/examples/classification), it seems has no effect between with GPU and with out GPU.

ubuntu@arsl-ubuntu-high:~/data/mnist$ sudo docker exec -t 1b6212c2e743 python -W ignore /code/example.py /model/mnist/snapshot_iter_21120.caffemodel /model/mnist/deploy.prototxt /data/mnist/10072.png --mean /model/mnist/mean.binaryproto --labels /model/mnist/labels.txt
Processed 1/1 images in 0.001959 seconds ...
--------------------- Prediction for /data/mnist/10072.png ---------------------
100.0000% - "2"
  0.0000% - "3"
  0.0000% - "8"
  0.0000% - "7"
  0.0000% - "1"

Script took 0.926027 seconds.

ubuntu@arsl-ubuntu-high:~/data/mnist$ sudo docker exec -t 1b6212c2e743 python -W ignore /code/example.py /model/mnist/snapshot_iter_21120.caffemodel /model/mnist/deploy.prototxt /data/mnist/10072.png --mean /model/mnist/mean.binaryproto --labels /model/mnist/labels.txt --nogpu
Processed 1/1 images in 0.000988 seconds ...
--------------------- Prediction for /data/mnist/10072.png ---------------------
100.0000% - "2"
  0.0000% - "3"
  0.0000% - "8"
  0.0000% - "7"
  0.0000% - "1"

Script took 0.931851 seconds.

I have activated 1 P100 GPU for this container, but seems still run slower than what it should be. 

root@1b6212c2e743:/workspace# nvidia-smi
Wed Feb 28 22:40:03 2018       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 390.30                 Driver Version: 390.30                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla P100-PCIE...  Off  | 00000000:00:05.0 Off |                    0 |
| N/A   25C    P0    28W / 250W |   2289MiB / 12198MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+

I am desperately seeking for help around. Thank you

**Comment by Noiredd** [comment]
I assume [this](https://groups.google.com/forum/#!topic/caffe-users/lZg9FjY1wpY) is your post on the caffe-users list? I have [replied](https://groups.google.com/d/msg/caffe-users/lZg9FjY1wpY/OvE7X1moCgAJ) with a few suggestions. This is almost definitely a usage issue, so per the [contribution guidelines](https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md#issues), I will close this issue. Let's have the conversation in the linked thread on the mailing list.
