### ISSUE TITLE
make runtest failed

### ISSUE THREAD

**Issue by waschbaer00** [BVLC/caffe#6280]
Hi there,

Ubuntu 16.04
OpenCV 3 but I actually comment out opencv_version = 3 to pass the make all
CUDA 9.1
Nvidia 390.25

after make all, make py, make test, I did make runtest

I got this:

F0306 22:42:36.133131 32533 math_functions.cu:375] Check failed: status == CURAND_STATUS_SUCCESS (201 vs. 0)  CURAND_STATUS_LAUNCH_FAILURE
*** Check failure stack trace: ***
    @     0x7f7a8081b5cd  google::LogMessage::Fail()
    @     0x7f7a8081d433  google::LogMessage::SendToLog()
    @     0x7f7a8081b15b  google::LogMessage::Flush()
    @     0x7f7a8081de1e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f7a7dccecca  caffe::caffe_gpu_rng_uniform()
    @     0x7f7a7dc7b2c2  caffe::DropoutLayer<>::Forward_gpu()
    @           0x483f06  caffe::Layer<>::Forward()
    @           0x484e14  caffe::GradientChecker<>::CheckGradientSingle()
    @           0x4db594  caffe::GradientChecker<>::CheckGradientEltwise()
    @           0x8ddb56  caffe::NeuronLayerTest_TestDropoutGradient_Test<>::TestBody()
    @           0x9f2533  testing::internal::HandleExceptionsInMethodIfSupported<>()
    @           0x9ebb4a  testing::Test::Run()
    @           0x9ebc98  testing::TestInfo::Run()
    @           0x9ebd75  testing::TestCase::Run()
    @           0x9ed04f  testing::internal::UnitTestImpl::RunAllTests()
    @           0x9ed373  testing::UnitTest::Run()
    @           0x4765bd  main
    @     0x7f7a7cd2b830  __libc_start_main
    @           0x47f319  _start
Makefile:527: recipe for target 'runtest' failed
make: *** [runtest] Aborted (core dumped)

Where I should modify the Makefile or Makefile.config to fix this?

**Comment by twmht** [comment]
@waschbaer00  @SlienceSun 

cudnn version? Did you fall back to cuda 8?

**Comment by waschbaer00** [comment]
It is said that caffe i scomatible to CUDA 9.1 and cuDNN 7.1

**Comment by shanmugaraj1986** [comment]
Hi, i am getting this error while doing...............Make all in caffe
Please provide the solution for the same. Thanks in advance

LD -o .build_release/lib/libcaffe.so.1.0.0
/usr/bin/ld: cannot find -latlas
collect2: error: ld returned 1 exit status
Makefile:572: recipe for target '.build_release/lib/libcaffe.so.1.0.0' failed
make: *** [.build_release/lib/libcaffe.so.1.0.0] Error 1

**Comment by Noiredd** [comment]
It is a common configuration error - either due to CUDA/cuDNN version mismatch or CUDA libraries mismatch (if you have multiple versions installed). Please look up CURAND_STATUS_LAUNCH_FAILURE, there are many available solutions. If none work, consult the [caffe-users list][1].

Please post usage, installation, or modeling questions, or other requests for help to the [caffe-users list][1] instead of Issues. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe. Please read the [guidelines for contributing][2] before submitting an issue or a pull request.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md

**Comment by meriem87** [comment]
I have more all less the same problem. I passed make -j8 all and make -j8 test but make -j8 runtest gives me the following error : 
```
.build_release/tools/caffe: symbol lookup error: .build_release/tools/caffe: undefined symbol: _ZN5caffe3NetIfE21CopyTrainedLayersFromERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
Makefile:543: recipe for target 'runtest' failed
make: *** [runtest] Error 127
```
My configuration is the following: 

Ubuntu 18.04
Cuda 9.1 
Python 3.6

**Comment by aaronchen98** [comment]
Hi@meriem87 
I have the same problem with you.Have you solved the problem?
