### ISSUE TITLE
Cuda memcheck issue

### ISSUE THREAD

**Issue by achalshah20** [BVLC/caffe#6281]
Hi, I am running cudamemcheck on my caffe program and getting 25 cudaErrorCudartUnloading errors. One of the example is below!

### Issue summary
========= Program hit cudaErrorCudartUnloading (error 29) due to "driver shutting down" on CUDA API call to cudaFree.
=========     Saved host backtrace up to driver entry point at error
=========     Host Frame:/usr/lib/x86_64-linux-gnu/libcuda.so.1 [0x311153]
=========     Host Frame:/usr/local/cuda/lib64/libcurand.so.9.1 [0xa8e40]
=========     Host Frame:/usr/local/cuda/lib64/libcurand.so.9.1 (curandDestroyGenerator + 0x23c) [0x24f3c]
=========     Host Frame:/usr/lib/x86_64-linux-gnu/libcaffe.so.1.0.0 (_ZN5caffe5CaffeD1Ev + 0x4c) [0x13e84c]
=========     Host Frame:/usr/lib/x86_64-linux-gnu/libcaffe.so.1.0.0 (_ZN5boost19thread_specific_ptrIN5caffe5CaffeEE11delete_dataclEPv + 0x11) [0x142971]
=========     Host Frame:/usr/lib/x86_64-linux-gnu/libboost_thread.so.1.58.0 (_ZN5boost6detail12set_tss_dataEPKvNS_10shared_ptrINS0_20tss_cleanup_functionEEEPvb + 0x55) [0x13ba5]
=========     Host Frame:/usr/lib/x86_64-linux-gnu/libcaffe.so.1.0.0 (_ZN5boost19thread_specific_ptrIN5caffe5CaffeEED1Ev + 0x39) [0x140e59]
=========     Host Frame:/lib/x86_64-linux-gnu/libc.so.6 (__cxa_finalize + 0x9a) [0x3a36a]
=========     Host Frame:/usr/lib/x86_64-linux-gnu/libcaffe.so.1.0.0 [0x12df93]

### Steps to reproduce

Ran example image classification code

### Your system configuration
Operating system: Ubuntu 16.04
Compiler: gcc 5.4
CUDA version (if applicable): 9.1
CUDNN version (if applicable): 7.0.5
BLAS: Yes
Python or MATLAB version (for pycaffe and matcaffe respectively): N/A

**Comment by achalshah20** [comment]
I am using " cuda-memcheck --leak-check full --error-exitcode 1 ./application" command to find memory leaks.

**Comment by Noiredd** [comment]
Is this a problem with your application that uses Caffe, or with the framework itself?

**Comment by Noiredd** [comment]
Closing due to lack of updates. Feel free to reopen when you complete the details requested in the previous post.
