### ISSUE TITLE
Umable to build caffe matlab

### ISSUE THREAD

**Issue by soulslicer** [BVLC/caffe#6287]
### Issue summary

I am on Ubuntu 16.04. I have setup my Matlab to support gcc 4.9 as well.

However, when I compile, it throws this error related to CUDA:

> 
> [100%] Building Matlab interface: /home/user/caffe/matlab/+caffe/private/caffe_.mexa64
> Building with 'g++-4.9'.
> /home/user/caffe/matlab/+caffe/private/caffe_.cpp:18:27: fatal error: caffe/caffe.hpp: No such file or directory
> compilation terminated.

Everything else built properly

I then switched over to a computer with Ubuntu 14.04. Tried to compile, I get this error:

```
Building with 'g++'.
In file included from /usr/local/include/caffe/common.hpp:19:0,
                 from /usr/local/include/caffe/blob.hpp:8,
                 from /usr/local/include/caffe/caffe.hpp:7,
                 from /home/raaj/caffe/matlab/+caffe/private/caffe_.cpp:18:
/usr/local/include/caffe/util/device_alternate.hpp:34:23: fatal error: cublas_v2.h: No such file or directory
 #include <cublas_v2.h>
```

Matlab seems to be broken in Caffe

**Comment by Deastan** [comment]
Did you find a solution ?

**Comment by soulslicer** [comment]
No, i gave up and switched to pytorch long time ago
