### ISSUE TITLE
ImageNet training, batch_size = 128 used to work but not any more

### ISSUE THREAD

**Issue by caffecuda** [BVLC/caffe#629]
Hello,

I have a GPU with CUDA capability 2.0 (and therefore CAFFE_CUDA_NUM_THREADS=512). With the Caffe master release downloaded on April 10th I was able to train ImagetNet by only changing batch_size in imagenet_train.prototxt from 256 to 128. With a new version downloaded on July 4th and the same batch_size (128) I got this error:

F0704 19:50:28.537441  4637 relu_layer.cu:29] Check failed: error == cudaSuccess (9 vs. 0)  invalid configuration argument
**\* Check failure stack trace: ***
    @     0x2ac5cb96bb7d  google::LogMessage::Fail()
    @     0x2ac5cb96dc7f  google::LogMessage::SendToLog()
    @     0x2ac5cb96b76c  google::LogMessage::Flush()
    @     0x2ac5cb96e51d  google::LogMessageFatal::~LogMessageFatal()
    @           0x4dbeee  caffe::ReLULayer<>::Forward_gpu()
    @           0x457c69  caffe::Net<>::ForwardPrefilled()
    @           0x439c94  caffe::Solver<>::Solve()
    @           0x413f2e  main
    @     0x2ac5ce12176d  (unknown)
    @           0x415d2d  (unknown)
Aborted (core dumped)

I then further reduced batch_size to 64, and changed base_lr from 0.01 to 0.01414, stepsize from 10,0000 to 20,0000, and max_iter from 450,000 to 900,000, as suggested in #430. With these changes, training proceeds but ts0 scores stays at 1/C after more than 35,000 iterations ie the net is not learning. Any idea what I am doing wrong here?
Thanks for your help!

**Comment by wguo68** [comment]
I have the problem:
  Check failed: error == cudaSuccess (9 vs. 0)  invalid configuration argument

My GPU is GTC 659Ti, and the traning image size is 250*250.
