### ISSUE TITLE
convert_imageset: No such file or directory

### ISSUE THREAD

**Issue by Yasmine1991** [BVLC/caffe#6292]
Hello,

I'm facing a problem for a while now and I'm wondering if anyone can help me. As you can see from the title, I'm trying to convert my png images of my dataset into LMDB format for caffe however when runing **bash create_wordLMDB.sh** (my sh file personalized according to my folders), I have this problem saying:

**convert_imageset: No such file or directory**

### I want to underline that I'm runing the sh file from the comand line under windows 10

Here the code of the file **create_wordLMDB.sh**

```sh
set -e

EXAMPLE=C:/Projects/caffe/examples/datasetTextEmbeddingModel/textEmbeddingLMDB
DATA=C:/Projects/caffe/examples/datasetTextEmbeddingModel/wordMatTxt
TOOLS=C:/Projects/caffe/build/tools

TRAIN_DATA_ROOT=C:/Projects/caffe/examples/datasetTextEmbeddingModel/wordMatImg
VAL_DATA_ROOT=C:/Projects/caffe/examples/datasetTextEmbeddingModel/wordTestImg


RESIZE=false
if $RESIZE; then
  RESIZE_HEIGHT=256
  RESIZE_WIDTH=256
else
  RESIZE_HEIGHT=0
  RESIZE_WIDTH=0
fi

if [ ! -d "$TRAIN_DATA_ROOT" ]; then
  echo "Error: TRAIN_DATA_ROOT is not a path to a directory: $TRAIN_DATA_ROOT"
  echo "Set the TRAIN_DATA_ROOT variable in create_imagenet.sh to the path" \
       "where the ImageNet training data is stored."
  exit 1
fi

if [ ! -d "$VAL_DATA_ROOT" ]; then
  echo "Error: VAL_DATA_ROOT is not a path to a directory: $VAL_DATA_ROOT"
  echo "Set the VAL_DATA_ROOT variable in create_imagenet.sh to the path" \
       "where the ImageNet validation data is stored."
  exit 1
fi

echo "Creating train lmdb..."

GLOG_logtostderr=1 $TOOLS/convert_imageset \
    --resize_height=$RESIZE_HEIGHT\
    --resize_width=$RESIZE_WIDTH \
    --shuffle\
    $TRAIN_DATA_ROOT \
    $DATA/train.txt \
    $EXAMPLE/ilsvrc12_train_lmdb

echo "Creating val lmdb..."

GLOG_logtostderr=1 $TOOLS/convert_imageset \
    --resize_height=$RESIZE_HEIGHT\
    --resize_width=$RESIZE_WIDTH \
    --shuffle\
    $VAL_DATA_ROOT \
    $DATA/val.txt \
    $EXAMPLE/ilsvrc12_val_lmdb

echo "Done."
```

**Comment by Yasmine1991** [comment]
Moreover, when I check the "build/tools" directory, I can see the file **convert_imageset** in there

Please can anyone help me, ?

**Comment by Noiredd** [comment]
Please post usage, installation, or modeling questions, or other requests for help to the [caffe-users list][1] instead of Issues. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe. Please read the [guidelines for contributing][2] before submitting an issue or a pull request.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
