### ISSUE TITLE
caffe 的opencl分支，支持linknet网络吗？

### ISSUE THREAD

**Issue by wsGinger** [BVLC/caffe#6295]
我跑的时候出现/mnt/ssd/builder/work/renesas/opencl/ddk-v2.23/output/llvm-build/llvm.src/lib/IR/Value.cpp:352: void llvm::Value::replaceAllUsesWith(llvm::Value*): Assertion `New && "Value::replaceAllUsesWith(<null>) is invalid!"' failed. Aborted (core dumped)，发现_net.reset函数中，构建fullconv时出错，有人遇到过吗？

**Comment by eaoibng** [comment]
你好，我也遇到了同样的问题，请问这个问题你解决了吗？采用的什么方式呢？
谢谢。
