### ISSUE TITLE
[pooling_layer.cpp][AVE POOL] The variable of "pool_size" is wrongly calculated, which caused the average pooling layer output is wrong

### ISSUE THREAD

**Issue by oscarriddle** [BVLC/caffe#6297]
Hi,

I've submitted a Pull Request for this issue, please refer #6296 
I tried to compare the output values of average pooling layer between Caffe and TensorFlow, and find Caffe's AVE pooling result is always smaller. From the source code, I located the issue that the variable "pool_size", which is the denominator of averaging, is fixed to the kernel size (like 9 for 3x3).
Hence if the pooling kernel overlaps some padded elements (for instance, 0), the averaged value becomes smaller. While I think the correct pooling method shall only calculate those valid elements.

This is a quite simple issue but also significant. Because if someone's network implements many average pooling layers within convolutions, the averaged outputs always lost the feature map information which is downgrading the significance of those elements around the edges.

For detailed bug info, please refer to the URL.

Thanks,
Xiaolun Cao

**Comment by Noiredd** [comment]
Let's have a single place to discuss the issue - I suggest your PR, #6296. I'll copy this comment to that thread and close this.
