### ISSUE TITLE
make test and make runtest error

### ISSUE THREAD

**Issue by mumtaz23** [BVLC/caffe#6308]
I am using ubuntu 14.04, cuda 8.0 cuDDN 5.0. Anaconda 2.1
$ sudo make all (successful)
$ sudo make pycaffe (successful)
import caffe (successful)
I met below error when I work work $ sudo make test OR $ sudo make runtest
I am newbie with deep learning. I am requested for your kind help please.

$ make runtest
CXX src/caffe/test/test_stochastic_pooling.cpp
src/caffe/test/test_stochastic_pooling.cpp: In member function ‘virtual void caffe::CPUStochasticPoolingLayerTest_TestSetup_Test<gtest_TypeParam_>::TestBody()’:
src/caffe/test/test_stochastic_pooling.cpp:59:35: error: no matching function for call to ‘caffe::PoolingParameter::set_kernel_size(int)’
pooling_param->set_kernel_size(3);
^
src/caffe/test/test_stochastic_pooling.cpp:59:35: note: candidate is:
In file included from ./include/caffe/util/cudnn.hpp:9:0,
from ./include/caffe/util/device_alternate.hpp:40,
from ./include/caffe/common.hpp:19,
from ./include/caffe/blob.hpp:8,
from src/caffe/test/test_stochastic_pooling.cpp:6:
.build_release/src/caffe/proto/caffe.pb.h:20194:13: note: void caffe::PoolingParameter::set_kernel_size(int, google::protobuf::uint32)
inline void PoolingParameter::set_kernel_size(int index, ::google::protobuf::uint32 value) {
^
.build_release/src/caffe/proto/caffe.pb.h:20194:13: note: candidate expects 2 arguments, 1 provided
src/caffe/test/test_stochastic_pooling.cpp:60:30: error: no matching function for call to ‘caffe::PoolingParameter::set_stride(int)’
pooling_param->set_stride(2);
^
src/caffe/test/test_stochastic_pooling.cpp:60:30: note: candidate is:
In file included from ./include/caffe/util/cudnn.hpp:9:0,
from ./include/caffe/util/device_alternate.hpp:40,
from ./include/caffe/common.hpp:19,
from ./include/caffe/blob.hpp:8,
from src/caffe/test/test_stochastic_pooling.cpp:6:
.build_release/src/caffe/proto/caffe.pb.h:20219:13: note: void caffe::PoolingParameter::set_stride(int, google::protobuf::uint32)
inline void PoolingParameter::set_stride(int index, ::google::protobuf::uint32 value) {
^
.build_release/src/caffe/proto/caffe.pb.h:20219:13: note: candidate expects 2 arguments, 1 provided
src/caffe/test/test_stochastic_pooling.cpp: In member function ‘virtual void caffe::GPUStochasticPoolingLayerTest_TestStochastic_Test<gtest_TypeParam_>::TestBody()’:
src/caffe/test/test_stochastic_pooling.cpp:82:35: error: no matching function for call to ‘caffe::PoolingParameter::set_kernel_size(int)’
pooling_param->set_kernel_size(3);
^
src/caffe/test/test_stochastic_pooling.cpp:82:35: note: candidate is:
In file included from ./include/caffe/util/cudnn.hpp:9:0,
from ./include/caffe/util/device_alternate.hpp:40,
from ./include/caffe/common.hpp:19,
from ./include/caffe/blob.hpp:8,
from src/caffe/test/test_stochastic_pooling.cpp:6:
.build_release/src/caffe/proto/caffe.pb.h:20194:13: note: void caffe::PoolingParameter::set_kernel_size(int, google::protobuf::uint32)
inline void PoolingParameter::set_kernel_size(int index, ::google::protobuf::uint32 value) {
^
.build_release/src/caffe/proto/caffe.pb.h:20194:13: note: candidate expects 2 arguments, 1 provided
src/caffe/test/test_stochastic_pooling.cpp:83:30: error: no matching function for call to ‘caffe::PoolingParameter::set_stride(int)’
pooling_param->set_stride(2);
^
src/caffe/test/test_stochastic_pooling.cpp:83:30: note: candidate is:
In file included from ./include/caffe/util/cudnn.hpp:9:0,
from ./include/caffe/util/device_alternate.hpp:40,
from ./include/caffe/common.hpp:19,
from ./include/caffe/blob.hpp:8,
from src/caffe/test/test_stochastic_pooling.cpp:6:
.build_release/src/caffe/proto/caffe.pb.h:20219:13: note: void caffe::PoolingParameter::set_stride(int, google::protobuf::uint32)
inline void PoolingParameter::set_stride(int index, ::google::protobuf::uint32 value) {
^
.build_release/src/caffe/proto/caffe.pb.h:20219:13: note: candidate expects 2 arguments, 1 provided
src/caffe/test/test_stochastic_pooling.cpp: In member function ‘virtual void caffe::GPUStochasticPoolingLayerTest_TestStochasticTestPhase_Test<gtest_TypeParam_>::TestBody()’:
src/caffe/test/test_stochastic_pooling.cpp:125:35: error: no matching function for call to ‘caffe::PoolingParameter::set_kernel_size(int)’
pooling_param->set_kernel_size(3);
^
src/caffe/test/test_stochastic_pooling.cpp:125:35: note: candidate is:
In file included from ./include/caffe/util/cudnn.hpp:9:0,
from ./include/caffe/util/device_alternate.hpp:40,
from ./include/caffe/common.hpp:19,
from ./include/caffe/blob.hpp:8,
from src/caffe/test/test_stochastic_pooling.cpp:6:
.build_release/src/caffe/proto/caffe.pb.h:20194:13: note: void caffe::PoolingParameter::set_kernel_size(int, google::protobuf::uint32)
inline void PoolingParameter::set_kernel_size(int index, ::google::protobuf::uint32 value) {
^
.build_release/src/caffe/proto/caffe.pb.h:20194:13: note: candidate expects 2 arguments, 1 provided
src/caffe/test/test_stochastic_pooling.cpp:126:30: error: no matching function for call to ‘caffe::PoolingParameter::set_stride(int)’
pooling_param->set_stride(2);
^
src/caffe/test/test_stochastic_pooling.cpp:126:30: note: candidate is:
In file included from ./include/caffe/util/cudnn.hpp:9:0,
from ./include/caffe/util/device_alternate.hpp:40,
from ./include/caffe/common.hpp:19,
from ./include/caffe/blob.hpp:8,
from src/caffe/test/test_stochastic_pooling.cpp:6:
.build_release/src/caffe/proto/caffe.pb.h:20219:13: note: void caffe::PoolingParameter::set_stride(int, google::protobuf::uint32)
inline void PoolingParameter::set_stride(int index, ::google::protobuf::uint32 value) {
^
.build_release/src/caffe/proto/caffe.pb.h:20219:13: note: candidate expects 2 arguments, 1 provided
src/caffe/test/test_stochastic_pooling.cpp: In member function ‘virtual void caffe::GPUStochasticPoolingLayerTest_TestGradient_Test<gtest_TypeParam_>::TestBody()’:
src/caffe/test/test_stochastic_pooling.cpp:162:35: error: no matching function for call to ‘caffe::PoolingParameter::set_kernel_size(int)’
pooling_param->set_kernel_size(3);
^
src/caffe/test/test_stochastic_pooling.cpp:162:35: note: candidate is:
In file included from ./include/caffe/util/cudnn.hpp:9:0,
from ./include/caffe/util/device_alternate.hpp:40,
from ./include/caffe/common.hpp:19,
from ./include/caffe/blob.hpp:8,
from src/caffe/test/test_stochastic_pooling.cpp:6:
.build_release/src/caffe/proto/caffe.pb.h:20194:13: note: void caffe::PoolingParameter::set_kernel_size(int, google::protobuf::uint32)
inline void PoolingParameter::set_kernel_size(int index, ::google::protobuf::uint32 value) {
^
.build_release/src/caffe/proto/caffe.pb.h:20194:13: note: candidate expects 2 arguments, 1 provided
src/caffe/test/test_stochastic_pooling.cpp:163:30: error: no matching function for call to ‘caffe::PoolingParameter::set_stride(int)’
pooling_param->set_stride(2);
^
src/caffe/test/test_stochastic_pooling.cpp:163:30: note: candidate is:
In file included from ./include/caffe/util/cudnn.hpp:9:0,
from ./include/caffe/util/device_alternate.hpp:40,
from ./include/caffe/common.hpp:19,
from ./include/caffe/blob.hpp:8,
from src/caffe/test/test_stochastic_pooling.cpp:6:
.build_release/src/caffe/proto/caffe.pb.h:20219:13: note: void caffe::PoolingParameter::set_stride(int, google::protobuf::uint32)
inline void PoolingParameter::set_stride(int index, ::google::protobuf::uint32 value) {
^
.build_release/src/caffe/proto/caffe.pb.h:20219:13: note: candidate expects 2 arguments, 1 provided
make: *** [.build_release/src/caffe/test/test_stochastic_pooling.o] Error 1

**Comment by Noiredd** [comment]
This has already been [posted on the users-list](https://groups.google.com/forum/#!topic/caffe-users/L3ahiM6B1rA). In that thread, I have requested further information on your issue. Let's keep this conversation in one place.
