### ISSUE TITLE
compile caffe error:   .build_release/src/caffe/proto/caffe.pb.o] Error 1

### ISSUE THREAD

**Issue by wvinzh** [BVLC/caffe#6319]
PROTOC src/caffe/proto/caffe.proto
CXX .build_release/src/caffe/proto/caffe.pb.cc
In file included from /usr/include/c++/4.8/cwchar:44:0,
                 from /usr/include/c++/4.8/bits/postypes.h:40,
                 from /usr/include/c++/4.8/bits/char_traits.h:40,
                 from /usr/include/c++/4.8/string:40,
                 from .build_release/src/caffe/proto/caffe.pb.h:7,
                 from .build_release/src/caffe/proto/caffe.pb.cc:5:
/usr/local/include/wchar.h:55:34: error: expected ‘)’ before ‘(’ token
 extern FILE (* __MINGW_IMP_SYMBOL(_iob))[]; /* A pointer to an array of FILE */
                                  ^
/usr/local/include/wchar.h:78:5: error: ‘__time32_t’ does not name a type
     __time32_t time_create;
     ^
/usr/local/include/wchar.h:79:5: error: ‘__time32_t’ does not name a type
     __time32_t time_access;
     ^
/usr/local/include/wchar.h:80:5: error: ‘__time32_t’ does not name a type
     __time32_t time_write;
     ^
/usr/local/include/wchar.h:87:5: error: ‘__time32_t’ does not name a type
     __time32_t time_create;
     ^
/usr/local/include/wchar.h:88:5: error: ‘__time32_t’ does not name a type
     __time32_t time_access;
     ^
/usr/local/include/wchar.h:89:5: error: ‘__time32_t’ does not name a type
     __time32_t time_write;
     ^
/usr/local/include/wchar.h:90:5: error: ‘__MINGW_EXTENSION’ does not name a type
     __MINGW_EXTENSION __int64 size;
     ^
/usr/local/include/wchar.h:96:5: error: ‘__time64_t’ does not name a type
     __time64_t time_create;
     ^
/usr/local/include/wchar.h:97:5: error: ‘__time64_t’ does not name a type
     __time64_t time_access;
     ^
/usr/local/include/wchar.h:98:5: error: ‘__time64_t’ does not name a type
     __time64_t time_write;
     ^

**Comment by twmht** [comment]
@wvinzh 

what is your environment? CUDA version? gcc version?

**Comment by wvinzh** [comment]
@twmht 
Operating system: Ubuntu 16.04
Compiler: gcc5.4 g++5.4(i also tried 4.8, but same error)
CUDA version (if applicable): 8.0
CUDNN version (if applicable): 5.1
protoc version 2.6.1(i changed to 3.5, it output the same)

**Comment by Noiredd** [comment]
Additionally, what is your version of protoc and protobuf headers? When in doubt, reinstall both.

Is this issue different than #6312? Maybe one should be closed?

**Comment by wvinzh** [comment]
@Noiredd I‘ve found the cause. Someone installed MinGW on the Ubuntu, and it covered many header files in /usr/include and /usr/local/include.  When i compiled, it included the .h files from MinGW but using system gcc. I solved it by reinstalling the system.
