### ISSUE TITLE
Optionally build with HDF5 support to simplify cross-compilation

### ISSUE THREAD

**Issue by jerryz123** [BVLC/caffe#6332]
### Issue summary
In order to cross-compile Caffe to run on an embedded system, all of the dependency libraries must also be cross-compiled. The HDF5 library does not natively support cross compiling, making automated cross-compilation of Caffe difficult. 

I propose adding a USE_HDF5 flag. By default USE_HDF5=1. When USE_HDF5=0, the HDF5 layers are not built, and the HDF5 library is not linked. This would greatly simplify automated cross-compilation of Caffe with Yocto.

[HDF5 Cross-Compiling](https://support.hdfgroup.org/HDF5/faq/compile.html)

### Steps to reproduce

Attempt to cross-compile Caffe using standard cross-compiling toolchain. It is very dificult.

### Your system configuration
Operating system: Ubuntu 16.04 x86
Cross-Compiler: riscv64-unknown-linux-gnu-gcc

**Comment by naibaf7** [comment]
@jerryz123 This is already available in https://github.com/BVLC/caffe/blob/opencl/CMakeLists.txt
The commit could be cherry-picked and merged into Master.

**Comment by Noiredd** [comment]
This was done in naibaf7/caffe#50, in aed934d. I'm not sure about that Android-related code though, do we need it on master or should I remove it?

**Comment by naibaf7** [comment]
@Noiredd Yes I recommend skipping the Android code for now. It needs improvement first.

**Comment by Noiredd** [comment]
Thank you @jerryz123!
