### ISSUE TITLE
MemoryDataLayer error

### ISSUE THREAD

**Issue by s0302102** [BVLC/caffe#6341]
I use MemoryDataLayer to do network forward process. At first, I didn't change the batch size and it runs correctly. However, when I tried to invoke the set_batch_size(), the program returned the error link 1120, which means it cannot find the implementation of set_batch_size(). I could invoke the AddMatVector() function. Finally I found that the is the keyword "virtual" before addMatVector() function, thus I added the "virtual" before the set_batch_size() function and it can be complied, but crashed during running. I am not sure whether it is a bug? Can anyone help with it?

Thanks

**Comment by s0302102** [comment]
Thank you @Noiredd 
Windows version from official site.
What kind of details do you need @Noiredd

**Comment by Noiredd** [comment]
Closing due to lack of updates. Feel free to reopen when you complete the details - read the checklist in the [issue template](https://github.com/BVLC/caffe/blob/master/.github/ISSUE_TEMPLATE.md) and complete your issue accordingly:
>read the guidelines and remove the first paragraph
>write a short summary and detailed steps to reproduce
>explain how solutions to related problems failed (tick if found none)
>fill system configuration
>attach relevant logs/config files (tick if not applicable)
