### ISSUE TITLE
Out of Memory in python interface for testing 

### ISSUE THREAD

**Issue by mislulu** [BVLC/caffe#6348]
### Issue summary
I have constructed a network by myself and use it for training facial landmarks.  I can successfully train the network with  my own train.prototxt and solver.prototxt. But something strange happen in my testing phase. As  I want to get the output of the testing images, so I write the documentations for testing images in python (like the examples: 00-classification.ipynb). When I load the caffemodel and network to test, the python displays the error:　Ｏut Of Memory! 

### Steps to reproduce
1. train successfully with prototxt files
2. Out of Memory within the same network in python for testing images

### System configuration

* Operating system:  Ubuntu 16.04.4 LTS
* CUDA version (if applicable):  cuda 8
* Python version (if using pycaffe):  pycharm 2018.1.1 (python 2.7)

**Comment by Noiredd** [comment]
This is most probably an usage issue. Please post it to the [caffe-users list][1] along with more details - train.prototxt, code that you use to load the net in Python, actual error log. Also it would be good to see the output from `nvidia-smi` during training of this particular net.

See CONTRIBUTING.md:
>Please post usage, installation, or modeling questions, or other requests for help to the [caffe-users list][1] instead of Issues. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe. Please read the [guidelines for contributing][2] before submitting an issue or a pull request.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
