### ISSUE TITLE
I wanna run make all matcaffe

### ISSUE THREAD

**Issue by VicomLab** [BVLC/caffe#6349]
## Issue
I am trying to run `make all matcaffe` on the caffe directionary `~/caffe`. But appears this error:

```
bash: -c: linha 0: erro de sintaxe próximo do `token' não esperado `('
bash: -c: linha 0: `find examples/SRCNNteste/model/9-3-5(ImageNet) -maxdepth 1 \( -name '*.cpp' -o -name '*.proto' \) | grep -q .'
bash: -c: linha 0: erro de sintaxe próximo do `token' não esperado `('
bash: -c: linha 0: `find examples/SRCNNteste/model/9-1-5(ImageNet) -maxdepth 1 \( -name '*.cpp' -o -name '*.proto' \) | grep -q .'
bash: -c: linha 0: erro de sintaxe próximo do `token' não esperado `('
bash: -c: linha 0: `find examples/SRCNNteste/model/9-1-5(91 images) -maxdepth 1 \( -name '*.cpp' -o -name '*.proto' \) | grep -q .'
bash: -c: linha 0: erro de sintaxe próximo do `token' não esperado `('
bash: -c: linha 0: `find examples/SRCNNteste/model/9-5-5(ImageNet) -maxdepth 1 \( -name '*.cpp' -o -name '*.proto' \) | grep -q .'
make: Nothing to be done for 'all'.
make: Nothing to be done for 'matcaffe'.
```

### System configuration

* Operating system: Ubuntu 16.04
* MATLAB version: R2016b

**Comment by Noiredd** [comment]
Please read the checklist in the [issue template](https://github.com/BVLC/caffe/blob/master/.github/ISSUE_TEMPLATE.md) and complete your issue accordingly:
>read the guidelines and remove the first paragraph
>write a short summary and detailed steps to reproduce
>explain how solutions to related problems failed (tick if found none)
>fill system configuration
>attach relevant logs/config files (tick if not applicable)

**Comment by Noiredd** [comment]
Closing due to lack of updates. Feel free to reopen when you complete the details requested in the previous post.
