### ISSUE TITLE
Error saveFilter.m in MEX

### ISSUE THREAD

**Issue by VicomLab** [BVLC/caffe#6350]
### Issue summary

I need to run `saveFilter.m` in MATLAB but this error appear:

```
Invalid MEX-file '/home/vicom/caffe/matlab/+caffe/private/caffe_.mexa64':
/home/vicom/Documentos/MATLAB_R2016b/bin/glnxa64/../../sys/os/glnxa64/libstdc++.so.6: version `GLIBCXX_3.4.21'
not found (required by /home/vicom/caffe/matlab/+caffe/private/caffe_.mexa64).

Error in caffe.reset_all (line 5)
caffe_('reset');

Error in saveFilters (line 1)
caffe.reset_all();
```

### System configuration

* Operating system: Ubuntu 16.06
* MATLAB: R2016b

**Comment by Noiredd** [comment]
Please read the checklist in the [issue template](https://github.com/BVLC/caffe/blob/master/.github/ISSUE_TEMPLATE.md) and complete your issue accordingly:
>read the guidelines and remove the first paragraph
>write a short summary and detailed steps to reproduce
>explain how solutions to related problems failed (tick if found none)
>fill system configuration
>attach relevant logs/config files (tick if not applicable)

**Comment by Noiredd** [comment]
Closing due to lack of updates. Feel free to reopen when you complete the details requested in the previous post.
