### ISSUE TITLE
Cmake could not find url for MSVC version

### ISSUE THREAD

**Issue by bit-scientist** [BVLC/caffe#6352]
```
The system cannot find the drive specified.
The system cannot find the drive specified.
INFO: ============================================================
INFO: Summary:
INFO: ============================================================
INFO: MSVC_VERSION               = 14
INFO: WITH_NINJA                 = 1
INFO: CMAKE_GENERATOR            = "Ninja"
INFO: CPU_ONLY                   = 0
INFO: CUDA_ARCH_NAME             = Auto
INFO: CMAKE_CONFIG               = Release
INFO: USE_NCCL                   = 0
INFO: CMAKE_BUILD_SHARED_LIBS    = 0
INFO: PYTHON_VERSION             = 2
INFO: BUILD_PYTHON               = 1
INFO: BUILD_PYTHON_LAYER         = 1
INFO: BUILD_MATLAB               = 0
INFO: PYTHON_EXE                 = "python"
INFO: RUN_TESTS                  = 0
INFO: RUN_LINT                   = 0
INFO: RUN_INSTALL                = 0
INFO: ============================================================
CMake Error at cmake/WindowsDownloadPrebuiltDependencies.cmake:40 (message):
  Could not find url for MSVC version = 1900 and Python version = 3.6.
Call Stack (most recent call first):
  CMakeLists.txt:77 (include)


-- Configuring incomplete, errors occurred!
See also "C:/Users/caffe/build/CMakeFiles/CMakeOutput.log".
ERROR: Configure failed
```
### Steps to reproduce
I am following [this ](https://github.com/BVLC/caffe/tree/windows) and when I run `scripts\build_win.cmd` I got the above errors.

### Tried solutions
I looked all the possible solutions and they are either not solved  or not clear to me.  **My cmake generator is Ninja while most people's generator is some version of Visual Studio.**

### System configuration

* Operating system: win 10, 64
* Compiler: Command line
* CUDA version (if applicable): none
* CUDNN version (if applicable): none
* BLAS: none
* Python version (if using pycaffe): Not using pycaffe, python 2.7
* MATLAB version (if using matcaffe):

**Comment by willyd** [comment]
Python 3.6 must be installed on your system and is the version picked up by CMake. The current windows branch does not support Python 3.6 yet.

Since you do not want pycaffe, you must remove the build directory, disable the python build with `set BUILD_PYTHON=0` in your terminal and execute the `scripts/build_win.cmd` script.

Otherwise, make sure CMake finds your Python 2.7 by specifying additional options on the CMake command line, like `PYTHON_EXECUTABLE`.

**Comment by git-sohib** [comment]
Thank you mister, after many trials I had deleted them all before I saw you reply and now it's fresh. Would you mind explaining what to do step by step? I think it would be useful for other folks as well. Right now I have Cmake only. For example, I don't know how to remove the build directory or disable python build, I haven't done them before. Or at least, could you refer to any link that explains all these things in detail? Thank you

**Comment by sungwuk** [comment]
if you don't mind can i ask you something? 
I also  CMake Error at 

> CMake Error at cmake/WindowsDownloadPrebuiltDependencies.cmake:40 (message):
  Could not find url for MSVC version = 1800 and Python version = 3.5.

> Call Stack (most recent call first):
  CMakeLists.txt:77 (include)

when I run scripts\build_win.cmd I got the errors.
## System configurations

- OS : window 10

- CUDA7.5

- cudnnv5 for cuda7.5 

- python = 3.5.2

**Comment by willyd** [comment]
@sungwuk  You need VS 2015 or 2017. You have 2013. 

You can also try my conda packages. See https://github.com/BVLC/caffe/issues/6569#issuecomment-432491851.

Closing since both situtations require rebuilding dependencies from source with caffe-builder.

**Comment by harsh-haria** [comment]
> Python 3.6 must be installed on your system and is the version picked up by CMake. The current windows branch does not support Python 3.6 yet.
> 
> Since you do not want pycaffe, you must remove the build directory, disable the python build with `set BUILD_PYTHON=0` in your terminal and execute the `scripts/build_win.cmd` script.
> 
> Otherwise, make sure CMake finds your Python 2.7 by specifying additional options on the CMake command line, like `PYTHON_EXECUTABLE`.

did not solve my case

**Comment by mehmetkurt20** [comment]
Are there any updates for this, Im using VS2022 and VS2019 in my computer, how to install caffe after I get could not find url for MSVC version = 1929 error? Also using python 3.5 but I dont build with python bcs I will use w/ c++.

**Comment by dragonQian** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by mehmetkurt20** [comment]
I understand, but could you help me now?
