### ISSUE TITLE
make runtest error

### ISSUE THREAD

**Issue by datamonday** [BVLC/caffe#6356]
ubuntu16.04+cuda8.0+cudnn7.1+opencv3.3.1+opencv_contribe3.3.1

when i run make runtest -j11,i got this error:

*** Aborted at 1524076044 (unix time) try "date -d @1524076044" if you are using GNU date ***
PC: @     0x7f57175d3532 cfree
*** SIGSEGV (@0x0) received by PID 21328 (TID 0x7f571a0d7b00) from PID 0; stack trace: ***
    @     0x7f57175844b0 (unknown)
    @     0x7f57175d3532 cfree
    @     0x7f57188dd8af google::protobuf::internal::DestroyDefaultRepeatedFields()
    @     0x7f57188dcb3b google::protobuf::ShutdownProtobufLibrary()
    @     0x7f56e90683b9 (unknown)
    @     0x7f5719fd9de7 (unknown)
    @     0x7f5717588ff8 (unknown)
    @     0x7f5717589045 exit
    @     0x7f571756f837 __libc_start_main
    @           0x408099 _start
    @                0x0 (unknown)
Makefile:530: recipe for target 'runtest' failed
make: *** [runtest] Segmentation fault (core dumped)

what's wrong? what shold i can do?thank you!

**Comment by Noiredd** [comment]
Please read the checklist in the [issue template](https://github.com/BVLC/caffe/blob/master/.github/ISSUE_TEMPLATE.md) and complete your issue accordingly:
>read the guidelines and remove the first paragraph
>write a short summary and detailed steps to reproduce
>explain how solutions to related problems failed (tick if found none)
>fill system configuration
>attach relevant logs/config files (tick if not applicable)

**Comment by Noiredd** [comment]
Closing due to lack of updates. Feel free to reopen when you complete the details requested in the previous post.

**Comment by KarthikKavinA** [comment]
Following is the solution for the above error:

please Install the libtcmalloc-minimal4 library
**sudo apt-get install libtcmalloc-minimal4**

Then, Export the path for the library in bashrc file.
**vim ~/.bashrc**  --- open bashrc file
**export LD_PRELOAD="/usr/lib/libtcmalloc_minimal.so.4"** ---- add this to the file
**source ~/.bashrc** ---- make it effective


It worked on Ubuntu 16.04
