### ISSUE TITLE
error "OpenCV 4.x+ requires enabled C++11 support

### ISSUE THREAD

**Issue by Dishcreate** [BVLC/caffe#6358]
[Makefile.config.log](https://github.com/BVLC/caffe/files/1932002/Makefile.config.log)
I have tired to install Caffe in Ubuntu 16.04 getting errors saying that ""OpenCV 4.x+ requires enabled C++11 support. 
I try different way to fix issue by changing python version and configuration file. But it did not work for me. 

System configuration

* Operating system: Ubuntu 16.04
* Compiler: g++ 5.4
* CUDA version (if applicable): 9.0
* CUDNN version (if applicable): 7.0.5
* OpenBLAS :  0.3.0
* Python version (if using pycaffe): 3.5
Can any one help on. I have attached my "Makefile.config" file here

**Comment by naibaf7** [comment]
Related: https://github.com/BVLC/caffe/issues/5262
I think it's time Caffe switched to C++11 as standard.
Related changes can be derived from the OpenCL Caffe branch, which has been on C++11 since the beginning of it's existence.

**Comment by Dishcreate** [comment]
Any update related with this issue?

**Comment by JohnWnx** [comment]
Hi, I'm experiencing the same issue too. May I know how did you fix this issue? Am I supposed to edit CMakeLists.txt or Makefile.config?

Thanks.
=============================================================================



(cvdev) john@john-H270N-WIFI:~/caffe$ make all
CXX src/caffe/util/io.cpp
/bin/sh: 1: cannot create .build_release/src/caffe/util/io.o.warnings.txt: Permission denied
In file included from /usr/local/include/opencv2/core.hpp:52:0,
                 from /usr/local/include/opencv2/core/core.hpp:48,
                 from src/caffe/util/io.cpp:6:
/usr/local/include/opencv2/core/cvdef.h:421:4: error: #error "OpenCV 4.x+ requires enabled C++11 support"
 #  error "OpenCV 4.x+ requires enabled C++11 support"
    ^
In file included from /usr/include/c++/5/array:35:0,
                 from /usr/local/include/opencv2/core/cvdef.h:426,
                 from /usr/local/include/opencv2/core.hpp:52,
                 from /usr/local/include/opencv2/core/core.hpp:48,
                 from src/caffe/util/io.cpp:6:
/usr/include/c++/5/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support \

**Comment by Dishcreate** [comment]
@JohnWnx 
You have to add follow flag while you prepare cmake ..
-DCMAKE_CXX_FLAGS="-std=c++11

**Comment by swoodford** [comment]
@Dishcreate I think what you meant was:
`-DCMAKE_CXX_FLAGS="-std=c++11"`
(missing end quote)

**Comment by adong7639** [comment]
In CmakeList.txt add 
set(CMAKE_CXX_STANDARD 14)

**Comment by Cartucho** [comment]
I solved it by adding to the CMakeLists.txt the following:
```
cmake_minimum_required(VERSION 3.1)
# Enable C++11
set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_STANDARD_REQUIRED TRUE)
```

**Comment by aidanlw17** [comment]
For anyone still having this issue, solved with the top answer here:
https://stackoverflow.com/questions/10851247/how-do-i-activate-c-11-in-cmake
