### ISSUE TITLE
caffe digits ERROR: error code -11

### ISSUE THREAD

**Issue by zhong-xin** [BVLC/caffe#6363]
## Important - read before submitting
ERROR: error code -11

Setting up train-data
Top shape: 64 3 180 320 (11059200)
Top shape: 64 (64)
Memory required for data: 44237056
Creating layer data_aug
        

### System configuration

* Operating system: ubuntu 16.04
* Compiler: 
* CUDA version (if applicable): 9.0
* CUDNN version (if applicable): 9.0.176
* BLAS: 
* Python version (if using pycaffe): python3.5.2
* MATLAB version (if using matcaffe): 

### Issue checklist

- [ ] read the guidelines and removed the first paragraph
- [ ] written a short summary and detailed steps to reproduce
- [ ] explained how solutions to related problems failed (tick if found none)
- [ ] filled system configuration
- [ ] attached relevant logs/config files (tick if not applicable)

**Comment by twmht** [comment]
Steps to reproduce?

**Comment by Noiredd** [comment]
Consider asking this on [DIGITS forum](https://groups.google.com/forum/#!forum/digits-users).
