### ISSUE TITLE
caffe installation issue 

### ISSUE THREAD

**Issue by israrulhaq07** [BVLC/caffe#6400]
LD -o .build_release/lib/libcaffe.so.1.0.0-rc3
/usr/bin/ld: cannot find -lsnappy
/usr/bin/ld: cannot find -lcblas
/usr/bin/ld: cannot find -latlas
collect2: error: ld returned 1 exit status
Makefile:566: recipe for target '.build_release/lib/libcaffe.so.1.0.0-rc3' failed
make: *** [.build_release/lib/libcaffe.so.1.0.0-rc3] Error 1

**Comment by CDLuminate** [comment]
Several dependency libraries are missing on your system. Please refer the official installation guide.

**Comment by Noiredd** [comment]
Please start by reading the [installation instructions](http://caffe.berkeleyvision.org/installation.html) and ask further questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) list.

**Comment by lrakesh24** [comment]
hello all iam installing the caffe on ubuntu installed all the dependency but i am getting the error -lopencv, but i am installed the opencv also please sujjest me.
Error log is given below 

LD -o .build_release/lib/libcaffe.so.1.0.0
/usr/bin/ld: cannot find -lopencv_imgcodecs
collect2: error: ld returned 1 exit status
Makefile:582: recipe for target '.build_release/lib/libcaffe.so.1.0.0' failed
make: *** [.build_release/lib/libcaffe.so.1.0.0] Error 1

**Comment by weilanShi** [comment]
I have also encountered this problem. Have you solved it


> hello all iam installing the caffe on ubuntu installed all the dependency but i am getting the error -lopencv, but i am installed the opencv also please sujjest me.
> Error log is given below
> 
> LD -o .build_release/lib/libcaffe.so.1.0.0
> /usr/bin/ld: cannot find -lopencv_imgcodecs
> collect2: error: ld returned 1 exit status
> Makefile:582: recipe for target '.build_release/lib/libcaffe.so.1.0.0' failed
> make: *** [.build_release/lib/libcaffe.so.1.0.0] Error 1



I have also encountered the same problem. Have you solved it

**Comment by lrakesh24** [comment]
hi,

Sorry for the late response,

Can you just share me the complete log.


Regards
Rakesh L
________________________________
