### ISSUE TITLE
pycaffe error: 'module' object has no attribute 'Layer'

### ISSUE THREAD

**Issue by Vivianyzw** [BVLC/caffe#6402]
I have changed "WITH_PYTHON_LAYER := 1",make pycaffe, abd add python path to /etc/profile so that I can import caffe successfully. 
But when I add new python layer like this:
```
import caffe  
import numpy as np  
from PIL import Image  
import random
class SBDDSegDataLayer(caffe.Layer):  
    def setup(self, bottom, top):   
```
it occured the error as follows:
```
I0521 17:35:15.180217 10861 layer_factory.hpp:77] Creating layer data
Traceback (most recent call last):
  File "/mnt/data1/caffe/python/voc_layer.py", line 8, in <module>
    class SBDDSegDataLayer(caffe.Layer):
AttributeError: 'module' object has no attribute 'Layer'
```
I am really confused of this, and I found no solution to solve it on the Internet. 
Could you please tell me how to deal with it? Thanks in advance!

**Comment by Noiredd** [comment]
I recommend reading Rafael Padilha's guide on [Python layer](https://gist.github.com/rafaspadilha/a67008cc3bd93bc2c1fc368c363ee363), especially the prototxt example. If you're still finding problems, please ask on [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) posting the details of your issue, especially the prototxt (as this seems to be the root of your issue).
