### ISSUE TITLE
Interoperability with Other Frameworks via Python Layer (Pytorch/Tensorflow/etc. layer -> Caffe layer)

### ISSUE THREAD

**Issue by wzb1005** [BVLC/caffe#6404]
Can the layers defined with  PyTorch/TensorFlow library been used in Caffe（in prototxt file)? 
For example., the layer is defined with Python language using PyTorch  library.
Can this be implemented with a Python layer in Caffe?
Thanks！

**Comment by naibaf7** [comment]
Yes that should actually be possible, however not recommended because data needs to be copied from CPU to GPU and back when going to python layers. A better approach would be to recreate the layer within Caffe and stick with just 1 deep learning library.

**Comment by shelhamer** [comment]
This can be done with sufficient hacking since #5904 exposed the GPU pointers as hinted at in https://github.com/BVLC/caffe/pull/5904#issuecomment-328621561.
