### ISSUE TITLE
Possible to change Caffe to support 2 or 3 sets of labels? (Data Layer)

### ISSUE THREAD

**Issue by soulslicer** [BVLC/caffe#6407]
As above,

Is it possible to modify caffe so that instead of supporting only 1 label type, it can support 2 or 3 labels of different resolutions/shapes. 

Is it just a matter of modify base_data_layer.cpp?

**Comment by naibaf7** [comment]
If you feed the data using a python script, you can do that already. It's usually the better choice than doing it with the data layers.

**Comment by soulslicer** [comment]
Ic, I am using a C++ custom data layer at this point though. And the Batch object seems to only provide a  data_ object and a label_ object.
