### ISSUE TITLE
Make test failed

### ISSUE THREAD

**Issue by SaddamRaut** [BVLC/caffe#6413]
make test
CXX src/caffe/test/test_gradient_based_solver.cpp
CXX src/caffe/test/test_memory_data_layer.cpp
CXX src/caffe/test/test_argmax_layer.cpp
CXX src/caffe/test/test_hdf5_output_layer.cpp
CXX src/caffe/test/test_sigmoid_cross_entropy_loss_layer.cpp
CXX src/caffe/test/test_batch_reindex_layer.cpp
CXX src/caffe/test/test_solver.cpp
CXX src/caffe/test/test_dummy_data_layer.cpp
CXX src/caffe/test/test_multinomial_logistic_loss_layer.cpp
CXX src/caffe/test/test_detectnet_transform.cpp
CXX src/caffe/test/test_mvn_layer.cpp
CXX src/caffe/test/test_crop_layer.cpp
CXX src/caffe/test/test_slice_layer.cpp
CXX src/caffe/test/test_stochastic_pooling.cpp
CXX src/caffe/test/test_hinge_loss_layer.cpp
CXX src/caffe/test/test_benchmark.cpp
CXX src/caffe/test/test_db.cpp
In file included from src/caffe/test/test_db.cpp:5:0:
src/caffe/test/test_db.cpp: In member function ‘virtual void caffe::DBTest_TestSeekToFirst_Test<gtest_TypeParam_>::TestBody()’:
src/caffe/test/test_db.cpp:89:35: error: no matching function for call to ‘caffe::db::Cursor::parse(caffe::Datum*)’
   EXPECT_TRUE(cursor->parse(&datum));
                                   ^
./src/gtest/gtest.h:7859:34: note: in definition of macro ‘GTEST_TEST_BOOLEAN_’
       ::testing::AssertionResult(expression)) \
                                  ^
src/caffe/test/test_db.cpp:89:3: note: in expansion of macro ‘EXPECT_TRUE’
   EXPECT_TRUE(cursor->parse(&datum));
   ^
src/caffe/test/test_db.cpp:89:35: note: candidate is:
   EXPECT_TRUE(cursor->parse(&datum));
                                   ^
./src/gtest/gtest.h:7859:34: note: in definition of macro ‘GTEST_TEST_BOOLEAN_’
       ::testing::AssertionResult(expression)) \
                                  ^
src/caffe/test/test_db.cpp:89:3: note: in expansion of macro ‘EXPECT_TRUE’
   EXPECT_TRUE(cursor->parse(&datum));
   ^
In file included from src/caffe/test/test_db.cpp:9:0:
./include/caffe/util/db.hpp:23:16: note: virtual bool caffe::db::Cursor::parse(void*, caffe::DatumTypeInfo) const
   virtual bool parse(void* datum, DatumTypeInfo datum_type_info) const = 0;
                ^
./include/caffe/util/db.hpp:23:16: note:   candidate expects 2 arguments, 1 provided
In file included from src/caffe/test/test_db.cpp:5:0:
src/caffe/test/test_db.cpp: In member function ‘virtual void caffe::DBTest_TestKeyValue_Test<gtest_TypeParam_>::TestBody()’:
src/caffe/test/test_db.cpp:103:35: error: no matching function for call to ‘caffe::db::Cursor::parse(caffe::Datum*)’
   EXPECT_TRUE(cursor->parse(&datum));
                                   ^
./src/gtest/gtest.h:7859:34: note: in definition of macro ‘GTEST_TEST_BOOLEAN_’
       ::testing::AssertionResult(expression)) \
                                  ^
src/caffe/test/test_db.cpp:103:3: note: in expansion of macro ‘EXPECT_TRUE’
   EXPECT_TRUE(cursor->parse(&datum));
   ^
src/caffe/test/test_db.cpp:103:35: note: candidate is:
   EXPECT_TRUE(cursor->parse(&datum));
                                   ^
./src/gtest/gtest.h:7859:34: note: in definition of macro ‘GTEST_TEST_BOOLEAN_’
       ::testing::AssertionResult(expression)) \
                                  ^
src/caffe/test/test_db.cpp:103:3: note: in expansion of macro ‘EXPECT_TRUE’
   EXPECT_TRUE(cursor->parse(&datum));
   ^
In file included from src/caffe/test/test_db.cpp:9:0:
./include/caffe/util/db.hpp:23:16: note: virtual bool caffe::db::Cursor::parse(void*, caffe::DatumTypeInfo) const
   virtual bool parse(void* datum, DatumTypeInfo datum_type_info) const = 0;
                ^
./include/caffe/util/db.hpp:23:16: note:   candidate expects 2 arguments, 1 provided
In file included from src/caffe/test/test_db.cpp:5:0:
src/caffe/test/test_db.cpp:111:35: error: no matching function for call to ‘caffe::db::Cursor::parse(caffe::Datum*)’
   EXPECT_TRUE(cursor->parse(&datum));
                                   ^
./src/gtest/gtest.h:7859:34: note: in definition of macro ‘GTEST_TEST_BOOLEAN_’
       ::testing::AssertionResult(expression)) \
                                  ^
src/caffe/test/test_db.cpp:111:3: note: in expansion of macro ‘EXPECT_TRUE’
   EXPECT_TRUE(cursor->parse(&datum));
   ^
src/caffe/test/test_db.cpp:111:35: note: candidate is:
   EXPECT_TRUE(cursor->parse(&datum));
                                   ^
./src/gtest/gtest.h:7859:34: note: in definition of macro ‘GTEST_TEST_BOOLEAN_’
       ::testing::AssertionResult(expression)) \
                                  ^
src/caffe/test/test_db.cpp:111:3: note: in expansion of macro ‘EXPECT_TRUE’
   EXPECT_TRUE(cursor->parse(&datum));
   ^
In file included from src/caffe/test/test_db.cpp:9:0:
./include/caffe/util/db.hpp:23:16: note: virtual bool caffe::db::Cursor::parse(void*, caffe::DatumTypeInfo) const
   virtual bool parse(void* datum, DatumTypeInfo datum_type_info) const = 0;
                ^
./include/caffe/util/db.hpp:23:16: note:   candidate expects 2 arguments, 1 provided
make: *** [.build_release/src/caffe/test/test_db.o] Error 1

**Comment by CJRobey** [comment]
I'm having this exact same issue.
a0232989local@ulb0232989:~/caffe-jacinto$ make test
CXX src/caffe/test/test_convolution_layer.cpp
CXX src/caffe/test/test_db.cpp
In file included from src/caffe/test/test_db.cpp:5:0:
src/caffe/test/test_db.cpp: In member function ‘virtual void caffe::DBTest_TestSeekToFirst_Test<gtest_TypeParam_>::TestBody()’:
src/caffe/test/test_db.cpp:89:35: error: no matching function for call to ‘caffe::db::Cursor::parse(caffe::Datum*)’
   EXPECT_TRUE(cursor->parse(&datum));
                                   ^
./src/gtest/gtest.h:7859:34: note: in definition of macro ‘GTEST_TEST_BOOLEAN_’
       ::testing::AssertionResult(expression)) \
                                  ^
src/caffe/test/test_db.cpp:89:3: note: in expansion of macro ‘EXPECT_TRUE’
   EXPECT_TRUE(cursor->parse(&datum));
   ^
src/caffe/test/test_db.cpp:89:35: note: candidate is:
   EXPECT_TRUE(cursor->parse(&datum));
                                   ^
./src/gtest/gtest.h:7859:34: note: in definition of macro ‘GTEST_TEST_BOOLEAN_’
       ::testing::AssertionResult(expression)) \
                                  ^
src/caffe/test/test_db.cpp:89:3: note: in expansion of macro ‘EXPECT_TRUE’
   EXPECT_TRUE(cursor->parse(&datum));
   ^
In file included from src/caffe/test/test_db.cpp:9:0:
./include/caffe/util/db.hpp:23:16: note: virtual bool caffe::db::Cursor::parse(void*, caffe::DatumTypeInfo) const
   virtual bool parse(void* datum, DatumTypeInfo datum_type_info) const = 0;
                ^
./include/caffe/util/db.hpp:23:16: note:   candidate expects 2 arguments, 1 provided
In file included from src/caffe/test/test_db.cpp:5:0:
src/caffe/test/test_db.cpp: In member function ‘virtual void caffe::DBTest_TestKeyValue_Test<gtest_TypeParam_>::TestBody()’:
src/caffe/test/test_db.cpp:103:35: error: no matching function for call to ‘caffe::db::Cursor::parse(caffe::Datum*)’
   EXPECT_TRUE(cursor->parse(&datum));
                                   ^
./src/gtest/gtest.h:7859:34: note: in definition of macro ‘GTEST_TEST_BOOLEAN_’
       ::testing::AssertionResult(expression)) \
                                  ^
src/caffe/test/test_db.cpp:103:3: note: in expansion of macro ‘EXPECT_TRUE’
   EXPECT_TRUE(cursor->parse(&datum));
   ^
src/caffe/test/test_db.cpp:103:35: note: candidate is:
   EXPECT_TRUE(cursor->parse(&datum));
                                   ^
./src/gtest/gtest.h:7859:34: note: in definition of macro ‘GTEST_TEST_BOOLEAN_’
       ::testing::AssertionResult(expression)) \
                                  ^
src/caffe/test/test_db.cpp:103:3: note: in expansion of macro ‘EXPECT_TRUE’
   EXPECT_TRUE(cursor->parse(&datum));
   ^
In file included from src/caffe/test/test_db.cpp:9:0:
./include/caffe/util/db.hpp:23:16: note: virtual bool caffe::db::Cursor::parse(void*, caffe::DatumTypeInfo) const
   virtual bool parse(void* datum, DatumTypeInfo datum_type_info) const = 0;
                ^
./include/caffe/util/db.hpp:23:16: note:   candidate expects 2 arguments, 1 provided
In file included from src/caffe/test/test_db.cpp:5:0:
src/caffe/test/test_db.cpp:111:35: error: no matching function for call to ‘caffe::db::Cursor::parse(caffe::Datum*)’
   EXPECT_TRUE(cursor->parse(&datum));
                                   ^
./src/gtest/gtest.h:7859:34: note: in definition of macro ‘GTEST_TEST_BOOLEAN_’
       ::testing::AssertionResult(expression)) \
                                  ^
src/caffe/test/test_db.cpp:111:3: note: in expansion of macro ‘EXPECT_TRUE’
   EXPECT_TRUE(cursor->parse(&datum));
   ^
src/caffe/test/test_db.cpp:111:35: note: candidate is:
   EXPECT_TRUE(cursor->parse(&datum));
                                   ^
./src/gtest/gtest.h:7859:34: note: in definition of macro ‘GTEST_TEST_BOOLEAN_’
       ::testing::AssertionResult(expression)) \
                                  ^
src/caffe/test/test_db.cpp:111:3: note: in expansion of macro ‘EXPECT_TRUE’
   EXPECT_TRUE(cursor->parse(&datum));
   ^
In file included from src/caffe/test/test_db.cpp:9:0:
./include/caffe/util/db.hpp:23:16: note: virtual bool caffe::db::Cursor::parse(void*, caffe::DatumTypeInfo) const
   virtual bool parse(void* datum, DatumTypeInfo datum_type_info) const = 0;
                ^
./include/caffe/util/db.hpp:23:16: note:   candidate expects 2 arguments, 1 provided
make: *** [.build_release/src/caffe/test/test_db.o] Error 1

**Comment by CJRobey** [comment]
Figured it out (at least for my issue). The test_db module is checking for your OpenCV version. So if you haven't downloaded and installed OpenCV yet, it will fail because that is a dependency. There are two solutions. 
1. Get OpenCV up and running.
2. Edit the Makefile.configure file
 - uncomment the line that says USE_OPENCV := 0

**Comment by SaddamRaut** [comment]
@CJRobey 
I building caffe with opencv 3.0.0 but still getting same error

**Comment by shelhamer** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
