### ISSUE TITLE
src/caffe/util/im2col.cu:3:28: fatal error: caffe/common.hpp: No such file or directory

### ISSUE THREAD

**Issue by ElegantLin** [BVLC/caffe#6416]
### Issue summary
CXX src/caffe/internal_thread.cpp
NVCC src/caffe/util/im2col.cu
src/caffe/util/im2col.cu:3:28: fatal error: caffe/common.hpp: No such file or directory
 #include "caffe/common.hpp"
                            ^
compilation terminated.
Makefile:594: recipe for target '.build_release/cuda/src/caffe/util/im2col.o' failed
make: *** [.build_release/cuda/src/caffe/util/im2col.o] Error 1

### Tried solutions
I haven't found possible solutions and I found common.hpp in the directory.

### System configuration

* Operating system: Ubuntu 18.04
* Compiler: gcc 6.4.0
* CUDA version (if applicable): 9.0
* CUDNN version (if applicable): 7
* BLAS: 
* Python version (if using pycaffe): yes
* MATLAB version (if using matcaffe): no

**Comment by shelhamer** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

**Comment by Isaamarod** [comment]
@ElegantLin  How did you resolve it?
I have this error:
src/caffe/util/math_functions.cu:8:28: fatal error: caffe/common.hpp: No such file or directory
compilation finished
Makefile:594:
'.build_release/cuda/src/caffe/util/math_functions.o'
make: *** [.build_release/cuda/src/caffe/util/math_functions.o] Error 1
