### ISSUE TITLE
make RunTest Error

### ISSUE THREAD

**Issue by danielanojan** [BVLC/caffe#6418]
When i Make runtest the libcudart.so error occurs 

.build_release/tools/caffe: error while loading shared libraries: libcudart.so.9.0: cannot open shared object file: No such file or directory
make: *** [runtest] Error 127
(workspace) [anojan@localhost PSPNET-cudnn5]$ source $HOME/.bashrc
(workspace) [anojan@localhost PSPNET-cudnn5]$ vi $HOME/.bashrc
(workspace) [anojan@localhost PSPNET-cudnn5]$ source $HOME/.bashrc
(workspace) [anojan@localhost PSPNET-cudnn5]$ sudo make runtest -j8
.build_release/tools/caffe

and i solved using 
sudo LD_LIBRARY_PATH=/home/anojan/workspace/cuda_install/lib64make runtest

once i use it i get libmatio.so error which is different lib folder(/usr/local/lib)

i tried adding LD_LIBRARY_PATHS in .bashrc but i still get the error

how to solve this?

**Comment by shelhamer** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
