### ISSUE TITLE
OpenCL Caffe - clCreateSubBuffer Error 13 only on AMD

### ISSUE THREAD

**Issue by soulslicer** [BVLC/caffe#6422]
## Important - read before submitting

*Please read the [guidelines for contributing](https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md) before submitting this issue!*

*Please do not post installation, build, usage, or modeling questions, or other requests for help to Issues.*
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead.
This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

### Issue summary

I am using the Caffe C++ OpenCL API. I have taken a GPU Ptr and have attempted to slice it with the clCreateSubBuffer function. This works perfectly in nvidia opencl. However, it crashes with 

> clCreateSubBuffer : Unknown OpenCL Error (-13)

in my code. is this opencl dev familiar with why this might happen on AMD? The actual forward pass of the net works, just that i cant slice the gpu ptr.

### Steps to reproduce

--

### Tried solutions

--

### System configuration

* Operating system: 16.04
* Compiler: 5.4
* OpenCL 2.0 on Vega RX 560 4GB

**Comment by naibaf7** [comment]
Might we see some of the code triggering the issue? What OpenCL driver for AMD are you using? Recommended for Polaris and Vega are ROCm 1.8. Any other OpenCL implementations from AMD I cannot guarantee as working "as intended".

**Comment by soulslicer** [comment]
Okay,

This took me alot of effort, but I finally managed to isolate it. I think its a problem with OpenCL Caffe. I am using a Vega rX 560 with ROCm. I installed ROCm from https://rocm.github.io/ROCmInstall.html

This is a net I am trying to load : https://paste.ee/p/gUcpU

This is the example I am trying to run: https://github.com/soulslicer/openpose/blob/amd_fix/examples/tests/clTest.cpp

As you can see in the code, I load a net, read a blob, and attempt to create opencl subbuffers of the blobs. if i read any of the blobs all the way to "relu2_2" it works fine. But the moment I get past the 2nd pooling, it crashes with the above error.

This works perfectly on Nvidia GPU. not sure why this is happening, and only too for layers with that resolution

**Comment by soulslicer** [comment]
So the meaning behind this error is:

CL_MISALIGNED_SUB_BUFFER_OFFSET if buffer is a sub-buffer object and offset specified when the sub-buffer object is created is not aligned to CL_DEVICE_MEM_BASE_ADDR_ALIGN value for device associated with queue. 

I happen to attempt to need to slice a blob of size [1x66x46x46]. When I slice with an offset 0 and size [46x46], its fine, but when I move to the next offset of 1 to see the next channel, it crashes. So what does this really mean?

**Comment by naibaf7** [comment]
It means you can't slice buffers in whatever way you like on AMD's OpenCL implementation, but only on certain aligned addresses (like every 8 bytes / 64 bits, most likely...)
This was why buffer slicing is not used at all in OpenCL Caffe, it usually leads to such problems.

**Comment by soulslicer** [comment]
Ic. Okay the specific problem I have is that I have a blob of size [1x57x46x46] of float, and I am trying to iterate each channel and apply an operation on it directly on the GPU. On my NVIDIA Card, its CL_DEVICE_MEM_BASE_ADDR_ALIGN is 4096, while for AMD is 1024 bits.

This means the size of my offset per iteration is 0, 1 * 46*46 * 4(float) * 8 = 67712,  2 * 46*46 * 4(float) * 8 = 135424 etc. Neither one of these values is a multiple of 4096 or 1024. Yet it still works on NVIDIA.

If this is an AMD specific limitation, then how can one actually go around this? Is subbuffer slicing not possible at all then for AMD?

**Comment by naibaf7** [comment]
I'm not sure without getting a response from an AMD employee such as @gstoner.
Test if it works on AMD when aligned to 1024bits. If that's the case, there isn't an easy way to get around this. In that case, I would recommend you build your code in a way that can either apply A.) offsets and strides to operators instead of slicing (and then pass the whole buffer to your operator), or B.) you do memory copies into a new buffer and apply the operator there.

I would generally recommend A.) and only use B.) if all else fails.

**Comment by soulslicer** [comment]
Youre right about the alignment issue. If I have a blob with channels that divide by 1024 correctly it works. For example [96*96*4] is divisible by 128 bytes (1024 bits). So that doesnt crash.

Are you suggest to do the channel wide operations directly in the kernel instead of slicing them? So instead of N threads where N*46*46 is my blob size, I have N846*46 threads where each thread operates on a specific channel, width and height?

**Comment by naibaf7** [comment]
It should not be any slower if you do it correctly. This requires, depending on the operation, careful tuning of the kernel workgroup sizes. But if your operation is O(c*n), you should not have any trouble reaching reasonable performance. If it's an O(c*n^2) or O(c*n^3) operation, please have a look at how LibDNN chooses work group sizes and sets kernel hints to gain ~60% of the performance of hand-tuned architecture-specific kernels: https://github.com/naibaf7/caffe/tree/master/src/caffe/libdnn

Having the kernel run N times on different slices is usually not the way to do it.

**Comment by soulslicer** [comment]
thx for the inputs. will change my code accordingly.
