### ISSUE TITLE
Add project topics to aid discoverability in GitHub browse

### ISSUE THREAD

**Issue by muendelezaji** [BVLC/caffe#6423]
### Issue summary
Hi, just a simple request/suggestion to [add topics](https://blog.github.com/2017-01-31-introducing-topics/) to aid discoverability.
Caffe does not appear in topic results under any ML-related labels despite having enough stars to rank in the top 5 for both [machine-learning](https://github.com/topics/machine-learning) and [deep-learning](https://github.com/topics/deep-learning).

### Steps to reproduce
--

### System configuration
any

**Comment by shelhamer** [comment]
Done! I added `machine-learning`, `deep-learning`, and `vision`. Thanks for pointing out topics—I did not catch the post when these were rolled out.
