### ISSUE TITLE
cublas_v2.h file missing

### ISSUE THREAD

**Issue by Anjali-iit8** [BVLC/caffe#6428]
### Issue summary
I downloaded and built the caffe CPU_ONLY but when I am building my code it is giving error:
"cublas_v2.h file not found". I have correctly edited the Makefile.config file and have followed closely the tutorial.

### Tried solutions
I tried giving cmake command for CPU_ONLY=1.
I also added the line add_definitions = (-DCPU_ONLY=1) in the CMakeLists.txt

* Operating system: Ubuntu 16.04
* Compiler: sds++
* CUDA version (if applicable): - 
* CUDNN version (if applicable): - 
* BLAS: openblas
* Python version (if using pycaffe): 2.7 
* MATLAB version (if using matcaffe): -

**Comment by Thomio-Watanabe** [comment]
@Anjali-iit8
I just built the latest caffe with openblas and it is working.
Did you tried this ?

    mkdir build && cd build
    cmake .. -DCPU_ONLY=ON -DBLAS=Open

**Comment by Anjali-iit8** [comment]
Yes,
I also build it using cmake and it is working. 
Thanks

**Comment by Noiredd** [comment]
Closing, assuming the given answer helped. If not, please reopen and provide further details, especially how the suggested solution failed.
