### ISSUE TITLE
dl.caffe.berkeleyvision.org down?

### ISSUE THREAD

**Issue by VongolaXIman** [BVLC/caffe#6430]
http://dl.caffe.berkeleyvision.org/bvlc_alexnet.caffemodel
cannot download this model@@

**Comment by deadprogram** [comment]
It appears the subdomain `dl.caffe.berkeleyvision.org` is `ERR_NAME_NOT_RESOLVED` and hence currently unreachable. DNS error, perhaps?

**Comment by clarkema** [comment]
I've just come across this while trying to get up and running with Intel's Movidius stick.  The `dl` subdomain is referenced in all sorts of documentation and in Caffe's own model download scripts, but doesn't seem to exist any more.

**Comment by shelhamer** [comment]
Hey all, this is a temporary issue and the site will be back up shortly! Sorry for the downtime.

**Comment by shelhamer** [comment]
It's back as of yesterday.

**Comment by TFotakis** [comment]
Hi there all,
Is the server down again, or are the .caffemodels no longer available?

**Comment by srishkee** [comment]
I'm facing the same issue. I've tried all sorts of methods but the website just won't load.

**Comment by phucducnguyen** [comment]
is the server down again today?

**Comment by dragonQian** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
