### ISSUE TITLE
Error while running "make runtest"  ( caffe related) on Redhat6.5

### ISSUE THREAD

**Issue by shokroll** [BVLC/caffe#645]
I am using  Nvidia version 331.89 and cudatoolkit is 5.5.22. I need to run caffe for doing some experiment on imageNet datasets. I went through all the mentioned steps in the instalation guide. when I say :  make runtest 
I get the following errors:
.
.
.

E0708 15:00:30.700234  3751 common.cpp:60] Curand not available. Skipping setting the curand seed.
E0708 15:00:30.700266  3751 common.cpp:60] Curand not available. Skipping setting the curand seed.
E0708 15:00:30.700299  3751 common.cpp:60] Curand not available. Skipping setting the curand seed.
E0708 15:00:30.700331  3751 common.cpp:60] Curand not available. Skipping setting the curand seed.
[       OK ] HingeLossLayerTest/0.TestGradientGPU (12 ms)
[----------] 2 tests from HingeLossLayerTest/0 (70 ms total)

[----------] 3 tests from PaddingLayerUpgradeTest
[ RUN      ] PaddingLayerUpgradeTest.TestSimple
[       OK ] PaddingLayerUpgradeTest.TestSimple (1 ms)
[ RUN      ] PaddingLayerUpgradeTest.TestTwoTops
[       OK ] PaddingLayerUpgradeTest.TestTwoTops (0 ms)
[ RUN      ] PaddingLayerUpgradeTest.TestImageNet
[       OK ] PaddingLayerUpgradeTest.TestImageNet (1 ms)
[----------] 3 tests from PaddingLayerUpgradeTest (2 ms total)

[----------] 10 tests from LRNLayerTest/0, where TypeParam = float
[ RUN      ] LRNLayerTest/0.TestGPUForwardAcrossChannels
E0708 15:00:30.702508  3751 common.cpp:60] Curand not available. Skipping setting the curand seed.
F0708 15:00:30.702576  3751 syncedmem.cpp:53] Check failed: error == cudaSuccess (30 vs. 0)  unknown error
**\* Check failure stack trace: ***
    @     0x7f501e14ccbd  google::LogMessage::Fail()
    @     0x7f501e150d77  google::LogMessage::SendToLog()
    @     0x7f501e14eb99  google::LogMessage::Flush()
    @     0x7f501e14ee9d  google::LogMessageFatal::~LogMessageFatal()
    @           0x588bc8  caffe::SyncedMemory::to_gpu()
    @           0x588819  caffe::SyncedMemory::gpu_data()
    @           0x5b5ddd  caffe::Blob<>::gpu_data()
    @           0x5c5d69  caffe::LRNLayer<>::CrossChannelForward_gpu()
    @           0x5c61de  caffe::LRNLayer<>::Forward_gpu()
    @           0x4543ef  caffe::Layer<>::Forward()
    @           0x4929d7  caffe::LRNLayerTest_TestGPUForwardAcrossChannels_Test<>::TestBody()
    @           0x53e87d  testing::internal::HandleExceptionsInMethodIfSupported<>()
    @           0x530661  testing::Test::Run()
    @           0x530747  testing::TestInfo::Run()
    @           0x530887  testing::TestCase::Run()
    @           0x53578f  testing::internal::UnitTestImpl::RunAllTests()
    @           0x53e42d  testing::internal::HandleExceptionsInMethodIfSupported<>()
    @           0x52fc8a  testing::UnitTest::Run()
    @           0x442ce1  main
    @     0x7f501af6dd1d  __libc_start_main
    @           0x442a49  (unknown)
make: **\* [runtest] Aborted

I wanted to see if I could ignore this problem and continue without it. So, I wanted to train  MNIST demo with caffe. I followed the steps and after running "./train_lenet.sh" I have recieved error again as below:

F0708 15:01:27.331490  3942 syncedmem.cpp:47] Check failed: error == cudaSuccess (30 vs. 0)  unknown error
**\* Check failure stack trace: ***
    @     0x7f5d66fbecbd  google::LogMessage::Fail()
    @     0x7f5d66fc2d77  google::LogMessage::SendToLog()
    @     0x7f5d66fc0b99  google::LogMessage::Flush()
    @     0x7f5d66fc0e9d  google::LogMessageFatal::~LogMessageFatal()
    @           0x44f578  caffe::SyncedMemory::to_gpu()
    @           0x44f1a9  caffe::SyncedMemory::mutable_gpu_data()
    @           0x449a7d  caffe::Blob<>::mutable_gpu_data()
    @           0x484287  caffe::DataLayer<>::Forward_gpu()
    @           0x455552  caffe::Net<>::ForwardPrefilled()
    @           0x4376ba  caffe::Solver<>::Test()
    @           0x438e64  caffe::Solver<>::Solve()
    @           0x412de4  main
    @     0x7f5d63ddfd1d  __libc_start_main
    @           0x412bd9  (unknown)
./train_lenet.sh: line 5:  3942 Aborted                 GLOG_logtostderr=1 $TOOLS/train_net.bin lenet_solver.prototxt

Does anyone manged to run the caffe on REDHAT correctly?

**Comment by urinieto** [comment]
I had the same issue and I fixed it by upgrading CUDA from 5.5 to 7.0.
