### ISSUE TITLE
./examples/mnist/create_mnist.sh Issue 

### ISSUE THREAD

**Issue by nicogamer6** [BVLC/caffe#6457]
Hello, 
i run Caffe on CPU_ONLY, 
I haven't errors before this one, and i had all to the path, I imported caffe well.
I have this problem and i didn't find why : 
![image](https://user-images.githubusercontent.com/39381964/42507148-6303528a-8444-11e8-914c-fc3268bf67bf.png)
Can someone help me ? 

Thank you

**Comment by Noiredd** [comment]
Please do not ask double questions. One thread on [caffe-users](https://groups.google.com/forum/#!topic/caffe-users/dR05kk9enuU) is enough.
