### ISSUE TITLE
opendlide causes caffe to crash

### ISSUE THREAD

**Issue by ihuale** [BVLC/caffe#6464]
### Issue summary
hello, I found an error when I was using caffe.
I tried to put caffe in my program，my program uses openslide to read images and display them. 
I compiled caffe correctly and put the classification.cpp in my program(remove the main function), and then my program was successfully compiled, but when I try to start the program it failed to start and with the messages:
![image](https://user-images.githubusercontent.com/18436096/42681023-2684fc06-86b9-11e8-86df-6cf1943a046b.png)
it means: 
Unable to locate program input point openslide_close on dynamic link library MPI.exe

and the console output:
![image](https://user-images.githubusercontent.com/18436096/42681063-439b9f34-86b9-11e8-997d-9cb5a02fa712.png)
the bottom fivelines it means: 
Exception thrown at 0x00007FFC6B769968(ntdll.dll): 0xc0000139: Entry Point Not Found.
Thread 0x13f0 has exited, return value is -1073741511 (0xc0000139).
Thread 0x35cc has exited, return value is -1073741511 (0xc0000139).
Thread 0x45ec has exited, return value is -1073741511 (0xc0000139).
Program"[11996]MPI.exe " has exited, return value is -1073741511 (0xc0000139) 'Entry Point Not Found'.

### Steps to reproduce
1.Put cafffe and openslide in the same project and configure them correctly
2.Use the api provided by openslide,  e.g. : “openslide_detect_vendor()”
3.successfully compiled
4.run output.exe

### Tried solutions
I tried the following methods:
(1)use the release version you provided and it was configured correctly, but still the same error.

(2)creat a new project, write a sample api from opensilde it run successed, and then I put the classification.cpp into it and configure it correctly but still the same error.

(3)creat a new project, put the classification.cpp into it and successfully ran it. and then add openslide and write a sample api from opensilde, successfully compiled it, but still the same error......

(4)reapt abrove steps on vs2013, failed again......

(4)used the another computer to reapt abrove steps,but it still the same error.....

### System configuration

* Operating system: win10
* Compiler: vs2015 and vs2013
* CUDA version (if applicable): cuda_8.0.61_win10
* CUDNN version (if applicable): cudnn-8.0-windows10-x64-v7.1
* BLAS: your offered
* Python version (if using pycaffe): 3.6 and 3.5

**Comment by ihuale** [comment]
I remove the openslide form my program, program a new IO function to my program, add caffe to my program,and it  it run successed.
I add opendslide to it for a test, use the function "openslide_detect_vendor()" again,and the same bug crash my program again,,, -_-!
Is there anybody can help fix the bug?
thank you!

**Comment by Noiredd** [comment]
As you see, everything worked as you expected when you excluded openslide. This suggests that the issue is either with openslide or your code - not with Caffe itself.
