### ISSUE TITLE
I cannot pass the 'make test' and my .build_release/test folder is empty

### ISSUE THREAD

**Issue by Daylighter** [BVLC/caffe#6465]
`sudo make test
CXX/LD -o .build_release/test/test_all.testbin src/caffe/test/test_caffe_main.cpp
/usr/bin/x86_64-linux-gnu-ld: cannot find -lhdf5_hl
/usr/bin/x86_64-linux-gnu-ld: cannot find -lhdf5
collect2: error: ld returned 1 exit status
Makefile:603: recipe for target '.build_release/test/test_all.testbin' failed
make: *** [.build_release/test/test_all.testbin] Error 1`

This is my Makefile.config
[Makefile.txt](https://github.com/BVLC/caffe/files/2194961/Makefile.txt)

### Issue summary

This is what happened when I run 'sudo make test'
It seems that when I run 'sudo make all'
some files are missing like 
upgrade_solver_proto_text.bin
caffe.bin
upgrade_net_proto_text.bin
upgrade_net_proto_binary.bin
compute_image_mean.bin
convert_imageset.bin
extract_features.bin
but I find file that have the same name in /usr/bin and copied those
so the 'make all' command passed
but the ./.build_release/test is empty and I cannot even pass the first step in 'make test'
what should I do?

### System configuration

* Operating system:  Ubuntu 18.04 LTS
* Compiler: g++?python?
* CUDA version (if applicable): 
* CUDNN version (if applicable): 
* BLAS: atlas
* Python version (if using pycaffe): 3.6
* MATLAB version (if using matcaffe):

**Comment by Noiredd** [comment]
This problem has been talked about on our [wiki](https://github.com/BVLC/caffe/wiki/Commonly-encountered-build-issues). If that doesn't help you, please reopen with an update.
