### ISSUE TITLE
Problems about deconvolution

### ISSUE THREAD

**Issue by yttdebaba2** [BVLC/caffe#6467]
I have an input image of size 3 x 16 x 16, and I use the deconvolution layer in caffe, and get an output of size 3 x 31 x 31. How can I get the output of size 3 x 32 x 32?
Since for deconvolution, 
output = (input - 1) x s + k - 2 x p;
I set s=2, k=3 and p=1, and result in 3 x 31 x 31.

**Comment by shaibagon** [comment]
Please use the [caffe-users list][1] for usage, installation, or modeling questions, or other requests for help.
You may also post questions on [stackoverflow][3], make sure you tag them with `caffe` tag.  
There is also [caffe.help][4] documenting the different layers of caffe.
Do not post such requests to Issues. Doing so interferes with the development of Caffe.

Please read the [guidelines for contributing][2] before submitting this issue.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
 [3]: http://stackoverflow.com/questions/tagged/caffe
 [4]: http://caffe.help/manual/layers.html
