### ISSUE TITLE
Error: import caffe can only be done in a specific directory

### ISSUE THREAD

**Issue by bennyphtam** [BVLC/caffe#6469]
I have installed caffe with pycaffe (Python 2.7) without GPU setting.

Inside the directory `/caffe/python`, I invoke Python 2.7

    /path/to/caffe/python$ python

And then try to import caffe in Python 2.7

    >>> import caffe
    >>> caffe
    <module 'caffe' from 'caffe/__init__.pyc'>

I thought it was a sucessful installation. But then, when I switch to **other directories**  and try to import caffe again, there is an error `ImportError: No module named caffe`.

How can I fix this issue so that the caffe module can be imported from all other directories? Thanks

**Comment by deepali-c** [comment]
`export PYTHONPATH=/path/to/caffe/python:$PYTHONPATH `

**Comment by Noiredd** [comment]
Closing, assuming the given answer helped. If not, please reopen and provide further details, especially how the suggested solution failed.
