### ISSUE TITLE
hide layer gradients respect to input

### ISSUE THREAD

**Issue by spiderman106** [BVLC/caffe#6485]
I am follow the paper https://arxiv.org/abs/1705.06640.[python]
Now I know I can get the output gradients to input with the net.blobs['data'].diff = B,
but if i want to get the gradients(sign as A) of output of a hide layer respect to input,for example 'conv1', and I can get the 'conv1' output to the final output through net.blobs['conv1'].diff=C, if A = B / C？，but A,B,C have different dimension, I have no idea how to figure it out,
any one have an idea about this, thanks very much

**Comment by Noiredd** [comment]
Please do not ask double questions. One thread on [caffe-users](https://groups.google.com/forum/#!topic/caffe-users/WEVn_V8zTVw) is enough.
