### ISSUE TITLE
when i make caffe，it occurs.

### ISSUE THREAD

**Issue by chanyixialex** [BVLC/caffe#6491]
CXX src/caffe/util/db_leveldb.cpp
CXX src/caffe/util/db.cpp
CXX src/caffe/util/upgrade_proto.cpp
CXX src/caffe/util/insert_splits.cpp
CXX src/caffe/util/hdf5.cpp
CXX src/caffe/util/signal_handler.cpp
CXX src/caffe/util/im2col.cpp
CXX src/caffe/util/db_lmdb.cpp
In file included from /home/alex/usr/local/include/leveldb/iterator.h:20:0,
                 from /home/alex/usr/local/include/leveldb/db.h:11,
                 from ./include/caffe/util/db_leveldb.hpp:7,
                 from src/caffe/util/db_leveldb.cpp:2:
/home/alex/usr/local/include/leveldb/status.h:26:10: error: expected ‘;’ at end of member declaration
   Status() noexcept : state_(nullptr) { }
          ^
/home/alex/usr/local/include/leveldb/status.h:26:12: error: ‘noexcept’ does not name a type
   Status() noexcept : state_(nullptr) { }
            ^
/home/alex/usr/local/include/leveldb/status.h:26:12: note: C++11 ‘noexcept’ only available with -std=c++11 or -std=gnu++11
/home/alex/usr/local/include/leveldb/status.h:32:16: error: expected ‘,’ or ‘...’ before ‘&&’ token
   Status(Status&& rhs) noexcept : state_(rhs.state_) { rhs.state_ = nullptr; }
                ^
/home/alex/usr/local/include/leveldb/status.h:32:22: error: invalid constructor; you probably meant ‘leveldb::Status (const leveldb::Status&)’
   Status(Status&& rhs) noexcept : state_(rhs.state_) { rhs.state_ = nullptr; }
                      ^
/home/alex/usr/local/include/leveldb/status.h:32:22: error: expected ‘;’ at end of member declaration
/home/alex/usr/local/include/leveldb/status.h:32:24: error: ‘noexcept’ does not name a type
   Status(Status&& rhs) noexcept : state_(rhs.state_) { rhs.state_ = nullptr; }
                        ^
/home/alex/usr/local/include/leveldb/status.h:32:24: note: C++11 ‘noexcept’ only available with -std=c++11 or -std=gnu++11
/home/alex/usr/local/include/leveldb/status.h:33:27: error: expected ‘,’ or ‘...’ before ‘&&’ token
   Status& operator=(Status&& rhs) noexcept;
                           ^
/home/alex/usr/local/include/leveldb/status.h:33:33: error: expected ‘;’ at end of member declaration
   Status& operator=(Status&& rhs) noexcept;
                                 ^
/home/alex/usr/local/include/leveldb/status.h:33:35: error: ‘noexcept’ does not name a type
   Status& operator=(Status&& rhs) noexcept;
                                   ^
/home/alex/usr/local/include/leveldb/status.h:33:35: note: C++11 ‘noexcept’ only available with -std=c++11 or -std=gnu++11
/home/alex/usr/local/include/leveldb/status.h: In member function ‘bool leveldb::Status::ok() const’:
/home/alex/usr/local/include/leveldb/status.h:56:39: error: ‘nullptr’ was not declared in this scope
   bool ok() const { return (state_ == nullptr); }
                                       ^
/home/alex/usr/local/include/leveldb/status.h: In member function ‘leveldb::Status::Code leveldb::Status::code() const’:
/home/alex/usr/local/include/leveldb/status.h:95:23: error: ‘nullptr’ was not declared in this scope
     return (state_ == nullptr) ? kOk : static_cast<Code>(state_[4]);
                       ^
/home/alex/usr/local/include/leveldb/status.h: In copy constructor ‘leveldb::Status::Status(const leveldb::Status&)’:
/home/alex/usr/local/include/leveldb/status.h:103:27: error: ‘nullptr’ was not declared in this scope
   state_ = (rhs.state_ == nullptr) ? nullptr : CopyState(rhs.state_);
                           ^
/home/alex/usr/local/include/leveldb/status.h: In member function ‘leveldb::Status& leveldb::Status::operator=(const leveldb::Status&)’:
/home/alex/usr/local/include/leveldb/status.h:110:29: error: ‘nullptr’ was not declared in this scope
     state_ = (rhs.state_ == nullptr) ? nullptr : CopyState(rhs.state_);
                             ^
/home/alex/usr/local/include/leveldb/status.h: At global scope:
/home/alex/usr/local/include/leveldb/status.h:114:40: error: expected ‘,’ or ‘...’ before ‘&&’ token
 inline Status& Status::operator=(Status&& rhs) noexcept {
                                        ^
/home/alex/usr/local/include/leveldb/status.h:114:48: error: expected initializer before ‘noexcept’
 inline Status& Status::operator=(Status&& rhs) noexcept {
                                                ^
In file included from /home/alex/usr/local/include/leveldb/db.h:11:0,
                 from ./include/caffe/util/db_leveldb.hpp:7,
                 from src/caffe/util/db_leveldb.cpp:2:
/home/alex/usr/local/include/leveldb/iterator.h:80:9: error: expected nested-name-specifier before ‘CleanupFunction’
   using CleanupFunction = void (*)(void* arg1, void* arg2);
         ^
/home/alex/usr/local/include/leveldb/iterator.h:81:24: error: ‘CleanupFunction’ has not been declared
   void RegisterCleanup(CleanupFunction function, void* arg1, void* arg2);
                        ^
/home/alex/usr/local/include/leveldb/iterator.h:88:5: error: ‘CleanupFunction’ does not name a type
     CleanupFunction function;
     ^
/home/alex/usr/local/include/leveldb/iterator.h: In member function ‘bool leveldb::Iterator::CleanupNode::IsEmpty() const’:
/home/alex/usr/local/include/leveldb/iterator.h:94:35: error: ‘function’ was not declared in this scope
     bool IsEmpty() const { return function == nullptr; }
                                   ^
/home/alex/usr/local/include/leveldb/iterator.h:94:47: error: ‘nullptr’ was not declared in this scope
     bool IsEmpty() const { return function == nullptr; }
                                               ^
/home/alex/usr/local/include/leveldb/iterator.h: In member function ‘void leveldb::Iterator::CleanupNode::Run()’:
/home/alex/usr/local/include/leveldb/iterator.h:96:49: error: ‘function’ was not declared in this scope
     void Run() { assert(function != nullptr); (*function)(arg1, arg2); }
                                                 ^
In file included from /home/alex/usr/local/include/leveldb/db.h:12:0,
                 from ./include/caffe/util/db_leveldb.hpp:7,
                 from src/caffe/util/db_leveldb.cpp:2:
/home/alex/usr/local/include/leveldb/options.h: In constructor ‘leveldb::ReadOptions::ReadOptions()’:
/home/alex/usr/local/include/leveldb/options.h:183:18: error: ‘nullptr’ was not declared in this scope
         snapshot(nullptr) {
                  ^
Makefile:581: recipe for target '.build_release/src/caffe/util/db_leveldb.o' failed
make: *** [.build_release/src/caffe/util/db_leveldb.o] Error 1
make: *** 正在等待未完成的任务....
In file included from /home/alex/usr/local/include/leveldb/iterator.h:20:0,
                 from /home/alex/usr/local/include/leveldb/db.h:11,
                 from ./include/caffe/util/db_leveldb.hpp:7,
                 from src/caffe/util/db.cpp:2:
/home/alex/usr/local/include/leveldb/status.h:26:10: error: expected ‘;’ at end of member declaration
   Status() noexcept : state_(nullptr) { }
          ^
/home/alex/usr/local/include/leveldb/status.h:26:12: error: ‘noexcept’ does not name a type
   Status() noexcept : state_(nullptr) { }
            ^
/home/alex/usr/local/include/leveldb/status.h:26:12: note: C++11 ‘noexcept’ only available with -std=c++11 or -std=gnu++11
/home/alex/usr/local/include/leveldb/status.h:32:16: error: expected ‘,’ or ‘...’ before ‘&&’ token
   Status(Status&& rhs) noexcept : state_(rhs.state_) { rhs.state_ = nullptr; }
                ^
/home/alex/usr/local/include/leveldb/status.h:32:22: error: invalid constructor; you probably meant ‘leveldb::Status (const leveldb::Status&)’
   Status(Status&& rhs) noexcept : state_(rhs.state_) { rhs.state_ = nullptr; }
                      ^
/home/alex/usr/local/include/leveldb/status.h:32:22: error: expected ‘;’ at end of member declaration
/home/alex/usr/local/include/leveldb/status.h:32:24: error: ‘noexcept’ does not name a type
   Status(Status&& rhs) noexcept : state_(rhs.state_) { rhs.state_ = nullptr; }
                        ^
/home/alex/usr/local/include/leveldb/status.h:32:24: note: C++11 ‘noexcept’ only available with -std=c++11 or -std=gnu++11
/home/alex/usr/local/include/leveldb/status.h:33:27: error: expected ‘,’ or ‘...’ before ‘&&’ token
   Status& operator=(Status&& rhs) noexcept;
                           ^
/home/alex/usr/local/include/leveldb/status.h:33:33: error: expected ‘;’ at end of member declaration
   Status& operator=(Status&& rhs) noexcept;
                                 ^
/home/alex/usr/local/include/leveldb/status.h:33:35: error: ‘noexcept’ does not name a type
   Status& operator=(Status&& rhs) noexcept;
                                   ^
/home/alex/usr/local/include/leveldb/status.h:33:35: note: C++11 ‘noexcept’ only available with -std=c++11 or -std=gnu++11
/home/alex/usr/local/include/leveldb/status.h: In member function ‘bool leveldb::Status::ok() const’:
/home/alex/usr/local/include/leveldb/status.h:56:39: error: ‘nullptr’ was not declared in this scope
   bool ok() const { return (state_ == nullptr); }
                                       ^
/home/alex/usr/local/include/leveldb/status.h: In member function ‘leveldb::Status::Code leveldb::Status::code() const’:
/home/alex/usr/local/include/leveldb/status.h:95:23: error: ‘nullptr’ was not declared in this scope
     return (state_ == nullptr) ? kOk : static_cast<Code>(state_[4]);
                       ^
/home/alex/usr/local/include/leveldb/status.h: In copy constructor ‘leveldb::Status::Status(const leveldb::Status&)’:
/home/alex/usr/local/include/leveldb/status.h:103:27: error: ‘nullptr’ was not declared in this scope
   state_ = (rhs.state_ == nullptr) ? nullptr : CopyState(rhs.state_);
                           ^
/home/alex/usr/local/include/leveldb/status.h: In member function ‘leveldb::Status& leveldb::Status::operator=(const leveldb::Status&)’:
/home/alex/usr/local/include/leveldb/status.h:110:29: error: ‘nullptr’ was not declared in this scope
     state_ = (rhs.state_ == nullptr) ? nullptr : CopyState(rhs.state_);
                             ^
/home/alex/usr/local/include/leveldb/status.h: At global scope:
/home/alex/usr/local/include/leveldb/status.h:114:40: error: expected ‘,’ or ‘...’ before ‘&&’ token
 inline Status& Status::operator=(Status&& rhs) noexcept {
                                        ^
/home/alex/usr/local/include/leveldb/status.h:114:48: error: expected initializer before ‘noexcept’
 inline Status& Status::operator=(Status&& rhs) noexcept {
                                                ^
In file included from /home/alex/usr/local/include/leveldb/db.h:11:0,
                 from ./include/caffe/util/db_leveldb.hpp:7,
                 from src/caffe/util/db.cpp:2:
/home/alex/usr/local/include/leveldb/iterator.h:80:9: error: expected nested-name-specifier before ‘CleanupFunction’
   using CleanupFunction = void (*)(void* arg1, void* arg2);
         ^
/home/alex/usr/local/include/leveldb/iterator.h:81:24: error: ‘CleanupFunction’ has not been declared
   void RegisterCleanup(CleanupFunction function, void* arg1, void* arg2);
                        ^
/home/alex/usr/local/include/leveldb/iterator.h:88:5: error: ‘CleanupFunction’ does not name a type
     CleanupFunction function;
     ^
/home/alex/usr/local/include/leveldb/iterator.h: In member function ‘bool leveldb::Iterator::CleanupNode::IsEmpty() const’:
/home/alex/usr/local/include/leveldb/iterator.h:94:35: error: ‘function’ was not declared in this scope
     bool IsEmpty() const { return function == nullptr; }
                                   ^
/home/alex/usr/local/include/leveldb/iterator.h:94:47: error: ‘nullptr’ was not declared in this scope
     bool IsEmpty() const { return function == nullptr; }
                                               ^
/home/alex/usr/local/include/leveldb/iterator.h: In member function ‘void leveldb::Iterator::CleanupNode::Run()’:
/home/alex/usr/local/include/leveldb/iterator.h:96:49: error: ‘function’ was not declared in this scope
     void Run() { assert(function != nullptr); (*function)(arg1, arg2); }
                                                 ^
In file included from /home/alex/usr/local/include/leveldb/db.h:12:0,
                 from ./include/caffe/util/db_leveldb.hpp:7,
                 from src/caffe/util/db.cpp:2:
/home/alex/usr/local/include/leveldb/options.h: In constructor ‘leveldb::ReadOptions::ReadOptions()’:
/home/alex/usr/local/include/leveldb/options.h:183:18: error: ‘nullptr’ was not declared in this scope
         snapshot(nullptr) {
                  ^
Makefile:581: recipe for target '.build_release/src/caffe/util/db.o' failed
make: *** [.build_release/src/caffe/util/db.o] Error 1

when i make,it occurs.  I install caffe in the virtualenv.(docker)

* Operating system: ubuntu16.04
* Compiler: gcc
* CUDA version (if applicable): 9.0
* CUDNN version (if applicable): 
* BLAS: openblas
* Python version (if using pycaffe): 3.6
Thanks!!!

**Comment by Noiredd** [comment]
Please post usage, installation, or modeling questions, or other requests for help to the [caffe-users list][1] instead of Issues. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe. Please read the [guidelines for contributing][2] before submitting an issue or a pull request.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md

**Comment by huziling** [comment]
I have same problem。 Do you find any?

**Comment by appleship** [comment]
I think you can look at this 
https://stackoverflow.com/questions/10851247/how-to-activate-c-11-in-cmake

**Comment by JuiChang** [comment]
I am using mac. Following the stackoverflow link above, in the Makefile, I change:
```
ifeq ($(OSX), 1)
	CXX := /usr/bin/clang++
```
to
```
ifeq ($(OSX), 1)
	CXX := /usr/bin/clang++ -std=c++11
```
and it works.

For linux, I guess changing:
```
ifeq ($(LINUX), 1)
	CXX ?= /usr/bin/g++
```
to 
```
ifeq ($(LINUX), 1)
	CXX ?= /usr/bin/g++ -std=c++11
```
in the Makefile may work.
