### ISSUE TITLE
Custom C++ Data Layer - Accesing current weights?

### ISSUE THREAD

**Issue by soulslicer** [BVLC/caffe#6500]
I am using the Caffe C++ Data Layer as a custom data layer

I want to access the caffe::Net object internally, so I can access the weights of the net, and possibly do a forward pass, is that actually possible? If so how can I do it?

**Comment by Noiredd** [comment]
Please do not ask double questions. One thread on [caffe-users](https://groups.google.com/forum/#!topic/caffe-users/iq8YL8iz9vQ) is enough.
