### ISSUE TITLE
caffe: error while loading shared libraries: libhdf5_hl.so.100:

### ISSUE THREAD

**Issue by ebron01** [BVLC/caffe#6504]
hi, when i make all and make test, it compiles but when i run make runtest it gives following error:

.build_release/tools/caffe
.build_release/tools/caffe: error while loading shared libraries: libhdf5_hl.so.100: cannot open shared object file: No such file or directory
make: *** [runtest] Error 127

libhdf5_hl.so.100 is installed in home/eboran/anaconda2/lib directory. Although i give the directory in 
PYTHON_LIB := /home/eboran/anaconda2/lib
and
LIBRARY_DIRS =  $(PYTHON_LIB) /usr/local/lib /usr/lib /home/anaconda2/lib 

it cannot find libhdf5_hl.so.100 still.

What is the problem i cannot understand.

os is centos 7.

**Comment by Noiredd** [comment]
Please do not ask double questions. One thread on [caffe-users](https://groups.google.com/forum/#!topic/caffe-users/MvWRT_gzKJU) is enough.

**Comment by cokeyke** [comment]
How did you solve that?

**Comment by VijayrajS** [comment]
There is no proper help given in the Google group
