### ISSUE TITLE
Makefile:591: recipe for target '.build_release/src/caffe/layers/cudnn_relu_layer.o' failed

### ISSUE THREAD

**Issue by 237014845** [BVLC/caffe#6510]
## Important - read before submitting

*Please read the [guidelines for contributing](https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md) before submitting this issue!*

*Please do not post installation, build, usage, or modeling questions, or other requests for help to Issues.*
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead.
This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

### System configuration

* Operating system: ubuntu16.04
* Compiler: 
* CUDA version (if applicable): 8.0
* CUDNN version (if applicable): 7.1
* BLAS: 
* Python version (if using pycaffe): 3.6
* MATLAB version (if using matcaffe): 

### Issue checklist

- [ ] read the guidelines and removed the first paragraph
- [ ] written a short summary and detailed steps to reproduce
- [ ] explained how solutions to related problems failed (tick if found none)
- [ ] filled system configuration
- [ ] attached relevant logs/config files (tick if not applicable)

CXX .build_release/src/caffe/proto/caffe.pb.cc
CXX src/caffe/syncedmem.cpp
CXX src/caffe/common.cpp
CXX src/caffe/layers/spp_layer.cpp
CXX src/caffe/layers/cudnn_deconv_layer.cpp
CXX src/caffe/layers/cudnn_tanh_layer.cpp
CXX src/caffe/layers/cudnn_lrn_layer.cpp
CXX src/caffe/layers/cudnn_relu_layer.cpp
In file included from ./include/caffe/util/math_functions.hpp:11:0,
                 from ./include/caffe/layer.hpp:12,
                 from src/caffe/layers/spp_layer.cpp:4:
./include/caffe/util/mkl_alternate.hpp:14:19: fatal error: cblas.h: No such file or directory
compilation terminated.
In file included from ./include/caffe/util/math_functions.hpp:11:0,
                 from ./include/caffe/layer.hpp:12,
                 from ./include/caffe/layers/cudnn_deconv_layer.hpp:7,
                 from src/caffe/layers/cudnn_deconv_layer.cpp:5:
./include/caffe/util/mkl_alternate.hpp:14:19: fatal error: cblas.h: No such file or directory
compilation terminated.
Makefile:591: recipe for target '.build_release/src/caffe/layers/spp_layer.o' failed
make: *** [.build_release/src/caffe/layers/spp_layer.o] Error 1
make: *** Waiting for unfinished jobs....
Makefile:591: recipe for target '.build_release/src/caffe/layers/cudnn_deconv_layer.o' failed
make: *** [.build_release/src/caffe/layers/cudnn_deconv_layer.o] Error 1
In file included from ./include/caffe/util/math_functions.hpp:11:0,
                 from ./include/caffe/layer.hpp:12,
                 from ./include/caffe/layers/cudnn_lrn_layer.hpp:7,
                 from src/caffe/layers/cudnn_lrn_layer.cpp:4:
./include/caffe/util/mkl_alternate.hpp:14:19: fatal error: cblas.h: No such file or directory
compilation terminated.
In file included from ./include/caffe/util/math_functions.hpp:11:0,
                 from src/caffe/syncedmem.cpp:3:
./include/caffe/util/mkl_alternate.hpp:14:19: fatal error: cblas.h: No such file or directory
compilation terminated.
In file included from ./include/caffe/util/math_functions.hpp:11:0,
                 from ./include/caffe/layer.hpp:12,
                 from ./include/caffe/layers/cudnn_tanh_layer.hpp:7,
                 from src/caffe/layers/cudnn_tanh_layer.cpp:4:
./include/caffe/util/mkl_alternate.hpp:14:19: fatal error: cblas.h: No such file or directory
compilation terminated.
Makefile:591: recipe for target '.build_release/src/caffe/layers/cudnn_lrn_layer.o' failed
make: *** [.build_release/src/caffe/layers/cudnn_lrn_layer.o] Error 1
Makefile:591: recipe for target '.build_release/src/caffe/syncedmem.o' failed
make: *** [.build_release/src/caffe/syncedmem.o] Error 1
Makefile:591: recipe for target '.build_release/src/caffe/layers/cudnn_tanh_layer.o' failed
make: *** [.build_release/src/caffe/layers/cudnn_tanh_layer.o] Error 1
In file included from ./include/caffe/util/math_functions.hpp:11:0,
                 from ./include/caffe/layer.hpp:12,
                 from ./include/caffe/layers/cudnn_relu_layer.hpp:7,
                 from src/caffe/layers/cudnn_relu_layer.cpp:4:
./include/caffe/util/mkl_alternate.hpp:14:19: fatal error: cblas.h: No such file or directory
compilation terminated.
Makefile:591: recipe for target '.build_release/src/caffe/layers/cudnn_relu_layer.o' failed
make: *** [.build_release/src/caffe/layers/cudnn_relu_layer.o] Error 1

**Comment by Noiredd** [comment]
This looks like a build issue, and as such should be posted to caffe-users group. If I'm wrong, please re-read the checklist in the [issue template](https://github.com/BVLC/caffe/blob/master/.github/ISSUE_TEMPLATE.md), complete and reopen your issue accordingly.

Please post usage, installation, or modeling questions, or other requests for help to the [caffe-users list][1] instead of Issues. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe. Please read the [guidelines for contributing][2] before submitting an issue or a pull request.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
