### ISSUE TITLE
Issue with YOLO with CaffeYolo-Armnn example

### ISSUE THREAD

**Issue by getsumit123** [BVLC/caffe#6520]
Hi
I tried to test CaffeYolo-Armnn example by converting yolo tiny darknet model to caffemodel

But everytime it returns "Prediction for test case 0 (14) is incorrect (should be 11)"
Issue may be with the yolo model which i am using.
Could anyone please provide Yolo model which works with armnn or redirect me to the place where i can get caffe port which works with armnn.

I am using command "CaffeYolo-Armnn -i 10 -d /path/to/image/ -m /path/to/alexnet/model_file/ -c GpuAcc"

Regards
Sumit

**Comment by Noiredd** [comment]
This is unrelated to Caffe master, therefore I'm closing. Consider asking this on the Armnn repository.
