### ISSUE TITLE
Prebuilt binaries cannot be downloaded

### ISSUE THREAD

**Issue by kalnkaya** [BVLC/caffe#6529]
Prebuilt binaries cannot be downloaded.

**Comment by willyd** [comment]
Yes prebuilt binaries links are broken. You can try the conda packages. See https://github.com/BVLC/caffe/issues/6569#issuecomment-432491851.

**Comment by willyd** [comment]
Closing as duplicate of https://github.com/BVLC/caffe/issues/6483.
