### ISSUE TITLE
Illegal memory access was encountered when trying to train network on GPU=1

### ISSUE THREAD

**Issue by erithacula** [BVLC/caffe#6538]
### Issue summary
I have two Titan X GPUs that I'm using for usually two seperate trainings. Everything worked fine until yesterday, since rebooting I get the following error when trying to train a network on GPU 1:

Check failed: error == cudaSuccess (77 vs. 0)  an illegal memory access was encountered
*** Check failure stack trace: ***
    @     0x7f76515875cd  google::LogMessage::Fail()
    @     0x7f7651589433  google::LogMessage::SendToLog()
    @     0x7f765158715b  google::LogMessage::Flush()
    @     0x7f7651589e1e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f7651d76eca  caffe::caffe_gpu_memcpy()
    @     0x7f7651bd5d1d  caffe::SyncedMemory::gpu_data()
    @     0x7f7651bc58b2  caffe::Blob<>::gpu_data()
    @     0x7f7651db75d0  caffe::CropLayer<>::Forward_gpu()
    @     0x7f7651b9fce1  caffe::Net<>::ForwardFromTo()
    @     0x7f7651b9fde7  caffe::Net<>::Forward()
    @     0x7f7651bdea62  caffe::Solver<>::Test()
    @     0x7f7651bdf33e  caffe::Solver<>::TestAll()
    @     0x7f7651be2897  caffe::Solver<>::Step()
    @     0x7f7651be2b5a  caffe::Solver<>::Solve()
    @           0x40a914  train()
    @           0x407548  main
    @     0x7f764fd1d830  __libc_start_main
    @           0x407e19  _start
    @              (nil)  (unknown)
Aborted (core dumped)

I did not change any files. Note that this does not happen with the _exact same_ configuration on GPU 0. The output of nividia-smi is:

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 390.87                 Driver Version: 390.87                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  TITAN X (Pascal)    Off  | 00000000:02:00.0 Off |                  N/A |
| 46%   76C    P2   132W / 250W |   7026MiB / 12196MiB |     96%      Default |
+-------------------------------+----------------------+----------------------+
|   1  TITAN X (Pascal)    Off  | 00000000:03:00.0  On |                  N/A |
| 23%   33C    P8     9W / 250W |     23MiB / 12196MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

### Steps to reproduce
caffe.bin train --solver=solver.prototxt -gpu=1 wields the error, same command with -gpu=0 works fine

### Tried solutions
None except for rebooting, since I have no idea how this can happen with the exact same configuration on only one of two GPUs.

### System configuration

* Operating system: Ubuntu 16.04
* Compiler: GCC
* CUDA version (if applicable): 9.0.176
* CUDNN version (if applicable): 7004 (Major 7, Minor 0, Patch Level 4)

### Issue checklist

- [ X] read the guidelines and removed the first paragraph
- [ X] written a short summary and detailed steps to reproduce
- [ X] explained how solutions to related problems failed (tick if found none)
- [X ] filled system configuration
- [X ] attached relevant logs/config files (tick if not applicable)

Any help or possible solutions would be greatly appreciated, since I really need the double processing power for time sensitive training processes.

**Comment by Shikherneo2** [comment]
Did you get around to figuring out the problem? I have been facing the same issue.

**Comment by erithacula** [comment]
Hi Shikherneo2,

as far as I know this issue arose because of a broken GPU. I'm sorry that I'm not capable of helping any further and hope your GPU isn't broken.

Best regards
