### ISSUE TITLE
[Source code problem] why xxx_layer.hpp use Dtype for parameter?

### ISSUE THREAD

**Issue by astronaut0131** [BVLC/caffe#6552]
take `include/caffe/layers/batch_norm_layer.hpp` for example
I think `Dtype` means the type of data stored in blob, but why parameter  `eps_` and `moving_average_fraction_` use `Dtype` ?
they are declared as `float` in `src/caffe/proto/caffe.proto`

**Comment by csukuangfj** [comment]
Caffe instantiates every layer with `Dtype=float` and `Dtype=double`.
It is fine if `eps_` and `moving_average_fraction_` were declared explicitly as `float` or as `double`.
Declare them as `Dtype` can avoid implicit conversion during computation if types mismatch.

**Comment by astronaut0131** [comment]
thanks for explanation @csukuangfj
