### ISSUE TITLE
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Type_get_envelope'

### ISSUE THREAD

**Issue by noraju** [BVLC/caffe#6622]
when i want to create a new type of  layer which need PCL , and add dependencies in cmake/Dependencies.cmake only with find_package line like this:
```find_package(PCL 1.7 REQUIRED)```
compile error with MPI xxxxxxx happend. if delete this line, everything's OK. 

building output as follow:
[  0%] Running C++/Python protocol buffer compiler on /home/dongxufu/Dev/caffe/src/caffe/proto/caffe.proto
Scanning dependencies of target caffeproto
[  1%] Building CXX object src/caffe/CMakeFiles/caffeproto.dir/__/__/include/caffe/proto/caffe.pb.cc.o
[  1%] Linking CXX static library ../../lib/libcaffeproto.a
[  1%] Built target caffeproto
Scanning dependencies of target caffe
[  1%] Building CXX object src/caffe/CMakeFiles/caffe.dir/solver.cpp.o
[  1%] Building CXX object src/caffe/CMakeFiles/caffe.dir/blob.cpp.o
[  3%] Building CXX object src/caffe/CMakeFiles/caffe.dir/data_transformer.cpp.o
[  3%] Building CXX object src/caffe/CMakeFiles/caffe.dir/syncedmem.cpp.o
[  4%] Building CXX object src/caffe/CMakeFiles/caffe.dir/parallel.cpp.o
[  4%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layer_factory.cpp.o
[  6%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layer.cpp.o
[  6%] Building CXX object src/caffe/CMakeFiles/caffe.dir/solvers/nesterov_solver.cpp.o
[  7%] Building CXX object src/caffe/CMakeFiles/caffe.dir/solvers/adagrad_solver.cpp.o
[  7%] Building CXX object src/caffe/CMakeFiles/caffe.dir/solvers/sgd_solver.cpp.o
[  9%] Building CXX object src/caffe/CMakeFiles/caffe.dir/solvers/adam_solver.cpp.o
[  9%] Building CXX object src/caffe/CMakeFiles/caffe.dir/solvers/rmsprop_solver.cpp.o
[ 10%] Building CXX object src/caffe/CMakeFiles/caffe.dir/solvers/adadelta_solver.cpp.o
[ 10%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/cudnn_relu_layer.cpp.o
[ 12%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/cudnn_softmax_layer.cpp.o
[ 12%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/rnn_layer.cpp.o
[ 14%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/lstm_layer.cpp.o
[ 14%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/cudnn_sigmoid_layer.cpp.o
[ 15%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/concat_layer.cpp.o
[ 15%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/mvn_layer.cpp.o
[ 17%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/cudnn_lrn_layer.cpp.o
[ 17%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/cudnn_conv_layer.cpp.o
[ 18%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/absval_layer.cpp.o
[ 18%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/input_layer.cpp.o
[ 20%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/silence_layer.cpp.o
[ 20%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/cudnn_tanh_layer.cpp.o
[ 21%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/recurrent_layer.cpp.o
[ 21%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/image_data_layer.cpp.o
[ 23%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/window_data_layer.cpp.o
[ 23%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/batch_reindex_layer.cpp.o
[ 25%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/accuracy_layer.cpp.o
[ 25%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/inner_product_layer.cpp.o
[ 26%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/argmax_layer.cpp.o
[ 26%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/relu_layer.cpp.o
[ 28%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/clip_layer.cpp.o
[ 28%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/neuron_layer.cpp.o
[ 29%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/spp_layer.cpp.o
[ 29%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/slice_layer.cpp.o
[ 31%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/flatten_layer.cpp.o
[ 31%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/lstm_unit_layer.cpp.o
[ 32%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/log_layer.cpp.o
[ 32%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/softmax_layer.cpp.o
[ 34%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/base_data_layer.cpp.o
[ 34%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/euclidean_loss_layer.cpp.o
[ 35%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/sigmoid_layer.cpp.o
[ 35%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/base_conv_layer.cpp.o
[ 37%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/loss_layer.cpp.o
[ 37%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/power_layer.cpp.o
[ 39%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/hdf5_output_layer.cpp.o
[ 39%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/crop_layer.cpp.o
[ 40%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/dropout_layer.cpp.o
[ 40%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/bias_layer.cpp.o
[ 42%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/conv_layer.cpp.o
[ 42%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/parameter_layer.cpp.o
[ 43%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/reduction_layer.cpp.o
[ 43%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/tanh_layer.cpp.o
[ 45%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/pooling_layer.cpp.o
[ 45%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/im2col_layer.cpp.o
[ 46%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/hinge_loss_layer.cpp.o
[ 46%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/sigmoid_cross_entropy_loss_layer.cpp.o
[ 48%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/prelu_layer.cpp.o
[ 48%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/contrastive_loss_layer.cpp.o
[ 50%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/cudnn_deconv_layer.cpp.o
[ 50%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/split_layer.cpp.o
[ 51%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/hdf5_data_layer.cpp.o
[ 51%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/threshold_layer.cpp.o
[ 53%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/cudnn_lcn_layer.cpp.o
[ 53%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/bnll_layer.cpp.o
[ 53%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/elu_layer.cpp.o
[ 54%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/cudnn_pooling_layer.cpp.o
[ 54%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/infogain_loss_layer.cpp.o
[ 56%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/deconv_layer.cpp.o
[ 56%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/eltwise_layer.cpp.o
[ 57%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/scale_layer.cpp.o
[ 57%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/softmax_loss_layer.cpp.o
[ 59%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/filter_layer.cpp.o
[ 59%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/dummy_data_layer.cpp.o
[ 60%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/lrn_layer.cpp.o
[ 60%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/tile_layer.cpp.o
[ 62%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/exp_layer.cpp.o
[ 62%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/data_layer.cpp.o
[ 64%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/memory_data_layer.cpp.o
[ 64%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/multinomial_logistic_loss_layer.cpp.o
[ 65%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/reshape_layer.cpp.o
[ 65%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/embed_layer.cpp.o
[ 67%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/swish_layer.cpp.o
[ 67%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/batch_norm_layer.cpp.o
[ 68%] Building CXX object src/caffe/CMakeFiles/caffe.dir/util/im2col.cpp.o
[ 68%] Building CXX object src/caffe/CMakeFiles/caffe.dir/util/db_lmdb.cpp.o
[ 70%] Building CXX object src/caffe/CMakeFiles/caffe.dir/util/io.cpp.o
[ 70%] Building CXX object src/caffe/CMakeFiles/caffe.dir/util/signal_handler.cpp.o
[ 71%] Building CXX object src/caffe/CMakeFiles/caffe.dir/util/math_functions.cpp.o
[ 71%] Building CXX object src/caffe/CMakeFiles/caffe.dir/util/benchmark.cpp.o
[ 73%] Building CXX object src/caffe/CMakeFiles/caffe.dir/util/cudnn.cpp.o
[ 73%] Building CXX object src/caffe/CMakeFiles/caffe.dir/util/upgrade_proto.cpp.o
[ 75%] Building CXX object src/caffe/CMakeFiles/caffe.dir/util/insert_splits.cpp.o
[ 75%] Building CXX object src/caffe/CMakeFiles/caffe.dir/util/blocking_queue.cpp.o
[ 76%] Building CXX object src/caffe/CMakeFiles/caffe.dir/util/hdf5.cpp.o
[ 76%] Building CXX object src/caffe/CMakeFiles/caffe.dir/util/db.cpp.o
[ 78%] Building CXX object src/caffe/CMakeFiles/caffe.dir/util/db_leveldb.cpp.o
[ 78%] Building CXX object src/caffe/CMakeFiles/caffe.dir/net.cpp.o
[ 79%] Building CXX object src/caffe/CMakeFiles/caffe.dir/common.cpp.o
[ 79%] Building CXX object src/caffe/CMakeFiles/caffe.dir/internal_thread.cpp.o
[ 81%] Linking CXX shared library ../../lib/libcaffe.so
[ 81%] Built target caffe
Scanning dependencies of target upgrade_net_proto_text
[ 81%] Building CXX object tools/CMakeFiles/upgrade_net_proto_text.dir/upgrade_net_proto_text.cpp.o
[ 82%] Linking CXX executable upgrade_net_proto_text
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Type_get_envelope'
../lib/libcaffe.so.1.0.0: undefined reference to `ompi_mpi_comm_null'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Abort'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Topo_test'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Group_excl'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Type_create_subarray'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Win_get_name'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Comm_dup'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Graph_create'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Get_count'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Op_free'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Graph_neighbors'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Grequest_complete'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Comm_create'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Win_test'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Scan'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Graphdims_get'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Test_cancelled'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Put'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Errhandler_free'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Bsend_init'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Group_incl'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Type_get_attr'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Group_range_excl'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Op_commutative'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Comm_get_attr'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Reduce_scatter'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Type_get_contents'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Info_get_valuelen'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Irsend'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Bcast'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Pack_external_size'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Info_free'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Sendrecv_replace'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Info_dup'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Comm_remote_group'
../lib/libcaffe.so.1.0.0: undefined reference to `ompi_mpi_cxx_op_intercept'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Ssend_init'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Alltoallv'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Win_set_errhandler'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Scatter'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Win_start'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Cart_create'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Comm_set_name'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Info_set'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Accumulate'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Scatterv'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Initialized'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Request_get_status'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Graph_neighbors_count'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Iprobe'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Probe'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Type_delete_attr'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Allgatherv'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Issend'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Comm_disconnect'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Win_set_attr'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Info_get'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Comm_group'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Cancel'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Cart_sub'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Unpack_external'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Comm_split'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Win_wait'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Comm_get_errhandler'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Send'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Win_complete'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Type_size'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Graph_map'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Allreduce'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Comm_remote_size'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Reduce_local'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI::Datatype::Free()'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Info_delete'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Send_init'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Exscan'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Comm_set_errhandler'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Status_set_cancelled'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Rsend'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Win_get_group'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Type_get_true_extent'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Bsend'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Get'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Cartdim_get'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Irecv'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Win_lock'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Type_contiguous'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Cart_coords'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Recv'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Type_create_indexed_block'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Win_fence'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Comm_free'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Type_get_extent'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Type_dup'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Group_rank'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Reduce'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Pack'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Cart_rank'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Gatherv'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Comm_delete_attr'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Start'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Wait'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Allgather'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Ibsend'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Type_create_darray'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Type_create_resized'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Type_create_hindexed'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Get_elements'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Group_size'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Op_create'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Info_get_nthkey'
../lib/libcaffe.so.1.0.0: undefined reference to `ompi_op_set_cxx_callback'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Request_free'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Pack_size'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Comm_set_attr'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Ssend'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Unpack'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Test'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Intercomm_create'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Comm_spawn_multiple'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Info_get_nkeys'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Win_delete_attr'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Recv_init'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Type_set_attr'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Isend'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI::Comm::Comm()'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Type_create_hvector'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Rsend_init'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Win_post'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Comm_test_inter'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Type_vector'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Type_get_name'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Comm_get_name'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Comm_spawn'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Type_set_name'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Win_set_name'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Alltoall'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Cart_shift'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Comm_accept'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Status_set_elements'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Sendrecv'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Win_call_errhandler'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Gather'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Win_get_errhandler'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Comm_connect'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Intercomm_merge'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Comm_size'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Group_range_incl'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Graph_get'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Group_free'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Type_indexed'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Cart_get'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Barrier'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Pack_external'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Type_commit'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI::Win::Free()'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Cart_map'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Win_unlock'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Comm_rank'
../lib/libcaffe.so.1.0.0: undefined reference to `MPI_Alltoallw'
collect2: error: ld returned 1 exit status
tools/CMakeFiles/upgrade_net_proto_text.dir/build.make:132: recipe for target 'tools/upgrade_net_proto_text' failed
make[2]: *** [tools/upgrade_net_proto_text] Error 1
CMakeFiles/Makefile2:457: recipe for target 'tools/CMakeFiles/upgrade_net_proto_text.dir/all' failed
make[1]: *** [tools/CMakeFiles/upgrade_net_proto_text.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

anybody knows why?

**Comment by sqsu-pg** [comment]
I have this problem too,can you tell me the reason? Thanks!
