### ISSUE TITLE
Deep Q-Learning with Caffe

### ISSUE THREAD

**Issue by nsoong** [BVLC/caffe#666]
Hello,

I was wondering what was needed to implement deep q learning as in:
www.cs.toronto.edu/~vmnih/docs/dqn.pdf

I was able to feed images in from Atari relatively easily to a MemoryDataLayer and call solver.Solve’s inner while loop as the game is played. However, I’m having trouble determining how to implement the loss. I believe I can update the labels in real time with the reward adjusted Q-value. However, I’ll also need to compute the loss with the pre-reward Q-value somehow in the loss layer. Looking at the existing loss layers, I’m completely stumped with what’s going on and how to implement my own `QLossLayer`. Especially with the Backward_cpu part. Any help would be greatly appreciated. Also, a high level explanation of the loss layers might go a long way. Like, how derivatives of the loss with respect to the weights are computed, etc...

A prototype implementation of the algorithm is here from Karpathy: https://github.com/karpathy/convnetjs/blob/master/build/deepqlearn.js 

Also, thanks so much for all your amazing work on this project.

**Comment by shelhamer** [comment]
Closing as a usage question, but It was great to have the DQN by @muupan to show how it could be done at the time!
