### ISSUE TITLE
cuda10 cmake Error

### ISSUE THREAD

**Issue by engineer1109** [BVLC/caffe#6665]
python2 cuda10 cudnn7  Ubuntu18.04
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Warning at /usr/share/cmake-3.10/Modules/FindBoost.cmake:801 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.10/Modules/FindBoost.cmake:1558 (_Boost_MISSING_DEPENDENCIES)
  cmake/Dependencies.cmake:8 (find_package)
  CMakeLists.txt:46 (include)

CMake Warning at /usr/share/cmake-3.10/Modules/FindBoost.cmake:801 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.10/Modules/FindBoost.cmake:1558 (_Boost_MISSING_DEPENDENCIES)
  cmake/Dependencies.cmake:8 (find_package)
  CMakeLists.txt:46 (include)

CMake Warning at /usr/share/cmake-3.10/Modules/FindBoost.cmake:801 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.10/Modules/FindBoost.cmake:1558 (_Boost_MISSING_DEPENDENCIES)
  cmake/Dependencies.cmake:8 (find_package)
  CMakeLists.txt:46 (include)

CMake Warning at /usr/share/cmake-3.10/Modules/FindBoost.cmake:801 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.10/Modules/FindBoost.cmake:1558 (_Boost_MISSING_DEPENDENCIES)
  cmake/Dependencies.cmake:8 (find_package)
  CMakeLists.txt:46 (include)

CMake Warning at /usr/share/cmake-3.10/Modules/FindBoost.cmake:801 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.10/Modules/FindBoost.cmake:1558 (_Boost_MISSING_DEPENDENCIES)
  cmake/Dependencies.cmake:8 (find_package)
  CMakeLists.txt:46 (include)

CMake Warning at /usr/share/cmake-3.10/Modules/FindBoost.cmake:801 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.10/Modules/FindBoost.cmake:1558 (_Boost_MISSING_DEPENDENCIES)
  cmake/Dependencies.cmake:8 (find_package)
  CMakeLists.txt:46 (include)

-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Boost version: 1.68.0
-- Found the following Boost libraries:
--   system
--   thread
--   filesystem
--   chrono
--   date_time
--   atomic
-- Found GFlags: /usr/include  
-- Found gflags  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libgflags.so)
-- Found Glog: /usr/include  
-- Found glog    (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libglog.so)
-- Found Protobuf: /usr/local/lib/libprotobuf.a;-lpthread (found version "3.5.0") 
-- Found PROTOBUF Compiler: /usr/local/bin/protoc
-- HDF5: Using hdf5 compiler wrapper to determine C configuration
-- HDF5: Using hdf5 compiler wrapper to determine CXX configuration
-- Found HDF5: /usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5_cpp.so;/usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5.so;/usr/lib/x86_64-linux-gnu/libpthread.so;/usr/lib/x86_64-linux-gnu/libsz.so;/usr/lib/x86_64-linux-gnu/libz.so;/usr/lib/x86_64-linux-gnu/libdl.so;/usr/lib/x86_64-linux-gnu/libm.so (found version "1.10.0.1") found components:  HL 
-- Found LMDB: /usr/include  
-- Found lmdb    (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/liblmdb.so)
-- Found LevelDB: /usr/include  
-- Found LevelDB (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libleveldb.so)
-- Found Snappy: /usr/include  
-- Found Snappy  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libsnappy.so)
-- CUDA detected: 10.0
-- Found cuDNN: ver. 7.3.1 found (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libcudnn.so)
-- Added CUDA NVCC flags for: sm_61
-- OpenCV found (/usr/local/share/OpenCV)
-- Found Atlas: /usr/include/x86_64-linux-gnu  
-- Found Atlas (include: /usr/include/x86_64-linux-gnu library: /usr/lib/x86_64-linux-gnu/libatlas.so lapack: /usr/lib/x86_64-linux-gnu/liblapack.so
-- Found PythonInterp: /usr/bin/python2.7 (found suitable version "2.7.15", minimum required is "2.7") 
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython2.7.so (found suitable version "2.7.15rc1", minimum required is "2.7") 
-- Found NumPy: /usr/local/lib/python2.7/dist-packages/numpy/core/include (found suitable version "1.15.4", minimum required is "1.7.1") 
-- NumPy ver. 1.15.4 found (include: /usr/local/lib/python2.7/dist-packages/numpy/core/include)
CMake Warning at /usr/share/cmake-3.10/Modules/FindBoost.cmake:801 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.10/Modules/FindBoost.cmake:1558 (_Boost_MISSING_DEPENDENCIES)
  cmake/Dependencies.cmake:172 (find_package)
  CMakeLists.txt:46 (include)

-- Could NOT find Boost
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
-- Python interface is disabled or not all required dependencies found. Building without it...
-- Found Git: /usr/bin/git (found version "2.17.1") 
-- 
-- ******************* Caffe Configuration Summary *******************
-- General:
--   Version           :   1.0.0
--   Git               :   unknown
--   System            :   Linux
--   C++ compiler      :   /usr/bin/c++
--   Release CXX flags :   -O3 -DNDEBUG -fPIC -Wall -Wno-sign-compare -Wno-uninitialized
--   Debug CXX flags   :   -g -fPIC -Wall -Wno-sign-compare -Wno-uninitialized
--   Build type        :   Release
-- 
--   BUILD_SHARED_LIBS :   ON
--   BUILD_python      :   ON
--   BUILD_matlab      :   OFF
--   BUILD_docs        :   ON
--   CPU_ONLY          :   OFF
--   USE_OPENCV        :   ON
--   USE_LEVELDB       :   ON
--   USE_LMDB          :   ON
--   USE_NCCL          :   OFF
--   ALLOW_LMDB_NOLOCK :   OFF
-- 
-- Dependencies:
--   BLAS              :   Yes (Atlas)
--   Boost             :   Yes (ver. 1.68)
--   glog              :   Yes
--   gflags            :   Yes
--   protobuf          :   Yes (ver. 3.5.0)
--   lmdb              :   Yes (ver. 0.9.21)
--   LevelDB           :   Yes (ver. 1.20)
--   Snappy            :   Yes (ver. ..)
--   OpenCV            :   Yes (ver. 3.4.0)
--   CUDA              :   Yes (ver. 10.0)
-- 
-- NVIDIA CUDA:
--   Target GPU(s)     :   Auto
--   GPU arch(s)       :   sm_61
--   cuDNN             :   Yes (ver. 7.3.1)
-- 
-- Documentaion:
--   Doxygen           :   No
--   config_file       :   
-- 
-- Install:
--   Install path      :   /media/wjl/New/caffese/caffe-4d2400e7ae692b25f034f02ff8e8cd3621725f5c/build/install
-- 
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
CUDA_cublas_device_LIBRARY (ADVANCED)
    linked by target "caffe" in directory /media/wjl/New/caffese/caffe-4d2400e7ae692b25f034f02ff8e8cd3621725f5c/src/caffe

-- Configuring incomplete, errors occurred!
See also "/media/wjl/New/caffese/caffe-4d2400e7ae692b25f034f02ff8e8cd3621725f5c/build/CMakeFiles/CMakeOutput.log".
See also "/media/wjl/New/caffese/caffe-4d2400e7ae692b25f034f02ff8e8cd3621725f5c/build/CMakeFiles/CMakeError.log".

**Comment by alexmyczko** [comment]
my build log is here: 
http://phd-sid.ethz.ch/debian/caffe-cuda/caffe-contrib_1.0.0-8ubuntu2_amd64.build

**Comment by erickim555** [comment]
I ran into this myself, and my fix was to upgrade my CMake version to 3.12.2, I got the idea from: https://github.com/clab/dynet/issues/1457

I dug into it, and the `CUDA_cublas_device_LIBRARY` cmake macro is defined in a fairly recent version of CMake (not sure if 3.12.2 introduced it, but at least it contains it).

I hope that helps!

**Comment by alexmyczko** [comment]
I got it to build from source, no problem. Thanks...

**Comment by urugn** [comment]
After installing cmake 3.12.4 and also installing cuDNN library and the devel package i still had the create_pthread issue. But after i deleted the build directory and recreated it, am now past the create_pthread issue and `cmake  -DBLAS=open ..` completes without errore. Now am having c++ compiler error when i run make.

`
In file included from /usr/include/c++/4.8.2/atomic:38:0,
                 from /usr/include/google/protobuf/io/coded_stream.h:115,
                 from /developer/resources/ai/caffe/caffe/build/include/caffe/proto/caffe.pb.h:23,
                 from /developer/resources/ai/caffe/caffe/build/include/caffe/proto/caffe.pb.cc:4:
/usr/include/c++/4.8.2/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support for the \
  ^
In file included from /usr/include/c++/4.8.2/atomic:41:0,
                 from /usr/include/google/protobuf/io/coded_stream.h:115,
                 from /developer/resources/ai/caffe/caffe/build/include/caffe/proto/caffe.pb.h:23,
                 from /developer/resources/ai/caffe/caffe/build/include/caffe/proto/caffe.pb.cc:4:
/usr/include/c++/4.8.2/bits/atomic_base.h:70:3: error: ‘constexpr’ does not name a type
   constexpr memory_order
   ^
/usr/include/c++/4.8.2/bits/atomic_base.h:70:3: note: C++11 ‘constexpr’ only available with -std=c++11 or -std=gnu++11
/usr/include/c++/4.8.2/bits/atomic_base.h:76:3: error: ‘constexpr’ does not name a type
   constexpr memory_order
   ^
/usr/include/c++/4.8.2/bits/atomic_base.h:76:3: note: C++11 ‘constexpr’ only available with -std=c++11 or -std=gnu++11
/usr/include/c++/4.8.2/bits/atomic_base.h:83:3: error: ‘constexpr’ does not name a type
   constexpr memory_order
   ^
/usr/include/c++/4.8.2/bits/atomic_base.h:83:3: note: C++11 ‘constexpr’ only available with -std=c++11 or -std=gnu++11
/usr/include/c++/4.8.2/bits/atomic_base.h:90:3: error: ‘constexpr’ does not name a type
   constexpr memory_order
   ^
/usr/include/c++/4.8.2/bits/atomic_base.h:90:3: note: C++11 ‘constexpr’ only available with -std=c++11 or -std=gnu++11
/usr/include/c++/4.8.2/bits/atomic_base.h:98:41: error: expected initializer before ‘noexcept’
   atomic_thread_fence(memory_order __m) noexcept
                                         ^
/usr/include/c++/4.8.2/bits/atomic_base.h:102:41: error: expected initializer before ‘noexcept’
   atomic_signal_fence(memory_order __m) noexcept
                                         ^
/usr/include/c++/4.8.2/bits/atomic_base.h:108:30: error: expected initializer before ‘noexcept’
     kill_dependency(_Tp __y) noexcept
                              ^
/usr/include/c++/4.8.2/bits/atomic_base.h:156:25: error: ‘char16_t’ was not declared in this scope
   typedef __atomic_base<char16_t>    atomic_char16_t;
                         ^
/usr/include/c++/4.8.2/bits/atomic_base.h:156:33: error: template argument 1 is invalid
   typedef __atomic_base<char16_t>    atomic_char16_t;
                                 ^
/usr/include/c++/4.8.2/bits/atomic_base.h:156:53: error: invalid type in declaration before ‘;’ token
   typedef __atomic_base<char16_t>    atomic_char16_t;
                                                     ^
/usr/include/c++/4.8.2/bits/atomic_base.h:159:25: error: ‘char32_t’ was not declared in this scope
   typedef __atomic_base<char32_t>    atomic_char32_t;
                         ^
/usr/include/c++/4.8.2/bits/atomic_base.h:159:33: error: template argument 1 is invalid
   typedef __atomic_base<char32_t>    atomic_char32_t;
                                 ^
/usr/include/c++/4.8.2/bits/atomic_base.h:159:53: error: invalid type in declaration before ‘;’ token
   typedef __atomic_base<char32_t>    atomic_char32_t;
                                                     ^
/usr/include/c++/4.8.2/bits/atomic_base.h:162:25: error: ‘char32_t’ was not declared in this scope
   typedef __atomic_base<char32_t>    atomic_char32_t;
                         ^
/usr/include/c++/4.8.2/bits/atomic_base.h:162:33: error: template argument 1 is invalid
   typedef __atomic_base<char32_t>    atomic_char32_t;
                                 ^
/usr/include/c++/4.8.2/bits/atomic_base.h:162:53: error: invalid type in declaration before ‘;’ token
   typedef __atomic_base<char32_t>    atomic_char32_t;
                                                     ^
/usr/include/c++/4.8.2/bits/atomic_base.h:273:17: error: expected ‘;’ at end of member declaration
     atomic_flag() noexcept = default;
                 ^
/usr/include/c++/4.8.2/bits/atomic_base.h:273:19: error: ‘noexcept’ does not name a type
     atomic_flag() noexcept = default;
                   ^
/usr/include/c++/4.8.2/bits/atomic_base.h:274:18: error: expected ‘;’ at end of member declaration
     ~atomic_flag() noexcept = default;
                  ^
/usr/include/c++/4.8.2/bits/atomic_base.h:274:20: error: ‘noexcept’ does not name a type
     ~atomic_flag() noexcept = default;
                    ^
/usr/include/c++/4.8.2/bits/atomic_base.h:280:5: error: ‘constexpr’ does not name a type
     constexpr atomic_flag(bool __i) noexcept
     ^
/usr/include/c++/4.8.2/bits/atomic_base.h:280:5: note: C++11 ‘constexpr’ only available with -std=c++11 or -std=gnu++11
/usr/include/c++/4.8.2/bits/atomic_base.h:282:5: error: expected unqualified-id before ‘{’ token
     { }
     ^
/usr/include/c++/4.8.2/bits/atomic_base.h:285:57: error: expected ‘;’ at end of member declaration
     test_and_set(memory_order __m = memory_order_seq_cst) noexcept
                                                         ^
/usr/include/c++/4.8.2/bits/atomic_base.h:285:59: error: ‘noexcept’ does not name a type
     test_and_set(memory_order __m = memory_order_seq_cst) noexcept
                                                           ^
/usr/include/c++/4.8.2/bits/atomic_base.h:291:59: error: expected ‘;’ at end of member declaration
     test_and_set(memory_order __m = memory_order_seq_cst) volatile noexcept
                                                           ^
/usr/include/c++/4.8.2/bits/atomic_base.h:291:68: error: ‘noexcept’ does not name a type
     test_and_set(memory_order __m = memory_order_seq_cst) volatile noexcept
                                                                    ^
/usr/include/c++/4.8.2/bits/atomic_base.h:297:50: error: expected ‘;’ at end of member declaration
     clear(memory_order __m = memory_order_seq_cst) noexcept
                                                  ^
/usr/include/c++/4.8.2/bits/atomic_base.h:297:52: error: ‘noexcept’ does not name a type
     clear(memory_order __m = memory_order_seq_cst) noexcept`

Any leads on what am i supposed to do. Perhaps enable c++11? Thx

**Comment by urugn** [comment]
After a week of war i finally got Caffe to link. Most importantly i had to compile most dependencies from source and with the same version of gcc in my case i used 7.3.0. 
protobuf
`./configure CXXFLAGS=-std=c++11 --prefix=/usr --with-cc=/usr/local/bin/gcc --with-cxx=/usr/local/bin/g++ --enable-shared --with-pic`
gtest
`cmake -D CMAKE_C_COMPILER=/usr/local/bin/gcc -D CMAKE_CXX_COMPILER=/usr/local/bin/g++ -D CMAKE_INSTALL_PREFIX=/usr  -DBUILD_SHARED_LIBS=ON ..`
leveldb, 
`cmake -DCMAKE_BUILD_TYPE=Release -D CMAKE_C_COMPILER=/usr/local/bin/gcc -D CMAKE_CXX_COMPILER=/usr/local/bin/g++ -D CMAKE_INSTALL_PREFIX=/usr  -DBUILD_SHARED_LIBS=ON ..`
 gflags
`cmake -D CMAKE_C_COMPILER=/usr/local/bin/gcc -D CMAKE_CXX_COMPILER=/usr/local/bin/g++ -D CMAKE_INSTALL_PREFIX=/usr  -DBUILD_SHARED_LIBS=ON ..`
glog
`./autogen.sh && ./configure --prefix=/usr --enable-shared --with-pic`

I had also to make some sym links for /usr/lib/libglog.so and /usr/lib/libgflags.so to /usr/lib64

hope this will helps future ML newbees..

**Comment by Tclz** [comment]
I am facing the similar problem, i use cuda10.1 and ubuntu18.04, and i have also tried the cmake 3.12.2. Could you give me some solution steps ? much thanks! 

CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
CUDA_cublas_LIBRARY (ADVANCED)
    linked by target "caffe" in directory /home/vilbert_beta/bottom-up-attention/caffe/src/caffe

-- Configuring incomplete, errors occurred!
See also "/home/vilbert_beta/bottom-up-attention/caffe/build/CMakeFiles/CMakeOutput.log".
See also "/home/vilbert_beta/bottom-up-attention/caffe/build/CMakeFiles/CMakeError.log".

**Comment by yutao007** [comment]
the same to me .who can  help me .thanks!

**Comment by Tclz** [comment]
> the same to me .who can help me .thanks!

well, this problem may occur when you using cmake in old version. As i mentioned above, cmake 3.12.2 also do not work. finally, i fix that through using cmake 3.14 in Anaconda. Try to upgrade your cmake version. 
Hope this helps you.

**Comment by yutao007** [comment]
thanks . my cmake is 3.16.3 .
i have done it through that
set(CUDA_cublas_LIBRARY /usr/lib/x86_64-linux-gnu/libcublas.so.10 )

**Comment by engineer1109** [comment]
abandon the caffe for years
