### ISSUE TITLE
Caffe OpenCL Branch not compiling on OSX 10.13.6

### ISSUE THREAD

**Issue by soulslicer** [BVLC/caffe#6677]
### Issue summary

Compiling the OpenCL branch results in this error:

```
[  0%] Linking CXX static library ../../lib/libpre_build.a
[  0%] Building CXX object src/caffe/CMakeFiles/caffeproto.dir/__/__/include/caffe/proto/caffe.pb.cc.o
ar: no archive members specified
usage:  ar -d [-TLsv] archive file ...
	ar -m [-TLsv] archive file ...
	ar -m [-abiTLsv] position archive file ...
	ar -p [-TLsv] archive [file ...]
	ar -q [-cTLsv] archive file ...
	ar -r [-cuTLsv] archive file ...
	ar -r [-abciuTLsv] position archive file ...
	ar -t [-TLsv] archive [file ...]
	ar -x [-ouTLsv] archive [file ...]
```

### Steps to reproduce

Compiling the OpenCL branch in OSX 10.13.6

### Tried solutution

The issue seems to be in:

```
add_library(pre_build STATIC ${pre_build_srcs})
							 
caffe_default_properties(pre_build)
set_target_properties(pre_build PROPERTIES LINKER_LANGUAGE CXX)

```

I tried removing STATIC on add_library, but then it throws a ton of errors in

`device_program.cpp`

With errors such as 

`/Users/user/caffe/src/caffe/backend/device_program.cpp:418: error: explicit specialization of 'device_type_name<caffe::bool>' after instantiation`

This all seems to work fine in Ubuntu

**Comment by soulslicer** [comment]
@naibaf7 do you know what this error might be about?

**Comment by gentlesystems** [comment]
I'm getting the same result in 10.14.3.

**Comment by soulslicer** [comment]
I just reverted to Branch fe2a1102. The master branch is broken on OSX

**Comment by gentlesystems** [comment]
I'm confused about why the issue is closed if the branch is still broken?  I'm just trying to find a way to compile OpenCL support on Mac (where the lack of Nvidia support and integrated OpenCL make this particularly relevant).

**Comment by soulslicer** [comment]
You can use the commit I mentioned. It works on macs with AMD cards
