### ISSUE TITLE
Failed to open video

### ISSUE THREAD

**Issue by james09111** [BVLC/caffe#6696]
I am testing on SSD.  ssd_detect.py and  ssd_pascal_wedcam.py are ok, but ssd_pascal_video is fail.
The path has video.

F0221 19:53:56.008097 16157 video_data_layer.cpp:55] Failed to open video: examples/videos/ILSVRC2015_train_00755001.mp4
*** Check failure stack trace: ***
    @     0x7fcc0f39f5cd  google::LogMessage::Fail()
    @     0x7fcc0f3a1433  google::LogMessage::SendToLog()
    @     0x7fcc0f39f15b  google::LogMessage::Flush()
    @     0x7fcc0f3a1e1e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fcc0fc1e597  caffe::VideoDataLayer<>::DataLayerSetUp()
    @     0x7fcc0fb36b73  caffe::BasePrefetchingDataLayer<>::LayerSetUp()
    @     0x7fcc0fafa2d4  caffe::Net<>::Init()
    @     0x7fcc0fafc2c0  caffe::Net<>::Net()
    @           0x4097c7  test()
    @           0x4077e8  main
    @     0x7fcc0db35830  __libc_start_main
    @           0x4080b9  _start
    @              (nil)  (unknown)
Aborted (core dumped)

### System configuration

* Operating system: ubuntu 16.04
* CUDA version : 9.0
* CUDNN version : 7.4.1
* Python version : 2.7

**Comment by Jiang1206** [comment]
Have you solved the problem?

**Comment by james09111** [comment]
Yes,I have solved.  I uninstall original opencv and install opencv3.4.1.
Please remember to install  ffmpeg  library dependency before you install
opencv.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
不含病毒。www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Jiang1206 <notifications@github.com> 於 2019年4月28日 週日 上午9:47寫道：
