### ISSUE TITLE
E: Package 'caffe-cuda' has no installation candidate

### ISSUE THREAD

**Issue by leigao97** [BVLC/caffe#6753]
I'm trying to install Caffe on Ubuntu 18.04, when I do `sudo apt install caffe-cuda`, the terminal gives me the following error:
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package caffe-cuda is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'caffe-cuda' has no installation candidate
```
I have tried apt-get update and upgrade, but it didn't work. Does any know how to solve this problem? Thank you in advance!

**Comment by TDBTECHNO** [comment]
did you find any solution yet?

**Comment by AntonyLi927** [comment]
The same question I have encountered. Have you solved this problem?

**Comment by Zander-J** [comment]
I have a same problem on Ubuntu 20.04. Is there a solution yet?

**Comment by AntonyLi927** [comment]
I've installed caffe by a different way through searching on Baidu. Maybe
you can find a way of installation on Baidu or Google. (Baidu is a search
engine in China.)

jzh109 ***@***.***> 于2021年7月24日周六 上午9:59写道：
