### ISSUE TITLE
Caffe-users group does not exist?

### ISSUE THREAD

**Issue by nemkin** [BVLC/caffe#6763]
Hello,

I am having trouble installing caffe and I wanted to post in https://groups.google.com/forum/#!forum/caffe-users but when I open the link this is the message I get:

"This group either doesn't exist, or you don't have permission to access it. If you're sure this group exists, contact the owner of the group and ask them to give you access."

Seems like the issue is similar to this one: https://github.com/BVLC/caffe/issues/4651

Could you help me gain access to the group?

Thank you!

Best regards,
Viktória

**Comment by hongsoog** [comment]
Hello,
Is there anyone access to https://groups.google.com/forum/#!forum/caffe-users ?
I cannot access the forum.
What should I do in order to access the forum if anyone access to the forum?

Thanks

**Comment by nemkin** [comment]
I just tried today and it works for me now.
