### ISSUE TITLE
Aborted at 1558541366 (unix time)  0x7fc1471a11ea caffe::UpgradeSnapshotPrefixProperty()

### ISSUE THREAD

**Issue by zgq91** [BVLC/caffe#6771]
Hi:
    Executing make runtest and make pycaffe  is fine, but ./examples/mnist/train_lenet_adam.sh 
*** Aborted at 1558541366 (unix time) try "date -d @1558541366" if you are using GNU date ***
PC: @     0x7fc145433512 (unknown)
*** SIGSEGV (@0x6) received by PID 3108 (TID 0x7fc147dcf740) from PID 6; stack trace: ***
    @     0x7fc1453e44b0 (unknown)
    @     0x7fc145433512 (unknown)
    @     0x7fc1471a11ea caffe::UpgradeSnapshotPrefixProperty()
    @     0x7fc1471a1530 caffe::ReadSolverParamsFromTextFileOrDie()
    @           0x40a408 train()
    @           0x407508 main
    @     0x7fc1453cf830 (unknown)
    @           0x407f09 _start
Segmentation fault (core dumped)

environment：
  ubuntu16.04  anaconda3 python3.6  cuda9.0

**Comment by LPCelite** [comment]
have you resolved this problem? I am stuck in this bug!

**Comment by zgq91** [comment]
comment  USE_CUDNN

**Comment by qyqbird** [comment]
maybe it cover up the true problem
