### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by zimenglan-sysu** [BVLC/caffe#678]
After compiling the source code,  i run the sh file, it suddently crashes

I0712 11:03:59.634418 29009 solver.cpp:46] Creating testing net.
I0712 11:03:59.634877 29009 net.cpp:78] Creating Layer data
I0712 11:03:59.634886 29009 net.cpp:114] data -> data
I0712 11:03:59.634892 29009 net.cpp:114] data -> label
I0712 11:03:59.634898 29009 data_layer.cpp:450] Opening leveldb imagenet_val_leveldb
I0712 11:03:59.724553 29009 net.cpp:129] Top shape: 64 5 220 220 (15488000)
I0712 11:03:59.724570 29009 net.cpp:129] Top shape: 64 48 1 1 (3072)
I0712 11:03:59.724576 29009 net.cpp:160] data does not need backward computation.
I0712 11:03:59.724586 29009 net.cpp:78] Creating Layer conv1
I0712 11:03:59.724591 29009 net.cpp:88] conv1 <- data
I0712 11:03:59.724596 29009 net.cpp:114] conv1 -> conv1
Segmentation fault (core dumped)
Done.

Any ideas on locating the problem?

Thanks.

**Comment by fanguu** [comment]
I face the problem to train the lstm. My computer have cudnn-v5, cuda 8.0 and the caffe version is lisa-caffe. The python path is changed by instruction

![unnamed qq screenshot20170825141155](https://user-images.githubusercontent.com/21071524/29701734-21fa853c-89a0-11e7-9e92-63399c1d5c00.png)

**Comment by myproject24** [comment]
Hi @OpenHero @zimenglan-sysu, I am facing same please suggest me what is solution for this problem and I am running caffe model inside docker container.
