### ISSUE TITLE
make all error (Makefile:583: .build_release/lib/libcaffe.so.1.0.0)

### ISSUE THREAD

**Issue by XijieJiao** [BVLC/caffe#6781]
My system is mac os 10.13.6  I use the cpu-only mode, therefore, no cuda, no cudnn.
After I ran make all, I faced the following error. The previous steps should be correct.
Does anyone have any idea what the problem should be here?

make all
CXX src/caffe/util/io.cpp
CXX src/caffe/util/db_leveldb.cpp
CXX src/caffe/util/insert_splits.cpp
CXX src/caffe/layer_factory.cpp
CXX src/caffe/blob.cpp
CXX src/caffe/layer.cpp
CXX src/caffe/solvers/nesterov_solver.cpp
CXX src/caffe/solvers/adam_solver.cpp
CXX src/caffe/solvers/sgd_solver.cpp
CXX src/caffe/solvers/adadelta_solver.cpp
CXX src/caffe/solvers/adagrad_solver.cpp
CXX src/caffe/solvers/rmsprop_solver.cpp
CXX src/caffe/internal_thread.cpp
CXX src/caffe/net.cpp
CXX src/caffe/solver.cpp
CXX src/caffe/syncedmem.cpp
AR -o .build_release/lib/libcaffe.a
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: .build_release/lib/libcaffe.a(cudnn_pooling_layer.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: .build_release/lib/libcaffe.a(cudnn_lcn_layer.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: .build_release/lib/libcaffe.a(cudnn_conv_layer.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: .build_release/lib/libcaffe.a(cudnn_tanh_layer.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: .build_release/lib/libcaffe.a(cudnn_deconv_layer.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: .build_release/lib/libcaffe.a(cudnn_softmax_layer.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: .build_release/lib/libcaffe.a(cudnn_relu_layer.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: .build_release/lib/libcaffe.a(cudnn_lrn_layer.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: .build_release/lib/libcaffe.a(cudnn_sigmoid_layer.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: .build_release/lib/libcaffe.a(parallel.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: .build_release/lib/libcaffe.a(cudnn.o) has no symbols
LD -o .build_release/lib/libcaffe.so.1.0.0
ld: warning: -pie being ignored. It is only used when linking a main executable
ld: cannot link directly with /System/Library/Frameworks//vecLib.framework/vecLib.tbd for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Makefile:583: .build_release/lib/libcaffe.so.1.0.0] Error 1

**Comment by XijieJiao** [comment]
Solved after reinstalling the system.

**Comment by mapavia** [comment]
> Solved after reinstalling the system.

Hi, what do you mean by reinstalling the system? I am encountering similar issues.

**Comment by XijieJiao** [comment]
I mean that reinstalling the whole Mac OS system helped me solve the problem. The problem may come from the redundancy and versions of different libs which can be hard to shot.

By the way, the problem occurred and was solved more than half a year ago. I forgot most of the details. 

Hope this may help.

Best,
Xijie Jiao
