### ISSUE TITLE
How to check GPU or CUDA exist before set gpu model

### ISSUE THREAD

**Issue by haikuoyao** [BVLC/caffe#6825]
Anyone knows,
how can I check if GPU or CUDA exists before setting gpu model

```
if CUDA or GPU Check ?
        caffe.set_mode_gpu()
        caffe.set_device(0)
```

Thanks.

**Comment by ravibanger** [comment]
In C/C++ you can use the function [get_gpus](https://github.com/BVLC/caffe/blob/04ab089db018a292ae48d51732dd6c66766b36b6/tools/caffe.cpp#L89)().

**Comment by haikuoyao** [comment]
@ravibanger 
Thanks a lot. 
I just do this in my python code
```
def is_available():

    """
        Check NVIDIA with nvidia-smi command
        Returning code 0 if no error, it means NVIDIA is installed
        Other codes mean not installed
    """
    code = os.system('nvidia-smi')
    return code == 0
```
