### ISSUE TITLE
make runtest error

### ISSUE THREAD

**Issue by kli017** [BVLC/caffe#6829]
## Important - read before submitting

*Please read the [guidelines for contributing](https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md) before submitting this issue!*

*Please do not post installation, build, usage, or modeling questions, or other requests for help to Issues.*
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead.
This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

### System configuration

* Operating system: 
* Compiler: 
* CUDA version (if applicable): 
* CUDNN version (if applicable): 
* BLAS: 
* Python version (if using pycaffe): 
* MATLAB version (if using matcaffe): 

### Issue checklist

- [x] read the guidelines and removed the first paragraph
- [x] written a short summary and detailed steps to reproduce
- [x] explained how solutions to related problems failed (tick if found none)
- [x] filled system configuration
- [x] attached relevant logs/config files (tick if not applicable)

**Comment by kli017** [comment]
Ubuntu16.04
CUDA 9.2
cundd7.6.3
python3.6.5

[----------] 14 tests from DataLayerTest/1, where TypeParam = caffe::CPUDevice<double>
[ RUN      ] DataLayerTest/1.TestSkipLevelDB
*** Aborted at 1567851757 (unix time) try "date -d @1567851757" if you are using GNU date ***
PC: @     0x7f50f2c90931 (unknown)
*** SIGSEGV (@0x8b43fc17e) received by PID 3141 (TID 0x7f50b08e1700) from PID 18446744072438661502; stack trace: ***
    @     0x7f50e8f3f390 (unknown)
    @     0x7f50f2c90931 (unknown)
    @     0x7f50ea3dc81e std::_Rb_tree<>::_M_insert_unique()
    @     0x7f50ea3d49f8 boost::detail::add_new_tss_node()
    @     0x7f50ea3d4c43 boost::detail::set_tss_data()
    @     0x7f50e95ed3bd caffe::Caffe::Get()
    @     0x7f50e9649cc0 caffe::InternalThread::entry()
    @     0x7f50e964aade boost::detail::thread_data<>::run()
    @     0x7f50ea3d25d5 (unknown)
    @     0x7f50e8f356ba start_thread
    @     0x7f50e8c6b41d clone
    @                0x0 (unknown)
Makefile:542: recipe for target 'runtest' failed

**Comment by Darcyzh** [comment]
Hello, I have the same problem for a few days, but I haven't solved it yet. Have you solved it? May you share something?

**Comment by kli017** [comment]
@Darcyzh I have no idea whats going wrong.. Maybe is the verson of libboost doesnt match. Finally I just reinstall the ubuntu and solved.
