### ISSUE TITLE
AttributeError: module 'caffe.proto.caffe_pb2' has no attribute 'LabelMap'

### ISSUE THREAD

**Issue by Samjith888** [BVLC/caffe#6830]
Traceback (most recent call last):
File "/home/sam/train_caffe/data/CustomDataset/../../scripts/create_annoset.py", line 103, in
label_map = caffe_pb2.LabelMap()
AttributeError: module 'caffe.proto.caffe_pb2' has no attribute 'LabelMap'
Traceback (most recent call last):
File "/home/sam/train_caffe/data/CustomDataset/../../scripts/create_annoset.py", line 103, in
label_map = caffe_pb2.LabelMap()
AttributeError: module 'caffe.proto.caffe_pb2' has no attribute 'LabelMap'

I'm training on custom dataset by using caffe. I got the above error while run **bash create_imagenet.sh** to create lmdb files.

OS :ubuntu

**Comment by Samjith888** [comment]
@sergeyk @pluskid @Franck-Dernoncourt @darxriggs

**Comment by DonghunP** [comment]
How can you solve this problem??

**Comment by Samjith888** [comment]
I didn''t get any response about this issue from the authors.

@pluskid @Franck-Dernoncourt @sergeyk

**Comment by zssjh** [comment]
> I didn''t get any response about this issue from the authors.
> 
> @pluskid @Franck-Dernoncourt @sergeyk

have you solved the problem?
