### ISSUE TITLE
how to develop new layers

### ISSUE THREAD

**Issue by wshenx** [BVLC/caffe#684]
Hi everyone. I'm new to caffe. I want to develop new layers but I don't know to start. I checked the development guide on http://caffe.berkeleyvision.org/development.html. But I still have no clues. Is there anyone who can give a small tutorial step by step on how to develop a new layer in caffe. That will be of great value. Thanks.

**Comment by kuaitoukid** [comment]
It is not a must, but safe to write a test file

**Comment by zisetiankong324** [comment]
@longjon  Hi,I followed your step and I have added my new layer,however,when I run caffe,I encountered an error:segmentation fault(core denied),would you please tell me what happend?

**Comment by gucasdongzi** [comment]
@longjon good~

**Comment by antran89** [comment]
@wshenx You can use QtCreator + Cmake combination that I used in Linux.

**Comment by artiit** [comment]
If I want to use GPU to train net, and I only write the cpp code, no .cu file, Is it OK?

**Comment by antran89** [comment]
@artiit Then your Caffe only runs on CPU. By default, Caffe has a safe fall-back mechanism when you do not have GPU CUDA implementation.

**Comment by williford** [comment]
For future reference, the wiki page has apparently moved to https://github.com/BVLC/caffe/wiki/Development

**Comment by LinHungShi** [comment]
@williford I follow the step, but when I train the model, it says unknown layer type.. Do I have to remake caffe after I write the new layer?

**Comment by misaka-10032** [comment]
It takes so long to test all the layers. Is there a way to only test a specific layer?

**Comment by matthieudelaro** [comment]
Here is the complete command I use to recompile caffe, recompile the tests, and run the tests of the layer I'm working on:
```
make all && make test && build/test/test_all.testbin --gtest_filter='*LocalLayerTest*'"
```

**Comment by cuijianaaa** [comment]
use Code::Blocks in linux，just like visual studio in windows，very easy

**Comment by PhilippeCb** [comment]
@cuijianaaa I am trying to use code::block to speed up the testing but cannot manage to start a project with existing files, and I am not confident enough to work directly in the caffe home directory (caffe is finaly working and I would like to keep it that way :) ) 
could you tell me how to create a project from a copy of the caffe directory?
or if this is absolutely the wrong way to do it please tell me I am new to programming
