### ISSUE TITLE
Link to bvlc_googlenet.caffemodel not working

### ISSUE THREAD

**Issue by patersonc** [BVLC/caffe#6864]
I'm trying to access the `bvlc_googlenet.caffemodel` model that is linked to in [readme.md](https://github.com/BVLC/caffe/blob/master/models/bvlc_googlenet/readme.md), but it appears that the link (http://dl.caffe.berkeleyvision.org/bvlc_googlenet.caffemodel) is dead.

Is anyone else seeing this issue?

Has the file been relocated? Or is it just a temporary glitch in the matrix?

**Comment by sagarjogadhenu** [comment]
I see the same issue!

**Comment by kadirbeytorun** [comment]
I have same issue with caffe_ilsvrc12.tar.gz on dl.caffe server, I think download server is all down for a while. But I couldn't find any information about when they will be up again.

**Comment by shelhamer** [comment]
The server is indeed down right now. Sorry for the temporary glitch, but the files will return, once we figure out alternative hosting.

**Comment by patersonc** [comment]
Thanks @shelhamer

**Comment by lutzroeder** [comment]
```
~: curl http://dl.caffe.berkeleyvision.org/bvlc_alexnet.caffemodel 
curl: (52) Empty reply from server
```

**Comment by srishkee** [comment]
I was facing the same issue a few days ago. I found this model on Codalab: https://worksheets.codalab.org/bundles/0x36208f78facf4a51aee2597bbea901d0

@shelhamer Do you know if this is the exact same model as the one on the berkeleyvision.org site? It appears to be trained by the same person.

**Comment by shelhamer** [comment]
http://dl.caffe.berkeleyvision.org/ is back up! We're looking in to migrating it to more reliable hosting so that these materials don't go down again.

**Comment by Hong-333** [comment]
@shelhamer The site still won't open.

**Comment by Hong-333** [comment]
@shelhamer The site still doesn't open.

**Comment by shelhamer** [comment]
Sorry, it went back down again after being briefly up again. We have now retired that host, and migrated the materials to cloud hosting, so they are back up and should remain up more reliably now!

**Comment by bpinaya** [comment]
Btw the server is down again: 
```bash
wget http://dl.caffe.berkeleyvision.org/bvlc_alexnet.caffemodel
```
returns: 
```bash
--2022-10-24 14:43:20--  http://dl.caffe.berkeleyvision.org/bvlc_alexnet.caffemodel
Resolving dl.caffe.berkeleyvision.org (dl.caffe.berkeleyvision.org)... 128.32.162.150
Connecting to dl.caffe.berkeleyvision.org (dl.caffe.berkeleyvision.org)|128.32.162.150|:80... connected.
HTTP request sent, awaiting response... Read error (Connection reset by peer) in headers.
Retrying.

```

**Comment by md3848** [comment]
i have same problem.

I downloaded the models from the link below.
https://github.com/facebookarchive/models
