### ISSUE TITLE
Are there any plans to release a prebuilt-binary for Windows?

### ISSUE THREAD

**Issue by AlanCPSC** [BVLC/caffe#6874]
Hello everyone,

I was wondering if you guys have any plans to release official prebuilt-binaries for Windows 7/8/10 (+ Mac OS if possible)? I've been working on helping fellow students at school install caffe onto their laptops - mainly through python's anaconda online package registry (https://anaconda.org/search?q=caffe).

Unfortunately this has been an incredibly challenging task, as finding a compatible distribution for everyone has not been easy.

I believe that releasing official prebuilt-binaries will help beginners/students pick up this library quicker.

**Comment by willyd** [comment]
Hi @AlanCPSC, I am (maybe was would be more appropriate here) responsible for maintaining the Windows branch. I tried to maintain pre-built binaries but I soon realized that it takes a considerable amount of time to create binaries with support for every python version and every cuda version. I created some [packages](https://anaconda.org/willyd/caffe/files) a year ago but I really don't have time to maintain them as CUDA and Python get updated. 

Also, it is very hard to compete with tensorflow and PyTorch in terms of support.

I really don't have much time for this (unpaid) work these days. You may try to build your own packages using the recipes I create [here](https://github.com/willyd/caffe/tree/windows/conda).

**Comment by AlanCPSC** [comment]
Thank you for your response. I appreciate your contribution and development of this library for the rest of us. Some followup questions that I have related to this matter are:

**Question 1)** I have looked at [the recipes you provided](https://github.com/willyd/caffe/tree/windows/conda), and I am a bit confused on how to exactly utilize them. Do I just run the `bld.bat` file on a windows machine? Are there any preparatory steps required before building? Any pointers would be great.

**Question 2)** Regarding the work required to prepare prebuilt-binaries. Is this due to difficulty with the everchanging CUDA specification. Or is this due to a difficulty building the binaries themselves (e.g. some non-trivial aspect that I am not aware of). Perhaps I can be of assistance.

**Comment by willyd** [comment]
**1)* * You need to install conda build. `conda install conda-build` then `cd` to the recipes directory and `conda build .`.

**2)** The difficulty is more related to me not having the time to test every combination of Python and CUDA that people want to use.
