### ISSUE TITLE
 fatal error: mex.h: No such file or directory

### ISSUE THREAD

**Issue by crazybirds** [BVLC/caffe#692]
hello, when I do make make matcafe.cpp, it has the following errors, I already set the matlab path  in makefile.configure, where I set MATLAB_DIR := /usr/local/MATLAB/R2014a, this is my matlab path
Can anyone help me with this? Many thanks!

caffe-0.999/matlab/caffe# make matcaffe
g++     matcaffe.cpp   -o matcaffe
matcaffe.cpp:10:17: fatal error: mex.h: No such file or directory

**Comment by lzqcode** [comment]
i also encountered this problem now,i would like to ask you how to she the path specifically?
