### ISSUE TITLE
cudnndeconvolutionlayer test/3 check failed：status == CUDNN_STATUS_SUCCESS (3 vs. 0)  CUDNN_STATUS_BAD_PARAM

### ISSUE THREAD

**Issue by sjam-aj** [BVLC/caffe#6999]
## Important - read before submitting

*Please read the [guidelines for contributing](https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md) before submitting this issue!*

*Please do not post installation, build, usage, or modeling questions, or other requests for help to Issues.*
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead.
This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

### Issue summary
runtest failed
CuDNNDeconvolutionLayerTest/3.TestNDAgainst2D
![image](https://user-images.githubusercontent.com/75112081/113986855-4d986180-9880-11eb-9a6c-c1964ae2e0d9.png)

### Tried solutions
Please help me to solve this problem！

### System configuration

* Operating system: ubuntu16.04
* Compiler: g ++
* CUDA version (if applicable): 10.2
* CUDNN version (if applicable): 8.04
* BLAS: atlas
* Python version (if using pycaffe): 3.7
* MATLAB version (if using matcaffe): 

### Issue checklist

- [ ] read the guidelines and removed the first paragraph
- [ ] written a short summary and detailed steps to reproduce
- [ ] explained how solutions to related problems failed (tick if found none)
- [ ] filled system configuration
- [ ] attached relevant logs/config files (tick if not applicable)

**Comment by artyom-beilis** [comment]
How did you build against 8.04? Some APIs were removed

**Comment by sjam-aj** [comment]
>
