### ISSUE TITLE
Extract Features from fc7 

### ISSUE THREAD

**Issue by afshindn** [BVLC/caffe#700]
Hi

I have two questions. 
1. The tutorial provided (http://nbviewer.ipython.org/github/BVLC/caffe/blob/master/examples/filter_visualization.ipynb) to extract features from different layers does not seem to be an efficient way of doing it. It takes around 0.5 second to extract features. Is there a way to speed it up or process images in batch mode? I assume it should take only a couple ms on a K40.
2. I tried to use the binary provided in builds/tools/extract_features.bin which seems to have batch model built in. But the features are save in leveldb format and I don't know how to read that in python?

Thanks

**Comment by kadarakos** [comment]
Hi sergey,

I implemented you suggestion, but i get the error:

Traceback (most recent call last):
  File "2.py", line 44, in <module>
    main(sys.argv)
  File "2.py", line 36, in main
    predictions = out['fc7'].squeeze(axis=(2,3))
ValueError: 'axis' entry 2 is out of bounds [-1, 1)

Do you have a guess why is this the case?

Thank you!

**Comment by seanbell** [comment]
Blobs are now general N-D and not 4D.  So the "squeeze" is no longer necessary.  See #1970.

You can try debugging with `print out['fc7'].shape` to see the new dimensions.

**Comment by anurikadisha** [comment]
Hi,

I ran python python/classify.py examples/images temp from the caffe root directory but get the following error:

Traceback (most recent call last):
  File "python/classify.py", line 138, in <module>
    main(sys.argv)
  File "python/classify.py", line 110, in main
    channel_swap=channel_swap)
  File "/home/anurika/Downloads/caffe-master-n/python/caffe/classifier.py", line 34, in __init__
    self.transformer.set_mean(in_, mean)
  File "/home/anurika/Downloads/caffe-master-n/python/caffe/io.py", line 255, in set_mean
    raise ValueError('Mean shape incompatible with input shape.')
ValueError: Mean shape incompatible with input shape.

Can anyone please help?

**Comment by xksteven** [comment]
As shown here #2075 
This can be fixed by changing:
mean=np.load(mean_file)
to this:
mean=np.load(mean_file).mean(1).mean(1)
