### ISSUE TITLE
Real time classification using ImageNet pretrained model 

### ISSUE THREAD

**Issue by hyungwonchoi** [BVLC/caffe#708]
I am currently working on implementing real time webcam demo using ImageNet pretrained model. 

Do I have to change the input layer type rather than just using data layer?
Also, do I have to train the model again if I want to change the input to the network?

Any helps would be appreciated.

Hyungwon

**Comment by jayajadhav** [comment]
Hello hyungwonchoi,
Have you got the answer?
I have the same question in my mind. please help me if you have got the answer.
