### ISSUE TITLE
issue with matlab r2014a crach, when call scores = caffe('forward', input_data);

### ISSUE THREAD

**Issue by crazybirds** [BVLC/caffe#713]
Hi Guys,

When I call caffe function on my machine (Ubuntu 14.04LTS, Matlab R2014a), I got a fatal error. 
The code I am trying to run is as follows:
im = imread('../../examples/images/cat.jpg');
images = prepare_image(im);
input_data = {prepare_image(im)};
scores = caffe('forward', input_data);
I have tried 
export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libstdc++.so.6
and followed 
https://github.com/BVLC/caffe/pull/696. 
If I made changes as indicated in https://github.com/BVLC/caffe/pull/696. I can't get caffe.mexa64. 
when I type caffe('get_init_key'), I can get -2.

I'm going to copy paste this below. I can't figure out what the problem is, so I thought I could post here.
Thanks.

---

```
   Segmentation violation detected at Thu Jul 17 00:12:06 2014
```

---

Configuration:
  Crash Decoding     : Disabled
  Current Visual     : 0x20 (class 4, depth 24)
  Default Encoding   : UTF-8
  GNU C Library      : 2.19 stable
  MATLAB Architecture: glnxa64
  MATLAB Root        : /usr/local/MATLAB/R2014a
  MATLAB Version     : 8.3.0.532 (R2014a)
  Operating System   : Linux 3.13.0-30-generic #55-Ubuntu SMP Fri Jul 4 21:40:53 UTC 2014 x86_64
  Processor ID       : x86 Family 6 Model 60 Stepping 3, GenuineIntel
  Virtual Machine    : Java 1.7.0_11-b21 with Oracle Corporation Java HotSpot(TM) 64-Bit Server VM mixed mode
  Window System      : The X.Org Foundation (11501000), display :0.0

Fault Count: 1

Abnormal termination:
Segmentation violation

Register State (from fault):
  RAX = 00007ff46a6d3c20  RBX = 0000000000000000
  RCX = 00007ff561b6a498  RDX = 0000000000000001
  RSP = 00007ff561b69c90  RBP = 00007ff561b69d00
  RSI = 00007ff561b6a550  RDI = 0000000000000001

   R8 = 0000000000000002   R9 = 00007ff561b69a3a
  R10 = 00007ff4d23d1fae  R11 = 00007ff57404a770
  R12 = 00007ff46a6d3c38  R13 = 00007ff561b6a498
  R14 = 00007ff5623b39e0  R15 = 0000000000000002

  RIP = 00007ff46a2c4bc7  EFL = 0000000000010246

   CS = 0033   FS = 0000   GS = 0000

Stack Trace (from fault):
[  0] 0x00007ff46a2c4bc7 /home/xiaolong/project/caffe-0.999/matlab/caffe/caffe.mexa64+00097223
[  1] 0x00007ff46a2c3b3e /home/xiaolong/project/caffe-0.999/matlab/caffe/caffe.mexa64+00092990 mexFunction+00000223
[  2] 0x00007ff56be2472a     /usr/local/MATLAB/R2014a/bin/glnxa64/libmex.so+00120618 mexRunMexFile+00000090
[  3] 0x00007ff56be20a94     /usr/local/MATLAB/R2014a/bin/glnxa64/libmex.so+00105108
[  4] 0x00007ff56be21fb4     /usr/local/MATLAB/R2014a/bin/glnxa64/libmex.so+00110516
[  5] 0x00007ff56b21bad9 /usr/local/MATLAB/R2014a/bin/glnxa64/libmwm_dispatcher.so+00670425 _ZN8Mfh_file11dispatch_fhEiPP11mxArray_tagiS2_+00000697
[  6] 0x00007ff56a4b82b4 /usr/local/MATLAB/R2014a/bin/glnxa64/libmwm_interpreter.so+04461236
[  7] 0x00007ff56a4b9bc9 /usr/local/MATLAB/R2014a/bin/glnxa64/libmwm_interpreter.so+04467657
[  8] 0x00007ff56a4ba3fc /usr/local/MATLAB/R2014a/bin/glnxa64/libmwm_interpreter.so+04469756
[  9] 0x00007ff56a3346e3 /usr/local/MATLAB/R2014a/bin/glnxa64/libmwm_interpreter.so+02873059
[ 10] 0x00007ff56a34409e /usr/local/MATLAB/R2014a/bin/glnxa64/libmwm_interpreter.so+02936990
[ 11] 0x00007ff56a344183 /usr/local/MATLAB/R2014a/bin/glnxa64/libmwm_interpreter.so+02937219
[ 12] 0x00007ff56a47a172 /usr/local/MATLAB/R2014a/bin/glnxa64/libmwm_interpreter.so+04206962
[ 13] 0x00007ff56a2b0df8 /usr/local/MATLAB/R2014a/bin/glnxa64/libmwm_interpreter.so+02334200
[ 14] 0x00007ff56a30e30b /usr/local/MATLAB/R2014a/bin/glnxa64/libmwm_interpreter.so+02716427
[ 15] 0x00007ff56b21bc5f /usr/local/MATLAB/R2014a/bin/glnxa64/libmwm_dispatcher.so+00670815 _ZN8Mfh_file11dispatch_fhEiPP11mxArray_tagiS2_+00001087
[ 16] 0x00007ff56a2e1135 /usr/local/MATLAB/R2014a/bin/glnxa64/libmwm_interpreter.so+02531637
[ 17] 0x00007ff56a2a80d9 /usr/local/MATLAB/R2014a/bin/glnxa64/libmwm_interpreter.so+02298073
[ 18] 0x00007ff56a2a4dc7 /usr/local/MATLAB/R2014a/bin/glnxa64/libmwm_interpreter.so+02284999
[ 19] 0x00007ff56a2a5193 /usr/local/MATLAB/R2014a/bin/glnxa64/libmwm_interpreter.so+02285971
[ 20] 0x00007ff56c04eafc /usr/local/MATLAB/R2014a/bin/glnxa64/libmwbridge.so+00142076
[ 21] 0x00007ff56c04f791 /usr/local/MATLAB/R2014a/bin/glnxa64/libmwbridge.so+00145297 _Z8mnParserv+00000721
[ 22] 0x00007ff57530692f   /usr/local/MATLAB/R2014a/bin/glnxa64/libmwmcr.so+00489775 _ZN11mcrInstance30mnParser_on_interpreter_threadEv+00000031
[ 23] 0x00007ff5752e7b6d   /usr/local/MATLAB/R2014a/bin/glnxa64/libmwmcr.so+00363373
[ 24] 0x00007ff5752e7be9   /usr/local/MATLAB/R2014a/bin/glnxa64/libmwmcr.so+00363497
[ 25] 0x00007ff5699dad46   /usr/local/MATLAB/R2014a/bin/glnxa64/libmwuix.so+00343366
[ 26] 0x00007ff5699bd382   /usr/local/MATLAB/R2014a/bin/glnxa64/libmwuix.so+00222082
[ 27] 0x00007ff575a5c50f /usr/local/MATLAB/R2014a/bin/glnxa64/libmwservices.so+02323727
[ 28] 0x00007ff575a5c67c /usr/local/MATLAB/R2014a/bin/glnxa64/libmwservices.so+02324092
[ 29] 0x00007ff575a5857f /usr/local/MATLAB/R2014a/bin/glnxa64/libmwservices.so+02307455
[ 30] 0x00007ff575a5d9b5 /usr/local/MATLAB/R2014a/bin/glnxa64/libmwservices.so+02329013
[ 31] 0x00007ff575a5dde7 /usr/local/MATLAB/R2014a/bin/glnxa64/libmwservices.so+02330087
[ 32] 0x00007ff575a5e4c0 /usr/local/MATLAB/R2014a/bin/glnxa64/libmwservices.so+02331840 _Z25svWS_ProcessPendingEventsiib+00000080
[ 33] 0x00007ff5752e8098   /usr/local/MATLAB/R2014a/bin/glnxa64/libmwmcr.so+00364696
[ 34] 0x00007ff5752e83bf   /usr/local/MATLAB/R2014a/bin/glnxa64/libmwmcr.so+00365503
[ 35] 0x00007ff5752e328f   /usr/local/MATLAB/R2014a/bin/glnxa64/libmwmcr.so+00344719
[ 36] 0x00007ff574291182              /lib/x86_64-linux-gnu/libpthread.so.0+00033154
[ 37] 0x00007ff573fbe30d                    /lib/x86_64-linux-gnu/libc.so.6+01028877 clone+00000109

This error was detected while a MEX-file was running. If the MEX-file
is not an official MathWorks function, please examine its source code
for errors. Please consult the External Interfaces Guide for information
on debugging MEX-files.

If this problem is reproducible, please submit a Service Request via:
    http://www.mathworks.com/support/contact_us/

A technical support engineer might contact you with further information.

Thank you for your help.*\* This crash report has been saved to disk as /home/

**Comment by cslxiao** [comment]
How did you solve this? @crazybirds 
I got the same problem and still unsolved.
