### ISSUE TITLE
[Ubuntu | Python wrapper]: cannot "import caffe"

### ISSUE THREAD

**Issue by luzhi** [BVLC/caffe#720]
I cannot "import caffe" in my python interactive shell. The error message is:

```
>>>import caffe
   Traceback (most recent call last): 
    File "<stdin>", line 1, in <module> 
   ImportError: No module named caffe
```

I performed "make pycaffe" in /caffe/ folder after "make all" and check all the dependencies. The ubuntu version is 14.04, python 2.7.6 .

In addition, if I tried to "import _caffe.so" the error message is:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: libcudart.so.6.0: cannot open shared object file: No such file or directory
```

Thanks!

**Comment by LinZhineng** [comment]
@luzhi  Thanks for your answer

**Comment by attiliotnt** [comment]
@luzhi  should I every time type I open the python console:
export PYTHONPATH=/home/username/caffe/python
from home ?

(sorry I'm a bit confused)

**Comment by evamy** [comment]
@attiliotnt 

luzhi said add this line in your ".bashrc" file which is located at "/home".

That way, terminal will run this line every time you open it ! So, no, you don't have to run it every time.

**Comment by sayadyaghoobi** [comment]
i got the same error! anyone has solved this please give us the point. i compiled and set path correctly but still it give me no caffe module found

**Comment by evamy** [comment]
@sayadyaghoobi 
I am hoping you are compiling caffe twice (i.e. once in the main repository and the other time in the recursively imported repository) and then posting the problems ?

Also, the PYTHONPATH exported would be better as:
export PYTHONPATH=/complete/path/to/caffe/python:$PYTHONPATH

in either your ~/.bashrc or ~/.bash_profile.

(The $PYTHONPATH also appends everything else in the new PYTHONPATH)

**Comment by MingmingWarm** [comment]
caffe_root = '../../../caffe-master/'    (This is the path of  caffe-master)
import sys  
sys.path.insert(0, caffe_root + 'python')  
import caffe 


you should add above lines in the script.

**Comment by DerOzean** [comment]
Okay, I ran in the same Problem.
I tried to import chainer and use caffe
 I found a solution here: https://teratail.com/questions/82964
So do this in top of your code:
import chainer
import chainer.links
from chainer.links import caffe
The original code was :
import chainer
import chainer.functions as F
from chainer.functions import caffe
Please also import functions as F so the code will work as it was intended
