### ISSUE TITLE
Why does extracting features process 500 query files irrespective of the number of images inside /examples/images folder

### ISSUE THREAD

**Issue by dasabir** [BVLC/caffe#722]
I think I'm doing something wrong when I try to extract features. I'm following the instructions given in http://caffe.berkeleyvision.org/gathered/examples/feature_extraction.html to extract features using the pretrained imagenet model. My concern is that, irrespective of the number of images inside 'caffe/examples/images' folder, the code always ends with a text as follows.

%%%%%
E0717 17:28:57.687183 10851 extract_features.cpp:157] Extracted features of 500 query images.
E0717 17:28:57.687410 10851 extract_features.cpp:163] Successfully extracted the features!
%%%%%

Cruicial is the number of query images. Why is it 500 images always? Am I missing a trick here? The size of the features leveldb also remains the same (about 10.2 mb) irrespective of the number of images in the 'images' folder.

Plesae also tell me if there is any other code (be it in matlab, python etc.) that I should try.

Many thanks,
Abir

**Comment by rnsandeep** [comment]
Is this thread solved. if yes please tell me how to correctly specify these params.
