### ISSUE TITLE
Creating LevelDB in Python

### ISSUE THREAD

**Issue by Zackory** [BVLC/caffe#745]
I am currently creating several million artificial data images in python, all of which I would like stored into LevelDB to be fed through caffe. 

At the moment I'm saving all of the images directly to file, and then using 'create_leveldb.sh' to create the LevelDB directories. This creates a problem as I  am having to save a couple million images to the HDD.

What I am trying to do is have python directly save the artificial images into LevelDB, and do so without having to save the image to file. Currently, my code is trying to emulate what happens in 'ReadImageToDatum' from io.cpp. 

The LevelDB created from my code matches the size (number of leveldb files) of the LevelDB created from  convert_imageset.bin; however, when I train caffe on my leveldb directory, both Test#1 and Test#2 get worse over time.

What I am suspecting is that I have missed something when converting the image into a string format, but I may have missed something completely different.

    db = plyvel.DB('train_leveldb/', create_if_missing=True, error_if_exists=True, write_buffer_size=268435456)
    wb = db.write_batch()

    ...

    for file in imageSet:
        image = cv.LoadImageM(file, cv.CV_LOAD_IMAGE_COLOR)

        # Load image into datum object
        datum = caffe.proto.caffe_pb2.Datum()
        datum.height = image.rows
        datum.width = image.cols
        datum.channels = 3
        datum.label = label
        datum.data = image.tostring()

        wb.put('%08d_%s' % (count, file), datum.SerializeToString())

        count = count + 1
        if count % 1000 == 0:
            # Write batch of images to database
            wb.write()
            del wb
            wb = db.write_batch()
            print 'Processed %i images.' % count

    if count % 1000 != 0:
        # Write last batch of images
        wb.write()
        print 'Processed a total of %i images.' % count
    else:
        print 'Processed a total of %i images.' % count

**Comment by serge-m** [comment]
One interesting thing about using plyvel. When I create DB without using write batch, compute_image_mean tool produces some wrong result.
If I put all writes in one batch, it works ok.

I use the code, listed bellow. It just copies data from one DB to another.

```python
import caffe
wb = db.write_batch()  # without batch binary mean is wrong
datum =  caffe.io.caffe_pb2.Datum()
for k, v in db_in:
    wb.put(k,v)
wb.write()  # without batch binary mean is wrong
```

**Comment by andresromero** [comment]
Does someone knows how to do it using lmdb module in Python?

I am doing something similar to the instructions in: http://deepdish.io/

But I found it very slow (I don't know how to do it in batches rather than image by image).

Thanks!

**Comment by andresromero** [comment]
Solution to do it in batches:

``` python
# Load image into datum object
        datum = caffe.io.array_to_datum(image, label)
        str_id = '{0:08d}_{1}'.format(count, img_file)
        batch.append((datum, str_id))
        # txn.commit()
        if count % 1000 == 0:
            # Write batch of images to database
            with env.begin(write=True) as txn:
                for datum, str_id in batch:
                    txn.put(str_id.encode('ascii'), datum.SerializeToString())
            batch[:] = []
            print('Processed {0} images.'.format(count))
        count = count + 1
```
