### ISSUE TITLE
Is there any help regarding training custom data?

### ISSUE THREAD

**Issue by netheril96** [BVLC/caffe#747]
All the documentation currently is about training predefined data with predefined network. And all we are told to do is simply invoke some scripts without explanation of what happens under the hood. Is there any minimal example training custom data?

I successfully ran the `train_net.bin` on some other datasets with trial and error, but the result is horrible comparing to other people's work. I suppose I did something wrong, but without documentation or example, I really cannot figure the error out.

**Comment by shivangpatel** [comment]
RAW data dim :

1) `64 x 45 x 18432` in `.mat` format... ---> Class1

`1 x 18432` in `.mat` format... ---> labels

2) `64 x 45 x 18432` in `.mat` format... ---> Class2

`1 x 18432` in `.mat` format... ---> labels

3) `64 x 45 x 18432` in `.mat` format... ---> Class3

`1 x 18432` in `.mat` format... ---> labels 

**So, How to deal with this kind of data....??  How to prepare it for caffe as a input ?!**

**Comment by alexandrenilton** [comment]
@mafiosso my images are distributed in folders (each folder is a class). 
To create this train.txt sould I put the directory? eg: 
`Orthoptera/122321.jpg Orthoptera`

where the files it's in : Orthorptera directory and called 122321.jpg ? or just: 

`122321.jpg Orthoptera`

?

**Comment by shivangpatel** [comment]
@alexandrenilton : It's a depending on you. Only make sure path is correct for each images in train.txt(list of images).

**Comment by shivangpatel** [comment]
@alexandrenilton : it's does't matter. Only make sure path is correct for each images in train.txt.
