### ISSUE TITLE
Save snapshot only if performance improves?

### ISSUE THREAD

**Issue by HoldenCaulfieldRye** [BVLC/caffe#751]
Hi, I used to work with cuda-convnet, and it would only save a snapshot of the net when the validation error would reach a new minimum. At the moment with caffe, a snapshot gets saved every fixed interval. If the interval is too small, too much space gets taken up; if it is too large, I am afraid of missing the global validation error minimum (since the net will eventually overfit). 
Is there a way of getting the snapshot to save like cuda-convnet? Has someone implemented this in their fork?

**Comment by shelhamer** [comment]
While this could be convenient in the core, it seems more simple and general to handle this through pycaffe since you could score any metric and decide whether or not to snapshot by any rule.

**Comment by aku1506** [comment]
I think this functionality is very much needed in Caffe!! It would make things much easier...
I want such a functionality right now, could you please tell how it could be done.

**Comment by jinfagang** [comment]
I think it can be done inside solver loop, just compare current loss with whole losses, if it minium, then snapshot the bestmodel.
