### ISSUE TITLE
Matlab Compilation

### ISSUE THREAD

**Issue by davboub** [BVLC/caffe#758]
Hi,

I am trying to compile for matlab, I ran make matcaffe and I got the following error:

/usr/local/MATLAB/R2014a/bin/mex matlab/caffe/matcaffe.cpp build/lib/libcaffe.a \
            CXXFLAGS="\$CXXFLAGS -pthread -fPIC -DNDEBUG -O2 -I/usr/local/include/python2.7 -I/usr/local/lib/python2.7/dist-packages/numpy/core/include -I/usr/local/include -Ibuild/src -I./src -I./include -I/usr/local/cuda/include -Wall" \
            CXXLIBS="\$CXXLIBS -L/usr/local/lib -L/usr/local/lib -L/usr/lib -L/usr/local/cuda/lib64 -L/usr/local/cuda/lib -lcudart -lcublas -lcurand -lpthread -lglog -lprotobuf -lleveldb -lsnappy -lboost_system -lhdf5_hl -lhdf5 -lopencv_core -lopencv_highgui -lopencv_imgproc -lcblas -latlas" -o matlab/caffe/caffe.mexa64
Unknown MEX argument '-o'.
make: **\* [matlab/caffe/caffe.mexa64] Error 255

I don't understand what is the problem... Can someone help me with that?

Thanks

**Comment by abrichr** [comment]
To install liblmdb-dev on ubunut:

```
sudo apt-get install liblmdb-dev
```
