### ISSUE TITLE
Parameter tuning for validation

### ISSUE THREAD

**Issue by sayanghosh** [BVLC/caffe#761]
Hi, is there an utility bundled with Caffe which takes in as input a grid of parameters, and creates appropriate prototxt files and then trains/tests them on validation data. It is a bit tedious to manually change the train, test and deploy to find the best topology of the net. This would be similar to something like GridSearchCV in scikit-learn.

In case this has not been done yet, I might create a shell script/C++ file to handle this and then submit a relevant pull request.

**Comment by mjpekala** [comment]
Hello,
I came across this thread, and also the related issue #1546 opened by bhack, and was wondering: has any progress has been made along these lines?  Or is anticipated in the near future?  Is anyone on the Caffe team in regular contact with researchers from the hyper parameter research community?

We have conducted a few very preliminary experiments using the open source version of Spearmint (a hyperparameter selection package see https://github.com/JasperSnoek/spearmint) to generate Caffe configuration files.  We're trying to determine whether this is something worth pursuing more seriously and, if so, if/how it might be possible to coordinate with the Caffe community.

**Comment by PiranjaF** [comment]
@mjpekala Could you upload the code somewhere with just a few lines of instruction if you choose to pursue this? Even if nobody on the Caffe team has time to coordinate an official implementation, it would be great with some code on how to use with Spearmint with Caffe!

**Comment by andyljones** [comment]
@mjpekala I'd definitely be interested in that too.

**Comment by nharada1** [comment]
@mjpekala I'm interested in this too. I'd be happy to help you work on this project also.

**Comment by sayanghosh** [comment]
Same here

**Comment by longjon** [comment]
Since this does not seem like an issue with Caffe (but rather with external tools), let's move this discussion to the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) list (or document relevant related tools on the wiki). Thanks!

**Comment by bhack** [comment]
Try https://github.com/kuz/caffe-with-spearmint

**Comment by nharada1** [comment]
I've created a tool to automatically generate prototxt files based on a grid or random search. In addition the tool offers batch jobs and remote monitoring of your jobs:

https://groups.google.com/forum/#!topic/caffe-users/SBEd9Jfsegk

Please let me know if you have questions!
