### ISSUE TITLE
What does InsertSplit() / SplitLayer do?

### ISSUE THREAD

**Issue by lim0606** [BVLC/caffe#767]
Hi! I'm learning 'caffe' to develop new  some other functionality in it, including new solvers.  
However, I'm stuck at understanding the initialization of  Net class (network architecture), especially understanding InsertSplit's purpose.
I've tried to understand its function in Init() of Net class, but I still have no clues. Is there anyone who can give an advise on what it stands for? 
That will be a great help!. Thanks :)

**Comment by gmlyytt-YANG** [comment]
That’s right. It will create one additional layer and blobs as many as the top layers above the bottom layer. @lim0606
