### ISSUE TITLE
Resume training fails

### ISSUE THREAD

**Issue by dutran** [BVLC/caffe#786]
Hi all,

I was trying to resume training (from 25k) and got this message, anyone have ideas/hints please help me out?

Many thanks,
Du

I0725 01:06:17.916695 10039 solver.cpp:66] Restoring previous solver status from convnet_iter_25000.solverstate
I0725 01:06:18.531533 10039 solver.cpp:312] SGDSolver: restoring history
I0725 01:06:18.621152 10039 solver.cpp:106] Iteration 25000, Testing net
I0725 01:08:52.277266 10039 solver.cpp:147] Test score #0: 0.3901
I0725 01:08:52.277325 10039 solver.cpp:147] Test score #1: 3.1283
F0725 01:08:55.576004 10039 syncedmem.cpp:55] Check failed: error == cudaSuccess (4 vs. 0)  unspecified launch failure
**\* Check failure stack trace: ***
    @     0x7f1c4da37b4d  google::LogMessage::Fail()
    @     0x7f1c4da3bb67  google::LogMessage::SendToLog()
    @     0x7f1c4da399e9  google::LogMessage::Flush()
    @     0x7f1c4da39ced  google::LogMessageFatal::~LogMessageFatal()
    @           0x4709f3  caffe::SyncedMemory::to_gpu()
    @           0x470579  caffe::SyncedMemory::mutable_gpu_data()
    @           0x45aadd  caffe::Blob<>::mutable_gpu_data()
    @           0x4465dc  caffe::SGDSolver<>::ComputeUpdateValue()
    @           0x44776e  caffe::Solver<>::Solve()
    @           0x41af86  main
    @     0x7f1c4ad09cdd  __libc_start_main
    @           0x41abe9  (unknown)
Aborted

**Comment by barrykui** [comment]
My problem is out of the memory, thank you! @Yangqing

**Comment by mrgloom** [comment]
Same error `Check failed: error == cudaSuccess (4 vs. 0)  unspecified launch failure`

I'm using AlexNet model with 256x256 images, I have gtx 1070 with 8Gb of memory and 8Gb of memory on host,  during training memory was < 4Gb, so I don't think this is memory issue.

I'm using NVIDIA branch 0.15.
Also I'm using CUDA 8.0 and CUDNN 5.1.

**Comment by sayadyaghoobi** [comment]
i have the exact same issue, if anyone have idea please share. i think that this is about cuda problems not caffe :::
I0424 16:51:36.866385  4297 caffe.cpp:218] Using GPUs 0
I0424 16:51:36.868625  4297 caffe.cpp:223] GPU 0: �7�~�
F0424 16:51:36.868661  4297 common.cpp:152] Check failed: error == cudaSuccess (30 vs. 0)  unknown error
*** Check failure stack trace: ***
    @     0x7f76f21485cd  google::LogMessage::Fail()
    @     0x7f76f214a433  google::LogMessage::SendToLog()
    @     0x7f76f214815b  google::LogMessage::Flush()
    @     0x7f76f214ae1e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f76f2911012  caffe::Caffe::SetDevice()
    @           0x40b018  train()
    @           0x4072f0  main
    @     0x7f76f10b9830  __libc_start_main
    @           0x407b19  _start
    @              (nil)  (unknown)
Aborted (core dumped)

**Comment by mrgloom** [comment]
Once more crush on fresh master branch:

```
ERROR: Check failed: error == cudaSuccess (4 vs. 0) unspecified launch failure

Ignoring source layer train-data
Restarting data prefetching from start.
Test net output #0: accuracy = 0.139648
Test net output #1: loss = 3.7423 (* 1 = 3.7423 loss)
Iteration 3200 (0.794172 iter/s, 20.1468s/16 iters), loss = 2.61571
Train net output #0: loss = 2.61571 (* 1 = 2.61571 loss)
Iteration 3200, lr = 0.0001
Iteration 3216 (3.13362 iter/s, 5.10591s/16 iters), loss = 2.96576
Train net output #0: loss = 2.96576 (* 1 = 2.96576 loss)
Iteration 3216, lr = 0.0001
Iteration 3232 (2.92405 iter/s, 5.47187s/16 iters), loss = 3.12505
Train net output #0: loss = 3.12505 (* 1 = 3.12505 loss)
Iteration 3232, lr = 0.0001
Iteration 3248 (2.80573 iter/s, 5.70261s/16 iters), loss = 2.75908
Train net output #0: loss = 2.75908 (* 1 = 2.75908 loss)
Iteration 3248, lr = 0.0001
Iteration 3264 (2.87587 iter/s, 5.56354s/16 iters), loss = 3.07124
Train net output #0: loss = 3.07124 (* 1 = 3.07124 loss)
Iteration 3264, lr = 0.0001
Check failed: error == cudaSuccess (4 vs. 0)  unspecified launch failure
```
        
BTW: I have successfully runned AlexNet model with batchsize 256 and 128, but with batch size 64 it crtashed somewhere in the middle of of the training.

**Comment by dong-x16** [comment]
<img width="1155" alt="screen shot 2017-11-05 at 9 31 14 pm" src="https://user-images.githubusercontent.com/11272357/32432464-b2aa9a9e-c312-11e7-9af3-889cf12524e0.png">

same error during trianing,  I don't know what's wrong with it, anyone have the same error? Many thanks

**Comment by dong-x16** [comment]
<img width="1155" alt="screen shot 2017-11-05 at 9 31 14 pm" src="https://user-images.githubusercontent.com/11272357/32439237-d31a68fc-c328-11e7-900f-ef4ac88d0b5d.png">


during training,  I meet this error, I don't know what's wrong with it,  anyone have ideas? Many thanks

**Comment by sebastiangonsal** [comment]
@chocolate9624 what was your problem?

**Comment by shaibagon** [comment]
Please use the [caffe-users list][1] for usage, installation, or modeling questions, or other requests for help.
You may also post questions on [stackoverflow][3], make sure you tag them with `caffe` tag.  
There is also [caffe.help][4] documenting the different layers of caffe.
Do not post such requests to Issues. Doing so interferes with the development of Caffe.

Please read the [guidelines for contributing][2] before submitting this issue.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
 [3]: http://stackoverflow.com/questions/tagged/caffe
 [4]: http://caffe.help/manual/layers.html
