### ISSUE TITLE
any people tried to compile matlab wrapper in windows?

### ISSUE THREAD

**Issue by fujun-liu** [BVLC/caffe#815]
I tried mex under matlab environment and didn't succeed. Does anyone have success experience? Thanks

**Comment by shuangao** [comment]
Can I use this Mex file standalone? I tried to put it in the caffe matlab folder and run the matlab demo. It doesn't work. @nian-liu Do I have to include any other DLLs?

**Comment by nian-liu** [comment]
@shuangao Sorry that I haven't receive the notification that you had replied me. First you should assure that you have built niuzhiheng's caffe-windows project correctly. Then you should build the project in https://github.com/mjmarin/caffe/tree/winmex/build/MSVCmex. Next you should copy all the DLLs in caffe-windows/bin to  caffe-windows/matlab/caffe. Then it should work.

**Comment by shuangao** [comment]
OK. I didnt compile the code myself. I just copied all the DLLs in
standalone version(for MNIST tutorial) to matlab directory.  I will try
again. Thanks

On Fri, Jan 9, 2015 at 9:01 AM, nian-liu <notifications@github.com> wrote:

> @shuangao <https://github.com/shuangao> Sorry that I haven't receive the
> notification that you had replied me. First you should assure that you have
> built niuzhiheng's caffe-windows project correctly. Then you should build
> the project in https://github.com/mjmarin/caffe/tree/winmex/build/MSVCmex.
> Next you should copy all the DLLs in caffe-windows/bin to
> caffe-windows/matlab/caffe. Then it should work.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BVLC/caffe/issues/815#issuecomment-69337176>.
>



-- 
Cheers
Shuang

**Comment by sunilrao43** [comment]
@shuangao https://github.com/mjmarin/caffe/tree/winmex/build/MSVCmex 
i could not build the project file it didnt load properly .. can you provide me more elaborated info on it 
iam using matlab 2013a
cuda 6.5

**Comment by shuangao** [comment]
Sorry. I didn't successfully compile it yet. I turned to the python wrapper
in Linux and I think the python wrapper can do most things for me. I still
have no idea how to make it work in Windows. Good luck!

On Fri, Feb 13, 2015 at 1:46 AM, sunilrao43 <notifications@github.com>
wrote:

> @shuangao <https://github.com/shuangao>
> https://github.com/mjmarin/caffe/tree/winmex/build/MSVCmex
> i could not build the project file it didnt load properly .. can you
> provide me more elaborated info on it
> iam using matlab 2013a
> cuda 6.5
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BVLC/caffe/issues/815#issuecomment-74212247>.
>



-- 
Cheers
Shuang

**Comment by Addhi86** [comment]
Hello, I have downloaded the Caffe for windows from https://github.com/BVLC/caffe/tree/windows
after that I have tried the steps mentioned at https://ahmedibrahimvt.wordpress.com/2016/04/18/caffe-in-matlab-matcaffe-simple-tutorial/
but it's not working. It gives me an error

Undefined function or variable 'caffe_'.

Error in caffe.set_mode_gpu (line 5)
caffe_('set_mode_gpu');

Please help me to solve this

**Comment by G33kyKitty** [comment]
Hello, 

I am having this error.

![image](https://user-images.githubusercontent.com/32497628/35040077-c71de2ae-fb77-11e7-9f36-e249b57cb906.png)

Grateful if someone can help me.

Kind regards..
