### ISSUE TITLE
Matlab demo

### ISSUE THREAD

**Issue by davboub** [BVLC/caffe#827]
Hi,

I am trying to use the matlab demo 
(I already compiled matcaffe and I ran the two export commands:
          export LD_LIBRARY_PATH=/opt/intel/mkl/lib/intel64:/usr/local/cuda-5.5/lib64
          export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libstdc++.so.6)
, but I have got the following error:
Invalid MEX-file '/home/gipuser/caffe-workspace/caffe-new2/matlab/caffe/caffe.mexa64':
/usr/local/MATLAB/R2013a/bin/glnxa64/../../sys/os/glnxa64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by
/home/gipuser/caffe-workspace/caffe-new2/matlab/caffe/caffe.mexa64)

Is anyone knows what can be the problem?

Thanks

**Comment by Beanocean** [comment]
I met with the same problem, and I changed the version of g++ to 4.4 to compile Caffe with it. But I met with new problem as follows: ( Does anybody have a suggestion ? )

	Abort signal detected at Sun Feb  1 16:35:40 2015

	Configuration:
	  Crash Decoding     : Disabled
	  Current Visual     : None
	  Default Encoding   : UTF-8
	  GNU C Library      : 2.19 stable
	  MATLAB Architecture: glnxa64
	  MATLAB Root        : /usr/local/MATLAB/R2013a
	  MATLAB Version     : 8.1.0.604 (R2013a)
	  Operating System   : Linux 3.13.0-45-generic #74-Ubuntu SMP Tue Jan 13 19:36:28 UTC 2015 x86_64
	  Processor ID       : x86 Family 6 Model 58 Stepping 9, GenuineIntel
	  Virtual Machine    : Java 1.6.0_17-b04 with Sun Microsystems Inc. Java HotSpot(TM) 64-Bit Server VM mixed mode
	  Window System      : No active display
	
	Fault Count: 1
	
	
	Abnormal termination:
	Abort signal
	
	Register State (from fault):
	  RAX = 0000000000000000  RBX = 00007f69bc750e60
	  RCX = ffffffffffffffff  RDX = 0000000000000006
	  RSP = 00007f6a27d14448  RBP = 00007f6a27d14580
	  RSI = 0000000000002d28  RDI = 0000000000002cf2
	
	   R8 = 000000000000ff08   R9 = 0000000000000000
	  R10 = 0000000000000008  R11 = 0000000000000202
	  R12 = 0000000000000080  R13 = 00007f6a27d15098
	  R14 = 0000000000000002  R15 = 00007f6a27d15090
	
	  RIP = 00007f6a393efcc9  EFL = 0000000000000202
	
	   CS = 0033   FS = 0000   GS = 0000
	
	Stack Trace (from fault):
	[  0] 0x00007f6a393efcc9                    /lib/x86_64-linux-gnu/libc.so.6+00224457 gsignal+00000057
	[  1] 0x00007f6a393f30d8                    /lib/x86_64-linux-gnu/libc.so.6+00237784 abort+00000328
	[  2] 0x00007f69bc52b5f3                        /usr/local/lib/libglog.so.0+00079347 _ZN6google22InstallFailureFunctionEPFvvE+00000000
	[  3] 0x00007f69bc52b61c                        /usr/local/lib/libglog.so.0+00079388 _ZN6google10LogMessage10SendToSinkEv+00000000
	[  4] 0x00007f69bc52b568                        /usr/local/lib/libglog.so.0+00079208 _ZN6google10LogMessage9SendToLogEv+00001224
	[  5] 0x00007f69bc52af6a                        /usr/local/lib/libglog.so.0+00077674 _ZN6google10LogMessage5FlushEv+00000414
	[  6] 0x00007f69bc52df01                        /usr/local/lib/libglog.so.0+00089857 _ZN6google15LogMessageFatalD1Ev+00000025
	[  7] 0x00007f69be4e0a26         /usr/local/caffe/matlab/caffe/caffe.mexa64+00506406
	[  8] 0x00007f69be4892e6         /usr/local/caffe/matlab/caffe/caffe.mexa64+00148198
	[  9] 0x00007f69be4897d3         /usr/local/caffe/matlab/caffe/caffe.mexa64+00149459 mexFunction+00000203
	[ 10] 0x00007f6a31a52f8a     /usr/local/MATLAB/R2013a/bin/glnxa64/libmex.so+00110474 mexRunMexFile+00000090
	[ 11] 0x00007f6a31a4f0f9     /usr/local/MATLAB/R2013a/bin/glnxa64/libmex.so+00094457
	[ 12] 0x00007f6a31a4ff1c     /usr/local/MATLAB/R2013a/bin/glnxa64/libmex.so+00098076
	[ 13] 0x00007f6a3b3816b2 /usr/local/MATLAB/R2013a/bin/glnxa64/libmwm_dispatcher.so+00562866 _ZN8Mfh_file11dispatch_fhEiPP11mxArray_tagiS2_+00000594
	[ 14] 0x00007f6a3ae0bbf6 /usr/local/MATLAB/R2013a/bin/glnxa64/libmwm_interpreter.so+04262902
	[ 15] 0x00007f6a3ae0c37a /usr/local/MATLAB/R2013a/bin/glnxa64/libmwm_interpreter.so+04264826
	[ 16] 0x00007f6a3ae0ceea /usr/local/MATLAB/R2013a/bin/glnxa64/libmwm_interpreter.so+04267754
	[ 17] 0x00007f6a3ac6fbbd /usr/local/MATLAB/R2013a/bin/glnxa64/libmwm_interpreter.so+02575293
	[ 18] 0x00007f6a3ac9b412 /usr/local/MATLAB/R2013a/bin/glnxa64/libmwm_interpreter.so+02753554
	[ 19] 0x00007f6a3ac9b53f /usr/local/MATLAB/R2013a/bin/glnxa64/libmwm_interpreter.so+02753855
	[ 20] 0x00007f6a3adb8500 /usr/local/MATLAB/R2013a/bin/glnxa64/libmwm_interpreter.so+03921152
	[ 21] 0x00007f6a3abd1868 /usr/local/MATLAB/R2013a/bin/glnxa64/libmwm_interpreter.so+01927272
	[ 22] 0x00007f6a3ac3ce50 /usr/local/MATLAB/R2013a/bin/glnxa64/libmwm_interpreter.so+02367056
	[ 23] 0x00007f6a3b3816b2 /usr/local/MATLAB/R2013a/bin/glnxa64/libmwm_dispatcher.so+00562866 _ZN8Mfh_file11dispatch_fhEiPP11mxArray_tagiS2_+00000594
	[ 24] 0x00007f6a3ac1f256 /usr/local/MATLAB/R2013a/bin/glnxa64/libmwm_interpreter.so+02245206
	[ 25] 0x00007f6a3abab09d /usr/local/MATLAB/R2013a/bin/glnxa64/libmwm_interpreter.so+01769629
	[ 26] 0x00007f6a3abd3b0e /usr/local/MATLAB/R2013a/bin/glnxa64/libmwm_interpreter.so+01936142
	[ 27] 0x00007f6a3abd0993 /usr/local/MATLAB/R2013a/bin/glnxa64/libmwm_interpreter.so+01923475
	[ 28] 0x00007f6a3abd1797 /usr/local/MATLAB/R2013a/bin/glnxa64/libmwm_interpreter.so+01927063
	[ 29] 0x00007f6a3ac3ce50 /usr/local/MATLAB/R2013a/bin/glnxa64/libmwm_interpreter.so+02367056
	[ 30] 0x00007f6a3b3816b2 /usr/local/MATLAB/R2013a/bin/glnxa64/libmwm_dispatcher.so+00562866 _ZN8Mfh_file11dispatch_fhEiPP11mxArray_tagiS2_+00000594
	[ 31] 0x00007f6a3ac0bdcb /usr/local/MATLAB/R2013a/bin/glnxa64/libmwm_interpreter.so+02166219
	[ 32] 0x00007f6a3abc97cc /usr/local/MATLAB/R2013a/bin/glnxa64/libmwm_interpreter.so+01894348
	[ 33] 0x00007f6a3abc5e1d /usr/local/MATLAB/R2013a/bin/glnxa64/libmwm_interpreter.so+01879581
	[ 34] 0x00007f6a3abc6255 /usr/local/MATLAB/R2013a/bin/glnxa64/libmwm_interpreter.so+01880661
	[ 35] 0x00007f6a31c7bfae /usr/local/MATLAB/R2013a/bin/glnxa64/libmwbridge.so+00139182
	[ 36] 0x00007f6a31c7c111 /usr/local/MATLAB/R2013a/bin/glnxa64/libmwbridge.so+00139537
	[ 37] 0x00007f6a31c7cce5 /usr/local/MATLAB/R2013a/bin/glnxa64/libmwbridge.so+00142565 _Z8mnParserv+00000725
	[ 38] 0x00007f6a3b6193d2   /usr/local/MATLAB/R2013a/bin/glnxa64/libmwmcr.so+00447442 _ZN11mcrInstance30mnParser_on_interpreter_threadEv+00000034
	[ 39] 0x00007f6a3b5f89ac   /usr/local/MATLAB/R2013a/bin/glnxa64/libmwmcr.so+00313772
	[ 40] 0x00007f6a3b5f8b88   /usr/local/MATLAB/R2013a/bin/glnxa64/libmwmcr.so+00314248
	[ 41] 0x00007f6a3bc3dcab /usr/local/MATLAB/R2013a/bin/glnxa64/libmwservices.so+01166507 _ZN10eventqueue18UserEventQueueImpl5flushEv+00000395
	[ 42] 0x00007f6a2f19d5fd   /usr/local/MATLAB/R2013a/bin/glnxa64/libmwuix.so+00534013
	[ 43] 0x00007f6a3bce3a9d /usr/local/MATLAB/R2013a/bin/glnxa64/libmwservices.so+01845917
	[ 44] 0x00007f6a3bce450f /usr/local/MATLAB/R2013a/bin/glnxa64/libmwservices.so+01848591 _Z25svWS_ProcessPendingEventsiib+00001615
	[ 45] 0x00007f6a3b5f95ef   /usr/local/MATLAB/R2013a/bin/glnxa64/libmwmcr.so+00316911
	[ 46] 0x00007f6a3b5f9f5c   /usr/local/MATLAB/R2013a/bin/glnxa64/libmwmcr.so+00319324
	[ 47] 0x00007f6a3b5f3592   /usr/local/MATLAB/R2013a/bin/glnxa64/libmwmcr.so+00292242
	[ 48] 0x00007f6a39787182              /lib/x86_64-linux-gnu/libpthread.so.0+00033154
	[ 49] 0x00007f6a394b400d                    /lib/x86_64-linux-gnu/libc.so.6+01028109 clone+00000109
	
	
	This error was detected while a MEX-file was running. If the MEX-file
	is not an official MathWorks function, please examine its source code
	for errors. Please consult the External Interfaces Guide for information
	on debugging MEX-files.
	
	If this problem is reproducible, please submit a Service Request via:
	    http://www.mathworks.com/support/contact_us/
	
	A technical support engineer might contact you with further information.
	
	Thank you for your help.

**Comment by yifita** [comment]
@Beanocean  I had the same crash report from matlab. 
After an hour of frustrated search, I noticed the error message was printed right on my terminal:
syncedmem.cpp:58] Check failed: error == cudaSuccess (2 vs. 0)  out of memory

So you will have to reduce your batch size.

**Comment by iBM88** [comment]
for me two tricks helped solving the problem:
1. installing the 64bit version of libstdc++6
`$ sudo apt-get install lib64stdc++6`
2. running matlab as:
`$ LD_PRELOAD="/usr/lib64/libstdc++.so.6" sh matlab`

**Comment by mjohn123** [comment]
Thank iBM88. For your second command, why I cannot set the path in ~/.bashrc file. I did by following steps

`sudo gedit ~/.bashrc`

I added the line in the file
`export LD_PRELOAD=/usr/lib64/libstdc++.so.6`

Then I ran 

`source ~/.bashrc`

However, if I run sh matlab, the error is still maintain. While If I run the second command, it will be successful.

**Comment by wujiyoung** [comment]
@iBM88 Should I re-compilie my caffe after installing libstdc++6?
