### ISSUE TITLE
How to convert the ".binaryproto" to ".mat"

### ISSUE THREAD

**Issue by shiorioxy** [BVLC/caffe#829]
When I want to do something by matlab, I need the .mat files, e.g. mean.binaryproto.
But I don't know to do it? How to convert the .binarproto to .mat ?
Thank you very much!

**Comment by BingZhangHu** [comment]
I think a better way to convert mean.binaryproto to .mat file is using read_mean() function, which can be found in caffe/matlab/+caffe/private/io.m

**Comment by priyapaul** [comment]
@BingZhangHu  Thank you. But could you please provide a code snippet?

**Comment by wangjy2020** [comment]
`if (strfind(conf.image_means,'binaryproto'))
            s=caffe.io.read_mean(conf.image_means);
            s_mean(:,:,1)=mean2(s(:,:,1));
            s_mean(:,:,2)=mean2(s(:,:,2));
            s_mean(:,:,3)=mean2(s(:,:,3));
            conf.image_means = s_mean;`
