### ISSUE TITLE
Layertype: Locally connected is not available?

### ISSUE THREAD

**Issue by shreyassaxena** [BVLC/caffe#837]
Some of papers using CNN [1] have a small trick. Instead of sharing the weights of a filter over an entire image, the weights depend on the local position.
These are called as locally connected CNN.

Is it possible that this functionality could be added?

Update: I checked the previous issues, and found that this is an open issue.

[1] DeepFace: Closing the Gap to Human-Level Performance in Face Verification

**Comment by kevin-li** [comment]
Could anyone help me on how to use the im2col layer? I'm using the Python interface and would normally add a layer into the prototxt file, but this layer is not described in caffe.proto

**Comment by knsong** [comment]
I implement a local convolution layer [here](https://github.com/knsong/caffe-mt) and will appreciate any suggestions.
