### ISSUE TITLE
Creating leveldB Issue

### ISSUE THREAD

**Issue by ghost** [BVLC/caffe#838]
Hello! I am a new user of Caffe.
I made my own dataset, and I want to convert my dataset into leveldB format.
By referencing Imagenet's create_imagenet.sh file, I created create_navigation.sh file. 
The code is:
TOOLS=/home/dkkim930122/caffe-master/build/tools
DATA=/home/dkkim930122/caffe-master/data/navigation

echo "Creating leveldb..."

GLOG_logtostderr=1 $TOOLS/convert_imageset.bin \
    /home/dkkim930122/caffe-master/data/navigation/ \
    $DATA/train.txt \
    navigation_train_leveldb 0

echo "Done."

As I run the file from terminal, it says: 
dkkim930122@DKK:~/caffe-master/examples/navigation$ ./create_navigation.sh
Creating leveldb...
I0801 17:52:19.638675  9643 convert_imageset.cpp:54] A total of 10 images.
I0801 17:52:19.638782  9643 convert_imageset.cpp:61] Opening leveldb navigation_train_leveldb
E0801 17:52:19.764928  9643 io.cpp:84] Could not open or find file /home/dkkim930122/caffe-master/data/navigation/airport_inside/airport_inside_0001.JPEG
E0801 17:52:19.764960  9643 io.cpp:84] Could not open or find file /home/dkkim930122/caffe-master/data/navigation/airport_inside/airport_inside_0002.JPEG
E0801 17:52:19.764974  9643 io.cpp:84] Could not open or find file /home/dkkim930122/caffe-master/data/navigation/airport_inside/airport_inside_0003.JPEG
E0801 17:52:19.764987  9643 io.cpp:84] Could not open or find file /home/dkkim930122/caffe-master/data/navigation/airport_inside/airport_inside_0004.JPEG
E0801 17:52:19.765000  9643 io.cpp:84] Could not open or find file /home/dkkim930122/caffe-master/data/navigation/airport_inside/airport_inside_0005.JPEG
E0801 17:52:19.765013  9643 io.cpp:84] Could not open or find file /home/dkkim930122/caffe-master/data/navigation/airport_inside/airport_inside_0007.JPEG
E0801 17:52:19.765025  9643 io.cpp:84] Could not open or find file /home/dkkim930122/caffe-master/data/navigation/airport_inside/airport_inside_0009.JPEG
E0801 17:52:19.765038  9643 io.cpp:84] Could not open or find file /home/dkkim930122/caffe-master/data/navigation/airport_inside/airport_inside_0010.JPEG
E0801 17:52:19.765053  9643 io.cpp:84] Could not open or find file /home/dkkim930122/caffe-master/data/navigation/airport_inside/airport_inside_0011.JPEG
E0801 17:52:19.765065  9643 io.cpp:84] Could not open or find file /home/dkkim930122/caffe-master/data/navigation/airport_inside/airport_inside_0013.JPEG
Done.

Could anyone help me how I could solve "Could not open or find file ..." error?
Thank you!

**Comment by daniaokuye** [comment]
I've met this problem. but it is solved now!!
the covert tools located in caffe_root/tools/convert_imageset.cpp, so does the binary file located in build.
the code read lable.txt in such a function as below:
```
while (std::getline(infile, line)) {
    pos = line.find_last_of(' '); // that's the mode where and what to split a line. only a **space** is accepted!
    label = atoi(line.substr(pos + 1).c_str()); //the second one to last convert to a intergter
    lines.push_back(std::make_pair(line.substr(0, pos), label)); // the total path as well as string
  }
```
we should make sure the string in every line of lable.txt should only have one and only sapce
