### ISSUE TITLE
Encountering the error of "Failed to open leveldb imagenet_val_leveldb" while training with imageNet

### ISSUE THREAD

**Issue by shokroll** [BVLC/caffe#850]
Hello,
I have fallowed the instruction of training caffe with imageNet according to http://caffe.berkeleyvision.org/gathered/examples/imagenet.html

everything was ok until I run  ./create_imagenet.sh to creat  imagenet_train_leveldb and imagenet_val_leveldb. I also modified the path of  train and val dirs in create_imagenet.sh file.
when I run  ./create_imagenet.sh, the imagenet_train_leveldb is created but for imagenet_val_leveldb I got the follwoing error:

Opening leveldb imagenet_val_leveldb
F0804 13:39:06.867671 24479 convert_imageset.cpp:64] Check failed: status.ok() Failed to open leveldb imagenet_val_leveldb
**\* Check failure stack trace: ***
    @     0x7ff67ea8acbd  google::LogMessage::Fail()
    @     0x7ff67ea8ed77  google::LogMessage::SendToLog()
    @     0x7ff67ea8cb99  google::LogMessage::Flush()
    @     0x7ff67ea8ce9d  google::LogMessageFatal::~LogMessageFatal()
    @           0x40ccf0  main
    @     0x7ff67b8abd1d  __libc_start_main
    @           0x40bc49  (unknown)
./create_imagenet.sh: line 18: 24479 Aborted                 GLOG_logtostderr=1 $TOOLS/convert_imageset.bin /worktmp2/ILSVR2014/CLS-LOC/ILSVRC2012_img_val/ $DATA/val.txt imagenet_val_leveldb 1
Done.

**Comment by honorpeter** [comment]
I have the same problem, can you help me? thank you very much，I  have enough space on that directory，but caffe Error running "make runtest" (Failed to open leveldb)

**Comment by yegane-AI** [comment]
> @shelhamer oh yeah, the problem was that I did not have enough space on that directory. thanks!

How did you know the space required for that job? I encounter the same problem and I don't know how much should I free?
