### ISSUE TITLE
Offset strided pooling

### ISSUE THREAD

**Issue by hosang** [BVLC/caffe#853]
I want to use a densely connected layer as a convolutional filter. The catch is that the layer has been trained on a max pooled layer with (let's say) stride and kernel size 3 and I want to get the convolution result with stride dense. The idea of how to do this is visualized in 1D in figure 3 in the Overfeat paper [1]. You put 3 max pooling layer on the output of the previous layer, each one offset by one more element, then you can convolve the filter with each of the three pooled maps and interleave the output of the convolution.

The simplest solution in caffe I can think of is to turn the pad field in PoolingParameter message from unsigned into signed and allow negative pooling. Or maybe if you want to keep the protos compatible add a "cropping offset" field which is implemented by substracting it from pad internally. My hope is that a negative pad value would do the job of skipping some rows/columns in the input blob and most details are just working out. The interleaving probably would need an additional layer?

What do you think about this feature and this solution? Does this make any sense to you?

[1] http://arxiv.org/pdf/1312.6229v4

**Comment by shelhamer** [comment]
This has been handled for awhile now by any of input jittering, cropping, and dilation (though note that dilated pooling is still missing in master).
