### ISSUE TITLE
How to compute the memory usage

### ISSUE THREAD

**Issue by xizhonghua** [BVLC/caffe#854]
Hi, I slightly modified MNIST example to work with my own data, I have a question about memory usage.

In the log file, it says that
train: Memory required for Data 130326192
test: Memory required for Data 173779144

Which in total is 290MiB, however, when I use nvidia-smi to monitor the GPU memory usage, it shows:
../../build/tools/train_net.bin                     1664MiB

I just wonder how to compute the memory usage thus I can set a proper bach_size, otherwise I need to try and see whether there is a crash or not.

Thanks!

**Comment by pranjaldaga** [comment]
@xizhonghua Can you let me know in which log file did you get "Memory required for Data"? 
I'm using the MNIST example as of now.

Thanks!
