### ISSUE TITLE
how to modify pretrained model?

### ISSUE THREAD

**Issue by sser-huangdong** [BVLC/caffe#864]
I am going to modify the layer 'fc8' of ImageNet from 1000 output to 100. And set the param to randoms. Is there any API or sample code for that?

**Comment by etienne87** [comment]
hello! can we expect that setting all convolutional layers to zero for fine-tuning will make the training much faster? (not only in terms of number of epochs for convergence)

**Comment by ajdroid** [comment]
Yes, because you won't backprop through the previous layers
