### ISSUE TITLE
Invalid Device Function

### ISSUE THREAD

**Issue by kelvinxu** [BVLC/caffe#869]
I am getting a similar problem #138, running make runtest.

---

[----------] 9 tests from ConvolutionLayerTest/0, where TypeParam = float
[ RUN ] ConvolutionLayerTest/0.TestGPUSimpleConvolutionGroup
F0806 12:02:26.552108 4388 im2col.cu:54] Check failed: error == cudaSuccess (8 vs. 0) invalid device function 
**\* Check failure stack trace: ***
@ 0x2b05a7478b7d google::LogMessage::Fail()
@ 0x2b05a747ac7f google::LogMessage::SendToLog()
@ 0x2b05a747876c google::LogMessage::Flush()
@ 0x2b05a747b51d google::LogMessageFatal::~LogMessageFatal()
@ 0x634fe2 caffe::im2col_gpu<>()
@ 0x62074d caffe::ConvolutionLayer<>::Forward_gpu()
@ 0x4790ef caffe::ConvolutionLayerTest_TestGPUSimpleConvolutionGroup_Test<>::TestBody()
@ 0x58b0ed testing::internal::HandleExceptionsInMethodIfSupported<>()
@ 0x582f11 testing::Test::Run()
@ 0x582ff6 testing::TestInfo::Run()
@ 0x583137 testing::TestCase::Run()
@ 0x58348e testing::internal::UnitTestImpl::RunAllTests()
@ 0x58ac6d testing::internal::HandleExceptionsInMethodIfSupported<>()
@ 0x58256e testing::UnitTest::Run()
@ 0x4434dd main
@ 0x2b05a97f076d (unknown)
@ 0x4481ad (unknown)
make: **\* [runtest] Aborted

---

Was anyone else able to resolve this issue?

**Comment by vamsus** [comment]
I am facing a similar error. @shelmar using latest CUDA version (8.0) with enabled GPU Nvidia Geforce 820M.  How to change the CUDA arch.
 
 [ RUN      ] TanHLayerTest/2.TestTanH
F0310 07:19:41.605973  3025 tanh_layer.cu:26] Check failed: error == cudaSuccess (8 vs. 0)  invalid device function
*** Check failure stack trace: ***
    @     0x7f5cb33b75cd  google::LogMessage::Fail()
    @     0x7f5cb33b9433  google::LogMessage::SendToLog()
    @     0x7f5cb33b715b  google::LogMessage::Flush()
    @     0x7f5cb33b9e1e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f5cb162f2aa  caffe::TanHLayer<>::Forward_gpu()
    @           0x481379  caffe::Layer<>::Forward()
    @           0x7b1320  caffe::TanHLayerTest<>::TestForward()
    @           0x8e1cb3  testing::internal::HandleExceptionsInMethodIfSupported<>()
    @           0x8db2ca  testing::Test::Run()
    @           0x8db418  testing::TestInfo::Run()
    @           0x8db4f5  testing::TestCase::Run()
    @           0x8dc7cf  testing::internal::UnitTestImpl::RunAllTests()
    @           0x8dcaf3  testing::UnitTest::Run()
    @           0x46693d  main
    @     0x7f5cb0d3b830  __libc_start_main
    @           0x46dfd9  _start
    @              (nil)  (unknown)
Makefile:532: recipe for target 'runtest' failed
make: *** [runtest] Aborted (core dumped)
