### ISSUE TITLE
For training new dataset (Caltech101) using imagenet pretrained model, which mean file should i use?

### ISSUE THREAD

**Issue by ZhengRui** [BVLC/caffe#870]
In the .prototxt file for the new dataset, when specifying mean_file, should i use imagenet_mean.binaryproto or should i calculate the meanfile corresponding to the new dataset by myself (like after resizing images, then use convert_imageset.bin command to create leveldb folder, then use compute_image_mean.bin command to calculate meanfile) ? I prefer to use the original input image of new dataset by specifying IMAGE_DATA layer in .prototxt file, but i don't know if this will be a good idea when training new dataset, i think if i don't want fine tuning, then extracting the features of new dataset only need one forward pass, so it's ok to specifying IMAGE_DATA layer, but if i have to calculate new meanfile, then this IMAGE_DATA layer can be replaced with data layer (which should be faster) as i already get leveldb folder, so which meanfile should i use?

**Comment by weilunzhong** [comment]
Hi, can I ask how do you prepare the data, from jpg file to mdb file, there seems to be no documentation for this online when i try to create my own training dataset
