### ISSUE TITLE
Multivariate regression

### ISSUE THREAD

**Issue by caffecuda** [BVLC/caffe#881]
Hello,
Is it possible to do multivariate regression with Caffe i.e. the labels are in R^d? thanks.

**Comment by wguo68** [comment]
Suppose I use a list text file for my dataset like this with one line per traing sample: 
            "image_file_name regression_vector  classified_id  regression_vector2"

for example:

             "path/to/image.jpg 0.54   2.34   4.56  4  5.60  7.45"

My question is : how to feed the dataset to caffe ( or convert to caffe accepted  format such as LMDB)? 

Thanks,

**Comment by anguyen8** [comment]
@wguo68 : Did you figure out if this is the right format? I'd greatly appreciate if you could share a little on how you fed this to Caffe?

**Comment by dsmic** [comment]
Hmm, sorry, you probably did not mean me? dmic seems to be somebody else?!

I use dsmic? Or I do not remember what it was about:)

Detlef

**Comment by anguyen8** [comment]
@dsmic : Ah no, I meant @wguo68 . Thanks for asking. :)
