### ISSUE TITLE
issue in glog/logging.h

### ISSUE THREAD

**Issue by ankitsinghalIITD** [BVLC/caffe#885]
Hi,
I am running ubuntu 14.04
I have installed all prerequisites for caffe. 'make all' is giving error 
./include/caffe/common.hpp:11:26: fatal error: glog/logging.h: No such file or directory
 #include <glog/logging.h>

the complete output of make all is
ankit@ankit-lab:~/deep_learning/caffe-master$ make all 
protoc --proto_path=src --cpp_out=build/src src/caffe/proto/caffe_pretty_print.proto

protoc --proto_path=src --cpp_out=build/src src/caffe/proto/caffe.proto

/usr/bin/g++ build/src/caffe/proto/caffe_pretty_print.pb.cc -pthread -fPIC -DNDEBUG -O2 -I/usr/local/include/python2.7 -I/usr/local/lib/python2.7/dist-packages/numpy/core/include -I/usr/local/include -Ibuild/src -I./src -I./include -I/usr/local/cuda/include -c -o build/src/caffe/proto/caffe_pretty_print.pb.o

/usr/bin/g++ build/src/caffe/proto/caffe.pb.cc -pthread -fPIC -DNDEBUG -O2 -I/usr/local/include/python2.7 -I/usr/local/lib/python2.7/dist-packages/numpy/core/include -I/usr/local/include -Ibuild/src -I./src -I./include -I/usr/local/cuda/include -c -o build/src/caffe/proto/caffe.pb.o

/usr/bin/g++ src/caffe/net.cpp -pthread -fPIC -DNDEBUG -O2 -I/usr/local/include/python2.7 -I/usr/local/lib/python2.7/dist-packages/numpy/core/include -I/usr/local/include -Ibuild/src -I./src -I./include -I/usr/local/cuda/include -c -o build/src/caffe/net.o
In file included from src/caffe/net.cpp:8:0:
./include/caffe/common.hpp:11:26: fatal error: glog/logging.h: No such file or directory
 #include <glog/logging.h>
                          ^
compilation terminated.
make: **\* [build/src/caffe/net.o] Error 1

please help

**Comment by scutzhe** [comment]
I have the same problem
./include/caffe/common.hpp:6:26: fatal error: glog/logging.h: No such file or directory
Please tell me how to install this package,Thank you
