### ISSUE TITLE
training is getting killed

### ISSUE THREAD

**Issue by vdudhmal** [BVLC/caffe#886]
Hi there,

I am training Caffe for 6 object classes following the general approach on the ImageNet Training Recipe Page. I have 100 images per class. Batch size is 100 and 6 test iterations. However, the training gets killed in the first iteration:
I0808 13:37:18.157456  2527 net.cpp:174] Network initialization done.
I0808 13:37:18.157467  2527 net.cpp:175] Memory required for Data 209716808
I0808 13:37:18.157564  2527 solver.cpp:49] Solver scaffolding done.
I0808 13:37:18.157584  2527 solver.cpp:61] Solving CaffeNet
I0808 13:37:18.157608  2527 solver.cpp:106] Iteration 0, Testing net
I0808 13:46:45.056787  2527 solver.cpp:142] Test score #0: 0.17
I0808 13:46:45.472862  2527 solver.cpp:142] Test score #1: 2.00962
Killed
Done.

Any help regarding training Caffe and debugging is greatly appreciated!

**Comment by Luonic** [comment]
@wangpichao probably you ran out of ram or gpu memory. Try to reduce batch size

**Comment by lwzeng** [comment]
If the user or sysadmin did not kill the program the kernel may have. The kernel would only kill a process under exceptional circumstances such as extreme resource starvation (think mem+swap exhaustion).you will find the answer you want  at https://stackoverflow.com/questions/726690/what-killed-my-process-and-why
