### ISSUE TITLE
gflags now seems replacing "gflags" namespace to "google" in gflags/gflags.h

### ISSUE THREAD

**Issue by musicx** [BVLC/caffe#890]
When compiling on MAC OSX 10.9.4, I encountered an error as follows :

/usr/bin/clang++ tools/caffe.cpp -stdlib=libstdc++ -pthread -fPIC -DNDEBUG -O2 -I/usr/include/python2.7 -I/usr/lib/python2.7/dist-packages/numpy/core/include -I/usr/local/include -I.build_release/src -I./src -I./include -I/usr/local/cuda/include -I/System/Library/Frameworks/vecLib.framework/Versions/Current/Headers/ -Wall -Wno-sign-compare -Wno-unneeded-internal-declaration -c -o .build_release/tools/caffe.o 2> .build_release/tools/caffe.o.warnings.txt \
        || (cat .build_release/tools/caffe.o.warnings.txt; exit 1)
tools/caffe.cpp:219:3: error: use of undeclared identifier 'gflags'
  gflags::SetUsageMessage("command line brew\n"
  ^
tools/caffe.cpp:231:5: error: use of undeclared identifier 'gflags'
    gflags::ShowUsageWithFlagsRestrict(argv[0], "tools/caffe");
    ^
2 errors generated.
make: **\* [.build_release/tools/caffe.o] Error 1

After little investigation, it seems gflags/gflags.h is using google namespace instead of gflags namespace

**Comment by luke831215** [comment]
Thank god it helps!
