### ISSUE TITLE
make runtest CUDA fails after Ubuntu upgrade

### ISSUE THREAD

**Issue by rmanor** [BVLC/caffe#893]
Hi,

I upgraded my Ubuntu to 14.04 and now 'make runtest' fails with:
E0522 16:04:44.114862 27133 common.cpp:31] Cannot create Cublas handle. Cublas won't be available.
E0522 16:04:44.427568 27133 common.cpp:38] Cannot create Curand generator. Curand won't be available.

I reinstalled the CUDA Toolkit , and the driver settings says it is installed.
What else can I check?
Thanks.

**Comment by gjy3035** [comment]
@rmanor I also faced the same problem. The fails 

[----------] 1 test from HDF5DataLayerTest/3, where TypeParam = caffe::DoubleGPU
[ RUN      ] HDF5DataLayerTest/3.TestRead
HDF5-DIAG: Error detected in HDF5 (1.8.14) thread 0:
  #000: /opt/hdf5-1.8.14/src/H5Dio.c line 173 in H5Dread(): can't read data
    major: Dataset
    minor: Read failed
  #001: /opt/hdf5-1.8.14/src/H5Dio.c line 550 in H5D__read(): can't read data
    major: Dataset
    minor: Read failed
  #002: /opt/hdf5-1.8.14/src/H5Dchunk.c line 1872 in H5D__chunk_read(): unable to read raw data chunk
    major: Low-level I/O
    minor: Read failed
  #003: /opt/hdf5-1.8.14/src/H5Dchunk.c line 2902 in H5D__chunk_lock(): data pipeline read failed
    major: Data filters
    minor: Filter operation failed
  #004: /opt/hdf5-1.8.14/src/H5Z.c line 1357 in H5Z_pipeline(): required filter 'deflate' is not registered
    major: Data filters
    minor: Read failed
  #005: /opt/hdf5-1.8.14/src/H5PL.c line 298 in H5PL_load(): search in paths failed
    major: Plugin for dynamically loaded library
    minor: Can't get value
  #006: /opt/hdf5-1.8.14/src/H5PL.c line 402 in H5PL__find(): can't open directory
    major: Plugin for dynamically loaded library
    minor: Can't open directory or file
F0324 20:42:57.229174 27543 io.cpp:277] Check failed: status >= 0 (-1 vs. 0) Failed to read double dataset data
*** Check failure stack trace: ***
    @     0x2b373dd86b5d  google::LogMessage::Fail()
    @     0x2b373dd8ab77  google::LogMessage::SendToLog()
    @     0x2b373dd889f9  google::LogMessage::Flush()
    @     0x2b373dd88cfd  google::LogMessageFatal::~LogMessageFatal()
    @     0x2b3741fe1f82  caffe::hdf5_load_nd_dataset<>()
    @     0x2b374209dc33  caffe::HDF5DataLayer<>::LoadHDF5FileData()
    @     0x2b37420ca04b  caffe::HDF5DataLayer<>::Forward_gpu()
    @           0x4d9f72  caffe::Layer<>::Forward()
    @           0x63679d  caffe::HDF5DataLayerTest_TestRead_Test<>::TestBody()
    @           0x7e5fea  testing::internal::HandleExceptionsInMethodIfSupported<>()
    @           0x7db879  testing::Test::Run()
    @           0x7db957  testing::TestInfo::Run()
    @           0x7dba95  testing::TestCase::Run()
    @           0x7dbe05  testing::internal::UnitTestImpl::RunAllTests()
    @           0x7e5b6a  testing::internal::HandleExceptionsInMethodIfSupported<>()
    @           0x7db0e1  testing::UnitTest::Run()
    @           0x4d4a92  main
    @     0x2b3742fa3cdd  __libc_start_main
    @           0x4d4869  (unknown)
make: *** [runtest] Aborted (core dumped)

And how do you solve it?
Thanks!
