### ISSUE TITLE
State of the art Pascal VOC Multilabel

### ISSUE THREAD

**Issue by bhack** [BVLC/caffe#898]
I want to collect here missing component, PR and feedbacks to replicate the design of the [new state of the art](http://arxiv.org/abs/1406.5726) in Pascal VOC.

https://github.com/BVLC/caffe/pull/523
https://github.com/BVLC/caffe/pull/601

**Comment by bitwangdan** [comment]
@wuqiangch  Hi: have you implement this paper "CNN: Single-label to Multi-label"?

**Comment by wuqiangch** [comment]
No。


发自网易邮箱大师
On 12/01/2016 21:00, wangdan wrote:

@wuqiangch Hi: have you implement this paper "CNN: Single-label to Multi-label"?
