### ISSUE TITLE
Python Web Demo Example Broken in Latest Release

### ISSUE THREAD

**Issue by mgh1** [BVLC/caffe#899]
The web demo has the following defects:
1. The parameter mean_file should be mean in the classifier initialization in app.py
2. The mean is treated as a string when it should be an array in pycaffe.py (should add mean = np.load(mean) above the line if mode == 'elementwise':
3. Even after making the code run, the actual result doesn't work, that is, no matter the query image, the result is classified as a "window screen."  (I believe the problem lies in the python/caffe code)

**Comment by qgicup** [comment]
I still have this issue, using the latest master
