### ISSUE TITLE
Problem with the MNIST example script train_lenet_consolidated.sh

### ISSUE THREAD

**Issue by dgromero** [BVLC/caffe#922]
When I run the consolidated training script there seems to be a problem with accessing the leveldb. See below for the log:

I0813 15:58:42.894651 2067604240 net.cpp:55] Memory required for data: 0
I0813 15:58:42.894733 2067604240 net.cpp:66] Creating Layer mnist
I0813 15:58:42.894764 2067604240 net.cpp:290] mnist -> data
I0813 15:58:42.894812 2067604240 net.cpp:290] mnist -> label
I0813 15:58:42.894852 2067604240 data_layer.cpp:179] Opening leveldb /Users/dgromero/Documents/software/caffe-master/examples/mnist/mnist-train-leveldb
F0813 15:58:42.895278 2067604240 data_layer.cpp:182] Check failed: status.ok() Failed to open leveldb /Users/dgromero/Documents/software/caffe-master/examples/mnist/mnist-train-leveldb
IO error: lock /Users/dgromero/Documents/software/caffe-master/examples/mnist/mnist-train-leveldb/LOCK: already held by process
**\* Check failure stack trace: ***
    @        0x104d8bc7a  google::LogMessage::Fail()
    @        0x104d8aed8  google::LogMessage::SendToLog()
    @        0x104d8b92a  google::LogMessage::Flush()
    @        0x104d8f2e8  google::LogMessageFatal::~LogMessageFatal()
    @        0x104d8c115  google::LogMessageFatal::~LogMessageFatal()
    @        0x104a64569  caffe::DataLayer<>::SetUp()
    @        0x104abeaee  caffe::Net<>::Init()
    @        0x104abd532  caffe::Net<>::Net()
    @        0x104abce4d  caffe::Net<>::Net()
    @        0x104aecc3d  caffe::Solver<>::InitTestNets()
    @        0x104aeb0fd  caffe::Solver<>::Init()
    @        0x104aeae28  caffe::Solver<>::Solver()
    @        0x104af2eed  caffe::SGDSolver<>::SGDSolver()
    @        0x104af2ebd  caffe::SGDSolver<>::SGDSolver()
    @        0x1049c478c  train()
    @        0x1049c6572  main
    @     0x7fff8f5e25fd  start
    @                0x3  (unknown)

**Comment by sammoes** [comment]
This same issue still exists for HDF5, at least the same error.
