### ISSUE TITLE
error libcudart.so.6.0: in imagenet

### ISSUE THREAD

**Issue by ankitsinghalIITD** [BVLC/caffe#926]
Hi, i was trying to run imagenet example. When i executed ./create_imagenet.sh from ./create_imagenet.sh, following error appears

ankit@ankit-lab:~/deep_learning/caffe-master/examples/imagenet$ ./create_imagenet.sh
Creating leveldb...
../../build/tools/convert_imageset.bin: error while loading shared libraries: libcudart.so.6.0: cannot open shared object file: No such file or directory
../../build/tools/convert_imageset.bin: error while loading shared libraries: libcudart.so.6.0: cannot open shared object file: No such file or directory
Done.

contents of  create_imagenet.sh are :
# !/usr/bin/env sh
# Create the imagenet leveldb inputs
# N.B. set the path to the imagenet train + val data dirs

TOOLS=../../build/tools
DATA=../../data/ilsvrc12

echo "Creating leveldb..."

GLOG_logtostderr=1 $TOOLS/convert_imageset.bin \
    /path/to/imagenet/train/ \
    $DATA/train.txt \
    imagenet_train_leveldb 1

GLOG_logtostderr=1 $TOOLS/convert_imageset.bin \
    /path/to/imagenet/val/ \
    $DATA/val.txt \
    imagenet_val_leveldb 1

echo "Done."

please help

**Comment by azrael417** [comment]
I have a similar issue and CUDA is inside my library path. I suspect that the Makefile is broken: I point the Makefile to /user/local/cuda-7.0/lib64 and it links it partially correctly, partially not: when I do ldd convert_imageset I get;

...
...
libcudart.so.7.0 => not found
	libcublas.so.7.0 => not found
	libcurand.so.7.0 => not found
...
libcudart.so.7.0 => not found
...
libcudart.so.7.0 => /usr/local/cuda-7.0/lib64/libcudart.so.7.0 (0x00007f2b2fe58000)

so it links against cudart multiple times and sometimes it finds it, sometimes it doesn't. I think that this is actually a bug.
