### ISSUE TITLE
Multiple cropped inputs 

### ISSUE THREAD

**Issue by Robert0812** [BVLC/caffe#927]
I am doing a finetuning task using the window_data_layer as input. How do you suggest to add  some sub-windows of an image, and warp to the same size as the image's extra channels? I know the concat_layer can merge two bottom blobs, but I don't think it is suitable for this goal.

**Comment by lulu2017** [comment]
Hello, @Robert0812 ! I'm working on CNN recently, but do not know how to use concat_layer.cpp, can you help me to tell how to modify the net.prototxt? Thanks very much.
