### ISSUE TITLE
Using Caffe for RGB-D dataset with depth map output

### ISSUE THREAD

**Issue by ghost** [BVLC/caffe#955]
Hello.
I have a dataset composed of images (3 x 256 x 256) and corresponding depth maps (256 x 256).
Would it be possible use Caffe for training this dataset (input as images and output as depth maps)?
I found that Caffe can deal with multi label data (#523), but this multi-label can deal with only 3 multiple labels.
I appreicate your help!

**Comment by demondan** [comment]
hello,how to deal with this question ? can you tell me?

**Comment by dk683** [comment]
Hello @demondan. This was my previous project. Unfortunately I could not figure out this. I am sorry!

**Comment by shelhamer** [comment]
See #1698 for how to prepare data for matrix (like an image) prediction and ground truth.
