### ISSUE TITLE
N-d tiling (aka repmat)

### ISSUE THREAD

**Issue by petergehler** [BVLC/caffe#966]
I am looking for a N-d tiling operation (aka repmat in matlab) and did not find one in the current dev branch. The concat layer does provide some of its functionality already. Is there an easy way to stich it together with current layers already, otherwise I would create a new one based on the concat implementation. Any hints?

**Comment by shelhamer** [comment]
Satisfied by #2083.

**Comment by haihaoshen** [comment]
Hi, would you take a look TileLayer Usage #4422?
