### ISSUE TITLE
“YOU HAVA 2 DISABLED TESTS”

### ISSUE THREAD

**Issue by lixin7895123** [BVLC/caffe#982]
I was installing caffe in ubuntu 12.04, with K20. And the result of "make runtest" tells me "YOU HAVE 2 DISABLED TESTS".
 Is this a fatal error? Or does this result in potential risk?
If does, How can i solve this?

**Comment by ducminhnguyen** [comment]
+1

**Comment by RyanCarey** [comment]
+1

**Comment by jsChenxinpeng** [comment]
thanks, I was thought it was my problem. ^_^
