### ISSUE TITLE
Build issue on Fedora (dev branch)

### ISSUE THREAD

**Issue by ozancaglayan** [BVLC/caffe#996]
Hi,

I just tested to build the dev branch using CMake on Fedora 19 x86_64. The problem is that the FindAtlas.cmake module tries to locate the lapack library but on Fedora there isn't a library shipped within atlas with those names:
`find_library(Atlas_LAPACK_LIBRARY NAMES alapack_r alapack lapack_atlas PATHS ${Atlas_LIB_SEARCH_PATHS})`

The interesting thing is that the old Makefile (line 262) based stuff wasn't trying to link against lapack, it was just linking against `cblas` and `atlas`.

If i comment the lines in the FindAtlas.cmake related to `Atlas_LAPACK_LIBRARY` the build succeeds without a problem.

**Comment by codewiz** [comment]
I'm seeing a similar problem with Fedora 22 x86_64:

CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:138 (message):
  Could NOT find Atlas (missing: Atlas_CBLAS_LIBRARY Atlas_BLAS_LIBRARY
  Atlas_LAPACK_LIBRARY)
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:374 (_FPHSA_FAILURE_MESSAGE)
  cmake/Modules/FindAtlas.cmake:44 (find_package_handle_standard_args)
  cmake/Dependencies.cmake:74 (find_package)
  CMakeLists.txt:28 (include)


Package atlas-devel is installed and these files are present:
  /usr/include/cblas.h
  /usr/include/clapack.h

Should I file a new bug?
